# Module 5: reproducibility, SOTA, explainability, and ablations

This notebook uses `core.module05_fusion_classifier` and retains the SOTA audit/benchmark/comparison flow from [01_train_val_test_batch_runner.ipynb](./01_train_val_test_batch_runner.ipynb).

The architecture matrix uses the nine existing Module 5 experiments, `center` pooling, NTv1 DNA length 1001, ESM2 protein length 501, all 28 requested tabular features (11 AF/conservation + 9 SpliceAI + 8 k=64 geometry), three separate training splits (`train1`, `train2`, `train3`), and the four test datasets. The modality matrix additionally tests all 3 DNA families × 4 protein families at DNA=1001/protein=501. A checkpoint is fitted once per train/validation configuration and reused for its four test datasets.

**Prerequisites observed in this workspace:** `fm_embeddings/sequence_ablation` currently has the requested 1001/501 embeddings for train3/val/test, but not train1/train2. The legacy train1/train2 embeddings are 601/101 and must not be substituted. `geometry_v2_k64` currently has only the `train3` normalization context. Generate the missing model-length embeddings and k=64 geometry for train1/train2 before enabling full-suite stages. The preflight below fails explicitly if any required artifact is missing.

Set the stage flags in the final cell deliberately; these matrices can take substantial compute. The sequence-length stage tests the full Cartesian product of four DNA lengths and five protein lengths (20 pairs), including the 1001/501 reference, which is reused from the architecture stage. NTv1 length 10001 is excluded because the existing tokenizer support manifest marks it unsupported.

In [1]:
from datetime import datetime
from pathlib import Path
import json
import os
import sys

import pandas as pd
import torch
from IPython.display import display

_cwd = Path.cwd().resolve()
REPO_ROOT = next(
    (candidate for candidate in (_cwd, *_cwd.parents)
     if (candidate / "controllers").is_dir() and (candidate / "experiments").is_dir()),
    None,
)
if REPO_ROOT is None:
    raise RuntimeError(f"Could not locate repository root from {_cwd}")
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from core.module05_fusion_classifier.dataset import (
    BIO_CORE_COLUMNS,
    SPLICEAI_COLUMNS,
)
from core.module05_fusion_classifier.pipeline import FusionBatchPipeline
from core.module05_fusion_classifier.sota_benchmark import (
    evaluate_sota_from_test_files,
    SOTA_MODEL_COLUMNS_FULL,
    SOTA_REQUIRED_COLUMNS,
)
from core.module05_fusion_classifier import pipeline as pipeline_module

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BASE_DIR = r"D:\variant_data"
EMBEDDING_DIR = os.path.join(BASE_DIR, "fm_embeddings", "sequence_ablation")
FM_PROFILE_JSON = os.path.join(BASE_DIR, "profiling", "fm_profiling_sequence_ablation.json")
GEOMETRY_K = 64
GEOMETRY_DIR = os.path.join(BASE_DIR, f"geometry_v2_k{GEOMETRY_K}", "{context}")
GEOM_FEATURE_NAMES = [
    f"{modality}_{feature}"
    for modality in ("dna", "prot")
    for feature in ("LID", "LVD_L2", "LVD_Relative", "LVD_Cosine")
]
POOLINGS = ["center", "cls", "mean"]
DNA_LENGTHS = [301, 601, 1001, 2001]
PROTEIN_LENGTHS = [31, 101, 201, 501, 1001]
DNA_MODEL = "nt_v1_500m_dna_1001"
PROTEIN_MODEL = "esm2_650m_prot_501"
REFERENCE_POOLING = "center"

MODELS_SPACE = [
    {"name": f"nt_v1_500m_dna_{length}", "seq_type": "dna", "sequence_length": length}
    for length in DNA_LENGTHS
] + [
    {"name": f"esm2_650m_prot_{length}", "seq_type": "protein", "sequence_length": length}
    for length in PROTEIN_LENGTHS
] + [
    {"name": f"{family}_dna_1001", "seq_type": "dna", "sequence_length": 1001}
    for family in ("nt_v3_650m", "nt_v2_500m")
] + [
    {"name": f"{family}_prot_501", "seq_type": "protein", "sequence_length": 501}
    for family in ("esm1b_650m", "esm1v_650m", "esmc_600m")
]
PAIR_DNA_MODELS = [
    "nt_v1_500m_dna_1001",
    "nt_v3_650m_dna_1001",
    "nt_v2_500m_dna_1001",
]
PAIR_PROTEIN_MODELS = [
    "esm1b_650m_prot_501",
    "esm1v_650m_prot_501",
    "esm2_650m_prot_501",
    "esmc_600m_prot_501",
]
EXPERIMENTS = [
    {"name": "PyTorch_Concat", "type": "pytorch", "fusion": "concat"},
    {"name": "PyTorch_CrossAttn", "type": "pytorch", "fusion": "cross_attention"},
    {"name": "PyTorch_Transformer", "type": "pytorch", "fusion": "transformer"},
    {"name": "PyTorch_Gating", "type": "pytorch", "fusion": "gating"},
    {"name": "Pure_XGBoost_Concat", "type": "xgboost_pure", "fusion": "concat"},
    {"name": "Hybrid_Concat_XGBoost", "type": "hybrid", "fusion": "concat"},
    {"name": "Hybrid_CrossAttn_XGBoost", "type": "hybrid", "fusion": "cross_attention"},
    {"name": "Hybrid_Transformer_XGBoost", "type": "hybrid", "fusion": "transformer"},
    {"name": "Hybrid_Gating_XGBoost", "type": "hybrid", "fusion": "gating"},
]
TEST_SPLITS = {
    "test": "Test",
    "clinvarhq": "ClinVarHQ",
    "uniprot": "UniProt",
    "proteingym": "ProteinGym",
}
TRAIN_SPLITS = ["train1", "train2", "train3"]
DATASETS = [
    {
        "name": f"{train.title()}Val_{test_label}",
        "train": train,
        "val": "val",
        "test": test_split,
    }
    for train in TRAIN_SPLITS
    for test_split, test_label in TEST_SPLITS.items()
]
CONFIG = {
    "batch_size": 256,
    "epochs": 30,
    "lr": 1e-4,
    "weight_decay": 1e-3,
    "lr_factor": 0.5,
    "lr_patience": 3,
    "early_stop_patience": 6,
    "num_workers": 0,
    "seed": 2,
    "xgb_n_jobs": 1,
}
EXPLAINABILITY = {
    "enable_shap": True,
    "enable_lime": True,
    "max_background_samples": 512,
    "max_explain_samples": 200,
    "lime_num_features": 20,
    "max_lime_samples": 20,
    "lime_num_samples": 2000,
    "shap_top_k": 30,
    "random_state": 2,
}

RESUME_EXISTING_RUN = False
RESUME_BATCH_RUN_DIR = None
if RESUME_EXISTING_RUN:
    if RESUME_BATCH_RUN_DIR is None:
        raise ValueError("Set RESUME_BATCH_RUN_DIR when RESUME_EXISTING_RUN=True")
    RUN_OUTPUT_DIR = Path(RESUME_BATCH_RUN_DIR).resolve()
else:
    _stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    RUN_OUTPUT_DIR = REPO_ROOT / "experiments" / f"reproduction_ablations_{_stamp}"
    _suffix = 2
    while RUN_OUTPUT_DIR.exists():
        RUN_OUTPUT_DIR = REPO_ROOT / "experiments" / f"reproduction_ablations_{_stamp}_{_suffix:02d}"
        _suffix += 1

pipeline = FusionBatchPipeline(
    base_dir=BASE_DIR,
    config=CONFIG,
    datasets=DATASETS,
    models_space=MODELS_SPACE,
    pooling_strategies=POOLINGS,
    experiments=EXPERIMENTS,
    explainability=EXPLAINABILITY,
    fm_profile_json=FM_PROFILE_JSON,
    geometry_dir=GEOMETRY_DIR,
    geom_feature_names=GEOM_FEATURE_NAMES,
    batch_run_dir=str(RUN_OUTPUT_DIR),
    embedding_dir=EMBEDDING_DIR,
)
print(f"[*] Device: {DEVICE} | batch: {pipeline.batch_run_dir}")
print(f"[*] Datasets: {len(DATASETS)} train/test combinations | models: {len(MODELS_SPACE)}")

c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[*] Device: cuda | batch: D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011
[*] Datasets: 12 train/test combinations | models: 14

## SOTA benchmark and artifact preflight

The SOTA definitions, strict required-column audit, thresholds, label candidates, and four source files mirror Notebook 01. This cell can be run before training; it writes the SOTA metrics, mapping, and audit CSVs into the current batch directory.

In [2]:
SOTA_TEST_FILES = {
    "test": os.path.join(BASE_DIR, "test_full_seq_after_vep_final.parquet"),
    "clinvarhq": os.path.join(BASE_DIR, "clinvarhq_full_seq_after_vep_final.parquet"),
    "uniprot": os.path.join(BASE_DIR, "uniprot_full_seq_after_vep_final.parquet"),
    "proteingym": os.path.join(BASE_DIR, "proteingym_full_seq_after_vep_final.parquet"),
}
SOTA_LABEL_COL = None
SOTA_LABEL_CANDIDATES = ["Pathogenicity_Label", "Label"]
SOTA_THRESHOLD = 0.5
SOTA_ENFORCE_REQUIRED = True

sota_result = evaluate_sota_from_test_files(
    test_files=SOTA_TEST_FILES,
    output_dir=pipeline.batch_run_dir,
    label_col=SOTA_LABEL_COL,
    label_candidates=SOTA_LABEL_CANDIDATES,
    model_columns=SOTA_MODEL_COLUMNS_FULL,
    threshold=SOTA_THRESHOLD,
    required_columns=SOTA_REQUIRED_COLUMNS,
    enforce_required_columns=SOTA_ENFORCE_REQUIRED,
)
print(f"[SOTA] metrics={sota_result['metrics_path']} | rows={sota_result['num_rows']}")
print(f"[SOTA] mapping={sota_result['mapping_path']} | models={sota_result['num_models']}")
if sota_result.get("audit") is not None:
    audit = sota_result["audit"]
    print(f"[SOTA] audit={audit['audit_path']} | missing={audit['missing_count']} | null={audit['null_issue_count']}")

BIO_FEATURE_GROUPS = {
    "allele_frequencies": ["AF", "gnomADe_AF"],
    "conservation_scores": [column for column in BIO_CORE_COLUMNS if column not in {"AF", "gnomADe_AF"}],
    "spliceai": list(SPLICEAI_COLUMNS),
    "geometry": list(GEOM_FEATURE_NAMES),
    "dna_geometry": [name for name in GEOM_FEATURE_NAMES if name.startswith("dna_")],
    "protein_geometry": [name for name in GEOM_FEATURE_NAMES if name.startswith("prot_")],
}
BIO_FEATURES = [*BIO_CORE_COLUMNS, *SPLICEAI_COLUMNS]
ALL_TABULAR_FEATURES = [*BIO_FEATURES, *GEOM_FEATURE_NAMES]
if len(ALL_TABULAR_FEATURES) != 28 or len(set(ALL_TABULAR_FEATURES)) != 28:
    raise RuntimeError(f"Expected 28 unique AF/conservation/SpliceAI/geometry features, got {len(ALL_TABULAR_FEATURES)}")

def full_feature_config(label="bio_core_dna_prot_spliceai_geom", **overrides):
    config = {
        "label": label,
        "active_modalities": ["dna", "prot", "bio_core", "spliceai", "geom"],
        "dna_model_name": DNA_MODEL,
        "prot_model_name": PROTEIN_MODEL,
        "geom_feature_names": list(GEOM_FEATURE_NAMES),
        "bio_feature_names": list(BIO_FEATURES),
        "poolings": [REFERENCE_POOLING],
        "experiment_names": [experiment["name"] for experiment in EXPERIMENTS],
    }
    config.update(overrides)
    return config

def preflight_configs(configs):
    missing = set()
    if not os.path.exists(FM_PROFILE_JSON):
        missing.add(f"Missing foundation-model profiling JSON: {FM_PROFILE_JSON}")
        fm_profile = {}
    else:
        with open(FM_PROFILE_JSON, "r", encoding="utf-8") as handle:
            fm_profile = json.load(handle)
    missing_profile = set()
    for config in configs:
        modalities = {str(mod).lower() for mod in config["active_modalities"]}
        dna_name = config.get("dna_model_name")
        prot_name = config.get("prot_model_name")
        for modality, model_name in (("dna", dna_name), ("prot", prot_name)):
            if model_name is None or modality not in modalities:
                continue
            for split in TEST_SPLITS:
                stats = fm_profile.get(model_name, {}).get(split, {})
                if float(stats.get("inference_time_ms", 0.0) or 0.0) <= 0:
                    missing_profile.add(f"{model_name}:{split}")
        for dataset in DATASETS:
            context = dataset["train"]
            for split in (dataset["train"], dataset["val"], dataset["test"]):
                try:
                    pipeline_module._resolve_bio_path(pipeline.bio_dir, split)
                except FileNotFoundError as exc:
                    missing.add(str(exc))
                for pooling in config.get("poolings", [REFERENCE_POOLING]):
                    for modality, model_name in (("dna", dna_name), ("prot", prot_name)):
                        if model_name is None:
                            continue
                        if modality in modalities:
                            try:
                                pipeline_module._resolve_pt_path(pipeline.embed_dir, split, model_name, pooling)
                            except FileNotFoundError as exc:
                                missing.add(str(exc))
                        if "geom" in modalities and any(name.startswith(f"{modality}_") for name in config["geom_feature_names"]):
                            try:
                                geometry_root = GEOMETRY_DIR.format(context=context)
                                pipeline_module._resolve_geom_path(geometry_root, split, model_name, pooling)
                            except FileNotFoundError as exc:
                                missing.add(str(exc))
    if missing_profile:
        missing.add("Missing FM inference profiling records: " + ", ".join(sorted(missing_profile)))
    if missing:
        examples = "\n".join(sorted(missing)[:30])
        raise FileNotFoundError(
            f"Preflight found {len(missing)} missing input artifacts. Prepare the required embeddings/geometry before running this stage.\n{examples}"
        )
    print(f"[PREFLIGHT PASS] {len(configs)} configurations across {len(DATASETS)} train/test combinations.")

print(f"[*] Feature groups: { {name: len(columns) for name, columns in BIO_FEATURE_GROUPS.items()} }")
print(f"[*] Total tabular features: {len(ALL_TABULAR_FEATURES)}")

[SOTA] metrics=D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011/sota_metrics.csv | rows=112
[SOTA] mapping=D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011/sota_column_mapping.csv | models=28
[SOTA] audit=D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011/sota_required_columns_audit.csv | missing=0 | null=0
[*] Feature groups: {'allele_frequencies': 2, 'conservation_scores': 9, 'spliceai': 9, 'geometry': 8, 'dna_geometry': 4, 'protein_geometry': 4}
[*] Total tabular features: 28

## Study matrix

The feature-group and individual-feature studies are leave-one-group/feature-out from the 28-feature reference. Sequence length varies one modality at a time while the other stays at 1001/501. Pooling, sequence, modality, and feature-ablation stages use pure XGBoost unless edited.

In [3]:
XGB_ONLY = ["Pure_XGBoost_Concat"]

def build_architecture_configs():
    return [full_feature_config()]

def build_explainability_configs():
    return [full_feature_config(
        label="bio_core_dna_prot_spliceai_geom_shap_lime",
        run_explainability=True,
        experiment_names=XGB_ONLY,
    )]

def build_group_ablation_configs():
    configs = []
    for group_name, removed in BIO_FEATURE_GROUPS.items():
        bio_features = [name for name in BIO_FEATURES if name not in removed]
        geom_features = [name for name in GEOM_FEATURE_NAMES if name not in removed]
        active = ["dna", "prot", "bio_core", "spliceai", "geom"]
        if not any(name in bio_features for name in BIO_CORE_COLUMNS):
            active.remove("bio_core")
        if not any(name in bio_features for name in SPLICEAI_COLUMNS):
            active.remove("spliceai")
        if not geom_features:
            active.remove("geom")
        configs.append(full_feature_config(
            label=f"bio_drop_group_{group_name}",
            active_modalities=active,
            bio_feature_names=bio_features or None,
            geom_feature_names=geom_features or None,
            experiment_names=XGB_ONLY,
        ))
    return configs

def build_single_feature_ablation_configs():
    configs = []
    for removed in ALL_TABULAR_FEATURES:
        bio_features = [name for name in BIO_FEATURES if name != removed]
        geom_features = [name for name in GEOM_FEATURE_NAMES if name != removed]
        configs.append(full_feature_config(
            label=f"bio_drop_feature_{removed}",
            bio_feature_names=bio_features,
            geom_feature_names=geom_features,
            experiment_names=XGB_ONLY,
        ))
    return configs

def build_pooling_configs():
    config = full_feature_config(experiment_names=XGB_ONLY)
    config["poolings"] = list(POOLINGS)
    return [config]

def build_sequence_length_configs():
    configs = []
    for dna_length in DNA_LENGTHS:
        for protein_length in PROTEIN_LENGTHS:
            is_reference = dna_length == 1001 and protein_length == 501
            label = (
                "bio_core_dna_prot_spliceai_geom"
                if is_reference
                else f"sequence_pair_dna_{dna_length}_protein_{protein_length}"
            )
            configs.append(full_feature_config(
                label=label,
                dna_model_name=f"nt_v1_500m_dna_{dna_length}",
                prot_model_name=f"esm2_650m_prot_{protein_length}",
                experiment_names=XGB_ONLY,
            ))
    return configs

def build_modality_configs():
    configs = [
        full_feature_config(label="bio_core_dna_prot_spliceai_geom", experiment_names=XGB_ONLY),
        full_feature_config(
            label="modalities_dna_only_bio_splice_geom",
            active_modalities=["dna", "bio_core", "spliceai", "geom"],
            experiment_names=XGB_ONLY,
        ),
        full_feature_config(
            label="modalities_protein_only_bio_splice_geom",
            active_modalities=["prot", "bio_core", "spliceai", "geom"],
            experiment_names=XGB_ONLY,
        ),
        full_feature_config(
            label="modalities_bio_splice_geom_only",
            active_modalities=["bio_core", "spliceai", "geom"],
            experiment_names=XGB_ONLY,
        ),
        full_feature_config(
            label="modalities_dna_only",
            active_modalities=["dna"],
            bio_feature_names=None,
            geom_feature_names=None,
            experiment_names=XGB_ONLY,
        ),
        full_feature_config(
            label="modalities_protein_only",
            active_modalities=["prot"],
            bio_feature_names=None,
            geom_feature_names=None,
            experiment_names=XGB_ONLY,
        ),
        full_feature_config(
            label="modalities_dna_protein_only",
            active_modalities=["dna", "prot"],
            bio_feature_names=None,
            geom_feature_names=None,
            experiment_names=XGB_ONLY,
        ),
        full_feature_config(
            label="modalities_bio_only",
            active_modalities=["bio_core"],
            dna_model_name=None,
            prot_model_name=None,
            bio_feature_names=list(BIO_CORE_COLUMNS),
            geom_feature_names=None,
            experiment_names=XGB_ONLY,
        ),
        full_feature_config(
            label="modalities_spliceai_only",
            active_modalities=["spliceai"],
            dna_model_name=None,
            prot_model_name=None,
            bio_feature_names=list(SPLICEAI_COLUMNS),
            geom_feature_names=None,
            experiment_names=XGB_ONLY,
        ),
        full_feature_config(
            label="modalities_geometry_only",
            active_modalities=["geom"],
            bio_feature_names=None,
            experiment_names=XGB_ONLY,
        ),
    ]
    for dna_name in PAIR_DNA_MODELS:
        for prot_name in PAIR_PROTEIN_MODELS:
            if dna_name == DNA_MODEL and prot_name == PROTEIN_MODEL:
                continue
            dna_family = dna_name.removesuffix("_dna_1001")
            protein_family = prot_name.removesuffix("_prot_501")
            configs.append(full_feature_config(
                label=f"model_pair_{dna_family}_{protein_family}_bio_splice_geom",
                dna_model_name=dna_name,
                prot_model_name=prot_name,
                experiment_names=XGB_ONLY,
            ))
    return configs

def run_configs(configs, resume=True):
    preflight_configs(configs)
    return pipeline.run_config_matrix(configs, resume=resume)

## Run selected stages

Enable only the stages to run in this session. Architecture comparison includes all nine existing fusion/classifier architectures. Set `RUN_EXPLAINABILITY` separately to fit the pure-XGBoost reference with both SHAP and LIME enabled.

In [4]:
RUN_ARCHITECTURE = True
RUN_EXPLAINABILITY = True
RUN_BIOLOGICAL_GROUP_ABLATION = True
RUN_28_FEATURE_ABLATION = True
RUN_POOLING_ABLATION = True
RUN_SEQUENCE_LENGTH_ABLATION = True
RUN_DNA_PROTEIN_ABLATION = True
RESUME = True

STAGES = [
    (RUN_ARCHITECTURE, "9-architecture comparison", build_architecture_configs),
    (RUN_EXPLAINABILITY, "SHAP + LIME", build_explainability_configs),
    (RUN_BIOLOGICAL_GROUP_ABLATION, "biological feature-group ablation", build_group_ablation_configs),
    (RUN_28_FEATURE_ABLATION, "28 individual-feature ablation", build_single_feature_ablation_configs),
    (RUN_POOLING_ABLATION, "pooling ablation", build_pooling_configs),
    (RUN_SEQUENCE_LENGTH_ABLATION, "sequence-length ablation", build_sequence_length_configs),
    (RUN_DNA_PROTEIN_ABLATION, "DNA/protein modality ablation", build_modality_configs),
]
selected_stages = [(name, builder()) for enabled, name, builder in STAGES if enabled]
if not selected_stages:
    print("[SKIP] No training stage enabled. Set one or more RUN_* flags to True.")
else:
    for stage_name, configs in selected_stages:
        print(f"\n{'=' * 80}\n[STAGE] {stage_name} | configs={len(configs)}\n{'=' * 80}")
        result = run_configs(configs, resume=RESUME)
        print(f"[DONE] {stage_name} | metrics={result['metrics_path']} | metric_rows={result['num_rows_metrics']} | fit_profile={result['fit_profiling_path']} | fit_rows={result['num_rows_fit_profiling']}")

print(f"[OUTPUT] {pipeline.batch_run_dir}")

================================================================================
[STAGE] 9-architecture comparison | configs=1
================================================================================
[PREFLIGHT PASS] 1 configurations across 12 train/test combinations.

[CONFIG MATRIX] bio_core_dna_prot_spliceai_geom | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=9
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test

[Epoch 01] train_loss=0.2118 | val_loss=0.1556 | val_mcc=0.8082 | val_f1=0.8399 | val_auroc=0.9758

[Epoch 02] train_loss=0.1615 | val_loss=0.1509 | val_mcc=0.8168 | val_f1=0.8498 | val_auroc=0.9761

[Epoch 03] train_loss=0.1422 | val_loss=0.1532 | val_mcc=0.8153 | val_f1=0.8480 | val_auroc=0.9769

[Epoch 04] train_loss=0.1234 | val_loss=0.1579 | val_mcc=0.8170 | val_f1=0.8494 | val_auroc=0.9762

[Epoch 05] train_loss=0.1035 | val_loss=0.1787 | val_mcc=0.8078 | val_f1=0.8402 | val_auroc=0.9743

[Epoch 06] train_loss=0.0839 | val_loss=0.1901 | val_mcc=0.8057 | val_f1=0.8394 | val_auroc=0.9726

[Epoch 07] train_loss=0.0675 | val_loss=0.2066 | val_mcc=0.8055 | val_f1=0.8396 | val_auroc=0.9709

[Epoch 08] train_loss=0.0532 | val_loss=0.2280 | val_mcc=0.7959 | val_f1=0.8302 | val_auroc=0.9684

[Epoch 09] train_loss=0.0331 | val_loss=0.2398 | val_mcc=0.8008 | val_f1=0.8345 | val_auroc=0.9689

[Epoch 10] train_loss=0.0259 | val_loss=0.2621 | val_mcc=0.7982 | val_f1=0.8328 | val_auroc=0.9668
[EarlyStop] epoch=10 | best_val_mcc=0.8170
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8185 | F1=0.8668 | AUROC=0.9720 | AUPRC=0.9398
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test

[Epoch 01] train_loss=0.2120 | val_loss=0.1589 | val_mcc=0.8023 | val_f1=0.8330 | val_auroc=0.9759

[Epoch 02] train_loss=0.1688 | val_loss=0.1584 | val_mcc=0.7953 | val_f1=0.8266 | val_auroc=0.9771

[Epoch 03] train_loss=0.1535 | val_loss=0.1596 | val_mcc=0.8035 | val_f1=0.8339 | val_auroc=0.9778

[Epoch 04] train_loss=0.1402 | val_loss=0.1514 | val_mcc=0.8178 | val_f1=0.8499 | val_auroc=0.9773

[Epoch 05] train_loss=0.1217 | val_loss=0.1657 | val_mcc=0.8125 | val_f1=0.8462 | val_auroc=0.9741

[Epoch 06] train_loss=0.1025 | val_loss=0.1837 | val_mcc=0.8018 | val_f1=0.8344 | val_auroc=0.9715

[Epoch 07] train_loss=0.0834 | val_loss=0.2026 | val_mcc=0.7937 | val_f1=0.8308 | val_auroc=0.9680

[Epoch 08] train_loss=0.0667 | val_loss=0.2175 | val_mcc=0.8031 | val_f1=0.8382 | val_auroc=0.9706

[Epoch 09] train_loss=0.0405 | val_loss=0.2536 | val_mcc=0.8001 | val_f1=0.8346 | val_auroc=0.9674

[Epoch 10] train_loss=0.0321 | val_loss=0.2718 | val_mcc=0.8066 | val_f1=0.8410 | val_auroc=0.9687
[EarlyStop] epoch=10 | best_val_mcc=0.8178
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8284 | F1=0.8740 | AUROC=0.9747 | AUPRC=0.9430
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test

[Epoch 01] train_loss=0.2111 | val_loss=0.1495 | val_mcc=0.8122 | val_f1=0.8456 | val_auroc=0.9757

[Epoch 02] train_loss=0.1658 | val_loss=0.1594 | val_mcc=0.8042 | val_f1=0.8349 | val_auroc=0.9759

[Epoch 03] train_loss=0.1488 | val_loss=0.1550 | val_mcc=0.8128 | val_f1=0.8452 | val_auroc=0.9756

[Epoch 04] train_loss=0.1310 | val_loss=0.1583 | val_mcc=0.8138 | val_f1=0.8462 | val_auroc=0.9755

[Epoch 05] train_loss=0.1103 | val_loss=0.1706 | val_mcc=0.8105 | val_f1=0.8446 | val_auroc=0.9741

[Epoch 06] train_loss=0.0903 | val_loss=0.1966 | val_mcc=0.7982 | val_f1=0.8328 | val_auroc=0.9694

[Epoch 07] train_loss=0.0695 | val_loss=0.2279 | val_mcc=0.7963 | val_f1=0.8302 | val_auroc=0.9676

[Epoch 08] train_loss=0.0557 | val_loss=0.2399 | val_mcc=0.7978 | val_f1=0.8338 | val_auroc=0.9676

[Epoch 09] train_loss=0.0332 | val_loss=0.2711 | val_mcc=0.8042 | val_f1=0.8376 | val_auroc=0.9667

[Epoch 10] train_loss=0.0249 | val_loss=0.3044 | val_mcc=0.7993 | val_f1=0.8341 | val_auroc=0.9662
[EarlyStop] epoch=10 | best_val_mcc=0.8138
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8178 | F1=0.8657 | AUROC=0.9704 | AUPRC=0.9375
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test

[Epoch 01] train_loss=0.2141 | val_loss=0.1560 | val_mcc=0.8037 | val_f1=0.8367 | val_auroc=0.9747

[Epoch 02] train_loss=0.1600 | val_loss=0.1533 | val_mcc=0.8084 | val_f1=0.8400 | val_auroc=0.9771

[Epoch 03] train_loss=0.1389 | val_loss=0.1613 | val_mcc=0.8085 | val_f1=0.8406 | val_auroc=0.9762

[Epoch 04] train_loss=0.1151 | val_loss=0.1736 | val_mcc=0.8045 | val_f1=0.8371 | val_auroc=0.9744

[Epoch 05] train_loss=0.0907 | val_loss=0.1904 | val_mcc=0.7970 | val_f1=0.8308 | val_auroc=0.9719

[Epoch 06] train_loss=0.0693 | val_loss=0.2102 | val_mcc=0.8003 | val_f1=0.8350 | val_auroc=0.9703

[Epoch 07] train_loss=0.0535 | val_loss=0.2361 | val_mcc=0.7834 | val_f1=0.8186 | val_auroc=0.9688

[Epoch 08] train_loss=0.0326 | val_loss=0.2539 | val_mcc=0.7947 | val_f1=0.8289 | val_auroc=0.9668

[Epoch 09] train_loss=0.0229 | val_loss=0.2758 | val_mcc=0.7949 | val_f1=0.8290 | val_auroc=0.9662
[EarlyStop] epoch=9 | best_val_mcc=0.8085
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8293 | F1=0.8752 | AUROC=0.9718 | AUPRC=0.9388
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 296.
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8320 | F1=0.8760 | AUROC=0.9758 | AUPRC=0.9427
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 255.
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8245 | F1=0.8710 | AUROC=0.9746 | AUPRC=0.9444
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 131.
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8265 | F1=0.8719 | AUROC=0.9750 | AUPRC=0.9450
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 159.
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8267 | F1=0.8710 | AUROC=0.9756 | AUPRC=0.9457
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 165.
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8176 | F1=0.8654 | AUROC=0.9729 | AUPRC=0.9390
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8261 | F1=0.9072 | AUROC=0.9812 | AUPRC=0.9808
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8445 | F1=0.9154 | AUROC=0.9876 | AUPRC=0.9870
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8550 | F1=0.9219 | AUROC=0.9855 | AUPRC=0.9856
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8615 | F1=0.9278 | AUROC=0.9833 | AUPRC=0.9824
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8674 | F1=0.9275 | AUROC=0.9886 | AUPRC=0.9890
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8729 | F1=0.9337 | AUROC=0.9871 | AUPRC=0.9879
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8604 | F1=0.9251 | AUROC=0.9847 | AUPRC=0.9853
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8559 | F1=0.9215 | AUROC=0.9866 | AUPRC=0.9862
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8543 | F1=0.9224 | AUROC=0.9838 | AUPRC=0.9842
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4810 | F1=0.7426 | AUROC=0.8104 | AUPRC=0.7925
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4767 | F1=0.7413 | AUROC=0.8051 | AUPRC=0.7803
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4617 | F1=0.7339 | AUROC=0.8054 | AUPRC=0.7850
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4740 | F1=0.7417 | AUROC=0.8062 | AUPRC=0.7876
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4809 | F1=0.7402 | AUROC=0.8098 | AUPRC=0.7948
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4675 | F1=0.7349 | AUROC=0.8058 | AUPRC=0.7835
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4719 | F1=0.7357 | AUROC=0.8075 | AUPRC=0.7840
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4946 | F1=0.7422 | AUROC=0.8107 | AUPRC=0.7858
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4794 | F1=0.7381 | AUROC=0.8091 | AUPRC=0.7910
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6677 | F1=0.8270 | AUROC=0.9035 | AUPRC=0.8724
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6577 | F1=0.8224 | AUROC=0.9065 | AUPRC=0.8752
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6582 | F1=0.8225 | AUROC=0.9001 | AUPRC=0.8697
[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache

[Epoch 01] train_loss=0.2887 | val_loss=0.1554 | val_mcc=0.8036 | val_f1=0.8383 | val_auroc=0.9740

[Epoch 02] train_loss=0.2227 | val_loss=0.1534 | val_mcc=0.8059 | val_f1=0.8397 | val_auroc=0.9751

[Epoch 03] train_loss=0.1951 | val_loss=0.1608 | val_mcc=0.8001 | val_f1=0.8367 | val_auroc=0.9724

[Epoch 04] train_loss=0.1712 | val_loss=0.1635 | val_mcc=0.7985 | val_f1=0.8346 | val_auroc=0.9731

[Epoch 05] train_loss=0.1438 | val_loss=0.1771 | val_mcc=0.7954 | val_f1=0.8328 | val_auroc=0.9706

[Epoch 06] train_loss=0.1167 | val_loss=0.2025 | val_mcc=0.7753 | val_f1=0.8147 | val_auroc=0.9671

[Epoch 07] train_loss=0.0792 | val_loss=0.2101 | val_mcc=0.7872 | val_f1=0.8257 | val_auroc=0.9670

[Epoch 08] train_loss=0.0630 | val_loss=0.2294 | val_mcc=0.7792 | val_f1=0.8189 | val_auroc=0.9650
[EarlyStop] epoch=8 | best_val_mcc=0.8059
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8134 | F1=0.8650 | AUROC=0.9712 | AUPRC=0.9374
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test

[Epoch 01] train_loss=0.2950 | val_loss=0.1570 | val_mcc=0.8039 | val_f1=0.8397 | val_auroc=0.9736

[Epoch 02] train_loss=0.2322 | val_loss=0.1568 | val_mcc=0.8020 | val_f1=0.8369 | val_auroc=0.9736

[Epoch 03] train_loss=0.2113 | val_loss=0.1603 | val_mcc=0.8005 | val_f1=0.8357 | val_auroc=0.9719

[Epoch 04] train_loss=0.1921 | val_loss=0.1659 | val_mcc=0.7967 | val_f1=0.8300 | val_auroc=0.9730

[Epoch 05] train_loss=0.1682 | val_loss=0.1785 | val_mcc=0.7910 | val_f1=0.8274 | val_auroc=0.9708

[Epoch 06] train_loss=0.1282 | val_loss=0.1991 | val_mcc=0.7886 | val_f1=0.8272 | val_auroc=0.9663

[Epoch 07] train_loss=0.1070 | val_loss=0.2145 | val_mcc=0.7813 | val_f1=0.8207 | val_auroc=0.9643
[EarlyStop] epoch=7 | best_val_mcc=0.8039
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8036 | F1=0.8561 | AUROC=0.9713 | AUPRC=0.9348
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test

[Epoch 01] train_loss=0.2949 | val_loss=0.1612 | val_mcc=0.7914 | val_f1=0.8251 | val_auroc=0.9725

[Epoch 02] train_loss=0.2292 | val_loss=0.1568 | val_mcc=0.8055 | val_f1=0.8400 | val_auroc=0.9738

[Epoch 03] train_loss=0.2076 | val_loss=0.1614 | val_mcc=0.8002 | val_f1=0.8347 | val_auroc=0.9718

[Epoch 04] train_loss=0.1813 | val_loss=0.1628 | val_mcc=0.8036 | val_f1=0.8398 | val_auroc=0.9713

[Epoch 05] train_loss=0.1533 | val_loss=0.1721 | val_mcc=0.8006 | val_f1=0.8375 | val_auroc=0.9707

[Epoch 06] train_loss=0.1270 | val_loss=0.1926 | val_mcc=0.7949 | val_f1=0.8320 | val_auroc=0.9687

[Epoch 07] train_loss=0.0833 | val_loss=0.2209 | val_mcc=0.7817 | val_f1=0.8232 | val_auroc=0.9646

[Epoch 08] train_loss=0.0672 | val_loss=0.2384 | val_mcc=0.7860 | val_f1=0.8246 | val_auroc=0.9639
[EarlyStop] epoch=8 | best_val_mcc=0.8055
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8107 | F1=0.8595 | AUROC=0.9704 | AUPRC=0.9353
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test

[Epoch 01] train_loss=0.2910 | val_loss=0.1566 | val_mcc=0.8051 | val_f1=0.8402 | val_auroc=0.9732

[Epoch 02] train_loss=0.2196 | val_loss=0.1560 | val_mcc=0.8050 | val_f1=0.8405 | val_auroc=0.9741

[Epoch 03] train_loss=0.1935 | val_loss=0.1608 | val_mcc=0.8034 | val_f1=0.8386 | val_auroc=0.9734

[Epoch 04] train_loss=0.1634 | val_loss=0.1717 | val_mcc=0.8028 | val_f1=0.8377 | val_auroc=0.9707

[Epoch 05] train_loss=0.1274 | val_loss=0.1886 | val_mcc=0.7902 | val_f1=0.8274 | val_auroc=0.9679

[Epoch 06] train_loss=0.0875 | val_loss=0.2082 | val_mcc=0.7923 | val_f1=0.8299 | val_auroc=0.9668

[Epoch 07] train_loss=0.0655 | val_loss=0.2298 | val_mcc=0.7853 | val_f1=0.8250 | val_auroc=0.9653
[EarlyStop] epoch=7 | best_val_mcc=0.8051
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8131 | F1=0.8626 | AUROC=0.9705 | AUPRC=0.9366
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 312.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8298 | F1=0.8756 | AUROC=0.9744 | AUPRC=0.9424
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 253.
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8281 | F1=0.8742 | AUROC=0.9725 | AUPRC=0.9415
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 135.
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8277 | F1=0.8750 | AUROC=0.9709 | AUPRC=0.9395
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 188.
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8243 | F1=0.8711 | AUROC=0.9725 | AUPRC=0.9397
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 223.
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8180 | F1=0.8660 | AUROC=0.9712 | AUPRC=0.9368
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8607 | F1=0.9289 | AUROC=0.9811 | AUPRC=0.9793
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8529 | F1=0.9235 | AUROC=0.9815 | AUPRC=0.9799
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8341 | F1=0.9121 | AUROC=0.9798 | AUPRC=0.9784
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8588 | F1=0.9263 | AUROC=0.9843 | AUPRC=0.9845
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8670 | F1=0.9310 | AUROC=0.9879 | AUPRC=0.9882
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8843 | F1=0.9396 | AUROC=0.9841 | AUPRC=0.9838
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8893 | F1=0.9432 | AUROC=0.9840 | AUPRC=0.9851
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8732 | F1=0.9335 | AUROC=0.9859 | AUPRC=0.9854
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8563 | F1=0.9244 | AUROC=0.9835 | AUPRC=0.9822
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4663 | F1=0.7454 | AUROC=0.8025 | AUPRC=0.7840
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4766 | F1=0.7409 | AUROC=0.8077 | AUPRC=0.7909
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4884 | F1=0.7411 | AUROC=0.8097 | AUPRC=0.7902
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.5034 | F1=0.7521 | AUROC=0.8111 | AUPRC=0.7937
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4774 | F1=0.7451 | AUROC=0.8003 | AUPRC=0.7744
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.5022 | F1=0.7541 | AUROC=0.8075 | AUPRC=0.7899
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4989 | F1=0.7567 | AUROC=0.8075 | AUPRC=0.7887
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.5035 | F1=0.7528 | AUROC=0.8067 | AUPRC=0.7922
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4674 | F1=0.7341 | AUROC=0.8050 | AUPRC=0.7843
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6287 | F1=0.8090 | AUROC=0.9013 | AUPRC=0.8821
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6489 | F1=0.8176 | AUROC=0.9026 | AUPRC=0.8811
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6716 | F1=0.8266 | AUROC=0.9074 | AUPRC=0.8856
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6307 | F1=0.8083 | AUROC=0.8993 | AUPRC=0.8776
[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6447 | F1=0.8167 | AUROC=0.9102 | AUPRC=0.8825

[Epoch 01] train_loss=0.3547 | val_loss=0.2086 | val_mcc=0.7676 | val_f1=0.8129 | val_auroc=0.9630

[Epoch 02] train_loss=0.2322 | val_loss=0.1887 | val_mcc=0.7848 | val_f1=0.8267 | val_auroc=0.9705

[Epoch 03] train_loss=0.1931 | val_loss=0.1983 | val_mcc=0.7728 | val_f1=0.8169 | val_auroc=0.9693

[Epoch 04] train_loss=0.1590 | val_loss=0.2091 | val_mcc=0.7601 | val_f1=0.8068 | val_auroc=0.9658

[Epoch 05] train_loss=0.1267 | val_loss=0.2292 | val_mcc=0.7545 | val_f1=0.8020 | val_auroc=0.9648

[Epoch 06] train_loss=0.0934 | val_loss=0.2500 | val_mcc=0.7427 | val_f1=0.7928 | val_auroc=0.9627

[Epoch 07] train_loss=0.0636 | val_loss=0.2593 | val_mcc=0.7443 | val_f1=0.7938 | val_auroc=0.9625

[Epoch 08] train_loss=0.0484 | val_loss=0.2649 | val_mcc=0.7491 | val_f1=0.7980 | val_auroc=0.9611
[EarlyStop] epoch=8 | best_val_mcc=0.7848
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7954 | F1=0.8507 | AUROC=0.9669 | AUPRC=0.9257
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test

[Epoch 01] train_loss=0.3508 | val_loss=0.2149 | val_mcc=0.7651 | val_f1=0.8101 | val_auroc=0.9693

[Epoch 02] train_loss=0.2443 | val_loss=0.1788 | val_mcc=0.7858 | val_f1=0.8275 | val_auroc=0.9728

[Epoch 03] train_loss=0.2099 | val_loss=0.1788 | val_mcc=0.7850 | val_f1=0.8267 | val_auroc=0.9702

[Epoch 04] train_loss=0.1828 | val_loss=0.2053 | val_mcc=0.7664 | val_f1=0.8120 | val_auroc=0.9674

[Epoch 05] train_loss=0.1496 | val_loss=0.2356 | val_mcc=0.7542 | val_f1=0.8015 | val_auroc=0.9642

[Epoch 06] train_loss=0.1155 | val_loss=0.2465 | val_mcc=0.7546 | val_f1=0.8025 | val_auroc=0.9603

[Epoch 07] train_loss=0.0793 | val_loss=0.2925 | val_mcc=0.7415 | val_f1=0.7912 | val_auroc=0.9575

[Epoch 08] train_loss=0.0617 | val_loss=0.3090 | val_mcc=0.7386 | val_f1=0.7889 | val_auroc=0.9579
[EarlyStop] epoch=8 | best_val_mcc=0.7858
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7886 | F1=0.8416 | AUROC=0.9670 | AUPRC=0.9275
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test

[Epoch 01] train_loss=0.3431 | val_loss=0.2116 | val_mcc=0.7607 | val_f1=0.8071 | val_auroc=0.9677

[Epoch 02] train_loss=0.2359 | val_loss=0.1819 | val_mcc=0.7844 | val_f1=0.8264 | val_auroc=0.9720

[Epoch 03] train_loss=0.1988 | val_loss=0.1904 | val_mcc=0.7767 | val_f1=0.8201 | val_auroc=0.9706

[Epoch 04] train_loss=0.1654 | val_loss=0.1985 | val_mcc=0.7735 | val_f1=0.8176 | val_auroc=0.9665

[Epoch 05] train_loss=0.1302 | val_loss=0.2159 | val_mcc=0.7639 | val_f1=0.8098 | val_auroc=0.9628

[Epoch 06] train_loss=0.0989 | val_loss=0.2806 | val_mcc=0.7328 | val_f1=0.7843 | val_auroc=0.9581

[Epoch 07] train_loss=0.0626 | val_loss=0.3042 | val_mcc=0.7385 | val_f1=0.7883 | val_auroc=0.9609

[Epoch 08] train_loss=0.0475 | val_loss=0.3376 | val_mcc=0.7235 | val_f1=0.7761 | val_auroc=0.9572
[EarlyStop] epoch=8 | best_val_mcc=0.7844
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7867 | F1=0.8420 | AUROC=0.9668 | AUPRC=0.9279
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test

[Epoch 01] train_loss=0.3577 | val_loss=0.2061 | val_mcc=0.7688 | val_f1=0.8139 | val_auroc=0.9663

[Epoch 02] train_loss=0.2287 | val_loss=0.1953 | val_mcc=0.7716 | val_f1=0.8159 | val_auroc=0.9705

[Epoch 03] train_loss=0.1888 | val_loss=0.1873 | val_mcc=0.7750 | val_f1=0.8188 | val_auroc=0.9711

[Epoch 04] train_loss=0.1474 | val_loss=0.2140 | val_mcc=0.7641 | val_f1=0.8095 | val_auroc=0.9681

[Epoch 05] train_loss=0.1141 | val_loss=0.2237 | val_mcc=0.7588 | val_f1=0.8058 | val_auroc=0.9653

[Epoch 06] train_loss=0.0803 | val_loss=0.2563 | val_mcc=0.7439 | val_f1=0.7936 | val_auroc=0.9623

[Epoch 07] train_loss=0.0568 | val_loss=0.2690 | val_mcc=0.7435 | val_f1=0.7937 | val_auroc=0.9618

[Epoch 08] train_loss=0.0342 | val_loss=0.2849 | val_mcc=0.7474 | val_f1=0.7962 | val_auroc=0.9640

[Epoch 09] train_loss=0.0252 | val_loss=0.2895 | val_mcc=0.7510 | val_f1=0.7994 | val_auroc=0.9634
[EarlyStop] epoch=9 | best_val_mcc=0.7750
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7997 | F1=0.8508 | AUROC=0.9643 | AUPRC=0.9248
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 197.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8211 | F1=0.8676 | AUROC=0.9721 | AUPRC=0.9358
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 152.
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7992 | F1=0.8502 | AUROC=0.9685 | AUPRC=0.9310
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 125.
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8026 | F1=0.8555 | AUROC=0.9659 | AUPRC=0.9253
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 123.
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8017 | F1=0.8533 | AUROC=0.9651 | AUPRC=0.9254
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 175.
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7978 | F1=0.8509 | AUROC=0.9668 | AUPRC=0.9291
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8497 | F1=0.9224 | AUROC=0.9738 | AUPRC=0.9721
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8273 | F1=0.9063 | AUROC=0.9772 | AUPRC=0.9761
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8402 | F1=0.9148 | AUROC=0.9765 | AUPRC=0.9752
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8348 | F1=0.9115 | AUROC=0.9776 | AUPRC=0.9760
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8788 | F1=0.9335 | AUROC=0.9886 | AUPRC=0.9870
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8283 | F1=0.9058 | AUROC=0.9794 | AUPRC=0.9765
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8680 | F1=0.9302 | AUROC=0.9810 | AUPRC=0.9805
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8335 | F1=0.9126 | AUROC=0.9752 | AUPRC=0.9740
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8506 | F1=0.9215 | AUROC=0.9784 | AUPRC=0.9775
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4607 | F1=0.7365 | AUROC=0.7983 | AUPRC=0.7908
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4720 | F1=0.7309 | AUROC=0.8027 | AUPRC=0.7905
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4749 | F1=0.7376 | AUROC=0.8047 | AUPRC=0.7918
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4855 | F1=0.7376 | AUROC=0.7944 | AUPRC=0.7844
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4959 | F1=0.7455 | AUROC=0.7983 | AUPRC=0.7860
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Concat_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4689 | F1=0.7322 | AUROC=0.7934 | AUPRC=0.7748
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_CrossAttn_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4814 | F1=0.7448 | AUROC=0.8017 | AUPRC=0.7888
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Transformer_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4734 | F1=0.7371 | AUROC=0.7957 | AUPRC=0.7778
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Hybrid_Gating_XGBoost__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4719 | F1=0.7349 | AUROC=0.7999 | AUPRC=0.7827
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6030 | F1=0.7960 | AUROC=0.8910 | AUPRC=0.8712
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_CrossAttn__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6140 | F1=0.7980 | AUROC=0.8897 | AUPRC=0.8712
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Transformer__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6435 | F1=0.8112 | AUROC=0.9013 | AUPRC=0.8844
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_PyTorch_Gating__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6245 | F1=0.8039 | AUROC=0.8919 | AUPRC=0.8683
[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6479 | F1=0.8177 | AUROC=0.9063 | AUPRC=0.8843

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004391151947068313.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004787725966002879.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003649041161018101.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004751494591689312.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004834500811966018.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004669825408432569.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004736213493648356.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003846723325238052.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0035871767053844016.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0046088524671323095.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004617899396441811.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8320 | F1=0.8760 | AUROC=0.9758 | AUPRC=0.9427
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache

c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003336960163600469.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003024173886285405.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.00334013119447783.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0028740811979353336.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.002717018301740591.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0030450941684136428.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004815010989295102.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003707171492620181.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0034284100709045468.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003120306751846432.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0035986155864013167.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0031961259983959195.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0026647888475044954.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8674 | F1=0.9275 | AUROC=0.9886 | AUPRC=0.9890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache

c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.002876281727792442.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0028378973735870587.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0031490662570775895.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0028289312331625576.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.00459161086455425.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0035143016390793724.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004502874329203025.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0026643591954724887.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4809 | F1=0.7402 | AUROC=0.8098 | AUPRC=0.7948
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache

c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.002874332059108881.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.002886424384986929.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.00276088351311521.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004890295656239483.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.002964120561941678.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0028249420573406205.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0028020330161237063.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0031647057193844954.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0027467233377594406.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0027570569709476577.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

[Test] train1__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6448 | F1=0.8163 | AUROC=0.9127 | AUPRC=0.8893
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 312.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004729908430201996.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0032826687066792202.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004702556123552024.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0033180017956440603.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004781749850429702.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.00335954824413712.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0032671039555350794.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0032138590264960045.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003252265865308075.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0035822328716890598.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8298 | F1=0.8756 | AUROC=0.9744 | AUPRC=0.9424
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache

c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003988344745782229.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004600718043778669.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004837280600709687.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0035517270022639.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0031169439748131235.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003092262200757555.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003627903068442135.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004480878638170064.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0034089751669823206.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003083627761780828.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8670 | F1=0.9310 | AUROC=0.9879 | AUPRC=0.9882
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache

c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.005026765437007651.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.002926017703694265.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003523089971160507.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0028820522321889603.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0029585686579024365.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0031277649256181484.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0031784115644854054.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.002886119202427337.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0026713102065759986.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0032336101694830153.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004901984636047803.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0030438500394796278.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4774 | F1=0.7451 | AUROC=0.8003 | AUPRC=0.7744
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache

c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004543827896172719.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.002784488239936511.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0030457938450464423.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004518250723323497.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0032791299735188467.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003035224532015808.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

[Test] train2__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6447 | F1=0.8167 | AUROC=0.9102 | AUPRC=0.8825
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 197.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004811401142816135.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004523024624485917.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004660385667297907.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.00446091324601606.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004024077153868764.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004028211242216498.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.005065200372630419.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004866886036077255.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004591287558853042.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0035146097092675806.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.005212228169517057.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0046697721743099215.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004037631312863451.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0046540768393882334.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004673659772340175.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8211 | F1=0.8676 | AUROC=0.9721 | AUPRC=0.9358
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache

c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.005190925812661075.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0047866629366324675.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.00358748824568495.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003507489432060386.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0031213048026073166.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0031115307581436056.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004733775772849599.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.00490627506537628.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0029124471256226827.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004472137299805103.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0048458660248825985.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8788 | F1=0.9335 | AUROC=0.9886 | AUPRC=0.9870
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache

c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.00474203441770373.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004655932170002236.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0034677449770004337.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004947579903130552.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004412105410794152.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0030213808345438274.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0030849830764014077.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004520904796617195.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0032930892891180376.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004875502067230723.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0046537710171559955.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0045692447073335165.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4959 | F1=0.7455 | AUROC=0.7983 | AUPRC=0.7860
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache

c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0031976851211145277.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.005024471113462719.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004906009811664445.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004634341504211784.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003022093156007939.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0030688850599225924.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004400133284282642.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.003375361872468368.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.005166091662323358.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.004482331240711827.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\sklearn\linear_model\_ridge.py:227: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 0.0050772267794756964.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

[Test] train3__val_center_bio_core_dna_prot_spliceai_geom_shap_lime_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6479 | F1=0.8177 | AUROC=0.9063 | AUPRC=0.8843
[DONE] SHAP + LIME | metrics=D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011/global_leaderboard_metrics.csv | metric_rows=120 | fit_profile=D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011/global_leaderboard_fit_profiling.csv | fit_rows=30

================================================================================
[STAGE] biological feature-group ablation | configs=6
================================================================================
[PREFLIGHT PASS] 6 configurations across 12 train/test combinations.

[CONFIG MATRIX] bio_drop_group_allele_frequencies | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 453.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.7419 | F1=0.8101 | AUROC=0.9515 | AUPRC=0.8832
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.7098 | F1=0.8534 | AUROC=0.9327 | AUPRC=0.9077
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5296 | F1=0.7570 | AUROC=0.8399 | AUPRC=0.8161
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6655 | F1=0.8165 | AUROC=0.9139 | AUPRC=0.8867
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 410.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.7314 | F1=0.8033 | AUROC=0.9514 | AUPRC=0.8826
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.7240 | F1=0.8608 | AUROC=0.9359 | AUPRC=0.9206
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.5405 | F1=0.7607 | AUROC=0.8351 | AUPRC=0.8073
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6683 | F1=0.8183 | AUROC=0.9157 | AUPRC=0.8812
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 187.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7058 | F1=0.7840 | AUROC=0.9440 | AUPRC=0.8667
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.6900 | F1=0.8413 | AUROC=0.9292 | AUPRC=0.9085
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.5316 | F1=0.7557 | AUROC=0.8316 | AUPRC=0.8159
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_allele_frequencies_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6419 | F1=0.8006 | AUROC=0.9087 | AUPRC=0.8790

[CONFIG MATRIX] bio_drop_group_conservation_scores | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 417.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.7807 | F1=0.8316 | AUROC=0.9600 | AUPRC=0.9205
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8077 | F1=0.8836 | AUROC=0.9879 | AUPRC=0.9886
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4134 | F1=0.6904 | AUROC=0.7676 | AUPRC=0.7449
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.5901 | F1=0.7791 | AUROC=0.8721 | AUPRC=0.8469
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 388.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.7720 | F1=0.8260 | AUROC=0.9591 | AUPRC=0.9156
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8042 | F1=0.8850 | AUROC=0.9866 | AUPRC=0.9863
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4154 | F1=0.6894 | AUROC=0.7649 | AUPRC=0.7552
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.5967 | F1=0.7846 | AUROC=0.8717 | AUPRC=0.8396
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 127.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7618 | F1=0.8174 | AUROC=0.9547 | AUPRC=0.9084
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8282 | F1=0.8973 | AUROC=0.9879 | AUPRC=0.9872
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4379 | F1=0.7016 | AUROC=0.7676 | AUPRC=0.7640
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_conservation_scores_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.5832 | F1=0.7752 | AUROC=0.8700 | AUPRC=0.8501

[CONFIG MATRIX] bio_drop_group_spliceai | modalities=['dna', 'prot', 'bio_core', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 282.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8275 | F1=0.8727 | AUROC=0.9755 | AUPRC=0.9433
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8657 | F1=0.9284 | AUROC=0.9875 | AUPRC=0.9875
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4974 | F1=0.7494 | AUROC=0.8094 | AUPRC=0.7892
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6511 | F1=0.8195 | AUROC=0.9141 | AUPRC=0.8858
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 251.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8278 | F1=0.8733 | AUROC=0.9745 | AUPRC=0.9419
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8604 | F1=0.9251 | AUROC=0.9878 | AUPRC=0.9878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4810 | F1=0.7418 | AUROC=0.8059 | AUPRC=0.7870
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6590 | F1=0.8235 | AUROC=0.9136 | AUPRC=0.8899
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 203.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8200 | F1=0.8669 | AUROC=0.9715 | AUPRC=0.9358
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8841 | F1=0.9367 | AUROC=0.9891 | AUPRC=0.9890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4989 | F1=0.7470 | AUROC=0.7979 | AUPRC=0.7885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_spliceai_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6633 | F1=0.8250 | AUROC=0.9055 | AUPRC=0.8883

[CONFIG MATRIX] bio_drop_group_geometry | modalities=['dna', 'prot', 'bio_core', 'spliceai'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 300.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.8353 | F1=0.8787 | AUROC=0.9762 | AUPRC=0.9423
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.8863 | F1=0.9385 | AUROC=0.9901 | AUPRC=0.9905
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.5084 | F1=0.7581 | AUROC=0.8128 | AUPRC=0.7943
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.6495 | F1=0.8190 | AUROC=0.9150 | AUPRC=0.8893
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 383.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_Test | MCC=0.8276 | F1=0.8745 | AUROC=0.9749 | AUPRC=0.9440
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ClinVarHQ | MCC=0.8871 | F1=0.9412 | AUROC=0.9884 | AUPRC=0.9886
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_UniProt | MCC=0.5108 | F1=0.7622 | AUROC=0.8072 | AUPRC=0.7858
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ProteinGym | MCC=0.6402 | F1=0.8146 | AUROC=0.9108 | AUPRC=0.8878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 175.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.8287 | F1=0.8745 | AUROC=0.9721 | AUPRC=0.9369
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8810 | F1=0.9353 | AUROC=0.9887 | AUPRC=0.9886
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4799 | F1=0.7443 | AUROC=0.7947 | AUPRC=0.7780
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6365 | F1=0.8126 | AUROC=0.9051 | AUPRC=0.8828

[CONFIG MATRIX] bio_drop_group_dna_geometry | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 303.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8295 | F1=0.8742 | AUROC=0.9756 | AUPRC=0.9417
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8855 | F1=0.9389 | AUROC=0.9876 | AUPRC=0.9881
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4944 | F1=0.7476 | AUROC=0.8118 | AUPRC=0.7964
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6500 | F1=0.8191 | AUROC=0.9144 | AUPRC=0.8897
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 395.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8312 | F1=0.8763 | AUROC=0.9748 | AUPRC=0.9412
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8768 | F1=0.9345 | AUROC=0.9881 | AUPRC=0.9885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4872 | F1=0.7467 | AUROC=0.8026 | AUPRC=0.7786
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6498 | F1=0.8190 | AUROC=0.9121 | AUPRC=0.8840
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 214.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8178 | F1=0.8677 | AUROC=0.9721 | AUPRC=0.9351
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8843 | F1=0.9396 | AUROC=0.9875 | AUPRC=0.9873
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4962 | F1=0.7563 | AUROC=0.8006 | AUPRC=0.7948
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_dna_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6204 | F1=0.8052 | AUROC=0.9052 | AUPRC=0.8809

[CONFIG MATRIX] bio_drop_group_protein_geometry | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 336.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train1Val_Test | MCC=0.8295 | F1=0.8755 | AUROC=0.9768 | AUPRC=0.9462
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8906 | F1=0.9422 | AUROC=0.9904 | AUPRC=0.9907
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4949 | F1=0.7517 | AUROC=0.8093 | AUPRC=0.7849
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6489 | F1=0.8188 | AUROC=0.9128 | AUPRC=0.8810
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 386.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train2Val_Test | MCC=0.8289 | F1=0.8753 | AUROC=0.9743 | AUPRC=0.9411
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8645 | F1=0.9292 | AUROC=0.9866 | AUPRC=0.9871
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4997 | F1=0.7551 | AUROC=0.8055 | AUPRC=0.7837
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6478 | F1=0.8182 | AUROC=0.9066 | AUPRC=0.8792
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 193.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train3Val_Test | MCC=0.8159 | F1=0.8626 | AUROC=0.9726 | AUPRC=0.9340
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8549 | F1=0.9191 | AUROC=0.9885 | AUPRC=0.9888
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4646 | F1=0.7264 | AUROC=0.8013 | AUPRC=0.7857
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_group_protein_geometry_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6484 | F1=0.8176 | AUROC=0.9055 | AUPRC=0.8803
[DONE] biological feature-group ablation | metrics=D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011/global_leaderboard_metrics.csv | metric_rows=192 | fit_profile=D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011/global_leaderboard_fit_profiling.csv | fit_rows=48

================================================================================
[STAGE] 28 individual-feature ablation | configs=28
================================================================================
[PREFLIGHT PASS] 28 configurations across 12 train/test combinations.

[CONFIG MATRIX] bio_drop_feature_AF | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 341.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8265 | F1=0.8731 | AUROC=0.9747 | AUPRC=0.9412
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8822 | F1=0.9377 | AUROC=0.9867 | AUPRC=0.9868
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4963 | F1=0.7518 | AUROC=0.8102 | AUPRC=0.7915
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6429 | F1=0.8159 | AUROC=0.9115 | AUPRC=0.8858
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 388.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8217 | F1=0.8699 | AUROC=0.9727 | AUPRC=0.9380
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8825 | F1=0.9375 | AUROC=0.9846 | AUPRC=0.9850
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4741 | F1=0.7425 | AUROC=0.8003 | AUPRC=0.7788
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6399 | F1=0.8144 | AUROC=0.9091 | AUPRC=0.8876
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 214.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8204 | F1=0.8680 | AUROC=0.9709 | AUPRC=0.9339
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8779 | F1=0.9339 | AUROC=0.9862 | AUPRC=0.9854
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4855 | F1=0.7446 | AUROC=0.7984 | AUPRC=0.7930
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6324 | F1=0.8105 | AUROC=0.9038 | AUPRC=0.8801

[CONFIG MATRIX] bio_drop_feature_gnomADe_AF | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 369.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.7846 | F1=0.8413 | AUROC=0.9666 | AUPRC=0.9225
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8039 | F1=0.8996 | AUROC=0.9678 | AUPRC=0.9620
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5305 | F1=0.7609 | AUROC=0.8349 | AUPRC=0.8242
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6839 | F1=0.8309 | AUROC=0.9215 | AUPRC=0.9005
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 410.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.7830 | F1=0.8432 | AUROC=0.9648 | AUPRC=0.9176
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8047 | F1=0.9032 | AUROC=0.9678 | AUPRC=0.9618
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.5276 | F1=0.7710 | AUROC=0.8300 | AUPRC=0.8153
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6819 | F1=0.8340 | AUROC=0.9203 | AUPRC=0.8939
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 203.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7666 | F1=0.8286 | AUROC=0.9603 | AUPRC=0.9074
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.7895 | F1=0.8928 | AUROC=0.9661 | AUPRC=0.9620
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.5169 | F1=0.7553 | AUROC=0.8253 | AUPRC=0.8133
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_gnomADe_AF_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6695 | F1=0.8221 | AUROC=0.9141 | AUPRC=0.8952

[CONFIG MATRIX] bio_drop_feature_phyloP100way_vertebrate | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 382.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8262 | F1=0.8703 | AUROC=0.9750 | AUPRC=0.9424
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8627 | F1=0.9240 | AUROC=0.9891 | AUPRC=0.9894
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4840 | F1=0.7374 | AUROC=0.8074 | AUPRC=0.7831
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6546 | F1=0.8208 | AUROC=0.9087 | AUPRC=0.8796
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 420.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8326 | F1=0.8777 | AUROC=0.9738 | AUPRC=0.9405
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.9017 | F1=0.9483 | AUROC=0.9876 | AUPRC=0.9879
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4803 | F1=0.7462 | AUROC=0.8008 | AUPRC=0.7808
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6574 | F1=0.8228 | AUROC=0.9057 | AUPRC=0.8785
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 230.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8160 | F1=0.8641 | AUROC=0.9706 | AUPRC=0.9305
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8814 | F1=0.9351 | AUROC=0.9889 | AUPRC=0.9889
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4734 | F1=0.7375 | AUROC=0.7940 | AUPRC=0.7862
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phyloP100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6202 | F1=0.8043 | AUROC=0.8948 | AUPRC=0.8678

[CONFIG MATRIX] bio_drop_feature_phyloP470way_mammalian | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 329.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8334 | F1=0.8780 | AUROC=0.9766 | AUPRC=0.9438
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8849 | F1=0.9393 | AUROC=0.9904 | AUPRC=0.9904
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4908 | F1=0.7511 | AUROC=0.8113 | AUPRC=0.7848
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6347 | F1=0.8119 | AUROC=0.9096 | AUPRC=0.8807
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 371.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8331 | F1=0.8785 | AUROC=0.9751 | AUPRC=0.9425
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8814 | F1=0.9382 | AUROC=0.9885 | AUPRC=0.9888
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4935 | F1=0.7556 | AUROC=0.8076 | AUPRC=0.7856
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6483 | F1=0.8185 | AUROC=0.9113 | AUPRC=0.8803
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 162.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8183 | F1=0.8656 | AUROC=0.9719 | AUPRC=0.9363
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8617 | F1=0.9245 | AUROC=0.9875 | AUPRC=0.9873
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4989 | F1=0.7474 | AUROC=0.7982 | AUPRC=0.7827
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phyloP470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6421 | F1=0.8149 | AUROC=0.9042 | AUPRC=0.8848

[CONFIG MATRIX] bio_drop_feature_phyloP17way_primate | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 273.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8272 | F1=0.8741 | AUROC=0.9747 | AUPRC=0.9423
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8792 | F1=0.9363 | AUROC=0.9888 | AUPRC=0.9891
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4843 | F1=0.7509 | AUROC=0.8062 | AUPRC=0.7872
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6300 | F1=0.8097 | AUROC=0.9127 | AUPRC=0.8908
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 362.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8235 | F1=0.8720 | AUROC=0.9739 | AUPRC=0.9409
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8782 | F1=0.9370 | AUROC=0.9879 | AUPRC=0.9882
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4812 | F1=0.7491 | AUROC=0.8006 | AUPRC=0.7814
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6343 | F1=0.8118 | AUROC=0.9102 | AUPRC=0.8824
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 202.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8183 | F1=0.8669 | AUROC=0.9704 | AUPRC=0.9338
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.9023 | F1=0.9480 | AUROC=0.9882 | AUPRC=0.9884
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4857 | F1=0.7461 | AUROC=0.7954 | AUPRC=0.7861
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phyloP17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6515 | F1=0.8197 | AUROC=0.9055 | AUPRC=0.8861

[CONFIG MATRIX] bio_drop_feature_phastCons100way_vertebrate | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 311.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8290 | F1=0.8746 | AUROC=0.9763 | AUPRC=0.9449
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8795 | F1=0.9361 | AUROC=0.9892 | AUPRC=0.9894
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4934 | F1=0.7507 | AUROC=0.8090 | AUPRC=0.7902
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6445 | F1=0.8165 | AUROC=0.9126 | AUPRC=0.8880
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 400.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8277 | F1=0.8727 | AUROC=0.9746 | AUPRC=0.9416
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8696 | F1=0.9293 | AUROC=0.9881 | AUPRC=0.9887
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4899 | F1=0.7432 | AUROC=0.8034 | AUPRC=0.7836
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6687 | F1=0.8280 | AUROC=0.9126 | AUPRC=0.8902
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 166.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8187 | F1=0.8671 | AUROC=0.9709 | AUPRC=0.9341
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8885 | F1=0.9403 | AUROC=0.9894 | AUPRC=0.9897
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4872 | F1=0.7470 | AUROC=0.7981 | AUPRC=0.7821
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phastCons100way_vertebrate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6413 | F1=0.8150 | AUROC=0.9087 | AUPRC=0.8891

[CONFIG MATRIX] bio_drop_feature_phastCons470way_mammalian | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 367.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8332 | F1=0.8777 | AUROC=0.9769 | AUPRC=0.9447
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8822 | F1=0.9377 | AUROC=0.9895 | AUPRC=0.9894
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4933 | F1=0.7500 | AUROC=0.8116 | AUPRC=0.7910
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6410 | F1=0.8149 | AUROC=0.9124 | AUPRC=0.8878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 364.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8301 | F1=0.8747 | AUROC=0.9748 | AUPRC=0.9417
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8680 | F1=0.9302 | AUROC=0.9876 | AUPRC=0.9877
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4824 | F1=0.7412 | AUROC=0.8033 | AUPRC=0.7814
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6659 | F1=0.8266 | AUROC=0.9116 | AUPRC=0.8842
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 169.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8198 | F1=0.8657 | AUROC=0.9714 | AUPRC=0.9371
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8689 | F1=0.9268 | AUROC=0.9884 | AUPRC=0.9886
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4944 | F1=0.7433 | AUROC=0.7976 | AUPRC=0.7837
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phastCons470way_mammalian_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6588 | F1=0.8224 | AUROC=0.9016 | AUPRC=0.8771

[CONFIG MATRIX] bio_drop_feature_phastCons17way_primate | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 378.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8302 | F1=0.8760 | AUROC=0.9765 | AUPRC=0.9449
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8816 | F1=0.9381 | AUROC=0.9897 | AUPRC=0.9899
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4759 | F1=0.7445 | AUROC=0.8093 | AUPRC=0.7888
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6245 | F1=0.8071 | AUROC=0.9135 | AUPRC=0.8827
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 334.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8253 | F1=0.8727 | AUROC=0.9752 | AUPRC=0.9410
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8816 | F1=0.9381 | AUROC=0.9877 | AUPRC=0.9874
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4915 | F1=0.7536 | AUROC=0.8047 | AUPRC=0.7862
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6391 | F1=0.8140 | AUROC=0.9105 | AUPRC=0.8864
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 202.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8250 | F1=0.8718 | AUROC=0.9725 | AUPRC=0.9368
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8859 | F1=0.9387 | AUROC=0.9896 | AUPRC=0.9894
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4907 | F1=0.7507 | AUROC=0.8024 | AUPRC=0.7883
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_phastCons17way_primate_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6335 | F1=0.8112 | AUROC=0.9074 | AUPRC=0.8837

[CONFIG MATRIX] bio_drop_feature_GERP++_RS | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 330.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8294 | F1=0.8740 | AUROC=0.9763 | AUPRC=0.9439
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8775 | F1=0.9341 | AUROC=0.9893 | AUPRC=0.9896
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4824 | F1=0.7396 | AUROC=0.8088 | AUPRC=0.7839
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6523 | F1=0.8200 | AUROC=0.9121 | AUPRC=0.8846
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 332.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8337 | F1=0.8777 | AUROC=0.9749 | AUPRC=0.9427
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8768 | F1=0.9345 | AUROC=0.9891 | AUPRC=0.9895
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4780 | F1=0.7407 | AUROC=0.8028 | AUPRC=0.7775
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6687 | F1=0.8281 | AUROC=0.9146 | AUPRC=0.8917
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 213.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8225 | F1=0.8703 | AUROC=0.9718 | AUPRC=0.9358
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8893 | F1=0.9399 | AUROC=0.9887 | AUPRC=0.9877
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4977 | F1=0.7517 | AUROC=0.8015 | AUPRC=0.7868
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_GERP++_RS_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6429 | F1=0.8158 | AUROC=0.9047 | AUPRC=0.8793

[CONFIG MATRIX] bio_drop_feature_GERP++_NR | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 327.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8314 | F1=0.8762 | AUROC=0.9756 | AUPRC=0.9435
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8859 | F1=0.9387 | AUROC=0.9908 | AUPRC=0.9910
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4975 | F1=0.7502 | AUROC=0.8107 | AUPRC=0.7906
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6278 | F1=0.8085 | AUROC=0.9116 | AUPRC=0.8900
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 273.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8258 | F1=0.8728 | AUROC=0.9747 | AUPRC=0.9421
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8843 | F1=0.9396 | AUROC=0.9877 | AUPRC=0.9881
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4833 | F1=0.7476 | AUROC=0.8060 | AUPRC=0.7918
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6454 | F1=0.8170 | AUROC=0.9100 | AUPRC=0.8854
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 209.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8182 | F1=0.8681 | AUROC=0.9723 | AUPRC=0.9374
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8896 | F1=0.9429 | AUROC=0.9885 | AUPRC=0.9884
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4922 | F1=0.7554 | AUROC=0.8037 | AUPRC=0.7891
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_GERP++_NR_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6154 | F1=0.8029 | AUROC=0.9044 | AUPRC=0.8798

[CONFIG MATRIX] bio_drop_feature_GERP_92_mammals | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 358.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8315 | F1=0.8769 | AUROC=0.9763 | AUPRC=0.9442
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8849 | F1=0.9393 | AUROC=0.9896 | AUPRC=0.9900
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4896 | F1=0.7516 | AUROC=0.8105 | AUPRC=0.7909
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6397 | F1=0.8143 | AUROC=0.9122 | AUPRC=0.8846
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 279.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8302 | F1=0.8757 | AUROC=0.9750 | AUPRC=0.9420
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8738 | F1=0.9331 | AUROC=0.9864 | AUPRC=0.9870
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4831 | F1=0.7465 | AUROC=0.8039 | AUPRC=0.7843
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6516 | F1=0.8200 | AUROC=0.9116 | AUPRC=0.8833
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 206.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8223 | F1=0.8702 | AUROC=0.9712 | AUPRC=0.9357
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8969 | F1=0.9449 | AUROC=0.9887 | AUPRC=0.9888
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4903 | F1=0.7489 | AUROC=0.8014 | AUPRC=0.7912
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_GERP_92_mammals_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6258 | F1=0.8077 | AUROC=0.9048 | AUPRC=0.8846

[CONFIG MATRIX] bio_drop_feature_SpliceAI_pred_DS_AG | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 314.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8299 | F1=0.8744 | AUROC=0.9758 | AUPRC=0.9428
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8700 | F1=0.9291 | AUROC=0.9892 | AUPRC=0.9894
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4809 | F1=0.7402 | AUROC=0.8098 | AUPRC=0.7944
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6464 | F1=0.8171 | AUROC=0.9119 | AUPRC=0.8873
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 254.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8243 | F1=0.8716 | AUROC=0.9742 | AUPRC=0.9413
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8677 | F1=0.9304 | AUROC=0.9876 | AUPRC=0.9878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4711 | F1=0.7410 | AUROC=0.8010 | AUPRC=0.7777
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6317 | F1=0.8104 | AUROC=0.9102 | AUPRC=0.8841
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 194.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8239 | F1=0.8718 | AUROC=0.9722 | AUPRC=0.9359
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8930 | F1=0.9440 | AUROC=0.9893 | AUPRC=0.9885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4859 | F1=0.7518 | AUROC=0.7993 | AUPRC=0.7897
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6228 | F1=0.8063 | AUROC=0.9054 | AUPRC=0.8851

[CONFIG MATRIX] bio_drop_feature_SpliceAI_pred_DS_AL | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 316.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8288 | F1=0.8733 | AUROC=0.9767 | AUPRC=0.9450
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8762 | F1=0.9319 | AUROC=0.9888 | AUPRC=0.9889
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4869 | F1=0.7421 | AUROC=0.8104 | AUPRC=0.7883
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6499 | F1=0.8187 | AUROC=0.9106 | AUPRC=0.8842
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 360.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8297 | F1=0.8749 | AUROC=0.9756 | AUPRC=0.9418
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8795 | F1=0.9361 | AUROC=0.9887 | AUPRC=0.9890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4780 | F1=0.7407 | AUROC=0.8052 | AUPRC=0.7855
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6625 | F1=0.8251 | AUROC=0.9099 | AUPRC=0.8857
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 185.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8196 | F1=0.8659 | AUROC=0.9715 | AUPRC=0.9350
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8726 | F1=0.9307 | AUROC=0.9893 | AUPRC=0.9894
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4914 | F1=0.7438 | AUROC=0.7995 | AUPRC=0.7838
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6401 | F1=0.8130 | AUROC=0.9070 | AUPRC=0.8844

[CONFIG MATRIX] bio_drop_feature_SpliceAI_pred_DS_DG | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 368.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8281 | F1=0.8739 | AUROC=0.9769 | AUPRC=0.9456
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8711 | F1=0.9315 | AUROC=0.9887 | AUPRC=0.9890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4814 | F1=0.7448 | AUROC=0.8148 | AUPRC=0.7988
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6335 | F1=0.8112 | AUROC=0.9129 | AUPRC=0.8880
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 365.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8331 | F1=0.8770 | AUROC=0.9750 | AUPRC=0.9418
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8627 | F1=0.9270 | AUROC=0.9882 | AUPRC=0.9884
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4839 | F1=0.7414 | AUROC=0.8025 | AUPRC=0.7850
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6616 | F1=0.8245 | AUROC=0.9081 | AUPRC=0.8818
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 194.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8287 | F1=0.8747 | AUROC=0.9725 | AUPRC=0.9378
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8802 | F1=0.9357 | AUROC=0.9886 | AUPRC=0.9885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4893 | F1=0.7505 | AUROC=0.7999 | AUPRC=0.7877
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6425 | F1=0.8156 | AUROC=0.9056 | AUPRC=0.8806

[CONFIG MATRIX] bio_drop_feature_SpliceAI_pred_DS_DL | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 358.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8335 | F1=0.8774 | AUROC=0.9763 | AUPRC=0.9437
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8810 | F1=0.9353 | AUROC=0.9900 | AUPRC=0.9906
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4841 | F1=0.7448 | AUROC=0.8116 | AUPRC=0.7879
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6583 | F1=0.8231 | AUROC=0.9129 | AUPRC=0.8844
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 282.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8319 | F1=0.8762 | AUROC=0.9753 | AUPRC=0.9444
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8711 | F1=0.9315 | AUROC=0.9876 | AUPRC=0.9881
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4839 | F1=0.7425 | AUROC=0.8042 | AUPRC=0.7791
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6609 | F1=0.8242 | AUROC=0.9116 | AUPRC=0.8851
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 219.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8230 | F1=0.8707 | AUROC=0.9722 | AUPRC=0.9355
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8885 | F1=0.9403 | AUROC=0.9899 | AUPRC=0.9896
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4952 | F1=0.7531 | AUROC=0.8002 | AUPRC=0.7861
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6276 | F1=0.8085 | AUROC=0.9100 | AUPRC=0.8903

[CONFIG MATRIX] bio_drop_feature_SpliceAI_pred_DP_AG | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 327.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8305 | F1=0.8744 | AUROC=0.9765 | AUPRC=0.9442
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8731 | F1=0.9305 | AUROC=0.9890 | AUPRC=0.9893
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4945 | F1=0.7426 | AUROC=0.8108 | AUPRC=0.7923
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6546 | F1=0.8210 | AUROC=0.9109 | AUPRC=0.8839
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 416.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8256 | F1=0.8732 | AUROC=0.9748 | AUPRC=0.9414
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8643 | F1=0.9294 | AUROC=0.9881 | AUPRC=0.9885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4766 | F1=0.7467 | AUROC=0.8021 | AUPRC=0.7808
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6411 | F1=0.8150 | AUROC=0.9121 | AUPRC=0.8843
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 183.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8175 | F1=0.8659 | AUROC=0.9717 | AUPRC=0.9364
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8784 | F1=0.9337 | AUROC=0.9890 | AUPRC=0.9889
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4825 | F1=0.7427 | AUROC=0.8000 | AUPRC=0.7863
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6317 | F1=0.8102 | AUROC=0.9053 | AUPRC=0.8821

[CONFIG MATRIX] bio_drop_feature_SpliceAI_pred_DP_AL | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 307.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8302 | F1=0.8755 | AUROC=0.9763 | AUPRC=0.9445
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8798 | F1=0.9359 | AUROC=0.9898 | AUPRC=0.9900
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4961 | F1=0.7504 | AUROC=0.8082 | AUPRC=0.7862
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6411 | F1=0.8148 | AUROC=0.9116 | AUPRC=0.8803
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 301.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8302 | F1=0.8764 | AUROC=0.9741 | AUPRC=0.9418
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8702 | F1=0.9322 | AUROC=0.9880 | AUPRC=0.9885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4782 | F1=0.7477 | AUROC=0.8033 | AUPRC=0.7811
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6505 | F1=0.8195 | AUROC=0.9121 | AUPRC=0.8854
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 210.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8186 | F1=0.8676 | AUROC=0.9719 | AUPRC=0.9351
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8852 | F1=0.9391 | AUROC=0.9889 | AUPRC=0.9890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4965 | F1=0.7526 | AUROC=0.8010 | AUPRC=0.7880
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_AL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6263 | F1=0.8079 | AUROC=0.9065 | AUPRC=0.8856

[CONFIG MATRIX] bio_drop_feature_SpliceAI_pred_DP_DG | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 311.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8287 | F1=0.8740 | AUROC=0.9765 | AUPRC=0.9448
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8775 | F1=0.9341 | AUROC=0.9896 | AUPRC=0.9895
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4750 | F1=0.7388 | AUROC=0.8116 | AUPRC=0.7939
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6422 | F1=0.8153 | AUROC=0.9128 | AUPRC=0.8819
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 303.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8330 | F1=0.8773 | AUROC=0.9744 | AUPRC=0.9394
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8741 | F1=0.9329 | AUROC=0.9881 | AUPRC=0.9887
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4782 | F1=0.7422 | AUROC=0.8009 | AUPRC=0.7779
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6502 | F1=0.8193 | AUROC=0.9098 | AUPRC=0.8816
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 183.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8257 | F1=0.8725 | AUROC=0.9721 | AUPRC=0.9353
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8966 | F1=0.9450 | AUROC=0.9893 | AUPRC=0.9895
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4906 | F1=0.7504 | AUROC=0.7989 | AUPRC=0.7897
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DG_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6465 | F1=0.8176 | AUROC=0.9028 | AUPRC=0.8840

[CONFIG MATRIX] bio_drop_feature_SpliceAI_pred_DP_DL | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 273.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8305 | F1=0.8746 | AUROC=0.9767 | AUPRC=0.9446
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8736 | F1=0.9303 | AUROC=0.9896 | AUPRC=0.9897
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4854 | F1=0.7400 | AUROC=0.8085 | AUPRC=0.7898
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6542 | F1=0.8209 | AUROC=0.9115 | AUPRC=0.8826
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 382.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8340 | F1=0.8779 | AUROC=0.9752 | AUPRC=0.9434
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8802 | F1=0.9357 | AUROC=0.9882 | AUPRC=0.9885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4856 | F1=0.7450 | AUROC=0.8053 | AUPRC=0.7795
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6496 | F1=0.8189 | AUROC=0.9108 | AUPRC=0.8784
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 223.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8228 | F1=0.8707 | AUROC=0.9726 | AUPRC=0.9367
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8795 | F1=0.9361 | AUROC=0.9881 | AUPRC=0.9871
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4878 | F1=0.7496 | AUROC=0.8000 | AUPRC=0.7943
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DP_DL_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6352 | F1=0.8122 | AUROC=0.9059 | AUPRC=0.8816

[CONFIG MATRIX] bio_drop_feature_SpliceAI_pred_DS_max | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 331.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8305 | F1=0.8737 | AUROC=0.9756 | AUPRC=0.9441
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8705 | F1=0.9289 | AUROC=0.9896 | AUPRC=0.9898
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4794 | F1=0.7361 | AUROC=0.8109 | AUPRC=0.7883
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6619 | F1=0.8240 | AUROC=0.9133 | AUPRC=0.8905
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 329.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8352 | F1=0.8791 | AUROC=0.9753 | AUPRC=0.9430
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8738 | F1=0.9331 | AUROC=0.9859 | AUPRC=0.9866
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4825 | F1=0.7427 | AUROC=0.8045 | AUPRC=0.7858
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6674 | F1=0.8276 | AUROC=0.9114 | AUPRC=0.8888
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 207.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8186 | F1=0.8658 | AUROC=0.9725 | AUPRC=0.9366
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8705 | F1=0.9289 | AUROC=0.9885 | AUPRC=0.9885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4899 | F1=0.7424 | AUROC=0.8004 | AUPRC=0.7875
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_SpliceAI_pred_DS_max_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6335 | F1=0.8106 | AUROC=0.9046 | AUPRC=0.8860

[CONFIG MATRIX] bio_drop_feature_dna_LID | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 324.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8370 | F1=0.8808 | AUROC=0.9772 | AUPRC=0.9459
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8903 | F1=0.9424 | AUROC=0.9897 | AUPRC=0.9896
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5042 | F1=0.7572 | AUROC=0.8105 | AUPRC=0.7941
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6407 | F1=0.8148 | AUROC=0.9169 | AUPRC=0.8942
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 227.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8291 | F1=0.8755 | AUROC=0.9744 | AUPRC=0.9407
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8849 | F1=0.9393 | AUROC=0.9882 | AUPRC=0.9883
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4820 | F1=0.7478 | AUROC=0.8056 | AUPRC=0.7833
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6509 | F1=0.8197 | AUROC=0.9111 | AUPRC=0.8849
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 163.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8172 | F1=0.8655 | AUROC=0.9720 | AUPRC=0.9356
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8745 | F1=0.9327 | AUROC=0.9901 | AUPRC=0.9894
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4990 | F1=0.7507 | AUROC=0.8000 | AUPRC=0.7841
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_dna_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6445 | F1=0.8162 | AUROC=0.9079 | AUPRC=0.8858

[CONFIG MATRIX] bio_drop_feature_dna_LVD_L2 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 350.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8309 | F1=0.8748 | AUROC=0.9750 | AUPRC=0.9428
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8617 | F1=0.9245 | AUROC=0.9892 | AUPRC=0.9892
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4929 | F1=0.7432 | AUROC=0.8105 | AUPRC=0.7915
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6473 | F1=0.8178 | AUROC=0.9108 | AUPRC=0.8871
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 309.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8296 | F1=0.8744 | AUROC=0.9752 | AUPRC=0.9430
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8687 | F1=0.9297 | AUROC=0.9883 | AUPRC=0.9886
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4809 | F1=0.7395 | AUROC=0.8046 | AUPRC=0.7858
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6632 | F1=0.8253 | AUROC=0.9118 | AUPRC=0.8853
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 184.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8159 | F1=0.8635 | AUROC=0.9723 | AUPRC=0.9349
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8788 | F1=0.9335 | AUROC=0.9888 | AUPRC=0.9884
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4809 | F1=0.7395 | AUROC=0.7970 | AUPRC=0.7857
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_dna_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6383 | F1=0.8124 | AUROC=0.9070 | AUPRC=0.8900

[CONFIG MATRIX] bio_drop_feature_dna_LVD_Relative | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 363.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8326 | F1=0.8777 | AUROC=0.9762 | AUPRC=0.9445
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8819 | F1=0.9379 | AUROC=0.9890 | AUPRC=0.9895
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4987 | F1=0.7564 | AUROC=0.8110 | AUPRC=0.7945
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6355 | F1=0.8124 | AUROC=0.9123 | AUPRC=0.8858
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 317.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8271 | F1=0.8734 | AUROC=0.9752 | AUPRC=0.9435
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8654 | F1=0.9286 | AUROC=0.9892 | AUPRC=0.9898
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4933 | F1=0.7504 | AUROC=0.8051 | AUPRC=0.7851
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6629 | F1=0.8254 | AUROC=0.9111 | AUPRC=0.8869
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 176.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8160 | F1=0.8646 | AUROC=0.9714 | AUPRC=0.9352
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8852 | F1=0.9391 | AUROC=0.9892 | AUPRC=0.9893
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4766 | F1=0.7405 | AUROC=0.7993 | AUPRC=0.7846
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_dna_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6407 | F1=0.8145 | AUROC=0.9063 | AUPRC=0.8851

[CONFIG MATRIX] bio_drop_feature_dna_LVD_Cosine | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 351.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8352 | F1=0.8786 | AUROC=0.9763 | AUPRC=0.9427
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8832 | F1=0.9371 | AUROC=0.9885 | AUPRC=0.9890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4945 | F1=0.7487 | AUROC=0.8082 | AUPRC=0.7865
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6388 | F1=0.8137 | AUROC=0.9122 | AUPRC=0.8847
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 272.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8284 | F1=0.8750 | AUROC=0.9749 | AUPRC=0.9437
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8757 | F1=0.9353 | AUROC=0.9876 | AUPRC=0.9882
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4852 | F1=0.7496 | AUROC=0.8048 | AUPRC=0.7836
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6520 | F1=0.8202 | AUROC=0.9103 | AUPRC=0.8832
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 187.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8205 | F1=0.8688 | AUROC=0.9724 | AUPRC=0.9362
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8885 | F1=0.9403 | AUROC=0.9884 | AUPRC=0.9885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4891 | F1=0.7494 | AUROC=0.8022 | AUPRC=0.7894
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_dna_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6232 | F1=0.8064 | AUROC=0.9054 | AUPRC=0.8834

[CONFIG MATRIX] bio_drop_feature_prot_LID | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 340.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8316 | F1=0.8756 | AUROC=0.9760 | AUPRC=0.9445
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8775 | F1=0.9341 | AUROC=0.9880 | AUPRC=0.9880
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4899 | F1=0.7432 | AUROC=0.8117 | AUPRC=0.7945
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6491 | F1=0.8184 | AUROC=0.9130 | AUPRC=0.8868
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 305.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8288 | F1=0.8738 | AUROC=0.9753 | AUPRC=0.9413
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8691 | F1=0.9295 | AUROC=0.9891 | AUPRC=0.9893
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4899 | F1=0.7440 | AUROC=0.8050 | AUPRC=0.7878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6698 | F1=0.8286 | AUROC=0.9120 | AUPRC=0.8834
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 226.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8195 | F1=0.8664 | AUROC=0.9719 | AUPRC=0.9359
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8819 | F1=0.9349 | AUROC=0.9881 | AUPRC=0.9880
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4704 | F1=0.7344 | AUROC=0.7962 | AUPRC=0.7817
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_prot_LID_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6393 | F1=0.8134 | AUROC=0.9025 | AUPRC=0.8808

[CONFIG MATRIX] bio_drop_feature_prot_LVD_L2 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 259.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8233 | F1=0.8698 | AUROC=0.9758 | AUPRC=0.9439
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8691 | F1=0.9295 | AUROC=0.9888 | AUPRC=0.9892
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4959 | F1=0.7474 | AUROC=0.8117 | AUPRC=0.7875
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6406 | F1=0.8143 | AUROC=0.9115 | AUPRC=0.8866
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 406.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8341 | F1=0.8787 | AUROC=0.9747 | AUPRC=0.9409
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8816 | F1=0.9381 | AUROC=0.9888 | AUPRC=0.9890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4935 | F1=0.7515 | AUROC=0.8045 | AUPRC=0.7754
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6484 | F1=0.8184 | AUROC=0.9094 | AUPRC=0.8804
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 196.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8246 | F1=0.8715 | AUROC=0.9723 | AUPRC=0.9356
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8943 | F1=0.9433 | AUROC=0.9894 | AUPRC=0.9895
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4818 | F1=0.7467 | AUROC=0.7990 | AUPRC=0.7850
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_prot_LVD_L2_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6401 | F1=0.8144 | AUROC=0.9078 | AUPRC=0.8886

[CONFIG MATRIX] bio_drop_feature_prot_LVD_Relative | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 317.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8390 | F1=0.8814 | AUROC=0.9766 | AUPRC=0.9461
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8806 | F1=0.9355 | AUROC=0.9890 | AUPRC=0.9891
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5097 | F1=0.7576 | AUROC=0.8122 | AUPRC=0.7955
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6508 | F1=0.8194 | AUROC=0.9111 | AUPRC=0.8853
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 333.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8338 | F1=0.8783 | AUROC=0.9747 | AUPRC=0.9426
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8825 | F1=0.9375 | AUROC=0.9888 | AUPRC=0.9892
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4872 | F1=0.7470 | AUROC=0.8034 | AUPRC=0.7838
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6560 | F1=0.8220 | AUROC=0.9116 | AUPRC=0.8854
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 193.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8203 | F1=0.8686 | AUROC=0.9726 | AUPRC=0.9379
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8795 | F1=0.9361 | AUROC=0.9876 | AUPRC=0.9874
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4948 | F1=0.7513 | AUROC=0.7998 | AUPRC=0.7851
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_prot_LVD_Relative_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6349 | F1=0.8120 | AUROC=0.9080 | AUPRC=0.8855

[CONFIG MATRIX] bio_drop_feature_prot_LVD_Cosine | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 326.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train1Val_Test | MCC=0.8252 | F1=0.8709 | AUROC=0.9763 | AUPRC=0.9428
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train1Val_ClinVarHQ | MCC=0.8696 | F1=0.9293 | AUROC=0.9884 | AUPRC=0.9888
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train1Val_UniProt | MCC=0.4944 | F1=0.7472 | AUROC=0.8110 | AUPRC=0.7945
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train1Val_ProteinGym | MCC=0.6401 | F1=0.8141 | AUROC=0.9106 | AUPRC=0.8820
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 306.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train2Val_Test | MCC=0.8351 | F1=0.8788 | AUROC=0.9753 | AUPRC=0.9429
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train2Val_ClinVarHQ | MCC=0.8680 | F1=0.9302 | AUROC=0.9872 | AUPRC=0.9878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train2Val_UniProt | MCC=0.4917 | F1=0.7491 | AUROC=0.8064 | AUPRC=0.7893
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train2Val_ProteinGym | MCC=0.6476 | F1=0.8178 | AUROC=0.9102 | AUPRC=0.8852
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 175.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train3Val_Test | MCC=0.8229 | F1=0.8703 | AUROC=0.9716 | AUPRC=0.9369
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train3Val_ClinVarHQ | MCC=0.8882 | F1=0.9405 | AUROC=0.9892 | AUPRC=0.9884
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train3Val_UniProt | MCC=0.4859 | F1=0.7472 | AUROC=0.7979 | AUPRC=0.7880
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_drop_feature_prot_LVD_Cosine_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative | test=Train3Val_ProteinGym | MCC=0.6346 | F1=0.8117 | AUROC=0.9068 | AUPRC=0.8800
[DONE] 28 individual-feature ablation | metrics=D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011/global_leaderboard_metrics.csv | metric_rows=528 | fit_profile=D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011/global_leaderboard_fit_profiling.csv | fit_rows=132

================================================================================
[STAGE] pooling ablation | configs=1
================================================================================
[PREFLIGHT PASS] 1 configurations across 12 train/test combinations.

[CONFIG MATRIX] bio_core_dna_prot_spliceai_geom | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center', 'cls', 'mean'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 343.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8005 | F1=0.8545 | AUROC=0.9667 | AUPRC=0.9194
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8612 | F1=0.9247 | AUROC=0.9850 | AUPRC=0.9858
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4629 | F1=0.7324 | AUROC=0.7887 | AUPRC=0.7622
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6121 | F1=0.8013 | AUROC=0.9056 | AUPRC=0.8753
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 385.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.7926 | F1=0.8482 | AUROC=0.9634 | AUPRC=0.9176
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8497 | F1=0.9158 | AUROC=0.9823 | AUPRC=0.9833
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4404 | F1=0.7214 | AUROC=0.7776 | AUPRC=0.7515
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6147 | F1=0.8024 | AUROC=0.8963 | AUPRC=0.8674
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 168.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7720 | F1=0.8348 | AUROC=0.9593 | AUPRC=0.9063
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8512 | F1=0.9179 | AUROC=0.9838 | AUPRC=0.9851
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4380 | F1=0.7245 | AUROC=0.7716 | AUPRC=0.7454
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.5448 | F1=0.7703 | AUROC=0.8802 | AUPRC=0.8454
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 312.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8279 | F1=0.8742 | AUROC=0.9731 | AUPRC=0.9348
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8802 | F1=0.9357 | AUROC=0.9878 | AUPRC=0.9878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4875 | F1=0.7485 | AUROC=0.8043 | AUPRC=0.7781
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6432 | F1=0.8160 | AUROC=0.9078 | AUPRC=0.8784
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 372.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8243 | F1=0.8706 | AUROC=0.9712 | AUPRC=0.9331
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8784 | F1=0.9337 | AUROC=0.9875 | AUPRC=0.9885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4840 | F1=0.7440 | AUROC=0.7944 | AUPRC=0.7749
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6336 | F1=0.8110 | AUROC=0.9045 | AUPRC=0.8799
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 187.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7962 | F1=0.8501 | AUROC=0.9669 | AUPRC=0.9237
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8440 | F1=0.9127 | AUROC=0.9872 | AUPRC=0.9874
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4419 | F1=0.7211 | AUROC=0.7787 | AUPRC=0.7542
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6164 | F1=0.8027 | AUROC=0.8984 | AUPRC=0.8616
[DONE] pooling ablation | metrics=D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011/global_leaderboard_metrics.csv | metric_rows=552 | fit_profile=D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011/global_leaderboard_fit_profiling.csv | fit_rows=138

================================================================================
[STAGE] sequence-length ablation | configs=20
================================================================================
[PREFLIGHT PASS] 20 configurations across 12 train/test combinations.

[CONFIG MATRIX] sequence_pair_dna_301_protein_31 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 380.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.7881 | F1=0.8462 | AUROC=0.9672 | AUPRC=0.9237
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8352 | F1=0.9113 | AUROC=0.9817 | AUPRC=0.9831
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4495 | F1=0.7267 | AUROC=0.7845 | AUPRC=0.7664
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.5855 | F1=0.7888 | AUROC=0.8993 | AUPRC=0.8819
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 269.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.7898 | F1=0.8453 | AUROC=0.9660 | AUPRC=0.9230
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8369 | F1=0.9074 | AUROC=0.9848 | AUPRC=0.9855
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4196 | F1=0.7025 | AUROC=0.7789 | AUPRC=0.7596
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6086 | F1=0.7989 | AUROC=0.8973 | AUPRC=0.8782
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 193.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7715 | F1=0.8333 | AUROC=0.9613 | AUPRC=0.9098
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8376 | F1=0.9071 | AUROC=0.9853 | AUPRC=0.9863
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4179 | F1=0.7061 | AUROC=0.7695 | AUPRC=0.7650
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_301_protein_31_nt_v1_500m_dna_301_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.5877 | F1=0.7894 | AUROC=0.8924 | AUPRC=0.8764

[CONFIG MATRIX] sequence_pair_dna_301_protein_101 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 362.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8207 | F1=0.8681 | AUROC=0.9729 | AUPRC=0.9370
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8653 | F1=0.9256 | AUROC=0.9868 | AUPRC=0.9875
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4794 | F1=0.7373 | AUROC=0.8009 | AUPRC=0.7729
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6367 | F1=0.8124 | AUROC=0.9142 | AUPRC=0.9000
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 336.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8186 | F1=0.8666 | AUROC=0.9709 | AUPRC=0.9363
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8486 | F1=0.9163 | AUROC=0.9845 | AUPRC=0.9842
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4689 | F1=0.7318 | AUROC=0.7903 | AUPRC=0.7708
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6335 | F1=0.8108 | AUROC=0.9067 | AUPRC=0.8880
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 186.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8046 | F1=0.8566 | AUROC=0.9689 | AUPRC=0.9309
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8466 | F1=0.9144 | AUROC=0.9862 | AUPRC=0.9859
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4569 | F1=0.7290 | AUROC=0.7885 | AUPRC=0.7663
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_301_protein_101_nt_v1_500m_dna_301_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6264 | F1=0.8073 | AUROC=0.9039 | AUPRC=0.8845

[CONFIG MATRIX] sequence_pair_dna_301_protein_201 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 318.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8242 | F1=0.8713 | AUROC=0.9736 | AUPRC=0.9411
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8691 | F1=0.9295 | AUROC=0.9880 | AUPRC=0.9884
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4946 | F1=0.7494 | AUROC=0.8068 | AUPRC=0.7909
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6445 | F1=0.8165 | AUROC=0.9135 | AUPRC=0.8973
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 333.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8337 | F1=0.8766 | AUROC=0.9732 | AUPRC=0.9404
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8481 | F1=0.9165 | AUROC=0.9871 | AUPRC=0.9872
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4974 | F1=0.7456 | AUROC=0.7979 | AUPRC=0.7784
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6602 | F1=0.8234 | AUROC=0.9118 | AUPRC=0.8943
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 155.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8119 | F1=0.8592 | AUROC=0.9708 | AUPRC=0.9355
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8466 | F1=0.9144 | AUROC=0.9876 | AUPRC=0.9862
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4784 | F1=0.7311 | AUROC=0.7904 | AUPRC=0.7690
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_301_protein_201_nt_v1_500m_dna_301_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6472 | F1=0.8159 | AUROC=0.9043 | AUPRC=0.8853

[CONFIG MATRIX] sequence_pair_dna_301_protein_501 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 343.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8327 | F1=0.8771 | AUROC=0.9762 | AUPRC=0.9441
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8771 | F1=0.9343 | AUROC=0.9893 | AUPRC=0.9895
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5036 | F1=0.7543 | AUROC=0.8104 | AUPRC=0.7870
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6500 | F1=0.8192 | AUROC=0.9169 | AUPRC=0.8957
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 363.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8268 | F1=0.8724 | AUROC=0.9743 | AUPRC=0.9413
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8467 | F1=0.9173 | AUROC=0.9877 | AUPRC=0.9881
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.5004 | F1=0.7494 | AUROC=0.8022 | AUPRC=0.7841
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6790 | F1=0.8328 | AUROC=0.9164 | AUPRC=0.8994
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 178.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8244 | F1=0.8720 | AUROC=0.9717 | AUPRC=0.9379
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8912 | F1=0.9419 | AUROC=0.9864 | AUPRC=0.9863
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4854 | F1=0.7504 | AUROC=0.7946 | AUPRC=0.7799
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_301_protein_501_nt_v1_500m_dna_301_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6273 | F1=0.8084 | AUROC=0.9068 | AUPRC=0.8850

[CONFIG MATRIX] sequence_pair_dna_301_protein_1001 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 261.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8352 | F1=0.8780 | AUROC=0.9765 | AUPRC=0.9455
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8893 | F1=0.9399 | AUROC=0.9894 | AUPRC=0.9898
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4959 | F1=0.7474 | AUROC=0.8069 | AUPRC=0.7847
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6550 | F1=0.8212 | AUROC=0.9167 | AUPRC=0.8968
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 349.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8317 | F1=0.8767 | AUROC=0.9748 | AUPRC=0.9431
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8903 | F1=0.9424 | AUROC=0.9896 | AUPRC=0.9896
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4828 | F1=0.7450 | AUROC=0.8014 | AUPRC=0.7735
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6537 | F1=0.8209 | AUROC=0.9142 | AUPRC=0.8939
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 188.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8198 | F1=0.8684 | AUROC=0.9722 | AUPRC=0.9378
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8882 | F1=0.9405 | AUROC=0.9910 | AUPRC=0.9911
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4845 | F1=0.7471 | AUROC=0.7966 | AUPRC=0.7754
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_301_protein_1001_nt_v1_500m_dna_301_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6179 | F1=0.8037 | AUROC=0.9059 | AUPRC=0.8858

[CONFIG MATRIX] sequence_pair_dna_601_protein_31 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 355.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.7936 | F1=0.8497 | AUROC=0.9669 | AUPRC=0.9237
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8326 | F1=0.9096 | AUROC=0.9843 | AUPRC=0.9854
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4569 | F1=0.7290 | AUROC=0.7871 | AUPRC=0.7699
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.5971 | F1=0.7943 | AUROC=0.8990 | AUPRC=0.8802
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 333.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.7906 | F1=0.8478 | AUROC=0.9654 | AUPRC=0.9212
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8481 | F1=0.9165 | AUROC=0.9839 | AUPRC=0.9849
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4315 | F1=0.7178 | AUROC=0.7776 | AUPRC=0.7637
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.5877 | F1=0.7898 | AUROC=0.8974 | AUPRC=0.8798
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 153.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7701 | F1=0.8285 | AUROC=0.9619 | AUPRC=0.9127
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8182 | F1=0.8931 | AUROC=0.9842 | AUPRC=0.9851
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4116 | F1=0.6913 | AUROC=0.7727 | AUPRC=0.7573
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_601_protein_31_nt_v1_500m_dna_601_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.5967 | F1=0.7921 | AUROC=0.8892 | AUPRC=0.8671

[CONFIG MATRIX] sequence_pair_dna_601_protein_101 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 334.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8175 | F1=0.8655 | AUROC=0.9731 | AUPRC=0.9408
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8357 | F1=0.9080 | AUROC=0.9859 | AUPRC=0.9866
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4750 | F1=0.7332 | AUROC=0.8026 | AUPRC=0.7830
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6296 | F1=0.8087 | AUROC=0.9140 | AUPRC=0.8980
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 346.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8174 | F1=0.8650 | AUROC=0.9719 | AUPRC=0.9383
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8382 | F1=0.9096 | AUROC=0.9840 | AUPRC=0.9847
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4600 | F1=0.7248 | AUROC=0.7944 | AUPRC=0.7760
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6405 | F1=0.8141 | AUROC=0.9064 | AUPRC=0.8834
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 170.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8066 | F1=0.8551 | AUROC=0.9691 | AUPRC=0.9308
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8383 | F1=0.9068 | AUROC=0.9873 | AUPRC=0.9868
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4759 | F1=0.7270 | AUROC=0.7876 | AUPRC=0.7623
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_601_protein_101_nt_v1_500m_dna_601_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6439 | F1=0.8140 | AUROC=0.9000 | AUPRC=0.8719

[CONFIG MATRIX] sequence_pair_dna_601_protein_201 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 360.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8264 | F1=0.8738 | AUROC=0.9749 | AUPRC=0.9444
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8819 | F1=0.9379 | AUROC=0.9890 | AUPRC=0.9892
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5060 | F1=0.7591 | AUROC=0.8122 | AUPRC=0.7913
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6278 | F1=0.8087 | AUROC=0.9132 | AUPRC=0.8925
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 333.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8253 | F1=0.8715 | AUROC=0.9728 | AUPRC=0.9401
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8714 | F1=0.9313 | AUROC=0.9880 | AUPRC=0.9885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4794 | F1=0.7397 | AUROC=0.8007 | AUPRC=0.7761
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6476 | F1=0.8178 | AUROC=0.9098 | AUPRC=0.8907
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 191.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8097 | F1=0.8600 | AUROC=0.9696 | AUPRC=0.9324
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8718 | F1=0.9311 | AUROC=0.9881 | AUPRC=0.9874
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4704 | F1=0.7344 | AUROC=0.7921 | AUPRC=0.7671
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_601_protein_201_nt_v1_500m_dna_601_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6323 | F1=0.8100 | AUROC=0.9031 | AUPRC=0.8799

[CONFIG MATRIX] sequence_pair_dna_601_protein_501 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 319.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8309 | F1=0.8753 | AUROC=0.9757 | AUPRC=0.9449
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8691 | F1=0.9295 | AUROC=0.9887 | AUPRC=0.9891
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4960 | F1=0.7489 | AUROC=0.8096 | AUPRC=0.7912
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6480 | F1=0.8181 | AUROC=0.9137 | AUPRC=0.8914
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 318.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8296 | F1=0.8748 | AUROC=0.9748 | AUPRC=0.9419
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8604 | F1=0.9251 | AUROC=0.9884 | AUPRC=0.9889
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4931 | F1=0.7485 | AUROC=0.8054 | AUPRC=0.7833
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6577 | F1=0.8226 | AUROC=0.9145 | AUPRC=0.8962
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 218.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8179 | F1=0.8668 | AUROC=0.9713 | AUPRC=0.9359
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8825 | F1=0.9375 | AUROC=0.9891 | AUPRC=0.9893
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4813 | F1=0.7445 | AUROC=0.7974 | AUPRC=0.7898
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_601_protein_501_nt_v1_500m_dna_601_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6276 | F1=0.8085 | AUROC=0.9081 | AUPRC=0.8883

[CONFIG MATRIX] sequence_pair_dna_601_protein_1001 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 307.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8309 | F1=0.8754 | AUROC=0.9763 | AUPRC=0.9456
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8684 | F1=0.9300 | AUROC=0.9889 | AUPRC=0.9889
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4899 | F1=0.7440 | AUROC=0.8081 | AUPRC=0.7873
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6628 | F1=0.8251 | AUROC=0.9157 | AUPRC=0.8853
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 371.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8337 | F1=0.8784 | AUROC=0.9747 | AUPRC=0.9425
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8828 | F1=0.9373 | AUROC=0.9898 | AUPRC=0.9898
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4842 | F1=0.7452 | AUROC=0.8026 | AUPRC=0.7816
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6486 | F1=0.8185 | AUROC=0.9113 | AUPRC=0.8890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 185.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8277 | F1=0.8731 | AUROC=0.9731 | AUPRC=0.9410
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8806 | F1=0.9355 | AUROC=0.9901 | AUPRC=0.9900
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4749 | F1=0.7384 | AUROC=0.7937 | AUPRC=0.7705
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_601_protein_1001_nt_v1_500m_dna_601_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6464 | F1=0.8169 | AUROC=0.9073 | AUPRC=0.8832

[CONFIG MATRIX] sequence_pair_dna_1001_protein_31 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 368.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.7941 | F1=0.8495 | AUROC=0.9680 | AUPRC=0.9246
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8410 | F1=0.9143 | AUROC=0.9839 | AUPRC=0.9846
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4614 | F1=0.7286 | AUROC=0.7906 | AUPRC=0.7758
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6036 | F1=0.7971 | AUROC=0.8955 | AUPRC=0.8730
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 383.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.7930 | F1=0.8470 | AUROC=0.9656 | AUPRC=0.9202
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8529 | F1=0.9172 | AUROC=0.9846 | AUPRC=0.9853
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4094 | F1=0.6946 | AUROC=0.7749 | AUPRC=0.7629
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6167 | F1=0.8027 | AUROC=0.8916 | AUPRC=0.8695
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 207.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7703 | F1=0.8315 | AUROC=0.9616 | AUPRC=0.9114
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8288 | F1=0.9055 | AUROC=0.9841 | AUPRC=0.9845
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4253 | F1=0.7105 | AUROC=0.7753 | AUPRC=0.7664
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_1001_protein_31_nt_v1_500m_dna_1001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.5842 | F1=0.7879 | AUROC=0.8951 | AUPRC=0.8777

[CONFIG MATRIX] sequence_pair_dna_1001_protein_101 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 375.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8222 | F1=0.8704 | AUROC=0.9729 | AUPRC=0.9387
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8643 | F1=0.9261 | AUROC=0.9864 | AUPRC=0.9867
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5049 | F1=0.7526 | AUROC=0.8072 | AUPRC=0.7826
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6131 | F1=0.8016 | AUROC=0.9071 | AUPRC=0.8827
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 318.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8201 | F1=0.8690 | AUROC=0.9710 | AUPRC=0.9359
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8493 | F1=0.9189 | AUROC=0.9843 | AUPRC=0.9846
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4620 | F1=0.7358 | AUROC=0.7954 | AUPRC=0.7713
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6164 | F1=0.8032 | AUROC=0.9045 | AUPRC=0.8802
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 157.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8068 | F1=0.8579 | AUROC=0.9691 | AUPRC=0.9307
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8371 | F1=0.9102 | AUROC=0.9868 | AUPRC=0.9863
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4599 | F1=0.7281 | AUROC=0.7916 | AUPRC=0.7673
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_1001_protein_101_nt_v1_500m_dna_1001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6355 | F1=0.8119 | AUROC=0.9006 | AUPRC=0.8757

[CONFIG MATRIX] sequence_pair_dna_1001_protein_201 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 352.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8263 | F1=0.8715 | AUROC=0.9752 | AUPRC=0.9434
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8586 | F1=0.9231 | AUROC=0.9892 | AUPRC=0.9892
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5109 | F1=0.7519 | AUROC=0.8088 | AUPRC=0.7928
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6515 | F1=0.8194 | AUROC=0.9087 | AUPRC=0.8838
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 324.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8298 | F1=0.8754 | AUROC=0.9728 | AUPRC=0.9410
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8680 | F1=0.9302 | AUROC=0.9875 | AUPRC=0.9879
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4901 | F1=0.7474 | AUROC=0.8025 | AUPRC=0.7795
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6300 | F1=0.8096 | AUROC=0.9072 | AUPRC=0.8779
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 205.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8151 | F1=0.8635 | AUROC=0.9711 | AUPRC=0.9345
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8806 | F1=0.9355 | AUROC=0.9876 | AUPRC=0.9876
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4929 | F1=0.7451 | AUROC=0.7972 | AUPRC=0.7800
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_1001_protein_201_nt_v1_500m_dna_1001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6351 | F1=0.8110 | AUROC=0.9031 | AUPRC=0.8805

[CONFIG MATRIX] bio_core_dna_prot_spliceai_geom | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1

[CONFIG MATRIX] sequence_pair_dna_1001_protein_1001 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 271.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8404 | F1=0.8830 | AUROC=0.9769 | AUPRC=0.9458
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8882 | F1=0.9405 | AUROC=0.9901 | AUPRC=0.9903
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4901 | F1=0.7478 | AUROC=0.8099 | AUPRC=0.7909
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6475 | F1=0.8179 | AUROC=0.9134 | AUPRC=0.8928
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 334.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8342 | F1=0.8782 | AUROC=0.9753 | AUPRC=0.9452
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8711 | F1=0.9315 | AUROC=0.9887 | AUPRC=0.9889
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4780 | F1=0.7407 | AUROC=0.7997 | AUPRC=0.7829
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6610 | F1=0.8245 | AUROC=0.9109 | AUPRC=0.8892
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 233.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8218 | F1=0.8695 | AUROC=0.9735 | AUPRC=0.9388
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.9026 | F1=0.9478 | AUROC=0.9909 | AUPRC=0.9910
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4946 | F1=0.7494 | AUROC=0.7983 | AUPRC=0.7799
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_1001_protein_1001_nt_v1_500m_dna_1001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6498 | F1=0.8190 | AUROC=0.9082 | AUPRC=0.8886

[CONFIG MATRIX] sequence_pair_dna_2001_protein_31 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 433.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.7993 | F1=0.8539 | AUROC=0.9667 | AUPRC=0.9236
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8493 | F1=0.9189 | AUROC=0.9837 | AUPRC=0.9851
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4556 | F1=0.7301 | AUROC=0.7900 | AUPRC=0.7763
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.5943 | F1=0.7930 | AUROC=0.8961 | AUPRC=0.8796
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 360.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.7881 | F1=0.8467 | AUROC=0.9661 | AUPRC=0.9206
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8524 | F1=0.9203 | AUROC=0.9825 | AUPRC=0.9838
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4200 | F1=0.7161 | AUROC=0.7808 | AUPRC=0.7735
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.5849 | F1=0.7887 | AUROC=0.8935 | AUPRC=0.8744
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 193.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7745 | F1=0.8360 | AUROC=0.9625 | AUPRC=0.9117
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8528 | F1=0.9201 | AUROC=0.9854 | AUPRC=0.9860
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4179 | F1=0.7091 | AUROC=0.7720 | AUPRC=0.7577
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_2001_protein_31_nt_v1_500m_dna_2001_esm2_650m_prot_31_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.5755 | F1=0.7836 | AUROC=0.8903 | AUPRC=0.8733

[CONFIG MATRIX] sequence_pair_dna_2001_protein_101 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 370.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8209 | F1=0.8688 | AUROC=0.9732 | AUPRC=0.9383
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8643 | F1=0.9261 | AUROC=0.9866 | AUPRC=0.9868
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4914 | F1=0.7464 | AUROC=0.8047 | AUPRC=0.7866
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6312 | F1=0.8101 | AUROC=0.9060 | AUPRC=0.8845
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 303.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8144 | F1=0.8631 | AUROC=0.9718 | AUPRC=0.9360
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8491 | F1=0.9160 | AUROC=0.9854 | AUPRC=0.9854
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4644 | F1=0.7281 | AUROC=0.7950 | AUPRC=0.7770
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6148 | F1=0.8019 | AUROC=0.9025 | AUPRC=0.8751
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 211.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8068 | F1=0.8585 | AUROC=0.9691 | AUPRC=0.9295
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8419 | F1=0.9138 | AUROC=0.9855 | AUPRC=0.9857
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4555 | F1=0.7293 | AUROC=0.7878 | AUPRC=0.7657
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_2001_protein_101_nt_v1_500m_dna_2001_esm2_650m_prot_101_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6161 | F1=0.8029 | AUROC=0.8975 | AUPRC=0.8715

[CONFIG MATRIX] sequence_pair_dna_2001_protein_201 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 366.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8276 | F1=0.8743 | AUROC=0.9743 | AUPRC=0.9414
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8849 | F1=0.9393 | AUROC=0.9889 | AUPRC=0.9894
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5101 | F1=0.7597 | AUROC=0.8086 | AUPRC=0.7930
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6288 | F1=0.8092 | AUROC=0.9083 | AUPRC=0.8845
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 349.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8255 | F1=0.8708 | AUROC=0.9734 | AUPRC=0.9387
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8570 | F1=0.9240 | AUROC=0.9872 | AUPRC=0.9868
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4854 | F1=0.7407 | AUROC=0.8032 | AUPRC=0.7876
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6468 | F1=0.8173 | AUROC=0.9074 | AUPRC=0.8821
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 193.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8180 | F1=0.8678 | AUROC=0.9704 | AUPRC=0.9328
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8735 | F1=0.9333 | AUROC=0.9878 | AUPRC=0.9866
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4806 | F1=0.7473 | AUROC=0.7929 | AUPRC=0.7747
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_2001_protein_201_nt_v1_500m_dna_2001_esm2_650m_prot_201_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6029 | F1=0.7968 | AUROC=0.9005 | AUPRC=0.8768

[CONFIG MATRIX] sequence_pair_dna_2001_protein_501 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 294.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8345 | F1=0.8786 | AUROC=0.9759 | AUPRC=0.9431
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8916 | F1=0.9417 | AUROC=0.9892 | AUPRC=0.9894
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5054 | F1=0.7566 | AUROC=0.8105 | AUPRC=0.7926
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6408 | F1=0.8149 | AUROC=0.9126 | AUPRC=0.8866
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 351.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8299 | F1=0.8744 | AUROC=0.9759 | AUPRC=0.9416
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8600 | F1=0.9254 | AUROC=0.9888 | AUPRC=0.9887
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4794 | F1=0.7389 | AUROC=0.8061 | AUPRC=0.7895
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6393 | F1=0.8136 | AUROC=0.9105 | AUPRC=0.8853
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 216.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8244 | F1=0.8712 | AUROC=0.9714 | AUPRC=0.9336
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8859 | F1=0.9387 | AUROC=0.9878 | AUPRC=0.9877
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4885 | F1=0.7461 | AUROC=0.7960 | AUPRC=0.7835
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_2001_protein_501_nt_v1_500m_dna_2001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6362 | F1=0.8125 | AUROC=0.9030 | AUPRC=0.8829

[CONFIG MATRIX] sequence_pair_dna_2001_protein_1001 | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 395.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8380 | F1=0.8813 | AUROC=0.9772 | AUPRC=0.9447
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8906 | F1=0.9422 | AUROC=0.9903 | AUPRC=0.9904
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5086 | F1=0.7592 | AUROC=0.8110 | AUPRC=0.7893
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6472 | F1=0.8179 | AUROC=0.9116 | AUPRC=0.8806
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 291.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8371 | F1=0.8809 | AUROC=0.9751 | AUPRC=0.9441
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8846 | F1=0.9394 | AUROC=0.9885 | AUPRC=0.9888
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4907 | F1=0.7507 | AUROC=0.8021 | AUPRC=0.7829
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6539 | F1=0.8211 | AUROC=0.9113 | AUPRC=0.8828
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 186.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8302 | F1=0.8755 | AUROC=0.9729 | AUPRC=0.9361
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8882 | F1=0.9405 | AUROC=0.9913 | AUPRC=0.9914
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4810 | F1=0.7426 | AUROC=0.7973 | AUPRC=0.7795
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_sequence_pair_dna_2001_protein_1001_nt_v1_500m_dna_2001_esm2_650m_prot_1001_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6329 | F1=0.8107 | AUROC=0.9022 | AUPRC=0.8809
[DONE] sequence-length ablation | metrics=D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011/global_leaderboard_metrics.csv | metric_rows=780 | fit_profile=D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011/global_leaderboard_fit_profiling.csv | fit_rows=195

================================================================================
[STAGE] DNA/protein modality ablation | configs=21
================================================================================
[PREFLIGHT PASS] 21 configurations across 12 train/test combinations.

[CONFIG MATRIX] bio_core_dna_prot_spliceai_geom | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1

[CONFIG MATRIX] modalities_dna_only_bio_splice_geom | modalities=['dna', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 381.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.7874 | F1=0.8454 | AUROC=0.9643 | AUPRC=0.9143
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8524 | F1=0.9203 | AUROC=0.9839 | AUPRC=0.9847
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4375 | F1=0.7204 | AUROC=0.7725 | AUPRC=0.7491
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.5949 | F1=0.7933 | AUROC=0.8879 | AUPRC=0.8491
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 311.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.7679 | F1=0.8323 | AUROC=0.9600 | AUPRC=0.9083
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8506 | F1=0.9215 | AUROC=0.9827 | AUPRC=0.9841
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4415 | F1=0.7283 | AUROC=0.7716 | AUPRC=0.7502
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.5904 | F1=0.7912 | AUROC=0.8881 | AUPRC=0.8487
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 230.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7650 | F1=0.8299 | AUROC=0.9580 | AUPRC=0.9038
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8423 | F1=0.9135 | AUROC=0.9852 | AUPRC=0.9856
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4187 | F1=0.7160 | AUROC=0.7680 | AUPRC=0.7467
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_dna_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.5782 | F1=0.7855 | AUROC=0.8893 | AUPRC=0.8597

[CONFIG MATRIX] modalities_protein_only_bio_splice_geom | modalities=['prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 346.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8332 | F1=0.8768 | AUROC=0.9762 | AUPRC=0.9463
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8810 | F1=0.9353 | AUROC=0.9894 | AUPRC=0.9900
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4916 | F1=0.7480 | AUROC=0.8109 | AUPRC=0.7870
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6477 | F1=0.8180 | AUROC=0.9166 | AUPRC=0.8897
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 296.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8381 | F1=0.8823 | AUROC=0.9753 | AUPRC=0.9436
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8898 | F1=0.9427 | AUROC=0.9894 | AUPRC=0.9896
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.5155 | F1=0.7649 | AUROC=0.8071 | AUPRC=0.7849
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6656 | F1=0.8268 | AUROC=0.9174 | AUPRC=0.8982
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 197.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8176 | F1=0.8664 | AUROC=0.9717 | AUPRC=0.9358
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8768 | F1=0.9345 | AUROC=0.9889 | AUPRC=0.9893
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4784 | F1=0.7434 | AUROC=0.7987 | AUPRC=0.7810
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_protein_only_bio_splice_geom_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6352 | F1=0.8118 | AUROC=0.9088 | AUPRC=0.8905

[CONFIG MATRIX] modalities_bio_splice_geom_only | modalities=['bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 412.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.7927 | F1=0.8483 | AUROC=0.9644 | AUPRC=0.9180
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8543 | F1=0.9193 | AUROC=0.9851 | AUPRC=0.9863
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4569 | F1=0.7245 | AUROC=0.7755 | AUPRC=0.7379
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6185 | F1=0.8042 | AUROC=0.8973 | AUPRC=0.8713
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 320.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.7870 | F1=0.8452 | AUROC=0.9632 | AUPRC=0.9141
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8687 | F1=0.9297 | AUROC=0.9865 | AUPRC=0.9860
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4390 | F1=0.7213 | AUROC=0.7724 | AUPRC=0.7377
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6178 | F1=0.8039 | AUROC=0.9001 | AUPRC=0.8808
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 179.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.7798 | F1=0.8387 | AUROC=0.9604 | AUPRC=0.9079
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8440 | F1=0.9127 | AUROC=0.9854 | AUPRC=0.9849
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4197 | F1=0.7016 | AUROC=0.7649 | AUPRC=0.7431
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai', 'geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_bio_splice_geom_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6133 | F1=0.8016 | AUROC=0.8926 | AUPRC=0.8753

[CONFIG MATRIX] modalities_dna_only | modalities=['dna'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 499.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.1592 | F1=0.4104 | AUROC=0.6287 | AUPRC=0.3722
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.1973 | F1=0.5472 | AUROC=0.6358 | AUPRC=0.5976
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.0413 | F1=0.4662 | AUROC=0.5428 | AUPRC=0.5348
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.1575 | F1=0.5093 | AUROC=0.6048 | AUPRC=0.5511
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 499.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_Test | MCC=0.1501 | F1=0.4177 | AUROC=0.6124 | AUPRC=0.3518
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ClinVarHQ | MCC=0.1492 | F1=0.5463 | AUROC=0.6115 | AUPRC=0.5859
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_UniProt | MCC=0.0669 | F1=0.4992 | AUROC=0.5469 | AUPRC=0.5408
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ProteinGym | MCC=0.1641 | F1=0.5298 | AUROC=0.6105 | AUPRC=0.5553
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 77.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.0828 | F1=0.2549 | AUROC=0.5690 | AUPRC=0.3243
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.1079 | F1=0.3277 | AUROC=0.6102 | AUPRC=0.5782
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.0255 | F1=0.2707 | AUROC=0.5297 | AUPRC=0.5150
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_dna_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.0403 | F1=0.2634 | AUROC=0.5589 | AUPRC=0.5025

[CONFIG MATRIX] modalities_protein_only | modalities=['prot'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 499.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.6760 | F1=0.7552 | AUROC=0.9160 | AUPRC=0.8363
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.6660 | F1=0.8178 | AUROC=0.9113 | AUPRC=0.8943
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.4724 | F1=0.7205 | AUROC=0.7971 | AUPRC=0.7809
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5774 | F1=0.7471 | AUROC=0.8664 | AUPRC=0.8403
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 499.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_Test | MCC=0.6585 | F1=0.7331 | AUROC=0.9122 | AUPRC=0.8292
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ClinVarHQ | MCC=0.6474 | F1=0.7962 | AUROC=0.9091 | AUPRC=0.8869
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_UniProt | MCC=0.4624 | F1=0.6998 | AUROC=0.7986 | AUPRC=0.7835
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ProteinGym | MCC=0.5552 | F1=0.7214 | AUROC=0.8644 | AUPRC=0.8406
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 199.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6512 | F1=0.7270 | AUROC=0.9014 | AUPRC=0.8132
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6209 | F1=0.7822 | AUROC=0.8921 | AUPRC=0.8707
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4721 | F1=0.7037 | AUROC=0.7928 | AUPRC=0.7897
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5743 | F1=0.7259 | AUROC=0.8589 | AUPRC=0.8370

[CONFIG MATRIX] modalities_dna_protein_only | modalities=['dna', 'prot'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 498.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.6711 | F1=0.7505 | AUROC=0.9139 | AUPRC=0.8324
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.6623 | F1=0.8124 | AUROC=0.9066 | AUPRC=0.8863
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.4547 | F1=0.7096 | AUROC=0.7942 | AUPRC=0.7735
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5671 | F1=0.7381 | AUROC=0.8621 | AUPRC=0.8349
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 499.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_Test | MCC=0.6749 | F1=0.7539 | AUROC=0.9134 | AUPRC=0.8315
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ClinVarHQ | MCC=0.6828 | F1=0.8275 | AUROC=0.9129 | AUPRC=0.8927
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_UniProt | MCC=0.4577 | F1=0.7112 | AUROC=0.7951 | AUPRC=0.7822
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train2Val_ProteinGym | MCC=0.5717 | F1=0.7439 | AUROC=0.8621 | AUPRC=0.8351
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 253.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6475 | F1=0.7255 | AUROC=0.9015 | AUPRC=0.8163
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6164 | F1=0.7823 | AUROC=0.8953 | AUPRC=0.8746
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4763 | F1=0.7034 | AUROC=0.7940 | AUPRC=0.7860
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_dna_protein_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5591 | F1=0.7182 | AUROC=0.8616 | AUPRC=0.8360

[CONFIG MATRIX] modalities_bio_only | modalities=['bio_core'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 337.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.7219 | F1=0.7977 | AUROC=0.9438 | AUPRC=0.8780
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.7756 | F1=0.8723 | AUROC=0.9684 | AUPRC=0.9705
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.3597 | F1=0.6698 | AUROC=0.7497 | AUPRC=0.7266
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5309 | F1=0.7637 | AUROC=0.8752 | AUPRC=0.8565
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train2Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 130.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train2Val_Test | MCC=0.7139 | F1=0.7919 | AUROC=0.9432 | AUPRC=0.8748
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train2Val_ClinVarHQ | MCC=0.7727 | F1=0.8675 | AUROC=0.9720 | AUPRC=0.9734
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train2Val_UniProt | MCC=0.3524 | F1=0.6641 | AUROC=0.7376 | AUPRC=0.7169
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train2Val_ProteinGym | MCC=0.5024 | F1=0.7506 | AUROC=0.8651 | AUPRC=0.8466
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 87.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7099 | F1=0.7914 | AUROC=0.9407 | AUPRC=0.8670
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.7915 | F1=0.8824 | AUROC=0.9743 | AUPRC=0.9754
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3254 | F1=0.6696 | AUROC=0.7212 | AUPRC=0.6956
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_bio_only_None_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4818 | F1=0.7430 | AUROC=0.8534 | AUPRC=0.8224

[CONFIG MATRIX] modalities_spliceai_only | modalities=['spliceai'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 497.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.0620 | F1=0.3797 | AUROC=0.5456 | AUPRC=0.3088
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.1406 | F1=0.5623 | AUROC=0.5902 | AUPRC=0.5690
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.0682 | F1=0.5263 | AUROC=0.5374 | AUPRC=0.5274
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.0842 | F1=0.5026 | AUROC=0.5551 | AUPRC=0.5026
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train2Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 71.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train2Val_Test | MCC=0.0532 | F1=0.3621 | AUROC=0.5427 | AUPRC=0.3051
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train2Val_ClinVarHQ | MCC=0.1063 | F1=0.5213 | AUROC=0.5653 | AUPRC=0.5602
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train2Val_UniProt | MCC=0.0516 | F1=0.5008 | AUROC=0.5355 | AUPRC=0.5382
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train2Val_ProteinGym | MCC=0.0994 | F1=0.4842 | AUROC=0.5541 | AUPRC=0.5027
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 21.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.0578 | F1=0.3465 | AUROC=0.5393 | AUPRC=0.3108
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.0837 | F1=0.4856 | AUROC=0.5564 | AUPRC=0.5698
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.0508 | F1=0.4622 | AUROC=0.5338 | AUPRC=0.5356
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['spliceai']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_spliceai_only_None_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.0515 | F1=0.4336 | AUROC=0.5327 | AUPRC=0.4875

[CONFIG MATRIX] modalities_geometry_only | modalities=['geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 499.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.4676 | F1=0.6166 | AUROC=0.8330 | AUPRC=0.6390
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.4547 | F1=0.6930 | AUROC=0.8218 | AUPRC=0.7829
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.2459 | F1=0.6055 | AUROC=0.6899 | AUPRC=0.6618
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.4360 | F1=0.6889 | AUROC=0.8031 | AUPRC=0.7459
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 312.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.4567 | F1=0.6081 | AUROC=0.8271 | AUPRC=0.6138
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.4880 | F1=0.7147 | AUROC=0.8249 | AUPRC=0.7842
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.2765 | F1=0.6164 | AUROC=0.7032 | AUPRC=0.6627
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.4403 | F1=0.6828 | AUROC=0.8060 | AUPRC=0.7430
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 107.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.4565 | F1=0.6174 | AUROC=0.8230 | AUPRC=0.6171
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.4767 | F1=0.7294 | AUROC=0.8200 | AUPRC=0.7770
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.2873 | F1=0.6415 | AUROC=0.7035 | AUPRC=0.6659
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_modalities_geometry_only_nt_v1_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.4633 | F1=0.7083 | AUROC=0.8115 | AUPRC=0.7544

[CONFIG MATRIX] model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 331.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8418 | F1=0.8847 | AUROC=0.9780 | AUPRC=0.9466
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8828 | F1=0.9373 | AUROC=0.9895 | AUPRC=0.9894
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5184 | F1=0.7592 | AUROC=0.8204 | AUPRC=0.8072
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6640 | F1=0.8260 | AUROC=0.9266 | AUPRC=0.9111
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 357.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8388 | F1=0.8822 | AUROC=0.9762 | AUPRC=0.9460
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8759 | F1=0.9351 | AUROC=0.9886 | AUPRC=0.9886
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.5079 | F1=0.7523 | AUROC=0.8133 | AUPRC=0.8050
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6694 | F1=0.8286 | AUROC=0.9198 | AUPRC=0.9033
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 199.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8290 | F1=0.8757 | AUROC=0.9736 | AUPRC=0.9429
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8732 | F1=0.9335 | AUROC=0.9888 | AUPRC=0.9878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4965 | F1=0.7526 | AUROC=0.8064 | AUPRC=0.7945
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6417 | F1=0.8153 | AUROC=0.9215 | AUPRC=0.9070

[CONFIG MATRIX] model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 325.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8176 | F1=0.8683 | AUROC=0.9749 | AUPRC=0.9448
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8778 | F1=0.9376 | AUROC=0.9888 | AUPRC=0.9891
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4990 | F1=0.7636 | AUROC=0.8073 | AUPRC=0.7816
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6226 | F1=0.8059 | AUROC=0.9219 | AUPRC=0.8986
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 272.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8238 | F1=0.8727 | AUROC=0.9732 | AUPRC=0.9423
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8702 | F1=0.9322 | AUROC=0.9878 | AUPRC=0.9887
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4974 | F1=0.7591 | AUROC=0.8029 | AUPRC=0.7825
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6240 | F1=0.8067 | AUROC=0.9189 | AUPRC=0.8925
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 228.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8314 | F1=0.8765 | AUROC=0.9718 | AUPRC=0.9366
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8638 | F1=0.9235 | AUROC=0.9894 | AUPRC=0.9900
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4705 | F1=0.7364 | AUROC=0.7905 | AUPRC=0.7765
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom_nt_v1_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6422 | F1=0.8155 | AUROC=0.9159 | AUPRC=0.8962

[CONFIG MATRIX] model_pair_nt_v1_500m_esmc_600m_bio_splice_geom | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 304.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8376 | F1=0.8811 | AUROC=0.9784 | AUPRC=0.9515
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8810 | F1=0.9353 | AUROC=0.9902 | AUPRC=0.9907
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5096 | F1=0.7572 | AUROC=0.8137 | AUPRC=0.7965
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6743 | F1=0.8310 | AUROC=0.9266 | AUPRC=0.9067
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 288.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8306 | F1=0.8752 | AUROC=0.9768 | AUPRC=0.9487
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8658 | F1=0.9254 | AUROC=0.9901 | AUPRC=0.9901
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4884 | F1=0.7430 | AUROC=0.8050 | AUPRC=0.7899
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6871 | F1=0.8370 | AUROC=0.9242 | AUPRC=0.9063
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 179.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8259 | F1=0.8731 | AUROC=0.9736 | AUPRC=0.9433
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8705 | F1=0.9289 | AUROC=0.9894 | AUPRC=0.9897
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4663 | F1=0.7371 | AUROC=0.7958 | AUPRC=0.7919
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v1_500m_esmc_600m_bio_splice_geom_nt_v1_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6475 | F1=0.8179 | AUROC=0.9152 | AUPRC=0.8969

[CONFIG MATRIX] model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 322.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8462 | F1=0.8875 | AUROC=0.9784 | AUPRC=0.9471
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8879 | F1=0.9407 | AUROC=0.9893 | AUPRC=0.9891
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5319 | F1=0.7633 | AUROC=0.8201 | AUPRC=0.8013
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6699 | F1=0.8289 | AUROC=0.9260 | AUPRC=0.9140
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 322.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8410 | F1=0.8838 | AUROC=0.9770 | AUPRC=0.9461
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8882 | F1=0.9405 | AUROC=0.9899 | AUPRC=0.9897
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.5005 | F1=0.7517 | AUROC=0.8165 | AUPRC=0.8087
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6514 | F1=0.8199 | AUROC=0.9228 | AUPRC=0.9105
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 222.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8311 | F1=0.8757 | AUROC=0.9735 | AUPRC=0.9430
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8665 | F1=0.9279 | AUROC=0.9885 | AUPRC=0.9878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.5008 | F1=0.7433 | AUROC=0.8016 | AUPRC=0.7946
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6727 | F1=0.8297 | AUROC=0.9189 | AUPRC=0.9064

[CONFIG MATRIX] model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 317.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8269 | F1=0.8736 | AUROC=0.9746 | AUPRC=0.9409
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8476 | F1=0.9168 | AUROC=0.9876 | AUPRC=0.9878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5004 | F1=0.7506 | AUROC=0.8060 | AUPRC=0.7773
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6699 | F1=0.8289 | AUROC=0.9223 | AUPRC=0.8989
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 260.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8265 | F1=0.8730 | AUROC=0.9737 | AUPRC=0.9418
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8523 | F1=0.9174 | AUROC=0.9873 | AUPRC=0.9883
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4854 | F1=0.7407 | AUROC=0.8001 | AUPRC=0.7791
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6743 | F1=0.8310 | AUROC=0.9199 | AUPRC=0.9025
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 187.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8211 | F1=0.8694 | AUROC=0.9704 | AUPRC=0.9371
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8543 | F1=0.9193 | AUROC=0.9888 | AUPRC=0.9894
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4602 | F1=0.7337 | AUROC=0.7898 | AUPRC=0.7797
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v3_650m_esm1v_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6347 | F1=0.8119 | AUROC=0.9135 | AUPRC=0.8856

[CONFIG MATRIX] model_pair_nt_v3_650m_esm2_650m_bio_splice_geom | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 324.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8352 | F1=0.8793 | AUROC=0.9765 | AUPRC=0.9443
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8798 | F1=0.9359 | AUROC=0.9908 | AUPRC=0.9911
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4993 | F1=0.7530 | AUROC=0.8078 | AUPRC=0.7854
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6454 | F1=0.8170 | AUROC=0.9148 | AUPRC=0.8945
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 207.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8354 | F1=0.8790 | AUROC=0.9752 | AUPRC=0.9420
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8745 | F1=0.9327 | AUROC=0.9894 | AUPRC=0.9891
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4840 | F1=0.7440 | AUROC=0.8019 | AUPRC=0.7807
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6531 | F1=0.8205 | AUROC=0.9127 | AUPRC=0.8950
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 186.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8229 | F1=0.8682 | AUROC=0.9725 | AUPRC=0.9383
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8784 | F1=0.9337 | AUROC=0.9885 | AUPRC=0.9885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4824 | F1=0.7388 | AUROC=0.7964 | AUPRC=0.7827
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v3_650m_esm2_650m_bio_splice_geom_nt_v3_650m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6501 | F1=0.8182 | AUROC=0.9059 | AUPRC=0.8903

[CONFIG MATRIX] model_pair_nt_v3_650m_esmc_600m_bio_splice_geom | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 298.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8410 | F1=0.8849 | AUROC=0.9785 | AUPRC=0.9505
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8987 | F1=0.9469 | AUROC=0.9906 | AUPRC=0.9907
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4944 | F1=0.7577 | AUROC=0.8119 | AUPRC=0.7939
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6619 | F1=0.8248 | AUROC=0.9272 | AUPRC=0.9070
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 296.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8317 | F1=0.8758 | AUROC=0.9763 | AUPRC=0.9484
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8440 | F1=0.9127 | AUROC=0.9896 | AUPRC=0.9892
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4974 | F1=0.7472 | AUROC=0.8042 | AUPRC=0.7913
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6749 | F1=0.8311 | AUROC=0.9248 | AUPRC=0.9087
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 154.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8221 | F1=0.8699 | AUROC=0.9726 | AUPRC=0.9420
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8423 | F1=0.9135 | AUROC=0.9876 | AUPRC=0.9875
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4814 | F1=0.7452 | AUROC=0.7961 | AUPRC=0.7862
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v3_650m_esmc_600m_bio_splice_geom_nt_v3_650m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6347 | F1=0.8119 | AUROC=0.9151 | AUPRC=0.8973

[CONFIG MATRIX] model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 308.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8391 | F1=0.8826 | AUROC=0.9772 | AUPRC=0.9476
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8711 | F1=0.9315 | AUROC=0.9890 | AUPRC=0.9886
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5214 | F1=0.7596 | AUROC=0.8193 | AUPRC=0.8024
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6594 | F1=0.8238 | AUROC=0.9249 | AUPRC=0.9097
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 293.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8307 | F1=0.8755 | AUROC=0.9760 | AUPRC=0.9445
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8643 | F1=0.9261 | AUROC=0.9877 | AUPRC=0.9876
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.5020 | F1=0.7462 | AUROC=0.8115 | AUPRC=0.7973
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6749 | F1=0.8312 | AUROC=0.9224 | AUPRC=0.9118
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 149.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8289 | F1=0.8756 | AUROC=0.9730 | AUPRC=0.9417
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8765 | F1=0.9347 | AUROC=0.9889 | AUPRC=0.9885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4916 | F1=0.7480 | AUROC=0.7994 | AUPRC=0.7883
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v2_500m_esm1b_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1b_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6374 | F1=0.8132 | AUROC=0.9177 | AUPRC=0.9044

[CONFIG MATRIX] model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 271.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8233 | F1=0.8721 | AUROC=0.9737 | AUPRC=0.9411
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8536 | F1=0.9228 | AUROC=0.9874 | AUPRC=0.9878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4842 | F1=0.7505 | AUROC=0.8047 | AUPRC=0.7734
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6459 | F1=0.8172 | AUROC=0.9218 | AUPRC=0.8962
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 208.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8304 | F1=0.8762 | AUROC=0.9733 | AUPRC=0.9417
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8595 | F1=0.9226 | AUROC=0.9881 | AUPRC=0.9890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4929 | F1=0.7470 | AUROC=0.8023 | AUPRC=0.7830
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6722 | F1=0.8300 | AUROC=0.9188 | AUPRC=0.8953
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 228.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8283 | F1=0.8749 | AUROC=0.9705 | AUPRC=0.9361
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8721 | F1=0.9282 | AUROC=0.9891 | AUPRC=0.9898
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4629 | F1=0.7324 | AUROC=0.7861 | AUPRC=0.7747
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v2_500m_esm1v_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm1v_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6483 | F1=0.8185 | AUROC=0.9145 | AUPRC=0.8923

[CONFIG MATRIX] model_pair_nt_v2_500m_esm2_650m_bio_splice_geom | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 300.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8350 | F1=0.8791 | AUROC=0.9763 | AUPRC=0.9454
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8722 | F1=0.9309 | AUROC=0.9895 | AUPRC=0.9897
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.4993 | F1=0.7533 | AUROC=0.8088 | AUPRC=0.7838
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6410 | F1=0.8149 | AUROC=0.9147 | AUPRC=0.8927
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 323.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8320 | F1=0.8771 | AUROC=0.9755 | AUPRC=0.9428
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8597 | F1=0.9256 | AUROC=0.9877 | AUPRC=0.9879
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4870 | F1=0.7452 | AUROC=0.8061 | AUPRC=0.7840
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6564 | F1=0.8223 | AUROC=0.9162 | AUPRC=0.8981
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 189.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8241 | F1=0.8714 | AUROC=0.9716 | AUPRC=0.9352
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8852 | F1=0.9391 | AUROC=0.9888 | AUPRC=0.9890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4860 | F1=0.7476 | AUROC=0.7968 | AUPRC=0.7825
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v2_500m_esm2_650m_bio_splice_geom_nt_v2_500m_dna_1001_esm2_650m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6372 | F1=0.8130 | AUROC=0.9056 | AUPRC=0.8843

[CONFIG MATRIX] model_pair_nt_v2_500m_esmc_600m_bio_splice_geom | modalities=['dna', 'prot', 'bio_core', 'spliceai', 'geom'] | poolings=['center'] | architectures=1
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 275.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train1__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_Test | MCC=0.8439 | F1=0.8862 | AUROC=0.9786 | AUPRC=0.9510
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ClinVarHQ | MCC=0.8771 | F1=0.9343 | AUROC=0.9913 | AUPRC=0.9915
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_UniProt | MCC=0.5039 | F1=0.7557 | AUROC=0.8104 | AUPRC=0.7966
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train1Val_ProteinGym | MCC=0.6699 | F1=0.8289 | AUROC=0.9278 | AUPRC=0.9092
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 164.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train2__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_Test | MCC=0.8354 | F1=0.8789 | AUROC=0.9769 | AUPRC=0.9492
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ClinVarHQ | MCC=0.8674 | F1=0.9275 | AUROC=0.9885 | AUPRC=0.9885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_UniProt | MCC=0.4959 | F1=0.7474 | AUROC=0.8083 | AUPRC=0.7940
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 67990 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train2__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train2__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train2Val_ProteinGym | MCC=0.6941 | F1=0.8407 | AUROC=0.9235 | AUPRC=0.9041
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 162.

D:\Missense_variant_pathogenicity_prediction\core\module05_fusion_classifier\pipeline.py:338: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fit = pd.concat([df_fit, pd.DataFrame([row])], ignore_index=True)

[Test] train3__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_Test | MCC=0.8323 | F1=0.8780 | AUROC=0.9734 | AUPRC=0.9417
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ClinVarHQ | MCC=0.8828 | F1=0.9373 | AUROC=0.9887 | AUPRC=0.9888
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_UniProt | MCC=0.4672 | F1=0.7413 | AUROC=0.7974 | AUPRC=0.7874
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_model_pair_nt_v2_500m_esmc_600m_bio_splice_geom_nt_v2_500m_dna_1001_esmc_600m_prot_501_Pure_XGBoost_Concat__geom_dna_LID+dna_LVD_L2+dna_LVD_Relative+dna_LVD_Cosine+prot_LID+prot_LVD_L2+prot_LVD_Relative+prot_LVD_Cosine | test=Train3Val_ProteinGym | MCC=0.6379 | F1=0.8135 | AUROC=0.9159 | AUPRC=0.8966
[DONE] DNA/protein modality ablation | metrics=D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011/global_leaderboard_metrics.csv | metric_rows=1020 | fit_profile=D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011/global_leaderboard_fit_profiling.csv | fit_rows=255
[OUTPUT] D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011

## Expected output files

All outputs are written under `pipeline.batch_run_dir` (`experiments/reproduction_ablations_<timestamp>` by default):

- `sota_metrics.csv`, `sota_column_mapping.csv`, `sota_metric_audit.csv`, and `sota_required_columns_audit.csv` for the four SOTA test sets.
- `global_leaderboard_metrics.csv` with test and validation metrics for every completed OURS row; `global_leaderboard_profiling.csv` with per-test inference/profile measurements; `global_leaderboard_fit_profiling.csv` with one row per unique train/validation fit, linked to the other tables by `Fit_ID`.
- Fit profiling records training duration, train/validation sample counts, epochs, batches and optimizer steps where applicable, effective train-sample throughput, device/GPU, and peak GPU memory. If an existing checkpoint has no recorded training profile, the row explicitly marks its training time as unavailable rather than fabricating a measurement.
- Per-config checkpoint/cache folders, validation-selected `decision_threshold.json`, and `tests/<dataset>/test_probabilities.csv` with Variant_ID, true label, predicted probability, threshold, and predicted class.
- Explainability runs add `tests/<dataset>/explainability/shap_global_importance.csv`, `shap_global_importance_by_true_class.csv`, `shap_local_top_ranked.csv`, `shap_run_info.json`, `lime_global_importance.csv`, `lime_local_explanations.csv`, and `lime_run_info.json` (subject to SHAP/LIME packages being installed).
- `global_compare_ours_vs_sota.csv` after at least one training stage has written metrics.

| Stage | Unique fits | OURS metric rows |
|---|---:|---:|
| 9 architecture | 27 | 108 |
| XGBoost SHAP/LIME | 3 | 12 |
| 6 feature-group ablations | 18 | 72 |
| 28 individual-feature ablations | 84 | 336 |
| Pooling (`center` reused; `cls` and `mean` new) | 6 | 24 |
| Sequence-length ablation (20 pairs; reference reused) | 57 | 228 |
| Modality and 3×4 DNA/protein model-pair ablations | 60 | 240 |
| **Total** | **255** | **1,020** |

If all seven training stages complete in one batch, expected metric and inference-profile rows are 1,020 OURS plus 112 SOTA rows (1,132 in the comparison); expected unique fit-profile rows are 255. The center-pooling XGBoost baseline and the reference DNA+protein sequence pair are reused from the architecture stage rather than fitted twice. These are expected counts, not a promise: missing artifacts or skipped/failed stages reduce the rows.

## Compare OURS vs SOTA

Run this after the selected training stages. The SOTA rows follow Notebook 01's score/rankscore/pred mapping; `Train_Split` differentiates models trained on train1, train2, and train3.

In [5]:
if not Path(pipeline.metrics_csv_path).exists():
    print("[COMPARE SKIP] No OURS metrics yet. Enable and run at least one RUN_* training stage first.")
else:
    ours = pd.read_csv(pipeline.metrics_csv_path)
    if ours.empty:
        print("[COMPARE SKIP] OURS metrics file is empty. Run at least one training stage first.")
    else:
        sota = pd.read_csv(sota_result["metrics_path"])
        test_name_map = {
            f"{train.title()}Val_{display_name}": test_split
            for train in TRAIN_SPLITS
            for test_split, display_name in TEST_SPLITS.items()
        }
        ours["Source"] = "OURS"
        ours["Train_Split"] = ours["Dataset"].astype(str).str.extract(r"^(Train[123])Val_", expand=False)
        ours["Test_Split"] = ours["Dataset"].map(test_name_map)
        sota["Source"] = "SOTA"
        sota["Train_Split"] = "N/A"
        sota["Test_Split"] = sota["Dataset"]
        comparison = pd.concat([ours, sota], ignore_index=True, sort=False)
        comparison = comparison.sort_values(["Test_Split", "Train_Split", "MCC"], ascending=[True, True, False])
        compare_path = Path(pipeline.batch_run_dir) / "global_compare_ours_vs_sota.csv"
        comparison.to_csv(compare_path, index=False)
        print(f"[COMPARE] {compare_path} | rows={len(comparison)}")
        display(comparison[["Test_Split", "Train_Split", "Source", "Ablation", "Network", "MCC", "AUROC", "AUPRC"]].head(60))
        display(pd.read_csv(sota_result["mapping_path"]).head(40))
        if sota_result.get("audit") is not None:
            audit = pd.read_csv(sota_result["audit"]["audit_path"])
            display(audit.query("exists == False or null_count > 0").head(100))

[COMPARE] D:\Missense_variant_pathogenicity_prediction\experiments\reproduction_ablations_20261101_111011\global_compare_ours_vs_sota.csv | rows=1132

,Test_Split,Train_Split,Source,Ablation,Network,MCC,AUROC,AUPRC
1066,clinvarhq,N/A,SOTA,sota,SOTA_ClinPred,0.9268,0.9912,0.9866
1055,clinvarhq,N/A,SOTA,sota,SOTA_MetaRNN,0.8957,0.9928,0.9921
1052,clinvarhq,N/A,SOTA,sota,SOTA_MutationTaster,0.8937,0.9867,0.9874
1064,clinvarhq,N/A,SOTA,sota,SOTA_BayesDel_addAF,0.8890,0.9903,0.9900
1057,clinvarhq,N/A,SOTA,sota,SOTA_REVEL,0.8275,0.9770,0.9738
1070,clinvarhq,N/A,SOTA,sota,SOTA_AlphaMissense,0.8216,0.9613,0.9517
1071,clinvarhq,N/A,SOTA,sota,SOTA_PHACTboost,0.8197,0.9770,0.9747
1068,clinvarhq,N/A,SOTA,sota,SOTA_VARITY_R,0.8052,0.9600,0.9563
1069,clinvarhq,N/A,SOTA,sota,SOTA_VARITY_ER,0.7705,0.9503,0.9445
1065,clinvarhq,N/A,SOTA,sota,SOTA_BayesDel_noAF,0.7617,0.9660,0.9648
1053,clinvarhq,N/A,SOTA,sota,SOTA_MetaSVM,0.7446,0.9404,0.9496
1072,clinvarhq,N/A,SOTA,sota,SOTA_MutFormer,0.7309,0.9427,0.9451
1058,clinvarhq,N/A,SOTA,sota,SOTA_MutPred2,0.7166,0.9400,0.9253
1060,clinvarhq,N/A,SOTA,sota,SOTA_gMVP,0.7164,0.9669,0.9659
1054,clinvarhq,N/A,SOTA,sota,SOTA_MetaLR,0.7077,0.9368,0.9454
1059,clinvarhq,N/A,SOTA,sota,SOTA_MVP,0.7021,0.9539,0.9599
1061,clinvarhq,N/A,SOTA,sota,SOTA_MisFit_D,0.6614,0.9360,0.9340
1051,clinvarhq,N/A,SOTA,sota,SOTA_Polyphen2_HVAR,0.6321,0.9069,0.8849
1049,clinvarhq,N/A,SOTA,sota,SOTA_SIFT4G,0.5902,0.8918,0.8646
1050,clinvarhq,N/A,SOTA,sota,SOTA_Polyphen2_HDIV,0.5833,0.8826,0.8368
1048,clinvarhq,N/A,SOTA,sota,SOTA_SIFT,0.5784,0.8881,0.8530
1067,clinvarhq,N/A,SOTA,sota,SOTA_LIST-S2,0.5629,0.8739,0.8725
1074,clinvarhq,N/A,SOTA,sota,SOTA_CADD,0.5603,0.9129,0.9030
1056,clinvarhq,N/A,SOTA,sota,SOTA_M-CAP,0.5485,0.9241,0.9153
1063,clinvarhq,N/A,SOTA,sota,SOTA_PrimateAI,0.4415,0.8529,0.8382
1075,clinvarhq,N/A,SOTA,sota,SOTA_DANN,0.3989,0.8286,0.7825
1062,clinvarhq,N/A,SOTA,sota,SOTA_MPC,0.3556,0.8423,0.8259
1073,clinvarhq,N/A,SOTA,sota,SOTA_popEVE,0.3359,0.8769,0.8820
0,clinvarhq,Train1,OURS,model_pair_nt_v3_650m_esmc_600m_bio_splice_geom,Pure_XGBoost_Concat,0.8987,0.9906,0.9907
1,clinvarhq,Train1,OURS,sequence_pair_dna_2001_protein_501,Pure_XGBoost_Concat,0.8916,0.9892,0.9894
2,clinvarhq,Train1,OURS,bio_drop_group_protein_geometry,Pure_XGBoost_Concat,0.8906,0.9904,0.9907
3,clinvarhq,Train1,OURS,sequence_pair_dna_2001_protein_1001,Pure_XGBoost_Concat,0.8906,0.9903,0.9904
4,clinvarhq,Train1,OURS,bio_drop_feature_dna_LID,Pure_XGBoost_Concat,0.8903,0.9897,0.9896
5,clinvarhq,Train1,OURS,sequence_pair_dna_301_protein_1001,Pure_XGBoost_Concat,0.8893,0.9894,0.9898
6,clinvarhq,Train1,OURS,sequence_pair_dna_1001_protein_1001,Pure_XGBoost_Concat,0.8882,0.9901,0.9903
7,clinvarhq,Train1,OURS,model_pair_nt_v3_650m_esm1b_650m_bio_splice_geom,Pure_XGBoost_Concat,0.8879,0.9893,0.9891
8,clinvarhq,Train1,OURS,bio_drop_group_geometry,Pure_XGBoost_Concat,0.8863,0.9901,0.9905
9,clinvarhq,Train1,OURS,bio_drop_feature_GERP++_NR,Pure_XGBoost_Concat,0.8859,0.9908,0.9910
10,clinvarhq,Train1,OURS,bio_drop_group_dna_geometry,Pure_XGBoost_Concat,0.8855,0.9876,0.9881
11,clinvarhq,Train1,OURS,bio_drop_feature_phyloP470way_mammalian,Pure_XGBoost_Concat,0.8849,0.9904,0.9904
12,clinvarhq,Train1,OURS,bio_drop_feature_GERP_92_mammals,Pure_XGBoost_Concat,0.8849,0.9896,0.9900
13,clinvarhq,Train1,OURS,sequence_pair_dna_2001_protein_201,Pure_XGBoost_Concat,0.8849,0.9889,0.9894
14,clinvarhq,Train1,OURS,bio_drop_feature_dna_LVD_Cosine,Pure_XGBoost_Concat,0.8832,0.9885,0.9890
15,clinvarhq,Train1,OURS,model_pair_nt_v1_500m_esm1b_650m_bio_splice_geom,Pure_XGBoost_Concat,0.8828,0.9895,0.9894
16,clinvarhq,Train1,OURS,bio_drop_feature_AF,Pure_XGBoost_Concat,0.8822,0.9867,0.9868
17,clinvarhq,Train1,OURS,bio_drop_feature_phastCons470way_mammalian,Pure_XGBoost_Concat,0.8822,0.9895,0.9894
18,clinvarhq,Train1,OURS,bio_drop_feature_dna_LVD_Relative,Pure_XGBoost_Concat,0.8819,0.9890,0.9895
19,clinvarhq,Train1,OURS,sequence_pair_dna_601_protein_201,Pure_XGBoost_Concat,0.8819,0.9890,0.9892
20,clinvarhq,Train1,OURS,bio_drop_feature_phastCons17way_primate,Pure_XGBoost_Concat,0.8816,0.9897,0.9899
21,clinvarhq,Train1,OURS,bio_drop_feature_SpliceAI_pred_DS_DL,Pure_XGBoost_Concat,0.8810,0.9900,0.9906
22,clinvarhq,Train1,OURS,modalities_protein_only_bio_splice_geom,Pure_XGBoost_Concat,0.8810,0.9894,0.9900
23,clinvarhq,Train1,OURS,model_pair_nt_v1_500m_esmc_600m_bio_splice_geom,Pure_XGBoost_Concat,0.8810,0.9902,0.9907
24,clinvarhq,Train1,OURS,bio_drop_feature_prot_LVD_Relative,Pure_XGBoost_Concat,0.8806,0.9890,0.9891
25,clinvarhq,Train1,OURS,bio_core_dna_prot_spliceai_geom,Pure_XGBoost_Concat,0.8802,0.9878,0.9878
26,clinvarhq,Train1,OURS,bio_drop_feature_SpliceAI_pred_DP_AL,Pure_XGBoost_Concat,0.8798,0.9898,0.9900
27,clinvarhq,Train1,OURS,model_pair_nt_v3_650m_esm2_650m_bio_splice_geom,Pure_XGBoost_Concat,0.8798,0.9908,0.9911
28,clinvarhq,Train1,OURS,bio_drop_feature_phastCons100way_vertebrate,Pure_XGBoost_Concat,0.8795,0.9892,0.9894
29,clinvarhq,Train1,OURS,bio_drop_feature_phyloP17way_primate,Pure_XGBoost_Concat,0.8792,0.9888,0.9891
30,clinvarhq,Train1,OURS,model_pair_nt_v1_500m_esm1v_650m_bio_splice_geom,Pure_XGBoost_Concat,0.8778,0.9888,0.9891
31,clinvarhq,Train1,OURS,bio_drop_feature_GERP++_RS,Pure_XGBoost_Concat,0.8775,0.9893,0.9896

,Dataset,Model,file_path,score_col,rankscore_col,pred_col,resolved_prob_col,resolved_prob_kind,resolved_threshold,pred_source,...,binary_metric_source,pred_known_count,pred_unknown_count,pred_positive_count,threshold_positive_count,pred_threshold_disagreement_count,module1_rule_score_col,module1_rule_threshold,module1_rule_checked_count,module1_rule_mismatch_count
0,test,SIFT,D:\variant_data\test_full_seq_after_vep_final....,['SIFT_score'],"['SIFT_converted_rankscore', 'SIFT_rankscore']",['SIFT_pred'],SIFT_converted_rankscore,rankscore,0.39575,SIFT_pred,...,pred,6095,0,2418,2521,103,NaN,NaN,0,0
1,test,SIFT4G,D:\variant_data\test_full_seq_after_vep_final....,['SIFT4G_score'],"['SIFT4G_converted_rankscore', 'SIFT4G_ranksco...",['SIFT4G_pred'],SIFT4G_converted_rankscore,rankscore,0.39575,SIFT4G_pred,...,pred,6095,0,2022,2502,480,NaN,NaN,0,0
2,test,Polyphen2_HDIV,D:\variant_data\test_full_seq_after_vep_final....,['Polyphen2_HDIV_score'],['Polyphen2_HDIV_rankscore'],['Polyphen2_HDIV_pred'],Polyphen2_HDIV_rankscore,rankscore,0.38028,Polyphen2_HDIV_pred,...,pred,6095,0,2468,2497,131,NaN,NaN,0,0
3,test,Polyphen2_HVAR,D:\variant_data\test_full_seq_after_vep_final....,['Polyphen2_HVAR_score'],['Polyphen2_HVAR_rankscore'],['Polyphen2_HVAR_pred'],Polyphen2_HVAR_rankscore,rankscore,0.48762,Polyphen2_HVAR_pred,...,pred,6095,0,2139,2144,137,NaN,NaN,0,0
4,test,MutationTaster,D:\variant_data\test_full_seq_after_vep_final....,['MutationTaster_score'],['MutationTaster_rankscore'],['MutationTaster_pred'],MutationTaster_rankscore,rankscore,0.31733,MutationTaster_pred,...,pred,6095,0,1776,2936,1180,NaN,NaN,0,0
5,test,MetaSVM,D:\variant_data\test_full_seq_after_vep_final....,['MetaSVM_score'],['MetaSVM_rankscore'],['MetaSVM_pred'],MetaSVM_rankscore,rankscore,0.82257,MetaSVM_pred,...,pred,6095,0,1680,1677,3,NaN,NaN,0,0
6,test,MetaLR,D:\variant_data\test_full_seq_after_vep_final....,['MetaLR_score'],['MetaLR_rankscore'],['MetaLR_pred'],MetaLR_rankscore,rankscore,0.81101,MetaLR_pred,...,pred,6095,0,1777,1776,1,NaN,NaN,0,0
7,test,MetaRNN,D:\variant_data\test_full_seq_after_vep_final....,['MetaRNN_score'],['MetaRNN_rankscore'],['MetaRNN_pred'],MetaRNN_rankscore,rankscore,0.61490,MetaRNN_pred,...,pred,6095,0,2003,1721,282,NaN,NaN,0,0
8,test,M-CAP,D:\variant_data\test_full_seq_after_vep_final....,['M-CAP_score'],['M-CAP_rankscore'],['M-CAP_pred'],M-CAP_rankscore,rankscore,0.50000,M-CAP_pred,...,pred,6095,0,2976,2870,106,NaN,NaN,0,0
9,test,REVEL,D:\variant_data\test_full_seq_after_vep_final....,['REVEL_score'],['REVEL_rankscore'],['REVEL_pred'],REVEL_rankscore,rankscore,0.50000,REVEL_pred,...,pred,6095,0,1679,2582,903,REVEL_score,0.5000,6095,0
10,test,MutPred2,D:\variant_data\test_full_seq_after_vep_final....,['MutPred2_score'],['MutPred2_rankscore'],['MutPred2_pred'],MutPred2_rankscore,rankscore,0.50000,MutPred2_pred,...,pred+threshold_fallback,5264,831,1230,2113,52,NaN,NaN,0,0
11,test,MVP,D:\variant_data\test_full_seq_after_vep_final....,['MVP_score'],['MVP_rankscore'],['MVP_pred'],MVP_rankscore,rankscore,0.50000,MVP_pred,...,pred,6095,0,1939,2826,887,MVP_score,0.7500,6095,0
12,test,gMVP,D:\variant_data\test_full_seq_after_vep_final....,['gMVP_score'],['gMVP_rankscore'],['gMVP_pred'],gMVP_rankscore,rankscore,0.50000,gMVP_pred,...,pred,6095,0,2498,2484,14,gMVP_score,0.5000,6095,0
13,test,MisFit_D,D:\variant_data\test_full_seq_after_vep_final....,['MisFit_D_score'],['MisFit_D_rankscore'],"['MisFit_D_pred_lenient', 'MisFit_D_pred']",MisFit_D_rankscore,rankscore,0.50000,MisFit_D_pred_lenient,...,pred,6095,0,2167,2199,32,NaN,NaN,0,0
14,test,MPC,D:\variant_data\test_full_seq_after_vep_final....,['MPC_score'],['MPC_rankscore'],['MPC_pred'],MPC_rankscore,rankscore,0.50000,MPC_pred,...,pred,6095,0,588,2410,1822,MPC_score,2.0000,6095,0
15,test,PrimateAI,D:\variant_data\test_full_seq_after_vep_final....,['PrimateAI_score'],['PrimateAI_rankscore'],['PrimateAI_pred'],PrimateAI_rankscore,rankscore,0.50000,PrimateAI_pred,...,pred,6095,0,1006,2154,1148,NaN,NaN,0,0
16,test,BayesDel_addAF,D:\variant_data\test_full_seq_after_vep_final....,['BayesDel_addAF_score'],['BayesDel_addAF_rankscore'],['BayesDel_addAF_pred'],BayesDel_addAF_rankscore,rankscore,0.50000,BayesDel_addAF_pred,...,pred,6095,0,1694,1874,180,NaN,NaN,0,0
17,test,BayesDel_noAF,D:\variant_data\test_full_seq_after_vep_final....,['BayesDel_noAF_score'],['BayesDel_noAF_rankscore'],['BayesDel_noAF_pred'],BayesDel_noAF_rankscore,rankscore,0.50000,BayesDel_noAF_pred,...,pred,6095,0,1814,2302,488,NaN,NaN,0,0
18,test,ClinPred,D:\variant_data\test_full_seq_after_vep_final....,['ClinPred_score'],['ClinPred_rankscore'],['ClinPred_pred'],ClinPred_rankscore,rankscore,0.50000,ClinPred_pred,...,pred,6095,0,1934,1647,287,NaN,NaN,0,0
19,test,LIST-S2,D:\variant_data\test_full_seq_after_vep_final....,['LIST-S2_score'],['LIST-S2_rankscore'],['LIST-S2_pred'],LIST-S2_rankscore,rankscore,0.50000,LIST-S2_pred,...,pred,6095,0,2424,2619,195,NaN,NaN,0,0
20,test,VARITY_R,D:\variant_data\test_full_seq_after_vep_final....,['VARITY_R_score'],['VARITY_R_rankscore'],['VARITY_R_pred'],VARITY_R_rankscore,rankscore,0.50000,VARITY_R_pred,...,pred,6095,0,1702,2077,375,VARITY_R_score,0.5000,6095,0
21,test,VARITY_ER,D:\variant_data\test_full_seq_after_vep_final....,['VARITY_ER_score'],['VARITY_ER_rankscore'],['VARITY_ER_pred'],VARITY_ER_rankscore,rankscore,0.50000,VARITY_ER_pred,...,pred,6095,0,1521,2055,534,VARITY_ER_score,0.5000,6095,0
22,test,AlphaMissense,D:\variant_data\test_full_seq_after_vep_final....,['AlphaMissense_score'],['AlphaMissense_rankscore'],['AlphaMissense_pred'],AlphaMissense_rankscore,rankscore,0.50000,AlphaMissense_pred,...,pred+threshold_fallback,5836,259,1541,2031,231,NaN,NaN,0,0
23,test,PHACTboost,D:\variant_data\test_full_seq_after_vep_final....,['PHACTboost_score'],['PHACTboost_rankscore'],['PHACTboost_pred'],PHACTboost_rankscore,rankscore,0.50000,PHACTboost_pred,...,pred,6095,0,2033,2412,379,PHACTboost_score,0.6200,6095,0
24,test,MutFormer,D:\variant_data\test_full_seq_after_vep_final....,['MutFormer_score'],['MutFormer_rankscore'],['MutFormer_pred'],MutFormer_rankscore,rankscore,0.50000,MutFormer_pred,...,pred,6095,0,1601,3351,1750,MutFormer_score,0.8838,6095,0
25,test,popEVE,D:\variant_data\test_full_seq_after_vep_final....,['popEVE_score'],"['popEVE_converted_rankscore', 'popEVE_ranksco...",['popEVE_pred'],popEVE_converted_rankscore,rankscore,0.50000,popEVE_pred,...,pred,6095,0,372,2137,1765,NaN,NaN,0,0
26,test,CADD,D:\variant_data\test_full_seq_after_vep_final....,"['CADD_raw', 'CADD_phred']",['CADD_raw_rankscore'],['CADD_pred'],CADD_raw_rankscore,rankscore,0.50000,CADD_pred,...,pred,6095,0,2750,2282,468,CADD_phred,20.0000,6095,0
27,test,DANN,D:\variant_data\test_full_seq_after_vep_final....,['DANN_score'],['DANN_rankscore'],['DANN_pred'],DANN_rankscore,rankscore,0.50000,DANN_pred,...,pred,6095,0,3612,2498,1114,DANN_score,0.9000,6095,0
28,clinvarhq,SIFT,D:\variant_data\clinvarhq_full_seq_after_vep_f...,['SIFT_score'],"['SIFT_converted_rankscore', 'SIFT_rankscore']",['SIFT_pred'],SIFT_converted_rankscore,rankscore,0.39575,SIFT_pred,...,pred,703,0,464,476,12,NaN,NaN,0,0
29,clinvarhq,SIFT4G,D:\variant_data\clinvarhq_full_seq_after_vep_f...,['SIFT4G_score'],"['SIFT4G_converted_rankscore', 'SIFT4G_ranksco...",['SIFT4G_pred'],SIFT4G_converted_rankscore,rankscore,0.39575,SIFT4G_pred,...,pred,703,0,405,468,63,NaN,NaN,0,0
30,clinvarhq,Polyphen2_HDIV,D:\variant_data\clinvarhq_full_seq_after_vep_f...,['Polyphen2_HDIV_score'],['Polyphen2_HDIV_rankscore'],['Polyphen2_HDIV_pred'],Polyphen2_HDIV_rankscore,rankscore,0.38028,Polyphen2_HDIV_pred,...,pred,703,0,467,472,23,NaN,NaN,0,0
31,clinvarhq,Polyphen2_HVAR,D:\variant_data\clinvarhq_full_seq_after_vep_f...,['Polyphen2_HVAR_score'],['Polyphen2_HVAR_rankscore'],['Polyphen2_HVAR_pred'],Polyphen2_HVAR_rankscore,rankscore,0.48762,Polyphen2_HVAR_pred,...,pred,703,0,418,422,16,NaN,NaN,0,0
32,clinvarhq,MutationTaster,D:\variant_data\clinvarhq_full_seq_after_vep_f...,['MutationTaster_score'],['MutationTaster_rankscore'],['MutationTaster_pred'],MutationTaster_rankscore,rankscore,0.31733,MutationTaster_pred,...,pred,703,0,370,486,118,NaN,NaN,0,0
33,clinvarhq,MetaSVM,D:\variant_data\clinvarhq_full_seq_after_vep_f...,['MetaSVM_score'],['MetaSVM_rankscore'],['MetaSVM_pred'],MetaSVM_rankscore,rankscore,0.82257,MetaSVM_pred,...,pred,703,0,362,362,0,NaN,NaN,0,0
34,clinvarhq,MetaLR,D:\variant_data\clinvarhq_full_seq_after_vep_f...,['MetaLR_score'],['MetaLR_rankscore'],['MetaLR_pred'],MetaLR_rankscore,rankscore,0.81101,MetaLR_pred,...,pred,703,0,363,363,0,NaN,NaN,0,0
35,clinvarhq,MetaRNN,D:\variant_data\clinvarhq_full_seq_after_vep_f...,['MetaRNN_score'],['MetaRNN_rankscore'],['MetaRNN_pred'],MetaRNN_rankscore,rankscore,0.61490,MetaRNN_pred,...,pred,703,0,380,348,32,NaN,NaN,0,0
36,clinvarhq,M-CAP,D:\variant_data\clinvarhq_full_seq_after_vep_f...,['M-CAP_score'],['M-CAP_rankscore'],['M-CAP_pred'],M-CAP_rankscore,rankscore,0.50000,M-CAP_pred,...,pred,703,0,520,508,12,NaN,NaN,0,0
37,clinvarhq,REVEL,D:\variant_data\clinvarhq_full_seq_after_vep_f...,['REVEL_score'],['REVEL_rankscore'],['REVEL_pred'],REVEL_rankscore,rankscore,0.50000,REVEL_pred,...,pred,703,0,365,466,101,REVEL_score,0.5000,703,0
38,clinvarhq,MutPred2,D:\variant_data\clinvarhq_full_seq_after_vep_f...,['MutPred2_score'],['MutPred2_rankscore'],['MutPred2_pred'],MutPred2_rankscore,rankscore,0.50000,MutPred2_pred,...,pred+threshold_fallback,535,168,251,425,6,NaN,NaN,0,0
39,clinvarhq,MVP,D:\variant_data\clinvarhq_full_seq_after_vep_f...,['MVP_score'],['MVP_rankscore'],['MVP_pred'],MVP_rankscore,rankscore,0.50000,MVP_pred,...,pred,703,0,404,516,112,MVP_score,0.7500,703,0

Empty DataFrame
Columns: [Dataset, file_path, column, exists, null_count]
Index: []