### Cách dùng Notebook 01 hiện tại

1. Mở `01_train_val_test_batch_runner.ipynb`.
2. Chạy Cell 2 để:
- Import pipeline
- Khai báo toàn bộ cấu hình bạn muốn kiểm soát
- Khởi tạo đối tượng pipeline
3. Chạy Cell 4 để chạy toàn bộ train-val-test batch.
4. Sau khi chạy xong, Cell 4 sẽ:
- In đường dẫn thư mục batch run
- Đọc và hiển thị 2 bảng tổng hợp metrics/profiling.

Luồng chạy thực tế nằm ở `pipeline.py`.

Các config ảnh hưởng pipeline train như thế nào

1. CONFIG trong Cell 2
- batch_size: tăng thì nhanh hơn nhưng tốn VRAM/RAM hơn.
- epochs: số epoch tối đa cho nhánh pytorch.
- lr: learning rate cho optimizer.
- weight_decay: regularization cho pytorch.
- lr_factor + lr_patience: giảm learning rate khi MCC val không cải thiện.
- early_stop_patience: dừng sớm nếu MCC val không tăng.
- num_workers: số worker DataLoader.

2. MODELS_SPACE trong Cell 2
- Xác định tập model DNA và Protein để vét cạn tổ hợp ở Stage 1.
- Pipeline tự tách model theo seq_type dna/protein.
- Nếu thêm/bớt model ở đây, số tổ hợp train tăng/giảm trực tiếp.

3. EXPERIMENTS trong Cell 2
- Quy định bạn chạy kiểu nào:
- pytorch: train end-to-end mạng fusion.
- hybrid: train nhanh mạng pytorch để lấy f_global, sau đó train XGBoost.
- xgboost_pure: PCA + XGBoost trên đặc trưng không gian bảng/biến thể.
- Với ablation chỉ có 1 nhánh chuỗi, pipeline tự bỏ các fusion cần 2 nhánh như cross_attention/transformer/gating.

4. datasets trong Cell 2
- Mỗi phần tử định nghĩa 1 job train/val/test.
- test split ở đây còn ảnh hưởng E2E profiling vì Module 5 sẽ đọc FM profiling đúng theo split test tương ứng.

5. pooling_strategies trong Cell 2
- Chạy lặp theo từng pooling center/cls/mean.
- Mỗi pooling sẽ có leaderboard và best pair search riêng.

6. EXPLAINABILITY trong Cell 2
- enable_shap: bật SHAP cho các nhánh dùng XGBoost.
- enable_lime: bật LIME cho local explanation.
- max_background_samples: số mẫu nền tối đa cho SHAP/LIME.
- max_explain_samples: số mẫu test giải thích bằng SHAP.
- max_lime_samples: số mẫu test giải thích bằng LIME.
- lime_num_features: số feature rule mỗi mẫu cho LIME.
- random_state: seed cho sampling explainability.

### Output sau khi chạy xong

Sau khi chạy toàn bộ Notebook 01 (Cell 2 rồi Cell 4), output sẽ gồm các nhóm sau trong thư mục batch run mới:

1. Output tổng hợp cấp batch run
- experiments / `batch_run_YYYYMMDD_HHMM/`
- `global_leaderboard_metrics.csv`: metrics của model mình (toàn bộ run trong pipeline)
- `global_leaderboard_profiling.csv`: profiling E2E của model mình
- `global_compare_ours_vs_sota.csv`: bảng gộp so sánh `OURS` và `SOTA`
- `sota_metrics.csv`: metrics SOTA tính trực tiếp từ cột score/rankscore/pred
- `sota_column_mapping.csv`: mapping model SOTA -> cột nào được dùng
- `sota_required_columns_audit.csv`: audit đủ cột/thiếu cột/null theo từng dataset test

2. Output theo từng experiment con
Mỗi tổ hợp dataset + pooling + ablation + model + network sẽ có 1 thư mục con, ví dụ:
- `Train1Val_Test_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat/`

Bên trong thường có:
- `test_probabilities.csv`: dự đoán chi tiết theo Variant_ID
- `tensorboard_logs/`: log train/val
- `checkpoints/best_model.pth`: với nhánh PyTorch

3. Output explainability (nếu bật trong EXPLAINABILITY)
Trong các run dùng XGBoost (`hybrid`, `xgboost_pure`) sẽ có:
- `explainability/shap_global_importance.csv`
- `explainability/shap_local_top_ranked.csv`
- `explainability/lime_local_explanations.csv` (chỉ có khi `enable_lime=True`)

4. Output hiển thị ngay trên notebook (không phải file)
- In đường dẫn batch run
- In số dòng của metrics/profiling
- `display(df_compare.head(...))` cho bảng so sánh OURS vs SOTA
- `display(mapping/audit head(...))` để xem nhanh mapping cột và lỗi audit (nếu có)

Các đầu vào mà Notebook 01 kỳ vọng

- Bio normalized: dưới D:/variant_data/processed_parquet
- Geometry: dưới D:/variant_data/geometry/split
- Embedding pt: dưới D:/variant_data/fm_embeddings/split
- FM profiling json: `fm_profiling.json`

### SET UP

In [1]:
import os
import sys
import importlib
import torch
import pandas as pd

sys.path.append(os.path.abspath("../"))

try:
    import thop
    print(f"[*] thop version: {getattr(thop, '__version__', 'unknown')}")
except Exception as e:
    print(f"[CẢNH BÁO] thop import lỗi: {e}")

import core.module05_fusion_classifier.dataset as dataset_module
importlib.reload(dataset_module)
import core.module05_fusion_classifier.evaluator_profiler as evalprof_module
importlib.reload(evalprof_module)
import core.module05_fusion_classifier.pipeline as pipeline_module
importlib.reload(pipeline_module)
from core.module05_fusion_classifier.pipeline import FusionBatchPipeline
from core.module05_fusion_classifier.sota_benchmark import (
    evaluate_sota_from_test_files,
    SOTA_MODEL_COLUMNS_FULL,
    SOTA_REQUIRED_COLUMNS,
)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"[*] Device: {DEVICE}")

BASE_DIR = "D:/variant_data"
FM_PROFILE_JSON = f"{BASE_DIR}/profiling/fm_profiling.json"
GEOM_PROFILE_JSON = f"{BASE_DIR}/profiling/geom_profiling.json"

# Default config dua ve notebook de de kiem soat
CONFIG = {
    "batch_size": 256,
    "epochs": 30,
    "lr": 1e-4,
    "weight_decay": 1e-3,
    "lr_factor": 0.5,
    "lr_patience": 3,
    "early_stop_patience": 6,
    "num_workers": 0,
}

MODELS_SPACE = [
    {"name": "nt_v1_500m", "seq_type": "dna"},
    {"name": "nt_v3_650m", "seq_type": "dna"},
    {"name": "nt_v2_500m", "seq_type": "dna"},
    {"name": "esm1b_650m", "seq_type": "protein"},
    {"name": "esm2_650m", "seq_type": "protein"},
    {"name": "esmc_600m", "seq_type": "protein"},
]

EXPERIMENTS = [
    {"name": "PyTorch_Concat", "type": "pytorch", "fusion": "concat"},
    {"name": "PyTorch_CrossAttn", "type": "pytorch", "fusion": "cross_attention"},
    {"name": "PyTorch_Transformer", "type": "pytorch", "fusion": "transformer"},
    {"name": "PyTorch_Gating", "type": "pytorch", "fusion": "gating"},
    {"name": "Pure_XGBoost_Concat", "type": "xgboost_pure", "fusion": "concat"},
    {"name": "Hybrid_Concat_XGBoost", "type": "hybrid", "fusion": "concat"},
    {"name": "Hybrid_CrossAttn_XGBoost", "type": "hybrid", "fusion": "cross_attention"},
    {"name": "Hybrid_Transformer_XGBoost", "type": "hybrid", "fusion": "transformer"},
    {"name": "Hybrid_Gating_XGBoost", "type": "hybrid", "fusion": "gating"},
]

# Dataset split run theo du lieu hien co: train1/val va 4 tap test
datasets = [
    {"name": "Train1Val_Test", "train": "train1", "val": "val", "test": "test"},
    {"name": "Train1Val_ClinVarHQ", "train": "train1", "val": "val", "test": "clinvarhq"},
    {"name": "Train1Val_UniProt", "train": "train1", "val": "val", "test": "uniprot"},
    {"name": "Train1Val_ProteinGym", "train": "train1", "val": "val", "test": "proteingym"},
]

pooling_strategies = ["center", "cls", "mean"]

# Explainability: nen bat SHAP truoc, LIME de sau vi ton thoi gian hon
EXPLAINABILITY = {
    "enable_shap": True,
    "enable_lime": False,
    "max_background_samples": 512,
    "max_explain_samples": 200,
    "lime_num_features": 20,
    "max_lime_samples": 20,
    "random_state": 42,
}

# [MOI] SOTA benchmark tu cot score/rankscore/pred trong 4 test files
SOTA_TEST_FILES = {
    "test": f"{BASE_DIR}/test_full_seq_after_vep_final.parquet",
    "clinvarhq": f"{BASE_DIR}/clinvarhq_full_seq_after_vep_final.parquet",
    "uniprot": f"{BASE_DIR}/uniprot_full_seq_after_vep_final.parquet",
    "proteingym": f"{BASE_DIR}/proteingym_full_seq_after_vep_final.parquet",
}
SOTA_LABEL_COL = None
SOTA_LABEL_CANDIDATES = ["Pathogenicity_Label", "Label"]
SOTA_THRESHOLD = 0.5

# Dung bo cot day du cho SOTA theo danh sach chuan
SOTA_MODEL_COLUMNS = SOTA_MODEL_COLUMNS_FULL
SOTA_REQUIRED = SOTA_REQUIRED_COLUMNS
SOTA_ENFORCE_REQUIRED = True

# Resume control: dat True de tiep tuc 1 batch run dang do
RESUME_ENABLED = True
RESUME_BATCH_RUN_DIR = '../experiments/batch_run_20260902_1626' # vd: '../experiments/batch_run_20260902_1430'

pipeline = FusionBatchPipeline(
    base_dir=BASE_DIR,
    config=CONFIG,
    datasets=datasets,
    models_space=MODELS_SPACE,
    pooling_strategies=pooling_strategies,
    experiments=EXPERIMENTS,
    explainability=EXPLAINABILITY,
    fm_profile_json=FM_PROFILE_JSON,
    geom_profile_json=GEOM_PROFILE_JSON,
    batch_run_dir=RESUME_BATCH_RUN_DIR,
)

print(f"[*] FM profiling json: {FM_PROFILE_JSON}")
print(f"[*] Geometry profiling json: {GEOM_PROFILE_JSON}")
print(f"[*] Batch run dir: {pipeline.batch_run_dir}")

[*] thop version: 0.1.1
[*] Device: cpu
[*] FM profiling json: D:/variant_data/profiling/fm_profiling.json
[*] Geometry profiling json: D:/variant_data/profiling/geom_profiling.json
[*] Batch run dir: d:\Missense_variant_pathogenicity_prediction\experiments\batch_run_20260902_1626

c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### The Master Loop

In [2]:
# 1) Benchmark SOTA truc tiep tu cot score/rankscore/pred tren 4 test files
sota_result = evaluate_sota_from_test_files(
    test_files=SOTA_TEST_FILES,
    output_dir=pipeline.batch_run_dir,
    label_col=SOTA_LABEL_COL,
    label_candidates=SOTA_LABEL_CANDIDATES,
    model_columns=SOTA_MODEL_COLUMNS,
    threshold=SOTA_THRESHOLD,
    required_columns=SOTA_REQUIRED,
    enforce_required_columns=SOTA_ENFORCE_REQUIRED,
)
print(f"[SOTA] Metrics CSV: {sota_result['metrics_path']} | rows={sota_result['num_rows']}")
print(f"[SOTA] Mapping CSV: {sota_result['mapping_path']} | unique models={sota_result['num_models']}")
if sota_result.get('audit') is not None:
    audit = sota_result['audit']
    print(f"[SOTA] Audit CSV: {audit['audit_path']}")
    print(f"[SOTA] missing_count={audit['missing_count']} | null_issue_count={audit['null_issue_count']}")

# 2) Chay pipeline model cua chung ta
result = pipeline.run(resume=RESUME_ENABLED)

print("\n" + "=" * 80)
print("[THANH CONG] Module 5 batch runner da hoan tat")
print("=" * 80)
print(f"Batch run dir: {result['batch_run_dir']}")
print(f"Metrics CSV: {result['metrics_path']} | rows={result['num_rows_metrics']}")
print(f"Profiling CSV: {result['profiling_path']} | rows={result['num_rows_profiling']}")

# 3) Gop bang so sanh SOTA vs Ours
ours = pd.read_csv(result["metrics_path"])
sota = pd.read_csv(sota_result["metrics_path"])
ours["Source"] = "OURS"
sota["Source"] = "SOTA"

df_compare = pd.concat([ours, sota], ignore_index=True)
df_compare = df_compare.sort_values(by=["Dataset", "MCC"], ascending=[True, False])
df_compare.to_csv(f"{result['batch_run_dir']}/global_compare_ours_vs_sota.csv", index=False)

print(f"Compare CSV: {result['batch_run_dir']}/global_compare_ours_vs_sota.csv")
display(df_compare.head(40))
display(pd.read_csv(sota_result["mapping_path"]).head(40))
if sota_result.get('audit') is not None:
    display(pd.read_csv(sota_result['audit']['audit_path']).query('exists == False or null_count > 0').head(100))

[SOTA] Metrics CSV: d:\Missense_variant_pathogenicity_prediction\experiments\batch_run_20260902_1626/sota_metrics.csv | rows=112
[SOTA] Mapping CSV: d:\Missense_variant_pathogenicity_prediction\experiments\batch_run_20260902_1626/sota_column_mapping.csv | unique models=28
[SOTA] Audit CSV: d:\Missense_variant_pathogenicity_prediction\experiments\batch_run_20260902_1626/sota_required_columns_audit.csv
[SOTA] missing_count=0 | null_issue_count=0
[*] Device: cpu
[*] Batch run dir: d:\Missense_variant_pathogenicity_prediction\experiments\batch_run_20260902_1626
[*] Resume mode: loaded metrics=1548 rows, profiling=1548 rows

================================================================================
[*] POOLING: CENTER
================================================================================
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_None_None_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.2879 | val_loss=0.2291 | val_mcc=0.6917 | val_f1=0.7430 | val_auroc=0.9471

[Epoch 02] train_loss=0.2598 | val_loss=0.2301 | val_mcc=0.6802 | val_f1=0.7273 | val_auroc=0.9486

[Epoch 03] train_loss=0.2561 | val_loss=0.2251 | val_mcc=0.6838 | val_f1=0.7357 | val_auroc=0.9487

[Epoch 04] train_loss=0.2530 | val_loss=0.2240 | val_mcc=0.6937 | val_f1=0.7472 | val_auroc=0.9488

[Epoch 05] train_loss=0.2521 | val_loss=0.2230 | val_mcc=0.6855 | val_f1=0.7365 | val_auroc=0.9497

[Epoch 06] train_loss=0.2509 | val_loss=0.2228 | val_mcc=0.6888 | val_f1=0.7375 | val_auroc=0.9500

[Epoch 07] train_loss=0.2504 | val_loss=0.2215 | val_mcc=0.6920 | val_f1=0.7427 | val_auroc=0.9500

[Epoch 08] train_loss=0.2493 | val_loss=0.2243 | val_mcc=0.6861 | val_f1=0.7347 | val_auroc=0.9501

[Epoch 09] train_loss=0.2485 | val_loss=0.2222 | val_mcc=0.6895 | val_f1=0.7384 | val_auroc=0.9503

[Epoch 10] train_loss=0.2482 | val_loss=0.2236 | val_mcc=0.6868 | val_f1=0.7384 | val_auroc=0.9500
[EarlyStop] epoch=10 | best_val_mcc=0.6937
[Test] train1__val_center_bio_None_None_PyTorch_Concat | test=Train1Val_Test | MCC=0.6946 | F1=0.7695 | AUROC=0.9402 | AUPRC=0.8679
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_None_None_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_None_None_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.7078 | F1=0.8068 | AUROC=0.9680 | AUPRC=0.9696
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_None_None_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_None_None_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.3183 | F1=0.6245 | AUROC=0.7337 | AUPRC=0.7066
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_None_None_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_None_None_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.5227 | F1=0.7572 | AUROC=0.8625 | AUPRC=0.8448
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 332.
[Test] train1__val_center_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.7130 | F1=0.7938 | AUROC=0.9443 | AUPRC=0.8775
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.7858 | F1=0.8866 | AUROC=0.9682 | AUPRC=0.9696
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.3780 | F1=0.6955 | AUROC=0.7527 | AUPRC=0.7273
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5324 | F1=0.7651 | AUROC=0.8757 | AUPRC=0.8581
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 346.
[Test] train1__val_center_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.7070 | F1=0.7883 | AUROC=0.9364 | AUPRC=0.8625
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.7647 | F1=0.8690 | AUROC=0.9647 | AUPRC=0.9665
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.3369 | F1=0.6697 | AUROC=0.7355 | AUPRC=0.7157
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.5192 | F1=0.7590 | AUROC=0.8635 | AUPRC=0.8481
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.3163 | val_loss=0.5965 | val_mcc=0.0915 | val_f1=0.0204 | val_auroc=0.8682

[Epoch 02] train_loss=0.2853 | val_loss=0.6666 | val_mcc=0.0726 | val_f1=0.0129 | val_auroc=0.8699

[Epoch 03] train_loss=0.2817 | val_loss=0.6765 | val_mcc=0.0787 | val_f1=0.0152 | val_auroc=0.8677

[Epoch 04] train_loss=0.2784 | val_loss=0.7636 | val_mcc=0.0610 | val_f1=0.0091 | val_auroc=0.8684

[Epoch 05] train_loss=0.2764 | val_loss=0.6960 | val_mcc=0.0925 | val_f1=0.0219 | val_auroc=0.8644

[Epoch 06] train_loss=0.2751 | val_loss=0.8233 | val_mcc=0.0682 | val_f1=0.0114 | val_auroc=0.8624

[Epoch 07] train_loss=0.2747 | val_loss=0.8356 | val_mcc=0.0498 | val_f1=0.0061 | val_auroc=0.8656

[Epoch 08] train_loss=0.2731 | val_loss=0.7647 | val_mcc=0.0948 | val_f1=0.0219 | val_auroc=0.8563

[Epoch 09] train_loss=0.2715 | val_loss=0.8711 | val_mcc=0.0528 | val_f1=0.0069 | val_auroc=0.8518

[Epoch 10] train_loss=0.2692 | val_loss=0.8438 | val_mcc=0.0610 | val_f1=0.0091 | val_auroc=0.8466

[Epoch 11] train_loss=0.2696 | val_loss=0.8938 | val_mcc=0.0352 | val_f1=0.0031 | val_auroc=0.8427

[Epoch 12] train_loss=0.2674 | val_loss=0.8975 | val_mcc=0.0466 | val_f1=0.0053 | val_auroc=0.8409

[Epoch 13] train_loss=0.2669 | val_loss=0.8874 | val_mcc=0.0352 | val_f1=0.0031 | val_auroc=0.8376

[Epoch 14] train_loss=0.2660 | val_loss=0.8915 | val_mcc=0.0352 | val_f1=0.0031 | val_auroc=0.8358
[EarlyStop] epoch=14 | best_val_mcc=0.0948
[Test] train1__val_center_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_Test | MCC=0.0865 | F1=0.0203 | AUROC=0.8698 | AUPRC=0.7836
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.0539 | F1=0.0114 | AUROC=0.8173 | AUPRC=0.8270
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.0750 | F1=0.0296 | AUROC=0.7566 | AUPRC=0.7664
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.0807 | F1=0.0235 | AUROC=0.8256 | AUPRC=0.8322
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 22.
[Test] train1__val_center_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.6369 | F1=0.6826 | AUROC=0.8823 | AUPRC=0.8056
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.5489 | F1=0.6704 | AUROC=0.8362 | AUPRC=0.8496
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.3980 | F1=0.5949 | AUROC=0.7510 | AUPRC=0.7571
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5543 | F1=0.6809 | AUROC=0.8391 | AUPRC=0.8259
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 16.
[Test] train1__val_center_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.1400 | F1=0.0540 | AUROC=0.8097 | AUPRC=0.7090
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.1331 | F1=0.0667 | AUROC=0.7846 | AUPRC=0.7968
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.0996 | F1=0.0384 | AUROC=0.7261 | AUPRC=0.7277
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.1519 | F1=0.0800 | AUROC=0.7838 | AUPRC=0.7816
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_Test
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_Test | MCC=0.5091 | F1=0.6027 | AUROC=0.8551 | AUPRC=0.7257
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.4440 | F1=0.6245 | AUROC=0.8429 | AUPRC=0.8370
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.2823 | F1=0.5322 | AUROC=0.7249 | AUPRC=0.7131
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.4280 | F1=0.6284 | AUROC=0.7999 | AUPRC=0.7703
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_Test
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.4831 | F1=0.6149 | AUROC=0.8306 | AUPRC=0.6941
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.4583 | F1=0.6733 | AUROC=0.8045 | AUPRC=0.8186
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.2433 | F1=0.5550 | AUROC=0.6735 | AUPRC=0.6765
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.4046 | F1=0.6651 | AUROC=0.7755 | AUPRC=0.7542
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.4605 | F1=0.6014 | AUROC=0.8205 | AUPRC=0.6787
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.4057 | F1=0.6491 | AUROC=0.7960 | AUPRC=0.8020
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.2606 | F1=0.5846 | AUROC=0.6722 | AUPRC=0.6750
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.3739 | F1=0.6454 | AUROC=0.7620 | AUPRC=0.7426
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_prot_None_esmc_600m_PyTorch_Concat | test=Train1Val_Test
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_prot_None_esmc_600m_PyTorch_Concat | test=Train1Val_Test | MCC=0.6949 | F1=0.7572 | AUROC=0.9360 | AUPRC=0.8763
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_prot_None_esmc_600m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_prot_None_esmc_600m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.6522 | F1=0.7922 | AUROC=0.9255 | AUPRC=0.9243
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.2906 | val_loss=0.2259 | val_mcc=0.6888 | val_f1=0.7348 | val_auroc=0.9510

[Epoch 02] train_loss=0.2521 | val_loss=0.2246 | val_mcc=0.6877 | val_f1=0.7306 | val_auroc=0.9530

[Epoch 03] train_loss=0.2406 | val_loss=0.2216 | val_mcc=0.6933 | val_f1=0.7353 | val_auroc=0.9548

[Epoch 04] train_loss=0.2323 | val_loss=0.2251 | val_mcc=0.6870 | val_f1=0.7252 | val_auroc=0.9573

[Epoch 05] train_loss=0.2237 | val_loss=0.2112 | val_mcc=0.7183 | val_f1=0.7635 | val_auroc=0.9557

[Epoch 06] train_loss=0.2147 | val_loss=0.2026 | val_mcc=0.7280 | val_f1=0.7707 | val_auroc=0.9598

[Epoch 07] train_loss=0.2053 | val_loss=0.2066 | val_mcc=0.7301 | val_f1=0.7708 | val_auroc=0.9588

[Epoch 08] train_loss=0.1979 | val_loss=0.2030 | val_mcc=0.7321 | val_f1=0.7728 | val_auroc=0.9608

[Epoch 09] train_loss=0.1885 | val_loss=0.2094 | val_mcc=0.7363 | val_f1=0.7774 | val_auroc=0.9607

[Epoch 10] train_loss=0.1817 | val_loss=0.2040 | val_mcc=0.7431 | val_f1=0.7881 | val_auroc=0.9591

[Epoch 11] train_loss=0.1743 | val_loss=0.2105 | val_mcc=0.7403 | val_f1=0.7843 | val_auroc=0.9581

[Epoch 12] train_loss=0.1663 | val_loss=0.2163 | val_mcc=0.7337 | val_f1=0.7826 | val_auroc=0.9545

[Epoch 13] train_loss=0.1609 | val_loss=0.2244 | val_mcc=0.7370 | val_f1=0.7792 | val_auroc=0.9575

[Epoch 14] train_loss=0.1535 | val_loss=0.2248 | val_mcc=0.7316 | val_f1=0.7759 | val_auroc=0.9570

[Epoch 15] train_loss=0.1388 | val_loss=0.2346 | val_mcc=0.7362 | val_f1=0.7806 | val_auroc=0.9547

[Epoch 16] train_loss=0.1327 | val_loss=0.2344 | val_mcc=0.7330 | val_f1=0.7771 | val_auroc=0.9544
[EarlyStop] epoch=16 | best_val_mcc=0.7431
[Test] train1__val_center_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_Test | MCC=0.7415 | F1=0.8045 | AUROC=0.9528 | AUPRC=0.8886
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.7456 | F1=0.8412 | AUROC=0.9758 | AUPRC=0.9768
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.3891 | F1=0.6656 | AUROC=0.7716 | AUPRC=0.7543
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.5625 | F1=0.7745 | AUROC=0.8597 | AUPRC=0.8225
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 453.
[Test] train1__val_center_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.7702 | F1=0.8328 | AUROC=0.9619 | AUPRC=0.9092
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.8159 | F1=0.8971 | AUROC=0.9797 | AUPRC=0.9803
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.4028 | F1=0.7003 | AUROC=0.7689 | AUPRC=0.7530
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5470 | F1=0.7714 | AUROC=0.8854 | AUPRC=0.8713
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 322.
[Test] train1__val_center_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.7533 | F1=0.8214 | AUROC=0.9554 | AUPRC=0.8957
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.7987 | F1=0.8912 | AUROC=0.9720 | AUPRC=0.9738
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.3913 | F1=0.7006 | AUROC=0.7543 | AUPRC=0.7364
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.5248 | F1=0.7615 | AUROC=0.8674 | AUPRC=0.8383
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_prot_None_esmc_600m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.2070 | val_loss=0.1573 | val_mcc=0.7989 | val_f1=0.8313 | val_auroc=0.9746

[Epoch 02] train_loss=0.1667 | val_loss=0.1519 | val_mcc=0.8142 | val_f1=0.8459 | val_auroc=0.9767

[Epoch 03] train_loss=0.1500 | val_loss=0.1442 | val_mcc=0.8242 | val_f1=0.8563 | val_auroc=0.9777

[Epoch 04] train_loss=0.1329 | val_loss=0.1498 | val_mcc=0.8208 | val_f1=0.8532 | val_auroc=0.9768

[Epoch 05] train_loss=0.1131 | val_loss=0.1777 | val_mcc=0.8006 | val_f1=0.8302 | val_auroc=0.9758

[Epoch 06] train_loss=0.0951 | val_loss=0.1782 | val_mcc=0.8101 | val_f1=0.8426 | val_auroc=0.9736

[Epoch 07] train_loss=0.0771 | val_loss=0.1928 | val_mcc=0.8073 | val_f1=0.8398 | val_auroc=0.9719

[Epoch 08] train_loss=0.0568 | val_loss=0.2190 | val_mcc=0.7978 | val_f1=0.8306 | val_auroc=0.9699

[Epoch 09] train_loss=0.0478 | val_loss=0.2266 | val_mcc=0.7998 | val_f1=0.8337 | val_auroc=0.9691
[EarlyStop] epoch=9 | best_val_mcc=0.8242
[Test] train1__val_center_bio_prot_None_esmc_600m_PyTorch_Concat | test=Train1Val_Test | MCC=0.8344 | F1=0.8780 | AUROC=0.9754 | AUPRC=0.9451
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_prot_None_esmc_600m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_prot_None_esmc_600m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.8293 | F1=0.9052 | AUROC=0.9841 | AUPRC=0.9843
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_prot_None_esmc_600m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_prot_None_esmc_600m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.4959 | F1=0.7447 | AUROC=0.8067 | AUPRC=0.7919
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_prot_None_esmc_600m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_prot_None_esmc_600m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.6915 | F1=0.8387 | AUROC=0.9223 | AUPRC=0.9053
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 384.
[Test] train1__val_center_bio_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.8266 | F1=0.8729 | AUROC=0.9750 | AUPRC=0.9461
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.8455 | F1=0.9149 | AUROC=0.9864 | AUPRC=0.9871
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.4944 | F1=0.7457 | AUROC=0.8040 | AUPRC=0.7743
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.6648 | F1=0.8262 | AUROC=0.9238 | AUPRC=0.9084
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 243.
[Test] train1__val_center_bio_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.8276 | F1=0.8743 | AUROC=0.9739 | AUPRC=0.9437
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.8498 | F1=0.9187 | AUROC=0.9824 | AUPRC=0.9842
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.4944 | F1=0.7479 | AUROC=0.8026 | AUPRC=0.7934
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.6621 | F1=0.8249 | AUROC=0.9205 | AUPRC=0.9024
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.3189 | val_loss=0.5965 | val_mcc=0.1190 | val_f1=0.0353 | val_auroc=0.8671

[Epoch 02] train_loss=0.2841 | val_loss=0.6880 | val_mcc=0.1099 | val_f1=0.0323 | val_auroc=0.8686

[Epoch 03] train_loss=0.2743 | val_loss=0.6479 | val_mcc=0.1635 | val_f1=0.0665 | val_auroc=0.8640

[Epoch 04] train_loss=0.2674 | val_loss=0.6533 | val_mcc=0.1958 | val_f1=0.0926 | val_auroc=0.8226

[Epoch 05] train_loss=0.2614 | val_loss=0.7042 | val_mcc=0.2184 | val_f1=0.1164 | val_auroc=0.8621

[Epoch 06] train_loss=0.2560 | val_loss=0.6818 | val_mcc=0.2241 | val_f1=0.1244 | val_auroc=0.8422

[Epoch 07] train_loss=0.2503 | val_loss=0.7809 | val_mcc=0.2039 | val_f1=0.1015 | val_auroc=0.8464

[Epoch 08] train_loss=0.2442 | val_loss=0.7716 | val_mcc=0.2198 | val_f1=0.1178 | val_auroc=0.8341

[Epoch 09] train_loss=0.2373 | val_loss=0.8159 | val_mcc=0.2307 | val_f1=0.1323 | val_auroc=0.8237

[Epoch 10] train_loss=0.2312 | val_loss=0.8504 | val_mcc=0.1982 | val_f1=0.0973 | val_auroc=0.8270

[Epoch 11] train_loss=0.2244 | val_loss=0.7999 | val_mcc=0.2336 | val_f1=0.1318 | val_auroc=0.8213

[Epoch 12] train_loss=0.2181 | val_loss=0.8298 | val_mcc=0.2347 | val_f1=0.1338 | val_auroc=0.8193

[Epoch 13] train_loss=0.2105 | val_loss=0.8345 | val_mcc=0.2354 | val_f1=0.1344 | val_auroc=0.7941

[Epoch 14] train_loss=0.2051 | val_loss=0.9398 | val_mcc=0.2050 | val_f1=0.1015 | val_auroc=0.8060

[Epoch 15] train_loss=0.1983 | val_loss=0.8613 | val_mcc=0.2602 | val_f1=0.1605 | val_auroc=0.8049

[Epoch 16] train_loss=0.1931 | val_loss=0.8982 | val_mcc=0.2508 | val_f1=0.1484 | val_auroc=0.7838

[Epoch 17] train_loss=0.1878 | val_loss=0.9628 | val_mcc=0.2420 | val_f1=0.1385 | val_auroc=0.7826

[Epoch 18] train_loss=0.1817 | val_loss=0.9802 | val_mcc=0.2490 | val_f1=0.1489 | val_auroc=0.7919

[Epoch 19] train_loss=0.1770 | val_loss=1.0258 | val_mcc=0.2285 | val_f1=0.1278 | val_auroc=0.7759

[Epoch 20] train_loss=0.1638 | val_loss=1.0184 | val_mcc=0.2588 | val_f1=0.1598 | val_auroc=0.7898

[Epoch 21] train_loss=0.1586 | val_loss=1.0837 | val_mcc=0.2532 | val_f1=0.1540 | val_auroc=0.7941
[EarlyStop] epoch=21 | best_val_mcc=0.2602
[Test] train1__val_center_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_Test | MCC=0.2489 | F1=0.1614 | AUROC=0.8030 | AUPRC=0.7246
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.1912 | F1=0.1436 | AUROC=0.7786 | AUPRC=0.8104
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.1539 | F1=0.1026 | AUROC=0.7351 | AUPRC=0.7470
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.2097 | F1=0.1727 | AUROC=0.7804 | AUPRC=0.7899
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 19.
[Test] train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.6252 | F1=0.6677 | AUROC=0.8657 | AUPRC=0.7878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.5302 | F1=0.6504 | AUROC=0.8166 | AUPRC=0.8301
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.3977 | F1=0.5831 | AUROC=0.7457 | AUPRC=0.7404
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5525 | F1=0.6704 | AUROC=0.8292 | AUPRC=0.8090
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 21.
[Test] train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.3040 | F1=0.2244 | AUROC=0.8668 | AUPRC=0.7823
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.2358 | F1=0.2010 | AUROC=0.8311 | AUPRC=0.8452
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.2208 | F1=0.2107 | AUROC=0.7473 | AUPRC=0.7544
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.2923 | F1=0.2610 | AUROC=0.8267 | AUPRC=0.8282
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.2756 | val_loss=0.4130 | val_mcc=0.5187 | val_f1=0.4950 | val_auroc=0.9126

[Epoch 02] train_loss=0.2334 | val_loss=0.4419 | val_mcc=0.4799 | val_f1=0.4424 | val_auroc=0.9226

[Epoch 03] train_loss=0.2124 | val_loss=0.4527 | val_mcc=0.5100 | val_f1=0.4874 | val_auroc=0.9241

[Epoch 04] train_loss=0.1903 | val_loss=0.4780 | val_mcc=0.4773 | val_f1=0.4512 | val_auroc=0.9195

[Epoch 05] train_loss=0.1651 | val_loss=0.6353 | val_mcc=0.3506 | val_f1=0.2828 | val_auroc=0.9126

[Epoch 06] train_loss=0.1321 | val_loss=0.5885 | val_mcc=0.4902 | val_f1=0.4697 | val_auroc=0.9108

[Epoch 07] train_loss=0.1171 | val_loss=0.6908 | val_mcc=0.4494 | val_f1=0.4125 | val_auroc=0.9081
[EarlyStop] epoch=7 | best_val_mcc=0.5187
[Test] train1__val_center_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_Test | MCC=0.5228 | F1=0.5252 | AUROC=0.9251 | AUPRC=0.8624
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.4641 | F1=0.5325 | AUROC=0.9174 | AUPRC=0.9134
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.3299 | F1=0.4412 | AUROC=0.7886 | AUPRC=0.7871
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.4578 | F1=0.5310 | AUROC=0.8956 | AUPRC=0.8872
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 20.
[Test] train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.6202 | F1=0.6594 | AUROC=0.8669 | AUPRC=0.7878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.5297 | F1=0.6465 | AUROC=0.8315 | AUPRC=0.8379
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.4040 | F1=0.5757 | AUROC=0.7509 | AUPRC=0.7467
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5389 | F1=0.6591 | AUROC=0.8265 | AUPRC=0.8142
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 35.
[Test] train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.3394 | F1=0.2687 | AUROC=0.9044 | AUPRC=0.8318
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.2807 | F1=0.2637 | AUROC=0.8969 | AUPRC=0.8946
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.2200 | F1=0.2196 | AUROC=0.7702 | AUPRC=0.7778
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.3086 | F1=0.2933 | AUROC=0.8700 | AUPRC=0.8597
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.2360 | val_loss=0.5630 | val_mcc=0.2518 | val_f1=0.1459 | val_auroc=0.9593

[Epoch 02] train_loss=0.1840 | val_loss=0.4831 | val_mcc=0.3200 | val_f1=0.2238 | val_auroc=0.9653

[Epoch 03] train_loss=0.1768 | val_loss=0.4602 | val_mcc=0.3784 | val_f1=0.2969 | val_auroc=0.9641

[Epoch 04] train_loss=0.1709 | val_loss=0.5319 | val_mcc=0.3111 | val_f1=0.2140 | val_auroc=0.9630

[Epoch 05] train_loss=0.1655 | val_loss=0.4666 | val_mcc=0.3888 | val_f1=0.3101 | val_auroc=0.9624

[Epoch 06] train_loss=0.1614 | val_loss=0.4623 | val_mcc=0.4214 | val_f1=0.3538 | val_auroc=0.9617

[Epoch 07] train_loss=0.1570 | val_loss=0.4571 | val_mcc=0.4379 | val_f1=0.3769 | val_auroc=0.9572

[Epoch 08] train_loss=0.1530 | val_loss=0.4723 | val_mcc=0.4209 | val_f1=0.3537 | val_auroc=0.9572

[Epoch 09] train_loss=0.1505 | val_loss=0.4229 | val_mcc=0.4717 | val_f1=0.4208 | val_auroc=0.9557

[Epoch 10] train_loss=0.1461 | val_loss=0.5037 | val_mcc=0.4244 | val_f1=0.3583 | val_auroc=0.9480

[Epoch 11] train_loss=0.1416 | val_loss=0.4969 | val_mcc=0.4546 | val_f1=0.3990 | val_auroc=0.9492

[Epoch 12] train_loss=0.1390 | val_loss=0.4235 | val_mcc=0.5161 | val_f1=0.4824 | val_auroc=0.9428

[Epoch 13] train_loss=0.1355 | val_loss=0.4611 | val_mcc=0.4885 | val_f1=0.4463 | val_auroc=0.9416

[Epoch 14] train_loss=0.1313 | val_loss=0.5035 | val_mcc=0.4729 | val_f1=0.4252 | val_auroc=0.9376

[Epoch 15] train_loss=0.1270 | val_loss=0.5250 | val_mcc=0.4904 | val_f1=0.4480 | val_auroc=0.9335

[Epoch 16] train_loss=0.1245 | val_loss=0.5130 | val_mcc=0.4863 | val_f1=0.4421 | val_auroc=0.9397

[Epoch 17] train_loss=0.1166 | val_loss=0.5416 | val_mcc=0.4785 | val_f1=0.4349 | val_auroc=0.9263

[Epoch 18] train_loss=0.1123 | val_loss=0.5354 | val_mcc=0.4975 | val_f1=0.4602 | val_auroc=0.9248
[EarlyStop] epoch=18 | best_val_mcc=0.5161
[Test] train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_Test | MCC=0.5334 | F1=0.5320 | AUROC=0.9351 | AUPRC=0.8841
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.4605 | F1=0.5160 | AUROC=0.9443 | AUPRC=0.9527
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.2781 | F1=0.3626 | AUROC=0.7853 | AUPRC=0.7760
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.4874 | F1=0.5891 | AUROC=0.8693 | AUPRC=0.8512
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 42.
[Test] train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.8067 | F1=0.8536 | AUROC=0.9694 | AUPRC=0.9336
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.8101 | F1=0.8854 | AUROC=0.9809 | AUPRC=0.9830
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.4836 | F1=0.7195 | AUROC=0.8012 | AUPRC=0.7741
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.6895 | F1=0.8351 | AUROC=0.9141 | AUPRC=0.8940
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 24.
[Test] train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.5609 | F1=0.5714 | AUROC=0.9497 | AUPRC=0.8994
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.4576 | F1=0.5180 | AUROC=0.9595 | AUPRC=0.9631
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.3281 | F1=0.4364 | AUROC=0.7875 | AUPRC=0.7827
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_dna_geom_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.5362 | F1=0.6493 | AUROC=0.9002 | AUPRC=0.8814
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.1972 | val_loss=0.4820 | val_mcc=0.4301 | val_f1=0.3651 | val_auroc=0.9631

[Epoch 02] train_loss=0.1550 | val_loss=0.3838 | val_mcc=0.5383 | val_f1=0.5105 | val_auroc=0.9661

[Epoch 03] train_loss=0.1370 | val_loss=0.4370 | val_mcc=0.5106 | val_f1=0.4724 | val_auroc=0.9642

[Epoch 04] train_loss=0.1189 | val_loss=0.3988 | val_mcc=0.5463 | val_f1=0.5244 | val_auroc=0.9598

[Epoch 05] train_loss=0.0995 | val_loss=0.4569 | val_mcc=0.5398 | val_f1=0.5161 | val_auroc=0.9586

[Epoch 06] train_loss=0.0811 | val_loss=0.4707 | val_mcc=0.5920 | val_f1=0.5839 | val_auroc=0.9531

[Epoch 07] train_loss=0.0646 | val_loss=0.6246 | val_mcc=0.5144 | val_f1=0.4819 | val_auroc=0.9455

[Epoch 08] train_loss=0.0515 | val_loss=0.6422 | val_mcc=0.5398 | val_f1=0.5197 | val_auroc=0.9403

[Epoch 09] train_loss=0.0432 | val_loss=0.6591 | val_mcc=0.5644 | val_f1=0.5504 | val_auroc=0.9355

[Epoch 10] train_loss=0.0357 | val_loss=0.6594 | val_mcc=0.5780 | val_f1=0.5670 | val_auroc=0.9297

[Epoch 11] train_loss=0.0250 | val_loss=0.7876 | val_mcc=0.5314 | val_f1=0.5077 | val_auroc=0.9282

[Epoch 12] train_loss=0.0210 | val_loss=0.8247 | val_mcc=0.5360 | val_f1=0.5124 | val_auroc=0.9235
[EarlyStop] epoch=12 | best_val_mcc=0.5920
[Test] train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_Test | MCC=0.6075 | F1=0.6312 | AUROC=0.9529 | AUPRC=0.9065
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.5460 | F1=0.6395 | AUROC=0.9592 | AUPRC=0.9573
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.3555 | F1=0.5000 | AUROC=0.7964 | AUPRC=0.7824
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.5434 | F1=0.6499 | AUROC=0.9079 | AUPRC=0.8969
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 43.
[Test] train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.8135 | F1=0.8582 | AUROC=0.9704 | AUPRC=0.9373
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.8141 | F1=0.8892 | AUROC=0.9815 | AUPRC=0.9837
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.4851 | F1=0.7163 | AUROC=0.8107 | AUPRC=0.7857
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.6962 | F1=0.8373 | AUROC=0.9188 | AUPRC=0.8981
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 27.
[Test] train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.5345 | F1=0.5300 | AUROC=0.9609 | AUPRC=0.9167
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.4605 | F1=0.5160 | AUROC=0.9633 | AUPRC=0.9655
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.2979 | F1=0.3874 | AUROC=0.8000 | AUPRC=0.7890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_center_bio_geom_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.5175 | F1=0.6146 | AUROC=0.9002 | AUPRC=0.8838

================================================================================
[*] POOLING: CLS
================================================================================
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_None_None_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.2900 | val_loss=0.2328 | val_mcc=0.6775 | val_f1=0.7276 | val_auroc=0.9472

[Epoch 02] train_loss=0.2587 | val_loss=0.2261 | val_mcc=0.6867 | val_f1=0.7380 | val_auroc=0.9486

[Epoch 03] train_loss=0.2556 | val_loss=0.2248 | val_mcc=0.6898 | val_f1=0.7411 | val_auroc=0.9491

[Epoch 04] train_loss=0.2530 | val_loss=0.2259 | val_mcc=0.6811 | val_f1=0.7300 | val_auroc=0.9494

[Epoch 05] train_loss=0.2519 | val_loss=0.2235 | val_mcc=0.6901 | val_f1=0.7407 | val_auroc=0.9498

[Epoch 06] train_loss=0.2515 | val_loss=0.2225 | val_mcc=0.6868 | val_f1=0.7355 | val_auroc=0.9504

[Epoch 07] train_loss=0.2503 | val_loss=0.2231 | val_mcc=0.6907 | val_f1=0.7394 | val_auroc=0.9503

[Epoch 08] train_loss=0.2492 | val_loss=0.2221 | val_mcc=0.6907 | val_f1=0.7397 | val_auroc=0.9502

[Epoch 09] train_loss=0.2487 | val_loss=0.2204 | val_mcc=0.6954 | val_f1=0.7475 | val_auroc=0.9508

[Epoch 10] train_loss=0.2483 | val_loss=0.2237 | val_mcc=0.6921 | val_f1=0.7425 | val_auroc=0.9503

[Epoch 11] train_loss=0.2476 | val_loss=0.2214 | val_mcc=0.6925 | val_f1=0.7435 | val_auroc=0.9505

[Epoch 12] train_loss=0.2475 | val_loss=0.2210 | val_mcc=0.6925 | val_f1=0.7435 | val_auroc=0.9507

[Epoch 13] train_loss=0.2470 | val_loss=0.2205 | val_mcc=0.6923 | val_f1=0.7420 | val_auroc=0.9512

[Epoch 14] train_loss=0.2469 | val_loss=0.2207 | val_mcc=0.6962 | val_f1=0.7444 | val_auroc=0.9511

[Epoch 15] train_loss=0.2463 | val_loss=0.2212 | val_mcc=0.6925 | val_f1=0.7427 | val_auroc=0.9508

[Epoch 16] train_loss=0.2461 | val_loss=0.2213 | val_mcc=0.6919 | val_f1=0.7421 | val_auroc=0.9506

[Epoch 17] train_loss=0.2464 | val_loss=0.2218 | val_mcc=0.6894 | val_f1=0.7411 | val_auroc=0.9503

[Epoch 18] train_loss=0.2463 | val_loss=0.2210 | val_mcc=0.6904 | val_f1=0.7412 | val_auroc=0.9507

[Epoch 19] train_loss=0.2458 | val_loss=0.2207 | val_mcc=0.6935 | val_f1=0.7435 | val_auroc=0.9509

[Epoch 20] train_loss=0.2454 | val_loss=0.2212 | val_mcc=0.6921 | val_f1=0.7424 | val_auroc=0.9508
[EarlyStop] epoch=20 | best_val_mcc=0.6962
[Test] train1__val_cls_bio_None_None_PyTorch_Concat | test=Train1Val_Test | MCC=0.7012 | F1=0.7671 | AUROC=0.9424 | AUPRC=0.8705
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_None_None_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_bio_None_None_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.6930 | F1=0.7917 | AUROC=0.9684 | AUPRC=0.9697
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_None_None_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_bio_None_None_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.3222 | F1=0.6012 | AUROC=0.7364 | AUPRC=0.7133
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_None_None_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_bio_None_None_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.5423 | F1=0.7632 | AUROC=0.8677 | AUPRC=0.8508
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 249.
[Test] train1__val_cls_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.7085 | F1=0.7907 | AUROC=0.9439 | AUPRC=0.8760
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.7922 | F1=0.8889 | AUROC=0.9704 | AUPRC=0.9721
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.3767 | F1=0.6964 | AUROC=0.7496 | AUPRC=0.7245
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5301 | F1=0.7641 | AUROC=0.8751 | AUPRC=0.8553
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 294.
[Test] train1__val_cls_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.7099 | F1=0.7914 | AUROC=0.9382 | AUPRC=0.8642
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.7600 | F1=0.8689 | AUROC=0.9662 | AUPRC=0.9676
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.3627 | F1=0.6859 | AUROC=0.7376 | AUPRC=0.7172
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.5237 | F1=0.7612 | AUROC=0.8630 | AUPRC=0.8460
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.3202 | val_loss=0.7410 | val_mcc=0.0431 | val_f1=0.0046 | val_auroc=0.8828

[Epoch 02] train_loss=0.2931 | val_loss=0.7621 | val_mcc=0.0466 | val_f1=0.0053 | val_auroc=0.8870

[Epoch 03] train_loss=0.2892 | val_loss=0.8173 | val_mcc=0.0528 | val_f1=0.0069 | val_auroc=0.8888

[Epoch 04] train_loss=0.2870 | val_loss=0.8048 | val_mcc=0.0528 | val_f1=0.0069 | val_auroc=0.8898

[Epoch 05] train_loss=0.2866 | val_loss=0.8289 | val_mcc=0.0352 | val_f1=0.0031 | val_auroc=0.8894

[Epoch 06] train_loss=0.2851 | val_loss=0.8910 | val_mcc=0.0305 | val_f1=0.0023 | val_auroc=0.8903

[Epoch 07] train_loss=0.2838 | val_loss=0.9315 | val_mcc=0.0249 | val_f1=0.0015 | val_auroc=0.8887

[Epoch 08] train_loss=0.2828 | val_loss=0.9019 | val_mcc=0.0249 | val_f1=0.0015 | val_auroc=0.8902

[Epoch 09] train_loss=0.2823 | val_loss=0.8995 | val_mcc=0.0249 | val_f1=0.0015 | val_auroc=0.8905
[EarlyStop] epoch=9 | best_val_mcc=0.0528
[Test] train1__val_cls_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test | MCC=0.0469 | F1=0.0060 | AUROC=0.9070 | AUPRC=0.8332
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.0000 | F1=0.0000 | AUROC=0.8635 | AUPRC=0.8767
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.0275 | F1=0.0030 | AUROC=0.7725 | AUPRC=0.7768
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.0402 | F1=0.0059 | AUROC=0.8713 | AUPRC=0.8662
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 26.
[Test] train1__val_cls_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.5128 | F1=0.5247 | AUROC=0.8974 | AUPRC=0.8226
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.4680 | F1=0.5533 | AUROC=0.8692 | AUPRC=0.8819
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.3142 | F1=0.4078 | AUROC=0.7705 | AUPRC=0.7703
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.4425 | F1=0.5322 | AUROC=0.8693 | AUPRC=0.8574
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 11.
[Test] train1__val_cls_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.2493 | F1=0.1556 | AUROC=0.8490 | AUPRC=0.7454
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.1939 | F1=0.1340 | AUROC=0.8291 | AUPRC=0.8294
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.1539 | F1=0.1026 | AUROC=0.7265 | AUPRC=0.7277
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.2298 | F1=0.1762 | AUROC=0.8371 | AUPRC=0.8210
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_Test
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_Test | MCC=0.0643 | F1=0.1241 | AUROC=0.6085 | AUPRC=0.3472
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.0530 | F1=0.1461 | AUROC=0.5846 | AUPRC=0.5619
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.0620 | F1=0.1296 | AUROC=0.5440 | AUPRC=0.5427
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.0646 | F1=0.1434 | AUROC=0.5929 | AUPRC=0.5258
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_Test
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.1071 | F1=0.3043 | AUROC=0.5949 | AUPRC=0.3453
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.1168 | F1=0.3629 | AUROC=0.6082 | AUPRC=0.6077
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.0345 | F1=0.3271 | AUROC=0.5286 | AUPRC=0.5164
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.0925 | F1=0.3547 | AUROC=0.5915 | AUPRC=0.5221
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.0687 | F1=0.3097 | AUROC=0.5635 | AUPRC=0.3251
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.0827 | F1=0.3665 | AUROC=0.5595 | AUPRC=0.5348
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.0156 | F1=0.3823 | AUROC=0.4977 | AUPRC=0.5143
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.0646 | F1=0.3736 | AUROC=0.5458 | AUPRC=0.4969
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_Test
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_Test | MCC=0.6471 | F1=0.7222 | AUROC=0.9142 | AUPRC=0.8299
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.5874 | F1=0.7437 | AUROC=0.8992 | AUPRC=0.8987
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt

[Epoch 01] train_loss=0.2934 | val_loss=0.2343 | val_mcc=0.6770 | val_f1=0.7264 | val_auroc=0.9462

[Epoch 02] train_loss=0.2646 | val_loss=0.2297 | val_mcc=0.6788 | val_f1=0.7283 | val_auroc=0.9475

[Epoch 03] train_loss=0.2592 | val_loss=0.2288 | val_mcc=0.6793 | val_f1=0.7305 | val_auroc=0.9479

[Epoch 04] train_loss=0.2559 | val_loss=0.2246 | val_mcc=0.6865 | val_f1=0.7378 | val_auroc=0.9483

[Epoch 05] train_loss=0.2533 | val_loss=0.2393 | val_mcc=0.6541 | val_f1=0.6970 | val_auroc=0.9479

[Epoch 06] train_loss=0.2508 | val_loss=0.2282 | val_mcc=0.6680 | val_f1=0.7151 | val_auroc=0.9491

[Epoch 07] train_loss=0.2483 | val_loss=0.2280 | val_mcc=0.6754 | val_f1=0.7216 | val_auroc=0.9491

[Epoch 08] train_loss=0.2451 | val_loss=0.2266 | val_mcc=0.6815 | val_f1=0.7279 | val_auroc=0.9495

[Epoch 09] train_loss=0.2408 | val_loss=0.2281 | val_mcc=0.6746 | val_f1=0.7207 | val_auroc=0.9496

[Epoch 10] train_loss=0.2389 | val_loss=0.2303 | val_mcc=0.6725 | val_f1=0.7179 | val_auroc=0.9492
[EarlyStop] epoch=10 | best_val_mcc=0.6865
[Test] train1__val_cls_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_Test | MCC=0.6960 | F1=0.7671 | AUROC=0.9387 | AUPRC=0.8661
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.6865 | F1=0.7918 | AUROC=0.9691 | AUPRC=0.9702
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.3094 | F1=0.6063 | AUROC=0.7312 | AUPRC=0.7039
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.5297 | F1=0.7602 | AUROC=0.8515 | AUPRC=0.8127
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 383.
[Test] train1__val_cls_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.7208 | F1=0.7972 | AUROC=0.9454 | AUPRC=0.8785
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.7571 | F1=0.8603 | AUROC=0.9689 | AUPRC=0.9724
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.3699 | F1=0.6789 | AUROC=0.7503 | AUPRC=0.7271
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5252 | F1=0.7614 | AUROC=0.8689 | AUPRC=0.8393
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 241.
[Test] train1__val_cls_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.7007 | F1=0.7841 | AUROC=0.9407 | AUPRC=0.8698
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.7513 | F1=0.8571 | AUROC=0.9664 | AUPRC=0.9678
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.3401 | F1=0.6741 | AUROC=0.7365 | AUPRC=0.7207
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.5199 | F1=0.7594 | AUROC=0.8605 | AUPRC=0.8327
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.2502 | val_loss=0.1941 | val_mcc=0.7439 | val_f1=0.7811 | val_auroc=0.9651

[Epoch 02] train_loss=0.2058 | val_loss=0.1743 | val_mcc=0.7748 | val_f1=0.8127 | val_auroc=0.9698

[Epoch 03] train_loss=0.1867 | val_loss=0.1637 | val_mcc=0.7900 | val_f1=0.8271 | val_auroc=0.9723

[Epoch 04] train_loss=0.1707 | val_loss=0.1653 | val_mcc=0.7855 | val_f1=0.8207 | val_auroc=0.9730

[Epoch 05] train_loss=0.1557 | val_loss=0.1752 | val_mcc=0.7747 | val_f1=0.8062 | val_auroc=0.9736

[Epoch 06] train_loss=0.1421 | val_loss=0.1652 | val_mcc=0.8011 | val_f1=0.8375 | val_auroc=0.9721

[Epoch 07] train_loss=0.1295 | val_loss=0.1842 | val_mcc=0.7762 | val_f1=0.8105 | val_auroc=0.9719

[Epoch 08] train_loss=0.1168 | val_loss=0.1885 | val_mcc=0.7884 | val_f1=0.8232 | val_auroc=0.9709

[Epoch 09] train_loss=0.1050 | val_loss=0.1910 | val_mcc=0.7836 | val_f1=0.8199 | val_auroc=0.9668

[Epoch 10] train_loss=0.0963 | val_loss=0.2053 | val_mcc=0.7877 | val_f1=0.8243 | val_auroc=0.9655

[Epoch 11] train_loss=0.0789 | val_loss=0.2170 | val_mcc=0.7785 | val_f1=0.8165 | val_auroc=0.9642

[Epoch 12] train_loss=0.0718 | val_loss=0.2295 | val_mcc=0.7794 | val_f1=0.8158 | val_auroc=0.9634
[EarlyStop] epoch=12 | best_val_mcc=0.8011
[Test] train1__val_cls_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_Test | MCC=0.8118 | F1=0.8615 | AUROC=0.9685 | AUPRC=0.9289
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.8165 | F1=0.8968 | AUROC=0.9804 | AUPRC=0.9817
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.4855 | F1=0.7384 | AUROC=0.8000 | AUPRC=0.7766
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.6418 | F1=0.8143 | AUROC=0.9035 | AUPRC=0.8639
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 350.
[Test] train1__val_cls_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.8092 | F1=0.8609 | AUROC=0.9696 | AUPRC=0.9318
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.8420 | F1=0.9108 | AUROC=0.9822 | AUPRC=0.9836
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.4899 | F1=0.7440 | AUROC=0.7940 | AUPRC=0.7664
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.6396 | F1=0.8143 | AUROC=0.9174 | AUPRC=0.8984
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 303.
[Test] train1__val_cls_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.8102 | F1=0.8614 | AUROC=0.9687 | AUPRC=0.9301
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.8382 | F1=0.9096 | AUROC=0.9828 | AUPRC=0.9842
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.4629 | F1=0.7320 | AUROC=0.7919 | AUPRC=0.7725
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.6407 | F1=0.8148 | AUROC=0.9112 | AUPRC=0.8900
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.3260 | val_loss=0.5843 | val_mcc=0.0610 | val_f1=0.0091 | val_auroc=0.8605

[Epoch 02] train_loss=0.2972 | val_loss=0.6509 | val_mcc=0.0498 | val_f1=0.0061 | val_auroc=0.8736

[Epoch 03] train_loss=0.2921 | val_loss=0.7012 | val_mcc=0.0498 | val_f1=0.0061 | val_auroc=0.8681

[Epoch 04] train_loss=0.2889 | val_loss=0.7177 | val_mcc=0.0498 | val_f1=0.0061 | val_auroc=0.8575

[Epoch 05] train_loss=0.2873 | val_loss=0.8209 | val_mcc=0.0610 | val_f1=0.0091 | val_auroc=0.8665

[Epoch 06] train_loss=0.2831 | val_loss=0.8329 | val_mcc=0.0528 | val_f1=0.0069 | val_auroc=0.8643

[Epoch 07] train_loss=0.2807 | val_loss=0.8213 | val_mcc=0.0557 | val_f1=0.0076 | val_auroc=0.8614
[EarlyStop] epoch=7 | best_val_mcc=0.0610
[Test] train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test | MCC=0.0555 | F1=0.0084 | AUROC=0.8773 | AUPRC=0.7938
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.0000 | F1=0.0000 | AUROC=0.8295 | AUPRC=0.8509
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.0275 | F1=0.0030 | AUROC=0.7447 | AUPRC=0.7596
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.0493 | F1=0.0089 | AUROC=0.8501 | AUPRC=0.8439
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 21.
[Test] train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.5738 | F1=0.6061 | AUROC=0.8883 | AUPRC=0.8145
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.5080 | F1=0.6148 | AUROC=0.8653 | AUPRC=0.8823
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.3365 | F1=0.4802 | AUROC=0.7659 | AUPRC=0.7664
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5026 | F1=0.6161 | AUROC=0.8513 | AUPRC=0.8516
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 14.
[Test] train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.0985 | F1=0.0262 | AUROC=0.8265 | AUPRC=0.6964
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.0764 | F1=0.0227 | AUROC=0.7997 | AUPRC=0.8025
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.0828 | F1=0.0267 | AUROC=0.7132 | AUPRC=0.7165
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.0856 | F1=0.0264 | AUROC=0.7925 | AUPRC=0.7777
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.3117 | val_loss=0.6442 | val_mcc=0.1743 | val_f1=0.0784 | val_auroc=0.8852

[Epoch 02] train_loss=0.2720 | val_loss=0.6426 | val_mcc=0.2390 | val_f1=0.1396 | val_auroc=0.8966

[Epoch 03] train_loss=0.2570 | val_loss=0.7049 | val_mcc=0.1903 | val_f1=0.0897 | val_auroc=0.8984

[Epoch 04] train_loss=0.2421 | val_loss=0.7136 | val_mcc=0.2299 | val_f1=0.1291 | val_auroc=0.8951

[Epoch 05] train_loss=0.2274 | val_loss=0.8574 | val_mcc=0.1603 | val_f1=0.0678 | val_auroc=0.8913

[Epoch 06] train_loss=0.2118 | val_loss=0.8281 | val_mcc=0.2186 | val_f1=0.1184 | val_auroc=0.8863

[Epoch 07] train_loss=0.1899 | val_loss=0.8501 | val_mcc=0.2336 | val_f1=0.1293 | val_auroc=0.8878

[Epoch 08] train_loss=0.1787 | val_loss=0.8251 | val_mcc=0.2857 | val_f1=0.1919 | val_auroc=0.8814

[Epoch 09] train_loss=0.1699 | val_loss=0.9097 | val_mcc=0.2591 | val_f1=0.1617 | val_auroc=0.8864

[Epoch 10] train_loss=0.1590 | val_loss=0.9343 | val_mcc=0.2522 | val_f1=0.1545 | val_auroc=0.8768

[Epoch 11] train_loss=0.1513 | val_loss=0.9925 | val_mcc=0.2466 | val_f1=0.1481 | val_auroc=0.8680

[Epoch 12] train_loss=0.1429 | val_loss=1.0001 | val_mcc=0.2559 | val_f1=0.1560 | val_auroc=0.8709

[Epoch 13] train_loss=0.1305 | val_loss=1.0313 | val_mcc=0.2607 | val_f1=0.1671 | val_auroc=0.8640

[Epoch 14] train_loss=0.1256 | val_loss=1.1211 | val_mcc=0.2451 | val_f1=0.1449 | val_auroc=0.8642
[EarlyStop] epoch=14 | best_val_mcc=0.2857
[Test] train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test | MCC=0.2815 | F1=0.2055 | AUROC=0.8992 | AUPRC=0.8047
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.2132 | F1=0.1587 | AUROC=0.8625 | AUPRC=0.8532
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.1528 | F1=0.1409 | AUROC=0.7656 | AUPRC=0.7443
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.2361 | F1=0.1952 | AUROC=0.8615 | AUPRC=0.8378
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 23.
[Test] train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.5835 | F1=0.6197 | AUROC=0.8943 | AUPRC=0.8198
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.5133 | F1=0.6284 | AUROC=0.8599 | AUPRC=0.8704
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.3520 | F1=0.5042 | AUROC=0.7720 | AUPRC=0.7633
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5198 | F1=0.6377 | AUROC=0.8658 | AUPRC=0.8591
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 13.
[Test] train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.1763 | F1=0.0810 | AUROC=0.8723 | AUPRC=0.7781
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.1491 | F1=0.0826 | AUROC=0.8426 | AUPRC=0.8465
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.0996 | F1=0.0384 | AUROC=0.7367 | AUPRC=0.7343
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.1800 | F1=0.1097 | AUROC=0.8491 | AUPRC=0.8326
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.2453 | val_loss=0.5210 | val_mcc=0.2176 | val_f1=0.1157 | val_auroc=0.9585

[Epoch 02] train_loss=0.1996 | val_loss=0.4805 | val_mcc=0.2842 | val_f1=0.1825 | val_auroc=0.9616

[Epoch 03] train_loss=0.1935 | val_loss=0.6236 | val_mcc=0.1533 | val_f1=0.0600 | val_auroc=0.9603

[Epoch 04] train_loss=0.1901 | val_loss=0.5854 | val_mcc=0.1895 | val_f1=0.0890 | val_auroc=0.9595

[Epoch 05] train_loss=0.1864 | val_loss=0.5790 | val_mcc=0.2048 | val_f1=0.0995 | val_auroc=0.9577

[Epoch 06] train_loss=0.1851 | val_loss=0.6204 | val_mcc=0.1623 | val_f1=0.0637 | val_auroc=0.9609

[Epoch 07] train_loss=0.1816 | val_loss=0.6022 | val_mcc=0.1873 | val_f1=0.0863 | val_auroc=0.9602

[Epoch 08] train_loss=0.1806 | val_loss=0.5836 | val_mcc=0.2513 | val_f1=0.1496 | val_auroc=0.9603
[EarlyStop] epoch=8 | best_val_mcc=0.2842
[Test] train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test | MCC=0.3152 | F1=0.2367 | AUROC=0.9574 | AUPRC=0.9089
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.2610 | F1=0.2245 | AUROC=0.9657 | AUPRC=0.9681
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.1910 | F1=0.1448 | AUROC=0.7834 | AUPRC=0.7762
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.2970 | F1=0.2861 | AUROC=0.9081 | AUPRC=0.8865
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 37.
[Test] train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.7897 | F1=0.8407 | AUROC=0.9658 | AUPRC=0.9232
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.7985 | F1=0.8790 | AUROC=0.9767 | AUPRC=0.9802
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.4554 | F1=0.6984 | AUROC=0.8035 | AUPRC=0.7826
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.7084 | F1=0.8450 | AUROC=0.9175 | AUPRC=0.8939
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 17.
[Test] train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.2728 | F1=0.1885 | AUROC=0.9282 | AUPRC=0.8708
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.2242 | F1=0.1732 | AUROC=0.9189 | AUPRC=0.9267
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.1614 | F1=0.1106 | AUROC=0.7651 | AUPRC=0.7585
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.2588 | F1=0.2347 | AUROC=0.8799 | AUPRC=0.8523
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.2350 | val_loss=0.5333 | val_mcc=0.2645 | val_f1=0.1626 | val_auroc=0.9553

[Epoch 02] train_loss=0.1855 | val_loss=0.5437 | val_mcc=0.3121 | val_f1=0.2153 | val_auroc=0.9595

[Epoch 03] train_loss=0.1726 | val_loss=0.4772 | val_mcc=0.4031 | val_f1=0.3321 | val_auroc=0.9628

[Epoch 04] train_loss=0.1613 | val_loss=0.4685 | val_mcc=0.4448 | val_f1=0.3895 | val_auroc=0.9597

[Epoch 05] train_loss=0.1511 | val_loss=0.4920 | val_mcc=0.4421 | val_f1=0.3844 | val_auroc=0.9627

[Epoch 06] train_loss=0.1376 | val_loss=0.5149 | val_mcc=0.4097 | val_f1=0.3405 | val_auroc=0.9528

[Epoch 07] train_loss=0.1268 | val_loss=0.5005 | val_mcc=0.4681 | val_f1=0.4191 | val_auroc=0.9534

[Epoch 08] train_loss=0.1156 | val_loss=0.6164 | val_mcc=0.4119 | val_f1=0.3462 | val_auroc=0.9504

[Epoch 09] train_loss=0.1053 | val_loss=0.6452 | val_mcc=0.4452 | val_f1=0.3880 | val_auroc=0.9423

[Epoch 10] train_loss=0.0944 | val_loss=0.7901 | val_mcc=0.3535 | val_f1=0.2685 | val_auroc=0.9459

[Epoch 11] train_loss=0.0861 | val_loss=0.7816 | val_mcc=0.3887 | val_f1=0.3162 | val_auroc=0.9339

[Epoch 12] train_loss=0.0697 | val_loss=0.6964 | val_mcc=0.4614 | val_f1=0.4109 | val_auroc=0.9319

[Epoch 13] train_loss=0.0629 | val_loss=0.8155 | val_mcc=0.4255 | val_f1=0.3658 | val_auroc=0.9280
[EarlyStop] epoch=13 | best_val_mcc=0.4681
[Test] train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test | MCC=0.4398 | F1=0.4088 | AUROC=0.9538 | AUPRC=0.8978
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.3895 | F1=0.4146 | AUROC=0.9512 | AUPRC=0.9535
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.2507 | F1=0.3252 | AUROC=0.8022 | AUPRC=0.7741
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.3906 | F1=0.4475 | AUROC=0.8944 | AUPRC=0.8673
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 44.
[Test] train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.7869 | F1=0.8376 | AUROC=0.9678 | AUPRC=0.9244
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.7859 | F1=0.8673 | AUROC=0.9768 | AUPRC=0.9804
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.4487 | F1=0.6884 | AUROC=0.8051 | AUPRC=0.7835
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.7124 | F1=0.8470 | AUROC=0.9199 | AUPRC=0.8986
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 19.
[Test] train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.3466 | F1=0.2817 | AUROC=0.9380 | AUPRC=0.8727
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.3029 | F1=0.2857 | AUROC=0.9342 | AUPRC=0.9359
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.1821 | F1=0.1877 | AUROC=0.8019 | AUPRC=0.7770
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_cls_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.3387 | F1=0.3590 | AUROC=0.8941 | AUPRC=0.8682

================================================================================
[*] POOLING: MEAN
================================================================================
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_None_None_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.2891 | val_loss=0.2326 | val_mcc=0.6747 | val_f1=0.7246 | val_auroc=0.9477

[Epoch 02] train_loss=0.2589 | val_loss=0.2234 | val_mcc=0.6892 | val_f1=0.7424 | val_auroc=0.9493

[Epoch 03] train_loss=0.2555 | val_loss=0.2239 | val_mcc=0.6871 | val_f1=0.7394 | val_auroc=0.9493

[Epoch 04] train_loss=0.2531 | val_loss=0.2221 | val_mcc=0.6966 | val_f1=0.7483 | val_auroc=0.9499

[Epoch 05] train_loss=0.2516 | val_loss=0.2230 | val_mcc=0.6833 | val_f1=0.7345 | val_auroc=0.9500

[Epoch 06] train_loss=0.2504 | val_loss=0.2216 | val_mcc=0.6913 | val_f1=0.7423 | val_auroc=0.9504

[Epoch 07] train_loss=0.2495 | val_loss=0.2234 | val_mcc=0.6838 | val_f1=0.7342 | val_auroc=0.9500

[Epoch 08] train_loss=0.2492 | val_loss=0.2209 | val_mcc=0.6948 | val_f1=0.7454 | val_auroc=0.9505

[Epoch 09] train_loss=0.2482 | val_loss=0.2213 | val_mcc=0.6873 | val_f1=0.7381 | val_auroc=0.9506

[Epoch 10] train_loss=0.2481 | val_loss=0.2218 | val_mcc=0.6894 | val_f1=0.7383 | val_auroc=0.9509
[EarlyStop] epoch=10 | best_val_mcc=0.6966
[Test] train1__val_mean_bio_None_None_PyTorch_Concat | test=Train1Val_Test | MCC=0.7015 | F1=0.7719 | AUROC=0.9414 | AUPRC=0.8694
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_None_None_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_bio_None_None_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.7115 | F1=0.8081 | AUROC=0.9691 | AUPRC=0.9707
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_None_None_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_bio_None_None_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.3114 | F1=0.6113 | AUROC=0.7322 | AUPRC=0.7073
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_None_None_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_bio_None_None_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.5227 | F1=0.7562 | AUROC=0.8633 | AUPRC=0.8406
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 229.
[Test] train1__val_mean_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.7130 | F1=0.7940 | AUROC=0.9447 | AUPRC=0.8768
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.7996 | F1=0.8945 | AUROC=0.9688 | AUPRC=0.9706
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.3724 | F1=0.6953 | AUROC=0.7504 | AUPRC=0.7266
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_None_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5301 | F1=0.7640 | AUROC=0.8753 | AUPRC=0.8551
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 314.
[Test] train1__val_mean_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.7047 | F1=0.7870 | AUROC=0.9379 | AUPRC=0.8659
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.7826 | F1=0.8779 | AUROC=0.9664 | AUPRC=0.9689
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.3491 | F1=0.6780 | AUROC=0.7336 | AUPRC=0.7140
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_bio_None_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.5220 | F1=0.7603 | AUROC=0.8636 | AUPRC=0.8441
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.3249 | val_loss=0.7705 | val_mcc=0.0498 | val_f1=0.0061 | val_auroc=0.8762

[Epoch 02] train_loss=0.2921 | val_loss=0.8411 | val_mcc=0.0498 | val_f1=0.0061 | val_auroc=0.8803

[Epoch 03] train_loss=0.2893 | val_loss=0.8781 | val_mcc=0.0498 | val_f1=0.0061 | val_auroc=0.8825

[Epoch 04] train_loss=0.2868 | val_loss=0.9158 | val_mcc=0.0431 | val_f1=0.0046 | val_auroc=0.8842

[Epoch 05] train_loss=0.2857 | val_loss=0.9480 | val_mcc=0.0352 | val_f1=0.0031 | val_auroc=0.8838

[Epoch 06] train_loss=0.2841 | val_loss=0.9334 | val_mcc=0.0431 | val_f1=0.0046 | val_auroc=0.8846

[Epoch 07] train_loss=0.2836 | val_loss=0.9156 | val_mcc=0.0431 | val_f1=0.0046 | val_auroc=0.8846
[EarlyStop] epoch=7 | best_val_mcc=0.0498
[Test] train1__val_mean_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test | MCC=0.0296 | F1=0.0024 | AUROC=0.8949 | AUPRC=0.8097
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.0381 | F1=0.0057 | AUROC=0.8491 | AUPRC=0.8684
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.0389 | F1=0.0060 | AUROC=0.7585 | AUPRC=0.7638
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.0570 | F1=0.0118 | AUROC=0.8609 | AUPRC=0.8520
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 25.
[Test] train1__val_mean_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.5617 | F1=0.5833 | AUROC=0.8882 | AUPRC=0.8190
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.5144 | F1=0.5972 | AUROC=0.8458 | AUPRC=0.8776
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.3291 | F1=0.4454 | AUROC=0.7573 | AUPRC=0.7610
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.4825 | F1=0.5887 | AUROC=0.8596 | AUPRC=0.8557
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 12.
[Test] train1__val_mean_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.1400 | F1=0.0540 | AUROC=0.8600 | AUPRC=0.7641
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.1013 | F1=0.0394 | AUROC=0.8267 | AUPRC=0.8392
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.0780 | F1=0.0238 | AUROC=0.7377 | AUPRC=0.7370
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.1248 | F1=0.0550 | AUROC=0.8382 | AUPRC=0.8251
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_Test
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_Test | MCC=0.4577 | F1=0.5593 | AUROC=0.8387 | AUPRC=0.6828
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.4124 | F1=0.6011 | AUROC=0.8162 | AUPRC=0.8026
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.2809 | F1=0.5045 | AUROC=0.7177 | AUPRC=0.7056
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.3859 | F1=0.5804 | AUROC=0.7960 | AUPRC=0.7473
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_Test
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.4292 | F1=0.5656 | AUROC=0.8046 | AUPRC=0.6311
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.4245 | F1=0.6379 | AUROC=0.7804 | AUPRC=0.7860
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.2482 | F1=0.5504 | AUROC=0.6795 | AUPRC=0.6733
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.3831 | F1=0.6205 | AUROC=0.7658 | AUPRC=0.7270
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.3459 | F1=0.5126 | AUROC=0.7397 | AUPRC=0.5572
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.3122 | F1=0.5749 | AUROC=0.7243 | AUPRC=0.7336
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.1860 | F1=0.5032 | AUROC=0.6271 | AUPRC=0.6280
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.2834 | F1=0.5475 | AUROC=0.7175 | AUPRC=0.6804
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_Test
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_Test | MCC=0.6801 | F1=0.7540 | AUROC=0.9268 | AUPRC=0.8512
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.5979 | F1=0.7645 | AUROC=0.9130 | AUPRC=0.9085
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.2901 | val_loss=0.2312 | val_mcc=0.6892 | val_f1=0.7369 | val_auroc=0.9479

[Epoch 02] train_loss=0.2578 | val_loss=0.2177 | val_mcc=0.7058 | val_f1=0.7573 | val_auroc=0.9515

[Epoch 03] train_loss=0.2514 | val_loss=0.2280 | val_mcc=0.6882 | val_f1=0.7333 | val_auroc=0.9503

[Epoch 04] train_loss=0.2456 | val_loss=0.2175 | val_mcc=0.6957 | val_f1=0.7420 | val_auroc=0.9540

[Epoch 05] train_loss=0.2406 | val_loss=0.2115 | val_mcc=0.7170 | val_f1=0.7637 | val_auroc=0.9552

[Epoch 06] train_loss=0.2353 | val_loss=0.2134 | val_mcc=0.7076 | val_f1=0.7496 | val_auroc=0.9569

[Epoch 07] train_loss=0.2299 | val_loss=0.2123 | val_mcc=0.6988 | val_f1=0.7426 | val_auroc=0.9569

[Epoch 08] train_loss=0.2258 | val_loss=0.2059 | val_mcc=0.7250 | val_f1=0.7692 | val_auroc=0.9584

[Epoch 09] train_loss=0.2214 | val_loss=0.2089 | val_mcc=0.7108 | val_f1=0.7537 | val_auroc=0.9586

[Epoch 10] train_loss=0.2171 | val_loss=0.2121 | val_mcc=0.7029 | val_f1=0.7439 | val_auroc=0.9590

[Epoch 11] train_loss=0.2135 | val_loss=0.2015 | val_mcc=0.7344 | val_f1=0.7782 | val_auroc=0.9597

[Epoch 12] train_loss=0.2101 | val_loss=0.2021 | val_mcc=0.7296 | val_f1=0.7704 | val_auroc=0.9617

[Epoch 13] train_loss=0.2061 | val_loss=0.1976 | val_mcc=0.7337 | val_f1=0.7759 | val_auroc=0.9618

[Epoch 14] train_loss=0.2029 | val_loss=0.2000 | val_mcc=0.7360 | val_f1=0.7800 | val_auroc=0.9595

[Epoch 15] train_loss=0.1994 | val_loss=0.1966 | val_mcc=0.7431 | val_f1=0.7867 | val_auroc=0.9614

[Epoch 16] train_loss=0.1965 | val_loss=0.2035 | val_mcc=0.7354 | val_f1=0.7783 | val_auroc=0.9601

[Epoch 17] train_loss=0.1930 | val_loss=0.2035 | val_mcc=0.7320 | val_f1=0.7731 | val_auroc=0.9616

[Epoch 18] train_loss=0.1911 | val_loss=0.2027 | val_mcc=0.7360 | val_f1=0.7792 | val_auroc=0.9608

[Epoch 19] train_loss=0.1871 | val_loss=0.2069 | val_mcc=0.7317 | val_f1=0.7704 | val_auroc=0.9611

[Epoch 20] train_loss=0.1787 | val_loss=0.2072 | val_mcc=0.7408 | val_f1=0.7832 | val_auroc=0.9593

[Epoch 21] train_loss=0.1759 | val_loss=0.2182 | val_mcc=0.7170 | val_f1=0.7579 | val_auroc=0.9595
[EarlyStop] epoch=21 | best_val_mcc=0.7431
[Test] train1__val_mean_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_Test | MCC=0.7496 | F1=0.8101 | AUROC=0.9560 | AUPRC=0.8962
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.7693 | F1=0.8571 | AUROC=0.9789 | AUPRC=0.9802
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.3986 | F1=0.6645 | AUROC=0.7716 | AUPRC=0.7529
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_bio_dna_nt_v3_650m_None_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.5866 | F1=0.7869 | AUROC=0.8787 | AUPRC=0.8420
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 419.
[Test] train1__val_mean_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.7723 | F1=0.8343 | AUROC=0.9601 | AUPRC=0.9035
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.8555 | F1=0.9188 | AUROC=0.9840 | AUPRC=0.9856
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.4525 | F1=0.7216 | AUROC=0.7765 | AUPRC=0.7574
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_dna_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5899 | F1=0.7909 | AUROC=0.8883 | AUPRC=0.8631
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 332.
[Test] train1__val_mean_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.7248 | F1=0.8013 | AUROC=0.9479 | AUPRC=0.8822
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.7741 | F1=0.8767 | AUROC=0.9702 | AUPRC=0.9705
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.3999 | F1=0.7006 | AUROC=0.7606 | AUPRC=0.7374
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_bio_dna_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.5348 | F1=0.7659 | AUROC=0.8713 | AUPRC=0.8395
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.2275 | val_loss=0.1688 | val_mcc=0.7846 | val_f1=0.8228 | val_auroc=0.9700

[Epoch 02] train_loss=0.1881 | val_loss=0.1615 | val_mcc=0.7947 | val_f1=0.8279 | val_auroc=0.9735

[Epoch 03] train_loss=0.1702 | val_loss=0.1667 | val_mcc=0.7983 | val_f1=0.8300 | val_auroc=0.9736

[Epoch 04] train_loss=0.1567 | val_loss=0.1608 | val_mcc=0.7984 | val_f1=0.8323 | val_auroc=0.9740

[Epoch 05] train_loss=0.1444 | val_loss=0.1748 | val_mcc=0.7880 | val_f1=0.8204 | val_auroc=0.9738

[Epoch 06] train_loss=0.1317 | val_loss=0.1765 | val_mcc=0.7925 | val_f1=0.8252 | val_auroc=0.9717

[Epoch 07] train_loss=0.1195 | val_loss=0.1778 | val_mcc=0.8011 | val_f1=0.8361 | val_auroc=0.9702

[Epoch 08] train_loss=0.1082 | val_loss=0.1860 | val_mcc=0.7914 | val_f1=0.8270 | val_auroc=0.9709

[Epoch 09] train_loss=0.0970 | val_loss=0.2010 | val_mcc=0.7874 | val_f1=0.8209 | val_auroc=0.9675

[Epoch 10] train_loss=0.0881 | val_loss=0.2139 | val_mcc=0.7760 | val_f1=0.8102 | val_auroc=0.9662

[Epoch 11] train_loss=0.0800 | val_loss=0.2129 | val_mcc=0.7920 | val_f1=0.8281 | val_auroc=0.9660

[Epoch 12] train_loss=0.0638 | val_loss=0.2316 | val_mcc=0.7885 | val_f1=0.8238 | val_auroc=0.9637

[Epoch 13] train_loss=0.0562 | val_loss=0.2386 | val_mcc=0.7950 | val_f1=0.8316 | val_auroc=0.9617
[EarlyStop] epoch=13 | best_val_mcc=0.8011
[Test] train1__val_mean_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_Test | MCC=0.8098 | F1=0.8580 | AUROC=0.9676 | AUPRC=0.9328
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.7959 | F1=0.8801 | AUROC=0.9811 | AUPRC=0.9829
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.4783 | F1=0.7241 | AUROC=0.8039 | AUPRC=0.7838
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_bio_prot_None_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.6837 | F1=0.8335 | AUROC=0.9133 | AUPRC=0.8945
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 317.
[Test] train1__val_mean_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.8095 | F1=0.8605 | AUROC=0.9704 | AUPRC=0.9337
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.8414 | F1=0.9110 | AUROC=0.9827 | AUPRC=0.9842
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.4644 | F1=0.7298 | AUROC=0.7959 | AUPRC=0.7711
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.6596 | F1=0.8238 | AUROC=0.9174 | AUPRC=0.9032
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 239.
[Test] train1__val_mean_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.8221 | F1=0.8702 | AUROC=0.9699 | AUPRC=0.9374
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.8414 | F1=0.9140 | AUROC=0.9778 | AUPRC=0.9779
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.4885 | F1=0.7453 | AUROC=0.8007 | AUPRC=0.7804
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_bio_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.6594 | F1=0.8238 | AUROC=0.9176 | AUPRC=0.9015
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.3243 | val_loss=0.6383 | val_mcc=0.0682 | val_f1=0.0114 | val_auroc=0.8773

[Epoch 02] train_loss=0.2945 | val_loss=0.7547 | val_mcc=0.0635 | val_f1=0.0099 | val_auroc=0.8762

[Epoch 03] train_loss=0.2887 | val_loss=0.7798 | val_mcc=0.1314 | val_f1=0.0427 | val_auroc=0.8557

[Epoch 04] train_loss=0.2833 | val_loss=0.7784 | val_mcc=0.1384 | val_f1=0.0471 | val_auroc=0.8723

[Epoch 05] train_loss=0.2805 | val_loss=0.8003 | val_mcc=0.1389 | val_f1=0.0463 | val_auroc=0.8786

[Epoch 06] train_loss=0.2781 | val_loss=0.7787 | val_mcc=0.1476 | val_f1=0.0522 | val_auroc=0.8791

[Epoch 07] train_loss=0.2753 | val_loss=0.8121 | val_mcc=0.1446 | val_f1=0.0521 | val_auroc=0.8793

[Epoch 08] train_loss=0.2725 | val_loss=0.8632 | val_mcc=0.1012 | val_f1=0.0249 | val_auroc=0.8803

[Epoch 09] train_loss=0.2699 | val_loss=0.7848 | val_mcc=0.1648 | val_f1=0.0665 | val_auroc=0.8819

[Epoch 10] train_loss=0.2682 | val_loss=0.9290 | val_mcc=0.1057 | val_f1=0.0272 | val_auroc=0.8780

[Epoch 11] train_loss=0.2654 | val_loss=0.8071 | val_mcc=0.1573 | val_f1=0.0629 | val_auroc=0.8754

[Epoch 12] train_loss=0.2619 | val_loss=0.8475 | val_mcc=0.1596 | val_f1=0.0636 | val_auroc=0.8795

[Epoch 13] train_loss=0.2594 | val_loss=0.8779 | val_mcc=0.1484 | val_f1=0.0557 | val_auroc=0.8775

[Epoch 14] train_loss=0.2545 | val_loss=0.8516 | val_mcc=0.1685 | val_f1=0.0721 | val_auroc=0.8762

[Epoch 15] train_loss=0.2509 | val_loss=0.8610 | val_mcc=0.1599 | val_f1=0.0657 | val_auroc=0.8703

[Epoch 16] train_loss=0.2483 | val_loss=0.9100 | val_mcc=0.1416 | val_f1=0.0521 | val_auroc=0.8720

[Epoch 17] train_loss=0.2465 | val_loss=0.8815 | val_mcc=0.1584 | val_f1=0.0664 | val_auroc=0.8762

[Epoch 18] train_loss=0.2439 | val_loss=0.8979 | val_mcc=0.1577 | val_f1=0.0650 | val_auroc=0.8668

[Epoch 19] train_loss=0.2400 | val_loss=0.9196 | val_mcc=0.1503 | val_f1=0.0607 | val_auroc=0.8663

[Epoch 20] train_loss=0.2384 | val_loss=0.8941 | val_mcc=0.1557 | val_f1=0.0636 | val_auroc=0.8704
[EarlyStop] epoch=20 | best_val_mcc=0.1685
[Test] train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test | MCC=0.1738 | F1=0.0874 | AUROC=0.8877 | AUPRC=0.8062
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.1683 | F1=0.1035 | AUROC=0.8647 | AUPRC=0.8777
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.0827 | F1=0.0469 | AUROC=0.7609 | AUPRC=0.7561
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.1516 | F1=0.1140 | AUROC=0.8604 | AUPRC=0.8344
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 26.
[Test] train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.5746 | F1=0.6038 | AUROC=0.8781 | AUPRC=0.8081
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.5189 | F1=0.6157 | AUROC=0.8439 | AUPRC=0.8725
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.3491 | F1=0.4721 | AUROC=0.7550 | AUPRC=0.7575
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5103 | F1=0.6214 | AUROC=0.8564 | AUPRC=0.8575
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 15.
[Test] train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.2348 | F1=0.1431 | AUROC=0.5991 | AUPRC=0.4271
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.1728 | F1=0.1087 | AUROC=0.5904 | AUPRC=0.6071
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.1166 | F1=0.0668 | AUROC=0.5521 | AUPRC=0.5712
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.2042 | F1=0.1557 | AUROC=0.5858 | AUPRC=0.5914
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.2952 | val_loss=0.5682 | val_mcc=0.3131 | val_f1=0.2236 | val_auroc=0.8960

[Epoch 02] train_loss=0.2554 | val_loss=0.6105 | val_mcc=0.2699 | val_f1=0.1708 | val_auroc=0.9092

[Epoch 03] train_loss=0.2359 | val_loss=0.6025 | val_mcc=0.3459 | val_f1=0.2664 | val_auroc=0.9135

[Epoch 04] train_loss=0.2203 | val_loss=0.7662 | val_mcc=0.2396 | val_f1=0.1353 | val_auroc=0.9122

[Epoch 05] train_loss=0.2048 | val_loss=0.6906 | val_mcc=0.3025 | val_f1=0.2142 | val_auroc=0.9075

[Epoch 06] train_loss=0.1903 | val_loss=0.8078 | val_mcc=0.2505 | val_f1=0.1520 | val_auroc=0.9073

[Epoch 07] train_loss=0.1745 | val_loss=0.8612 | val_mcc=0.2755 | val_f1=0.1864 | val_auroc=0.9051

[Epoch 08] train_loss=0.1518 | val_loss=0.9682 | val_mcc=0.2391 | val_f1=0.1421 | val_auroc=0.8950

[Epoch 09] train_loss=0.1409 | val_loss=0.8870 | val_mcc=0.3390 | val_f1=0.2673 | val_auroc=0.8992
[EarlyStop] epoch=9 | best_val_mcc=0.3459
[Test] train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test | MCC=0.3695 | F1=0.3136 | AUROC=0.9295 | AUPRC=0.8586
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.3027 | F1=0.3051 | AUROC=0.9185 | AUPRC=0.9097
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.1906 | F1=0.2108 | AUROC=0.8011 | AUPRC=0.7851
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.3260 | F1=0.3090 | AUROC=0.9050 | AUPRC=0.8893
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 22.
[Test] train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.5927 | F1=0.6301 | AUROC=0.8894 | AUPRC=0.8220
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.5320 | F1=0.6491 | AUROC=0.8506 | AUPRC=0.8735
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.3652 | F1=0.5048 | AUROC=0.7581 | AUPRC=0.7579
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.5318 | F1=0.6461 | AUROC=0.8631 | AUPRC=0.8624
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 18.
[Test] train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.2490 | F1=0.1585 | AUROC=0.8955 | AUPRC=0.8210
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.2242 | F1=0.1732 | AUROC=0.8715 | AUPRC=0.8863
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.1493 | F1=0.1103 | AUROC=0.7648 | AUPRC=0.7710
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.2538 | F1=0.2077 | AUROC=0.8634 | AUPRC=0.8609
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.2419 | val_loss=0.6254 | val_mcc=0.1384 | val_f1=0.0471 | val_auroc=0.9578

[Epoch 02] train_loss=0.1997 | val_loss=0.5790 | val_mcc=0.1776 | val_f1=0.0765 | val_auroc=0.9614

[Epoch 03] train_loss=0.1926 | val_loss=0.5676 | val_mcc=0.2079 | val_f1=0.1023 | val_auroc=0.9600

[Epoch 04] train_loss=0.1889 | val_loss=0.5749 | val_mcc=0.2028 | val_f1=0.0968 | val_auroc=0.9615

[Epoch 05] train_loss=0.1863 | val_loss=0.5588 | val_mcc=0.2623 | val_f1=0.1570 | val_auroc=0.9603

[Epoch 06] train_loss=0.1835 | val_loss=0.5801 | val_mcc=0.2897 | val_f1=0.1870 | val_auroc=0.9603

[Epoch 07] train_loss=0.1810 | val_loss=0.5893 | val_mcc=0.2479 | val_f1=0.1420 | val_auroc=0.9575

[Epoch 08] train_loss=0.1794 | val_loss=0.6137 | val_mcc=0.2443 | val_f1=0.1374 | val_auroc=0.9533

[Epoch 09] train_loss=0.1767 | val_loss=0.6642 | val_mcc=0.1883 | val_f1=0.0842 | val_auroc=0.9596

[Epoch 10] train_loss=0.1744 | val_loss=0.6414 | val_mcc=0.2418 | val_f1=0.1367 | val_auroc=0.9588

[Epoch 11] train_loss=0.1718 | val_loss=0.6338 | val_mcc=0.2840 | val_f1=0.1831 | val_auroc=0.9591

[Epoch 12] train_loss=0.1699 | val_loss=0.6664 | val_mcc=0.2697 | val_f1=0.1666 | val_auroc=0.9577
[EarlyStop] epoch=12 | best_val_mcc=0.2897
[Test] train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test | MCC=0.3216 | F1=0.2434 | AUROC=0.9585 | AUPRC=0.9116
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.2641 | F1=0.2290 | AUROC=0.9660 | AUPRC=0.9671
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.1847 | F1=0.1496 | AUROC=0.7883 | AUPRC=0.7733
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.2973 | F1=0.2821 | AUROC=0.9038 | AUPRC=0.8851
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 40.
[Test] train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.7890 | F1=0.8378 | AUROC=0.9670 | AUPRC=0.9234
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.7756 | F1=0.8631 | AUROC=0.9757 | AUPRC=0.9784
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.4638 | F1=0.6936 | AUROC=0.8058 | AUPRC=0.7865
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.7151 | F1=0.8473 | AUROC=0.9178 | AUPRC=0.8942
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 19.
[Test] train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.2890 | F1=0.2062 | AUROC=0.9367 | AUPRC=0.8652
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.2095 | F1=0.1538 | AUROC=0.9404 | AUPRC=0.9415
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.1745 | F1=0.1492 | AUROC=0.7635 | AUPRC=0.7507
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_bio_dna_geom_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.2786 | F1=0.2741 | AUROC=0.8842 | AUPRC=0.8570
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test

[Epoch 01] train_loss=0.2197 | val_loss=0.6097 | val_mcc=0.2498 | val_f1=0.1421 | val_auroc=0.9596

[Epoch 02] train_loss=0.1738 | val_loss=0.6425 | val_mcc=0.2340 | val_f1=0.1261 | val_auroc=0.9646

[Epoch 03] train_loss=0.1580 | val_loss=0.5859 | val_mcc=0.3579 | val_f1=0.2706 | val_auroc=0.9642

[Epoch 04] train_loss=0.1460 | val_loss=0.5530 | val_mcc=0.3823 | val_f1=0.3019 | val_auroc=0.9606

[Epoch 05] train_loss=0.1348 | val_loss=0.5611 | val_mcc=0.3998 | val_f1=0.3260 | val_auroc=0.9614

[Epoch 06] train_loss=0.1228 | val_loss=0.7272 | val_mcc=0.3158 | val_f1=0.2195 | val_auroc=0.9521

[Epoch 07] train_loss=0.1112 | val_loss=0.5745 | val_mcc=0.4605 | val_f1=0.4068 | val_auroc=0.9529

[Epoch 08] train_loss=0.1003 | val_loss=0.7800 | val_mcc=0.3749 | val_f1=0.2944 | val_auroc=0.9473

[Epoch 09] train_loss=0.0907 | val_loss=0.7894 | val_mcc=0.3758 | val_f1=0.2975 | val_auroc=0.9477

[Epoch 10] train_loss=0.0814 | val_loss=0.8583 | val_mcc=0.3608 | val_f1=0.2776 | val_auroc=0.9372

[Epoch 11] train_loss=0.0729 | val_loss=0.9373 | val_mcc=0.3142 | val_f1=0.2199 | val_auroc=0.9271

[Epoch 12] train_loss=0.0574 | val_loss=0.9809 | val_mcc=0.3413 | val_f1=0.2530 | val_auroc=0.9215

[Epoch 13] train_loss=0.0531 | val_loss=1.0876 | val_mcc=0.3150 | val_f1=0.2216 | val_auroc=0.9202
[EarlyStop] epoch=13 | best_val_mcc=0.4605
[Test] train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_Test | MCC=0.4630 | F1=0.4393 | AUROC=0.9505 | AUPRC=0.9007
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ClinVarHQ | MCC=0.3870 | F1=0.4110 | AUROC=0.9551 | AUPRC=0.9548
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_UniProt | MCC=0.2697 | F1=0.3457 | AUROC=0.7950 | AUPRC=0.7814
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train1Val_ProteinGym | MCC=0.4126 | F1=0.4622 | AUROC=0.9035 | AUPRC=0.8869
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 57.
[Test] train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_Test | MCC=0.7938 | F1=0.8411 | AUROC=0.9695 | AUPRC=0.9310
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ClinVarHQ | MCC=0.7931 | F1=0.8728 | AUROC=0.9790 | AUPRC=0.9817
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_UniProt | MCC=0.4744 | F1=0.6997 | AUROC=0.8085 | AUPRC=0.7870
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train1Val_ProteinGym | MCC=0.7145 | F1=0.8462 | AUROC=0.9214 | AUPRC=0.8975
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 16.
[Test] train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_Test | MCC=0.3892 | F1=0.3360 | AUROC=0.9461 | AUPRC=0.8895
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ClinVarHQ | MCC=0.3113 | F1=0.2983 | AUROC=0.9493 | AUPRC=0.9540
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_UniProt | MCC=0.2023 | F1=0.2116 | AUROC=0.7810 | AUPRC=0.7737
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 104385 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train1__val_mean_bio_geom_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train1Val_ProteinGym | MCC=0.3767 | F1=0.4171 | AUROC=0.8971 | AUPRC=0.8731

================================================================================
[THANH CONG] Module 5 batch runner da hoan tat
================================================================================
Batch run dir: d:\Missense_variant_pathogenicity_prediction\experiments\batch_run_20260902_1626
Metrics CSV: d:\Missense_variant_pathogenicity_prediction\experiments\batch_run_20260902_1626/global_leaderboard_metrics.csv | rows=1908
Profiling CSV: d:\Missense_variant_pathogenicity_prediction\experiments\batch_run_20260902_1626/global_leaderboard_profiling.csv | rows=1908
Compare CSV: d:\Missense_variant_pathogenicity_prediction\experiments\batch_run_20260902_1626/global_compare_ours_vs_sota.csv

,Dataset,Pooling,Ablation,DNA_Model,Prot_Model,Network,Accuracy,Precision,Recall,Specificity,F1_Score,MCC,AUROC,AUPRC,Source
0,Train1Val_ClinVarHQ,cls,bio_dna_prot,nt_v3_650m,esm1b_650m,Pure_XGBoost_Concat,0.9275,0.9744,0.8764,0.9775,0.9228,0.8590,0.9863,0.9874,OURS
1,Train1Val_ClinVarHQ,center,bio_dna_prot,nt_v3_650m,esmc_600m,Pure_XGBoost_Concat,0.9260,0.9744,0.8736,0.9775,0.9212,0.8564,0.9881,0.9885,OURS
2,Train1Val_ClinVarHQ,mean,bio_dna_prot,nt_v3_650m,esm1b_650m,Hybrid_Concat_XGBoost,0.9260,0.9684,0.8793,0.9718,0.9217,0.8555,0.9827,0.9835,OURS
3,Train1Val_ClinVarHQ,mean,bio_dna,nt_v3_650m,NaN,Pure_XGBoost_Concat,0.9246,0.9836,0.8621,0.9859,0.9188,0.8555,0.9840,0.9856,OURS
4,Train1Val_ClinVarHQ,center,bio_dna_prot,nt_v3_650m,esmc_600m,Hybrid_CrossAttn_XGBoost,0.9260,0.9596,0.8879,0.9634,0.9224,0.8543,0.9863,0.9865,OURS
5,Train1Val_ClinVarHQ,center,bio_dna_prot,nt_v3_650m,esmc_600m,Hybrid_Gating_XGBoost,0.9246,0.9712,0.8736,0.9746,0.9198,0.8533,0.9836,0.9847,OURS
6,Train1Val_ClinVarHQ,center,bio_dna_prot,nt_v3_650m,esmc_600m,Hybrid_Concat_XGBoost,0.9246,0.9595,0.8851,0.9634,0.9208,0.8516,0.9865,0.9864,OURS
7,Train1Val_ClinVarHQ,center,bio_dna_prot,nt_v3_650m,esmc_600m,Hybrid_Transformer_XGBoost,0.9232,0.9742,0.8678,0.9775,0.9179,0.8512,0.9840,0.9847,OURS
8,Train1Val_ClinVarHQ,mean,bio_dna_prot,nt_v3_650m,esm1b_650m,Hybrid_Gating_XGBoost,0.9232,0.9712,0.8707,0.9746,0.9182,0.8507,0.9822,0.9825,OURS
9,Train1Val_ClinVarHQ,center,bio_prot,NaN,esmc_600m,Hybrid_Concat_XGBoost,0.9232,0.9652,0.8764,0.9690,0.9187,0.8498,0.9824,0.9842,OURS
10,Train1Val_ClinVarHQ,cls,bio_dna_prot,nt_v3_650m,esm1b_650m,Hybrid_Transformer_XGBoost,0.9218,0.9741,0.8649,0.9775,0.9163,0.8486,0.9830,0.9840,OURS
11,Train1Val_ClinVarHQ,center,bio_prot,NaN,esmc_600m,Pure_XGBoost_Concat,0.9203,0.9710,0.8649,0.9746,0.9149,0.8455,0.9864,0.9871,OURS
12,Train1Val_ClinVarHQ,cls,bio_prot,NaN,esm1b_650m,Pure_XGBoost_Concat,0.9175,0.9801,0.8506,0.9831,0.9108,0.8420,0.9822,0.9836,OURS
13,Train1Val_ClinVarHQ,mean,bio_prot,NaN,esm1b_650m,Pure_XGBoost_Concat,0.9175,0.9770,0.8534,0.9803,0.9110,0.8414,0.9827,0.9842,OURS
14,Train1Val_ClinVarHQ,mean,bio_prot,NaN,esm1b_650m,Hybrid_Concat_XGBoost,0.9189,0.9619,0.8707,0.9662,0.9140,0.8414,0.9778,0.9779,OURS
15,Train1Val_ClinVarHQ,mean,bio_dna_prot,nt_v3_650m,esm1b_650m,Hybrid_Transformer_XGBoost,0.9175,0.9647,0.8649,0.9690,0.9121,0.8392,0.9825,0.9836,OURS
16,Train1Val_ClinVarHQ,cls,bio_prot,NaN,esm1b_650m,Hybrid_Concat_XGBoost,0.9161,0.9738,0.8534,0.9775,0.9096,0.8382,0.9828,0.9842,OURS
17,Train1Val_ClinVarHQ,mean,bio_dna_prot,nt_v3_650m,esm1b_650m,Hybrid_CrossAttn_XGBoost,0.9175,0.9531,0.8764,0.9577,0.9132,0.8375,0.9826,0.9822,OURS
18,Train1Val_ClinVarHQ,mean,bio_dna_prot,nt_v3_650m,esm1b_650m,PyTorch_Concat,0.9132,0.9705,0.8506,0.9746,0.9066,0.8325,0.9811,0.9825,OURS
19,Train1Val_ClinVarHQ,cls,bio_dna_prot,nt_v3_650m,esm1b_650m,Hybrid_CrossAttn_XGBoost,0.9132,0.9614,0.8592,0.9662,0.9074,0.8309,0.9812,0.9826,OURS
20,Train1Val_ClinVarHQ,mean,bio_dna_prot,nt_v3_650m,esm1b_650m,Pure_XGBoost_Concat,0.9118,0.9673,0.8506,0.9718,0.9052,0.8293,0.9838,0.9845,OURS
21,Train1Val_ClinVarHQ,center,bio_prot,NaN,esmc_600m,PyTorch_Concat,0.9118,0.9673,0.8506,0.9718,0.9052,0.8293,0.9841,0.9843,OURS
22,Train1Val_ClinVarHQ,center,bio_dna_prot,nt_v3_650m,esmc_600m,PyTorch_Gating,0.9104,0.9766,0.8391,0.9803,0.9026,0.8286,0.9856,0.9858,OURS
23,Train1Val_ClinVarHQ,cls,bio_dna_prot,nt_v3_650m,esm1b_650m,PyTorch_CrossAttn,0.9104,0.9734,0.8420,0.9775,0.9029,0.8280,0.9811,0.9823,OURS
24,Train1Val_ClinVarHQ,mean,bio_dna_prot,nt_v3_650m,esm1b_650m,PyTorch_CrossAttn,0.9104,0.9672,0.8477,0.9718,0.9035,0.8268,0.9823,0.9831,OURS
25,Train1Val_ClinVarHQ,center,bio_dna_geom_prot,nt_v3_650m,esmc_600m,Pure_XGBoost_Concat,0.9075,0.9896,0.8218,0.9915,0.8980,0.8265,0.9814,0.9834,OURS
26,Train1Val_ClinVarHQ,cls,bio_dna_prot,nt_v3_650m,esm1b_650m,Hybrid_Concat_XGBoost,0.9090,0.9702,0.8420,0.9746,0.9015,0.8248,0.9809,0.9822,OURS
27,Train1Val_ClinVarHQ,mean,bio_dna_prot,nt_v3_650m,esm1b_650m,PyTorch_Transformer,0.9090,0.9641,0.8477,0.9690,0.9021,0.8236,0.9782,0.9786,OURS
28,Train1Val_ClinVarHQ,cls,bio_dna_prot,nt_v3_650m,esm1b_650m,PyTorch_Transformer,0.9033,0.9795,0.8218,0.9831,0.8938,0.8167,0.9808,0.9819,OURS
29,Train1Val_ClinVarHQ,cls,bio_prot,NaN,esm1b_650m,PyTorch_Concat,0.9047,0.9668,0.8362,0.9718,0.8968,0.8165,0.9804,0.9817,OURS
30,Train1Val_ClinVarHQ,center,bio_dna,nt_v3_650m,NaN,Pure_XGBoost_Concat,0.9047,0.9637,0.8391,0.9690,0.8971,0.8159,0.9797,0.9803,OURS
31,Train1Val_ClinVarHQ,center,bio_geom_prot,nt_v3_650m,esmc_600m,Pure_XGBoost_Concat,0.9004,0.9894,0.8075,0.9915,0.8892,0.8141,0.9815,0.9837,OURS
32,Train1Val_ClinVarHQ,cls,bio_dna_prot,nt_v3_650m,esm1b_650m,Hybrid_Gating_XGBoost,0.9033,0.9667,0.8333,0.9718,0.8951,0.8139,0.9801,0.9815,OURS
33,Train1Val_ClinVarHQ,center,bio_geom,nt_v3_650m,esmc_600m,Pure_XGBoost_Concat,0.8990,0.9929,0.8017,0.9944,0.8871,0.8126,0.9806,0.9830,OURS
34,Train1Val_ClinVarHQ,center,bio_dna_geom,nt_v3_650m,esmc_600m,Pure_XGBoost_Concat,0.8976,0.9929,0.7989,0.9944,0.8854,0.8101,0.9809,0.9830,OURS
35,Train1Val_ClinVarHQ,center,bio_dna_prot,nt_v3_650m,esmc_600m,PyTorch_Concat,0.8990,0.9826,0.8103,0.9859,0.8882,0.8100,0.9863,0.9871,OURS
36,Train1Val_ClinVarHQ,center,bio_dna_prot,nt_v3_650m,esmc_600m,PyTorch_Transformer,0.8990,0.9759,0.8161,0.9803,0.8889,0.8084,0.9808,0.9809,OURS
37,Train1Val_ClinVarHQ,cls,bio_dna_prot,nt_v3_650m,esm1b_650m,PyTorch_Concat,0.8976,0.9859,0.8046,0.9887,0.8861,0.8083,0.9801,0.9801,OURS
38,Train1Val_ClinVarHQ,mean,bio_dna_prot,nt_v3_650m,esm1b_650m,PyTorch_Gating,0.8962,0.9758,0.8103,0.9803,0.8854,0.8034,0.9837,0.9843,OURS
39,Train1Val_ClinVarHQ,cls,bio_dna_geom_prot,nt_v3_650m,esm1b_650m,Pure_XGBoost_Concat,0.8919,0.9928,0.7874,0.9944,0.8782,0.8004,0.9773,0.9807,OURS

,Dataset,Model,file_path,score_col,rankscore_col,pred_col,resolved_prob_col,resolved_prob_kind,resolved_threshold,pred_source,label_col
0,test,SIFT,D:/variant_data/test_full_seq_after_vep_final....,['SIFT_score'],"['SIFT_converted_rankscore', 'SIFT_rankscore']",['SIFT_pred'],SIFT_converted_rankscore,rankscore,0.395750,SIFT_pred,Label
1,test,SIFT4G,D:/variant_data/test_full_seq_after_vep_final....,['SIFT4G_score'],"['SIFT4G_converted_rankscore', 'SIFT4G_ranksco...",['SIFT4G_pred'],SIFT4G_converted_rankscore,rankscore,0.395750,SIFT4G_pred,Label
2,test,Polyphen2_HDIV,D:/variant_data/test_full_seq_after_vep_final....,['Polyphen2_HDIV_score'],['Polyphen2_HDIV_rankscore'],['Polyphen2_HDIV_pred'],Polyphen2_HDIV_rankscore,rankscore,0.380280,Polyphen2_HDIV_pred,Label
3,test,Polyphen2_HVAR,D:/variant_data/test_full_seq_after_vep_final....,['Polyphen2_HVAR_score'],['Polyphen2_HVAR_rankscore'],['Polyphen2_HVAR_pred'],Polyphen2_HVAR_rankscore,rankscore,0.487620,Polyphen2_HVAR_pred,Label
4,test,MutationTaster,D:/variant_data/test_full_seq_after_vep_final....,['MutationTaster_score'],['MutationTaster_rankscore'],['MutationTaster_pred'],MutationTaster_rankscore,rankscore,0.317330,MutationTaster_pred,Label
5,test,MetaSVM,D:/variant_data/test_full_seq_after_vep_final....,['MetaSVM_score'],['MetaSVM_rankscore'],['MetaSVM_pred'],MetaSVM_rankscore,rankscore,0.822570,MetaSVM_pred,Label
6,test,MetaLR,D:/variant_data/test_full_seq_after_vep_final....,['MetaLR_score'],['MetaLR_rankscore'],['MetaLR_pred'],MetaLR_rankscore,rankscore,0.811010,MetaLR_pred,Label
7,test,MetaRNN,D:/variant_data/test_full_seq_after_vep_final....,['MetaRNN_score'],['MetaRNN_rankscore'],['MetaRNN_pred'],MetaRNN_rankscore,rankscore,0.614900,MetaRNN_pred,Label
8,test,M-CAP,D:/variant_data/test_full_seq_after_vep_final....,['M-CAP_score'],['M-CAP_rankscore'],['M-CAP_pred'],M-CAP_rankscore,rankscore,0.025000,M-CAP_pred,Label
9,test,REVEL,D:/variant_data/test_full_seq_after_vep_final....,['REVEL_score'],['REVEL_rankscore'],['REVEL_pred'],REVEL_rankscore,rankscore,0.500000,REVEL_pred,Label
10,test,MutPred2,D:/variant_data/test_full_seq_after_vep_final....,['MutPred2_score'],['MutPred2_rankscore'],['MutPred2_pred'],MutPred2_rankscore,rankscore,0.500000,MutPred2_pred,Label
11,test,MVP,D:/variant_data/test_full_seq_after_vep_final....,['MVP_score'],['MVP_rankscore'],['MVP_pred'],MVP_rankscore,rankscore,0.500000,MVP_pred,Label
12,test,gMVP,D:/variant_data/test_full_seq_after_vep_final....,['gMVP_score'],['gMVP_rankscore'],['gMVP_pred'],gMVP_rankscore,rankscore,0.500000,gMVP_pred,Label
13,test,MisFit_D,D:/variant_data/test_full_seq_after_vep_final....,['MisFit_D_score'],['MisFit_D_rankscore'],"['MisFit_D_pred_lenient', 'MisFit_D_pred']",MisFit_D_rankscore,rankscore,0.450000,MisFit_D_pred_lenient,Label
14,test,MPC,D:/variant_data/test_full_seq_after_vep_final....,['MPC_score'],['MPC_rankscore'],['MPC_pred'],MPC_rankscore,rankscore,0.500000,MPC_pred,Label
15,test,PrimateAI,D:/variant_data/test_full_seq_after_vep_final....,['PrimateAI_score'],['PrimateAI_rankscore'],['PrimateAI_pred'],PrimateAI_rankscore,rankscore,0.803000,PrimateAI_pred,Label
16,test,BayesDel_addAF,D:/variant_data/test_full_seq_after_vep_final....,['BayesDel_addAF_score'],['BayesDel_addAF_rankscore'],['BayesDel_addAF_pred'],BayesDel_addAF_rankscore,rankscore,0.069265,BayesDel_addAF_pred,Label
17,test,BayesDel_noAF,D:/variant_data/test_full_seq_after_vep_final....,['BayesDel_noAF_score'],['BayesDel_noAF_rankscore'],['BayesDel_noAF_pred'],BayesDel_noAF_rankscore,rankscore,-0.057010,BayesDel_noAF_pred,Label
18,test,ClinPred,D:/variant_data/test_full_seq_after_vep_final....,['ClinPred_score'],['ClinPred_rankscore'],['ClinPred_pred'],ClinPred_rankscore,rankscore,0.500000,ClinPred_pred,Label
19,test,LIST-S2,D:/variant_data/test_full_seq_after_vep_final....,['LIST-S2_score'],['LIST-S2_rankscore'],['LIST-S2_pred'],LIST-S2_rankscore,rankscore,0.850000,LIST-S2_pred,Label
20,test,VARITY_R,D:/variant_data/test_full_seq_after_vep_final....,['VARITY_R_score'],['VARITY_R_rankscore'],['VARITY_R_pred'],VARITY_R_rankscore,rankscore,0.500000,VARITY_R_pred,Label
21,test,VARITY_ER,D:/variant_data/test_full_seq_after_vep_final....,['VARITY_ER_score'],['VARITY_ER_rankscore'],['VARITY_ER_pred'],VARITY_ER_rankscore,rankscore,0.500000,VARITY_ER_pred,Label
22,test,AlphaMissense,D:/variant_data/test_full_seq_after_vep_final....,['AlphaMissense_score'],['AlphaMissense_rankscore'],['AlphaMissense_pred'],AlphaMissense_rankscore,rankscore,0.500000,AlphaMissense_pred,Label
23,test,PHACTboost,D:/variant_data/test_full_seq_after_vep_final....,['PHACTboost_score'],['PHACTboost_rankscore'],['PHACTboost_pred'],PHACTboost_rankscore,rankscore,0.620000,PHACTboost_pred,Label
24,test,MutFormer,D:/variant_data/test_full_seq_after_vep_final....,['MutFormer_score'],['MutFormer_rankscore'],['MutFormer_pred'],MutFormer_rankscore,rankscore,0.883800,MutFormer_pred,Label
25,test,popEVE,D:/variant_data/test_full_seq_after_vep_final....,['popEVE_score'],"['popEVE_converted_rankscore', 'popEVE_ranksco...",['popEVE_pred'],popEVE_converted_rankscore,rankscore,0.500000,popEVE_pred,Label
26,test,CADD,D:/variant_data/test_full_seq_after_vep_final....,"['CADD_raw', 'CADD_phred']",['CADD_raw_rankscore'],['CADD_pred'],CADD_raw_rankscore,rankscore,0.500000,CADD_pred,Label
27,test,DANN,D:/variant_data/test_full_seq_after_vep_final....,['DANN_score'],['DANN_rankscore'],['DANN_pred'],DANN_rankscore,rankscore,0.500000,DANN_pred,Label
28,clinvarhq,SIFT,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['SIFT_score'],"['SIFT_converted_rankscore', 'SIFT_rankscore']",['SIFT_pred'],SIFT_converted_rankscore,rankscore,0.395750,SIFT_pred,Label
29,clinvarhq,SIFT4G,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['SIFT4G_score'],"['SIFT4G_converted_rankscore', 'SIFT4G_ranksco...",['SIFT4G_pred'],SIFT4G_converted_rankscore,rankscore,0.395750,SIFT4G_pred,Label
30,clinvarhq,Polyphen2_HDIV,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['Polyphen2_HDIV_score'],['Polyphen2_HDIV_rankscore'],['Polyphen2_HDIV_pred'],Polyphen2_HDIV_rankscore,rankscore,0.380280,Polyphen2_HDIV_pred,Label
31,clinvarhq,Polyphen2_HVAR,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['Polyphen2_HVAR_score'],['Polyphen2_HVAR_rankscore'],['Polyphen2_HVAR_pred'],Polyphen2_HVAR_rankscore,rankscore,0.487620,Polyphen2_HVAR_pred,Label
32,clinvarhq,MutationTaster,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MutationTaster_score'],['MutationTaster_rankscore'],['MutationTaster_pred'],MutationTaster_rankscore,rankscore,0.317330,MutationTaster_pred,Label
33,clinvarhq,MetaSVM,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MetaSVM_score'],['MetaSVM_rankscore'],['MetaSVM_pred'],MetaSVM_rankscore,rankscore,0.822570,MetaSVM_pred,Label
34,clinvarhq,MetaLR,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MetaLR_score'],['MetaLR_rankscore'],['MetaLR_pred'],MetaLR_rankscore,rankscore,0.811010,MetaLR_pred,Label
35,clinvarhq,MetaRNN,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MetaRNN_score'],['MetaRNN_rankscore'],['MetaRNN_pred'],MetaRNN_rankscore,rankscore,0.614900,MetaRNN_pred,Label
36,clinvarhq,M-CAP,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['M-CAP_score'],['M-CAP_rankscore'],['M-CAP_pred'],M-CAP_rankscore,rankscore,0.025000,M-CAP_pred,Label
37,clinvarhq,REVEL,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['REVEL_score'],['REVEL_rankscore'],['REVEL_pred'],REVEL_rankscore,rankscore,0.500000,REVEL_pred,Label
38,clinvarhq,MutPred2,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MutPred2_score'],['MutPred2_rankscore'],['MutPred2_pred'],MutPred2_rankscore,rankscore,0.500000,MutPred2_pred,Label
39,clinvarhq,MVP,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MVP_score'],['MVP_rankscore'],['MVP_pred'],MVP_rankscore,rankscore,0.500000,MVP_pred,Label

Empty DataFrame
Columns: [Dataset, file_path, column, exists, null_count]
Index: []