### Cách dùng Notebook 01 hiện tại

1. Mở `01_train_val_test_batch_runner.ipynb`.
2. Chạy Cell 2 để:
- Import pipeline
- Khai báo toàn bộ cấu hình bạn muốn kiểm soát
- Khởi tạo đối tượng pipeline
3. Chạy Cell 4 để chạy toàn bộ train-val-test batch.
4. Sau khi chạy xong, Cell 4 sẽ:
- In đường dẫn thư mục batch run
- Đọc và hiển thị 2 bảng tổng hợp metrics/profiling.

Luồng chạy thực tế nằm ở `pipeline.py`.

Các config ảnh hưởng pipeline train như thế nào

1. CONFIG trong Cell 2
- batch_size: tăng thì nhanh hơn nhưng tốn VRAM/RAM hơn.
- epochs: số epoch tối đa cho nhánh pytorch.
- lr: learning rate cho optimizer.
- weight_decay: regularization cho pytorch.
- lr_factor + lr_patience: giảm learning rate khi MCC val không cải thiện.
- early_stop_patience: dừng sớm nếu MCC val không tăng.
- num_workers: số worker DataLoader.

2. MODELS_SPACE trong Cell 2
- Xác định tập model DNA và Protein để vét cạn tổ hợp ở Stage 1.
- Pipeline tự tách model theo seq_type dna/protein.
- Nếu thêm/bớt model ở đây, số tổ hợp train tăng/giảm trực tiếp.

3. EXPERIMENTS trong Cell 2
- Quy định bạn chạy kiểu nào:
- pytorch: train end-to-end mạng fusion.
- hybrid: train nhanh mạng pytorch để lấy f_global, sau đó train XGBoost.
- xgboost_pure: PCA + XGBoost trên đặc trưng không gian bảng/biến thể.
- Với ablation chỉ có 1 nhánh chuỗi, pipeline tự bỏ các fusion cần 2 nhánh như cross_attention/transformer/gating.

4. datasets trong Cell 2
- Mỗi phần tử định nghĩa 1 job train/val/test.
- test split ở đây còn ảnh hưởng E2E profiling vì Module 5 sẽ đọc FM profiling đúng theo split test tương ứng.

5. pooling_strategies trong Cell 2
- Chạy lặp theo từng pooling center/cls/mean.
- Mỗi pooling sẽ có leaderboard và best pair search riêng.

6. EXPLAINABILITY trong Cell 2
- enable_shap: bật SHAP cho các nhánh dùng XGBoost.
- enable_lime: bật LIME cho local explanation.
- max_background_samples: số mẫu nền tối đa cho SHAP/LIME.
- max_explain_samples: số mẫu test giải thích bằng SHAP.
- max_lime_samples: số mẫu test giải thích bằng LIME.
- lime_num_features: số feature rule mỗi mẫu cho LIME.
- random_state: seed cho sampling explainability.

### Output sau khi chạy xong

Sau khi chạy toàn bộ Notebook 01 (Cell 2 rồi Cell 4), output sẽ gồm các nhóm sau trong thư mục batch run mới:

1. Output tổng hợp cấp batch run
- experiments / `batch_run_YYYYMMDD_HHMM/`
- `global_leaderboard_metrics.csv`: metrics của model mình (toàn bộ run trong pipeline)
- `global_leaderboard_profiling.csv`: profiling E2E của model mình
- `global_compare_ours_vs_sota.csv`: bảng gộp so sánh `OURS` và `SOTA`
- `sota_metrics.csv`: metrics SOTA tính trực tiếp từ cột score/rankscore/pred
- `sota_column_mapping.csv`: mapping model SOTA -> cột nào được dùng
- `sota_required_columns_audit.csv`: audit đủ cột/thiếu cột/null theo từng dataset test

2. Output theo từng experiment con
Mỗi tổ hợp dataset + pooling + ablation + model + network sẽ có 1 thư mục con, ví dụ:
- `Train1Val_Test_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat/`

Bên trong thường có:
- `test_probabilities.csv`: dự đoán chi tiết theo Variant_ID
- `tensorboard_logs/`: log train/val
- `checkpoints/best_model.pth`: với nhánh PyTorch

3. Output explainability (nếu bật trong EXPLAINABILITY)
Trong các run dùng XGBoost (`hybrid`, `xgboost_pure`) sẽ có:
- `explainability/shap_global_importance.csv`
- `explainability/shap_local_top_features.csv`
- `explainability/lime_local_explanations.csv` (chỉ có khi `enable_lime=True`)

4. Output hiển thị ngay trên notebook (không phải file)
- In đường dẫn batch run
- In số dòng của metrics/profiling
- `display(df_compare.head(...))` cho bảng so sánh OURS vs SOTA
- `display(mapping/audit head(...))` để xem nhanh mapping cột và lỗi audit (nếu có)

Các đầu vào mà Notebook 01 kỳ vọng

- Bio normalized: dưới D:/variant_data/processed_parquet
- Geometry: dưới D:/variant_data/geometry/split
- Embedding pt: dưới D:/variant_data/fm_embeddings/split
- FM profiling json: `fm_profiling.json`

### SET UP

In [1]:
import os
import sys
import importlib
import torch
import pandas as pd

sys.path.append(os.path.abspath("../"))

try:
    import thop
    print(f"[*] thop version: {getattr(thop, '__version__', 'unknown')}")
except Exception as e:
    print(f"[CẢNH BÁO] thop import lỗi: {e}")

import core.module05_fusion_classifier.dataset as dataset_module
importlib.reload(dataset_module)
import core.module05_fusion_classifier.evaluator_profiler as evalprof_module
importlib.reload(evalprof_module)
import core.module05_fusion_classifier.pipeline as pipeline_module
importlib.reload(pipeline_module)
from core.module05_fusion_classifier.pipeline import FusionBatchPipeline
from core.module05_fusion_classifier.sota_benchmark import (
    evaluate_sota_from_test_files,
    SOTA_MODEL_COLUMNS_FULL,
    SOTA_REQUIRED_COLUMNS,
)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"[*] Device: {DEVICE}")

BASE_DIR = "D:/variant_data"
FM_PROFILE_JSON = f"{BASE_DIR}/profiling/fm_profiling.json"
GEOM_PROFILE_JSON = f"{BASE_DIR}/profiling/geom_profiling.json"

# Default config dua ve notebook de de kiem soat
CONFIG = {
    "batch_size": 256,
    "epochs": 30,
    "lr": 1e-4,
    "weight_decay": 1e-3,
    "lr_factor": 0.5,
    "lr_patience": 3,
    "early_stop_patience": 6,
    "num_workers": 0,
}

MODELS_SPACE = [
    {"name": "nt_v1_500m", "seq_type": "dna"},
    {"name": "nt_v3_650m", "seq_type": "dna"},
    {"name": "nt_v2_500m", "seq_type": "dna"},
    {"name": "esm1b_650m", "seq_type": "protein"},
    {"name": "esm2_650m", "seq_type": "protein"},
    {"name": "esmc_600m", "seq_type": "protein"},
]

EXPERIMENTS = [
    {"name": "PyTorch_Concat", "type": "pytorch", "fusion": "concat"},
    {"name": "PyTorch_CrossAttn", "type": "pytorch", "fusion": "cross_attention"},
    {"name": "PyTorch_Transformer", "type": "pytorch", "fusion": "transformer"},
    {"name": "PyTorch_Gating", "type": "pytorch", "fusion": "gating"},
    {"name": "Pure_XGBoost_Concat", "type": "xgboost_pure", "fusion": "concat"},
    {"name": "Hybrid_Concat_XGBoost", "type": "hybrid", "fusion": "concat"},
    {"name": "Hybrid_CrossAttn_XGBoost", "type": "hybrid", "fusion": "cross_attention"},
    {"name": "Hybrid_Transformer_XGBoost", "type": "hybrid", "fusion": "transformer"},
    {"name": "Hybrid_Gating_XGBoost", "type": "hybrid", "fusion": "gating"},
]

# Dataset split run theo du lieu hien co: train1/val va 4 tap test
datasets = [
    {"name": "Train3Val_Test", "train": "train3", "val": "val", "test": "test"},
    {"name": "Train3Val_ClinVarHQ", "train": "train3", "val": "val", "test": "clinvarhq"},
    {"name": "Train3Val_UniProt", "train": "train3", "val": "val", "test": "uniprot"},
    {"name": "Train3Val_ProteinGym", "train": "train3", "val": "val", "test": "proteingym"},
]

pooling_strategies = ["center", "cls", "mean"]

# Explainability: nen bat SHAP truoc, LIME de sau vi ton thoi gian hon
EXPLAINABILITY = {
    "enable_shap": True,
    "enable_lime": False,
    "max_background_samples": 512,
    "max_explain_samples": 200,
    "lime_num_features": 20,
    "max_lime_samples": 20,
    "random_state": 42,
}

# [MOI] SOTA benchmark tu cot score/rankscore/pred trong 4 test files
SOTA_TEST_FILES = {
    "test": f"{BASE_DIR}/test_full_seq_after_vep_final.parquet",
    "clinvarhq": f"{BASE_DIR}/clinvarhq_full_seq_after_vep_final.parquet",
    "uniprot": f"{BASE_DIR}/uniprot_full_seq_after_vep_final.parquet",
    "proteingym": f"{BASE_DIR}/proteingym_full_seq_after_vep_final.parquet",
}
SOTA_LABEL_COL = None
SOTA_LABEL_CANDIDATES = ["Pathogenicity_Label", "Label"]
SOTA_THRESHOLD = 0.5

# Dung bo cot day du cho SOTA theo danh sach chuan
SOTA_MODEL_COLUMNS = SOTA_MODEL_COLUMNS_FULL
SOTA_REQUIRED = SOTA_REQUIRED_COLUMNS
SOTA_ENFORCE_REQUIRED = True

# Resume control: dat True de tiep tuc 1 batch run dang do
RESUME_ENABLED = False
RESUME_BATCH_RUN_DIR = None  # vd: '../experiments/batch_run_20260902_1430'

pipeline = FusionBatchPipeline(
    base_dir=BASE_DIR,
    config=CONFIG,
    datasets=datasets,
    models_space=MODELS_SPACE,
    pooling_strategies=pooling_strategies,
    experiments=EXPERIMENTS,
    explainability=EXPLAINABILITY,
    fm_profile_json=FM_PROFILE_JSON,
    batch_run_dir=RESUME_BATCH_RUN_DIR,
)

print(f"[*] FM profiling json: {FM_PROFILE_JSON}")
print(f"[*] Geometry profiling json: {GEOM_PROFILE_JSON}")
print(f"[*] Batch run dir: {pipeline.batch_run_dir}")

[*] thop version: 0.1.1

c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[*] Device: cpu
[*] FM profiling json: D:/variant_data/profiling/fm_profiling.json
[*] Geometry profiling json: D:/variant_data/profiling/geom_profiling.json
[*] Batch run dir: d:\Missense_variant_pathogenicity_prediction/experiments/batch_run_20260904_1800

### The Master Loop

In [2]:
# 1) Benchmark SOTA truc tiep tu cot score/rankscore/pred tren 4 test files
sota_result = evaluate_sota_from_test_files(
    test_files=SOTA_TEST_FILES,
    output_dir=pipeline.batch_run_dir,
    label_col=SOTA_LABEL_COL,
    label_candidates=SOTA_LABEL_CANDIDATES,
    model_columns=SOTA_MODEL_COLUMNS,
    threshold=SOTA_THRESHOLD,
    required_columns=SOTA_REQUIRED,
    enforce_required_columns=SOTA_ENFORCE_REQUIRED,
)
print(f"[SOTA] Metrics CSV: {sota_result['metrics_path']} | rows={sota_result['num_rows']}")
print(f"[SOTA] Mapping CSV: {sota_result['mapping_path']} | unique models={sota_result['num_models']}")
if sota_result.get('audit') is not None:
    audit = sota_result['audit']
    print(f"[SOTA] Audit CSV: {audit['audit_path']}")
    print(f"[SOTA] missing_count={audit['missing_count']} | null_issue_count={audit['null_issue_count']}")

# 2) Chay pipeline model cua chung ta
result = pipeline.run(resume=RESUME_ENABLED)

print("\n" + "=" * 80)
print("[THANH CONG] Module 5 batch runner da hoan tat")
print("=" * 80)
print(f"Batch run dir: {result['batch_run_dir']}")
print(f"Metrics CSV: {result['metrics_path']} | rows={result['num_rows_metrics']}")
print(f"Profiling CSV: {result['profiling_path']} | rows={result['num_rows_profiling']}")

# 3) Gop bang so sanh SOTA vs Ours
ours = pd.read_csv(result["metrics_path"])
sota = pd.read_csv(sota_result["metrics_path"])
ours["Source"] = "OURS"
sota["Source"] = "SOTA"

df_compare = pd.concat([ours, sota], ignore_index=True)
df_compare = df_compare.sort_values(by=["Dataset", "MCC"], ascending=[True, False])
df_compare.to_csv(f"{result['batch_run_dir']}/global_compare_ours_vs_sota.csv", index=False)

print(f"Compare CSV: {result['batch_run_dir']}/global_compare_ours_vs_sota.csv")
display(df_compare.head(40))
display(pd.read_csv(sota_result["mapping_path"]).head(40))
if sota_result.get('audit') is not None:
    display(pd.read_csv(sota_result['audit']['audit_path']).query('exists == False or null_count > 0').head(100))

[SOTA] Metrics CSV: d:\Missense_variant_pathogenicity_prediction/experiments/batch_run_20260904_1800/sota_metrics.csv | rows=112
[SOTA] Mapping CSV: d:\Missense_variant_pathogenicity_prediction/experiments/batch_run_20260904_1800/sota_column_mapping.csv | unique models=28
[SOTA] Audit CSV: d:\Missense_variant_pathogenicity_prediction/experiments/batch_run_20260904_1800/sota_required_columns_audit.csv
[SOTA] missing_count=0 | null_issue_count=0
[*] Device: cpu
[*] Batch run dir: d:\Missense_variant_pathogenicity_prediction/experiments/batch_run_20260904_1800

================================================================================
[*] POOLING: CENTER
================================================================================
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4623 | val_loss=0.3795 | val_mcc=0.5771 | val_f1=0.6620 | val_auroc=0.8901

[Epoch 02] train_loss=0.3860 | val_loss=0.3595 | val_mcc=0.6007 | val_f1=0.6806 | val_auroc=0.8967

[Epoch 03] train_loss=0.3481 | val_loss=0.3458 | val_mcc=0.6067 | val_f1=0.6853 | val_auroc=0.8955

[Epoch 04] train_loss=0.3055 | val_loss=0.3461 | val_mcc=0.6047 | val_f1=0.6837 | val_auroc=0.8968

[Epoch 05] train_loss=0.2567 | val_loss=0.4143 | val_mcc=0.5629 | val_f1=0.6501 | val_auroc=0.8877

[Epoch 06] train_loss=0.2102 | val_loss=0.4385 | val_mcc=0.5650 | val_f1=0.6519 | val_auroc=0.8878

[Epoch 07] train_loss=0.1592 | val_loss=0.4532 | val_mcc=0.5713 | val_f1=0.6575 | val_auroc=0.8830

[Epoch 08] train_loss=0.1030 | val_loss=0.5038 | val_mcc=0.5664 | val_f1=0.6528 | val_auroc=0.8875

[Epoch 09] train_loss=0.0833 | val_loss=0.5084 | val_mcc=0.5695 | val_f1=0.6559 | val_auroc=0.8869
[EarlyStop] epoch=9 | best_val_mcc=0.6067
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6459 | F1=0.7445 | AUROC=0.9019 | AUPRC=0.8202
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6020 | F1=0.7947 | AUROC=0.8782 | AUPRC=0.8933
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4106 | F1=0.6979 | AUROC=0.7636 | AUPRC=0.7656
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5710 | F1=0.7712 | AUROC=0.8719 | AUPRC=0.8595
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4640 | val_loss=0.3889 | val_mcc=0.5856 | val_f1=0.6685 | val_auroc=0.8917

[Epoch 02] train_loss=0.4010 | val_loss=0.3472 | val_mcc=0.6172 | val_f1=0.6934 | val_auroc=0.8985

[Epoch 03] train_loss=0.3706 | val_loss=0.3634 | val_mcc=0.6042 | val_f1=0.6834 | val_auroc=0.8970

[Epoch 04] train_loss=0.3339 | val_loss=0.3551 | val_mcc=0.6131 | val_f1=0.6903 | val_auroc=0.8978

[Epoch 05] train_loss=0.2902 | val_loss=0.3919 | val_mcc=0.5728 | val_f1=0.6588 | val_auroc=0.8845

[Epoch 06] train_loss=0.2383 | val_loss=0.4496 | val_mcc=0.5736 | val_f1=0.6590 | val_auroc=0.8847

[Epoch 07] train_loss=0.1676 | val_loss=0.5082 | val_mcc=0.5637 | val_f1=0.6513 | val_auroc=0.8801

[Epoch 08] train_loss=0.1373 | val_loss=0.6373 | val_mcc=0.5412 | val_f1=0.6313 | val_auroc=0.8777
[EarlyStop] epoch=8 | best_val_mcc=0.6172
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6739 | F1=0.7624 | AUROC=0.9080 | AUPRC=0.8324
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6251 | F1=0.8053 | AUROC=0.8830 | AUPRC=0.8928
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4448 | F1=0.7081 | AUROC=0.7752 | AUPRC=0.7753
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6131 | F1=0.7860 | AUROC=0.8743 | AUPRC=0.8692
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4586 | val_loss=0.3521 | val_mcc=0.6025 | val_f1=0.6820 | val_auroc=0.8944

[Epoch 02] train_loss=0.3883 | val_loss=0.3424 | val_mcc=0.6129 | val_f1=0.6898 | val_auroc=0.8968

[Epoch 03] train_loss=0.3512 | val_loss=0.3274 | val_mcc=0.6175 | val_f1=0.6925 | val_auroc=0.8950

[Epoch 04] train_loss=0.3085 | val_loss=0.3797 | val_mcc=0.5877 | val_f1=0.6704 | val_auroc=0.8937

[Epoch 05] train_loss=0.2559 | val_loss=0.4083 | val_mcc=0.5670 | val_f1=0.6543 | val_auroc=0.8831

[Epoch 06] train_loss=0.2005 | val_loss=0.4613 | val_mcc=0.5543 | val_f1=0.6441 | val_auroc=0.8809

[Epoch 07] train_loss=0.1530 | val_loss=0.5266 | val_mcc=0.5553 | val_f1=0.6449 | val_auroc=0.8790

[Epoch 08] train_loss=0.0950 | val_loss=0.5839 | val_mcc=0.5721 | val_f1=0.6582 | val_auroc=0.8829

[Epoch 09] train_loss=0.0770 | val_loss=0.6194 | val_mcc=0.5624 | val_f1=0.6507 | val_auroc=0.8795
[EarlyStop] epoch=9 | best_val_mcc=0.6175
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6677 | F1=0.7556 | AUROC=0.9066 | AUPRC=0.8270
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6318 | F1=0.8054 | AUROC=0.8791 | AUPRC=0.8925
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4350 | F1=0.6941 | AUROC=0.7681 | AUPRC=0.7692
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6186 | F1=0.7848 | AUROC=0.8757 | AUPRC=0.8665
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4683 | val_loss=0.3634 | val_mcc=0.5873 | val_f1=0.6702 | val_auroc=0.8918

[Epoch 02] train_loss=0.3890 | val_loss=0.3614 | val_mcc=0.5991 | val_f1=0.6794 | val_auroc=0.8987

[Epoch 03] train_loss=0.3416 | val_loss=0.3506 | val_mcc=0.6033 | val_f1=0.6827 | val_auroc=0.8980

[Epoch 04] train_loss=0.2942 | val_loss=0.3629 | val_mcc=0.5975 | val_f1=0.6782 | val_auroc=0.8950

[Epoch 05] train_loss=0.2355 | val_loss=0.3951 | val_mcc=0.5783 | val_f1=0.6632 | val_auroc=0.8886

[Epoch 06] train_loss=0.1787 | val_loss=0.4347 | val_mcc=0.5647 | val_f1=0.6525 | val_auroc=0.8864

[Epoch 07] train_loss=0.1274 | val_loss=0.4985 | val_mcc=0.5505 | val_f1=0.6410 | val_auroc=0.8835

[Epoch 08] train_loss=0.0808 | val_loss=0.5249 | val_mcc=0.5570 | val_f1=0.6461 | val_auroc=0.8855

[Epoch 09] train_loss=0.0597 | val_loss=0.5579 | val_mcc=0.5584 | val_f1=0.6470 | val_auroc=0.8861
[EarlyStop] epoch=9 | best_val_mcc=0.6033
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6620 | F1=0.7561 | AUROC=0.9050 | AUPRC=0.8265
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6045 | F1=0.7988 | AUROC=0.8858 | AUPRC=0.8947
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4125 | F1=0.6957 | AUROC=0.7749 | AUPRC=0.7759
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6255 | F1=0.7924 | AUROC=0.8779 | AUPRC=0.8704
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 346.
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6650 | F1=0.7589 | AUROC=0.9097 | AUPRC=0.8300
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6417 | F1=0.8163 | AUROC=0.8920 | AUPRC=0.8871
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4379 | F1=0.7095 | AUROC=0.7789 | AUPRC=0.7689
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6127 | F1=0.7899 | AUROC=0.8809 | AUPRC=0.8657
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 177.
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6568 | F1=0.7527 | AUROC=0.9078 | AUPRC=0.8221
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6103 | F1=0.8040 | AUROC=0.8846 | AUPRC=0.8939
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4239 | F1=0.7086 | AUROC=0.7700 | AUPRC=0.7694
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.6035 | F1=0.7858 | AUROC=0.8787 | AUPRC=0.8697
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 42.
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6695 | F1=0.7615 | AUROC=0.9100 | AUPRC=0.8340
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6159 | F1=0.8069 | AUROC=0.8905 | AUPRC=0.8985
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4210 | F1=0.7044 | AUROC=0.7726 | AUPRC=0.7793
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.6056 | F1=0.7883 | AUROC=0.8739 | AUPRC=0.8684
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 75.
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6455 | F1=0.7444 | AUROC=0.9047 | AUPRC=0.8217
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5988 | F1=0.7971 | AUROC=0.8866 | AUPRC=0.8857
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4257 | F1=0.7052 | AUROC=0.7753 | AUPRC=0.7678
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5919 | F1=0.7779 | AUROC=0.8733 | AUPRC=0.8674
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.4728 | val_loss=0.3948 | val_mcc=0.5504 | val_f1=0.6414 | val_auroc=0.8769

[Epoch 02] train_loss=0.3968 | val_loss=0.3733 | val_mcc=0.5707 | val_f1=0.6571 | val_auroc=0.8845

[Epoch 03] train_loss=0.3559 | val_loss=0.3573 | val_mcc=0.5842 | val_f1=0.6674 | val_auroc=0.8865

[Epoch 04] train_loss=0.3109 | val_loss=0.3729 | val_mcc=0.5712 | val_f1=0.6576 | val_auroc=0.8840

[Epoch 05] train_loss=0.2620 | val_loss=0.4413 | val_mcc=0.5313 | val_f1=0.6259 | val_auroc=0.8796

[Epoch 06] train_loss=0.2088 | val_loss=0.4339 | val_mcc=0.5420 | val_f1=0.6349 | val_auroc=0.8764

[Epoch 07] train_loss=0.1593 | val_loss=0.4947 | val_mcc=0.5264 | val_f1=0.6227 | val_auroc=0.8715

[Epoch 08] train_loss=0.1044 | val_loss=0.5180 | val_mcc=0.5404 | val_f1=0.6336 | val_auroc=0.8739

[Epoch 09] train_loss=0.0835 | val_loss=0.5399 | val_mcc=0.5394 | val_f1=0.6328 | val_auroc=0.8737
[EarlyStop] epoch=9 | best_val_mcc=0.5842
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6192 | F1=0.7224 | AUROC=0.8915 | AUPRC=0.7994
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6227 | F1=0.8024 | AUROC=0.8850 | AUPRC=0.8822
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4136 | F1=0.6990 | AUROC=0.7625 | AUPRC=0.7572
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5581 | F1=0.7469 | AUROC=0.8526 | AUPRC=0.8406
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4763 | val_loss=0.3969 | val_mcc=0.5582 | val_f1=0.6474 | val_auroc=0.8800

[Epoch 02] train_loss=0.4057 | val_loss=0.3609 | val_mcc=0.5821 | val_f1=0.6654 | val_auroc=0.8835

[Epoch 03] train_loss=0.3727 | val_loss=0.4045 | val_mcc=0.5524 | val_f1=0.6426 | val_auroc=0.8862

[Epoch 04] train_loss=0.3356 | val_loss=0.4263 | val_mcc=0.5618 | val_f1=0.6492 | val_auroc=0.8882

[Epoch 05] train_loss=0.2863 | val_loss=0.4428 | val_mcc=0.5418 | val_f1=0.6341 | val_auroc=0.8758

[Epoch 06] train_loss=0.2398 | val_loss=0.4838 | val_mcc=0.5264 | val_f1=0.6226 | val_auroc=0.8656

[Epoch 07] train_loss=0.1690 | val_loss=0.5512 | val_mcc=0.5212 | val_f1=0.6183 | val_auroc=0.8670

[Epoch 08] train_loss=0.1381 | val_loss=0.5993 | val_mcc=0.5157 | val_f1=0.6143 | val_auroc=0.8618
[EarlyStop] epoch=8 | best_val_mcc=0.5821
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6131 | F1=0.7161 | AUROC=0.8827 | AUPRC=0.7959
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6083 | F1=0.7953 | AUROC=0.8771 | AUPRC=0.8728
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4235 | F1=0.6980 | AUROC=0.7663 | AUPRC=0.7580
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5429 | F1=0.7380 | AUROC=0.8404 | AUPRC=0.8339
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4708 | val_loss=0.3932 | val_mcc=0.5581 | val_f1=0.6473 | val_auroc=0.8771

[Epoch 02] train_loss=0.3981 | val_loss=0.3459 | val_mcc=0.5843 | val_f1=0.6654 | val_auroc=0.8820

[Epoch 03] train_loss=0.3569 | val_loss=0.3633 | val_mcc=0.5813 | val_f1=0.6651 | val_auroc=0.8879

[Epoch 04] train_loss=0.3054 | val_loss=0.3675 | val_mcc=0.5725 | val_f1=0.6568 | val_auroc=0.8786

[Epoch 05] train_loss=0.2576 | val_loss=0.4636 | val_mcc=0.5297 | val_f1=0.6248 | val_auroc=0.8742

[Epoch 06] train_loss=0.2029 | val_loss=0.4864 | val_mcc=0.5324 | val_f1=0.6274 | val_auroc=0.8720

[Epoch 07] train_loss=0.1322 | val_loss=0.5620 | val_mcc=0.5246 | val_f1=0.6212 | val_auroc=0.8712

[Epoch 08] train_loss=0.0988 | val_loss=0.6494 | val_mcc=0.5180 | val_f1=0.6154 | val_auroc=0.8713
[EarlyStop] epoch=8 | best_val_mcc=0.5843
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6149 | F1=0.7133 | AUROC=0.8832 | AUPRC=0.7880
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6263 | F1=0.7957 | AUROC=0.8884 | AUPRC=0.8817
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4447 | F1=0.7024 | AUROC=0.7744 | AUPRC=0.7649
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5308 | F1=0.7205 | AUROC=0.8423 | AUPRC=0.8327
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4808 | val_loss=0.4005 | val_mcc=0.5461 | val_f1=0.6380 | val_auroc=0.8756

[Epoch 02] train_loss=0.3974 | val_loss=0.3654 | val_mcc=0.5765 | val_f1=0.6614 | val_auroc=0.8835

[Epoch 03] train_loss=0.3445 | val_loss=0.3726 | val_mcc=0.5708 | val_f1=0.6573 | val_auroc=0.8848

[Epoch 04] train_loss=0.2947 | val_loss=0.4091 | val_mcc=0.5525 | val_f1=0.6424 | val_auroc=0.8841

[Epoch 05] train_loss=0.2400 | val_loss=0.4264 | val_mcc=0.5547 | val_f1=0.6446 | val_auroc=0.8795

[Epoch 06] train_loss=0.1755 | val_loss=0.4879 | val_mcc=0.5349 | val_f1=0.6287 | val_auroc=0.8782

[Epoch 07] train_loss=0.1199 | val_loss=0.5123 | val_mcc=0.5431 | val_f1=0.6352 | val_auroc=0.8792

[Epoch 08] train_loss=0.0893 | val_loss=0.5293 | val_mcc=0.5432 | val_f1=0.6354 | val_auroc=0.8785
[EarlyStop] epoch=8 | best_val_mcc=0.5765
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6093 | F1=0.7135 | AUROC=0.8858 | AUPRC=0.7909
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6153 | F1=0.7952 | AUROC=0.8823 | AUPRC=0.8793
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4246 | F1=0.7014 | AUROC=0.7670 | AUPRC=0.7648
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5443 | F1=0.7382 | AUROC=0.8428 | AUPRC=0.8354
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 319.
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6099 | F1=0.7182 | AUROC=0.8907 | AUPRC=0.7863
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6306 | F1=0.8088 | AUROC=0.8825 | AUPRC=0.8738
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4390 | F1=0.7136 | AUROC=0.7745 | AUPRC=0.7704
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5565 | F1=0.7525 | AUROC=0.8556 | AUPRC=0.8329
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 188.
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6183 | F1=0.7247 | AUROC=0.8886 | AUPRC=0.7944
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6302 | F1=0.8110 | AUROC=0.8833 | AUPRC=0.8747
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4283 | F1=0.7120 | AUROC=0.7679 | AUPRC=0.7546
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5375 | F1=0.7437 | AUROC=0.8408 | AUPRC=0.8325
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 46.
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6207 | F1=0.7257 | AUROC=0.8916 | AUPRC=0.7986
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6332 | F1=0.8117 | AUROC=0.8911 | AUPRC=0.8873
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4313 | F1=0.7144 | AUROC=0.7658 | AUPRC=0.7529
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5541 | F1=0.7540 | AUROC=0.8422 | AUPRC=0.8335
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 47.
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6055 | F1=0.7149 | AUROC=0.8881 | AUPRC=0.7945
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6019 | F1=0.7953 | AUROC=0.8766 | AUPRC=0.8660
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4163 | F1=0.7060 | AUROC=0.7717 | AUPRC=0.7661
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5455 | F1=0.7456 | AUROC=0.8433 | AUPRC=0.8333
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.4848 | val_loss=0.3497 | val_mcc=0.6183 | val_f1=0.6900 | val_auroc=0.8749

[Epoch 02] train_loss=0.4036 | val_loss=0.3195 | val_mcc=0.6296 | val_f1=0.6993 | val_auroc=0.8926

[Epoch 03] train_loss=0.3488 | val_loss=0.3597 | val_mcc=0.5934 | val_f1=0.6749 | val_auroc=0.8993

[Epoch 04] train_loss=0.2913 | val_loss=0.3485 | val_mcc=0.6062 | val_f1=0.6849 | val_auroc=0.8974

[Epoch 05] train_loss=0.2251 | val_loss=0.3787 | val_mcc=0.5840 | val_f1=0.6676 | val_auroc=0.8929

[Epoch 06] train_loss=0.1611 | val_loss=0.4934 | val_mcc=0.5376 | val_f1=0.6288 | val_auroc=0.8878

[Epoch 07] train_loss=0.1011 | val_loss=0.4611 | val_mcc=0.5730 | val_f1=0.6586 | val_auroc=0.8916

[Epoch 08] train_loss=0.0743 | val_loss=0.5203 | val_mcc=0.5537 | val_f1=0.6429 | val_auroc=0.8875
[EarlyStop] epoch=8 | best_val_mcc=0.6296
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6722 | F1=0.7556 | AUROC=0.9006 | AUPRC=0.8342
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6205 | F1=0.7926 | AUROC=0.8885 | AUPRC=0.9025
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4465 | F1=0.6930 | AUROC=0.7713 | AUPRC=0.7729
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6289 | F1=0.7821 | AUROC=0.8777 | AUPRC=0.8751
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4826 | val_loss=0.3139 | val_mcc=0.6303 | val_f1=0.6885 | val_auroc=0.8816

[Epoch 02] train_loss=0.4112 | val_loss=0.3785 | val_mcc=0.5937 | val_f1=0.6752 | val_auroc=0.8963

[Epoch 03] train_loss=0.3625 | val_loss=0.3655 | val_mcc=0.6004 | val_f1=0.6804 | val_auroc=0.9035

[Epoch 04] train_loss=0.3036 | val_loss=0.3428 | val_mcc=0.6108 | val_f1=0.6878 | val_auroc=0.8956

[Epoch 05] train_loss=0.2353 | val_loss=0.4536 | val_mcc=0.5663 | val_f1=0.6534 | val_auroc=0.8892

[Epoch 06] train_loss=0.1488 | val_loss=0.5231 | val_mcc=0.5613 | val_f1=0.6498 | val_auroc=0.8828

[Epoch 07] train_loss=0.1097 | val_loss=0.6492 | val_mcc=0.5298 | val_f1=0.6243 | val_auroc=0.8744
[EarlyStop] epoch=7 | best_val_mcc=0.6303
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6637 | F1=0.7359 | AUROC=0.8926 | AUPRC=0.8281
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6063 | F1=0.7611 | AUROC=0.8830 | AUPRC=0.8956
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4354 | F1=0.6655 | AUROC=0.7720 | AUPRC=0.7715
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5971 | F1=0.7485 | AUROC=0.8636 | AUPRC=0.8635
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4800 | val_loss=0.3102 | val_mcc=0.6372 | val_f1=0.6950 | val_auroc=0.8823

[Epoch 02] train_loss=0.4050 | val_loss=0.3070 | val_mcc=0.6281 | val_f1=0.6965 | val_auroc=0.8934

[Epoch 03] train_loss=0.3509 | val_loss=0.3487 | val_mcc=0.5964 | val_f1=0.6773 | val_auroc=0.8995

[Epoch 04] train_loss=0.2946 | val_loss=0.3489 | val_mcc=0.5991 | val_f1=0.6791 | val_auroc=0.8967

[Epoch 05] train_loss=0.2210 | val_loss=0.4388 | val_mcc=0.5550 | val_f1=0.6442 | val_auroc=0.8906

[Epoch 06] train_loss=0.1386 | val_loss=0.5194 | val_mcc=0.5601 | val_f1=0.6487 | val_auroc=0.8879

[Epoch 07] train_loss=0.0971 | val_loss=0.5589 | val_mcc=0.5741 | val_f1=0.6598 | val_auroc=0.8872
[EarlyStop] epoch=7 | best_val_mcc=0.6372
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6563 | F1=0.7315 | AUROC=0.8949 | AUPRC=0.8275
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5726 | F1=0.7443 | AUROC=0.8807 | AUPRC=0.8914
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4444 | F1=0.6713 | AUROC=0.7758 | AUPRC=0.7753
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5944 | F1=0.7436 | AUROC=0.8698 | AUPRC=0.8692
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4844 | val_loss=0.3441 | val_mcc=0.6211 | val_f1=0.6895 | val_auroc=0.8743

[Epoch 02] train_loss=0.4041 | val_loss=0.3334 | val_mcc=0.6187 | val_f1=0.6929 | val_auroc=0.8923

[Epoch 03] train_loss=0.3454 | val_loss=0.3554 | val_mcc=0.5968 | val_f1=0.6776 | val_auroc=0.8967

[Epoch 04] train_loss=0.2823 | val_loss=0.3668 | val_mcc=0.5925 | val_f1=0.6741 | val_auroc=0.8959

[Epoch 05] train_loss=0.2051 | val_loss=0.4241 | val_mcc=0.5594 | val_f1=0.6474 | val_auroc=0.8888

[Epoch 06] train_loss=0.1303 | val_loss=0.4008 | val_mcc=0.5876 | val_f1=0.6701 | val_auroc=0.8909

[Epoch 07] train_loss=0.0957 | val_loss=0.4805 | val_mcc=0.5655 | val_f1=0.6524 | val_auroc=0.8893
[EarlyStop] epoch=7 | best_val_mcc=0.6211
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6690 | F1=0.7506 | AUROC=0.8925 | AUPRC=0.8258
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5816 | F1=0.7634 | AUROC=0.8678 | AUPRC=0.8852
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4657 | F1=0.7009 | AUROC=0.7687 | AUPRC=0.7743
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5984 | F1=0.7596 | AUROC=0.8612 | AUPRC=0.8617
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 352.
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6624 | F1=0.7548 | AUROC=0.9095 | AUPRC=0.8332
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6557 | F1=0.8254 | AUROC=0.8911 | AUPRC=0.8958
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4288 | F1=0.7058 | AUROC=0.7719 | AUPRC=0.7723
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6075 | F1=0.7820 | AUROC=0.8774 | AUPRC=0.8653
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 227.
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6625 | F1=0.7562 | AUROC=0.9094 | AUPRC=0.8394
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6565 | F1=0.8213 | AUROC=0.9013 | AUPRC=0.9081
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4073 | F1=0.7028 | AUROC=0.7756 | AUPRC=0.7748
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5970 | F1=0.7793 | AUROC=0.8772 | AUPRC=0.8691
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 46.
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6540 | F1=0.7509 | AUROC=0.9051 | AUPRC=0.8334
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6472 | F1=0.8213 | AUROC=0.8996 | AUPRC=0.9106
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4418 | F1=0.7190 | AUROC=0.7798 | AUPRC=0.7728
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5976 | F1=0.7816 | AUROC=0.8731 | AUPRC=0.8635
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 51.
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6441 | F1=0.7443 | AUROC=0.9065 | AUPRC=0.8373
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6559 | F1=0.8234 | AUROC=0.8938 | AUPRC=0.9043
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4358 | F1=0.7160 | AUROC=0.7770 | AUPRC=0.7727
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.6158 | F1=0.7923 | AUROC=0.8782 | AUPRC=0.8761
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.4577 | val_loss=0.3599 | val_mcc=0.5968 | val_f1=0.6776 | val_auroc=0.8928

[Epoch 02] train_loss=0.4007 | val_loss=0.3338 | val_mcc=0.6142 | val_f1=0.6907 | val_auroc=0.9013

[Epoch 03] train_loss=0.3788 | val_loss=0.3242 | val_mcc=0.6291 | val_f1=0.7025 | val_auroc=0.9023

[Epoch 04] train_loss=0.3581 | val_loss=0.3306 | val_mcc=0.6190 | val_f1=0.6947 | val_auroc=0.9053

[Epoch 05] train_loss=0.3418 | val_loss=0.3562 | val_mcc=0.6037 | val_f1=0.6830 | val_auroc=0.9017

[Epoch 06] train_loss=0.3264 | val_loss=0.3706 | val_mcc=0.5939 | val_f1=0.6752 | val_auroc=0.9006

[Epoch 07] train_loss=0.3084 | val_loss=0.3625 | val_mcc=0.5918 | val_f1=0.6735 | val_auroc=0.9003

[Epoch 08] train_loss=0.2800 | val_loss=0.3600 | val_mcc=0.6106 | val_f1=0.6884 | val_auroc=0.9051

[Epoch 09] train_loss=0.2658 | val_loss=0.3760 | val_mcc=0.5940 | val_f1=0.6754 | val_auroc=0.9002
[EarlyStop] epoch=9 | best_val_mcc=0.6291
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6725 | F1=0.7613 | AUROC=0.9115 | AUPRC=0.8341
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6309 | F1=0.8077 | AUROC=0.8893 | AUPRC=0.8932
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4509 | F1=0.7108 | AUROC=0.7855 | AUPRC=0.7800
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6185 | F1=0.7878 | AUROC=0.8862 | AUPRC=0.8753
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4661 | val_loss=0.3430 | val_mcc=0.6107 | val_f1=0.6878 | val_auroc=0.8969

[Epoch 02] train_loss=0.4102 | val_loss=0.3322 | val_mcc=0.6213 | val_f1=0.6962 | val_auroc=0.8983

[Epoch 03] train_loss=0.3885 | val_loss=0.3559 | val_mcc=0.6203 | val_f1=0.6960 | val_auroc=0.9063

[Epoch 04] train_loss=0.3687 | val_loss=0.3503 | val_mcc=0.6159 | val_f1=0.6926 | val_auroc=0.9040

[Epoch 05] train_loss=0.3534 | val_loss=0.3410 | val_mcc=0.6275 | val_f1=0.7017 | val_auroc=0.9057

[Epoch 06] train_loss=0.3324 | val_loss=0.3300 | val_mcc=0.6207 | val_f1=0.6959 | val_auroc=0.9058

[Epoch 07] train_loss=0.3175 | val_loss=0.3695 | val_mcc=0.6119 | val_f1=0.6895 | val_auroc=0.9013

[Epoch 08] train_loss=0.2992 | val_loss=0.4429 | val_mcc=0.5754 | val_f1=0.6586 | val_auroc=0.8960

[Epoch 09] train_loss=0.2860 | val_loss=0.4890 | val_mcc=0.5589 | val_f1=0.6433 | val_auroc=0.8999

[Epoch 10] train_loss=0.2523 | val_loss=0.4076 | val_mcc=0.5936 | val_f1=0.6751 | val_auroc=0.8955

[Epoch 11] train_loss=0.2397 | val_loss=0.4171 | val_mcc=0.5934 | val_f1=0.6749 | val_auroc=0.8944
[EarlyStop] epoch=11 | best_val_mcc=0.6275
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6803 | F1=0.7673 | AUROC=0.9165 | AUPRC=0.8425
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6391 | F1=0.8135 | AUROC=0.9006 | AUPRC=0.9006
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4514 | F1=0.7167 | AUROC=0.7886 | AUPRC=0.7854
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6203 | F1=0.7922 | AUROC=0.8892 | AUPRC=0.8728
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4594 | val_loss=0.4023 | val_mcc=0.5730 | val_f1=0.6582 | val_auroc=0.8862

[Epoch 02] train_loss=0.4068 | val_loss=0.3365 | val_mcc=0.6196 | val_f1=0.6952 | val_auroc=0.8996

[Epoch 03] train_loss=0.3801 | val_loss=0.3745 | val_mcc=0.5936 | val_f1=0.6748 | val_auroc=0.8960

[Epoch 04] train_loss=0.3663 | val_loss=0.3735 | val_mcc=0.6032 | val_f1=0.6819 | val_auroc=0.9034

[Epoch 05] train_loss=0.3473 | val_loss=0.3544 | val_mcc=0.6122 | val_f1=0.6897 | val_auroc=0.9004

[Epoch 06] train_loss=0.3268 | val_loss=0.3322 | val_mcc=0.6261 | val_f1=0.6992 | val_auroc=0.8998

[Epoch 07] train_loss=0.3077 | val_loss=0.3941 | val_mcc=0.6017 | val_f1=0.6811 | val_auroc=0.9016

[Epoch 08] train_loss=0.2895 | val_loss=0.4634 | val_mcc=0.5482 | val_f1=0.6370 | val_auroc=0.8913

[Epoch 09] train_loss=0.2713 | val_loss=0.3914 | val_mcc=0.5937 | val_f1=0.6751 | val_auroc=0.8945

[Epoch 10] train_loss=0.2554 | val_loss=0.4362 | val_mcc=0.5719 | val_f1=0.6579 | val_auroc=0.8918

[Epoch 11] train_loss=0.2190 | val_loss=0.4141 | val_mcc=0.5903 | val_f1=0.6723 | val_auroc=0.8900

[Epoch 12] train_loss=0.2024 | val_loss=0.4778 | val_mcc=0.5608 | val_f1=0.6492 | val_auroc=0.8842
[EarlyStop] epoch=12 | best_val_mcc=0.6261
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6817 | F1=0.7662 | AUROC=0.9096 | AUPRC=0.8325
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6284 | F1=0.8053 | AUROC=0.8945 | AUPRC=0.8937
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4423 | F1=0.7047 | AUROC=0.7841 | AUPRC=0.7757
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6254 | F1=0.7921 | AUROC=0.8851 | AUPRC=0.8711
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4649 | val_loss=0.3576 | val_mcc=0.5950 | val_f1=0.6762 | val_auroc=0.8950

[Epoch 02] train_loss=0.4019 | val_loss=0.3549 | val_mcc=0.6009 | val_f1=0.6808 | val_auroc=0.8973

[Epoch 03] train_loss=0.3808 | val_loss=0.3514 | val_mcc=0.6192 | val_f1=0.6952 | val_auroc=0.9034

[Epoch 04] train_loss=0.3609 | val_loss=0.3261 | val_mcc=0.6225 | val_f1=0.6972 | val_auroc=0.9029

[Epoch 05] train_loss=0.3398 | val_loss=0.3675 | val_mcc=0.5925 | val_f1=0.6738 | val_auroc=0.9015

[Epoch 06] train_loss=0.3226 | val_loss=0.3527 | val_mcc=0.6056 | val_f1=0.6845 | val_auroc=0.9000

[Epoch 07] train_loss=0.3041 | val_loss=0.3474 | val_mcc=0.6036 | val_f1=0.6827 | val_auroc=0.8967

[Epoch 08] train_loss=0.2818 | val_loss=0.3819 | val_mcc=0.5902 | val_f1=0.6721 | val_auroc=0.9016

[Epoch 09] train_loss=0.2512 | val_loss=0.3853 | val_mcc=0.5944 | val_f1=0.6757 | val_auroc=0.8990

[Epoch 10] train_loss=0.2379 | val_loss=0.4202 | val_mcc=0.5783 | val_f1=0.6622 | val_auroc=0.8975
[EarlyStop] epoch=10 | best_val_mcc=0.6225
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6793 | F1=0.7647 | AUROC=0.9133 | AUPRC=0.8396
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6202 | F1=0.8000 | AUROC=0.8905 | AUPRC=0.8971
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4411 | F1=0.7027 | AUROC=0.7786 | AUPRC=0.7780
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6227 | F1=0.7896 | AUROC=0.8851 | AUPRC=0.8729
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 314.
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6676 | F1=0.7607 | AUROC=0.9140 | AUPRC=0.8356
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6301 | F1=0.8127 | AUROC=0.8955 | AUPRC=0.8961
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4228 | F1=0.7027 | AUROC=0.7830 | AUPRC=0.7845
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5987 | F1=0.7845 | AUROC=0.8772 | AUPRC=0.8618
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 127.
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6634 | F1=0.7577 | AUROC=0.9121 | AUPRC=0.8313
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6273 | F1=0.8110 | AUROC=0.8951 | AUPRC=0.8984
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4299 | F1=0.7121 | AUROC=0.7751 | AUPRC=0.7704
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.6131 | F1=0.7911 | AUROC=0.8825 | AUPRC=0.8715
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 65.
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6773 | F1=0.7669 | AUROC=0.9160 | AUPRC=0.8363
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6159 | F1=0.8046 | AUROC=0.8927 | AUPRC=0.8980
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4464 | F1=0.7190 | AUROC=0.7887 | AUPRC=0.7903
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.6130 | F1=0.7908 | AUROC=0.8845 | AUPRC=0.8741
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 65.
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6694 | F1=0.7610 | AUROC=0.9110 | AUPRC=0.8275
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6074 | F1=0.8000 | AUROC=0.8856 | AUPRC=0.8822
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4209 | F1=0.7053 | AUROC=0.7838 | AUPRC=0.7824
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.6223 | F1=0.7953 | AUROC=0.8808 | AUPRC=0.8625
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.4701 | val_loss=0.3540 | val_mcc=0.5732 | val_f1=0.6577 | val_auroc=0.8792

[Epoch 02] train_loss=0.4101 | val_loss=0.3455 | val_mcc=0.5968 | val_f1=0.6764 | val_auroc=0.8903

[Epoch 03] train_loss=0.3841 | val_loss=0.3644 | val_mcc=0.5859 | val_f1=0.6691 | val_auroc=0.8936

[Epoch 04] train_loss=0.3639 | val_loss=0.3818 | val_mcc=0.5846 | val_f1=0.6679 | val_auroc=0.8949

[Epoch 05] train_loss=0.3446 | val_loss=0.3431 | val_mcc=0.5941 | val_f1=0.6753 | val_auroc=0.8960

[Epoch 06] train_loss=0.3224 | val_loss=0.3577 | val_mcc=0.5906 | val_f1=0.6728 | val_auroc=0.8962

[Epoch 07] train_loss=0.2934 | val_loss=0.3466 | val_mcc=0.6027 | val_f1=0.6819 | val_auroc=0.8961

[Epoch 08] train_loss=0.2800 | val_loss=0.3622 | val_mcc=0.5942 | val_f1=0.6756 | val_auroc=0.8951

[Epoch 09] train_loss=0.2655 | val_loss=0.3653 | val_mcc=0.5843 | val_f1=0.6678 | val_auroc=0.8929

[Epoch 10] train_loss=0.2540 | val_loss=0.3804 | val_mcc=0.5843 | val_f1=0.6678 | val_auroc=0.8895

[Epoch 11] train_loss=0.2400 | val_loss=0.4394 | val_mcc=0.5568 | val_f1=0.6456 | val_auroc=0.8864

[Epoch 12] train_loss=0.2203 | val_loss=0.4198 | val_mcc=0.5684 | val_f1=0.6552 | val_auroc=0.8884

[Epoch 13] train_loss=0.2094 | val_loss=0.4370 | val_mcc=0.5666 | val_f1=0.6537 | val_auroc=0.8865
[EarlyStop] epoch=13 | best_val_mcc=0.6027
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6410 | F1=0.7365 | AUROC=0.8997 | AUPRC=0.8092
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6270 | F1=0.8006 | AUROC=0.8849 | AUPRC=0.8778
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4472 | F1=0.7124 | AUROC=0.7747 | AUPRC=0.7615
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5641 | F1=0.7476 | AUROC=0.8605 | AUPRC=0.8451
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4776 | val_loss=0.3343 | val_mcc=0.5911 | val_f1=0.6665 | val_auroc=0.8794

[Epoch 02] train_loss=0.4156 | val_loss=0.3527 | val_mcc=0.5861 | val_f1=0.6688 | val_auroc=0.8893

[Epoch 03] train_loss=0.3913 | val_loss=0.3603 | val_mcc=0.5906 | val_f1=0.6728 | val_auroc=0.8964

[Epoch 04] train_loss=0.3712 | val_loss=0.3530 | val_mcc=0.5887 | val_f1=0.6708 | val_auroc=0.8940

[Epoch 05] train_loss=0.3520 | val_loss=0.4031 | val_mcc=0.5784 | val_f1=0.6619 | val_auroc=0.8992

[Epoch 06] train_loss=0.3198 | val_loss=0.3929 | val_mcc=0.5871 | val_f1=0.6695 | val_auroc=0.8974

[Epoch 07] train_loss=0.3056 | val_loss=0.3859 | val_mcc=0.5853 | val_f1=0.6686 | val_auroc=0.8922
[EarlyStop] epoch=7 | best_val_mcc=0.5911
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6098 | F1=0.7010 | AUROC=0.8807 | AUPRC=0.7895
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5725 | F1=0.7540 | AUROC=0.8710 | AUPRC=0.8681
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4431 | F1=0.6840 | AUROC=0.7687 | AUPRC=0.7661
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5459 | F1=0.7178 | AUROC=0.8364 | AUPRC=0.8316
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4728 | val_loss=0.3660 | val_mcc=0.5814 | val_f1=0.6645 | val_auroc=0.8807

[Epoch 02] train_loss=0.4139 | val_loss=0.3267 | val_mcc=0.6066 | val_f1=0.6816 | val_auroc=0.8917

[Epoch 03] train_loss=0.3864 | val_loss=0.3638 | val_mcc=0.5869 | val_f1=0.6699 | val_auroc=0.8917

[Epoch 04] train_loss=0.3645 | val_loss=0.3414 | val_mcc=0.5987 | val_f1=0.6788 | val_auroc=0.8964

[Epoch 05] train_loss=0.3438 | val_loss=0.3553 | val_mcc=0.5947 | val_f1=0.6757 | val_auroc=0.8940

[Epoch 06] train_loss=0.3256 | val_loss=0.3649 | val_mcc=0.5927 | val_f1=0.6743 | val_auroc=0.8941

[Epoch 07] train_loss=0.2919 | val_loss=0.3775 | val_mcc=0.5954 | val_f1=0.6766 | val_auroc=0.8941

[Epoch 08] train_loss=0.2726 | val_loss=0.4094 | val_mcc=0.5844 | val_f1=0.6679 | val_auroc=0.8906
[EarlyStop] epoch=8 | best_val_mcc=0.6066
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6289 | F1=0.7175 | AUROC=0.8946 | AUPRC=0.8027
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6184 | F1=0.7849 | AUROC=0.8858 | AUPRC=0.8714
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4561 | F1=0.7010 | AUROC=0.7766 | AUPRC=0.7706
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5708 | F1=0.7380 | AUROC=0.8518 | AUPRC=0.8415
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4792 | val_loss=0.4104 | val_mcc=0.5439 | val_f1=0.6363 | val_auroc=0.8777

[Epoch 02] train_loss=0.4123 | val_loss=0.3718 | val_mcc=0.5843 | val_f1=0.6678 | val_auroc=0.8920

[Epoch 03] train_loss=0.3853 | val_loss=0.3598 | val_mcc=0.5914 | val_f1=0.6734 | val_auroc=0.8944

[Epoch 04] train_loss=0.3583 | val_loss=0.3535 | val_mcc=0.5914 | val_f1=0.6734 | val_auroc=0.8985

[Epoch 05] train_loss=0.3395 | val_loss=0.3530 | val_mcc=0.5958 | val_f1=0.6768 | val_auroc=0.8995

[Epoch 06] train_loss=0.3135 | val_loss=0.3988 | val_mcc=0.5644 | val_f1=0.6517 | val_auroc=0.8899

[Epoch 07] train_loss=0.2964 | val_loss=0.3649 | val_mcc=0.5790 | val_f1=0.6635 | val_auroc=0.8894

[Epoch 08] train_loss=0.2736 | val_loss=0.3657 | val_mcc=0.5843 | val_f1=0.6674 | val_auroc=0.8900

[Epoch 09] train_loss=0.2542 | val_loss=0.4140 | val_mcc=0.5677 | val_f1=0.6548 | val_auroc=0.8874

[Epoch 10] train_loss=0.2212 | val_loss=0.4299 | val_mcc=0.5683 | val_f1=0.6550 | val_auroc=0.8902

[Epoch 11] train_loss=0.2044 | val_loss=0.4587 | val_mcc=0.5486 | val_f1=0.6391 | val_auroc=0.8877
[EarlyStop] epoch=11 | best_val_mcc=0.5958
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6411 | F1=0.7390 | AUROC=0.9021 | AUPRC=0.8142
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6311 | F1=0.8071 | AUROC=0.8844 | AUPRC=0.8757
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4524 | F1=0.7224 | AUROC=0.7764 | AUPRC=0.7651
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5689 | F1=0.7596 | AUROC=0.8581 | AUPRC=0.8466
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 275.
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6194 | F1=0.7248 | AUROC=0.8973 | AUPRC=0.8010
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6588 | F1=0.8246 | AUROC=0.8937 | AUPRC=0.8748
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4615 | F1=0.7257 | AUROC=0.7803 | AUPRC=0.7700
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5512 | F1=0.7510 | AUROC=0.8564 | AUPRC=0.8293
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 161.
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6208 | F1=0.7266 | AUROC=0.8976 | AUPRC=0.8066
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6132 | F1=0.8017 | AUROC=0.8948 | AUPRC=0.8871
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4104 | F1=0.7061 | AUROC=0.7729 | AUPRC=0.7632
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5593 | F1=0.7544 | AUROC=0.8540 | AUPRC=0.8457
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 55.
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6279 | F1=0.7308 | AUROC=0.8955 | AUPRC=0.8069
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6249 | F1=0.8059 | AUROC=0.8910 | AUPRC=0.8768
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4268 | F1=0.7119 | AUROC=0.7757 | AUPRC=0.7656
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5607 | F1=0.7554 | AUROC=0.8504 | AUPRC=0.8430
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 64.
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6332 | F1=0.7346 | AUROC=0.8972 | AUPRC=0.8060
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6419 | F1=0.8152 | AUROC=0.8929 | AUPRC=0.8850
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4405 | F1=0.7218 | AUROC=0.7789 | AUPRC=0.7634
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5609 | F1=0.7572 | AUROC=0.8502 | AUPRC=0.8382
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.4887 | val_loss=0.3865 | val_mcc=0.6109 | val_f1=0.6870 | val_auroc=0.8799

[Epoch 02] train_loss=0.4189 | val_loss=0.3609 | val_mcc=0.6025 | val_f1=0.6819 | val_auroc=0.8919

[Epoch 03] train_loss=0.3821 | val_loss=0.3639 | val_mcc=0.6153 | val_f1=0.6920 | val_auroc=0.9088

[Epoch 04] train_loss=0.3474 | val_loss=0.3439 | val_mcc=0.6065 | val_f1=0.6851 | val_auroc=0.9094

[Epoch 05] train_loss=0.3104 | val_loss=0.3619 | val_mcc=0.5981 | val_f1=0.6782 | val_auroc=0.9087

[Epoch 06] train_loss=0.2713 | val_loss=0.3606 | val_mcc=0.5930 | val_f1=0.6746 | val_auroc=0.9024

[Epoch 07] train_loss=0.2248 | val_loss=0.3742 | val_mcc=0.6005 | val_f1=0.6805 | val_auroc=0.9021

[Epoch 08] train_loss=0.1739 | val_loss=0.4588 | val_mcc=0.5682 | val_f1=0.6536 | val_auroc=0.8975

[Epoch 09] train_loss=0.1484 | val_loss=0.4515 | val_mcc=0.5733 | val_f1=0.6589 | val_auroc=0.8917
[EarlyStop] epoch=9 | best_val_mcc=0.6153
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6750 | F1=0.7666 | AUROC=0.9146 | AUPRC=0.8513
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6615 | F1=0.8298 | AUROC=0.9046 | AUPRC=0.9121
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4526 | F1=0.7286 | AUROC=0.7838 | AUPRC=0.7801
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5966 | F1=0.7820 | AUROC=0.8850 | AUPRC=0.8797
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4825 | val_loss=0.3202 | val_mcc=0.6285 | val_f1=0.6943 | val_auroc=0.8820

[Epoch 02] train_loss=0.4160 | val_loss=0.3146 | val_mcc=0.6270 | val_f1=0.6989 | val_auroc=0.9018

[Epoch 03] train_loss=0.3771 | val_loss=0.3752 | val_mcc=0.5980 | val_f1=0.6778 | val_auroc=0.9074

[Epoch 04] train_loss=0.3363 | val_loss=0.3129 | val_mcc=0.6224 | val_f1=0.6962 | val_auroc=0.9067

[Epoch 05] train_loss=0.2863 | val_loss=0.3594 | val_mcc=0.5973 | val_f1=0.6775 | val_auroc=0.8988

[Epoch 06] train_loss=0.2229 | val_loss=0.4725 | val_mcc=0.5630 | val_f1=0.6499 | val_auroc=0.8942

[Epoch 07] train_loss=0.1887 | val_loss=0.4669 | val_mcc=0.5809 | val_f1=0.6652 | val_auroc=0.8881
[EarlyStop] epoch=7 | best_val_mcc=0.6285
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6760 | F1=0.7536 | AUROC=0.8965 | AUPRC=0.8309
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6256 | F1=0.7913 | AUROC=0.8816 | AUPRC=0.8907
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4566 | F1=0.6959 | AUROC=0.7741 | AUPRC=0.7773
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5911 | F1=0.7561 | AUROC=0.8686 | AUPRC=0.8637
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4770 | val_loss=0.3176 | val_mcc=0.6313 | val_f1=0.6946 | val_auroc=0.8843

[Epoch 02] train_loss=0.4158 | val_loss=0.2918 | val_mcc=0.6418 | val_f1=0.7041 | val_auroc=0.9003

[Epoch 03] train_loss=0.3765 | val_loss=0.3030 | val_mcc=0.6361 | val_f1=0.7070 | val_auroc=0.9100

[Epoch 04] train_loss=0.3388 | val_loss=0.4209 | val_mcc=0.5787 | val_f1=0.6600 | val_auroc=0.9097

[Epoch 05] train_loss=0.2896 | val_loss=0.3501 | val_mcc=0.6116 | val_f1=0.6892 | val_auroc=0.9046

[Epoch 06] train_loss=0.2347 | val_loss=0.3910 | val_mcc=0.6062 | val_f1=0.6847 | val_auroc=0.8984

[Epoch 07] train_loss=0.1705 | val_loss=0.4449 | val_mcc=0.5960 | val_f1=0.6763 | val_auroc=0.8908

[Epoch 08] train_loss=0.1393 | val_loss=0.5153 | val_mcc=0.5860 | val_f1=0.6692 | val_auroc=0.8881
[EarlyStop] epoch=8 | best_val_mcc=0.6418
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6805 | F1=0.7565 | AUROC=0.9087 | AUPRC=0.8450
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6331 | F1=0.7925 | AUROC=0.8999 | AUPRC=0.9060
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4560 | F1=0.6897 | AUROC=0.7789 | AUPRC=0.7793
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6052 | F1=0.7605 | AUROC=0.8810 | AUPRC=0.8753
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4846 | val_loss=0.3214 | val_mcc=0.6409 | val_f1=0.7023 | val_auroc=0.8808

[Epoch 02] train_loss=0.4146 | val_loss=0.3040 | val_mcc=0.6396 | val_f1=0.7052 | val_auroc=0.8985

[Epoch 03] train_loss=0.3792 | val_loss=0.3196 | val_mcc=0.6290 | val_f1=0.7021 | val_auroc=0.9042

[Epoch 04] train_loss=0.3436 | val_loss=0.3131 | val_mcc=0.6257 | val_f1=0.6995 | val_auroc=0.9072

[Epoch 05] train_loss=0.3055 | val_loss=0.3533 | val_mcc=0.5959 | val_f1=0.6767 | val_auroc=0.9071

[Epoch 06] train_loss=0.2568 | val_loss=0.3490 | val_mcc=0.6005 | val_f1=0.6805 | val_auroc=0.9060

[Epoch 07] train_loss=0.2254 | val_loss=0.3747 | val_mcc=0.5907 | val_f1=0.6727 | val_auroc=0.9030
[EarlyStop] epoch=7 | best_val_mcc=0.6409
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6640 | F1=0.7417 | AUROC=0.8938 | AUPRC=0.8282
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5687 | F1=0.7484 | AUROC=0.8762 | AUPRC=0.8849
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4336 | F1=0.6757 | AUROC=0.7713 | AUPRC=0.7711
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5911 | F1=0.7456 | AUROC=0.8642 | AUPRC=0.8646
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 335.
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6660 | F1=0.7577 | AUROC=0.9135 | AUPRC=0.8393
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6337 | F1=0.8095 | AUROC=0.8943 | AUPRC=0.9040
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4316 | F1=0.7087 | AUROC=0.7780 | AUPRC=0.7737
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5981 | F1=0.7782 | AUROC=0.8788 | AUPRC=0.8627
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 210.
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6679 | F1=0.7607 | AUROC=0.9134 | AUPRC=0.8436
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6672 | F1=0.8297 | AUROC=0.9115 | AUPRC=0.9150
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4464 | F1=0.7244 | AUROC=0.7854 | AUPRC=0.7778
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5977 | F1=0.7819 | AUROC=0.8797 | AUPRC=0.8747
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 61.
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6556 | F1=0.7522 | AUROC=0.9067 | AUPRC=0.8390
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6502 | F1=0.8204 | AUROC=0.9034 | AUPRC=0.9114
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4420 | F1=0.7232 | AUROC=0.7803 | AUPRC=0.7797
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.6046 | F1=0.7858 | AUROC=0.8792 | AUPRC=0.8759
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 134.
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6560 | F1=0.7522 | AUROC=0.9075 | AUPRC=0.8395
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6672 | F1=0.8297 | AUROC=0.9048 | AUPRC=0.9061
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4554 | F1=0.7277 | AUROC=0.7786 | AUPRC=0.7790
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.6053 | F1=0.7841 | AUROC=0.8757 | AUPRC=0.8678
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.4655 | val_loss=0.3409 | val_mcc=0.6037 | val_f1=0.6822 | val_auroc=0.8958

[Epoch 02] train_loss=0.3945 | val_loss=0.3492 | val_mcc=0.6132 | val_f1=0.6905 | val_auroc=0.9031

[Epoch 03] train_loss=0.3637 | val_loss=0.3579 | val_mcc=0.5987 | val_f1=0.6790 | val_auroc=0.9010

[Epoch 04] train_loss=0.3351 | val_loss=0.3674 | val_mcc=0.5984 | val_f1=0.6786 | val_auroc=0.9005

[Epoch 05] train_loss=0.3068 | val_loss=0.3660 | val_mcc=0.5897 | val_f1=0.6719 | val_auroc=0.8973

[Epoch 06] train_loss=0.2846 | val_loss=0.3845 | val_mcc=0.5871 | val_f1=0.6693 | val_auroc=0.9001

[Epoch 07] train_loss=0.2446 | val_loss=0.3964 | val_mcc=0.5825 | val_f1=0.6658 | val_auroc=0.8992

[Epoch 08] train_loss=0.2218 | val_loss=0.3947 | val_mcc=0.5852 | val_f1=0.6681 | val_auroc=0.8970
[EarlyStop] epoch=8 | best_val_mcc=0.6132
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6745 | F1=0.7644 | AUROC=0.9131 | AUPRC=0.8379
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6388 | F1=0.8151 | AUROC=0.8890 | AUPRC=0.8931
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4500 | F1=0.7153 | AUROC=0.7835 | AUPRC=0.7800
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6230 | F1=0.7931 | AUROC=0.8816 | AUPRC=0.8747
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4655 | val_loss=0.3563 | val_mcc=0.5960 | val_f1=0.6770 | val_auroc=0.8982

[Epoch 02] train_loss=0.4043 | val_loss=0.3919 | val_mcc=0.5797 | val_f1=0.6630 | val_auroc=0.8979

[Epoch 03] train_loss=0.3739 | val_loss=0.3539 | val_mcc=0.5968 | val_f1=0.6776 | val_auroc=0.8963

[Epoch 04] train_loss=0.3587 | val_loss=0.3554 | val_mcc=0.6192 | val_f1=0.6952 | val_auroc=0.9017

[Epoch 05] train_loss=0.3280 | val_loss=0.3425 | val_mcc=0.6106 | val_f1=0.6882 | val_auroc=0.9021

[Epoch 06] train_loss=0.3057 | val_loss=0.3696 | val_mcc=0.5997 | val_f1=0.6799 | val_auroc=0.8947

[Epoch 07] train_loss=0.2813 | val_loss=0.4209 | val_mcc=0.5870 | val_f1=0.6687 | val_auroc=0.8971

[Epoch 08] train_loss=0.2580 | val_loss=0.3831 | val_mcc=0.6039 | val_f1=0.6832 | val_auroc=0.8978

[Epoch 09] train_loss=0.2134 | val_loss=0.4340 | val_mcc=0.5738 | val_f1=0.6595 | val_auroc=0.8892

[Epoch 10] train_loss=0.2007 | val_loss=0.4314 | val_mcc=0.5808 | val_f1=0.6651 | val_auroc=0.8855
[EarlyStop] epoch=10 | best_val_mcc=0.6192
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6743 | F1=0.7646 | AUROC=0.9155 | AUPRC=0.8425
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6273 | F1=0.8126 | AUROC=0.8919 | AUPRC=0.8971
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4560 | F1=0.7184 | AUROC=0.7778 | AUPRC=0.7625
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6220 | F1=0.7940 | AUROC=0.8822 | AUPRC=0.8730
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4631 | val_loss=0.3903 | val_mcc=0.5838 | val_f1=0.6670 | val_auroc=0.8943

[Epoch 02] train_loss=0.3944 | val_loss=0.3421 | val_mcc=0.6170 | val_f1=0.6931 | val_auroc=0.9006

[Epoch 03] train_loss=0.3636 | val_loss=0.3651 | val_mcc=0.6052 | val_f1=0.6841 | val_auroc=0.9029

[Epoch 04] train_loss=0.3408 | val_loss=0.3683 | val_mcc=0.5984 | val_f1=0.6786 | val_auroc=0.9010

[Epoch 05] train_loss=0.3138 | val_loss=0.3474 | val_mcc=0.6155 | val_f1=0.6921 | val_auroc=0.8995

[Epoch 06] train_loss=0.2810 | val_loss=0.4085 | val_mcc=0.5724 | val_f1=0.6578 | val_auroc=0.8929

[Epoch 07] train_loss=0.2406 | val_loss=0.3977 | val_mcc=0.5906 | val_f1=0.6726 | val_auroc=0.8980

[Epoch 08] train_loss=0.2165 | val_loss=0.4527 | val_mcc=0.5725 | val_f1=0.6571 | val_auroc=0.8946
[EarlyStop] epoch=8 | best_val_mcc=0.6170
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6764 | F1=0.7636 | AUROC=0.9110 | AUPRC=0.8357
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6218 | F1=0.8058 | AUROC=0.8827 | AUPRC=0.8921
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4449 | F1=0.7076 | AUROC=0.7805 | AUPRC=0.7779
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6227 | F1=0.7909 | AUROC=0.8829 | AUPRC=0.8740
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4667 | val_loss=0.3647 | val_mcc=0.5903 | val_f1=0.6725 | val_auroc=0.8943

[Epoch 02] train_loss=0.3932 | val_loss=0.3566 | val_mcc=0.5971 | val_f1=0.6778 | val_auroc=0.8987

[Epoch 03] train_loss=0.3593 | val_loss=0.3531 | val_mcc=0.6066 | val_f1=0.6853 | val_auroc=0.9008

[Epoch 04] train_loss=0.3277 | val_loss=0.3417 | val_mcc=0.6080 | val_f1=0.6864 | val_auroc=0.9014

[Epoch 05] train_loss=0.2968 | val_loss=0.3773 | val_mcc=0.5930 | val_f1=0.6743 | val_auroc=0.8992

[Epoch 06] train_loss=0.2620 | val_loss=0.4004 | val_mcc=0.5803 | val_f1=0.6643 | val_auroc=0.8946

[Epoch 07] train_loss=0.2312 | val_loss=0.4056 | val_mcc=0.5814 | val_f1=0.6654 | val_auroc=0.8916

[Epoch 08] train_loss=0.1946 | val_loss=0.4382 | val_mcc=0.5691 | val_f1=0.6557 | val_auroc=0.8913

[Epoch 09] train_loss=0.1550 | val_loss=0.4786 | val_mcc=0.5662 | val_f1=0.6525 | val_auroc=0.8909

[Epoch 10] train_loss=0.1343 | val_loss=0.4848 | val_mcc=0.5690 | val_f1=0.6553 | val_auroc=0.8901
[EarlyStop] epoch=10 | best_val_mcc=0.6080
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6642 | F1=0.7559 | AUROC=0.9104 | AUPRC=0.8339
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6018 | F1=0.7959 | AUROC=0.8810 | AUPRC=0.8922
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4265 | F1=0.6996 | AUROC=0.7770 | AUPRC=0.7746
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6123 | F1=0.7886 | AUROC=0.8792 | AUPRC=0.8699
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 302.
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6644 | F1=0.7583 | AUROC=0.9113 | AUPRC=0.8366
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6189 | F1=0.8091 | AUROC=0.8883 | AUPRC=0.8924
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4410 | F1=0.7106 | AUROC=0.7783 | AUPRC=0.7801
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5955 | F1=0.7820 | AUROC=0.8750 | AUPRC=0.8599
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 127.
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6636 | F1=0.7578 | AUROC=0.9122 | AUPRC=0.8332
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6221 | F1=0.8124 | AUROC=0.8817 | AUPRC=0.8828
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4148 | F1=0.7045 | AUROC=0.7751 | AUPRC=0.7777
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.6191 | F1=0.7953 | AUROC=0.8788 | AUPRC=0.8633
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 40.
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6742 | F1=0.7647 | AUROC=0.9115 | AUPRC=0.8296
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6216 | F1=0.8097 | AUROC=0.8891 | AUPRC=0.8919
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4389 | F1=0.7149 | AUROC=0.7804 | AUPRC=0.7683
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.6064 | F1=0.7876 | AUROC=0.8825 | AUPRC=0.8741
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 75.
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6688 | F1=0.7611 | AUROC=0.9117 | AUPRC=0.8355
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6131 | F1=0.8023 | AUROC=0.8921 | AUPRC=0.9025
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4178 | F1=0.7065 | AUROC=0.7818 | AUPRC=0.7741
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.6199 | F1=0.7947 | AUROC=0.8774 | AUPRC=0.8692
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.4692 | val_loss=0.3888 | val_mcc=0.5600 | val_f1=0.6489 | val_auroc=0.8847

[Epoch 02] train_loss=0.3987 | val_loss=0.3448 | val_mcc=0.5875 | val_f1=0.6695 | val_auroc=0.8941

[Epoch 03] train_loss=0.3645 | val_loss=0.3692 | val_mcc=0.5839 | val_f1=0.6675 | val_auroc=0.8948

[Epoch 04] train_loss=0.3373 | val_loss=0.3851 | val_mcc=0.5634 | val_f1=0.6506 | val_auroc=0.8942

[Epoch 05] train_loss=0.3089 | val_loss=0.3890 | val_mcc=0.5702 | val_f1=0.6562 | val_auroc=0.8943

[Epoch 06] train_loss=0.2815 | val_loss=0.4167 | val_mcc=0.5578 | val_f1=0.6460 | val_auroc=0.8904

[Epoch 07] train_loss=0.2394 | val_loss=0.4011 | val_mcc=0.5698 | val_f1=0.6562 | val_auroc=0.8912

[Epoch 08] train_loss=0.2147 | val_loss=0.4277 | val_mcc=0.5627 | val_f1=0.6501 | val_auroc=0.8896
[EarlyStop] epoch=8 | best_val_mcc=0.5875
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6297 | F1=0.7265 | AUROC=0.8925 | AUPRC=0.8042
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6018 | F1=0.7860 | AUROC=0.8795 | AUPRC=0.8759
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4163 | F1=0.6924 | AUROC=0.7699 | AUPRC=0.7632
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5668 | F1=0.7492 | AUROC=0.8497 | AUPRC=0.8395
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4774 | val_loss=0.4228 | val_mcc=0.5395 | val_f1=0.6325 | val_auroc=0.8792

[Epoch 02] train_loss=0.4099 | val_loss=0.3812 | val_mcc=0.5736 | val_f1=0.6594 | val_auroc=0.8895

[Epoch 03] train_loss=0.3806 | val_loss=0.3757 | val_mcc=0.5805 | val_f1=0.6647 | val_auroc=0.8951

[Epoch 04] train_loss=0.3531 | val_loss=0.3930 | val_mcc=0.5691 | val_f1=0.6555 | val_auroc=0.8908

[Epoch 05] train_loss=0.3248 | val_loss=0.4159 | val_mcc=0.5658 | val_f1=0.6526 | val_auroc=0.8911

[Epoch 06] train_loss=0.3007 | val_loss=0.4261 | val_mcc=0.5590 | val_f1=0.6468 | val_auroc=0.8905

[Epoch 07] train_loss=0.2734 | val_loss=0.4089 | val_mcc=0.5610 | val_f1=0.6496 | val_auroc=0.8824

[Epoch 08] train_loss=0.2337 | val_loss=0.4685 | val_mcc=0.5596 | val_f1=0.6472 | val_auroc=0.8866

[Epoch 09] train_loss=0.2104 | val_loss=0.4760 | val_mcc=0.5555 | val_f1=0.6447 | val_auroc=0.8838
[EarlyStop] epoch=9 | best_val_mcc=0.5805
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6296 | F1=0.7330 | AUROC=0.8948 | AUPRC=0.8069
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6559 | F1=0.8239 | AUROC=0.8918 | AUPRC=0.8876
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4452 | F1=0.7263 | AUROC=0.7771 | AUPRC=0.7574
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5773 | F1=0.7656 | AUROC=0.8564 | AUPRC=0.8378
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4697 | val_loss=0.3918 | val_mcc=0.5654 | val_f1=0.6531 | val_auroc=0.8788

[Epoch 02] train_loss=0.4026 | val_loss=0.3643 | val_mcc=0.5884 | val_f1=0.6708 | val_auroc=0.8911

[Epoch 03] train_loss=0.3722 | val_loss=0.3900 | val_mcc=0.5762 | val_f1=0.6611 | val_auroc=0.8921

[Epoch 04] train_loss=0.3418 | val_loss=0.3863 | val_mcc=0.5702 | val_f1=0.6566 | val_auroc=0.8895

[Epoch 05] train_loss=0.3132 | val_loss=0.4091 | val_mcc=0.5611 | val_f1=0.6494 | val_auroc=0.8860

[Epoch 06] train_loss=0.2863 | val_loss=0.3755 | val_mcc=0.5701 | val_f1=0.6558 | val_auroc=0.8798

[Epoch 07] train_loss=0.2376 | val_loss=0.4166 | val_mcc=0.5662 | val_f1=0.6537 | val_auroc=0.8879

[Epoch 08] train_loss=0.2139 | val_loss=0.4730 | val_mcc=0.5516 | val_f1=0.6414 | val_auroc=0.8854
[EarlyStop] epoch=8 | best_val_mcc=0.5884
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6267 | F1=0.7274 | AUROC=0.8942 | AUPRC=0.8084
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6371 | F1=0.8095 | AUROC=0.8840 | AUPRC=0.8818
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4410 | F1=0.7106 | AUROC=0.7715 | AUPRC=0.7634
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5483 | F1=0.7479 | AUROC=0.8482 | AUPRC=0.8318
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4770 | val_loss=0.3863 | val_mcc=0.5617 | val_f1=0.6499 | val_auroc=0.8813

[Epoch 02] train_loss=0.4029 | val_loss=0.3742 | val_mcc=0.5725 | val_f1=0.6586 | val_auroc=0.8895

[Epoch 03] train_loss=0.3636 | val_loss=0.3515 | val_mcc=0.5885 | val_f1=0.6707 | val_auroc=0.8922

[Epoch 04] train_loss=0.3299 | val_loss=0.3810 | val_mcc=0.5665 | val_f1=0.6539 | val_auroc=0.8891

[Epoch 05] train_loss=0.2956 | val_loss=0.3759 | val_mcc=0.5687 | val_f1=0.6557 | val_auroc=0.8908

[Epoch 06] train_loss=0.2626 | val_loss=0.4310 | val_mcc=0.5438 | val_f1=0.6354 | val_auroc=0.8848

[Epoch 07] train_loss=0.2286 | val_loss=0.4288 | val_mcc=0.5424 | val_f1=0.6351 | val_auroc=0.8827

[Epoch 08] train_loss=0.1790 | val_loss=0.4646 | val_mcc=0.5477 | val_f1=0.6385 | val_auroc=0.8866

[Epoch 09] train_loss=0.1570 | val_loss=0.4814 | val_mcc=0.5427 | val_f1=0.6350 | val_auroc=0.8835
[EarlyStop] epoch=9 | best_val_mcc=0.5885
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6319 | F1=0.7305 | AUROC=0.8966 | AUPRC=0.8079
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6177 | F1=0.7976 | AUROC=0.8911 | AUPRC=0.8808
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4450 | F1=0.7171 | AUROC=0.7781 | AUPRC=0.7674
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5427 | F1=0.7436 | AUROC=0.8492 | AUPRC=0.8381
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 280.
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6066 | F1=0.7160 | AUROC=0.8866 | AUPRC=0.7902
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6020 | F1=0.7947 | AUROC=0.8826 | AUPRC=0.8760
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4315 | F1=0.7096 | AUROC=0.7675 | AUPRC=0.7593
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5407 | F1=0.7479 | AUROC=0.8479 | AUPRC=0.8264
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 163.
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6174 | F1=0.7240 | AUROC=0.8926 | AUPRC=0.8004
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6333 | F1=0.8111 | AUROC=0.8819 | AUPRC=0.8677
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4284 | F1=0.7155 | AUROC=0.7744 | AUPRC=0.7705
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5573 | F1=0.7577 | AUROC=0.8417 | AUPRC=0.8331
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 48.
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6245 | F1=0.7284 | AUROC=0.8964 | AUPRC=0.8051
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6278 | F1=0.8071 | AUROC=0.8955 | AUPRC=0.8882
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4299 | F1=0.7104 | AUROC=0.7753 | AUPRC=0.7684
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5651 | F1=0.7600 | AUROC=0.8495 | AUPRC=0.8367
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 62.
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6203 | F1=0.7244 | AUROC=0.8898 | AUPRC=0.7984
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6400 | F1=0.8107 | AUROC=0.8924 | AUPRC=0.8763
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4255 | F1=0.7144 | AUROC=0.7766 | AUPRC=0.7604
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5511 | F1=0.7502 | AUROC=0.8461 | AUPRC=0.8356
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.4826 | val_loss=0.3390 | val_mcc=0.6236 | val_f1=0.6930 | val_auroc=0.8782

[Epoch 02] train_loss=0.4065 | val_loss=0.3394 | val_mcc=0.6143 | val_f1=0.6900 | val_auroc=0.8949

[Epoch 03] train_loss=0.3638 | val_loss=0.3378 | val_mcc=0.6142 | val_f1=0.6912 | val_auroc=0.9024

[Epoch 04] train_loss=0.3231 | val_loss=0.3352 | val_mcc=0.6084 | val_f1=0.6866 | val_auroc=0.9027

[Epoch 05] train_loss=0.2757 | val_loss=0.3754 | val_mcc=0.5881 | val_f1=0.6703 | val_auroc=0.9012

[Epoch 06] train_loss=0.2212 | val_loss=0.3780 | val_mcc=0.5910 | val_f1=0.6728 | val_auroc=0.9014

[Epoch 07] train_loss=0.1904 | val_loss=0.3964 | val_mcc=0.5877 | val_f1=0.6701 | val_auroc=0.9000
[EarlyStop] epoch=7 | best_val_mcc=0.6236
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6570 | F1=0.7423 | AUROC=0.8925 | AUPRC=0.8270
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6081 | F1=0.7724 | AUROC=0.8829 | AUPRC=0.8952
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4449 | F1=0.6883 | AUROC=0.7672 | AUPRC=0.7712
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5841 | F1=0.7518 | AUROC=0.8617 | AUPRC=0.8618
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4821 | val_loss=0.3823 | val_mcc=0.6051 | val_f1=0.6833 | val_auroc=0.8823

[Epoch 02] train_loss=0.4102 | val_loss=0.3566 | val_mcc=0.6103 | val_f1=0.6879 | val_auroc=0.8976

[Epoch 03] train_loss=0.3702 | val_loss=0.4148 | val_mcc=0.5658 | val_f1=0.6506 | val_auroc=0.9061

[Epoch 04] train_loss=0.3249 | val_loss=0.3675 | val_mcc=0.5978 | val_f1=0.6783 | val_auroc=0.9041

[Epoch 05] train_loss=0.2686 | val_loss=0.3773 | val_mcc=0.6019 | val_f1=0.6811 | val_auroc=0.8937

[Epoch 06] train_loss=0.2191 | val_loss=0.4645 | val_mcc=0.5725 | val_f1=0.6583 | val_auroc=0.8928

[Epoch 07] train_loss=0.1478 | val_loss=0.5756 | val_mcc=0.5612 | val_f1=0.6487 | val_auroc=0.8889

[Epoch 08] train_loss=0.1226 | val_loss=0.6419 | val_mcc=0.5473 | val_f1=0.6376 | val_auroc=0.8808
[EarlyStop] epoch=8 | best_val_mcc=0.6103
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6714 | F1=0.7620 | AUROC=0.9087 | AUPRC=0.8439
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6591 | F1=0.8235 | AUROC=0.9043 | AUPRC=0.9061
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4466 | F1=0.7164 | AUROC=0.7784 | AUPRC=0.7742
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6084 | F1=0.7869 | AUROC=0.8776 | AUPRC=0.8691
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4695 | val_loss=0.3641 | val_mcc=0.6073 | val_f1=0.6850 | val_auroc=0.8898

[Epoch 02] train_loss=0.4078 | val_loss=0.3217 | val_mcc=0.6294 | val_f1=0.7017 | val_auroc=0.9004

[Epoch 03] train_loss=0.3651 | val_loss=0.3194 | val_mcc=0.6212 | val_f1=0.6960 | val_auroc=0.9049

[Epoch 04] train_loss=0.3246 | val_loss=0.3390 | val_mcc=0.6058 | val_f1=0.6847 | val_auroc=0.9072

[Epoch 05] train_loss=0.2722 | val_loss=0.3869 | val_mcc=0.5884 | val_f1=0.6704 | val_auroc=0.9039

[Epoch 06] train_loss=0.2212 | val_loss=0.3952 | val_mcc=0.6036 | val_f1=0.6829 | val_auroc=0.8982

[Epoch 07] train_loss=0.1549 | val_loss=0.4635 | val_mcc=0.5808 | val_f1=0.6651 | val_auroc=0.8958

[Epoch 08] train_loss=0.1211 | val_loss=0.6003 | val_mcc=0.5504 | val_f1=0.6395 | val_auroc=0.8949
[EarlyStop] epoch=8 | best_val_mcc=0.6294
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6815 | F1=0.7656 | AUROC=0.9045 | AUPRC=0.8420
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6496 | F1=0.8133 | AUROC=0.8920 | AUPRC=0.9033
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4534 | F1=0.7081 | AUROC=0.7700 | AUPRC=0.7727
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6049 | F1=0.7764 | AUROC=0.8720 | AUPRC=0.8712
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4823 | val_loss=0.3475 | val_mcc=0.6192 | val_f1=0.6913 | val_auroc=0.8835

[Epoch 02] train_loss=0.4030 | val_loss=0.3282 | val_mcc=0.6196 | val_f1=0.6941 | val_auroc=0.8972

[Epoch 03] train_loss=0.3591 | val_loss=0.3385 | val_mcc=0.6097 | val_f1=0.6878 | val_auroc=0.9019

[Epoch 04] train_loss=0.3144 | val_loss=0.3286 | val_mcc=0.6118 | val_f1=0.6890 | val_auroc=0.9013

[Epoch 05] train_loss=0.2667 | val_loss=0.3503 | val_mcc=0.5996 | val_f1=0.6798 | val_auroc=0.9012

[Epoch 06] train_loss=0.2143 | val_loss=0.4291 | val_mcc=0.5622 | val_f1=0.6496 | val_auroc=0.8948

[Epoch 07] train_loss=0.1556 | val_loss=0.4176 | val_mcc=0.5813 | val_f1=0.6653 | val_auroc=0.8962

[Epoch 08] train_loss=0.1253 | val_loss=0.4656 | val_mcc=0.5711 | val_f1=0.6571 | val_auroc=0.8936
[EarlyStop] epoch=8 | best_val_mcc=0.6196
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6758 | F1=0.7629 | AUROC=0.9064 | AUPRC=0.8437
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6460 | F1=0.8132 | AUROC=0.8990 | AUPRC=0.9085
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4370 | F1=0.7053 | AUROC=0.7742 | AUPRC=0.7712
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6061 | F1=0.7797 | AUROC=0.8727 | AUPRC=0.8697
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 237.
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6590 | F1=0.7531 | AUROC=0.9099 | AUPRC=0.8356
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6422 | F1=0.8142 | AUROC=0.8979 | AUPRC=0.9046
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4314 | F1=0.7118 | AUROC=0.7695 | AUPRC=0.7624
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6120 | F1=0.7871 | AUROC=0.8769 | AUPRC=0.8664
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 169.
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6627 | F1=0.7566 | AUROC=0.9091 | AUPRC=0.8404
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6615 | F1=0.8268 | AUROC=0.8991 | AUPRC=0.9005
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4584 | F1=0.7259 | AUROC=0.7839 | AUPRC=0.7810
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.6080 | F1=0.7853 | AUROC=0.8795 | AUPRC=0.8685
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 55.
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6490 | F1=0.7481 | AUROC=0.9082 | AUPRC=0.8401
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6501 | F1=0.8240 | AUROC=0.9097 | AUPRC=0.9174
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4330 | F1=0.7179 | AUROC=0.7795 | AUPRC=0.7786
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5980 | F1=0.7829 | AUROC=0.8829 | AUPRC=0.8755
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 82.
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6481 | F1=0.7472 | AUROC=0.9068 | AUPRC=0.8370
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6335 | F1=0.8100 | AUROC=0.8964 | AUPRC=0.9064
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4316 | F1=0.7186 | AUROC=0.7714 | AUPRC=0.7634
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.6011 | F1=0.7853 | AUROC=0.8766 | AUPRC=0.8643
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.7069 | val_loss=0.6705 | val_mcc=0.0764 | val_f1=0.3100 | val_auroc=0.5681

[Epoch 02] train_loss=0.6657 | val_loss=0.6718 | val_mcc=0.0844 | val_f1=0.3168 | val_auroc=0.5771

[Epoch 03] train_loss=0.6359 | val_loss=0.6806 | val_mcc=0.0998 | val_f1=0.3279 | val_auroc=0.5877

[Epoch 04] train_loss=0.6001 | val_loss=0.6812 | val_mcc=0.0982 | val_f1=0.3242 | val_auroc=0.5876

[Epoch 05] train_loss=0.5520 | val_loss=0.7268 | val_mcc=0.1129 | val_f1=0.3364 | val_auroc=0.5921

[Epoch 06] train_loss=0.4998 | val_loss=0.7372 | val_mcc=0.1027 | val_f1=0.3275 | val_auroc=0.5907

[Epoch 07] train_loss=0.4407 | val_loss=0.7912 | val_mcc=0.0999 | val_f1=0.3263 | val_auroc=0.5900

[Epoch 08] train_loss=0.3786 | val_loss=0.8781 | val_mcc=0.0991 | val_f1=0.3279 | val_auroc=0.5843

[Epoch 09] train_loss=0.3186 | val_loss=0.9403 | val_mcc=0.0964 | val_f1=0.3263 | val_auroc=0.5849

[Epoch 10] train_loss=0.2519 | val_loss=0.9713 | val_mcc=0.1009 | val_f1=0.3287 | val_auroc=0.5891

[Epoch 11] train_loss=0.2150 | val_loss=1.0442 | val_mcc=0.1092 | val_f1=0.3344 | val_auroc=0.5939
[EarlyStop] epoch=11 | best_val_mcc=0.1129
[Test] train3__val_center_dna_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.0850 | F1=0.3949 | AUROC=0.5703 | AUPRC=0.3222
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.1527 | F1=0.5815 | AUROC=0.6196 | AUPRC=0.6013
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.0728 | F1=0.5381 | AUROC=0.5343 | AUPRC=0.5197
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.0631 | F1=0.5262 | AUROC=0.5555 | AUPRC=0.5020
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 41.
[Test] train3__val_center_dna_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.0680 | F1=0.3885 | AUROC=0.5577 | AUPRC=0.3090
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.0725 | F1=0.5316 | AUROC=0.5488 | AUPRC=0.5328
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.0475 | F1=0.5348 | AUROC=0.5313 | AUPRC=0.5121
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.0455 | F1=0.5118 | AUROC=0.5351 | AUPRC=0.4739
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 49.
[Test] train3__val_center_dna_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.0447 | F1=0.3746 | AUROC=0.5396 | AUPRC=0.2996
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.0754 | F1=0.5364 | AUROC=0.5417 | AUPRC=0.5229
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.0173 | F1=0.5108 | AUROC=0.5239 | AUPRC=0.5235
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.0240 | F1=0.4951 | AUROC=0.5147 | AUPRC=0.4649
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_None_esmc_600m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4763 | val_loss=0.3107 | val_mcc=0.6342 | val_f1=0.6940 | val_auroc=0.8866

[Epoch 02] train_loss=0.4136 | val_loss=0.3122 | val_mcc=0.6340 | val_f1=0.7026 | val_auroc=0.9016

[Epoch 03] train_loss=0.3809 | val_loss=0.3019 | val_mcc=0.6306 | val_f1=0.7016 | val_auroc=0.9077

[Epoch 04] train_loss=0.3510 | val_loss=0.3097 | val_mcc=0.6304 | val_f1=0.7034 | val_auroc=0.9107

[Epoch 05] train_loss=0.3208 | val_loss=0.3356 | val_mcc=0.6156 | val_f1=0.6923 | val_auroc=0.9093

[Epoch 06] train_loss=0.2806 | val_loss=0.3271 | val_mcc=0.6129 | val_f1=0.6901 | val_auroc=0.9079

[Epoch 07] train_loss=0.2549 | val_loss=0.3453 | val_mcc=0.6037 | val_f1=0.6831 | val_auroc=0.9067
[EarlyStop] epoch=7 | best_val_mcc=0.6342
[Test] train3__val_center_prot_None_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6637 | F1=0.7378 | AUROC=0.9016 | AUPRC=0.8328
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_None_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_prot_None_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6078 | F1=0.7682 | AUROC=0.8894 | AUPRC=0.8933
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_None_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_prot_None_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4430 | F1=0.6735 | AUROC=0.7795 | AUPRC=0.7769
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_None_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_prot_None_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5983 | F1=0.7527 | AUROC=0.8775 | AUPRC=0.8728
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 270.
[Test] train3__val_center_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6655 | F1=0.7582 | AUROC=0.9127 | AUPRC=0.8386
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6614 | F1=0.8278 | AUROC=0.9017 | AUPRC=0.9019
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4420 | F1=0.7152 | AUROC=0.7761 | AUPRC=0.7653
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_prot_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6022 | F1=0.7806 | AUROC=0.8794 | AUPRC=0.8688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 161.
[Test] train3__val_center_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6643 | F1=0.7577 | AUROC=0.9128 | AUPRC=0.8410
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6586 | F1=0.8261 | AUROC=0.9055 | AUPRC=0.9042
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4434 | F1=0.7187 | AUROC=0.7824 | AUPRC=0.7775
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_prot_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5926 | F1=0.7752 | AUROC=0.8766 | AUPRC=0.8686
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4668 | val_loss=0.3480 | val_mcc=0.6261 | val_f1=0.6928 | val_auroc=0.8810

[Epoch 02] train_loss=0.3942 | val_loss=0.3462 | val_mcc=0.6077 | val_f1=0.6847 | val_auroc=0.8919

[Epoch 03] train_loss=0.3385 | val_loss=0.3302 | val_mcc=0.6029 | val_f1=0.6816 | val_auroc=0.8957

[Epoch 04] train_loss=0.2808 | val_loss=0.3599 | val_mcc=0.5771 | val_f1=0.6622 | val_auroc=0.8956

[Epoch 05] train_loss=0.2170 | val_loss=0.4055 | val_mcc=0.5622 | val_f1=0.6499 | val_auroc=0.8926

[Epoch 06] train_loss=0.1478 | val_loss=0.4127 | val_mcc=0.5540 | val_f1=0.6441 | val_auroc=0.8875

[Epoch 07] train_loss=0.1136 | val_loss=0.4711 | val_mcc=0.5371 | val_f1=0.6298 | val_auroc=0.8875
[EarlyStop] epoch=7 | best_val_mcc=0.6261
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6723 | F1=0.7505 | AUROC=0.8906 | AUPRC=0.8278
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6138 | F1=0.7804 | AUROC=0.8823 | AUPRC=0.8960
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4446 | F1=0.6813 | AUROC=0.7670 | AUPRC=0.7728
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6098 | F1=0.7657 | AUROC=0.8641 | AUPRC=0.8637
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4706 | val_loss=0.3356 | val_mcc=0.6334 | val_f1=0.6933 | val_auroc=0.8812

[Epoch 02] train_loss=0.4015 | val_loss=0.3702 | val_mcc=0.5995 | val_f1=0.6797 | val_auroc=0.8966

[Epoch 03] train_loss=0.3487 | val_loss=0.3318 | val_mcc=0.6119 | val_f1=0.6888 | val_auroc=0.8995

[Epoch 04] train_loss=0.2918 | val_loss=0.4228 | val_mcc=0.5586 | val_f1=0.6464 | val_auroc=0.8912

[Epoch 05] train_loss=0.2235 | val_loss=0.4896 | val_mcc=0.5466 | val_f1=0.6365 | val_auroc=0.8885

[Epoch 06] train_loss=0.1416 | val_loss=0.6606 | val_mcc=0.5245 | val_f1=0.6166 | val_auroc=0.8828

[Epoch 07] train_loss=0.1064 | val_loss=0.6516 | val_mcc=0.5379 | val_f1=0.6300 | val_auroc=0.8810
[EarlyStop] epoch=7 | best_val_mcc=0.6334
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6675 | F1=0.7414 | AUROC=0.8971 | AUPRC=0.8319
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6037 | F1=0.7677 | AUROC=0.8884 | AUPRC=0.8920
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4468 | F1=0.6775 | AUROC=0.7758 | AUPRC=0.7731
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6045 | F1=0.7552 | AUROC=0.8749 | AUPRC=0.8716
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4684 | val_loss=0.3123 | val_mcc=0.6347 | val_f1=0.6923 | val_auroc=0.8836

[Epoch 02] train_loss=0.3966 | val_loss=0.2898 | val_mcc=0.6195 | val_f1=0.6811 | val_auroc=0.8962

[Epoch 03] train_loss=0.3467 | val_loss=0.2970 | val_mcc=0.6198 | val_f1=0.6895 | val_auroc=0.8994

[Epoch 04] train_loss=0.2844 | val_loss=0.3836 | val_mcc=0.5870 | val_f1=0.6695 | val_auroc=0.8985

[Epoch 05] train_loss=0.2140 | val_loss=0.4023 | val_mcc=0.5848 | val_f1=0.6683 | val_auroc=0.8960

[Epoch 06] train_loss=0.1313 | val_loss=0.4828 | val_mcc=0.5700 | val_f1=0.6567 | val_auroc=0.8891

[Epoch 07] train_loss=0.0943 | val_loss=0.5505 | val_mcc=0.5528 | val_f1=0.6432 | val_auroc=0.8837
[EarlyStop] epoch=7 | best_val_mcc=0.6347
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6609 | F1=0.7332 | AUROC=0.8965 | AUPRC=0.8310
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6156 | F1=0.7657 | AUROC=0.8872 | AUPRC=0.8977
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4431 | F1=0.6667 | AUROC=0.7779 | AUPRC=0.7774
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5944 | F1=0.7436 | AUROC=0.8731 | AUPRC=0.8712
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4721 | val_loss=0.3202 | val_mcc=0.6256 | val_f1=0.6780 | val_auroc=0.8763

[Epoch 02] train_loss=0.3982 | val_loss=0.3014 | val_mcc=0.6259 | val_f1=0.6834 | val_auroc=0.8888

[Epoch 03] train_loss=0.3392 | val_loss=0.3011 | val_mcc=0.6170 | val_f1=0.6845 | val_auroc=0.8936

[Epoch 04] train_loss=0.2731 | val_loss=0.3148 | val_mcc=0.5949 | val_f1=0.6692 | val_auroc=0.8911

[Epoch 05] train_loss=0.1964 | val_loss=0.3491 | val_mcc=0.5842 | val_f1=0.6645 | val_auroc=0.8882

[Epoch 06] train_loss=0.1257 | val_loss=0.4212 | val_mcc=0.5664 | val_f1=0.6537 | val_auroc=0.8884

[Epoch 07] train_loss=0.0714 | val_loss=0.4383 | val_mcc=0.5633 | val_f1=0.6502 | val_auroc=0.8835

[Epoch 08] train_loss=0.0519 | val_loss=0.4935 | val_mcc=0.5560 | val_f1=0.6457 | val_auroc=0.8828
[EarlyStop] epoch=8 | best_val_mcc=0.6259
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6581 | F1=0.7306 | AUROC=0.9000 | AUPRC=0.8299
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6162 | F1=0.7735 | AUROC=0.8956 | AUPRC=0.9029
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4091 | F1=0.6505 | AUROC=0.7729 | AUPRC=0.7732
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5950 | F1=0.7428 | AUROC=0.8753 | AUPRC=0.8700
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 245.
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6999 | F1=0.7812 | AUROC=0.9191 | AUPRC=0.8521
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6453 | F1=0.8148 | AUROC=0.9002 | AUPRC=0.9016
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4472 | F1=0.7128 | AUROC=0.7847 | AUPRC=0.7809
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6227 | F1=0.7902 | AUROC=0.8805 | AUPRC=0.8728
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 69.
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6437 | F1=0.7315 | AUROC=0.8979 | AUPRC=0.8176
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6223 | F1=0.7808 | AUROC=0.8903 | AUPRC=0.8937
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4121 | F1=0.6770 | AUROC=0.7710 | AUPRC=0.7717
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5661 | F1=0.7458 | AUROC=0.8595 | AUPRC=0.8525
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 41.
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6555 | F1=0.7519 | AUROC=0.9025 | AUPRC=0.8367
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6416 | F1=0.8200 | AUROC=0.9010 | AUPRC=0.9090
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4284 | F1=0.7137 | AUROC=0.7717 | AUPRC=0.7700
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.6030 | F1=0.7842 | AUROC=0.8727 | AUPRC=0.8691
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 46.
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6440 | F1=0.7429 | AUROC=0.9008 | AUPRC=0.8291
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6619 | F1=0.8253 | AUROC=0.9030 | AUPRC=0.9110
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4257 | F1=0.7052 | AUROC=0.7721 | AUPRC=0.7680
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.3532 | val_loss=0.1916 | val_mcc=0.7721 | val_f1=0.8162 | val_auroc=0.9657

[Epoch 02] train_loss=0.2448 | val_loss=0.2041 | val_mcc=0.7631 | val_f1=0.8090 | val_auroc=0.9667

[Epoch 03] train_loss=0.2050 | val_loss=0.1856 | val_mcc=0.7788 | val_f1=0.8213 | val_auroc=0.9653

[Epoch 04] train_loss=0.1639 | val_loss=0.2313 | val_mcc=0.7471 | val_f1=0.7952 | val_auroc=0.9641

[Epoch 05] train_loss=0.1185 | val_loss=0.2231 | val_mcc=0.7613 | val_f1=0.8078 | val_auroc=0.9633

[Epoch 06] train_loss=0.0811 | val_loss=0.2668 | val_mcc=0.7409 | val_f1=0.7904 | val_auroc=0.9614

[Epoch 07] train_loss=0.0516 | val_loss=0.2680 | val_mcc=0.7545 | val_f1=0.8024 | val_auroc=0.9598

[Epoch 08] train_loss=0.0322 | val_loss=0.2881 | val_mcc=0.7522 | val_f1=0.8003 | val_auroc=0.9605

[Epoch 09] train_loss=0.0237 | val_loss=0.3067 | val_mcc=0.7467 | val_f1=0.7956 | val_auroc=0.9600
[EarlyStop] epoch=9 | best_val_mcc=0.7788
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7876 | F1=0.8454 | AUROC=0.9611 | AUPRC=0.9185
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8044 | F1=0.8943 | AUROC=0.9747 | AUPRC=0.9745
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4455 | F1=0.7279 | AUROC=0.7895 | AUPRC=0.7840
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5902 | F1=0.7905 | AUROC=0.8955 | AUPRC=0.8763
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3503 | val_loss=0.2098 | val_mcc=0.7563 | val_f1=0.8034 | val_auroc=0.9665

[Epoch 02] train_loss=0.2539 | val_loss=0.1750 | val_mcc=0.7843 | val_f1=0.8254 | val_auroc=0.9666

[Epoch 03] train_loss=0.2176 | val_loss=0.2085 | val_mcc=0.7557 | val_f1=0.8030 | val_auroc=0.9644

[Epoch 04] train_loss=0.1772 | val_loss=0.2770 | val_mcc=0.7114 | val_f1=0.7629 | val_auroc=0.9639

[Epoch 05] train_loss=0.1288 | val_loss=0.2739 | val_mcc=0.7264 | val_f1=0.7787 | val_auroc=0.9573

[Epoch 06] train_loss=0.0839 | val_loss=0.2998 | val_mcc=0.7332 | val_f1=0.7853 | val_auroc=0.9522

[Epoch 07] train_loss=0.0496 | val_loss=0.3326 | val_mcc=0.7337 | val_f1=0.7855 | val_auroc=0.9514

[Epoch 08] train_loss=0.0348 | val_loss=0.3889 | val_mcc=0.7205 | val_f1=0.7738 | val_auroc=0.9506
[EarlyStop] epoch=8 | best_val_mcc=0.7843
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7890 | F1=0.8456 | AUROC=0.9635 | AUPRC=0.9229
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8064 | F1=0.8930 | AUROC=0.9755 | AUPRC=0.9751
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4585 | F1=0.7312 | AUROC=0.7897 | AUPRC=0.7811
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6007 | F1=0.7955 | AUROC=0.8966 | AUPRC=0.8819
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3590 | val_loss=0.2049 | val_mcc=0.7651 | val_f1=0.8108 | val_auroc=0.9674

[Epoch 02] train_loss=0.2564 | val_loss=0.2044 | val_mcc=0.7652 | val_f1=0.8106 | val_auroc=0.9671

[Epoch 03] train_loss=0.2165 | val_loss=0.2150 | val_mcc=0.7541 | val_f1=0.8011 | val_auroc=0.9660

[Epoch 04] train_loss=0.1743 | val_loss=0.2178 | val_mcc=0.7559 | val_f1=0.8033 | val_auroc=0.9629

[Epoch 05] train_loss=0.1254 | val_loss=0.2388 | val_mcc=0.7520 | val_f1=0.8004 | val_auroc=0.9580

[Epoch 06] train_loss=0.0821 | val_loss=0.3092 | val_mcc=0.7246 | val_f1=0.7780 | val_auroc=0.9543

[Epoch 07] train_loss=0.0469 | val_loss=0.3028 | val_mcc=0.7391 | val_f1=0.7902 | val_auroc=0.9537

[Epoch 08] train_loss=0.0341 | val_loss=0.3293 | val_mcc=0.7389 | val_f1=0.7900 | val_auroc=0.9536
[EarlyStop] epoch=8 | best_val_mcc=0.7652
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7782 | F1=0.8402 | AUROC=0.9625 | AUPRC=0.9229
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8276 | F1=0.9099 | AUROC=0.9736 | AUPRC=0.9737
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4442 | F1=0.7381 | AUROC=0.7908 | AUPRC=0.7816
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5477 | F1=0.7718 | AUROC=0.8967 | AUPRC=0.8821
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3573 | val_loss=0.2114 | val_mcc=0.7530 | val_f1=0.8008 | val_auroc=0.9673

[Epoch 02] train_loss=0.2472 | val_loss=0.1854 | val_mcc=0.7737 | val_f1=0.8178 | val_auroc=0.9686

[Epoch 03] train_loss=0.2070 | val_loss=0.1950 | val_mcc=0.7696 | val_f1=0.8144 | val_auroc=0.9677

[Epoch 04] train_loss=0.1594 | val_loss=0.2179 | val_mcc=0.7517 | val_f1=0.7997 | val_auroc=0.9638

[Epoch 05] train_loss=0.1131 | val_loss=0.2333 | val_mcc=0.7523 | val_f1=0.8004 | val_auroc=0.9625

[Epoch 06] train_loss=0.0702 | val_loss=0.2528 | val_mcc=0.7483 | val_f1=0.7975 | val_auroc=0.9595

[Epoch 07] train_loss=0.0407 | val_loss=0.2627 | val_mcc=0.7521 | val_f1=0.8005 | val_auroc=0.9602

[Epoch 08] train_loss=0.0280 | val_loss=0.2836 | val_mcc=0.7490 | val_f1=0.7979 | val_auroc=0.9601
[EarlyStop] epoch=8 | best_val_mcc=0.7737
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7843 | F1=0.8443 | AUROC=0.9634 | AUPRC=0.9248
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8269 | F1=0.9066 | AUROC=0.9759 | AUPRC=0.9760
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4320 | F1=0.7270 | AUROC=0.7853 | AUPRC=0.7769
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5454 | F1=0.7707 | AUROC=0.8928 | AUPRC=0.8812
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 187.
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7967 | F1=0.8533 | AUROC=0.9693 | AUPRC=0.9332
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8509 | F1=0.9212 | AUROC=0.9833 | AUPRC=0.9837
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4270 | F1=0.7294 | AUROC=0.7835 | AUPRC=0.7645
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5587 | F1=0.7767 | AUROC=0.9055 | AUPRC=0.8871
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 160.
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7832 | F1=0.8438 | AUROC=0.9649 | AUPRC=0.9261
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8641 | F1=0.9296 | AUROC=0.9793 | AUPRC=0.9794
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4475 | F1=0.7378 | AUROC=0.7887 | AUPRC=0.7830
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5784 | F1=0.7856 | AUROC=0.9019 | AUPRC=0.8811
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 80.
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7770 | F1=0.8393 | AUROC=0.9637 | AUPRC=0.9212
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8246 | F1=0.9086 | AUROC=0.9748 | AUPRC=0.9744
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4513 | F1=0.7407 | AUROC=0.7885 | AUPRC=0.7750
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5872 | F1=0.7896 | AUROC=0.9001 | AUPRC=0.8832
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 100.
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7867 | F1=0.8462 | AUROC=0.9650 | AUPRC=0.9248
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8368 | F1=0.9137 | AUROC=0.9752 | AUPRC=0.9764
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4438 | F1=0.7374 | AUROC=0.7893 | AUPRC=0.7792
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.3775 | val_loss=0.2434 | val_mcc=0.7193 | val_f1=0.7702 | val_auroc=0.9459

[Epoch 02] train_loss=0.2542 | val_loss=0.2120 | val_mcc=0.7232 | val_f1=0.7669 | val_auroc=0.9520

[Epoch 03] train_loss=0.2121 | val_loss=0.2474 | val_mcc=0.7023 | val_f1=0.7609 | val_auroc=0.9489

[Epoch 04] train_loss=0.1690 | val_loss=0.2580 | val_mcc=0.6938 | val_f1=0.7541 | val_auroc=0.9417

[Epoch 05] train_loss=0.1222 | val_loss=0.3014 | val_mcc=0.6634 | val_f1=0.7296 | val_auroc=0.9339

[Epoch 06] train_loss=0.0822 | val_loss=0.3308 | val_mcc=0.6557 | val_f1=0.7223 | val_auroc=0.9378

[Epoch 07] train_loss=0.0510 | val_loss=0.3126 | val_mcc=0.6784 | val_f1=0.7419 | val_auroc=0.9358

[Epoch 08] train_loss=0.0375 | val_loss=0.3451 | val_mcc=0.6698 | val_f1=0.7349 | val_auroc=0.9361
[EarlyStop] epoch=8 | best_val_mcc=0.7232
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7290 | F1=0.7933 | AUROC=0.9481 | AUPRC=0.8924
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7022 | F1=0.8267 | AUROC=0.9539 | AUPRC=0.9525
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4408 | F1=0.6887 | AUROC=0.7810 | AUPRC=0.7797
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6241 | F1=0.7892 | AUROC=0.8885 | AUPRC=0.8768
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3778 | val_loss=0.2487 | val_mcc=0.7363 | val_f1=0.7877 | val_auroc=0.9557

[Epoch 02] train_loss=0.2646 | val_loss=0.2210 | val_mcc=0.7508 | val_f1=0.7993 | val_auroc=0.9607

[Epoch 03] train_loss=0.2235 | val_loss=0.2066 | val_mcc=0.7333 | val_f1=0.7776 | val_auroc=0.9530

[Epoch 04] train_loss=0.1888 | val_loss=0.2535 | val_mcc=0.7123 | val_f1=0.7688 | val_auroc=0.9485

[Epoch 05] train_loss=0.1357 | val_loss=0.3386 | val_mcc=0.6610 | val_f1=0.7257 | val_auroc=0.9396

[Epoch 06] train_loss=0.0928 | val_loss=0.3145 | val_mcc=0.6871 | val_f1=0.7434 | val_auroc=0.9308

[Epoch 07] train_loss=0.0541 | val_loss=0.3642 | val_mcc=0.6802 | val_f1=0.7434 | val_auroc=0.9331

[Epoch 08] train_loss=0.0364 | val_loss=0.4033 | val_mcc=0.6685 | val_f1=0.7341 | val_auroc=0.9263
[EarlyStop] epoch=8 | best_val_mcc=0.7508
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7716 | F1=0.8346 | AUROC=0.9587 | AUPRC=0.9118
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7762 | F1=0.8833 | AUROC=0.9633 | AUPRC=0.9618
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4670 | F1=0.7405 | AUROC=0.7947 | AUPRC=0.7853
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6339 | F1=0.8104 | AUROC=0.9099 | AUPRC=0.8982
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3829 | val_loss=0.2244 | val_mcc=0.6981 | val_f1=0.7331 | val_auroc=0.9491

[Epoch 02] train_loss=0.2596 | val_loss=0.2103 | val_mcc=0.7274 | val_f1=0.7683 | val_auroc=0.9509

[Epoch 03] train_loss=0.2154 | val_loss=0.2217 | val_mcc=0.7044 | val_f1=0.7501 | val_auroc=0.9452

[Epoch 04] train_loss=0.1713 | val_loss=0.2519 | val_mcc=0.6986 | val_f1=0.7565 | val_auroc=0.9379

[Epoch 05] train_loss=0.1261 | val_loss=0.2947 | val_mcc=0.6769 | val_f1=0.7408 | val_auroc=0.9351

[Epoch 06] train_loss=0.0846 | val_loss=0.3249 | val_mcc=0.6815 | val_f1=0.7404 | val_auroc=0.9263

[Epoch 07] train_loss=0.0469 | val_loss=0.3752 | val_mcc=0.6645 | val_f1=0.7304 | val_auroc=0.9251

[Epoch 08] train_loss=0.0340 | val_loss=0.3869 | val_mcc=0.6682 | val_f1=0.7327 | val_auroc=0.9246
[EarlyStop] epoch=8 | best_val_mcc=0.7274
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7346 | F1=0.7947 | AUROC=0.9474 | AUPRC=0.8947
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6927 | F1=0.8118 | AUROC=0.9553 | AUPRC=0.9540
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4615 | F1=0.6940 | AUROC=0.7915 | AUPRC=0.7831
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6574 | F1=0.8006 | AUROC=0.8981 | AUPRC=0.8863
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3796 | val_loss=0.2344 | val_mcc=0.7252 | val_f1=0.7753 | val_auroc=0.9512

[Epoch 02] train_loss=0.2564 | val_loss=0.2072 | val_mcc=0.7341 | val_f1=0.7790 | val_auroc=0.9553

[Epoch 03] train_loss=0.2091 | val_loss=0.2196 | val_mcc=0.7243 | val_f1=0.7754 | val_auroc=0.9504

[Epoch 04] train_loss=0.1626 | val_loss=0.2485 | val_mcc=0.7034 | val_f1=0.7618 | val_auroc=0.9463

[Epoch 05] train_loss=0.1137 | val_loss=0.2506 | val_mcc=0.7006 | val_f1=0.7553 | val_auroc=0.9409

[Epoch 06] train_loss=0.0731 | val_loss=0.2951 | val_mcc=0.6840 | val_f1=0.7457 | val_auroc=0.9369

[Epoch 07] train_loss=0.0426 | val_loss=0.3122 | val_mcc=0.6890 | val_f1=0.7502 | val_auroc=0.9389

[Epoch 08] train_loss=0.0298 | val_loss=0.3285 | val_mcc=0.6881 | val_f1=0.7497 | val_auroc=0.9396
[EarlyStop] epoch=8 | best_val_mcc=0.7341
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7427 | F1=0.8069 | AUROC=0.9504 | AUPRC=0.8965
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7288 | F1=0.8478 | AUROC=0.9513 | AUPRC=0.9495
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4651 | F1=0.7159 | AUROC=0.7914 | AUPRC=0.7837
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6438 | F1=0.8057 | AUROC=0.9018 | AUPRC=0.8870
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 169.
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7975 | F1=0.8539 | AUROC=0.9704 | AUPRC=0.9373
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8675 | F1=0.9306 | AUROC=0.9837 | AUPRC=0.9841
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4395 | F1=0.7358 | AUROC=0.7932 | AUPRC=0.7851
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5598 | F1=0.7772 | AUROC=0.9059 | AUPRC=0.8911
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 264.
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7625 | F1=0.8206 | AUROC=0.9585 | AUPRC=0.9110
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7679 | F1=0.8704 | AUROC=0.9690 | AUPRC=0.9671
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4663 | F1=0.7122 | AUROC=0.7984 | AUPRC=0.7927
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.6331 | F1=0.8006 | AUROC=0.9005 | AUPRC=0.8855
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 80.
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7524 | F1=0.8212 | AUROC=0.9529 | AUPRC=0.9020
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7442 | F1=0.8688 | AUROC=0.9540 | AUPRC=0.9526
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4685 | F1=0.7411 | AUROC=0.7963 | AUPRC=0.7904
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.6343 | F1=0.8100 | AUROC=0.9046 | AUPRC=0.8848
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 118.
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6877 | F1=0.7712 | AUROC=0.9252 | AUPRC=0.8590
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6688 | F1=0.8251 | AUROC=0.9167 | AUPRC=0.9215
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_dna_geom_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4275 | F1=0.7034 | AUROC=0.7725 | AUPRC=0.7712
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.3832 | val_loss=0.3180 | val_mcc=0.7495 | val_f1=0.7981 | val_auroc=0.9549

[Epoch 02] train_loss=0.3006 | val_loss=0.2933 | val_mcc=0.7496 | val_f1=0.7980 | val_auroc=0.9516

[Epoch 03] train_loss=0.2893 | val_loss=0.2828 | val_mcc=0.7496 | val_f1=0.7984 | val_auroc=0.9537

[Epoch 04] train_loss=0.2811 | val_loss=0.2496 | val_mcc=0.7636 | val_f1=0.8044 | val_auroc=0.9556

[Epoch 05] train_loss=0.2784 | val_loss=0.2463 | val_mcc=0.7673 | val_f1=0.8094 | val_auroc=0.9575

[Epoch 06] train_loss=0.2756 | val_loss=0.2384 | val_mcc=0.7668 | val_f1=0.8068 | val_auroc=0.9579

[Epoch 07] train_loss=0.2716 | val_loss=0.2462 | val_mcc=0.7651 | val_f1=0.8090 | val_auroc=0.9583

[Epoch 08] train_loss=0.2684 | val_loss=0.2395 | val_mcc=0.7677 | val_f1=0.8093 | val_auroc=0.9590

[Epoch 09] train_loss=0.2665 | val_loss=0.2299 | val_mcc=0.7770 | val_f1=0.8159 | val_auroc=0.9624

[Epoch 10] train_loss=0.2663 | val_loss=0.2221 | val_mcc=0.7680 | val_f1=0.8012 | val_auroc=0.9638

[Epoch 11] train_loss=0.2627 | val_loss=0.2217 | val_mcc=0.7758 | val_f1=0.8120 | val_auroc=0.9633

[Epoch 12] train_loss=0.2617 | val_loss=0.2193 | val_mcc=0.7568 | val_f1=0.7871 | val_auroc=0.9628

[Epoch 13] train_loss=0.2610 | val_loss=0.2206 | val_mcc=0.7677 | val_f1=0.8006 | val_auroc=0.9630

[Epoch 14] train_loss=0.2596 | val_loss=0.2178 | val_mcc=0.7632 | val_f1=0.7955 | val_auroc=0.9637

[Epoch 15] train_loss=0.2589 | val_loss=0.2187 | val_mcc=0.7721 | val_f1=0.8064 | val_auroc=0.9637
[EarlyStop] epoch=15 | best_val_mcc=0.7770
[Test] train3__val_center_bio_geom_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7797 | F1=0.8344 | AUROC=0.9606 | AUPRC=0.9214
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_geom_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_geom_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7863 | F1=0.8700 | AUROC=0.9716 | AUPRC=0.9734
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_geom_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_geom_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4242 | F1=0.6952 | AUROC=0.7649 | AUPRC=0.7618
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_geom_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_geom_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5757 | F1=0.7814 | AUROC=0.8777 | AUPRC=0.8660
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 95.
[Test] train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7930 | F1=0.8507 | AUROC=0.9691 | AUPRC=0.9334
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8444 | F1=0.9190 | AUROC=0.9793 | AUPRC=0.9808
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4436 | F1=0.7370 | AUROC=0.7906 | AUPRC=0.7770
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5611 | F1=0.7778 | AUROC=0.8999 | AUPRC=0.8833
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 99.
[Test] train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6565 | F1=0.6957 | AUROC=0.9433 | AUPRC=0.8875
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5958 | F1=0.6987 | AUROC=0.9590 | AUPRC=0.9576
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3821 | F1=0.5655 | AUROC=0.7712 | AUPRC=0.7653
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_geom_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5980 | F1=0.7416 | AUROC=0.8835 | AUPRC=0.8623

================================================================================
[*] POOLING: CLS
================================================================================
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.5821 | val_loss=0.4155 | val_mcc=0.5022 | val_f1=0.5983 | val_auroc=0.8294

[Epoch 02] train_loss=0.5089 | val_loss=0.4394 | val_mcc=0.5134 | val_f1=0.6127 | val_auroc=0.8425

[Epoch 03] train_loss=0.4742 | val_loss=0.4667 | val_mcc=0.5097 | val_f1=0.6087 | val_auroc=0.8564

[Epoch 04] train_loss=0.4454 | val_loss=0.3596 | val_mcc=0.5578 | val_f1=0.6424 | val_auroc=0.8626

[Epoch 05] train_loss=0.4196 | val_loss=0.4095 | val_mcc=0.5521 | val_f1=0.6427 | val_auroc=0.8668

[Epoch 06] train_loss=0.3915 | val_loss=0.4843 | val_mcc=0.5190 | val_f1=0.6133 | val_auroc=0.8732

[Epoch 07] train_loss=0.3625 | val_loss=0.4225 | val_mcc=0.5422 | val_f1=0.6349 | val_auroc=0.8713

[Epoch 08] train_loss=0.3317 | val_loss=0.4451 | val_mcc=0.5404 | val_f1=0.6326 | val_auroc=0.8737

[Epoch 09] train_loss=0.2947 | val_loss=0.4454 | val_mcc=0.5425 | val_f1=0.6348 | val_auroc=0.8727

[Epoch 10] train_loss=0.2752 | val_loss=0.5137 | val_mcc=0.5195 | val_f1=0.6149 | val_auroc=0.8682
[EarlyStop] epoch=10 | best_val_mcc=0.5578
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5868 | F1=0.6904 | AUROC=0.8747 | AUPRC=0.7708
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5636 | F1=0.7443 | AUROC=0.8609 | AUPRC=0.8623
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3788 | F1=0.6441 | AUROC=0.7439 | AUPRC=0.7256
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5527 | F1=0.7357 | AUROC=0.8533 | AUPRC=0.8330
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5896 | val_loss=0.4236 | val_mcc=0.5090 | val_f1=0.6063 | val_auroc=0.8302

[Epoch 02] train_loss=0.5141 | val_loss=0.4558 | val_mcc=0.5182 | val_f1=0.6164 | val_auroc=0.8440

[Epoch 03] train_loss=0.4725 | val_loss=0.4051 | val_mcc=0.5394 | val_f1=0.6325 | val_auroc=0.8540

[Epoch 04] train_loss=0.4491 | val_loss=0.3739 | val_mcc=0.5570 | val_f1=0.6442 | val_auroc=0.8620

[Epoch 05] train_loss=0.4225 | val_loss=0.4515 | val_mcc=0.5318 | val_f1=0.6261 | val_auroc=0.8670

[Epoch 06] train_loss=0.3906 | val_loss=0.4409 | val_mcc=0.5420 | val_f1=0.6348 | val_auroc=0.8638

[Epoch 07] train_loss=0.3720 | val_loss=0.4955 | val_mcc=0.5188 | val_f1=0.6145 | val_auroc=0.8667

[Epoch 08] train_loss=0.3367 | val_loss=0.5227 | val_mcc=0.5133 | val_f1=0.6100 | val_auroc=0.8634

[Epoch 09] train_loss=0.3024 | val_loss=0.5023 | val_mcc=0.5308 | val_f1=0.6254 | val_auroc=0.8584

[Epoch 10] train_loss=0.2827 | val_loss=0.4960 | val_mcc=0.5428 | val_f1=0.6354 | val_auroc=0.8601
[EarlyStop] epoch=10 | best_val_mcc=0.5570
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5949 | F1=0.7003 | AUROC=0.8740 | AUPRC=0.7635
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5673 | F1=0.7500 | AUROC=0.8556 | AUPRC=0.8512
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3849 | F1=0.6567 | AUROC=0.7486 | AUPRC=0.7284
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5717 | F1=0.7490 | AUROC=0.8549 | AUPRC=0.8291
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5903 | val_loss=0.4055 | val_mcc=0.5074 | val_f1=0.6018 | val_auroc=0.8341

[Epoch 02] train_loss=0.5012 | val_loss=0.3669 | val_mcc=0.5335 | val_f1=0.6221 | val_auroc=0.8539

[Epoch 03] train_loss=0.4678 | val_loss=0.3670 | val_mcc=0.5459 | val_f1=0.6333 | val_auroc=0.8615

[Epoch 04] train_loss=0.4408 | val_loss=0.3846 | val_mcc=0.5520 | val_f1=0.6417 | val_auroc=0.8689

[Epoch 05] train_loss=0.4187 | val_loss=0.3959 | val_mcc=0.5541 | val_f1=0.6443 | val_auroc=0.8751

[Epoch 06] train_loss=0.3883 | val_loss=0.3783 | val_mcc=0.5654 | val_f1=0.6528 | val_auroc=0.8740

[Epoch 07] train_loss=0.3600 | val_loss=0.3643 | val_mcc=0.5684 | val_f1=0.6523 | val_auroc=0.8758

[Epoch 08] train_loss=0.3259 | val_loss=0.4363 | val_mcc=0.5561 | val_f1=0.6458 | val_auroc=0.8753

[Epoch 09] train_loss=0.2935 | val_loss=0.4262 | val_mcc=0.5480 | val_f1=0.6380 | val_auroc=0.8668

[Epoch 10] train_loss=0.2639 | val_loss=0.4666 | val_mcc=0.5565 | val_f1=0.6457 | val_auroc=0.8681

[Epoch 11] train_loss=0.2370 | val_loss=0.5177 | val_mcc=0.5212 | val_f1=0.6187 | val_auroc=0.8535

[Epoch 12] train_loss=0.1767 | val_loss=0.6815 | val_mcc=0.5265 | val_f1=0.6225 | val_auroc=0.8542

[Epoch 13] train_loss=0.1517 | val_loss=0.7306 | val_mcc=0.5099 | val_f1=0.6096 | val_auroc=0.8457
[EarlyStop] epoch=13 | best_val_mcc=0.5684
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5904 | F1=0.6952 | AUROC=0.8882 | AUPRC=0.7727
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5376 | F1=0.7348 | AUROC=0.8636 | AUPRC=0.8604
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3896 | F1=0.6589 | AUROC=0.7500 | AUPRC=0.7217
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5724 | F1=0.7466 | AUROC=0.8652 | AUPRC=0.8312
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5783 | val_loss=0.4137 | val_mcc=0.5034 | val_f1=0.6008 | val_auroc=0.8322

[Epoch 02] train_loss=0.4992 | val_loss=0.3950 | val_mcc=0.5270 | val_f1=0.6220 | val_auroc=0.8501

[Epoch 03] train_loss=0.4628 | val_loss=0.4097 | val_mcc=0.5333 | val_f1=0.6281 | val_auroc=0.8630

[Epoch 04] train_loss=0.4344 | val_loss=0.3926 | val_mcc=0.5477 | val_f1=0.6391 | val_auroc=0.8698

[Epoch 05] train_loss=0.4030 | val_loss=0.4389 | val_mcc=0.5357 | val_f1=0.6287 | val_auroc=0.8729

[Epoch 06] train_loss=0.3702 | val_loss=0.4380 | val_mcc=0.5378 | val_f1=0.6303 | val_auroc=0.8741

[Epoch 07] train_loss=0.3403 | val_loss=0.3700 | val_mcc=0.5650 | val_f1=0.6513 | val_auroc=0.8746

[Epoch 08] train_loss=0.3046 | val_loss=0.4911 | val_mcc=0.5294 | val_f1=0.6228 | val_auroc=0.8733

[Epoch 09] train_loss=0.2673 | val_loss=0.4936 | val_mcc=0.5277 | val_f1=0.6220 | val_auroc=0.8676

[Epoch 10] train_loss=0.2265 | val_loss=0.5200 | val_mcc=0.5051 | val_f1=0.6059 | val_auroc=0.8539

[Epoch 11] train_loss=0.1799 | val_loss=0.6020 | val_mcc=0.4987 | val_f1=0.6004 | val_auroc=0.8536

[Epoch 12] train_loss=0.1258 | val_loss=0.6305 | val_mcc=0.4977 | val_f1=0.5999 | val_auroc=0.8496

[Epoch 13] train_loss=0.0987 | val_loss=0.6701 | val_mcc=0.4876 | val_f1=0.5924 | val_auroc=0.8463
[EarlyStop] epoch=13 | best_val_mcc=0.5650
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5993 | F1=0.7072 | AUROC=0.8869 | AUPRC=0.7774
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5670 | F1=0.7616 | AUROC=0.8650 | AUPRC=0.8634
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3983 | F1=0.6758 | AUROC=0.7486 | AUPRC=0.7235
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5747 | F1=0.7571 | AUROC=0.8683 | AUPRC=0.8440
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 197.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5666 | F1=0.6926 | AUROC=0.8821 | AUPRC=0.7654
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5400 | F1=0.7731 | AUROC=0.8548 | AUPRC=0.8454
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3719 | F1=0.6921 | AUROC=0.7399 | AUPRC=0.7281
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5597 | F1=0.7666 | AUROC=0.8577 | AUPRC=0.8228
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 66.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5669 | F1=0.6909 | AUROC=0.8764 | AUPRC=0.7661
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5514 | F1=0.7649 | AUROC=0.8621 | AUPRC=0.8586
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3654 | F1=0.6773 | AUROC=0.7478 | AUPRC=0.7349
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5658 | F1=0.7633 | AUROC=0.8561 | AUPRC=0.8368
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 61.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5667 | F1=0.6904 | AUROC=0.8702 | AUPRC=0.7558
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5540 | F1=0.7674 | AUROC=0.8604 | AUPRC=0.8573
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3610 | F1=0.6723 | AUROC=0.7441 | AUPRC=0.7371
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5358 | F1=0.7476 | AUROC=0.8493 | AUPRC=0.8277
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 86.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5705 | F1=0.6935 | AUROC=0.8756 | AUPRC=0.7693
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5707 | F1=0.7783 | AUROC=0.8618 | AUPRC=0.8531
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3729 | F1=0.6814 | AUROC=0.7509 | AUPRC=0.7333
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5668 | F1=0.7664 | AUROC=0.8577 | AUPRC=0.8396
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']

[Epoch 01] train_loss=0.6203 | val_loss=0.5084 | val_mcc=0.3999 | val_f1=0.5206 | val_auroc=0.7711

[Epoch 02] train_loss=0.5556 | val_loss=0.4839 | val_mcc=0.4349 | val_f1=0.5461 | val_auroc=0.7899

[Epoch 03] train_loss=0.5255 | val_loss=0.4746 | val_mcc=0.4473 | val_f1=0.5579 | val_auroc=0.8013

[Epoch 04] train_loss=0.5040 | val_loss=0.4912 | val_mcc=0.4507 | val_f1=0.5643 | val_auroc=0.8145

[Epoch 05] train_loss=0.4752 | val_loss=0.5407 | val_mcc=0.4389 | val_f1=0.5550 | val_auroc=0.8232

[Epoch 06] train_loss=0.4511 | val_loss=0.5408 | val_mcc=0.4564 | val_f1=0.5680 | val_auroc=0.8339

[Epoch 07] train_loss=0.4155 | val_loss=0.4240 | val_mcc=0.5002 | val_f1=0.6014 | val_auroc=0.8436

[Epoch 08] train_loss=0.3826 | val_loss=0.4558 | val_mcc=0.4913 | val_f1=0.5956 | val_auroc=0.8421

[Epoch 09] train_loss=0.3508 | val_loss=0.4492 | val_mcc=0.4941 | val_f1=0.5974 | val_auroc=0.8414

[Epoch 10] train_loss=0.3149 | val_loss=0.5120 | val_mcc=0.4767 | val_f1=0.5845 | val_auroc=0.8383

[Epoch 11] train_loss=0.2824 | val_loss=0.5707 | val_mcc=0.4735 | val_f1=0.5812 | val_auroc=0.8428

[Epoch 12] train_loss=0.2353 | val_loss=0.5754 | val_mcc=0.4594 | val_f1=0.5711 | val_auroc=0.8352

[Epoch 13] train_loss=0.2110 | val_loss=0.6222 | val_mcc=0.4552 | val_f1=0.5675 | val_auroc=0.8343
[EarlyStop] epoch=13 | best_val_mcc=0.5002
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5237 | F1=0.6516 | AUROC=0.8433 | AUPRC=0.7178
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.4884 | F1=0.7220 | AUROC=0.8183 | AUPRC=0.8162
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3409 | F1=0.6446 | AUROC=0.7318 | AUPRC=0.7004
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4766 | F1=0.6945 | AUROC=0.7997 | AUPRC=0.7814
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.6312 | val_loss=0.4937 | val_mcc=0.4027 | val_f1=0.5214 | val_auroc=0.7759

[Epoch 02] train_loss=0.5553 | val_loss=0.4566 | val_mcc=0.4532 | val_f1=0.5571 | val_auroc=0.7962

[Epoch 03] train_loss=0.5309 | val_loss=0.4549 | val_mcc=0.4591 | val_f1=0.5634 | val_auroc=0.8062

[Epoch 04] train_loss=0.5089 | val_loss=0.4881 | val_mcc=0.4652 | val_f1=0.5751 | val_auroc=0.8193

[Epoch 05] train_loss=0.4821 | val_loss=0.4555 | val_mcc=0.4887 | val_f1=0.5920 | val_auroc=0.8254

[Epoch 06] train_loss=0.4553 | val_loss=0.5087 | val_mcc=0.4691 | val_f1=0.5788 | val_auroc=0.8274

[Epoch 07] train_loss=0.4289 | val_loss=0.4428 | val_mcc=0.4966 | val_f1=0.5981 | val_auroc=0.8341

[Epoch 08] train_loss=0.4013 | val_loss=0.5042 | val_mcc=0.4785 | val_f1=0.5859 | val_auroc=0.8344

[Epoch 09] train_loss=0.3705 | val_loss=0.5616 | val_mcc=0.4676 | val_f1=0.5768 | val_auroc=0.8341

[Epoch 10] train_loss=0.3387 | val_loss=0.5914 | val_mcc=0.4460 | val_f1=0.5603 | val_auroc=0.8224

[Epoch 11] train_loss=0.2874 | val_loss=0.6066 | val_mcc=0.4542 | val_f1=0.5671 | val_auroc=0.8198

[Epoch 12] train_loss=0.2181 | val_loss=0.6800 | val_mcc=0.4406 | val_f1=0.5571 | val_auroc=0.8086

[Epoch 13] train_loss=0.1738 | val_loss=0.7854 | val_mcc=0.4431 | val_f1=0.5591 | val_auroc=0.8090
[EarlyStop] epoch=13 | best_val_mcc=0.4966
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5120 | F1=0.6399 | AUROC=0.8307 | AUPRC=0.6964
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.4703 | F1=0.7063 | AUROC=0.7964 | AUPRC=0.7915
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3321 | F1=0.6386 | AUROC=0.7167 | AUPRC=0.6878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.4590 | F1=0.6792 | AUROC=0.7840 | AUPRC=0.7709
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.6285 | val_loss=0.4425 | val_mcc=0.4053 | val_f1=0.5061 | val_auroc=0.7769

[Epoch 02] train_loss=0.5544 | val_loss=0.4583 | val_mcc=0.4380 | val_f1=0.5450 | val_auroc=0.7984

[Epoch 03] train_loss=0.5263 | val_loss=0.4154 | val_mcc=0.4583 | val_f1=0.5551 | val_auroc=0.8112

[Epoch 04] train_loss=0.5020 | val_loss=0.4371 | val_mcc=0.4790 | val_f1=0.5815 | val_auroc=0.8231

[Epoch 05] train_loss=0.4752 | val_loss=0.4210 | val_mcc=0.4911 | val_f1=0.5904 | val_auroc=0.8304

[Epoch 06] train_loss=0.4500 | val_loss=0.3887 | val_mcc=0.5011 | val_f1=0.5902 | val_auroc=0.8354

[Epoch 07] train_loss=0.4179 | val_loss=0.4259 | val_mcc=0.4972 | val_f1=0.5980 | val_auroc=0.8411

[Epoch 08] train_loss=0.3853 | val_loss=0.5120 | val_mcc=0.4863 | val_f1=0.5916 | val_auroc=0.8439

[Epoch 09] train_loss=0.3514 | val_loss=0.4845 | val_mcc=0.4863 | val_f1=0.5917 | val_auroc=0.8411

[Epoch 10] train_loss=0.3110 | val_loss=0.5214 | val_mcc=0.4764 | val_f1=0.5836 | val_auroc=0.8313

[Epoch 11] train_loss=0.2465 | val_loss=0.5946 | val_mcc=0.4739 | val_f1=0.5825 | val_auroc=0.8312

[Epoch 12] train_loss=0.2137 | val_loss=0.7793 | val_mcc=0.4414 | val_f1=0.5556 | val_auroc=0.8272
[EarlyStop] epoch=12 | best_val_mcc=0.5011
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5165 | F1=0.6232 | AUROC=0.8301 | AUPRC=0.7074
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.4444 | F1=0.6576 | AUROC=0.8057 | AUPRC=0.8068
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3248 | F1=0.6043 | AUROC=0.7157 | AUPRC=0.6918
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.4639 | F1=0.6484 | AUROC=0.7867 | AUPRC=0.7708
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.6241 | val_loss=0.5161 | val_mcc=0.3955 | val_f1=0.5198 | val_auroc=0.7724

[Epoch 02] train_loss=0.5539 | val_loss=0.5204 | val_mcc=0.4225 | val_f1=0.5427 | val_auroc=0.7934

[Epoch 03] train_loss=0.5196 | val_loss=0.4281 | val_mcc=0.4575 | val_f1=0.5580 | val_auroc=0.8090

[Epoch 04] train_loss=0.4967 | val_loss=0.4662 | val_mcc=0.4642 | val_f1=0.5735 | val_auroc=0.8184

[Epoch 05] train_loss=0.4670 | val_loss=0.4560 | val_mcc=0.4846 | val_f1=0.5898 | val_auroc=0.8333

[Epoch 06] train_loss=0.4362 | val_loss=0.4838 | val_mcc=0.4748 | val_f1=0.5831 | val_auroc=0.8390

[Epoch 07] train_loss=0.4058 | val_loss=0.4175 | val_mcc=0.5042 | val_f1=0.6037 | val_auroc=0.8447

[Epoch 08] train_loss=0.3683 | val_loss=0.5067 | val_mcc=0.4699 | val_f1=0.5783 | val_auroc=0.8433

[Epoch 09] train_loss=0.3284 | val_loss=0.4602 | val_mcc=0.4868 | val_f1=0.5919 | val_auroc=0.8420

[Epoch 10] train_loss=0.2899 | val_loss=0.6023 | val_mcc=0.4497 | val_f1=0.5617 | val_auroc=0.8384

[Epoch 11] train_loss=0.2477 | val_loss=0.5449 | val_mcc=0.4677 | val_f1=0.5777 | val_auroc=0.8355

[Epoch 12] train_loss=0.1803 | val_loss=0.6089 | val_mcc=0.4459 | val_f1=0.5611 | val_auroc=0.8256

[Epoch 13] train_loss=0.1503 | val_loss=0.6907 | val_mcc=0.4408 | val_f1=0.5564 | val_auroc=0.8282
[EarlyStop] epoch=13 | best_val_mcc=0.5042
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5227 | F1=0.6485 | AUROC=0.8377 | AUPRC=0.7149
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.4847 | F1=0.7070 | AUROC=0.8082 | AUPRC=0.8037
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3321 | F1=0.6386 | AUROC=0.7167 | AUPRC=0.6937
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.4617 | F1=0.6818 | AUROC=0.7879 | AUPRC=0.7726
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 215.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.4890 | F1=0.6372 | AUROC=0.8387 | AUPRC=0.7067
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.4907 | F1=0.7410 | AUROC=0.8273 | AUPRC=0.8204
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3324 | F1=0.6667 | AUROC=0.7299 | AUPRC=0.7081
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4456 | F1=0.6989 | AUROC=0.7958 | AUPRC=0.7753
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 213.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.4733 | F1=0.6250 | AUROC=0.8258 | AUPRC=0.6890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4852 | F1=0.7350 | AUROC=0.8104 | AUPRC=0.7974
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3536 | F1=0.6682 | AUROC=0.7250 | AUPRC=0.6968
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4264 | F1=0.6838 | AUROC=0.7761 | AUPRC=0.7483
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 58.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.4528 | F1=0.6089 | AUROC=0.8141 | AUPRC=0.6796
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4437 | F1=0.7048 | AUROC=0.7867 | AUPRC=0.7868
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3311 | F1=0.6433 | AUROC=0.7154 | AUPRC=0.6973
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.3949 | F1=0.6594 | AUROC=0.7579 | AUPRC=0.7391
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 98.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.4743 | F1=0.6248 | AUROC=0.8220 | AUPRC=0.6858
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4340 | F1=0.7078 | AUROC=0.7992 | AUPRC=0.7927
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3346 | F1=0.6520 | AUROC=0.7130 | AUPRC=0.6847
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.4238 | F1=0.6744 | AUROC=0.7761 | AUPRC=0.7425
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.6334 | val_loss=0.4438 | val_mcc=0.4784 | val_f1=0.5500 | val_auroc=0.7924

[Epoch 02] train_loss=0.5405 | val_loss=0.4487 | val_mcc=0.5092 | val_f1=0.5924 | val_auroc=0.8049

[Epoch 03] train_loss=0.5152 | val_loss=0.4240 | val_mcc=0.5275 | val_f1=0.5959 | val_auroc=0.8066

[Epoch 04] train_loss=0.4996 | val_loss=0.4723 | val_mcc=0.5051 | val_f1=0.6035 | val_auroc=0.8108

[Epoch 05] train_loss=0.4838 | val_loss=0.4392 | val_mcc=0.5146 | val_f1=0.6066 | val_auroc=0.8136

[Epoch 06] train_loss=0.4736 | val_loss=0.5305 | val_mcc=0.4716 | val_f1=0.5807 | val_auroc=0.8204

[Epoch 07] train_loss=0.4632 | val_loss=0.3859 | val_mcc=0.5276 | val_f1=0.6073 | val_auroc=0.8186

[Epoch 08] train_loss=0.4491 | val_loss=0.4854 | val_mcc=0.4874 | val_f1=0.5927 | val_auroc=0.8279

[Epoch 09] train_loss=0.4339 | val_loss=0.4444 | val_mcc=0.5057 | val_f1=0.6064 | val_auroc=0.8269

[Epoch 10] train_loss=0.4231 | val_loss=0.4263 | val_mcc=0.5208 | val_f1=0.6143 | val_auroc=0.8180

[Epoch 11] train_loss=0.3971 | val_loss=0.4145 | val_mcc=0.5135 | val_f1=0.6109 | val_auroc=0.8320

[Epoch 12] train_loss=0.3561 | val_loss=0.4482 | val_mcc=0.4912 | val_f1=0.5952 | val_auroc=0.8209

[Epoch 13] train_loss=0.3264 | val_loss=0.5502 | val_mcc=0.4331 | val_f1=0.5505 | val_auroc=0.8182
[EarlyStop] epoch=13 | best_val_mcc=0.5276
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5624 | F1=0.6608 | AUROC=0.8079 | AUPRC=0.7208
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.4951 | F1=0.6815 | AUROC=0.7689 | AUPRC=0.8058
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3534 | F1=0.6101 | AUROC=0.7076 | AUPRC=0.7175
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4995 | F1=0.6799 | AUROC=0.7718 | AUPRC=0.7840
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.6446 | val_loss=0.5491 | val_mcc=0.4550 | val_f1=0.5671 | val_auroc=0.7958

[Epoch 02] train_loss=0.5482 | val_loss=0.4378 | val_mcc=0.5066 | val_f1=0.5849 | val_auroc=0.8061

[Epoch 03] train_loss=0.5166 | val_loss=0.5143 | val_mcc=0.4994 | val_f1=0.6010 | val_auroc=0.8096

[Epoch 04] train_loss=0.4968 | val_loss=0.4868 | val_mcc=0.4917 | val_f1=0.5961 | val_auroc=0.8176

[Epoch 05] train_loss=0.4803 | val_loss=0.3795 | val_mcc=0.5325 | val_f1=0.6143 | val_auroc=0.8261

[Epoch 06] train_loss=0.4684 | val_loss=0.4672 | val_mcc=0.5110 | val_f1=0.6082 | val_auroc=0.8209

[Epoch 07] train_loss=0.4603 | val_loss=0.4429 | val_mcc=0.5098 | val_f1=0.6091 | val_auroc=0.8295

[Epoch 08] train_loss=0.4438 | val_loss=0.3740 | val_mcc=0.5337 | val_f1=0.6157 | val_auroc=0.8271

[Epoch 09] train_loss=0.4282 | val_loss=0.4102 | val_mcc=0.5145 | val_f1=0.6065 | val_auroc=0.8175

[Epoch 10] train_loss=0.3947 | val_loss=0.4313 | val_mcc=0.4941 | val_f1=0.5928 | val_auroc=0.8111

[Epoch 11] train_loss=0.3379 | val_loss=0.7605 | val_mcc=0.3466 | val_f1=0.4827 | val_auroc=0.7963

[Epoch 12] train_loss=0.2648 | val_loss=0.6621 | val_mcc=0.4007 | val_f1=0.5273 | val_auroc=0.7868

[Epoch 13] train_loss=0.1813 | val_loss=0.8861 | val_mcc=0.3600 | val_f1=0.4971 | val_auroc=0.7680

[Epoch 14] train_loss=0.1427 | val_loss=0.9183 | val_mcc=0.3880 | val_f1=0.5179 | val_auroc=0.7777
[EarlyStop] epoch=14 | best_val_mcc=0.5337
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5533 | F1=0.6585 | AUROC=0.8144 | AUPRC=0.7184
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.4965 | F1=0.6902 | AUROC=0.7686 | AUPRC=0.8080
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3679 | F1=0.6254 | AUROC=0.7054 | AUPRC=0.7122
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.4838 | F1=0.6785 | AUROC=0.7740 | AUPRC=0.7829
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.6399 | val_loss=0.4897 | val_mcc=0.4703 | val_f1=0.5679 | val_auroc=0.7947

[Epoch 02] train_loss=0.5422 | val_loss=0.5418 | val_mcc=0.4781 | val_f1=0.5853 | val_auroc=0.8061

[Epoch 03] train_loss=0.5174 | val_loss=0.4183 | val_mcc=0.5239 | val_f1=0.5990 | val_auroc=0.8103

[Epoch 04] train_loss=0.5000 | val_loss=0.4416 | val_mcc=0.5250 | val_f1=0.6110 | val_auroc=0.8134

[Epoch 05] train_loss=0.4904 | val_loss=0.4011 | val_mcc=0.5368 | val_f1=0.6174 | val_auroc=0.8211

[Epoch 06] train_loss=0.4734 | val_loss=0.4080 | val_mcc=0.5297 | val_f1=0.6195 | val_auroc=0.8295

[Epoch 07] train_loss=0.4646 | val_loss=0.4114 | val_mcc=0.5267 | val_f1=0.6190 | val_auroc=0.8330

[Epoch 08] train_loss=0.4484 | val_loss=0.4586 | val_mcc=0.4994 | val_f1=0.6017 | val_auroc=0.8297

[Epoch 09] train_loss=0.4353 | val_loss=0.4842 | val_mcc=0.4786 | val_f1=0.5860 | val_auroc=0.8243

[Epoch 10] train_loss=0.4011 | val_loss=0.4496 | val_mcc=0.4851 | val_f1=0.5906 | val_auroc=0.8229

[Epoch 11] train_loss=0.3806 | val_loss=0.4740 | val_mcc=0.4785 | val_f1=0.5853 | val_auroc=0.8124
[EarlyStop] epoch=11 | best_val_mcc=0.5368
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5588 | F1=0.6622 | AUROC=0.8158 | AUPRC=0.7254
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.4888 | F1=0.6890 | AUROC=0.7854 | AUPRC=0.8129
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3629 | F1=0.6193 | AUROC=0.7094 | AUPRC=0.7189
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.4935 | F1=0.6853 | AUROC=0.7847 | AUPRC=0.7875
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.6354 | val_loss=0.4771 | val_mcc=0.4710 | val_f1=0.5629 | val_auroc=0.7902

[Epoch 02] train_loss=0.5366 | val_loss=0.4264 | val_mcc=0.5108 | val_f1=0.5871 | val_auroc=0.8035

[Epoch 03] train_loss=0.5117 | val_loss=0.4362 | val_mcc=0.5188 | val_f1=0.6013 | val_auroc=0.8074

[Epoch 04] train_loss=0.4954 | val_loss=0.4117 | val_mcc=0.5260 | val_f1=0.6060 | val_auroc=0.8099

[Epoch 05] train_loss=0.4807 | val_loss=0.4252 | val_mcc=0.5146 | val_f1=0.6063 | val_auroc=0.8151

[Epoch 06] train_loss=0.4659 | val_loss=0.4050 | val_mcc=0.5206 | val_f1=0.6122 | val_auroc=0.8202

[Epoch 07] train_loss=0.4514 | val_loss=0.4107 | val_mcc=0.5185 | val_f1=0.6125 | val_auroc=0.8233

[Epoch 08] train_loss=0.4363 | val_loss=0.3861 | val_mcc=0.5234 | val_f1=0.6133 | val_auroc=0.8250

[Epoch 09] train_loss=0.4136 | val_loss=0.4447 | val_mcc=0.4926 | val_f1=0.5963 | val_auroc=0.8258

[Epoch 10] train_loss=0.3968 | val_loss=0.4561 | val_mcc=0.4773 | val_f1=0.5850 | val_auroc=0.8242
[EarlyStop] epoch=10 | best_val_mcc=0.5260
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5518 | F1=0.6531 | AUROC=0.8106 | AUPRC=0.7211
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.4863 | F1=0.6814 | AUROC=0.7746 | AUPRC=0.8054
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3555 | F1=0.6099 | AUROC=0.7117 | AUPRC=0.7178
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.4945 | F1=0.6787 | AUROC=0.7783 | AUPRC=0.7872
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 304.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5475 | F1=0.6773 | AUROC=0.8675 | AUPRC=0.7685
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5335 | F1=0.7609 | AUROC=0.8558 | AUPRC=0.8656
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3642 | F1=0.6718 | AUROC=0.7364 | AUPRC=0.7416
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4953 | F1=0.7225 | AUROC=0.8255 | AUPRC=0.8186
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 41.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5339 | F1=0.6651 | AUROC=0.8417 | AUPRC=0.7502
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5141 | F1=0.7362 | AUROC=0.8122 | AUPRC=0.8295
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3460 | F1=0.6523 | AUROC=0.7284 | AUPRC=0.7278
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4689 | F1=0.7066 | AUROC=0.8036 | AUPRC=0.8013
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 48.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5268 | F1=0.6605 | AUROC=0.8381 | AUPRC=0.7486
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4857 | F1=0.7200 | AUROC=0.8092 | AUPRC=0.8288
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3457 | F1=0.6540 | AUROC=0.7193 | AUPRC=0.7264
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4652 | F1=0.6977 | AUROC=0.7930 | AUPRC=0.7985
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 58.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5234 | F1=0.6582 | AUROC=0.8352 | AUPRC=0.7452
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5080 | F1=0.7339 | AUROC=0.8133 | AUPRC=0.8313
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3411 | F1=0.6524 | AUROC=0.7169 | AUPRC=0.7234
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.4681 | F1=0.7002 | AUROC=0.7941 | AUPRC=0.8010
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.5838 | val_loss=0.4308 | val_mcc=0.5045 | val_f1=0.6022 | val_auroc=0.8273

[Epoch 02] train_loss=0.5095 | val_loss=0.4525 | val_mcc=0.5085 | val_f1=0.6090 | val_auroc=0.8407

[Epoch 03] train_loss=0.4811 | val_loss=0.4019 | val_mcc=0.5380 | val_f1=0.6308 | val_auroc=0.8530

[Epoch 04] train_loss=0.4537 | val_loss=0.4519 | val_mcc=0.5230 | val_f1=0.6194 | val_auroc=0.8619

[Epoch 05] train_loss=0.4290 | val_loss=0.3802 | val_mcc=0.5516 | val_f1=0.6419 | val_auroc=0.8694

[Epoch 06] train_loss=0.3987 | val_loss=0.4139 | val_mcc=0.5512 | val_f1=0.6417 | val_auroc=0.8744

[Epoch 07] train_loss=0.3707 | val_loss=0.3915 | val_mcc=0.5599 | val_f1=0.6488 | val_auroc=0.8758

[Epoch 08] train_loss=0.3435 | val_loss=0.3801 | val_mcc=0.5605 | val_f1=0.6485 | val_auroc=0.8735

[Epoch 09] train_loss=0.3162 | val_loss=0.4019 | val_mcc=0.5625 | val_f1=0.6508 | val_auroc=0.8762

[Epoch 10] train_loss=0.2950 | val_loss=0.4403 | val_mcc=0.5487 | val_f1=0.6397 | val_auroc=0.8715

[Epoch 11] train_loss=0.2629 | val_loss=0.5430 | val_mcc=0.5132 | val_f1=0.6092 | val_auroc=0.8688

[Epoch 12] train_loss=0.2387 | val_loss=0.5257 | val_mcc=0.5181 | val_f1=0.6150 | val_auroc=0.8645

[Epoch 13] train_loss=0.2138 | val_loss=0.5268 | val_mcc=0.5350 | val_f1=0.6293 | val_auroc=0.8633

[Epoch 14] train_loss=0.1798 | val_loss=0.5702 | val_mcc=0.5227 | val_f1=0.6189 | val_auroc=0.8612

[Epoch 15] train_loss=0.1657 | val_loss=0.5873 | val_mcc=0.5146 | val_f1=0.6129 | val_auroc=0.8579
[EarlyStop] epoch=15 | best_val_mcc=0.5625
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6108 | F1=0.7190 | AUROC=0.8910 | AUPRC=0.7826
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5601 | F1=0.7690 | AUROC=0.8648 | AUPRC=0.8618
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4140 | F1=0.6962 | AUROC=0.7567 | AUPRC=0.7390
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5650 | F1=0.7593 | AUROC=0.8668 | AUPRC=0.8387
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5841 | val_loss=0.4836 | val_mcc=0.4916 | val_f1=0.5960 | val_auroc=0.8281

[Epoch 02] train_loss=0.5077 | val_loss=0.4187 | val_mcc=0.5263 | val_f1=0.6219 | val_auroc=0.8468

[Epoch 03] train_loss=0.4731 | val_loss=0.4330 | val_mcc=0.5350 | val_f1=0.6294 | val_auroc=0.8549

[Epoch 04] train_loss=0.4455 | val_loss=0.4424 | val_mcc=0.5414 | val_f1=0.6337 | val_auroc=0.8669

[Epoch 05] train_loss=0.4183 | val_loss=0.5154 | val_mcc=0.5095 | val_f1=0.6049 | val_auroc=0.8700

[Epoch 06] train_loss=0.3968 | val_loss=0.4365 | val_mcc=0.5477 | val_f1=0.6386 | val_auroc=0.8744

[Epoch 07] train_loss=0.3682 | val_loss=0.3761 | val_mcc=0.5656 | val_f1=0.6506 | val_auroc=0.8753

[Epoch 08] train_loss=0.3411 | val_loss=0.4114 | val_mcc=0.5504 | val_f1=0.6414 | val_auroc=0.8716

[Epoch 09] train_loss=0.3129 | val_loss=0.5159 | val_mcc=0.5367 | val_f1=0.6288 | val_auroc=0.8673

[Epoch 10] train_loss=0.2917 | val_loss=0.5000 | val_mcc=0.5331 | val_f1=0.6273 | val_auroc=0.8597

[Epoch 11] train_loss=0.2678 | val_loss=0.5446 | val_mcc=0.5331 | val_f1=0.6275 | val_auroc=0.8556

[Epoch 12] train_loss=0.2307 | val_loss=0.6209 | val_mcc=0.5319 | val_f1=0.6264 | val_auroc=0.8573

[Epoch 13] train_loss=0.2147 | val_loss=0.6190 | val_mcc=0.5287 | val_f1=0.6242 | val_auroc=0.8516
[EarlyStop] epoch=13 | best_val_mcc=0.5656
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5926 | F1=0.6977 | AUROC=0.8881 | AUPRC=0.7523
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5458 | F1=0.7461 | AUROC=0.8625 | AUPRC=0.8461
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3878 | F1=0.6639 | AUROC=0.7543 | AUPRC=0.7234
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5589 | F1=0.7424 | AUROC=0.8646 | AUPRC=0.8123
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5819 | val_loss=0.4196 | val_mcc=0.5047 | val_f1=0.6035 | val_auroc=0.8341

[Epoch 02] train_loss=0.5040 | val_loss=0.3980 | val_mcc=0.5212 | val_f1=0.6161 | val_auroc=0.8508

[Epoch 03] train_loss=0.4730 | val_loss=0.3874 | val_mcc=0.5421 | val_f1=0.6342 | val_auroc=0.8638

[Epoch 04] train_loss=0.4478 | val_loss=0.3640 | val_mcc=0.5564 | val_f1=0.6431 | val_auroc=0.8710

[Epoch 05] train_loss=0.4220 | val_loss=0.3586 | val_mcc=0.5674 | val_f1=0.6536 | val_auroc=0.8791

[Epoch 06] train_loss=0.3941 | val_loss=0.3849 | val_mcc=0.5630 | val_f1=0.6511 | val_auroc=0.8799

[Epoch 07] train_loss=0.3614 | val_loss=0.3883 | val_mcc=0.5661 | val_f1=0.6531 | val_auroc=0.8797

[Epoch 08] train_loss=0.3407 | val_loss=0.4242 | val_mcc=0.5509 | val_f1=0.6417 | val_auroc=0.8759

[Epoch 09] train_loss=0.3080 | val_loss=0.4298 | val_mcc=0.5654 | val_f1=0.6530 | val_auroc=0.8757

[Epoch 10] train_loss=0.2690 | val_loss=0.4604 | val_mcc=0.5530 | val_f1=0.6433 | val_auroc=0.8683

[Epoch 11] train_loss=0.2498 | val_loss=0.4965 | val_mcc=0.5496 | val_f1=0.6407 | val_auroc=0.8652
[EarlyStop] epoch=11 | best_val_mcc=0.5674
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6007 | F1=0.7070 | AUROC=0.8930 | AUPRC=0.7839
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5773 | F1=0.7637 | AUROC=0.8734 | AUPRC=0.8687
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3795 | F1=0.6623 | AUROC=0.7583 | AUPRC=0.7362
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5677 | F1=0.7533 | AUROC=0.8693 | AUPRC=0.8338
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5861 | val_loss=0.4678 | val_mcc=0.4885 | val_f1=0.5936 | val_auroc=0.8297

[Epoch 02] train_loss=0.5048 | val_loss=0.3943 | val_mcc=0.5247 | val_f1=0.6184 | val_auroc=0.8452

[Epoch 03] train_loss=0.4723 | val_loss=0.3797 | val_mcc=0.5411 | val_f1=0.6320 | val_auroc=0.8586

[Epoch 04] train_loss=0.4448 | val_loss=0.4143 | val_mcc=0.5326 | val_f1=0.6275 | val_auroc=0.8658

[Epoch 05] train_loss=0.4173 | val_loss=0.3988 | val_mcc=0.5480 | val_f1=0.6395 | val_auroc=0.8736

[Epoch 06] train_loss=0.3886 | val_loss=0.4201 | val_mcc=0.5466 | val_f1=0.6379 | val_auroc=0.8769

[Epoch 07] train_loss=0.3595 | val_loss=0.3629 | val_mcc=0.5660 | val_f1=0.6518 | val_auroc=0.8780

[Epoch 08] train_loss=0.3294 | val_loss=0.4114 | val_mcc=0.5404 | val_f1=0.6335 | val_auroc=0.8757

[Epoch 09] train_loss=0.2963 | val_loss=0.4556 | val_mcc=0.5307 | val_f1=0.6253 | val_auroc=0.8719

[Epoch 10] train_loss=0.2644 | val_loss=0.4646 | val_mcc=0.5268 | val_f1=0.6225 | val_auroc=0.8695

[Epoch 11] train_loss=0.2364 | val_loss=0.4792 | val_mcc=0.5217 | val_f1=0.6192 | val_auroc=0.8619

[Epoch 12] train_loss=0.1941 | val_loss=0.5347 | val_mcc=0.5097 | val_f1=0.6095 | val_auroc=0.8626

[Epoch 13] train_loss=0.1782 | val_loss=0.5611 | val_mcc=0.5237 | val_f1=0.6199 | val_auroc=0.8644
[EarlyStop] epoch=13 | best_val_mcc=0.5660
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5957 | F1=0.7032 | AUROC=0.8918 | AUPRC=0.7824
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5852 | F1=0.7695 | AUROC=0.8702 | AUPRC=0.8645
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4013 | F1=0.6774 | AUROC=0.7550 | AUPRC=0.7349
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5638 | F1=0.7488 | AUROC=0.8708 | AUPRC=0.8370
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 142.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5691 | F1=0.6942 | AUROC=0.8823 | AUPRC=0.7621
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5625 | F1=0.7831 | AUROC=0.8591 | AUPRC=0.8351
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3836 | F1=0.6953 | AUROC=0.7482 | AUPRC=0.7379
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5783 | F1=0.7757 | AUROC=0.8637 | AUPRC=0.8313
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 130.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5862 | F1=0.7046 | AUROC=0.8887 | AUPRC=0.7811
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5422 | F1=0.7636 | AUROC=0.8611 | AUPRC=0.8639
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3998 | F1=0.6979 | AUROC=0.7575 | AUPRC=0.7427
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5644 | F1=0.7660 | AUROC=0.8624 | AUPRC=0.8408
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 101.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5744 | F1=0.6956 | AUROC=0.8828 | AUPRC=0.7732
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5599 | F1=0.7697 | AUROC=0.8697 | AUPRC=0.8702
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3972 | F1=0.6893 | AUROC=0.7580 | AUPRC=0.7476
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5671 | F1=0.7638 | AUROC=0.8634 | AUPRC=0.8317
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 36.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5809 | F1=0.6993 | AUROC=0.8797 | AUPRC=0.7698
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5603 | F1=0.7683 | AUROC=0.8621 | AUPRC=0.8588
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3714 | F1=0.6794 | AUROC=0.7534 | AUPRC=0.7382
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5806 | F1=0.7706 | AUROC=0.8591 | AUPRC=0.8309
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']

[Epoch 01] train_loss=0.6304 | val_loss=0.4499 | val_mcc=0.4005 | val_f1=0.4958 | val_auroc=0.7713

[Epoch 02] train_loss=0.5578 | val_loss=0.5032 | val_mcc=0.4313 | val_f1=0.5480 | val_auroc=0.7910

[Epoch 03] train_loss=0.5310 | val_loss=0.4670 | val_mcc=0.4524 | val_f1=0.5608 | val_auroc=0.8025

[Epoch 04] train_loss=0.5075 | val_loss=0.4763 | val_mcc=0.4696 | val_f1=0.5778 | val_auroc=0.8156

[Epoch 05] train_loss=0.4847 | val_loss=0.4871 | val_mcc=0.4702 | val_f1=0.5795 | val_auroc=0.8267

[Epoch 06] train_loss=0.4581 | val_loss=0.4507 | val_mcc=0.4948 | val_f1=0.5980 | val_auroc=0.8389

[Epoch 07] train_loss=0.4258 | val_loss=0.4186 | val_mcc=0.5019 | val_f1=0.6016 | val_auroc=0.8443

[Epoch 08] train_loss=0.4006 | val_loss=0.4142 | val_mcc=0.5002 | val_f1=0.6004 | val_auroc=0.8459

[Epoch 09] train_loss=0.3718 | val_loss=0.4487 | val_mcc=0.4907 | val_f1=0.5950 | val_auroc=0.8475

[Epoch 10] train_loss=0.3436 | val_loss=0.5796 | val_mcc=0.4600 | val_f1=0.5680 | val_auroc=0.8479

[Epoch 11] train_loss=0.3194 | val_loss=0.5071 | val_mcc=0.4821 | val_f1=0.5884 | val_auroc=0.8482

[Epoch 12] train_loss=0.2812 | val_loss=0.5015 | val_mcc=0.4932 | val_f1=0.5973 | val_auroc=0.8502

[Epoch 13] train_loss=0.2657 | val_loss=0.5642 | val_mcc=0.4800 | val_f1=0.5859 | val_auroc=0.8473
[EarlyStop] epoch=13 | best_val_mcc=0.5019
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5291 | F1=0.6528 | AUROC=0.8482 | AUPRC=0.7219
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.4791 | F1=0.7105 | AUROC=0.8179 | AUPRC=0.8087
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3565 | F1=0.6510 | AUROC=0.7337 | AUPRC=0.7098
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4797 | F1=0.6936 | AUROC=0.8063 | AUPRC=0.7870
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.6310 | val_loss=0.6337 | val_mcc=0.3470 | val_f1=0.4860 | val_auroc=0.7719

[Epoch 02] train_loss=0.5612 | val_loss=0.5105 | val_mcc=0.4339 | val_f1=0.5492 | val_auroc=0.7876

[Epoch 03] train_loss=0.5342 | val_loss=0.4729 | val_mcc=0.4435 | val_f1=0.5535 | val_auroc=0.7987

[Epoch 04] train_loss=0.5112 | val_loss=0.4913 | val_mcc=0.4641 | val_f1=0.5732 | val_auroc=0.8118

[Epoch 05] train_loss=0.4931 | val_loss=0.4690 | val_mcc=0.4846 | val_f1=0.5890 | val_auroc=0.8198

[Epoch 06] train_loss=0.4630 | val_loss=0.4123 | val_mcc=0.4998 | val_f1=0.5943 | val_auroc=0.8284

[Epoch 07] train_loss=0.4425 | val_loss=0.4992 | val_mcc=0.4905 | val_f1=0.5951 | val_auroc=0.8325

[Epoch 08] train_loss=0.4194 | val_loss=0.4308 | val_mcc=0.5133 | val_f1=0.6102 | val_auroc=0.8352

[Epoch 09] train_loss=0.3932 | val_loss=0.4668 | val_mcc=0.4951 | val_f1=0.5981 | val_auroc=0.8366

[Epoch 10] train_loss=0.3697 | val_loss=0.5136 | val_mcc=0.4945 | val_f1=0.5980 | val_auroc=0.8367

[Epoch 11] train_loss=0.3452 | val_loss=0.5174 | val_mcc=0.4919 | val_f1=0.5962 | val_auroc=0.8365

[Epoch 12] train_loss=0.3293 | val_loss=0.5332 | val_mcc=0.4823 | val_f1=0.5889 | val_auroc=0.8311

[Epoch 13] train_loss=0.2923 | val_loss=0.5684 | val_mcc=0.4901 | val_f1=0.5948 | val_auroc=0.8358

[Epoch 14] train_loss=0.2784 | val_loss=0.5654 | val_mcc=0.4868 | val_f1=0.5923 | val_auroc=0.8331
[EarlyStop] epoch=14 | best_val_mcc=0.5133
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5343 | F1=0.6554 | AUROC=0.8415 | AUPRC=0.7072
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5053 | F1=0.7177 | AUROC=0.8164 | AUPRC=0.8150
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3561 | F1=0.6527 | AUROC=0.7146 | AUPRC=0.6971
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.4927 | F1=0.6992 | AUROC=0.8035 | AUPRC=0.7892
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.6272 | val_loss=0.5505 | val_mcc=0.3849 | val_f1=0.5153 | val_auroc=0.7743

[Epoch 02] train_loss=0.5539 | val_loss=0.4571 | val_mcc=0.4407 | val_f1=0.5495 | val_auroc=0.7993

[Epoch 03] train_loss=0.5275 | val_loss=0.4400 | val_mcc=0.4579 | val_f1=0.5630 | val_auroc=0.8161

[Epoch 04] train_loss=0.5025 | val_loss=0.4026 | val_mcc=0.4766 | val_f1=0.5725 | val_auroc=0.8274

[Epoch 05] train_loss=0.4813 | val_loss=0.4536 | val_mcc=0.4923 | val_f1=0.5962 | val_auroc=0.8388

[Epoch 06] train_loss=0.4548 | val_loss=0.4036 | val_mcc=0.5084 | val_f1=0.6062 | val_auroc=0.8468

[Epoch 07] train_loss=0.4278 | val_loss=0.4651 | val_mcc=0.4953 | val_f1=0.5988 | val_auroc=0.8516

[Epoch 08] train_loss=0.3997 | val_loss=0.4123 | val_mcc=0.5122 | val_f1=0.6096 | val_auroc=0.8509

[Epoch 09] train_loss=0.3658 | val_loss=0.4458 | val_mcc=0.5085 | val_f1=0.6085 | val_auroc=0.8517

[Epoch 10] train_loss=0.3421 | val_loss=0.5020 | val_mcc=0.5016 | val_f1=0.6037 | val_auroc=0.8468

[Epoch 11] train_loss=0.3091 | val_loss=0.4780 | val_mcc=0.5105 | val_f1=0.6090 | val_auroc=0.8456

[Epoch 12] train_loss=0.2886 | val_loss=0.5133 | val_mcc=0.5055 | val_f1=0.6048 | val_auroc=0.8395

[Epoch 13] train_loss=0.2509 | val_loss=0.6035 | val_mcc=0.4814 | val_f1=0.5876 | val_auroc=0.8378

[Epoch 14] train_loss=0.2293 | val_loss=0.6228 | val_mcc=0.4827 | val_f1=0.5892 | val_auroc=0.8348
[EarlyStop] epoch=14 | best_val_mcc=0.5122
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5360 | F1=0.6586 | AUROC=0.8533 | AUPRC=0.7235
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5156 | F1=0.7329 | AUROC=0.8308 | AUPRC=0.8202
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3444 | F1=0.6445 | AUROC=0.7308 | AUPRC=0.7044
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.4770 | F1=0.6915 | AUROC=0.8112 | AUPRC=0.7905
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.6248 | val_loss=0.5264 | val_mcc=0.3896 | val_f1=0.5160 | val_auroc=0.7714

[Epoch 02] train_loss=0.5543 | val_loss=0.4763 | val_mcc=0.4380 | val_f1=0.5486 | val_auroc=0.7950

[Epoch 03] train_loss=0.5242 | val_loss=0.5091 | val_mcc=0.4409 | val_f1=0.5570 | val_auroc=0.8084

[Epoch 04] train_loss=0.5039 | val_loss=0.4709 | val_mcc=0.4649 | val_f1=0.5740 | val_auroc=0.8196

[Epoch 05] train_loss=0.4801 | val_loss=0.4480 | val_mcc=0.4797 | val_f1=0.5846 | val_auroc=0.8306

[Epoch 06] train_loss=0.4500 | val_loss=0.4590 | val_mcc=0.4850 | val_f1=0.5907 | val_auroc=0.8351

[Epoch 07] train_loss=0.4196 | val_loss=0.4224 | val_mcc=0.5068 | val_f1=0.6067 | val_auroc=0.8475

[Epoch 08] train_loss=0.3893 | val_loss=0.4656 | val_mcc=0.4972 | val_f1=0.6003 | val_auroc=0.8445

[Epoch 09] train_loss=0.3567 | val_loss=0.4412 | val_mcc=0.5011 | val_f1=0.6028 | val_auroc=0.8476

[Epoch 10] train_loss=0.3252 | val_loss=0.4370 | val_mcc=0.4895 | val_f1=0.5923 | val_auroc=0.8453

[Epoch 11] train_loss=0.2992 | val_loss=0.5089 | val_mcc=0.4760 | val_f1=0.5839 | val_auroc=0.8427

[Epoch 12] train_loss=0.2582 | val_loss=0.5428 | val_mcc=0.4754 | val_f1=0.5832 | val_auroc=0.8438

[Epoch 13] train_loss=0.2417 | val_loss=0.5637 | val_mcc=0.4670 | val_f1=0.5767 | val_auroc=0.8413
[EarlyStop] epoch=13 | best_val_mcc=0.5068
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5275 | F1=0.6556 | AUROC=0.8515 | AUPRC=0.7260
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.4615 | F1=0.7112 | AUROC=0.8311 | AUPRC=0.8169
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3767 | F1=0.6661 | AUROC=0.7391 | AUPRC=0.7150
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.4905 | F1=0.7030 | AUROC=0.8115 | AUPRC=0.7895
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 251.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5043 | F1=0.6486 | AUROC=0.8429 | AUPRC=0.7074
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.4793 | F1=0.7344 | AUROC=0.8172 | AUPRC=0.8061
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3642 | F1=0.6869 | AUROC=0.7357 | AUPRC=0.7187
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4630 | F1=0.7070 | AUROC=0.7967 | AUPRC=0.7718
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 161.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.4813 | F1=0.6287 | AUROC=0.8355 | AUPRC=0.7012
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4693 | F1=0.7188 | AUROC=0.8205 | AUPRC=0.8079
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3297 | F1=0.6532 | AUROC=0.7230 | AUPRC=0.6950
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4293 | F1=0.6775 | AUROC=0.7887 | AUPRC=0.7580
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 74.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.4860 | F1=0.6313 | AUROC=0.8307 | AUPRC=0.6971
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4770 | F1=0.7278 | AUROC=0.8198 | AUPRC=0.8101
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3315 | F1=0.6516 | AUROC=0.7237 | AUPRC=0.7076
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4333 | F1=0.6786 | AUROC=0.7808 | AUPRC=0.7536
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 153.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.4916 | F1=0.6351 | AUROC=0.8318 | AUPRC=0.7011
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4920 | F1=0.7316 | AUROC=0.8125 | AUPRC=0.7997
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3377 | F1=0.6536 | AUROC=0.7312 | AUPRC=0.7035
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.4209 | F1=0.6724 | AUROC=0.7786 | AUPRC=0.7578
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.6439 | val_loss=0.5305 | val_mcc=0.4544 | val_f1=0.5608 | val_auroc=0.7885

[Epoch 02] train_loss=0.5443 | val_loss=0.4747 | val_mcc=0.4934 | val_f1=0.5893 | val_auroc=0.8030

[Epoch 03] train_loss=0.5223 | val_loss=0.4734 | val_mcc=0.5152 | val_f1=0.6083 | val_auroc=0.8090

[Epoch 04] train_loss=0.5119 | val_loss=0.4167 | val_mcc=0.5259 | val_f1=0.6003 | val_auroc=0.8053

[Epoch 05] train_loss=0.5005 | val_loss=0.4130 | val_mcc=0.5337 | val_f1=0.6114 | val_auroc=0.8166

[Epoch 06] train_loss=0.4889 | val_loss=0.3905 | val_mcc=0.5357 | val_f1=0.6071 | val_auroc=0.8210

[Epoch 07] train_loss=0.4818 | val_loss=0.4212 | val_mcc=0.5295 | val_f1=0.6172 | val_auroc=0.8238

[Epoch 08] train_loss=0.4721 | val_loss=0.4426 | val_mcc=0.5295 | val_f1=0.6217 | val_auroc=0.8293

[Epoch 09] train_loss=0.4623 | val_loss=0.4252 | val_mcc=0.5375 | val_f1=0.6278 | val_auroc=0.8335

[Epoch 10] train_loss=0.4544 | val_loss=0.4447 | val_mcc=0.5252 | val_f1=0.6211 | val_auroc=0.8387

[Epoch 11] train_loss=0.4454 | val_loss=0.3746 | val_mcc=0.5549 | val_f1=0.6374 | val_auroc=0.8340

[Epoch 12] train_loss=0.4390 | val_loss=0.4524 | val_mcc=0.5228 | val_f1=0.6195 | val_auroc=0.8379

[Epoch 13] train_loss=0.4278 | val_loss=0.4571 | val_mcc=0.5194 | val_f1=0.6171 | val_auroc=0.8401

[Epoch 14] train_loss=0.4159 | val_loss=0.4365 | val_mcc=0.5190 | val_f1=0.6167 | val_auroc=0.8419

[Epoch 15] train_loss=0.4068 | val_loss=0.4486 | val_mcc=0.5100 | val_f1=0.6101 | val_auroc=0.8440

[Epoch 16] train_loss=0.3926 | val_loss=0.4398 | val_mcc=0.5217 | val_f1=0.6191 | val_auroc=0.8479

[Epoch 17] train_loss=0.3862 | val_loss=0.4424 | val_mcc=0.5174 | val_f1=0.6158 | val_auroc=0.8488
[EarlyStop] epoch=17 | best_val_mcc=0.5549
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5780 | F1=0.6816 | AUROC=0.8384 | AUPRC=0.7487
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5376 | F1=0.7293 | AUROC=0.8191 | AUPRC=0.8330
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3602 | F1=0.6296 | AUROC=0.7281 | AUPRC=0.7360
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5201 | F1=0.7121 | AUROC=0.7975 | AUPRC=0.8004
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.6340 | val_loss=0.4675 | val_mcc=0.4818 | val_f1=0.5741 | val_auroc=0.7979

[Epoch 02] train_loss=0.5425 | val_loss=0.5648 | val_mcc=0.4256 | val_f1=0.5457 | val_auroc=0.7966

[Epoch 03] train_loss=0.5235 | val_loss=0.4844 | val_mcc=0.5170 | val_f1=0.6112 | val_auroc=0.8127

[Epoch 04] train_loss=0.5038 | val_loss=0.4345 | val_mcc=0.5326 | val_f1=0.6158 | val_auroc=0.8139

[Epoch 05] train_loss=0.4971 | val_loss=0.3909 | val_mcc=0.5372 | val_f1=0.6170 | val_auroc=0.8256

[Epoch 06] train_loss=0.4866 | val_loss=0.4452 | val_mcc=0.5401 | val_f1=0.6299 | val_auroc=0.8340

[Epoch 07] train_loss=0.4782 | val_loss=0.4486 | val_mcc=0.5312 | val_f1=0.6254 | val_auroc=0.8368

[Epoch 08] train_loss=0.4716 | val_loss=0.3977 | val_mcc=0.5501 | val_f1=0.6287 | val_auroc=0.8300

[Epoch 09] train_loss=0.4679 | val_loss=0.4541 | val_mcc=0.5101 | val_f1=0.6098 | val_auroc=0.8342

[Epoch 10] train_loss=0.4616 | val_loss=0.4696 | val_mcc=0.5256 | val_f1=0.6218 | val_auroc=0.8408

[Epoch 11] train_loss=0.4539 | val_loss=0.3953 | val_mcc=0.5472 | val_f1=0.6337 | val_auroc=0.8403

[Epoch 12] train_loss=0.4465 | val_loss=0.4035 | val_mcc=0.5393 | val_f1=0.6310 | val_auroc=0.8400

[Epoch 13] train_loss=0.4360 | val_loss=0.4387 | val_mcc=0.5188 | val_f1=0.6166 | val_auroc=0.8384

[Epoch 14] train_loss=0.4341 | val_loss=0.4720 | val_mcc=0.5065 | val_f1=0.6074 | val_auroc=0.8364
[EarlyStop] epoch=14 | best_val_mcc=0.5501
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5672 | F1=0.6678 | AUROC=0.8315 | AUPRC=0.7341
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.4990 | F1=0.6924 | AUROC=0.8134 | AUPRC=0.8250
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3623 | F1=0.6206 | AUROC=0.7146 | AUPRC=0.7205
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5158 | F1=0.7003 | AUROC=0.8021 | AUPRC=0.8017
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.6334 | val_loss=0.4683 | val_mcc=0.4657 | val_f1=0.5632 | val_auroc=0.7837

[Epoch 02] train_loss=0.5405 | val_loss=0.5032 | val_mcc=0.4972 | val_f1=0.5983 | val_auroc=0.8075

[Epoch 03] train_loss=0.5200 | val_loss=0.4223 | val_mcc=0.5251 | val_f1=0.6077 | val_auroc=0.8139

[Epoch 04] train_loss=0.5016 | val_loss=0.4155 | val_mcc=0.5285 | val_f1=0.6095 | val_auroc=0.8176

[Epoch 05] train_loss=0.4953 | val_loss=0.4092 | val_mcc=0.5351 | val_f1=0.6236 | val_auroc=0.8307

[Epoch 06] train_loss=0.4829 | val_loss=0.3951 | val_mcc=0.5417 | val_f1=0.6277 | val_auroc=0.8414

[Epoch 07] train_loss=0.4750 | val_loss=0.3711 | val_mcc=0.5435 | val_f1=0.6270 | val_auroc=0.8438

[Epoch 08] train_loss=0.4690 | val_loss=0.3832 | val_mcc=0.5382 | val_f1=0.6267 | val_auroc=0.8413

[Epoch 09] train_loss=0.4604 | val_loss=0.3919 | val_mcc=0.5444 | val_f1=0.6345 | val_auroc=0.8455

[Epoch 10] train_loss=0.4555 | val_loss=0.3704 | val_mcc=0.5497 | val_f1=0.6351 | val_auroc=0.8462

[Epoch 11] train_loss=0.4509 | val_loss=0.4228 | val_mcc=0.5279 | val_f1=0.6237 | val_auroc=0.8456

[Epoch 12] train_loss=0.4433 | val_loss=0.4362 | val_mcc=0.5175 | val_f1=0.6159 | val_auroc=0.8451

[Epoch 13] train_loss=0.4316 | val_loss=0.4073 | val_mcc=0.5293 | val_f1=0.6235 | val_auroc=0.8425

[Epoch 14] train_loss=0.4243 | val_loss=0.3801 | val_mcc=0.5426 | val_f1=0.6289 | val_auroc=0.8335

[Epoch 15] train_loss=0.4142 | val_loss=0.3846 | val_mcc=0.5376 | val_f1=0.6269 | val_auroc=0.8401

[Epoch 16] train_loss=0.4075 | val_loss=0.4208 | val_mcc=0.5262 | val_f1=0.6218 | val_auroc=0.8421
[EarlyStop] epoch=16 | best_val_mcc=0.5497
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5807 | F1=0.6871 | AUROC=0.8452 | AUPRC=0.7545
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5233 | F1=0.7264 | AUROC=0.8192 | AUPRC=0.8338
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3669 | F1=0.6409 | AUROC=0.7252 | AUPRC=0.7372
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5267 | F1=0.7178 | AUROC=0.8061 | AUPRC=0.8077
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.6400 | val_loss=0.4598 | val_mcc=0.4678 | val_f1=0.5477 | val_auroc=0.7898

[Epoch 02] train_loss=0.5409 | val_loss=0.4519 | val_mcc=0.5029 | val_f1=0.5896 | val_auroc=0.8056

[Epoch 03] train_loss=0.5222 | val_loss=0.5630 | val_mcc=0.4537 | val_f1=0.5669 | val_auroc=0.8080

[Epoch 04] train_loss=0.5051 | val_loss=0.4646 | val_mcc=0.5222 | val_f1=0.6122 | val_auroc=0.8140

[Epoch 05] train_loss=0.4909 | val_loss=0.4342 | val_mcc=0.5289 | val_f1=0.6169 | val_auroc=0.8205

[Epoch 06] train_loss=0.4806 | val_loss=0.4676 | val_mcc=0.5135 | val_f1=0.6117 | val_auroc=0.8264

[Epoch 07] train_loss=0.4741 | val_loss=0.4191 | val_mcc=0.5318 | val_f1=0.6238 | val_auroc=0.8332

[Epoch 08] train_loss=0.4626 | val_loss=0.4564 | val_mcc=0.5174 | val_f1=0.6156 | val_auroc=0.8349

[Epoch 09] train_loss=0.4564 | val_loss=0.4494 | val_mcc=0.5263 | val_f1=0.6219 | val_auroc=0.8351

[Epoch 10] train_loss=0.4459 | val_loss=0.3830 | val_mcc=0.5405 | val_f1=0.6245 | val_auroc=0.8307

[Epoch 11] train_loss=0.4394 | val_loss=0.3903 | val_mcc=0.5416 | val_f1=0.6328 | val_auroc=0.8423

[Epoch 12] train_loss=0.4288 | val_loss=0.3968 | val_mcc=0.5343 | val_f1=0.6271 | val_auroc=0.8434

[Epoch 13] train_loss=0.4194 | val_loss=0.3959 | val_mcc=0.5370 | val_f1=0.6289 | val_auroc=0.8432

[Epoch 14] train_loss=0.4092 | val_loss=0.4386 | val_mcc=0.5180 | val_f1=0.6163 | val_auroc=0.8468

[Epoch 15] train_loss=0.3967 | val_loss=0.4350 | val_mcc=0.5187 | val_f1=0.6168 | val_auroc=0.8467

[Epoch 16] train_loss=0.3828 | val_loss=0.5325 | val_mcc=0.4776 | val_f1=0.5829 | val_auroc=0.8454

[Epoch 17] train_loss=0.3738 | val_loss=0.4292 | val_mcc=0.5303 | val_f1=0.6255 | val_auroc=0.8422
[EarlyStop] epoch=17 | best_val_mcc=0.5416
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5667 | F1=0.6837 | AUROC=0.8447 | AUPRC=0.7543
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5416 | F1=0.7405 | AUROC=0.8237 | AUPRC=0.8353
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3491 | F1=0.6461 | AUROC=0.7297 | AUPRC=0.7366
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5207 | F1=0.7245 | AUROC=0.8055 | AUPRC=0.8045
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 287.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5474 | F1=0.6771 | AUROC=0.8708 | AUPRC=0.7756
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5407 | F1=0.7568 | AUROC=0.8500 | AUPRC=0.8617
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3414 | F1=0.6657 | AUROC=0.7389 | AUPRC=0.7415
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4864 | F1=0.7204 | AUROC=0.8297 | AUPRC=0.8200
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 115.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5491 | F1=0.6773 | AUROC=0.8552 | AUPRC=0.7661
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5068 | F1=0.7372 | AUROC=0.8336 | AUPRC=0.8452
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3720 | F1=0.6739 | AUROC=0.7358 | AUPRC=0.7429
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4952 | F1=0.7221 | AUROC=0.8153 | AUPRC=0.8143
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 78.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5425 | F1=0.6715 | AUROC=0.8464 | AUPRC=0.7525
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5225 | F1=0.7412 | AUROC=0.8232 | AUPRC=0.8348
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3510 | F1=0.6625 | AUROC=0.7314 | AUPRC=0.7307
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5000 | F1=0.7200 | AUROC=0.8100 | AUPRC=0.8027
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 82.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5257 | F1=0.6598 | AUROC=0.8413 | AUPRC=0.7479
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4887 | F1=0.7211 | AUROC=0.8151 | AUPRC=0.8328
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3363 | F1=0.6520 | AUROC=0.7232 | AUPRC=0.7336
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.4737 | F1=0.7042 | AUROC=0.7987 | AUPRC=0.8014
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.5884 | val_loss=0.4755 | val_mcc=0.4838 | val_f1=0.5899 | val_auroc=0.8249

[Epoch 02] train_loss=0.5007 | val_loss=0.4103 | val_mcc=0.5233 | val_f1=0.6188 | val_auroc=0.8432

[Epoch 03] train_loss=0.4602 | val_loss=0.4194 | val_mcc=0.5321 | val_f1=0.6272 | val_auroc=0.8533

[Epoch 04] train_loss=0.4230 | val_loss=0.3862 | val_mcc=0.5472 | val_f1=0.6384 | val_auroc=0.8624

[Epoch 05] train_loss=0.3785 | val_loss=0.3870 | val_mcc=0.5473 | val_f1=0.6383 | val_auroc=0.8657

[Epoch 06] train_loss=0.3343 | val_loss=0.4316 | val_mcc=0.5243 | val_f1=0.6210 | val_auroc=0.8635

[Epoch 07] train_loss=0.2809 | val_loss=0.4795 | val_mcc=0.5169 | val_f1=0.6138 | val_auroc=0.8646

[Epoch 08] train_loss=0.2296 | val_loss=0.5199 | val_mcc=0.4990 | val_f1=0.6004 | val_auroc=0.8584

[Epoch 09] train_loss=0.1916 | val_loss=0.5864 | val_mcc=0.4869 | val_f1=0.5897 | val_auroc=0.8571

[Epoch 10] train_loss=0.1345 | val_loss=0.5813 | val_mcc=0.5003 | val_f1=0.6017 | val_auroc=0.8564

[Epoch 11] train_loss=0.1100 | val_loss=0.6435 | val_mcc=0.4885 | val_f1=0.5915 | val_auroc=0.8547
[EarlyStop] epoch=11 | best_val_mcc=0.5473
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5745 | F1=0.6902 | AUROC=0.8776 | AUPRC=0.7681
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5654 | F1=0.7645 | AUROC=0.8712 | AUPRC=0.8711
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3934 | F1=0.6747 | AUROC=0.7522 | AUPRC=0.7279
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5523 | F1=0.7477 | AUROC=0.8576 | AUPRC=0.8315
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5940 | val_loss=0.4283 | val_mcc=0.5046 | val_f1=0.6006 | val_auroc=0.8261

[Epoch 02] train_loss=0.5053 | val_loss=0.4860 | val_mcc=0.5013 | val_f1=0.6029 | val_auroc=0.8434

[Epoch 03] train_loss=0.4684 | val_loss=0.4210 | val_mcc=0.5331 | val_f1=0.6279 | val_auroc=0.8528

[Epoch 04] train_loss=0.4307 | val_loss=0.4898 | val_mcc=0.5106 | val_f1=0.6090 | val_auroc=0.8552

[Epoch 05] train_loss=0.3868 | val_loss=0.4420 | val_mcc=0.5279 | val_f1=0.6239 | val_auroc=0.8549

[Epoch 06] train_loss=0.3445 | val_loss=0.4758 | val_mcc=0.5278 | val_f1=0.6235 | val_auroc=0.8575

[Epoch 07] train_loss=0.2835 | val_loss=0.4752 | val_mcc=0.5353 | val_f1=0.6293 | val_auroc=0.8499

[Epoch 08] train_loss=0.2408 | val_loss=0.6133 | val_mcc=0.4718 | val_f1=0.5793 | val_auroc=0.8351

[Epoch 09] train_loss=0.1998 | val_loss=0.5749 | val_mcc=0.4999 | val_f1=0.6021 | val_auroc=0.8336

[Epoch 10] train_loss=0.1560 | val_loss=0.7424 | val_mcc=0.4666 | val_f1=0.5761 | val_auroc=0.8330

[Epoch 11] train_loss=0.1353 | val_loss=0.7416 | val_mcc=0.4976 | val_f1=0.6004 | val_auroc=0.8372

[Epoch 12] train_loss=0.0971 | val_loss=0.7986 | val_mcc=0.4963 | val_f1=0.5995 | val_auroc=0.8347

[Epoch 13] train_loss=0.0816 | val_loss=0.8921 | val_mcc=0.4813 | val_f1=0.5875 | val_auroc=0.8324
[EarlyStop] epoch=13 | best_val_mcc=0.5353
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5796 | F1=0.6960 | AUROC=0.8642 | AUPRC=0.7266
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5487 | F1=0.7630 | AUROC=0.8573 | AUPRC=0.8393
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4012 | F1=0.6850 | AUROC=0.7352 | AUPRC=0.7147
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5482 | F1=0.7467 | AUROC=0.8449 | AUPRC=0.8023
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5934 | val_loss=0.4653 | val_mcc=0.4935 | val_f1=0.5972 | val_auroc=0.8295

[Epoch 02] train_loss=0.4994 | val_loss=0.3694 | val_mcc=0.5282 | val_f1=0.6180 | val_auroc=0.8490

[Epoch 03] train_loss=0.4664 | val_loss=0.3741 | val_mcc=0.5457 | val_f1=0.6341 | val_auroc=0.8579

[Epoch 04] train_loss=0.4293 | val_loss=0.4016 | val_mcc=0.5413 | val_f1=0.6339 | val_auroc=0.8638

[Epoch 05] train_loss=0.3912 | val_loss=0.3897 | val_mcc=0.5518 | val_f1=0.6420 | val_auroc=0.8652

[Epoch 06] train_loss=0.3395 | val_loss=0.4406 | val_mcc=0.5294 | val_f1=0.6251 | val_auroc=0.8625

[Epoch 07] train_loss=0.2799 | val_loss=0.4642 | val_mcc=0.5454 | val_f1=0.6372 | val_auroc=0.8634

[Epoch 08] train_loss=0.2344 | val_loss=0.5227 | val_mcc=0.5096 | val_f1=0.6095 | val_auroc=0.8522

[Epoch 09] train_loss=0.1822 | val_loss=0.5627 | val_mcc=0.5333 | val_f1=0.6280 | val_auroc=0.8566

[Epoch 10] train_loss=0.1290 | val_loss=0.6798 | val_mcc=0.4942 | val_f1=0.5976 | val_auroc=0.8463

[Epoch 11] train_loss=0.1072 | val_loss=0.7631 | val_mcc=0.4993 | val_f1=0.6012 | val_auroc=0.8487
[EarlyStop] epoch=11 | best_val_mcc=0.5518
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5983 | F1=0.7091 | AUROC=0.8787 | AUPRC=0.7665
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5900 | F1=0.7806 | AUROC=0.8710 | AUPRC=0.8682
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4172 | F1=0.6890 | AUROC=0.7534 | AUPRC=0.7244
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5868 | F1=0.7693 | AUROC=0.8616 | AUPRC=0.8286
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5899 | val_loss=0.4388 | val_mcc=0.4923 | val_f1=0.5936 | val_auroc=0.8259

[Epoch 02] train_loss=0.5056 | val_loss=0.4631 | val_mcc=0.5075 | val_f1=0.6081 | val_auroc=0.8432

[Epoch 03] train_loss=0.4605 | val_loss=0.4254 | val_mcc=0.5245 | val_f1=0.6212 | val_auroc=0.8518

[Epoch 04] train_loss=0.4185 | val_loss=0.4207 | val_mcc=0.5315 | val_f1=0.6268 | val_auroc=0.8607

[Epoch 05] train_loss=0.3735 | val_loss=0.4205 | val_mcc=0.5283 | val_f1=0.6242 | val_auroc=0.8607

[Epoch 06] train_loss=0.3202 | val_loss=0.4711 | val_mcc=0.5186 | val_f1=0.6158 | val_auroc=0.8639

[Epoch 07] train_loss=0.2693 | val_loss=0.4659 | val_mcc=0.5055 | val_f1=0.6065 | val_auroc=0.8559

[Epoch 08] train_loss=0.2136 | val_loss=0.5940 | val_mcc=0.4843 | val_f1=0.5885 | val_auroc=0.8545

[Epoch 09] train_loss=0.1532 | val_loss=0.5707 | val_mcc=0.4886 | val_f1=0.5930 | val_auroc=0.8514

[Epoch 10] train_loss=0.1249 | val_loss=0.6425 | val_mcc=0.4814 | val_f1=0.5867 | val_auroc=0.8510
[EarlyStop] epoch=10 | best_val_mcc=0.5315
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5808 | F1=0.6990 | AUROC=0.8728 | AUPRC=0.7670
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5629 | F1=0.7708 | AUROC=0.8612 | AUPRC=0.8608
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3763 | F1=0.6780 | AUROC=0.7484 | AUPRC=0.7278
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5847 | F1=0.7727 | AUROC=0.8569 | AUPRC=0.8331
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 194.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5790 | F1=0.7011 | AUROC=0.8874 | AUPRC=0.7721
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5838 | F1=0.7967 | AUROC=0.8699 | AUPRC=0.8589
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4017 | F1=0.7051 | AUROC=0.7524 | AUPRC=0.7353
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5646 | F1=0.7713 | AUROC=0.8638 | AUPRC=0.8404
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 176.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5677 | F1=0.6916 | AUROC=0.8763 | AUPRC=0.7631
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5248 | F1=0.7583 | AUROC=0.8556 | AUPRC=0.8552
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3895 | F1=0.6886 | AUROC=0.7559 | AUPRC=0.7389
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5518 | F1=0.7585 | AUROC=0.8590 | AUPRC=0.8321
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 121.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5774 | F1=0.6982 | AUROC=0.8744 | AUPRC=0.7627
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5791 | F1=0.7836 | AUROC=0.8624 | AUPRC=0.8537
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3896 | F1=0.6872 | AUROC=0.7487 | AUPRC=0.7256
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5619 | F1=0.7619 | AUROC=0.8578 | AUPRC=0.8317
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 39.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5783 | F1=0.6982 | AUROC=0.8761 | AUPRC=0.7663
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5519 | F1=0.7635 | AUROC=0.8630 | AUPRC=0.8632
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3759 | F1=0.6824 | AUROC=0.7491 | AUPRC=0.7316
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5617 | F1=0.7612 | AUROC=0.8573 | AUPRC=0.8345
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']

[Epoch 01] train_loss=0.6323 | val_loss=0.5505 | val_mcc=0.3727 | val_f1=0.5058 | val_auroc=0.7623

[Epoch 02] train_loss=0.5558 | val_loss=0.4731 | val_mcc=0.4306 | val_f1=0.5420 | val_auroc=0.7867

[Epoch 03] train_loss=0.5206 | val_loss=0.5655 | val_mcc=0.4036 | val_f1=0.5291 | val_auroc=0.7979

[Epoch 04] train_loss=0.4896 | val_loss=0.5369 | val_mcc=0.4198 | val_f1=0.5415 | val_auroc=0.8085

[Epoch 05] train_loss=0.4533 | val_loss=0.4745 | val_mcc=0.4566 | val_f1=0.5685 | val_auroc=0.8193

[Epoch 06] train_loss=0.4060 | val_loss=0.4481 | val_mcc=0.4722 | val_f1=0.5785 | val_auroc=0.8223

[Epoch 07] train_loss=0.3516 | val_loss=0.4688 | val_mcc=0.4618 | val_f1=0.5728 | val_auroc=0.8246

[Epoch 08] train_loss=0.2996 | val_loss=0.4488 | val_mcc=0.4631 | val_f1=0.5685 | val_auroc=0.8244

[Epoch 09] train_loss=0.2535 | val_loss=0.5741 | val_mcc=0.4353 | val_f1=0.5531 | val_auroc=0.8207

[Epoch 10] train_loss=0.2024 | val_loss=0.6226 | val_mcc=0.4262 | val_f1=0.5460 | val_auroc=0.8208

[Epoch 11] train_loss=0.1467 | val_loss=0.6270 | val_mcc=0.4388 | val_f1=0.5558 | val_auroc=0.8228

[Epoch 12] train_loss=0.1221 | val_loss=0.7053 | val_mcc=0.4316 | val_f1=0.5499 | val_auroc=0.8221
[EarlyStop] epoch=12 | best_val_mcc=0.4722
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.4787 | F1=0.6174 | AUROC=0.8125 | AUPRC=0.6871
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.4730 | F1=0.7083 | AUROC=0.8158 | AUPRC=0.8090
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3300 | F1=0.6404 | AUROC=0.7229 | AUPRC=0.6993
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4434 | F1=0.6715 | AUROC=0.7810 | AUPRC=0.7680
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.6267 | val_loss=0.4510 | val_mcc=0.4073 | val_f1=0.5052 | val_auroc=0.7743

[Epoch 02] train_loss=0.5582 | val_loss=0.5255 | val_mcc=0.4165 | val_f1=0.5377 | val_auroc=0.7895

[Epoch 03] train_loss=0.5271 | val_loss=0.4804 | val_mcc=0.4453 | val_f1=0.5568 | val_auroc=0.8033

[Epoch 04] train_loss=0.4995 | val_loss=0.4623 | val_mcc=0.4646 | val_f1=0.5713 | val_auroc=0.8137

[Epoch 05] train_loss=0.4586 | val_loss=0.6321 | val_mcc=0.3884 | val_f1=0.5152 | val_auroc=0.8119

[Epoch 06] train_loss=0.4148 | val_loss=0.4943 | val_mcc=0.4301 | val_f1=0.5485 | val_auroc=0.8001

[Epoch 07] train_loss=0.3623 | val_loss=0.4774 | val_mcc=0.4489 | val_f1=0.5597 | val_auroc=0.8054

[Epoch 08] train_loss=0.3069 | val_loss=0.5806 | val_mcc=0.4080 | val_f1=0.5326 | val_auroc=0.8003

[Epoch 09] train_loss=0.2449 | val_loss=0.8553 | val_mcc=0.3608 | val_f1=0.4942 | val_auroc=0.7946

[Epoch 10] train_loss=0.2125 | val_loss=0.8579 | val_mcc=0.3696 | val_f1=0.5020 | val_auroc=0.7917
[EarlyStop] epoch=10 | best_val_mcc=0.4646
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.4907 | F1=0.6240 | AUROC=0.8086 | AUPRC=0.6777
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.4769 | F1=0.7075 | AUROC=0.8027 | AUPRC=0.7965
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3457 | F1=0.6393 | AUROC=0.7064 | AUPRC=0.6855
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.4342 | F1=0.6612 | AUROC=0.7737 | AUPRC=0.7513
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.6249 | val_loss=0.4762 | val_mcc=0.4042 | val_f1=0.5197 | val_auroc=0.7758

[Epoch 02] train_loss=0.5500 | val_loss=0.4109 | val_mcc=0.4321 | val_f1=0.5181 | val_auroc=0.7927

[Epoch 03] train_loss=0.5179 | val_loss=0.4632 | val_mcc=0.4497 | val_f1=0.5598 | val_auroc=0.8123

[Epoch 04] train_loss=0.4872 | val_loss=0.4519 | val_mcc=0.4674 | val_f1=0.5736 | val_auroc=0.8220

[Epoch 05] train_loss=0.4526 | val_loss=0.4803 | val_mcc=0.4610 | val_f1=0.5721 | val_auroc=0.8263

[Epoch 06] train_loss=0.3981 | val_loss=0.4570 | val_mcc=0.4651 | val_f1=0.5743 | val_auroc=0.8256

[Epoch 07] train_loss=0.3417 | val_loss=0.4820 | val_mcc=0.4631 | val_f1=0.5729 | val_auroc=0.8253

[Epoch 08] train_loss=0.2843 | val_loss=0.5249 | val_mcc=0.4497 | val_f1=0.5632 | val_auroc=0.8193

[Epoch 09] train_loss=0.2154 | val_loss=0.6116 | val_mcc=0.4433 | val_f1=0.5592 | val_auroc=0.8198

[Epoch 10] train_loss=0.1812 | val_loss=0.6320 | val_mcc=0.4502 | val_f1=0.5618 | val_auroc=0.8153
[EarlyStop] epoch=10 | best_val_mcc=0.4674
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.4971 | F1=0.6307 | AUROC=0.8140 | AUPRC=0.6936
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.4760 | F1=0.7094 | AUROC=0.8085 | AUPRC=0.8032
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3605 | F1=0.6492 | AUROC=0.7184 | AUPRC=0.6988
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.4323 | F1=0.6640 | AUROC=0.7735 | AUPRC=0.7591
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.6306 | val_loss=0.5131 | val_mcc=0.3794 | val_f1=0.5055 | val_auroc=0.7629

[Epoch 02] train_loss=0.5539 | val_loss=0.4572 | val_mcc=0.4366 | val_f1=0.5424 | val_auroc=0.7876

[Epoch 03] train_loss=0.5140 | val_loss=0.4749 | val_mcc=0.4419 | val_f1=0.5542 | val_auroc=0.8003

[Epoch 04] train_loss=0.4798 | val_loss=0.4861 | val_mcc=0.4431 | val_f1=0.5581 | val_auroc=0.8070

[Epoch 05] train_loss=0.4368 | val_loss=0.5015 | val_mcc=0.4325 | val_f1=0.5511 | val_auroc=0.8156

[Epoch 06] train_loss=0.3801 | val_loss=0.4724 | val_mcc=0.4507 | val_f1=0.5640 | val_auroc=0.8191

[Epoch 07] train_loss=0.3272 | val_loss=0.5006 | val_mcc=0.4530 | val_f1=0.5665 | val_auroc=0.8252

[Epoch 08] train_loss=0.2674 | val_loss=0.5228 | val_mcc=0.4421 | val_f1=0.5581 | val_auroc=0.8172

[Epoch 09] train_loss=0.2208 | val_loss=0.5940 | val_mcc=0.4178 | val_f1=0.5400 | val_auroc=0.8140

[Epoch 10] train_loss=0.1663 | val_loss=0.6470 | val_mcc=0.4246 | val_f1=0.5452 | val_auroc=0.8164

[Epoch 11] train_loss=0.1305 | val_loss=0.6977 | val_mcc=0.4133 | val_f1=0.5366 | val_auroc=0.8104

[Epoch 12] train_loss=0.0928 | val_loss=0.7627 | val_mcc=0.4130 | val_f1=0.5363 | val_auroc=0.8177

[Epoch 13] train_loss=0.0788 | val_loss=0.7725 | val_mcc=0.4248 | val_f1=0.5453 | val_auroc=0.8191
[EarlyStop] epoch=13 | best_val_mcc=0.4530
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.4642 | F1=0.6168 | AUROC=0.8081 | AUPRC=0.6754
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.4914 | F1=0.7340 | AUROC=0.8169 | AUPRC=0.8048
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3118 | F1=0.6428 | AUROC=0.7007 | AUPRC=0.6754
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.4263 | F1=0.6833 | AUROC=0.7800 | AUPRC=0.7603
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 173.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.4844 | F1=0.6344 | AUROC=0.8418 | AUPRC=0.7092
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5050 | F1=0.7514 | AUROC=0.8325 | AUPRC=0.8239
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3414 | F1=0.6712 | AUROC=0.7286 | AUPRC=0.7107
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4369 | F1=0.6926 | AUROC=0.7977 | AUPRC=0.7750
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 124.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.4796 | F1=0.6282 | AUROC=0.8285 | AUPRC=0.6976
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4453 | F1=0.7137 | AUROC=0.8095 | AUPRC=0.8074
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3210 | F1=0.6458 | AUROC=0.7318 | AUPRC=0.7060
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4283 | F1=0.6805 | AUROC=0.7796 | AUPRC=0.7586
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 48.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.4730 | F1=0.6221 | AUROC=0.8161 | AUPRC=0.6821
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4660 | F1=0.7194 | AUROC=0.8059 | AUPRC=0.7953
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3562 | F1=0.6598 | AUROC=0.7224 | AUPRC=0.7009
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4184 | F1=0.6729 | AUROC=0.7687 | AUPRC=0.7450
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 64.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.4666 | F1=0.6168 | AUROC=0.8113 | AUPRC=0.6787
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4606 | F1=0.7147 | AUROC=0.7983 | AUPRC=0.7962
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3425 | F1=0.6541 | AUROC=0.7150 | AUPRC=0.6891
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.4028 | F1=0.6604 | AUROC=0.7614 | AUPRC=0.7360
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.6309 | val_loss=0.5012 | val_mcc=0.4590 | val_f1=0.5627 | val_auroc=0.7893

[Epoch 02] train_loss=0.5337 | val_loss=0.4737 | val_mcc=0.4926 | val_f1=0.5888 | val_auroc=0.8040

[Epoch 03] train_loss=0.5089 | val_loss=0.4490 | val_mcc=0.5084 | val_f1=0.5993 | val_auroc=0.8072

[Epoch 04] train_loss=0.4836 | val_loss=0.4156 | val_mcc=0.5137 | val_f1=0.5979 | val_auroc=0.8071

[Epoch 05] train_loss=0.4535 | val_loss=0.4184 | val_mcc=0.5000 | val_f1=0.5917 | val_auroc=0.8043

[Epoch 06] train_loss=0.4198 | val_loss=0.4252 | val_mcc=0.4874 | val_f1=0.5862 | val_auroc=0.8036

[Epoch 07] train_loss=0.3835 | val_loss=0.5027 | val_mcc=0.4370 | val_f1=0.5544 | val_auroc=0.8011

[Epoch 08] train_loss=0.3369 | val_loss=0.5174 | val_mcc=0.4297 | val_f1=0.5489 | val_auroc=0.8023

[Epoch 09] train_loss=0.2886 | val_loss=0.4817 | val_mcc=0.4498 | val_f1=0.5620 | val_auroc=0.7987

[Epoch 10] train_loss=0.2580 | val_loss=0.5066 | val_mcc=0.4346 | val_f1=0.5500 | val_auroc=0.7923
[EarlyStop] epoch=10 | best_val_mcc=0.5137
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5487 | F1=0.6530 | AUROC=0.8089 | AUPRC=0.7132
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5162 | F1=0.6983 | AUROC=0.7820 | AUPRC=0.8039
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3524 | F1=0.6121 | AUROC=0.7168 | AUPRC=0.7162
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4844 | F1=0.6769 | AUROC=0.7810 | AUPRC=0.7876
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.6505 | val_loss=0.4140 | val_mcc=0.4742 | val_f1=0.5385 | val_auroc=0.7924

[Epoch 02] train_loss=0.5382 | val_loss=0.5547 | val_mcc=0.4540 | val_f1=0.5672 | val_auroc=0.8069

[Epoch 03] train_loss=0.5125 | val_loss=0.5445 | val_mcc=0.4381 | val_f1=0.5553 | val_auroc=0.8038

[Epoch 04] train_loss=0.4901 | val_loss=0.3952 | val_mcc=0.5091 | val_f1=0.5844 | val_auroc=0.8005

[Epoch 05] train_loss=0.4567 | val_loss=0.4270 | val_mcc=0.5053 | val_f1=0.6015 | val_auroc=0.8164

[Epoch 06] train_loss=0.4222 | val_loss=0.5802 | val_mcc=0.4049 | val_f1=0.5285 | val_auroc=0.8109

[Epoch 07] train_loss=0.3840 | val_loss=0.6162 | val_mcc=0.3759 | val_f1=0.5070 | val_auroc=0.7959

[Epoch 08] train_loss=0.3385 | val_loss=0.6283 | val_mcc=0.3886 | val_f1=0.5166 | val_auroc=0.7989

[Epoch 09] train_loss=0.2849 | val_loss=0.6282 | val_mcc=0.3903 | val_f1=0.5195 | val_auroc=0.7900

[Epoch 10] train_loss=0.2547 | val_loss=0.6673 | val_mcc=0.3807 | val_f1=0.5125 | val_auroc=0.7814
[EarlyStop] epoch=10 | best_val_mcc=0.5091
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5334 | F1=0.6323 | AUROC=0.7995 | AUPRC=0.6979
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.4942 | F1=0.6725 | AUROC=0.7851 | AUPRC=0.8057
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3538 | F1=0.5936 | AUROC=0.7032 | AUPRC=0.7004
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.4770 | F1=0.6566 | AUROC=0.7643 | AUPRC=0.7756
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.6456 | val_loss=0.4185 | val_mcc=0.4700 | val_f1=0.5385 | val_auroc=0.7883

[Epoch 02] train_loss=0.5363 | val_loss=0.4279 | val_mcc=0.5097 | val_f1=0.5921 | val_auroc=0.8037

[Epoch 03] train_loss=0.5112 | val_loss=0.3916 | val_mcc=0.5242 | val_f1=0.5924 | val_auroc=0.8088

[Epoch 04] train_loss=0.4855 | val_loss=0.5663 | val_mcc=0.4379 | val_f1=0.5540 | val_auroc=0.8157

[Epoch 05] train_loss=0.4612 | val_loss=0.5010 | val_mcc=0.4601 | val_f1=0.5717 | val_auroc=0.8135

[Epoch 06] train_loss=0.4199 | val_loss=0.4470 | val_mcc=0.4757 | val_f1=0.5821 | val_auroc=0.8092

[Epoch 07] train_loss=0.3856 | val_loss=0.4609 | val_mcc=0.4600 | val_f1=0.5701 | val_auroc=0.8068

[Epoch 08] train_loss=0.3177 | val_loss=0.5439 | val_mcc=0.4353 | val_f1=0.5532 | val_auroc=0.8029

[Epoch 09] train_loss=0.2851 | val_loss=0.6013 | val_mcc=0.4134 | val_f1=0.5367 | val_auroc=0.7927
[EarlyStop] epoch=9 | best_val_mcc=0.5242
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5427 | F1=0.6321 | AUROC=0.8116 | AUPRC=0.7151
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.4890 | F1=0.6631 | AUROC=0.7884 | AUPRC=0.8083
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3397 | F1=0.5733 | AUROC=0.7145 | AUPRC=0.7120
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.4826 | F1=0.6572 | AUROC=0.7844 | AUPRC=0.7904
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.6536 | val_loss=0.5233 | val_mcc=0.4410 | val_f1=0.5474 | val_auroc=0.7782

[Epoch 02] train_loss=0.5353 | val_loss=0.4478 | val_mcc=0.4938 | val_f1=0.5808 | val_auroc=0.7993

[Epoch 03] train_loss=0.5009 | val_loss=0.4275 | val_mcc=0.5138 | val_f1=0.5958 | val_auroc=0.8025

[Epoch 04] train_loss=0.4796 | val_loss=0.4074 | val_mcc=0.5201 | val_f1=0.5979 | val_auroc=0.8081

[Epoch 05] train_loss=0.4463 | val_loss=0.4617 | val_mcc=0.4757 | val_f1=0.5807 | val_auroc=0.8059

[Epoch 06] train_loss=0.4097 | val_loss=0.4301 | val_mcc=0.4797 | val_f1=0.5812 | val_auroc=0.8042

[Epoch 07] train_loss=0.3708 | val_loss=0.4842 | val_mcc=0.4358 | val_f1=0.5522 | val_auroc=0.7984

[Epoch 08] train_loss=0.3273 | val_loss=0.5382 | val_mcc=0.4156 | val_f1=0.5384 | val_auroc=0.7938

[Epoch 09] train_loss=0.2773 | val_loss=0.4905 | val_mcc=0.4407 | val_f1=0.5539 | val_auroc=0.7933

[Epoch 10] train_loss=0.2497 | val_loss=0.5610 | val_mcc=0.4156 | val_f1=0.5382 | val_auroc=0.7915
[EarlyStop] epoch=10 | best_val_mcc=0.5201
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5399 | F1=0.6426 | AUROC=0.8071 | AUPRC=0.7122
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.4668 | F1=0.6621 | AUROC=0.7852 | AUPRC=0.8071
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3465 | F1=0.5957 | AUROC=0.7100 | AUPRC=0.7160
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.4807 | F1=0.6684 | AUROC=0.7816 | AUPRC=0.7872
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 167.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5498 | F1=0.6792 | AUROC=0.8694 | AUPRC=0.7711
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5371 | F1=0.7578 | AUROC=0.8559 | AUPRC=0.8604
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3505 | F1=0.6677 | AUROC=0.7481 | AUPRC=0.7540
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4894 | F1=0.7227 | AUROC=0.8300 | AUPRC=0.8212
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 42.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5397 | F1=0.6682 | AUROC=0.8456 | AUPRC=0.7507
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5255 | F1=0.7423 | AUROC=0.8243 | AUPRC=0.8366
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3363 | F1=0.6520 | AUROC=0.7304 | AUPRC=0.7361
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4779 | F1=0.7072 | AUROC=0.8021 | AUPRC=0.8091
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 46.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5383 | F1=0.6680 | AUROC=0.8374 | AUPRC=0.7435
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4972 | F1=0.7262 | AUROC=0.8172 | AUPRC=0.8340
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3289 | F1=0.6472 | AUROC=0.7232 | AUPRC=0.7235
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4669 | F1=0.7020 | AUROC=0.7939 | AUPRC=0.7981
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 41.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5146 | F1=0.6491 | AUROC=0.8267 | AUPRC=0.7296
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4753 | F1=0.7112 | AUROC=0.8080 | AUPRC=0.8153
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3221 | F1=0.6303 | AUROC=0.7138 | AUPRC=0.7226
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.4596 | F1=0.6898 | AUROC=0.7887 | AUPRC=0.7924
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.7081 | val_loss=0.6977 | val_mcc=0.0384 | val_f1=0.2934 | val_auroc=0.5359

[Epoch 02] train_loss=0.6884 | val_loss=0.6658 | val_mcc=0.0420 | val_f1=0.2698 | val_auroc=0.5368

[Epoch 03] train_loss=0.6757 | val_loss=0.7350 | val_mcc=0.0352 | val_f1=0.3075 | val_auroc=0.5290

[Epoch 04] train_loss=0.6613 | val_loss=0.7053 | val_mcc=0.0288 | val_f1=0.2867 | val_auroc=0.5274

[Epoch 05] train_loss=0.6420 | val_loss=0.6957 | val_mcc=0.0365 | val_f1=0.2819 | val_auroc=0.5319

[Epoch 06] train_loss=0.6161 | val_loss=0.7223 | val_mcc=0.0275 | val_f1=0.2818 | val_auroc=0.5230

[Epoch 07] train_loss=0.5731 | val_loss=0.8123 | val_mcc=0.0173 | val_f1=0.2950 | val_auroc=0.5160

[Epoch 08] train_loss=0.5435 | val_loss=0.7622 | val_mcc=0.0301 | val_f1=0.2854 | val_auroc=0.5222
[EarlyStop] epoch=8 | best_val_mcc=0.0420
[Test] train3__val_cls_dna_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.0416 | F1=0.3248 | AUROC=0.5235 | AUPRC=0.2900
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.0645 | F1=0.4318 | AUROC=0.5324 | AUPRC=0.5251
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=-0.0034 | F1=0.4181 | AUROC=0.4987 | AUPRC=0.5022
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.0410 | F1=0.4076 | AUROC=0.5165 | AUPRC=0.4709
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 12.
[Test] train3__val_cls_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.0463 | F1=0.3539 | AUROC=0.5273 | AUPRC=0.3024
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.0748 | F1=0.4914 | AUROC=0.5466 | AUPRC=0.5443
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.0260 | F1=0.4641 | AUROC=0.5061 | AUPRC=0.5058
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.0800 | F1=0.4874 | AUROC=0.5365 | AUPRC=0.4890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 9.
[Test] train3__val_cls_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.0316 | F1=0.3479 | AUROC=0.5255 | AUPRC=0.2883
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.0314 | F1=0.4654 | AUROC=0.5175 | AUPRC=0.5053
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.0443 | F1=0.4757 | AUROC=0.5251 | AUPRC=0.5130
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.0269 | F1=0.4641 | AUROC=0.5129 | AUPRC=0.4731
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.5774 | val_loss=0.4221 | val_mcc=0.5043 | val_f1=0.6020 | val_auroc=0.8337

[Epoch 02] train_loss=0.5072 | val_loss=0.4872 | val_mcc=0.5013 | val_f1=0.6018 | val_auroc=0.8495

[Epoch 03] train_loss=0.4756 | val_loss=0.4430 | val_mcc=0.5222 | val_f1=0.6191 | val_auroc=0.8598

[Epoch 04] train_loss=0.4508 | val_loss=0.4154 | val_mcc=0.5438 | val_f1=0.6359 | val_auroc=0.8694

[Epoch 05] train_loss=0.4292 | val_loss=0.3811 | val_mcc=0.5567 | val_f1=0.6461 | val_auroc=0.8743

[Epoch 06] train_loss=0.4049 | val_loss=0.4197 | val_mcc=0.5450 | val_f1=0.6363 | val_auroc=0.8783

[Epoch 07] train_loss=0.3839 | val_loss=0.4044 | val_mcc=0.5560 | val_f1=0.6454 | val_auroc=0.8778

[Epoch 08] train_loss=0.3574 | val_loss=0.4048 | val_mcc=0.5537 | val_f1=0.6438 | val_auroc=0.8798

[Epoch 09] train_loss=0.3370 | val_loss=0.4089 | val_mcc=0.5514 | val_f1=0.6419 | val_auroc=0.8785

[Epoch 10] train_loss=0.3025 | val_loss=0.3828 | val_mcc=0.5670 | val_f1=0.6541 | val_auroc=0.8797

[Epoch 11] train_loss=0.2853 | val_loss=0.4250 | val_mcc=0.5563 | val_f1=0.6458 | val_auroc=0.8783

[Epoch 12] train_loss=0.2682 | val_loss=0.4284 | val_mcc=0.5514 | val_f1=0.6421 | val_auroc=0.8753

[Epoch 13] train_loss=0.2557 | val_loss=0.4603 | val_mcc=0.5412 | val_f1=0.6339 | val_auroc=0.8741

[Epoch 14] train_loss=0.2374 | val_loss=0.4647 | val_mcc=0.5363 | val_f1=0.6303 | val_auroc=0.8719

[Epoch 15] train_loss=0.2209 | val_loss=0.4878 | val_mcc=0.5328 | val_f1=0.6270 | val_auroc=0.8693

[Epoch 16] train_loss=0.2140 | val_loss=0.4930 | val_mcc=0.5326 | val_f1=0.6270 | val_auroc=0.8686
[EarlyStop] epoch=16 | best_val_mcc=0.5670
[Test] train3__val_cls_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6071 | F1=0.7161 | AUROC=0.8949 | AUPRC=0.7836
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5752 | F1=0.7741 | AUROC=0.8764 | AUPRC=0.8699
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4127 | F1=0.6942 | AUROC=0.7624 | AUPRC=0.7360
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5399 | F1=0.7413 | AUROC=0.8679 | AUPRC=0.8395
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 171.
[Test] train3__val_cls_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5766 | F1=0.6993 | AUROC=0.8860 | AUPRC=0.7710
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5765 | F1=0.7893 | AUROC=0.8706 | AUPRC=0.8619
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3870 | F1=0.6999 | AUROC=0.7503 | AUPRC=0.7289
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5597 | F1=0.7666 | AUROC=0.8616 | AUPRC=0.8278
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 98.
[Test] train3__val_cls_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5931 | F1=0.7092 | AUROC=0.8901 | AUPRC=0.7830
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5765 | F1=0.7806 | AUROC=0.8722 | AUPRC=0.8589
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4030 | F1=0.6957 | AUROC=0.7582 | AUPRC=0.7517
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5748 | F1=0.7705 | AUROC=0.8633 | AUPRC=0.8362
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4987 | val_loss=0.6028 | val_mcc=0.4251 | val_f1=0.5311 | val_auroc=0.8681

[Epoch 02] train_loss=0.4281 | val_loss=0.7278 | val_mcc=0.2912 | val_f1=0.4295 | val_auroc=0.8549

[Epoch 03] train_loss=0.4034 | val_loss=0.4868 | val_mcc=0.5020 | val_f1=0.6027 | val_auroc=0.8537

[Epoch 04] train_loss=0.3803 | val_loss=0.5657 | val_mcc=0.4166 | val_f1=0.5321 | val_auroc=0.8378

[Epoch 05] train_loss=0.3558 | val_loss=0.5243 | val_mcc=0.4538 | val_f1=0.5629 | val_auroc=0.8446

[Epoch 06] train_loss=0.3195 | val_loss=0.6511 | val_mcc=0.3565 | val_f1=0.4862 | val_auroc=0.8199

[Epoch 07] train_loss=0.2830 | val_loss=0.5355 | val_mcc=0.4181 | val_f1=0.5387 | val_auroc=0.8194

[Epoch 08] train_loss=0.2277 | val_loss=0.7028 | val_mcc=0.3464 | val_f1=0.4810 | val_auroc=0.8087

[Epoch 09] train_loss=0.2000 | val_loss=0.6842 | val_mcc=0.3755 | val_f1=0.5025 | val_auroc=0.8145
[EarlyStop] epoch=9 | best_val_mcc=0.5020
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5469 | F1=0.6789 | AUROC=0.8590 | AUPRC=0.7596
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5476 | F1=0.7692 | AUROC=0.8464 | AUPRC=0.8513
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3894 | F1=0.6910 | AUROC=0.7489 | AUPRC=0.7406
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5397 | F1=0.7524 | AUROC=0.8387 | AUPRC=0.8206
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5033 | val_loss=0.3949 | val_mcc=0.5838 | val_f1=0.6581 | val_auroc=0.8660

[Epoch 02] train_loss=0.4346 | val_loss=0.3570 | val_mcc=0.5288 | val_f1=0.5578 | val_auroc=0.8693

[Epoch 03] train_loss=0.4142 | val_loss=0.3670 | val_mcc=0.5514 | val_f1=0.6049 | val_auroc=0.8573

[Epoch 04] train_loss=0.3981 | val_loss=0.4475 | val_mcc=0.5452 | val_f1=0.6372 | val_auroc=0.8551

[Epoch 05] train_loss=0.3676 | val_loss=0.3684 | val_mcc=0.5223 | val_f1=0.5950 | val_auroc=0.8366

[Epoch 06] train_loss=0.3221 | val_loss=0.4549 | val_mcc=0.4799 | val_f1=0.5865 | val_auroc=0.8249

[Epoch 07] train_loss=0.2901 | val_loss=0.4183 | val_mcc=0.4840 | val_f1=0.5800 | val_auroc=0.8205
[EarlyStop] epoch=7 | best_val_mcc=0.5838
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6391 | F1=0.7238 | AUROC=0.8809 | AUPRC=0.7916
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5961 | F1=0.7618 | AUROC=0.8595 | AUPRC=0.8669
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3999 | F1=0.6489 | AUROC=0.7510 | AUPRC=0.7512
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5658 | F1=0.7370 | AUROC=0.8550 | AUPRC=0.8251
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5120 | val_loss=0.3932 | val_mcc=0.5543 | val_f1=0.6365 | val_auroc=0.8607

[Epoch 02] train_loss=0.4345 | val_loss=0.3812 | val_mcc=0.5505 | val_f1=0.6241 | val_auroc=0.8600

[Epoch 03] train_loss=0.4133 | val_loss=0.4134 | val_mcc=0.5356 | val_f1=0.6270 | val_auroc=0.8548

[Epoch 04] train_loss=0.3934 | val_loss=0.3668 | val_mcc=0.5277 | val_f1=0.5991 | val_auroc=0.8444

[Epoch 05] train_loss=0.3643 | val_loss=0.3613 | val_mcc=0.5033 | val_f1=0.5660 | val_auroc=0.8369

[Epoch 06] train_loss=0.3182 | val_loss=0.4163 | val_mcc=0.4528 | val_f1=0.5558 | val_auroc=0.8143

[Epoch 07] train_loss=0.2871 | val_loss=0.4641 | val_mcc=0.4612 | val_f1=0.5718 | val_auroc=0.8177
[EarlyStop] epoch=7 | best_val_mcc=0.5543
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5958 | F1=0.6914 | AUROC=0.8720 | AUPRC=0.7626
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5414 | F1=0.7249 | AUROC=0.8597 | AUPRC=0.8580
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3805 | F1=0.6361 | AUROC=0.7456 | AUPRC=0.7350
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5428 | F1=0.7205 | AUROC=0.8497 | AUPRC=0.8193
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5046 | val_loss=0.5352 | val_mcc=0.4731 | val_f1=0.5753 | val_auroc=0.8619

[Epoch 02] train_loss=0.4289 | val_loss=0.6624 | val_mcc=0.3615 | val_f1=0.4790 | val_auroc=0.8600

[Epoch 03] train_loss=0.4065 | val_loss=0.5343 | val_mcc=0.4505 | val_f1=0.5580 | val_auroc=0.8529

[Epoch 04] train_loss=0.3787 | val_loss=0.5616 | val_mcc=0.4306 | val_f1=0.5417 | val_auroc=0.8495

[Epoch 05] train_loss=0.3490 | val_loss=0.5467 | val_mcc=0.4267 | val_f1=0.5418 | val_auroc=0.8399

[Epoch 06] train_loss=0.3060 | val_loss=0.5940 | val_mcc=0.3910 | val_f1=0.5143 | val_auroc=0.8285

[Epoch 07] train_loss=0.2746 | val_loss=0.6507 | val_mcc=0.3705 | val_f1=0.4979 | val_auroc=0.8183
[EarlyStop] epoch=7 | best_val_mcc=0.4731
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5437 | F1=0.6771 | AUROC=0.8757 | AUPRC=0.7783
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5410 | F1=0.7819 | AUROC=0.8617 | AUPRC=0.8733
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3714 | F1=0.7045 | AUROC=0.7423 | AUPRC=0.7301
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5391 | F1=0.7643 | AUROC=0.8554 | AUPRC=0.8287
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 163.
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6577 | F1=0.7536 | AUROC=0.9126 | AUPRC=0.8379
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6077 | F1=0.7977 | AUROC=0.8896 | AUPRC=0.8882
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4330 | F1=0.7110 | AUROC=0.7812 | AUPRC=0.7695
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6197 | F1=0.7941 | AUROC=0.8898 | AUPRC=0.8804
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 19.
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.4587 | F1=0.5814 | AUROC=0.8079 | AUPRC=0.6426
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4184 | F1=0.6345 | AUROC=0.8004 | AUPRC=0.7749
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3043 | F1=0.5604 | AUROC=0.7031 | AUPRC=0.6963
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4216 | F1=0.6262 | AUROC=0.7791 | AUPRC=0.7293
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 0.
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.0106 | F1=0.4230 | AUROC=0.7318 | AUPRC=0.5592
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.0486 | F1=0.6554 | AUROC=0.7325 | AUPRC=0.7156
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.0466 | F1=0.6517 | AUROC=0.6689 | AUPRC=0.6527
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.0495 | F1=0.6178 | AUROC=0.7231 | AUPRC=0.6924
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 21.
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5298 | F1=0.6680 | AUROC=0.8488 | AUPRC=0.7216
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5018 | F1=0.7582 | AUROC=0.8185 | AUPRC=0.8140
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3586 | F1=0.6871 | AUROC=0.7306 | AUPRC=0.7151
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.4115 | val_loss=0.2504 | val_mcc=0.7103 | val_f1=0.7664 | val_auroc=0.9530

[Epoch 02] train_loss=0.3078 | val_loss=0.2303 | val_mcc=0.7302 | val_f1=0.7829 | val_auroc=0.9548

[Epoch 03] train_loss=0.2818 | val_loss=0.2394 | val_mcc=0.7215 | val_f1=0.7754 | val_auroc=0.9549

[Epoch 04] train_loss=0.2608 | val_loss=0.2481 | val_mcc=0.7169 | val_f1=0.7711 | val_auroc=0.9565

[Epoch 05] train_loss=0.2315 | val_loss=0.2516 | val_mcc=0.7110 | val_f1=0.7663 | val_auroc=0.9551

[Epoch 06] train_loss=0.2065 | val_loss=0.2836 | val_mcc=0.6941 | val_f1=0.7515 | val_auroc=0.9533

[Epoch 07] train_loss=0.1722 | val_loss=0.2491 | val_mcc=0.7138 | val_f1=0.7699 | val_auroc=0.9539

[Epoch 08] train_loss=0.1506 | val_loss=0.2672 | val_mcc=0.6994 | val_f1=0.7581 | val_auroc=0.9516
[EarlyStop] epoch=8 | best_val_mcc=0.7302
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7507 | F1=0.8203 | AUROC=0.9518 | AUPRC=0.8961
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8049 | F1=0.8939 | AUROC=0.9731 | AUPRC=0.9732
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4020 | F1=0.7131 | AUROC=0.7564 | AUPRC=0.7453
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5420 | F1=0.7693 | AUROC=0.8767 | AUPRC=0.8433
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4244 | val_loss=0.3170 | val_mcc=0.6714 | val_f1=0.7284 | val_auroc=0.9535

[Epoch 02] train_loss=0.3166 | val_loss=0.2056 | val_mcc=0.7387 | val_f1=0.7873 | val_auroc=0.9560

[Epoch 03] train_loss=0.2927 | val_loss=0.2184 | val_mcc=0.7339 | val_f1=0.7860 | val_auroc=0.9571

[Epoch 04] train_loss=0.2723 | val_loss=0.3110 | val_mcc=0.6793 | val_f1=0.7364 | val_auroc=0.9542

[Epoch 05] train_loss=0.2491 | val_loss=0.2348 | val_mcc=0.7209 | val_f1=0.7754 | val_auroc=0.9562

[Epoch 06] train_loss=0.2144 | val_loss=0.2491 | val_mcc=0.7138 | val_f1=0.7701 | val_auroc=0.9506

[Epoch 07] train_loss=0.1732 | val_loss=0.3036 | val_mcc=0.6865 | val_f1=0.7467 | val_auroc=0.9473

[Epoch 08] train_loss=0.1484 | val_loss=0.2926 | val_mcc=0.6950 | val_f1=0.7548 | val_auroc=0.9457
[EarlyStop] epoch=8 | best_val_mcc=0.7387
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7541 | F1=0.8158 | AUROC=0.9510 | AUPRC=0.8913
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7663 | F1=0.8585 | AUROC=0.9715 | AUPRC=0.9713
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3544 | F1=0.6609 | AUROC=0.7493 | AUPRC=0.7404
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5761 | F1=0.7831 | AUROC=0.8729 | AUPRC=0.8329
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4174 | val_loss=0.2242 | val_mcc=0.7333 | val_f1=0.7851 | val_auroc=0.9529

[Epoch 02] train_loss=0.3120 | val_loss=0.2385 | val_mcc=0.7189 | val_f1=0.7738 | val_auroc=0.9535

[Epoch 03] train_loss=0.2865 | val_loss=0.2383 | val_mcc=0.7214 | val_f1=0.7758 | val_auroc=0.9539

[Epoch 04] train_loss=0.2671 | val_loss=0.2298 | val_mcc=0.7268 | val_f1=0.7802 | val_auroc=0.9558

[Epoch 05] train_loss=0.2420 | val_loss=0.2143 | val_mcc=0.7304 | val_f1=0.7823 | val_auroc=0.9555

[Epoch 06] train_loss=0.2041 | val_loss=0.2508 | val_mcc=0.7130 | val_f1=0.7691 | val_auroc=0.9521

[Epoch 07] train_loss=0.1791 | val_loss=0.2619 | val_mcc=0.7102 | val_f1=0.7672 | val_auroc=0.9485
[EarlyStop] epoch=7 | best_val_mcc=0.7333
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7597 | F1=0.8249 | AUROC=0.9511 | AUPRC=0.8914
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8007 | F1=0.8899 | AUROC=0.9690 | AUPRC=0.9700
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3998 | F1=0.6970 | AUROC=0.7633 | AUPRC=0.7514
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5905 | F1=0.7911 | AUROC=0.8836 | AUPRC=0.8482
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4089 | val_loss=0.2537 | val_mcc=0.7157 | val_f1=0.7700 | val_auroc=0.9546

[Epoch 02] train_loss=0.3050 | val_loss=0.2668 | val_mcc=0.7055 | val_f1=0.7604 | val_auroc=0.9559

[Epoch 03] train_loss=0.2812 | val_loss=0.2422 | val_mcc=0.7232 | val_f1=0.7762 | val_auroc=0.9577

[Epoch 04] train_loss=0.2558 | val_loss=0.2236 | val_mcc=0.7258 | val_f1=0.7796 | val_auroc=0.9566

[Epoch 05] train_loss=0.2297 | val_loss=0.2307 | val_mcc=0.7248 | val_f1=0.7787 | val_auroc=0.9559

[Epoch 06] train_loss=0.1936 | val_loss=0.2756 | val_mcc=0.7037 | val_f1=0.7593 | val_auroc=0.9558

[Epoch 07] train_loss=0.1589 | val_loss=0.2856 | val_mcc=0.7049 | val_f1=0.7613 | val_auroc=0.9539

[Epoch 08] train_loss=0.1243 | val_loss=0.2737 | val_mcc=0.7249 | val_f1=0.7789 | val_auroc=0.9522

[Epoch 09] train_loss=0.0903 | val_loss=0.2911 | val_mcc=0.7088 | val_f1=0.7660 | val_auroc=0.9500

[Epoch 10] train_loss=0.0760 | val_loss=0.3340 | val_mcc=0.6972 | val_f1=0.7556 | val_auroc=0.9488
[EarlyStop] epoch=10 | best_val_mcc=0.7258
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7421 | F1=0.8138 | AUROC=0.9501 | AUPRC=0.8954
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8111 | F1=0.8967 | AUROC=0.9719 | AUPRC=0.9718
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3750 | F1=0.6945 | AUROC=0.7535 | AUPRC=0.7388
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5571 | F1=0.7760 | AUROC=0.8715 | AUPRC=0.8319
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 170.
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7666 | F1=0.8319 | AUROC=0.9620 | AUPRC=0.9129
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8735 | F1=0.9333 | AUROC=0.9867 | AUPRC=0.9874
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4099 | F1=0.7251 | AUROC=0.7601 | AUPRC=0.7350
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5600 | F1=0.7770 | AUROC=0.9000 | AUPRC=0.8834
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 109.
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7671 | F1=0.8323 | AUROC=0.9577 | AUPRC=0.9078
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8230 | F1=0.9058 | AUROC=0.9760 | AUPRC=0.9764
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4179 | F1=0.7252 | AUROC=0.7652 | AUPRC=0.7494
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5700 | F1=0.7817 | AUROC=0.8897 | AUPRC=0.8585
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 87.
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7618 | F1=0.8285 | AUROC=0.9566 | AUPRC=0.9069
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8314 | F1=0.9104 | AUROC=0.9780 | AUPRC=0.9786
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4334 | F1=0.7305 | AUROC=0.7691 | AUPRC=0.7562
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5650 | F1=0.7795 | AUROC=0.8900 | AUPRC=0.8624
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 81.
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7572 | F1=0.8253 | AUROC=0.9551 | AUPRC=0.9054
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8314 | F1=0.9104 | AUROC=0.9774 | AUPRC=0.9776
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4060 | F1=0.7200 | AUROC=0.7630 | AUPRC=0.7449
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.4104 | val_loss=0.2798 | val_mcc=0.7010 | val_f1=0.7599 | val_auroc=0.9455

[Epoch 02] train_loss=0.2862 | val_loss=0.2560 | val_mcc=0.7157 | val_f1=0.7713 | val_auroc=0.9482

[Epoch 03] train_loss=0.2639 | val_loss=0.2567 | val_mcc=0.7025 | val_f1=0.7601 | val_auroc=0.9450

[Epoch 04] train_loss=0.2424 | val_loss=0.2774 | val_mcc=0.6817 | val_f1=0.7446 | val_auroc=0.9388

[Epoch 05] train_loss=0.2208 | val_loss=0.3333 | val_mcc=0.6352 | val_f1=0.7029 | val_auroc=0.9357

[Epoch 06] train_loss=0.2029 | val_loss=0.3231 | val_mcc=0.6295 | val_f1=0.7008 | val_auroc=0.9286

[Epoch 07] train_loss=0.1731 | val_loss=0.2892 | val_mcc=0.6370 | val_f1=0.7092 | val_auroc=0.9236

[Epoch 08] train_loss=0.1532 | val_loss=0.2989 | val_mcc=0.6291 | val_f1=0.7029 | val_auroc=0.9206
[EarlyStop] epoch=8 | best_val_mcc=0.7157
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7397 | F1=0.8106 | AUROC=0.9473 | AUPRC=0.8876
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7685 | F1=0.8700 | AUROC=0.9650 | AUPRC=0.9650
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4074 | F1=0.6982 | AUROC=0.7701 | AUPRC=0.7609
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5780 | F1=0.7839 | AUROC=0.8817 | AUPRC=0.8598
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4228 | val_loss=0.2728 | val_mcc=0.7228 | val_f1=0.7772 | val_auroc=0.9533

[Epoch 02] train_loss=0.3003 | val_loss=0.2561 | val_mcc=0.7256 | val_f1=0.7793 | val_auroc=0.9564

[Epoch 03] train_loss=0.2767 | val_loss=0.2344 | val_mcc=0.7287 | val_f1=0.7800 | val_auroc=0.9548

[Epoch 04] train_loss=0.2623 | val_loss=0.2408 | val_mcc=0.7208 | val_f1=0.7723 | val_auroc=0.9517

[Epoch 05] train_loss=0.2441 | val_loss=0.2267 | val_mcc=0.6950 | val_f1=0.7387 | val_auroc=0.9493

[Epoch 06] train_loss=0.2153 | val_loss=0.2594 | val_mcc=0.6617 | val_f1=0.7259 | val_auroc=0.9317

[Epoch 07] train_loss=0.1885 | val_loss=0.2753 | val_mcc=0.6450 | val_f1=0.7078 | val_auroc=0.9231

[Epoch 08] train_loss=0.1483 | val_loss=0.3327 | val_mcc=0.6215 | val_f1=0.6968 | val_auroc=0.9158

[Epoch 09] train_loss=0.1275 | val_loss=0.3300 | val_mcc=0.6254 | val_f1=0.6974 | val_auroc=0.9112
[EarlyStop] epoch=9 | best_val_mcc=0.7287
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7496 | F1=0.8148 | AUROC=0.9516 | AUPRC=0.8936
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7537 | F1=0.8558 | AUROC=0.9620 | AUPRC=0.9575
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4409 | F1=0.7032 | AUROC=0.7725 | AUPRC=0.7590
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6178 | F1=0.8006 | AUROC=0.8869 | AUPRC=0.8584
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3975 | val_loss=0.2399 | val_mcc=0.6665 | val_f1=0.6999 | val_auroc=0.9501

[Epoch 02] train_loss=0.2887 | val_loss=0.2329 | val_mcc=0.7363 | val_f1=0.7824 | val_auroc=0.9539

[Epoch 03] train_loss=0.2715 | val_loss=0.2249 | val_mcc=0.7069 | val_f1=0.7461 | val_auroc=0.9509

[Epoch 04] train_loss=0.2557 | val_loss=0.2338 | val_mcc=0.6880 | val_f1=0.7257 | val_auroc=0.9470

[Epoch 05] train_loss=0.2389 | val_loss=0.2426 | val_mcc=0.6705 | val_f1=0.7087 | val_auroc=0.9407

[Epoch 06] train_loss=0.2077 | val_loss=0.2656 | val_mcc=0.6740 | val_f1=0.7381 | val_auroc=0.9321

[Epoch 07] train_loss=0.1693 | val_loss=0.2779 | val_mcc=0.6521 | val_f1=0.7108 | val_auroc=0.9219

[Epoch 08] train_loss=0.1460 | val_loss=0.3104 | val_mcc=0.6310 | val_f1=0.7037 | val_auroc=0.9152
[EarlyStop] epoch=8 | best_val_mcc=0.7363
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7477 | F1=0.8093 | AUROC=0.9525 | AUPRC=0.8983
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7437 | F1=0.8485 | AUROC=0.9639 | AUPRC=0.9621
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4361 | F1=0.6911 | AUROC=0.7769 | AUPRC=0.7619
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6309 | F1=0.8054 | AUROC=0.8920 | AUPRC=0.8572
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4054 | val_loss=0.2992 | val_mcc=0.6591 | val_f1=0.7264 | val_auroc=0.9359

[Epoch 02] train_loss=0.2942 | val_loss=0.2547 | val_mcc=0.6961 | val_f1=0.7508 | val_auroc=0.9458

[Epoch 03] train_loss=0.2696 | val_loss=0.2665 | val_mcc=0.6854 | val_f1=0.7467 | val_auroc=0.9412

[Epoch 04] train_loss=0.2477 | val_loss=0.2632 | val_mcc=0.6729 | val_f1=0.7350 | val_auroc=0.9363

[Epoch 05] train_loss=0.2220 | val_loss=0.2759 | val_mcc=0.6504 | val_f1=0.7178 | val_auroc=0.9242

[Epoch 06] train_loss=0.1965 | val_loss=0.2976 | val_mcc=0.6183 | val_f1=0.6926 | val_auroc=0.9113

[Epoch 07] train_loss=0.1619 | val_loss=0.2949 | val_mcc=0.6192 | val_f1=0.6932 | val_auroc=0.9132

[Epoch 08] train_loss=0.1425 | val_loss=0.3177 | val_mcc=0.6158 | val_f1=0.6921 | val_auroc=0.9089
[EarlyStop] epoch=8 | best_val_mcc=0.6961
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7110 | F1=0.7836 | AUROC=0.9414 | AUPRC=0.8697
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7005 | F1=0.8243 | AUROC=0.9508 | AUPRC=0.9483
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4387 | F1=0.6937 | AUROC=0.7865 | AUPRC=0.7715
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6134 | F1=0.7918 | AUROC=0.8863 | AUPRC=0.8624
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 137.
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7823 | F1=0.8431 | AUROC=0.9672 | AUPRC=0.9285
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8527 | F1=0.9238 | AUROC=0.9833 | AUPRC=0.9843
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4603 | F1=0.7449 | AUROC=0.7846 | AUPRC=0.7703
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5770 | F1=0.7848 | AUROC=0.9059 | AUPRC=0.8883
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 173.
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6417 | F1=0.7430 | AUROC=0.9305 | AUPRC=0.8581
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7364 | F1=0.8696 | AUROC=0.9508 | AUPRC=0.9507
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3641 | F1=0.7098 | AUROC=0.7560 | AUPRC=0.7408
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5155 | F1=0.7577 | AUROC=0.8705 | AUPRC=0.8499
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 205.
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6876 | F1=0.7529 | AUROC=0.9299 | AUPRC=0.8627
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6564 | F1=0.7747 | AUROC=0.9458 | AUPRC=0.9491
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3820 | F1=0.6292 | AUROC=0.7479 | AUPRC=0.7427
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5843 | F1=0.7631 | AUROC=0.8730 | AUPRC=0.8548
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 186.
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7115 | F1=0.7925 | AUROC=0.9398 | AUPRC=0.8720
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7464 | F1=0.8649 | AUROC=0.9545 | AUPRC=0.9544
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3943 | F1=0.7025 | AUROC=0.7571 | AUPRC=0.7384
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.4012 | val_loss=0.3033 | val_mcc=0.7117 | val_f1=0.7680 | val_auroc=0.9545

[Epoch 02] train_loss=0.2948 | val_loss=0.2441 | val_mcc=0.7356 | val_f1=0.7867 | val_auroc=0.9585

[Epoch 03] train_loss=0.2854 | val_loss=0.2342 | val_mcc=0.7417 | val_f1=0.7912 | val_auroc=0.9606

[Epoch 04] train_loss=0.2806 | val_loss=0.2292 | val_mcc=0.7440 | val_f1=0.7922 | val_auroc=0.9620

[Epoch 05] train_loss=0.2770 | val_loss=0.2239 | val_mcc=0.7388 | val_f1=0.7868 | val_auroc=0.9627

[Epoch 06] train_loss=0.2735 | val_loss=0.2302 | val_mcc=0.7442 | val_f1=0.7937 | val_auroc=0.9627

[Epoch 07] train_loss=0.2722 | val_loss=0.2229 | val_mcc=0.7473 | val_f1=0.7954 | val_auroc=0.9641

[Epoch 08] train_loss=0.2698 | val_loss=0.2237 | val_mcc=0.7492 | val_f1=0.7972 | val_auroc=0.9641

[Epoch 09] train_loss=0.2696 | val_loss=0.2190 | val_mcc=0.7495 | val_f1=0.7953 | val_auroc=0.9646

[Epoch 10] train_loss=0.2683 | val_loss=0.2162 | val_mcc=0.7496 | val_f1=0.7948 | val_auroc=0.9648

[Epoch 11] train_loss=0.2668 | val_loss=0.2230 | val_mcc=0.7552 | val_f1=0.8012 | val_auroc=0.9653

[Epoch 12] train_loss=0.2639 | val_loss=0.2227 | val_mcc=0.7553 | val_f1=0.8006 | val_auroc=0.9651

[Epoch 13] train_loss=0.2644 | val_loss=0.2163 | val_mcc=0.7525 | val_f1=0.7956 | val_auroc=0.9654

[Epoch 14] train_loss=0.2638 | val_loss=0.2206 | val_mcc=0.7564 | val_f1=0.7997 | val_auroc=0.9651

[Epoch 15] train_loss=0.2628 | val_loss=0.2210 | val_mcc=0.7515 | val_f1=0.7972 | val_auroc=0.9648

[Epoch 16] train_loss=0.2632 | val_loss=0.2218 | val_mcc=0.7560 | val_f1=0.8019 | val_auroc=0.9656

[Epoch 17] train_loss=0.2633 | val_loss=0.2247 | val_mcc=0.7586 | val_f1=0.8049 | val_auroc=0.9657

[Epoch 18] train_loss=0.2639 | val_loss=0.2256 | val_mcc=0.7606 | val_f1=0.8065 | val_auroc=0.9658

[Epoch 19] train_loss=0.2610 | val_loss=0.2292 | val_mcc=0.7582 | val_f1=0.8050 | val_auroc=0.9652

[Epoch 20] train_loss=0.2607 | val_loss=0.2253 | val_mcc=0.7611 | val_f1=0.8071 | val_auroc=0.9657

[Epoch 21] train_loss=0.2594 | val_loss=0.2262 | val_mcc=0.7642 | val_f1=0.8098 | val_auroc=0.9660

[Epoch 22] train_loss=0.2595 | val_loss=0.2252 | val_mcc=0.7598 | val_f1=0.8058 | val_auroc=0.9653

[Epoch 23] train_loss=0.2587 | val_loss=0.2272 | val_mcc=0.7669 | val_f1=0.8118 | val_auroc=0.9661

[Epoch 24] train_loss=0.2599 | val_loss=0.2245 | val_mcc=0.7647 | val_f1=0.8098 | val_auroc=0.9658

[Epoch 25] train_loss=0.2587 | val_loss=0.2235 | val_mcc=0.7672 | val_f1=0.8113 | val_auroc=0.9662

[Epoch 26] train_loss=0.2571 | val_loss=0.2284 | val_mcc=0.7682 | val_f1=0.8122 | val_auroc=0.9661

[Epoch 27] train_loss=0.2573 | val_loss=0.2290 | val_mcc=0.7682 | val_f1=0.8126 | val_auroc=0.9662

[Epoch 28] train_loss=0.2560 | val_loss=0.2251 | val_mcc=0.7723 | val_f1=0.8152 | val_auroc=0.9665

[Epoch 29] train_loss=0.2546 | val_loss=0.2245 | val_mcc=0.7698 | val_f1=0.8135 | val_auroc=0.9662

[Epoch 30] train_loss=0.2573 | val_loss=0.2289 | val_mcc=0.7682 | val_f1=0.8126 | val_auroc=0.9664
[Test] train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7876 | F1=0.8422 | AUROC=0.9616 | AUPRC=0.9203
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7929 | F1=0.8816 | AUROC=0.9719 | AUPRC=0.9731
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4290 | F1=0.7040 | AUROC=0.7699 | AUPRC=0.7649
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6136 | F1=0.8011 | AUROC=0.8936 | AUPRC=0.8776
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 74.
[Test] train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7864 | F1=0.8460 | AUROC=0.9665 | AUPRC=0.9244
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8531 | F1=0.9233 | AUROC=0.9795 | AUPRC=0.9816
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4487 | F1=0.7380 | AUROC=0.7862 | AUPRC=0.7772
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5813 | F1=0.7867 | AUROC=0.9057 | AUPRC=0.8893
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 121.
[Test] train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6171 | F1=0.7226 | AUROC=0.9338 | AUPRC=0.8588
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7401 | F1=0.8722 | AUROC=0.9495 | AUPRC=0.9500
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3513 | F1=0.7119 | AUROC=0.7509 | AUPRC=0.7356
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.3915 | F1=0.7075 | AUROC=0.8456 | AUPRC=0.8256

================================================================================
[*] POOLING: MEAN
================================================================================
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.5278 | val_loss=0.4110 | val_mcc=0.5336 | val_f1=0.6280 | val_auroc=0.8550

[Epoch 02] train_loss=0.4605 | val_loss=0.3609 | val_mcc=0.5668 | val_f1=0.6524 | val_auroc=0.8689

[Epoch 03] train_loss=0.4224 | val_loss=0.3675 | val_mcc=0.5702 | val_f1=0.6567 | val_auroc=0.8801

[Epoch 04] train_loss=0.3889 | val_loss=0.4321 | val_mcc=0.5479 | val_f1=0.6375 | val_auroc=0.8865

[Epoch 05] train_loss=0.3503 | val_loss=0.3804 | val_mcc=0.5584 | val_f1=0.6476 | val_auroc=0.8839

[Epoch 06] train_loss=0.3146 | val_loss=0.4327 | val_mcc=0.5431 | val_f1=0.6345 | val_auroc=0.8834

[Epoch 07] train_loss=0.2659 | val_loss=0.4457 | val_mcc=0.5373 | val_f1=0.6307 | val_auroc=0.8789

[Epoch 08] train_loss=0.2101 | val_loss=0.4835 | val_mcc=0.5243 | val_f1=0.6201 | val_auroc=0.8759

[Epoch 09] train_loss=0.1789 | val_loss=0.5664 | val_mcc=0.5056 | val_f1=0.6029 | val_auroc=0.8741
[EarlyStop] epoch=9 | best_val_mcc=0.5702
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6251 | F1=0.7290 | AUROC=0.8898 | AUPRC=0.8045
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5681 | F1=0.7758 | AUROC=0.8766 | AUPRC=0.8781
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4447 | F1=0.7024 | AUROC=0.7732 | AUPRC=0.7554
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5872 | F1=0.7728 | AUROC=0.8645 | AUPRC=0.8496
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5327 | val_loss=0.3856 | val_mcc=0.5539 | val_f1=0.6420 | val_auroc=0.8562

[Epoch 02] train_loss=0.4666 | val_loss=0.4017 | val_mcc=0.5540 | val_f1=0.6441 | val_auroc=0.8675

[Epoch 03] train_loss=0.4313 | val_loss=0.4027 | val_mcc=0.5692 | val_f1=0.6559 | val_auroc=0.8804

[Epoch 04] train_loss=0.3995 | val_loss=0.4435 | val_mcc=0.5496 | val_f1=0.6383 | val_auroc=0.8841

[Epoch 05] train_loss=0.3595 | val_loss=0.3966 | val_mcc=0.5678 | val_f1=0.6549 | val_auroc=0.8859

[Epoch 06] train_loss=0.3133 | val_loss=0.4710 | val_mcc=0.5216 | val_f1=0.6173 | val_auroc=0.8715

[Epoch 07] train_loss=0.2709 | val_loss=0.4570 | val_mcc=0.5342 | val_f1=0.6285 | val_auroc=0.8702

[Epoch 08] train_loss=0.1966 | val_loss=0.5387 | val_mcc=0.5320 | val_f1=0.6269 | val_auroc=0.8624

[Epoch 09] train_loss=0.1510 | val_loss=0.7471 | val_mcc=0.4782 | val_f1=0.5820 | val_auroc=0.8558
[EarlyStop] epoch=9 | best_val_mcc=0.5692
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6191 | F1=0.7269 | AUROC=0.8885 | AUPRC=0.7985
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5960 | F1=0.7936 | AUROC=0.8785 | AUPRC=0.8767
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4382 | F1=0.7077 | AUROC=0.7730 | AUPRC=0.7660
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5806 | F1=0.7741 | AUROC=0.8643 | AUPRC=0.8431
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5274 | val_loss=0.3964 | val_mcc=0.5418 | val_f1=0.6344 | val_auroc=0.8598

[Epoch 02] train_loss=0.4572 | val_loss=0.3764 | val_mcc=0.5659 | val_f1=0.6531 | val_auroc=0.8751

[Epoch 03] train_loss=0.4260 | val_loss=0.3315 | val_mcc=0.5827 | val_f1=0.6623 | val_auroc=0.8808

[Epoch 04] train_loss=0.3944 | val_loss=0.3385 | val_mcc=0.5937 | val_f1=0.6741 | val_auroc=0.8891

[Epoch 05] train_loss=0.3578 | val_loss=0.3680 | val_mcc=0.5788 | val_f1=0.6634 | val_auroc=0.8888

[Epoch 06] train_loss=0.3129 | val_loss=0.3739 | val_mcc=0.5706 | val_f1=0.6556 | val_auroc=0.8829

[Epoch 07] train_loss=0.2656 | val_loss=0.4616 | val_mcc=0.5523 | val_f1=0.6428 | val_auroc=0.8783

[Epoch 08] train_loss=0.2127 | val_loss=0.5195 | val_mcc=0.5463 | val_f1=0.6381 | val_auroc=0.8730

[Epoch 09] train_loss=0.1469 | val_loss=0.5717 | val_mcc=0.5376 | val_f1=0.6313 | val_auroc=0.8636

[Epoch 10] train_loss=0.1123 | val_loss=0.6835 | val_mcc=0.5099 | val_f1=0.6097 | val_auroc=0.8577
[EarlyStop] epoch=10 | best_val_mcc=0.5937
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6343 | F1=0.7322 | AUROC=0.9020 | AUPRC=0.8075
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5485 | F1=0.7546 | AUROC=0.8784 | AUPRC=0.8665
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4450 | F1=0.6965 | AUROC=0.7829 | AUPRC=0.7677
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5717 | F1=0.7589 | AUROC=0.8717 | AUPRC=0.8475
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5329 | val_loss=0.4505 | val_mcc=0.5198 | val_f1=0.6174 | val_auroc=0.8565

[Epoch 02] train_loss=0.4621 | val_loss=0.3913 | val_mcc=0.5541 | val_f1=0.6442 | val_auroc=0.8685

[Epoch 03] train_loss=0.4258 | val_loss=0.3875 | val_mcc=0.5666 | val_f1=0.6540 | val_auroc=0.8795

[Epoch 04] train_loss=0.3917 | val_loss=0.3946 | val_mcc=0.5603 | val_f1=0.6485 | val_auroc=0.8863

[Epoch 05] train_loss=0.3562 | val_loss=0.3398 | val_mcc=0.5862 | val_f1=0.6678 | val_auroc=0.8866

[Epoch 06] train_loss=0.3096 | val_loss=0.4258 | val_mcc=0.5451 | val_f1=0.6366 | val_auroc=0.8809

[Epoch 07] train_loss=0.2578 | val_loss=0.4688 | val_mcc=0.5315 | val_f1=0.6257 | val_auroc=0.8762

[Epoch 08] train_loss=0.2026 | val_loss=0.5588 | val_mcc=0.5014 | val_f1=0.6001 | val_auroc=0.8711

[Epoch 09] train_loss=0.1523 | val_loss=0.5577 | val_mcc=0.5099 | val_f1=0.6090 | val_auroc=0.8650

[Epoch 10] train_loss=0.0960 | val_loss=0.5901 | val_mcc=0.5265 | val_f1=0.6224 | val_auroc=0.8672

[Epoch 11] train_loss=0.0704 | val_loss=0.6143 | val_mcc=0.5167 | val_f1=0.6152 | val_auroc=0.8620
[EarlyStop] epoch=11 | best_val_mcc=0.5862
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6315 | F1=0.7303 | AUROC=0.8978 | AUPRC=0.8063
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5466 | F1=0.7512 | AUROC=0.8758 | AUPRC=0.8700
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4288 | F1=0.6863 | AUROC=0.7767 | AUPRC=0.7608
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5896 | F1=0.7698 | AUROC=0.8711 | AUPRC=0.8505
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 213.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6078 | F1=0.7203 | AUROC=0.8968 | AUPRC=0.7916
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5909 | F1=0.7972 | AUROC=0.8862 | AUPRC=0.8859
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4524 | F1=0.7245 | AUROC=0.7798 | AUPRC=0.7529
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5742 | F1=0.7751 | AUROC=0.8714 | AUPRC=0.8465
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 113.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6186 | F1=0.7272 | AUROC=0.8926 | AUPRC=0.7909
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5960 | F1=0.7966 | AUROC=0.8849 | AUPRC=0.8816
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4392 | F1=0.7123 | AUROC=0.7759 | AUPRC=0.7715
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5832 | F1=0.7776 | AUROC=0.8629 | AUPRC=0.8435
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 45.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6131 | F1=0.7233 | AUROC=0.8851 | AUPRC=0.7905
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5789 | F1=0.7855 | AUROC=0.8732 | AUPRC=0.8651
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4318 | F1=0.7069 | AUROC=0.7714 | AUPRC=0.7559
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5688 | F1=0.7687 | AUROC=0.8595 | AUPRC=0.8331
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 61.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6174 | F1=0.7267 | AUROC=0.8938 | AUPRC=0.7965
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5875 | F1=0.7896 | AUROC=0.8782 | AUPRC=0.8720
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4524 | F1=0.7220 | AUROC=0.7776 | AUPRC=0.7624
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5842 | F1=0.7775 | AUROC=0.8615 | AUPRC=0.8426
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5707 | val_loss=0.4786 | val_mcc=0.4568 | val_f1=0.5667 | val_auroc=0.8107

[Epoch 02] train_loss=0.5091 | val_loss=0.4485 | val_mcc=0.4941 | val_f1=0.5963 | val_auroc=0.8295

[Epoch 03] train_loss=0.4782 | val_loss=0.3815 | val_mcc=0.5269 | val_f1=0.6148 | val_auroc=0.8458

[Epoch 04] train_loss=0.4374 | val_loss=0.3879 | val_mcc=0.5319 | val_f1=0.6249 | val_auroc=0.8627

[Epoch 05] train_loss=0.3969 | val_loss=0.3923 | val_mcc=0.5409 | val_f1=0.6338 | val_auroc=0.8734

[Epoch 06] train_loss=0.3609 | val_loss=0.4739 | val_mcc=0.5054 | val_f1=0.6034 | val_auroc=0.8732

[Epoch 07] train_loss=0.3192 | val_loss=0.4295 | val_mcc=0.5292 | val_f1=0.6248 | val_auroc=0.8742

[Epoch 08] train_loss=0.2734 | val_loss=0.4269 | val_mcc=0.5235 | val_f1=0.6201 | val_auroc=0.8677

[Epoch 09] train_loss=0.2238 | val_loss=0.5544 | val_mcc=0.4967 | val_f1=0.5984 | val_auroc=0.8624

[Epoch 10] train_loss=0.1663 | val_loss=0.5419 | val_mcc=0.4838 | val_f1=0.5894 | val_auroc=0.8560

[Epoch 11] train_loss=0.1365 | val_loss=0.5730 | val_mcc=0.4736 | val_f1=0.5818 | val_auroc=0.8511
[EarlyStop] epoch=11 | best_val_mcc=0.5409
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5832 | F1=0.6980 | AUROC=0.8763 | AUPRC=0.7720
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5798 | F1=0.7804 | AUROC=0.8569 | AUPRC=0.8466
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4063 | F1=0.6935 | AUROC=0.7550 | AUPRC=0.7395
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5039 | F1=0.7186 | AUROC=0.8247 | AUPRC=0.7994
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5755 | val_loss=0.4342 | val_mcc=0.4850 | val_f1=0.5808 | val_auroc=0.8130

[Epoch 02] train_loss=0.5104 | val_loss=0.4390 | val_mcc=0.4894 | val_f1=0.5907 | val_auroc=0.8294

[Epoch 03] train_loss=0.4834 | val_loss=0.4270 | val_mcc=0.5146 | val_f1=0.6123 | val_auroc=0.8447

[Epoch 04] train_loss=0.4461 | val_loss=0.4331 | val_mcc=0.5194 | val_f1=0.6174 | val_auroc=0.8609

[Epoch 05] train_loss=0.4075 | val_loss=0.4447 | val_mcc=0.5202 | val_f1=0.6177 | val_auroc=0.8665

[Epoch 06] train_loss=0.3640 | val_loss=0.4584 | val_mcc=0.5018 | val_f1=0.6034 | val_auroc=0.8569

[Epoch 07] train_loss=0.3212 | val_loss=0.4275 | val_mcc=0.5166 | val_f1=0.6118 | val_auroc=0.8532

[Epoch 08] train_loss=0.2689 | val_loss=0.5023 | val_mcc=0.4844 | val_f1=0.5904 | val_auroc=0.8465

[Epoch 09] train_loss=0.2117 | val_loss=0.7210 | val_mcc=0.4524 | val_f1=0.5618 | val_auroc=0.8443

[Epoch 10] train_loss=0.1437 | val_loss=0.6654 | val_mcc=0.4895 | val_f1=0.5942 | val_auroc=0.8406

[Epoch 11] train_loss=0.1166 | val_loss=0.8325 | val_mcc=0.4674 | val_f1=0.5762 | val_auroc=0.8398
[EarlyStop] epoch=11 | best_val_mcc=0.5202
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5641 | F1=0.6892 | AUROC=0.8734 | AUPRC=0.7638
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5846 | F1=0.7902 | AUROC=0.8598 | AUPRC=0.8500
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3893 | F1=0.6938 | AUROC=0.7589 | AUPRC=0.7423
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5097 | F1=0.7328 | AUROC=0.8284 | AUPRC=0.7974
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5635 | val_loss=0.5001 | val_mcc=0.4632 | val_f1=0.5738 | val_auroc=0.8142

[Epoch 02] train_loss=0.5139 | val_loss=0.4511 | val_mcc=0.4873 | val_f1=0.5906 | val_auroc=0.8308

[Epoch 03] train_loss=0.4751 | val_loss=0.4555 | val_mcc=0.5164 | val_f1=0.6150 | val_auroc=0.8544

[Epoch 04] train_loss=0.4367 | val_loss=0.3809 | val_mcc=0.5387 | val_f1=0.6294 | val_auroc=0.8671

[Epoch 05] train_loss=0.3980 | val_loss=0.4195 | val_mcc=0.5344 | val_f1=0.6289 | val_auroc=0.8690

[Epoch 06] train_loss=0.3509 | val_loss=0.4131 | val_mcc=0.5141 | val_f1=0.6126 | val_auroc=0.8603

[Epoch 07] train_loss=0.3116 | val_loss=0.5761 | val_mcc=0.4681 | val_f1=0.5722 | val_auroc=0.8605

[Epoch 08] train_loss=0.2498 | val_loss=0.4684 | val_mcc=0.5133 | val_f1=0.6115 | val_auroc=0.8560

[Epoch 09] train_loss=0.1761 | val_loss=0.5707 | val_mcc=0.5000 | val_f1=0.6013 | val_auroc=0.8499

[Epoch 10] train_loss=0.1393 | val_loss=0.6888 | val_mcc=0.4835 | val_f1=0.5897 | val_auroc=0.8456
[EarlyStop] epoch=10 | best_val_mcc=0.5387
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5828 | F1=0.6902 | AUROC=0.8702 | AUPRC=0.7644
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5455 | F1=0.7534 | AUROC=0.8468 | AUPRC=0.8336
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3993 | F1=0.6726 | AUROC=0.7529 | AUPRC=0.7353
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5010 | F1=0.7045 | AUROC=0.8181 | AUPRC=0.7889
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5723 | val_loss=0.4930 | val_mcc=0.4604 | val_f1=0.5714 | val_auroc=0.8113

[Epoch 02] train_loss=0.5077 | val_loss=0.4378 | val_mcc=0.4838 | val_f1=0.5872 | val_auroc=0.8286

[Epoch 03] train_loss=0.4725 | val_loss=0.4192 | val_mcc=0.5104 | val_f1=0.6092 | val_auroc=0.8476

[Epoch 04] train_loss=0.4356 | val_loss=0.3924 | val_mcc=0.5258 | val_f1=0.6213 | val_auroc=0.8614

[Epoch 05] train_loss=0.3931 | val_loss=0.4307 | val_mcc=0.5148 | val_f1=0.6137 | val_auroc=0.8686

[Epoch 06] train_loss=0.3480 | val_loss=0.4312 | val_mcc=0.5141 | val_f1=0.6132 | val_auroc=0.8677

[Epoch 07] train_loss=0.3007 | val_loss=0.4628 | val_mcc=0.5174 | val_f1=0.6154 | val_auroc=0.8666

[Epoch 08] train_loss=0.2439 | val_loss=0.4687 | val_mcc=0.4868 | val_f1=0.5920 | val_auroc=0.8549

[Epoch 09] train_loss=0.1759 | val_loss=0.5643 | val_mcc=0.4780 | val_f1=0.5842 | val_auroc=0.8554

[Epoch 10] train_loss=0.1404 | val_loss=0.5955 | val_mcc=0.4809 | val_f1=0.5869 | val_auroc=0.8550
[EarlyStop] epoch=10 | best_val_mcc=0.5258
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5811 | F1=0.6953 | AUROC=0.8672 | AUPRC=0.7580
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5741 | F1=0.7774 | AUROC=0.8527 | AUPRC=0.8424
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3968 | F1=0.6819 | AUROC=0.7565 | AUPRC=0.7358
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5125 | F1=0.7189 | AUROC=0.8223 | AUPRC=0.7954
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 241.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5482 | F1=0.6777 | AUROC=0.8695 | AUPRC=0.7516
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5192 | F1=0.7582 | AUROC=0.8419 | AUPRC=0.8354
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3938 | F1=0.6962 | AUROC=0.7502 | AUPRC=0.7249
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4838 | F1=0.7193 | AUROC=0.8183 | AUPRC=0.7871
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 217.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5438 | F1=0.6715 | AUROC=0.8639 | AUPRC=0.7495
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5250 | F1=0.7555 | AUROC=0.8447 | AUPRC=0.8238
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3762 | F1=0.6790 | AUROC=0.7499 | AUPRC=0.7399
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4655 | F1=0.7010 | AUROC=0.8145 | AUPRC=0.7786
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 147.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5215 | F1=0.6567 | AUROC=0.8480 | AUPRC=0.7350
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5053 | F1=0.7434 | AUROC=0.8288 | AUPRC=0.8155
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3598 | F1=0.6687 | AUROC=0.7366 | AUPRC=0.7255
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4544 | F1=0.6939 | AUROC=0.7998 | AUPRC=0.7691
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 113.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5390 | F1=0.6695 | AUROC=0.8574 | AUPRC=0.7429
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4944 | F1=0.7351 | AUROC=0.8374 | AUPRC=0.8185
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3687 | F1=0.6744 | AUROC=0.7465 | AUPRC=0.7245
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.4599 | F1=0.6970 | AUROC=0.8001 | AUPRC=0.7768
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']

[Epoch 01] train_loss=0.5783 | val_loss=0.4523 | val_mcc=0.5330 | val_f1=0.6220 | val_auroc=0.8218

[Epoch 02] train_loss=0.4962 | val_loss=0.4314 | val_mcc=0.5638 | val_f1=0.6462 | val_auroc=0.8399

[Epoch 03] train_loss=0.4741 | val_loss=0.4099 | val_mcc=0.5622 | val_f1=0.6475 | val_auroc=0.8463

[Epoch 04] train_loss=0.4540 | val_loss=0.4106 | val_mcc=0.5567 | val_f1=0.6442 | val_auroc=0.8494

[Epoch 05] train_loss=0.4342 | val_loss=0.3496 | val_mcc=0.5781 | val_f1=0.6509 | val_auroc=0.8522

[Epoch 06] train_loss=0.4107 | val_loss=0.4634 | val_mcc=0.5028 | val_f1=0.6041 | val_auroc=0.8566

[Epoch 07] train_loss=0.3815 | val_loss=0.3973 | val_mcc=0.5393 | val_f1=0.6316 | val_auroc=0.8472

[Epoch 08] train_loss=0.3433 | val_loss=0.3881 | val_mcc=0.5377 | val_f1=0.6294 | val_auroc=0.8504

[Epoch 09] train_loss=0.2948 | val_loss=0.4764 | val_mcc=0.4842 | val_f1=0.5903 | val_auroc=0.8401

[Epoch 10] train_loss=0.2314 | val_loss=0.4908 | val_mcc=0.4790 | val_f1=0.5862 | val_auroc=0.8410

[Epoch 11] train_loss=0.2008 | val_loss=0.4753 | val_mcc=0.5091 | val_f1=0.6093 | val_auroc=0.8420
[EarlyStop] epoch=11 | best_val_mcc=0.5781
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6039 | F1=0.6962 | AUROC=0.8428 | AUPRC=0.7708
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5439 | F1=0.7221 | AUROC=0.8046 | AUPRC=0.8402
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3985 | F1=0.6477 | AUROC=0.7283 | AUPRC=0.7483
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5263 | F1=0.7090 | AUROC=0.8027 | AUPRC=0.8131
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5803 | val_loss=0.5759 | val_mcc=0.4337 | val_f1=0.5489 | val_auroc=0.8266

[Epoch 02] train_loss=0.4992 | val_loss=0.4229 | val_mcc=0.5661 | val_f1=0.6483 | val_auroc=0.8387

[Epoch 03] train_loss=0.4765 | val_loss=0.4032 | val_mcc=0.5724 | val_f1=0.6519 | val_auroc=0.8440

[Epoch 04] train_loss=0.4534 | val_loss=0.3792 | val_mcc=0.5811 | val_f1=0.6571 | val_auroc=0.8438

[Epoch 05] train_loss=0.4308 | val_loss=0.4192 | val_mcc=0.5349 | val_f1=0.6288 | val_auroc=0.8479

[Epoch 06] train_loss=0.3965 | val_loss=0.3941 | val_mcc=0.5415 | val_f1=0.6322 | val_auroc=0.8419

[Epoch 07] train_loss=0.3418 | val_loss=0.5656 | val_mcc=0.4287 | val_f1=0.5455 | val_auroc=0.8288

[Epoch 08] train_loss=0.2930 | val_loss=0.4557 | val_mcc=0.5273 | val_f1=0.6180 | val_auroc=0.8304

[Epoch 09] train_loss=0.2193 | val_loss=0.6600 | val_mcc=0.4447 | val_f1=0.5595 | val_auroc=0.8171

[Epoch 10] train_loss=0.1802 | val_loss=0.7137 | val_mcc=0.4377 | val_f1=0.5549 | val_auroc=0.8080
[EarlyStop] epoch=10 | best_val_mcc=0.5811
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6031 | F1=0.6990 | AUROC=0.8368 | AUPRC=0.7678
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5616 | F1=0.7368 | AUROC=0.8068 | AUPRC=0.8445
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3721 | F1=0.6419 | AUROC=0.7173 | AUPRC=0.7387
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5277 | F1=0.7145 | AUROC=0.7971 | AUPRC=0.8065
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5686 | val_loss=0.3827 | val_mcc=0.5491 | val_f1=0.6134 | val_auroc=0.8274

[Epoch 02] train_loss=0.4937 | val_loss=0.3538 | val_mcc=0.5739 | val_f1=0.6395 | val_auroc=0.8407

[Epoch 03] train_loss=0.4701 | val_loss=0.3646 | val_mcc=0.5799 | val_f1=0.6560 | val_auroc=0.8490

[Epoch 04] train_loss=0.4529 | val_loss=0.3561 | val_mcc=0.5809 | val_f1=0.6554 | val_auroc=0.8501

[Epoch 05] train_loss=0.4297 | val_loss=0.3371 | val_mcc=0.5815 | val_f1=0.6424 | val_auroc=0.8427

[Epoch 06] train_loss=0.4013 | val_loss=0.4619 | val_mcc=0.5217 | val_f1=0.6189 | val_auroc=0.8570

[Epoch 07] train_loss=0.3647 | val_loss=0.4206 | val_mcc=0.5360 | val_f1=0.6289 | val_auroc=0.8361

[Epoch 08] train_loss=0.3059 | val_loss=0.5579 | val_mcc=0.4523 | val_f1=0.5647 | val_auroc=0.8357

[Epoch 09] train_loss=0.2447 | val_loss=0.5567 | val_mcc=0.4729 | val_f1=0.5814 | val_auroc=0.8349

[Epoch 10] train_loss=0.1769 | val_loss=0.6449 | val_mcc=0.4607 | val_f1=0.5724 | val_auroc=0.8190

[Epoch 11] train_loss=0.1406 | val_loss=0.7011 | val_mcc=0.4505 | val_f1=0.5646 | val_auroc=0.8165
[EarlyStop] epoch=11 | best_val_mcc=0.5815
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5979 | F1=0.6786 | AUROC=0.8312 | AUPRC=0.7633
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5149 | F1=0.6852 | AUROC=0.8022 | AUPRC=0.8360
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3687 | F1=0.6083 | AUROC=0.7131 | AUPRC=0.7338
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5165 | F1=0.6842 | AUROC=0.7920 | AUPRC=0.8092
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5681 | val_loss=0.3940 | val_mcc=0.5505 | val_f1=0.6171 | val_auroc=0.8250

[Epoch 02] train_loss=0.4909 | val_loss=0.3973 | val_mcc=0.5729 | val_f1=0.6488 | val_auroc=0.8407

[Epoch 03] train_loss=0.4674 | val_loss=0.3741 | val_mcc=0.5768 | val_f1=0.6529 | val_auroc=0.8471

[Epoch 04] train_loss=0.4447 | val_loss=0.3611 | val_mcc=0.5744 | val_f1=0.6500 | val_auroc=0.8525

[Epoch 05] train_loss=0.4219 | val_loss=0.4249 | val_mcc=0.5278 | val_f1=0.6238 | val_auroc=0.8528

[Epoch 06] train_loss=0.3905 | val_loss=0.3804 | val_mcc=0.5475 | val_f1=0.6359 | val_auroc=0.8504

[Epoch 07] train_loss=0.3520 | val_loss=0.3988 | val_mcc=0.5353 | val_f1=0.6276 | val_auroc=0.8469

[Epoch 08] train_loss=0.2894 | val_loss=0.4471 | val_mcc=0.5017 | val_f1=0.6036 | val_auroc=0.8447

[Epoch 09] train_loss=0.2540 | val_loss=0.4927 | val_mcc=0.4825 | val_f1=0.5890 | val_auroc=0.8418
[EarlyStop] epoch=9 | best_val_mcc=0.5768
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5969 | F1=0.6932 | AUROC=0.8432 | AUPRC=0.7720
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5422 | F1=0.7240 | AUROC=0.8027 | AUPRC=0.8405
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3694 | F1=0.6347 | AUROC=0.7265 | AUPRC=0.7411
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5229 | F1=0.7088 | AUROC=0.8009 | AUPRC=0.8141
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 387.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5925 | F1=0.7079 | AUROC=0.8834 | AUPRC=0.7982
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5506 | F1=0.7690 | AUROC=0.8686 | AUPRC=0.8709
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3686 | F1=0.6754 | AUROC=0.7479 | AUPRC=0.7494
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5266 | F1=0.7388 | AUROC=0.8458 | AUPRC=0.8406
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 277.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5924 | F1=0.7065 | AUROC=0.8735 | AUPRC=0.7963
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5620 | F1=0.7641 | AUROC=0.8505 | AUPRC=0.8661
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3691 | F1=0.6714 | AUROC=0.7376 | AUPRC=0.7396
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5262 | F1=0.7348 | AUROC=0.8291 | AUPRC=0.8242
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 158.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5693 | F1=0.6903 | AUROC=0.8632 | AUPRC=0.7809
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5121 | F1=0.7417 | AUROC=0.8280 | AUPRC=0.8492
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3452 | F1=0.6573 | AUROC=0.7367 | AUPRC=0.7489
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4946 | F1=0.7187 | AUROC=0.8259 | AUPRC=0.8233
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 230.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5746 | F1=0.6935 | AUROC=0.8623 | AUPRC=0.7844
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5071 | F1=0.7364 | AUROC=0.8356 | AUPRC=0.8566
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3651 | F1=0.6656 | AUROC=0.7388 | AUPRC=0.7485
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5137 | F1=0.7269 | AUROC=0.8190 | AUPRC=0.8258
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']

[Epoch 01] train_loss=0.5294 | val_loss=0.4152 | val_mcc=0.5444 | val_f1=0.6365 | val_auroc=0.8563

[Epoch 02] train_loss=0.4666 | val_loss=0.3970 | val_mcc=0.5556 | val_f1=0.6453 | val_auroc=0.8665

[Epoch 03] train_loss=0.4364 | val_loss=0.3929 | val_mcc=0.5641 | val_f1=0.6520 | val_auroc=0.8796

[Epoch 04] train_loss=0.4085 | val_loss=0.3971 | val_mcc=0.5670 | val_f1=0.6540 | val_auroc=0.8866

[Epoch 05] train_loss=0.3820 | val_loss=0.3670 | val_mcc=0.5773 | val_f1=0.6624 | val_auroc=0.8911

[Epoch 06] train_loss=0.3555 | val_loss=0.3750 | val_mcc=0.5775 | val_f1=0.6623 | val_auroc=0.8908

[Epoch 07] train_loss=0.3296 | val_loss=0.3953 | val_mcc=0.5751 | val_f1=0.6600 | val_auroc=0.8919

[Epoch 08] train_loss=0.3024 | val_loss=0.4305 | val_mcc=0.5571 | val_f1=0.6453 | val_auroc=0.8908

[Epoch 09] train_loss=0.2794 | val_loss=0.4148 | val_mcc=0.5530 | val_f1=0.6434 | val_auroc=0.8815

[Epoch 10] train_loss=0.2498 | val_loss=0.4436 | val_mcc=0.5580 | val_f1=0.6470 | val_auroc=0.8821

[Epoch 11] train_loss=0.2131 | val_loss=0.4804 | val_mcc=0.5442 | val_f1=0.6363 | val_auroc=0.8793

[Epoch 12] train_loss=0.1955 | val_loss=0.4685 | val_mcc=0.5369 | val_f1=0.6309 | val_auroc=0.8712
[EarlyStop] epoch=12 | best_val_mcc=0.5775
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6380 | F1=0.7405 | AUROC=0.9040 | AUPRC=0.8095
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6130 | F1=0.8035 | AUROC=0.8894 | AUPRC=0.8776
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4301 | F1=0.7086 | AUROC=0.7848 | AUPRC=0.7697
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5890 | F1=0.7792 | AUROC=0.8766 | AUPRC=0.8489
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5313 | val_loss=0.3991 | val_mcc=0.5564 | val_f1=0.6449 | val_auroc=0.8555

[Epoch 02] train_loss=0.4726 | val_loss=0.4222 | val_mcc=0.5497 | val_f1=0.6405 | val_auroc=0.8706

[Epoch 03] train_loss=0.4344 | val_loss=0.4114 | val_mcc=0.5629 | val_f1=0.6506 | val_auroc=0.8796

[Epoch 04] train_loss=0.4058 | val_loss=0.3692 | val_mcc=0.5836 | val_f1=0.6672 | val_auroc=0.8863

[Epoch 05] train_loss=0.3764 | val_loss=0.3944 | val_mcc=0.5747 | val_f1=0.6599 | val_auroc=0.8898

[Epoch 06] train_loss=0.3475 | val_loss=0.4192 | val_mcc=0.5676 | val_f1=0.6539 | val_auroc=0.8863

[Epoch 07] train_loss=0.3234 | val_loss=0.3948 | val_mcc=0.5840 | val_f1=0.6676 | val_auroc=0.8865

[Epoch 08] train_loss=0.2991 | val_loss=0.5223 | val_mcc=0.5337 | val_f1=0.6246 | val_auroc=0.8794

[Epoch 09] train_loss=0.2724 | val_loss=0.4841 | val_mcc=0.5406 | val_f1=0.6336 | val_auroc=0.8682

[Epoch 10] train_loss=0.2430 | val_loss=0.5474 | val_mcc=0.5459 | val_f1=0.6370 | val_auroc=0.8721

[Epoch 11] train_loss=0.2188 | val_loss=0.5350 | val_mcc=0.5496 | val_f1=0.6408 | val_auroc=0.8667

[Epoch 12] train_loss=0.1845 | val_loss=0.6636 | val_mcc=0.5336 | val_f1=0.6279 | val_auroc=0.8643

[Epoch 13] train_loss=0.1701 | val_loss=0.7477 | val_mcc=0.5198 | val_f1=0.6158 | val_auroc=0.8635
[EarlyStop] epoch=13 | best_val_mcc=0.5840
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6423 | F1=0.7425 | AUROC=0.9020 | AUPRC=0.8037
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5847 | F1=0.7872 | AUROC=0.8802 | AUPRC=0.8535
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4474 | F1=0.7115 | AUROC=0.7873 | AUPRC=0.7705
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5860 | F1=0.7733 | AUROC=0.8773 | AUPRC=0.8461
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5290 | val_loss=0.3697 | val_mcc=0.5500 | val_f1=0.6368 | val_auroc=0.8537

[Epoch 02] train_loss=0.4637 | val_loss=0.4200 | val_mcc=0.5446 | val_f1=0.6367 | val_auroc=0.8689

[Epoch 03] train_loss=0.4323 | val_loss=0.4097 | val_mcc=0.5634 | val_f1=0.6505 | val_auroc=0.8855

[Epoch 04] train_loss=0.4012 | val_loss=0.3229 | val_mcc=0.5986 | val_f1=0.6728 | val_auroc=0.8899

[Epoch 05] train_loss=0.3736 | val_loss=0.3682 | val_mcc=0.5811 | val_f1=0.6653 | val_auroc=0.8902

[Epoch 06] train_loss=0.3441 | val_loss=0.3749 | val_mcc=0.5738 | val_f1=0.6596 | val_auroc=0.8879

[Epoch 07] train_loss=0.3184 | val_loss=0.3514 | val_mcc=0.5839 | val_f1=0.6635 | val_auroc=0.8861

[Epoch 08] train_loss=0.2858 | val_loss=0.4358 | val_mcc=0.5559 | val_f1=0.6457 | val_auroc=0.8798

[Epoch 09] train_loss=0.2408 | val_loss=0.4429 | val_mcc=0.5615 | val_f1=0.6495 | val_auroc=0.8775

[Epoch 10] train_loss=0.2195 | val_loss=0.4712 | val_mcc=0.5456 | val_f1=0.6373 | val_auroc=0.8704
[EarlyStop] epoch=10 | best_val_mcc=0.5986
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6412 | F1=0.7293 | AUROC=0.9047 | AUPRC=0.8127
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5757 | F1=0.7552 | AUROC=0.8901 | AUPRC=0.8792
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4375 | F1=0.6724 | AUROC=0.7861 | AUPRC=0.7750
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5658 | F1=0.7415 | AUROC=0.8804 | AUPRC=0.8532
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5345 | val_loss=0.3886 | val_mcc=0.5509 | val_f1=0.6400 | val_auroc=0.8583

[Epoch 02] train_loss=0.4619 | val_loss=0.3720 | val_mcc=0.5615 | val_f1=0.6494 | val_auroc=0.8700

[Epoch 03] train_loss=0.4313 | val_loss=0.3614 | val_mcc=0.5751 | val_f1=0.6603 | val_auroc=0.8798

[Epoch 04] train_loss=0.4000 | val_loss=0.4022 | val_mcc=0.5555 | val_f1=0.6442 | val_auroc=0.8873

[Epoch 05] train_loss=0.3733 | val_loss=0.3546 | val_mcc=0.5819 | val_f1=0.6659 | val_auroc=0.8921

[Epoch 06] train_loss=0.3429 | val_loss=0.4024 | val_mcc=0.5494 | val_f1=0.6401 | val_auroc=0.8864

[Epoch 07] train_loss=0.3137 | val_loss=0.3715 | val_mcc=0.5708 | val_f1=0.6572 | val_auroc=0.8886

[Epoch 08] train_loss=0.2814 | val_loss=0.4275 | val_mcc=0.5504 | val_f1=0.6409 | val_auroc=0.8816

[Epoch 09] train_loss=0.2534 | val_loss=0.4636 | val_mcc=0.5473 | val_f1=0.6377 | val_auroc=0.8801

[Epoch 10] train_loss=0.2104 | val_loss=0.4750 | val_mcc=0.5519 | val_f1=0.6421 | val_auroc=0.8816

[Epoch 11] train_loss=0.1898 | val_loss=0.5085 | val_mcc=0.5416 | val_f1=0.6334 | val_auroc=0.8780
[EarlyStop] epoch=11 | best_val_mcc=0.5819
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6430 | F1=0.7423 | AUROC=0.9040 | AUPRC=0.8149
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6023 | F1=0.7935 | AUROC=0.8955 | AUPRC=0.8833
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4499 | F1=0.7084 | AUROC=0.7857 | AUPRC=0.7741
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5956 | F1=0.7784 | AUROC=0.8807 | AUPRC=0.8585
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 206.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6164 | F1=0.7265 | AUROC=0.9000 | AUPRC=0.8027
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6234 | F1=0.8155 | AUROC=0.8833 | AUPRC=0.8838
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4389 | F1=0.7188 | AUROC=0.7760 | AUPRC=0.7617
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5742 | F1=0.7751 | AUROC=0.8707 | AUPRC=0.8494
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 86.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6300 | F1=0.7349 | AUROC=0.8968 | AUPRC=0.8006
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5963 | F1=0.7918 | AUROC=0.8863 | AUPRC=0.8780
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4455 | F1=0.7127 | AUROC=0.7842 | AUPRC=0.7772
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5974 | F1=0.7839 | AUROC=0.8727 | AUPRC=0.8460
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 96.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6157 | F1=0.7247 | AUROC=0.8916 | AUPRC=0.7941
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5903 | F1=0.7913 | AUROC=0.8713 | AUPRC=0.8662
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4375 | F1=0.7131 | AUROC=0.7717 | AUPRC=0.7559
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5678 | F1=0.7688 | AUROC=0.8691 | AUPRC=0.8435
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 123.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6161 | F1=0.7254 | AUROC=0.8935 | AUPRC=0.7984
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5817 | F1=0.7885 | AUROC=0.8827 | AUPRC=0.8743
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4333 | F1=0.7079 | AUROC=0.7751 | AUPRC=0.7573
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5962 | F1=0.7836 | AUROC=0.8756 | AUPRC=0.8536
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5661 | val_loss=0.4508 | val_mcc=0.4744 | val_f1=0.5763 | val_auroc=0.8137

[Epoch 02] train_loss=0.5097 | val_loss=0.4578 | val_mcc=0.4924 | val_f1=0.5952 | val_auroc=0.8294

[Epoch 03] train_loss=0.4806 | val_loss=0.4277 | val_mcc=0.5122 | val_f1=0.6105 | val_auroc=0.8446

[Epoch 04] train_loss=0.4539 | val_loss=0.3881 | val_mcc=0.5321 | val_f1=0.6257 | val_auroc=0.8645

[Epoch 05] train_loss=0.4231 | val_loss=0.4347 | val_mcc=0.5258 | val_f1=0.6216 | val_auroc=0.8748

[Epoch 06] train_loss=0.3978 | val_loss=0.3935 | val_mcc=0.5423 | val_f1=0.6351 | val_auroc=0.8786

[Epoch 07] train_loss=0.3743 | val_loss=0.4045 | val_mcc=0.5403 | val_f1=0.6333 | val_auroc=0.8804

[Epoch 08] train_loss=0.3537 | val_loss=0.4174 | val_mcc=0.5331 | val_f1=0.6276 | val_auroc=0.8784

[Epoch 09] train_loss=0.3284 | val_loss=0.3818 | val_mcc=0.5385 | val_f1=0.6315 | val_auroc=0.8779

[Epoch 10] train_loss=0.3058 | val_loss=0.4393 | val_mcc=0.5297 | val_f1=0.6248 | val_auroc=0.8775

[Epoch 11] train_loss=0.2735 | val_loss=0.4385 | val_mcc=0.5265 | val_f1=0.6228 | val_auroc=0.8741

[Epoch 12] train_loss=0.2585 | val_loss=0.4553 | val_mcc=0.5234 | val_f1=0.6203 | val_auroc=0.8725
[EarlyStop] epoch=12 | best_val_mcc=0.5423
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5939 | F1=0.7083 | AUROC=0.8857 | AUPRC=0.7825
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6075 | F1=0.7988 | AUROC=0.8752 | AUPRC=0.8617
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4133 | F1=0.7054 | AUROC=0.7696 | AUPRC=0.7534
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5304 | F1=0.7381 | AUROC=0.8394 | AUPRC=0.8077
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5633 | val_loss=0.4592 | val_mcc=0.4839 | val_f1=0.5853 | val_auroc=0.8120

[Epoch 02] train_loss=0.5109 | val_loss=0.4151 | val_mcc=0.5051 | val_f1=0.5993 | val_auroc=0.8325

[Epoch 03] train_loss=0.4825 | val_loss=0.4967 | val_mcc=0.4874 | val_f1=0.5917 | val_auroc=0.8517

[Epoch 04] train_loss=0.4489 | val_loss=0.3778 | val_mcc=0.5432 | val_f1=0.6342 | val_auroc=0.8694

[Epoch 05] train_loss=0.4185 | val_loss=0.4736 | val_mcc=0.5135 | val_f1=0.6107 | val_auroc=0.8735

[Epoch 06] train_loss=0.3964 | val_loss=0.4311 | val_mcc=0.5363 | val_f1=0.6299 | val_auroc=0.8768

[Epoch 07] train_loss=0.3696 | val_loss=0.3876 | val_mcc=0.5442 | val_f1=0.6360 | val_auroc=0.8783

[Epoch 08] train_loss=0.3479 | val_loss=0.4321 | val_mcc=0.5266 | val_f1=0.6226 | val_auroc=0.8694

[Epoch 09] train_loss=0.3283 | val_loss=0.4677 | val_mcc=0.5376 | val_f1=0.6303 | val_auroc=0.8760

[Epoch 10] train_loss=0.3097 | val_loss=0.4777 | val_mcc=0.5260 | val_f1=0.6214 | val_auroc=0.8729

[Epoch 11] train_loss=0.2895 | val_loss=0.4287 | val_mcc=0.5323 | val_f1=0.6263 | val_auroc=0.8711

[Epoch 12] train_loss=0.2544 | val_loss=0.5561 | val_mcc=0.5147 | val_f1=0.6128 | val_auroc=0.8642

[Epoch 13] train_loss=0.2414 | val_loss=0.5562 | val_mcc=0.5091 | val_f1=0.6088 | val_auroc=0.8586
[EarlyStop] epoch=13 | best_val_mcc=0.5442
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5911 | F1=0.7029 | AUROC=0.8861 | AUPRC=0.7772
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6063 | F1=0.7916 | AUROC=0.8716 | AUPRC=0.8562
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4113 | F1=0.6927 | AUROC=0.7727 | AUPRC=0.7499
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5333 | F1=0.7314 | AUROC=0.8414 | AUPRC=0.8102
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5669 | val_loss=0.5197 | val_mcc=0.4639 | val_f1=0.5748 | val_auroc=0.8191

[Epoch 02] train_loss=0.5058 | val_loss=0.4310 | val_mcc=0.4937 | val_f1=0.5957 | val_auroc=0.8354

[Epoch 03] train_loss=0.4758 | val_loss=0.4121 | val_mcc=0.5191 | val_f1=0.6160 | val_auroc=0.8566

[Epoch 04] train_loss=0.4433 | val_loss=0.3530 | val_mcc=0.5541 | val_f1=0.6387 | val_auroc=0.8717

[Epoch 05] train_loss=0.4171 | val_loss=0.3528 | val_mcc=0.5547 | val_f1=0.6414 | val_auroc=0.8795

[Epoch 06] train_loss=0.3877 | val_loss=0.4075 | val_mcc=0.5463 | val_f1=0.6382 | val_auroc=0.8815

[Epoch 07] train_loss=0.3644 | val_loss=0.3580 | val_mcc=0.5570 | val_f1=0.6444 | val_auroc=0.8822

[Epoch 08] train_loss=0.3425 | val_loss=0.4589 | val_mcc=0.5221 | val_f1=0.6183 | val_auroc=0.8776

[Epoch 09] train_loss=0.3196 | val_loss=0.4014 | val_mcc=0.5397 | val_f1=0.6330 | val_auroc=0.8751

[Epoch 10] train_loss=0.2921 | val_loss=0.4222 | val_mcc=0.5377 | val_f1=0.6312 | val_auroc=0.8714

[Epoch 11] train_loss=0.2792 | val_loss=0.4511 | val_mcc=0.5347 | val_f1=0.6290 | val_auroc=0.8730

[Epoch 12] train_loss=0.2368 | val_loss=0.4918 | val_mcc=0.5348 | val_f1=0.6293 | val_auroc=0.8718

[Epoch 13] train_loss=0.2195 | val_loss=0.4893 | val_mcc=0.5257 | val_f1=0.6221 | val_auroc=0.8677
[EarlyStop] epoch=13 | best_val_mcc=0.5570
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5954 | F1=0.7020 | AUROC=0.8908 | AUPRC=0.7885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5822 | F1=0.7744 | AUROC=0.8816 | AUPRC=0.8638
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4172 | F1=0.6890 | AUROC=0.7709 | AUPRC=0.7604
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5298 | F1=0.7245 | AUROC=0.8426 | AUPRC=0.8121
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5623 | val_loss=0.4423 | val_mcc=0.4780 | val_f1=0.5799 | val_auroc=0.8179

[Epoch 02] train_loss=0.5064 | val_loss=0.4494 | val_mcc=0.4950 | val_f1=0.5974 | val_auroc=0.8320

[Epoch 03] train_loss=0.4787 | val_loss=0.4144 | val_mcc=0.5161 | val_f1=0.6130 | val_auroc=0.8458

[Epoch 04] train_loss=0.4521 | val_loss=0.4059 | val_mcc=0.5306 | val_f1=0.6258 | val_auroc=0.8670

[Epoch 05] train_loss=0.4206 | val_loss=0.4172 | val_mcc=0.5357 | val_f1=0.6298 | val_auroc=0.8754

[Epoch 06] train_loss=0.3946 | val_loss=0.3961 | val_mcc=0.5404 | val_f1=0.6336 | val_auroc=0.8813

[Epoch 07] train_loss=0.3692 | val_loss=0.4315 | val_mcc=0.5231 | val_f1=0.6189 | val_auroc=0.8772

[Epoch 08] train_loss=0.3473 | val_loss=0.3780 | val_mcc=0.5490 | val_f1=0.6401 | val_auroc=0.8815

[Epoch 09] train_loss=0.3210 | val_loss=0.3885 | val_mcc=0.5435 | val_f1=0.6358 | val_auroc=0.8775

[Epoch 10] train_loss=0.2985 | val_loss=0.4718 | val_mcc=0.5146 | val_f1=0.6124 | val_auroc=0.8735

[Epoch 11] train_loss=0.2681 | val_loss=0.4005 | val_mcc=0.5234 | val_f1=0.6187 | val_auroc=0.8692

[Epoch 12] train_loss=0.2485 | val_loss=0.5294 | val_mcc=0.4978 | val_f1=0.5987 | val_auroc=0.8664

[Epoch 13] train_loss=0.2131 | val_loss=0.4979 | val_mcc=0.5118 | val_f1=0.6113 | val_auroc=0.8687

[Epoch 14] train_loss=0.1967 | val_loss=0.5405 | val_mcc=0.5002 | val_f1=0.6013 | val_auroc=0.8670
[EarlyStop] epoch=14 | best_val_mcc=0.5490
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5937 | F1=0.7057 | AUROC=0.8865 | AUPRC=0.7867
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5852 | F1=0.7847 | AUROC=0.8619 | AUPRC=0.8539
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4093 | F1=0.6950 | AUROC=0.7665 | AUPRC=0.7495
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5219 | F1=0.7290 | AUROC=0.8392 | AUPRC=0.8120
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 310.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5675 | F1=0.6908 | AUROC=0.8788 | AUPRC=0.7626
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5705 | F1=0.7846 | AUROC=0.8540 | AUPRC=0.8360
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3878 | F1=0.6909 | AUROC=0.7505 | AUPRC=0.7277
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4806 | F1=0.7161 | AUROC=0.8249 | AUPRC=0.7965
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 156.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5540 | F1=0.6809 | AUROC=0.8691 | AUPRC=0.7509
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5448 | F1=0.7708 | AUROC=0.8501 | AUPRC=0.8254
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3851 | F1=0.6841 | AUROC=0.7528 | AUPRC=0.7347
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4979 | F1=0.7236 | AUROC=0.8278 | AUPRC=0.7946
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 139.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5570 | F1=0.6820 | AUROC=0.8609 | AUPRC=0.7537
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5191 | F1=0.7554 | AUROC=0.8401 | AUPRC=0.8253
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4138 | F1=0.6976 | AUROC=0.7589 | AUPRC=0.7407
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4998 | F1=0.7156 | AUROC=0.8158 | AUPRC=0.7881
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 179.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5521 | F1=0.6784 | AUROC=0.8625 | AUPRC=0.7519
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5222 | F1=0.7537 | AUROC=0.8518 | AUPRC=0.8370
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4081 | F1=0.6926 | AUROC=0.7550 | AUPRC=0.7260
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.4971 | F1=0.7167 | AUROC=0.8149 | AUPRC=0.7804
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']

[Epoch 01] train_loss=0.5738 | val_loss=0.3936 | val_mcc=0.5453 | val_f1=0.6099 | val_auroc=0.8207

[Epoch 02] train_loss=0.4977 | val_loss=0.3981 | val_mcc=0.5765 | val_f1=0.6529 | val_auroc=0.8392

[Epoch 03] train_loss=0.4796 | val_loss=0.4555 | val_mcc=0.5528 | val_f1=0.6429 | val_auroc=0.8451

[Epoch 04] train_loss=0.4686 | val_loss=0.3723 | val_mcc=0.5838 | val_f1=0.6589 | val_auroc=0.8495

[Epoch 05] train_loss=0.4588 | val_loss=0.3542 | val_mcc=0.5919 | val_f1=0.6614 | val_auroc=0.8541

[Epoch 06] train_loss=0.4496 | val_loss=0.4168 | val_mcc=0.5617 | val_f1=0.6498 | val_auroc=0.8569

[Epoch 07] train_loss=0.4419 | val_loss=0.3952 | val_mcc=0.5758 | val_f1=0.6602 | val_auroc=0.8635

[Epoch 08] train_loss=0.4345 | val_loss=0.3536 | val_mcc=0.5952 | val_f1=0.6726 | val_auroc=0.8660

[Epoch 09] train_loss=0.4243 | val_loss=0.3527 | val_mcc=0.5843 | val_f1=0.6654 | val_auroc=0.8689

[Epoch 10] train_loss=0.4143 | val_loss=0.3614 | val_mcc=0.5839 | val_f1=0.6667 | val_auroc=0.8755

[Epoch 11] train_loss=0.4036 | val_loss=0.3696 | val_mcc=0.5828 | val_f1=0.6659 | val_auroc=0.8742

[Epoch 12] train_loss=0.3940 | val_loss=0.3703 | val_mcc=0.5808 | val_f1=0.6651 | val_auroc=0.8806

[Epoch 13] train_loss=0.3800 | val_loss=0.3788 | val_mcc=0.5793 | val_f1=0.6639 | val_auroc=0.8847

[Epoch 14] train_loss=0.3718 | val_loss=0.3750 | val_mcc=0.5796 | val_f1=0.6642 | val_auroc=0.8842
[EarlyStop] epoch=14 | best_val_mcc=0.5952
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6158 | F1=0.7148 | AUROC=0.8679 | AUPRC=0.7921
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5867 | F1=0.7624 | AUROC=0.8475 | AUPRC=0.8642
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3698 | F1=0.6536 | AUROC=0.7466 | AUPRC=0.7595
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5191 | F1=0.7158 | AUROC=0.8328 | AUPRC=0.8272
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5725 | val_loss=0.3920 | val_mcc=0.5567 | val_f1=0.6262 | val_auroc=0.8272

[Epoch 02] train_loss=0.4993 | val_loss=0.4552 | val_mcc=0.5608 | val_f1=0.6475 | val_auroc=0.8386

[Epoch 03] train_loss=0.4832 | val_loss=0.4361 | val_mcc=0.5678 | val_f1=0.6534 | val_auroc=0.8458

[Epoch 04] train_loss=0.4709 | val_loss=0.3889 | val_mcc=0.5807 | val_f1=0.6619 | val_auroc=0.8523

[Epoch 05] train_loss=0.4603 | val_loss=0.4026 | val_mcc=0.5792 | val_f1=0.6615 | val_auroc=0.8503

[Epoch 06] train_loss=0.4493 | val_loss=0.3878 | val_mcc=0.5836 | val_f1=0.6630 | val_auroc=0.8570

[Epoch 07] train_loss=0.4458 | val_loss=0.4082 | val_mcc=0.5703 | val_f1=0.6564 | val_auroc=0.8649

[Epoch 08] train_loss=0.4411 | val_loss=0.4208 | val_mcc=0.5553 | val_f1=0.6452 | val_auroc=0.8586

[Epoch 09] train_loss=0.4325 | val_loss=0.3926 | val_mcc=0.5772 | val_f1=0.6614 | val_auroc=0.8684

[Epoch 10] train_loss=0.4272 | val_loss=0.3219 | val_mcc=0.6049 | val_f1=0.6741 | val_auroc=0.8712

[Epoch 11] train_loss=0.4188 | val_loss=0.3834 | val_mcc=0.5742 | val_f1=0.6587 | val_auroc=0.8634

[Epoch 12] train_loss=0.4113 | val_loss=0.3668 | val_mcc=0.5866 | val_f1=0.6686 | val_auroc=0.8744

[Epoch 13] train_loss=0.4065 | val_loss=0.4050 | val_mcc=0.5656 | val_f1=0.6532 | val_auroc=0.8755

[Epoch 14] train_loss=0.3942 | val_loss=0.3735 | val_mcc=0.5783 | val_f1=0.6624 | val_auroc=0.8724

[Epoch 15] train_loss=0.3834 | val_loss=0.3694 | val_mcc=0.5761 | val_f1=0.6607 | val_auroc=0.8749

[Epoch 16] train_loss=0.3778 | val_loss=0.3681 | val_mcc=0.5772 | val_f1=0.6617 | val_auroc=0.8758
[EarlyStop] epoch=16 | best_val_mcc=0.6049
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6248 | F1=0.7135 | AUROC=0.8699 | AUPRC=0.7929
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5684 | F1=0.7393 | AUROC=0.8516 | AUPRC=0.8671
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4027 | F1=0.6512 | AUROC=0.7500 | AUPRC=0.7596
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5434 | F1=0.7191 | AUROC=0.8366 | AUPRC=0.8298
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5747 | val_loss=0.4226 | val_mcc=0.5439 | val_f1=0.6239 | val_auroc=0.8248

[Epoch 02] train_loss=0.4940 | val_loss=0.3652 | val_mcc=0.5777 | val_f1=0.6451 | val_auroc=0.8437

[Epoch 03] train_loss=0.4815 | val_loss=0.3704 | val_mcc=0.5851 | val_f1=0.6581 | val_auroc=0.8491

[Epoch 04] train_loss=0.4652 | val_loss=0.3533 | val_mcc=0.5887 | val_f1=0.6598 | val_auroc=0.8550

[Epoch 05] train_loss=0.4565 | val_loss=0.3857 | val_mcc=0.5831 | val_f1=0.6643 | val_auroc=0.8592

[Epoch 06] train_loss=0.4515 | val_loss=0.3425 | val_mcc=0.5921 | val_f1=0.6680 | val_auroc=0.8628

[Epoch 07] train_loss=0.4407 | val_loss=0.3793 | val_mcc=0.5754 | val_f1=0.6588 | val_auroc=0.8645

[Epoch 08] train_loss=0.4376 | val_loss=0.3883 | val_mcc=0.5722 | val_f1=0.6578 | val_auroc=0.8697

[Epoch 09] train_loss=0.4288 | val_loss=0.3371 | val_mcc=0.5934 | val_f1=0.6700 | val_auroc=0.8727

[Epoch 10] train_loss=0.4169 | val_loss=0.3504 | val_mcc=0.5891 | val_f1=0.6697 | val_auroc=0.8753

[Epoch 11] train_loss=0.4109 | val_loss=0.3407 | val_mcc=0.5928 | val_f1=0.6726 | val_auroc=0.8792

[Epoch 12] train_loss=0.4010 | val_loss=0.3500 | val_mcc=0.5805 | val_f1=0.6639 | val_auroc=0.8795

[Epoch 13] train_loss=0.3920 | val_loss=0.3332 | val_mcc=0.5980 | val_f1=0.6747 | val_auroc=0.8823

[Epoch 14] train_loss=0.3780 | val_loss=0.3962 | val_mcc=0.5630 | val_f1=0.6509 | val_auroc=0.8834

[Epoch 15] train_loss=0.3740 | val_loss=0.3249 | val_mcc=0.5935 | val_f1=0.6710 | val_auroc=0.8855

[Epoch 16] train_loss=0.3559 | val_loss=0.3494 | val_mcc=0.5806 | val_f1=0.6642 | val_auroc=0.8848

[Epoch 17] train_loss=0.3430 | val_loss=0.3976 | val_mcc=0.5627 | val_f1=0.6508 | val_auroc=0.8869

[Epoch 18] train_loss=0.3242 | val_loss=0.4128 | val_mcc=0.5576 | val_f1=0.6467 | val_auroc=0.8830

[Epoch 19] train_loss=0.3153 | val_loss=0.4114 | val_mcc=0.5588 | val_f1=0.6478 | val_auroc=0.8852
[EarlyStop] epoch=19 | best_val_mcc=0.5980
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6253 | F1=0.7222 | AUROC=0.8870 | AUPRC=0.8036
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5658 | F1=0.7574 | AUROC=0.8637 | AUPRC=0.8680
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4010 | F1=0.6678 | AUROC=0.7670 | AUPRC=0.7685
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5563 | F1=0.7400 | AUROC=0.8532 | AUPRC=0.8368
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5767 | val_loss=0.4075 | val_mcc=0.5372 | val_f1=0.6078 | val_auroc=0.8201

[Epoch 02] train_loss=0.4967 | val_loss=0.4096 | val_mcc=0.5722 | val_f1=0.6473 | val_auroc=0.8379

[Epoch 03] train_loss=0.4795 | val_loss=0.4784 | val_mcc=0.5399 | val_f1=0.6332 | val_auroc=0.8445

[Epoch 04] train_loss=0.4687 | val_loss=0.3866 | val_mcc=0.5838 | val_f1=0.6619 | val_auroc=0.8506

[Epoch 05] train_loss=0.4566 | val_loss=0.4354 | val_mcc=0.5564 | val_f1=0.6458 | val_auroc=0.8562

[Epoch 06] train_loss=0.4461 | val_loss=0.4043 | val_mcc=0.5705 | val_f1=0.6563 | val_auroc=0.8622

[Epoch 07] train_loss=0.4380 | val_loss=0.3747 | val_mcc=0.5855 | val_f1=0.6667 | val_auroc=0.8662

[Epoch 08] train_loss=0.4260 | val_loss=0.3825 | val_mcc=0.5730 | val_f1=0.6585 | val_auroc=0.8711

[Epoch 09] train_loss=0.4175 | val_loss=0.4326 | val_mcc=0.5574 | val_f1=0.6467 | val_auroc=0.8723

[Epoch 10] train_loss=0.4081 | val_loss=0.3859 | val_mcc=0.5745 | val_f1=0.6601 | val_auroc=0.8788

[Epoch 11] train_loss=0.3939 | val_loss=0.4004 | val_mcc=0.5700 | val_f1=0.6565 | val_auroc=0.8821

[Epoch 12] train_loss=0.3783 | val_loss=0.3614 | val_mcc=0.5834 | val_f1=0.6669 | val_auroc=0.8832

[Epoch 13] train_loss=0.3698 | val_loss=0.3967 | val_mcc=0.5659 | val_f1=0.6532 | val_auroc=0.8839
[EarlyStop] epoch=13 | best_val_mcc=0.5855
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6032 | F1=0.7093 | AUROC=0.8666 | AUPRC=0.7931
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5658 | F1=0.7574 | AUROC=0.8396 | AUPRC=0.8603
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3623 | F1=0.6554 | AUROC=0.7454 | AUPRC=0.7557
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5138 | F1=0.7208 | AUROC=0.8300 | AUPRC=0.8271
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 332.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5950 | F1=0.7094 | AUROC=0.8854 | AUPRC=0.8022
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5459 | F1=0.7612 | AUROC=0.8662 | AUPRC=0.8734
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3954 | F1=0.6921 | AUROC=0.7584 | AUPRC=0.7626
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5358 | F1=0.7476 | AUROC=0.8493 | AUPRC=0.8445
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 261.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5975 | F1=0.7107 | AUROC=0.8827 | AUPRC=0.8004
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5774 | F1=0.7773 | AUROC=0.8621 | AUPRC=0.8707
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3901 | F1=0.6828 | AUROC=0.7576 | AUPRC=0.7580
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5373 | F1=0.7426 | AUROC=0.8540 | AUPRC=0.8429
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 171.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5933 | F1=0.7078 | AUROC=0.8742 | AUPRC=0.7975
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5578 | F1=0.7658 | AUROC=0.8501 | AUPRC=0.8625
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4004 | F1=0.6899 | AUROC=0.7460 | AUPRC=0.7555
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5267 | F1=0.7392 | AUROC=0.8370 | AUPRC=0.8348
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 324.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5895 | F1=0.7050 | AUROC=0.8727 | AUPRC=0.7901
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5485 | F1=0.7637 | AUROC=0.8494 | AUPRC=0.8619
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3897 | F1=0.6857 | AUROC=0.7631 | AUPRC=0.7611
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5214 | F1=0.7370 | AUROC=0.8357 | AUPRC=0.8293
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']

[Epoch 01] train_loss=0.5310 | val_loss=0.4110 | val_mcc=0.5450 | val_f1=0.6369 | val_auroc=0.8551

[Epoch 02] train_loss=0.4679 | val_loss=0.3845 | val_mcc=0.5599 | val_f1=0.6484 | val_auroc=0.8684

[Epoch 03] train_loss=0.4370 | val_loss=0.4127 | val_mcc=0.5520 | val_f1=0.6423 | val_auroc=0.8768

[Epoch 04] train_loss=0.4085 | val_loss=0.3940 | val_mcc=0.5643 | val_f1=0.6518 | val_auroc=0.8869

[Epoch 05] train_loss=0.3822 | val_loss=0.3713 | val_mcc=0.5719 | val_f1=0.6581 | val_auroc=0.8908

[Epoch 06] train_loss=0.3531 | val_loss=0.3665 | val_mcc=0.5765 | val_f1=0.6618 | val_auroc=0.8924

[Epoch 07] train_loss=0.3228 | val_loss=0.3854 | val_mcc=0.5674 | val_f1=0.6546 | val_auroc=0.8891

[Epoch 08] train_loss=0.2976 | val_loss=0.4010 | val_mcc=0.5527 | val_f1=0.6432 | val_auroc=0.8811

[Epoch 09] train_loss=0.2713 | val_loss=0.3991 | val_mcc=0.5679 | val_f1=0.6550 | val_auroc=0.8882

[Epoch 10] train_loss=0.2397 | val_loss=0.4640 | val_mcc=0.5544 | val_f1=0.6440 | val_auroc=0.8847

[Epoch 11] train_loss=0.1997 | val_loss=0.4788 | val_mcc=0.5386 | val_f1=0.6316 | val_auroc=0.8782

[Epoch 12] train_loss=0.1819 | val_loss=0.4975 | val_mcc=0.5431 | val_f1=0.6350 | val_auroc=0.8781
[EarlyStop] epoch=12 | best_val_mcc=0.5765
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6425 | F1=0.7428 | AUROC=0.9041 | AUPRC=0.8116
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5933 | F1=0.7912 | AUROC=0.8877 | AUPRC=0.8794
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4482 | F1=0.7165 | AUROC=0.7888 | AUPRC=0.7741
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6137 | F1=0.7892 | AUROC=0.8791 | AUPRC=0.8549
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5419 | val_loss=0.4118 | val_mcc=0.5381 | val_f1=0.6311 | val_auroc=0.8522

[Epoch 02] train_loss=0.4697 | val_loss=0.3900 | val_mcc=0.5550 | val_f1=0.6449 | val_auroc=0.8711

[Epoch 03] train_loss=0.4373 | val_loss=0.4186 | val_mcc=0.5473 | val_f1=0.6383 | val_auroc=0.8772

[Epoch 04] train_loss=0.4101 | val_loss=0.3719 | val_mcc=0.5731 | val_f1=0.6591 | val_auroc=0.8855

[Epoch 05] train_loss=0.3813 | val_loss=0.3837 | val_mcc=0.5717 | val_f1=0.6580 | val_auroc=0.8907

[Epoch 06] train_loss=0.3509 | val_loss=0.3909 | val_mcc=0.5688 | val_f1=0.6557 | val_auroc=0.8879

[Epoch 07] train_loss=0.3297 | val_loss=0.4151 | val_mcc=0.5656 | val_f1=0.6532 | val_auroc=0.8841

[Epoch 08] train_loss=0.3026 | val_loss=0.5260 | val_mcc=0.5379 | val_f1=0.6278 | val_auroc=0.8848

[Epoch 09] train_loss=0.2623 | val_loss=0.5191 | val_mcc=0.5395 | val_f1=0.6315 | val_auroc=0.8762

[Epoch 10] train_loss=0.2407 | val_loss=0.5344 | val_mcc=0.5486 | val_f1=0.6393 | val_auroc=0.8753
[EarlyStop] epoch=10 | best_val_mcc=0.5731
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6274 | F1=0.7320 | AUROC=0.8961 | AUPRC=0.7944
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5964 | F1=0.7912 | AUROC=0.8799 | AUPRC=0.8677
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4414 | F1=0.7084 | AUROC=0.7806 | AUPRC=0.7600
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5893 | F1=0.7768 | AUROC=0.8738 | AUPRC=0.8412
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5293 | val_loss=0.3741 | val_mcc=0.5449 | val_f1=0.6345 | val_auroc=0.8603

[Epoch 02] train_loss=0.4648 | val_loss=0.3963 | val_mcc=0.5533 | val_f1=0.6437 | val_auroc=0.8722

[Epoch 03] train_loss=0.4341 | val_loss=0.3779 | val_mcc=0.5685 | val_f1=0.6555 | val_auroc=0.8835

[Epoch 04] train_loss=0.4029 | val_loss=0.3505 | val_mcc=0.5868 | val_f1=0.6693 | val_auroc=0.8897

[Epoch 05] train_loss=0.3778 | val_loss=0.3479 | val_mcc=0.5826 | val_f1=0.6661 | val_auroc=0.8903

[Epoch 06] train_loss=0.3427 | val_loss=0.3741 | val_mcc=0.5818 | val_f1=0.6659 | val_auroc=0.8934

[Epoch 07] train_loss=0.3154 | val_loss=0.4040 | val_mcc=0.5635 | val_f1=0.6516 | val_auroc=0.8859

[Epoch 08] train_loss=0.2888 | val_loss=0.4732 | val_mcc=0.5516 | val_f1=0.6418 | val_auroc=0.8826

[Epoch 09] train_loss=0.2436 | val_loss=0.4820 | val_mcc=0.5512 | val_f1=0.6416 | val_auroc=0.8788

[Epoch 10] train_loss=0.2204 | val_loss=0.4986 | val_mcc=0.5603 | val_f1=0.6491 | val_auroc=0.8781
[EarlyStop] epoch=10 | best_val_mcc=0.5868
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6468 | F1=0.7431 | AUROC=0.9049 | AUPRC=0.8111
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6075 | F1=0.7891 | AUROC=0.8900 | AUPRC=0.8828
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4461 | F1=0.7034 | AUROC=0.7841 | AUPRC=0.7602
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5980 | F1=0.7775 | AUROC=0.8778 | AUPRC=0.8549
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5287 | val_loss=0.3747 | val_mcc=0.5541 | val_f1=0.6410 | val_auroc=0.8593

[Epoch 02] train_loss=0.4626 | val_loss=0.3928 | val_mcc=0.5540 | val_f1=0.6442 | val_auroc=0.8712

[Epoch 03] train_loss=0.4307 | val_loss=0.3690 | val_mcc=0.5746 | val_f1=0.6603 | val_auroc=0.8826

[Epoch 04] train_loss=0.4017 | val_loss=0.3579 | val_mcc=0.5834 | val_f1=0.6669 | val_auroc=0.8910

[Epoch 05] train_loss=0.3731 | val_loss=0.4001 | val_mcc=0.5563 | val_f1=0.6454 | val_auroc=0.8881

[Epoch 06] train_loss=0.3458 | val_loss=0.4023 | val_mcc=0.5728 | val_f1=0.6581 | val_auroc=0.8935

[Epoch 07] train_loss=0.3124 | val_loss=0.4466 | val_mcc=0.5417 | val_f1=0.6326 | val_auroc=0.8886

[Epoch 08] train_loss=0.2832 | val_loss=0.3911 | val_mcc=0.5691 | val_f1=0.6559 | val_auroc=0.8874

[Epoch 09] train_loss=0.2445 | val_loss=0.4266 | val_mcc=0.5517 | val_f1=0.6424 | val_auroc=0.8832

[Epoch 10] train_loss=0.2217 | val_loss=0.4553 | val_mcc=0.5430 | val_f1=0.6356 | val_auroc=0.8779
[EarlyStop] epoch=10 | best_val_mcc=0.5834
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6432 | F1=0.7417 | AUROC=0.9021 | AUPRC=0.8150
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5884 | F1=0.7845 | AUROC=0.8872 | AUPRC=0.8835
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4455 | F1=0.7053 | AUROC=0.7803 | AUPRC=0.7553
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5820 | F1=0.7715 | AUROC=0.8756 | AUPRC=0.8552
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 244.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6175 | F1=0.7272 | AUROC=0.8981 | AUPRC=0.7991
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6232 | F1=0.8150 | AUROC=0.8872 | AUPRC=0.8861
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4599 | F1=0.7309 | AUROC=0.7780 | AUPRC=0.7487
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5946 | F1=0.7857 | AUROC=0.8731 | AUPRC=0.8473
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 145.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6146 | F1=0.7244 | AUROC=0.8935 | AUPRC=0.7957
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5818 | F1=0.7897 | AUROC=0.8755 | AUPRC=0.8672
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4467 | F1=0.7155 | AUROC=0.7732 | AUPRC=0.7543
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5797 | F1=0.7745 | AUROC=0.8648 | AUPRC=0.8426
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 95.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6134 | F1=0.7237 | AUROC=0.8879 | AUPRC=0.7855
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6102 | F1=0.8023 | AUROC=0.8759 | AUPRC=0.8739
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4405 | F1=0.7142 | AUROC=0.7771 | AUPRC=0.7570
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5823 | F1=0.7757 | AUROC=0.8571 | AUPRC=0.8372
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 90.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6281 | F1=0.7338 | AUROC=0.8924 | AUPRC=0.7976
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5960 | F1=0.7936 | AUROC=0.8807 | AUPRC=0.8782
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4569 | F1=0.7241 | AUROC=0.7753 | AUPRC=0.7510
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5840 | F1=0.7772 | AUROC=0.8672 | AUPRC=0.8440
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5699 | val_loss=0.4452 | val_mcc=0.4741 | val_f1=0.5761 | val_auroc=0.8107

[Epoch 02] train_loss=0.5140 | val_loss=0.4497 | val_mcc=0.4887 | val_f1=0.5912 | val_auroc=0.8267

[Epoch 03] train_loss=0.4864 | val_loss=0.4860 | val_mcc=0.4940 | val_f1=0.5978 | val_auroc=0.8445

[Epoch 04] train_loss=0.4565 | val_loss=0.3980 | val_mcc=0.5294 | val_f1=0.6240 | val_auroc=0.8629

[Epoch 05] train_loss=0.4238 | val_loss=0.3957 | val_mcc=0.5408 | val_f1=0.6336 | val_auroc=0.8718

[Epoch 06] train_loss=0.3948 | val_loss=0.4482 | val_mcc=0.5292 | val_f1=0.6229 | val_auroc=0.8783

[Epoch 07] train_loss=0.3730 | val_loss=0.3849 | val_mcc=0.5468 | val_f1=0.6383 | val_auroc=0.8831

[Epoch 08] train_loss=0.3466 | val_loss=0.4498 | val_mcc=0.5247 | val_f1=0.6193 | val_auroc=0.8821

[Epoch 09] train_loss=0.3239 | val_loss=0.4147 | val_mcc=0.5363 | val_f1=0.6305 | val_auroc=0.8802

[Epoch 10] train_loss=0.2974 | val_loss=0.4221 | val_mcc=0.5250 | val_f1=0.6217 | val_auroc=0.8741

[Epoch 11] train_loss=0.2807 | val_loss=0.5129 | val_mcc=0.5077 | val_f1=0.6051 | val_auroc=0.8738

[Epoch 12] train_loss=0.2415 | val_loss=0.4645 | val_mcc=0.5282 | val_f1=0.6239 | val_auroc=0.8738

[Epoch 13] train_loss=0.2262 | val_loss=0.5128 | val_mcc=0.5077 | val_f1=0.6069 | val_auroc=0.8689
[EarlyStop] epoch=13 | best_val_mcc=0.5468
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5871 | F1=0.7011 | AUROC=0.8826 | AUPRC=0.7802
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5750 | F1=0.7748 | AUROC=0.8571 | AUPRC=0.8475
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3896 | F1=0.6872 | AUROC=0.7591 | AUPRC=0.7437
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5123 | F1=0.7246 | AUROC=0.8308 | AUPRC=0.8060
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5708 | val_loss=0.4898 | val_mcc=0.4650 | val_f1=0.5741 | val_auroc=0.8119

[Epoch 02] train_loss=0.5146 | val_loss=0.5215 | val_mcc=0.4792 | val_f1=0.5865 | val_auroc=0.8308

[Epoch 03] train_loss=0.4847 | val_loss=0.3979 | val_mcc=0.5279 | val_f1=0.6174 | val_auroc=0.8511

[Epoch 04] train_loss=0.4542 | val_loss=0.3638 | val_mcc=0.5395 | val_f1=0.6272 | val_auroc=0.8667

[Epoch 05] train_loss=0.4237 | val_loss=0.3770 | val_mcc=0.5395 | val_f1=0.6317 | val_auroc=0.8755

[Epoch 06] train_loss=0.3994 | val_loss=0.4460 | val_mcc=0.5279 | val_f1=0.6233 | val_auroc=0.8780

[Epoch 07] train_loss=0.3735 | val_loss=0.4812 | val_mcc=0.5244 | val_f1=0.6186 | val_auroc=0.8798

[Epoch 08] train_loss=0.3446 | val_loss=0.4390 | val_mcc=0.5347 | val_f1=0.6286 | val_auroc=0.8783

[Epoch 09] train_loss=0.3124 | val_loss=0.4197 | val_mcc=0.5340 | val_f1=0.6284 | val_auroc=0.8763

[Epoch 10] train_loss=0.2955 | val_loss=0.4352 | val_mcc=0.5310 | val_f1=0.6263 | val_auroc=0.8725
[EarlyStop] epoch=10 | best_val_mcc=0.5395
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5920 | F1=0.6930 | AUROC=0.8738 | AUPRC=0.7709
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5564 | F1=0.7539 | AUROC=0.8633 | AUPRC=0.8443
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3841 | F1=0.6590 | AUROC=0.7519 | AUPRC=0.7404
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5087 | F1=0.7005 | AUROC=0.8306 | AUPRC=0.8020
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5676 | val_loss=0.4852 | val_mcc=0.4715 | val_f1=0.5793 | val_auroc=0.8154

[Epoch 02] train_loss=0.5061 | val_loss=0.3973 | val_mcc=0.4988 | val_f1=0.5928 | val_auroc=0.8330

[Epoch 03] train_loss=0.4772 | val_loss=0.4472 | val_mcc=0.5123 | val_f1=0.6119 | val_auroc=0.8566

[Epoch 04] train_loss=0.4434 | val_loss=0.4095 | val_mcc=0.5378 | val_f1=0.6316 | val_auroc=0.8735

[Epoch 05] train_loss=0.4159 | val_loss=0.3740 | val_mcc=0.5454 | val_f1=0.6365 | val_auroc=0.8782

[Epoch 06] train_loss=0.3903 | val_loss=0.3806 | val_mcc=0.5441 | val_f1=0.6358 | val_auroc=0.8795

[Epoch 07] train_loss=0.3698 | val_loss=0.4221 | val_mcc=0.5312 | val_f1=0.6263 | val_auroc=0.8790

[Epoch 08] train_loss=0.3460 | val_loss=0.3839 | val_mcc=0.5487 | val_f1=0.6391 | val_auroc=0.8797

[Epoch 09] train_loss=0.3199 | val_loss=0.4105 | val_mcc=0.5362 | val_f1=0.6304 | val_auroc=0.8801

[Epoch 10] train_loss=0.2882 | val_loss=0.4420 | val_mcc=0.5376 | val_f1=0.6314 | val_auroc=0.8756

[Epoch 11] train_loss=0.2690 | val_loss=0.4488 | val_mcc=0.5295 | val_f1=0.6250 | val_auroc=0.8700

[Epoch 12] train_loss=0.2471 | val_loss=0.4593 | val_mcc=0.5252 | val_f1=0.6211 | val_auroc=0.8659

[Epoch 13] train_loss=0.2072 | val_loss=0.5359 | val_mcc=0.5161 | val_f1=0.6148 | val_auroc=0.8614

[Epoch 14] train_loss=0.1899 | val_loss=0.5176 | val_mcc=0.5320 | val_f1=0.6268 | val_auroc=0.8657
[EarlyStop] epoch=14 | best_val_mcc=0.5487
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5899 | F1=0.7005 | AUROC=0.8853 | AUPRC=0.7818
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5873 | F1=0.7788 | AUROC=0.8785 | AUPRC=0.8652
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4032 | F1=0.6836 | AUROC=0.7662 | AUPRC=0.7435
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5221 | F1=0.7256 | AUROC=0.8334 | AUPRC=0.8029
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5658 | val_loss=0.4618 | val_mcc=0.4689 | val_f1=0.5751 | val_auroc=0.8152

[Epoch 02] train_loss=0.5115 | val_loss=0.4368 | val_mcc=0.4976 | val_f1=0.5981 | val_auroc=0.8331

[Epoch 03] train_loss=0.4755 | val_loss=0.4040 | val_mcc=0.5247 | val_f1=0.6189 | val_auroc=0.8511

[Epoch 04] train_loss=0.4458 | val_loss=0.4044 | val_mcc=0.5336 | val_f1=0.6281 | val_auroc=0.8693

[Epoch 05] train_loss=0.4144 | val_loss=0.4080 | val_mcc=0.5365 | val_f1=0.6305 | val_auroc=0.8767

[Epoch 06] train_loss=0.3872 | val_loss=0.3888 | val_mcc=0.5484 | val_f1=0.6398 | val_auroc=0.8804

[Epoch 07] train_loss=0.3617 | val_loss=0.4387 | val_mcc=0.5305 | val_f1=0.6248 | val_auroc=0.8818

[Epoch 08] train_loss=0.3336 | val_loss=0.4078 | val_mcc=0.5226 | val_f1=0.6198 | val_auroc=0.8776

[Epoch 09] train_loss=0.3109 | val_loss=0.4020 | val_mcc=0.5230 | val_f1=0.6200 | val_auroc=0.8751

[Epoch 10] train_loss=0.2791 | val_loss=0.4580 | val_mcc=0.5188 | val_f1=0.6164 | val_auroc=0.8739

[Epoch 11] train_loss=0.2439 | val_loss=0.4631 | val_mcc=0.5248 | val_f1=0.6214 | val_auroc=0.8761

[Epoch 12] train_loss=0.2257 | val_loss=0.5052 | val_mcc=0.5078 | val_f1=0.6071 | val_auroc=0.8713
[EarlyStop] epoch=12 | best_val_mcc=0.5484
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5780 | F1=0.6961 | AUROC=0.8831 | AUPRC=0.7799
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5914 | F1=0.7857 | AUROC=0.8704 | AUPRC=0.8577
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4090 | F1=0.6988 | AUROC=0.7651 | AUPRC=0.7452
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5206 | F1=0.7309 | AUROC=0.8350 | AUPRC=0.8062
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 336.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5497 | F1=0.6793 | AUROC=0.8737 | AUPRC=0.7565
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5395 | F1=0.7712 | AUROC=0.8501 | AUPRC=0.8277
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3819 | F1=0.6916 | AUROC=0.7496 | AUPRC=0.7172
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4855 | F1=0.7211 | AUROC=0.8196 | AUPRC=0.7880
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 153.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5600 | F1=0.6842 | AUROC=0.8677 | AUPRC=0.7463
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5534 | F1=0.7708 | AUROC=0.8435 | AUPRC=0.8189
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3716 | F1=0.6774 | AUROC=0.7459 | AUPRC=0.7317
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4764 | F1=0.7053 | AUROC=0.8154 | AUPRC=0.7836
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 118.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5422 | F1=0.6711 | AUROC=0.8538 | AUPRC=0.7373
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5080 | F1=0.7460 | AUROC=0.8327 | AUPRC=0.8083
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3474 | F1=0.6677 | AUROC=0.7390 | AUPRC=0.7225
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4810 | F1=0.7119 | AUROC=0.8063 | AUPRC=0.7788
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 157.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5464 | F1=0.6740 | AUROC=0.8626 | AUPRC=0.7485
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5136 | F1=0.7496 | AUROC=0.8429 | AUPRC=0.8263
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3776 | F1=0.6810 | AUROC=0.7485 | AUPRC=0.7288
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.4918 | F1=0.7167 | AUROC=0.8203 | AUPRC=0.7830
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']

[Epoch 01] train_loss=0.5657 | val_loss=0.3971 | val_mcc=0.5546 | val_f1=0.6170 | val_auroc=0.8252

[Epoch 02] train_loss=0.4984 | val_loss=0.5071 | val_mcc=0.5138 | val_f1=0.6129 | val_auroc=0.8381

[Epoch 03] train_loss=0.4848 | val_loss=0.3959 | val_mcc=0.5754 | val_f1=0.6556 | val_auroc=0.8459

[Epoch 04] train_loss=0.4686 | val_loss=0.3890 | val_mcc=0.5749 | val_f1=0.6562 | val_auroc=0.8507

[Epoch 05] train_loss=0.4571 | val_loss=0.4250 | val_mcc=0.5602 | val_f1=0.6484 | val_auroc=0.8542

[Epoch 06] train_loss=0.4492 | val_loss=0.4511 | val_mcc=0.5405 | val_f1=0.6336 | val_auroc=0.8572

[Epoch 07] train_loss=0.4368 | val_loss=0.3553 | val_mcc=0.5875 | val_f1=0.6664 | val_auroc=0.8627

[Epoch 08] train_loss=0.4271 | val_loss=0.4235 | val_mcc=0.5542 | val_f1=0.6443 | val_auroc=0.8679

[Epoch 09] train_loss=0.4179 | val_loss=0.4216 | val_mcc=0.5603 | val_f1=0.6491 | val_auroc=0.8702

[Epoch 10] train_loss=0.4053 | val_loss=0.3479 | val_mcc=0.5881 | val_f1=0.6673 | val_auroc=0.8693

[Epoch 11] train_loss=0.3938 | val_loss=0.3601 | val_mcc=0.5822 | val_f1=0.6656 | val_auroc=0.8729

[Epoch 12] train_loss=0.3785 | val_loss=0.4124 | val_mcc=0.5594 | val_f1=0.6483 | val_auroc=0.8756

[Epoch 13] train_loss=0.3639 | val_loss=0.4072 | val_mcc=0.5552 | val_f1=0.6449 | val_auroc=0.8771

[Epoch 14] train_loss=0.3484 | val_loss=0.3846 | val_mcc=0.5610 | val_f1=0.6496 | val_auroc=0.8779

[Epoch 15] train_loss=0.3225 | val_loss=0.4002 | val_mcc=0.5547 | val_f1=0.6447 | val_auroc=0.8772

[Epoch 16] train_loss=0.3097 | val_loss=0.3993 | val_mcc=0.5543 | val_f1=0.6444 | val_auroc=0.8789
[EarlyStop] epoch=16 | best_val_mcc=0.5881
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6084 | F1=0.7091 | AUROC=0.8661 | AUPRC=0.7923
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5747 | F1=0.7618 | AUROC=0.8587 | AUPRC=0.8655
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3752 | F1=0.6535 | AUROC=0.7457 | AUPRC=0.7467
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5373 | F1=0.7265 | AUROC=0.8325 | AUPRC=0.8316
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5693 | val_loss=0.4507 | val_mcc=0.5455 | val_f1=0.6320 | val_auroc=0.8266

[Epoch 02] train_loss=0.4997 | val_loss=0.3745 | val_mcc=0.5842 | val_f1=0.6518 | val_auroc=0.8410

[Epoch 03] train_loss=0.4806 | val_loss=0.4405 | val_mcc=0.5650 | val_f1=0.6511 | val_auroc=0.8481

[Epoch 04] train_loss=0.4684 | val_loss=0.4130 | val_mcc=0.5702 | val_f1=0.6551 | val_auroc=0.8532

[Epoch 05] train_loss=0.4596 | val_loss=0.4134 | val_mcc=0.5654 | val_f1=0.6520 | val_auroc=0.8571

[Epoch 06] train_loss=0.4492 | val_loss=0.4440 | val_mcc=0.5459 | val_f1=0.6379 | val_auroc=0.8598

[Epoch 07] train_loss=0.4384 | val_loss=0.3924 | val_mcc=0.5727 | val_f1=0.6578 | val_auroc=0.8630

[Epoch 08] train_loss=0.4319 | val_loss=0.3746 | val_mcc=0.5819 | val_f1=0.6637 | val_auroc=0.8630
[EarlyStop] epoch=8 | best_val_mcc=0.5842
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6030 | F1=0.6903 | AUROC=0.8452 | AUPRC=0.7719
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5357 | F1=0.7116 | AUROC=0.8183 | AUPRC=0.8482
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3772 | F1=0.6269 | AUROC=0.7313 | AUPRC=0.7420
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5150 | F1=0.6940 | AUROC=0.8046 | AUPRC=0.8175
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5666 | val_loss=0.3665 | val_mcc=0.5522 | val_f1=0.6103 | val_auroc=0.8268

[Epoch 02] train_loss=0.4964 | val_loss=0.4024 | val_mcc=0.5784 | val_f1=0.6548 | val_auroc=0.8427

[Epoch 03] train_loss=0.4786 | val_loss=0.3699 | val_mcc=0.5834 | val_f1=0.6534 | val_auroc=0.8518

[Epoch 04] train_loss=0.4668 | val_loss=0.3407 | val_mcc=0.5867 | val_f1=0.6599 | val_auroc=0.8584

[Epoch 05] train_loss=0.4546 | val_loss=0.3942 | val_mcc=0.5744 | val_f1=0.6586 | val_auroc=0.8643

[Epoch 06] train_loss=0.4474 | val_loss=0.4209 | val_mcc=0.5582 | val_f1=0.6472 | val_auroc=0.8655

[Epoch 07] train_loss=0.4378 | val_loss=0.3653 | val_mcc=0.5794 | val_f1=0.6617 | val_auroc=0.8652

[Epoch 08] train_loss=0.4283 | val_loss=0.3477 | val_mcc=0.5921 | val_f1=0.6680 | val_auroc=0.8633

[Epoch 09] train_loss=0.4233 | val_loss=0.3252 | val_mcc=0.5957 | val_f1=0.6664 | val_auroc=0.8681

[Epoch 10] train_loss=0.4090 | val_loss=0.3291 | val_mcc=0.5949 | val_f1=0.6689 | val_auroc=0.8681

[Epoch 11] train_loss=0.3975 | val_loss=0.3427 | val_mcc=0.5932 | val_f1=0.6711 | val_auroc=0.8721

[Epoch 12] train_loss=0.3795 | val_loss=0.3294 | val_mcc=0.5972 | val_f1=0.6728 | val_auroc=0.8740

[Epoch 13] train_loss=0.3690 | val_loss=0.3663 | val_mcc=0.5757 | val_f1=0.6606 | val_auroc=0.8762

[Epoch 14] train_loss=0.3475 | val_loss=0.3886 | val_mcc=0.5618 | val_f1=0.6502 | val_auroc=0.8719

[Epoch 15] train_loss=0.3300 | val_loss=0.4492 | val_mcc=0.5357 | val_f1=0.6286 | val_auroc=0.8743

[Epoch 16] train_loss=0.3064 | val_loss=0.3826 | val_mcc=0.5709 | val_f1=0.6557 | val_auroc=0.8650

[Epoch 17] train_loss=0.2706 | val_loss=0.4388 | val_mcc=0.5475 | val_f1=0.6392 | val_auroc=0.8648

[Epoch 18] train_loss=0.2551 | val_loss=0.4622 | val_mcc=0.5358 | val_f1=0.6299 | val_auroc=0.8651
[EarlyStop] epoch=18 | best_val_mcc=0.5972
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6035 | F1=0.7035 | AUROC=0.8713 | AUPRC=0.7901
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5370 | F1=0.7357 | AUROC=0.8603 | AUPRC=0.8657
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3867 | F1=0.6521 | AUROC=0.7543 | AUPRC=0.7568
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5349 | F1=0.7236 | AUROC=0.8363 | AUPRC=0.8314
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5621 | val_loss=0.3719 | val_mcc=0.5566 | val_f1=0.6144 | val_auroc=0.8277

[Epoch 02] train_loss=0.4949 | val_loss=0.4144 | val_mcc=0.5671 | val_f1=0.6481 | val_auroc=0.8399

[Epoch 03] train_loss=0.4770 | val_loss=0.3951 | val_mcc=0.5808 | val_f1=0.6602 | val_auroc=0.8488

[Epoch 04] train_loss=0.4639 | val_loss=0.3866 | val_mcc=0.5755 | val_f1=0.6570 | val_auroc=0.8527

[Epoch 05] train_loss=0.4518 | val_loss=0.3552 | val_mcc=0.5894 | val_f1=0.6646 | val_auroc=0.8591

[Epoch 06] train_loss=0.4416 | val_loss=0.3860 | val_mcc=0.5753 | val_f1=0.6588 | val_auroc=0.8629

[Epoch 07] train_loss=0.4301 | val_loss=0.3536 | val_mcc=0.5857 | val_f1=0.6649 | val_auroc=0.8657

[Epoch 08] train_loss=0.4214 | val_loss=0.3570 | val_mcc=0.5804 | val_f1=0.6633 | val_auroc=0.8701

[Epoch 09] train_loss=0.4070 | val_loss=0.3732 | val_mcc=0.5777 | val_f1=0.6623 | val_auroc=0.8722

[Epoch 10] train_loss=0.3919 | val_loss=0.3844 | val_mcc=0.5684 | val_f1=0.6554 | val_auroc=0.8748

[Epoch 11] train_loss=0.3822 | val_loss=0.3515 | val_mcc=0.5838 | val_f1=0.6665 | val_auroc=0.8749
[EarlyStop] epoch=11 | best_val_mcc=0.5894
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6154 | F1=0.7094 | AUROC=0.8561 | AUPRC=0.7863
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5669 | F1=0.7455 | AUROC=0.8340 | AUPRC=0.8594
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3726 | F1=0.6407 | AUROC=0.7373 | AUPRC=0.7476
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5291 | F1=0.7156 | AUROC=0.8177 | AUPRC=0.8254
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 335.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5841 | F1=0.7017 | AUROC=0.8828 | AUPRC=0.7961
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5544 | F1=0.7660 | AUROC=0.8746 | AUPRC=0.8769
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3885 | F1=0.6827 | AUROC=0.7504 | AUPRC=0.7480
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5513 | F1=0.7521 | AUROC=0.8504 | AUPRC=0.8421
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 300.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6073 | F1=0.7168 | AUROC=0.8828 | AUPRC=0.8032
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5995 | F1=0.7917 | AUROC=0.8628 | AUPRC=0.8766
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3823 | F1=0.6811 | AUROC=0.7495 | AUPRC=0.7504
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5420 | F1=0.7485 | AUROC=0.8451 | AUPRC=0.8380
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 188.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5958 | F1=0.7090 | AUROC=0.8748 | AUPRC=0.7939
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5658 | F1=0.7720 | AUROC=0.8523 | AUPRC=0.8654
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3733 | F1=0.6760 | AUROC=0.7477 | AUPRC=0.7431
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5292 | F1=0.7392 | AUROC=0.8365 | AUPRC=0.8375
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 263.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5905 | F1=0.7046 | AUROC=0.8692 | AUPRC=0.7920
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5475 | F1=0.7568 | AUROC=0.8511 | AUPRC=0.8663
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3736 | F1=0.6739 | AUROC=0.7404 | AUPRC=0.7450
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5459 | F1=0.7494 | AUROC=0.8339 | AUPRC=0.8365
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']

[Epoch 01] train_loss=0.7024 | val_loss=0.6512 | val_mcc=0.0604 | val_f1=0.2466 | val_auroc=0.5567

[Epoch 02] train_loss=0.6929 | val_loss=0.6856 | val_mcc=0.0700 | val_f1=0.3117 | val_auroc=0.5699

[Epoch 03] train_loss=0.6874 | val_loss=0.6997 | val_mcc=0.0761 | val_f1=0.3222 | val_auroc=0.5723

[Epoch 04] train_loss=0.6843 | val_loss=0.6830 | val_mcc=0.0720 | val_f1=0.3120 | val_auroc=0.5689

[Epoch 05] train_loss=0.6808 | val_loss=0.6504 | val_mcc=0.0743 | val_f1=0.2891 | val_auroc=0.5774

[Epoch 06] train_loss=0.6757 | val_loss=0.6573 | val_mcc=0.0874 | val_f1=0.3090 | val_auroc=0.5814

[Epoch 07] train_loss=0.6708 | val_loss=0.5961 | val_mcc=0.0779 | val_f1=0.2303 | val_auroc=0.5865

[Epoch 08] train_loss=0.6646 | val_loss=0.6581 | val_mcc=0.1149 | val_f1=0.3310 | val_auroc=0.6032

[Epoch 09] train_loss=0.6559 | val_loss=0.6627 | val_mcc=0.1290 | val_f1=0.3442 | val_auroc=0.6073

[Epoch 10] train_loss=0.6436 | val_loss=0.6940 | val_mcc=0.1365 | val_f1=0.3535 | val_auroc=0.6197

[Epoch 11] train_loss=0.6311 | val_loss=0.6901 | val_mcc=0.1477 | val_f1=0.3587 | val_auroc=0.6269

[Epoch 12] train_loss=0.6163 | val_loss=0.6508 | val_mcc=0.1501 | val_f1=0.3528 | val_auroc=0.6326

[Epoch 13] train_loss=0.5996 | val_loss=0.7270 | val_mcc=0.1535 | val_f1=0.3639 | val_auroc=0.6321

[Epoch 14] train_loss=0.5794 | val_loss=0.6826 | val_mcc=0.1511 | val_f1=0.3573 | val_auroc=0.6282

[Epoch 15] train_loss=0.5543 | val_loss=0.6551 | val_mcc=0.1427 | val_f1=0.3468 | val_auroc=0.6277

[Epoch 16] train_loss=0.5350 | val_loss=0.6684 | val_mcc=0.1425 | val_f1=0.3445 | val_auroc=0.6286

[Epoch 17] train_loss=0.5097 | val_loss=0.7575 | val_mcc=0.1462 | val_f1=0.3558 | val_auroc=0.6280

[Epoch 18] train_loss=0.4674 | val_loss=0.7638 | val_mcc=0.1407 | val_f1=0.3502 | val_auroc=0.6222

[Epoch 19] train_loss=0.4466 | val_loss=0.8467 | val_mcc=0.1325 | val_f1=0.3494 | val_auroc=0.6205
[EarlyStop] epoch=19 | best_val_mcc=0.1535
[Test] train3__val_mean_dna_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.1574 | F1=0.4478 | AUROC=0.6229 | AUPRC=0.3688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.1912 | F1=0.6247 | AUROC=0.6304 | AUPRC=0.6124
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.0717 | F1=0.5868 | AUROC=0.5419 | AUPRC=0.5298
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.1408 | F1=0.5858 | AUROC=0.5933 | AUPRC=0.5361
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 36.
[Test] train3__val_mean_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.0510 | F1=0.3695 | AUROC=0.5475 | AUPRC=0.3101
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.0493 | F1=0.5074 | AUROC=0.5494 | AUPRC=0.5497
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.0006 | F1=0.4924 | AUROC=0.4974 | AUPRC=0.5019
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.0639 | F1=0.5033 | AUROC=0.5483 | AUPRC=0.4970
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 55.
[Test] train3__val_mean_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.0655 | F1=0.3830 | AUROC=0.5572 | AUPRC=0.3160
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.0927 | F1=0.5488 | AUROC=0.5685 | AUPRC=0.5568
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.0323 | F1=0.5197 | AUROC=0.5193 | AUPRC=0.5119
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.0738 | F1=0.5223 | AUROC=0.5352 | AUPRC=0.4857
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.5269 | val_loss=0.4156 | val_mcc=0.5357 | val_f1=0.6300 | val_auroc=0.8595

[Epoch 02] train_loss=0.4640 | val_loss=0.3545 | val_mcc=0.5741 | val_f1=0.6577 | val_auroc=0.8722

[Epoch 03] train_loss=0.4342 | val_loss=0.3804 | val_mcc=0.5680 | val_f1=0.6551 | val_auroc=0.8828

[Epoch 04] train_loss=0.4099 | val_loss=0.3802 | val_mcc=0.5694 | val_f1=0.6558 | val_auroc=0.8885

[Epoch 05] train_loss=0.3855 | val_loss=0.4095 | val_mcc=0.5552 | val_f1=0.6436 | val_auroc=0.8882

[Epoch 06] train_loss=0.3638 | val_loss=0.4094 | val_mcc=0.5549 | val_f1=0.6432 | val_auroc=0.8910

[Epoch 07] train_loss=0.3373 | val_loss=0.3755 | val_mcc=0.5767 | val_f1=0.6617 | val_auroc=0.8917

[Epoch 08] train_loss=0.3196 | val_loss=0.3938 | val_mcc=0.5656 | val_f1=0.6529 | val_auroc=0.8905

[Epoch 09] train_loss=0.3045 | val_loss=0.3712 | val_mcc=0.5793 | val_f1=0.6639 | val_auroc=0.8910

[Epoch 10] train_loss=0.2906 | val_loss=0.4156 | val_mcc=0.5638 | val_f1=0.6508 | val_auroc=0.8891

[Epoch 11] train_loss=0.2766 | val_loss=0.4237 | val_mcc=0.5581 | val_f1=0.6466 | val_auroc=0.8883

[Epoch 12] train_loss=0.2589 | val_loss=0.4033 | val_mcc=0.5596 | val_f1=0.6486 | val_auroc=0.8833

[Epoch 13] train_loss=0.2460 | val_loss=0.4100 | val_mcc=0.5619 | val_f1=0.6503 | val_auroc=0.8825

[Epoch 14] train_loss=0.2252 | val_loss=0.4739 | val_mcc=0.5399 | val_f1=0.6322 | val_auroc=0.8799

[Epoch 15] train_loss=0.2163 | val_loss=0.4633 | val_mcc=0.5529 | val_f1=0.6424 | val_auroc=0.8828
[EarlyStop] epoch=15 | best_val_mcc=0.5793
[Test] train3__val_mean_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6415 | F1=0.7421 | AUROC=0.9060 | AUPRC=0.8112
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6192 | F1=0.8029 | AUROC=0.8907 | AUPRC=0.8794
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4530 | F1=0.7168 | AUROC=0.7879 | AUPRC=0.7687
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_prot_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5877 | F1=0.7752 | AUROC=0.8746 | AUPRC=0.8473
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 192.
[Test] train3__val_mean_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6171 | F1=0.7268 | AUROC=0.9037 | AUPRC=0.8063
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6069 | F1=0.8083 | AUROC=0.8926 | AUPRC=0.8868
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4359 | F1=0.7177 | AUROC=0.7806 | AUPRC=0.7628
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_prot_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5755 | F1=0.7770 | AUROC=0.8757 | AUPRC=0.8509
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 196.
[Test] train3__val_mean_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6136 | F1=0.7238 | AUROC=0.8976 | AUPRC=0.8027
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5961 | F1=0.7971 | AUROC=0.8820 | AUPRC=0.8800
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4406 | F1=0.7137 | AUROC=0.7762 | AUPRC=0.7647
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_prot_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5928 | F1=0.7806 | AUROC=0.8732 | AUPRC=0.8490
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4858 | val_loss=0.5748 | val_mcc=0.4528 | val_f1=0.5554 | val_auroc=0.8681

[Epoch 02] train_loss=0.4248 | val_loss=0.5410 | val_mcc=0.4779 | val_f1=0.5775 | val_auroc=0.8709

[Epoch 03] train_loss=0.4047 | val_loss=0.6116 | val_mcc=0.4288 | val_f1=0.5334 | val_auroc=0.8715

[Epoch 04] train_loss=0.3905 | val_loss=0.6745 | val_mcc=0.3756 | val_f1=0.4877 | val_auroc=0.8720

[Epoch 05] train_loss=0.3687 | val_loss=0.6459 | val_mcc=0.4076 | val_f1=0.5141 | val_auroc=0.8715

[Epoch 06] train_loss=0.3494 | val_loss=0.6583 | val_mcc=0.4158 | val_f1=0.5181 | val_auroc=0.8761

[Epoch 07] train_loss=0.3242 | val_loss=0.6113 | val_mcc=0.4477 | val_f1=0.5460 | val_auroc=0.8765

[Epoch 08] train_loss=0.3084 | val_loss=0.5350 | val_mcc=0.4788 | val_f1=0.5777 | val_auroc=0.8726

[Epoch 09] train_loss=0.2931 | val_loss=0.5968 | val_mcc=0.4603 | val_f1=0.5584 | val_auroc=0.8787

[Epoch 10] train_loss=0.2755 | val_loss=0.5323 | val_mcc=0.4784 | val_f1=0.5797 | val_auroc=0.8693

[Epoch 11] train_loss=0.2622 | val_loss=0.5591 | val_mcc=0.4697 | val_f1=0.5718 | val_auroc=0.8640

[Epoch 12] train_loss=0.2437 | val_loss=0.6166 | val_mcc=0.4550 | val_f1=0.5585 | val_auroc=0.8680

[Epoch 13] train_loss=0.2239 | val_loss=0.6112 | val_mcc=0.4547 | val_f1=0.5602 | val_auroc=0.8588

[Epoch 14] train_loss=0.2147 | val_loss=0.6023 | val_mcc=0.4718 | val_f1=0.5738 | val_auroc=0.8667
[EarlyStop] epoch=14 | best_val_mcc=0.4788
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5509 | F1=0.6809 | AUROC=0.8861 | AUPRC=0.7797
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5735 | F1=0.7984 | AUROC=0.8684 | AUPRC=0.8570
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4020 | F1=0.7229 | AUROC=0.7682 | AUPRC=0.7536
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5709 | F1=0.7804 | AUROC=0.8620 | AUPRC=0.8296
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4975 | val_loss=0.5913 | val_mcc=0.4378 | val_f1=0.5432 | val_auroc=0.8646

[Epoch 02] train_loss=0.4284 | val_loss=0.5747 | val_mcc=0.4605 | val_f1=0.5615 | val_auroc=0.8686

[Epoch 03] train_loss=0.4055 | val_loss=0.4926 | val_mcc=0.5193 | val_f1=0.6139 | val_auroc=0.8717

[Epoch 04] train_loss=0.3896 | val_loss=0.4948 | val_mcc=0.5256 | val_f1=0.6170 | val_auroc=0.8806

[Epoch 05] train_loss=0.3667 | val_loss=0.5222 | val_mcc=0.5125 | val_f1=0.6033 | val_auroc=0.8810

[Epoch 06] train_loss=0.3413 | val_loss=0.5088 | val_mcc=0.5063 | val_f1=0.6023 | val_auroc=0.8700

[Epoch 07] train_loss=0.3143 | val_loss=0.4050 | val_mcc=0.5553 | val_f1=0.6449 | val_auroc=0.8755

[Epoch 08] train_loss=0.2922 | val_loss=0.5361 | val_mcc=0.4951 | val_f1=0.5946 | val_auroc=0.8609

[Epoch 09] train_loss=0.2664 | val_loss=0.6263 | val_mcc=0.4852 | val_f1=0.5815 | val_auroc=0.8712

[Epoch 10] train_loss=0.2404 | val_loss=0.4875 | val_mcc=0.4987 | val_f1=0.5999 | val_auroc=0.8453

[Epoch 11] train_loss=0.2182 | val_loss=0.5916 | val_mcc=0.4787 | val_f1=0.5844 | val_auroc=0.8480

[Epoch 12] train_loss=0.1773 | val_loss=0.6771 | val_mcc=0.4959 | val_f1=0.5980 | val_auroc=0.8518

[Epoch 13] train_loss=0.1615 | val_loss=0.8074 | val_mcc=0.4770 | val_f1=0.5808 | val_auroc=0.8473
[EarlyStop] epoch=13 | best_val_mcc=0.5553
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5996 | F1=0.7108 | AUROC=0.8839 | AUPRC=0.7521
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5608 | F1=0.7669 | AUROC=0.8660 | AUPRC=0.8456
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4217 | F1=0.6989 | AUROC=0.7728 | AUPRC=0.7484
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5690 | F1=0.7555 | AUROC=0.8624 | AUPRC=0.8253
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4870 | val_loss=0.5106 | val_mcc=0.4959 | val_f1=0.5955 | val_auroc=0.8637

[Epoch 02] train_loss=0.4263 | val_loss=0.4634 | val_mcc=0.5351 | val_f1=0.6289 | val_auroc=0.8681

[Epoch 03] train_loss=0.4063 | val_loss=0.4732 | val_mcc=0.5267 | val_f1=0.6210 | val_auroc=0.8726

[Epoch 04] train_loss=0.3880 | val_loss=0.4409 | val_mcc=0.5473 | val_f1=0.6381 | val_auroc=0.8771

[Epoch 05] train_loss=0.3688 | val_loss=0.3860 | val_mcc=0.5561 | val_f1=0.6448 | val_auroc=0.8758

[Epoch 06] train_loss=0.3466 | val_loss=0.3691 | val_mcc=0.5738 | val_f1=0.6593 | val_auroc=0.8853

[Epoch 07] train_loss=0.3178 | val_loss=0.4052 | val_mcc=0.5470 | val_f1=0.6388 | val_auroc=0.8704

[Epoch 08] train_loss=0.2933 | val_loss=0.4859 | val_mcc=0.5266 | val_f1=0.6207 | val_auroc=0.8724

[Epoch 09] train_loss=0.2652 | val_loss=0.6358 | val_mcc=0.4727 | val_f1=0.5752 | val_auroc=0.8578

[Epoch 10] train_loss=0.2381 | val_loss=0.5570 | val_mcc=0.5024 | val_f1=0.6035 | val_auroc=0.8546

[Epoch 11] train_loss=0.1952 | val_loss=0.6362 | val_mcc=0.4935 | val_f1=0.5959 | val_auroc=0.8555

[Epoch 12] train_loss=0.1816 | val_loss=0.6993 | val_mcc=0.4898 | val_f1=0.5923 | val_auroc=0.8538
[EarlyStop] epoch=12 | best_val_mcc=0.5738
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6293 | F1=0.7322 | AUROC=0.8983 | AUPRC=0.7913
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5912 | F1=0.7864 | AUROC=0.8767 | AUPRC=0.8580
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4267 | F1=0.6987 | AUROC=0.7742 | AUPRC=0.7579
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5996 | F1=0.7798 | AUROC=0.8778 | AUPRC=0.8448
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4756 | val_loss=0.3879 | val_mcc=0.5626 | val_f1=0.6488 | val_auroc=0.8689

[Epoch 02] train_loss=0.4197 | val_loss=0.3615 | val_mcc=0.5808 | val_f1=0.6596 | val_auroc=0.8729

[Epoch 03] train_loss=0.3989 | val_loss=0.3493 | val_mcc=0.5880 | val_f1=0.6638 | val_auroc=0.8815

[Epoch 04] train_loss=0.3816 | val_loss=0.3476 | val_mcc=0.5793 | val_f1=0.6590 | val_auroc=0.8829

[Epoch 05] train_loss=0.3644 | val_loss=0.3369 | val_mcc=0.5958 | val_f1=0.6737 | val_auroc=0.8873

[Epoch 06] train_loss=0.3360 | val_loss=0.3770 | val_mcc=0.5463 | val_f1=0.6373 | val_auroc=0.8750

[Epoch 07] train_loss=0.3106 | val_loss=0.3496 | val_mcc=0.5587 | val_f1=0.6446 | val_auroc=0.8788

[Epoch 08] train_loss=0.2833 | val_loss=0.4214 | val_mcc=0.5295 | val_f1=0.6247 | val_auroc=0.8760

[Epoch 09] train_loss=0.2555 | val_loss=0.4397 | val_mcc=0.5200 | val_f1=0.6178 | val_auroc=0.8687

[Epoch 10] train_loss=0.2107 | val_loss=0.5268 | val_mcc=0.4877 | val_f1=0.5905 | val_auroc=0.8609

[Epoch 11] train_loss=0.1937 | val_loss=0.6297 | val_mcc=0.4744 | val_f1=0.5751 | val_auroc=0.8690
[EarlyStop] epoch=11 | best_val_mcc=0.5958
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6190 | F1=0.7166 | AUROC=0.8963 | AUPRC=0.7995
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5784 | F1=0.7622 | AUROC=0.8809 | AUPRC=0.8730
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4142 | F1=0.6765 | AUROC=0.7746 | AUPRC=0.7526
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5563 | F1=0.7400 | AUROC=0.8681 | AUPRC=0.8345
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 97.
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6632 | F1=0.7577 | AUROC=0.9121 | AUPRC=0.8436
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5934 | F1=0.7972 | AUROC=0.8877 | AUPRC=0.8921
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4377 | F1=0.7113 | AUROC=0.7870 | AUPRC=0.7736
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6100 | F1=0.7912 | AUROC=0.8914 | AUPRC=0.8828
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 0.
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.0192 | F1=0.4280 | AUROC=0.5933 | AUPRC=0.3318
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.0000 | F1=0.6622 | AUROC=0.6438 | AUPRC=0.6017
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.0273 | F1=0.6653 | AUROC=0.5687 | AUPRC=0.5480
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=-0.0032 | F1=0.6265 | AUROC=0.5810 | AUPRC=0.5159
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 7.
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5093 | F1=0.6533 | AUROC=0.8609 | AUPRC=0.7307
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5060 | F1=0.7674 | AUROC=0.8458 | AUPRC=0.8327
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3902 | F1=0.7164 | AUROC=0.7535 | AUPRC=0.7364
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5236 | F1=0.7583 | AUROC=0.8372 | AUPRC=0.7962
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 0.
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.2401 | F1=0.4928 | AUROC=0.8021 | AUPRC=0.6279
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.3594 | F1=0.7222 | AUROC=0.7992 | AUPRC=0.7656
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.1950 | F1=0.6710 | AUROC=0.6985 | AUPRC=0.6637
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.3877 | val_loss=0.2076 | val_mcc=0.7468 | val_f1=0.7959 | val_auroc=0.9578

[Epoch 02] train_loss=0.2957 | val_loss=0.2296 | val_mcc=0.7358 | val_f1=0.7862 | val_auroc=0.9618

[Epoch 03] train_loss=0.2738 | val_loss=0.1998 | val_mcc=0.7604 | val_f1=0.8072 | val_auroc=0.9614

[Epoch 04] train_loss=0.2599 | val_loss=0.2387 | val_mcc=0.7357 | val_f1=0.7851 | val_auroc=0.9637

[Epoch 05] train_loss=0.2421 | val_loss=0.1920 | val_mcc=0.7615 | val_f1=0.8077 | val_auroc=0.9635

[Epoch 06] train_loss=0.2268 | val_loss=0.1939 | val_mcc=0.7680 | val_f1=0.8133 | val_auroc=0.9656

[Epoch 07] train_loss=0.2088 | val_loss=0.2084 | val_mcc=0.7674 | val_f1=0.8125 | val_auroc=0.9656

[Epoch 08] train_loss=0.1861 | val_loss=0.2316 | val_mcc=0.7494 | val_f1=0.7976 | val_auroc=0.9639

[Epoch 09] train_loss=0.1698 | val_loss=0.2397 | val_mcc=0.7432 | val_f1=0.7925 | val_auroc=0.9611

[Epoch 10] train_loss=0.1486 | val_loss=0.2561 | val_mcc=0.7372 | val_f1=0.7875 | val_auroc=0.9604

[Epoch 11] train_loss=0.1219 | val_loss=0.2793 | val_mcc=0.7265 | val_f1=0.7777 | val_auroc=0.9615

[Epoch 12] train_loss=0.1084 | val_loss=0.2692 | val_mcc=0.7380 | val_f1=0.7885 | val_auroc=0.9589
[EarlyStop] epoch=12 | best_val_mcc=0.7680
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7808 | F1=0.8413 | AUROC=0.9599 | AUPRC=0.9151
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8185 | F1=0.9020 | AUROC=0.9771 | AUPRC=0.9762
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4384 | F1=0.7265 | AUROC=0.7761 | AUPRC=0.7570
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5793 | F1=0.7860 | AUROC=0.8863 | AUPRC=0.8552
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3984 | val_loss=0.3017 | val_mcc=0.6831 | val_f1=0.7389 | val_auroc=0.9574

[Epoch 02] train_loss=0.3032 | val_loss=0.2196 | val_mcc=0.7493 | val_f1=0.7977 | val_auroc=0.9624

[Epoch 03] train_loss=0.2797 | val_loss=0.1987 | val_mcc=0.7628 | val_f1=0.8090 | val_auroc=0.9626

[Epoch 04] train_loss=0.2647 | val_loss=0.2521 | val_mcc=0.7229 | val_f1=0.7739 | val_auroc=0.9638

[Epoch 05] train_loss=0.2469 | val_loss=0.2028 | val_mcc=0.7590 | val_f1=0.8061 | val_auroc=0.9632

[Epoch 06] train_loss=0.2281 | val_loss=0.1984 | val_mcc=0.7590 | val_f1=0.8059 | val_auroc=0.9635

[Epoch 07] train_loss=0.2154 | val_loss=0.2345 | val_mcc=0.7362 | val_f1=0.7869 | val_auroc=0.9603

[Epoch 08] train_loss=0.1843 | val_loss=0.2633 | val_mcc=0.7303 | val_f1=0.7813 | val_auroc=0.9601

[Epoch 09] train_loss=0.1706 | val_loss=0.2284 | val_mcc=0.7555 | val_f1=0.8033 | val_auroc=0.9609
[EarlyStop] epoch=9 | best_val_mcc=0.7628
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7784 | F1=0.8388 | AUROC=0.9585 | AUPRC=0.9117
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7981 | F1=0.8882 | AUROC=0.9753 | AUPRC=0.9753
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4360 | F1=0.7194 | AUROC=0.7751 | AUPRC=0.7650
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5993 | F1=0.7953 | AUROC=0.8923 | AUPRC=0.8607
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3872 | val_loss=0.2150 | val_mcc=0.7411 | val_f1=0.7917 | val_auroc=0.9580

[Epoch 02] train_loss=0.2985 | val_loss=0.2298 | val_mcc=0.7325 | val_f1=0.7832 | val_auroc=0.9636

[Epoch 03] train_loss=0.2755 | val_loss=0.1824 | val_mcc=0.7704 | val_f1=0.8117 | val_auroc=0.9653

[Epoch 04] train_loss=0.2597 | val_loss=0.1930 | val_mcc=0.7672 | val_f1=0.8123 | val_auroc=0.9644

[Epoch 05] train_loss=0.2425 | val_loss=0.2203 | val_mcc=0.7500 | val_f1=0.7983 | val_auroc=0.9637

[Epoch 06] train_loss=0.2212 | val_loss=0.2131 | val_mcc=0.7600 | val_f1=0.8064 | val_auroc=0.9653

[Epoch 07] train_loss=0.2021 | val_loss=0.1895 | val_mcc=0.7745 | val_f1=0.8166 | val_auroc=0.9646

[Epoch 08] train_loss=0.1866 | val_loss=0.2083 | val_mcc=0.7577 | val_f1=0.8047 | val_auroc=0.9628

[Epoch 09] train_loss=0.1596 | val_loss=0.2260 | val_mcc=0.7479 | val_f1=0.7964 | val_auroc=0.9564

[Epoch 10] train_loss=0.1410 | val_loss=0.2889 | val_mcc=0.7224 | val_f1=0.7746 | val_auroc=0.9588

[Epoch 11] train_loss=0.1211 | val_loss=0.2567 | val_mcc=0.7443 | val_f1=0.7943 | val_auroc=0.9570

[Epoch 12] train_loss=0.0976 | val_loss=0.2768 | val_mcc=0.7395 | val_f1=0.7901 | val_auroc=0.9522

[Epoch 13] train_loss=0.0843 | val_loss=0.3133 | val_mcc=0.7330 | val_f1=0.7854 | val_auroc=0.9515
[EarlyStop] epoch=13 | best_val_mcc=0.7745
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7830 | F1=0.8393 | AUROC=0.9604 | AUPRC=0.9144
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7922 | F1=0.8820 | AUROC=0.9777 | AUPRC=0.9761
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4624 | F1=0.7198 | AUROC=0.7913 | AUPRC=0.7719
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6395 | F1=0.8110 | AUROC=0.8994 | AUPRC=0.8648
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3721 | val_loss=0.2588 | val_mcc=0.7165 | val_f1=0.7689 | val_auroc=0.9580

[Epoch 02] train_loss=0.2938 | val_loss=0.2184 | val_mcc=0.7474 | val_f1=0.7962 | val_auroc=0.9617

[Epoch 03] train_loss=0.2717 | val_loss=0.2123 | val_mcc=0.7529 | val_f1=0.8006 | val_auroc=0.9645

[Epoch 04] train_loss=0.2559 | val_loss=0.2072 | val_mcc=0.7575 | val_f1=0.8044 | val_auroc=0.9645

[Epoch 05] train_loss=0.2376 | val_loss=0.2525 | val_mcc=0.7305 | val_f1=0.7797 | val_auroc=0.9656

[Epoch 06] train_loss=0.2225 | val_loss=0.2126 | val_mcc=0.7563 | val_f1=0.8034 | val_auroc=0.9649

[Epoch 07] train_loss=0.1958 | val_loss=0.2486 | val_mcc=0.7342 | val_f1=0.7842 | val_auroc=0.9612

[Epoch 08] train_loss=0.1747 | val_loss=0.2416 | val_mcc=0.7460 | val_f1=0.7946 | val_auroc=0.9624

[Epoch 09] train_loss=0.1489 | val_loss=0.2503 | val_mcc=0.7391 | val_f1=0.7887 | val_auroc=0.9624

[Epoch 10] train_loss=0.1317 | val_loss=0.2606 | val_mcc=0.7326 | val_f1=0.7836 | val_auroc=0.9605
[EarlyStop] epoch=10 | best_val_mcc=0.7575
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7719 | F1=0.8357 | AUROC=0.9594 | AUPRC=0.9125
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8200 | F1=0.9045 | AUROC=0.9761 | AUPRC=0.9747
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4223 | F1=0.7242 | AUROC=0.7753 | AUPRC=0.7525
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5603 | F1=0.7774 | AUROC=0.8872 | AUPRC=0.8572
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 184.
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7759 | F1=0.8385 | AUROC=0.9653 | AUPRC=0.9232
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8620 | F1=0.9274 | AUROC=0.9870 | AUPRC=0.9875
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4256 | F1=0.7311 | AUROC=0.7759 | AUPRC=0.7575
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5601 | F1=0.7769 | AUROC=0.9014 | AUPRC=0.8803
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 137.
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7708 | F1=0.8349 | AUROC=0.9588 | AUPRC=0.9118
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8059 | F1=0.8969 | AUROC=0.9739 | AUPRC=0.9746
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4186 | F1=0.7242 | AUROC=0.7700 | AUPRC=0.7567
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5626 | F1=0.7785 | AUROC=0.8883 | AUPRC=0.8443
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 158.
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7633 | F1=0.8296 | AUROC=0.9594 | AUPRC=0.9143
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8261 | F1=0.9072 | AUROC=0.9774 | AUPRC=0.9769
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4316 | F1=0.7292 | AUROC=0.7790 | AUPRC=0.7649
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5833 | F1=0.7879 | AUROC=0.8954 | AUPRC=0.8618
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 153.
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7670 | F1=0.8322 | AUROC=0.9606 | AUPRC=0.9163
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8191 | F1=0.9053 | AUROC=0.9755 | AUPRC=0.9759
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4135 | F1=0.7207 | AUROC=0.7739 | AUPRC=0.7530
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.4025 | val_loss=0.2526 | val_mcc=0.6932 | val_f1=0.7516 | val_auroc=0.9435

[Epoch 02] train_loss=0.2870 | val_loss=0.3034 | val_mcc=0.6840 | val_f1=0.7432 | val_auroc=0.9503

[Epoch 03] train_loss=0.2664 | val_loss=0.2762 | val_mcc=0.6920 | val_f1=0.7513 | val_auroc=0.9516

[Epoch 04] train_loss=0.2524 | val_loss=0.2775 | val_mcc=0.6998 | val_f1=0.7581 | val_auroc=0.9494

[Epoch 05] train_loss=0.2397 | val_loss=0.2546 | val_mcc=0.7012 | val_f1=0.7600 | val_auroc=0.9485

[Epoch 06] train_loss=0.2247 | val_loss=0.2271 | val_mcc=0.7051 | val_f1=0.7594 | val_auroc=0.9476

[Epoch 07] train_loss=0.2084 | val_loss=0.2717 | val_mcc=0.6869 | val_f1=0.7486 | val_auroc=0.9437

[Epoch 08] train_loss=0.1913 | val_loss=0.3083 | val_mcc=0.6779 | val_f1=0.7381 | val_auroc=0.9450

[Epoch 09] train_loss=0.1760 | val_loss=0.3312 | val_mcc=0.6521 | val_f1=0.7180 | val_auroc=0.9354

[Epoch 10] train_loss=0.1536 | val_loss=0.3090 | val_mcc=0.6681 | val_f1=0.7328 | val_auroc=0.9385

[Epoch 11] train_loss=0.1282 | val_loss=0.3596 | val_mcc=0.6364 | val_f1=0.7051 | val_auroc=0.9340

[Epoch 12] train_loss=0.1173 | val_loss=0.3334 | val_mcc=0.6542 | val_f1=0.7221 | val_auroc=0.9319
[EarlyStop] epoch=12 | best_val_mcc=0.7051
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7088 | F1=0.7825 | AUROC=0.9383 | AUPRC=0.8655
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7121 | F1=0.8380 | AUROC=0.9464 | AUPRC=0.9421
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4495 | F1=0.7098 | AUROC=0.7781 | AUPRC=0.7653
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6002 | F1=0.7827 | AUROC=0.8797 | AUPRC=0.8525
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4118 | val_loss=0.2458 | val_mcc=0.7342 | val_f1=0.7846 | val_auroc=0.9548

[Epoch 02] train_loss=0.2935 | val_loss=0.3305 | val_mcc=0.6803 | val_f1=0.7344 | val_auroc=0.9618

[Epoch 03] train_loss=0.2745 | val_loss=0.2259 | val_mcc=0.7482 | val_f1=0.7864 | val_auroc=0.9596

[Epoch 04] train_loss=0.2574 | val_loss=0.2355 | val_mcc=0.7343 | val_f1=0.7849 | val_auroc=0.9545

[Epoch 05] train_loss=0.2420 | val_loss=0.2586 | val_mcc=0.7238 | val_f1=0.7779 | val_auroc=0.9527

[Epoch 06] train_loss=0.2282 | val_loss=0.2521 | val_mcc=0.7223 | val_f1=0.7768 | val_auroc=0.9528

[Epoch 07] train_loss=0.2104 | val_loss=0.2975 | val_mcc=0.6821 | val_f1=0.7432 | val_auroc=0.9448

[Epoch 08] train_loss=0.1827 | val_loss=0.3553 | val_mcc=0.6299 | val_f1=0.7002 | val_auroc=0.9281

[Epoch 09] train_loss=0.1684 | val_loss=0.3467 | val_mcc=0.6456 | val_f1=0.7135 | val_auroc=0.9321
[EarlyStop] epoch=9 | best_val_mcc=0.7482
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7411 | F1=0.7976 | AUROC=0.9538 | AUPRC=0.9021
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7064 | F1=0.8140 | AUROC=0.9678 | AUPRC=0.9669
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4261 | F1=0.6712 | AUROC=0.7756 | AUPRC=0.7653
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6061 | F1=0.7807 | AUROC=0.8843 | AUPRC=0.8602
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4189 | val_loss=0.2929 | val_mcc=0.5540 | val_f1=0.5775 | val_auroc=0.9238

[Epoch 02] train_loss=0.3043 | val_loss=0.2493 | val_mcc=0.6601 | val_f1=0.7002 | val_auroc=0.9380

[Epoch 03] train_loss=0.2763 | val_loss=0.2837 | val_mcc=0.7049 | val_f1=0.7628 | val_auroc=0.9426

[Epoch 04] train_loss=0.2646 | val_loss=0.2462 | val_mcc=0.6854 | val_f1=0.7369 | val_auroc=0.9395

[Epoch 05] train_loss=0.2491 | val_loss=0.3022 | val_mcc=0.6712 | val_f1=0.7354 | val_auroc=0.9364

[Epoch 06] train_loss=0.2327 | val_loss=0.2513 | val_mcc=0.7005 | val_f1=0.7571 | val_auroc=0.9411

[Epoch 07] train_loss=0.2184 | val_loss=0.2622 | val_mcc=0.6753 | val_f1=0.7370 | val_auroc=0.9309

[Epoch 08] train_loss=0.1943 | val_loss=0.2638 | val_mcc=0.6562 | val_f1=0.7169 | val_auroc=0.9264

[Epoch 09] train_loss=0.1795 | val_loss=0.2904 | val_mcc=0.6319 | val_f1=0.7009 | val_auroc=0.9121
[EarlyStop] epoch=9 | best_val_mcc=0.7049
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6975 | F1=0.7809 | AUROC=0.9272 | AUPRC=0.8625
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6974 | F1=0.8305 | AUROC=0.9480 | AUPRC=0.9470
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3818 | F1=0.6898 | AUROC=0.7481 | AUPRC=0.7407
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5336 | F1=0.7599 | AUROC=0.8535 | AUPRC=0.8353
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3720 | val_loss=0.3287 | val_mcc=0.6724 | val_f1=0.7349 | val_auroc=0.9446

[Epoch 02] train_loss=0.2809 | val_loss=0.3059 | val_mcc=0.6837 | val_f1=0.7448 | val_auroc=0.9469

[Epoch 03] train_loss=0.2622 | val_loss=0.2647 | val_mcc=0.7151 | val_f1=0.7711 | val_auroc=0.9491

[Epoch 04] train_loss=0.2450 | val_loss=0.3605 | val_mcc=0.6290 | val_f1=0.6942 | val_auroc=0.9424

[Epoch 05] train_loss=0.2317 | val_loss=0.2968 | val_mcc=0.6855 | val_f1=0.7455 | val_auroc=0.9468

[Epoch 06] train_loss=0.2161 | val_loss=0.2581 | val_mcc=0.6977 | val_f1=0.7573 | val_auroc=0.9457

[Epoch 07] train_loss=0.1959 | val_loss=0.2606 | val_mcc=0.6866 | val_f1=0.7484 | val_auroc=0.9400

[Epoch 08] train_loss=0.1737 | val_loss=0.2929 | val_mcc=0.6536 | val_f1=0.7219 | val_auroc=0.9329

[Epoch 09] train_loss=0.1598 | val_loss=0.2972 | val_mcc=0.6514 | val_f1=0.7204 | val_auroc=0.9289
[EarlyStop] epoch=9 | best_val_mcc=0.7151
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7287 | F1=0.8044 | AUROC=0.9410 | AUPRC=0.8824
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7374 | F1=0.8610 | AUROC=0.9483 | AUPRC=0.9469
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4363 | F1=0.7223 | AUROC=0.7733 | AUPRC=0.7640
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5826 | F1=0.7857 | AUROC=0.8797 | AUPRC=0.8595
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 178.
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7981 | F1=0.8543 | AUROC=0.9685 | AUPRC=0.9318
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8506 | F1=0.9215 | AUROC=0.9828 | AUPRC=0.9830
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4505 | F1=0.7392 | AUROC=0.7887 | AUPRC=0.7685
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6093 | F1=0.7995 | AUROC=0.9111 | AUPRC=0.8905
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 165.
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6579 | F1=0.7532 | AUROC=0.9438 | AUPRC=0.8804
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7676 | F1=0.8848 | AUROC=0.9528 | AUPRC=0.9495
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3778 | F1=0.7191 | AUROC=0.7756 | AUPRC=0.7521
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4927 | F1=0.7476 | AUROC=0.8753 | AUPRC=0.8388
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 117.
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5714 | F1=0.6145 | AUROC=0.8916 | AUPRC=0.8073
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5102 | F1=0.6352 | AUROC=0.8815 | AUPRC=0.8909
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3657 | F1=0.5484 | AUROC=0.7499 | AUPRC=0.7389
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4719 | F1=0.6213 | AUROC=0.8447 | AUPRC=0.8224
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 214.
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6811 | F1=0.7629 | AUROC=0.9289 | AUPRC=0.8543
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6764 | F1=0.8121 | AUROC=0.9435 | AUPRC=0.9416
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_dna_geom_prot_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4162 | F1=0.6864 | AUROC=0.7645 | AUPRC=0.7534
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio', 'geom']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4079 | val_loss=0.2948 | val_mcc=0.5827 | val_f1=0.6012 | val_auroc=0.9363

[Epoch 02] train_loss=0.2982 | val_loss=0.2637 | val_mcc=0.6311 | val_f1=0.6538 | val_auroc=0.9431

[Epoch 03] train_loss=0.2896 | val_loss=0.2566 | val_mcc=0.6415 | val_f1=0.6624 | val_auroc=0.9466

[Epoch 04] train_loss=0.2835 | val_loss=0.2456 | val_mcc=0.6757 | val_f1=0.7069 | val_auroc=0.9488

[Epoch 05] train_loss=0.2788 | val_loss=0.2401 | val_mcc=0.6864 | val_f1=0.7202 | val_auroc=0.9507

[Epoch 06] train_loss=0.2779 | val_loss=0.2380 | val_mcc=0.6821 | val_f1=0.7108 | val_auroc=0.9526

[Epoch 07] train_loss=0.2734 | val_loss=0.2382 | val_mcc=0.6751 | val_f1=0.7004 | val_auroc=0.9538

[Epoch 08] train_loss=0.2746 | val_loss=0.2393 | val_mcc=0.6816 | val_f1=0.7078 | val_auroc=0.9526

[Epoch 09] train_loss=0.2717 | val_loss=0.2321 | val_mcc=0.7191 | val_f1=0.7571 | val_auroc=0.9561

[Epoch 10] train_loss=0.2710 | val_loss=0.2322 | val_mcc=0.7154 | val_f1=0.7521 | val_auroc=0.9557

[Epoch 11] train_loss=0.2696 | val_loss=0.2288 | val_mcc=0.7235 | val_f1=0.7603 | val_auroc=0.9576

[Epoch 12] train_loss=0.2694 | val_loss=0.2308 | val_mcc=0.7250 | val_f1=0.7621 | val_auroc=0.9566

[Epoch 13] train_loss=0.2683 | val_loss=0.2342 | val_mcc=0.7358 | val_f1=0.7782 | val_auroc=0.9576

[Epoch 14] train_loss=0.2667 | val_loss=0.2321 | val_mcc=0.7349 | val_f1=0.7750 | val_auroc=0.9579

[Epoch 15] train_loss=0.2656 | val_loss=0.2359 | val_mcc=0.7430 | val_f1=0.7850 | val_auroc=0.9585

[Epoch 16] train_loss=0.2652 | val_loss=0.2301 | val_mcc=0.7406 | val_f1=0.7804 | val_auroc=0.9598

[Epoch 17] train_loss=0.2644 | val_loss=0.2296 | val_mcc=0.7427 | val_f1=0.7840 | val_auroc=0.9602

[Epoch 18] train_loss=0.2659 | val_loss=0.2340 | val_mcc=0.7545 | val_f1=0.7990 | val_auroc=0.9610

[Epoch 19] train_loss=0.2615 | val_loss=0.2379 | val_mcc=0.7511 | val_f1=0.7961 | val_auroc=0.9604

[Epoch 20] train_loss=0.2605 | val_loss=0.2309 | val_mcc=0.7520 | val_f1=0.7946 | val_auroc=0.9613

[Epoch 21] train_loss=0.2618 | val_loss=0.2327 | val_mcc=0.7557 | val_f1=0.7983 | val_auroc=0.9617

[Epoch 22] train_loss=0.2625 | val_loss=0.2362 | val_mcc=0.7524 | val_f1=0.7975 | val_auroc=0.9615

[Epoch 23] train_loss=0.2597 | val_loss=0.2397 | val_mcc=0.7562 | val_f1=0.8026 | val_auroc=0.9623

[Epoch 24] train_loss=0.2596 | val_loss=0.2345 | val_mcc=0.7543 | val_f1=0.7994 | val_auroc=0.9616

[Epoch 25] train_loss=0.2612 | val_loss=0.2497 | val_mcc=0.7522 | val_f1=0.8004 | val_auroc=0.9625

[Epoch 26] train_loss=0.2578 | val_loss=0.2476 | val_mcc=0.7599 | val_f1=0.8064 | val_auroc=0.9630

[Epoch 27] train_loss=0.2596 | val_loss=0.2510 | val_mcc=0.7543 | val_f1=0.8018 | val_auroc=0.9613

[Epoch 28] train_loss=0.2585 | val_loss=0.2535 | val_mcc=0.7514 | val_f1=0.7998 | val_auroc=0.9622

[Epoch 29] train_loss=0.2586 | val_loss=0.2701 | val_mcc=0.7397 | val_f1=0.7906 | val_auroc=0.9619

[Epoch 30] train_loss=0.2566 | val_loss=0.2644 | val_mcc=0.7427 | val_f1=0.7930 | val_auroc=0.9629
[Test] train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7707 | F1=0.8326 | AUROC=0.9566 | AUPRC=0.9127
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8075 | F1=0.8923 | AUROC=0.9722 | AUPRC=0.9720
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4193 | F1=0.7084 | AUROC=0.7656 | AUPRC=0.7632
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5516 | F1=0.7730 | AUROC=0.8846 | AUPRC=0.8721
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 54.
[Test] train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7754 | F1=0.8382 | AUROC=0.9656 | AUPRC=0.9263
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8527 | F1=0.9238 | AUROC=0.9800 | AUPRC=0.9814
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4336 | F1=0.7351 | AUROC=0.7859 | AUPRC=0.7699
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5532 | F1=0.7741 | AUROC=0.9041 | AUPRC=0.8919
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 81.
[Test] train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.4426 | F1=0.4708 | AUROC=0.8865 | AUPRC=0.7429
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4089 | F1=0.4430 | AUROC=0.9293 | AUPRC=0.9269
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.1600 | F1=0.3226 | AUROC=0.6613 | AUPRC=0.6466
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio', 'geom']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_geom_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.3497 | F1=0.5179 | AUROC=0.7641 | AUPRC=0.7300

================================================================================
[THANH CONG] Module 5 batch runner da hoan tat
================================================================================
Batch run dir: d:\Missense_variant_pathogenicity_prediction/experiments/batch_run_20260904_1800
Metrics CSV: d:\Missense_variant_pathogenicity_prediction/experiments/batch_run_20260904_1800/global_leaderboard_metrics.csv | rows=1404
Profiling CSV: d:\Missense_variant_pathogenicity_prediction/experiments/batch_run_20260904_1800/global_leaderboard_profiling.csv | rows=1404
Compare CSV: d:\Missense_variant_pathogenicity_prediction/experiments/batch_run_20260904_1800/global_compare_ours_vs_sota.csv

,Dataset,Pooling,Ablation,DNA_Model,Prot_Model,Network,Accuracy,Precision,Recall,Specificity,F1_Score,MCC,AUROC,AUPRC,Source
0,Train3Val_ClinVarHQ,cls,bio_dna_prot,nt_v2_500m,esm1b_650m,Pure_XGBoost_Concat,0.9360,0.9633,0.9052,0.9662,0.9333,0.8735,0.9867,0.9874,OURS
1,Train3Val_ClinVarHQ,center,bio_dna_geom_prot,nt_v1_500m,esmc_600m,Pure_XGBoost_Concat,0.9331,0.9574,0.9052,0.9606,0.9306,0.8675,0.9837,0.9841,OURS
2,Train3Val_ClinVarHQ,center,bio_dna_prot,nt_v1_500m,esmc_600m,Hybrid_Concat_XGBoost,0.9317,0.9491,0.9109,0.9521,0.9296,0.8641,0.9793,0.9794,OURS
3,Train3Val_ClinVarHQ,mean,bio_dna_prot,nt_v2_500m,esm1b_650m,Pure_XGBoost_Concat,0.9303,0.9572,0.8994,0.9606,0.9274,0.8620,0.9870,0.9875,OURS
4,Train3Val_ClinVarHQ,center,bio_dna_prot,nt_v1_500m,esmc_600m,Hybrid_Gating_XGBoost,0.9275,0.9486,0.9023,0.9521,0.9249,0.8558,0.9761,0.9771,OURS
5,Train3Val_ClinVarHQ,cls,bio_geom,nt_v2_500m,esm1b_650m,Pure_XGBoost_Concat,0.9260,0.9485,0.8994,0.9521,0.9233,0.8531,0.9795,0.9816,OURS
6,Train3Val_ClinVarHQ,cls,bio_dna_geom_prot,nt_v2_500m,esm1b_650m,Pure_XGBoost_Concat,0.9260,0.9431,0.9052,0.9465,0.9238,0.8527,0.9833,0.9843,OURS
7,Train3Val_ClinVarHQ,mean,bio_geom,nt_v2_500m,esm1b_650m,Pure_XGBoost_Concat,0.9260,0.9431,0.9052,0.9465,0.9238,0.8527,0.9800,0.9814,OURS
8,Train3Val_ClinVarHQ,center,bio_dna_prot,nt_v1_500m,esmc_600m,Pure_XGBoost_Concat,0.9246,0.9538,0.8908,0.9577,0.9212,0.8509,0.9833,0.9837,OURS
9,Train3Val_ClinVarHQ,mean,bio_dna_geom_prot,nt_v2_500m,esm1b_650m,Pure_XGBoost_Concat,0.9246,0.9511,0.8937,0.9549,0.9215,0.8506,0.9828,0.9830,OURS
10,Train3Val_ClinVarHQ,center,bio_geom,nt_v1_500m,esmc_600m,Pure_XGBoost_Concat,0.9218,0.9426,0.8966,0.9465,0.9190,0.8444,0.9793,0.9808,OURS
11,Train3Val_ClinVarHQ,center,bio_dna_prot,nt_v1_500m,esmc_600m,Hybrid_Transformer_XGBoost,0.9175,0.9475,0.8822,0.9521,0.9137,0.8368,0.9752,0.9764,OURS
12,Train3Val_ClinVarHQ,mean,bio_dna_prot,nt_v2_500m,esm1b_650m,Hybrid_Gating_XGBoost,0.9161,0.9392,0.8879,0.9437,0.9129,0.8333,0.9773,0.9780,OURS
13,Train3Val_ClinVarHQ,cls,bio_dna_prot,nt_v2_500m,esm1b_650m,Hybrid_CrossAttn_XGBoost,0.9147,0.9472,0.8764,0.9521,0.9104,0.8314,0.9780,0.9786,OURS
14,Train3Val_ClinVarHQ,cls,bio_dna_prot,nt_v2_500m,esm1b_650m,Hybrid_Transformer_XGBoost,0.9147,0.9472,0.8764,0.9521,0.9104,0.8314,0.9774,0.9776,OURS
15,Train3Val_ClinVarHQ,center,bio_dna_prot,nt_v1_500m,esmc_600m,PyTorch_Transformer,0.9132,0.9362,0.8851,0.9408,0.9099,0.8276,0.9736,0.9737,OURS
16,Train3Val_ClinVarHQ,center,bio_dna_prot,nt_v1_500m,esmc_600m,PyTorch_Gating,0.9118,0.9525,0.8649,0.9577,0.9066,0.8269,0.9759,0.9760,OURS
17,Train3Val_ClinVarHQ,mean,bio_dna_prot,nt_v2_500m,esm1b_650m,Hybrid_CrossAttn_XGBoost,0.9118,0.9469,0.8707,0.9521,0.9072,0.8261,0.9774,0.9769,OURS
18,Train3Val_ClinVarHQ,center,bio_dna_prot,nt_v1_500m,esmc_600m,Hybrid_CrossAttn_XGBoost,0.9118,0.9333,0.8851,0.9380,0.9086,0.8246,0.9748,0.9744,OURS
19,Train3Val_ClinVarHQ,cls,bio_dna_prot,nt_v2_500m,esm1b_650m,Hybrid_Concat_XGBoost,0.9104,0.9439,0.8707,0.9493,0.9058,0.8230,0.9760,0.9764,OURS
20,Train3Val_ClinVarHQ,mean,bio_dna_prot,nt_v2_500m,esm1b_650m,PyTorch_Gating,0.9090,0.9410,0.8707,0.9465,0.9045,0.8200,0.9761,0.9747,OURS
21,Train3Val_ClinVarHQ,mean,bio_dna_prot,nt_v2_500m,esm1b_650m,Hybrid_Transformer_XGBoost,0.9090,0.9329,0.8793,0.9380,0.9053,0.8191,0.9755,0.9759,OURS
22,Train3Val_ClinVarHQ,mean,bio_dna_prot,nt_v2_500m,esm1b_650m,PyTorch_Concat,0.9075,0.9492,0.8592,0.9549,0.9020,0.8185,0.9771,0.9762,OURS
23,Train3Val_ClinVarHQ,cls,bio_dna_prot,nt_v2_500m,esm1b_650m,PyTorch_Gating,0.9033,0.9516,0.8477,0.9577,0.8967,0.8111,0.9719,0.9718,OURS
24,Train3Val_ClinVarHQ,cls,bio_dna_prot,nt_v2_500m,esm1b_650m,Hybrid_Gating_XGBoost,0.9033,0.9375,0.8621,0.9437,0.8982,0.8089,0.9736,0.9733,OURS
25,Train3Val_ClinVarHQ,mean,bio_geom,nt_v2_500m,esm1b_650m,PyTorch_Concat,0.9004,0.9603,0.8333,0.9662,0.8923,0.8075,0.9722,0.9720,OURS
26,Train3Val_ClinVarHQ,center,bio_dna_prot,nt_v1_500m,esmc_600m,PyTorch_CrossAttn,0.9004,0.9542,0.8391,0.9606,0.8930,0.8064,0.9755,0.9751,OURS
27,Train3Val_ClinVarHQ,mean,bio_dna_prot,nt_v2_500m,esm1b_650m,Hybrid_Concat_XGBoost,0.9018,0.9346,0.8621,0.9408,0.8969,0.8059,0.9739,0.9746,OURS
28,Train3Val_ClinVarHQ,cls,bio_dna_prot,nt_v2_500m,esm1b_650m,PyTorch_Concat,0.9004,0.9455,0.8477,0.9521,0.8939,0.8049,0.9731,0.9732,OURS
29,Train3Val_ClinVarHQ,center,bio_dna_prot,nt_v1_500m,esmc_600m,PyTorch_Concat,0.9004,0.9427,0.8506,0.9493,0.8943,0.8044,0.9747,0.9745,OURS
30,Train3Val_ClinVarHQ,cls,bio_dna_prot,nt_v2_500m,esm1b_650m,PyTorch_Transformer,0.8976,0.9510,0.8362,0.9577,0.8899,0.8007,0.9690,0.9700,OURS
31,Train3Val_ClinVarHQ,mean,bio_dna_prot,nt_v2_500m,esm1b_650m,PyTorch_CrossAttn,0.8962,0.9508,0.8333,0.9577,0.8882,0.7981,0.9753,0.9753,OURS
32,Train3Val_ClinVarHQ,cls,bio_geom,nt_v2_500m,esm1b_650m,PyTorch_Concat,0.8919,0.9626,0.8132,0.9690,0.8816,0.7929,0.9719,0.9731,OURS
33,Train3Val_ClinVarHQ,mean,bio_dna_prot,nt_v2_500m,esm1b_650m,PyTorch_Transformer,0.8919,0.9595,0.8161,0.9662,0.8820,0.7922,0.9777,0.9761,OURS
34,Train3Val_ClinVarHQ,center,bio_geom,nt_v1_500m,esmc_600m,PyTorch_Concat,0.8848,0.9855,0.7787,0.9887,0.8700,0.7863,0.9716,0.9734,OURS
35,Train3Val_ClinVarHQ,center,bio_dna_geom_prot,nt_v1_500m,esmc_600m,PyTorch_CrossAttn,0.8876,0.9088,0.8592,0.9155,0.8833,0.7762,0.9633,0.9618,OURS
36,Train3Val_ClinVarHQ,cls,bio_dna_geom_prot,nt_v2_500m,esm1b_650m,PyTorch_Concat,0.8805,0.9430,0.8075,0.9521,0.8700,0.7685,0.9650,0.9650,OURS
37,Train3Val_ClinVarHQ,center,bio_dna_geom_prot,nt_v1_500m,esmc_600m,Hybrid_Concat_XGBoost,0.8805,0.9400,0.8103,0.9493,0.8704,0.7679,0.9690,0.9671,OURS
38,Train3Val_ClinVarHQ,mean,bio_dna_geom_prot,nt_v2_500m,esm1b_650m,Hybrid_Concat_XGBoost,0.8834,0.8654,0.9052,0.8620,0.8848,0.7676,0.9528,0.9495,OURS
39,Train3Val_ClinVarHQ,cls,bio_dna_prot,nt_v2_500m,esm1b_650m,PyTorch_CrossAttn,0.8748,0.9745,0.7672,0.9803,0.8585,0.7663,0.9715,0.9713,OURS

,Dataset,Model,file_path,score_col,rankscore_col,pred_col,resolved_prob_col,resolved_prob_kind,resolved_threshold,pred_source,label_col
0,test,SIFT,D:/variant_data/test_full_seq_after_vep_final....,['SIFT_score'],"['SIFT_converted_rankscore', 'SIFT_rankscore']",['SIFT_pred'],SIFT_converted_rankscore,rankscore,0.395750,SIFT_pred,Label
1,test,SIFT4G,D:/variant_data/test_full_seq_after_vep_final....,['SIFT4G_score'],"['SIFT4G_converted_rankscore', 'SIFT4G_ranksco...",['SIFT4G_pred'],SIFT4G_converted_rankscore,rankscore,0.395750,SIFT4G_pred,Label
2,test,Polyphen2_HDIV,D:/variant_data/test_full_seq_after_vep_final....,['Polyphen2_HDIV_score'],['Polyphen2_HDIV_rankscore'],['Polyphen2_HDIV_pred'],Polyphen2_HDIV_rankscore,rankscore,0.380280,Polyphen2_HDIV_pred,Label
3,test,Polyphen2_HVAR,D:/variant_data/test_full_seq_after_vep_final....,['Polyphen2_HVAR_score'],['Polyphen2_HVAR_rankscore'],['Polyphen2_HVAR_pred'],Polyphen2_HVAR_rankscore,rankscore,0.487620,Polyphen2_HVAR_pred,Label
4,test,MutationTaster,D:/variant_data/test_full_seq_after_vep_final....,['MutationTaster_score'],['MutationTaster_rankscore'],['MutationTaster_pred'],MutationTaster_rankscore,rankscore,0.317330,MutationTaster_pred,Label
5,test,MetaSVM,D:/variant_data/test_full_seq_after_vep_final....,['MetaSVM_score'],['MetaSVM_rankscore'],['MetaSVM_pred'],MetaSVM_rankscore,rankscore,0.822570,MetaSVM_pred,Label
6,test,MetaLR,D:/variant_data/test_full_seq_after_vep_final....,['MetaLR_score'],['MetaLR_rankscore'],['MetaLR_pred'],MetaLR_rankscore,rankscore,0.811010,MetaLR_pred,Label
7,test,MetaRNN,D:/variant_data/test_full_seq_after_vep_final....,['MetaRNN_score'],['MetaRNN_rankscore'],['MetaRNN_pred'],MetaRNN_rankscore,rankscore,0.614900,MetaRNN_pred,Label
8,test,M-CAP,D:/variant_data/test_full_seq_after_vep_final....,['M-CAP_score'],['M-CAP_rankscore'],['M-CAP_pred'],M-CAP_rankscore,rankscore,0.025000,M-CAP_pred,Label
9,test,REVEL,D:/variant_data/test_full_seq_after_vep_final....,['REVEL_score'],['REVEL_rankscore'],['REVEL_pred'],REVEL_rankscore,rankscore,0.500000,REVEL_pred,Label
10,test,MutPred2,D:/variant_data/test_full_seq_after_vep_final....,['MutPred2_score'],['MutPred2_rankscore'],['MutPred2_pred'],MutPred2_rankscore,rankscore,0.500000,MutPred2_pred,Label
11,test,MVP,D:/variant_data/test_full_seq_after_vep_final....,['MVP_score'],['MVP_rankscore'],['MVP_pred'],MVP_rankscore,rankscore,0.500000,MVP_pred,Label
12,test,gMVP,D:/variant_data/test_full_seq_after_vep_final....,['gMVP_score'],['gMVP_rankscore'],['gMVP_pred'],gMVP_rankscore,rankscore,0.500000,gMVP_pred,Label
13,test,MisFit_D,D:/variant_data/test_full_seq_after_vep_final....,['MisFit_D_score'],['MisFit_D_rankscore'],"['MisFit_D_pred_lenient', 'MisFit_D_pred']",MisFit_D_rankscore,rankscore,0.450000,MisFit_D_pred_lenient,Label
14,test,MPC,D:/variant_data/test_full_seq_after_vep_final....,['MPC_score'],['MPC_rankscore'],['MPC_pred'],MPC_rankscore,rankscore,0.500000,MPC_pred,Label
15,test,PrimateAI,D:/variant_data/test_full_seq_after_vep_final....,['PrimateAI_score'],['PrimateAI_rankscore'],['PrimateAI_pred'],PrimateAI_rankscore,rankscore,0.803000,PrimateAI_pred,Label
16,test,BayesDel_addAF,D:/variant_data/test_full_seq_after_vep_final....,['BayesDel_addAF_score'],['BayesDel_addAF_rankscore'],['BayesDel_addAF_pred'],BayesDel_addAF_rankscore,rankscore,0.069265,BayesDel_addAF_pred,Label
17,test,BayesDel_noAF,D:/variant_data/test_full_seq_after_vep_final....,['BayesDel_noAF_score'],['BayesDel_noAF_rankscore'],['BayesDel_noAF_pred'],BayesDel_noAF_rankscore,rankscore,-0.057010,BayesDel_noAF_pred,Label
18,test,ClinPred,D:/variant_data/test_full_seq_after_vep_final....,['ClinPred_score'],['ClinPred_rankscore'],['ClinPred_pred'],ClinPred_rankscore,rankscore,0.500000,ClinPred_pred,Label
19,test,LIST-S2,D:/variant_data/test_full_seq_after_vep_final....,['LIST-S2_score'],['LIST-S2_rankscore'],['LIST-S2_pred'],LIST-S2_rankscore,rankscore,0.850000,LIST-S2_pred,Label
20,test,VARITY_R,D:/variant_data/test_full_seq_after_vep_final....,['VARITY_R_score'],['VARITY_R_rankscore'],['VARITY_R_pred'],VARITY_R_rankscore,rankscore,0.500000,VARITY_R_pred,Label
21,test,VARITY_ER,D:/variant_data/test_full_seq_after_vep_final....,['VARITY_ER_score'],['VARITY_ER_rankscore'],['VARITY_ER_pred'],VARITY_ER_rankscore,rankscore,0.500000,VARITY_ER_pred,Label
22,test,AlphaMissense,D:/variant_data/test_full_seq_after_vep_final....,['AlphaMissense_score'],['AlphaMissense_rankscore'],['AlphaMissense_pred'],AlphaMissense_rankscore,rankscore,0.500000,AlphaMissense_pred,Label
23,test,PHACTboost,D:/variant_data/test_full_seq_after_vep_final....,['PHACTboost_score'],['PHACTboost_rankscore'],['PHACTboost_pred'],PHACTboost_rankscore,rankscore,0.620000,PHACTboost_pred,Label
24,test,MutFormer,D:/variant_data/test_full_seq_after_vep_final....,['MutFormer_score'],['MutFormer_rankscore'],['MutFormer_pred'],MutFormer_rankscore,rankscore,0.883800,MutFormer_pred,Label
25,test,popEVE,D:/variant_data/test_full_seq_after_vep_final....,['popEVE_score'],"['popEVE_converted_rankscore', 'popEVE_ranksco...",['popEVE_pred'],popEVE_converted_rankscore,rankscore,0.500000,popEVE_pred,Label
26,test,CADD,D:/variant_data/test_full_seq_after_vep_final....,"['CADD_raw', 'CADD_phred']",['CADD_raw_rankscore'],['CADD_pred'],CADD_raw_rankscore,rankscore,0.500000,CADD_pred,Label
27,test,DANN,D:/variant_data/test_full_seq_after_vep_final....,['DANN_score'],['DANN_rankscore'],['DANN_pred'],DANN_rankscore,rankscore,0.500000,DANN_pred,Label
28,clinvarhq,SIFT,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['SIFT_score'],"['SIFT_converted_rankscore', 'SIFT_rankscore']",['SIFT_pred'],SIFT_converted_rankscore,rankscore,0.395750,SIFT_pred,Label
29,clinvarhq,SIFT4G,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['SIFT4G_score'],"['SIFT4G_converted_rankscore', 'SIFT4G_ranksco...",['SIFT4G_pred'],SIFT4G_converted_rankscore,rankscore,0.395750,SIFT4G_pred,Label
30,clinvarhq,Polyphen2_HDIV,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['Polyphen2_HDIV_score'],['Polyphen2_HDIV_rankscore'],['Polyphen2_HDIV_pred'],Polyphen2_HDIV_rankscore,rankscore,0.380280,Polyphen2_HDIV_pred,Label
31,clinvarhq,Polyphen2_HVAR,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['Polyphen2_HVAR_score'],['Polyphen2_HVAR_rankscore'],['Polyphen2_HVAR_pred'],Polyphen2_HVAR_rankscore,rankscore,0.487620,Polyphen2_HVAR_pred,Label
32,clinvarhq,MutationTaster,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MutationTaster_score'],['MutationTaster_rankscore'],['MutationTaster_pred'],MutationTaster_rankscore,rankscore,0.317330,MutationTaster_pred,Label
33,clinvarhq,MetaSVM,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MetaSVM_score'],['MetaSVM_rankscore'],['MetaSVM_pred'],MetaSVM_rankscore,rankscore,0.822570,MetaSVM_pred,Label
34,clinvarhq,MetaLR,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MetaLR_score'],['MetaLR_rankscore'],['MetaLR_pred'],MetaLR_rankscore,rankscore,0.811010,MetaLR_pred,Label
35,clinvarhq,MetaRNN,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MetaRNN_score'],['MetaRNN_rankscore'],['MetaRNN_pred'],MetaRNN_rankscore,rankscore,0.614900,MetaRNN_pred,Label
36,clinvarhq,M-CAP,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['M-CAP_score'],['M-CAP_rankscore'],['M-CAP_pred'],M-CAP_rankscore,rankscore,0.025000,M-CAP_pred,Label
37,clinvarhq,REVEL,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['REVEL_score'],['REVEL_rankscore'],['REVEL_pred'],REVEL_rankscore,rankscore,0.500000,REVEL_pred,Label
38,clinvarhq,MutPred2,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MutPred2_score'],['MutPred2_rankscore'],['MutPred2_pred'],MutPred2_rankscore,rankscore,0.500000,MutPred2_pred,Label
39,clinvarhq,MVP,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MVP_score'],['MVP_rankscore'],['MVP_pred'],MVP_rankscore,rankscore,0.500000,MVP_pred,Label

Empty DataFrame
Columns: [Dataset, file_path, column, exists, null_count]
Index: []