### Cách dùng Notebook 01 hiện tại

1. Mở `01_train_val_test_batch_runner.ipynb`.
2. Chạy Cell 2 để:
- Import pipeline
- Khai báo toàn bộ cấu hình bạn muốn kiểm soát
- Khởi tạo đối tượng pipeline
3. Chạy Cell 4 để chạy toàn bộ train-val-test batch.
4. Sau khi chạy xong, Cell 4 sẽ:
- In đường dẫn thư mục batch run
- Đọc và hiển thị 2 bảng tổng hợp metrics/profiling.

Luồng chạy thực tế nằm ở `pipeline.py`.

Các config ảnh hưởng pipeline train như thế nào

1. CONFIG trong Cell 2
- batch_size: tăng thì nhanh hơn nhưng tốn VRAM/RAM hơn.
- epochs: số epoch tối đa cho nhánh pytorch.
- lr: learning rate cho optimizer.
- weight_decay: regularization cho pytorch.
- lr_factor + lr_patience: giảm learning rate khi MCC val không cải thiện.
- early_stop_patience: dừng sớm nếu MCC val không tăng.
- num_workers: số worker DataLoader.

2. MODELS_SPACE trong Cell 2
- Xác định tập model DNA và Protein để vét cạn tổ hợp ở Stage 1.
- Pipeline tự tách model theo seq_type dna/protein.
- Nếu thêm/bớt model ở đây, số tổ hợp train tăng/giảm trực tiếp.

3. EXPERIMENTS trong Cell 2
- Quy định bạn chạy kiểu nào:
- pytorch: train end-to-end mạng fusion.
- hybrid: train nhanh mạng pytorch để lấy f_global, sau đó train XGBoost.
- xgboost_pure: PCA + XGBoost trên đặc trưng không gian bảng/biến thể.
- Với ablation chỉ có 1 nhánh chuỗi, pipeline tự bỏ các fusion cần 2 nhánh như cross_attention/transformer/gating.

4. datasets trong Cell 2
- Mỗi phần tử định nghĩa 1 job train/val/test.
- test split ở đây còn ảnh hưởng E2E profiling vì Module 5 sẽ đọc FM profiling đúng theo split test tương ứng.

5. pooling_strategies trong Cell 2
- Chạy lặp theo từng pooling center/cls/mean.
- Mỗi pooling sẽ có leaderboard và best pair search riêng.

6. EXPLAINABILITY trong Cell 2
- enable_shap: bật SHAP cho các nhánh dùng XGBoost.
- enable_lime: bật LIME cho local explanation.
- max_background_samples: số mẫu nền tối đa cho SHAP/LIME.
- max_explain_samples: số mẫu test giải thích bằng SHAP.
- max_lime_samples: số mẫu test giải thích bằng LIME.
- lime_num_features: số feature rule mỗi mẫu cho LIME.
- random_state: seed cho sampling explainability.

### Output sau khi chạy xong

Sau khi chạy toàn bộ Notebook 01 (Cell 2 rồi Cell 4), output sẽ gồm các nhóm sau trong thư mục batch run mới:

1. Output tổng hợp cấp batch run
- experiments / `batch_run_YYYYMMDD_HHMM/`
- `global_leaderboard_metrics.csv`: metrics của model mình (toàn bộ run trong pipeline)
- `global_leaderboard_profiling.csv`: profiling E2E của model mình
- `global_compare_ours_vs_sota.csv`: bảng gộp so sánh `OURS` và `SOTA`
- `sota_metrics.csv`: metrics SOTA tính trực tiếp từ cột score/rankscore/pred
- `sota_column_mapping.csv`: mapping model SOTA -> cột nào được dùng
- `sota_required_columns_audit.csv`: audit đủ cột/thiếu cột/null theo từng dataset test

2. Output theo từng experiment con
Mỗi tổ hợp dataset + pooling + ablation + model + network sẽ có 1 thư mục con, ví dụ:
- `Train1Val_Test_center_dna_prot_nt_v1_500m_esm1b_650m_PyTorch_Concat/`

Bên trong thường có:
- `test_probabilities.csv`: dự đoán chi tiết theo Variant_ID
- `tensorboard_logs/`: log train/val
- `checkpoints/best_model.pth`: với nhánh PyTorch

3. Output explainability (nếu bật trong EXPLAINABILITY)
Trong các run dùng XGBoost (`hybrid`, `xgboost_pure`) sẽ có:
- `explainability/shap_global_importance.csv`
- `explainability/shap_local_top_ranked.csv`
- `explainability/lime_local_explanations.csv` (chỉ có khi `enable_lime=True`)

4. Output hiển thị ngay trên notebook (không phải file)
- In đường dẫn batch run
- In số dòng của metrics/profiling
- `display(df_compare.head(...))` cho bảng so sánh OURS vs SOTA
- `display(mapping/audit head(...))` để xem nhanh mapping cột và lỗi audit (nếu có)

Các đầu vào mà Notebook 01 kỳ vọng

- Bio normalized: dưới D:/variant_data/processed_parquet
- Geometry: dưới D:/variant_data/geometry/split
- Embedding pt: dưới D:/variant_data/fm_embeddings/split
- FM profiling json: `fm_profiling.json`

### SET UP

In [1]:
import os
import sys
import importlib
import torch
import pandas as pd

sys.path.append(os.path.abspath("../"))

try:
    import thop
    print(f"[*] thop version: {getattr(thop, '__version__', 'unknown')}")
except Exception as e:
    print(f"[CẢNH BÁO] thop import lỗi: {e}")

import core.module05_fusion_classifier.dataset as dataset_module
importlib.reload(dataset_module)
import core.module05_fusion_classifier.evaluator_profiler as evalprof_module
importlib.reload(evalprof_module)
import core.module05_fusion_classifier.pipeline as pipeline_module
importlib.reload(pipeline_module)
from core.module05_fusion_classifier.pipeline import FusionBatchPipeline
from core.module05_fusion_classifier.sota_benchmark import (
    evaluate_sota_from_test_files,
    SOTA_MODEL_COLUMNS_FULL,
    SOTA_REQUIRED_COLUMNS,
)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"[*] Device: {DEVICE}")

BASE_DIR = "D:/variant_data"
FM_PROFILE_JSON = f"{BASE_DIR}/profiling/fm_profiling.json"
GEOM_PROFILE_JSON = f"{BASE_DIR}/profiling/geom_profiling.json"

# Default config dua ve notebook de de kiem soat
CONFIG = {
    "batch_size": 256,
    "epochs": 30,
    "lr": 1e-4,
    "weight_decay": 1e-3,
    "lr_factor": 0.5,
    "lr_patience": 3,
    "early_stop_patience": 6,
    "num_workers": 0,
}

MODELS_SPACE = [
    {"name": "nt_v1_500m", "seq_type": "dna"},
    {"name": "nt_v3_650m", "seq_type": "dna"},
    {"name": "nt_v2_500m", "seq_type": "dna"},
    {"name": "esm1b_650m", "seq_type": "protein"},
    {"name": "esm1v_650m", "seq_type": "protein"},
    {"name": "esm2_650m", "seq_type": "protein"},
    {"name": "esmc_600m", "seq_type": "protein"},
]

EXPERIMENTS = [
    {"name": "PyTorch_Concat", "type": "pytorch", "fusion": "concat"},
    {"name": "PyTorch_CrossAttn", "type": "pytorch", "fusion": "cross_attention"},
    {"name": "PyTorch_Transformer", "type": "pytorch", "fusion": "transformer"},
    {"name": "PyTorch_Gating", "type": "pytorch", "fusion": "gating"},
    {"name": "Pure_XGBoost_Concat", "type": "xgboost_pure", "fusion": "concat"},
    {"name": "Hybrid_Concat_XGBoost", "type": "hybrid", "fusion": "concat"},
    {"name": "Hybrid_CrossAttn_XGBoost", "type": "hybrid", "fusion": "cross_attention"},
    {"name": "Hybrid_Transformer_XGBoost", "type": "hybrid", "fusion": "transformer"},
    {"name": "Hybrid_Gating_XGBoost", "type": "hybrid", "fusion": "gating"},
]

# Dataset split run theo du lieu hien co: train1/val va 4 tap test
datasets = [
    {"name": "Train3Val_Test", "train": "train3", "val": "val", "test": "test"},
    {"name": "Train3Val_ClinVarHQ", "train": "train3", "val": "val", "test": "clinvarhq"},
    {"name": "Train3Val_UniProt", "train": "train3", "val": "val", "test": "uniprot"},
    {"name": "Train3Val_ProteinGym", "train": "train3", "val": "val", "test": "proteingym"},
]

pooling_strategies = ["center", "cls", "mean"]

# Explainability: nen bat SHAP truoc, LIME de sau vi ton thoi gian hon
EXPLAINABILITY = {
    "enable_shap": True,
    "enable_lime": False,
    "max_background_samples": 512,
    "max_explain_samples": 200,
    "lime_num_features": 20,
    "max_lime_samples": 20,
    "random_state": 42,
}

# [MOI] SOTA benchmark tu cot score/rankscore/pred trong 4 test files
SOTA_TEST_FILES = {
    "test": f"{BASE_DIR}/test_full_seq_after_vep_final.parquet",
    "clinvarhq": f"{BASE_DIR}/clinvarhq_full_seq_after_vep_final.parquet",
    "uniprot": f"{BASE_DIR}/uniprot_full_seq_after_vep_final.parquet",
    "proteingym": f"{BASE_DIR}/proteingym_full_seq_after_vep_final.parquet",
}
SOTA_LABEL_COL = None
SOTA_LABEL_CANDIDATES = ["Pathogenicity_Label", "Label"]
SOTA_THRESHOLD = 0.5

# Dung bo cot day du cho SOTA theo danh sach chuan
SOTA_MODEL_COLUMNS = SOTA_MODEL_COLUMNS_FULL
SOTA_REQUIRED = SOTA_REQUIRED_COLUMNS
SOTA_ENFORCE_REQUIRED = True

# Resume control: dat True de tiep tuc 1 batch run dang do
RESUME_ENABLED = True
RESUME_BATCH_RUN_DIR = '../experiments/batch_run_20260904_1800' # vd: '../experiments/batch_run_20260902_1430'

pipeline = FusionBatchPipeline(
    base_dir=BASE_DIR,
    config=CONFIG,
    datasets=datasets,
    models_space=MODELS_SPACE,
    pooling_strategies=pooling_strategies,
    experiments=EXPERIMENTS,
    explainability=EXPLAINABILITY,
    fm_profile_json=FM_PROFILE_JSON,
    geom_profile_json=GEOM_PROFILE_JSON,
    batch_run_dir=RESUME_BATCH_RUN_DIR,
)

print(f"[*] FM profiling json: {FM_PROFILE_JSON}")
print(f"[*] Geometry profiling json: {GEOM_PROFILE_JSON}")
print(f"[*] Batch run dir: {pipeline.batch_run_dir}")

[*] thop version: 0.1.1
[*] Device: cuda
[*] FM profiling json: D:/variant_data/profiling/fm_profiling.json
[*] Geometry profiling json: D:/variant_data/profiling/geom_profiling.json
[*] Batch run dir: d:\Missense_variant_pathogenicity_prediction\experiments\batch_run_20260904_1800

c:\Users\Dung\anaconda3\envs\missense_variant_patho_predict_clean\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### The Master Loop

In [2]:
# 1) Benchmark SOTA truc tiep tu cot score/rankscore/pred tren 4 test files
sota_result = evaluate_sota_from_test_files(
    test_files=SOTA_TEST_FILES,
    output_dir=pipeline.batch_run_dir,
    label_col=SOTA_LABEL_COL,
    label_candidates=SOTA_LABEL_CANDIDATES,
    model_columns=SOTA_MODEL_COLUMNS,
    threshold=SOTA_THRESHOLD,
    required_columns=SOTA_REQUIRED,
    enforce_required_columns=SOTA_ENFORCE_REQUIRED,
)
print(f"[SOTA] Metrics CSV: {sota_result['metrics_path']} | rows={sota_result['num_rows']}")
print(f"[SOTA] Mapping CSV: {sota_result['mapping_path']} | unique models={sota_result['num_models']}")
if sota_result.get('audit') is not None:
    audit = sota_result['audit']
    print(f"[SOTA] Audit CSV: {audit['audit_path']}")
    print(f"[SOTA] missing_count={audit['missing_count']} | null_issue_count={audit['null_issue_count']}")

# 2) Chay pipeline model cua chung ta
result = pipeline.run(resume=RESUME_ENABLED)

print("\n" + "=" * 80)
print("[THANH CONG] Module 5 batch runner da hoan tat")
print("=" * 80)
print(f"Batch run dir: {result['batch_run_dir']}")
print(f"Metrics CSV: {result['metrics_path']} | rows={result['num_rows_metrics']}")
print(f"Profiling CSV: {result['profiling_path']} | rows={result['num_rows_profiling']}")

# 3) Gop bang so sanh SOTA vs Ours
ours = pd.read_csv(result["metrics_path"])
sota = pd.read_csv(sota_result["metrics_path"])
ours["Source"] = "OURS"
sota["Source"] = "SOTA"

df_compare = pd.concat([ours, sota], ignore_index=True)
df_compare = df_compare.sort_values(by=["Dataset", "MCC"], ascending=[True, False])
df_compare.to_csv(f"{result['batch_run_dir']}/global_compare_ours_vs_sota.csv", index=False)

print(f"Compare CSV: {result['batch_run_dir']}/global_compare_ours_vs_sota.csv")
display(df_compare.head(40))
display(pd.read_csv(sota_result["mapping_path"]).head(40))
if sota_result.get('audit') is not None:
    display(pd.read_csv(sota_result['audit']['audit_path']).query('exists == False or null_count > 0').head(100))

[SOTA] Metrics CSV: d:\Missense_variant_pathogenicity_prediction\experiments\batch_run_20260904_1800/sota_metrics.csv | rows=112
[SOTA] Mapping CSV: d:\Missense_variant_pathogenicity_prediction\experiments\batch_run_20260904_1800/sota_column_mapping.csv | unique models=28
[SOTA] Audit CSV: d:\Missense_variant_pathogenicity_prediction\experiments\batch_run_20260904_1800/sota_required_columns_audit.csv
[SOTA] missing_count=0 | null_issue_count=0
[*] Device: cuda
[*] Batch run dir: d:\Missense_variant_pathogenicity_prediction\experiments\batch_run_20260904_1800
[*] Resume mode: loaded metrics=2196 rows, profiling=2196 rows

================================================================================
[*] POOLING: CENTER
================================================================================
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4997 | val_loss=0.4078 | val_mcc=0.5260 | val_f1=0.6224 | val_auroc=0.8637

[Epoch 02] train_loss=0.4255 | val_loss=0.4217 | val_mcc=0.5318 | val_f1=0.6264 | val_auroc=0.8715

[Epoch 03] train_loss=0.3858 | val_loss=0.3884 | val_mcc=0.5490 | val_f1=0.6403 | val_auroc=0.8767

[Epoch 04] train_loss=0.3404 | val_loss=0.3929 | val_mcc=0.5356 | val_f1=0.6299 | val_auroc=0.8738

[Epoch 05] train_loss=0.2900 | val_loss=0.4452 | val_mcc=0.5152 | val_f1=0.6135 | val_auroc=0.8696

[Epoch 06] train_loss=0.2409 | val_loss=0.4610 | val_mcc=0.5162 | val_f1=0.6146 | val_auroc=0.8666

[Epoch 07] train_loss=0.1858 | val_loss=0.5281 | val_mcc=0.4937 | val_f1=0.5971 | val_auroc=0.8603

[Epoch 08] train_loss=0.1286 | val_loss=0.5119 | val_mcc=0.5085 | val_f1=0.6088 | val_auroc=0.8631

[Epoch 09] train_loss=0.1067 | val_loss=0.5427 | val_mcc=0.5148 | val_f1=0.6138 | val_auroc=0.8658
[EarlyStop] epoch=9 | best_val_mcc=0.5490
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6218 | F1=0.7291 | AUROC=0.8982 | AUPRC=0.8202
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5903 | F1=0.7907 | AUROC=0.8735 | AUPRC=0.8866
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3863 | F1=0.6913 | AUROC=0.7512 | AUPRC=0.7450
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5886 | F1=0.7782 | AUROC=0.8724 | AUPRC=0.8641
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5031 | val_loss=0.4210 | val_mcc=0.5115 | val_f1=0.6112 | val_auroc=0.8647

[Epoch 02] train_loss=0.4366 | val_loss=0.3921 | val_mcc=0.5392 | val_f1=0.6327 | val_auroc=0.8705

[Epoch 03] train_loss=0.4048 | val_loss=0.4066 | val_mcc=0.5444 | val_f1=0.6365 | val_auroc=0.8780

[Epoch 04] train_loss=0.3668 | val_loss=0.4067 | val_mcc=0.5201 | val_f1=0.6179 | val_auroc=0.8686

[Epoch 05] train_loss=0.3128 | val_loss=0.4410 | val_mcc=0.5114 | val_f1=0.6112 | val_auroc=0.8648

[Epoch 06] train_loss=0.2644 | val_loss=0.5596 | val_mcc=0.4840 | val_f1=0.5877 | val_auroc=0.8596

[Epoch 07] train_loss=0.2096 | val_loss=0.5809 | val_mcc=0.4900 | val_f1=0.5942 | val_auroc=0.8542

[Epoch 08] train_loss=0.1443 | val_loss=0.6543 | val_mcc=0.4845 | val_f1=0.5901 | val_auroc=0.8519

[Epoch 09] train_loss=0.1151 | val_loss=0.7006 | val_mcc=0.4938 | val_f1=0.5973 | val_auroc=0.8513
[EarlyStop] epoch=9 | best_val_mcc=0.5444
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6185 | F1=0.7277 | AUROC=0.8973 | AUPRC=0.8191
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5988 | F1=0.7977 | AUROC=0.8681 | AUPRC=0.8825
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4001 | F1=0.7033 | AUROC=0.7582 | AUPRC=0.7465
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5801 | F1=0.7772 | AUROC=0.8723 | AUPRC=0.8608
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4993 | val_loss=0.4427 | val_mcc=0.5107 | val_f1=0.6101 | val_auroc=0.8664

[Epoch 02] train_loss=0.4259 | val_loss=0.3645 | val_mcc=0.5692 | val_f1=0.6554 | val_auroc=0.8815

[Epoch 03] train_loss=0.3921 | val_loss=0.3800 | val_mcc=0.5536 | val_f1=0.6438 | val_auroc=0.8785

[Epoch 04] train_loss=0.3435 | val_loss=0.4016 | val_mcc=0.5198 | val_f1=0.6173 | val_auroc=0.8656

[Epoch 05] train_loss=0.2916 | val_loss=0.4852 | val_mcc=0.5174 | val_f1=0.6146 | val_auroc=0.8708

[Epoch 06] train_loss=0.2351 | val_loss=0.4405 | val_mcc=0.5249 | val_f1=0.6197 | val_auroc=0.8608

[Epoch 07] train_loss=0.1630 | val_loss=0.5472 | val_mcc=0.5105 | val_f1=0.6105 | val_auroc=0.8605

[Epoch 08] train_loss=0.1264 | val_loss=0.6537 | val_mcc=0.4958 | val_f1=0.5982 | val_auroc=0.8606
[EarlyStop] epoch=8 | best_val_mcc=0.5692
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6489 | F1=0.7453 | AUROC=0.8979 | AUPRC=0.8215
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6048 | F1=0.7872 | AUROC=0.8711 | AUPRC=0.8862
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4096 | F1=0.6931 | AUROC=0.7530 | AUPRC=0.7459
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5816 | F1=0.7691 | AUROC=0.8665 | AUPRC=0.8609
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5086 | val_loss=0.4087 | val_mcc=0.5243 | val_f1=0.6211 | val_auroc=0.8630

[Epoch 02] train_loss=0.4256 | val_loss=0.4226 | val_mcc=0.5210 | val_f1=0.6179 | val_auroc=0.8722

[Epoch 03] train_loss=0.3771 | val_loss=0.3971 | val_mcc=0.5395 | val_f1=0.6329 | val_auroc=0.8735

[Epoch 04] train_loss=0.3223 | val_loss=0.3935 | val_mcc=0.5337 | val_f1=0.6283 | val_auroc=0.8723

[Epoch 05] train_loss=0.2625 | val_loss=0.4366 | val_mcc=0.5243 | val_f1=0.6212 | val_auroc=0.8670

[Epoch 06] train_loss=0.2021 | val_loss=0.4718 | val_mcc=0.5098 | val_f1=0.6099 | val_auroc=0.8634

[Epoch 07] train_loss=0.1455 | val_loss=0.5506 | val_mcc=0.4940 | val_f1=0.5976 | val_auroc=0.8594

[Epoch 08] train_loss=0.0942 | val_loss=0.5531 | val_mcc=0.5156 | val_f1=0.6143 | val_auroc=0.8646

[Epoch 09] train_loss=0.0731 | val_loss=0.6051 | val_mcc=0.5058 | val_f1=0.6065 | val_auroc=0.8628
[EarlyStop] epoch=9 | best_val_mcc=0.5395
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6074 | F1=0.7196 | AUROC=0.8949 | AUPRC=0.8105
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6159 | F1=0.8046 | AUROC=0.8745 | AUPRC=0.8848
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4270 | F1=0.7154 | AUROC=0.7631 | AUPRC=0.7484
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5736 | F1=0.7741 | AUROC=0.8690 | AUPRC=0.8599
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 308.
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6193 | F1=0.7267 | AUROC=0.8947 | AUPRC=0.8127
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5904 | F1=0.7901 | AUROC=0.8771 | AUPRC=0.8802
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4134 | F1=0.7027 | AUROC=0.7568 | AUPRC=0.7421
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5903 | F1=0.7760 | AUROC=0.8725 | AUPRC=0.8667
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 168.
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6243 | F1=0.7308 | AUROC=0.8988 | AUPRC=0.8188
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5960 | F1=0.7936 | AUROC=0.8747 | AUPRC=0.8829
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4343 | F1=0.7155 | AUROC=0.7633 | AUPRC=0.7581
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5848 | F1=0.7788 | AUROC=0.8665 | AUPRC=0.8566
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 39.
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6270 | F1=0.7327 | AUROC=0.8948 | AUPRC=0.8175
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6132 | F1=0.8017 | AUROC=0.8775 | AUPRC=0.8816
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3923 | F1=0.6943 | AUROC=0.7549 | AUPRC=0.7509
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5990 | F1=0.7851 | AUROC=0.8679 | AUPRC=0.8605
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 113.
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6188 | F1=0.7270 | AUROC=0.8948 | AUPRC=0.8080
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5966 | F1=0.7906 | AUROC=0.8676 | AUPRC=0.8737
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3984 | F1=0.7001 | AUROC=0.7543 | AUPRC=0.7426
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5724 | F1=0.7697 | AUROC=0.8652 | AUPRC=0.8554
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.4965 | val_loss=0.4110 | val_mcc=0.5384 | val_f1=0.6320 | val_auroc=0.8684

[Epoch 02] train_loss=0.4429 | val_loss=0.4202 | val_mcc=0.5356 | val_f1=0.6292 | val_auroc=0.8790

[Epoch 03] train_loss=0.4179 | val_loss=0.3852 | val_mcc=0.5585 | val_f1=0.6477 | val_auroc=0.8870

[Epoch 04] train_loss=0.3958 | val_loss=0.3836 | val_mcc=0.5734 | val_f1=0.6593 | val_auroc=0.8931

[Epoch 05] train_loss=0.3777 | val_loss=0.4037 | val_mcc=0.5458 | val_f1=0.6374 | val_auroc=0.8853

[Epoch 06] train_loss=0.3605 | val_loss=0.3821 | val_mcc=0.5612 | val_f1=0.6498 | val_auroc=0.8858

[Epoch 07] train_loss=0.3400 | val_loss=0.3845 | val_mcc=0.5618 | val_f1=0.6503 | val_auroc=0.8890

[Epoch 08] train_loss=0.3257 | val_loss=0.3959 | val_mcc=0.5601 | val_f1=0.6489 | val_auroc=0.8900

[Epoch 09] train_loss=0.2951 | val_loss=0.4074 | val_mcc=0.5594 | val_f1=0.6483 | val_auroc=0.8872

[Epoch 10] train_loss=0.2780 | val_loss=0.4193 | val_mcc=0.5471 | val_f1=0.6387 | val_auroc=0.8860
[EarlyStop] epoch=10 | best_val_mcc=0.5734
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6435 | F1=0.7443 | AUROC=0.9082 | AUPRC=0.8353
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6331 | F1=0.8122 | AUROC=0.8941 | AUPRC=0.8968
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4284 | F1=0.7146 | AUROC=0.7761 | AUPRC=0.7718
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5982 | F1=0.7832 | AUROC=0.8876 | AUPRC=0.8786
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5020 | val_loss=0.3841 | val_mcc=0.5430 | val_f1=0.6350 | val_auroc=0.8727

[Epoch 02] train_loss=0.4488 | val_loss=0.3993 | val_mcc=0.5443 | val_f1=0.6367 | val_auroc=0.8778

[Epoch 03] train_loss=0.4276 | val_loss=0.4195 | val_mcc=0.5461 | val_f1=0.6364 | val_auroc=0.8879

[Epoch 04] train_loss=0.4065 | val_loss=0.3506 | val_mcc=0.5744 | val_f1=0.6588 | val_auroc=0.8898

[Epoch 05] train_loss=0.3904 | val_loss=0.3559 | val_mcc=0.5846 | val_f1=0.6673 | val_auroc=0.8921

[Epoch 06] train_loss=0.3745 | val_loss=0.4245 | val_mcc=0.5500 | val_f1=0.6401 | val_auroc=0.8882

[Epoch 07] train_loss=0.3544 | val_loss=0.4012 | val_mcc=0.5536 | val_f1=0.6439 | val_auroc=0.8791

[Epoch 08] train_loss=0.3368 | val_loss=0.4050 | val_mcc=0.5609 | val_f1=0.6496 | val_auroc=0.8869

[Epoch 09] train_loss=0.3228 | val_loss=0.4762 | val_mcc=0.5389 | val_f1=0.6301 | val_auroc=0.8865

[Epoch 10] train_loss=0.2880 | val_loss=0.4148 | val_mcc=0.5500 | val_f1=0.6407 | val_auroc=0.8793

[Epoch 11] train_loss=0.2761 | val_loss=0.4824 | val_mcc=0.5429 | val_f1=0.6352 | val_auroc=0.8824
[EarlyStop] epoch=11 | best_val_mcc=0.5846
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6577 | F1=0.7513 | AUROC=0.9084 | AUPRC=0.8353
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6123 | F1=0.7940 | AUROC=0.8869 | AUPRC=0.8900
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4183 | F1=0.6997 | AUROC=0.7745 | AUPRC=0.7636
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5993 | F1=0.7771 | AUROC=0.8798 | AUPRC=0.8722
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4974 | val_loss=0.3609 | val_mcc=0.5532 | val_f1=0.6368 | val_auroc=0.8602

[Epoch 02] train_loss=0.4452 | val_loss=0.3601 | val_mcc=0.5654 | val_f1=0.6511 | val_auroc=0.8792

[Epoch 03] train_loss=0.4188 | val_loss=0.3599 | val_mcc=0.5709 | val_f1=0.6569 | val_auroc=0.8880

[Epoch 04] train_loss=0.3984 | val_loss=0.3510 | val_mcc=0.5810 | val_f1=0.6644 | val_auroc=0.8885

[Epoch 05] train_loss=0.3790 | val_loss=0.4130 | val_mcc=0.5533 | val_f1=0.6429 | val_auroc=0.8878

[Epoch 06] train_loss=0.3633 | val_loss=0.3908 | val_mcc=0.5721 | val_f1=0.6582 | val_auroc=0.8920

[Epoch 07] train_loss=0.3430 | val_loss=0.4585 | val_mcc=0.5378 | val_f1=0.6299 | val_auroc=0.8860

[Epoch 08] train_loss=0.3256 | val_loss=0.3688 | val_mcc=0.5748 | val_f1=0.6567 | val_auroc=0.8829

[Epoch 09] train_loss=0.2931 | val_loss=0.4564 | val_mcc=0.5414 | val_f1=0.6337 | val_auroc=0.8827

[Epoch 10] train_loss=0.2773 | val_loss=0.4201 | val_mcc=0.5617 | val_f1=0.6501 | val_auroc=0.8853
[EarlyStop] epoch=10 | best_val_mcc=0.5810
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6511 | F1=0.7471 | AUROC=0.9057 | AUPRC=0.8286
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6120 | F1=0.7946 | AUROC=0.8863 | AUPRC=0.8936
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4273 | F1=0.6963 | AUROC=0.7681 | AUPRC=0.7618
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6103 | F1=0.7835 | AUROC=0.8797 | AUPRC=0.8678
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5045 | val_loss=0.4121 | val_mcc=0.5307 | val_f1=0.6261 | val_auroc=0.8700

[Epoch 02] train_loss=0.4437 | val_loss=0.3624 | val_mcc=0.5637 | val_f1=0.6502 | val_auroc=0.8810

[Epoch 03] train_loss=0.4160 | val_loss=0.3785 | val_mcc=0.5667 | val_f1=0.6541 | val_auroc=0.8840

[Epoch 04] train_loss=0.3960 | val_loss=0.3669 | val_mcc=0.5660 | val_f1=0.6533 | val_auroc=0.8898

[Epoch 05] train_loss=0.3742 | val_loss=0.3481 | val_mcc=0.5823 | val_f1=0.6651 | val_auroc=0.8928

[Epoch 06] train_loss=0.3525 | val_loss=0.3793 | val_mcc=0.5665 | val_f1=0.6539 | val_auroc=0.8881

[Epoch 07] train_loss=0.3352 | val_loss=0.3951 | val_mcc=0.5558 | val_f1=0.6455 | val_auroc=0.8872

[Epoch 08] train_loss=0.3144 | val_loss=0.3764 | val_mcc=0.5620 | val_f1=0.6500 | val_auroc=0.8848

[Epoch 09] train_loss=0.2972 | val_loss=0.4274 | val_mcc=0.5472 | val_f1=0.6389 | val_auroc=0.8804

[Epoch 10] train_loss=0.2635 | val_loss=0.4291 | val_mcc=0.5486 | val_f1=0.6396 | val_auroc=0.8876

[Epoch 11] train_loss=0.2469 | val_loss=0.4465 | val_mcc=0.5459 | val_f1=0.6374 | val_auroc=0.8836
[EarlyStop] epoch=11 | best_val_mcc=0.5823
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6619 | F1=0.7540 | AUROC=0.9078 | AUPRC=0.8330
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6240 | F1=0.7994 | AUROC=0.8871 | AUPRC=0.8916
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4425 | F1=0.7112 | AUROC=0.7739 | AUPRC=0.7636
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5993 | F1=0.7778 | AUROC=0.8830 | AUPRC=0.8749
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 344.
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6337 | F1=0.7376 | AUROC=0.9034 | AUPRC=0.8229
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6045 | F1=0.8000 | AUROC=0.8889 | AUPRC=0.8878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4373 | F1=0.7174 | AUROC=0.7708 | AUPRC=0.7652
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6022 | F1=0.7875 | AUROC=0.8772 | AUPRC=0.8637
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 192.
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6341 | F1=0.7381 | AUROC=0.9040 | AUPRC=0.8242
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6045 | F1=0.7994 | AUROC=0.8784 | AUPRC=0.8791
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4030 | F1=0.7043 | AUROC=0.7690 | AUPRC=0.7638
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.6069 | F1=0.7907 | AUROC=0.8778 | AUPRC=0.8715
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 111.
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6344 | F1=0.7382 | AUROC=0.9064 | AUPRC=0.8284
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6388 | F1=0.8151 | AUROC=0.8887 | AUPRC=0.8922
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4181 | F1=0.7122 | AUROC=0.7701 | AUPRC=0.7598
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5906 | F1=0.7804 | AUROC=0.8777 | AUPRC=0.8649
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 79.
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6342 | F1=0.7377 | AUROC=0.9006 | AUPRC=0.8204
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6131 | F1=0.8029 | AUROC=0.8859 | AUPRC=0.8879
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4135 | F1=0.7084 | AUROC=0.7656 | AUPRC=0.7580
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5916 | F1=0.7803 | AUROC=0.8735 | AUPRC=0.8635
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.4976 | val_loss=0.4114 | val_mcc=0.5217 | val_f1=0.6192 | val_auroc=0.8669

[Epoch 02] train_loss=0.4302 | val_loss=0.4094 | val_mcc=0.5366 | val_f1=0.6301 | val_auroc=0.8801

[Epoch 03] train_loss=0.3964 | val_loss=0.3635 | val_mcc=0.5710 | val_f1=0.6572 | val_auroc=0.8868

[Epoch 04] train_loss=0.3664 | val_loss=0.3939 | val_mcc=0.5463 | val_f1=0.6379 | val_auroc=0.8824

[Epoch 05] train_loss=0.3406 | val_loss=0.3760 | val_mcc=0.5600 | val_f1=0.6489 | val_auroc=0.8860

[Epoch 06] train_loss=0.3115 | val_loss=0.3787 | val_mcc=0.5635 | val_f1=0.6515 | val_auroc=0.8863

[Epoch 07] train_loss=0.2863 | val_loss=0.4661 | val_mcc=0.5091 | val_f1=0.6081 | val_auroc=0.8743

[Epoch 08] train_loss=0.2435 | val_loss=0.4179 | val_mcc=0.5460 | val_f1=0.6379 | val_auroc=0.8845

[Epoch 09] train_loss=0.2226 | val_loss=0.4434 | val_mcc=0.5316 | val_f1=0.6266 | val_auroc=0.8803
[EarlyStop] epoch=9 | best_val_mcc=0.5710
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6396 | F1=0.7402 | AUROC=0.9011 | AUPRC=0.8231
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5825 | F1=0.7822 | AUROC=0.8765 | AUPRC=0.8835
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4211 | F1=0.7031 | AUROC=0.7690 | AUPRC=0.7540
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5790 | F1=0.7729 | AUROC=0.8711 | AUPRC=0.8630
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5012 | val_loss=0.4152 | val_mcc=0.5231 | val_f1=0.6202 | val_auroc=0.8687

[Epoch 02] train_loss=0.4402 | val_loss=0.3685 | val_mcc=0.5623 | val_f1=0.6495 | val_auroc=0.8796

[Epoch 03] train_loss=0.4122 | val_loss=0.3349 | val_mcc=0.5845 | val_f1=0.6640 | val_auroc=0.8867

[Epoch 04] train_loss=0.3909 | val_loss=0.3856 | val_mcc=0.5527 | val_f1=0.6432 | val_auroc=0.8814

[Epoch 05] train_loss=0.3608 | val_loss=0.3669 | val_mcc=0.5663 | val_f1=0.6534 | val_auroc=0.8842

[Epoch 06] train_loss=0.3398 | val_loss=0.4031 | val_mcc=0.5568 | val_f1=0.6463 | val_auroc=0.8783

[Epoch 07] train_loss=0.3106 | val_loss=0.4483 | val_mcc=0.5312 | val_f1=0.6259 | val_auroc=0.8762

[Epoch 08] train_loss=0.2696 | val_loss=0.4675 | val_mcc=0.5382 | val_f1=0.6312 | val_auroc=0.8773

[Epoch 09] train_loss=0.2465 | val_loss=0.4506 | val_mcc=0.5531 | val_f1=0.6435 | val_auroc=0.8770
[EarlyStop] epoch=9 | best_val_mcc=0.5845
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6540 | F1=0.7435 | AUROC=0.9025 | AUPRC=0.8288
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5790 | F1=0.7615 | AUROC=0.8784 | AUPRC=0.8850
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4262 | F1=0.6883 | AUROC=0.7616 | AUPRC=0.7507
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6013 | F1=0.7703 | AUROC=0.8744 | AUPRC=0.8688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4995 | val_loss=0.4178 | val_mcc=0.5199 | val_f1=0.6176 | val_auroc=0.8709

[Epoch 02] train_loss=0.4320 | val_loss=0.4199 | val_mcc=0.5514 | val_f1=0.6415 | val_auroc=0.8834

[Epoch 03] train_loss=0.3996 | val_loss=0.3574 | val_mcc=0.5714 | val_f1=0.6567 | val_auroc=0.8849

[Epoch 04] train_loss=0.3726 | val_loss=0.4154 | val_mcc=0.5356 | val_f1=0.6290 | val_auroc=0.8839

[Epoch 05] train_loss=0.3442 | val_loss=0.4038 | val_mcc=0.5484 | val_f1=0.6396 | val_auroc=0.8883

[Epoch 06] train_loss=0.3178 | val_loss=0.3787 | val_mcc=0.5626 | val_f1=0.6506 | val_auroc=0.8853

[Epoch 07] train_loss=0.2870 | val_loss=0.4205 | val_mcc=0.5482 | val_f1=0.6397 | val_auroc=0.8813

[Epoch 08] train_loss=0.2398 | val_loss=0.4690 | val_mcc=0.5308 | val_f1=0.6253 | val_auroc=0.8835

[Epoch 09] train_loss=0.2187 | val_loss=0.4514 | val_mcc=0.5425 | val_f1=0.6353 | val_auroc=0.8777
[EarlyStop] epoch=9 | best_val_mcc=0.5714
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6593 | F1=0.7520 | AUROC=0.9048 | AUPRC=0.8298
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6147 | F1=0.7964 | AUROC=0.8794 | AUPRC=0.8869
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4291 | F1=0.7035 | AUROC=0.7689 | AUPRC=0.7560
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5806 | F1=0.7703 | AUROC=0.8683 | AUPRC=0.8580
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5001 | val_loss=0.4127 | val_mcc=0.5222 | val_f1=0.6196 | val_auroc=0.8669

[Epoch 02] train_loss=0.4301 | val_loss=0.3953 | val_mcc=0.5393 | val_f1=0.6327 | val_auroc=0.8793

[Epoch 03] train_loss=0.3940 | val_loss=0.3907 | val_mcc=0.5503 | val_f1=0.6411 | val_auroc=0.8835

[Epoch 04] train_loss=0.3595 | val_loss=0.4045 | val_mcc=0.5415 | val_f1=0.6338 | val_auroc=0.8865

[Epoch 05] train_loss=0.3302 | val_loss=0.4158 | val_mcc=0.5464 | val_f1=0.6375 | val_auroc=0.8868

[Epoch 06] train_loss=0.2977 | val_loss=0.4478 | val_mcc=0.5246 | val_f1=0.6197 | val_auroc=0.8799

[Epoch 07] train_loss=0.2613 | val_loss=0.4866 | val_mcc=0.5145 | val_f1=0.6111 | val_auroc=0.8775

[Epoch 08] train_loss=0.2130 | val_loss=0.4459 | val_mcc=0.5381 | val_f1=0.6317 | val_auroc=0.8794

[Epoch 09] train_loss=0.1864 | val_loss=0.4878 | val_mcc=0.5274 | val_f1=0.6230 | val_auroc=0.8786
[EarlyStop] epoch=9 | best_val_mcc=0.5503
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6188 | F1=0.7276 | AUROC=0.8982 | AUPRC=0.8177
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5875 | F1=0.7920 | AUROC=0.8767 | AUPRC=0.8839
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4287 | F1=0.7180 | AUROC=0.7646 | AUPRC=0.7538
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5784 | F1=0.7774 | AUROC=0.8646 | AUPRC=0.8574
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 360.
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6235 | F1=0.7297 | AUROC=0.8979 | AUPRC=0.8178
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6104 | F1=0.8000 | AUROC=0.8863 | AUPRC=0.8886
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4254 | F1=0.7092 | AUROC=0.7627 | AUPRC=0.7477
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5858 | F1=0.7764 | AUROC=0.8741 | AUPRC=0.8659
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 195.
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6267 | F1=0.7325 | AUROC=0.8955 | AUPRC=0.8154
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5993 | F1=0.7923 | AUROC=0.8670 | AUPRC=0.8772
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3864 | F1=0.6932 | AUROC=0.7555 | AUPRC=0.7472
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5807 | F1=0.7765 | AUROC=0.8644 | AUPRC=0.8572
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 75.
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6277 | F1=0.7333 | AUROC=0.9006 | AUPRC=0.8205
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5876 | F1=0.7883 | AUROC=0.8814 | AUPRC=0.8845
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4180 | F1=0.7104 | AUROC=0.7655 | AUPRC=0.7542
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5675 | F1=0.7702 | AUROC=0.8697 | AUPRC=0.8588
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 73.
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6292 | F1=0.7344 | AUROC=0.8972 | AUPRC=0.8155
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5989 | F1=0.7948 | AUROC=0.8714 | AUPRC=0.8784
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4239 | F1=0.7113 | AUROC=0.7637 | AUPRC=0.7501
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5868 | F1=0.7787 | AUROC=0.8689 | AUPRC=0.8628
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.4539 | val_loss=0.2839 | val_mcc=0.6626 | val_f1=0.7282 | val_auroc=0.9398

[Epoch 02] train_loss=0.3669 | val_loss=0.2871 | val_mcc=0.6733 | val_f1=0.7350 | val_auroc=0.9440

[Epoch 03] train_loss=0.3565 | val_loss=0.2798 | val_mcc=0.6766 | val_f1=0.7382 | val_auroc=0.9450

[Epoch 04] train_loss=0.3546 | val_loss=0.2807 | val_mcc=0.6749 | val_f1=0.7365 | val_auroc=0.9458

[Epoch 05] train_loss=0.3491 | val_loss=0.2787 | val_mcc=0.6813 | val_f1=0.7417 | val_auroc=0.9463

[Epoch 06] train_loss=0.3455 | val_loss=0.2739 | val_mcc=0.6797 | val_f1=0.7407 | val_auroc=0.9468

[Epoch 07] train_loss=0.3450 | val_loss=0.2696 | val_mcc=0.6829 | val_f1=0.7436 | val_auroc=0.9477

[Epoch 08] train_loss=0.3426 | val_loss=0.2784 | val_mcc=0.6789 | val_f1=0.7395 | val_auroc=0.9470

[Epoch 09] train_loss=0.3410 | val_loss=0.2769 | val_mcc=0.6801 | val_f1=0.7407 | val_auroc=0.9479

[Epoch 10] train_loss=0.3401 | val_loss=0.2727 | val_mcc=0.6805 | val_f1=0.7414 | val_auroc=0.9476

[Epoch 11] train_loss=0.3372 | val_loss=0.2642 | val_mcc=0.6853 | val_f1=0.7462 | val_auroc=0.9479

[Epoch 12] train_loss=0.3390 | val_loss=0.2661 | val_mcc=0.6863 | val_f1=0.7467 | val_auroc=0.9479

[Epoch 13] train_loss=0.3372 | val_loss=0.2653 | val_mcc=0.6867 | val_f1=0.7472 | val_auroc=0.9479

[Epoch 14] train_loss=0.3372 | val_loss=0.2640 | val_mcc=0.6854 | val_f1=0.7463 | val_auroc=0.9480

[Epoch 15] train_loss=0.3346 | val_loss=0.2653 | val_mcc=0.6855 | val_f1=0.7460 | val_auroc=0.9484

[Epoch 16] train_loss=0.3335 | val_loss=0.2666 | val_mcc=0.6860 | val_f1=0.7464 | val_auroc=0.9483

[Epoch 17] train_loss=0.3333 | val_loss=0.2706 | val_mcc=0.6839 | val_f1=0.7440 | val_auroc=0.9483

[Epoch 18] train_loss=0.3334 | val_loss=0.2662 | val_mcc=0.6861 | val_f1=0.7463 | val_auroc=0.9487

[Epoch 19] train_loss=0.3317 | val_loss=0.2666 | val_mcc=0.6856 | val_f1=0.7460 | val_auroc=0.9485
[EarlyStop] epoch=19 | best_val_mcc=0.6867
[Test] train3__val_center_bio_core_spliceai_None_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.6882 | F1=0.7767 | AUROC=0.9340 | AUPRC=0.8562
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_spliceai_None_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_spliceai_None_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8177 | F1=0.9025 | AUROC=0.9728 | AUPRC=0.9728
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_spliceai_None_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_spliceai_None_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3149 | F1=0.6774 | AUROC=0.7100 | AUPRC=0.6831
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_spliceai_None_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_spliceai_None_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4561 | F1=0.7327 | AUROC=0.8437 | AUPRC=0.8103
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_spliceai_None_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 97.
[Test] train3__val_center_bio_core_spliceai_None_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7040 | F1=0.7878 | AUROC=0.9412 | AUPRC=0.8689
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_spliceai_None_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_spliceai_None_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8107 | F1=0.9007 | AUROC=0.9753 | AUPRC=0.9756
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_spliceai_None_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_spliceai_None_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3470 | F1=0.6928 | AUROC=0.7266 | AUPRC=0.6959
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_spliceai_None_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_spliceai_None_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4829 | F1=0.7438 | AUROC=0.8598 | AUPRC=0.8351
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_spliceai_None_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 95.
[Test] train3__val_center_bio_core_spliceai_None_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6684 | F1=0.7628 | AUROC=0.9287 | AUPRC=0.8417
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_spliceai_None_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_spliceai_None_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8032 | F1=0.8952 | AUROC=0.9661 | AUPRC=0.9676
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_spliceai_None_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_spliceai_None_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3172 | F1=0.6766 | AUROC=0.7101 | AUPRC=0.6839
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['bio_core', 'spliceai']
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_spliceai_None_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_spliceai_None_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4645 | F1=0.7362 | AUROC=0.8319 | AUPRC=0.7998
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.7039 | val_loss=0.6720 | val_mcc=0.0829 | val_f1=0.3158 | val_auroc=0.5752

[Epoch 02] train_loss=0.6654 | val_loss=0.6577 | val_mcc=0.0936 | val_f1=0.3193 | val_auroc=0.5883

[Epoch 03] train_loss=0.6342 | val_loss=0.6834 | val_mcc=0.0984 | val_f1=0.3278 | val_auroc=0.5933

[Epoch 04] train_loss=0.5989 | val_loss=0.7037 | val_mcc=0.1051 | val_f1=0.3328 | val_auroc=0.5921

[Epoch 05] train_loss=0.5487 | val_loss=0.6826 | val_mcc=0.1060 | val_f1=0.3257 | val_auroc=0.5981

[Epoch 06] train_loss=0.4893 | val_loss=0.7615 | val_mcc=0.1004 | val_f1=0.3279 | val_auroc=0.5906

[Epoch 07] train_loss=0.4249 | val_loss=0.8164 | val_mcc=0.1101 | val_f1=0.3346 | val_auroc=0.5965

[Epoch 08] train_loss=0.3598 | val_loss=0.8615 | val_mcc=0.1184 | val_f1=0.3374 | val_auroc=0.6035

[Epoch 09] train_loss=0.3056 | val_loss=0.9575 | val_mcc=0.1121 | val_f1=0.3357 | val_auroc=0.5932

[Epoch 10] train_loss=0.2524 | val_loss=1.0098 | val_mcc=0.1038 | val_f1=0.3290 | val_auroc=0.5941

[Epoch 11] train_loss=0.2079 | val_loss=1.0675 | val_mcc=0.1115 | val_f1=0.3321 | val_auroc=0.5945

[Epoch 12] train_loss=0.1781 | val_loss=1.1966 | val_mcc=0.1113 | val_f1=0.3356 | val_auroc=0.5940

[Epoch 13] train_loss=0.1377 | val_loss=1.1845 | val_mcc=0.1251 | val_f1=0.3424 | val_auroc=0.6006

[Epoch 14] train_loss=0.1192 | val_loss=1.2594 | val_mcc=0.1243 | val_f1=0.3434 | val_auroc=0.6009

[Epoch 15] train_loss=0.1072 | val_loss=1.3477 | val_mcc=0.1153 | val_f1=0.3391 | val_auroc=0.5998

[Epoch 16] train_loss=0.1011 | val_loss=1.3688 | val_mcc=0.1183 | val_f1=0.3404 | val_auroc=0.6009

[Epoch 17] train_loss=0.0878 | val_loss=1.3859 | val_mcc=0.1205 | val_f1=0.3406 | val_auroc=0.6002

[Epoch 18] train_loss=0.0804 | val_loss=1.3698 | val_mcc=0.1234 | val_f1=0.3415 | val_auroc=0.5995

[Epoch 19] train_loss=0.0714 | val_loss=1.3930 | val_mcc=0.1179 | val_f1=0.3380 | val_auroc=0.5996
[EarlyStop] epoch=19 | best_val_mcc=0.1251
[Test] train3__val_center_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.0906 | F1=0.3937 | AUROC=0.5774 | AUPRC=0.3282
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.1123 | F1=0.5530 | AUROC=0.5885 | AUPRC=0.5624
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=-0.0202 | F1=0.4903 | AUROC=0.5121 | AUPRC=0.5025
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.0669 | F1=0.5185 | AUROC=0.5387 | AUPRC=0.4836
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 79.
[Test] train3__val_center_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.0778 | F1=0.3854 | AUROC=0.5695 | AUPRC=0.3267
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.0522 | F1=0.5110 | AUROC=0.5520 | AUPRC=0.5389
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.0277 | F1=0.5120 | AUROC=0.5219 | AUPRC=0.5141
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.0662 | F1=0.5033 | AUROC=0.5419 | AUPRC=0.4839
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 51.
[Test] train3__val_center_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.0511 | F1=0.3739 | AUROC=0.5446 | AUPRC=0.3046
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.0721 | F1=0.5192 | AUROC=0.5590 | AUPRC=0.5407
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.0172 | F1=0.5042 | AUROC=0.5113 | AUPRC=0.5160
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.0134 | F1=0.4836 | AUROC=0.5147 | AUPRC=0.4664
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4904 | val_loss=0.2916 | val_mcc=0.6617 | val_f1=0.7277 | val_auroc=0.9377

[Epoch 02] train_loss=0.3470 | val_loss=0.2882 | val_mcc=0.6639 | val_f1=0.7286 | val_auroc=0.9400

[Epoch 03] train_loss=0.3093 | val_loss=0.2826 | val_mcc=0.6664 | val_f1=0.7313 | val_auroc=0.9384

[Epoch 04] train_loss=0.2765 | val_loss=0.2985 | val_mcc=0.6577 | val_f1=0.7239 | val_auroc=0.9353

[Epoch 05] train_loss=0.2400 | val_loss=0.3221 | val_mcc=0.6408 | val_f1=0.7101 | val_auroc=0.9316

[Epoch 06] train_loss=0.2029 | val_loss=0.3241 | val_mcc=0.6428 | val_f1=0.7129 | val_auroc=0.9284

[Epoch 07] train_loss=0.1642 | val_loss=0.3455 | val_mcc=0.6366 | val_f1=0.7081 | val_auroc=0.9252

[Epoch 08] train_loss=0.1247 | val_loss=0.3775 | val_mcc=0.6300 | val_f1=0.7020 | val_auroc=0.9254

[Epoch 09] train_loss=0.1034 | val_loss=0.3819 | val_mcc=0.6289 | val_f1=0.7017 | val_auroc=0.9239
[EarlyStop] epoch=9 | best_val_mcc=0.6664
[Test] train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.6649 | F1=0.7604 | AUROC=0.9240 | AUPRC=0.8256
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7847 | F1=0.8879 | AUROC=0.9641 | AUPRC=0.9652
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.2947 | F1=0.6708 | AUROC=0.6930 | AUPRC=0.6741
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4397 | F1=0.7262 | AUROC=0.7970 | AUPRC=0.7219
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 177.
[Test] train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6970 | F1=0.7829 | AUROC=0.9390 | AUPRC=0.8630
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8137 | F1=0.8983 | AUROC=0.9760 | AUPRC=0.9758
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3293 | F1=0.6822 | AUROC=0.7146 | AUPRC=0.6996
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4734 | F1=0.7399 | AUROC=0.8499 | AUPRC=0.8059
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 109.
[Test] train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6748 | F1=0.7673 | AUROC=0.9281 | AUPRC=0.8385
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7895 | F1=0.8872 | AUROC=0.9641 | AUPRC=0.9638
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3005 | F1=0.6686 | AUROC=0.7049 | AUPRC=0.6756
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4293 | F1=0.7220 | AUROC=0.8200 | AUPRC=0.7650
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.6874 | val_loss=0.6264 | val_mcc=0.2000 | val_f1=0.3411 | val_auroc=0.6528

[Epoch 02] train_loss=0.6627 | val_loss=0.6029 | val_mcc=0.2244 | val_f1=0.3592 | val_auroc=0.6738

[Epoch 03] train_loss=0.6430 | val_loss=0.5919 | val_mcc=0.2640 | val_f1=0.3982 | val_auroc=0.6903

[Epoch 04] train_loss=0.6233 | val_loss=0.5581 | val_mcc=0.2776 | val_f1=0.3970 | val_auroc=0.6909

[Epoch 05] train_loss=0.6061 | val_loss=0.5682 | val_mcc=0.3061 | val_f1=0.4330 | val_auroc=0.7161

[Epoch 06] train_loss=0.5919 | val_loss=0.5406 | val_mcc=0.2792 | val_f1=0.4108 | val_auroc=0.6950

[Epoch 07] train_loss=0.5766 | val_loss=0.5536 | val_mcc=0.3034 | val_f1=0.4332 | val_auroc=0.7214

[Epoch 08] train_loss=0.5579 | val_loss=0.5805 | val_mcc=0.3210 | val_f1=0.4636 | val_auroc=0.7396

[Epoch 09] train_loss=0.5428 | val_loss=0.5666 | val_mcc=0.3306 | val_f1=0.4665 | val_auroc=0.7475

[Epoch 10] train_loss=0.5252 | val_loss=0.5804 | val_mcc=0.2824 | val_f1=0.4403 | val_auroc=0.7392

[Epoch 11] train_loss=0.5041 | val_loss=0.5586 | val_mcc=0.3461 | val_f1=0.4780 | val_auroc=0.7573

[Epoch 12] train_loss=0.4896 | val_loss=0.6022 | val_mcc=0.3246 | val_f1=0.4716 | val_auroc=0.7637

[Epoch 13] train_loss=0.4695 | val_loss=0.5782 | val_mcc=0.3159 | val_f1=0.4644 | val_auroc=0.7613

[Epoch 14] train_loss=0.4526 | val_loss=0.6165 | val_mcc=0.3398 | val_f1=0.4828 | val_auroc=0.7722

[Epoch 15] train_loss=0.4332 | val_loss=0.5806 | val_mcc=0.3857 | val_f1=0.5145 | val_auroc=0.7822

[Epoch 16] train_loss=0.4150 | val_loss=0.6283 | val_mcc=0.3511 | val_f1=0.4907 | val_auroc=0.7805

[Epoch 17] train_loss=0.4061 | val_loss=0.6405 | val_mcc=0.3441 | val_f1=0.4857 | val_auroc=0.7750

[Epoch 18] train_loss=0.3841 | val_loss=0.6175 | val_mcc=0.3733 | val_f1=0.5071 | val_auroc=0.7800

[Epoch 19] train_loss=0.3683 | val_loss=0.6254 | val_mcc=0.3873 | val_f1=0.5160 | val_auroc=0.7828

[Epoch 20] train_loss=0.3576 | val_loss=0.6621 | val_mcc=0.3310 | val_f1=0.4765 | val_auroc=0.7705

[Epoch 21] train_loss=0.3493 | val_loss=0.7209 | val_mcc=0.3421 | val_f1=0.4842 | val_auroc=0.7707

[Epoch 22] train_loss=0.3290 | val_loss=0.7319 | val_mcc=0.3380 | val_f1=0.4816 | val_auroc=0.7715

[Epoch 23] train_loss=0.3264 | val_loss=0.7359 | val_mcc=0.3525 | val_f1=0.4920 | val_auroc=0.7731

[Epoch 24] train_loss=0.2986 | val_loss=0.7440 | val_mcc=0.3610 | val_f1=0.4982 | val_auroc=0.7769

[Epoch 25] train_loss=0.2860 | val_loss=0.7779 | val_mcc=0.3528 | val_f1=0.4915 | val_auroc=0.7778
[EarlyStop] epoch=25 | best_val_mcc=0.3873
[Test] train3__val_center_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.4356 | F1=0.5923 | AUROC=0.7842 | AUPRC=0.6250
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.4042 | F1=0.6603 | AUROC=0.7659 | AUPRC=0.7696
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.2324 | F1=0.5833 | AUROC=0.6675 | AUPRC=0.6586
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.3904 | F1=0.6536 | AUROC=0.7603 | AUPRC=0.7240
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 257.
[Test] train3__val_center_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.4276 | F1=0.5964 | AUROC=0.8053 | AUPRC=0.6429
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.4110 | F1=0.6987 | AUROC=0.7884 | AUPRC=0.7904
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.2048 | F1=0.5985 | AUROC=0.6481 | AUPRC=0.6417
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.3796 | F1=0.6774 | AUROC=0.7529 | AUPRC=0.7263
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 297.
[Test] train3__val_center_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.3559 | F1=0.5481 | AUROC=0.7604 | AUPRC=0.5987
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.3230 | F1=0.6479 | AUROC=0.7429 | AUPRC=0.7564
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.1793 | F1=0.5840 | AUROC=0.6222 | AUPRC=0.6270
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.2775 | F1=0.6228 | AUROC=0.7060 | AUPRC=0.6907
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4693 | val_loss=0.2605 | val_mcc=0.6634 | val_f1=0.7301 | val_auroc=0.9379

[Epoch 02] train_loss=0.3676 | val_loss=0.2510 | val_mcc=0.6818 | val_f1=0.7443 | val_auroc=0.9467

[Epoch 03] train_loss=0.3464 | val_loss=0.2724 | val_mcc=0.6712 | val_f1=0.7339 | val_auroc=0.9478

[Epoch 04] train_loss=0.3375 | val_loss=0.2675 | val_mcc=0.6811 | val_f1=0.7416 | val_auroc=0.9498

[Epoch 05] train_loss=0.3274 | val_loss=0.2479 | val_mcc=0.6886 | val_f1=0.7500 | val_auroc=0.9468

[Epoch 06] train_loss=0.3194 | val_loss=0.2474 | val_mcc=0.6971 | val_f1=0.7565 | val_auroc=0.9497

[Epoch 07] train_loss=0.3105 | val_loss=0.2783 | val_mcc=0.6703 | val_f1=0.7326 | val_auroc=0.9468

[Epoch 08] train_loss=0.3052 | val_loss=0.2602 | val_mcc=0.6992 | val_f1=0.7569 | val_auroc=0.9496

[Epoch 09] train_loss=0.2949 | val_loss=0.2428 | val_mcc=0.7060 | val_f1=0.7639 | val_auroc=0.9477

[Epoch 10] train_loss=0.2898 | val_loss=0.2609 | val_mcc=0.6992 | val_f1=0.7572 | val_auroc=0.9479

[Epoch 11] train_loss=0.2830 | val_loss=0.2580 | val_mcc=0.7006 | val_f1=0.7591 | val_auroc=0.9459

[Epoch 12] train_loss=0.2760 | val_loss=0.2697 | val_mcc=0.6911 | val_f1=0.7509 | val_auroc=0.9439

[Epoch 13] train_loss=0.2687 | val_loss=0.2740 | val_mcc=0.6895 | val_f1=0.7500 | val_auroc=0.9416

[Epoch 14] train_loss=0.2610 | val_loss=0.2842 | val_mcc=0.6911 | val_f1=0.7501 | val_auroc=0.9417

[Epoch 15] train_loss=0.2539 | val_loss=0.2802 | val_mcc=0.6951 | val_f1=0.7539 | val_auroc=0.9419
[EarlyStop] epoch=15 | best_val_mcc=0.7060
[Test] train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.7009 | F1=0.7845 | AUROC=0.9322 | AUPRC=0.8480
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8063 | F1=0.8899 | AUROC=0.9687 | AUPRC=0.9658
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3239 | F1=0.6691 | AUROC=0.7103 | AUPRC=0.6954
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4662 | F1=0.7365 | AUROC=0.8355 | AUPRC=0.8026
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 187.
[Test] train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7354 | F1=0.8098 | AUROC=0.9545 | AUPRC=0.8969
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8536 | F1=0.9228 | AUROC=0.9812 | AUPRC=0.9816
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3699 | F1=0.7064 | AUROC=0.7424 | AUPRC=0.7236
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5135 | F1=0.7565 | AUROC=0.8734 | AUPRC=0.8445
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 160.
[Test] train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7001 | F1=0.7850 | AUROC=0.9394 | AUPRC=0.8599
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8132 | F1=0.9027 | AUROC=0.9678 | AUPRC=0.9688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3497 | F1=0.6934 | AUROC=0.7210 | AUPRC=0.6919
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4727 | F1=0.7395 | AUROC=0.8420 | AUPRC=0.8057
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.6972 | val_loss=0.7037 | val_mcc=0.1143 | val_f1=0.3426 | val_auroc=0.6089

[Epoch 02] train_loss=0.6614 | val_loss=0.6578 | val_mcc=0.1350 | val_f1=0.3482 | val_auroc=0.6290

[Epoch 03] train_loss=0.6432 | val_loss=0.6656 | val_mcc=0.1450 | val_f1=0.3553 | val_auroc=0.6333

[Epoch 04] train_loss=0.6205 | val_loss=0.6887 | val_mcc=0.1591 | val_f1=0.3657 | val_auroc=0.6397

[Epoch 05] train_loss=0.6012 | val_loss=0.6288 | val_mcc=0.1554 | val_f1=0.3558 | val_auroc=0.6392

[Epoch 06] train_loss=0.5822 | val_loss=0.7029 | val_mcc=0.1614 | val_f1=0.3666 | val_auroc=0.6383

[Epoch 07] train_loss=0.5621 | val_loss=0.7150 | val_mcc=0.1575 | val_f1=0.3636 | val_auroc=0.6353

[Epoch 08] train_loss=0.5399 | val_loss=0.6704 | val_mcc=0.1561 | val_f1=0.3585 | val_auroc=0.6398

[Epoch 09] train_loss=0.5219 | val_loss=0.7240 | val_mcc=0.1460 | val_f1=0.3555 | val_auroc=0.6293

[Epoch 10] train_loss=0.5038 | val_loss=0.7776 | val_mcc=0.1497 | val_f1=0.3600 | val_auroc=0.6334

[Epoch 11] train_loss=0.4674 | val_loss=0.7875 | val_mcc=0.1512 | val_f1=0.3609 | val_auroc=0.6376

[Epoch 12] train_loss=0.4511 | val_loss=0.7642 | val_mcc=0.1586 | val_f1=0.3634 | val_auroc=0.6376
[EarlyStop] epoch=12 | best_val_mcc=0.1614
[Test] train3__val_center_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.1526 | F1=0.4368 | AUROC=0.6202 | AUPRC=0.3753
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.1482 | F1=0.5913 | AUROC=0.6329 | AUPRC=0.6264
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.0328 | F1=0.5376 | AUROC=0.5348 | AUPRC=0.5401
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.0942 | F1=0.5577 | AUROC=0.5660 | AUPRC=0.5083
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 62.
[Test] train3__val_center_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.1410 | F1=0.4227 | AUROC=0.6072 | AUPRC=0.3631
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.1349 | F1=0.5569 | AUROC=0.5812 | AUPRC=0.5525
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.0116 | F1=0.5242 | AUROC=0.5096 | AUPRC=0.5048
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.0310 | F1=0.5119 | AUROC=0.5287 | AUPRC=0.4765
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 63.
[Test] train3__val_center_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.1290 | F1=0.4179 | AUROC=0.6021 | AUPRC=0.3530
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.1350 | F1=0.5607 | AUROC=0.6028 | AUPRC=0.6008
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.0654 | F1=0.5395 | AUROC=0.5303 | AUPRC=0.5246
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.0867 | F1=0.5331 | AUROC=0.5372 | AUPRC=0.4806
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.5038 | val_loss=0.3137 | val_mcc=0.6533 | val_f1=0.7189 | val_auroc=0.9366

[Epoch 02] train_loss=0.3550 | val_loss=0.2903 | val_mcc=0.6691 | val_f1=0.7314 | val_auroc=0.9434

[Epoch 03] train_loss=0.3297 | val_loss=0.2894 | val_mcc=0.6724 | val_f1=0.7343 | val_auroc=0.9426

[Epoch 04] train_loss=0.3063 | val_loss=0.2856 | val_mcc=0.6758 | val_f1=0.7374 | val_auroc=0.9423

[Epoch 05] train_loss=0.2876 | val_loss=0.2997 | val_mcc=0.6631 | val_f1=0.7266 | val_auroc=0.9419

[Epoch 06] train_loss=0.2740 | val_loss=0.2873 | val_mcc=0.6692 | val_f1=0.7333 | val_auroc=0.9399

[Epoch 07] train_loss=0.2557 | val_loss=0.3162 | val_mcc=0.6538 | val_f1=0.7195 | val_auroc=0.9373

[Epoch 08] train_loss=0.2404 | val_loss=0.3208 | val_mcc=0.6549 | val_f1=0.7205 | val_auroc=0.9361

[Epoch 09] train_loss=0.2162 | val_loss=0.3073 | val_mcc=0.6572 | val_f1=0.7238 | val_auroc=0.9355

[Epoch 10] train_loss=0.2054 | val_loss=0.3218 | val_mcc=0.6555 | val_f1=0.7218 | val_auroc=0.9349
[EarlyStop] epoch=10 | best_val_mcc=0.6758
[Test] train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.6805 | F1=0.7711 | AUROC=0.9274 | AUPRC=0.8340
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7867 | F1=0.8915 | AUROC=0.9599 | AUPRC=0.9588
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.2976 | F1=0.6780 | AUROC=0.6969 | AUPRC=0.6671
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4582 | F1=0.7335 | AUROC=0.7964 | AUPRC=0.7260
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 146.
[Test] train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7064 | F1=0.7894 | AUROC=0.9419 | AUPRC=0.8689
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8311 | F1=0.9107 | AUROC=0.9756 | AUPRC=0.9748
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3441 | F1=0.6919 | AUROC=0.7216 | AUPRC=0.7044
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4764 | F1=0.7411 | AUROC=0.8494 | AUPRC=0.8106
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 135.
[Test] train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6863 | F1=0.7753 | AUROC=0.9334 | AUPRC=0.8519
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7961 | F1=0.8938 | AUROC=0.9654 | AUPRC=0.9647
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3189 | F1=0.6815 | AUROC=0.7075 | AUPRC=0.6827
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4473 | F1=0.7292 | AUROC=0.8187 | AUPRC=0.7568
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4536 | val_loss=0.3554 | val_mcc=0.5929 | val_f1=0.6746 | val_auroc=0.8956

[Epoch 02] train_loss=0.4009 | val_loss=0.3335 | val_mcc=0.6223 | val_f1=0.6973 | val_auroc=0.9016

[Epoch 03] train_loss=0.3786 | val_loss=0.3501 | val_mcc=0.6172 | val_f1=0.6936 | val_auroc=0.9017

[Epoch 04] train_loss=0.3641 | val_loss=0.3531 | val_mcc=0.6070 | val_f1=0.6854 | val_auroc=0.9030

[Epoch 05] train_loss=0.3479 | val_loss=0.3475 | val_mcc=0.6133 | val_f1=0.6904 | val_auroc=0.9053

[Epoch 06] train_loss=0.3317 | val_loss=0.3625 | val_mcc=0.6029 | val_f1=0.6820 | val_auroc=0.9020

[Epoch 07] train_loss=0.3091 | val_loss=0.3470 | val_mcc=0.6109 | val_f1=0.6886 | val_auroc=0.9050

[Epoch 08] train_loss=0.2979 | val_loss=0.3377 | val_mcc=0.6151 | val_f1=0.6920 | val_auroc=0.9055
[EarlyStop] epoch=8 | best_val_mcc=0.6223
[Test] train3__val_center_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6767 | F1=0.7642 | AUROC=0.9146 | AUPRC=0.8365
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6334 | F1=0.8106 | AUROC=0.8922 | AUPRC=0.8959
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4377 | F1=0.7025 | AUROC=0.7745 | AUPRC=0.7700
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6213 | F1=0.7890 | AUROC=0.8816 | AUPRC=0.8733
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 256.
[Test] train3__val_center_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6668 | F1=0.7602 | AUROC=0.9151 | AUPRC=0.8350
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6245 | F1=0.8114 | AUROC=0.8934 | AUPRC=0.8883
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4392 | F1=0.7119 | AUROC=0.7827 | AUPRC=0.7770
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6119 | F1=0.7909 | AUROC=0.8828 | AUPRC=0.8673
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 137.
[Test] train3__val_center_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6655 | F1=0.7593 | AUROC=0.9128 | AUPRC=0.8260
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6102 | F1=0.8034 | AUROC=0.8884 | AUPRC=0.8915
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4449 | F1=0.7180 | AUROC=0.7779 | AUPRC=0.7748
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.6091 | F1=0.7891 | AUROC=0.8798 | AUPRC=0.8700
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.3694 | val_loss=0.2220 | val_mcc=0.7490 | val_f1=0.7980 | val_auroc=0.9608

[Epoch 02] train_loss=0.2680 | val_loss=0.2109 | val_mcc=0.7631 | val_f1=0.8086 | val_auroc=0.9659

[Epoch 03] train_loss=0.2429 | val_loss=0.1951 | val_mcc=0.7731 | val_f1=0.8173 | val_auroc=0.9670

[Epoch 04] train_loss=0.2296 | val_loss=0.1999 | val_mcc=0.7672 | val_f1=0.8122 | val_auroc=0.9674

[Epoch 05] train_loss=0.2191 | val_loss=0.1960 | val_mcc=0.7679 | val_f1=0.8130 | val_auroc=0.9666

[Epoch 06] train_loss=0.2086 | val_loss=0.2084 | val_mcc=0.7733 | val_f1=0.8167 | val_auroc=0.9672

[Epoch 07] train_loss=0.1953 | val_loss=0.1981 | val_mcc=0.7711 | val_f1=0.8156 | val_auroc=0.9654

[Epoch 08] train_loss=0.1849 | val_loss=0.2129 | val_mcc=0.7591 | val_f1=0.8056 | val_auroc=0.9656

[Epoch 09] train_loss=0.1742 | val_loss=0.2319 | val_mcc=0.7481 | val_f1=0.7961 | val_auroc=0.9653

[Epoch 10] train_loss=0.1635 | val_loss=0.2147 | val_mcc=0.7607 | val_f1=0.8072 | val_auroc=0.9640

[Epoch 11] train_loss=0.1434 | val_loss=0.2208 | val_mcc=0.7639 | val_f1=0.8095 | val_auroc=0.9646

[Epoch 12] train_loss=0.1328 | val_loss=0.2317 | val_mcc=0.7550 | val_f1=0.8022 | val_auroc=0.9640
[EarlyStop] epoch=12 | best_val_mcc=0.7733
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7756 | F1=0.8383 | AUROC=0.9637 | AUPRC=0.9226
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8237 | F1=0.9101 | AUROC=0.9745 | AUPRC=0.9749
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4256 | F1=0.7311 | AUROC=0.7921 | AUPRC=0.7813
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5872 | F1=0.7896 | AUROC=0.9075 | AUPRC=0.8918
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 180.
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7972 | F1=0.8537 | AUROC=0.9692 | AUPRC=0.9313
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8668 | F1=0.9312 | AUROC=0.9839 | AUPRC=0.9840
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4488 | F1=0.7404 | AUROC=0.7891 | AUPRC=0.7794
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5959 | F1=0.7935 | AUROC=0.9156 | AUPRC=0.9007
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 142.
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7754 | F1=0.8382 | AUROC=0.9641 | AUPRC=0.9246
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8356 | F1=0.9150 | AUROC=0.9771 | AUPRC=0.9770
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4291 | F1=0.7289 | AUROC=0.7858 | AUPRC=0.7704
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5795 | F1=0.7861 | AUROC=0.9070 | AUPRC=0.8985
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4897 | val_loss=0.3884 | val_mcc=0.5454 | val_f1=0.6372 | val_auroc=0.8706

[Epoch 02] train_loss=0.4363 | val_loss=0.3716 | val_mcc=0.5597 | val_f1=0.6481 | val_auroc=0.8836

[Epoch 03] train_loss=0.4171 | val_loss=0.3913 | val_mcc=0.5498 | val_f1=0.6408 | val_auroc=0.8824

[Epoch 04] train_loss=0.4018 | val_loss=0.3726 | val_mcc=0.5732 | val_f1=0.6590 | val_auroc=0.8910

[Epoch 05] train_loss=0.3840 | val_loss=0.3672 | val_mcc=0.5724 | val_f1=0.6585 | val_auroc=0.8927

[Epoch 06] train_loss=0.3687 | val_loss=0.3997 | val_mcc=0.5382 | val_f1=0.6312 | val_auroc=0.8862

[Epoch 07] train_loss=0.3543 | val_loss=0.3564 | val_mcc=0.5755 | val_f1=0.6605 | val_auroc=0.8928

[Epoch 08] train_loss=0.3413 | val_loss=0.3946 | val_mcc=0.5601 | val_f1=0.6488 | val_auroc=0.8898

[Epoch 09] train_loss=0.3271 | val_loss=0.4012 | val_mcc=0.5501 | val_f1=0.6408 | val_auroc=0.8869

[Epoch 10] train_loss=0.3154 | val_loss=0.3856 | val_mcc=0.5507 | val_f1=0.6416 | val_auroc=0.8855

[Epoch 11] train_loss=0.3006 | val_loss=0.4175 | val_mcc=0.5487 | val_f1=0.6396 | val_auroc=0.8866

[Epoch 12] train_loss=0.2682 | val_loss=0.4262 | val_mcc=0.5437 | val_f1=0.6357 | val_auroc=0.8860

[Epoch 13] train_loss=0.2564 | val_loss=0.4201 | val_mcc=0.5500 | val_f1=0.6410 | val_auroc=0.8857
[EarlyStop] epoch=13 | best_val_mcc=0.5755
[Test] train3__val_center_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6576 | F1=0.7522 | AUROC=0.9091 | AUPRC=0.8304
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6493 | F1=0.8138 | AUROC=0.8969 | AUPRC=0.9037
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4331 | F1=0.7092 | AUROC=0.7739 | AUPRC=0.7714
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5773 | F1=0.7656 | AUROC=0.8867 | AUPRC=0.8741
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 258.
[Test] train3__val_center_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6386 | F1=0.7405 | AUROC=0.9029 | AUPRC=0.8232
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6244 | F1=0.8092 | AUROC=0.8910 | AUPRC=0.8961
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4254 | F1=0.7122 | AUROC=0.7679 | AUPRC=0.7545
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6007 | F1=0.7840 | AUROC=0.8806 | AUPRC=0.8705
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 98.
[Test] train3__val_center_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6277 | F1=0.7336 | AUROC=0.8998 | AUPRC=0.8150
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5961 | F1=0.7930 | AUROC=0.8799 | AUPRC=0.8865
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4270 | F1=0.7154 | AUROC=0.7700 | AUPRC=0.7691
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.6028 | F1=0.7868 | AUROC=0.8747 | AUPRC=0.8616
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.3782 | val_loss=0.2050 | val_mcc=0.7540 | val_f1=0.8011 | val_auroc=0.9617

[Epoch 02] train_loss=0.2758 | val_loss=0.1948 | val_mcc=0.7696 | val_f1=0.8146 | val_auroc=0.9669

[Epoch 03] train_loss=0.2533 | val_loss=0.1962 | val_mcc=0.7645 | val_f1=0.8105 | val_auroc=0.9667

[Epoch 04] train_loss=0.2384 | val_loss=0.1863 | val_mcc=0.7737 | val_f1=0.8178 | val_auroc=0.9686

[Epoch 05] train_loss=0.2258 | val_loss=0.1946 | val_mcc=0.7680 | val_f1=0.8131 | val_auroc=0.9686

[Epoch 06] train_loss=0.2124 | val_loss=0.2108 | val_mcc=0.7603 | val_f1=0.8064 | val_auroc=0.9665

[Epoch 07] train_loss=0.2025 | val_loss=0.2076 | val_mcc=0.7562 | val_f1=0.8032 | val_auroc=0.9674

[Epoch 08] train_loss=0.1933 | val_loss=0.2037 | val_mcc=0.7625 | val_f1=0.8085 | val_auroc=0.9685

[Epoch 09] train_loss=0.1734 | val_loss=0.2011 | val_mcc=0.7666 | val_f1=0.8119 | val_auroc=0.9680

[Epoch 10] train_loss=0.1661 | val_loss=0.2055 | val_mcc=0.7705 | val_f1=0.8151 | val_auroc=0.9677
[EarlyStop] epoch=10 | best_val_mcc=0.7737
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7854 | F1=0.8445 | AUROC=0.9649 | AUPRC=0.9213
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8197 | F1=0.8981 | AUROC=0.9769 | AUPRC=0.9772
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4320 | F1=0.7215 | AUROC=0.7834 | AUPRC=0.7751
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5922 | F1=0.7919 | AUROC=0.8996 | AUPRC=0.8860
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 172.
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7912 | F1=0.8494 | AUROC=0.9685 | AUPRC=0.9303
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8580 | F1=0.9271 | AUROC=0.9833 | AUPRC=0.9839
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4460 | F1=0.7393 | AUROC=0.7891 | AUPRC=0.7732
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5699 | F1=0.7814 | AUROC=0.9078 | AUPRC=0.8914
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 216.
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7803 | F1=0.8416 | AUROC=0.9628 | AUPRC=0.9202
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8529 | F1=0.9235 | AUROC=0.9763 | AUPRC=0.9776
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4266 | F1=0.7308 | AUROC=0.7788 | AUPRC=0.7692
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5844 | F1=0.7880 | AUROC=0.9003 | AUPRC=0.8804
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4691 | val_loss=0.3846 | val_mcc=0.5596 | val_f1=0.6485 | val_auroc=0.8819

[Epoch 02] train_loss=0.4085 | val_loss=0.3681 | val_mcc=0.5780 | val_f1=0.6629 | val_auroc=0.8902

[Epoch 03] train_loss=0.3836 | val_loss=0.3410 | val_mcc=0.6007 | val_f1=0.6802 | val_auroc=0.8950

[Epoch 04] train_loss=0.3663 | val_loss=0.3768 | val_mcc=0.5709 | val_f1=0.6572 | val_auroc=0.8911

[Epoch 05] train_loss=0.3508 | val_loss=0.3584 | val_mcc=0.5835 | val_f1=0.6672 | val_auroc=0.8961

[Epoch 06] train_loss=0.3329 | val_loss=0.3817 | val_mcc=0.5834 | val_f1=0.6667 | val_auroc=0.8966

[Epoch 07] train_loss=0.3153 | val_loss=0.3850 | val_mcc=0.5827 | val_f1=0.6661 | val_auroc=0.8950

[Epoch 08] train_loss=0.2908 | val_loss=0.3763 | val_mcc=0.5835 | val_f1=0.6671 | val_auroc=0.8964

[Epoch 09] train_loss=0.2785 | val_loss=0.3986 | val_mcc=0.5779 | val_f1=0.6621 | val_auroc=0.8933
[EarlyStop] epoch=9 | best_val_mcc=0.6007
[Test] train3__val_center_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6337 | F1=0.7304 | AUROC=0.8979 | AUPRC=0.8093
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6342 | F1=0.8012 | AUROC=0.8883 | AUPRC=0.8815
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4342 | F1=0.7028 | AUROC=0.7734 | AUPRC=0.7589
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5630 | F1=0.7454 | AUROC=0.8483 | AUPRC=0.8396
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 164.
[Test] train3__val_center_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6201 | F1=0.7251 | AUROC=0.8917 | AUPRC=0.7935
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6672 | F1=0.8297 | AUROC=0.8906 | AUPRC=0.8760
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4210 | F1=0.7040 | AUROC=0.7744 | AUPRC=0.7647
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5731 | F1=0.7613 | AUROC=0.8539 | AUPRC=0.8251
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 142.
[Test] train3__val_center_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6165 | F1=0.7238 | AUROC=0.8958 | AUPRC=0.8020
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6217 | F1=0.8064 | AUROC=0.8867 | AUPRC=0.8761
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4614 | F1=0.7315 | AUROC=0.7747 | AUPRC=0.7736
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5433 | F1=0.7487 | AUROC=0.8525 | AUPRC=0.8376
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.3695 | val_loss=0.2142 | val_mcc=0.7577 | val_f1=0.8050 | val_auroc=0.9639

[Epoch 02] train_loss=0.2589 | val_loss=0.2079 | val_mcc=0.7674 | val_f1=0.8118 | val_auroc=0.9683

[Epoch 03] train_loss=0.2340 | val_loss=0.1943 | val_mcc=0.7757 | val_f1=0.8190 | val_auroc=0.9695

[Epoch 04] train_loss=0.2207 | val_loss=0.1838 | val_mcc=0.7863 | val_f1=0.8279 | val_auroc=0.9680

[Epoch 05] train_loss=0.2061 | val_loss=0.1916 | val_mcc=0.7775 | val_f1=0.8206 | val_auroc=0.9698

[Epoch 06] train_loss=0.1936 | val_loss=0.1892 | val_mcc=0.7749 | val_f1=0.8188 | val_auroc=0.9667

[Epoch 07] train_loss=0.1829 | val_loss=0.2149 | val_mcc=0.7653 | val_f1=0.8103 | val_auroc=0.9666

[Epoch 08] train_loss=0.1732 | val_loss=0.2199 | val_mcc=0.7574 | val_f1=0.8037 | val_auroc=0.9668

[Epoch 09] train_loss=0.1520 | val_loss=0.2046 | val_mcc=0.7718 | val_f1=0.8161 | val_auroc=0.9674

[Epoch 10] train_loss=0.1434 | val_loss=0.2215 | val_mcc=0.7581 | val_f1=0.8047 | val_auroc=0.9661
[EarlyStop] epoch=10 | best_val_mcc=0.7863
[Test] train3__val_center_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7898 | F1=0.8479 | AUROC=0.9634 | AUPRC=0.9186
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8365 | F1=0.9139 | AUROC=0.9761 | AUPRC=0.9746
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4640 | F1=0.7391 | AUROC=0.7927 | AUPRC=0.7831
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5833 | F1=0.7877 | AUROC=0.8890 | AUPRC=0.8673
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 196.
[Test] train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7924 | F1=0.8503 | AUROC=0.9677 | AUPRC=0.9292
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8563 | F1=0.9244 | AUROC=0.9852 | AUPRC=0.9850
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4521 | F1=0.7421 | AUROC=0.7872 | AUPRC=0.7568
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5561 | F1=0.7756 | AUROC=0.9024 | AUPRC=0.8778
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 192.
[Test] train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7861 | F1=0.8458 | AUROC=0.9638 | AUPRC=0.9200
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8496 | F1=0.9226 | AUROC=0.9762 | AUPRC=0.9750
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4491 | F1=0.7387 | AUROC=0.7910 | AUPRC=0.7779
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5628 | F1=0.7786 | AUROC=0.8904 | AUPRC=0.8709
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4776 | val_loss=0.3219 | val_mcc=0.6326 | val_f1=0.6969 | val_auroc=0.8864

[Epoch 02] train_loss=0.4156 | val_loss=0.3098 | val_mcc=0.6393 | val_f1=0.7069 | val_auroc=0.9025

[Epoch 03] train_loss=0.3793 | val_loss=0.3037 | val_mcc=0.6341 | val_f1=0.7056 | val_auroc=0.9098

[Epoch 04] train_loss=0.3501 | val_loss=0.3273 | val_mcc=0.6253 | val_f1=0.7000 | val_auroc=0.9115

[Epoch 05] train_loss=0.3148 | val_loss=0.3321 | val_mcc=0.6147 | val_f1=0.6916 | val_auroc=0.9133

[Epoch 06] train_loss=0.2737 | val_loss=0.3609 | val_mcc=0.5954 | val_f1=0.6761 | val_auroc=0.9108

[Epoch 07] train_loss=0.2296 | val_loss=0.3496 | val_mcc=0.6055 | val_f1=0.6844 | val_auroc=0.9082

[Epoch 08] train_loss=0.2013 | val_loss=0.3730 | val_mcc=0.5849 | val_f1=0.6682 | val_auroc=0.9039
[EarlyStop] epoch=8 | best_val_mcc=0.6393
[Test] train3__val_center_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6859 | F1=0.7663 | AUROC=0.9112 | AUPRC=0.8455
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6598 | F1=0.8153 | AUROC=0.9035 | AUPRC=0.9081
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4786 | F1=0.7139 | AUROC=0.7802 | AUPRC=0.7793
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6147 | F1=0.7748 | AUROC=0.8826 | AUPRC=0.8780
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 259.
[Test] train3__val_center_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6614 | F1=0.7549 | AUROC=0.9140 | AUPRC=0.8378
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6447 | F1=0.8170 | AUROC=0.9037 | AUPRC=0.9059
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4359 | F1=0.7139 | AUROC=0.7762 | AUPRC=0.7645
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6080 | F1=0.7856 | AUROC=0.8784 | AUPRC=0.8688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 281.
[Test] train3__val_center_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6627 | F1=0.7569 | AUROC=0.9178 | AUPRC=0.8463
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6416 | F1=0.8169 | AUROC=0.9063 | AUPRC=0.9094
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4345 | F1=0.7189 | AUROC=0.7803 | AUPRC=0.7761
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5890 | F1=0.7758 | AUROC=0.8809 | AUPRC=0.8679
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.3716 | val_loss=0.1856 | val_mcc=0.7739 | val_f1=0.8177 | val_auroc=0.9668

[Epoch 02] train_loss=0.2605 | val_loss=0.1766 | val_mcc=0.7844 | val_f1=0.8264 | val_auroc=0.9702

[Epoch 03] train_loss=0.2361 | val_loss=0.1899 | val_mcc=0.7749 | val_f1=0.8182 | val_auroc=0.9697

[Epoch 04] train_loss=0.2145 | val_loss=0.1755 | val_mcc=0.7902 | val_f1=0.8311 | val_auroc=0.9709

[Epoch 05] train_loss=0.1904 | val_loss=0.1802 | val_mcc=0.7871 | val_f1=0.8286 | val_auroc=0.9697

[Epoch 06] train_loss=0.1605 | val_loss=0.2062 | val_mcc=0.7755 | val_f1=0.8186 | val_auroc=0.9677

[Epoch 07] train_loss=0.1346 | val_loss=0.2181 | val_mcc=0.7637 | val_f1=0.8092 | val_auroc=0.9666

[Epoch 08] train_loss=0.1070 | val_loss=0.2265 | val_mcc=0.7684 | val_f1=0.8134 | val_auroc=0.9648

[Epoch 09] train_loss=0.0780 | val_loss=0.2491 | val_mcc=0.7573 | val_f1=0.8041 | val_auroc=0.9643

[Epoch 10] train_loss=0.0680 | val_loss=0.2679 | val_mcc=0.7504 | val_f1=0.7983 | val_auroc=0.9629
[EarlyStop] epoch=10 | best_val_mcc=0.7902
[Test] train3__val_center_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7926 | F1=0.8502 | AUROC=0.9660 | AUPRC=0.9282
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8402 | F1=0.9148 | AUROC=0.9803 | AUPRC=0.9803
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4517 | F1=0.7365 | AUROC=0.7916 | AUPRC=0.7821
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6243 | F1=0.8071 | AUROC=0.9059 | AUPRC=0.8936
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 218.
[Test] train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7960 | F1=0.8529 | AUROC=0.9705 | AUPRC=0.9357
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8648 | F1=0.9290 | AUROC=0.9840 | AUPRC=0.9849
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4507 | F1=0.7416 | AUROC=0.7886 | AUPRC=0.7766
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5751 | F1=0.7841 | AUROC=0.9089 | AUPRC=0.8902
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 185.
[Test] train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7906 | F1=0.8490 | AUROC=0.9651 | AUPRC=0.9261
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8415 | F1=0.9176 | AUROC=0.9759 | AUPRC=0.9765
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4420 | F1=0.7361 | AUROC=0.7870 | AUPRC=0.7773
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5780 | F1=0.7855 | AUROC=0.9027 | AUPRC=0.8900
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4638 | val_loss=0.3506 | val_mcc=0.5962 | val_f1=0.6772 | val_auroc=0.8962

[Epoch 02] train_loss=0.3880 | val_loss=0.3878 | val_mcc=0.5821 | val_f1=0.6648 | val_auroc=0.8983

[Epoch 03] train_loss=0.3475 | val_loss=0.3694 | val_mcc=0.5979 | val_f1=0.6781 | val_auroc=0.9007

[Epoch 04] train_loss=0.3030 | val_loss=0.3611 | val_mcc=0.6031 | val_f1=0.6826 | val_auroc=0.8968

[Epoch 05] train_loss=0.2593 | val_loss=0.3919 | val_mcc=0.5879 | val_f1=0.6702 | val_auroc=0.8933

[Epoch 06] train_loss=0.2068 | val_loss=0.4240 | val_mcc=0.5710 | val_f1=0.6572 | val_auroc=0.8871

[Epoch 07] train_loss=0.1564 | val_loss=0.4447 | val_mcc=0.5613 | val_f1=0.6499 | val_auroc=0.8852

[Epoch 08] train_loss=0.1236 | val_loss=0.5188 | val_mcc=0.5463 | val_f1=0.6372 | val_auroc=0.8860

[Epoch 09] train_loss=0.0756 | val_loss=0.5264 | val_mcc=0.5592 | val_f1=0.6477 | val_auroc=0.8849

[Epoch 10] train_loss=0.0592 | val_loss=0.5459 | val_mcc=0.5610 | val_f1=0.6494 | val_auroc=0.8830
[EarlyStop] epoch=10 | best_val_mcc=0.6031
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6491 | F1=0.7469 | AUROC=0.9032 | AUPRC=0.8238
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6102 | F1=0.8017 | AUROC=0.8935 | AUPRC=0.9049
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3916 | F1=0.6833 | AUROC=0.7586 | AUPRC=0.7562
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6069 | F1=0.7857 | AUROC=0.8768 | AUPRC=0.8687
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4622 | val_loss=0.3546 | val_mcc=0.6094 | val_f1=0.6873 | val_auroc=0.8934

[Epoch 02] train_loss=0.3949 | val_loss=0.3398 | val_mcc=0.6154 | val_f1=0.6921 | val_auroc=0.9008

[Epoch 03] train_loss=0.3636 | val_loss=0.3648 | val_mcc=0.6030 | val_f1=0.6824 | val_auroc=0.8964

[Epoch 04] train_loss=0.3251 | val_loss=0.3991 | val_mcc=0.5909 | val_f1=0.6720 | val_auroc=0.8955

[Epoch 05] train_loss=0.2809 | val_loss=0.4296 | val_mcc=0.5680 | val_f1=0.6541 | val_auroc=0.8862

[Epoch 06] train_loss=0.2319 | val_loss=0.4505 | val_mcc=0.5737 | val_f1=0.6589 | val_auroc=0.8875

[Epoch 07] train_loss=0.1615 | val_loss=0.5466 | val_mcc=0.5451 | val_f1=0.6359 | val_auroc=0.8767

[Epoch 08] train_loss=0.1319 | val_loss=0.5328 | val_mcc=0.5626 | val_f1=0.6507 | val_auroc=0.8756
[EarlyStop] epoch=8 | best_val_mcc=0.6154
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6634 | F1=0.7560 | AUROC=0.9093 | AUPRC=0.8330
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6017 | F1=0.7965 | AUROC=0.8892 | AUPRC=0.8982
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4431 | F1=0.7080 | AUROC=0.7735 | AUPRC=0.7720
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6160 | F1=0.7888 | AUROC=0.8794 | AUPRC=0.8710
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4613 | val_loss=0.3686 | val_mcc=0.5939 | val_f1=0.6753 | val_auroc=0.8961

[Epoch 02] train_loss=0.3875 | val_loss=0.3271 | val_mcc=0.6190 | val_f1=0.6942 | val_auroc=0.8987

[Epoch 03] train_loss=0.3500 | val_loss=0.3654 | val_mcc=0.5971 | val_f1=0.6777 | val_auroc=0.8991

[Epoch 04] train_loss=0.3053 | val_loss=0.3822 | val_mcc=0.5837 | val_f1=0.6673 | val_auroc=0.8913

[Epoch 05] train_loss=0.2550 | val_loss=0.3796 | val_mcc=0.5887 | val_f1=0.6711 | val_auroc=0.8920

[Epoch 06] train_loss=0.2039 | val_loss=0.4289 | val_mcc=0.5853 | val_f1=0.6684 | val_auroc=0.8862

[Epoch 07] train_loss=0.1352 | val_loss=0.5082 | val_mcc=0.5622 | val_f1=0.6503 | val_auroc=0.8858

[Epoch 08] train_loss=0.1070 | val_loss=0.5862 | val_mcc=0.5574 | val_f1=0.6462 | val_auroc=0.8838
[EarlyStop] epoch=8 | best_val_mcc=0.6190
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6658 | F1=0.7551 | AUROC=0.9084 | AUPRC=0.8275
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6001 | F1=0.7899 | AUROC=0.8834 | AUPRC=0.8942
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4359 | F1=0.7029 | AUROC=0.7748 | AUPRC=0.7749
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5952 | F1=0.7750 | AUROC=0.8724 | AUPRC=0.8622
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4720 | val_loss=0.3554 | val_mcc=0.5951 | val_f1=0.6762 | val_auroc=0.8921

[Epoch 02] train_loss=0.3852 | val_loss=0.3533 | val_mcc=0.6042 | val_f1=0.6834 | val_auroc=0.8965

[Epoch 03] train_loss=0.3404 | val_loss=0.3516 | val_mcc=0.6015 | val_f1=0.6813 | val_auroc=0.8951

[Epoch 04] train_loss=0.2920 | val_loss=0.3859 | val_mcc=0.5697 | val_f1=0.6561 | val_auroc=0.8878

[Epoch 05] train_loss=0.2369 | val_loss=0.4195 | val_mcc=0.5701 | val_f1=0.6562 | val_auroc=0.8872

[Epoch 06] train_loss=0.1797 | val_loss=0.4596 | val_mcc=0.5505 | val_f1=0.6411 | val_auroc=0.8823

[Epoch 07] train_loss=0.1169 | val_loss=0.4665 | val_mcc=0.5715 | val_f1=0.6577 | val_auroc=0.8878

[Epoch 08] train_loss=0.0917 | val_loss=0.5370 | val_mcc=0.5399 | val_f1=0.6322 | val_auroc=0.8827
[EarlyStop] epoch=8 | best_val_mcc=0.6042
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6577 | F1=0.7522 | AUROC=0.9070 | AUPRC=0.8271
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5847 | F1=0.7878 | AUROC=0.8800 | AUPRC=0.8863
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4198 | F1=0.7012 | AUROC=0.7685 | AUPRC=0.7705
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6001 | F1=0.7824 | AUROC=0.8723 | AUPRC=0.8628
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 377.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6610 | F1=0.7559 | AUROC=0.9134 | AUPRC=0.8327
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6159 | F1=0.8052 | AUROC=0.8947 | AUPRC=0.8970
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4483 | F1=0.7156 | AUROC=0.7781 | AUPRC=0.7774
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6062 | F1=0.7873 | AUROC=0.8836 | AUPRC=0.8652
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 147.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6585 | F1=0.7539 | AUROC=0.9056 | AUPRC=0.8201
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6048 | F1=0.7965 | AUROC=0.8814 | AUPRC=0.8922
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4329 | F1=0.7132 | AUROC=0.7710 | AUPRC=0.7644
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5919 | F1=0.7810 | AUROC=0.8688 | AUPRC=0.8550
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 48.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6567 | F1=0.7526 | AUROC=0.9057 | AUPRC=0.8240
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6017 | F1=0.7977 | AUROC=0.8745 | AUPRC=0.8745
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4242 | F1=0.7037 | AUROC=0.7738 | AUPRC=0.7803
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.6096 | F1=0.7903 | AUROC=0.8711 | AUPRC=0.8634
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 68.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6597 | F1=0.7541 | AUROC=0.9046 | AUPRC=0.8254
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6216 | F1=0.8092 | AUROC=0.8809 | AUPRC=0.8920
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4406 | F1=0.7133 | AUROC=0.7718 | AUPRC=0.7756
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.3855 | val_loss=0.2132 | val_mcc=0.7467 | val_f1=0.7961 | val_auroc=0.9603

[Epoch 02] train_loss=0.2542 | val_loss=0.2190 | val_mcc=0.7522 | val_f1=0.7996 | val_auroc=0.9653

[Epoch 03] train_loss=0.2140 | val_loss=0.2192 | val_mcc=0.7522 | val_f1=0.7994 | val_auroc=0.9661

[Epoch 04] train_loss=0.1812 | val_loss=0.2121 | val_mcc=0.7567 | val_f1=0.8041 | val_auroc=0.9635

[Epoch 05] train_loss=0.1428 | val_loss=0.2407 | val_mcc=0.7362 | val_f1=0.7871 | val_auroc=0.9606

[Epoch 06] train_loss=0.1124 | val_loss=0.2441 | val_mcc=0.7377 | val_f1=0.7891 | val_auroc=0.9582

[Epoch 07] train_loss=0.0827 | val_loss=0.2709 | val_mcc=0.7364 | val_f1=0.7875 | val_auroc=0.9577

[Epoch 08] train_loss=0.0582 | val_loss=0.3044 | val_mcc=0.7275 | val_f1=0.7803 | val_auroc=0.9562

[Epoch 09] train_loss=0.0378 | val_loss=0.3142 | val_mcc=0.7333 | val_f1=0.7846 | val_auroc=0.9576

[Epoch 10] train_loss=0.0300 | val_loss=0.3152 | val_mcc=0.7359 | val_f1=0.7870 | val_auroc=0.9571
[EarlyStop] epoch=10 | best_val_mcc=0.7567
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7541 | F1=0.8227 | AUROC=0.9553 | AUPRC=0.9081
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7956 | F1=0.8899 | AUROC=0.9731 | AUPRC=0.9738
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4060 | F1=0.7134 | AUROC=0.7715 | AUPRC=0.7663
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5571 | F1=0.7757 | AUROC=0.8907 | AUPRC=0.8777
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3803 | val_loss=0.2346 | val_mcc=0.7292 | val_f1=0.7818 | val_auroc=0.9577

[Epoch 02] train_loss=0.2721 | val_loss=0.2081 | val_mcc=0.7598 | val_f1=0.8063 | val_auroc=0.9663

[Epoch 03] train_loss=0.2355 | val_loss=0.2234 | val_mcc=0.7480 | val_f1=0.7967 | val_auroc=0.9615

[Epoch 04] train_loss=0.2036 | val_loss=0.2624 | val_mcc=0.7193 | val_f1=0.7718 | val_auroc=0.9599

[Epoch 05] train_loss=0.1677 | val_loss=0.2794 | val_mcc=0.7208 | val_f1=0.7734 | val_auroc=0.9569

[Epoch 06] train_loss=0.1329 | val_loss=0.2814 | val_mcc=0.7173 | val_f1=0.7724 | val_auroc=0.9536

[Epoch 07] train_loss=0.0875 | val_loss=0.3197 | val_mcc=0.7118 | val_f1=0.7677 | val_auroc=0.9509

[Epoch 08] train_loss=0.0681 | val_loss=0.3463 | val_mcc=0.7085 | val_f1=0.7651 | val_auroc=0.9485
[EarlyStop] epoch=8 | best_val_mcc=0.7598
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7583 | F1=0.8260 | AUROC=0.9602 | AUPRC=0.9138
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8068 | F1=0.9009 | AUROC=0.9683 | AUPRC=0.9686
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4218 | F1=0.7260 | AUROC=0.7822 | AUPRC=0.7777
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5485 | F1=0.7722 | AUROC=0.8969 | AUPRC=0.8841
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3714 | val_loss=0.2363 | val_mcc=0.7336 | val_f1=0.7850 | val_auroc=0.9599

[Epoch 02] train_loss=0.2600 | val_loss=0.1949 | val_mcc=0.7660 | val_f1=0.8117 | val_auroc=0.9647

[Epoch 03] train_loss=0.2226 | val_loss=0.2306 | val_mcc=0.7379 | val_f1=0.7876 | val_auroc=0.9636

[Epoch 04] train_loss=0.1886 | val_loss=0.2502 | val_mcc=0.7248 | val_f1=0.7768 | val_auroc=0.9603

[Epoch 05] train_loss=0.1505 | val_loss=0.2533 | val_mcc=0.7371 | val_f1=0.7883 | val_auroc=0.9575

[Epoch 06] train_loss=0.1144 | val_loss=0.2659 | val_mcc=0.7271 | val_f1=0.7806 | val_auroc=0.9528

[Epoch 07] train_loss=0.0743 | val_loss=0.2925 | val_mcc=0.7339 | val_f1=0.7859 | val_auroc=0.9539

[Epoch 08] train_loss=0.0540 | val_loss=0.3609 | val_mcc=0.7192 | val_f1=0.7733 | val_auroc=0.9500
[EarlyStop] epoch=8 | best_val_mcc=0.7660
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7795 | F1=0.8404 | AUROC=0.9605 | AUPRC=0.9163
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7865 | F1=0.8859 | AUROC=0.9700 | AUPRC=0.9710
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4498 | F1=0.7292 | AUROC=0.7878 | AUPRC=0.7754
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5978 | F1=0.7945 | AUROC=0.9008 | AUPRC=0.8857
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3787 | val_loss=0.2234 | val_mcc=0.7429 | val_f1=0.7932 | val_auroc=0.9594

[Epoch 02] train_loss=0.2503 | val_loss=0.1945 | val_mcc=0.7645 | val_f1=0.8105 | val_auroc=0.9663

[Epoch 03] train_loss=0.2080 | val_loss=0.2013 | val_mcc=0.7570 | val_f1=0.8045 | val_auroc=0.9647

[Epoch 04] train_loss=0.1714 | val_loss=0.2444 | val_mcc=0.7325 | val_f1=0.7835 | val_auroc=0.9599

[Epoch 05] train_loss=0.1326 | val_loss=0.2424 | val_mcc=0.7334 | val_f1=0.7855 | val_auroc=0.9583

[Epoch 06] train_loss=0.0924 | val_loss=0.2684 | val_mcc=0.7296 | val_f1=0.7822 | val_auroc=0.9569

[Epoch 07] train_loss=0.0577 | val_loss=0.2808 | val_mcc=0.7303 | val_f1=0.7827 | val_auroc=0.9575

[Epoch 08] train_loss=0.0457 | val_loss=0.2959 | val_mcc=0.7285 | val_f1=0.7815 | val_auroc=0.9559
[EarlyStop] epoch=8 | best_val_mcc=0.7645
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7790 | F1=0.8402 | AUROC=0.9607 | AUPRC=0.9136
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8045 | F1=0.8984 | AUROC=0.9683 | AUPRC=0.9697
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4428 | F1=0.7281 | AUROC=0.7820 | AUPRC=0.7673
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6055 | F1=0.7982 | AUROC=0.9010 | AUPRC=0.8857
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 185.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.8027 | F1=0.8576 | AUROC=0.9691 | AUPRC=0.9285
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8553 | F1=0.9255 | AUROC=0.9830 | AUPRC=0.9828
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4428 | F1=0.7355 | AUROC=0.7858 | AUPRC=0.7728
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5958 | F1=0.7932 | AUROC=0.9122 | AUPRC=0.8944
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 168.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7847 | F1=0.8449 | AUROC=0.9633 | AUPRC=0.9204
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8156 | F1=0.9048 | AUROC=0.9739 | AUPRC=0.9750
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4236 | F1=0.7294 | AUROC=0.7841 | AUPRC=0.7711
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5707 | F1=0.7820 | AUROC=0.8955 | AUPRC=0.8795
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 73.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7847 | F1=0.8448 | AUROC=0.9627 | AUPRC=0.9182
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8216 | F1=0.9072 | AUROC=0.9696 | AUPRC=0.9689
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4334 | F1=0.7305 | AUROC=0.7879 | AUPRC=0.7799
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5785 | F1=0.7858 | AUROC=0.8992 | AUPRC=0.8846
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 119.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7778 | F1=0.8399 | AUROC=0.9615 | AUPRC=0.9182
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8102 | F1=0.9013 | AUROC=0.9705 | AUPRC=0.9700
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4992 | val_loss=0.4088 | val_mcc=0.5241 | val_f1=0.6210 | val_auroc=0.8676

[Epoch 02] train_loss=0.4241 | val_loss=0.3863 | val_mcc=0.5539 | val_f1=0.6441 | val_auroc=0.8814

[Epoch 03] train_loss=0.3817 | val_loss=0.4004 | val_mcc=0.5331 | val_f1=0.6279 | val_auroc=0.8769

[Epoch 04] train_loss=0.3369 | val_loss=0.3932 | val_mcc=0.5507 | val_f1=0.6416 | val_auroc=0.8789

[Epoch 05] train_loss=0.2849 | val_loss=0.4074 | val_mcc=0.5402 | val_f1=0.6334 | val_auroc=0.8751

[Epoch 06] train_loss=0.2342 | val_loss=0.4951 | val_mcc=0.5055 | val_f1=0.6055 | val_auroc=0.8671

[Epoch 07] train_loss=0.1697 | val_loss=0.4777 | val_mcc=0.5205 | val_f1=0.6181 | val_auroc=0.8690

[Epoch 08] train_loss=0.1319 | val_loss=0.5097 | val_mcc=0.5210 | val_f1=0.6184 | val_auroc=0.8682
[EarlyStop] epoch=8 | best_val_mcc=0.5539
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6285 | F1=0.7334 | AUROC=0.8987 | AUPRC=0.8198
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5802 | F1=0.7791 | AUROC=0.8692 | AUPRC=0.8827
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3968 | F1=0.6977 | AUROC=0.7522 | AUPRC=0.7459
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5839 | F1=0.7741 | AUROC=0.8639 | AUPRC=0.8585
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4977 | val_loss=0.4196 | val_mcc=0.5370 | val_f1=0.6309 | val_auroc=0.8731

[Epoch 02] train_loss=0.4364 | val_loss=0.4012 | val_mcc=0.5474 | val_f1=0.6391 | val_auroc=0.8767

[Epoch 03] train_loss=0.4024 | val_loss=0.3896 | val_mcc=0.5517 | val_f1=0.6424 | val_auroc=0.8804

[Epoch 04] train_loss=0.3617 | val_loss=0.4732 | val_mcc=0.5091 | val_f1=0.6062 | val_auroc=0.8801

[Epoch 05] train_loss=0.3174 | val_loss=0.4473 | val_mcc=0.5224 | val_f1=0.6194 | val_auroc=0.8686

[Epoch 06] train_loss=0.2646 | val_loss=0.4698 | val_mcc=0.5144 | val_f1=0.6133 | val_auroc=0.8666

[Epoch 07] train_loss=0.2081 | val_loss=0.6269 | val_mcc=0.4605 | val_f1=0.5694 | val_auroc=0.8530

[Epoch 08] train_loss=0.1441 | val_loss=0.6483 | val_mcc=0.4991 | val_f1=0.6009 | val_auroc=0.8614

[Epoch 09] train_loss=0.1128 | val_loss=0.6606 | val_mcc=0.5026 | val_f1=0.6041 | val_auroc=0.8553
[EarlyStop] epoch=9 | best_val_mcc=0.5517
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6159 | F1=0.7249 | AUROC=0.8971 | AUPRC=0.8152
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5914 | F1=0.7857 | AUROC=0.8794 | AUPRC=0.8881
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3983 | F1=0.6974 | AUROC=0.7599 | AUPRC=0.7539
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5780 | F1=0.7695 | AUROC=0.8683 | AUPRC=0.8597
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5042 | val_loss=0.3844 | val_mcc=0.5447 | val_f1=0.6365 | val_auroc=0.8721

[Epoch 02] train_loss=0.4280 | val_loss=0.3817 | val_mcc=0.5600 | val_f1=0.6488 | val_auroc=0.8834

[Epoch 03] train_loss=0.3858 | val_loss=0.3634 | val_mcc=0.5619 | val_f1=0.6491 | val_auroc=0.8773

[Epoch 04] train_loss=0.3416 | val_loss=0.3949 | val_mcc=0.5393 | val_f1=0.6326 | val_auroc=0.8737

[Epoch 05] train_loss=0.2860 | val_loss=0.4342 | val_mcc=0.5238 | val_f1=0.6208 | val_auroc=0.8693

[Epoch 06] train_loss=0.2348 | val_loss=0.4804 | val_mcc=0.5233 | val_f1=0.6204 | val_auroc=0.8626

[Epoch 07] train_loss=0.1828 | val_loss=0.6002 | val_mcc=0.5019 | val_f1=0.6028 | val_auroc=0.8639

[Epoch 08] train_loss=0.1198 | val_loss=0.6848 | val_mcc=0.4880 | val_f1=0.5917 | val_auroc=0.8605

[Epoch 09] train_loss=0.0905 | val_loss=0.6817 | val_mcc=0.4908 | val_f1=0.5951 | val_auroc=0.8558
[EarlyStop] epoch=9 | best_val_mcc=0.5619
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6362 | F1=0.7358 | AUROC=0.8976 | AUPRC=0.8162
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6014 | F1=0.7867 | AUROC=0.8704 | AUPRC=0.8849
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3963 | F1=0.6844 | AUROC=0.7616 | AUPRC=0.7519
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6048 | F1=0.7808 | AUROC=0.8729 | AUPRC=0.8627
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5050 | val_loss=0.4015 | val_mcc=0.5306 | val_f1=0.6259 | val_auroc=0.8672

[Epoch 02] train_loss=0.4232 | val_loss=0.3808 | val_mcc=0.5492 | val_f1=0.6401 | val_auroc=0.8779

[Epoch 03] train_loss=0.3778 | val_loss=0.3959 | val_mcc=0.5362 | val_f1=0.6304 | val_auroc=0.8768

[Epoch 04] train_loss=0.3245 | val_loss=0.3689 | val_mcc=0.5485 | val_f1=0.6387 | val_auroc=0.8755

[Epoch 05] train_loss=0.2655 | val_loss=0.4284 | val_mcc=0.5265 | val_f1=0.6228 | val_auroc=0.8737

[Epoch 06] train_loss=0.2030 | val_loss=0.4708 | val_mcc=0.5085 | val_f1=0.6090 | val_auroc=0.8653

[Epoch 07] train_loss=0.1373 | val_loss=0.4929 | val_mcc=0.5122 | val_f1=0.6118 | val_auroc=0.8698

[Epoch 08] train_loss=0.1060 | val_loss=0.5559 | val_mcc=0.5012 | val_f1=0.6030 | val_auroc=0.8656
[EarlyStop] epoch=8 | best_val_mcc=0.5492
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6357 | F1=0.7368 | AUROC=0.8974 | AUPRC=0.8170
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5971 | F1=0.7887 | AUROC=0.8676 | AUPRC=0.8804
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3865 | F1=0.6871 | AUROC=0.7631 | AUPRC=0.7542
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6131 | F1=0.7860 | AUROC=0.8679 | AUPRC=0.8608
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 348.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6131 | F1=0.7226 | AUROC=0.8944 | AUPRC=0.8107
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6020 | F1=0.7947 | AUROC=0.8821 | AUPRC=0.8858
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4119 | F1=0.7021 | AUROC=0.7599 | AUPRC=0.7426
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5945 | F1=0.7821 | AUROC=0.8767 | AUPRC=0.8671
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 217.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6244 | F1=0.7309 | AUROC=0.8966 | AUPRC=0.8140
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6021 | F1=0.7941 | AUROC=0.8799 | AUPRC=0.8893
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3879 | F1=0.6937 | AUROC=0.7602 | AUPRC=0.7543
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5935 | F1=0.7822 | AUROC=0.8690 | AUPRC=0.8627
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 44.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6203 | F1=0.7287 | AUROC=0.8990 | AUPRC=0.8173
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6075 | F1=0.7988 | AUROC=0.8717 | AUPRC=0.8783
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3956 | F1=0.7008 | AUROC=0.7569 | AUPRC=0.7442
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5739 | F1=0.7730 | AUROC=0.8675 | AUPRC=0.8559
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 53.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6209 | F1=0.7281 | AUROC=0.8956 | AUPRC=0.8111
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5619 | F1=0.7762 | AUROC=0.8649 | AUPRC=0.8769
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3863 | F1=0.6922 | AUROC=0.7546 | AUPRC=0.7447
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.3780 | val_loss=0.2243 | val_mcc=0.7323 | val_f1=0.7847 | val_auroc=0.9589

[Epoch 02] train_loss=0.2566 | val_loss=0.2125 | val_mcc=0.7486 | val_f1=0.7975 | val_auroc=0.9625

[Epoch 03] train_loss=0.2205 | val_loss=0.2186 | val_mcc=0.7429 | val_f1=0.7926 | val_auroc=0.9635

[Epoch 04] train_loss=0.1854 | val_loss=0.2295 | val_mcc=0.7388 | val_f1=0.7892 | val_auroc=0.9611

[Epoch 05] train_loss=0.1472 | val_loss=0.2547 | val_mcc=0.7242 | val_f1=0.7775 | val_auroc=0.9570

[Epoch 06] train_loss=0.1127 | val_loss=0.2628 | val_mcc=0.7271 | val_f1=0.7803 | val_auroc=0.9562

[Epoch 07] train_loss=0.0778 | val_loss=0.2821 | val_mcc=0.7253 | val_f1=0.7786 | val_auroc=0.9571

[Epoch 08] train_loss=0.0604 | val_loss=0.3021 | val_mcc=0.7168 | val_f1=0.7718 | val_auroc=0.9548
[EarlyStop] epoch=8 | best_val_mcc=0.7486
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7537 | F1=0.8228 | AUROC=0.9587 | AUPRC=0.9095
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8338 | F1=0.9123 | AUROC=0.9700 | AUPRC=0.9719
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4153 | F1=0.7220 | AUROC=0.7701 | AUPRC=0.7609
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5710 | F1=0.7823 | AUROC=0.8920 | AUPRC=0.8765
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3990 | val_loss=0.2272 | val_mcc=0.7409 | val_f1=0.7915 | val_auroc=0.9605

[Epoch 02] train_loss=0.2811 | val_loss=0.2272 | val_mcc=0.7358 | val_f1=0.7857 | val_auroc=0.9643

[Epoch 03] train_loss=0.2489 | val_loss=0.2322 | val_mcc=0.7361 | val_f1=0.7859 | val_auroc=0.9629

[Epoch 04] train_loss=0.2190 | val_loss=0.2265 | val_mcc=0.7399 | val_f1=0.7902 | val_auroc=0.9613

[Epoch 05] train_loss=0.1830 | val_loss=0.2462 | val_mcc=0.7235 | val_f1=0.7774 | val_auroc=0.9566

[Epoch 06] train_loss=0.1334 | val_loss=0.2740 | val_mcc=0.7116 | val_f1=0.7682 | val_auroc=0.9509

[Epoch 07] train_loss=0.1078 | val_loss=0.3198 | val_mcc=0.6974 | val_f1=0.7558 | val_auroc=0.9489
[EarlyStop] epoch=7 | best_val_mcc=0.7409
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7533 | F1=0.8225 | AUROC=0.9589 | AUPRC=0.9062
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7817 | F1=0.8866 | AUROC=0.9617 | AUPRC=0.9613
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4447 | F1=0.7343 | AUROC=0.7852 | AUPRC=0.7683
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5922 | F1=0.7921 | AUROC=0.8964 | AUPRC=0.8814
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3906 | val_loss=0.2288 | val_mcc=0.7349 | val_f1=0.7861 | val_auroc=0.9602

[Epoch 02] train_loss=0.2671 | val_loss=0.1935 | val_mcc=0.7602 | val_f1=0.8070 | val_auroc=0.9649

[Epoch 03] train_loss=0.2329 | val_loss=0.2385 | val_mcc=0.7234 | val_f1=0.7755 | val_auroc=0.9610

[Epoch 04] train_loss=0.1989 | val_loss=0.2483 | val_mcc=0.7166 | val_f1=0.7707 | val_auroc=0.9583

[Epoch 05] train_loss=0.1539 | val_loss=0.2572 | val_mcc=0.7295 | val_f1=0.7824 | val_auroc=0.9538

[Epoch 06] train_loss=0.1248 | val_loss=0.2647 | val_mcc=0.7309 | val_f1=0.7836 | val_auroc=0.9514

[Epoch 07] train_loss=0.0795 | val_loss=0.3060 | val_mcc=0.7130 | val_f1=0.7694 | val_auroc=0.9485

[Epoch 08] train_loss=0.0600 | val_loss=0.3385 | val_mcc=0.7113 | val_f1=0.7676 | val_auroc=0.9488
[EarlyStop] epoch=8 | best_val_mcc=0.7602
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7808 | F1=0.8413 | AUROC=0.9608 | AUPRC=0.9148
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7908 | F1=0.8862 | AUROC=0.9696 | AUPRC=0.9683
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4201 | F1=0.7165 | AUROC=0.7804 | AUPRC=0.7655
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5838 | F1=0.7876 | AUROC=0.8951 | AUPRC=0.8779
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3932 | val_loss=0.2336 | val_mcc=0.7252 | val_f1=0.7789 | val_auroc=0.9590

[Epoch 02] train_loss=0.2655 | val_loss=0.2053 | val_mcc=0.7531 | val_f1=0.8011 | val_auroc=0.9656

[Epoch 03] train_loss=0.2212 | val_loss=0.2112 | val_mcc=0.7549 | val_f1=0.8021 | val_auroc=0.9651

[Epoch 04] train_loss=0.1801 | val_loss=0.2213 | val_mcc=0.7433 | val_f1=0.7931 | val_auroc=0.9623

[Epoch 05] train_loss=0.1394 | val_loss=0.2510 | val_mcc=0.7257 | val_f1=0.7785 | val_auroc=0.9590

[Epoch 06] train_loss=0.1005 | val_loss=0.2739 | val_mcc=0.7174 | val_f1=0.7728 | val_auroc=0.9540

[Epoch 07] train_loss=0.0727 | val_loss=0.2995 | val_mcc=0.7147 | val_f1=0.7706 | val_auroc=0.9525

[Epoch 08] train_loss=0.0450 | val_loss=0.3154 | val_mcc=0.7179 | val_f1=0.7727 | val_auroc=0.9551

[Epoch 09] train_loss=0.0348 | val_loss=0.3274 | val_mcc=0.7201 | val_f1=0.7744 | val_auroc=0.9547
[EarlyStop] epoch=9 | best_val_mcc=0.7549
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7711 | F1=0.8351 | AUROC=0.9618 | AUPRC=0.9142
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8326 | F1=0.9136 | AUROC=0.9680 | AUPRC=0.9693
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4363 | F1=0.7340 | AUROC=0.7797 | AUPRC=0.7597
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5738 | F1=0.7833 | AUROC=0.8952 | AUPRC=0.8801
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 182.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7805 | F1=0.8418 | AUROC=0.9662 | AUPRC=0.9242
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8613 | F1=0.9280 | AUROC=0.9839 | AUPRC=0.9846
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4551 | F1=0.7435 | AUROC=0.7848 | AUPRC=0.7718
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5589 | F1=0.7765 | AUROC=0.9064 | AUPRC=0.8895
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 174.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7817 | F1=0.8427 | AUROC=0.9633 | AUPRC=0.9182
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8191 | F1=0.9053 | AUROC=0.9743 | AUPRC=0.9746
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4167 | F1=0.7225 | AUROC=0.7757 | AUPRC=0.7674
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5546 | F1=0.7749 | AUROC=0.8944 | AUPRC=0.8769
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 76.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7729 | F1=0.8364 | AUROC=0.9611 | AUPRC=0.9148
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8246 | F1=0.9086 | AUROC=0.9730 | AUPRC=0.9715
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4319 | F1=0.7321 | AUROC=0.7811 | AUPRC=0.7683
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5844 | F1=0.7884 | AUROC=0.8939 | AUPRC=0.8764
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 135.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7735 | F1=0.8369 | AUROC=0.9593 | AUPRC=0.9102
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8271 | F1=0.9104 | AUROC=0.9660 | AUPRC=0.9664
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4711 | val_loss=0.3677 | val_mcc=0.5630 | val_f1=0.6507 | val_auroc=0.8795

[Epoch 02] train_loss=0.3936 | val_loss=0.3597 | val_mcc=0.5804 | val_f1=0.6644 | val_auroc=0.8883

[Epoch 03] train_loss=0.3489 | val_loss=0.3921 | val_mcc=0.5685 | val_f1=0.6551 | val_auroc=0.8893

[Epoch 04] train_loss=0.3048 | val_loss=0.3761 | val_mcc=0.5726 | val_f1=0.6587 | val_auroc=0.8875

[Epoch 05] train_loss=0.2551 | val_loss=0.3912 | val_mcc=0.5626 | val_f1=0.6506 | val_auroc=0.8798

[Epoch 06] train_loss=0.2027 | val_loss=0.4430 | val_mcc=0.5500 | val_f1=0.6410 | val_auroc=0.8790

[Epoch 07] train_loss=0.1443 | val_loss=0.4809 | val_mcc=0.5456 | val_f1=0.6374 | val_auroc=0.8798

[Epoch 08] train_loss=0.1136 | val_loss=0.5031 | val_mcc=0.5431 | val_f1=0.6355 | val_auroc=0.8785
[EarlyStop] epoch=8 | best_val_mcc=0.5804
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6158 | F1=0.7192 | AUROC=0.8908 | AUPRC=0.8012
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5930 | F1=0.7818 | AUROC=0.8806 | AUPRC=0.8806
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4243 | F1=0.7032 | AUROC=0.7679 | AUPRC=0.7613
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5579 | F1=0.7488 | AUROC=0.8450 | AUPRC=0.8364
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4741 | val_loss=0.3830 | val_mcc=0.5645 | val_f1=0.6522 | val_auroc=0.8837

[Epoch 02] train_loss=0.4060 | val_loss=0.3607 | val_mcc=0.5908 | val_f1=0.6725 | val_auroc=0.8888

[Epoch 03] train_loss=0.3689 | val_loss=0.3535 | val_mcc=0.5896 | val_f1=0.6707 | val_auroc=0.8885

[Epoch 04] train_loss=0.3333 | val_loss=0.3642 | val_mcc=0.5774 | val_f1=0.6618 | val_auroc=0.8870

[Epoch 05] train_loss=0.2896 | val_loss=0.4632 | val_mcc=0.5327 | val_f1=0.6259 | val_auroc=0.8805

[Epoch 06] train_loss=0.2403 | val_loss=0.5009 | val_mcc=0.5100 | val_f1=0.6093 | val_auroc=0.8677

[Epoch 07] train_loss=0.1713 | val_loss=0.5562 | val_mcc=0.5203 | val_f1=0.6178 | val_auroc=0.8672

[Epoch 08] train_loss=0.1366 | val_loss=0.5853 | val_mcc=0.5278 | val_f1=0.6238 | val_auroc=0.8635
[EarlyStop] epoch=8 | best_val_mcc=0.5908
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6175 | F1=0.7192 | AUROC=0.8892 | AUPRC=0.7966
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6153 | F1=0.7952 | AUROC=0.8877 | AUPRC=0.8792
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4334 | F1=0.7070 | AUROC=0.7711 | AUPRC=0.7643
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5498 | F1=0.7425 | AUROC=0.8466 | AUPRC=0.8327
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4704 | val_loss=0.3412 | val_mcc=0.5866 | val_f1=0.6663 | val_auroc=0.8825

[Epoch 02] train_loss=0.3997 | val_loss=0.3688 | val_mcc=0.5736 | val_f1=0.6595 | val_auroc=0.8872

[Epoch 03] train_loss=0.3561 | val_loss=0.3682 | val_mcc=0.5718 | val_f1=0.6580 | val_auroc=0.8897

[Epoch 04] train_loss=0.3108 | val_loss=0.4285 | val_mcc=0.5550 | val_f1=0.6443 | val_auroc=0.8815

[Epoch 05] train_loss=0.2619 | val_loss=0.4085 | val_mcc=0.5589 | val_f1=0.6479 | val_auroc=0.8785

[Epoch 06] train_loss=0.1876 | val_loss=0.4698 | val_mcc=0.5531 | val_f1=0.6435 | val_auroc=0.8775

[Epoch 07] train_loss=0.1483 | val_loss=0.5323 | val_mcc=0.5398 | val_f1=0.6332 | val_auroc=0.8723
[EarlyStop] epoch=7 | best_val_mcc=0.5866
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6245 | F1=0.7176 | AUROC=0.8872 | AUPRC=0.7959
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6377 | F1=0.7969 | AUROC=0.8778 | AUPRC=0.8758
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4239 | F1=0.6846 | AUROC=0.7662 | AUPRC=0.7518
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5465 | F1=0.7288 | AUROC=0.8360 | AUPRC=0.8253
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4740 | val_loss=0.3817 | val_mcc=0.5559 | val_f1=0.6453 | val_auroc=0.8792

[Epoch 02] train_loss=0.3927 | val_loss=0.3852 | val_mcc=0.5571 | val_f1=0.6466 | val_auroc=0.8849

[Epoch 03] train_loss=0.3453 | val_loss=0.3671 | val_mcc=0.5710 | val_f1=0.6573 | val_auroc=0.8881

[Epoch 04] train_loss=0.2920 | val_loss=0.3984 | val_mcc=0.5460 | val_f1=0.6380 | val_auroc=0.8840

[Epoch 05] train_loss=0.2316 | val_loss=0.4415 | val_mcc=0.5413 | val_f1=0.6340 | val_auroc=0.8787

[Epoch 06] train_loss=0.1769 | val_loss=0.5108 | val_mcc=0.5271 | val_f1=0.6219 | val_auroc=0.8775

[Epoch 07] train_loss=0.1263 | val_loss=0.5600 | val_mcc=0.5244 | val_f1=0.6202 | val_auroc=0.8763

[Epoch 08] train_loss=0.0818 | val_loss=0.5823 | val_mcc=0.5276 | val_f1=0.6227 | val_auroc=0.8792

[Epoch 09] train_loss=0.0584 | val_loss=0.6145 | val_mcc=0.5279 | val_f1=0.6230 | val_auroc=0.8786
[EarlyStop] epoch=9 | best_val_mcc=0.5710
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6148 | F1=0.7198 | AUROC=0.8904 | AUPRC=0.7980
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6056 | F1=0.7935 | AUROC=0.8883 | AUPRC=0.8828
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4209 | F1=0.7067 | AUROC=0.7657 | AUPRC=0.7569
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5385 | F1=0.7403 | AUROC=0.8438 | AUPRC=0.8298
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 323.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6032 | F1=0.7133 | AUROC=0.8878 | AUPRC=0.7854
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6162 | F1=0.8023 | AUROC=0.8851 | AUPRC=0.8729
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4224 | F1=0.7068 | AUROC=0.7692 | AUPRC=0.7586
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5399 | F1=0.7409 | AUROC=0.8488 | AUPRC=0.8186
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 178.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6153 | F1=0.7218 | AUROC=0.8915 | AUPRC=0.7995
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6195 | F1=0.8018 | AUROC=0.8885 | AUPRC=0.8801
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4360 | F1=0.7130 | AUROC=0.7745 | AUPRC=0.7602
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5371 | F1=0.7390 | AUROC=0.8453 | AUPRC=0.8307
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 42.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6220 | F1=0.7266 | AUROC=0.8925 | AUPRC=0.8020
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6309 | F1=0.8077 | AUROC=0.8917 | AUPRC=0.8834
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4148 | F1=0.7063 | AUROC=0.7719 | AUPRC=0.7607
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5538 | F1=0.7513 | AUROC=0.8452 | AUPRC=0.8323
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 60.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6084 | F1=0.7165 | AUROC=0.8899 | AUPRC=0.7967
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5936 | F1=0.7894 | AUROC=0.8801 | AUPRC=0.8688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3970 | F1=0.6927 | AUROC=0.7642 | AUPRC=0.7599
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.3778 | val_loss=0.2212 | val_mcc=0.7413 | val_f1=0.7920 | val_auroc=0.9588

[Epoch 02] train_loss=0.2491 | val_loss=0.2022 | val_mcc=0.7649 | val_f1=0.8105 | val_auroc=0.9675

[Epoch 03] train_loss=0.2045 | val_loss=0.1987 | val_mcc=0.7655 | val_f1=0.8112 | val_auroc=0.9658

[Epoch 04] train_loss=0.1717 | val_loss=0.2321 | val_mcc=0.7398 | val_f1=0.7898 | val_auroc=0.9626

[Epoch 05] train_loss=0.1387 | val_loss=0.2223 | val_mcc=0.7499 | val_f1=0.7986 | val_auroc=0.9621

[Epoch 06] train_loss=0.1036 | val_loss=0.2572 | val_mcc=0.7377 | val_f1=0.7881 | val_auroc=0.9598

[Epoch 07] train_loss=0.0743 | val_loss=0.2673 | val_mcc=0.7420 | val_f1=0.7918 | val_auroc=0.9601

[Epoch 08] train_loss=0.0506 | val_loss=0.2624 | val_mcc=0.7493 | val_f1=0.7983 | val_auroc=0.9600

[Epoch 09] train_loss=0.0380 | val_loss=0.2862 | val_mcc=0.7432 | val_f1=0.7930 | val_auroc=0.9600
[EarlyStop] epoch=9 | best_val_mcc=0.7655
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7678 | F1=0.8322 | AUROC=0.9569 | AUPRC=0.9111
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8077 | F1=0.8994 | AUROC=0.9685 | AUPRC=0.9690
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4276 | F1=0.7251 | AUROC=0.7823 | AUPRC=0.7675
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5923 | F1=0.7912 | AUROC=0.8870 | AUPRC=0.8603
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3708 | val_loss=0.2074 | val_mcc=0.7545 | val_f1=0.8024 | val_auroc=0.9654

[Epoch 02] train_loss=0.2594 | val_loss=0.1884 | val_mcc=0.7786 | val_f1=0.8218 | val_auroc=0.9683

[Epoch 03] train_loss=0.2245 | val_loss=0.2188 | val_mcc=0.7563 | val_f1=0.8031 | val_auroc=0.9653

[Epoch 04] train_loss=0.1922 | val_loss=0.2338 | val_mcc=0.7420 | val_f1=0.7910 | val_auroc=0.9639

[Epoch 05] train_loss=0.1573 | val_loss=0.2651 | val_mcc=0.7342 | val_f1=0.7851 | val_auroc=0.9589

[Epoch 06] train_loss=0.1267 | val_loss=0.2722 | val_mcc=0.7262 | val_f1=0.7795 | val_auroc=0.9539

[Epoch 07] train_loss=0.0829 | val_loss=0.3110 | val_mcc=0.7168 | val_f1=0.7713 | val_auroc=0.9554

[Epoch 08] train_loss=0.0662 | val_loss=0.3106 | val_mcc=0.7289 | val_f1=0.7818 | val_auroc=0.9540
[EarlyStop] epoch=8 | best_val_mcc=0.7786
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7757 | F1=0.8379 | AUROC=0.9615 | AUPRC=0.9131
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8303 | F1=0.9115 | AUROC=0.9723 | AUPRC=0.9712
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4481 | F1=0.7332 | AUROC=0.7847 | AUPRC=0.7677
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5511 | F1=0.7726 | AUROC=0.8739 | AUPRC=0.8485
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3680 | val_loss=0.2078 | val_mcc=0.7494 | val_f1=0.7984 | val_auroc=0.9632

[Epoch 02] train_loss=0.2570 | val_loss=0.1821 | val_mcc=0.7752 | val_f1=0.8184 | val_auroc=0.9672

[Epoch 03] train_loss=0.2195 | val_loss=0.2062 | val_mcc=0.7604 | val_f1=0.8068 | val_auroc=0.9657

[Epoch 04] train_loss=0.1796 | val_loss=0.2122 | val_mcc=0.7564 | val_f1=0.8040 | val_auroc=0.9629

[Epoch 05] train_loss=0.1447 | val_loss=0.2423 | val_mcc=0.7387 | val_f1=0.7898 | val_auroc=0.9576

[Epoch 06] train_loss=0.1099 | val_loss=0.3099 | val_mcc=0.7171 | val_f1=0.7707 | val_auroc=0.9560

[Epoch 07] train_loss=0.0697 | val_loss=0.2751 | val_mcc=0.7357 | val_f1=0.7874 | val_auroc=0.9568

[Epoch 08] train_loss=0.0498 | val_loss=0.3532 | val_mcc=0.7144 | val_f1=0.7688 | val_auroc=0.9544
[EarlyStop] epoch=8 | best_val_mcc=0.7752
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7723 | F1=0.8337 | AUROC=0.9605 | AUPRC=0.9122
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8007 | F1=0.8899 | AUROC=0.9716 | AUPRC=0.9684
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4345 | F1=0.7197 | AUROC=0.7836 | AUPRC=0.7670
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5904 | F1=0.7898 | AUROC=0.8837 | AUPRC=0.8660
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3729 | val_loss=0.2197 | val_mcc=0.7499 | val_f1=0.7986 | val_auroc=0.9630

[Epoch 02] train_loss=0.2438 | val_loss=0.2023 | val_mcc=0.7653 | val_f1=0.8109 | val_auroc=0.9659

[Epoch 03] train_loss=0.2006 | val_loss=0.2046 | val_mcc=0.7562 | val_f1=0.8037 | val_auroc=0.9653

[Epoch 04] train_loss=0.1636 | val_loss=0.2141 | val_mcc=0.7575 | val_f1=0.8048 | val_auroc=0.9638

[Epoch 05] train_loss=0.1247 | val_loss=0.2489 | val_mcc=0.7359 | val_f1=0.7868 | val_auroc=0.9598

[Epoch 06] train_loss=0.0880 | val_loss=0.2757 | val_mcc=0.7301 | val_f1=0.7818 | val_auroc=0.9590

[Epoch 07] train_loss=0.0560 | val_loss=0.2717 | val_mcc=0.7327 | val_f1=0.7846 | val_auroc=0.9601

[Epoch 08] train_loss=0.0417 | val_loss=0.2834 | val_mcc=0.7372 | val_f1=0.7884 | val_auroc=0.9592
[EarlyStop] epoch=8 | best_val_mcc=0.7653
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7677 | F1=0.8326 | AUROC=0.9611 | AUPRC=0.9142
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7957 | F1=0.8944 | AUROC=0.9688 | AUPRC=0.9675
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4341 | F1=0.7320 | AUROC=0.7822 | AUPRC=0.7649
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5476 | F1=0.7717 | AUROC=0.8785 | AUPRC=0.8580
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 201.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7905 | F1=0.8489 | AUROC=0.9671 | AUPRC=0.9278
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8588 | F1=0.9263 | AUROC=0.9848 | AUPRC=0.9843
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4491 | F1=0.7387 | AUROC=0.7853 | AUPRC=0.7662
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5578 | F1=0.7764 | AUROC=0.9003 | AUPRC=0.8745
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 190.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7791 | F1=0.8408 | AUROC=0.9627 | AUPRC=0.9184
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8154 | F1=0.9051 | AUROC=0.9722 | AUPRC=0.9695
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4458 | F1=0.7369 | AUROC=0.7840 | AUPRC=0.7599
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5602 | F1=0.7775 | AUROC=0.8864 | AUPRC=0.8674
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 77.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7697 | F1=0.8341 | AUROC=0.9595 | AUPRC=0.9091
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8185 | F1=0.9062 | AUROC=0.9702 | AUPRC=0.9668
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4337 | F1=0.7313 | AUROC=0.7868 | AUPRC=0.7689
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5688 | F1=0.7813 | AUROC=0.8825 | AUPRC=0.8588
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 94.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7818 | F1=0.8427 | AUROC=0.9615 | AUPRC=0.9155
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8551 | F1=0.9258 | AUROC=0.9768 | AUPRC=0.9753
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.4889 | val_loss=0.3438 | val_mcc=0.6287 | val_f1=0.6968 | val_auroc=0.8771

[Epoch 02] train_loss=0.4097 | val_loss=0.3307 | val_mcc=0.6234 | val_f1=0.6957 | val_auroc=0.8914

[Epoch 03] train_loss=0.3537 | val_loss=0.3402 | val_mcc=0.6123 | val_f1=0.6896 | val_auroc=0.8979

[Epoch 04] train_loss=0.2961 | val_loss=0.3284 | val_mcc=0.6157 | val_f1=0.6913 | val_auroc=0.8979

[Epoch 05] train_loss=0.2327 | val_loss=0.4028 | val_mcc=0.5797 | val_f1=0.6635 | val_auroc=0.8977

[Epoch 06] train_loss=0.1592 | val_loss=0.4223 | val_mcc=0.5716 | val_f1=0.6574 | val_auroc=0.8941

[Epoch 07] train_loss=0.1228 | val_loss=0.4530 | val_mcc=0.5685 | val_f1=0.6551 | val_auroc=0.8931
[EarlyStop] epoch=7 | best_val_mcc=0.6287
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6610 | F1=0.7448 | AUROC=0.8888 | AUPRC=0.8241
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5910 | F1=0.7726 | AUROC=0.8734 | AUPRC=0.8889
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4380 | F1=0.6865 | AUROC=0.7631 | AUPRC=0.7703
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6031 | F1=0.7648 | AUROC=0.8610 | AUPRC=0.8615
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4823 | val_loss=0.3518 | val_mcc=0.6212 | val_f1=0.6932 | val_auroc=0.8849

[Epoch 02] train_loss=0.4099 | val_loss=0.3312 | val_mcc=0.6233 | val_f1=0.6970 | val_auroc=0.9011

[Epoch 03] train_loss=0.3606 | val_loss=0.3297 | val_mcc=0.6137 | val_f1=0.6905 | val_auroc=0.9030

[Epoch 04] train_loss=0.3071 | val_loss=0.3292 | val_mcc=0.6116 | val_f1=0.6884 | val_auroc=0.9024

[Epoch 05] train_loss=0.2387 | val_loss=0.3865 | val_mcc=0.5973 | val_f1=0.6780 | val_auroc=0.8969

[Epoch 06] train_loss=0.1740 | val_loss=0.4771 | val_mcc=0.5709 | val_f1=0.6574 | val_auroc=0.8839

[Epoch 07] train_loss=0.1043 | val_loss=0.5627 | val_mcc=0.5633 | val_f1=0.6510 | val_auroc=0.8858

[Epoch 08] train_loss=0.0757 | val_loss=0.6859 | val_mcc=0.5514 | val_f1=0.6410 | val_auroc=0.8842
[EarlyStop] epoch=8 | best_val_mcc=0.6233
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6718 | F1=0.7598 | AUROC=0.9095 | AUPRC=0.8413
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6711 | F1=0.8279 | AUROC=0.8932 | AUPRC=0.9062
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4551 | F1=0.7147 | AUROC=0.7849 | AUPRC=0.7723
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6118 | F1=0.7801 | AUROC=0.8745 | AUPRC=0.8693
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4764 | val_loss=0.3560 | val_mcc=0.6168 | val_f1=0.6911 | val_auroc=0.8860

[Epoch 02] train_loss=0.4006 | val_loss=0.2999 | val_mcc=0.6361 | val_f1=0.7022 | val_auroc=0.8974

[Epoch 03] train_loss=0.3492 | val_loss=0.3514 | val_mcc=0.5896 | val_f1=0.6720 | val_auroc=0.8949

[Epoch 04] train_loss=0.2874 | val_loss=0.3389 | val_mcc=0.6108 | val_f1=0.6878 | val_auroc=0.8984

[Epoch 05] train_loss=0.2204 | val_loss=0.4026 | val_mcc=0.5804 | val_f1=0.6647 | val_auroc=0.8888

[Epoch 06] train_loss=0.1521 | val_loss=0.4981 | val_mcc=0.5719 | val_f1=0.6580 | val_auroc=0.8876

[Epoch 07] train_loss=0.0874 | val_loss=0.5651 | val_mcc=0.5864 | val_f1=0.6695 | val_auroc=0.8896

[Epoch 08] train_loss=0.0615 | val_loss=0.6668 | val_mcc=0.5590 | val_f1=0.6474 | val_auroc=0.8840
[EarlyStop] epoch=8 | best_val_mcc=0.6361
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6671 | F1=0.7482 | AUROC=0.9068 | AUPRC=0.8389
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6262 | F1=0.7906 | AUROC=0.8986 | AUPRC=0.9061
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4351 | F1=0.6806 | AUROC=0.7755 | AUPRC=0.7711
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6033 | F1=0.7644 | AUROC=0.8766 | AUPRC=0.8707
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4873 | val_loss=0.3437 | val_mcc=0.6168 | val_f1=0.6875 | val_auroc=0.8768

[Epoch 02] train_loss=0.4032 | val_loss=0.3450 | val_mcc=0.6099 | val_f1=0.6872 | val_auroc=0.8932

[Epoch 03] train_loss=0.3453 | val_loss=0.3184 | val_mcc=0.6134 | val_f1=0.6887 | val_auroc=0.8962

[Epoch 04] train_loss=0.2826 | val_loss=0.3836 | val_mcc=0.5802 | val_f1=0.6642 | val_auroc=0.8956

[Epoch 05] train_loss=0.2102 | val_loss=0.4207 | val_mcc=0.5625 | val_f1=0.6502 | val_auroc=0.8923

[Epoch 06] train_loss=0.1351 | val_loss=0.4227 | val_mcc=0.5735 | val_f1=0.6594 | val_auroc=0.8904

[Epoch 07] train_loss=0.0973 | val_loss=0.4727 | val_mcc=0.5644 | val_f1=0.6521 | val_auroc=0.8879
[EarlyStop] epoch=7 | best_val_mcc=0.6168
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6625 | F1=0.7468 | AUROC=0.8878 | AUPRC=0.8211
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5831 | F1=0.7668 | AUROC=0.8701 | AUPRC=0.8879
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4406 | F1=0.6892 | AUROC=0.7677 | AUPRC=0.7729
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5967 | F1=0.7593 | AUROC=0.8575 | AUPRC=0.8586
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 315.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6579 | F1=0.7519 | AUROC=0.9082 | AUPRC=0.8329
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6474 | F1=0.8187 | AUROC=0.8971 | AUPRC=0.9035
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4318 | F1=0.7073 | AUROC=0.7739 | AUPRC=0.7709
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6022 | F1=0.7806 | AUROC=0.8748 | AUPRC=0.8692
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 201.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6576 | F1=0.7526 | AUROC=0.9111 | AUPRC=0.8390
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6360 | F1=0.8134 | AUROC=0.8961 | AUPRC=0.9017
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4374 | F1=0.7148 | AUROC=0.7752 | AUPRC=0.7656
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.6064 | F1=0.7834 | AUROC=0.8739 | AUPRC=0.8652
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 54.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6590 | F1=0.7546 | AUROC=0.9060 | AUPRC=0.8325
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6415 | F1=0.8184 | AUROC=0.9010 | AUPRC=0.9075
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4343 | F1=0.7155 | AUROC=0.7752 | AUPRC=0.7728
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.6099 | F1=0.7881 | AUROC=0.8771 | AUPRC=0.8700
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 97.
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6517 | F1=0.7501 | AUROC=0.9039 | AUPRC=0.8306
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6417 | F1=0.8163 | AUROC=0.8911 | AUPRC=0.9035
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4449 | F1=0.7222 | AUROC=0.7756 | AUPRC=0.7725
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.3746 | val_loss=0.1949 | val_mcc=0.7657 | val_f1=0.8108 | val_auroc=0.9645

[Epoch 02] train_loss=0.2522 | val_loss=0.1988 | val_mcc=0.7661 | val_f1=0.8114 | val_auroc=0.9675

[Epoch 03] train_loss=0.2095 | val_loss=0.1911 | val_mcc=0.7684 | val_f1=0.8136 | val_auroc=0.9667

[Epoch 04] train_loss=0.1662 | val_loss=0.1951 | val_mcc=0.7671 | val_f1=0.8125 | val_auroc=0.9652

[Epoch 05] train_loss=0.1258 | val_loss=0.2096 | val_mcc=0.7699 | val_f1=0.8145 | val_auroc=0.9627

[Epoch 06] train_loss=0.0852 | val_loss=0.2561 | val_mcc=0.7464 | val_f1=0.7955 | val_auroc=0.9615

[Epoch 07] train_loss=0.0548 | val_loss=0.2736 | val_mcc=0.7455 | val_f1=0.7952 | val_auroc=0.9590

[Epoch 08] train_loss=0.0363 | val_loss=0.3031 | val_mcc=0.7378 | val_f1=0.7887 | val_auroc=0.9583

[Epoch 09] train_loss=0.0266 | val_loss=0.3182 | val_mcc=0.7414 | val_f1=0.7919 | val_auroc=0.9568

[Epoch 10] train_loss=0.0159 | val_loss=0.3211 | val_mcc=0.7462 | val_f1=0.7957 | val_auroc=0.9578

[Epoch 11] train_loss=0.0122 | val_loss=0.3286 | val_mcc=0.7471 | val_f1=0.7965 | val_auroc=0.9586
[EarlyStop] epoch=11 | best_val_mcc=0.7699
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7709 | F1=0.8339 | AUROC=0.9576 | AUPRC=0.9095
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7999 | F1=0.8942 | AUROC=0.9704 | AUPRC=0.9691
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4651 | F1=0.7381 | AUROC=0.7880 | AUPRC=0.7831
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6261 | F1=0.8073 | AUROC=0.8995 | AUPRC=0.8812
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3707 | val_loss=0.1874 | val_mcc=0.7774 | val_f1=0.8206 | val_auroc=0.9668

[Epoch 02] train_loss=0.2616 | val_loss=0.1728 | val_mcc=0.7858 | val_f1=0.8257 | val_auroc=0.9679

[Epoch 03] train_loss=0.2255 | val_loss=0.1905 | val_mcc=0.7706 | val_f1=0.8154 | val_auroc=0.9677

[Epoch 04] train_loss=0.1834 | val_loss=0.2414 | val_mcc=0.7301 | val_f1=0.7806 | val_auroc=0.9644

[Epoch 05] train_loss=0.1368 | val_loss=0.2419 | val_mcc=0.7405 | val_f1=0.7910 | val_auroc=0.9605

[Epoch 06] train_loss=0.0943 | val_loss=0.2836 | val_mcc=0.7407 | val_f1=0.7914 | val_auroc=0.9562

[Epoch 07] train_loss=0.0558 | val_loss=0.3424 | val_mcc=0.7204 | val_f1=0.7742 | val_auroc=0.9534

[Epoch 08] train_loss=0.0410 | val_loss=0.3370 | val_mcc=0.7397 | val_f1=0.7906 | val_auroc=0.9509
[EarlyStop] epoch=8 | best_val_mcc=0.7858
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7887 | F1=0.8450 | AUROC=0.9627 | AUPRC=0.9220
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8044 | F1=0.8909 | AUROC=0.9760 | AUPRC=0.9754
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4629 | F1=0.7288 | AUROC=0.7868 | AUPRC=0.7766
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6476 | F1=0.8166 | AUROC=0.9083 | AUPRC=0.8935
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3736 | val_loss=0.2042 | val_mcc=0.7675 | val_f1=0.8129 | val_auroc=0.9660

[Epoch 02] train_loss=0.2576 | val_loss=0.1819 | val_mcc=0.7796 | val_f1=0.8223 | val_auroc=0.9671

[Epoch 03] train_loss=0.2189 | val_loss=0.1801 | val_mcc=0.7779 | val_f1=0.8198 | val_auroc=0.9661

[Epoch 04] train_loss=0.1693 | val_loss=0.2214 | val_mcc=0.7521 | val_f1=0.8005 | val_auroc=0.9614

[Epoch 05] train_loss=0.1254 | val_loss=0.2206 | val_mcc=0.7609 | val_f1=0.8070 | val_auroc=0.9607

[Epoch 06] train_loss=0.0848 | val_loss=0.2720 | val_mcc=0.7364 | val_f1=0.7880 | val_auroc=0.9575

[Epoch 07] train_loss=0.0461 | val_loss=0.3082 | val_mcc=0.7305 | val_f1=0.7833 | val_auroc=0.9542

[Epoch 08] train_loss=0.0311 | val_loss=0.3393 | val_mcc=0.7263 | val_f1=0.7798 | val_auroc=0.9538
[EarlyStop] epoch=8 | best_val_mcc=0.7796
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7850 | F1=0.8442 | AUROC=0.9615 | AUPRC=0.9188
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8120 | F1=0.8996 | AUROC=0.9700 | AUPRC=0.9708
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4727 | F1=0.7423 | AUROC=0.7850 | AUPRC=0.7778
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5830 | F1=0.7874 | AUROC=0.8954 | AUPRC=0.8811
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3812 | val_loss=0.2035 | val_mcc=0.7550 | val_f1=0.8029 | val_auroc=0.9644

[Epoch 02] train_loss=0.2560 | val_loss=0.1931 | val_mcc=0.7675 | val_f1=0.8128 | val_auroc=0.9677

[Epoch 03] train_loss=0.2092 | val_loss=0.1908 | val_mcc=0.7674 | val_f1=0.8128 | val_auroc=0.9666

[Epoch 04] train_loss=0.1669 | val_loss=0.2011 | val_mcc=0.7672 | val_f1=0.8126 | val_auroc=0.9642

[Epoch 05] train_loss=0.1166 | val_loss=0.2305 | val_mcc=0.7551 | val_f1=0.8028 | val_auroc=0.9618

[Epoch 06] train_loss=0.0747 | val_loss=0.2479 | val_mcc=0.7488 | val_f1=0.7980 | val_auroc=0.9599

[Epoch 07] train_loss=0.0438 | val_loss=0.2797 | val_mcc=0.7403 | val_f1=0.7904 | val_auroc=0.9605

[Epoch 08] train_loss=0.0325 | val_loss=0.2804 | val_mcc=0.7479 | val_f1=0.7970 | val_auroc=0.9598
[EarlyStop] epoch=8 | best_val_mcc=0.7675
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7677 | F1=0.8327 | AUROC=0.9620 | AUPRC=0.9202
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8134 | F1=0.9024 | AUROC=0.9740 | AUPRC=0.9729
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4263 | F1=0.7279 | AUROC=0.7789 | AUPRC=0.7677
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5520 | F1=0.7738 | AUROC=0.8962 | AUPRC=0.8833
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 219.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7937 | F1=0.8512 | AUROC=0.9689 | AUPRC=0.9332
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8741 | F1=0.9329 | AUROC=0.9840 | AUPRC=0.9846
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4612 | F1=0.7463 | AUROC=0.7879 | AUPRC=0.7777
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5559 | F1=0.7755 | AUROC=0.9038 | AUPRC=0.8876
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 161.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7854 | F1=0.8453 | AUROC=0.9640 | AUPRC=0.9256
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8531 | F1=0.9233 | AUROC=0.9773 | AUPRC=0.9776
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4397 | F1=0.7362 | AUROC=0.7879 | AUPRC=0.7796
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5824 | F1=0.7872 | AUROC=0.9009 | AUPRC=0.8836
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 76.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7817 | F1=0.8427 | AUROC=0.9623 | AUPRC=0.9225
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8440 | F1=0.9195 | AUROC=0.9733 | AUPRC=0.9740
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4418 | F1=0.7357 | AUROC=0.7915 | AUPRC=0.7884
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5961 | F1=0.7939 | AUROC=0.9057 | AUPRC=0.8923
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 96.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7737 | F1=0.8370 | AUROC=0.9619 | AUPRC=0.9197
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8497 | F1=0.9224 | AUROC=0.9740 | AUPRC=0.9739
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.4605 | val_loss=0.3672 | val_mcc=0.5944 | val_f1=0.6757 | val_auroc=0.8942

[Epoch 02] train_loss=0.3984 | val_loss=0.3588 | val_mcc=0.6054 | val_f1=0.6843 | val_auroc=0.9026

[Epoch 03] train_loss=0.3776 | val_loss=0.3381 | val_mcc=0.6148 | val_f1=0.6914 | val_auroc=0.8989

[Epoch 04] train_loss=0.3604 | val_loss=0.3614 | val_mcc=0.6017 | val_f1=0.6813 | val_auroc=0.9016

[Epoch 05] train_loss=0.3401 | val_loss=0.3339 | val_mcc=0.6223 | val_f1=0.6976 | val_auroc=0.9047

[Epoch 06] train_loss=0.3202 | val_loss=0.3363 | val_mcc=0.6113 | val_f1=0.6888 | val_auroc=0.9045

[Epoch 07] train_loss=0.3044 | val_loss=0.4147 | val_mcc=0.5790 | val_f1=0.6610 | val_auroc=0.9038

[Epoch 08] train_loss=0.2862 | val_loss=0.3476 | val_mcc=0.6065 | val_f1=0.6849 | val_auroc=0.8969

[Epoch 09] train_loss=0.2744 | val_loss=0.4042 | val_mcc=0.5860 | val_f1=0.6685 | val_auroc=0.8976

[Epoch 10] train_loss=0.2378 | val_loss=0.3881 | val_mcc=0.5876 | val_f1=0.6704 | val_auroc=0.8980

[Epoch 11] train_loss=0.2262 | val_loss=0.4081 | val_mcc=0.5831 | val_f1=0.6668 | val_auroc=0.8929
[EarlyStop] epoch=11 | best_val_mcc=0.6223
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6818 | F1=0.7698 | AUROC=0.9172 | AUPRC=0.8406
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6444 | F1=0.8186 | AUROC=0.8988 | AUPRC=0.9060
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4496 | F1=0.7179 | AUROC=0.7856 | AUPRC=0.7798
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6423 | F1=0.8045 | AUROC=0.8952 | AUPRC=0.8838
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4642 | val_loss=0.3579 | val_mcc=0.5959 | val_f1=0.6769 | val_auroc=0.8949

[Epoch 02] train_loss=0.4080 | val_loss=0.3510 | val_mcc=0.6138 | val_f1=0.6909 | val_auroc=0.8986

[Epoch 03] train_loss=0.3849 | val_loss=0.3642 | val_mcc=0.6069 | val_f1=0.6853 | val_auroc=0.9016

[Epoch 04] train_loss=0.3673 | val_loss=0.3657 | val_mcc=0.6071 | val_f1=0.6851 | val_auroc=0.9029

[Epoch 05] train_loss=0.3522 | val_loss=0.3573 | val_mcc=0.6090 | val_f1=0.6872 | val_auroc=0.9002

[Epoch 06] train_loss=0.3303 | val_loss=0.3503 | val_mcc=0.6111 | val_f1=0.6888 | val_auroc=0.8984

[Epoch 07] train_loss=0.3055 | val_loss=0.3888 | val_mcc=0.5969 | val_f1=0.6771 | val_auroc=0.9016

[Epoch 08] train_loss=0.2883 | val_loss=0.3748 | val_mcc=0.6010 | val_f1=0.6808 | val_auroc=0.9022
[EarlyStop] epoch=8 | best_val_mcc=0.6138
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6640 | F1=0.7572 | AUROC=0.9117 | AUPRC=0.8336
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6304 | F1=0.8099 | AUROC=0.8917 | AUPRC=0.8940
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4590 | F1=0.7199 | AUROC=0.7858 | AUPRC=0.7774
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6085 | F1=0.7875 | AUROC=0.8758 | AUPRC=0.8675
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4615 | val_loss=0.3544 | val_mcc=0.6021 | val_f1=0.6816 | val_auroc=0.8909

[Epoch 02] train_loss=0.4010 | val_loss=0.3346 | val_mcc=0.6209 | val_f1=0.6960 | val_auroc=0.9034

[Epoch 03] train_loss=0.3806 | val_loss=0.3435 | val_mcc=0.6157 | val_f1=0.6925 | val_auroc=0.9047

[Epoch 04] train_loss=0.3595 | val_loss=0.3717 | val_mcc=0.6115 | val_f1=0.6887 | val_auroc=0.9092

[Epoch 05] train_loss=0.3446 | val_loss=0.3815 | val_mcc=0.5971 | val_f1=0.6766 | val_auroc=0.9049

[Epoch 06] train_loss=0.3265 | val_loss=0.3369 | val_mcc=0.6021 | val_f1=0.6808 | val_auroc=0.8946

[Epoch 07] train_loss=0.2909 | val_loss=0.3744 | val_mcc=0.6042 | val_f1=0.6833 | val_auroc=0.9026

[Epoch 08] train_loss=0.2773 | val_loss=0.3975 | val_mcc=0.6027 | val_f1=0.6816 | val_auroc=0.9044
[EarlyStop] epoch=8 | best_val_mcc=0.6209
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6700 | F1=0.7592 | AUROC=0.9097 | AUPRC=0.8304
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6135 | F1=0.8000 | AUROC=0.8900 | AUPRC=0.8923
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4376 | F1=0.7030 | AUROC=0.7759 | AUPRC=0.7816
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6076 | F1=0.7823 | AUROC=0.8783 | AUPRC=0.8714
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4666 | val_loss=0.3537 | val_mcc=0.5929 | val_f1=0.6745 | val_auroc=0.8958

[Epoch 02] train_loss=0.4018 | val_loss=0.3522 | val_mcc=0.6065 | val_f1=0.6852 | val_auroc=0.8996

[Epoch 03] train_loss=0.3794 | val_loss=0.3343 | val_mcc=0.6109 | val_f1=0.6886 | val_auroc=0.9050

[Epoch 04] train_loss=0.3580 | val_loss=0.3437 | val_mcc=0.6134 | val_f1=0.6906 | val_auroc=0.9063

[Epoch 05] train_loss=0.3339 | val_loss=0.3566 | val_mcc=0.6091 | val_f1=0.6872 | val_auroc=0.9040

[Epoch 06] train_loss=0.3194 | val_loss=0.3837 | val_mcc=0.5974 | val_f1=0.6771 | val_auroc=0.9025

[Epoch 07] train_loss=0.2979 | val_loss=0.3426 | val_mcc=0.6187 | val_f1=0.6943 | val_auroc=0.9002

[Epoch 08] train_loss=0.2746 | val_loss=0.3699 | val_mcc=0.6001 | val_f1=0.6802 | val_auroc=0.8952

[Epoch 09] train_loss=0.2617 | val_loss=0.4057 | val_mcc=0.5813 | val_f1=0.6654 | val_auroc=0.8872

[Epoch 10] train_loss=0.2425 | val_loss=0.4221 | val_mcc=0.5850 | val_f1=0.6679 | val_auroc=0.8974

[Epoch 11] train_loss=0.2266 | val_loss=0.4250 | val_mcc=0.5721 | val_f1=0.6583 | val_auroc=0.8824

[Epoch 12] train_loss=0.1921 | val_loss=0.4257 | val_mcc=0.5766 | val_f1=0.6617 | val_auroc=0.8911

[Epoch 13] train_loss=0.1749 | val_loss=0.4344 | val_mcc=0.5825 | val_f1=0.6664 | val_auroc=0.8868
[EarlyStop] epoch=13 | best_val_mcc=0.6187
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6842 | F1=0.7697 | AUROC=0.9132 | AUPRC=0.8377
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6078 | F1=0.7971 | AUROC=0.8903 | AUPRC=0.8980
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4469 | F1=0.7146 | AUROC=0.7768 | AUPRC=0.7755
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6351 | F1=0.7973 | AUROC=0.8878 | AUPRC=0.8781
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 149.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6700 | F1=0.7622 | AUROC=0.9169 | AUPRC=0.8389
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6244 | F1=0.8092 | AUROC=0.8952 | AUPRC=0.8950
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4319 | F1=0.7064 | AUROC=0.7827 | AUPRC=0.7814
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6167 | F1=0.7944 | AUROC=0.8827 | AUPRC=0.8656
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 206.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6602 | F1=0.7554 | AUROC=0.9125 | AUPRC=0.8284
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5903 | F1=0.7937 | AUROC=0.8864 | AUPRC=0.8891
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4149 | F1=0.7076 | AUROC=0.7849 | AUPRC=0.7825
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.6040 | F1=0.7871 | AUROC=0.8806 | AUPRC=0.8684
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 67.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6756 | F1=0.7661 | AUROC=0.9154 | AUPRC=0.8424
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6244 | F1=0.8092 | AUROC=0.8935 | AUPRC=0.8968
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4449 | F1=0.7193 | AUROC=0.7830 | AUPRC=0.7773
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.6067 | F1=0.7885 | AUROC=0.8823 | AUPRC=0.8721
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 76.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6769 | F1=0.7670 | AUROC=0.9113 | AUPRC=0.8350
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6216 | F1=0.8097 | AUROC=0.8834 | AUPRC=0.8902
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4299 | F1=0.7117 | AUROC=0.7778 | AUPRC=0.7773
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.3712 | val_loss=0.2058 | val_mcc=0.7508 | val_f1=0.7994 | val_auroc=0.9619

[Epoch 02] train_loss=0.2650 | val_loss=0.1868 | val_mcc=0.7753 | val_f1=0.8191 | val_auroc=0.9673

[Epoch 03] train_loss=0.2405 | val_loss=0.2162 | val_mcc=0.7619 | val_f1=0.8069 | val_auroc=0.9689

[Epoch 04] train_loss=0.2245 | val_loss=0.2077 | val_mcc=0.7647 | val_f1=0.8094 | val_auroc=0.9689

[Epoch 05] train_loss=0.2155 | val_loss=0.2189 | val_mcc=0.7568 | val_f1=0.8029 | val_auroc=0.9666

[Epoch 06] train_loss=0.2005 | val_loss=0.2185 | val_mcc=0.7547 | val_f1=0.8020 | val_auroc=0.9641

[Epoch 07] train_loss=0.1790 | val_loss=0.2002 | val_mcc=0.7721 | val_f1=0.8163 | val_auroc=0.9670

[Epoch 08] train_loss=0.1683 | val_loss=0.2159 | val_mcc=0.7595 | val_f1=0.8060 | val_auroc=0.9654
[EarlyStop] epoch=8 | best_val_mcc=0.7753
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7715 | F1=0.8349 | AUROC=0.9612 | AUPRC=0.9174
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7918 | F1=0.8892 | AUROC=0.9674 | AUPRC=0.9672
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4700 | F1=0.7420 | AUROC=0.7836 | AUPRC=0.7705
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5754 | F1=0.7842 | AUROC=0.9007 | AUPRC=0.8925
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3828 | val_loss=0.2200 | val_mcc=0.7390 | val_f1=0.7901 | val_auroc=0.9588

[Epoch 02] train_loss=0.2758 | val_loss=0.2122 | val_mcc=0.7543 | val_f1=0.8015 | val_auroc=0.9674

[Epoch 03] train_loss=0.2516 | val_loss=0.1983 | val_mcc=0.7657 | val_f1=0.8114 | val_auroc=0.9668

[Epoch 04] train_loss=0.2370 | val_loss=0.1873 | val_mcc=0.7729 | val_f1=0.8171 | val_auroc=0.9665

[Epoch 05] train_loss=0.2262 | val_loss=0.1941 | val_mcc=0.7738 | val_f1=0.8179 | val_auroc=0.9641

[Epoch 06] train_loss=0.2104 | val_loss=0.2026 | val_mcc=0.7687 | val_f1=0.8138 | val_auroc=0.9664

[Epoch 07] train_loss=0.2016 | val_loss=0.2186 | val_mcc=0.7524 | val_f1=0.8002 | val_auroc=0.9633

[Epoch 08] train_loss=0.1847 | val_loss=0.2399 | val_mcc=0.7477 | val_f1=0.7951 | val_auroc=0.9654

[Epoch 09] train_loss=0.1745 | val_loss=0.2077 | val_mcc=0.7705 | val_f1=0.8153 | val_auroc=0.9646

[Epoch 10] train_loss=0.1498 | val_loss=0.2470 | val_mcc=0.7443 | val_f1=0.7938 | val_auroc=0.9603

[Epoch 11] train_loss=0.1406 | val_loss=0.2314 | val_mcc=0.7551 | val_f1=0.8029 | val_auroc=0.9612
[EarlyStop] epoch=11 | best_val_mcc=0.7738
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7723 | F1=0.8350 | AUROC=0.9584 | AUPRC=0.9134
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7781 | F1=0.8812 | AUROC=0.9685 | AUPRC=0.9682
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4378 | F1=0.7232 | AUROC=0.7823 | AUPRC=0.7796
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5943 | F1=0.7926 | AUROC=0.8988 | AUPRC=0.8852
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3724 | val_loss=0.2141 | val_mcc=0.7496 | val_f1=0.7986 | val_auroc=0.9615

[Epoch 02] train_loss=0.2679 | val_loss=0.2037 | val_mcc=0.7640 | val_f1=0.8100 | val_auroc=0.9648

[Epoch 03] train_loss=0.2472 | val_loss=0.1922 | val_mcc=0.7780 | val_f1=0.8213 | val_auroc=0.9674

[Epoch 04] train_loss=0.2302 | val_loss=0.2201 | val_mcc=0.7585 | val_f1=0.8041 | val_auroc=0.9668

[Epoch 05] train_loss=0.2176 | val_loss=0.2272 | val_mcc=0.7519 | val_f1=0.7990 | val_auroc=0.9658

[Epoch 06] train_loss=0.2037 | val_loss=0.1917 | val_mcc=0.7787 | val_f1=0.8214 | val_auroc=0.9637

[Epoch 07] train_loss=0.1918 | val_loss=0.2056 | val_mcc=0.7697 | val_f1=0.8145 | val_auroc=0.9657

[Epoch 08] train_loss=0.1759 | val_loss=0.2205 | val_mcc=0.7566 | val_f1=0.8037 | val_auroc=0.9632

[Epoch 09] train_loss=0.1665 | val_loss=0.2293 | val_mcc=0.7532 | val_f1=0.8015 | val_auroc=0.9589

[Epoch 10] train_loss=0.1554 | val_loss=0.2742 | val_mcc=0.7241 | val_f1=0.7762 | val_auroc=0.9594

[Epoch 11] train_loss=0.1263 | val_loss=0.2531 | val_mcc=0.7459 | val_f1=0.7956 | val_auroc=0.9590

[Epoch 12] train_loss=0.1192 | val_loss=0.2492 | val_mcc=0.7560 | val_f1=0.8037 | val_auroc=0.9573
[EarlyStop] epoch=12 | best_val_mcc=0.7787
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7831 | F1=0.8424 | AUROC=0.9572 | AUPRC=0.9114
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8029 | F1=0.8955 | AUROC=0.9696 | AUPRC=0.9700
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4779 | F1=0.7395 | AUROC=0.7896 | AUPRC=0.7774
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6218 | F1=0.8056 | AUROC=0.9009 | AUPRC=0.8851
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3755 | val_loss=0.2004 | val_mcc=0.7674 | val_f1=0.8128 | val_auroc=0.9655

[Epoch 02] train_loss=0.2642 | val_loss=0.1825 | val_mcc=0.7761 | val_f1=0.8194 | val_auroc=0.9676

[Epoch 03] train_loss=0.2425 | val_loss=0.2107 | val_mcc=0.7649 | val_f1=0.8094 | val_auroc=0.9682

[Epoch 04] train_loss=0.2251 | val_loss=0.1950 | val_mcc=0.7778 | val_f1=0.8209 | val_auroc=0.9682

[Epoch 05] train_loss=0.2087 | val_loss=0.2072 | val_mcc=0.7676 | val_f1=0.8121 | val_auroc=0.9676

[Epoch 06] train_loss=0.1949 | val_loss=0.2014 | val_mcc=0.7682 | val_f1=0.8130 | val_auroc=0.9690

[Epoch 07] train_loss=0.1819 | val_loss=0.2430 | val_mcc=0.7415 | val_f1=0.7901 | val_auroc=0.9626

[Epoch 08] train_loss=0.1667 | val_loss=0.2100 | val_mcc=0.7671 | val_f1=0.8124 | val_auroc=0.9659

[Epoch 09] train_loss=0.1462 | val_loss=0.2187 | val_mcc=0.7692 | val_f1=0.8139 | val_auroc=0.9651

[Epoch 10] train_loss=0.1332 | val_loss=0.2260 | val_mcc=0.7661 | val_f1=0.8113 | val_auroc=0.9657
[EarlyStop] epoch=10 | best_val_mcc=0.7778
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7853 | F1=0.8452 | AUROC=0.9638 | AUPRC=0.9224
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8042 | F1=0.8990 | AUROC=0.9727 | AUPRC=0.9723
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4183 | F1=0.7234 | AUROC=0.7875 | AUPRC=0.7808
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5878 | F1=0.7900 | AUROC=0.9065 | AUPRC=0.8961
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 212.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7976 | F1=0.8540 | AUROC=0.9692 | AUPRC=0.9289
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8553 | F1=0.9255 | AUROC=0.9829 | AUPRC=0.9823
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4250 | F1=0.7299 | AUROC=0.7858 | AUPRC=0.7717
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5788 | F1=0.7854 | AUROC=0.9131 | AUPRC=0.8940
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 177.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7742 | F1=0.8374 | AUROC=0.9620 | AUPRC=0.9182
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8181 | F1=0.9070 | AUROC=0.9743 | AUPRC=0.9748
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4352 | F1=0.7318 | AUROC=0.7863 | AUPRC=0.7727
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5795 | F1=0.7860 | AUROC=0.9045 | AUPRC=0.8929
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 146.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7846 | F1=0.8447 | AUROC=0.9629 | AUPRC=0.9197
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8182 | F1=0.9067 | AUROC=0.9674 | AUPRC=0.9680
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4331 | F1=0.7297 | AUROC=0.7885 | AUPRC=0.7761
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.6102 | F1=0.8003 | AUROC=0.9074 | AUPRC=0.8935
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 113.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7840 | F1=0.8443 | AUROC=0.9646 | AUPRC=0.9252
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8325 | F1=0.9139 | AUROC=0.9733 | AUPRC=0.9718
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4954 | val_loss=0.3970 | val_mcc=0.5461 | val_f1=0.6379 | val_auroc=0.8738

[Epoch 02] train_loss=0.4352 | val_loss=0.3999 | val_mcc=0.5400 | val_f1=0.6333 | val_auroc=0.8789

[Epoch 03] train_loss=0.4142 | val_loss=0.4274 | val_mcc=0.5450 | val_f1=0.6354 | val_auroc=0.8882

[Epoch 04] train_loss=0.3966 | val_loss=0.3681 | val_mcc=0.5768 | val_f1=0.6620 | val_auroc=0.8921

[Epoch 05] train_loss=0.3763 | val_loss=0.3947 | val_mcc=0.5549 | val_f1=0.6446 | val_auroc=0.8883

[Epoch 06] train_loss=0.3577 | val_loss=0.3811 | val_mcc=0.5665 | val_f1=0.6539 | val_auroc=0.8880

[Epoch 07] train_loss=0.3361 | val_loss=0.4012 | val_mcc=0.5544 | val_f1=0.6441 | val_auroc=0.8874

[Epoch 08] train_loss=0.3215 | val_loss=0.4117 | val_mcc=0.5511 | val_f1=0.6413 | val_auroc=0.8872

[Epoch 09] train_loss=0.2909 | val_loss=0.4252 | val_mcc=0.5523 | val_f1=0.6424 | val_auroc=0.8873

[Epoch 10] train_loss=0.2807 | val_loss=0.3994 | val_mcc=0.5675 | val_f1=0.6547 | val_auroc=0.8869
[EarlyStop] epoch=10 | best_val_mcc=0.5768
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6467 | F1=0.7459 | AUROC=0.9101 | AUPRC=0.8345
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5932 | F1=0.7925 | AUROC=0.8893 | AUPRC=0.8956
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4284 | F1=0.7133 | AUROC=0.7719 | AUPRC=0.7638
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6123 | F1=0.7883 | AUROC=0.8840 | AUPRC=0.8761
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5026 | val_loss=0.4257 | val_mcc=0.5256 | val_f1=0.6219 | val_auroc=0.8687

[Epoch 02] train_loss=0.4445 | val_loss=0.4475 | val_mcc=0.5234 | val_f1=0.6186 | val_auroc=0.8790

[Epoch 03] train_loss=0.4221 | val_loss=0.3942 | val_mcc=0.5658 | val_f1=0.6534 | val_auroc=0.8894

[Epoch 04] train_loss=0.4031 | val_loss=0.4139 | val_mcc=0.5533 | val_f1=0.6427 | val_auroc=0.8906

[Epoch 05] train_loss=0.3873 | val_loss=0.3509 | val_mcc=0.5830 | val_f1=0.6658 | val_auroc=0.8902

[Epoch 06] train_loss=0.3677 | val_loss=0.3592 | val_mcc=0.5756 | val_f1=0.6604 | val_auroc=0.8900

[Epoch 07] train_loss=0.3529 | val_loss=0.3948 | val_mcc=0.5525 | val_f1=0.6430 | val_auroc=0.8868

[Epoch 08] train_loss=0.3341 | val_loss=0.3723 | val_mcc=0.5631 | val_f1=0.6501 | val_auroc=0.8831

[Epoch 09] train_loss=0.3174 | val_loss=0.4420 | val_mcc=0.5456 | val_f1=0.6374 | val_auroc=0.8802

[Epoch 10] train_loss=0.2818 | val_loss=0.4094 | val_mcc=0.5665 | val_f1=0.6535 | val_auroc=0.8840

[Epoch 11] train_loss=0.2675 | val_loss=0.4610 | val_mcc=0.5453 | val_f1=0.6374 | val_auroc=0.8785
[EarlyStop] epoch=11 | best_val_mcc=0.5830
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6534 | F1=0.7479 | AUROC=0.9075 | AUPRC=0.8301
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6177 | F1=0.7976 | AUROC=0.8869 | AUPRC=0.8901
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4290 | F1=0.7044 | AUROC=0.7724 | AUPRC=0.7691
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6050 | F1=0.7821 | AUROC=0.8862 | AUPRC=0.8760
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4956 | val_loss=0.3958 | val_mcc=0.5302 | val_f1=0.6255 | val_auroc=0.8713

[Epoch 02] train_loss=0.4419 | val_loss=0.3815 | val_mcc=0.5560 | val_f1=0.6457 | val_auroc=0.8852

[Epoch 03] train_loss=0.4159 | val_loss=0.3937 | val_mcc=0.5545 | val_f1=0.6445 | val_auroc=0.8902

[Epoch 04] train_loss=0.3981 | val_loss=0.3590 | val_mcc=0.5846 | val_f1=0.6678 | val_auroc=0.8908

[Epoch 05] train_loss=0.3814 | val_loss=0.3444 | val_mcc=0.5794 | val_f1=0.6628 | val_auroc=0.8906

[Epoch 06] train_loss=0.3600 | val_loss=0.3725 | val_mcc=0.5644 | val_f1=0.6523 | val_auroc=0.8899

[Epoch 07] train_loss=0.3422 | val_loss=0.3917 | val_mcc=0.5428 | val_f1=0.6354 | val_auroc=0.8841

[Epoch 08] train_loss=0.3252 | val_loss=0.3513 | val_mcc=0.5904 | val_f1=0.6682 | val_auroc=0.8871

[Epoch 09] train_loss=0.3129 | val_loss=0.3634 | val_mcc=0.5684 | val_f1=0.6517 | val_auroc=0.8839

[Epoch 10] train_loss=0.2923 | val_loss=0.4896 | val_mcc=0.5349 | val_f1=0.6275 | val_auroc=0.8837

[Epoch 11] train_loss=0.2739 | val_loss=0.4780 | val_mcc=0.5196 | val_f1=0.6167 | val_auroc=0.8760

[Epoch 12] train_loss=0.2594 | val_loss=0.4646 | val_mcc=0.5543 | val_f1=0.6444 | val_auroc=0.8774

[Epoch 13] train_loss=0.2254 | val_loss=0.4955 | val_mcc=0.5469 | val_f1=0.6386 | val_auroc=0.8795

[Epoch 14] train_loss=0.2016 | val_loss=0.5490 | val_mcc=0.5170 | val_f1=0.6151 | val_auroc=0.8705
[EarlyStop] epoch=14 | best_val_mcc=0.5904
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6557 | F1=0.7433 | AUROC=0.9009 | AUPRC=0.8230
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5868 | F1=0.7673 | AUROC=0.8801 | AUPRC=0.8846
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4075 | F1=0.6801 | AUROC=0.7601 | AUPRC=0.7619
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6068 | F1=0.7738 | AUROC=0.8772 | AUPRC=0.8695
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5021 | val_loss=0.3772 | val_mcc=0.5449 | val_f1=0.6351 | val_auroc=0.8703

[Epoch 02] train_loss=0.4396 | val_loss=0.3925 | val_mcc=0.5520 | val_f1=0.6426 | val_auroc=0.8790

[Epoch 03] train_loss=0.4129 | val_loss=0.3711 | val_mcc=0.5632 | val_f1=0.6512 | val_auroc=0.8844

[Epoch 04] train_loss=0.3894 | val_loss=0.3722 | val_mcc=0.5690 | val_f1=0.6558 | val_auroc=0.8860

[Epoch 05] train_loss=0.3731 | val_loss=0.3747 | val_mcc=0.5688 | val_f1=0.6557 | val_auroc=0.8927

[Epoch 06] train_loss=0.3500 | val_loss=0.3608 | val_mcc=0.5676 | val_f1=0.6546 | val_auroc=0.8902

[Epoch 07] train_loss=0.3316 | val_loss=0.3639 | val_mcc=0.5559 | val_f1=0.6446 | val_auroc=0.8813

[Epoch 08] train_loss=0.3121 | val_loss=0.4040 | val_mcc=0.5457 | val_f1=0.6376 | val_auroc=0.8837

[Epoch 09] train_loss=0.2829 | val_loss=0.3988 | val_mcc=0.5605 | val_f1=0.6492 | val_auroc=0.8862

[Epoch 10] train_loss=0.2619 | val_loss=0.4097 | val_mcc=0.5496 | val_f1=0.6408 | val_auroc=0.8849
[EarlyStop] epoch=10 | best_val_mcc=0.5690
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6415 | F1=0.7422 | AUROC=0.9039 | AUPRC=0.8298
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5847 | F1=0.7878 | AUROC=0.8847 | AUPRC=0.8901
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4194 | F1=0.7062 | AUROC=0.7682 | AUPRC=0.7649
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5821 | F1=0.7753 | AUROC=0.8722 | AUPRC=0.8663
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 408.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6374 | F1=0.7399 | AUROC=0.9034 | AUPRC=0.8244
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6017 | F1=0.7983 | AUROC=0.8807 | AUPRC=0.8834
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3985 | F1=0.7014 | AUROC=0.7679 | AUPRC=0.7538
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5998 | F1=0.7866 | AUROC=0.8772 | AUPRC=0.8658
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 271.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6309 | F1=0.7360 | AUROC=0.9044 | AUPRC=0.8222
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6017 | F1=0.7977 | AUROC=0.8825 | AUPRC=0.8851
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3899 | F1=0.7010 | AUROC=0.7682 | AUPRC=0.7656
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5839 | F1=0.7789 | AUROC=0.8724 | AUPRC=0.8667
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 105.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6332 | F1=0.7372 | AUROC=0.9065 | AUPRC=0.8256
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5762 | F1=0.7825 | AUROC=0.8796 | AUPRC=0.8860
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4360 | F1=0.7202 | AUROC=0.7715 | AUPRC=0.7670
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5852 | F1=0.7795 | AUROC=0.8746 | AUPRC=0.8639
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 88.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6336 | F1=0.7375 | AUROC=0.9031 | AUPRC=0.8268
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6074 | F1=0.8006 | AUROC=0.8778 | AUPRC=0.8891
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4254 | F1=0.7140 | AUROC=0.7638 | AUPRC=0.7536
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.3888 | val_loss=0.2260 | val_mcc=0.7406 | val_f1=0.7909 | val_auroc=0.9617

[Epoch 02] train_loss=0.2742 | val_loss=0.2127 | val_mcc=0.7568 | val_f1=0.8028 | val_auroc=0.9675

[Epoch 03] train_loss=0.2513 | val_loss=0.1822 | val_mcc=0.7771 | val_f1=0.8205 | val_auroc=0.9691

[Epoch 04] train_loss=0.2373 | val_loss=0.2091 | val_mcc=0.7648 | val_f1=0.8097 | val_auroc=0.9677

[Epoch 05] train_loss=0.2215 | val_loss=0.2034 | val_mcc=0.7611 | val_f1=0.8073 | val_auroc=0.9673

[Epoch 06] train_loss=0.2084 | val_loss=0.1929 | val_mcc=0.7650 | val_f1=0.8109 | val_auroc=0.9670

[Epoch 07] train_loss=0.1975 | val_loss=0.2118 | val_mcc=0.7586 | val_f1=0.8050 | val_auroc=0.9669

[Epoch 08] train_loss=0.1745 | val_loss=0.2119 | val_mcc=0.7639 | val_f1=0.8091 | val_auroc=0.9678

[Epoch 09] train_loss=0.1629 | val_loss=0.2128 | val_mcc=0.7616 | val_f1=0.8077 | val_auroc=0.9663
[EarlyStop] epoch=9 | best_val_mcc=0.7771
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7814 | F1=0.8417 | AUROC=0.9635 | AUPRC=0.9205
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8027 | F1=0.8919 | AUROC=0.9722 | AUPRC=0.9720
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4252 | F1=0.7213 | AUROC=0.7871 | AUPRC=0.7735
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5894 | F1=0.7906 | AUROC=0.9015 | AUPRC=0.8906
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3958 | val_loss=0.2139 | val_mcc=0.7446 | val_f1=0.7946 | val_auroc=0.9618

[Epoch 02] train_loss=0.2899 | val_loss=0.2273 | val_mcc=0.7444 | val_f1=0.7921 | val_auroc=0.9668

[Epoch 03] train_loss=0.2646 | val_loss=0.1944 | val_mcc=0.7715 | val_f1=0.8160 | val_auroc=0.9678

[Epoch 04] train_loss=0.2500 | val_loss=0.2359 | val_mcc=0.7379 | val_f1=0.7869 | val_auroc=0.9643

[Epoch 05] train_loss=0.2367 | val_loss=0.1805 | val_mcc=0.7736 | val_f1=0.8170 | val_auroc=0.9677

[Epoch 06] train_loss=0.2235 | val_loss=0.1984 | val_mcc=0.7609 | val_f1=0.8076 | val_auroc=0.9654

[Epoch 07] train_loss=0.2102 | val_loss=0.2278 | val_mcc=0.7472 | val_f1=0.7955 | val_auroc=0.9645

[Epoch 08] train_loss=0.1974 | val_loss=0.1928 | val_mcc=0.7702 | val_f1=0.8150 | val_auroc=0.9663

[Epoch 09] train_loss=0.1842 | val_loss=0.2336 | val_mcc=0.7399 | val_f1=0.7900 | val_auroc=0.9612

[Epoch 10] train_loss=0.1607 | val_loss=0.2489 | val_mcc=0.7354 | val_f1=0.7864 | val_auroc=0.9611

[Epoch 11] train_loss=0.1477 | val_loss=0.2228 | val_mcc=0.7471 | val_f1=0.7962 | val_auroc=0.9601
[EarlyStop] epoch=11 | best_val_mcc=0.7736
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7982 | F1=0.8532 | AUROC=0.9636 | AUPRC=0.9206
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8288 | F1=0.9055 | AUROC=0.9739 | AUPRC=0.9735
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4645 | F1=0.7338 | AUROC=0.7884 | AUPRC=0.7771
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6148 | F1=0.8019 | AUROC=0.9008 | AUPRC=0.8888
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3810 | val_loss=0.2116 | val_mcc=0.7405 | val_f1=0.7910 | val_auroc=0.9594

[Epoch 02] train_loss=0.2823 | val_loss=0.1957 | val_mcc=0.7641 | val_f1=0.8101 | val_auroc=0.9672

[Epoch 03] train_loss=0.2592 | val_loss=0.2169 | val_mcc=0.7481 | val_f1=0.7960 | val_auroc=0.9664

[Epoch 04] train_loss=0.2401 | val_loss=0.2153 | val_mcc=0.7475 | val_f1=0.7954 | val_auroc=0.9655

[Epoch 05] train_loss=0.2331 | val_loss=0.1995 | val_mcc=0.7551 | val_f1=0.8030 | val_auroc=0.9637

[Epoch 06] train_loss=0.2150 | val_loss=0.2045 | val_mcc=0.7656 | val_f1=0.8110 | val_auroc=0.9667

[Epoch 07] train_loss=0.2000 | val_loss=0.2002 | val_mcc=0.7592 | val_f1=0.8043 | val_auroc=0.9630

[Epoch 08] train_loss=0.1910 | val_loss=0.2157 | val_mcc=0.7525 | val_f1=0.8007 | val_auroc=0.9630

[Epoch 09] train_loss=0.1764 | val_loss=0.2178 | val_mcc=0.7512 | val_f1=0.7998 | val_auroc=0.9621

[Epoch 10] train_loss=0.1669 | val_loss=0.2108 | val_mcc=0.7479 | val_f1=0.7969 | val_auroc=0.9609

[Epoch 11] train_loss=0.1423 | val_loss=0.2438 | val_mcc=0.7421 | val_f1=0.7924 | val_auroc=0.9610

[Epoch 12] train_loss=0.1257 | val_loss=0.2543 | val_mcc=0.7334 | val_f1=0.7856 | val_auroc=0.9564
[EarlyStop] epoch=12 | best_val_mcc=0.7656
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7704 | F1=0.8347 | AUROC=0.9613 | AUPRC=0.9155
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8053 | F1=0.8975 | AUROC=0.9708 | AUPRC=0.9700
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4396 | F1=0.7337 | AUROC=0.7887 | AUPRC=0.7805
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5810 | F1=0.7869 | AUROC=0.9027 | AUPRC=0.8909
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3868 | val_loss=0.2232 | val_mcc=0.7416 | val_f1=0.7919 | val_auroc=0.9613

[Epoch 02] train_loss=0.2761 | val_loss=0.2166 | val_mcc=0.7472 | val_f1=0.7959 | val_auroc=0.9646

[Epoch 03] train_loss=0.2509 | val_loss=0.1907 | val_mcc=0.7699 | val_f1=0.8148 | val_auroc=0.9665

[Epoch 04] train_loss=0.2349 | val_loss=0.2225 | val_mcc=0.7445 | val_f1=0.7921 | val_auroc=0.9671

[Epoch 05] train_loss=0.2210 | val_loss=0.2029 | val_mcc=0.7554 | val_f1=0.8024 | val_auroc=0.9683

[Epoch 06] train_loss=0.2071 | val_loss=0.2217 | val_mcc=0.7489 | val_f1=0.7968 | val_auroc=0.9664

[Epoch 07] train_loss=0.1871 | val_loss=0.2136 | val_mcc=0.7535 | val_f1=0.8013 | val_auroc=0.9646

[Epoch 08] train_loss=0.1686 | val_loss=0.2185 | val_mcc=0.7598 | val_f1=0.8058 | val_auroc=0.9668

[Epoch 09] train_loss=0.1580 | val_loss=0.2170 | val_mcc=0.7540 | val_f1=0.8018 | val_auroc=0.9659
[EarlyStop] epoch=9 | best_val_mcc=0.7699
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7826 | F1=0.8429 | AUROC=0.9620 | AUPRC=0.9169
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8142 | F1=0.8980 | AUROC=0.9737 | AUPRC=0.9735
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4163 | F1=0.7174 | AUROC=0.7750 | AUPRC=0.7636
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5843 | F1=0.7883 | AUROC=0.8964 | AUPRC=0.8828
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 189.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7907 | F1=0.8491 | AUROC=0.9676 | AUPRC=0.9292
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8496 | F1=0.9226 | AUROC=0.9838 | AUPRC=0.9843
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4191 | F1=0.7293 | AUROC=0.7839 | AUPRC=0.7723
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5522 | F1=0.7736 | AUROC=0.9047 | AUPRC=0.8851
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 146.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7699 | F1=0.8343 | AUROC=0.9614 | AUPRC=0.9149
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8185 | F1=0.9062 | AUROC=0.9717 | AUPRC=0.9690
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4113 | F1=0.7212 | AUROC=0.7761 | AUPRC=0.7555
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5735 | F1=0.7833 | AUROC=0.9032 | AUPRC=0.8883
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 152.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7803 | F1=0.8417 | AUROC=0.9640 | AUPRC=0.9218
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8352 | F1=0.9157 | AUROC=0.9747 | AUPRC=0.9747
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4143 | F1=0.7249 | AUROC=0.7774 | AUPRC=0.7641
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5948 | F1=0.7931 | AUROC=0.9013 | AUPRC=0.8848
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 175.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7814 | F1=0.8425 | AUROC=0.9644 | AUPRC=0.9204
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8219 | F1=0.9069 | AUROC=0.9734 | AUPRC=0.9733
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4753 | val_loss=0.3860 | val_mcc=0.5630 | val_f1=0.6512 | val_auroc=0.8788

[Epoch 02] train_loss=0.4087 | val_loss=0.3496 | val_mcc=0.5921 | val_f1=0.6735 | val_auroc=0.8906

[Epoch 03] train_loss=0.3814 | val_loss=0.3862 | val_mcc=0.5728 | val_f1=0.6585 | val_auroc=0.8923

[Epoch 04] train_loss=0.3596 | val_loss=0.3828 | val_mcc=0.5779 | val_f1=0.6623 | val_auroc=0.8943

[Epoch 05] train_loss=0.3405 | val_loss=0.3881 | val_mcc=0.5745 | val_f1=0.6595 | val_auroc=0.8964

[Epoch 06] train_loss=0.3225 | val_loss=0.3680 | val_mcc=0.5830 | val_f1=0.6668 | val_auroc=0.8958

[Epoch 07] train_loss=0.2881 | val_loss=0.3625 | val_mcc=0.5901 | val_f1=0.6724 | val_auroc=0.8980

[Epoch 08] train_loss=0.2735 | val_loss=0.3693 | val_mcc=0.5908 | val_f1=0.6729 | val_auroc=0.8936
[EarlyStop] epoch=8 | best_val_mcc=0.5921
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6310 | F1=0.7296 | AUROC=0.8937 | AUPRC=0.8023
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6318 | F1=0.8054 | AUROC=0.8830 | AUPRC=0.8772
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4478 | F1=0.7097 | AUROC=0.7737 | AUPRC=0.7649
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5596 | F1=0.7470 | AUROC=0.8471 | AUPRC=0.8367
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4767 | val_loss=0.3778 | val_mcc=0.5656 | val_f1=0.6528 | val_auroc=0.8820

[Epoch 02] train_loss=0.4161 | val_loss=0.4601 | val_mcc=0.5443 | val_f1=0.6335 | val_auroc=0.8891

[Epoch 03] train_loss=0.3908 | val_loss=0.3674 | val_mcc=0.5872 | val_f1=0.6701 | val_auroc=0.8933

[Epoch 04] train_loss=0.3713 | val_loss=0.3839 | val_mcc=0.5780 | val_f1=0.6623 | val_auroc=0.8925

[Epoch 05] train_loss=0.3524 | val_loss=0.3284 | val_mcc=0.6141 | val_f1=0.6893 | val_auroc=0.8963

[Epoch 06] train_loss=0.3324 | val_loss=0.3519 | val_mcc=0.6080 | val_f1=0.6858 | val_auroc=0.8951

[Epoch 07] train_loss=0.3115 | val_loss=0.4282 | val_mcc=0.5756 | val_f1=0.6604 | val_auroc=0.8944

[Epoch 08] train_loss=0.2926 | val_loss=0.4897 | val_mcc=0.5543 | val_f1=0.6420 | val_auroc=0.8867

[Epoch 09] train_loss=0.2743 | val_loss=0.4280 | val_mcc=0.5807 | val_f1=0.6649 | val_auroc=0.8883

[Epoch 10] train_loss=0.2407 | val_loss=0.4423 | val_mcc=0.5702 | val_f1=0.6567 | val_auroc=0.8819

[Epoch 11] train_loss=0.2219 | val_loss=0.5100 | val_mcc=0.5578 | val_f1=0.6464 | val_auroc=0.8825
[EarlyStop] epoch=11 | best_val_mcc=0.6141
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6492 | F1=0.7399 | AUROC=0.8993 | AUPRC=0.8091
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6594 | F1=0.8158 | AUROC=0.8988 | AUPRC=0.8894
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4559 | F1=0.7116 | AUROC=0.7814 | AUPRC=0.7679
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5850 | F1=0.7540 | AUROC=0.8610 | AUPRC=0.8473
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4692 | val_loss=0.3949 | val_mcc=0.5661 | val_f1=0.6536 | val_auroc=0.8836

[Epoch 02] train_loss=0.4124 | val_loss=0.3741 | val_mcc=0.5711 | val_f1=0.6575 | val_auroc=0.8840

[Epoch 03] train_loss=0.3841 | val_loss=0.3484 | val_mcc=0.5945 | val_f1=0.6752 | val_auroc=0.8940

[Epoch 04] train_loss=0.3629 | val_loss=0.3792 | val_mcc=0.5806 | val_f1=0.6648 | val_auroc=0.8960

[Epoch 05] train_loss=0.3379 | val_loss=0.3726 | val_mcc=0.5869 | val_f1=0.6697 | val_auroc=0.8985

[Epoch 06] train_loss=0.3203 | val_loss=0.4632 | val_mcc=0.5374 | val_f1=0.6283 | val_auroc=0.8853

[Epoch 07] train_loss=0.3056 | val_loss=0.3904 | val_mcc=0.5927 | val_f1=0.6743 | val_auroc=0.8944

[Epoch 08] train_loss=0.2663 | val_loss=0.4116 | val_mcc=0.5847 | val_f1=0.6681 | val_auroc=0.8935

[Epoch 09] train_loss=0.2505 | val_loss=0.3903 | val_mcc=0.6011 | val_f1=0.6807 | val_auroc=0.8920

[Epoch 10] train_loss=0.2345 | val_loss=0.4536 | val_mcc=0.5769 | val_f1=0.6617 | val_auroc=0.8919

[Epoch 11] train_loss=0.2239 | val_loss=0.4457 | val_mcc=0.5841 | val_f1=0.6677 | val_auroc=0.8881

[Epoch 12] train_loss=0.2064 | val_loss=0.5055 | val_mcc=0.5564 | val_f1=0.6452 | val_auroc=0.8841

[Epoch 13] train_loss=0.1937 | val_loss=0.4428 | val_mcc=0.5712 | val_f1=0.6568 | val_auroc=0.8821

[Epoch 14] train_loss=0.1724 | val_loss=0.5130 | val_mcc=0.5648 | val_f1=0.6524 | val_auroc=0.8820

[Epoch 15] train_loss=0.1644 | val_loss=0.5056 | val_mcc=0.5654 | val_f1=0.6530 | val_auroc=0.8783
[EarlyStop] epoch=15 | best_val_mcc=0.6011
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6333 | F1=0.7311 | AUROC=0.8908 | AUPRC=0.7997
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6058 | F1=0.7928 | AUROC=0.8820 | AUPRC=0.8775
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4637 | F1=0.7212 | AUROC=0.7769 | AUPRC=0.7571
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5803 | F1=0.7594 | AUROC=0.8591 | AUPRC=0.8412
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4746 | val_loss=0.3997 | val_mcc=0.5568 | val_f1=0.6464 | val_auroc=0.8819

[Epoch 02] train_loss=0.4086 | val_loss=0.3883 | val_mcc=0.5658 | val_f1=0.6532 | val_auroc=0.8900

[Epoch 03] train_loss=0.3822 | val_loss=0.3625 | val_mcc=0.5852 | val_f1=0.6685 | val_auroc=0.8922

[Epoch 04] train_loss=0.3576 | val_loss=0.3576 | val_mcc=0.5941 | val_f1=0.6755 | val_auroc=0.8965

[Epoch 05] train_loss=0.3350 | val_loss=0.3873 | val_mcc=0.5743 | val_f1=0.6594 | val_auroc=0.8943

[Epoch 06] train_loss=0.3123 | val_loss=0.3658 | val_mcc=0.5913 | val_f1=0.6733 | val_auroc=0.8937

[Epoch 07] train_loss=0.2879 | val_loss=0.3783 | val_mcc=0.5844 | val_f1=0.6679 | val_auroc=0.8924

[Epoch 08] train_loss=0.2699 | val_loss=0.4217 | val_mcc=0.5753 | val_f1=0.6600 | val_auroc=0.8927

[Epoch 09] train_loss=0.2317 | val_loss=0.4294 | val_mcc=0.5668 | val_f1=0.6533 | val_auroc=0.8909

[Epoch 10] train_loss=0.2182 | val_loss=0.4433 | val_mcc=0.5684 | val_f1=0.6549 | val_auroc=0.8895
[EarlyStop] epoch=10 | best_val_mcc=0.5941
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6309 | F1=0.7330 | AUROC=0.8996 | AUPRC=0.8127
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6190 | F1=0.8041 | AUROC=0.8882 | AUPRC=0.8830
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4284 | F1=0.7107 | AUROC=0.7780 | AUPRC=0.7667
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5565 | F1=0.7525 | AUROC=0.8542 | AUPRC=0.8449
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 330.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6301 | F1=0.7330 | AUROC=0.8957 | AUPRC=0.7964
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6446 | F1=0.8175 | AUROC=0.8927 | AUPRC=0.8752
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4389 | F1=0.7171 | AUROC=0.7750 | AUPRC=0.7662
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5583 | F1=0.7568 | AUROC=0.8559 | AUPRC=0.8297
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 187.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6291 | F1=0.7316 | AUROC=0.8941 | AUPRC=0.7999
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6216 | F1=0.8086 | AUROC=0.8838 | AUPRC=0.8639
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4118 | F1=0.7048 | AUROC=0.7685 | AUPRC=0.7628
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5462 | F1=0.7513 | AUROC=0.8478 | AUPRC=0.8334
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 52.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6307 | F1=0.7330 | AUROC=0.8964 | AUPRC=0.8065
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6301 | F1=0.8116 | AUROC=0.8836 | AUPRC=0.8735
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4389 | F1=0.7196 | AUROC=0.7728 | AUPRC=0.7607
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5705 | F1=0.7623 | AUROC=0.8534 | AUPRC=0.8407
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 69.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6263 | F1=0.7297 | AUROC=0.8930 | AUPRC=0.7998
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6304 | F1=0.8099 | AUROC=0.8845 | AUPRC=0.8714
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4299 | F1=0.7104 | AUROC=0.7719 | AUPRC=0.7595
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.3754 | val_loss=0.2069 | val_mcc=0.7541 | val_f1=0.8019 | val_auroc=0.9599

[Epoch 02] train_loss=0.2633 | val_loss=0.1990 | val_mcc=0.7697 | val_f1=0.8143 | val_auroc=0.9677

[Epoch 03] train_loss=0.2354 | val_loss=0.1908 | val_mcc=0.7711 | val_f1=0.8156 | val_auroc=0.9686

[Epoch 04] train_loss=0.2184 | val_loss=0.1934 | val_mcc=0.7711 | val_f1=0.8158 | val_auroc=0.9672

[Epoch 05] train_loss=0.2041 | val_loss=0.2045 | val_mcc=0.7653 | val_f1=0.8103 | val_auroc=0.9684

[Epoch 06] train_loss=0.1885 | val_loss=0.2007 | val_mcc=0.7736 | val_f1=0.8175 | val_auroc=0.9684

[Epoch 07] train_loss=0.1755 | val_loss=0.2018 | val_mcc=0.7650 | val_f1=0.8109 | val_auroc=0.9650

[Epoch 08] train_loss=0.1630 | val_loss=0.2199 | val_mcc=0.7645 | val_f1=0.8100 | val_auroc=0.9647

[Epoch 09] train_loss=0.1493 | val_loss=0.2266 | val_mcc=0.7531 | val_f1=0.8011 | val_auroc=0.9624

[Epoch 10] train_loss=0.1374 | val_loss=0.2411 | val_mcc=0.7477 | val_f1=0.7964 | val_auroc=0.9630

[Epoch 11] train_loss=0.1136 | val_loss=0.2435 | val_mcc=0.7574 | val_f1=0.8042 | val_auroc=0.9637

[Epoch 12] train_loss=0.1046 | val_loss=0.2456 | val_mcc=0.7521 | val_f1=0.8006 | val_auroc=0.9603
[EarlyStop] epoch=12 | best_val_mcc=0.7736
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7800 | F1=0.8414 | AUROC=0.9606 | AUPRC=0.9162
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8240 | F1=0.9094 | AUROC=0.9699 | AUPRC=0.9671
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4469 | F1=0.7367 | AUROC=0.7877 | AUPRC=0.7686
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5849 | F1=0.7885 | AUROC=0.8854 | AUPRC=0.8655
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3827 | val_loss=0.1966 | val_mcc=0.7565 | val_f1=0.8017 | val_auroc=0.9605

[Epoch 02] train_loss=0.2707 | val_loss=0.2143 | val_mcc=0.7536 | val_f1=0.8001 | val_auroc=0.9694

[Epoch 03] train_loss=0.2436 | val_loss=0.1858 | val_mcc=0.7796 | val_f1=0.8226 | val_auroc=0.9671

[Epoch 04] train_loss=0.2294 | val_loss=0.2387 | val_mcc=0.7425 | val_f1=0.7898 | val_auroc=0.9683

[Epoch 05] train_loss=0.2144 | val_loss=0.1926 | val_mcc=0.7716 | val_f1=0.8161 | val_auroc=0.9682

[Epoch 06] train_loss=0.1964 | val_loss=0.2043 | val_mcc=0.7670 | val_f1=0.8125 | val_auroc=0.9649

[Epoch 07] train_loss=0.1877 | val_loss=0.2414 | val_mcc=0.7325 | val_f1=0.7843 | val_auroc=0.9608

[Epoch 08] train_loss=0.1634 | val_loss=0.2169 | val_mcc=0.7590 | val_f1=0.8059 | val_auroc=0.9650

[Epoch 09] train_loss=0.1514 | val_loss=0.2359 | val_mcc=0.7464 | val_f1=0.7955 | val_auroc=0.9631
[EarlyStop] epoch=9 | best_val_mcc=0.7796
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7843 | F1=0.8440 | AUROC=0.9606 | AUPRC=0.9152
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8325 | F1=0.9139 | AUROC=0.9729 | AUPRC=0.9718
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4503 | F1=0.7360 | AUROC=0.7963 | AUPRC=0.7751
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5894 | F1=0.7906 | AUROC=0.8820 | AUPRC=0.8596
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3585 | val_loss=0.2174 | val_mcc=0.7520 | val_f1=0.8000 | val_auroc=0.9653

[Epoch 02] train_loss=0.2577 | val_loss=0.1791 | val_mcc=0.7788 | val_f1=0.8209 | val_auroc=0.9670

[Epoch 03] train_loss=0.2380 | val_loss=0.1849 | val_mcc=0.7846 | val_f1=0.8266 | val_auroc=0.9686

[Epoch 04] train_loss=0.2217 | val_loss=0.1806 | val_mcc=0.7869 | val_f1=0.8284 | val_auroc=0.9700

[Epoch 05] train_loss=0.2026 | val_loss=0.1962 | val_mcc=0.7725 | val_f1=0.8168 | val_auroc=0.9679

[Epoch 06] train_loss=0.1952 | val_loss=0.1869 | val_mcc=0.7819 | val_f1=0.8233 | val_auroc=0.9663

[Epoch 07] train_loss=0.1798 | val_loss=0.2417 | val_mcc=0.7412 | val_f1=0.7895 | val_auroc=0.9648

[Epoch 08] train_loss=0.1642 | val_loss=0.2202 | val_mcc=0.7614 | val_f1=0.8079 | val_auroc=0.9649

[Epoch 09] train_loss=0.1375 | val_loss=0.2272 | val_mcc=0.7661 | val_f1=0.8118 | val_auroc=0.9632

[Epoch 10] train_loss=0.1235 | val_loss=0.2584 | val_mcc=0.7433 | val_f1=0.7925 | val_auroc=0.9630
[EarlyStop] epoch=10 | best_val_mcc=0.7869
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7898 | F1=0.8476 | AUROC=0.9642 | AUPRC=0.9219
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8278 | F1=0.9096 | AUROC=0.9731 | AUPRC=0.9709
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4362 | F1=0.7282 | AUROC=0.7876 | AUPRC=0.7667
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5862 | F1=0.7890 | AUROC=0.8854 | AUPRC=0.8654
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3602 | val_loss=0.2065 | val_mcc=0.7683 | val_f1=0.8134 | val_auroc=0.9663

[Epoch 02] train_loss=0.2555 | val_loss=0.1851 | val_mcc=0.7841 | val_f1=0.8262 | val_auroc=0.9689

[Epoch 03] train_loss=0.2310 | val_loss=0.1946 | val_mcc=0.7775 | val_f1=0.8205 | val_auroc=0.9693

[Epoch 04] train_loss=0.2147 | val_loss=0.2013 | val_mcc=0.7699 | val_f1=0.8139 | val_auroc=0.9698

[Epoch 05] train_loss=0.1993 | val_loss=0.2042 | val_mcc=0.7664 | val_f1=0.8112 | val_auroc=0.9696

[Epoch 06] train_loss=0.1817 | val_loss=0.2055 | val_mcc=0.7626 | val_f1=0.8087 | val_auroc=0.9666

[Epoch 07] train_loss=0.1593 | val_loss=0.2101 | val_mcc=0.7655 | val_f1=0.8107 | val_auroc=0.9671

[Epoch 08] train_loss=0.1466 | val_loss=0.2088 | val_mcc=0.7693 | val_f1=0.8141 | val_auroc=0.9669
[EarlyStop] epoch=8 | best_val_mcc=0.7841
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7801 | F1=0.8413 | AUROC=0.9616 | AUPRC=0.9174
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8387 | F1=0.9161 | AUROC=0.9726 | AUPRC=0.9718
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4497 | F1=0.7345 | AUROC=0.7973 | AUPRC=0.7813
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5862 | F1=0.7890 | AUROC=0.8902 | AUPRC=0.8709
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 184.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7945 | F1=0.8518 | AUROC=0.9694 | AUPRC=0.9325
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8675 | F1=0.9306 | AUROC=0.9864 | AUPRC=0.9853
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4280 | F1=0.7313 | AUROC=0.7853 | AUPRC=0.7606
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5619 | F1=0.7782 | AUROC=0.8981 | AUPRC=0.8648
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 202.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7861 | F1=0.8458 | AUROC=0.9648 | AUPRC=0.9205
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8611 | F1=0.9283 | AUROC=0.9764 | AUPRC=0.9743
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4448 | F1=0.7371 | AUROC=0.7984 | AUPRC=0.7835
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5810 | F1=0.7869 | AUROC=0.8908 | AUPRC=0.8675
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 126.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7879 | F1=0.8471 | AUROC=0.9634 | AUPRC=0.9188
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8265 | F1=0.9117 | AUROC=0.9721 | AUPRC=0.9687
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4526 | F1=0.7388 | AUROC=0.7966 | AUPRC=0.7759
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5757 | F1=0.7845 | AUROC=0.8924 | AUPRC=0.8741
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 135.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7767 | F1=0.8392 | AUROC=0.9624 | AUPRC=0.9162
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8180 | F1=0.9072 | AUROC=0.9720 | AUPRC=0.9695
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.4788 | val_loss=0.3751 | val_mcc=0.6144 | val_f1=0.6897 | val_auroc=0.8835

[Epoch 02] train_loss=0.4152 | val_loss=0.3653 | val_mcc=0.6087 | val_f1=0.6870 | val_auroc=0.8992

[Epoch 03] train_loss=0.3806 | val_loss=0.3178 | val_mcc=0.6222 | val_f1=0.6962 | val_auroc=0.9062

[Epoch 04] train_loss=0.3450 | val_loss=0.3507 | val_mcc=0.5939 | val_f1=0.6752 | val_auroc=0.9039

[Epoch 05] train_loss=0.3073 | val_loss=0.3231 | val_mcc=0.6084 | val_f1=0.6863 | val_auroc=0.9071

[Epoch 06] train_loss=0.2687 | val_loss=0.3499 | val_mcc=0.6007 | val_f1=0.6807 | val_auroc=0.9063

[Epoch 07] train_loss=0.2259 | val_loss=0.3851 | val_mcc=0.5908 | val_f1=0.6729 | val_auroc=0.9003

[Epoch 08] train_loss=0.1752 | val_loss=0.4074 | val_mcc=0.5843 | val_f1=0.6678 | val_auroc=0.8984

[Epoch 09] train_loss=0.1490 | val_loss=0.4253 | val_mcc=0.5853 | val_f1=0.6686 | val_auroc=0.8928
[EarlyStop] epoch=9 | best_val_mcc=0.6222
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6766 | F1=0.7637 | AUROC=0.9123 | AUPRC=0.8460
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6803 | F1=0.8311 | AUROC=0.9080 | AUPRC=0.9118
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4322 | F1=0.7046 | AUROC=0.7829 | AUPRC=0.7865
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6090 | F1=0.7792 | AUROC=0.8849 | AUPRC=0.8767
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4759 | val_loss=0.3671 | val_mcc=0.6155 | val_f1=0.6908 | val_auroc=0.8900

[Epoch 02] train_loss=0.4127 | val_loss=0.3568 | val_mcc=0.6161 | val_f1=0.6928 | val_auroc=0.8997

[Epoch 03] train_loss=0.3767 | val_loss=0.3172 | val_mcc=0.6328 | val_f1=0.7054 | val_auroc=0.9095

[Epoch 04] train_loss=0.3343 | val_loss=0.3796 | val_mcc=0.6039 | val_f1=0.6823 | val_auroc=0.9105

[Epoch 05] train_loss=0.2822 | val_loss=0.3842 | val_mcc=0.5990 | val_f1=0.6790 | val_auroc=0.9055

[Epoch 06] train_loss=0.2329 | val_loss=0.4784 | val_mcc=0.5652 | val_f1=0.6504 | val_auroc=0.9003

[Epoch 07] train_loss=0.1816 | val_loss=0.4884 | val_mcc=0.5800 | val_f1=0.6642 | val_auroc=0.8876

[Epoch 08] train_loss=0.1289 | val_loss=0.6932 | val_mcc=0.5317 | val_f1=0.6228 | val_auroc=0.8856

[Epoch 09] train_loss=0.1078 | val_loss=0.6226 | val_mcc=0.5729 | val_f1=0.6587 | val_auroc=0.8803
[EarlyStop] epoch=9 | best_val_mcc=0.6328
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6840 | F1=0.7703 | AUROC=0.9186 | AUPRC=0.8522
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6964 | F1=0.8419 | AUROC=0.9176 | AUPRC=0.9203
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4571 | F1=0.7224 | AUROC=0.7862 | AUPRC=0.7860
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6116 | F1=0.7835 | AUROC=0.8852 | AUPRC=0.8794
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4718 | val_loss=0.3007 | val_mcc=0.6370 | val_f1=0.6941 | val_auroc=0.8880

[Epoch 02] train_loss=0.4098 | val_loss=0.3483 | val_mcc=0.6195 | val_f1=0.6952 | val_auroc=0.9005

[Epoch 03] train_loss=0.3814 | val_loss=0.3544 | val_mcc=0.6145 | val_f1=0.6914 | val_auroc=0.9056

[Epoch 04] train_loss=0.3395 | val_loss=0.3160 | val_mcc=0.6253 | val_f1=0.6991 | val_auroc=0.9086

[Epoch 05] train_loss=0.2923 | val_loss=0.3595 | val_mcc=0.6022 | val_f1=0.6819 | val_auroc=0.9058

[Epoch 06] train_loss=0.2272 | val_loss=0.3852 | val_mcc=0.6028 | val_f1=0.6822 | val_auroc=0.9024

[Epoch 07] train_loss=0.1917 | val_loss=0.4798 | val_mcc=0.5730 | val_f1=0.6581 | val_auroc=0.8932
[EarlyStop] epoch=7 | best_val_mcc=0.6370
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6695 | F1=0.7399 | AUROC=0.9014 | AUPRC=0.8337
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6054 | F1=0.7619 | AUROC=0.8898 | AUPRC=0.8958
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4403 | F1=0.6678 | AUROC=0.7753 | AUPRC=0.7736
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6072 | F1=0.7515 | AUROC=0.8692 | AUPRC=0.8692
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4833 | val_loss=0.3394 | val_mcc=0.6215 | val_f1=0.6927 | val_auroc=0.8831

[Epoch 02] train_loss=0.4144 | val_loss=0.3215 | val_mcc=0.6295 | val_f1=0.6997 | val_auroc=0.8986

[Epoch 03] train_loss=0.3781 | val_loss=0.3364 | val_mcc=0.6177 | val_f1=0.6940 | val_auroc=0.9047

[Epoch 04] train_loss=0.3431 | val_loss=0.3068 | val_mcc=0.6263 | val_f1=0.6990 | val_auroc=0.9063

[Epoch 05] train_loss=0.3013 | val_loss=0.3651 | val_mcc=0.5970 | val_f1=0.6775 | val_auroc=0.9048

[Epoch 06] train_loss=0.2538 | val_loss=0.3679 | val_mcc=0.5934 | val_f1=0.6749 | val_auroc=0.9003

[Epoch 07] train_loss=0.1971 | val_loss=0.3934 | val_mcc=0.5889 | val_f1=0.6714 | val_auroc=0.8988

[Epoch 08] train_loss=0.1683 | val_loss=0.4389 | val_mcc=0.5723 | val_f1=0.6580 | val_auroc=0.8953
[EarlyStop] epoch=8 | best_val_mcc=0.6295
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6796 | F1=0.7616 | AUROC=0.9088 | AUPRC=0.8444
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6312 | F1=0.8000 | AUROC=0.8940 | AUPRC=0.9020
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4671 | F1=0.7104 | AUROC=0.7773 | AUPRC=0.7733
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6237 | F1=0.7826 | AUROC=0.8768 | AUPRC=0.8744
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 266.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6811 | F1=0.7687 | AUROC=0.9148 | AUPRC=0.8467
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6512 | F1=0.8172 | AUROC=0.8940 | AUPRC=0.9006
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4390 | F1=0.7145 | AUROC=0.7777 | AUPRC=0.7688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5998 | F1=0.7811 | AUROC=0.8765 | AUPRC=0.8641
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 183.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6782 | F1=0.7680 | AUROC=0.9142 | AUPRC=0.8467
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6842 | F1=0.8407 | AUROC=0.9075 | AUPRC=0.9132
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4479 | F1=0.7250 | AUROC=0.7761 | AUPRC=0.7727
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.6019 | F1=0.7843 | AUROC=0.8815 | AUPRC=0.8706
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 124.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6601 | F1=0.7558 | AUROC=0.9088 | AUPRC=0.8410
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6500 | F1=0.8225 | AUROC=0.9042 | AUPRC=0.9080
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4419 | F1=0.7211 | AUROC=0.7809 | AUPRC=0.7779
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5900 | F1=0.7788 | AUROC=0.8732 | AUPRC=0.8696
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 103.
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6480 | F1=0.7469 | AUROC=0.9079 | AUPRC=0.8388
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6416 | F1=0.8169 | AUROC=0.9045 | AUPRC=0.9091
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4404 | F1=0.7202 | AUROC=0.7801 | AUPRC=0.7699
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.3649 | val_loss=0.2023 | val_mcc=0.7616 | val_f1=0.8081 | val_auroc=0.9652

[Epoch 02] train_loss=0.2625 | val_loss=0.2313 | val_mcc=0.7420 | val_f1=0.7888 | val_auroc=0.9690

[Epoch 03] train_loss=0.2349 | val_loss=0.1937 | val_mcc=0.7736 | val_f1=0.8172 | val_auroc=0.9698

[Epoch 04] train_loss=0.2091 | val_loss=0.2149 | val_mcc=0.7514 | val_f1=0.7982 | val_auroc=0.9680

[Epoch 05] train_loss=0.1869 | val_loss=0.2303 | val_mcc=0.7450 | val_f1=0.7934 | val_auroc=0.9648

[Epoch 06] train_loss=0.1544 | val_loss=0.2097 | val_mcc=0.7638 | val_f1=0.8095 | val_auroc=0.9658

[Epoch 07] train_loss=0.1271 | val_loss=0.2226 | val_mcc=0.7589 | val_f1=0.8060 | val_auroc=0.9632

[Epoch 08] train_loss=0.0946 | val_loss=0.2507 | val_mcc=0.7483 | val_f1=0.7962 | val_auroc=0.9647

[Epoch 09] train_loss=0.0787 | val_loss=0.2570 | val_mcc=0.7453 | val_f1=0.7947 | val_auroc=0.9633
[EarlyStop] epoch=9 | best_val_mcc=0.7736
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7821 | F1=0.8430 | AUROC=0.9642 | AUPRC=0.9272
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8444 | F1=0.9190 | AUROC=0.9776 | AUPRC=0.9780
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4360 | F1=0.7354 | AUROC=0.7872 | AUPRC=0.7787
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5633 | F1=0.7788 | AUROC=0.9027 | AUPRC=0.8900
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3735 | val_loss=0.1821 | val_mcc=0.7742 | val_f1=0.8158 | val_auroc=0.9663

[Epoch 02] train_loss=0.2737 | val_loss=0.1738 | val_mcc=0.7791 | val_f1=0.8192 | val_auroc=0.9670

[Epoch 03] train_loss=0.2475 | val_loss=0.2859 | val_mcc=0.6972 | val_f1=0.7476 | val_auroc=0.9694

[Epoch 04] train_loss=0.2146 | val_loss=0.2174 | val_mcc=0.7569 | val_f1=0.8029 | val_auroc=0.9677

[Epoch 05] train_loss=0.1797 | val_loss=0.2289 | val_mcc=0.7505 | val_f1=0.7976 | val_auroc=0.9661

[Epoch 06] train_loss=0.1456 | val_loss=0.3560 | val_mcc=0.6788 | val_f1=0.7332 | val_auroc=0.9606

[Epoch 07] train_loss=0.1033 | val_loss=0.2783 | val_mcc=0.7439 | val_f1=0.7938 | val_auroc=0.9590

[Epoch 08] train_loss=0.0809 | val_loss=0.3220 | val_mcc=0.7249 | val_f1=0.7784 | val_auroc=0.9541
[EarlyStop] epoch=8 | best_val_mcc=0.7791
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7897 | F1=0.8452 | AUROC=0.9621 | AUPRC=0.9219
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8069 | F1=0.8926 | AUROC=0.9740 | AUPRC=0.9741
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4661 | F1=0.7270 | AUROC=0.7914 | AUPRC=0.7825
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6276 | F1=0.8066 | AUROC=0.9074 | AUPRC=0.8941
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3672 | val_loss=0.2164 | val_mcc=0.7563 | val_f1=0.8033 | val_auroc=0.9662

[Epoch 02] train_loss=0.2699 | val_loss=0.1911 | val_mcc=0.7707 | val_f1=0.8154 | val_auroc=0.9662

[Epoch 03] train_loss=0.2401 | val_loss=0.1709 | val_mcc=0.7876 | val_f1=0.8275 | val_auroc=0.9690

[Epoch 04] train_loss=0.2127 | val_loss=0.1870 | val_mcc=0.7747 | val_f1=0.8183 | val_auroc=0.9660

[Epoch 05] train_loss=0.1902 | val_loss=0.2039 | val_mcc=0.7648 | val_f1=0.8105 | val_auroc=0.9666

[Epoch 06] train_loss=0.1512 | val_loss=0.2062 | val_mcc=0.7620 | val_f1=0.8074 | val_auroc=0.9636

[Epoch 07] train_loss=0.1162 | val_loss=0.2451 | val_mcc=0.7513 | val_f1=0.7985 | val_auroc=0.9566

[Epoch 08] train_loss=0.0759 | val_loss=0.3021 | val_mcc=0.7421 | val_f1=0.7926 | val_auroc=0.9558

[Epoch 09] train_loss=0.0587 | val_loss=0.3206 | val_mcc=0.7389 | val_f1=0.7900 | val_auroc=0.9542
[EarlyStop] epoch=9 | best_val_mcc=0.7876
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7892 | F1=0.8454 | AUROC=0.9638 | AUPRC=0.9246
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8133 | F1=0.8954 | AUROC=0.9759 | AUPRC=0.9759
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4554 | F1=0.7265 | AUROC=0.7905 | AUPRC=0.7789
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6198 | F1=0.8035 | AUROC=0.9013 | AUPRC=0.8865
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3694 | val_loss=0.2145 | val_mcc=0.7478 | val_f1=0.7966 | val_auroc=0.9647

[Epoch 02] train_loss=0.2646 | val_loss=0.1935 | val_mcc=0.7713 | val_f1=0.8156 | val_auroc=0.9688

[Epoch 03] train_loss=0.2357 | val_loss=0.1982 | val_mcc=0.7638 | val_f1=0.8090 | val_auroc=0.9692

[Epoch 04] train_loss=0.2106 | val_loss=0.1875 | val_mcc=0.7749 | val_f1=0.8186 | val_auroc=0.9699

[Epoch 05] train_loss=0.1857 | val_loss=0.1971 | val_mcc=0.7700 | val_f1=0.8145 | val_auroc=0.9686

[Epoch 06] train_loss=0.1515 | val_loss=0.2303 | val_mcc=0.7495 | val_f1=0.7971 | val_auroc=0.9661

[Epoch 07] train_loss=0.1193 | val_loss=0.2373 | val_mcc=0.7602 | val_f1=0.8065 | val_auroc=0.9649

[Epoch 08] train_loss=0.0900 | val_loss=0.2409 | val_mcc=0.7506 | val_f1=0.7993 | val_auroc=0.9605

[Epoch 09] train_loss=0.0624 | val_loss=0.2983 | val_mcc=0.7299 | val_f1=0.7812 | val_auroc=0.9608

[Epoch 10] train_loss=0.0513 | val_loss=0.2777 | val_mcc=0.7435 | val_f1=0.7936 | val_auroc=0.9599
[EarlyStop] epoch=10 | best_val_mcc=0.7749
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7714 | F1=0.8353 | AUROC=0.9648 | AUPRC=0.9264
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8251 | F1=0.9080 | AUROC=0.9768 | AUPRC=0.9764
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4305 | F1=0.7295 | AUROC=0.7847 | AUPRC=0.7775
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6012 | F1=0.7962 | AUROC=0.9071 | AUPRC=0.8954
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 165.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7996 | F1=0.8554 | AUROC=0.9691 | AUPRC=0.9331
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8711 | F1=0.9315 | AUROC=0.9838 | AUPRC=0.9844
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4170 | F1=0.7277 | AUROC=0.7831 | AUPRC=0.7652
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5486 | F1=0.7722 | AUROC=0.9046 | AUPRC=0.8884
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 176.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7831 | F1=0.8437 | AUROC=0.9643 | AUPRC=0.9242
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8525 | F1=0.9240 | AUROC=0.9760 | AUPRC=0.9768
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4430 | F1=0.7379 | AUROC=0.7865 | AUPRC=0.7794
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5856 | F1=0.7887 | AUROC=0.9017 | AUPRC=0.8818
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 108.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7775 | F1=0.8397 | AUROC=0.9644 | AUPRC=0.9229
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8504 | F1=0.9217 | AUROC=0.9769 | AUPRC=0.9776
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4201 | F1=0.7273 | AUROC=0.7891 | AUPRC=0.7781
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5920 | F1=0.7919 | AUROC=0.9025 | AUPRC=0.8858
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 133.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7870 | F1=0.8464 | AUROC=0.9643 | AUPRC=0.9247
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8470 | F1=0.9208 | AUROC=0.9766 | AUPRC=0.9767
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.4626 | val_loss=0.3447 | val_mcc=0.6032 | val_f1=0.6825 | val_auroc=0.8951

[Epoch 02] train_loss=0.3921 | val_loss=0.3425 | val_mcc=0.6067 | val_f1=0.6850 | val_auroc=0.8976

[Epoch 03] train_loss=0.3614 | val_loss=0.3493 | val_mcc=0.6077 | val_f1=0.6862 | val_auroc=0.9040

[Epoch 04] train_loss=0.3333 | val_loss=0.3730 | val_mcc=0.5895 | val_f1=0.6711 | val_auroc=0.9030

[Epoch 05] train_loss=0.3028 | val_loss=0.3581 | val_mcc=0.6035 | val_f1=0.6828 | val_auroc=0.9001

[Epoch 06] train_loss=0.2798 | val_loss=0.3756 | val_mcc=0.5894 | val_f1=0.6715 | val_auroc=0.8991

[Epoch 07] train_loss=0.2507 | val_loss=0.4211 | val_mcc=0.5752 | val_f1=0.6594 | val_auroc=0.8950

[Epoch 08] train_loss=0.2085 | val_loss=0.4144 | val_mcc=0.5800 | val_f1=0.6637 | val_auroc=0.8961

[Epoch 09] train_loss=0.1850 | val_loss=0.4312 | val_mcc=0.5763 | val_f1=0.6609 | val_auroc=0.8959
[EarlyStop] epoch=9 | best_val_mcc=0.6077
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6737 | F1=0.7643 | AUROC=0.9124 | AUPRC=0.8351
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6415 | F1=0.8195 | AUROC=0.8901 | AUPRC=0.8953
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4450 | F1=0.7167 | AUROC=0.7791 | AUPRC=0.7695
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6118 | F1=0.7906 | AUROC=0.8793 | AUPRC=0.8720
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4641 | val_loss=0.3929 | val_mcc=0.5795 | val_f1=0.6632 | val_auroc=0.8932

[Epoch 02] train_loss=0.4023 | val_loss=0.3358 | val_mcc=0.6220 | val_f1=0.6971 | val_auroc=0.9022

[Epoch 03] train_loss=0.3752 | val_loss=0.3300 | val_mcc=0.6179 | val_f1=0.6934 | val_auroc=0.9003

[Epoch 04] train_loss=0.3509 | val_loss=0.3275 | val_mcc=0.6142 | val_f1=0.6899 | val_auroc=0.8970

[Epoch 05] train_loss=0.3232 | val_loss=0.3450 | val_mcc=0.6086 | val_f1=0.6860 | val_auroc=0.8937

[Epoch 06] train_loss=0.3038 | val_loss=0.3667 | val_mcc=0.5937 | val_f1=0.6752 | val_auroc=0.8942

[Epoch 07] train_loss=0.2609 | val_loss=0.4091 | val_mcc=0.5864 | val_f1=0.6693 | val_auroc=0.8918

[Epoch 08] train_loss=0.2428 | val_loss=0.5141 | val_mcc=0.5508 | val_f1=0.6366 | val_auroc=0.8930
[EarlyStop] epoch=8 | best_val_mcc=0.6220
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6771 | F1=0.7647 | AUROC=0.9144 | AUPRC=0.8383
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6277 | F1=0.8076 | AUROC=0.8899 | AUPRC=0.8965
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4463 | F1=0.7091 | AUROC=0.7819 | AUPRC=0.7793
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6241 | F1=0.7924 | AUROC=0.8824 | AUPRC=0.8737
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4553 | val_loss=0.3824 | val_mcc=0.5896 | val_f1=0.6715 | val_auroc=0.8945

[Epoch 02] train_loss=0.3913 | val_loss=0.3406 | val_mcc=0.6116 | val_f1=0.6891 | val_auroc=0.8996

[Epoch 03] train_loss=0.3606 | val_loss=0.3454 | val_mcc=0.6084 | val_f1=0.6867 | val_auroc=0.8976

[Epoch 04] train_loss=0.3334 | val_loss=0.3407 | val_mcc=0.6181 | val_f1=0.6944 | val_auroc=0.9033

[Epoch 05] train_loss=0.3052 | val_loss=0.3439 | val_mcc=0.6168 | val_f1=0.6931 | val_auroc=0.9004

[Epoch 06] train_loss=0.2790 | val_loss=0.3545 | val_mcc=0.6172 | val_f1=0.6935 | val_auroc=0.8993

[Epoch 07] train_loss=0.2482 | val_loss=0.4374 | val_mcc=0.5642 | val_f1=0.6504 | val_auroc=0.8919

[Epoch 08] train_loss=0.2248 | val_loss=0.4296 | val_mcc=0.5739 | val_f1=0.6592 | val_auroc=0.8902

[Epoch 09] train_loss=0.1729 | val_loss=0.4711 | val_mcc=0.5762 | val_f1=0.6610 | val_auroc=0.8898

[Epoch 10] train_loss=0.1512 | val_loss=0.5023 | val_mcc=0.5617 | val_f1=0.6493 | val_auroc=0.8867
[EarlyStop] epoch=10 | best_val_mcc=0.6181
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6800 | F1=0.7677 | AUROC=0.9136 | AUPRC=0.8349
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6245 | F1=0.8087 | AUROC=0.8894 | AUPRC=0.8941
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4458 | F1=0.7114 | AUROC=0.7864 | AUPRC=0.7797
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6214 | F1=0.7909 | AUROC=0.8825 | AUPRC=0.8693
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4670 | val_loss=0.3604 | val_mcc=0.5961 | val_f1=0.6771 | val_auroc=0.8980

[Epoch 02] train_loss=0.3893 | val_loss=0.3501 | val_mcc=0.6098 | val_f1=0.6878 | val_auroc=0.9023

[Epoch 03] train_loss=0.3556 | val_loss=0.3412 | val_mcc=0.6078 | val_f1=0.6863 | val_auroc=0.9042

[Epoch 04] train_loss=0.3245 | val_loss=0.3620 | val_mcc=0.6073 | val_f1=0.6857 | val_auroc=0.9023

[Epoch 05] train_loss=0.2926 | val_loss=0.3726 | val_mcc=0.5896 | val_f1=0.6718 | val_auroc=0.8971

[Epoch 06] train_loss=0.2589 | val_loss=0.3810 | val_mcc=0.5879 | val_f1=0.6705 | val_auroc=0.8951

[Epoch 07] train_loss=0.2126 | val_loss=0.4141 | val_mcc=0.5771 | val_f1=0.6613 | val_auroc=0.8967

[Epoch 08] train_loss=0.1919 | val_loss=0.4255 | val_mcc=0.5738 | val_f1=0.6591 | val_auroc=0.8939
[EarlyStop] epoch=8 | best_val_mcc=0.6098
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6720 | F1=0.7629 | AUROC=0.9121 | AUPRC=0.8350
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6189 | F1=0.8047 | AUROC=0.8839 | AUPRC=0.8860
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4166 | F1=0.7015 | AUROC=0.7758 | AUPRC=0.7733
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6098 | F1=0.7878 | AUROC=0.8769 | AUPRC=0.8678
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 314.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6638 | F1=0.7575 | AUROC=0.9133 | AUPRC=0.8354
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6188 | F1=0.8052 | AUROC=0.8941 | AUPRC=0.8970
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4186 | F1=0.6978 | AUROC=0.7733 | AUPRC=0.7664
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5980 | F1=0.7829 | AUROC=0.8754 | AUPRC=0.8638
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 110.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6562 | F1=0.7522 | AUROC=0.9117 | AUPRC=0.8285
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5904 | F1=0.7943 | AUROC=0.8815 | AUPRC=0.8868
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4496 | F1=0.7183 | AUROC=0.7795 | AUPRC=0.7771
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5865 | F1=0.7750 | AUROC=0.8755 | AUPRC=0.8614
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 40.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6802 | F1=0.7688 | AUROC=0.9106 | AUPRC=0.8309
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6415 | F1=0.8174 | AUROC=0.8872 | AUPRC=0.8933
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4151 | F1=0.7000 | AUROC=0.7742 | AUPRC=0.7790
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.6184 | F1=0.7935 | AUROC=0.8803 | AUPRC=0.8644
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 54.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6663 | F1=0.7597 | AUROC=0.9135 | AUPRC=0.8360
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6046 | F1=0.8011 | AUROC=0.8898 | AUPRC=0.8947
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4239 | F1=0.7121 | AUROC=0.7795 | AUPRC=0.7829
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.3764 | val_loss=0.2170 | val_mcc=0.7509 | val_f1=0.7996 | val_auroc=0.9629

[Epoch 02] train_loss=0.2567 | val_loss=0.2117 | val_mcc=0.7615 | val_f1=0.8072 | val_auroc=0.9669

[Epoch 03] train_loss=0.2265 | val_loss=0.2067 | val_mcc=0.7626 | val_f1=0.8085 | val_auroc=0.9667

[Epoch 04] train_loss=0.2022 | val_loss=0.2019 | val_mcc=0.7670 | val_f1=0.8124 | val_auroc=0.9644

[Epoch 05] train_loss=0.1780 | val_loss=0.2255 | val_mcc=0.7504 | val_f1=0.7983 | val_auroc=0.9635

[Epoch 06] train_loss=0.1583 | val_loss=0.2247 | val_mcc=0.7526 | val_f1=0.8008 | val_auroc=0.9626

[Epoch 07] train_loss=0.1364 | val_loss=0.2495 | val_mcc=0.7341 | val_f1=0.7850 | val_auroc=0.9601

[Epoch 08] train_loss=0.1215 | val_loss=0.2529 | val_mcc=0.7378 | val_f1=0.7884 | val_auroc=0.9612

[Epoch 09] train_loss=0.0916 | val_loss=0.2572 | val_mcc=0.7446 | val_f1=0.7941 | val_auroc=0.9599

[Epoch 10] train_loss=0.0807 | val_loss=0.2600 | val_mcc=0.7440 | val_f1=0.7941 | val_auroc=0.9589
[EarlyStop] epoch=10 | best_val_mcc=0.7670
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7718 | F1=0.8355 | AUROC=0.9586 | AUPRC=0.9155
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7983 | F1=0.8964 | AUROC=0.9702 | AUPRC=0.9723
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4351 | F1=0.7284 | AUROC=0.7771 | AUPRC=0.7661
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5858 | F1=0.7891 | AUROC=0.8985 | AUPRC=0.8842
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3683 | val_loss=0.2124 | val_mcc=0.7456 | val_f1=0.7954 | val_auroc=0.9607

[Epoch 02] train_loss=0.2685 | val_loss=0.2183 | val_mcc=0.7468 | val_f1=0.7953 | val_auroc=0.9666

[Epoch 03] train_loss=0.2399 | val_loss=0.2078 | val_mcc=0.7580 | val_f1=0.8047 | val_auroc=0.9647

[Epoch 04] train_loss=0.2202 | val_loss=0.2138 | val_mcc=0.7541 | val_f1=0.8018 | val_auroc=0.9636

[Epoch 05] train_loss=0.1975 | val_loss=0.2111 | val_mcc=0.7522 | val_f1=0.8007 | val_auroc=0.9618

[Epoch 06] train_loss=0.1834 | val_loss=0.2553 | val_mcc=0.7321 | val_f1=0.7823 | val_auroc=0.9623

[Epoch 07] train_loss=0.1564 | val_loss=0.2642 | val_mcc=0.7251 | val_f1=0.7776 | val_auroc=0.9580

[Epoch 08] train_loss=0.1253 | val_loss=0.2714 | val_mcc=0.7286 | val_f1=0.7810 | val_auroc=0.9571

[Epoch 09] train_loss=0.1114 | val_loss=0.2915 | val_mcc=0.7161 | val_f1=0.7709 | val_auroc=0.9553
[EarlyStop] epoch=9 | best_val_mcc=0.7580
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7716 | F1=0.8355 | AUROC=0.9604 | AUPRC=0.9161
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7980 | F1=0.8978 | AUROC=0.9660 | AUPRC=0.9666
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4464 | F1=0.7380 | AUROC=0.7923 | AUPRC=0.7807
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5866 | F1=0.7894 | AUROC=0.9083 | AUPRC=0.8965
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3784 | val_loss=0.2209 | val_mcc=0.7365 | val_f1=0.7881 | val_auroc=0.9582

[Epoch 02] train_loss=0.2646 | val_loss=0.2225 | val_mcc=0.7492 | val_f1=0.7972 | val_auroc=0.9651

[Epoch 03] train_loss=0.2335 | val_loss=0.2092 | val_mcc=0.7500 | val_f1=0.7985 | val_auroc=0.9656

[Epoch 04] train_loss=0.2101 | val_loss=0.2327 | val_mcc=0.7420 | val_f1=0.7920 | val_auroc=0.9601

[Epoch 05] train_loss=0.1893 | val_loss=0.2438 | val_mcc=0.7290 | val_f1=0.7812 | val_auroc=0.9589

[Epoch 06] train_loss=0.1644 | val_loss=0.2224 | val_mcc=0.7511 | val_f1=0.7997 | val_auroc=0.9601

[Epoch 07] train_loss=0.1431 | val_loss=0.2646 | val_mcc=0.7275 | val_f1=0.7804 | val_auroc=0.9571

[Epoch 08] train_loss=0.1231 | val_loss=0.2635 | val_mcc=0.7287 | val_f1=0.7820 | val_auroc=0.9535

[Epoch 09] train_loss=0.1074 | val_loss=0.3055 | val_mcc=0.7206 | val_f1=0.7744 | val_auroc=0.9530

[Epoch 10] train_loss=0.0893 | val_loss=0.2976 | val_mcc=0.7346 | val_f1=0.7863 | val_auroc=0.9542

[Epoch 11] train_loss=0.0647 | val_loss=0.3556 | val_mcc=0.7224 | val_f1=0.7756 | val_auroc=0.9523

[Epoch 12] train_loss=0.0517 | val_loss=0.3445 | val_mcc=0.7297 | val_f1=0.7820 | val_auroc=0.9529
[EarlyStop] epoch=12 | best_val_mcc=0.7511
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7714 | F1=0.8348 | AUROC=0.9570 | AUPRC=0.9083
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7797 | F1=0.8839 | AUROC=0.9642 | AUPRC=0.9647
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4577 | F1=0.7350 | AUROC=0.7893 | AUPRC=0.7813
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6081 | F1=0.7992 | AUROC=0.8950 | AUPRC=0.8814
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3769 | val_loss=0.2197 | val_mcc=0.7503 | val_f1=0.7991 | val_auroc=0.9610

[Epoch 02] train_loss=0.2570 | val_loss=0.2172 | val_mcc=0.7554 | val_f1=0.8022 | val_auroc=0.9657

[Epoch 03] train_loss=0.2265 | val_loss=0.2070 | val_mcc=0.7553 | val_f1=0.8030 | val_auroc=0.9647

[Epoch 04] train_loss=0.1976 | val_loss=0.2220 | val_mcc=0.7509 | val_f1=0.7984 | val_auroc=0.9654

[Epoch 05] train_loss=0.1693 | val_loss=0.2195 | val_mcc=0.7497 | val_f1=0.7985 | val_auroc=0.9627

[Epoch 06] train_loss=0.1450 | val_loss=0.2295 | val_mcc=0.7489 | val_f1=0.7977 | val_auroc=0.9617

[Epoch 07] train_loss=0.1133 | val_loss=0.2426 | val_mcc=0.7459 | val_f1=0.7950 | val_auroc=0.9623

[Epoch 08] train_loss=0.0979 | val_loss=0.2514 | val_mcc=0.7397 | val_f1=0.7904 | val_auroc=0.9607
[EarlyStop] epoch=8 | best_val_mcc=0.7554
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7625 | F1=0.8290 | AUROC=0.9627 | AUPRC=0.9182
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7752 | F1=0.8860 | AUROC=0.9678 | AUPRC=0.9667
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4444 | F1=0.7385 | AUROC=0.7914 | AUPRC=0.7750
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5842 | F1=0.7882 | AUROC=0.9039 | AUPRC=0.8865
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 155.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7955 | F1=0.8525 | AUROC=0.9680 | AUPRC=0.9294
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8522 | F1=0.9244 | AUROC=0.9817 | AUPRC=0.9817
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4486 | F1=0.7400 | AUROC=0.7848 | AUPRC=0.7732
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5721 | F1=0.7826 | AUROC=0.9084 | AUPRC=0.8908
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 181.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7782 | F1=0.8402 | AUROC=0.9641 | AUPRC=0.9223
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8042 | F1=0.8990 | AUROC=0.9735 | AUPRC=0.9745
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4298 | F1=0.7305 | AUROC=0.7875 | AUPRC=0.7760
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5742 | F1=0.7835 | AUROC=0.9027 | AUPRC=0.8893
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 76.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7789 | F1=0.8407 | AUROC=0.9623 | AUPRC=0.9211
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7933 | F1=0.8922 | AUROC=0.9691 | AUPRC=0.9699
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4274 | F1=0.7277 | AUROC=0.7876 | AUPRC=0.7789
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5723 | F1=0.7829 | AUROC=0.9017 | AUPRC=0.8924
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 115.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7831 | F1=0.8437 | AUROC=0.9625 | AUPRC=0.9217
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8350 | F1=0.9162 | AUROC=0.9752 | AUPRC=0.9731
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4942 | val_loss=0.3739 | val_mcc=0.5532 | val_f1=0.6423 | val_auroc=0.8743

[Epoch 02] train_loss=0.4244 | val_loss=0.3815 | val_mcc=0.5626 | val_f1=0.6508 | val_auroc=0.8845

[Epoch 03] train_loss=0.3910 | val_loss=0.3660 | val_mcc=0.5774 | val_f1=0.6624 | val_auroc=0.8876

[Epoch 04] train_loss=0.3615 | val_loss=0.3749 | val_mcc=0.5674 | val_f1=0.6546 | val_auroc=0.8869

[Epoch 05] train_loss=0.3332 | val_loss=0.4179 | val_mcc=0.5415 | val_f1=0.6333 | val_auroc=0.8839

[Epoch 06] train_loss=0.3048 | val_loss=0.3856 | val_mcc=0.5428 | val_f1=0.6354 | val_auroc=0.8814

[Epoch 07] train_loss=0.2776 | val_loss=0.4130 | val_mcc=0.5558 | val_f1=0.6456 | val_auroc=0.8809

[Epoch 08] train_loss=0.2324 | val_loss=0.4330 | val_mcc=0.5453 | val_f1=0.6373 | val_auroc=0.8801

[Epoch 09] train_loss=0.2148 | val_loss=0.4424 | val_mcc=0.5402 | val_f1=0.6334 | val_auroc=0.8789
[EarlyStop] epoch=9 | best_val_mcc=0.5774
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6552 | F1=0.7511 | AUROC=0.9029 | AUPRC=0.8275
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5789 | F1=0.7855 | AUROC=0.8784 | AUPRC=0.8872
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4104 | F1=0.7016 | AUROC=0.7619 | AUPRC=0.7534
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5762 | F1=0.7710 | AUROC=0.8721 | AUPRC=0.8639
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5038 | val_loss=0.3626 | val_mcc=0.5506 | val_f1=0.6390 | val_auroc=0.8692

[Epoch 02] train_loss=0.4409 | val_loss=0.3965 | val_mcc=0.5433 | val_f1=0.6358 | val_auroc=0.8784

[Epoch 03] train_loss=0.4108 | val_loss=0.4365 | val_mcc=0.5311 | val_f1=0.6245 | val_auroc=0.8857

[Epoch 04] train_loss=0.3883 | val_loss=0.3755 | val_mcc=0.5705 | val_f1=0.6570 | val_auroc=0.8875

[Epoch 05] train_loss=0.3641 | val_loss=0.3745 | val_mcc=0.5696 | val_f1=0.6560 | val_auroc=0.8872

[Epoch 06] train_loss=0.3373 | val_loss=0.4343 | val_mcc=0.5497 | val_f1=0.6399 | val_auroc=0.8848

[Epoch 07] train_loss=0.3099 | val_loss=0.4182 | val_mcc=0.5614 | val_f1=0.6500 | val_auroc=0.8835

[Epoch 08] train_loss=0.2904 | val_loss=0.4552 | val_mcc=0.5441 | val_f1=0.6357 | val_auroc=0.8811

[Epoch 09] train_loss=0.2380 | val_loss=0.4590 | val_mcc=0.5483 | val_f1=0.6398 | val_auroc=0.8801

[Epoch 10] train_loss=0.2141 | val_loss=0.4998 | val_mcc=0.5411 | val_f1=0.6340 | val_auroc=0.8757
[EarlyStop] epoch=10 | best_val_mcc=0.5705
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6495 | F1=0.7474 | AUROC=0.9072 | AUPRC=0.8307
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6202 | F1=0.8000 | AUROC=0.8882 | AUPRC=0.8914
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4223 | F1=0.7090 | AUROC=0.7659 | AUPRC=0.7584
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6109 | F1=0.7874 | AUROC=0.8771 | AUPRC=0.8693
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4949 | val_loss=0.3910 | val_mcc=0.5404 | val_f1=0.6335 | val_auroc=0.8693

[Epoch 02] train_loss=0.4295 | val_loss=0.4426 | val_mcc=0.5129 | val_f1=0.6102 | val_auroc=0.8796

[Epoch 03] train_loss=0.3984 | val_loss=0.3578 | val_mcc=0.5613 | val_f1=0.6494 | val_auroc=0.8863

[Epoch 04] train_loss=0.3694 | val_loss=0.4080 | val_mcc=0.5447 | val_f1=0.6363 | val_auroc=0.8848

[Epoch 05] train_loss=0.3410 | val_loss=0.3723 | val_mcc=0.5658 | val_f1=0.6532 | val_auroc=0.8884

[Epoch 06] train_loss=0.3109 | val_loss=0.4216 | val_mcc=0.5252 | val_f1=0.6214 | val_auroc=0.8772

[Epoch 07] train_loss=0.2850 | val_loss=0.4205 | val_mcc=0.5294 | val_f1=0.6251 | val_auroc=0.8762

[Epoch 08] train_loss=0.2607 | val_loss=0.4330 | val_mcc=0.5422 | val_f1=0.6350 | val_auroc=0.8776

[Epoch 09] train_loss=0.2273 | val_loss=0.4343 | val_mcc=0.5528 | val_f1=0.6422 | val_auroc=0.8763

[Epoch 10] train_loss=0.1828 | val_loss=0.5257 | val_mcc=0.5269 | val_f1=0.6223 | val_auroc=0.8777

[Epoch 11] train_loss=0.1567 | val_loss=0.5905 | val_mcc=0.5075 | val_f1=0.6059 | val_auroc=0.8742
[EarlyStop] epoch=11 | best_val_mcc=0.5658
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6504 | F1=0.7485 | AUROC=0.9025 | AUPRC=0.8260
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6282 | F1=0.8059 | AUROC=0.8847 | AUPRC=0.8867
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4239 | F1=0.7073 | AUROC=0.7706 | AUPRC=0.7664
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5996 | F1=0.7798 | AUROC=0.8802 | AUPRC=0.8693
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4990 | val_loss=0.4089 | val_mcc=0.5347 | val_f1=0.6292 | val_auroc=0.8703

[Epoch 02] train_loss=0.4263 | val_loss=0.3712 | val_mcc=0.5549 | val_f1=0.6445 | val_auroc=0.8818

[Epoch 03] train_loss=0.3912 | val_loss=0.3770 | val_mcc=0.5611 | val_f1=0.6498 | val_auroc=0.8857

[Epoch 04] train_loss=0.3560 | val_loss=0.3948 | val_mcc=0.5459 | val_f1=0.6375 | val_auroc=0.8847

[Epoch 05] train_loss=0.3201 | val_loss=0.4484 | val_mcc=0.5097 | val_f1=0.6078 | val_auroc=0.8788

[Epoch 06] train_loss=0.2891 | val_loss=0.4486 | val_mcc=0.5228 | val_f1=0.6186 | val_auroc=0.8776

[Epoch 07] train_loss=0.2545 | val_loss=0.4523 | val_mcc=0.5387 | val_f1=0.6318 | val_auroc=0.8789

[Epoch 08] train_loss=0.2022 | val_loss=0.4519 | val_mcc=0.5423 | val_f1=0.6348 | val_auroc=0.8793

[Epoch 09] train_loss=0.1785 | val_loss=0.4783 | val_mcc=0.5364 | val_f1=0.6301 | val_auroc=0.8786
[EarlyStop] epoch=9 | best_val_mcc=0.5611
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6459 | F1=0.7451 | AUROC=0.9018 | AUPRC=0.8241
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6048 | F1=0.7965 | AUROC=0.8681 | AUPRC=0.8799
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3968 | F1=0.6973 | AUROC=0.7539 | AUPRC=0.7435
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5714 | F1=0.7698 | AUROC=0.8654 | AUPRC=0.8590
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 333.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6198 | F1=0.7272 | AUROC=0.8978 | AUPRC=0.8159
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5903 | F1=0.7919 | AUROC=0.8791 | AUPRC=0.8781
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4013 | F1=0.6984 | AUROC=0.7519 | AUPRC=0.7373
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5882 | F1=0.7796 | AUROC=0.8705 | AUPRC=0.8591
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 223.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6228 | F1=0.7303 | AUROC=0.8998 | AUPRC=0.8163
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5846 | F1=0.7890 | AUROC=0.8668 | AUPRC=0.8687
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4344 | F1=0.7168 | AUROC=0.7670 | AUPRC=0.7579
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5776 | F1=0.7744 | AUROC=0.8682 | AUPRC=0.8581
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 84.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6316 | F1=0.7364 | AUROC=0.9036 | AUPRC=0.8270
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5932 | F1=0.7954 | AUROC=0.8762 | AUPRC=0.8856
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4034 | F1=0.7069 | AUROC=0.7615 | AUPRC=0.7558
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5909 | F1=0.7810 | AUROC=0.8792 | AUPRC=0.8702
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 106.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6278 | F1=0.7339 | AUROC=0.8994 | AUPRC=0.8170
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5903 | F1=0.7907 | AUROC=0.8754 | AUPRC=0.8773
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3810 | F1=0.6970 | AUROC=0.7540 | AUPRC=0.7472
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.3848 | val_loss=0.2141 | val_mcc=0.7419 | val_f1=0.7924 | val_auroc=0.9606

[Epoch 02] train_loss=0.2659 | val_loss=0.2093 | val_mcc=0.7543 | val_f1=0.8020 | val_auroc=0.9650

[Epoch 03] train_loss=0.2355 | val_loss=0.2073 | val_mcc=0.7622 | val_f1=0.8083 | val_auroc=0.9651

[Epoch 04] train_loss=0.2110 | val_loss=0.2015 | val_mcc=0.7604 | val_f1=0.8072 | val_auroc=0.9646

[Epoch 05] train_loss=0.1878 | val_loss=0.2217 | val_mcc=0.7479 | val_f1=0.7968 | val_auroc=0.9620

[Epoch 06] train_loss=0.1680 | val_loss=0.2269 | val_mcc=0.7441 | val_f1=0.7934 | val_auroc=0.9646

[Epoch 07] train_loss=0.1435 | val_loss=0.2432 | val_mcc=0.7333 | val_f1=0.7851 | val_auroc=0.9609

[Epoch 08] train_loss=0.1149 | val_loss=0.2447 | val_mcc=0.7410 | val_f1=0.7912 | val_auroc=0.9619

[Epoch 09] train_loss=0.1027 | val_loss=0.2502 | val_mcc=0.7382 | val_f1=0.7893 | val_auroc=0.9604
[EarlyStop] epoch=9 | best_val_mcc=0.7622
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7721 | F1=0.8359 | AUROC=0.9622 | AUPRC=0.9186
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8011 | F1=0.8980 | AUROC=0.9675 | AUPRC=0.9681
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4336 | F1=0.7309 | AUROC=0.7823 | AUPRC=0.7703
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5790 | F1=0.7860 | AUROC=0.8947 | AUPRC=0.8821
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3824 | val_loss=0.2135 | val_mcc=0.7385 | val_f1=0.7896 | val_auroc=0.9593

[Epoch 02] train_loss=0.2771 | val_loss=0.2126 | val_mcc=0.7577 | val_f1=0.8042 | val_auroc=0.9656

[Epoch 03] train_loss=0.2522 | val_loss=0.2237 | val_mcc=0.7474 | val_f1=0.7960 | val_auroc=0.9634

[Epoch 04] train_loss=0.2323 | val_loss=0.2158 | val_mcc=0.7522 | val_f1=0.8000 | val_auroc=0.9655

[Epoch 05] train_loss=0.2093 | val_loss=0.2160 | val_mcc=0.7527 | val_f1=0.8011 | val_auroc=0.9614

[Epoch 06] train_loss=0.1902 | val_loss=0.2459 | val_mcc=0.7299 | val_f1=0.7820 | val_auroc=0.9582

[Epoch 07] train_loss=0.1611 | val_loss=0.2457 | val_mcc=0.7460 | val_f1=0.7950 | val_auroc=0.9610

[Epoch 08] train_loss=0.1410 | val_loss=0.2876 | val_mcc=0.7186 | val_f1=0.7720 | val_auroc=0.9581
[EarlyStop] epoch=8 | best_val_mcc=0.7577
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7665 | F1=0.8318 | AUROC=0.9607 | AUPRC=0.9144
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8026 | F1=0.8958 | AUROC=0.9689 | AUPRC=0.9695
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3992 | F1=0.7201 | AUROC=0.7767 | AUPRC=0.7711
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5618 | F1=0.7781 | AUROC=0.8918 | AUPRC=0.8772
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3892 | val_loss=0.2790 | val_mcc=0.7018 | val_f1=0.7561 | val_auroc=0.9569

[Epoch 02] train_loss=0.2764 | val_loss=0.2017 | val_mcc=0.7548 | val_f1=0.8027 | val_auroc=0.9629

[Epoch 03] train_loss=0.2479 | val_loss=0.2422 | val_mcc=0.7296 | val_f1=0.7793 | val_auroc=0.9659

[Epoch 04] train_loss=0.2232 | val_loss=0.2141 | val_mcc=0.7472 | val_f1=0.7964 | val_auroc=0.9630

[Epoch 05] train_loss=0.1960 | val_loss=0.2147 | val_mcc=0.7425 | val_f1=0.7929 | val_auroc=0.9610

[Epoch 06] train_loss=0.1766 | val_loss=0.2478 | val_mcc=0.7265 | val_f1=0.7801 | val_auroc=0.9555

[Epoch 07] train_loss=0.1410 | val_loss=0.2463 | val_mcc=0.7377 | val_f1=0.7887 | val_auroc=0.9604

[Epoch 08] train_loss=0.1215 | val_loss=0.2606 | val_mcc=0.7330 | val_f1=0.7851 | val_auroc=0.9569
[EarlyStop] epoch=8 | best_val_mcc=0.7548
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7678 | F1=0.8326 | AUROC=0.9592 | AUPRC=0.9132
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8018 | F1=0.8968 | AUROC=0.9648 | AUPRC=0.9667
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4541 | F1=0.7361 | AUROC=0.7886 | AUPRC=0.7746
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5810 | F1=0.7867 | AUROC=0.8996 | AUPRC=0.8859
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3875 | val_loss=0.2227 | val_mcc=0.7381 | val_f1=0.7894 | val_auroc=0.9603

[Epoch 02] train_loss=0.2701 | val_loss=0.2161 | val_mcc=0.7532 | val_f1=0.8004 | val_auroc=0.9660

[Epoch 03] train_loss=0.2338 | val_loss=0.2037 | val_mcc=0.7557 | val_f1=0.8033 | val_auroc=0.9650

[Epoch 04] train_loss=0.2090 | val_loss=0.2088 | val_mcc=0.7616 | val_f1=0.8079 | val_auroc=0.9651

[Epoch 05] train_loss=0.1815 | val_loss=0.2240 | val_mcc=0.7532 | val_f1=0.8009 | val_auroc=0.9637

[Epoch 06] train_loss=0.1584 | val_loss=0.2291 | val_mcc=0.7459 | val_f1=0.7950 | val_auroc=0.9630

[Epoch 07] train_loss=0.1328 | val_loss=0.2531 | val_mcc=0.7395 | val_f1=0.7898 | val_auroc=0.9594

[Epoch 08] train_loss=0.1130 | val_loss=0.2661 | val_mcc=0.7294 | val_f1=0.7818 | val_auroc=0.9584

[Epoch 09] train_loss=0.0828 | val_loss=0.2651 | val_mcc=0.7315 | val_f1=0.7838 | val_auroc=0.9590

[Epoch 10] train_loss=0.0709 | val_loss=0.2869 | val_mcc=0.7338 | val_f1=0.7852 | val_auroc=0.9581
[EarlyStop] epoch=10 | best_val_mcc=0.7616
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7654 | F1=0.8310 | AUROC=0.9600 | AUPRC=0.9139
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7963 | F1=0.8935 | AUROC=0.9684 | AUPRC=0.9684
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4269 | F1=0.7265 | AUROC=0.7766 | AUPRC=0.7639
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5700 | F1=0.7819 | AUROC=0.8924 | AUPRC=0.8791
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 219.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7912 | F1=0.8494 | AUROC=0.9679 | AUPRC=0.9277
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8668 | F1=0.9312 | AUROC=0.9841 | AUPRC=0.9851
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4296 | F1=0.7339 | AUROC=0.7824 | AUPRC=0.7691
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5618 | F1=0.7778 | AUROC=0.9085 | AUPRC=0.8965
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 194.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7678 | F1=0.8328 | AUROC=0.9622 | AUPRC=0.9166
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8269 | F1=0.9107 | AUROC=0.9704 | AUPRC=0.9715
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4335 | F1=0.7330 | AUROC=0.7798 | AUPRC=0.7638
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5742 | F1=0.7834 | AUROC=0.8980 | AUPRC=0.8814
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 107.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7738 | F1=0.8371 | AUROC=0.9622 | AUPRC=0.9169
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8381 | F1=0.9170 | AUROC=0.9711 | AUPRC=0.9709
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4446 | F1=0.7368 | AUROC=0.7850 | AUPRC=0.7682
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5862 | F1=0.7891 | AUROC=0.9004 | AUPRC=0.8847
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 177.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7771 | F1=0.8394 | AUROC=0.9612 | AUPRC=0.9149
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8224 | F1=0.9064 | AUROC=0.9722 | AUPRC=0.9725
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4680 | val_loss=0.3615 | val_mcc=0.5808 | val_f1=0.6644 | val_auroc=0.8854

[Epoch 02] train_loss=0.3982 | val_loss=0.3762 | val_mcc=0.5717 | val_f1=0.6579 | val_auroc=0.8890

[Epoch 03] train_loss=0.3647 | val_loss=0.3784 | val_mcc=0.5749 | val_f1=0.6604 | val_auroc=0.8910

[Epoch 04] train_loss=0.3339 | val_loss=0.3887 | val_mcc=0.5624 | val_f1=0.6501 | val_auroc=0.8923

[Epoch 05] train_loss=0.3073 | val_loss=0.3721 | val_mcc=0.5779 | val_f1=0.6627 | val_auroc=0.8931

[Epoch 06] train_loss=0.2642 | val_loss=0.3960 | val_mcc=0.5718 | val_f1=0.6574 | val_auroc=0.8936

[Epoch 07] train_loss=0.2415 | val_loss=0.4067 | val_mcc=0.5559 | val_f1=0.6452 | val_auroc=0.8910
[EarlyStop] epoch=7 | best_val_mcc=0.5808
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6162 | F1=0.7163 | AUROC=0.8849 | AUPRC=0.7954
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6121 | F1=0.7877 | AUROC=0.8750 | AUPRC=0.8696
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4281 | F1=0.7002 | AUROC=0.7614 | AUPRC=0.7601
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5562 | F1=0.7404 | AUROC=0.8359 | AUPRC=0.8298
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4744 | val_loss=0.3599 | val_mcc=0.5726 | val_f1=0.6575 | val_auroc=0.8834

[Epoch 02] train_loss=0.4094 | val_loss=0.3975 | val_mcc=0.5681 | val_f1=0.6550 | val_auroc=0.8909

[Epoch 03] train_loss=0.3767 | val_loss=0.3462 | val_mcc=0.6033 | val_f1=0.6822 | val_auroc=0.8924

[Epoch 04] train_loss=0.3510 | val_loss=0.3713 | val_mcc=0.5818 | val_f1=0.6658 | val_auroc=0.8967

[Epoch 05] train_loss=0.3257 | val_loss=0.3957 | val_mcc=0.5775 | val_f1=0.6622 | val_auroc=0.8923

[Epoch 06] train_loss=0.3008 | val_loss=0.3883 | val_mcc=0.5732 | val_f1=0.6591 | val_auroc=0.8908

[Epoch 07] train_loss=0.2731 | val_loss=0.4251 | val_mcc=0.5683 | val_f1=0.6549 | val_auroc=0.8870

[Epoch 08] train_loss=0.2316 | val_loss=0.4583 | val_mcc=0.5651 | val_f1=0.6523 | val_auroc=0.8858

[Epoch 09] train_loss=0.2094 | val_loss=0.4882 | val_mcc=0.5518 | val_f1=0.6414 | val_auroc=0.8843
[EarlyStop] epoch=9 | best_val_mcc=0.6033
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6390 | F1=0.7337 | AUROC=0.8965 | AUPRC=0.8061
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6270 | F1=0.8006 | AUROC=0.8848 | AUPRC=0.8725
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4484 | F1=0.7152 | AUROC=0.7795 | AUPRC=0.7655
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5863 | F1=0.7603 | AUROC=0.8531 | AUPRC=0.8438
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4734 | val_loss=0.3653 | val_mcc=0.5742 | val_f1=0.6595 | val_auroc=0.8837

[Epoch 02] train_loss=0.4045 | val_loss=0.3441 | val_mcc=0.5916 | val_f1=0.6727 | val_auroc=0.8909

[Epoch 03] train_loss=0.3689 | val_loss=0.3514 | val_mcc=0.5874 | val_f1=0.6700 | val_auroc=0.8933

[Epoch 04] train_loss=0.3413 | val_loss=0.3739 | val_mcc=0.5769 | val_f1=0.6620 | val_auroc=0.8930

[Epoch 05] train_loss=0.3105 | val_loss=0.4005 | val_mcc=0.5689 | val_f1=0.6551 | val_auroc=0.8921

[Epoch 06] train_loss=0.2812 | val_loss=0.3767 | val_mcc=0.5819 | val_f1=0.6656 | val_auroc=0.8880

[Epoch 07] train_loss=0.2345 | val_loss=0.4309 | val_mcc=0.5622 | val_f1=0.6505 | val_auroc=0.8876

[Epoch 08] train_loss=0.2114 | val_loss=0.4256 | val_mcc=0.5691 | val_f1=0.6559 | val_auroc=0.8870
[EarlyStop] epoch=8 | best_val_mcc=0.5916
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6127 | F1=0.7145 | AUROC=0.8877 | AUPRC=0.7988
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6136 | F1=0.7915 | AUROC=0.8772 | AUPRC=0.8734
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4251 | F1=0.6986 | AUROC=0.7701 | AUPRC=0.7660
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5609 | F1=0.7484 | AUROC=0.8453 | AUPRC=0.8373
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4784 | val_loss=0.3954 | val_mcc=0.5538 | val_f1=0.6440 | val_auroc=0.8782

[Epoch 02] train_loss=0.3996 | val_loss=0.3664 | val_mcc=0.5737 | val_f1=0.6595 | val_auroc=0.8873

[Epoch 03] train_loss=0.3611 | val_loss=0.3732 | val_mcc=0.5772 | val_f1=0.6622 | val_auroc=0.8913

[Epoch 04] train_loss=0.3272 | val_loss=0.4036 | val_mcc=0.5586 | val_f1=0.6467 | val_auroc=0.8892

[Epoch 05] train_loss=0.2943 | val_loss=0.3813 | val_mcc=0.5729 | val_f1=0.6589 | val_auroc=0.8905

[Epoch 06] train_loss=0.2575 | val_loss=0.4270 | val_mcc=0.5506 | val_f1=0.6411 | val_auroc=0.8866

[Epoch 07] train_loss=0.2191 | val_loss=0.4156 | val_mcc=0.5606 | val_f1=0.6494 | val_auroc=0.8864

[Epoch 08] train_loss=0.1745 | val_loss=0.4741 | val_mcc=0.5449 | val_f1=0.6362 | val_auroc=0.8867

[Epoch 09] train_loss=0.1486 | val_loss=0.4963 | val_mcc=0.5342 | val_f1=0.6282 | val_auroc=0.8826
[EarlyStop] epoch=9 | best_val_mcc=0.5772
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6257 | F1=0.7298 | AUROC=0.8923 | AUPRC=0.8003
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6302 | F1=0.8110 | AUROC=0.8908 | AUPRC=0.8796
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4585 | F1=0.7304 | AUROC=0.7779 | AUPRC=0.7689
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5458 | F1=0.7491 | AUROC=0.8485 | AUPRC=0.8386
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 243.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6096 | F1=0.7177 | AUROC=0.8870 | AUPRC=0.7877
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6223 | F1=0.8035 | AUROC=0.8835 | AUPRC=0.8689
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4421 | F1=0.7143 | AUROC=0.7705 | AUPRC=0.7571
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5634 | F1=0.7561 | AUROC=0.8517 | AUPRC=0.8268
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 178.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6256 | F1=0.7295 | AUROC=0.8907 | AUPRC=0.8006
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6417 | F1=0.8163 | AUROC=0.8766 | AUPRC=0.8749
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4314 | F1=0.7165 | AUROC=0.7759 | AUPRC=0.7581
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5596 | F1=0.7566 | AUROC=0.8424 | AUPRC=0.8295
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 44.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6266 | F1=0.7299 | AUROC=0.8959 | AUPRC=0.8056
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6048 | F1=0.7965 | AUROC=0.8811 | AUPRC=0.8765
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4284 | F1=0.7155 | AUROC=0.7684 | AUPRC=0.7527
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5627 | F1=0.7603 | AUROC=0.8440 | AUPRC=0.8354
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 50.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6187 | F1=0.7247 | AUROC=0.8907 | AUPRC=0.7992
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6164 | F1=0.8012 | AUROC=0.8811 | AUPRC=0.8719
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4227 | F1=0.7036 | AUROC=0.7706 | AUPRC=0.7627
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.3650 | val_loss=0.2010 | val_mcc=0.7630 | val_f1=0.8091 | val_auroc=0.9635

[Epoch 02] train_loss=0.2481 | val_loss=0.1882 | val_mcc=0.7791 | val_f1=0.8222 | val_auroc=0.9685

[Epoch 03] train_loss=0.2159 | val_loss=0.2079 | val_mcc=0.7632 | val_f1=0.8088 | val_auroc=0.9663

[Epoch 04] train_loss=0.1894 | val_loss=0.1948 | val_mcc=0.7759 | val_f1=0.8195 | val_auroc=0.9676

[Epoch 05] train_loss=0.1682 | val_loss=0.1971 | val_mcc=0.7726 | val_f1=0.8169 | val_auroc=0.9675

[Epoch 06] train_loss=0.1489 | val_loss=0.2263 | val_mcc=0.7555 | val_f1=0.8022 | val_auroc=0.9650

[Epoch 07] train_loss=0.1187 | val_loss=0.2157 | val_mcc=0.7616 | val_f1=0.8079 | val_auroc=0.9665

[Epoch 08] train_loss=0.1040 | val_loss=0.2306 | val_mcc=0.7600 | val_f1=0.8064 | val_auroc=0.9643
[EarlyStop] epoch=8 | best_val_mcc=0.7791
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7709 | F1=0.8341 | AUROC=0.9617 | AUPRC=0.9147
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8059 | F1=0.8969 | AUROC=0.9688 | AUPRC=0.9663
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4311 | F1=0.7238 | AUROC=0.7890 | AUPRC=0.7677
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5562 | F1=0.7750 | AUROC=0.8798 | AUPRC=0.8583
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3736 | val_loss=0.2491 | val_mcc=0.7216 | val_f1=0.7746 | val_auroc=0.9591

[Epoch 02] train_loss=0.2632 | val_loss=0.1916 | val_mcc=0.7736 | val_f1=0.8177 | val_auroc=0.9691

[Epoch 03] train_loss=0.2304 | val_loss=0.1998 | val_mcc=0.7754 | val_f1=0.8185 | val_auroc=0.9693

[Epoch 04] train_loss=0.2106 | val_loss=0.1836 | val_mcc=0.7867 | val_f1=0.8282 | val_auroc=0.9695

[Epoch 05] train_loss=0.1884 | val_loss=0.1988 | val_mcc=0.7781 | val_f1=0.8214 | val_auroc=0.9668

[Epoch 06] train_loss=0.1722 | val_loss=0.2049 | val_mcc=0.7636 | val_f1=0.8097 | val_auroc=0.9650

[Epoch 07] train_loss=0.1486 | val_loss=0.2493 | val_mcc=0.7433 | val_f1=0.7928 | val_auroc=0.9623

[Epoch 08] train_loss=0.1323 | val_loss=0.2912 | val_mcc=0.7244 | val_f1=0.7761 | val_auroc=0.9588

[Epoch 09] train_loss=0.1036 | val_loss=0.2865 | val_mcc=0.7323 | val_f1=0.7835 | val_auroc=0.9580

[Epoch 10] train_loss=0.0879 | val_loss=0.2912 | val_mcc=0.7388 | val_f1=0.7894 | val_auroc=0.9582
[EarlyStop] epoch=10 | best_val_mcc=0.7867
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7799 | F1=0.8402 | AUROC=0.9616 | AUPRC=0.9151
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8110 | F1=0.9004 | AUROC=0.9729 | AUPRC=0.9717
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4655 | F1=0.7396 | AUROC=0.7868 | AUPRC=0.7667
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5778 | F1=0.7847 | AUROC=0.8812 | AUPRC=0.8583
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3715 | val_loss=0.2070 | val_mcc=0.7589 | val_f1=0.8060 | val_auroc=0.9629

[Epoch 02] train_loss=0.2544 | val_loss=0.2005 | val_mcc=0.7740 | val_f1=0.8177 | val_auroc=0.9689

[Epoch 03] train_loss=0.2212 | val_loss=0.2015 | val_mcc=0.7640 | val_f1=0.8097 | val_auroc=0.9677

[Epoch 04] train_loss=0.1982 | val_loss=0.2380 | val_mcc=0.7428 | val_f1=0.7907 | val_auroc=0.9654

[Epoch 05] train_loss=0.1725 | val_loss=0.2344 | val_mcc=0.7457 | val_f1=0.7944 | val_auroc=0.9623

[Epoch 06] train_loss=0.1530 | val_loss=0.2445 | val_mcc=0.7442 | val_f1=0.7935 | val_auroc=0.9613

[Epoch 07] train_loss=0.1194 | val_loss=0.2468 | val_mcc=0.7561 | val_f1=0.8029 | val_auroc=0.9623

[Epoch 08] train_loss=0.1048 | val_loss=0.2452 | val_mcc=0.7543 | val_f1=0.8022 | val_auroc=0.9603
[EarlyStop] epoch=8 | best_val_mcc=0.7740
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7652 | F1=0.8310 | AUROC=0.9618 | AUPRC=0.9171
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8123 | F1=0.9043 | AUROC=0.9677 | AUPRC=0.9662
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4445 | F1=0.7339 | AUROC=0.7938 | AUPRC=0.7709
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5382 | F1=0.7675 | AUROC=0.8887 | AUPRC=0.8738
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3710 | val_loss=0.2099 | val_mcc=0.7619 | val_f1=0.8084 | val_auroc=0.9640

[Epoch 02] train_loss=0.2528 | val_loss=0.1895 | val_mcc=0.7804 | val_f1=0.8232 | val_auroc=0.9675

[Epoch 03] train_loss=0.2187 | val_loss=0.1965 | val_mcc=0.7733 | val_f1=0.8173 | val_auroc=0.9677

[Epoch 04] train_loss=0.1882 | val_loss=0.1989 | val_mcc=0.7773 | val_f1=0.8204 | val_auroc=0.9681

[Epoch 05] train_loss=0.1647 | val_loss=0.2153 | val_mcc=0.7640 | val_f1=0.8093 | val_auroc=0.9666

[Epoch 06] train_loss=0.1390 | val_loss=0.2252 | val_mcc=0.7566 | val_f1=0.8039 | val_auroc=0.9633

[Epoch 07] train_loss=0.1071 | val_loss=0.2363 | val_mcc=0.7510 | val_f1=0.7991 | val_auroc=0.9640

[Epoch 08] train_loss=0.0891 | val_loss=0.2290 | val_mcc=0.7556 | val_f1=0.8033 | val_auroc=0.9636
[EarlyStop] epoch=8 | best_val_mcc=0.7804
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7707 | F1=0.8343 | AUROC=0.9608 | AUPRC=0.9154
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8244 | F1=0.9088 | AUROC=0.9701 | AUPRC=0.9680
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4639 | F1=0.7387 | AUROC=0.7966 | AUPRC=0.7805
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5888 | F1=0.7900 | AUROC=0.8865 | AUPRC=0.8654
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 182.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7922 | F1=0.8502 | AUROC=0.9681 | AUPRC=0.9304
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8533 | F1=0.9231 | AUROC=0.9865 | AUPRC=0.9861
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4462 | F1=0.7397 | AUROC=0.7844 | AUPRC=0.7650
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5672 | F1=0.7805 | AUROC=0.9023 | AUPRC=0.8830
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 155.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7811 | F1=0.8422 | AUROC=0.9623 | AUPRC=0.9178
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8607 | F1=0.9289 | AUROC=0.9746 | AUPRC=0.9724
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4483 | F1=0.7372 | AUROC=0.7893 | AUPRC=0.7727
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5579 | F1=0.7764 | AUROC=0.8885 | AUPRC=0.8661
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 86.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7811 | F1=0.8423 | AUROC=0.9650 | AUPRC=0.9211
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8411 | F1=0.9181 | AUROC=0.9743 | AUPRC=0.9717
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4587 | F1=0.7440 | AUROC=0.7908 | AUPRC=0.7666
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5654 | F1=0.7796 | AUROC=0.8914 | AUPRC=0.8731
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 138.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7831 | F1=0.8437 | AUROC=0.9632 | AUPRC=0.9174
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8550 | F1=0.9262 | AUROC=0.9751 | AUPRC=0.9740
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.4827 | val_loss=0.3330 | val_mcc=0.6222 | val_f1=0.6911 | val_auroc=0.8826

[Epoch 02] train_loss=0.4035 | val_loss=0.3451 | val_mcc=0.6118 | val_f1=0.6891 | val_auroc=0.8985

[Epoch 03] train_loss=0.3615 | val_loss=0.3375 | val_mcc=0.6104 | val_f1=0.6882 | val_auroc=0.9039

[Epoch 04] train_loss=0.3202 | val_loss=0.3248 | val_mcc=0.6161 | val_f1=0.6924 | val_auroc=0.9063

[Epoch 05] train_loss=0.2734 | val_loss=0.3715 | val_mcc=0.5849 | val_f1=0.6680 | val_auroc=0.9031

[Epoch 06] train_loss=0.2164 | val_loss=0.3711 | val_mcc=0.5850 | val_f1=0.6682 | val_auroc=0.9035

[Epoch 07] train_loss=0.1884 | val_loss=0.3932 | val_mcc=0.5816 | val_f1=0.6654 | val_auroc=0.9011
[EarlyStop] epoch=7 | best_val_mcc=0.6222
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6722 | F1=0.7525 | AUROC=0.8989 | AUPRC=0.8325
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6286 | F1=0.7880 | AUROC=0.8790 | AUPRC=0.8921
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4542 | F1=0.6969 | AUROC=0.7714 | AUPRC=0.7734
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5914 | F1=0.7553 | AUROC=0.8664 | AUPRC=0.8640
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4724 | val_loss=0.4106 | val_mcc=0.5822 | val_f1=0.6662 | val_auroc=0.8866

[Epoch 02] train_loss=0.4068 | val_loss=0.3100 | val_mcc=0.6278 | val_f1=0.6987 | val_auroc=0.9012

[Epoch 03] train_loss=0.3693 | val_loss=0.3268 | val_mcc=0.6252 | val_f1=0.6996 | val_auroc=0.9095

[Epoch 04] train_loss=0.3186 | val_loss=0.3278 | val_mcc=0.6147 | val_f1=0.6913 | val_auroc=0.9054

[Epoch 05] train_loss=0.2662 | val_loss=0.3606 | val_mcc=0.5983 | val_f1=0.6787 | val_auroc=0.8995

[Epoch 06] train_loss=0.2113 | val_loss=0.4206 | val_mcc=0.5851 | val_f1=0.6685 | val_auroc=0.8953

[Epoch 07] train_loss=0.1495 | val_loss=0.5361 | val_mcc=0.5670 | val_f1=0.6534 | val_auroc=0.8911

[Epoch 08] train_loss=0.1231 | val_loss=0.5670 | val_mcc=0.5679 | val_f1=0.6546 | val_auroc=0.8879
[EarlyStop] epoch=8 | best_val_mcc=0.6278
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6806 | F1=0.7630 | AUROC=0.9081 | AUPRC=0.8429
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6560 | F1=0.8152 | AUROC=0.9047 | AUPRC=0.9113
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4654 | F1=0.7098 | AUROC=0.7727 | AUPRC=0.7717
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6123 | F1=0.7773 | AUROC=0.8750 | AUPRC=0.8706
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4773 | val_loss=0.3501 | val_mcc=0.6226 | val_f1=0.6952 | val_auroc=0.8893

[Epoch 02] train_loss=0.4038 | val_loss=0.3455 | val_mcc=0.6170 | val_f1=0.6933 | val_auroc=0.8999

[Epoch 03] train_loss=0.3660 | val_loss=0.3747 | val_mcc=0.5952 | val_f1=0.6756 | val_auroc=0.9043

[Epoch 04] train_loss=0.3229 | val_loss=0.3373 | val_mcc=0.6191 | val_f1=0.6951 | val_auroc=0.9085

[Epoch 05] train_loss=0.2775 | val_loss=0.3664 | val_mcc=0.6000 | val_f1=0.6801 | val_auroc=0.9025

[Epoch 06] train_loss=0.2042 | val_loss=0.4076 | val_mcc=0.5962 | val_f1=0.6769 | val_auroc=0.9016

[Epoch 07] train_loss=0.1688 | val_loss=0.4465 | val_mcc=0.5956 | val_f1=0.6767 | val_auroc=0.8975
[EarlyStop] epoch=7 | best_val_mcc=0.6226
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6729 | F1=0.7580 | AUROC=0.9027 | AUPRC=0.8381
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6304 | F1=0.8012 | AUROC=0.8830 | AUPRC=0.8994
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4574 | F1=0.7069 | AUROC=0.7717 | AUPRC=0.7736
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6050 | F1=0.7754 | AUROC=0.8674 | AUPRC=0.8664
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4834 | val_loss=0.3369 | val_mcc=0.6204 | val_f1=0.6901 | val_auroc=0.8829

[Epoch 02] train_loss=0.4050 | val_loss=0.3166 | val_mcc=0.6248 | val_f1=0.6962 | val_auroc=0.8983

[Epoch 03] train_loss=0.3622 | val_loss=0.3460 | val_mcc=0.6105 | val_f1=0.6884 | val_auroc=0.9041

[Epoch 04] train_loss=0.3167 | val_loss=0.3320 | val_mcc=0.6033 | val_f1=0.6825 | val_auroc=0.9025

[Epoch 05] train_loss=0.2649 | val_loss=0.3392 | val_mcc=0.6052 | val_f1=0.6838 | val_auroc=0.9017

[Epoch 06] train_loss=0.2110 | val_loss=0.3736 | val_mcc=0.5947 | val_f1=0.6760 | val_auroc=0.8990

[Epoch 07] train_loss=0.1497 | val_loss=0.3988 | val_mcc=0.5969 | val_f1=0.6777 | val_auroc=0.9000

[Epoch 08] train_loss=0.1215 | val_loss=0.4547 | val_mcc=0.5850 | val_f1=0.6681 | val_auroc=0.8958
[EarlyStop] epoch=8 | best_val_mcc=0.6248
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6718 | F1=0.7569 | AUROC=0.9045 | AUPRC=0.8407
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6445 | F1=0.8091 | AUROC=0.8923 | AUPRC=0.9036
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4526 | F1=0.7052 | AUROC=0.7719 | AUPRC=0.7680
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6152 | F1=0.7782 | AUROC=0.8721 | AUPRC=0.8714
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 422.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6739 | F1=0.7639 | AUROC=0.9115 | AUPRC=0.8415
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6701 | F1=0.8309 | AUROC=0.8991 | AUPRC=0.9065
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4393 | F1=0.7114 | AUROC=0.7708 | AUPRC=0.7603
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.6203 | F1=0.7922 | AUROC=0.8747 | AUPRC=0.8656
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 227.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6636 | F1=0.7571 | AUROC=0.9146 | AUPRC=0.8431
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6306 | F1=0.8088 | AUROC=0.8994 | AUPRC=0.9052
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4269 | F1=0.7145 | AUROC=0.7822 | AUPRC=0.7840
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5915 | F1=0.7759 | AUROC=0.8810 | AUPRC=0.8699
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 75.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6556 | F1=0.7524 | AUROC=0.9083 | AUPRC=0.8411
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6500 | F1=0.8230 | AUROC=0.8973 | AUPRC=0.9077
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4450 | F1=0.7243 | AUROC=0.7784 | AUPRC=0.7718
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5949 | F1=0.7801 | AUROC=0.8719 | AUPRC=0.8673
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 86.
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6567 | F1=0.7532 | AUROC=0.9094 | AUPRC=0.8428
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6444 | F1=0.8191 | AUROC=0.8987 | AUPRC=0.9097
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4106 | F1=0.7082 | AUROC=0.7757 | AUPRC=0.7714
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.3636 | val_loss=0.2001 | val_mcc=0.7625 | val_f1=0.8089 | val_auroc=0.9659

[Epoch 02] train_loss=0.2547 | val_loss=0.1829 | val_mcc=0.7802 | val_f1=0.8230 | val_auroc=0.9688

[Epoch 03] train_loss=0.2182 | val_loss=0.1769 | val_mcc=0.7818 | val_f1=0.8243 | val_auroc=0.9697

[Epoch 04] train_loss=0.1877 | val_loss=0.1894 | val_mcc=0.7759 | val_f1=0.8195 | val_auroc=0.9695

[Epoch 05] train_loss=0.1541 | val_loss=0.2085 | val_mcc=0.7630 | val_f1=0.8090 | val_auroc=0.9665

[Epoch 06] train_loss=0.1190 | val_loss=0.2333 | val_mcc=0.7475 | val_f1=0.7965 | val_auroc=0.9646

[Epoch 07] train_loss=0.0880 | val_loss=0.2555 | val_mcc=0.7488 | val_f1=0.7973 | val_auroc=0.9631

[Epoch 08] train_loss=0.0581 | val_loss=0.2570 | val_mcc=0.7518 | val_f1=0.8001 | val_auroc=0.9631

[Epoch 09] train_loss=0.0459 | val_loss=0.2854 | val_mcc=0.7418 | val_f1=0.7917 | val_auroc=0.9608
[EarlyStop] epoch=9 | best_val_mcc=0.7818
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7878 | F1=0.8465 | AUROC=0.9651 | AUPRC=0.9265
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8392 | F1=0.9156 | AUROC=0.9764 | AUPRC=0.9768
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4501 | F1=0.7356 | AUROC=0.7896 | AUPRC=0.7795
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6083 | F1=0.7995 | AUROC=0.9008 | AUPRC=0.8853
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3658 | val_loss=0.1995 | val_mcc=0.7707 | val_f1=0.8154 | val_auroc=0.9667

[Epoch 02] train_loss=0.2655 | val_loss=0.2017 | val_mcc=0.7644 | val_f1=0.8093 | val_auroc=0.9698

[Epoch 03] train_loss=0.2340 | val_loss=0.1936 | val_mcc=0.7737 | val_f1=0.8173 | val_auroc=0.9693

[Epoch 04] train_loss=0.1976 | val_loss=0.1855 | val_mcc=0.7758 | val_f1=0.8195 | val_auroc=0.9685

[Epoch 05] train_loss=0.1644 | val_loss=0.2193 | val_mcc=0.7585 | val_f1=0.8048 | val_auroc=0.9667

[Epoch 06] train_loss=0.1282 | val_loss=0.3094 | val_mcc=0.7176 | val_f1=0.7688 | val_auroc=0.9629

[Epoch 07] train_loss=0.0922 | val_loss=0.3266 | val_mcc=0.7172 | val_f1=0.7706 | val_auroc=0.9565

[Epoch 08] train_loss=0.0659 | val_loss=0.3436 | val_mcc=0.7223 | val_f1=0.7754 | val_auroc=0.9545

[Epoch 09] train_loss=0.0425 | val_loss=0.3336 | val_mcc=0.7311 | val_f1=0.7838 | val_auroc=0.9529

[Epoch 10] train_loss=0.0333 | val_loss=0.3764 | val_mcc=0.7245 | val_f1=0.7784 | val_auroc=0.9509
[EarlyStop] epoch=10 | best_val_mcc=0.7758
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7919 | F1=0.8497 | AUROC=0.9638 | AUPRC=0.9242
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8159 | F1=0.9003 | AUROC=0.9780 | AUPRC=0.9778
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4567 | F1=0.7400 | AUROC=0.7876 | AUPRC=0.7797
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5871 | F1=0.7896 | AUROC=0.8989 | AUPRC=0.8807
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3721 | val_loss=0.2205 | val_mcc=0.7538 | val_f1=0.8013 | val_auroc=0.9658

[Epoch 02] train_loss=0.2626 | val_loss=0.1697 | val_mcc=0.7877 | val_f1=0.8266 | val_auroc=0.9689

[Epoch 03] train_loss=0.2284 | val_loss=0.1729 | val_mcc=0.7881 | val_f1=0.8272 | val_auroc=0.9686

[Epoch 04] train_loss=0.2005 | val_loss=0.1915 | val_mcc=0.7814 | val_f1=0.8239 | val_auroc=0.9679

[Epoch 05] train_loss=0.1633 | val_loss=0.1947 | val_mcc=0.7800 | val_f1=0.8227 | val_auroc=0.9652

[Epoch 06] train_loss=0.1269 | val_loss=0.2195 | val_mcc=0.7648 | val_f1=0.8103 | val_auroc=0.9612

[Epoch 07] train_loss=0.0947 | val_loss=0.2624 | val_mcc=0.7526 | val_f1=0.8010 | val_auroc=0.9578

[Epoch 08] train_loss=0.0617 | val_loss=0.3211 | val_mcc=0.7330 | val_f1=0.7841 | val_auroc=0.9575

[Epoch 09] train_loss=0.0444 | val_loss=0.3012 | val_mcc=0.7443 | val_f1=0.7944 | val_auroc=0.9555
[EarlyStop] epoch=9 | best_val_mcc=0.7881
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7829 | F1=0.8379 | AUROC=0.9639 | AUPRC=0.9246
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7911 | F1=0.8795 | AUROC=0.9741 | AUPRC=0.9756
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4454 | F1=0.7136 | AUROC=0.7889 | AUPRC=0.7803
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6279 | F1=0.8045 | AUROC=0.9007 | AUPRC=0.8898
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3786 | val_loss=0.2199 | val_mcc=0.7426 | val_f1=0.7924 | val_auroc=0.9641

[Epoch 02] train_loss=0.2597 | val_loss=0.1861 | val_mcc=0.7753 | val_f1=0.8191 | val_auroc=0.9693

[Epoch 03] train_loss=0.2205 | val_loss=0.1985 | val_mcc=0.7672 | val_f1=0.8121 | val_auroc=0.9688

[Epoch 04] train_loss=0.1857 | val_loss=0.1984 | val_mcc=0.7688 | val_f1=0.8136 | val_auroc=0.9679

[Epoch 05] train_loss=0.1512 | val_loss=0.2185 | val_mcc=0.7524 | val_f1=0.8005 | val_auroc=0.9650

[Epoch 06] train_loss=0.1142 | val_loss=0.2409 | val_mcc=0.7436 | val_f1=0.7933 | val_auroc=0.9625

[Epoch 07] train_loss=0.0768 | val_loss=0.2478 | val_mcc=0.7496 | val_f1=0.7980 | val_auroc=0.9632

[Epoch 08] train_loss=0.0600 | val_loss=0.2670 | val_mcc=0.7457 | val_f1=0.7949 | val_auroc=0.9611
[EarlyStop] epoch=8 | best_val_mcc=0.7753
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7827 | F1=0.8433 | AUROC=0.9641 | AUPRC=0.9254
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8110 | F1=0.9004 | AUROC=0.9737 | AUPRC=0.9735
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4649 | F1=0.7448 | AUROC=0.7949 | AUPRC=0.7858
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5847 | F1=0.7886 | AUROC=0.9034 | AUPRC=0.8903
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 208.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7972 | F1=0.8537 | AUROC=0.9696 | AUPRC=0.9344
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8757 | F1=0.9353 | AUROC=0.9844 | AUPRC=0.9850
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4502 | F1=0.7425 | AUROC=0.7906 | AUPRC=0.7698
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5672 | F1=0.7805 | AUROC=0.9075 | AUPRC=0.8874
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 181.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7842 | F1=0.8444 | AUROC=0.9660 | AUPRC=0.9285
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8586 | F1=0.9265 | AUROC=0.9798 | AUPRC=0.9808
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4454 | F1=0.7382 | AUROC=0.7885 | AUPRC=0.7805
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5813 | F1=0.7867 | AUROC=0.8992 | AUPRC=0.8814
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 87.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7889 | F1=0.8478 | AUROC=0.9641 | AUPRC=0.9247
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8338 | F1=0.9123 | AUROC=0.9778 | AUPRC=0.9776
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4612 | F1=0.7444 | AUROC=0.7843 | AUPRC=0.7722
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5967 | F1=0.7941 | AUROC=0.9052 | AUPRC=0.8874
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 123.
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7891 | F1=0.8480 | AUROC=0.9639 | AUPRC=0.9244
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8522 | F1=0.9244 | AUROC=0.9744 | AUPRC=0.9747
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.3850 | val_loss=0.2173 | val_mcc=0.7395 | val_f1=0.7905 | val_auroc=0.9608

[Epoch 02] train_loss=0.2587 | val_loss=0.2054 | val_mcc=0.7495 | val_f1=0.7985 | val_auroc=0.9633

[Epoch 03] train_loss=0.2182 | val_loss=0.2095 | val_mcc=0.7517 | val_f1=0.8001 | val_auroc=0.9630

[Epoch 04] train_loss=0.1839 | val_loss=0.2236 | val_mcc=0.7441 | val_f1=0.7937 | val_auroc=0.9614

[Epoch 05] train_loss=0.1459 | val_loss=0.2579 | val_mcc=0.7205 | val_f1=0.7742 | val_auroc=0.9576

[Epoch 06] train_loss=0.1104 | val_loss=0.2699 | val_mcc=0.7163 | val_f1=0.7716 | val_auroc=0.9542

[Epoch 07] train_loss=0.0816 | val_loss=0.2923 | val_mcc=0.7154 | val_f1=0.7709 | val_auroc=0.9527

[Epoch 08] train_loss=0.0509 | val_loss=0.2963 | val_mcc=0.7234 | val_f1=0.7774 | val_auroc=0.9548

[Epoch 09] train_loss=0.0414 | val_loss=0.3170 | val_mcc=0.7230 | val_f1=0.7768 | val_auroc=0.9537
[EarlyStop] epoch=9 | best_val_mcc=0.7517
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7763 | F1=0.8388 | AUROC=0.9610 | AUPRC=0.9141
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8230 | F1=0.9058 | AUROC=0.9673 | AUPRC=0.9682
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3984 | F1=0.7136 | AUROC=0.7748 | AUPRC=0.7559
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5799 | F1=0.7864 | AUROC=0.8930 | AUPRC=0.8757
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3644 | val_loss=0.2032 | val_mcc=0.7521 | val_f1=0.8006 | val_auroc=0.9619

[Epoch 02] train_loss=0.2728 | val_loss=0.1926 | val_mcc=0.7666 | val_f1=0.8121 | val_auroc=0.9658

[Epoch 03] train_loss=0.2374 | val_loss=0.2374 | val_mcc=0.7343 | val_f1=0.7843 | val_auroc=0.9617

[Epoch 04] train_loss=0.2063 | val_loss=0.2561 | val_mcc=0.7170 | val_f1=0.7701 | val_auroc=0.9583

[Epoch 05] train_loss=0.1706 | val_loss=0.2537 | val_mcc=0.7190 | val_f1=0.7741 | val_auroc=0.9503

[Epoch 06] train_loss=0.1363 | val_loss=0.2836 | val_mcc=0.7224 | val_f1=0.7764 | val_auroc=0.9523

[Epoch 07] train_loss=0.0898 | val_loss=0.3253 | val_mcc=0.7027 | val_f1=0.7608 | val_auroc=0.9459

[Epoch 08] train_loss=0.0703 | val_loss=0.3382 | val_mcc=0.7039 | val_f1=0.7620 | val_auroc=0.9463
[EarlyStop] epoch=8 | best_val_mcc=0.7666
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7808 | F1=0.8419 | AUROC=0.9623 | AUPRC=0.9166
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8181 | F1=0.9023 | AUROC=0.9715 | AUPRC=0.9728
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4571 | F1=0.7375 | AUROC=0.7855 | AUPRC=0.7711
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5616 | F1=0.7781 | AUROC=0.8930 | AUPRC=0.8746
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3717 | val_loss=0.2196 | val_mcc=0.7392 | val_f1=0.7901 | val_auroc=0.9607

[Epoch 02] train_loss=0.2620 | val_loss=0.2476 | val_mcc=0.7236 | val_f1=0.7742 | val_auroc=0.9630

[Epoch 03] train_loss=0.2266 | val_loss=0.2166 | val_mcc=0.7487 | val_f1=0.7977 | val_auroc=0.9606

[Epoch 04] train_loss=0.1915 | val_loss=0.2285 | val_mcc=0.7409 | val_f1=0.7916 | val_auroc=0.9577

[Epoch 05] train_loss=0.1518 | val_loss=0.2534 | val_mcc=0.7309 | val_f1=0.7836 | val_auroc=0.9526

[Epoch 06] train_loss=0.1094 | val_loss=0.3328 | val_mcc=0.7049 | val_f1=0.7614 | val_auroc=0.9468

[Epoch 07] train_loss=0.0859 | val_loss=0.3160 | val_mcc=0.7176 | val_f1=0.7729 | val_auroc=0.9476

[Epoch 08] train_loss=0.0519 | val_loss=0.3406 | val_mcc=0.7176 | val_f1=0.7728 | val_auroc=0.9482

[Epoch 09] train_loss=0.0368 | val_loss=0.3648 | val_mcc=0.7133 | val_f1=0.7692 | val_auroc=0.9480
[EarlyStop] epoch=9 | best_val_mcc=0.7487
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7643 | F1=0.8302 | AUROC=0.9603 | AUPRC=0.9117
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8018 | F1=0.8926 | AUROC=0.9691 | AUPRC=0.9693
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4273 | F1=0.7243 | AUROC=0.7808 | AUPRC=0.7750
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5859 | F1=0.7891 | AUROC=0.8986 | AUPRC=0.8839
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3817 | val_loss=0.2293 | val_mcc=0.7417 | val_f1=0.7919 | val_auroc=0.9611

[Epoch 02] train_loss=0.2618 | val_loss=0.2038 | val_mcc=0.7590 | val_f1=0.8060 | val_auroc=0.9647

[Epoch 03] train_loss=0.2203 | val_loss=0.2134 | val_mcc=0.7533 | val_f1=0.8011 | val_auroc=0.9636

[Epoch 04] train_loss=0.1858 | val_loss=0.2405 | val_mcc=0.7292 | val_f1=0.7810 | val_auroc=0.9608

[Epoch 05] train_loss=0.1429 | val_loss=0.2513 | val_mcc=0.7334 | val_f1=0.7846 | val_auroc=0.9604

[Epoch 06] train_loss=0.1030 | val_loss=0.2680 | val_mcc=0.7310 | val_f1=0.7830 | val_auroc=0.9562

[Epoch 07] train_loss=0.0668 | val_loss=0.2717 | val_mcc=0.7381 | val_f1=0.7889 | val_auroc=0.9566

[Epoch 08] train_loss=0.0493 | val_loss=0.2872 | val_mcc=0.7376 | val_f1=0.7887 | val_auroc=0.9556
[EarlyStop] epoch=8 | best_val_mcc=0.7590
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7747 | F1=0.8375 | AUROC=0.9618 | AUPRC=0.9160
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8086 | F1=0.8985 | AUROC=0.9686 | AUPRC=0.9700
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4246 | F1=0.7236 | AUROC=0.7782 | AUPRC=0.7657
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5729 | F1=0.7832 | AUROC=0.8933 | AUPRC=0.8790
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 193.
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7815 | F1=0.8425 | AUROC=0.9666 | AUPRC=0.9243
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8522 | F1=0.9244 | AUROC=0.9841 | AUPRC=0.9846
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4217 | F1=0.7282 | AUROC=0.7824 | AUPRC=0.7688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5553 | F1=0.7746 | AUROC=0.9101 | AUPRC=0.8940
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 164.
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7775 | F1=0.8396 | AUROC=0.9641 | AUPRC=0.9223
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8436 | F1=0.9204 | AUROC=0.9733 | AUPRC=0.9752
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4478 | F1=0.7385 | AUROC=0.7856 | AUPRC=0.7749
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5664 | F1=0.7799 | AUROC=0.8985 | AUPRC=0.8801
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 101.
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7839 | F1=0.8442 | AUROC=0.9626 | AUPRC=0.9182
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8048 | F1=0.8981 | AUROC=0.9712 | AUPRC=0.9713
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4336 | F1=0.7309 | AUROC=0.7825 | AUPRC=0.7737
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5659 | F1=0.7800 | AUROC=0.8971 | AUPRC=0.8783
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 91.
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7694 | F1=0.8339 | AUROC=0.9621 | AUPRC=0.9155
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8360 | F1=0.9145 | AUROC=0.9747 | AUPRC=0.9752
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4327 | F1=0.7315 | AUROC=0.7848 | AUPRC=0.7783
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.3684 | val_loss=0.2185 | val_mcc=0.7507 | val_f1=0.7989 | val_auroc=0.9624

[Epoch 02] train_loss=0.2685 | val_loss=0.2129 | val_mcc=0.7527 | val_f1=0.8000 | val_auroc=0.9665

[Epoch 03] train_loss=0.2486 | val_loss=0.2282 | val_mcc=0.7481 | val_f1=0.7948 | val_auroc=0.9666

[Epoch 04] train_loss=0.2348 | val_loss=0.2156 | val_mcc=0.7498 | val_f1=0.7975 | val_auroc=0.9661

[Epoch 05] train_loss=0.2206 | val_loss=0.2188 | val_mcc=0.7539 | val_f1=0.8003 | val_auroc=0.9673

[Epoch 06] train_loss=0.2084 | val_loss=0.2038 | val_mcc=0.7666 | val_f1=0.8114 | val_auroc=0.9683

[Epoch 07] train_loss=0.1953 | val_loss=0.1984 | val_mcc=0.7633 | val_f1=0.8095 | val_auroc=0.9663

[Epoch 08] train_loss=0.1842 | val_loss=0.2234 | val_mcc=0.7568 | val_f1=0.8034 | val_auroc=0.9649

[Epoch 09] train_loss=0.1748 | val_loss=0.2203 | val_mcc=0.7604 | val_f1=0.8067 | val_auroc=0.9646

[Epoch 10] train_loss=0.1623 | val_loss=0.2160 | val_mcc=0.7482 | val_f1=0.7974 | val_auroc=0.9622

[Epoch 11] train_loss=0.1432 | val_loss=0.2172 | val_mcc=0.7670 | val_f1=0.8125 | val_auroc=0.9647

[Epoch 12] train_loss=0.1265 | val_loss=0.2299 | val_mcc=0.7533 | val_f1=0.8014 | val_auroc=0.9628

[Epoch 13] train_loss=0.1194 | val_loss=0.2498 | val_mcc=0.7452 | val_f1=0.7943 | val_auroc=0.9624

[Epoch 14] train_loss=0.1121 | val_loss=0.2624 | val_mcc=0.7408 | val_f1=0.7905 | val_auroc=0.9618

[Epoch 15] train_loss=0.1066 | val_loss=0.2567 | val_mcc=0.7384 | val_f1=0.7893 | val_auroc=0.9607

[Epoch 16] train_loss=0.0923 | val_loss=0.2659 | val_mcc=0.7419 | val_f1=0.7916 | val_auroc=0.9615

[Epoch 17] train_loss=0.0879 | val_loss=0.2750 | val_mcc=0.7406 | val_f1=0.7907 | val_auroc=0.9605
[EarlyStop] epoch=17 | best_val_mcc=0.7670
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7768 | F1=0.8388 | AUROC=0.9576 | AUPRC=0.9108
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8150 | F1=0.9009 | AUROC=0.9669 | AUPRC=0.9662
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4554 | F1=0.7362 | AUROC=0.7844 | AUPRC=0.7760
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6230 | F1=0.8063 | AUROC=0.8985 | AUPRC=0.8857
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3750 | val_loss=0.2044 | val_mcc=0.7474 | val_f1=0.7962 | val_auroc=0.9598

[Epoch 02] train_loss=0.2800 | val_loss=0.2250 | val_mcc=0.7441 | val_f1=0.7923 | val_auroc=0.9661

[Epoch 03] train_loss=0.2634 | val_loss=0.1901 | val_mcc=0.7706 | val_f1=0.8152 | val_auroc=0.9666

[Epoch 04] train_loss=0.2460 | val_loss=0.2069 | val_mcc=0.7637 | val_f1=0.8091 | val_auroc=0.9682

[Epoch 05] train_loss=0.2317 | val_loss=0.2500 | val_mcc=0.7261 | val_f1=0.7765 | val_auroc=0.9643

[Epoch 06] train_loss=0.2222 | val_loss=0.2077 | val_mcc=0.7588 | val_f1=0.8059 | val_auroc=0.9643

[Epoch 07] train_loss=0.2073 | val_loss=0.2285 | val_mcc=0.7484 | val_f1=0.7967 | val_auroc=0.9652

[Epoch 08] train_loss=0.1838 | val_loss=0.2143 | val_mcc=0.7581 | val_f1=0.8052 | val_auroc=0.9656

[Epoch 09] train_loss=0.1729 | val_loss=0.2265 | val_mcc=0.7491 | val_f1=0.7978 | val_auroc=0.9645
[EarlyStop] epoch=9 | best_val_mcc=0.7706
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7868 | F1=0.8459 | AUROC=0.9638 | AUPRC=0.9203
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7952 | F1=0.8902 | AUROC=0.9700 | AUPRC=0.9690
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4425 | F1=0.7265 | AUROC=0.7876 | AUPRC=0.7749
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5798 | F1=0.7863 | AUROC=0.8982 | AUPRC=0.8852
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3724 | val_loss=0.2038 | val_mcc=0.7542 | val_f1=0.8023 | val_auroc=0.9642

[Epoch 02] train_loss=0.2730 | val_loss=0.1962 | val_mcc=0.7610 | val_f1=0.8077 | val_auroc=0.9659

[Epoch 03] train_loss=0.2542 | val_loss=0.2022 | val_mcc=0.7527 | val_f1=0.8007 | val_auroc=0.9666

[Epoch 04] train_loss=0.2424 | val_loss=0.2014 | val_mcc=0.7615 | val_f1=0.8080 | val_auroc=0.9662

[Epoch 05] train_loss=0.2258 | val_loss=0.2250 | val_mcc=0.7498 | val_f1=0.7971 | val_auroc=0.9660

[Epoch 06] train_loss=0.2155 | val_loss=0.2306 | val_mcc=0.7544 | val_f1=0.8001 | val_auroc=0.9669

[Epoch 07] train_loss=0.2024 | val_loss=0.2049 | val_mcc=0.7635 | val_f1=0.8095 | val_auroc=0.9660

[Epoch 08] train_loss=0.1874 | val_loss=0.2235 | val_mcc=0.7523 | val_f1=0.7992 | val_auroc=0.9666

[Epoch 09] train_loss=0.1750 | val_loss=0.2212 | val_mcc=0.7547 | val_f1=0.8026 | val_auroc=0.9613

[Epoch 10] train_loss=0.1638 | val_loss=0.2418 | val_mcc=0.7375 | val_f1=0.7879 | val_auroc=0.9628

[Epoch 11] train_loss=0.1526 | val_loss=0.2362 | val_mcc=0.7365 | val_f1=0.7879 | val_auroc=0.9593

[Epoch 12] train_loss=0.1229 | val_loss=0.2598 | val_mcc=0.7367 | val_f1=0.7879 | val_auroc=0.9611

[Epoch 13] train_loss=0.1110 | val_loss=0.2780 | val_mcc=0.7385 | val_f1=0.7894 | val_auroc=0.9569
[EarlyStop] epoch=13 | best_val_mcc=0.7635
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7808 | F1=0.8419 | AUROC=0.9623 | AUPRC=0.9171
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8059 | F1=0.8969 | AUROC=0.9700 | AUPRC=0.9666
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4359 | F1=0.7308 | AUROC=0.7852 | AUPRC=0.7737
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5799 | F1=0.7862 | AUROC=0.8981 | AUPRC=0.8881
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3677 | val_loss=0.2097 | val_mcc=0.7532 | val_f1=0.8011 | val_auroc=0.9632

[Epoch 02] train_loss=0.2683 | val_loss=0.2123 | val_mcc=0.7586 | val_f1=0.8046 | val_auroc=0.9655

[Epoch 03] train_loss=0.2510 | val_loss=0.2077 | val_mcc=0.7582 | val_f1=0.8044 | val_auroc=0.9675

[Epoch 04] train_loss=0.2306 | val_loss=0.1977 | val_mcc=0.7733 | val_f1=0.8171 | val_auroc=0.9684

[Epoch 05] train_loss=0.2151 | val_loss=0.1928 | val_mcc=0.7720 | val_f1=0.8164 | val_auroc=0.9679

[Epoch 06] train_loss=0.2027 | val_loss=0.2008 | val_mcc=0.7634 | val_f1=0.8092 | val_auroc=0.9669

[Epoch 07] train_loss=0.1868 | val_loss=0.2236 | val_mcc=0.7477 | val_f1=0.7959 | val_auroc=0.9653

[Epoch 08] train_loss=0.1781 | val_loss=0.2276 | val_mcc=0.7493 | val_f1=0.7967 | val_auroc=0.9659

[Epoch 09] train_loss=0.1517 | val_loss=0.2109 | val_mcc=0.7616 | val_f1=0.8080 | val_auroc=0.9662

[Epoch 10] train_loss=0.1417 | val_loss=0.2226 | val_mcc=0.7616 | val_f1=0.8079 | val_auroc=0.9644
[EarlyStop] epoch=10 | best_val_mcc=0.7733
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7823 | F1=0.8431 | AUROC=0.9657 | AUPRC=0.9248
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8281 | F1=0.9094 | AUROC=0.9738 | AUPRC=0.9731
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4353 | F1=0.7322 | AUROC=0.7866 | AUPRC=0.7720
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5743 | F1=0.7837 | AUROC=0.8997 | AUPRC=0.8892
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 217.
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7924 | F1=0.8503 | AUROC=0.9678 | AUPRC=0.9286
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8525 | F1=0.9240 | AUROC=0.9836 | AUPRC=0.9839
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4423 | F1=0.7385 | AUROC=0.7868 | AUPRC=0.7664
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5557 | F1=0.7751 | AUROC=0.9053 | AUPRC=0.8883
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 211.
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7781 | F1=0.8401 | AUROC=0.9638 | AUPRC=0.9211
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8328 | F1=0.9134 | AUROC=0.9741 | AUPRC=0.9727
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4325 | F1=0.7332 | AUROC=0.7876 | AUPRC=0.7727
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5518 | F1=0.7735 | AUROC=0.9008 | AUPRC=0.8830
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 97.
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7823 | F1=0.8431 | AUROC=0.9649 | AUPRC=0.9249
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8194 | F1=0.9050 | AUROC=0.9722 | AUPRC=0.9724
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4323 | F1=0.7329 | AUROC=0.7835 | AUPRC=0.7745
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5600 | F1=0.7773 | AUROC=0.8992 | AUPRC=0.8873
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 136.
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7818 | F1=0.8428 | AUROC=0.9657 | AUPRC=0.9241
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8099 | F1=0.9019 | AUROC=0.9740 | AUPRC=0.9723
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4384 | F1=0.7336 | AUROC=0.7909 | AUPRC=0.7772
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.3766 | val_loss=0.2103 | val_mcc=0.7496 | val_f1=0.7986 | val_auroc=0.9618

[Epoch 02] train_loss=0.2607 | val_loss=0.2040 | val_mcc=0.7634 | val_f1=0.8095 | val_auroc=0.9647

[Epoch 03] train_loss=0.2316 | val_loss=0.1970 | val_mcc=0.7667 | val_f1=0.8122 | val_auroc=0.9661

[Epoch 04] train_loss=0.2086 | val_loss=0.2122 | val_mcc=0.7564 | val_f1=0.8035 | val_auroc=0.9651

[Epoch 05] train_loss=0.1859 | val_loss=0.2097 | val_mcc=0.7628 | val_f1=0.8091 | val_auroc=0.9634

[Epoch 06] train_loss=0.1654 | val_loss=0.2142 | val_mcc=0.7556 | val_f1=0.8033 | val_auroc=0.9637

[Epoch 07] train_loss=0.1447 | val_loss=0.2461 | val_mcc=0.7405 | val_f1=0.7909 | val_auroc=0.9608

[Epoch 08] train_loss=0.1141 | val_loss=0.2387 | val_mcc=0.7483 | val_f1=0.7972 | val_auroc=0.9620

[Epoch 09] train_loss=0.1007 | val_loss=0.2484 | val_mcc=0.7411 | val_f1=0.7916 | val_auroc=0.9609
[EarlyStop] epoch=9 | best_val_mcc=0.7667
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7797 | F1=0.8410 | AUROC=0.9625 | AUPRC=0.9206
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8291 | F1=0.9085 | AUROC=0.9738 | AUPRC=0.9741
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4452 | F1=0.7321 | AUROC=0.7821 | AUPRC=0.7727
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5640 | F1=0.7792 | AUROC=0.8925 | AUPRC=0.8753
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3757 | val_loss=0.2069 | val_mcc=0.7546 | val_f1=0.8025 | val_auroc=0.9633

[Epoch 02] train_loss=0.2728 | val_loss=0.2159 | val_mcc=0.7536 | val_f1=0.8008 | val_auroc=0.9649

[Epoch 03] train_loss=0.2502 | val_loss=0.2560 | val_mcc=0.7221 | val_f1=0.7720 | val_auroc=0.9641

[Epoch 04] train_loss=0.2280 | val_loss=0.1983 | val_mcc=0.7559 | val_f1=0.8034 | val_auroc=0.9626

[Epoch 05] train_loss=0.2067 | val_loss=0.2217 | val_mcc=0.7507 | val_f1=0.7990 | val_auroc=0.9630

[Epoch 06] train_loss=0.1869 | val_loss=0.2393 | val_mcc=0.7366 | val_f1=0.7870 | val_auroc=0.9610

[Epoch 07] train_loss=0.1689 | val_loss=0.2615 | val_mcc=0.7195 | val_f1=0.7728 | val_auroc=0.9582

[Epoch 08] train_loss=0.1501 | val_loss=0.2412 | val_mcc=0.7364 | val_f1=0.7878 | val_auroc=0.9585

[Epoch 09] train_loss=0.1210 | val_loss=0.2606 | val_mcc=0.7364 | val_f1=0.7880 | val_auroc=0.9560

[Epoch 10] train_loss=0.1039 | val_loss=0.2649 | val_mcc=0.7388 | val_f1=0.7899 | val_auroc=0.9563
[EarlyStop] epoch=10 | best_val_mcc=0.7559
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7762 | F1=0.8376 | AUROC=0.9600 | AUPRC=0.9129
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7944 | F1=0.8872 | AUROC=0.9709 | AUPRC=0.9713
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4515 | F1=0.7313 | AUROC=0.7773 | AUPRC=0.7628
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5683 | F1=0.7807 | AUROC=0.8816 | AUPRC=0.8590
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3747 | val_loss=0.2068 | val_mcc=0.7559 | val_f1=0.8036 | val_auroc=0.9621

[Epoch 02] train_loss=0.2678 | val_loss=0.2138 | val_mcc=0.7489 | val_f1=0.7974 | val_auroc=0.9636

[Epoch 03] train_loss=0.2407 | val_loss=0.2133 | val_mcc=0.7560 | val_f1=0.8028 | val_auroc=0.9657

[Epoch 04] train_loss=0.2163 | val_loss=0.2070 | val_mcc=0.7569 | val_f1=0.8041 | val_auroc=0.9656

[Epoch 05] train_loss=0.1938 | val_loss=0.2175 | val_mcc=0.7520 | val_f1=0.8002 | val_auroc=0.9622

[Epoch 06] train_loss=0.1726 | val_loss=0.2614 | val_mcc=0.7246 | val_f1=0.7764 | val_auroc=0.9606

[Epoch 07] train_loss=0.1519 | val_loss=0.2390 | val_mcc=0.7418 | val_f1=0.7924 | val_auroc=0.9584

[Epoch 08] train_loss=0.1350 | val_loss=0.2791 | val_mcc=0.7195 | val_f1=0.7733 | val_auroc=0.9576

[Epoch 09] train_loss=0.0969 | val_loss=0.2881 | val_mcc=0.7228 | val_f1=0.7763 | val_auroc=0.9569

[Epoch 10] train_loss=0.0822 | val_loss=0.3030 | val_mcc=0.7243 | val_f1=0.7775 | val_auroc=0.9571
[EarlyStop] epoch=10 | best_val_mcc=0.7569
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7699 | F1=0.8342 | AUROC=0.9595 | AUPRC=0.9146
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8020 | F1=0.8964 | AUROC=0.9650 | AUPRC=0.9659
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4305 | F1=0.7295 | AUROC=0.7798 | AUPRC=0.7648
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5595 | F1=0.7772 | AUROC=0.8900 | AUPRC=0.8747
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3749 | val_loss=0.2182 | val_mcc=0.7516 | val_f1=0.7999 | val_auroc=0.9622

[Epoch 02] train_loss=0.2626 | val_loss=0.2029 | val_mcc=0.7663 | val_f1=0.8118 | val_auroc=0.9647

[Epoch 03] train_loss=0.2305 | val_loss=0.1982 | val_mcc=0.7693 | val_f1=0.8143 | val_auroc=0.9657

[Epoch 04] train_loss=0.2036 | val_loss=0.2113 | val_mcc=0.7613 | val_f1=0.8075 | val_auroc=0.9641

[Epoch 05] train_loss=0.1767 | val_loss=0.2251 | val_mcc=0.7423 | val_f1=0.7924 | val_auroc=0.9618

[Epoch 06] train_loss=0.1549 | val_loss=0.2240 | val_mcc=0.7517 | val_f1=0.8001 | val_auroc=0.9624

[Epoch 07] train_loss=0.1308 | val_loss=0.2322 | val_mcc=0.7506 | val_f1=0.7992 | val_auroc=0.9612

[Epoch 08] train_loss=0.1002 | val_loss=0.2409 | val_mcc=0.7441 | val_f1=0.7942 | val_auroc=0.9599

[Epoch 09] train_loss=0.0822 | val_loss=0.2660 | val_mcc=0.7406 | val_f1=0.7910 | val_auroc=0.9589
[EarlyStop] epoch=9 | best_val_mcc=0.7693
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7760 | F1=0.8385 | AUROC=0.9623 | AUPRC=0.9176
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8194 | F1=0.9050 | AUROC=0.9710 | AUPRC=0.9717
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4369 | F1=0.7301 | AUROC=0.7850 | AUPRC=0.7663
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5785 | F1=0.7858 | AUROC=0.8973 | AUPRC=0.8802
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 215.
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7882 | F1=0.8472 | AUROC=0.9671 | AUPRC=0.9261
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8580 | F1=0.9271 | AUROC=0.9836 | AUPRC=0.9843
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4343 | F1=0.7362 | AUROC=0.7864 | AUPRC=0.7751
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5512 | F1=0.7730 | AUROC=0.9043 | AUPRC=0.8890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 171.
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7789 | F1=0.8406 | AUROC=0.9650 | AUPRC=0.9243
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8299 | F1=0.9120 | AUROC=0.9752 | AUPRC=0.9753
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4440 | F1=0.7377 | AUROC=0.7865 | AUPRC=0.7725
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5834 | F1=0.7874 | AUROC=0.9034 | AUPRC=0.8902
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 95.
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7731 | F1=0.8365 | AUROC=0.9646 | AUPRC=0.9212
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8335 | F1=0.9126 | AUROC=0.9758 | AUPRC=0.9758
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4175 | F1=0.7266 | AUROC=0.7848 | AUPRC=0.7650
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5673 | F1=0.7806 | AUROC=0.9021 | AUPRC=0.8860
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 129.
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7821 | F1=0.8429 | AUROC=0.9652 | AUPRC=0.9243
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8439 | F1=0.9197 | AUROC=0.9727 | AUPRC=0.9736
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_center_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4329 | F1=0.7340 | AUROC=0.7893 | AUPRC=0.7832
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5881 | val_loss=0.4404 | val_mcc=0.4544 | val_f1=0.5629 | val_auroc=0.8209

[Epoch 02] train_loss=0.5111 | val_loss=0.4518 | val_mcc=0.4761 | val_f1=0.5826 | val_auroc=0.8347

[Epoch 03] train_loss=0.4794 | val_loss=0.4784 | val_mcc=0.4677 | val_f1=0.5776 | val_auroc=0.8438

[Epoch 04] train_loss=0.4513 | val_loss=0.4182 | val_mcc=0.4927 | val_f1=0.5964 | val_auroc=0.8528

[Epoch 05] train_loss=0.4224 | val_loss=0.4606 | val_mcc=0.4844 | val_f1=0.5899 | val_auroc=0.8555

[Epoch 06] train_loss=0.3884 | val_loss=0.4082 | val_mcc=0.4965 | val_f1=0.5984 | val_auroc=0.8595

[Epoch 07] train_loss=0.3497 | val_loss=0.4947 | val_mcc=0.5009 | val_f1=0.6019 | val_auroc=0.8631

[Epoch 08] train_loss=0.3136 | val_loss=0.4939 | val_mcc=0.4956 | val_f1=0.5987 | val_auroc=0.8587

[Epoch 09] train_loss=0.2703 | val_loss=0.5406 | val_mcc=0.4780 | val_f1=0.5849 | val_auroc=0.8520

[Epoch 10] train_loss=0.2310 | val_loss=0.5995 | val_mcc=0.4812 | val_f1=0.5872 | val_auroc=0.8483

[Epoch 11] train_loss=0.1998 | val_loss=0.6548 | val_mcc=0.4629 | val_f1=0.5729 | val_auroc=0.8430

[Epoch 12] train_loss=0.1541 | val_loss=0.6310 | val_mcc=0.4760 | val_f1=0.5840 | val_auroc=0.8431

[Epoch 13] train_loss=0.1304 | val_loss=0.7645 | val_mcc=0.4506 | val_f1=0.5617 | val_auroc=0.8400
[EarlyStop] epoch=13 | best_val_mcc=0.5009
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5631 | F1=0.6900 | AUROC=0.8727 | AUPRC=0.7501
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5451 | F1=0.7647 | AUROC=0.8387 | AUPRC=0.8361
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3258 | F1=0.6725 | AUROC=0.7241 | AUPRC=0.7025
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5480 | F1=0.7609 | AUROC=0.8355 | AUPRC=0.8018
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5847 | val_loss=0.4637 | val_mcc=0.4650 | val_f1=0.5746 | val_auroc=0.8252

[Epoch 02] train_loss=0.5096 | val_loss=0.4956 | val_mcc=0.4727 | val_f1=0.5812 | val_auroc=0.8370

[Epoch 03] train_loss=0.4784 | val_loss=0.5320 | val_mcc=0.4537 | val_f1=0.5649 | val_auroc=0.8437

[Epoch 04] train_loss=0.4443 | val_loss=0.4609 | val_mcc=0.4803 | val_f1=0.5873 | val_auroc=0.8490

[Epoch 05] train_loss=0.4138 | val_loss=0.4731 | val_mcc=0.4930 | val_f1=0.5968 | val_auroc=0.8565

[Epoch 06] train_loss=0.3800 | val_loss=0.5293 | val_mcc=0.4738 | val_f1=0.5806 | val_auroc=0.8546

[Epoch 07] train_loss=0.3420 | val_loss=0.4756 | val_mcc=0.4867 | val_f1=0.5921 | val_auroc=0.8454

[Epoch 08] train_loss=0.3054 | val_loss=0.5266 | val_mcc=0.4836 | val_f1=0.5895 | val_auroc=0.8463

[Epoch 09] train_loss=0.2730 | val_loss=0.5744 | val_mcc=0.4911 | val_f1=0.5956 | val_auroc=0.8460

[Epoch 10] train_loss=0.2173 | val_loss=0.7748 | val_mcc=0.4547 | val_f1=0.5659 | val_auroc=0.8332

[Epoch 11] train_loss=0.2005 | val_loss=0.7678 | val_mcc=0.4652 | val_f1=0.5750 | val_auroc=0.8382
[EarlyStop] epoch=11 | best_val_mcc=0.4930
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5584 | F1=0.6857 | AUROC=0.8691 | AUPRC=0.7441
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5079 | F1=0.7467 | AUROC=0.8316 | AUPRC=0.8338
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3325 | F1=0.6696 | AUROC=0.7289 | AUPRC=0.7088
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5424 | F1=0.7539 | AUROC=0.8346 | AUPRC=0.7969
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5771 | val_loss=0.3928 | val_mcc=0.4514 | val_f1=0.5490 | val_auroc=0.8322

[Epoch 02] train_loss=0.5049 | val_loss=0.3726 | val_mcc=0.4778 | val_f1=0.5701 | val_auroc=0.8455

[Epoch 03] train_loss=0.4734 | val_loss=0.4094 | val_mcc=0.4987 | val_f1=0.6005 | val_auroc=0.8528

[Epoch 04] train_loss=0.4422 | val_loss=0.4338 | val_mcc=0.4987 | val_f1=0.6014 | val_auroc=0.8612

[Epoch 05] train_loss=0.4056 | val_loss=0.4148 | val_mcc=0.5026 | val_f1=0.6039 | val_auroc=0.8613

[Epoch 06] train_loss=0.3649 | val_loss=0.3889 | val_mcc=0.4978 | val_f1=0.5855 | val_auroc=0.8622

[Epoch 07] train_loss=0.3223 | val_loss=0.4865 | val_mcc=0.4897 | val_f1=0.5940 | val_auroc=0.8537

[Epoch 08] train_loss=0.2777 | val_loss=0.5087 | val_mcc=0.4936 | val_f1=0.5941 | val_auroc=0.8508

[Epoch 09] train_loss=0.2466 | val_loss=0.6424 | val_mcc=0.4837 | val_f1=0.5894 | val_auroc=0.8526

[Epoch 10] train_loss=0.1924 | val_loss=0.6693 | val_mcc=0.4772 | val_f1=0.5840 | val_auroc=0.8387

[Epoch 11] train_loss=0.1657 | val_loss=0.6873 | val_mcc=0.4700 | val_f1=0.5778 | val_auroc=0.8244
[EarlyStop] epoch=11 | best_val_mcc=0.5026
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5737 | F1=0.6928 | AUROC=0.8756 | AUPRC=0.7529
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5175 | F1=0.7365 | AUROC=0.8357 | AUPRC=0.8358
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3416 | F1=0.6615 | AUROC=0.7266 | AUPRC=0.7039
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5290 | F1=0.7376 | AUROC=0.8410 | AUPRC=0.8084
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5824 | val_loss=0.4554 | val_mcc=0.4579 | val_f1=0.5685 | val_auroc=0.8248

[Epoch 02] train_loss=0.5046 | val_loss=0.4037 | val_mcc=0.4842 | val_f1=0.5849 | val_auroc=0.8394

[Epoch 03] train_loss=0.4711 | val_loss=0.4129 | val_mcc=0.4933 | val_f1=0.5958 | val_auroc=0.8486

[Epoch 04] train_loss=0.4416 | val_loss=0.3874 | val_mcc=0.4968 | val_f1=0.5962 | val_auroc=0.8561

[Epoch 05] train_loss=0.4038 | val_loss=0.4059 | val_mcc=0.4993 | val_f1=0.6012 | val_auroc=0.8620

[Epoch 06] train_loss=0.3668 | val_loss=0.4626 | val_mcc=0.4917 | val_f1=0.5959 | val_auroc=0.8598

[Epoch 07] train_loss=0.3240 | val_loss=0.4338 | val_mcc=0.4917 | val_f1=0.5950 | val_auroc=0.8571

[Epoch 08] train_loss=0.2777 | val_loss=0.5576 | val_mcc=0.4757 | val_f1=0.5826 | val_auroc=0.8510

[Epoch 09] train_loss=0.2346 | val_loss=0.6448 | val_mcc=0.4563 | val_f1=0.5664 | val_auroc=0.8475

[Epoch 10] train_loss=0.1771 | val_loss=0.6573 | val_mcc=0.4587 | val_f1=0.5694 | val_auroc=0.8447

[Epoch 11] train_loss=0.1513 | val_loss=0.6309 | val_mcc=0.4701 | val_f1=0.5795 | val_auroc=0.8429
[EarlyStop] epoch=11 | best_val_mcc=0.4993
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5690 | F1=0.6891 | AUROC=0.8747 | AUPRC=0.7547
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.4739 | F1=0.7147 | AUROC=0.8296 | AUPRC=0.8241
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3242 | F1=0.6457 | AUROC=0.7217 | AUPRC=0.7050
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5207 | F1=0.7322 | AUROC=0.8418 | AUPRC=0.8097
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 160.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5458 | F1=0.6786 | AUROC=0.8636 | AUPRC=0.7209
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.4997 | F1=0.7514 | AUROC=0.8291 | AUPRC=0.8199
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3421 | F1=0.6793 | AUROC=0.7273 | AUPRC=0.7032
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4950 | F1=0.7376 | AUROC=0.8287 | AUPRC=0.7918
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 89.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5531 | F1=0.6828 | AUROC=0.8635 | AUPRC=0.7436
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4992 | F1=0.7457 | AUROC=0.8204 | AUPRC=0.8191
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3234 | F1=0.6637 | AUROC=0.7268 | AUPRC=0.7005
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5248 | F1=0.7469 | AUROC=0.8330 | AUPRC=0.8061
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 34.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5501 | F1=0.6793 | AUROC=0.8628 | AUPRC=0.7393
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5023 | F1=0.7430 | AUROC=0.8220 | AUPRC=0.8260
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3234 | F1=0.6560 | AUROC=0.7229 | AUPRC=0.7034
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5118 | F1=0.7361 | AUROC=0.8312 | AUPRC=0.7956
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 42.
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5502 | F1=0.6797 | AUROC=0.8640 | AUPRC=0.7419
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5280 | F1=0.7559 | AUROC=0.8310 | AUPRC=0.8274
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3504 | F1=0.6702 | AUROC=0.7261 | AUPRC=0.7065
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5207 | F1=0.7425 | AUROC=0.8358 | AUPRC=0.8031
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']

[Epoch 01] train_loss=0.5890 | val_loss=0.4367 | val_mcc=0.4598 | val_f1=0.5647 | val_auroc=0.8142

[Epoch 02] train_loss=0.5085 | val_loss=0.4103 | val_mcc=0.4769 | val_f1=0.5785 | val_auroc=0.8352

[Epoch 03] train_loss=0.4787 | val_loss=0.4036 | val_mcc=0.4920 | val_f1=0.5936 | val_auroc=0.8467

[Epoch 04] train_loss=0.4522 | val_loss=0.3927 | val_mcc=0.4950 | val_f1=0.5958 | val_auroc=0.8571

[Epoch 05] train_loss=0.4194 | val_loss=0.4116 | val_mcc=0.4916 | val_f1=0.5953 | val_auroc=0.8587

[Epoch 06] train_loss=0.3859 | val_loss=0.4084 | val_mcc=0.5045 | val_f1=0.6055 | val_auroc=0.8650

[Epoch 07] train_loss=0.3491 | val_loss=0.4247 | val_mcc=0.4954 | val_f1=0.5984 | val_auroc=0.8618

[Epoch 08] train_loss=0.3116 | val_loss=0.4856 | val_mcc=0.4900 | val_f1=0.5946 | val_auroc=0.8611

[Epoch 09] train_loss=0.2735 | val_loss=0.5270 | val_mcc=0.4863 | val_f1=0.5916 | val_auroc=0.8518

[Epoch 10] train_loss=0.2304 | val_loss=0.6389 | val_mcc=0.4654 | val_f1=0.5734 | val_auroc=0.8515

[Epoch 11] train_loss=0.1893 | val_loss=0.5651 | val_mcc=0.4703 | val_f1=0.5796 | val_auroc=0.8457

[Epoch 12] train_loss=0.1669 | val_loss=0.6355 | val_mcc=0.4644 | val_f1=0.5750 | val_auroc=0.8454
[EarlyStop] epoch=12 | best_val_mcc=0.5045
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5683 | F1=0.6887 | AUROC=0.8747 | AUPRC=0.7494
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.4972 | F1=0.7262 | AUROC=0.8349 | AUPRC=0.8334
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3275 | F1=0.6456 | AUROC=0.7310 | AUPRC=0.7071
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5345 | F1=0.7398 | AUROC=0.8411 | AUPRC=0.8039
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5863 | val_loss=0.4638 | val_mcc=0.4619 | val_f1=0.5718 | val_auroc=0.8241

[Epoch 02] train_loss=0.5113 | val_loss=0.4197 | val_mcc=0.4847 | val_f1=0.5878 | val_auroc=0.8378

[Epoch 03] train_loss=0.4806 | val_loss=0.4700 | val_mcc=0.4789 | val_f1=0.5862 | val_auroc=0.8458

[Epoch 04] train_loss=0.4504 | val_loss=0.4221 | val_mcc=0.4957 | val_f1=0.5980 | val_auroc=0.8547

[Epoch 05] train_loss=0.4166 | val_loss=0.4164 | val_mcc=0.5054 | val_f1=0.6051 | val_auroc=0.8560

[Epoch 06] train_loss=0.3836 | val_loss=0.4943 | val_mcc=0.4945 | val_f1=0.5976 | val_auroc=0.8572

[Epoch 07] train_loss=0.3476 | val_loss=0.4862 | val_mcc=0.4936 | val_f1=0.5974 | val_auroc=0.8518

[Epoch 08] train_loss=0.3078 | val_loss=0.5315 | val_mcc=0.4955 | val_f1=0.5990 | val_auroc=0.8519

[Epoch 09] train_loss=0.2840 | val_loss=0.5514 | val_mcc=0.4868 | val_f1=0.5921 | val_auroc=0.8428

[Epoch 10] train_loss=0.2330 | val_loss=0.7415 | val_mcc=0.4750 | val_f1=0.5807 | val_auroc=0.8438

[Epoch 11] train_loss=0.2074 | val_loss=0.7777 | val_mcc=0.4765 | val_f1=0.5829 | val_auroc=0.8393
[EarlyStop] epoch=11 | best_val_mcc=0.5054
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5687 | F1=0.6863 | AUROC=0.8705 | AUPRC=0.7474
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5129 | F1=0.7309 | AUROC=0.8400 | AUPRC=0.8436
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3363 | F1=0.6425 | AUROC=0.7303 | AUPRC=0.7109
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5206 | F1=0.7313 | AUROC=0.8461 | AUPRC=0.8093
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5804 | val_loss=0.4124 | val_mcc=0.4592 | val_f1=0.5619 | val_auroc=0.8318

[Epoch 02] train_loss=0.5051 | val_loss=0.4073 | val_mcc=0.4815 | val_f1=0.5845 | val_auroc=0.8427

[Epoch 03] train_loss=0.4769 | val_loss=0.4154 | val_mcc=0.4885 | val_f1=0.5928 | val_auroc=0.8545

[Epoch 04] train_loss=0.4469 | val_loss=0.3710 | val_mcc=0.4994 | val_f1=0.5953 | val_auroc=0.8626

[Epoch 05] train_loss=0.4161 | val_loss=0.4032 | val_mcc=0.5017 | val_f1=0.6027 | val_auroc=0.8642

[Epoch 06] train_loss=0.3801 | val_loss=0.4108 | val_mcc=0.5033 | val_f1=0.6035 | val_auroc=0.8669

[Epoch 07] train_loss=0.3434 | val_loss=0.4250 | val_mcc=0.5000 | val_f1=0.5973 | val_auroc=0.8637

[Epoch 08] train_loss=0.3016 | val_loss=0.4755 | val_mcc=0.4969 | val_f1=0.5981 | val_auroc=0.8600

[Epoch 09] train_loss=0.2606 | val_loss=0.5214 | val_mcc=0.4867 | val_f1=0.5917 | val_auroc=0.8451

[Epoch 10] train_loss=0.2254 | val_loss=0.5412 | val_mcc=0.5008 | val_f1=0.5997 | val_auroc=0.8488

[Epoch 11] train_loss=0.1823 | val_loss=0.6724 | val_mcc=0.4763 | val_f1=0.5842 | val_auroc=0.8431

[Epoch 12] train_loss=0.1566 | val_loss=0.6922 | val_mcc=0.4663 | val_f1=0.5754 | val_auroc=0.8276
[EarlyStop] epoch=12 | best_val_mcc=0.5033
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5763 | F1=0.6918 | AUROC=0.8783 | AUPRC=0.7550
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5374 | F1=0.7410 | AUROC=0.8410 | AUPRC=0.8402
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3357 | F1=0.6454 | AUROC=0.7331 | AUPRC=0.7122
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5109 | F1=0.7219 | AUROC=0.8421 | AUPRC=0.8106
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5887 | val_loss=0.4713 | val_mcc=0.4475 | val_f1=0.5606 | val_auroc=0.8142

[Epoch 02] train_loss=0.5128 | val_loss=0.4509 | val_mcc=0.4695 | val_f1=0.5786 | val_auroc=0.8333

[Epoch 03] train_loss=0.4780 | val_loss=0.4273 | val_mcc=0.4853 | val_f1=0.5909 | val_auroc=0.8492

[Epoch 04] train_loss=0.4484 | val_loss=0.4070 | val_mcc=0.4979 | val_f1=0.6002 | val_auroc=0.8576

[Epoch 05] train_loss=0.4151 | val_loss=0.4227 | val_mcc=0.4984 | val_f1=0.6012 | val_auroc=0.8626

[Epoch 06] train_loss=0.3776 | val_loss=0.4141 | val_mcc=0.5078 | val_f1=0.6082 | val_auroc=0.8658

[Epoch 07] train_loss=0.3369 | val_loss=0.4414 | val_mcc=0.4887 | val_f1=0.5938 | val_auroc=0.8616

[Epoch 08] train_loss=0.2950 | val_loss=0.4879 | val_mcc=0.4803 | val_f1=0.5872 | val_auroc=0.8558

[Epoch 09] train_loss=0.2501 | val_loss=0.5376 | val_mcc=0.4872 | val_f1=0.5922 | val_auroc=0.8558

[Epoch 10] train_loss=0.2153 | val_loss=0.5690 | val_mcc=0.4650 | val_f1=0.5756 | val_auroc=0.8484

[Epoch 11] train_loss=0.1671 | val_loss=0.6372 | val_mcc=0.4587 | val_f1=0.5701 | val_auroc=0.8477

[Epoch 12] train_loss=0.1482 | val_loss=0.6390 | val_mcc=0.4671 | val_f1=0.5770 | val_auroc=0.8462
[EarlyStop] epoch=12 | best_val_mcc=0.5078
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5619 | F1=0.6854 | AUROC=0.8774 | AUPRC=0.7574
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.4872 | F1=0.7253 | AUROC=0.8320 | AUPRC=0.8344
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3313 | F1=0.6537 | AUROC=0.7284 | AUPRC=0.7107
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5264 | F1=0.7372 | AUROC=0.8457 | AUPRC=0.8174
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 116.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5377 | F1=0.6727 | AUROC=0.8655 | AUPRC=0.7279
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5021 | F1=0.7453 | AUROC=0.8314 | AUPRC=0.8238
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3130 | F1=0.6597 | AUROC=0.7151 | AUPRC=0.6981
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5031 | F1=0.7392 | AUROC=0.8345 | AUPRC=0.8040
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 88.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5398 | F1=0.6732 | AUROC=0.8663 | AUPRC=0.7392
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5021 | F1=0.7467 | AUROC=0.8317 | AUPRC=0.8325
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3249 | F1=0.6632 | AUROC=0.7271 | AUPRC=0.7028
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5057 | F1=0.7368 | AUROC=0.8303 | AUPRC=0.7920
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 37.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5579 | F1=0.6853 | AUROC=0.8657 | AUPRC=0.7437
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5079 | F1=0.7474 | AUROC=0.8275 | AUPRC=0.8272
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3503 | F1=0.6707 | AUROC=0.7275 | AUPRC=0.7036
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5276 | F1=0.7463 | AUROC=0.8321 | AUPRC=0.7969
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 51.
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5566 | F1=0.6843 | AUROC=0.8679 | AUPRC=0.7445
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4966 | F1=0.7401 | AUROC=0.8259 | AUPRC=0.8266
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3368 | F1=0.6667 | AUROC=0.7159 | AUPRC=0.6946
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5112 | F1=0.7375 | AUROC=0.8368 | AUPRC=0.8048
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']

[Epoch 01] train_loss=0.5966 | val_loss=0.4481 | val_mcc=0.4500 | val_f1=0.5570 | val_auroc=0.8109

[Epoch 02] train_loss=0.5074 | val_loss=0.4063 | val_mcc=0.4601 | val_f1=0.5623 | val_auroc=0.8300

[Epoch 03] train_loss=0.4689 | val_loss=0.4523 | val_mcc=0.4736 | val_f1=0.5820 | val_auroc=0.8397

[Epoch 04] train_loss=0.4284 | val_loss=0.3947 | val_mcc=0.4857 | val_f1=0.5874 | val_auroc=0.8490

[Epoch 05] train_loss=0.3810 | val_loss=0.4409 | val_mcc=0.4806 | val_f1=0.5876 | val_auroc=0.8515

[Epoch 06] train_loss=0.3277 | val_loss=0.4445 | val_mcc=0.4799 | val_f1=0.5868 | val_auroc=0.8514

[Epoch 07] train_loss=0.2699 | val_loss=0.5185 | val_mcc=0.4633 | val_f1=0.5741 | val_auroc=0.8471

[Epoch 08] train_loss=0.2140 | val_loss=0.6087 | val_mcc=0.4464 | val_f1=0.5603 | val_auroc=0.8417

[Epoch 09] train_loss=0.1550 | val_loss=0.6095 | val_mcc=0.4496 | val_f1=0.5634 | val_auroc=0.8425

[Epoch 10] train_loss=0.1239 | val_loss=0.6109 | val_mcc=0.4625 | val_f1=0.5738 | val_auroc=0.8400
[EarlyStop] epoch=10 | best_val_mcc=0.4857
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5619 | F1=0.6786 | AUROC=0.8662 | AUPRC=0.7434
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5280 | F1=0.7313 | AUROC=0.8350 | AUPRC=0.8367
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3101 | F1=0.6232 | AUROC=0.7205 | AUPRC=0.7011
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5166 | F1=0.7215 | AUROC=0.8352 | AUPRC=0.7983
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5950 | val_loss=0.4765 | val_mcc=0.4629 | val_f1=0.5732 | val_auroc=0.8197

[Epoch 02] train_loss=0.5067 | val_loss=0.4300 | val_mcc=0.4829 | val_f1=0.5878 | val_auroc=0.8365

[Epoch 03] train_loss=0.4701 | val_loss=0.4823 | val_mcc=0.4720 | val_f1=0.5808 | val_auroc=0.8465

[Epoch 04] train_loss=0.4311 | val_loss=0.4323 | val_mcc=0.4819 | val_f1=0.5879 | val_auroc=0.8514

[Epoch 05] train_loss=0.3836 | val_loss=0.4731 | val_mcc=0.4856 | val_f1=0.5914 | val_auroc=0.8464

[Epoch 06] train_loss=0.3320 | val_loss=0.4772 | val_mcc=0.4801 | val_f1=0.5871 | val_auroc=0.8419

[Epoch 07] train_loss=0.2701 | val_loss=0.6315 | val_mcc=0.4478 | val_f1=0.5622 | val_auroc=0.8318

[Epoch 08] train_loss=0.2233 | val_loss=0.7388 | val_mcc=0.4252 | val_f1=0.5431 | val_auroc=0.8235

[Epoch 09] train_loss=0.1726 | val_loss=0.8326 | val_mcc=0.4348 | val_f1=0.5504 | val_auroc=0.8256

[Epoch 10] train_loss=0.1230 | val_loss=0.9049 | val_mcc=0.4317 | val_f1=0.5489 | val_auroc=0.8240

[Epoch 11] train_loss=0.0981 | val_loss=0.9334 | val_mcc=0.4374 | val_f1=0.5544 | val_auroc=0.8236
[EarlyStop] epoch=11 | best_val_mcc=0.4856
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5458 | F1=0.6754 | AUROC=0.8582 | AUPRC=0.7291
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5263 | F1=0.7496 | AUROC=0.8241 | AUPRC=0.8272
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3340 | F1=0.6590 | AUROC=0.7192 | AUPRC=0.7011
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5171 | F1=0.7337 | AUROC=0.8270 | AUPRC=0.7851
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5849 | val_loss=0.4042 | val_mcc=0.4601 | val_f1=0.5599 | val_auroc=0.8280

[Epoch 02] train_loss=0.5012 | val_loss=0.4058 | val_mcc=0.4802 | val_f1=0.5839 | val_auroc=0.8428

[Epoch 03] train_loss=0.4685 | val_loss=0.4615 | val_mcc=0.4749 | val_f1=0.5831 | val_auroc=0.8507

[Epoch 04] train_loss=0.4307 | val_loss=0.4398 | val_mcc=0.4962 | val_f1=0.5995 | val_auroc=0.8588

[Epoch 05] train_loss=0.3863 | val_loss=0.4341 | val_mcc=0.5052 | val_f1=0.6062 | val_auroc=0.8595

[Epoch 06] train_loss=0.3337 | val_loss=0.4606 | val_mcc=0.4896 | val_f1=0.5942 | val_auroc=0.8525

[Epoch 07] train_loss=0.2746 | val_loss=0.5527 | val_mcc=0.4847 | val_f1=0.5905 | val_auroc=0.8455

[Epoch 08] train_loss=0.2157 | val_loss=0.5693 | val_mcc=0.4781 | val_f1=0.5851 | val_auroc=0.8410

[Epoch 09] train_loss=0.1681 | val_loss=0.6808 | val_mcc=0.4618 | val_f1=0.5732 | val_auroc=0.8332

[Epoch 10] train_loss=0.1170 | val_loss=0.7290 | val_mcc=0.4785 | val_f1=0.5858 | val_auroc=0.8368

[Epoch 11] train_loss=0.0893 | val_loss=0.8983 | val_mcc=0.4484 | val_f1=0.5621 | val_auroc=0.8307
[EarlyStop] epoch=11 | best_val_mcc=0.5052
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5641 | F1=0.6858 | AUROC=0.8686 | AUPRC=0.7347
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5023 | F1=0.7309 | AUROC=0.8291 | AUPRC=0.8282
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3221 | F1=0.6512 | AUROC=0.7203 | AUPRC=0.6989
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5182 | F1=0.7327 | AUROC=0.8355 | AUPRC=0.7918
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5988 | val_loss=0.4475 | val_mcc=0.4464 | val_f1=0.5568 | val_auroc=0.8140

[Epoch 02] train_loss=0.5067 | val_loss=0.4386 | val_mcc=0.4665 | val_f1=0.5752 | val_auroc=0.8300

[Epoch 03] train_loss=0.4622 | val_loss=0.4515 | val_mcc=0.4729 | val_f1=0.5817 | val_auroc=0.8427

[Epoch 04] train_loss=0.4223 | val_loss=0.3970 | val_mcc=0.4910 | val_f1=0.5918 | val_auroc=0.8497

[Epoch 05] train_loss=0.3705 | val_loss=0.4247 | val_mcc=0.4866 | val_f1=0.5917 | val_auroc=0.8522

[Epoch 06] train_loss=0.3164 | val_loss=0.4682 | val_mcc=0.4758 | val_f1=0.5839 | val_auroc=0.8499

[Epoch 07] train_loss=0.2478 | val_loss=0.5070 | val_mcc=0.4791 | val_f1=0.5863 | val_auroc=0.8486

[Epoch 08] train_loss=0.1890 | val_loss=0.6566 | val_mcc=0.4335 | val_f1=0.5498 | val_auroc=0.8369

[Epoch 09] train_loss=0.1298 | val_loss=0.5937 | val_mcc=0.4582 | val_f1=0.5705 | val_auroc=0.8393

[Epoch 10] train_loss=0.1036 | val_loss=0.7128 | val_mcc=0.4442 | val_f1=0.5587 | val_auroc=0.8366
[EarlyStop] epoch=10 | best_val_mcc=0.4910
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5604 | F1=0.6779 | AUROC=0.8673 | AUPRC=0.7465
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5206 | F1=0.7307 | AUROC=0.8387 | AUPRC=0.8370
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3409 | F1=0.6377 | AUROC=0.7266 | AUPRC=0.7035
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5154 | F1=0.7192 | AUROC=0.8333 | AUPRC=0.8007
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 160.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5356 | F1=0.6714 | AUROC=0.8674 | AUPRC=0.7311
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5106 | F1=0.7529 | AUROC=0.8352 | AUPRC=0.8229
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3146 | F1=0.6617 | AUROC=0.7186 | AUPRC=0.6976
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5019 | F1=0.7386 | AUROC=0.8365 | AUPRC=0.8004
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 83.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5447 | F1=0.6765 | AUROC=0.8647 | AUPRC=0.7318
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4740 | F1=0.7267 | AUROC=0.8239 | AUPRC=0.8236
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3385 | F1=0.6721 | AUROC=0.7237 | AUPRC=0.7078
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5159 | F1=0.7431 | AUROC=0.8327 | AUPRC=0.7939
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 49.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5566 | F1=0.6843 | AUROC=0.8667 | AUPRC=0.7463
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5223 | F1=0.7529 | AUROC=0.8338 | AUPRC=0.8327
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3218 | F1=0.6565 | AUROC=0.7231 | AUPRC=0.7057
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5329 | F1=0.7489 | AUROC=0.8352 | AUPRC=0.8078
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 36.
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5414 | F1=0.6737 | AUROC=0.8635 | AUPRC=0.7382
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5055 | F1=0.7426 | AUROC=0.8253 | AUPRC=0.8185
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3428 | F1=0.6682 | AUROC=0.7258 | AUPRC=0.7007
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5219 | F1=0.7426 | AUROC=0.8349 | AUPRC=0.7976
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']

[Epoch 01] train_loss=0.6975 | val_loss=0.7071 | val_mcc=0.0666 | val_f1=0.3206 | val_auroc=0.5675

[Epoch 02] train_loss=0.6889 | val_loss=0.6495 | val_mcc=0.0837 | val_f1=0.2811 | val_auroc=0.5678

[Epoch 03] train_loss=0.6860 | val_loss=0.6931 | val_mcc=0.0788 | val_f1=0.3197 | val_auroc=0.5684

[Epoch 04] train_loss=0.6801 | val_loss=0.6501 | val_mcc=0.0741 | val_f1=0.2864 | val_auroc=0.5623

[Epoch 05] train_loss=0.6740 | val_loss=0.7159 | val_mcc=0.0663 | val_f1=0.3186 | val_auroc=0.5579

[Epoch 06] train_loss=0.6684 | val_loss=0.6220 | val_mcc=0.0554 | val_f1=0.2546 | val_auroc=0.5559

[Epoch 07] train_loss=0.6587 | val_loss=0.7271 | val_mcc=0.0581 | val_f1=0.3135 | val_auroc=0.5557

[Epoch 08] train_loss=0.6508 | val_loss=0.6930 | val_mcc=0.0559 | val_f1=0.3012 | val_auroc=0.5557
[EarlyStop] epoch=8 | best_val_mcc=0.0837
[Test] train3__val_cls_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.0605 | F1=0.3105 | AUROC=0.5416 | AUPRC=0.3081
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.0596 | F1=0.4014 | AUROC=0.5424 | AUPRC=0.5468
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.0123 | F1=0.3816 | AUROC=0.5126 | AUPRC=0.5097
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.0469 | F1=0.3760 | AUROC=0.5255 | AUPRC=0.4761
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 32.
[Test] train3__val_cls_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.0624 | F1=0.3712 | AUROC=0.5454 | AUPRC=0.3134
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.0519 | F1=0.4992 | AUROC=0.5625 | AUPRC=0.5550
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=-0.0311 | F1=0.4645 | AUROC=0.4855 | AUPRC=0.4895
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.0316 | F1=0.4684 | AUROC=0.5249 | AUPRC=0.4798
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 26.
[Test] train3__val_cls_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.0300 | F1=0.3596 | AUROC=0.5302 | AUPRC=0.2984
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.0208 | F1=0.4926 | AUROC=0.5139 | AUPRC=0.5139
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.0096 | F1=0.4931 | AUROC=0.5068 | AUPRC=0.5100
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.0200 | F1=0.4794 | AUROC=0.5088 | AUPRC=0.4686
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4727 | val_loss=0.2660 | val_mcc=0.6654 | val_f1=0.7309 | val_auroc=0.9418

[Epoch 02] train_loss=0.3703 | val_loss=0.2690 | val_mcc=0.6712 | val_f1=0.7351 | val_auroc=0.9434

[Epoch 03] train_loss=0.3552 | val_loss=0.2870 | val_mcc=0.6637 | val_f1=0.7270 | val_auroc=0.9438

[Epoch 04] train_loss=0.3489 | val_loss=0.2866 | val_mcc=0.6641 | val_f1=0.7273 | val_auroc=0.9447

[Epoch 05] train_loss=0.3382 | val_loss=0.3212 | val_mcc=0.6458 | val_f1=0.7090 | val_auroc=0.9437

[Epoch 06] train_loss=0.3335 | val_loss=0.2845 | val_mcc=0.6648 | val_f1=0.7281 | val_auroc=0.9440

[Epoch 07] train_loss=0.3242 | val_loss=0.2587 | val_mcc=0.6766 | val_f1=0.7402 | val_auroc=0.9429

[Epoch 08] train_loss=0.3240 | val_loss=0.2789 | val_mcc=0.6695 | val_f1=0.7332 | val_auroc=0.9424

[Epoch 09] train_loss=0.3176 | val_loss=0.2811 | val_mcc=0.6679 | val_f1=0.7321 | val_auroc=0.9415

[Epoch 10] train_loss=0.3113 | val_loss=0.2820 | val_mcc=0.6667 | val_f1=0.7314 | val_auroc=0.9406

[Epoch 11] train_loss=0.3077 | val_loss=0.2994 | val_mcc=0.6573 | val_f1=0.7222 | val_auroc=0.9392

[Epoch 12] train_loss=0.2997 | val_loss=0.2968 | val_mcc=0.6600 | val_f1=0.7249 | val_auroc=0.9394

[Epoch 13] train_loss=0.2935 | val_loss=0.2976 | val_mcc=0.6583 | val_f1=0.7237 | val_auroc=0.9388
[EarlyStop] epoch=13 | best_val_mcc=0.6766
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.6915 | F1=0.7789 | AUROC=0.9282 | AUPRC=0.8412
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8268 | F1=0.9035 | AUROC=0.9694 | AUPRC=0.9687
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.2796 | F1=0.6596 | AUROC=0.6952 | AUPRC=0.6760
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4709 | F1=0.7388 | AUROC=0.8136 | AUPRC=0.7611
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 75.
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7022 | F1=0.7865 | AUROC=0.9418 | AUPRC=0.8719
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8147 | F1=0.9012 | AUROC=0.9769 | AUPRC=0.9781
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3295 | F1=0.6827 | AUROC=0.7207 | AUPRC=0.6982
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4600 | F1=0.7343 | AUROC=0.8524 | AUPRC=0.8193
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 85.
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6894 | F1=0.7775 | AUROC=0.9299 | AUPRC=0.8468
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7942 | F1=0.8912 | AUROC=0.9641 | AUPRC=0.9656
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3075 | F1=0.6746 | AUROC=0.7026 | AUPRC=0.6803
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4818 | F1=0.7434 | AUROC=0.8186 | AUPRC=0.7540
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.6997 | val_loss=0.6768 | val_mcc=0.0751 | val_f1=0.3101 | val_auroc=0.5650

[Epoch 02] train_loss=0.6903 | val_loss=0.6641 | val_mcc=0.0671 | val_f1=0.2876 | val_auroc=0.5549

[Epoch 03] train_loss=0.6883 | val_loss=0.6617 | val_mcc=0.0758 | val_f1=0.2930 | val_auroc=0.5614

[Epoch 04] train_loss=0.6856 | val_loss=0.7101 | val_mcc=0.0750 | val_f1=0.3270 | val_auroc=0.5734

[Epoch 05] train_loss=0.6836 | val_loss=0.6611 | val_mcc=0.0872 | val_f1=0.3029 | val_auroc=0.5702

[Epoch 06] train_loss=0.6818 | val_loss=0.6474 | val_mcc=0.0903 | val_f1=0.2896 | val_auroc=0.5683

[Epoch 07] train_loss=0.6793 | val_loss=0.7024 | val_mcc=0.0703 | val_f1=0.3207 | val_auroc=0.5629

[Epoch 08] train_loss=0.6773 | val_loss=0.6649 | val_mcc=0.0940 | val_f1=0.3183 | val_auroc=0.5714

[Epoch 09] train_loss=0.6748 | val_loss=0.6466 | val_mcc=0.0872 | val_f1=0.2846 | val_auroc=0.5688

[Epoch 10] train_loss=0.6725 | val_loss=0.6873 | val_mcc=0.0510 | val_f1=0.2966 | val_auroc=0.5514

[Epoch 11] train_loss=0.6681 | val_loss=0.7122 | val_mcc=0.0552 | val_f1=0.3074 | val_auroc=0.5508

[Epoch 12] train_loss=0.6639 | val_loss=0.6384 | val_mcc=0.0665 | val_f1=0.2663 | val_auroc=0.5555

[Epoch 13] train_loss=0.6568 | val_loss=0.6881 | val_mcc=0.0478 | val_f1=0.2910 | val_auroc=0.5471

[Epoch 14] train_loss=0.6557 | val_loss=0.7045 | val_mcc=0.0753 | val_f1=0.3218 | val_auroc=0.5672
[EarlyStop] epoch=14 | best_val_mcc=0.0940
[Test] train3__val_cls_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.0904 | F1=0.3846 | AUROC=0.5613 | AUPRC=0.3083
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.1005 | F1=0.5212 | AUROC=0.5603 | AUPRC=0.5603
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.0832 | F1=0.5275 | AUROC=0.5272 | AUPRC=0.5166
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.0852 | F1=0.4939 | AUROC=0.5518 | AUPRC=0.4901
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 37.
[Test] train3__val_cls_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.0987 | F1=0.3779 | AUROC=0.5810 | AUPRC=0.3361
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.0577 | F1=0.4565 | AUROC=0.5308 | AUPRC=0.5298
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.0396 | F1=0.4797 | AUROC=0.5365 | AUPRC=0.5393
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.0812 | F1=0.4679 | AUROC=0.5566 | AUPRC=0.4975
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 27.
[Test] train3__val_cls_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.0792 | F1=0.3647 | AUROC=0.5557 | AUPRC=0.3223
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.0690 | F1=0.4850 | AUROC=0.5484 | AUPRC=0.5435
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.0704 | F1=0.4825 | AUROC=0.5414 | AUPRC=0.5371
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.0742 | F1=0.4528 | AUROC=0.5518 | AUPRC=0.4966
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.5009 | val_loss=0.2634 | val_mcc=0.6709 | val_f1=0.7360 | val_auroc=0.9397

[Epoch 02] train_loss=0.3772 | val_loss=0.2803 | val_mcc=0.6655 | val_f1=0.7309 | val_auroc=0.9398

[Epoch 03] train_loss=0.3673 | val_loss=0.2664 | val_mcc=0.6703 | val_f1=0.7355 | val_auroc=0.9366

[Epoch 04] train_loss=0.3575 | val_loss=0.2570 | val_mcc=0.6818 | val_f1=0.7445 | val_auroc=0.9428

[Epoch 05] train_loss=0.3517 | val_loss=0.2666 | val_mcc=0.6814 | val_f1=0.7435 | val_auroc=0.9451

[Epoch 06] train_loss=0.3491 | val_loss=0.2802 | val_mcc=0.6724 | val_f1=0.7352 | val_auroc=0.9433

[Epoch 07] train_loss=0.3440 | val_loss=0.2728 | val_mcc=0.6780 | val_f1=0.7400 | val_auroc=0.9450

[Epoch 08] train_loss=0.3400 | val_loss=0.2594 | val_mcc=0.6855 | val_f1=0.7469 | val_auroc=0.9461

[Epoch 09] train_loss=0.3384 | val_loss=0.2726 | val_mcc=0.6813 | val_f1=0.7421 | val_auroc=0.9461

[Epoch 10] train_loss=0.3330 | val_loss=0.2470 | val_mcc=0.6853 | val_f1=0.7474 | val_auroc=0.9450

[Epoch 11] train_loss=0.3316 | val_loss=0.2752 | val_mcc=0.6754 | val_f1=0.7375 | val_auroc=0.9451

[Epoch 12] train_loss=0.3263 | val_loss=0.2762 | val_mcc=0.6772 | val_f1=0.7389 | val_auroc=0.9446

[Epoch 13] train_loss=0.3217 | val_loss=0.2546 | val_mcc=0.6852 | val_f1=0.7472 | val_auroc=0.9446

[Epoch 14] train_loss=0.3207 | val_loss=0.2635 | val_mcc=0.6836 | val_f1=0.7453 | val_auroc=0.9445
[EarlyStop] epoch=14 | best_val_mcc=0.6855
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.6924 | F1=0.7796 | AUROC=0.9315 | AUPRC=0.8532
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8179 | F1=0.8991 | AUROC=0.9704 | AUPRC=0.9719
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3287 | F1=0.6800 | AUROC=0.7004 | AUPRC=0.6663
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4806 | F1=0.7429 | AUROC=0.8274 | AUPRC=0.7763
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 120.
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7052 | F1=0.7886 | AUROC=0.9420 | AUPRC=0.8724
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8375 | F1=0.9132 | AUROC=0.9752 | AUPRC=0.9765
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3336 | F1=0.6872 | AUROC=0.7236 | AUPRC=0.7081
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4954 | F1=0.7491 | AUROC=0.8500 | AUPRC=0.8206
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 85.
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6802 | F1=0.7711 | AUROC=0.9290 | AUPRC=0.8433
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7899 | F1=0.8869 | AUROC=0.9680 | AUPRC=0.9688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3210 | F1=0.6803 | AUROC=0.7014 | AUPRC=0.6750
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4792 | F1=0.7423 | AUROC=0.8313 | AUPRC=0.7758
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.7048 | val_loss=0.6681 | val_mcc=0.0622 | val_f1=0.2882 | val_auroc=0.5548

[Epoch 02] train_loss=0.6855 | val_loss=0.7211 | val_mcc=0.0474 | val_f1=0.3118 | val_auroc=0.5450

[Epoch 03] train_loss=0.6739 | val_loss=0.7101 | val_mcc=0.0681 | val_f1=0.3156 | val_auroc=0.5506

[Epoch 04] train_loss=0.6585 | val_loss=0.6549 | val_mcc=0.0506 | val_f1=0.2735 | val_auroc=0.5487

[Epoch 05] train_loss=0.6378 | val_loss=0.6687 | val_mcc=0.0551 | val_f1=0.2853 | val_auroc=0.5494

[Epoch 06] train_loss=0.6102 | val_loss=0.6866 | val_mcc=0.0437 | val_f1=0.2796 | val_auroc=0.5407

[Epoch 07] train_loss=0.5734 | val_loss=0.7247 | val_mcc=0.0497 | val_f1=0.2899 | val_auroc=0.5343

[Epoch 08] train_loss=0.5184 | val_loss=0.8278 | val_mcc=0.0414 | val_f1=0.3002 | val_auroc=0.5321

[Epoch 09] train_loss=0.4853 | val_loss=0.7812 | val_mcc=0.0376 | val_f1=0.2831 | val_auroc=0.5316
[EarlyStop] epoch=9 | best_val_mcc=0.0681
[Test] train3__val_cls_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.0483 | F1=0.3846 | AUROC=0.5326 | AUPRC=0.2972
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.1267 | F1=0.5904 | AUROC=0.5675 | AUPRC=0.5505
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=-0.0184 | F1=0.5248 | AUROC=0.4870 | AUPRC=0.4865
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.0475 | F1=0.5141 | AUROC=0.5289 | AUPRC=0.4866
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 17.
[Test] train3__val_cls_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.0760 | F1=0.3624 | AUROC=0.5550 | AUPRC=0.3234
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.1710 | F1=0.5335 | AUROC=0.5953 | AUPRC=0.5875
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.0093 | F1=0.4686 | AUROC=0.5146 | AUPRC=0.5129
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.0498 | F1=0.4477 | AUROC=0.5418 | AUPRC=0.4972
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 13.
[Test] train3__val_cls_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.0537 | F1=0.3608 | AUROC=0.5383 | AUPRC=0.3084
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.1240 | F1=0.5157 | AUROC=0.5699 | AUPRC=0.5705
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.0472 | F1=0.4908 | AUROC=0.5216 | AUPRC=0.5220
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.0239 | F1=0.4446 | AUROC=0.5324 | AUPRC=0.4944
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4958 | val_loss=0.3080 | val_mcc=0.6440 | val_f1=0.7116 | val_auroc=0.9349

[Epoch 02] train_loss=0.3706 | val_loss=0.2691 | val_mcc=0.6711 | val_f1=0.7356 | val_auroc=0.9389

[Epoch 03] train_loss=0.3477 | val_loss=0.2827 | val_mcc=0.6656 | val_f1=0.7303 | val_auroc=0.9397

[Epoch 04] train_loss=0.3296 | val_loss=0.2959 | val_mcc=0.6551 | val_f1=0.7205 | val_auroc=0.9398

[Epoch 05] train_loss=0.3128 | val_loss=0.2921 | val_mcc=0.6512 | val_f1=0.7191 | val_auroc=0.9358

[Epoch 06] train_loss=0.2887 | val_loss=0.3060 | val_mcc=0.6386 | val_f1=0.7086 | val_auroc=0.9334

[Epoch 07] train_loss=0.2618 | val_loss=0.3034 | val_mcc=0.6451 | val_f1=0.7141 | val_auroc=0.9330

[Epoch 08] train_loss=0.2456 | val_loss=0.2872 | val_mcc=0.6462 | val_f1=0.7164 | val_auroc=0.9307
[EarlyStop] epoch=8 | best_val_mcc=0.6711
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.6746 | F1=0.7671 | AUROC=0.9245 | AUPRC=0.8261
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7956 | F1=0.8899 | AUROC=0.9625 | AUPRC=0.9636
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3028 | F1=0.6667 | AUROC=0.6892 | AUPRC=0.6458
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4600 | F1=0.7343 | AUROC=0.7949 | AUPRC=0.7003
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 88.
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6998 | F1=0.7848 | AUROC=0.9396 | AUPRC=0.8684
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8224 | F1=0.9064 | AUROC=0.9769 | AUPRC=0.9775
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3305 | F1=0.6858 | AUROC=0.7138 | AUPRC=0.6828
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4831 | F1=0.7439 | AUROC=0.8519 | AUPRC=0.8261
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 83.
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6811 | F1=0.7717 | AUROC=0.9287 | AUPRC=0.8377
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7983 | F1=0.8916 | AUROC=0.9675 | AUPRC=0.9708
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3168 | F1=0.6793 | AUROC=0.7045 | AUPRC=0.6639
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4734 | F1=0.7399 | AUROC=0.8313 | AUPRC=0.7809
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.5836 | val_loss=0.4022 | val_mcc=0.5047 | val_f1=0.5975 | val_auroc=0.8331

[Epoch 02] train_loss=0.5062 | val_loss=0.4154 | val_mcc=0.5286 | val_f1=0.6238 | val_auroc=0.8497

[Epoch 03] train_loss=0.4739 | val_loss=0.4206 | val_mcc=0.5296 | val_f1=0.6253 | val_auroc=0.8593

[Epoch 04] train_loss=0.4513 | val_loss=0.3894 | val_mcc=0.5480 | val_f1=0.6395 | val_auroc=0.8660

[Epoch 05] train_loss=0.4314 | val_loss=0.3813 | val_mcc=0.5519 | val_f1=0.6426 | val_auroc=0.8743

[Epoch 06] train_loss=0.4078 | val_loss=0.3956 | val_mcc=0.5581 | val_f1=0.6474 | val_auroc=0.8757

[Epoch 07] train_loss=0.3810 | val_loss=0.3749 | val_mcc=0.5712 | val_f1=0.6573 | val_auroc=0.8806

[Epoch 08] train_loss=0.3586 | val_loss=0.4150 | val_mcc=0.5564 | val_f1=0.6456 | val_auroc=0.8806

[Epoch 09] train_loss=0.3322 | val_loss=0.4134 | val_mcc=0.5563 | val_f1=0.6455 | val_auroc=0.8796

[Epoch 10] train_loss=0.3093 | val_loss=0.4161 | val_mcc=0.5569 | val_f1=0.6462 | val_auroc=0.8795

[Epoch 11] train_loss=0.2832 | val_loss=0.4099 | val_mcc=0.5487 | val_f1=0.6401 | val_auroc=0.8721

[Epoch 12] train_loss=0.2472 | val_loss=0.4712 | val_mcc=0.5466 | val_f1=0.6371 | val_auroc=0.8755

[Epoch 13] train_loss=0.2302 | val_loss=0.4426 | val_mcc=0.5478 | val_f1=0.6394 | val_auroc=0.8732
[EarlyStop] epoch=13 | best_val_mcc=0.5712
[Test] train3__val_cls_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6042 | F1=0.7135 | AUROC=0.8950 | AUPRC=0.7928
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5795 | F1=0.7725 | AUROC=0.8758 | AUPRC=0.8749
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4139 | F1=0.6884 | AUROC=0.7688 | AUPRC=0.7501
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5690 | F1=0.7599 | AUROC=0.8729 | AUPRC=0.8513
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 237.
[Test] train3__val_cls_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5909 | F1=0.7090 | AUROC=0.8905 | AUPRC=0.7747
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5707 | F1=0.7858 | AUROC=0.8769 | AUPRC=0.8614
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3985 | F1=0.7019 | AUROC=0.7564 | AUPRC=0.7486
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5911 | F1=0.7813 | AUROC=0.8700 | AUPRC=0.8366
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 125.
[Test] train3__val_cls_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5927 | F1=0.7088 | AUROC=0.8859 | AUPRC=0.7731
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5590 | F1=0.7763 | AUROC=0.8645 | AUPRC=0.8595
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4118 | F1=0.7035 | AUROC=0.7609 | AUPRC=0.7433
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5788 | F1=0.7722 | AUROC=0.8610 | AUPRC=0.8289
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4119 | val_loss=0.2223 | val_mcc=0.7354 | val_f1=0.7870 | val_auroc=0.9546

[Epoch 02] train_loss=0.3134 | val_loss=0.2247 | val_mcc=0.7334 | val_f1=0.7856 | val_auroc=0.9577

[Epoch 03] train_loss=0.2931 | val_loss=0.2205 | val_mcc=0.7383 | val_f1=0.7895 | val_auroc=0.9589

[Epoch 04] train_loss=0.2784 | val_loss=0.2082 | val_mcc=0.7457 | val_f1=0.7953 | val_auroc=0.9591

[Epoch 05] train_loss=0.2694 | val_loss=0.2344 | val_mcc=0.7303 | val_f1=0.7820 | val_auroc=0.9602

[Epoch 06] train_loss=0.2587 | val_loss=0.2222 | val_mcc=0.7437 | val_f1=0.7935 | val_auroc=0.9615

[Epoch 07] train_loss=0.2440 | val_loss=0.2145 | val_mcc=0.7421 | val_f1=0.7925 | val_auroc=0.9601

[Epoch 08] train_loss=0.2331 | val_loss=0.2026 | val_mcc=0.7485 | val_f1=0.7971 | val_auroc=0.9614

[Epoch 09] train_loss=0.2195 | val_loss=0.2146 | val_mcc=0.7510 | val_f1=0.7996 | val_auroc=0.9623

[Epoch 10] train_loss=0.2022 | val_loss=0.2242 | val_mcc=0.7450 | val_f1=0.7949 | val_auroc=0.9612

[Epoch 11] train_loss=0.1868 | val_loss=0.2131 | val_mcc=0.7482 | val_f1=0.7973 | val_auroc=0.9610

[Epoch 12] train_loss=0.1688 | val_loss=0.2508 | val_mcc=0.7296 | val_f1=0.7821 | val_auroc=0.9569

[Epoch 13] train_loss=0.1570 | val_loss=0.2343 | val_mcc=0.7399 | val_f1=0.7908 | val_auroc=0.9590

[Epoch 14] train_loss=0.1328 | val_loss=0.2515 | val_mcc=0.7347 | val_f1=0.7865 | val_auroc=0.9560

[Epoch 15] train_loss=0.1198 | val_loss=0.2686 | val_mcc=0.7257 | val_f1=0.7792 | val_auroc=0.9545
[EarlyStop] epoch=15 | best_val_mcc=0.7510
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7662 | F1=0.8314 | AUROC=0.9564 | AUPRC=0.9014
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7849 | F1=0.8876 | AUROC=0.9692 | AUPRC=0.9698
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4174 | F1=0.7210 | AUROC=0.7754 | AUPRC=0.7612
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6099 | F1=0.8003 | AUROC=0.8933 | AUPRC=0.8538
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 138.
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7616 | F1=0.8283 | AUROC=0.9620 | AUPRC=0.9124
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8597 | F1=0.9256 | AUROC=0.9855 | AUPRC=0.9868
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4027 | F1=0.7204 | AUROC=0.7633 | AUPRC=0.7533
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5565 | F1=0.7754 | AUROC=0.9006 | AUPRC=0.8688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 138.
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7529 | F1=0.8223 | AUROC=0.9565 | AUPRC=0.9039
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8276 | F1=0.9099 | AUROC=0.9762 | AUPRC=0.9766
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4042 | F1=0.7187 | AUROC=0.7678 | AUPRC=0.7456
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5799 | F1=0.7862 | AUROC=0.8914 | AUPRC=0.8577
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.5872 | val_loss=0.4527 | val_mcc=0.4591 | val_f1=0.5691 | val_auroc=0.8235

[Epoch 02] train_loss=0.5115 | val_loss=0.4160 | val_mcc=0.4812 | val_f1=0.5856 | val_auroc=0.8405

[Epoch 03] train_loss=0.4796 | val_loss=0.4225 | val_mcc=0.4893 | val_f1=0.5933 | val_auroc=0.8489

[Epoch 04] train_loss=0.4527 | val_loss=0.3863 | val_mcc=0.5078 | val_f1=0.6057 | val_auroc=0.8596

[Epoch 05] train_loss=0.4229 | val_loss=0.4174 | val_mcc=0.4970 | val_f1=0.6001 | val_auroc=0.8636

[Epoch 06] train_loss=0.3947 | val_loss=0.4218 | val_mcc=0.4955 | val_f1=0.5990 | val_auroc=0.8670

[Epoch 07] train_loss=0.3639 | val_loss=0.4256 | val_mcc=0.4976 | val_f1=0.6006 | val_auroc=0.8661

[Epoch 08] train_loss=0.3296 | val_loss=0.4346 | val_mcc=0.4944 | val_f1=0.5981 | val_auroc=0.8627

[Epoch 09] train_loss=0.2834 | val_loss=0.4455 | val_mcc=0.4926 | val_f1=0.5966 | val_auroc=0.8617

[Epoch 10] train_loss=0.2566 | val_loss=0.4827 | val_mcc=0.4866 | val_f1=0.5922 | val_auroc=0.8608
[EarlyStop] epoch=10 | best_val_mcc=0.5078
[Test] train3__val_cls_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5697 | F1=0.6852 | AUROC=0.8759 | AUPRC=0.7543
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5253 | F1=0.7293 | AUROC=0.8351 | AUPRC=0.8314
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3533 | F1=0.6500 | AUROC=0.7319 | AUPRC=0.7139
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5165 | F1=0.7237 | AUROC=0.8428 | AUPRC=0.8063
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 164.
[Test] train3__val_cls_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5505 | F1=0.6817 | AUROC=0.8717 | AUPRC=0.7351
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5278 | F1=0.7629 | AUROC=0.8406 | AUPRC=0.8394
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3461 | F1=0.6775 | AUROC=0.7301 | AUPRC=0.7066
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5272 | F1=0.7512 | AUROC=0.8433 | AUPRC=0.8113
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 85.
[Test] train3__val_cls_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5420 | F1=0.6752 | AUROC=0.8691 | AUPRC=0.7402
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4879 | F1=0.7376 | AUROC=0.8279 | AUPRC=0.8203
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3398 | F1=0.6667 | AUROC=0.7372 | AUPRC=0.7107
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5305 | F1=0.7482 | AUROC=0.8410 | AUPRC=0.8063
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4018 | val_loss=0.2168 | val_mcc=0.7212 | val_f1=0.7755 | val_auroc=0.9555

[Epoch 02] train_loss=0.3033 | val_loss=0.2176 | val_mcc=0.7363 | val_f1=0.7879 | val_auroc=0.9593

[Epoch 03] train_loss=0.2793 | val_loss=0.1979 | val_mcc=0.7435 | val_f1=0.7910 | val_auroc=0.9604

[Epoch 04] train_loss=0.2661 | val_loss=0.2137 | val_mcc=0.7455 | val_f1=0.7952 | val_auroc=0.9608

[Epoch 05] train_loss=0.2452 | val_loss=0.2127 | val_mcc=0.7497 | val_f1=0.7984 | val_auroc=0.9610

[Epoch 06] train_loss=0.2299 | val_loss=0.2070 | val_mcc=0.7560 | val_f1=0.8037 | val_auroc=0.9616

[Epoch 07] train_loss=0.2122 | val_loss=0.2317 | val_mcc=0.7389 | val_f1=0.7890 | val_auroc=0.9618

[Epoch 08] train_loss=0.1926 | val_loss=0.2299 | val_mcc=0.7399 | val_f1=0.7908 | val_auroc=0.9584

[Epoch 09] train_loss=0.1697 | val_loss=0.2323 | val_mcc=0.7396 | val_f1=0.7906 | val_auroc=0.9588

[Epoch 10] train_loss=0.1504 | val_loss=0.2391 | val_mcc=0.7435 | val_f1=0.7937 | val_auroc=0.9574

[Epoch 11] train_loss=0.1187 | val_loss=0.2636 | val_mcc=0.7285 | val_f1=0.7814 | val_auroc=0.9558

[Epoch 12] train_loss=0.1061 | val_loss=0.2919 | val_mcc=0.7247 | val_f1=0.7776 | val_auroc=0.9553
[EarlyStop] epoch=12 | best_val_mcc=0.7560
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7561 | F1=0.8239 | AUROC=0.9551 | AUPRC=0.8937
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7834 | F1=0.8846 | AUROC=0.9687 | AUPRC=0.9690
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4340 | F1=0.7249 | AUROC=0.7617 | AUPRC=0.7380
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5621 | F1=0.7779 | AUROC=0.8771 | AUPRC=0.8472
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 218.
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7603 | F1=0.8275 | AUROC=0.9620 | AUPRC=0.9116
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8539 | F1=0.9226 | AUROC=0.9847 | AUPRC=0.9842
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4193 | F1=0.7279 | AUROC=0.7662 | AUPRC=0.7490
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5455 | F1=0.7706 | AUROC=0.8958 | AUPRC=0.8634
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 142.
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7426 | F1=0.8149 | AUROC=0.9561 | AUPRC=0.9019
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8240 | F1=0.9094 | AUROC=0.9736 | AUPRC=0.9733
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4039 | F1=0.7206 | AUROC=0.7638 | AUPRC=0.7452
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5318 | F1=0.7648 | AUROC=0.8829 | AUPRC=0.8548
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.6195 | val_loss=0.4889 | val_mcc=0.4100 | val_f1=0.5270 | val_auroc=0.7768

[Epoch 02] train_loss=0.5546 | val_loss=0.4635 | val_mcc=0.4458 | val_f1=0.5503 | val_auroc=0.7970

[Epoch 03] train_loss=0.5268 | val_loss=0.4316 | val_mcc=0.4615 | val_f1=0.5604 | val_auroc=0.8103

[Epoch 04] train_loss=0.5069 | val_loss=0.4931 | val_mcc=0.4623 | val_f1=0.5734 | val_auroc=0.8196

[Epoch 05] train_loss=0.4889 | val_loss=0.4512 | val_mcc=0.4830 | val_f1=0.5884 | val_auroc=0.8314

[Epoch 06] train_loss=0.4669 | val_loss=0.4570 | val_mcc=0.4871 | val_f1=0.5917 | val_auroc=0.8376

[Epoch 07] train_loss=0.4490 | val_loss=0.4188 | val_mcc=0.5116 | val_f1=0.6086 | val_auroc=0.8458

[Epoch 08] train_loss=0.4201 | val_loss=0.4502 | val_mcc=0.5004 | val_f1=0.6027 | val_auroc=0.8500

[Epoch 09] train_loss=0.3955 | val_loss=0.4376 | val_mcc=0.5107 | val_f1=0.6107 | val_auroc=0.8555

[Epoch 10] train_loss=0.3713 | val_loss=0.4089 | val_mcc=0.5203 | val_f1=0.6172 | val_auroc=0.8561

[Epoch 11] train_loss=0.3451 | val_loss=0.4501 | val_mcc=0.5047 | val_f1=0.6061 | val_auroc=0.8534

[Epoch 12] train_loss=0.3190 | val_loss=0.4591 | val_mcc=0.5068 | val_f1=0.6077 | val_auroc=0.8521

[Epoch 13] train_loss=0.2918 | val_loss=0.4603 | val_mcc=0.5060 | val_f1=0.6067 | val_auroc=0.8519

[Epoch 14] train_loss=0.2766 | val_loss=0.4849 | val_mcc=0.4972 | val_f1=0.6003 | val_auroc=0.8502

[Epoch 15] train_loss=0.2351 | val_loss=0.5456 | val_mcc=0.4776 | val_f1=0.5844 | val_auroc=0.8462

[Epoch 16] train_loss=0.2187 | val_loss=0.5256 | val_mcc=0.4864 | val_f1=0.5920 | val_auroc=0.8462
[EarlyStop] epoch=16 | best_val_mcc=0.5203
[Test] train3__val_cls_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5396 | F1=0.6634 | AUROC=0.8545 | AUPRC=0.7282
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.4948 | F1=0.7233 | AUROC=0.8348 | AUPRC=0.8241
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3428 | F1=0.6519 | AUROC=0.7245 | AUPRC=0.7010
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4710 | F1=0.6913 | AUROC=0.8131 | AUPRC=0.7961
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 228.
[Test] train3__val_cls_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5000 | F1=0.6458 | AUROC=0.8496 | AUPRC=0.7213
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.4765 | F1=0.7326 | AUROC=0.8244 | AUPRC=0.8187
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3638 | F1=0.6793 | AUROC=0.7446 | AUPRC=0.7233
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4577 | F1=0.7049 | AUROC=0.8048 | AUPRC=0.7795
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 116.
[Test] train3__val_cls_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5020 | F1=0.6444 | AUROC=0.8413 | AUPRC=0.7099
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4880 | F1=0.7361 | AUROC=0.8164 | AUPRC=0.8075
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3585 | F1=0.6667 | AUROC=0.7344 | AUPRC=0.7062
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4474 | F1=0.6889 | AUROC=0.7910 | AUPRC=0.7626
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4253 | val_loss=0.2278 | val_mcc=0.7105 | val_f1=0.7675 | val_auroc=0.9543

[Epoch 02] train_loss=0.3252 | val_loss=0.2446 | val_mcc=0.7147 | val_f1=0.7696 | val_auroc=0.9566

[Epoch 03] train_loss=0.3066 | val_loss=0.2235 | val_mcc=0.7326 | val_f1=0.7848 | val_auroc=0.9590

[Epoch 04] train_loss=0.2955 | val_loss=0.2218 | val_mcc=0.7304 | val_f1=0.7830 | val_auroc=0.9594

[Epoch 05] train_loss=0.2874 | val_loss=0.2279 | val_mcc=0.7295 | val_f1=0.7822 | val_auroc=0.9597

[Epoch 06] train_loss=0.2759 | val_loss=0.2238 | val_mcc=0.7340 | val_f1=0.7856 | val_auroc=0.9602

[Epoch 07] train_loss=0.2634 | val_loss=0.2347 | val_mcc=0.7282 | val_f1=0.7803 | val_auroc=0.9606

[Epoch 08] train_loss=0.2549 | val_loss=0.2379 | val_mcc=0.7229 | val_f1=0.7759 | val_auroc=0.9596

[Epoch 09] train_loss=0.2428 | val_loss=0.2129 | val_mcc=0.7438 | val_f1=0.7939 | val_auroc=0.9608

[Epoch 10] train_loss=0.2311 | val_loss=0.2297 | val_mcc=0.7373 | val_f1=0.7881 | val_auroc=0.9602

[Epoch 11] train_loss=0.2180 | val_loss=0.2196 | val_mcc=0.7414 | val_f1=0.7920 | val_auroc=0.9599

[Epoch 12] train_loss=0.2038 | val_loss=0.2144 | val_mcc=0.7454 | val_f1=0.7952 | val_auroc=0.9598

[Epoch 13] train_loss=0.1863 | val_loss=0.2303 | val_mcc=0.7416 | val_f1=0.7921 | val_auroc=0.9586

[Epoch 14] train_loss=0.1717 | val_loss=0.2362 | val_mcc=0.7366 | val_f1=0.7880 | val_auroc=0.9581

[Epoch 15] train_loss=0.1587 | val_loss=0.2844 | val_mcc=0.7076 | val_f1=0.7623 | val_auroc=0.9556

[Epoch 16] train_loss=0.1425 | val_loss=0.2893 | val_mcc=0.7119 | val_f1=0.7668 | val_auroc=0.9539

[Epoch 17] train_loss=0.1202 | val_loss=0.2674 | val_mcc=0.7272 | val_f1=0.7806 | val_auroc=0.9534

[Epoch 18] train_loss=0.1119 | val_loss=0.2754 | val_mcc=0.7264 | val_f1=0.7797 | val_auroc=0.9534
[EarlyStop] epoch=18 | best_val_mcc=0.7454
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7381 | F1=0.8110 | AUROC=0.9456 | AUPRC=0.8754
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8038 | F1=0.8913 | AUROC=0.9631 | AUPRC=0.9617
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4075 | F1=0.7139 | AUROC=0.7570 | AUPRC=0.7227
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5618 | F1=0.7775 | AUROC=0.8633 | AUPRC=0.8280
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 217.
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7468 | F1=0.8179 | AUROC=0.9572 | AUPRC=0.9058
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8765 | F1=0.9347 | AUROC=0.9861 | AUPRC=0.9862
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4126 | F1=0.7240 | AUROC=0.7638 | AUPRC=0.7279
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5514 | F1=0.7733 | AUROC=0.8857 | AUPRC=0.8630
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 223.
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7490 | F1=0.8195 | AUROC=0.9518 | AUPRC=0.8965
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8442 | F1=0.9192 | AUROC=0.9728 | AUPRC=0.9746
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4173 | F1=0.7263 | AUROC=0.7643 | AUPRC=0.7271
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5274 | F1=0.7629 | AUROC=0.8693 | AUPRC=0.8388
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.6237 | val_loss=0.5276 | val_mcc=0.4564 | val_f1=0.5672 | val_auroc=0.7986

[Epoch 02] train_loss=0.5351 | val_loss=0.5137 | val_mcc=0.4887 | val_f1=0.5920 | val_auroc=0.8093

[Epoch 03] train_loss=0.5173 | val_loss=0.4130 | val_mcc=0.5239 | val_f1=0.6011 | val_auroc=0.8150

[Epoch 04] train_loss=0.5055 | val_loss=0.4539 | val_mcc=0.5247 | val_f1=0.6152 | val_auroc=0.8187

[Epoch 05] train_loss=0.4982 | val_loss=0.4087 | val_mcc=0.5338 | val_f1=0.6204 | val_auroc=0.8252

[Epoch 06] train_loss=0.4855 | val_loss=0.4583 | val_mcc=0.5231 | val_f1=0.6183 | val_auroc=0.8311

[Epoch 07] train_loss=0.4792 | val_loss=0.4396 | val_mcc=0.5303 | val_f1=0.6226 | val_auroc=0.8346

[Epoch 08] train_loss=0.4722 | val_loss=0.4008 | val_mcc=0.5341 | val_f1=0.6260 | val_auroc=0.8415

[Epoch 09] train_loss=0.4661 | val_loss=0.4319 | val_mcc=0.5193 | val_f1=0.6170 | val_auroc=0.8467

[Epoch 10] train_loss=0.4623 | val_loss=0.3982 | val_mcc=0.5435 | val_f1=0.6343 | val_auroc=0.8485

[Epoch 11] train_loss=0.4562 | val_loss=0.3943 | val_mcc=0.5471 | val_f1=0.6362 | val_auroc=0.8473

[Epoch 12] train_loss=0.4515 | val_loss=0.3684 | val_mcc=0.5601 | val_f1=0.6433 | val_auroc=0.8499

[Epoch 13] train_loss=0.4467 | val_loss=0.4145 | val_mcc=0.5366 | val_f1=0.6304 | val_auroc=0.8517

[Epoch 14] train_loss=0.4414 | val_loss=0.3852 | val_mcc=0.5539 | val_f1=0.6427 | val_auroc=0.8568

[Epoch 15] train_loss=0.4389 | val_loss=0.4814 | val_mcc=0.4923 | val_f1=0.5946 | val_auroc=0.8600

[Epoch 16] train_loss=0.4314 | val_loss=0.4022 | val_mcc=0.5390 | val_f1=0.6322 | val_auroc=0.8599

[Epoch 17] train_loss=0.4208 | val_loss=0.4191 | val_mcc=0.5306 | val_f1=0.6260 | val_auroc=0.8620

[Epoch 18] train_loss=0.4193 | val_loss=0.4421 | val_mcc=0.5169 | val_f1=0.6148 | val_auroc=0.8639
[EarlyStop] epoch=18 | best_val_mcc=0.5601
[Test] train3__val_cls_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5741 | F1=0.6824 | AUROC=0.8461 | AUPRC=0.7562
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5311 | F1=0.7270 | AUROC=0.8200 | AUPRC=0.8362
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3573 | F1=0.6370 | AUROC=0.7346 | AUPRC=0.7442
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5180 | F1=0.7138 | AUROC=0.8114 | AUPRC=0.8134
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 360.
[Test] train3__val_cls_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5679 | F1=0.6920 | AUROC=0.8794 | AUPRC=0.7887
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5167 | F1=0.7493 | AUROC=0.8586 | AUPRC=0.8683
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3578 | F1=0.6758 | AUROC=0.7480 | AUPRC=0.7548
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5079 | F1=0.7307 | AUROC=0.8382 | AUPRC=0.8289
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 169.
[Test] train3__val_cls_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5652 | F1=0.6890 | AUROC=0.8666 | AUPRC=0.7739
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5371 | F1=0.7578 | AUROC=0.8408 | AUPRC=0.8573
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3821 | F1=0.6826 | AUROC=0.7455 | AUPRC=0.7368
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5131 | F1=0.7321 | AUROC=0.8177 | AUPRC=0.8111
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4279 | val_loss=0.2227 | val_mcc=0.7212 | val_f1=0.7759 | val_auroc=0.9570

[Epoch 02] train_loss=0.3216 | val_loss=0.2488 | val_mcc=0.7060 | val_f1=0.7606 | val_auroc=0.9581

[Epoch 03] train_loss=0.3109 | val_loss=0.2444 | val_mcc=0.7096 | val_f1=0.7640 | val_auroc=0.9588

[Epoch 04] train_loss=0.3014 | val_loss=0.2330 | val_mcc=0.7230 | val_f1=0.7760 | val_auroc=0.9593

[Epoch 05] train_loss=0.2932 | val_loss=0.2261 | val_mcc=0.7266 | val_f1=0.7792 | val_auroc=0.9600

[Epoch 06] train_loss=0.2904 | val_loss=0.2454 | val_mcc=0.7156 | val_f1=0.7678 | val_auroc=0.9605

[Epoch 07] train_loss=0.2857 | val_loss=0.2377 | val_mcc=0.7250 | val_f1=0.7769 | val_auroc=0.9605

[Epoch 08] train_loss=0.2825 | val_loss=0.2002 | val_mcc=0.7426 | val_f1=0.7926 | val_auroc=0.9609

[Epoch 09] train_loss=0.2805 | val_loss=0.2235 | val_mcc=0.7273 | val_f1=0.7799 | val_auroc=0.9610

[Epoch 10] train_loss=0.2763 | val_loss=0.2187 | val_mcc=0.7296 | val_f1=0.7818 | val_auroc=0.9620

[Epoch 11] train_loss=0.2744 | val_loss=0.2057 | val_mcc=0.7438 | val_f1=0.7939 | val_auroc=0.9622

[Epoch 12] train_loss=0.2716 | val_loss=0.2444 | val_mcc=0.7180 | val_f1=0.7694 | val_auroc=0.9626

[Epoch 13] train_loss=0.2705 | val_loss=0.2176 | val_mcc=0.7378 | val_f1=0.7885 | val_auroc=0.9628

[Epoch 14] train_loss=0.2666 | val_loss=0.2077 | val_mcc=0.7462 | val_f1=0.7957 | val_auroc=0.9635

[Epoch 15] train_loss=0.2656 | val_loss=0.1947 | val_mcc=0.7506 | val_f1=0.7991 | val_auroc=0.9634

[Epoch 16] train_loss=0.2610 | val_loss=0.2124 | val_mcc=0.7454 | val_f1=0.7948 | val_auroc=0.9634

[Epoch 17] train_loss=0.2574 | val_loss=0.2327 | val_mcc=0.7298 | val_f1=0.7797 | val_auroc=0.9650

[Epoch 18] train_loss=0.2568 | val_loss=0.2210 | val_mcc=0.7437 | val_f1=0.7923 | val_auroc=0.9643

[Epoch 19] train_loss=0.2517 | val_loss=0.2152 | val_mcc=0.7525 | val_f1=0.7997 | val_auroc=0.9657

[Epoch 20] train_loss=0.2486 | val_loss=0.2272 | val_mcc=0.7401 | val_f1=0.7890 | val_auroc=0.9652

[Epoch 21] train_loss=0.2463 | val_loss=0.2348 | val_mcc=0.7362 | val_f1=0.7848 | val_auroc=0.9659

[Epoch 22] train_loss=0.2452 | val_loss=0.2059 | val_mcc=0.7537 | val_f1=0.8014 | val_auroc=0.9656

[Epoch 23] train_loss=0.2392 | val_loss=0.2322 | val_mcc=0.7401 | val_f1=0.7889 | val_auroc=0.9646

[Epoch 24] train_loss=0.2391 | val_loss=0.2421 | val_mcc=0.7352 | val_f1=0.7832 | val_auroc=0.9661

[Epoch 25] train_loss=0.2336 | val_loss=0.2050 | val_mcc=0.7554 | val_f1=0.8031 | val_auroc=0.9654

[Epoch 26] train_loss=0.2270 | val_loss=0.2249 | val_mcc=0.7403 | val_f1=0.7895 | val_auroc=0.9653

[Epoch 27] train_loss=0.2257 | val_loss=0.1962 | val_mcc=0.7581 | val_f1=0.8054 | val_auroc=0.9651

[Epoch 28] train_loss=0.2193 | val_loss=0.2211 | val_mcc=0.7472 | val_f1=0.7953 | val_auroc=0.9652

[Epoch 29] train_loss=0.2172 | val_loss=0.2064 | val_mcc=0.7543 | val_f1=0.8023 | val_auroc=0.9642

[Epoch 30] train_loss=0.2130 | val_loss=0.1994 | val_mcc=0.7525 | val_f1=0.8005 | val_auroc=0.9628
[Test] train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7665 | F1=0.8315 | AUROC=0.9558 | AUPRC=0.9011
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7961 | F1=0.8896 | AUROC=0.9715 | AUPRC=0.9695
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4423 | F1=0.7311 | AUROC=0.7736 | AUPRC=0.7628
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5810 | F1=0.7868 | AUROC=0.8833 | AUPRC=0.8590
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 163.
[Test] train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7629 | F1=0.8293 | AUROC=0.9613 | AUPRC=0.9154
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8417 | F1=0.9174 | AUROC=0.9817 | AUPRC=0.9820
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4041 | F1=0.7209 | AUROC=0.7720 | AUPRC=0.7611
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5494 | F1=0.7723 | AUROC=0.8907 | AUPRC=0.8706
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 180.
[Test] train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7534 | F1=0.8226 | AUROC=0.9546 | AUPRC=0.9062
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8383 | F1=0.9165 | AUROC=0.9721 | AUPRC=0.9714
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4448 | F1=0.7392 | AUROC=0.7753 | AUPRC=0.7529
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5436 | F1=0.7700 | AUROC=0.8762 | AUPRC=0.8564
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.5835 | val_loss=0.5042 | val_mcc=0.4770 | val_f1=0.5846 | val_auroc=0.8273

[Epoch 02] train_loss=0.5034 | val_loss=0.3940 | val_mcc=0.5302 | val_f1=0.6227 | val_auroc=0.8458

[Epoch 03] train_loss=0.4726 | val_loss=0.4093 | val_mcc=0.5344 | val_f1=0.6280 | val_auroc=0.8542

[Epoch 04] train_loss=0.4449 | val_loss=0.3632 | val_mcc=0.5603 | val_f1=0.6464 | val_auroc=0.8642

[Epoch 05] train_loss=0.4180 | val_loss=0.3873 | val_mcc=0.5546 | val_f1=0.6442 | val_auroc=0.8666

[Epoch 06] train_loss=0.3871 | val_loss=0.3856 | val_mcc=0.5593 | val_f1=0.6483 | val_auroc=0.8740

[Epoch 07] train_loss=0.3559 | val_loss=0.4008 | val_mcc=0.5549 | val_f1=0.6448 | val_auroc=0.8728

[Epoch 08] train_loss=0.3250 | val_loss=0.4142 | val_mcc=0.5464 | val_f1=0.6383 | val_auroc=0.8722

[Epoch 09] train_loss=0.2819 | val_loss=0.4698 | val_mcc=0.5290 | val_f1=0.6237 | val_auroc=0.8718

[Epoch 10] train_loss=0.2627 | val_loss=0.4635 | val_mcc=0.5315 | val_f1=0.6262 | val_auroc=0.8683
[EarlyStop] epoch=10 | best_val_mcc=0.5603
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5901 | F1=0.6978 | AUROC=0.8754 | AUPRC=0.7665
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5732 | F1=0.7583 | AUROC=0.8593 | AUPRC=0.8608
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4002 | F1=0.6650 | AUROC=0.7482 | AUPRC=0.7311
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5668 | F1=0.7492 | AUROC=0.8543 | AUPRC=0.8342
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5913 | val_loss=0.4259 | val_mcc=0.5066 | val_f1=0.6044 | val_auroc=0.8325

[Epoch 02] train_loss=0.5069 | val_loss=0.3788 | val_mcc=0.5359 | val_f1=0.6247 | val_auroc=0.8484

[Epoch 03] train_loss=0.4678 | val_loss=0.5297 | val_mcc=0.4965 | val_f1=0.5960 | val_auroc=0.8573

[Epoch 04] train_loss=0.4444 | val_loss=0.4308 | val_mcc=0.5423 | val_f1=0.6351 | val_auroc=0.8649

[Epoch 05] train_loss=0.4092 | val_loss=0.3912 | val_mcc=0.5557 | val_f1=0.6449 | val_auroc=0.8672

[Epoch 06] train_loss=0.3792 | val_loss=0.3844 | val_mcc=0.5601 | val_f1=0.6485 | val_auroc=0.8678

[Epoch 07] train_loss=0.3522 | val_loss=0.4262 | val_mcc=0.5421 | val_f1=0.6349 | val_auroc=0.8651

[Epoch 08] train_loss=0.3246 | val_loss=0.4334 | val_mcc=0.5477 | val_f1=0.6391 | val_auroc=0.8624

[Epoch 09] train_loss=0.2960 | val_loss=0.5213 | val_mcc=0.5198 | val_f1=0.6163 | val_auroc=0.8580

[Epoch 10] train_loss=0.2578 | val_loss=0.6587 | val_mcc=0.4771 | val_f1=0.5803 | val_auroc=0.8469

[Epoch 11] train_loss=0.2145 | val_loss=0.6736 | val_mcc=0.5010 | val_f1=0.6014 | val_auroc=0.8484

[Epoch 12] train_loss=0.1838 | val_loss=0.6829 | val_mcc=0.4912 | val_f1=0.5953 | val_auroc=0.8384
[EarlyStop] epoch=12 | best_val_mcc=0.5601
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5936 | F1=0.7045 | AUROC=0.8800 | AUPRC=0.7463
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5617 | F1=0.7648 | AUROC=0.8537 | AUPRC=0.8371
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3999 | F1=0.6763 | AUROC=0.7462 | AUPRC=0.7219
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5648 | F1=0.7548 | AUROC=0.8583 | AUPRC=0.8205
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5899 | val_loss=0.4163 | val_mcc=0.5040 | val_f1=0.6024 | val_auroc=0.8356

[Epoch 02] train_loss=0.4977 | val_loss=0.4143 | val_mcc=0.5208 | val_f1=0.6179 | val_auroc=0.8538

[Epoch 03] train_loss=0.4639 | val_loss=0.3758 | val_mcc=0.5413 | val_f1=0.6318 | val_auroc=0.8644

[Epoch 04] train_loss=0.4384 | val_loss=0.4308 | val_mcc=0.5409 | val_f1=0.6335 | val_auroc=0.8738

[Epoch 05] train_loss=0.4158 | val_loss=0.3935 | val_mcc=0.5676 | val_f1=0.6546 | val_auroc=0.8774

[Epoch 06] train_loss=0.3879 | val_loss=0.3888 | val_mcc=0.5655 | val_f1=0.6531 | val_auroc=0.8768

[Epoch 07] train_loss=0.3556 | val_loss=0.3771 | val_mcc=0.5656 | val_f1=0.6526 | val_auroc=0.8767

[Epoch 08] train_loss=0.3277 | val_loss=0.4604 | val_mcc=0.5401 | val_f1=0.6330 | val_auroc=0.8731

[Epoch 09] train_loss=0.2938 | val_loss=0.4189 | val_mcc=0.5413 | val_f1=0.6329 | val_auroc=0.8652

[Epoch 10] train_loss=0.2492 | val_loss=0.5159 | val_mcc=0.5341 | val_f1=0.6286 | val_auroc=0.8614

[Epoch 11] train_loss=0.2271 | val_loss=0.5342 | val_mcc=0.5408 | val_f1=0.6339 | val_auroc=0.8599
[EarlyStop] epoch=11 | best_val_mcc=0.5676
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5934 | F1=0.7052 | AUROC=0.8887 | AUPRC=0.7813
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5458 | F1=0.7527 | AUROC=0.8662 | AUPRC=0.8653
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3800 | F1=0.6745 | AUROC=0.7524 | AUPRC=0.7279
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5677 | F1=0.7605 | AUROC=0.8650 | AUPRC=0.8378
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5929 | val_loss=0.4093 | val_mcc=0.4994 | val_f1=0.5959 | val_auroc=0.8325

[Epoch 02] train_loss=0.5082 | val_loss=0.4304 | val_mcc=0.5143 | val_f1=0.6134 | val_auroc=0.8455

[Epoch 03] train_loss=0.4687 | val_loss=0.4497 | val_mcc=0.5212 | val_f1=0.6181 | val_auroc=0.8585

[Epoch 04] train_loss=0.4410 | val_loss=0.4100 | val_mcc=0.5424 | val_f1=0.6352 | val_auroc=0.8661

[Epoch 05] train_loss=0.4122 | val_loss=0.3994 | val_mcc=0.5471 | val_f1=0.6388 | val_auroc=0.8746

[Epoch 06] train_loss=0.3804 | val_loss=0.4537 | val_mcc=0.5358 | val_f1=0.6280 | val_auroc=0.8755

[Epoch 07] train_loss=0.3493 | val_loss=0.4322 | val_mcc=0.5366 | val_f1=0.6299 | val_auroc=0.8717

[Epoch 08] train_loss=0.3135 | val_loss=0.4549 | val_mcc=0.5347 | val_f1=0.6279 | val_auroc=0.8742

[Epoch 09] train_loss=0.2751 | val_loss=0.4719 | val_mcc=0.5255 | val_f1=0.6217 | val_auroc=0.8670

[Epoch 10] train_loss=0.2300 | val_loss=0.4553 | val_mcc=0.5355 | val_f1=0.6297 | val_auroc=0.8643

[Epoch 11] train_loss=0.2008 | val_loss=0.4854 | val_mcc=0.5295 | val_f1=0.6251 | val_auroc=0.8617
[EarlyStop] epoch=11 | best_val_mcc=0.5471
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5927 | F1=0.7078 | AUROC=0.8847 | AUPRC=0.7753
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5660 | F1=0.7713 | AUROC=0.8636 | AUPRC=0.8595
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3745 | F1=0.6800 | AUROC=0.7502 | AUPRC=0.7300
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5661 | F1=0.7643 | AUROC=0.8595 | AUPRC=0.8338
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 174.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5860 | F1=0.7057 | AUROC=0.8833 | AUPRC=0.7671
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5712 | F1=0.7882 | AUROC=0.8640 | AUPRC=0.8526
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3929 | F1=0.7024 | AUROC=0.7401 | AUPRC=0.7214
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5472 | F1=0.7596 | AUROC=0.8575 | AUPRC=0.8302
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 79.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5743 | F1=0.6961 | AUROC=0.8770 | AUPRC=0.7682
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5713 | F1=0.7756 | AUROC=0.8707 | AUPRC=0.8671
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3684 | F1=0.6789 | AUROC=0.7437 | AUPRC=0.7272
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5731 | F1=0.7685 | AUROC=0.8563 | AUPRC=0.8355
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 51.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5720 | F1=0.6944 | AUROC=0.8721 | AUPRC=0.7640
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5511 | F1=0.7663 | AUROC=0.8609 | AUPRC=0.8592
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3534 | F1=0.6712 | AUROC=0.7425 | AUPRC=0.7313
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5510 | F1=0.7560 | AUROC=0.8476 | AUPRC=0.8253
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 53.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5679 | F1=0.6916 | AUROC=0.8774 | AUPRC=0.7667
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5563 | F1=0.7719 | AUROC=0.8614 | AUPRC=0.8676
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3758 | F1=0.6844 | AUROC=0.7520 | AUPRC=0.7330
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4159 | val_loss=0.2239 | val_mcc=0.7325 | val_f1=0.7850 | val_auroc=0.9549

[Epoch 02] train_loss=0.3126 | val_loss=0.2122 | val_mcc=0.7436 | val_f1=0.7936 | val_auroc=0.9565

[Epoch 03] train_loss=0.2911 | val_loss=0.2223 | val_mcc=0.7427 | val_f1=0.7930 | val_auroc=0.9574

[Epoch 04] train_loss=0.2751 | val_loss=0.2204 | val_mcc=0.7362 | val_f1=0.7879 | val_auroc=0.9581

[Epoch 05] train_loss=0.2609 | val_loss=0.2018 | val_mcc=0.7500 | val_f1=0.7966 | val_auroc=0.9576

[Epoch 06] train_loss=0.2491 | val_loss=0.2036 | val_mcc=0.7500 | val_f1=0.7983 | val_auroc=0.9589

[Epoch 07] train_loss=0.2333 | val_loss=0.2341 | val_mcc=0.7299 | val_f1=0.7826 | val_auroc=0.9575

[Epoch 08] train_loss=0.2131 | val_loss=0.3675 | val_mcc=0.6546 | val_f1=0.7122 | val_auroc=0.9582

[Epoch 09] train_loss=0.1985 | val_loss=0.2892 | val_mcc=0.7030 | val_f1=0.7584 | val_auroc=0.9545

[Epoch 10] train_loss=0.1662 | val_loss=0.2727 | val_mcc=0.7111 | val_f1=0.7667 | val_auroc=0.9546

[Epoch 11] train_loss=0.1543 | val_loss=0.2683 | val_mcc=0.7137 | val_f1=0.7697 | val_auroc=0.9532
[EarlyStop] epoch=11 | best_val_mcc=0.7500
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7508 | F1=0.8147 | AUROC=0.9506 | AUPRC=0.8921
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7337 | F1=0.8444 | AUROC=0.9691 | AUPRC=0.9689
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4055 | F1=0.6881 | AUROC=0.7622 | AUPRC=0.7541
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6163 | F1=0.8008 | AUROC=0.8828 | AUPRC=0.8434
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4436 | val_loss=0.2889 | val_mcc=0.6803 | val_f1=0.7378 | val_auroc=0.9541

[Epoch 02] train_loss=0.3190 | val_loss=0.2667 | val_mcc=0.7042 | val_f1=0.7583 | val_auroc=0.9588

[Epoch 03] train_loss=0.3002 | val_loss=0.2767 | val_mcc=0.6964 | val_f1=0.7513 | val_auroc=0.9577

[Epoch 04] train_loss=0.2814 | val_loss=0.2155 | val_mcc=0.7455 | val_f1=0.7953 | val_auroc=0.9593

[Epoch 05] train_loss=0.2629 | val_loss=0.2630 | val_mcc=0.7109 | val_f1=0.7651 | val_auroc=0.9579

[Epoch 06] train_loss=0.2506 | val_loss=0.2213 | val_mcc=0.7429 | val_f1=0.7929 | val_auroc=0.9610

[Epoch 07] train_loss=0.2330 | val_loss=0.2298 | val_mcc=0.7346 | val_f1=0.7863 | val_auroc=0.9593

[Epoch 08] train_loss=0.2149 | val_loss=0.2520 | val_mcc=0.7200 | val_f1=0.7735 | val_auroc=0.9582

[Epoch 09] train_loss=0.1913 | val_loss=0.2787 | val_mcc=0.7041 | val_f1=0.7610 | val_auroc=0.9538

[Epoch 10] train_loss=0.1766 | val_loss=0.2979 | val_mcc=0.6978 | val_f1=0.7552 | val_auroc=0.9517
[EarlyStop] epoch=10 | best_val_mcc=0.7455
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7613 | F1=0.8277 | AUROC=0.9538 | AUPRC=0.8964
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8216 | F1=0.9033 | AUROC=0.9750 | AUPRC=0.9756
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3941 | F1=0.7080 | AUROC=0.7606 | AUPRC=0.7502
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5861 | F1=0.7893 | AUROC=0.8831 | AUPRC=0.8424
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4355 | val_loss=0.2186 | val_mcc=0.6982 | val_f1=0.7420 | val_auroc=0.9549

[Epoch 02] train_loss=0.3140 | val_loss=0.2319 | val_mcc=0.7304 | val_f1=0.7823 | val_auroc=0.9592

[Epoch 03] train_loss=0.2989 | val_loss=0.2102 | val_mcc=0.7451 | val_f1=0.7947 | val_auroc=0.9589

[Epoch 04] train_loss=0.2766 | val_loss=0.2031 | val_mcc=0.7498 | val_f1=0.7986 | val_auroc=0.9613

[Epoch 05] train_loss=0.2648 | val_loss=0.2035 | val_mcc=0.7477 | val_f1=0.7960 | val_auroc=0.9589

[Epoch 06] train_loss=0.2505 | val_loss=0.2068 | val_mcc=0.7435 | val_f1=0.7933 | val_auroc=0.9594

[Epoch 07] train_loss=0.2406 | val_loss=0.2061 | val_mcc=0.7476 | val_f1=0.7964 | val_auroc=0.9600

[Epoch 08] train_loss=0.2183 | val_loss=0.2249 | val_mcc=0.7405 | val_f1=0.7913 | val_auroc=0.9586

[Epoch 09] train_loss=0.1939 | val_loss=0.2258 | val_mcc=0.7389 | val_f1=0.7864 | val_auroc=0.9558

[Epoch 10] train_loss=0.1790 | val_loss=0.2657 | val_mcc=0.7230 | val_f1=0.7773 | val_auroc=0.9537
[EarlyStop] epoch=10 | best_val_mcc=0.7498
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7642 | F1=0.8287 | AUROC=0.9552 | AUPRC=0.9009
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7899 | F1=0.8869 | AUROC=0.9731 | AUPRC=0.9729
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3942 | F1=0.7012 | AUROC=0.7606 | AUPRC=0.7470
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5833 | F1=0.7878 | AUROC=0.8870 | AUPRC=0.8573
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4051 | val_loss=0.2528 | val_mcc=0.7053 | val_f1=0.7617 | val_auroc=0.9550

[Epoch 02] train_loss=0.3070 | val_loss=0.2359 | val_mcc=0.7246 | val_f1=0.7778 | val_auroc=0.9571

[Epoch 03] train_loss=0.2873 | val_loss=0.2419 | val_mcc=0.7224 | val_f1=0.7754 | val_auroc=0.9587

[Epoch 04] train_loss=0.2706 | val_loss=0.2184 | val_mcc=0.7416 | val_f1=0.7920 | val_auroc=0.9594

[Epoch 05] train_loss=0.2531 | val_loss=0.2411 | val_mcc=0.7245 | val_f1=0.7770 | val_auroc=0.9588

[Epoch 06] train_loss=0.2371 | val_loss=0.2326 | val_mcc=0.7291 | val_f1=0.7818 | val_auroc=0.9590

[Epoch 07] train_loss=0.2205 | val_loss=0.2211 | val_mcc=0.7457 | val_f1=0.7954 | val_auroc=0.9597

[Epoch 08] train_loss=0.2017 | val_loss=0.2223 | val_mcc=0.7441 | val_f1=0.7941 | val_auroc=0.9574

[Epoch 09] train_loss=0.1794 | val_loss=0.2362 | val_mcc=0.7371 | val_f1=0.7886 | val_auroc=0.9545

[Epoch 10] train_loss=0.1533 | val_loss=0.2470 | val_mcc=0.7296 | val_f1=0.7824 | val_auroc=0.9518

[Epoch 11] train_loss=0.1248 | val_loss=0.2974 | val_mcc=0.7078 | val_f1=0.7643 | val_auroc=0.9519

[Epoch 12] train_loss=0.0924 | val_loss=0.3401 | val_mcc=0.6910 | val_f1=0.7504 | val_auroc=0.9483

[Epoch 13] train_loss=0.0736 | val_loss=0.3363 | val_mcc=0.6993 | val_f1=0.7576 | val_auroc=0.9478
[EarlyStop] epoch=13 | best_val_mcc=0.7457
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7568 | F1=0.8244 | AUROC=0.9519 | AUPRC=0.8950
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8001 | F1=0.8902 | AUROC=0.9721 | AUPRC=0.9728
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3940 | F1=0.7116 | AUROC=0.7576 | AUPRC=0.7428
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5615 | F1=0.7779 | AUROC=0.8790 | AUPRC=0.8427
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 178.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7599 | F1=0.8270 | AUROC=0.9613 | AUPRC=0.9143
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8593 | F1=0.9258 | AUROC=0.9846 | AUPRC=0.9852
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4158 | F1=0.7275 | AUROC=0.7614 | AUPRC=0.7499
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5429 | F1=0.7695 | AUROC=0.8982 | AUPRC=0.8718
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 149.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7555 | F1=0.8240 | AUROC=0.9550 | AUPRC=0.9031
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8362 | F1=0.9142 | AUROC=0.9776 | AUPRC=0.9788
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3786 | F1=0.7097 | AUROC=0.7622 | AUPRC=0.7496
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5682 | F1=0.7805 | AUROC=0.8921 | AUPRC=0.8570
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 70.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7547 | F1=0.8235 | AUROC=0.9547 | AUPRC=0.9012
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8107 | F1=0.9007 | AUROC=0.9761 | AUPRC=0.9764
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3962 | F1=0.7142 | AUROC=0.7659 | AUPRC=0.7471
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5667 | F1=0.7801 | AUROC=0.8859 | AUPRC=0.8564
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 107.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7546 | F1=0.8234 | AUROC=0.9552 | AUPRC=0.9015
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8314 | F1=0.9104 | AUROC=0.9764 | AUPRC=0.9769
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5879 | val_loss=0.4243 | val_mcc=0.4673 | val_f1=0.5681 | val_auroc=0.8249

[Epoch 02] train_loss=0.5111 | val_loss=0.4170 | val_mcc=0.4839 | val_f1=0.5863 | val_auroc=0.8381

[Epoch 03] train_loss=0.4750 | val_loss=0.4398 | val_mcc=0.4882 | val_f1=0.5934 | val_auroc=0.8487

[Epoch 04] train_loss=0.4465 | val_loss=0.4684 | val_mcc=0.4807 | val_f1=0.5869 | val_auroc=0.8559

[Epoch 05] train_loss=0.4140 | val_loss=0.4745 | val_mcc=0.4913 | val_f1=0.5941 | val_auroc=0.8626

[Epoch 06] train_loss=0.3769 | val_loss=0.4329 | val_mcc=0.4998 | val_f1=0.6022 | val_auroc=0.8632

[Epoch 07] train_loss=0.3355 | val_loss=0.5280 | val_mcc=0.4801 | val_f1=0.5843 | val_auroc=0.8607

[Epoch 08] train_loss=0.2933 | val_loss=0.4913 | val_mcc=0.4815 | val_f1=0.5882 | val_auroc=0.8580

[Epoch 09] train_loss=0.2541 | val_loss=0.5266 | val_mcc=0.4725 | val_f1=0.5814 | val_auroc=0.8468

[Epoch 10] train_loss=0.2179 | val_loss=0.6283 | val_mcc=0.4602 | val_f1=0.5712 | val_auroc=0.8470

[Epoch 11] train_loss=0.1657 | val_loss=0.6496 | val_mcc=0.4628 | val_f1=0.5733 | val_auroc=0.8472

[Epoch 12] train_loss=0.1508 | val_loss=0.7044 | val_mcc=0.4518 | val_f1=0.5637 | val_auroc=0.8413
[EarlyStop] epoch=12 | best_val_mcc=0.4998
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5611 | F1=0.6857 | AUROC=0.8730 | AUPRC=0.7487
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5047 | F1=0.7336 | AUROC=0.8297 | AUPRC=0.8266
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3281 | F1=0.6543 | AUROC=0.7244 | AUPRC=0.7031
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5120 | F1=0.7327 | AUROC=0.8379 | AUPRC=0.8036
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5899 | val_loss=0.4131 | val_mcc=0.4740 | val_f1=0.5708 | val_auroc=0.8251

[Epoch 02] train_loss=0.5092 | val_loss=0.3831 | val_mcc=0.4902 | val_f1=0.5825 | val_auroc=0.8398

[Epoch 03] train_loss=0.4746 | val_loss=0.4481 | val_mcc=0.4795 | val_f1=0.5867 | val_auroc=0.8455

[Epoch 04] train_loss=0.4439 | val_loss=0.4571 | val_mcc=0.4885 | val_f1=0.5934 | val_auroc=0.8568

[Epoch 05] train_loss=0.4073 | val_loss=0.5683 | val_mcc=0.4657 | val_f1=0.5699 | val_auroc=0.8595

[Epoch 06] train_loss=0.3743 | val_loss=0.5308 | val_mcc=0.4811 | val_f1=0.5861 | val_auroc=0.8586

[Epoch 07] train_loss=0.3242 | val_loss=0.5091 | val_mcc=0.4972 | val_f1=0.6003 | val_auroc=0.8577

[Epoch 08] train_loss=0.2987 | val_loss=0.5868 | val_mcc=0.4850 | val_f1=0.5899 | val_auroc=0.8504

[Epoch 09] train_loss=0.2726 | val_loss=0.6272 | val_mcc=0.4826 | val_f1=0.5879 | val_auroc=0.8485

[Epoch 10] train_loss=0.2523 | val_loss=0.6475 | val_mcc=0.4753 | val_f1=0.5830 | val_auroc=0.8439

[Epoch 11] train_loss=0.2269 | val_loss=0.7124 | val_mcc=0.4712 | val_f1=0.5796 | val_auroc=0.8374

[Epoch 12] train_loss=0.1983 | val_loss=0.7121 | val_mcc=0.4758 | val_f1=0.5839 | val_auroc=0.8362

[Epoch 13] train_loss=0.1849 | val_loss=0.7932 | val_mcc=0.4713 | val_f1=0.5797 | val_auroc=0.8357
[EarlyStop] epoch=13 | best_val_mcc=0.4972
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5561 | F1=0.6830 | AUROC=0.8647 | AUPRC=0.7299
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5060 | F1=0.7403 | AUROC=0.8248 | AUPRC=0.8122
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3338 | F1=0.6647 | AUROC=0.7169 | AUPRC=0.6976
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5144 | F1=0.7372 | AUROC=0.8261 | AUPRC=0.7927
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5857 | val_loss=0.4099 | val_mcc=0.4668 | val_f1=0.5681 | val_auroc=0.8299

[Epoch 02] train_loss=0.5021 | val_loss=0.3950 | val_mcc=0.4965 | val_f1=0.5952 | val_auroc=0.8463

[Epoch 03] train_loss=0.4683 | val_loss=0.3723 | val_mcc=0.5018 | val_f1=0.5953 | val_auroc=0.8560

[Epoch 04] train_loss=0.4390 | val_loss=0.3641 | val_mcc=0.5047 | val_f1=0.5969 | val_auroc=0.8631

[Epoch 05] train_loss=0.3974 | val_loss=0.4022 | val_mcc=0.5026 | val_f1=0.6019 | val_auroc=0.8636

[Epoch 06] train_loss=0.3645 | val_loss=0.4009 | val_mcc=0.4951 | val_f1=0.5942 | val_auroc=0.8624

[Epoch 07] train_loss=0.3194 | val_loss=0.4491 | val_mcc=0.5060 | val_f1=0.6057 | val_auroc=0.8589

[Epoch 08] train_loss=0.2732 | val_loss=0.4868 | val_mcc=0.4972 | val_f1=0.5941 | val_auroc=0.8514

[Epoch 09] train_loss=0.2326 | val_loss=0.5536 | val_mcc=0.4874 | val_f1=0.5911 | val_auroc=0.8401

[Epoch 10] train_loss=0.1982 | val_loss=0.6238 | val_mcc=0.4685 | val_f1=0.5738 | val_auroc=0.8252

[Epoch 11] train_loss=0.1705 | val_loss=0.7479 | val_mcc=0.4582 | val_f1=0.5704 | val_auroc=0.8305

[Epoch 12] train_loss=0.1236 | val_loss=0.7787 | val_mcc=0.4766 | val_f1=0.5835 | val_auroc=0.8252

[Epoch 13] train_loss=0.1026 | val_loss=0.8792 | val_mcc=0.4698 | val_f1=0.5793 | val_auroc=0.8249
[EarlyStop] epoch=13 | best_val_mcc=0.5060
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5690 | F1=0.6885 | AUROC=0.8691 | AUPRC=0.7381
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5049 | F1=0.7250 | AUROC=0.8241 | AUPRC=0.8193
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3479 | F1=0.6512 | AUROC=0.7214 | AUPRC=0.7059
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5110 | F1=0.7266 | AUROC=0.8289 | AUPRC=0.7938
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5835 | val_loss=0.4696 | val_mcc=0.4637 | val_f1=0.5744 | val_auroc=0.8272

[Epoch 02] train_loss=0.5017 | val_loss=0.4362 | val_mcc=0.4823 | val_f1=0.5885 | val_auroc=0.8405

[Epoch 03] train_loss=0.4678 | val_loss=0.4048 | val_mcc=0.4990 | val_f1=0.6004 | val_auroc=0.8500

[Epoch 04] train_loss=0.4359 | val_loss=0.3926 | val_mcc=0.5019 | val_f1=0.6024 | val_auroc=0.8575

[Epoch 05] train_loss=0.4000 | val_loss=0.4572 | val_mcc=0.4954 | val_f1=0.5979 | val_auroc=0.8638

[Epoch 06] train_loss=0.3617 | val_loss=0.4345 | val_mcc=0.5012 | val_f1=0.6033 | val_auroc=0.8631

[Epoch 07] train_loss=0.3187 | val_loss=0.4590 | val_mcc=0.4960 | val_f1=0.5994 | val_auroc=0.8630

[Epoch 08] train_loss=0.2718 | val_loss=0.5641 | val_mcc=0.4791 | val_f1=0.5849 | val_auroc=0.8552

[Epoch 09] train_loss=0.2119 | val_loss=0.6018 | val_mcc=0.4734 | val_f1=0.5798 | val_auroc=0.8547

[Epoch 10] train_loss=0.1808 | val_loss=0.6140 | val_mcc=0.4690 | val_f1=0.5782 | val_auroc=0.8508
[EarlyStop] epoch=10 | best_val_mcc=0.5019
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5619 | F1=0.6810 | AUROC=0.8721 | AUPRC=0.7530
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5074 | F1=0.7206 | AUROC=0.8316 | AUPRC=0.8322
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3314 | F1=0.6421 | AUROC=0.7294 | AUPRC=0.7066
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5150 | F1=0.7236 | AUROC=0.8413 | AUPRC=0.8093
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 140.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5450 | F1=0.6779 | AUROC=0.8655 | AUPRC=0.7250
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.4964 | F1=0.7438 | AUROC=0.8315 | AUPRC=0.8247
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3358 | F1=0.6740 | AUROC=0.7183 | AUPRC=0.7044
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5106 | F1=0.7436 | AUROC=0.8301 | AUPRC=0.7943
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 82.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5465 | F1=0.6781 | AUROC=0.8643 | AUPRC=0.7405
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5051 | F1=0.7456 | AUROC=0.8289 | AUPRC=0.8259
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3175 | F1=0.6612 | AUROC=0.7288 | AUPRC=0.7059
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5119 | F1=0.7412 | AUROC=0.8329 | AUPRC=0.8000
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 36.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5565 | F1=0.6837 | AUROC=0.8629 | AUPRC=0.7361
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5084 | F1=0.7437 | AUROC=0.8287 | AUPRC=0.8275
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3174 | F1=0.6508 | AUROC=0.7165 | AUPRC=0.6985
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5124 | F1=0.7377 | AUROC=0.8322 | AUPRC=0.7915
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 46.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5624 | F1=0.6885 | AUROC=0.8683 | AUPRC=0.7460
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5505 | F1=0.7710 | AUROC=0.8369 | AUPRC=0.8337
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3413 | F1=0.6682 | AUROC=0.7321 | AUPRC=0.7082
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4305 | val_loss=0.2352 | val_mcc=0.7154 | val_f1=0.7711 | val_auroc=0.9552

[Epoch 02] train_loss=0.3112 | val_loss=0.2265 | val_mcc=0.7296 | val_f1=0.7825 | val_auroc=0.9572

[Epoch 03] train_loss=0.2840 | val_loss=0.2315 | val_mcc=0.7277 | val_f1=0.7804 | val_auroc=0.9587

[Epoch 04] train_loss=0.2675 | val_loss=0.2207 | val_mcc=0.7376 | val_f1=0.7889 | val_auroc=0.9597

[Epoch 05] train_loss=0.2445 | val_loss=0.2100 | val_mcc=0.7342 | val_f1=0.7841 | val_auroc=0.9585

[Epoch 06] train_loss=0.2271 | val_loss=0.2465 | val_mcc=0.7302 | val_f1=0.7816 | val_auroc=0.9589

[Epoch 07] train_loss=0.2054 | val_loss=0.2702 | val_mcc=0.7175 | val_f1=0.7709 | val_auroc=0.9572

[Epoch 08] train_loss=0.1800 | val_loss=0.2688 | val_mcc=0.7239 | val_f1=0.7762 | val_auroc=0.9579

[Epoch 09] train_loss=0.1508 | val_loss=0.2677 | val_mcc=0.7277 | val_f1=0.7809 | val_auroc=0.9555

[Epoch 10] train_loss=0.1383 | val_loss=0.3008 | val_mcc=0.7118 | val_f1=0.7666 | val_auroc=0.9548
[EarlyStop] epoch=10 | best_val_mcc=0.7376
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7465 | F1=0.8176 | AUROC=0.9529 | AUPRC=0.8920
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8029 | F1=0.8955 | AUROC=0.9706 | AUPRC=0.9693
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4009 | F1=0.7134 | AUROC=0.7578 | AUPRC=0.7405
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5440 | F1=0.7702 | AUROC=0.8749 | AUPRC=0.8494
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4301 | val_loss=0.2959 | val_mcc=0.6841 | val_f1=0.7388 | val_auroc=0.9579

[Epoch 02] train_loss=0.3062 | val_loss=0.2148 | val_mcc=0.7399 | val_f1=0.7908 | val_auroc=0.9594

[Epoch 03] train_loss=0.2886 | val_loss=0.2156 | val_mcc=0.7430 | val_f1=0.7933 | val_auroc=0.9593

[Epoch 04] train_loss=0.2653 | val_loss=0.2167 | val_mcc=0.7423 | val_f1=0.7927 | val_auroc=0.9591

[Epoch 05] train_loss=0.2462 | val_loss=0.2253 | val_mcc=0.7402 | val_f1=0.7911 | val_auroc=0.9575

[Epoch 06] train_loss=0.2262 | val_loss=0.3073 | val_mcc=0.6989 | val_f1=0.7518 | val_auroc=0.9574

[Epoch 07] train_loss=0.2087 | val_loss=0.2470 | val_mcc=0.7304 | val_f1=0.7830 | val_auroc=0.9565

[Epoch 08] train_loss=0.1735 | val_loss=0.2794 | val_mcc=0.7117 | val_f1=0.7682 | val_auroc=0.9524

[Epoch 09] train_loss=0.1554 | val_loss=0.2959 | val_mcc=0.7069 | val_f1=0.7636 | val_auroc=0.9508
[EarlyStop] epoch=9 | best_val_mcc=0.7430
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7523 | F1=0.8214 | AUROC=0.9519 | AUPRC=0.8882
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7991 | F1=0.8909 | AUROC=0.9680 | AUPRC=0.9650
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4170 | F1=0.7198 | AUROC=0.7590 | AUPRC=0.7380
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5460 | F1=0.7710 | AUROC=0.8741 | AUPRC=0.8463
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4271 | val_loss=0.2100 | val_mcc=0.7264 | val_f1=0.7782 | val_auroc=0.9558

[Epoch 02] train_loss=0.3104 | val_loss=0.2070 | val_mcc=0.7429 | val_f1=0.7930 | val_auroc=0.9586

[Epoch 03] train_loss=0.2895 | val_loss=0.2047 | val_mcc=0.7335 | val_f1=0.7832 | val_auroc=0.9579

[Epoch 04] train_loss=0.2626 | val_loss=0.2187 | val_mcc=0.7409 | val_f1=0.7915 | val_auroc=0.9586

[Epoch 05] train_loss=0.2448 | val_loss=0.2048 | val_mcc=0.7394 | val_f1=0.7870 | val_auroc=0.9594

[Epoch 06] train_loss=0.2174 | val_loss=0.2291 | val_mcc=0.7382 | val_f1=0.7893 | val_auroc=0.9574

[Epoch 07] train_loss=0.1917 | val_loss=0.2394 | val_mcc=0.7307 | val_f1=0.7830 | val_auroc=0.9557

[Epoch 08] train_loss=0.1738 | val_loss=0.2420 | val_mcc=0.7227 | val_f1=0.7768 | val_auroc=0.9553
[EarlyStop] epoch=8 | best_val_mcc=0.7429
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7399 | F1=0.8114 | AUROC=0.9527 | AUPRC=0.8926
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7621 | F1=0.8673 | AUROC=0.9669 | AUPRC=0.9636
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4149 | F1=0.7081 | AUROC=0.7568 | AUPRC=0.7354
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5633 | F1=0.7784 | AUROC=0.8778 | AUPRC=0.8500
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4080 | val_loss=0.2213 | val_mcc=0.7219 | val_f1=0.7764 | val_auroc=0.9548

[Epoch 02] train_loss=0.3057 | val_loss=0.2162 | val_mcc=0.7320 | val_f1=0.7846 | val_auroc=0.9571

[Epoch 03] train_loss=0.2806 | val_loss=0.2513 | val_mcc=0.7169 | val_f1=0.7699 | val_auroc=0.9581

[Epoch 04] train_loss=0.2591 | val_loss=0.2129 | val_mcc=0.7392 | val_f1=0.7903 | val_auroc=0.9588

[Epoch 05] train_loss=0.2440 | val_loss=0.2201 | val_mcc=0.7357 | val_f1=0.7873 | val_auroc=0.9590

[Epoch 06] train_loss=0.2216 | val_loss=0.2276 | val_mcc=0.7306 | val_f1=0.7834 | val_auroc=0.9570

[Epoch 07] train_loss=0.1990 | val_loss=0.2270 | val_mcc=0.7301 | val_f1=0.7829 | val_auroc=0.9578

[Epoch 08] train_loss=0.1739 | val_loss=0.2544 | val_mcc=0.7196 | val_f1=0.7742 | val_auroc=0.9565

[Epoch 09] train_loss=0.1448 | val_loss=0.2734 | val_mcc=0.7151 | val_f1=0.7707 | val_auroc=0.9549

[Epoch 10] train_loss=0.1269 | val_loss=0.2883 | val_mcc=0.7071 | val_f1=0.7640 | val_auroc=0.9535
[EarlyStop] epoch=10 | best_val_mcc=0.7392
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7541 | F1=0.8226 | AUROC=0.9518 | AUPRC=0.8888
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7865 | F1=0.8859 | AUROC=0.9659 | AUPRC=0.9644
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3883 | F1=0.7060 | AUROC=0.7571 | AUPRC=0.7368
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5338 | F1=0.7655 | AUROC=0.8668 | AUPRC=0.8339
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 148.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7592 | F1=0.8267 | AUROC=0.9609 | AUPRC=0.9113
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8516 | F1=0.9208 | AUROC=0.9835 | AUPRC=0.9833
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4102 | F1=0.7237 | AUROC=0.7604 | AUPRC=0.7449
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5370 | F1=0.7668 | AUROC=0.8902 | AUPRC=0.8616
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 182.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7469 | F1=0.8180 | AUROC=0.9536 | AUPRC=0.8977
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8189 | F1=0.9056 | AUROC=0.9721 | AUPRC=0.9712
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4062 | F1=0.7226 | AUROC=0.7654 | AUPRC=0.7430
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5168 | F1=0.7583 | AUROC=0.8782 | AUPRC=0.8508
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 61.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7436 | F1=0.8156 | AUROC=0.9522 | AUPRC=0.8920
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7929 | F1=0.8928 | AUROC=0.9675 | AUPRC=0.9672
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4143 | F1=0.7227 | AUROC=0.7611 | AUPRC=0.7349
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5468 | F1=0.7713 | AUROC=0.8783 | AUPRC=0.8509
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 96.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7341 | F1=0.8089 | AUROC=0.9498 | AUPRC=0.8874
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7933 | F1=0.8922 | AUROC=0.9670 | AUPRC=0.9652
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.6258 | val_loss=0.5557 | val_mcc=0.3806 | val_f1=0.5122 | val_auroc=0.7707

[Epoch 02] train_loss=0.5560 | val_loss=0.4756 | val_mcc=0.4398 | val_f1=0.5501 | val_auroc=0.7909

[Epoch 03] train_loss=0.5270 | val_loss=0.4780 | val_mcc=0.4481 | val_f1=0.5594 | val_auroc=0.8010

[Epoch 04] train_loss=0.5009 | val_loss=0.5364 | val_mcc=0.4367 | val_f1=0.5542 | val_auroc=0.8113

[Epoch 05] train_loss=0.4754 | val_loss=0.5100 | val_mcc=0.4588 | val_f1=0.5708 | val_auroc=0.8223

[Epoch 06] train_loss=0.4490 | val_loss=0.4663 | val_mcc=0.4953 | val_f1=0.5987 | val_auroc=0.8341

[Epoch 07] train_loss=0.4191 | val_loss=0.5197 | val_mcc=0.4686 | val_f1=0.5776 | val_auroc=0.8377

[Epoch 08] train_loss=0.3891 | val_loss=0.5128 | val_mcc=0.4737 | val_f1=0.5815 | val_auroc=0.8377

[Epoch 09] train_loss=0.3566 | val_loss=0.4998 | val_mcc=0.4851 | val_f1=0.5906 | val_auroc=0.8465

[Epoch 10] train_loss=0.3198 | val_loss=0.5837 | val_mcc=0.4470 | val_f1=0.5582 | val_auroc=0.8408

[Epoch 11] train_loss=0.2742 | val_loss=0.5443 | val_mcc=0.4693 | val_f1=0.5784 | val_auroc=0.8416

[Epoch 12] train_loss=0.2474 | val_loss=0.6248 | val_mcc=0.4398 | val_f1=0.5536 | val_auroc=0.8384
[EarlyStop] epoch=12 | best_val_mcc=0.4953
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.4961 | F1=0.6371 | AUROC=0.8230 | AUPRC=0.7043
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.4666 | F1=0.7169 | AUROC=0.8055 | AUPRC=0.8084
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3333 | F1=0.6504 | AUROC=0.7192 | AUPRC=0.6929
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4541 | F1=0.6891 | AUROC=0.7788 | AUPRC=0.7749
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.6404 | val_loss=0.6456 | val_mcc=0.3415 | val_f1=0.4801 | val_auroc=0.7758

[Epoch 02] train_loss=0.5608 | val_loss=0.4797 | val_mcc=0.4421 | val_f1=0.5519 | val_auroc=0.7930

[Epoch 03] train_loss=0.5259 | val_loss=0.4730 | val_mcc=0.4588 | val_f1=0.5669 | val_auroc=0.8057

[Epoch 04] train_loss=0.5022 | val_loss=0.4645 | val_mcc=0.4699 | val_f1=0.5775 | val_auroc=0.8169

[Epoch 05] train_loss=0.4757 | val_loss=0.4772 | val_mcc=0.4725 | val_f1=0.5808 | val_auroc=0.8223

[Epoch 06] train_loss=0.4572 | val_loss=0.4694 | val_mcc=0.4897 | val_f1=0.5932 | val_auroc=0.8265

[Epoch 07] train_loss=0.4242 | val_loss=0.5405 | val_mcc=0.4557 | val_f1=0.5681 | val_auroc=0.8252

[Epoch 08] train_loss=0.3984 | val_loss=0.5127 | val_mcc=0.4681 | val_f1=0.5780 | val_auroc=0.8275

[Epoch 09] train_loss=0.3639 | val_loss=0.4914 | val_mcc=0.4860 | val_f1=0.5911 | val_auroc=0.8279

[Epoch 10] train_loss=0.3280 | val_loss=0.6538 | val_mcc=0.4369 | val_f1=0.5511 | val_auroc=0.8219

[Epoch 11] train_loss=0.2732 | val_loss=0.6207 | val_mcc=0.4560 | val_f1=0.5688 | val_auroc=0.8165

[Epoch 12] train_loss=0.2368 | val_loss=0.7173 | val_mcc=0.4426 | val_f1=0.5585 | val_auroc=0.8119
[EarlyStop] epoch=12 | best_val_mcc=0.4897
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5060 | F1=0.6408 | AUROC=0.8203 | AUPRC=0.6969
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.4745 | F1=0.7130 | AUROC=0.7898 | AUPRC=0.7956
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3413 | F1=0.6513 | AUROC=0.7186 | AUPRC=0.6915
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.4485 | F1=0.6815 | AUROC=0.7741 | AUPRC=0.7643
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.6351 | val_loss=0.6745 | val_mcc=0.3238 | val_f1=0.4660 | val_auroc=0.7792

[Epoch 02] train_loss=0.5519 | val_loss=0.4610 | val_mcc=0.4427 | val_f1=0.5519 | val_auroc=0.8017

[Epoch 03] train_loss=0.5223 | val_loss=0.4399 | val_mcc=0.4578 | val_f1=0.5634 | val_auroc=0.8145

[Epoch 04] train_loss=0.4986 | val_loss=0.4851 | val_mcc=0.4666 | val_f1=0.5767 | val_auroc=0.8262

[Epoch 05] train_loss=0.4780 | val_loss=0.4485 | val_mcc=0.4874 | val_f1=0.5918 | val_auroc=0.8335

[Epoch 06] train_loss=0.4528 | val_loss=0.4127 | val_mcc=0.5009 | val_f1=0.5991 | val_auroc=0.8377

[Epoch 07] train_loss=0.4178 | val_loss=0.4567 | val_mcc=0.4900 | val_f1=0.5945 | val_auroc=0.8407

[Epoch 08] train_loss=0.3884 | val_loss=0.4838 | val_mcc=0.4837 | val_f1=0.5900 | val_auroc=0.8365

[Epoch 09] train_loss=0.3583 | val_loss=0.5004 | val_mcc=0.4803 | val_f1=0.5873 | val_auroc=0.8395

[Epoch 10] train_loss=0.3178 | val_loss=0.4916 | val_mcc=0.4887 | val_f1=0.5927 | val_auroc=0.8306

[Epoch 11] train_loss=0.2644 | val_loss=0.6003 | val_mcc=0.4669 | val_f1=0.5770 | val_auroc=0.8277

[Epoch 12] train_loss=0.2248 | val_loss=0.6295 | val_mcc=0.4644 | val_f1=0.5752 | val_auroc=0.8214
[EarlyStop] epoch=12 | best_val_mcc=0.5009
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5180 | F1=0.6430 | AUROC=0.8304 | AUPRC=0.7100
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5100 | F1=0.7227 | AUROC=0.8113 | AUPRC=0.8122
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3234 | F1=0.6320 | AUROC=0.7204 | AUPRC=0.6976
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.4780 | F1=0.6864 | AUROC=0.7827 | AUPRC=0.7696
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.6222 | val_loss=0.4649 | val_mcc=0.4008 | val_f1=0.5113 | val_auroc=0.7759

[Epoch 02] train_loss=0.5474 | val_loss=0.4517 | val_mcc=0.4368 | val_f1=0.5452 | val_auroc=0.7973

[Epoch 03] train_loss=0.5177 | val_loss=0.5275 | val_mcc=0.4426 | val_f1=0.5587 | val_auroc=0.8095

[Epoch 04] train_loss=0.4918 | val_loss=0.4435 | val_mcc=0.4728 | val_f1=0.5785 | val_auroc=0.8210

[Epoch 05] train_loss=0.4644 | val_loss=0.4739 | val_mcc=0.4755 | val_f1=0.5833 | val_auroc=0.8318

[Epoch 06] train_loss=0.4345 | val_loss=0.4246 | val_mcc=0.5049 | val_f1=0.6050 | val_auroc=0.8414

[Epoch 07] train_loss=0.3974 | val_loss=0.4495 | val_mcc=0.4943 | val_f1=0.5979 | val_auroc=0.8418

[Epoch 08] train_loss=0.3613 | val_loss=0.4935 | val_mcc=0.4709 | val_f1=0.5801 | val_auroc=0.8410

[Epoch 09] train_loss=0.3236 | val_loss=0.5105 | val_mcc=0.4731 | val_f1=0.5815 | val_auroc=0.8439

[Epoch 10] train_loss=0.2799 | val_loss=0.5250 | val_mcc=0.4681 | val_f1=0.5780 | val_auroc=0.8379

[Epoch 11] train_loss=0.2173 | val_loss=0.6225 | val_mcc=0.4500 | val_f1=0.5631 | val_auroc=0.8326

[Epoch 12] train_loss=0.1823 | val_loss=0.6089 | val_mcc=0.4607 | val_f1=0.5724 | val_auroc=0.8300
[EarlyStop] epoch=12 | best_val_mcc=0.5049
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5153 | F1=0.6448 | AUROC=0.8311 | AUPRC=0.7119
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.4668 | F1=0.7061 | AUROC=0.8060 | AUPRC=0.8090
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3360 | F1=0.6442 | AUROC=0.7200 | AUPRC=0.6969
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.4574 | F1=0.6796 | AUROC=0.7855 | AUPRC=0.7713
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 282.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.4894 | F1=0.6379 | AUROC=0.8381 | AUPRC=0.7023
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.4992 | F1=0.7457 | AUROC=0.8284 | AUPRC=0.8170
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3415 | F1=0.6741 | AUROC=0.7366 | AUPRC=0.7090
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4141 | F1=0.6853 | AUROC=0.7880 | AUPRC=0.7672
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 135.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.4708 | F1=0.6230 | AUROC=0.8238 | AUPRC=0.6942
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4452 | F1=0.7153 | AUROC=0.8019 | AUPRC=0.8061
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3310 | F1=0.6564 | AUROC=0.7239 | AUPRC=0.6982
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.3946 | F1=0.6651 | AUROC=0.7750 | AUPRC=0.7475
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 77.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.4566 | F1=0.6104 | AUROC=0.8116 | AUPRC=0.6799
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4459 | F1=0.7094 | AUROC=0.7904 | AUPRC=0.7867
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3241 | F1=0.6463 | AUROC=0.7132 | AUPRC=0.6862
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.3918 | F1=0.6547 | AUROC=0.7597 | AUPRC=0.7430
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 66.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.4715 | F1=0.6216 | AUROC=0.8182 | AUPRC=0.6854
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4287 | F1=0.7013 | AUROC=0.7905 | AUPRC=0.7877
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3284 | F1=0.6505 | AUROC=0.7259 | AUPRC=0.6954
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4294 | val_loss=0.2391 | val_mcc=0.7192 | val_f1=0.7740 | val_auroc=0.9537

[Epoch 02] train_loss=0.3247 | val_loss=0.2201 | val_mcc=0.7291 | val_f1=0.7822 | val_auroc=0.9559

[Epoch 03] train_loss=0.3024 | val_loss=0.2115 | val_mcc=0.7333 | val_f1=0.7849 | val_auroc=0.9565

[Epoch 04] train_loss=0.2923 | val_loss=0.2200 | val_mcc=0.7320 | val_f1=0.7846 | val_auroc=0.9568

[Epoch 05] train_loss=0.2765 | val_loss=0.2243 | val_mcc=0.7269 | val_f1=0.7805 | val_auroc=0.9562

[Epoch 06] train_loss=0.2682 | val_loss=0.2241 | val_mcc=0.7308 | val_f1=0.7836 | val_auroc=0.9565

[Epoch 07] train_loss=0.2530 | val_loss=0.2596 | val_mcc=0.7056 | val_f1=0.7614 | val_auroc=0.9566

[Epoch 08] train_loss=0.2349 | val_loss=0.2473 | val_mcc=0.7161 | val_f1=0.7710 | val_auroc=0.9558

[Epoch 09] train_loss=0.2237 | val_loss=0.2358 | val_mcc=0.7310 | val_f1=0.7838 | val_auroc=0.9540
[EarlyStop] epoch=9 | best_val_mcc=0.7333
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7389 | F1=0.8108 | AUROC=0.9436 | AUPRC=0.8761
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8147 | F1=0.8977 | AUROC=0.9649 | AUPRC=0.9639
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3685 | F1=0.6865 | AUROC=0.7406 | AUPRC=0.7134
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5258 | F1=0.7614 | AUROC=0.8413 | AUPRC=0.7975
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4652 | val_loss=0.2677 | val_mcc=0.6946 | val_f1=0.7530 | val_auroc=0.9528

[Epoch 02] train_loss=0.3357 | val_loss=0.2418 | val_mcc=0.7139 | val_f1=0.7693 | val_auroc=0.9558

[Epoch 03] train_loss=0.3161 | val_loss=0.2548 | val_mcc=0.7114 | val_f1=0.7662 | val_auroc=0.9563

[Epoch 04] train_loss=0.3004 | val_loss=0.2134 | val_mcc=0.7362 | val_f1=0.7876 | val_auroc=0.9575

[Epoch 05] train_loss=0.2906 | val_loss=0.2354 | val_mcc=0.7270 | val_f1=0.7801 | val_auroc=0.9574

[Epoch 06] train_loss=0.2746 | val_loss=0.2732 | val_mcc=0.6945 | val_f1=0.7515 | val_auroc=0.9548

[Epoch 07] train_loss=0.2650 | val_loss=0.2574 | val_mcc=0.7155 | val_f1=0.7702 | val_auroc=0.9550

[Epoch 08] train_loss=0.2484 | val_loss=0.2283 | val_mcc=0.7302 | val_f1=0.7831 | val_auroc=0.9551

[Epoch 09] train_loss=0.2284 | val_loss=0.2953 | val_mcc=0.6866 | val_f1=0.7448 | val_auroc=0.9515

[Epoch 10] train_loss=0.2173 | val_loss=0.2683 | val_mcc=0.6996 | val_f1=0.7581 | val_auroc=0.9492
[EarlyStop] epoch=10 | best_val_mcc=0.7362
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7370 | F1=0.8099 | AUROC=0.9428 | AUPRC=0.8773
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8173 | F1=0.8994 | AUROC=0.9686 | AUPRC=0.9689
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3850 | F1=0.6954 | AUROC=0.7379 | AUPRC=0.7079
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5271 | F1=0.7625 | AUROC=0.8507 | AUPRC=0.8089
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4568 | val_loss=0.2179 | val_mcc=0.7289 | val_f1=0.7813 | val_auroc=0.9540

[Epoch 02] train_loss=0.3352 | val_loss=0.2478 | val_mcc=0.7113 | val_f1=0.7662 | val_auroc=0.9568

[Epoch 03] train_loss=0.3161 | val_loss=0.2313 | val_mcc=0.7241 | val_f1=0.7776 | val_auroc=0.9576

[Epoch 04] train_loss=0.2985 | val_loss=0.2092 | val_mcc=0.7387 | val_f1=0.7889 | val_auroc=0.9569

[Epoch 05] train_loss=0.2859 | val_loss=0.2140 | val_mcc=0.7407 | val_f1=0.7914 | val_auroc=0.9586

[Epoch 06] train_loss=0.2726 | val_loss=0.2292 | val_mcc=0.7269 | val_f1=0.7804 | val_auroc=0.9559

[Epoch 07] train_loss=0.2566 | val_loss=0.2375 | val_mcc=0.7271 | val_f1=0.7806 | val_auroc=0.9548

[Epoch 08] train_loss=0.2451 | val_loss=0.2393 | val_mcc=0.7295 | val_f1=0.7819 | val_auroc=0.9566

[Epoch 09] train_loss=0.2232 | val_loss=0.2309 | val_mcc=0.7350 | val_f1=0.7870 | val_auroc=0.9546

[Epoch 10] train_loss=0.2015 | val_loss=0.2573 | val_mcc=0.7175 | val_f1=0.7730 | val_auroc=0.9502

[Epoch 11] train_loss=0.1898 | val_loss=0.2718 | val_mcc=0.7085 | val_f1=0.7656 | val_auroc=0.9488
[EarlyStop] epoch=11 | best_val_mcc=0.7407
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7301 | F1=0.8053 | AUROC=0.9438 | AUPRC=0.8808
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8252 | F1=0.9044 | AUROC=0.9671 | AUPRC=0.9665
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3723 | F1=0.6944 | AUROC=0.7443 | AUPRC=0.7115
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5197 | F1=0.7591 | AUROC=0.8499 | AUPRC=0.8123
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4350 | val_loss=0.2259 | val_mcc=0.7240 | val_f1=0.7781 | val_auroc=0.9536

[Epoch 02] train_loss=0.3272 | val_loss=0.2328 | val_mcc=0.7243 | val_f1=0.7780 | val_auroc=0.9560

[Epoch 03] train_loss=0.3077 | val_loss=0.2347 | val_mcc=0.7188 | val_f1=0.7733 | val_auroc=0.9562

[Epoch 04] train_loss=0.2924 | val_loss=0.2566 | val_mcc=0.7039 | val_f1=0.7593 | val_auroc=0.9562

[Epoch 05] train_loss=0.2788 | val_loss=0.2187 | val_mcc=0.7262 | val_f1=0.7799 | val_auroc=0.9557

[Epoch 06] train_loss=0.2647 | val_loss=0.2202 | val_mcc=0.7357 | val_f1=0.7873 | val_auroc=0.9559

[Epoch 07] train_loss=0.2510 | val_loss=0.2419 | val_mcc=0.7202 | val_f1=0.7748 | val_auroc=0.9550

[Epoch 08] train_loss=0.2350 | val_loss=0.2477 | val_mcc=0.7150 | val_f1=0.7706 | val_auroc=0.9537

[Epoch 09] train_loss=0.2182 | val_loss=0.2444 | val_mcc=0.7162 | val_f1=0.7714 | val_auroc=0.9542

[Epoch 10] train_loss=0.1943 | val_loss=0.2470 | val_mcc=0.7272 | val_f1=0.7807 | val_auroc=0.9519

[Epoch 11] train_loss=0.1627 | val_loss=0.3280 | val_mcc=0.6782 | val_f1=0.7387 | val_auroc=0.9491

[Epoch 12] train_loss=0.1465 | val_loss=0.3153 | val_mcc=0.6896 | val_f1=0.7485 | val_auroc=0.9485
[EarlyStop] epoch=12 | best_val_mcc=0.7357
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7272 | F1=0.8028 | AUROC=0.9403 | AUPRC=0.8723
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7955 | F1=0.8865 | AUROC=0.9647 | AUPRC=0.9635
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3672 | F1=0.6879 | AUROC=0.7402 | AUPRC=0.7111
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5264 | F1=0.7618 | AUROC=0.8453 | AUPRC=0.8085
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 181.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7483 | F1=0.8189 | AUROC=0.9560 | AUPRC=0.9021
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8472 | F1=0.9206 | AUROC=0.9810 | AUPRC=0.9814
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4060 | F1=0.7200 | AUROC=0.7637 | AUPRC=0.7353
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5315 | F1=0.7647 | AUROC=0.8772 | AUPRC=0.8431
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 158.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7303 | F1=0.8063 | AUROC=0.9453 | AUPRC=0.8848
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8265 | F1=0.9117 | AUROC=0.9712 | AUPRC=0.9728
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3999 | F1=0.7172 | AUROC=0.7513 | AUPRC=0.7286
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5086 | F1=0.7548 | AUROC=0.8592 | AUPRC=0.8222
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 135.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7206 | F1=0.7994 | AUROC=0.9439 | AUPRC=0.8803
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8216 | F1=0.9072 | AUROC=0.9685 | AUPRC=0.9679
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3741 | F1=0.7018 | AUROC=0.7480 | AUPRC=0.7143
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5124 | F1=0.7562 | AUROC=0.8594 | AUPRC=0.8259
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 142.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7272 | F1=0.8040 | AUROC=0.9458 | AUPRC=0.8851
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8392 | F1=0.9156 | AUROC=0.9725 | AUPRC=0.9728
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.6304 | val_loss=0.4404 | val_mcc=0.4795 | val_f1=0.5527 | val_auroc=0.7960

[Epoch 02] train_loss=0.5342 | val_loss=0.4872 | val_mcc=0.4956 | val_f1=0.5933 | val_auroc=0.8083

[Epoch 03] train_loss=0.5114 | val_loss=0.4605 | val_mcc=0.5102 | val_f1=0.6019 | val_auroc=0.8106

[Epoch 04] train_loss=0.4980 | val_loss=0.3976 | val_mcc=0.5319 | val_f1=0.6071 | val_auroc=0.8134

[Epoch 05] train_loss=0.4831 | val_loss=0.3886 | val_mcc=0.5333 | val_f1=0.6027 | val_auroc=0.8145

[Epoch 06] train_loss=0.4695 | val_loss=0.4163 | val_mcc=0.5205 | val_f1=0.6129 | val_auroc=0.8207

[Epoch 07] train_loss=0.4589 | val_loss=0.4016 | val_mcc=0.5245 | val_f1=0.6131 | val_auroc=0.8229

[Epoch 08] train_loss=0.4541 | val_loss=0.5328 | val_mcc=0.4536 | val_f1=0.5662 | val_auroc=0.8262

[Epoch 09] train_loss=0.4354 | val_loss=0.4174 | val_mcc=0.5207 | val_f1=0.6141 | val_auroc=0.8258

[Epoch 10] train_loss=0.4184 | val_loss=0.4655 | val_mcc=0.4885 | val_f1=0.5936 | val_auroc=0.8331

[Epoch 11] train_loss=0.4058 | val_loss=0.5106 | val_mcc=0.4664 | val_f1=0.5762 | val_auroc=0.8288
[EarlyStop] epoch=11 | best_val_mcc=0.5333
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5538 | F1=0.6459 | AUROC=0.8105 | AUPRC=0.7219
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.4853 | F1=0.6620 | AUROC=0.7687 | AUPRC=0.8025
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3618 | F1=0.6020 | AUROC=0.7107 | AUPRC=0.7208
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4976 | F1=0.6690 | AUROC=0.7746 | AUPRC=0.7870
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.6449 | val_loss=0.4803 | val_mcc=0.4786 | val_f1=0.5750 | val_auroc=0.8011

[Epoch 02] train_loss=0.5371 | val_loss=0.4045 | val_mcc=0.5224 | val_f1=0.5882 | val_auroc=0.8119

[Epoch 03] train_loss=0.5147 | val_loss=0.4487 | val_mcc=0.5179 | val_f1=0.6078 | val_auroc=0.8153

[Epoch 04] train_loss=0.4950 | val_loss=0.4106 | val_mcc=0.5264 | val_f1=0.6140 | val_auroc=0.8232

[Epoch 05] train_loss=0.4789 | val_loss=0.4197 | val_mcc=0.5247 | val_f1=0.6164 | val_auroc=0.8347

[Epoch 06] train_loss=0.4678 | val_loss=0.4191 | val_mcc=0.5195 | val_f1=0.6141 | val_auroc=0.8329

[Epoch 07] train_loss=0.4526 | val_loss=0.4812 | val_mcc=0.4949 | val_f1=0.5985 | val_auroc=0.8342

[Epoch 08] train_loss=0.4413 | val_loss=0.4560 | val_mcc=0.4955 | val_f1=0.5989 | val_auroc=0.8318

[Epoch 09] train_loss=0.4150 | val_loss=0.4290 | val_mcc=0.5027 | val_f1=0.6033 | val_auroc=0.8302

[Epoch 10] train_loss=0.3967 | val_loss=0.4494 | val_mcc=0.4922 | val_f1=0.5958 | val_auroc=0.8268
[EarlyStop] epoch=10 | best_val_mcc=0.5264
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5566 | F1=0.6651 | AUROC=0.8179 | AUPRC=0.7261
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.4843 | F1=0.6951 | AUROC=0.7817 | AUPRC=0.8137
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3503 | F1=0.6213 | AUROC=0.7116 | AUPRC=0.7155
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5045 | F1=0.6978 | AUROC=0.7818 | AUPRC=0.7908
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.6473 | val_loss=0.4589 | val_mcc=0.4816 | val_f1=0.5662 | val_auroc=0.7989

[Epoch 02] train_loss=0.5382 | val_loss=0.3897 | val_mcc=0.5108 | val_f1=0.5673 | val_auroc=0.8103

[Epoch 03] train_loss=0.5128 | val_loss=0.4250 | val_mcc=0.5249 | val_f1=0.6048 | val_auroc=0.8140

[Epoch 04] train_loss=0.4987 | val_loss=0.4550 | val_mcc=0.5196 | val_f1=0.6101 | val_auroc=0.8183

[Epoch 05] train_loss=0.4829 | val_loss=0.3750 | val_mcc=0.5394 | val_f1=0.6182 | val_auroc=0.8310

[Epoch 06] train_loss=0.4711 | val_loss=0.3997 | val_mcc=0.5320 | val_f1=0.6212 | val_auroc=0.8353

[Epoch 07] train_loss=0.4560 | val_loss=0.4217 | val_mcc=0.5228 | val_f1=0.6170 | val_auroc=0.8327

[Epoch 08] train_loss=0.4444 | val_loss=0.3587 | val_mcc=0.5434 | val_f1=0.6217 | val_auroc=0.8354

[Epoch 09] train_loss=0.4232 | val_loss=0.3947 | val_mcc=0.5267 | val_f1=0.6183 | val_auroc=0.8327

[Epoch 10] train_loss=0.3919 | val_loss=0.4820 | val_mcc=0.4835 | val_f1=0.5897 | val_auroc=0.8315

[Epoch 11] train_loss=0.3370 | val_loss=0.4534 | val_mcc=0.5003 | val_f1=0.6015 | val_auroc=0.8263

[Epoch 12] train_loss=0.2739 | val_loss=0.5837 | val_mcc=0.4281 | val_f1=0.5478 | val_auroc=0.8024

[Epoch 13] train_loss=0.1870 | val_loss=0.6977 | val_mcc=0.4368 | val_f1=0.5542 | val_auroc=0.7998

[Epoch 14] train_loss=0.1405 | val_loss=0.7947 | val_mcc=0.4168 | val_f1=0.5392 | val_auroc=0.7911
[EarlyStop] epoch=14 | best_val_mcc=0.5434
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5600 | F1=0.6601 | AUROC=0.8229 | AUPRC=0.7323
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5046 | F1=0.6861 | AUROC=0.7823 | AUPRC=0.8155
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3489 | F1=0.6071 | AUROC=0.7060 | AUPRC=0.7226
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.4963 | F1=0.6788 | AUROC=0.7856 | AUPRC=0.7898
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.6317 | val_loss=0.5004 | val_mcc=0.4650 | val_f1=0.5692 | val_auroc=0.7961

[Epoch 02] train_loss=0.5289 | val_loss=0.4629 | val_mcc=0.5112 | val_f1=0.5982 | val_auroc=0.8079

[Epoch 03] train_loss=0.5063 | val_loss=0.3884 | val_mcc=0.5261 | val_f1=0.5939 | val_auroc=0.8127

[Epoch 04] train_loss=0.4945 | val_loss=0.4512 | val_mcc=0.5161 | val_f1=0.6098 | val_auroc=0.8169

[Epoch 05] train_loss=0.4800 | val_loss=0.4828 | val_mcc=0.4931 | val_f1=0.5967 | val_auroc=0.8216

[Epoch 06] train_loss=0.4659 | val_loss=0.4853 | val_mcc=0.4849 | val_f1=0.5908 | val_auroc=0.8256

[Epoch 07] train_loss=0.4504 | val_loss=0.3867 | val_mcc=0.5345 | val_f1=0.6187 | val_auroc=0.8212

[Epoch 08] train_loss=0.4383 | val_loss=0.4588 | val_mcc=0.4987 | val_f1=0.6009 | val_auroc=0.8259

[Epoch 09] train_loss=0.4178 | val_loss=0.4789 | val_mcc=0.4806 | val_f1=0.5876 | val_auroc=0.8267

[Epoch 10] train_loss=0.3963 | val_loss=0.4076 | val_mcc=0.5103 | val_f1=0.6070 | val_auroc=0.8206

[Epoch 11] train_loss=0.3520 | val_loss=0.4543 | val_mcc=0.4861 | val_f1=0.5903 | val_auroc=0.8138

[Epoch 12] train_loss=0.2921 | val_loss=0.5671 | val_mcc=0.4306 | val_f1=0.5494 | val_auroc=0.8067

[Epoch 13] train_loss=0.2538 | val_loss=0.5595 | val_mcc=0.4342 | val_f1=0.5524 | val_auroc=0.7995
[EarlyStop] epoch=13 | best_val_mcc=0.5345
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5519 | F1=0.6594 | AUROC=0.8116 | AUPRC=0.7272
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.4862 | F1=0.6868 | AUROC=0.7679 | AUPRC=0.8059
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3491 | F1=0.6195 | AUROC=0.7070 | AUPRC=0.7221
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.4809 | F1=0.6768 | AUROC=0.7727 | AUPRC=0.7860
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 400.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5565 | F1=0.6832 | AUROC=0.8684 | AUPRC=0.7748
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5371 | F1=0.7578 | AUROC=0.8572 | AUPRC=0.8676
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3504 | F1=0.6702 | AUROC=0.7423 | AUPRC=0.7521
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5117 | F1=0.7315 | AUROC=0.8292 | AUPRC=0.8242
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 62.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5372 | F1=0.6684 | AUROC=0.8448 | AUPRC=0.7570
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4959 | F1=0.7295 | AUROC=0.8126 | AUPRC=0.8316
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3462 | F1=0.6625 | AUROC=0.7233 | AUPRC=0.7317
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4616 | F1=0.7003 | AUROC=0.7914 | AUPRC=0.7985
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 64.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5278 | F1=0.6619 | AUROC=0.8402 | AUPRC=0.7477
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5053 | F1=0.7320 | AUROC=0.8150 | AUPRC=0.8299
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3563 | F1=0.6593 | AUROC=0.7262 | AUPRC=0.7339
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4711 | F1=0.7050 | AUROC=0.7938 | AUPRC=0.7928
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 43.
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5394 | F1=0.6686 | AUROC=0.8342 | AUPRC=0.7443
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5222 | F1=0.7420 | AUROC=0.8134 | AUPRC=0.8260
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3413 | F1=0.6513 | AUROC=0.7145 | AUPRC=0.7209
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4396 | val_loss=0.2233 | val_mcc=0.7190 | val_f1=0.7742 | val_auroc=0.9538

[Epoch 02] train_loss=0.3213 | val_loss=0.2160 | val_mcc=0.7358 | val_f1=0.7875 | val_auroc=0.9561

[Epoch 03] train_loss=0.3027 | val_loss=0.2171 | val_mcc=0.7348 | val_f1=0.7867 | val_auroc=0.9569

[Epoch 04] train_loss=0.2962 | val_loss=0.2257 | val_mcc=0.7276 | val_f1=0.7809 | val_auroc=0.9580

[Epoch 05] train_loss=0.2833 | val_loss=0.2353 | val_mcc=0.7178 | val_f1=0.7726 | val_auroc=0.9568

[Epoch 06] train_loss=0.2754 | val_loss=0.2212 | val_mcc=0.7279 | val_f1=0.7812 | val_auroc=0.9573

[Epoch 07] train_loss=0.2666 | val_loss=0.2238 | val_mcc=0.7261 | val_f1=0.7798 | val_auroc=0.9572

[Epoch 08] train_loss=0.2603 | val_loss=0.2147 | val_mcc=0.7323 | val_f1=0.7847 | val_auroc=0.9568
[EarlyStop] epoch=8 | best_val_mcc=0.7358
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7339 | F1=0.8082 | AUROC=0.9458 | AUPRC=0.8841
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7846 | F1=0.8835 | AUROC=0.9646 | AUPRC=0.9572
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3826 | F1=0.6984 | AUROC=0.7474 | AUPRC=0.7283
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5309 | F1=0.7644 | AUROC=0.8601 | AUPRC=0.8398
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4587 | val_loss=0.2301 | val_mcc=0.7126 | val_f1=0.7690 | val_auroc=0.9537

[Epoch 02] train_loss=0.3274 | val_loss=0.2041 | val_mcc=0.7372 | val_f1=0.7859 | val_auroc=0.9568

[Epoch 03] train_loss=0.3067 | val_loss=0.2429 | val_mcc=0.7154 | val_f1=0.7699 | val_auroc=0.9571

[Epoch 04] train_loss=0.2996 | val_loss=0.2107 | val_mcc=0.7345 | val_f1=0.7865 | val_auroc=0.9580

[Epoch 05] train_loss=0.2875 | val_loss=0.2595 | val_mcc=0.7023 | val_f1=0.7581 | val_auroc=0.9574

[Epoch 06] train_loss=0.2819 | val_loss=0.2365 | val_mcc=0.7205 | val_f1=0.7745 | val_auroc=0.9586

[Epoch 07] train_loss=0.2688 | val_loss=0.2166 | val_mcc=0.7317 | val_f1=0.7843 | val_auroc=0.9576

[Epoch 08] train_loss=0.2627 | val_loss=0.2516 | val_mcc=0.7040 | val_f1=0.7603 | val_auroc=0.9569
[EarlyStop] epoch=8 | best_val_mcc=0.7372
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7422 | F1=0.8100 | AUROC=0.9480 | AUPRC=0.8881
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7446 | F1=0.8480 | AUROC=0.9679 | AUPRC=0.9614
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3780 | F1=0.6770 | AUROC=0.7485 | AUPRC=0.7302
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5523 | F1=0.7731 | AUROC=0.8637 | AUPRC=0.8443
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4790 | val_loss=0.2329 | val_mcc=0.7057 | val_f1=0.7636 | val_auroc=0.9516

[Epoch 02] train_loss=0.3333 | val_loss=0.2237 | val_mcc=0.7254 | val_f1=0.7793 | val_auroc=0.9564

[Epoch 03] train_loss=0.3181 | val_loss=0.2234 | val_mcc=0.7284 | val_f1=0.7815 | val_auroc=0.9572

[Epoch 04] train_loss=0.2994 | val_loss=0.2076 | val_mcc=0.7364 | val_f1=0.7876 | val_auroc=0.9576

[Epoch 05] train_loss=0.2894 | val_loss=0.2213 | val_mcc=0.7261 | val_f1=0.7797 | val_auroc=0.9578

[Epoch 06] train_loss=0.2833 | val_loss=0.2225 | val_mcc=0.7249 | val_f1=0.7787 | val_auroc=0.9579

[Epoch 07] train_loss=0.2762 | val_loss=0.2222 | val_mcc=0.7242 | val_f1=0.7782 | val_auroc=0.9574

[Epoch 08] train_loss=0.2650 | val_loss=0.2199 | val_mcc=0.7284 | val_f1=0.7817 | val_auroc=0.9568

[Epoch 09] train_loss=0.2557 | val_loss=0.2670 | val_mcc=0.6926 | val_f1=0.7499 | val_auroc=0.9551

[Epoch 10] train_loss=0.2469 | val_loss=0.2411 | val_mcc=0.7146 | val_f1=0.7704 | val_auroc=0.9539
[EarlyStop] epoch=10 | best_val_mcc=0.7364
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7388 | F1=0.8110 | AUROC=0.9461 | AUPRC=0.8836
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7762 | F1=0.8752 | AUROC=0.9650 | AUPRC=0.9565
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4120 | F1=0.7075 | AUROC=0.7562 | AUPRC=0.7392
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5476 | F1=0.7717 | AUROC=0.8652 | AUPRC=0.8451
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4222 | val_loss=0.2546 | val_mcc=0.6969 | val_f1=0.7542 | val_auroc=0.9548

[Epoch 02] train_loss=0.3173 | val_loss=0.2385 | val_mcc=0.7135 | val_f1=0.7684 | val_auroc=0.9565

[Epoch 03] train_loss=0.3030 | val_loss=0.2298 | val_mcc=0.7241 | val_f1=0.7776 | val_auroc=0.9577

[Epoch 04] train_loss=0.2886 | val_loss=0.2147 | val_mcc=0.7349 | val_f1=0.7869 | val_auroc=0.9583

[Epoch 05] train_loss=0.2835 | val_loss=0.2626 | val_mcc=0.7014 | val_f1=0.7559 | val_auroc=0.9576

[Epoch 06] train_loss=0.2748 | val_loss=0.2083 | val_mcc=0.7364 | val_f1=0.7876 | val_auroc=0.9570

[Epoch 07] train_loss=0.2648 | val_loss=0.2260 | val_mcc=0.7258 | val_f1=0.7795 | val_auroc=0.9567

[Epoch 08] train_loss=0.2587 | val_loss=0.2377 | val_mcc=0.7156 | val_f1=0.7705 | val_auroc=0.9565

[Epoch 09] train_loss=0.2466 | val_loss=0.2155 | val_mcc=0.7345 | val_f1=0.7860 | val_auroc=0.9545

[Epoch 10] train_loss=0.2308 | val_loss=0.2384 | val_mcc=0.7195 | val_f1=0.7745 | val_auroc=0.9534

[Epoch 11] train_loss=0.2086 | val_loss=0.2784 | val_mcc=0.6919 | val_f1=0.7512 | val_auroc=0.9509

[Epoch 12] train_loss=0.1938 | val_loss=0.2899 | val_mcc=0.6895 | val_f1=0.7490 | val_auroc=0.9506
[EarlyStop] epoch=12 | best_val_mcc=0.7364
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7397 | F1=0.8111 | AUROC=0.9459 | AUPRC=0.8846
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7634 | F1=0.8665 | AUROC=0.9668 | AUPRC=0.9601
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3851 | F1=0.6963 | AUROC=0.7528 | AUPRC=0.7391
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5286 | F1=0.7631 | AUROC=0.8597 | AUPRC=0.8429
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 174.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7550 | F1=0.8237 | AUROC=0.9606 | AUPRC=0.9134
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8486 | F1=0.9194 | AUROC=0.9842 | AUPRC=0.9844
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3894 | F1=0.7125 | AUROC=0.7704 | AUPRC=0.7493
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5275 | F1=0.7626 | AUROC=0.8864 | AUPRC=0.8637
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 130.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7436 | F1=0.8156 | AUROC=0.9521 | AUPRC=0.8980
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8189 | F1=0.9056 | AUROC=0.9718 | AUPRC=0.9717
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4054 | F1=0.7211 | AUROC=0.7697 | AUPRC=0.7628
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5329 | F1=0.7652 | AUROC=0.8707 | AUPRC=0.8450
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 115.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7317 | F1=0.8073 | AUROC=0.9511 | AUPRC=0.8939
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8246 | F1=0.9086 | AUROC=0.9720 | AUPRC=0.9694
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4321 | F1=0.7304 | AUROC=0.7685 | AUPRC=0.7563
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5336 | F1=0.7655 | AUROC=0.8748 | AUPRC=0.8502
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 142.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7420 | F1=0.8145 | AUROC=0.9508 | AUPRC=0.8946
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8333 | F1=0.9129 | AUROC=0.9709 | AUPRC=0.9682
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5916 | val_loss=0.4349 | val_mcc=0.5007 | val_f1=0.5998 | val_auroc=0.8274

[Epoch 02] train_loss=0.5108 | val_loss=0.4588 | val_mcc=0.5075 | val_f1=0.6081 | val_auroc=0.8440

[Epoch 03] train_loss=0.4769 | val_loss=0.4351 | val_mcc=0.5268 | val_f1=0.6229 | val_auroc=0.8546

[Epoch 04] train_loss=0.4481 | val_loss=0.4611 | val_mcc=0.5227 | val_f1=0.6184 | val_auroc=0.8649

[Epoch 05] train_loss=0.4190 | val_loss=0.4146 | val_mcc=0.5415 | val_f1=0.6342 | val_auroc=0.8719

[Epoch 06] train_loss=0.3901 | val_loss=0.4100 | val_mcc=0.5576 | val_f1=0.6469 | val_auroc=0.8749

[Epoch 07] train_loss=0.3612 | val_loss=0.3934 | val_mcc=0.5630 | val_f1=0.6511 | val_auroc=0.8770

[Epoch 08] train_loss=0.3360 | val_loss=0.4446 | val_mcc=0.5414 | val_f1=0.6331 | val_auroc=0.8741

[Epoch 09] train_loss=0.3027 | val_loss=0.4013 | val_mcc=0.5588 | val_f1=0.6478 | val_auroc=0.8765

[Epoch 10] train_loss=0.2772 | val_loss=0.4810 | val_mcc=0.5386 | val_f1=0.6314 | val_auroc=0.8718

[Epoch 11] train_loss=0.2501 | val_loss=0.4632 | val_mcc=0.5461 | val_f1=0.6381 | val_auroc=0.8668

[Epoch 12] train_loss=0.2134 | val_loss=0.4990 | val_mcc=0.5361 | val_f1=0.6302 | val_auroc=0.8665

[Epoch 13] train_loss=0.1961 | val_loss=0.5509 | val_mcc=0.5179 | val_f1=0.6151 | val_auroc=0.8616
[EarlyStop] epoch=13 | best_val_mcc=0.5630
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6138 | F1=0.7227 | AUROC=0.8918 | AUPRC=0.7853
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5596 | F1=0.7710 | AUROC=0.8698 | AUPRC=0.8701
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4138 | F1=0.6976 | AUROC=0.7481 | AUPRC=0.7235
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5722 | F1=0.7654 | AUROC=0.8651 | AUPRC=0.8381
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5891 | val_loss=0.4363 | val_mcc=0.5078 | val_f1=0.6065 | val_auroc=0.8332

[Epoch 02] train_loss=0.5103 | val_loss=0.3986 | val_mcc=0.5331 | val_f1=0.6260 | val_auroc=0.8473

[Epoch 03] train_loss=0.4792 | val_loss=0.4267 | val_mcc=0.5349 | val_f1=0.6294 | val_auroc=0.8552

[Epoch 04] train_loss=0.4504 | val_loss=0.4074 | val_mcc=0.5471 | val_f1=0.6388 | val_auroc=0.8626

[Epoch 05] train_loss=0.4276 | val_loss=0.4367 | val_mcc=0.5460 | val_f1=0.6374 | val_auroc=0.8670

[Epoch 06] train_loss=0.4034 | val_loss=0.3618 | val_mcc=0.5707 | val_f1=0.6542 | val_auroc=0.8709

[Epoch 07] train_loss=0.3773 | val_loss=0.3924 | val_mcc=0.5649 | val_f1=0.6525 | val_auroc=0.8718

[Epoch 08] train_loss=0.3510 | val_loss=0.4089 | val_mcc=0.5685 | val_f1=0.6555 | val_auroc=0.8729

[Epoch 09] train_loss=0.3271 | val_loss=0.5671 | val_mcc=0.5243 | val_f1=0.6173 | val_auroc=0.8691

[Epoch 10] train_loss=0.3005 | val_loss=0.5104 | val_mcc=0.5541 | val_f1=0.6434 | val_auroc=0.8654

[Epoch 11] train_loss=0.2659 | val_loss=0.5290 | val_mcc=0.5376 | val_f1=0.6312 | val_auroc=0.8559

[Epoch 12] train_loss=0.2519 | val_loss=0.5311 | val_mcc=0.5401 | val_f1=0.6334 | val_auroc=0.8559
[EarlyStop] epoch=12 | best_val_mcc=0.5707
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5924 | F1=0.6984 | AUROC=0.8894 | AUPRC=0.7638
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5770 | F1=0.7587 | AUROC=0.8648 | AUPRC=0.8570
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3874 | F1=0.6601 | AUROC=0.7572 | AUPRC=0.7275
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5600 | F1=0.7446 | AUROC=0.8663 | AUPRC=0.8238
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5801 | val_loss=0.4417 | val_mcc=0.5008 | val_f1=0.6025 | val_auroc=0.8385

[Epoch 02] train_loss=0.5023 | val_loss=0.4361 | val_mcc=0.5171 | val_f1=0.6156 | val_auroc=0.8530

[Epoch 03] train_loss=0.4702 | val_loss=0.3691 | val_mcc=0.5438 | val_f1=0.6343 | val_auroc=0.8630

[Epoch 04] train_loss=0.4438 | val_loss=0.3772 | val_mcc=0.5579 | val_f1=0.6461 | val_auroc=0.8732

[Epoch 05] train_loss=0.4138 | val_loss=0.4020 | val_mcc=0.5502 | val_f1=0.6411 | val_auroc=0.8788

[Epoch 06] train_loss=0.3889 | val_loss=0.4000 | val_mcc=0.5670 | val_f1=0.6542 | val_auroc=0.8819

[Epoch 07] train_loss=0.3615 | val_loss=0.3495 | val_mcc=0.5817 | val_f1=0.6606 | val_auroc=0.8846

[Epoch 08] train_loss=0.3288 | val_loss=0.3954 | val_mcc=0.5766 | val_f1=0.6617 | val_auroc=0.8805

[Epoch 09] train_loss=0.2988 | val_loss=0.4309 | val_mcc=0.5496 | val_f1=0.6408 | val_auroc=0.8693

[Epoch 10] train_loss=0.2699 | val_loss=0.4233 | val_mcc=0.5552 | val_f1=0.6434 | val_auroc=0.8666

[Epoch 11] train_loss=0.2453 | val_loss=0.4712 | val_mcc=0.5539 | val_f1=0.6416 | val_auroc=0.8633

[Epoch 12] train_loss=0.2070 | val_loss=0.5368 | val_mcc=0.5451 | val_f1=0.6371 | val_auroc=0.8592

[Epoch 13] train_loss=0.1956 | val_loss=0.5721 | val_mcc=0.5473 | val_f1=0.6389 | val_auroc=0.8584
[EarlyStop] epoch=13 | best_val_mcc=0.5817
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6100 | F1=0.7061 | AUROC=0.8983 | AUPRC=0.7916
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5667 | F1=0.7508 | AUROC=0.8733 | AUPRC=0.8692
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4075 | F1=0.6656 | AUROC=0.7614 | AUPRC=0.7418
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5695 | F1=0.7454 | AUROC=0.8751 | AUPRC=0.8447
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5863 | val_loss=0.4270 | val_mcc=0.4991 | val_f1=0.5982 | val_auroc=0.8299

[Epoch 02] train_loss=0.5019 | val_loss=0.4373 | val_mcc=0.5123 | val_f1=0.6118 | val_auroc=0.8434

[Epoch 03] train_loss=0.4697 | val_loss=0.4483 | val_mcc=0.5207 | val_f1=0.6181 | val_auroc=0.8590

[Epoch 04] train_loss=0.4415 | val_loss=0.4013 | val_mcc=0.5455 | val_f1=0.6376 | val_auroc=0.8708

[Epoch 05] train_loss=0.4095 | val_loss=0.4319 | val_mcc=0.5445 | val_f1=0.6361 | val_auroc=0.8757

[Epoch 06] train_loss=0.3803 | val_loss=0.4291 | val_mcc=0.5452 | val_f1=0.6363 | val_auroc=0.8808

[Epoch 07] train_loss=0.3488 | val_loss=0.3891 | val_mcc=0.5695 | val_f1=0.6562 | val_auroc=0.8812

[Epoch 08] train_loss=0.3165 | val_loss=0.4253 | val_mcc=0.5505 | val_f1=0.6413 | val_auroc=0.8771

[Epoch 09] train_loss=0.2820 | val_loss=0.4839 | val_mcc=0.5325 | val_f1=0.6258 | val_auroc=0.8746

[Epoch 10] train_loss=0.2478 | val_loss=0.4868 | val_mcc=0.5354 | val_f1=0.6292 | val_auroc=0.8712

[Epoch 11] train_loss=0.2208 | val_loss=0.5312 | val_mcc=0.5289 | val_f1=0.6236 | val_auroc=0.8698

[Epoch 12] train_loss=0.1826 | val_loss=0.5082 | val_mcc=0.5384 | val_f1=0.6321 | val_auroc=0.8668

[Epoch 13] train_loss=0.1661 | val_loss=0.6112 | val_mcc=0.5085 | val_f1=0.6071 | val_auroc=0.8621
[EarlyStop] epoch=13 | best_val_mcc=0.5695
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6020 | F1=0.7126 | AUROC=0.8961 | AUPRC=0.7920
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5819 | F1=0.7751 | AUROC=0.8831 | AUPRC=0.8740
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4120 | F1=0.6893 | AUROC=0.7550 | AUPRC=0.7376
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5689 | F1=0.7596 | AUROC=0.8733 | AUPRC=0.8475
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 185.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5752 | F1=0.6983 | AUROC=0.8857 | AUPRC=0.7690
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5792 | F1=0.7898 | AUROC=0.8673 | AUPRC=0.8527
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3825 | F1=0.6975 | AUROC=0.7520 | AUPRC=0.7403
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5766 | F1=0.7745 | AUROC=0.8643 | AUPRC=0.8335
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 100.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5874 | F1=0.7052 | AUROC=0.8872 | AUPRC=0.7774
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5733 | F1=0.7820 | AUROC=0.8769 | AUPRC=0.8719
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3971 | F1=0.6912 | AUROC=0.7572 | AUPRC=0.7389
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5775 | F1=0.7716 | AUROC=0.8653 | AUPRC=0.8390
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 91.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5712 | F1=0.6932 | AUROC=0.8780 | AUPRC=0.7675
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5720 | F1=0.7736 | AUROC=0.8653 | AUPRC=0.8663
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3901 | F1=0.6828 | AUROC=0.7504 | AUPRC=0.7352
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5646 | F1=0.7634 | AUROC=0.8606 | AUPRC=0.8355
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 97.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5768 | F1=0.6978 | AUROC=0.8822 | AUPRC=0.7729
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5487 | F1=0.7630 | AUROC=0.8693 | AUPRC=0.8651
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3851 | F1=0.6846 | AUROC=0.7594 | AUPRC=0.7445
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4292 | val_loss=0.2170 | val_mcc=0.7296 | val_f1=0.7813 | val_auroc=0.9529

[Epoch 02] train_loss=0.3186 | val_loss=0.2170 | val_mcc=0.7415 | val_f1=0.7921 | val_auroc=0.9570

[Epoch 03] train_loss=0.2946 | val_loss=0.2127 | val_mcc=0.7435 | val_f1=0.7937 | val_auroc=0.9572

[Epoch 04] train_loss=0.2821 | val_loss=0.2205 | val_mcc=0.7393 | val_f1=0.7902 | val_auroc=0.9579

[Epoch 05] train_loss=0.2738 | val_loss=0.2117 | val_mcc=0.7510 | val_f1=0.7997 | val_auroc=0.9595

[Epoch 06] train_loss=0.2585 | val_loss=0.1963 | val_mcc=0.7551 | val_f1=0.8021 | val_auroc=0.9608

[Epoch 07] train_loss=0.2435 | val_loss=0.2253 | val_mcc=0.7403 | val_f1=0.7906 | val_auroc=0.9603

[Epoch 08] train_loss=0.2265 | val_loss=0.2128 | val_mcc=0.7512 | val_f1=0.7999 | val_auroc=0.9613

[Epoch 09] train_loss=0.2081 | val_loss=0.2263 | val_mcc=0.7398 | val_f1=0.7905 | val_auroc=0.9595

[Epoch 10] train_loss=0.1894 | val_loss=0.2258 | val_mcc=0.7400 | val_f1=0.7908 | val_auroc=0.9582

[Epoch 11] train_loss=0.1700 | val_loss=0.2308 | val_mcc=0.7400 | val_f1=0.7909 | val_auroc=0.9577

[Epoch 12] train_loss=0.1549 | val_loss=0.2348 | val_mcc=0.7476 | val_f1=0.7970 | val_auroc=0.9569
[EarlyStop] epoch=12 | best_val_mcc=0.7551
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7601 | F1=0.8245 | AUROC=0.9545 | AUPRC=0.9003
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7929 | F1=0.8816 | AUROC=0.9741 | AUPRC=0.9748
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3938 | F1=0.6939 | AUROC=0.7615 | AUPRC=0.7459
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5989 | F1=0.7944 | AUROC=0.8882 | AUPRC=0.8490
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4276 | val_loss=0.3200 | val_mcc=0.6669 | val_f1=0.7253 | val_auroc=0.9526

[Epoch 02] train_loss=0.3207 | val_loss=0.2447 | val_mcc=0.7234 | val_f1=0.7764 | val_auroc=0.9571

[Epoch 03] train_loss=0.2989 | val_loss=0.2413 | val_mcc=0.7287 | val_f1=0.7804 | val_auroc=0.9591

[Epoch 04] train_loss=0.2857 | val_loss=0.2416 | val_mcc=0.7292 | val_f1=0.7805 | val_auroc=0.9596

[Epoch 05] train_loss=0.2737 | val_loss=0.2695 | val_mcc=0.7125 | val_f1=0.7650 | val_auroc=0.9592

[Epoch 06] train_loss=0.2584 | val_loss=0.2297 | val_mcc=0.7386 | val_f1=0.7892 | val_auroc=0.9598

[Epoch 07] train_loss=0.2464 | val_loss=0.2234 | val_mcc=0.7336 | val_f1=0.7854 | val_auroc=0.9546

[Epoch 08] train_loss=0.2290 | val_loss=0.2359 | val_mcc=0.7292 | val_f1=0.7822 | val_auroc=0.9550

[Epoch 09] train_loss=0.2159 | val_loss=0.2073 | val_mcc=0.7451 | val_f1=0.7925 | val_auroc=0.9595

[Epoch 10] train_loss=0.1976 | val_loss=0.2580 | val_mcc=0.7252 | val_f1=0.7784 | val_auroc=0.9544

[Epoch 11] train_loss=0.1804 | val_loss=0.2699 | val_mcc=0.7217 | val_f1=0.7751 | val_auroc=0.9555

[Epoch 12] train_loss=0.1635 | val_loss=0.3083 | val_mcc=0.7050 | val_f1=0.7611 | val_auroc=0.9504

[Epoch 13] train_loss=0.1444 | val_loss=0.3083 | val_mcc=0.7147 | val_f1=0.7694 | val_auroc=0.9517

[Epoch 14] train_loss=0.1244 | val_loss=0.3254 | val_mcc=0.7125 | val_f1=0.7685 | val_auroc=0.9485

[Epoch 15] train_loss=0.1125 | val_loss=0.3417 | val_mcc=0.7037 | val_f1=0.7610 | val_auroc=0.9477
[EarlyStop] epoch=15 | best_val_mcc=0.7451
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7477 | F1=0.8123 | AUROC=0.9524 | AUPRC=0.8876
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7529 | F1=0.8530 | AUROC=0.9677 | AUPRC=0.9651
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4156 | F1=0.6963 | AUROC=0.7590 | AUPRC=0.7413
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6256 | F1=0.8037 | AUROC=0.8802 | AUPRC=0.8280
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4269 | val_loss=0.2122 | val_mcc=0.7134 | val_f1=0.7624 | val_auroc=0.9533

[Epoch 02] train_loss=0.3191 | val_loss=0.2188 | val_mcc=0.7374 | val_f1=0.7888 | val_auroc=0.9575

[Epoch 03] train_loss=0.2953 | val_loss=0.2186 | val_mcc=0.7340 | val_f1=0.7861 | val_auroc=0.9573

[Epoch 04] train_loss=0.2843 | val_loss=0.1966 | val_mcc=0.7444 | val_f1=0.7887 | val_auroc=0.9598

[Epoch 05] train_loss=0.2721 | val_loss=0.2075 | val_mcc=0.7390 | val_f1=0.7899 | val_auroc=0.9593

[Epoch 06] train_loss=0.2580 | val_loss=0.2140 | val_mcc=0.7458 | val_f1=0.7955 | val_auroc=0.9605

[Epoch 07] train_loss=0.2447 | val_loss=0.2128 | val_mcc=0.7504 | val_f1=0.7991 | val_auroc=0.9620

[Epoch 08] train_loss=0.2278 | val_loss=0.1939 | val_mcc=0.7586 | val_f1=0.8031 | val_auroc=0.9611

[Epoch 09] train_loss=0.2142 | val_loss=0.2399 | val_mcc=0.7308 | val_f1=0.7829 | val_auroc=0.9593

[Epoch 10] train_loss=0.1944 | val_loss=0.2252 | val_mcc=0.7527 | val_f1=0.8011 | val_auroc=0.9595

[Epoch 11] train_loss=0.1768 | val_loss=0.2827 | val_mcc=0.7192 | val_f1=0.7732 | val_auroc=0.9556

[Epoch 12] train_loss=0.1554 | val_loss=0.2301 | val_mcc=0.7457 | val_f1=0.7937 | val_auroc=0.9560

[Epoch 13] train_loss=0.1255 | val_loss=0.2997 | val_mcc=0.7170 | val_f1=0.7721 | val_auroc=0.9519

[Epoch 14] train_loss=0.1181 | val_loss=0.2938 | val_mcc=0.7287 | val_f1=0.7819 | val_auroc=0.9509
[EarlyStop] epoch=14 | best_val_mcc=0.7586
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7416 | F1=0.8082 | AUROC=0.9533 | AUPRC=0.8934
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7471 | F1=0.8531 | AUROC=0.9671 | AUPRC=0.9677
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4283 | F1=0.6992 | AUROC=0.7675 | AUPRC=0.7491
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6294 | F1=0.8046 | AUROC=0.8898 | AUPRC=0.8469
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4139 | val_loss=0.2924 | val_mcc=0.6845 | val_f1=0.7411 | val_auroc=0.9541

[Epoch 02] train_loss=0.3104 | val_loss=0.2496 | val_mcc=0.7168 | val_f1=0.7702 | val_auroc=0.9578

[Epoch 03] train_loss=0.2910 | val_loss=0.2108 | val_mcc=0.7408 | val_f1=0.7915 | val_auroc=0.9581

[Epoch 04] train_loss=0.2790 | val_loss=0.2380 | val_mcc=0.7277 | val_f1=0.7795 | val_auroc=0.9604

[Epoch 05] train_loss=0.2632 | val_loss=0.2252 | val_mcc=0.7368 | val_f1=0.7875 | val_auroc=0.9613

[Epoch 06] train_loss=0.2461 | val_loss=0.2142 | val_mcc=0.7430 | val_f1=0.7932 | val_auroc=0.9616

[Epoch 07] train_loss=0.2322 | val_loss=0.2544 | val_mcc=0.7163 | val_f1=0.7693 | val_auroc=0.9613

[Epoch 08] train_loss=0.2140 | val_loss=0.2078 | val_mcc=0.7547 | val_f1=0.8025 | val_auroc=0.9611

[Epoch 09] train_loss=0.1955 | val_loss=0.2353 | val_mcc=0.7367 | val_f1=0.7880 | val_auroc=0.9590

[Epoch 10] train_loss=0.1731 | val_loss=0.2721 | val_mcc=0.7165 | val_f1=0.7702 | val_auroc=0.9574

[Epoch 11] train_loss=0.1557 | val_loss=0.2740 | val_mcc=0.7228 | val_f1=0.7754 | val_auroc=0.9581

[Epoch 12] train_loss=0.1365 | val_loss=0.2654 | val_mcc=0.7325 | val_f1=0.7849 | val_auroc=0.9550

[Epoch 13] train_loss=0.1128 | val_loss=0.2958 | val_mcc=0.7245 | val_f1=0.7771 | val_auroc=0.9537

[Epoch 14] train_loss=0.0993 | val_loss=0.3074 | val_mcc=0.7197 | val_f1=0.7736 | val_auroc=0.9534
[EarlyStop] epoch=14 | best_val_mcc=0.7547
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7577 | F1=0.8245 | AUROC=0.9542 | AUPRC=0.8961
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7731 | F1=0.8738 | AUROC=0.9720 | AUPRC=0.9730
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4069 | F1=0.7114 | AUROC=0.7699 | AUPRC=0.7571
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6173 | F1=0.8032 | AUROC=0.8887 | AUPRC=0.8497
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 177.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7657 | F1=0.8313 | AUROC=0.9625 | AUPRC=0.9149
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8879 | F1=0.9407 | AUROC=0.9863 | AUPRC=0.9877
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4161 | F1=0.7261 | AUROC=0.7591 | AUPRC=0.7431
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5525 | F1=0.7737 | AUROC=0.8982 | AUPRC=0.8774
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 164.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7628 | F1=0.8293 | AUROC=0.9587 | AUPRC=0.9024
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8439 | F1=0.9197 | AUROC=0.9782 | AUPRC=0.9794
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4124 | F1=0.7236 | AUROC=0.7691 | AUPRC=0.7506
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5959 | F1=0.7935 | AUROC=0.8910 | AUPRC=0.8545
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 134.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7517 | F1=0.8214 | AUROC=0.9566 | AUPRC=0.9050
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8197 | F1=0.9048 | AUROC=0.9734 | AUPRC=0.9746
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4081 | F1=0.7194 | AUROC=0.7687 | AUPRC=0.7548
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5888 | F1=0.7904 | AUROC=0.8883 | AUPRC=0.8592
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 74.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7502 | F1=0.8203 | AUROC=0.9567 | AUPRC=0.9055
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7879 | F1=0.8889 | AUROC=0.9714 | AUPRC=0.9714
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5914 | val_loss=0.4092 | val_mcc=0.4528 | val_f1=0.5484 | val_auroc=0.8213

[Epoch 02] train_loss=0.5124 | val_loss=0.4299 | val_mcc=0.4772 | val_f1=0.5824 | val_auroc=0.8318

[Epoch 03] train_loss=0.4771 | val_loss=0.3981 | val_mcc=0.4858 | val_f1=0.5875 | val_auroc=0.8476

[Epoch 04] train_loss=0.4467 | val_loss=0.4206 | val_mcc=0.4992 | val_f1=0.6017 | val_auroc=0.8567

[Epoch 05] train_loss=0.4132 | val_loss=0.4210 | val_mcc=0.5090 | val_f1=0.6093 | val_auroc=0.8649

[Epoch 06] train_loss=0.3806 | val_loss=0.3973 | val_mcc=0.5040 | val_f1=0.6035 | val_auroc=0.8659

[Epoch 07] train_loss=0.3365 | val_loss=0.4556 | val_mcc=0.5003 | val_f1=0.6027 | val_auroc=0.8645

[Epoch 08] train_loss=0.3041 | val_loss=0.4920 | val_mcc=0.4848 | val_f1=0.5905 | val_auroc=0.8595

[Epoch 09] train_loss=0.2649 | val_loss=0.4918 | val_mcc=0.4847 | val_f1=0.5903 | val_auroc=0.8565

[Epoch 10] train_loss=0.2155 | val_loss=0.5444 | val_mcc=0.4882 | val_f1=0.5934 | val_auroc=0.8555

[Epoch 11] train_loss=0.1915 | val_loss=0.5731 | val_mcc=0.4797 | val_f1=0.5868 | val_auroc=0.8515
[EarlyStop] epoch=11 | best_val_mcc=0.5090
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5663 | F1=0.6898 | AUROC=0.8781 | AUPRC=0.7594
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5121 | F1=0.7417 | AUROC=0.8374 | AUPRC=0.8372
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3475 | F1=0.6656 | AUROC=0.7341 | AUPRC=0.7176
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5307 | F1=0.7405 | AUROC=0.8467 | AUPRC=0.8125
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5895 | val_loss=0.5094 | val_mcc=0.4591 | val_f1=0.5711 | val_auroc=0.8248

[Epoch 02] train_loss=0.5086 | val_loss=0.4271 | val_mcc=0.4862 | val_f1=0.5900 | val_auroc=0.8381

[Epoch 03] train_loss=0.4750 | val_loss=0.4042 | val_mcc=0.5033 | val_f1=0.6025 | val_auroc=0.8503

[Epoch 04] train_loss=0.4451 | val_loss=0.4389 | val_mcc=0.5028 | val_f1=0.6046 | val_auroc=0.8601

[Epoch 05] train_loss=0.4124 | val_loss=0.5095 | val_mcc=0.4774 | val_f1=0.5832 | val_auroc=0.8599

[Epoch 06] train_loss=0.3799 | val_loss=0.4844 | val_mcc=0.4943 | val_f1=0.5978 | val_auroc=0.8596

[Epoch 07] train_loss=0.3448 | val_loss=0.4848 | val_mcc=0.4932 | val_f1=0.5972 | val_auroc=0.8540

[Epoch 08] train_loss=0.2966 | val_loss=0.6083 | val_mcc=0.4956 | val_f1=0.5969 | val_auroc=0.8576

[Epoch 09] train_loss=0.2724 | val_loss=0.5598 | val_mcc=0.4955 | val_f1=0.5990 | val_auroc=0.8512
[EarlyStop] epoch=9 | best_val_mcc=0.5033
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5571 | F1=0.6747 | AUROC=0.8673 | AUPRC=0.7404
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5047 | F1=0.7186 | AUROC=0.8312 | AUPRC=0.8375
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3370 | F1=0.6331 | AUROC=0.7296 | AUPRC=0.7143
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.4972 | F1=0.7095 | AUROC=0.8369 | AUPRC=0.7992
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5843 | val_loss=0.4123 | val_mcc=0.4584 | val_f1=0.5613 | val_auroc=0.8306

[Epoch 02] train_loss=0.5080 | val_loss=0.4065 | val_mcc=0.4913 | val_f1=0.5937 | val_auroc=0.8448

[Epoch 03] train_loss=0.4784 | val_loss=0.3635 | val_mcc=0.4917 | val_f1=0.5798 | val_auroc=0.8527

[Epoch 04] train_loss=0.4495 | val_loss=0.4068 | val_mcc=0.5014 | val_f1=0.6030 | val_auroc=0.8639

[Epoch 05] train_loss=0.4192 | val_loss=0.3614 | val_mcc=0.5018 | val_f1=0.5860 | val_auroc=0.8683

[Epoch 06] train_loss=0.3808 | val_loss=0.4674 | val_mcc=0.4998 | val_f1=0.6021 | val_auroc=0.8649

[Epoch 07] train_loss=0.3429 | val_loss=0.4153 | val_mcc=0.5012 | val_f1=0.6012 | val_auroc=0.8679

[Epoch 08] train_loss=0.2988 | val_loss=0.4564 | val_mcc=0.4931 | val_f1=0.5940 | val_auroc=0.8578

[Epoch 09] train_loss=0.2545 | val_loss=0.5289 | val_mcc=0.4831 | val_f1=0.5884 | val_auroc=0.8497

[Epoch 10] train_loss=0.2027 | val_loss=0.5966 | val_mcc=0.4856 | val_f1=0.5906 | val_auroc=0.8449

[Epoch 11] train_loss=0.1808 | val_loss=0.6486 | val_mcc=0.4733 | val_f1=0.5807 | val_auroc=0.8398
[EarlyStop] epoch=11 | best_val_mcc=0.5018
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5669 | F1=0.6642 | AUROC=0.8791 | AUPRC=0.7574
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5087 | F1=0.6917 | AUROC=0.8412 | AUPRC=0.8435
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3394 | F1=0.6018 | AUROC=0.7356 | AUPRC=0.7117
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.4921 | F1=0.6759 | AUROC=0.8488 | AUPRC=0.8127
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5935 | val_loss=0.5059 | val_mcc=0.4477 | val_f1=0.5625 | val_auroc=0.8178

[Epoch 02] train_loss=0.5084 | val_loss=0.4310 | val_mcc=0.4818 | val_f1=0.5871 | val_auroc=0.8379

[Epoch 03] train_loss=0.4774 | val_loss=0.4075 | val_mcc=0.4954 | val_f1=0.5970 | val_auroc=0.8485

[Epoch 04] train_loss=0.4472 | val_loss=0.4192 | val_mcc=0.5006 | val_f1=0.6028 | val_auroc=0.8591

[Epoch 05] train_loss=0.4138 | val_loss=0.4202 | val_mcc=0.5016 | val_f1=0.6037 | val_auroc=0.8645

[Epoch 06] train_loss=0.3757 | val_loss=0.4158 | val_mcc=0.5150 | val_f1=0.6137 | val_auroc=0.8674

[Epoch 07] train_loss=0.3337 | val_loss=0.4447 | val_mcc=0.4963 | val_f1=0.5995 | val_auroc=0.8638

[Epoch 08] train_loss=0.2895 | val_loss=0.4884 | val_mcc=0.4881 | val_f1=0.5932 | val_auroc=0.8565

[Epoch 09] train_loss=0.2444 | val_loss=0.5516 | val_mcc=0.4800 | val_f1=0.5866 | val_auroc=0.8538

[Epoch 10] train_loss=0.2036 | val_loss=0.6350 | val_mcc=0.4665 | val_f1=0.5753 | val_auroc=0.8456

[Epoch 11] train_loss=0.1553 | val_loss=0.7056 | val_mcc=0.4582 | val_f1=0.5678 | val_auroc=0.8475

[Epoch 12] train_loss=0.1365 | val_loss=0.6285 | val_mcc=0.4747 | val_f1=0.5831 | val_auroc=0.8476
[EarlyStop] epoch=12 | best_val_mcc=0.5150
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5747 | F1=0.6928 | AUROC=0.8787 | AUPRC=0.7543
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5104 | F1=0.7367 | AUROC=0.8328 | AUPRC=0.8339
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3300 | F1=0.6511 | AUROC=0.7309 | AUPRC=0.7113
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5291 | F1=0.7380 | AUROC=0.8462 | AUPRC=0.8073
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 146.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5491 | F1=0.6807 | AUROC=0.8683 | AUPRC=0.7326
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.4878 | F1=0.7406 | AUROC=0.8260 | AUPRC=0.8253
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3194 | F1=0.6667 | AUROC=0.7270 | AUPRC=0.7102
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5285 | F1=0.7502 | AUROC=0.8356 | AUPRC=0.8013
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 121.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5578 | F1=0.6861 | AUROC=0.8738 | AUPRC=0.7491
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5449 | F1=0.7668 | AUROC=0.8342 | AUPRC=0.8226
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3445 | F1=0.6756 | AUROC=0.7301 | AUPRC=0.7088
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5488 | F1=0.7608 | AUROC=0.8447 | AUPRC=0.8082
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 38.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5605 | F1=0.6870 | AUROC=0.8671 | AUPRC=0.7441
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5227 | F1=0.7507 | AUROC=0.8301 | AUPRC=0.8285
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3443 | F1=0.6692 | AUROC=0.7293 | AUPRC=0.7082
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5203 | F1=0.7413 | AUROC=0.8405 | AUPRC=0.8065
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 41.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5451 | F1=0.6766 | AUROC=0.8694 | AUPRC=0.7438
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4964 | F1=0.7431 | AUROC=0.8311 | AUPRC=0.8288
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3354 | F1=0.6626 | AUROC=0.7311 | AUPRC=0.7075
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4265 | val_loss=0.2371 | val_mcc=0.7171 | val_f1=0.7723 | val_auroc=0.9557

[Epoch 02] train_loss=0.3090 | val_loss=0.2184 | val_mcc=0.7327 | val_f1=0.7850 | val_auroc=0.9581

[Epoch 03] train_loss=0.2882 | val_loss=0.2235 | val_mcc=0.7339 | val_f1=0.7857 | val_auroc=0.9581

[Epoch 04] train_loss=0.2663 | val_loss=0.2424 | val_mcc=0.7206 | val_f1=0.7737 | val_auroc=0.9585

[Epoch 05] train_loss=0.2488 | val_loss=0.2121 | val_mcc=0.7349 | val_f1=0.7867 | val_auroc=0.9590

[Epoch 06] train_loss=0.2310 | val_loss=0.2117 | val_mcc=0.7442 | val_f1=0.7942 | val_auroc=0.9592

[Epoch 07] train_loss=0.2132 | val_loss=0.2200 | val_mcc=0.7422 | val_f1=0.7926 | val_auroc=0.9586

[Epoch 08] train_loss=0.1885 | val_loss=0.2563 | val_mcc=0.7277 | val_f1=0.7792 | val_auroc=0.9591

[Epoch 09] train_loss=0.1690 | val_loss=0.2308 | val_mcc=0.7396 | val_f1=0.7906 | val_auroc=0.9579

[Epoch 10] train_loss=0.1436 | val_loss=0.2513 | val_mcc=0.7271 | val_f1=0.7806 | val_auroc=0.9548

[Epoch 11] train_loss=0.1137 | val_loss=0.2738 | val_mcc=0.7234 | val_f1=0.7774 | val_auroc=0.9550

[Epoch 12] train_loss=0.0981 | val_loss=0.3258 | val_mcc=0.7038 | val_f1=0.7599 | val_auroc=0.9539
[EarlyStop] epoch=12 | best_val_mcc=0.7442
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7529 | F1=0.8207 | AUROC=0.9522 | AUPRC=0.8905
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7777 | F1=0.8777 | AUROC=0.9649 | AUPRC=0.9665
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4014 | F1=0.7020 | AUROC=0.7570 | AUPRC=0.7338
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5542 | F1=0.7738 | AUROC=0.8752 | AUPRC=0.8480
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4378 | val_loss=0.2409 | val_mcc=0.7072 | val_f1=0.7640 | val_auroc=0.9553

[Epoch 02] train_loss=0.3124 | val_loss=0.2713 | val_mcc=0.7064 | val_f1=0.7597 | val_auroc=0.9587

[Epoch 03] train_loss=0.2868 | val_loss=0.2078 | val_mcc=0.7388 | val_f1=0.7888 | val_auroc=0.9585

[Epoch 04] train_loss=0.2702 | val_loss=0.2611 | val_mcc=0.7137 | val_f1=0.7662 | val_auroc=0.9600

[Epoch 05] train_loss=0.2495 | val_loss=0.2244 | val_mcc=0.7340 | val_f1=0.7861 | val_auroc=0.9588

[Epoch 06] train_loss=0.2331 | val_loss=0.2497 | val_mcc=0.7338 | val_f1=0.7841 | val_auroc=0.9607

[Epoch 07] train_loss=0.2121 | val_loss=0.2410 | val_mcc=0.7335 | val_f1=0.7857 | val_auroc=0.9574

[Epoch 08] train_loss=0.1827 | val_loss=0.2593 | val_mcc=0.7330 | val_f1=0.7847 | val_auroc=0.9569

[Epoch 09] train_loss=0.1694 | val_loss=0.2723 | val_mcc=0.7233 | val_f1=0.7773 | val_auroc=0.9545
[EarlyStop] epoch=9 | best_val_mcc=0.7388
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7497 | F1=0.8175 | AUROC=0.9510 | AUPRC=0.8898
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7519 | F1=0.8602 | AUROC=0.9667 | AUPRC=0.9661
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3954 | F1=0.6981 | AUROC=0.7584 | AUPRC=0.7390
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5591 | F1=0.7762 | AUROC=0.8716 | AUPRC=0.8421
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4269 | val_loss=0.2207 | val_mcc=0.7248 | val_f1=0.7787 | val_auroc=0.9566

[Epoch 02] train_loss=0.3131 | val_loss=0.2235 | val_mcc=0.7317 | val_f1=0.7841 | val_auroc=0.9591

[Epoch 03] train_loss=0.2885 | val_loss=0.2056 | val_mcc=0.7463 | val_f1=0.7957 | val_auroc=0.9604

[Epoch 04] train_loss=0.2702 | val_loss=0.2041 | val_mcc=0.7431 | val_f1=0.7915 | val_auroc=0.9594

[Epoch 05] train_loss=0.2511 | val_loss=0.2022 | val_mcc=0.7479 | val_f1=0.7944 | val_auroc=0.9605

[Epoch 06] train_loss=0.2352 | val_loss=0.2342 | val_mcc=0.7319 | val_f1=0.7843 | val_auroc=0.9575

[Epoch 07] train_loss=0.2119 | val_loss=0.2688 | val_mcc=0.7216 | val_f1=0.7731 | val_auroc=0.9593

[Epoch 08] train_loss=0.1835 | val_loss=0.2346 | val_mcc=0.7349 | val_f1=0.7866 | val_auroc=0.9570

[Epoch 09] train_loss=0.1562 | val_loss=0.2681 | val_mcc=0.7264 | val_f1=0.7788 | val_auroc=0.9577

[Epoch 10] train_loss=0.1250 | val_loss=0.3024 | val_mcc=0.7079 | val_f1=0.7649 | val_auroc=0.9489

[Epoch 11] train_loss=0.1085 | val_loss=0.3147 | val_mcc=0.7037 | val_f1=0.7621 | val_auroc=0.9476
[EarlyStop] epoch=11 | best_val_mcc=0.7479
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7457 | F1=0.8123 | AUROC=0.9512 | AUPRC=0.8859
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7416 | F1=0.8531 | AUROC=0.9624 | AUPRC=0.9625
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4003 | F1=0.6904 | AUROC=0.7638 | AUPRC=0.7422
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5945 | F1=0.7898 | AUROC=0.8758 | AUPRC=0.8442
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4113 | val_loss=0.2342 | val_mcc=0.7163 | val_f1=0.7720 | val_auroc=0.9541

[Epoch 02] train_loss=0.3057 | val_loss=0.2177 | val_mcc=0.7261 | val_f1=0.7798 | val_auroc=0.9573

[Epoch 03] train_loss=0.2814 | val_loss=0.2232 | val_mcc=0.7300 | val_f1=0.7827 | val_auroc=0.9578

[Epoch 04] train_loss=0.2633 | val_loss=0.2199 | val_mcc=0.7340 | val_f1=0.7858 | val_auroc=0.9593

[Epoch 05] train_loss=0.2457 | val_loss=0.2179 | val_mcc=0.7416 | val_f1=0.7920 | val_auroc=0.9601

[Epoch 06] train_loss=0.2259 | val_loss=0.2228 | val_mcc=0.7396 | val_f1=0.7905 | val_auroc=0.9587

[Epoch 07] train_loss=0.2083 | val_loss=0.2509 | val_mcc=0.7285 | val_f1=0.7793 | val_auroc=0.9604

[Epoch 08] train_loss=0.1809 | val_loss=0.2475 | val_mcc=0.7298 | val_f1=0.7817 | val_auroc=0.9575

[Epoch 09] train_loss=0.1563 | val_loss=0.2924 | val_mcc=0.7041 | val_f1=0.7597 | val_auroc=0.9541

[Epoch 10] train_loss=0.1240 | val_loss=0.2819 | val_mcc=0.7227 | val_f1=0.7758 | val_auroc=0.9563

[Epoch 11] train_loss=0.1066 | val_loss=0.2869 | val_mcc=0.7176 | val_f1=0.7722 | val_auroc=0.9546
[EarlyStop] epoch=11 | best_val_mcc=0.7416
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7455 | F1=0.8168 | AUROC=0.9521 | AUPRC=0.8904
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7811 | F1=0.8825 | AUROC=0.9665 | AUPRC=0.9664
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4086 | F1=0.7175 | AUROC=0.7619 | AUPRC=0.7402
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5410 | F1=0.7687 | AUROC=0.8757 | AUPRC=0.8503
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 185.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7568 | F1=0.8250 | AUROC=0.9612 | AUPRC=0.9094
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8449 | F1=0.9185 | AUROC=0.9839 | AUPRC=0.9836
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4032 | F1=0.7212 | AUROC=0.7654 | AUPRC=0.7466
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5320 | F1=0.7646 | AUROC=0.8911 | AUPRC=0.8623
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 189.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7403 | F1=0.8133 | AUROC=0.9552 | AUPRC=0.8974
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7906 | F1=0.8905 | AUROC=0.9724 | AUPRC=0.9722
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4423 | F1=0.7385 | AUROC=0.7673 | AUPRC=0.7426
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5326 | F1=0.7651 | AUROC=0.8778 | AUPRC=0.8469
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 120.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7382 | F1=0.8119 | AUROC=0.9536 | AUPRC=0.8999
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8048 | F1=0.8981 | AUROC=0.9712 | AUPRC=0.9702
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4084 | F1=0.7225 | AUROC=0.7654 | AUPRC=0.7366
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5472 | F1=0.7716 | AUROC=0.8764 | AUPRC=0.8343
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 110.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7386 | F1=0.8121 | AUROC=0.9527 | AUPRC=0.8948
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8043 | F1=0.8987 | AUROC=0.9679 | AUPRC=0.9686
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.6273 | val_loss=0.4712 | val_mcc=0.3984 | val_f1=0.5059 | val_auroc=0.7706

[Epoch 02] train_loss=0.5569 | val_loss=0.5032 | val_mcc=0.4302 | val_f1=0.5467 | val_auroc=0.7893

[Epoch 03] train_loss=0.5265 | val_loss=0.4705 | val_mcc=0.4520 | val_f1=0.5613 | val_auroc=0.8055

[Epoch 04] train_loss=0.5042 | val_loss=0.4476 | val_mcc=0.4702 | val_f1=0.5754 | val_auroc=0.8165

[Epoch 05] train_loss=0.4771 | val_loss=0.4157 | val_mcc=0.4923 | val_f1=0.5889 | val_auroc=0.8297

[Epoch 06] train_loss=0.4475 | val_loss=0.4149 | val_mcc=0.5085 | val_f1=0.6072 | val_auroc=0.8456

[Epoch 07] train_loss=0.4174 | val_loss=0.3992 | val_mcc=0.5115 | val_f1=0.6075 | val_auroc=0.8485

[Epoch 08] train_loss=0.3876 | val_loss=0.4627 | val_mcc=0.5021 | val_f1=0.6039 | val_auroc=0.8525

[Epoch 09] train_loss=0.3579 | val_loss=0.4765 | val_mcc=0.4772 | val_f1=0.5849 | val_auroc=0.8370

[Epoch 10] train_loss=0.3353 | val_loss=0.4846 | val_mcc=0.4957 | val_f1=0.5991 | val_auroc=0.8472

[Epoch 11] train_loss=0.3058 | val_loss=0.4738 | val_mcc=0.4913 | val_f1=0.5958 | val_auroc=0.8439

[Epoch 12] train_loss=0.2714 | val_loss=0.4995 | val_mcc=0.4916 | val_f1=0.5960 | val_auroc=0.8474

[Epoch 13] train_loss=0.2528 | val_loss=0.5221 | val_mcc=0.4927 | val_f1=0.5968 | val_auroc=0.8462
[EarlyStop] epoch=13 | best_val_mcc=0.5115
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5334 | F1=0.6541 | AUROC=0.8469 | AUPRC=0.7114
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.4958 | F1=0.7143 | AUROC=0.8288 | AUPRC=0.8161
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3599 | F1=0.6452 | AUROC=0.7249 | AUPRC=0.7068
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4964 | F1=0.7043 | AUROC=0.8052 | AUPRC=0.7846
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.6329 | val_loss=0.5461 | val_mcc=0.3992 | val_f1=0.5259 | val_auroc=0.7774

[Epoch 02] train_loss=0.5560 | val_loss=0.5131 | val_mcc=0.4351 | val_f1=0.5520 | val_auroc=0.7933

[Epoch 03] train_loss=0.5284 | val_loss=0.5316 | val_mcc=0.4425 | val_f1=0.5586 | val_auroc=0.8086

[Epoch 04] train_loss=0.5047 | val_loss=0.4172 | val_mcc=0.4746 | val_f1=0.5690 | val_auroc=0.8207

[Epoch 05] train_loss=0.4841 | val_loss=0.4265 | val_mcc=0.4917 | val_f1=0.5901 | val_auroc=0.8314

[Epoch 06] train_loss=0.4661 | val_loss=0.4487 | val_mcc=0.4894 | val_f1=0.5925 | val_auroc=0.8378

[Epoch 07] train_loss=0.4412 | val_loss=0.4445 | val_mcc=0.5005 | val_f1=0.6014 | val_auroc=0.8419

[Epoch 08] train_loss=0.4145 | val_loss=0.6002 | val_mcc=0.4523 | val_f1=0.5615 | val_auroc=0.8378

[Epoch 09] train_loss=0.3946 | val_loss=0.4281 | val_mcc=0.5043 | val_f1=0.6020 | val_auroc=0.8427

[Epoch 10] train_loss=0.3668 | val_loss=0.4636 | val_mcc=0.4972 | val_f1=0.5992 | val_auroc=0.8407

[Epoch 11] train_loss=0.3444 | val_loss=0.5951 | val_mcc=0.4706 | val_f1=0.5775 | val_auroc=0.8399

[Epoch 12] train_loss=0.3225 | val_loss=0.5649 | val_mcc=0.4821 | val_f1=0.5885 | val_auroc=0.8418

[Epoch 13] train_loss=0.3009 | val_loss=0.5876 | val_mcc=0.4841 | val_f1=0.5900 | val_auroc=0.8361

[Epoch 14] train_loss=0.2673 | val_loss=0.5501 | val_mcc=0.4942 | val_f1=0.5972 | val_auroc=0.8353

[Epoch 15] train_loss=0.2520 | val_loss=0.6030 | val_mcc=0.4833 | val_f1=0.5896 | val_auroc=0.8297
[EarlyStop] epoch=15 | best_val_mcc=0.5043
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5399 | F1=0.6571 | AUROC=0.8425 | AUPRC=0.7002
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.4852 | F1=0.7061 | AUROC=0.8206 | AUPRC=0.8116
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3617 | F1=0.6509 | AUROC=0.7164 | AUPRC=0.6838
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.4919 | F1=0.6957 | AUROC=0.8048 | AUPRC=0.7815
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.6308 | val_loss=0.4814 | val_mcc=0.3993 | val_f1=0.5177 | val_auroc=0.7730

[Epoch 02] train_loss=0.5574 | val_loss=0.4732 | val_mcc=0.4325 | val_f1=0.5449 | val_auroc=0.7976

[Epoch 03] train_loss=0.5269 | val_loss=0.4609 | val_mcc=0.4559 | val_f1=0.5650 | val_auroc=0.8148

[Epoch 04] train_loss=0.5051 | val_loss=0.4255 | val_mcc=0.4746 | val_f1=0.5754 | val_auroc=0.8262

[Epoch 05] train_loss=0.4793 | val_loss=0.4104 | val_mcc=0.4983 | val_f1=0.5968 | val_auroc=0.8383

[Epoch 06] train_loss=0.4575 | val_loss=0.4595 | val_mcc=0.4928 | val_f1=0.5969 | val_auroc=0.8472

[Epoch 07] train_loss=0.4290 | val_loss=0.3689 | val_mcc=0.5205 | val_f1=0.6057 | val_auroc=0.8526

[Epoch 08] train_loss=0.3976 | val_loss=0.4308 | val_mcc=0.5130 | val_f1=0.6105 | val_auroc=0.8517

[Epoch 09] train_loss=0.3682 | val_loss=0.4552 | val_mcc=0.5054 | val_f1=0.6064 | val_auroc=0.8529

[Epoch 10] train_loss=0.3387 | val_loss=0.5227 | val_mcc=0.4945 | val_f1=0.5978 | val_auroc=0.8507

[Epoch 11] train_loss=0.3137 | val_loss=0.4485 | val_mcc=0.5091 | val_f1=0.6058 | val_auroc=0.8444

[Epoch 12] train_loss=0.2753 | val_loss=0.5433 | val_mcc=0.5005 | val_f1=0.6027 | val_auroc=0.8411

[Epoch 13] train_loss=0.2571 | val_loss=0.5381 | val_mcc=0.5005 | val_f1=0.6027 | val_auroc=0.8403
[EarlyStop] epoch=13 | best_val_mcc=0.5205
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5364 | F1=0.6393 | AUROC=0.8508 | AUPRC=0.7281
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.4872 | F1=0.6910 | AUROC=0.8309 | AUPRC=0.8247
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3463 | F1=0.6126 | AUROC=0.7314 | AUPRC=0.7086
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.4754 | F1=0.6638 | AUROC=0.8091 | AUPRC=0.7944
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.6263 | val_loss=0.5590 | val_mcc=0.3896 | val_f1=0.5189 | val_auroc=0.7713

[Epoch 02] train_loss=0.5564 | val_loss=0.4659 | val_mcc=0.4325 | val_f1=0.5439 | val_auroc=0.7946

[Epoch 03] train_loss=0.5267 | val_loss=0.4368 | val_mcc=0.4595 | val_f1=0.5611 | val_auroc=0.8074

[Epoch 04] train_loss=0.5037 | val_loss=0.4415 | val_mcc=0.4681 | val_f1=0.5734 | val_auroc=0.8201

[Epoch 05] train_loss=0.4811 | val_loss=0.4315 | val_mcc=0.4911 | val_f1=0.5921 | val_auroc=0.8311

[Epoch 06] train_loss=0.4528 | val_loss=0.4391 | val_mcc=0.4990 | val_f1=0.6008 | val_auroc=0.8403

[Epoch 07] train_loss=0.4229 | val_loss=0.4262 | val_mcc=0.5031 | val_f1=0.6034 | val_auroc=0.8427

[Epoch 08] train_loss=0.3899 | val_loss=0.5018 | val_mcc=0.4762 | val_f1=0.5832 | val_auroc=0.8443

[Epoch 09] train_loss=0.3603 | val_loss=0.4836 | val_mcc=0.4879 | val_f1=0.5926 | val_auroc=0.8506

[Epoch 10] train_loss=0.3318 | val_loss=0.4908 | val_mcc=0.4867 | val_f1=0.5919 | val_auroc=0.8504

[Epoch 11] train_loss=0.2950 | val_loss=0.5705 | val_mcc=0.4682 | val_f1=0.5762 | val_auroc=0.8461

[Epoch 12] train_loss=0.2599 | val_loss=0.5282 | val_mcc=0.4798 | val_f1=0.5869 | val_auroc=0.8442

[Epoch 13] train_loss=0.2370 | val_loss=0.5579 | val_mcc=0.4756 | val_f1=0.5832 | val_auroc=0.8459
[EarlyStop] epoch=13 | best_val_mcc=0.5031
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5376 | F1=0.6628 | AUROC=0.8450 | AUPRC=0.7169
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.4766 | F1=0.7167 | AUROC=0.8193 | AUPRC=0.8090
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3532 | F1=0.6582 | AUROC=0.7271 | AUPRC=0.7058
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.4846 | F1=0.7040 | AUROC=0.8081 | AUPRC=0.7864
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 139.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.4937 | F1=0.6411 | AUROC=0.8407 | AUPRC=0.7091
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.4651 | F1=0.7283 | AUROC=0.8165 | AUPRC=0.8150
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3594 | F1=0.6801 | AUROC=0.7376 | AUPRC=0.7251
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4364 | F1=0.6948 | AUROC=0.7885 | AUPRC=0.7661
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 156.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.4879 | F1=0.6350 | AUROC=0.8378 | AUPRC=0.7060
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4742 | F1=0.7259 | AUROC=0.8151 | AUPRC=0.8090
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3703 | F1=0.6744 | AUROC=0.7283 | AUPRC=0.7071
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4440 | F1=0.6920 | AUROC=0.7883 | AUPRC=0.7611
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 168.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.4728 | F1=0.6225 | AUROC=0.8229 | AUPRC=0.6874
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4632 | F1=0.7175 | AUROC=0.8025 | AUPRC=0.7923
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3530 | F1=0.6598 | AUROC=0.7162 | AUPRC=0.6873
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4365 | F1=0.6846 | AUROC=0.7725 | AUPRC=0.7498
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 139.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.4731 | F1=0.6224 | AUROC=0.8240 | AUPRC=0.6862
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4568 | F1=0.7187 | AUROC=0.8073 | AUPRC=0.7946
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3254 | F1=0.6495 | AUROC=0.7138 | AUPRC=0.6918
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4411 | val_loss=0.2573 | val_mcc=0.7001 | val_f1=0.7573 | val_auroc=0.9541

[Epoch 02] train_loss=0.3331 | val_loss=0.2498 | val_mcc=0.7160 | val_f1=0.7701 | val_auroc=0.9567

[Epoch 03] train_loss=0.3108 | val_loss=0.2192 | val_mcc=0.7241 | val_f1=0.7781 | val_auroc=0.9560

[Epoch 04] train_loss=0.3005 | val_loss=0.2315 | val_mcc=0.7249 | val_f1=0.7785 | val_auroc=0.9574

[Epoch 05] train_loss=0.2869 | val_loss=0.2250 | val_mcc=0.7368 | val_f1=0.7884 | val_auroc=0.9555

[Epoch 06] train_loss=0.2789 | val_loss=0.2245 | val_mcc=0.7332 | val_f1=0.7853 | val_auroc=0.9596

[Epoch 07] train_loss=0.2646 | val_loss=0.2277 | val_mcc=0.7342 | val_f1=0.7860 | val_auroc=0.9596

[Epoch 08] train_loss=0.2551 | val_loss=0.2110 | val_mcc=0.7452 | val_f1=0.7948 | val_auroc=0.9591

[Epoch 09] train_loss=0.2427 | val_loss=0.2219 | val_mcc=0.7391 | val_f1=0.7901 | val_auroc=0.9585

[Epoch 10] train_loss=0.2288 | val_loss=0.2329 | val_mcc=0.7226 | val_f1=0.7770 | val_auroc=0.9569

[Epoch 11] train_loss=0.2144 | val_loss=0.2084 | val_mcc=0.7503 | val_f1=0.7983 | val_auroc=0.9590

[Epoch 12] train_loss=0.1975 | val_loss=0.2518 | val_mcc=0.7281 | val_f1=0.7808 | val_auroc=0.9564

[Epoch 13] train_loss=0.1770 | val_loss=0.2349 | val_mcc=0.7394 | val_f1=0.7903 | val_auroc=0.9577

[Epoch 14] train_loss=0.1633 | val_loss=0.2906 | val_mcc=0.7032 | val_f1=0.7586 | val_auroc=0.9556

[Epoch 15] train_loss=0.1485 | val_loss=0.2575 | val_mcc=0.7216 | val_f1=0.7761 | val_auroc=0.9520

[Epoch 16] train_loss=0.1255 | val_loss=0.2807 | val_mcc=0.7176 | val_f1=0.7728 | val_auroc=0.9524

[Epoch 17] train_loss=0.1171 | val_loss=0.3447 | val_mcc=0.6848 | val_f1=0.7432 | val_auroc=0.9497
[EarlyStop] epoch=17 | best_val_mcc=0.7503
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7337 | F1=0.8060 | AUROC=0.9441 | AUPRC=0.8770
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7763 | F1=0.8719 | AUROC=0.9604 | AUPRC=0.9573
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4074 | F1=0.6996 | AUROC=0.7474 | AUPRC=0.7183
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5658 | F1=0.7780 | AUROC=0.8652 | AUPRC=0.8334
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4399 | val_loss=0.2165 | val_mcc=0.7269 | val_f1=0.7776 | val_auroc=0.9546

[Epoch 02] train_loss=0.3362 | val_loss=0.2264 | val_mcc=0.7326 | val_f1=0.7849 | val_auroc=0.9572

[Epoch 03] train_loss=0.3138 | val_loss=0.2799 | val_mcc=0.6971 | val_f1=0.7518 | val_auroc=0.9564

[Epoch 04] train_loss=0.3016 | val_loss=0.2495 | val_mcc=0.7207 | val_f1=0.7734 | val_auroc=0.9580

[Epoch 05] train_loss=0.2878 | val_loss=0.2193 | val_mcc=0.7328 | val_f1=0.7852 | val_auroc=0.9580

[Epoch 06] train_loss=0.2800 | val_loss=0.2919 | val_mcc=0.6891 | val_f1=0.7443 | val_auroc=0.9568

[Epoch 07] train_loss=0.2666 | val_loss=0.2453 | val_mcc=0.7194 | val_f1=0.7732 | val_auroc=0.9578

[Epoch 08] train_loss=0.2547 | val_loss=0.2305 | val_mcc=0.7263 | val_f1=0.7800 | val_auroc=0.9552

[Epoch 09] train_loss=0.2499 | val_loss=0.2419 | val_mcc=0.7245 | val_f1=0.7783 | val_auroc=0.9546

[Epoch 10] train_loss=0.2300 | val_loss=0.2576 | val_mcc=0.7123 | val_f1=0.7677 | val_auroc=0.9542

[Epoch 11] train_loss=0.2218 | val_loss=0.2545 | val_mcc=0.7163 | val_f1=0.7714 | val_auroc=0.9535
[EarlyStop] epoch=11 | best_val_mcc=0.7328
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7302 | F1=0.8058 | AUROC=0.9423 | AUPRC=0.8743
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7903 | F1=0.8865 | AUROC=0.9604 | AUPRC=0.9619
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3888 | F1=0.7026 | AUROC=0.7452 | AUPRC=0.7155
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5353 | F1=0.7663 | AUROC=0.8528 | AUPRC=0.8142
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4487 | val_loss=0.2205 | val_mcc=0.7101 | val_f1=0.7620 | val_auroc=0.9511

[Epoch 02] train_loss=0.3379 | val_loss=0.2248 | val_mcc=0.7120 | val_f1=0.7684 | val_auroc=0.9521

[Epoch 03] train_loss=0.3100 | val_loss=0.2594 | val_mcc=0.7078 | val_f1=0.7621 | val_auroc=0.9581

[Epoch 04] train_loss=0.3032 | val_loss=0.2498 | val_mcc=0.7213 | val_f1=0.7745 | val_auroc=0.9584

[Epoch 05] train_loss=0.2893 | val_loss=0.2100 | val_mcc=0.7373 | val_f1=0.7870 | val_auroc=0.9573

[Epoch 06] train_loss=0.2825 | val_loss=0.2032 | val_mcc=0.7451 | val_f1=0.7931 | val_auroc=0.9592

[Epoch 07] train_loss=0.2691 | val_loss=0.1977 | val_mcc=0.7582 | val_f1=0.8038 | val_auroc=0.9614

[Epoch 08] train_loss=0.2552 | val_loss=0.2416 | val_mcc=0.7181 | val_f1=0.7721 | val_auroc=0.9598

[Epoch 09] train_loss=0.2426 | val_loss=0.2317 | val_mcc=0.7378 | val_f1=0.7889 | val_auroc=0.9592

[Epoch 10] train_loss=0.2264 | val_loss=0.2142 | val_mcc=0.7408 | val_f1=0.7911 | val_auroc=0.9587

[Epoch 11] train_loss=0.2093 | val_loss=0.2232 | val_mcc=0.7435 | val_f1=0.7937 | val_auroc=0.9598

[Epoch 12] train_loss=0.1865 | val_loss=0.2335 | val_mcc=0.7380 | val_f1=0.7892 | val_auroc=0.9556

[Epoch 13] train_loss=0.1745 | val_loss=0.2542 | val_mcc=0.7297 | val_f1=0.7825 | val_auroc=0.9537
[EarlyStop] epoch=13 | best_val_mcc=0.7582
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7368 | F1=0.8067 | AUROC=0.9462 | AUPRC=0.8834
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7803 | F1=0.8728 | AUROC=0.9641 | AUPRC=0.9663
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3911 | F1=0.6877 | AUROC=0.7461 | AUPRC=0.7171
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5658 | F1=0.7780 | AUROC=0.8632 | AUPRC=0.8307
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4329 | val_loss=0.2233 | val_mcc=0.7129 | val_f1=0.7693 | val_auroc=0.9543

[Epoch 02] train_loss=0.3246 | val_loss=0.2385 | val_mcc=0.7179 | val_f1=0.7725 | val_auroc=0.9555

[Epoch 03] train_loss=0.3057 | val_loss=0.2201 | val_mcc=0.7304 | val_f1=0.7833 | val_auroc=0.9585

[Epoch 04] train_loss=0.2934 | val_loss=0.2311 | val_mcc=0.7243 | val_f1=0.7778 | val_auroc=0.9584

[Epoch 05] train_loss=0.2797 | val_loss=0.2572 | val_mcc=0.7141 | val_f1=0.7676 | val_auroc=0.9585

[Epoch 06] train_loss=0.2716 | val_loss=0.2247 | val_mcc=0.7366 | val_f1=0.7880 | val_auroc=0.9595

[Epoch 07] train_loss=0.2596 | val_loss=0.2295 | val_mcc=0.7351 | val_f1=0.7865 | val_auroc=0.9595

[Epoch 08] train_loss=0.2444 | val_loss=0.2288 | val_mcc=0.7289 | val_f1=0.7817 | val_auroc=0.9597

[Epoch 09] train_loss=0.2327 | val_loss=0.2241 | val_mcc=0.7375 | val_f1=0.7886 | val_auroc=0.9603

[Epoch 10] train_loss=0.2136 | val_loss=0.2417 | val_mcc=0.7299 | val_f1=0.7815 | val_auroc=0.9604

[Epoch 11] train_loss=0.1972 | val_loss=0.2485 | val_mcc=0.7182 | val_f1=0.7730 | val_auroc=0.9566

[Epoch 12] train_loss=0.1784 | val_loss=0.2655 | val_mcc=0.7245 | val_f1=0.7770 | val_auroc=0.9578

[Epoch 13] train_loss=0.1581 | val_loss=0.2505 | val_mcc=0.7326 | val_f1=0.7849 | val_auroc=0.9558

[Epoch 14] train_loss=0.1340 | val_loss=0.2987 | val_mcc=0.7149 | val_f1=0.7688 | val_auroc=0.9543

[Epoch 15] train_loss=0.1238 | val_loss=0.3031 | val_mcc=0.7108 | val_f1=0.7653 | val_auroc=0.9547
[EarlyStop] epoch=15 | best_val_mcc=0.7375
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7295 | F1=0.8056 | AUROC=0.9441 | AUPRC=0.8810
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8150 | F1=0.9009 | AUROC=0.9640 | AUPRC=0.9588
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4059 | F1=0.7169 | AUROC=0.7528 | AUPRC=0.7196
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5140 | F1=0.7569 | AUROC=0.8608 | AUPRC=0.8321
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 196.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7490 | F1=0.8195 | AUROC=0.9580 | AUPRC=0.9052
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8597 | F1=0.9256 | AUROC=0.9836 | AUPRC=0.9839
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4015 | F1=0.7181 | AUROC=0.7677 | AUPRC=0.7440
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5400 | F1=0.7684 | AUROC=0.8810 | AUPRC=0.8556
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 140.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7349 | F1=0.8095 | AUROC=0.9486 | AUPRC=0.8876
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8390 | F1=0.9158 | AUROC=0.9712 | AUPRC=0.9697
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4099 | F1=0.7207 | AUROC=0.7660 | AUPRC=0.7393
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5444 | F1=0.7704 | AUROC=0.8658 | AUPRC=0.8281
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 127.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7243 | F1=0.8020 | AUROC=0.9471 | AUPRC=0.8863
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8422 | F1=0.9169 | AUROC=0.9710 | AUPRC=0.9707
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3659 | F1=0.7001 | AUROC=0.7473 | AUPRC=0.7177
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5137 | F1=0.7569 | AUROC=0.8601 | AUPRC=0.8200
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 122.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7339 | F1=0.8088 | AUROC=0.9462 | AUPRC=0.8837
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8063 | F1=0.8966 | AUROC=0.9701 | AUPRC=0.9698
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.6387 | val_loss=0.5278 | val_mcc=0.4494 | val_f1=0.5603 | val_auroc=0.7905

[Epoch 02] train_loss=0.5396 | val_loss=0.4572 | val_mcc=0.5028 | val_f1=0.5926 | val_auroc=0.8082

[Epoch 03] train_loss=0.5160 | val_loss=0.4471 | val_mcc=0.5230 | val_f1=0.6087 | val_auroc=0.8130

[Epoch 04] train_loss=0.5056 | val_loss=0.4979 | val_mcc=0.5117 | val_f1=0.6104 | val_auroc=0.8168

[Epoch 05] train_loss=0.4940 | val_loss=0.4734 | val_mcc=0.5131 | val_f1=0.6096 | val_auroc=0.8182

[Epoch 06] train_loss=0.4861 | val_loss=0.4650 | val_mcc=0.5013 | val_f1=0.6016 | val_auroc=0.8145

[Epoch 07] train_loss=0.4753 | val_loss=0.4327 | val_mcc=0.5339 | val_f1=0.6228 | val_auroc=0.8305

[Epoch 08] train_loss=0.4682 | val_loss=0.4849 | val_mcc=0.5088 | val_f1=0.6090 | val_auroc=0.8345

[Epoch 09] train_loss=0.4592 | val_loss=0.4384 | val_mcc=0.5278 | val_f1=0.6218 | val_auroc=0.8304

[Epoch 10] train_loss=0.4479 | val_loss=0.4142 | val_mcc=0.5405 | val_f1=0.6298 | val_auroc=0.8388

[Epoch 11] train_loss=0.4389 | val_loss=0.4322 | val_mcc=0.5215 | val_f1=0.6184 | val_auroc=0.8441

[Epoch 12] train_loss=0.4330 | val_loss=0.4972 | val_mcc=0.4958 | val_f1=0.5987 | val_auroc=0.8467

[Epoch 13] train_loss=0.4206 | val_loss=0.4115 | val_mcc=0.5368 | val_f1=0.6300 | val_auroc=0.8484

[Epoch 14] train_loss=0.4137 | val_loss=0.4156 | val_mcc=0.5427 | val_f1=0.6339 | val_auroc=0.8453

[Epoch 15] train_loss=0.4028 | val_loss=0.4143 | val_mcc=0.5366 | val_f1=0.6303 | val_auroc=0.8494

[Epoch 16] train_loss=0.3946 | val_loss=0.4486 | val_mcc=0.5198 | val_f1=0.6170 | val_auroc=0.8461

[Epoch 17] train_loss=0.3865 | val_loss=0.4247 | val_mcc=0.5321 | val_f1=0.6268 | val_auroc=0.8475

[Epoch 18] train_loss=0.3770 | val_loss=0.5011 | val_mcc=0.4924 | val_f1=0.5952 | val_auroc=0.8486

[Epoch 19] train_loss=0.3587 | val_loss=0.4359 | val_mcc=0.5243 | val_f1=0.6211 | val_auroc=0.8462

[Epoch 20] train_loss=0.3525 | val_loss=0.4549 | val_mcc=0.5137 | val_f1=0.6130 | val_auroc=0.8461
[EarlyStop] epoch=20 | best_val_mcc=0.5427
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5830 | F1=0.6959 | AUROC=0.8488 | AUPRC=0.7590
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5564 | F1=0.7539 | AUROC=0.8214 | AUPRC=0.8451
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3696 | F1=0.6602 | AUROC=0.7274 | AUPRC=0.7426
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5206 | F1=0.7263 | AUROC=0.8164 | AUPRC=0.8168
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.6309 | val_loss=0.4986 | val_mcc=0.4722 | val_f1=0.5770 | val_auroc=0.7995

[Epoch 02] train_loss=0.5334 | val_loss=0.5334 | val_mcc=0.4768 | val_f1=0.5846 | val_auroc=0.8113

[Epoch 03] train_loss=0.5151 | val_loss=0.5175 | val_mcc=0.5017 | val_f1=0.6033 | val_auroc=0.8173

[Epoch 04] train_loss=0.4998 | val_loss=0.4321 | val_mcc=0.5313 | val_f1=0.6183 | val_auroc=0.8296

[Epoch 05] train_loss=0.4873 | val_loss=0.4522 | val_mcc=0.5281 | val_f1=0.6225 | val_auroc=0.8346

[Epoch 06] train_loss=0.4796 | val_loss=0.4561 | val_mcc=0.5237 | val_f1=0.6197 | val_auroc=0.8409

[Epoch 07] train_loss=0.4740 | val_loss=0.4435 | val_mcc=0.5267 | val_f1=0.6217 | val_auroc=0.8367

[Epoch 08] train_loss=0.4714 | val_loss=0.5034 | val_mcc=0.4948 | val_f1=0.5975 | val_auroc=0.8360

[Epoch 09] train_loss=0.4575 | val_loss=0.4373 | val_mcc=0.5308 | val_f1=0.6256 | val_auroc=0.8450

[Epoch 10] train_loss=0.4546 | val_loss=0.4085 | val_mcc=0.5405 | val_f1=0.6316 | val_auroc=0.8436

[Epoch 11] train_loss=0.4517 | val_loss=0.3777 | val_mcc=0.5510 | val_f1=0.6354 | val_auroc=0.8447

[Epoch 12] train_loss=0.4460 | val_loss=0.4025 | val_mcc=0.5462 | val_f1=0.6343 | val_auroc=0.8437

[Epoch 13] train_loss=0.4490 | val_loss=0.3856 | val_mcc=0.5497 | val_f1=0.6374 | val_auroc=0.8455

[Epoch 14] train_loss=0.4404 | val_loss=0.4875 | val_mcc=0.4965 | val_f1=0.5994 | val_auroc=0.8433

[Epoch 15] train_loss=0.4354 | val_loss=0.3686 | val_mcc=0.5513 | val_f1=0.6354 | val_auroc=0.8442

[Epoch 16] train_loss=0.4357 | val_loss=0.4039 | val_mcc=0.5408 | val_f1=0.6318 | val_auroc=0.8394

[Epoch 17] train_loss=0.4296 | val_loss=0.3928 | val_mcc=0.5389 | val_f1=0.6292 | val_auroc=0.8412

[Epoch 18] train_loss=0.4278 | val_loss=0.4516 | val_mcc=0.5183 | val_f1=0.6163 | val_auroc=0.8399

[Epoch 19] train_loss=0.4244 | val_loss=0.4171 | val_mcc=0.5313 | val_f1=0.6247 | val_auroc=0.8387

[Epoch 20] train_loss=0.4175 | val_loss=0.4215 | val_mcc=0.5356 | val_f1=0.6286 | val_auroc=0.8379

[Epoch 21] train_loss=0.4144 | val_loss=0.4215 | val_mcc=0.5353 | val_f1=0.6284 | val_auroc=0.8376
[EarlyStop] epoch=21 | best_val_mcc=0.5513
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5684 | F1=0.6757 | AUROC=0.8442 | AUPRC=0.7455
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5204 | F1=0.7138 | AUROC=0.8181 | AUPRC=0.8346
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3649 | F1=0.6318 | AUROC=0.7235 | AUPRC=0.7350
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5181 | F1=0.7080 | AUROC=0.8069 | AUPRC=0.8077
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.6329 | val_loss=0.4404 | val_mcc=0.4826 | val_f1=0.5668 | val_auroc=0.7898

[Epoch 02] train_loss=0.5399 | val_loss=0.4051 | val_mcc=0.5213 | val_f1=0.5855 | val_auroc=0.8095

[Epoch 03] train_loss=0.5162 | val_loss=0.4527 | val_mcc=0.5235 | val_f1=0.6143 | val_auroc=0.8155

[Epoch 04] train_loss=0.4998 | val_loss=0.4290 | val_mcc=0.5329 | val_f1=0.6218 | val_auroc=0.8226

[Epoch 05] train_loss=0.4901 | val_loss=0.4101 | val_mcc=0.5382 | val_f1=0.6240 | val_auroc=0.8341

[Epoch 06] train_loss=0.4803 | val_loss=0.3938 | val_mcc=0.5424 | val_f1=0.6269 | val_auroc=0.8427

[Epoch 07] train_loss=0.4695 | val_loss=0.3665 | val_mcc=0.5439 | val_f1=0.6267 | val_auroc=0.8416

[Epoch 08] train_loss=0.4736 | val_loss=0.3767 | val_mcc=0.5467 | val_f1=0.6295 | val_auroc=0.8453

[Epoch 09] train_loss=0.4609 | val_loss=0.3791 | val_mcc=0.5496 | val_f1=0.6366 | val_auroc=0.8478

[Epoch 10] train_loss=0.4538 | val_loss=0.3647 | val_mcc=0.5498 | val_f1=0.6349 | val_auroc=0.8478

[Epoch 11] train_loss=0.4460 | val_loss=0.4772 | val_mcc=0.5118 | val_f1=0.6115 | val_auroc=0.8495

[Epoch 12] train_loss=0.4366 | val_loss=0.4396 | val_mcc=0.5048 | val_f1=0.6061 | val_auroc=0.8450

[Epoch 13] train_loss=0.4330 | val_loss=0.3635 | val_mcc=0.5524 | val_f1=0.6356 | val_auroc=0.8447

[Epoch 14] train_loss=0.4206 | val_loss=0.4252 | val_mcc=0.5255 | val_f1=0.6216 | val_auroc=0.8471

[Epoch 15] train_loss=0.4119 | val_loss=0.4487 | val_mcc=0.5164 | val_f1=0.6151 | val_auroc=0.8476

[Epoch 16] train_loss=0.4029 | val_loss=0.4023 | val_mcc=0.5414 | val_f1=0.6320 | val_auroc=0.8386

[Epoch 17] train_loss=0.3957 | val_loss=0.3757 | val_mcc=0.5364 | val_f1=0.6157 | val_auroc=0.8202

[Epoch 18] train_loss=0.3814 | val_loss=0.4415 | val_mcc=0.5248 | val_f1=0.6214 | val_auroc=0.8423

[Epoch 19] train_loss=0.3707 | val_loss=0.4285 | val_mcc=0.5300 | val_f1=0.6245 | val_auroc=0.8424
[EarlyStop] epoch=19 | best_val_mcc=0.5524
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5816 | F1=0.6858 | AUROC=0.8451 | AUPRC=0.7536
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5255 | F1=0.7180 | AUROC=0.8214 | AUPRC=0.8371
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3622 | F1=0.6338 | AUROC=0.7244 | AUPRC=0.7382
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5261 | F1=0.7144 | AUROC=0.8129 | AUPRC=0.8125
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.6428 | val_loss=0.4915 | val_mcc=0.4535 | val_f1=0.5557 | val_auroc=0.7832

[Epoch 02] train_loss=0.5386 | val_loss=0.4927 | val_mcc=0.4899 | val_f1=0.5917 | val_auroc=0.8091

[Epoch 03] train_loss=0.5136 | val_loss=0.4138 | val_mcc=0.5198 | val_f1=0.5995 | val_auroc=0.8135

[Epoch 04] train_loss=0.5000 | val_loss=0.4426 | val_mcc=0.5210 | val_f1=0.6133 | val_auroc=0.8195

[Epoch 05] train_loss=0.4867 | val_loss=0.4104 | val_mcc=0.5299 | val_f1=0.6169 | val_auroc=0.8255

[Epoch 06] train_loss=0.4798 | val_loss=0.4336 | val_mcc=0.5273 | val_f1=0.6163 | val_auroc=0.8204

[Epoch 07] train_loss=0.4678 | val_loss=0.4025 | val_mcc=0.5366 | val_f1=0.6250 | val_auroc=0.8349

[Epoch 08] train_loss=0.4629 | val_loss=0.4418 | val_mcc=0.5189 | val_f1=0.6164 | val_auroc=0.8382

[Epoch 09] train_loss=0.4515 | val_loss=0.4351 | val_mcc=0.5116 | val_f1=0.6112 | val_auroc=0.8386

[Epoch 10] train_loss=0.4421 | val_loss=0.4353 | val_mcc=0.5255 | val_f1=0.6217 | val_auroc=0.8424

[Epoch 11] train_loss=0.4334 | val_loss=0.3977 | val_mcc=0.5397 | val_f1=0.6306 | val_auroc=0.8468

[Epoch 12] train_loss=0.4244 | val_loss=0.4313 | val_mcc=0.5273 | val_f1=0.6234 | val_auroc=0.8485

[Epoch 13] train_loss=0.4149 | val_loss=0.3908 | val_mcc=0.5422 | val_f1=0.6336 | val_auroc=0.8502

[Epoch 14] train_loss=0.4013 | val_loss=0.4072 | val_mcc=0.5348 | val_f1=0.6288 | val_auroc=0.8521

[Epoch 15] train_loss=0.3943 | val_loss=0.4468 | val_mcc=0.5155 | val_f1=0.6144 | val_auroc=0.8501

[Epoch 16] train_loss=0.3835 | val_loss=0.4983 | val_mcc=0.4892 | val_f1=0.5929 | val_auroc=0.8489

[Epoch 17] train_loss=0.3716 | val_loss=0.5198 | val_mcc=0.4844 | val_f1=0.5885 | val_auroc=0.8506

[Epoch 18] train_loss=0.3550 | val_loss=0.4584 | val_mcc=0.5074 | val_f1=0.6080 | val_auroc=0.8502

[Epoch 19] train_loss=0.3471 | val_loss=0.4510 | val_mcc=0.5146 | val_f1=0.6137 | val_auroc=0.8478
[EarlyStop] epoch=19 | best_val_mcc=0.5422
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5768 | F1=0.6915 | AUROC=0.8526 | AUPRC=0.7639
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5240 | F1=0.7380 | AUROC=0.8212 | AUPRC=0.8397
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3545 | F1=0.6522 | AUROC=0.7307 | AUPRC=0.7432
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5206 | F1=0.7263 | AUROC=0.8130 | AUPRC=0.8125
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 383.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5583 | F1=0.6848 | AUROC=0.8742 | AUPRC=0.7785
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.4709 | F1=0.7281 | AUROC=0.8460 | AUPRC=0.8534
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3308 | F1=0.6652 | AUROC=0.7412 | AUPRC=0.7503
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4783 | F1=0.7163 | AUROC=0.8271 | AUPRC=0.8146
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 121.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5489 | F1=0.6763 | AUROC=0.8532 | AUPRC=0.7577
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5330 | F1=0.7496 | AUROC=0.8204 | AUPRC=0.8388
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3539 | F1=0.6651 | AUROC=0.7372 | AUPRC=0.7383
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5028 | F1=0.7220 | AUROC=0.8124 | AUPRC=0.8084
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 54.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5368 | F1=0.6661 | AUROC=0.8454 | AUPRC=0.7541
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5117 | F1=0.7334 | AUROC=0.8200 | AUPRC=0.8370
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3301 | F1=0.6500 | AUROC=0.7266 | AUPRC=0.7288
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4958 | F1=0.7175 | AUROC=0.7996 | AUPRC=0.7998
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 94.
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5295 | F1=0.6628 | AUROC=0.8428 | AUPRC=0.7500
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5107 | F1=0.7359 | AUROC=0.8121 | AUPRC=0.8303
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3317 | F1=0.6499 | AUROC=0.7223 | AUPRC=0.7325
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4459 | val_loss=0.2436 | val_mcc=0.7062 | val_f1=0.7630 | val_auroc=0.9537

[Epoch 02] train_loss=0.3245 | val_loss=0.2717 | val_mcc=0.6876 | val_f1=0.7454 | val_auroc=0.9558

[Epoch 03] train_loss=0.3062 | val_loss=0.2331 | val_mcc=0.7240 | val_f1=0.7777 | val_auroc=0.9557

[Epoch 04] train_loss=0.2958 | val_loss=0.2351 | val_mcc=0.7182 | val_f1=0.7725 | val_auroc=0.9579

[Epoch 05] train_loss=0.2914 | val_loss=0.2142 | val_mcc=0.7377 | val_f1=0.7891 | val_auroc=0.9589

[Epoch 06] train_loss=0.2876 | val_loss=0.2647 | val_mcc=0.7087 | val_f1=0.7620 | val_auroc=0.9590

[Epoch 07] train_loss=0.2836 | val_loss=0.2124 | val_mcc=0.7329 | val_f1=0.7851 | val_auroc=0.9578

[Epoch 08] train_loss=0.2765 | val_loss=0.2188 | val_mcc=0.7339 | val_f1=0.7859 | val_auroc=0.9596

[Epoch 09] train_loss=0.2736 | val_loss=0.2169 | val_mcc=0.7353 | val_f1=0.7871 | val_auroc=0.9605

[Epoch 10] train_loss=0.2685 | val_loss=0.2157 | val_mcc=0.7367 | val_f1=0.7882 | val_auroc=0.9609

[Epoch 11] train_loss=0.2633 | val_loss=0.2267 | val_mcc=0.7318 | val_f1=0.7836 | val_auroc=0.9606
[EarlyStop] epoch=11 | best_val_mcc=0.7377
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7419 | F1=0.8141 | AUROC=0.9487 | AUPRC=0.8885
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7975 | F1=0.8885 | AUROC=0.9676 | AUPRC=0.9580
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4152 | F1=0.7181 | AUROC=0.7629 | AUPRC=0.7467
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5378 | F1=0.7675 | AUROC=0.8648 | AUPRC=0.8456
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4575 | val_loss=0.2257 | val_mcc=0.7238 | val_f1=0.7776 | val_auroc=0.9552

[Epoch 02] train_loss=0.3232 | val_loss=0.2920 | val_mcc=0.6795 | val_f1=0.7359 | val_auroc=0.9576

[Epoch 03] train_loss=0.3083 | val_loss=0.2253 | val_mcc=0.7296 | val_f1=0.7823 | val_auroc=0.9583

[Epoch 04] train_loss=0.3010 | val_loss=0.2157 | val_mcc=0.7321 | val_f1=0.7845 | val_auroc=0.9591

[Epoch 05] train_loss=0.2911 | val_loss=0.2517 | val_mcc=0.7097 | val_f1=0.7639 | val_auroc=0.9592

[Epoch 06] train_loss=0.2846 | val_loss=0.2343 | val_mcc=0.7283 | val_f1=0.7802 | val_auroc=0.9597

[Epoch 07] train_loss=0.2849 | val_loss=0.2139 | val_mcc=0.7389 | val_f1=0.7900 | val_auroc=0.9608

[Epoch 08] train_loss=0.2763 | val_loss=0.2149 | val_mcc=0.7342 | val_f1=0.7860 | val_auroc=0.9619

[Epoch 09] train_loss=0.2735 | val_loss=0.2157 | val_mcc=0.7385 | val_f1=0.7895 | val_auroc=0.9617

[Epoch 10] train_loss=0.2691 | val_loss=0.2237 | val_mcc=0.7345 | val_f1=0.7852 | val_auroc=0.9633

[Epoch 11] train_loss=0.2646 | val_loss=0.2088 | val_mcc=0.7440 | val_f1=0.7939 | val_auroc=0.9638

[Epoch 12] train_loss=0.2598 | val_loss=0.2092 | val_mcc=0.7421 | val_f1=0.7922 | val_auroc=0.9633

[Epoch 13] train_loss=0.2571 | val_loss=0.2378 | val_mcc=0.7252 | val_f1=0.7770 | val_auroc=0.9622

[Epoch 14] train_loss=0.2556 | val_loss=0.2148 | val_mcc=0.7384 | val_f1=0.7889 | val_auroc=0.9639

[Epoch 15] train_loss=0.2517 | val_loss=0.2458 | val_mcc=0.7174 | val_f1=0.7697 | val_auroc=0.9626

[Epoch 16] train_loss=0.2423 | val_loss=0.2373 | val_mcc=0.7263 | val_f1=0.7777 | val_auroc=0.9625

[Epoch 17] train_loss=0.2395 | val_loss=0.2372 | val_mcc=0.7255 | val_f1=0.7767 | val_auroc=0.9628
[EarlyStop] epoch=17 | best_val_mcc=0.7440
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7509 | F1=0.8208 | AUROC=0.9534 | AUPRC=0.9021
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8284 | F1=0.9091 | AUROC=0.9719 | AUPRC=0.9706
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4196 | F1=0.7235 | AUROC=0.7636 | AUPRC=0.7446
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5423 | F1=0.7694 | AUROC=0.8766 | AUPRC=0.8550
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4512 | val_loss=0.3173 | val_mcc=0.6589 | val_f1=0.7171 | val_auroc=0.9530

[Epoch 02] train_loss=0.3270 | val_loss=0.2447 | val_mcc=0.7140 | val_f1=0.7689 | val_auroc=0.9564

[Epoch 03] train_loss=0.3082 | val_loss=0.2398 | val_mcc=0.7176 | val_f1=0.7722 | val_auroc=0.9570

[Epoch 04] train_loss=0.3005 | val_loss=0.2068 | val_mcc=0.7353 | val_f1=0.7870 | val_auroc=0.9590

[Epoch 05] train_loss=0.2950 | val_loss=0.2058 | val_mcc=0.7400 | val_f1=0.7906 | val_auroc=0.9594

[Epoch 06] train_loss=0.2864 | val_loss=0.2275 | val_mcc=0.7302 | val_f1=0.7825 | val_auroc=0.9604

[Epoch 07] train_loss=0.2818 | val_loss=0.2040 | val_mcc=0.7464 | val_f1=0.7956 | val_auroc=0.9601

[Epoch 08] train_loss=0.2799 | val_loss=0.2044 | val_mcc=0.7433 | val_f1=0.7936 | val_auroc=0.9616

[Epoch 09] train_loss=0.2736 | val_loss=0.1907 | val_mcc=0.7512 | val_f1=0.7989 | val_auroc=0.9626

[Epoch 10] train_loss=0.2705 | val_loss=0.2032 | val_mcc=0.7412 | val_f1=0.7918 | val_auroc=0.9614

[Epoch 11] train_loss=0.2658 | val_loss=0.2409 | val_mcc=0.7185 | val_f1=0.7718 | val_auroc=0.9601

[Epoch 12] train_loss=0.2608 | val_loss=0.2195 | val_mcc=0.7408 | val_f1=0.7908 | val_auroc=0.9628

[Epoch 13] train_loss=0.2557 | val_loss=0.2123 | val_mcc=0.7423 | val_f1=0.7927 | val_auroc=0.9617

[Epoch 14] train_loss=0.2475 | val_loss=0.2122 | val_mcc=0.7432 | val_f1=0.7934 | val_auroc=0.9613

[Epoch 15] train_loss=0.2475 | val_loss=0.2218 | val_mcc=0.7344 | val_f1=0.7861 | val_auroc=0.9607
[EarlyStop] epoch=15 | best_val_mcc=0.7512
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7615 | F1=0.8262 | AUROC=0.9522 | AUPRC=0.8998
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7826 | F1=0.8779 | AUROC=0.9684 | AUPRC=0.9662
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4134 | F1=0.7080 | AUROC=0.7623 | AUPRC=0.7440
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5760 | F1=0.7844 | AUROC=0.8744 | AUPRC=0.8498
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4377 | val_loss=0.2467 | val_mcc=0.7084 | val_f1=0.7651 | val_auroc=0.9527

[Epoch 02] train_loss=0.3220 | val_loss=0.2477 | val_mcc=0.7130 | val_f1=0.7679 | val_auroc=0.9563

[Epoch 03] train_loss=0.3041 | val_loss=0.2186 | val_mcc=0.7341 | val_f1=0.7862 | val_auroc=0.9573

[Epoch 04] train_loss=0.2959 | val_loss=0.2377 | val_mcc=0.7208 | val_f1=0.7744 | val_auroc=0.9576

[Epoch 05] train_loss=0.2891 | val_loss=0.2129 | val_mcc=0.7380 | val_f1=0.7893 | val_auroc=0.9589

[Epoch 06] train_loss=0.2823 | val_loss=0.2181 | val_mcc=0.7326 | val_f1=0.7848 | val_auroc=0.9596

[Epoch 07] train_loss=0.2779 | val_loss=0.2122 | val_mcc=0.7388 | val_f1=0.7899 | val_auroc=0.9606

[Epoch 08] train_loss=0.2707 | val_loss=0.1969 | val_mcc=0.7513 | val_f1=0.7993 | val_auroc=0.9610

[Epoch 09] train_loss=0.2681 | val_loss=0.2254 | val_mcc=0.7315 | val_f1=0.7833 | val_auroc=0.9606

[Epoch 10] train_loss=0.2634 | val_loss=0.2079 | val_mcc=0.7432 | val_f1=0.7934 | val_auroc=0.9602

[Epoch 11] train_loss=0.2569 | val_loss=0.2116 | val_mcc=0.7423 | val_f1=0.7927 | val_auroc=0.9604

[Epoch 12] train_loss=0.2539 | val_loss=0.2266 | val_mcc=0.7284 | val_f1=0.7810 | val_auroc=0.9599

[Epoch 13] train_loss=0.2460 | val_loss=0.2313 | val_mcc=0.7317 | val_f1=0.7829 | val_auroc=0.9609

[Epoch 14] train_loss=0.2408 | val_loss=0.2200 | val_mcc=0.7349 | val_f1=0.7865 | val_auroc=0.9605
[EarlyStop] epoch=14 | best_val_mcc=0.7513
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7610 | F1=0.8259 | AUROC=0.9518 | AUPRC=0.8961
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7839 | F1=0.8771 | AUROC=0.9703 | AUPRC=0.9627
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4195 | F1=0.7114 | AUROC=0.7650 | AUPRC=0.7520
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5681 | F1=0.7809 | AUROC=0.8771 | AUPRC=0.8572
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 169.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7739 | F1=0.8371 | AUROC=0.9622 | AUPRC=0.9155
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8620 | F1=0.9274 | AUROC=0.9825 | AUPRC=0.9834
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4100 | F1=0.7233 | AUROC=0.7741 | AUPRC=0.7667
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5319 | F1=0.7647 | AUROC=0.8900 | AUPRC=0.8677
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 107.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7430 | F1=0.8153 | AUROC=0.9516 | AUPRC=0.8939
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8191 | F1=0.9053 | AUROC=0.9678 | AUPRC=0.9660
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4311 | F1=0.7306 | AUROC=0.7681 | AUPRC=0.7561
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5486 | F1=0.7722 | AUROC=0.8723 | AUPRC=0.8472
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 162.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7483 | F1=0.8190 | AUROC=0.9520 | AUPRC=0.8967
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8494 | F1=0.9229 | AUROC=0.9718 | AUPRC=0.9707
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4224 | F1=0.7271 | AUROC=0.7655 | AUPRC=0.7542
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5610 | F1=0.7776 | AUROC=0.8775 | AUPRC=0.8549
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 142.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7501 | F1=0.8202 | AUROC=0.9513 | AUPRC=0.8974
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8216 | F1=0.9072 | AUROC=0.9694 | AUPRC=0.9666
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5828 | val_loss=0.4943 | val_mcc=0.4720 | val_f1=0.5809 | val_auroc=0.8283

[Epoch 02] train_loss=0.4998 | val_loss=0.4571 | val_mcc=0.5114 | val_f1=0.6112 | val_auroc=0.8426

[Epoch 03] train_loss=0.4611 | val_loss=0.4222 | val_mcc=0.5202 | val_f1=0.6180 | val_auroc=0.8534

[Epoch 04] train_loss=0.4242 | val_loss=0.4280 | val_mcc=0.5262 | val_f1=0.6224 | val_auroc=0.8618

[Epoch 05] train_loss=0.3816 | val_loss=0.4081 | val_mcc=0.5398 | val_f1=0.6332 | val_auroc=0.8639

[Epoch 06] train_loss=0.3331 | val_loss=0.4892 | val_mcc=0.5068 | val_f1=0.6054 | val_auroc=0.8642

[Epoch 07] train_loss=0.2830 | val_loss=0.4249 | val_mcc=0.5224 | val_f1=0.6195 | val_auroc=0.8583

[Epoch 08] train_loss=0.2344 | val_loss=0.6362 | val_mcc=0.4665 | val_f1=0.5708 | val_auroc=0.8606

[Epoch 09] train_loss=0.1873 | val_loss=0.5606 | val_mcc=0.4970 | val_f1=0.5994 | val_auroc=0.8544

[Epoch 10] train_loss=0.1332 | val_loss=0.6061 | val_mcc=0.4884 | val_f1=0.5922 | val_auroc=0.8550

[Epoch 11] train_loss=0.1107 | val_loss=0.6053 | val_mcc=0.4955 | val_f1=0.5984 | val_auroc=0.8546
[EarlyStop] epoch=11 | best_val_mcc=0.5398
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5879 | F1=0.7035 | AUROC=0.8777 | AUPRC=0.7676
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6080 | F1=0.7965 | AUROC=0.8728 | AUPRC=0.8714
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3884 | F1=0.6832 | AUROC=0.7528 | AUPRC=0.7222
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5680 | F1=0.7626 | AUROC=0.8586 | AUPRC=0.8373
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5846 | val_loss=0.5415 | val_mcc=0.4665 | val_f1=0.5742 | val_auroc=0.8313

[Epoch 02] train_loss=0.5022 | val_loss=0.4567 | val_mcc=0.5146 | val_f1=0.6136 | val_auroc=0.8489

[Epoch 03] train_loss=0.4652 | val_loss=0.4162 | val_mcc=0.5326 | val_f1=0.6275 | val_auroc=0.8549

[Epoch 04] train_loss=0.4327 | val_loss=0.3856 | val_mcc=0.5490 | val_f1=0.6395 | val_auroc=0.8617

[Epoch 05] train_loss=0.3845 | val_loss=0.5349 | val_mcc=0.4975 | val_f1=0.5968 | val_auroc=0.8600

[Epoch 06] train_loss=0.3407 | val_loss=0.4585 | val_mcc=0.5239 | val_f1=0.6208 | val_auroc=0.8544

[Epoch 07] train_loss=0.2902 | val_loss=0.5715 | val_mcc=0.4794 | val_f1=0.5829 | val_auroc=0.8512

[Epoch 08] train_loss=0.2463 | val_loss=0.6106 | val_mcc=0.4715 | val_f1=0.5782 | val_auroc=0.8476

[Epoch 09] train_loss=0.1834 | val_loss=0.6648 | val_mcc=0.4859 | val_f1=0.5897 | val_auroc=0.8458

[Epoch 10] train_loss=0.1532 | val_loss=0.7473 | val_mcc=0.4849 | val_f1=0.5886 | val_auroc=0.8465
[EarlyStop] epoch=10 | best_val_mcc=0.5490
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5870 | F1=0.6981 | AUROC=0.8743 | AUPRC=0.7501
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5622 | F1=0.7570 | AUROC=0.8638 | AUPRC=0.8525
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3911 | F1=0.6704 | AUROC=0.7499 | AUPRC=0.7287
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5413 | F1=0.7395 | AUROC=0.8570 | AUPRC=0.8271
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5840 | val_loss=0.4664 | val_mcc=0.4985 | val_f1=0.6013 | val_auroc=0.8374

[Epoch 02] train_loss=0.4984 | val_loss=0.3637 | val_mcc=0.5302 | val_f1=0.6176 | val_auroc=0.8522

[Epoch 03] train_loss=0.4601 | val_loss=0.4476 | val_mcc=0.5207 | val_f1=0.6175 | val_auroc=0.8644

[Epoch 04] train_loss=0.4223 | val_loss=0.3804 | val_mcc=0.5593 | val_f1=0.6473 | val_auroc=0.8693

[Epoch 05] train_loss=0.3763 | val_loss=0.3982 | val_mcc=0.5488 | val_f1=0.6402 | val_auroc=0.8705

[Epoch 06] train_loss=0.3366 | val_loss=0.4093 | val_mcc=0.5451 | val_f1=0.6372 | val_auroc=0.8673

[Epoch 07] train_loss=0.2746 | val_loss=0.4488 | val_mcc=0.5339 | val_f1=0.6285 | val_auroc=0.8615

[Epoch 08] train_loss=0.2260 | val_loss=0.4623 | val_mcc=0.5254 | val_f1=0.6200 | val_auroc=0.8519

[Epoch 09] train_loss=0.1613 | val_loss=0.6687 | val_mcc=0.5006 | val_f1=0.6013 | val_auroc=0.8518

[Epoch 10] train_loss=0.1303 | val_loss=0.6589 | val_mcc=0.5058 | val_f1=0.6068 | val_auroc=0.8469
[EarlyStop] epoch=10 | best_val_mcc=0.5593
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5919 | F1=0.7008 | AUROC=0.8801 | AUPRC=0.7710
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5657 | F1=0.7638 | AUROC=0.8660 | AUPRC=0.8647
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3769 | F1=0.6591 | AUROC=0.7460 | AUPRC=0.7265
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5623 | F1=0.7494 | AUROC=0.8610 | AUPRC=0.8334
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5872 | val_loss=0.4284 | val_mcc=0.4958 | val_f1=0.5962 | val_auroc=0.8294

[Epoch 02] train_loss=0.4963 | val_loss=0.4439 | val_mcc=0.5125 | val_f1=0.6120 | val_auroc=0.8465

[Epoch 03] train_loss=0.4554 | val_loss=0.4146 | val_mcc=0.5290 | val_f1=0.6248 | val_auroc=0.8535

[Epoch 04] train_loss=0.4130 | val_loss=0.3854 | val_mcc=0.5429 | val_f1=0.6347 | val_auroc=0.8605

[Epoch 05] train_loss=0.3696 | val_loss=0.4371 | val_mcc=0.5302 | val_f1=0.6249 | val_auroc=0.8644

[Epoch 06] train_loss=0.3162 | val_loss=0.4182 | val_mcc=0.5392 | val_f1=0.6327 | val_auroc=0.8660

[Epoch 07] train_loss=0.2616 | val_loss=0.4542 | val_mcc=0.5287 | val_f1=0.6246 | val_auroc=0.8597

[Epoch 08] train_loss=0.2080 | val_loss=0.5353 | val_mcc=0.5030 | val_f1=0.6040 | val_auroc=0.8514

[Epoch 09] train_loss=0.1467 | val_loss=0.5178 | val_mcc=0.5156 | val_f1=0.6144 | val_auroc=0.8533

[Epoch 10] train_loss=0.1210 | val_loss=0.5573 | val_mcc=0.5060 | val_f1=0.6070 | val_auroc=0.8488
[EarlyStop] epoch=10 | best_val_mcc=0.5429
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5838 | F1=0.6957 | AUROC=0.8724 | AUPRC=0.7656
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5547 | F1=0.7504 | AUROC=0.8614 | AUPRC=0.8592
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3648 | F1=0.6525 | AUROC=0.7464 | AUPRC=0.7261
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5620 | F1=0.7518 | AUROC=0.8521 | AUPRC=0.8307
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 190.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5763 | F1=0.6991 | AUROC=0.8839 | AUPRC=0.7690
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5961 | F1=0.7971 | AUROC=0.8648 | AUPRC=0.8565
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3956 | F1=0.7013 | AUROC=0.7510 | AUPRC=0.7317
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5688 | F1=0.7708 | AUROC=0.8660 | AUPRC=0.8350
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 76.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5592 | F1=0.6851 | AUROC=0.8794 | AUPRC=0.7732
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5591 | F1=0.7744 | AUROC=0.8633 | AUPRC=0.8647
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3565 | F1=0.6708 | AUROC=0.7466 | AUPRC=0.7321
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5499 | F1=0.7561 | AUROC=0.8578 | AUPRC=0.8418
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 47.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5733 | F1=0.6951 | AUROC=0.8738 | AUPRC=0.7697
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5544 | F1=0.7660 | AUROC=0.8663 | AUPRC=0.8600
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3850 | F1=0.6851 | AUROC=0.7511 | AUPRC=0.7322
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5538 | F1=0.7578 | AUROC=0.8533 | AUPRC=0.8306
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 58.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5687 | F1=0.6917 | AUROC=0.8738 | AUPRC=0.7611
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5631 | F1=0.7701 | AUROC=0.8630 | AUPRC=0.8617
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3670 | F1=0.6764 | AUROC=0.7461 | AUPRC=0.7231
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4409 | val_loss=0.2569 | val_mcc=0.7039 | val_f1=0.7609 | val_auroc=0.9517

[Epoch 02] train_loss=0.3131 | val_loss=0.2365 | val_mcc=0.7240 | val_f1=0.7775 | val_auroc=0.9561

[Epoch 03] train_loss=0.2846 | val_loss=0.2577 | val_mcc=0.7040 | val_f1=0.7592 | val_auroc=0.9569

[Epoch 04] train_loss=0.2607 | val_loss=0.2897 | val_mcc=0.6857 | val_f1=0.7423 | val_auroc=0.9559

[Epoch 05] train_loss=0.2381 | val_loss=0.2420 | val_mcc=0.7175 | val_f1=0.7725 | val_auroc=0.9546

[Epoch 06] train_loss=0.2131 | val_loss=0.2434 | val_mcc=0.7180 | val_f1=0.7730 | val_auroc=0.9545

[Epoch 07] train_loss=0.1761 | val_loss=0.2364 | val_mcc=0.7256 | val_f1=0.7795 | val_auroc=0.9547

[Epoch 08] train_loss=0.1563 | val_loss=0.2673 | val_mcc=0.7111 | val_f1=0.7669 | val_auroc=0.9533

[Epoch 09] train_loss=0.1365 | val_loss=0.2935 | val_mcc=0.7009 | val_f1=0.7577 | val_auroc=0.9523

[Epoch 10] train_loss=0.1222 | val_loss=0.2827 | val_mcc=0.7121 | val_f1=0.7682 | val_auroc=0.9512

[Epoch 11] train_loss=0.1061 | val_loss=0.3127 | val_mcc=0.6971 | val_f1=0.7551 | val_auroc=0.9508

[Epoch 12] train_loss=0.0897 | val_loss=0.3045 | val_mcc=0.7037 | val_f1=0.7611 | val_auroc=0.9502

[Epoch 13] train_loss=0.0780 | val_loss=0.3158 | val_mcc=0.7027 | val_f1=0.7602 | val_auroc=0.9498
[EarlyStop] epoch=13 | best_val_mcc=0.7256
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7396 | F1=0.8121 | AUROC=0.9483 | AUPRC=0.8874
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7762 | F1=0.8788 | AUROC=0.9661 | AUPRC=0.9677
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3993 | F1=0.7075 | AUROC=0.7572 | AUPRC=0.7385
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5643 | F1=0.7792 | AUROC=0.8773 | AUPRC=0.8403
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4399 | val_loss=0.3109 | val_mcc=0.6689 | val_f1=0.7277 | val_auroc=0.9525

[Epoch 02] train_loss=0.3157 | val_loss=0.2219 | val_mcc=0.7327 | val_f1=0.7851 | val_auroc=0.9557

[Epoch 03] train_loss=0.2942 | val_loss=0.2869 | val_mcc=0.6910 | val_f1=0.7469 | val_auroc=0.9567

[Epoch 04] train_loss=0.2744 | val_loss=0.2415 | val_mcc=0.7179 | val_f1=0.7721 | val_auroc=0.9568

[Epoch 05] train_loss=0.2506 | val_loss=0.2717 | val_mcc=0.6976 | val_f1=0.7542 | val_auroc=0.9569

[Epoch 06] train_loss=0.2265 | val_loss=0.2426 | val_mcc=0.7188 | val_f1=0.7738 | val_auroc=0.9564

[Epoch 07] train_loss=0.1812 | val_loss=0.2675 | val_mcc=0.7043 | val_f1=0.7624 | val_auroc=0.9513

[Epoch 08] train_loss=0.1602 | val_loss=0.3113 | val_mcc=0.6840 | val_f1=0.7443 | val_auroc=0.9495
[EarlyStop] epoch=8 | best_val_mcc=0.7327
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7446 | F1=0.8153 | AUROC=0.9485 | AUPRC=0.8880
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8194 | F1=0.9014 | AUROC=0.9715 | AUPRC=0.9720
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3766 | F1=0.6955 | AUROC=0.7518 | AUPRC=0.7426
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5667 | F1=0.7804 | AUROC=0.8804 | AUPRC=0.8501
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4433 | val_loss=0.2241 | val_mcc=0.7194 | val_f1=0.7731 | val_auroc=0.9500

[Epoch 02] train_loss=0.3174 | val_loss=0.2161 | val_mcc=0.7381 | val_f1=0.7893 | val_auroc=0.9560

[Epoch 03] train_loss=0.2895 | val_loss=0.2401 | val_mcc=0.7172 | val_f1=0.7718 | val_auroc=0.9563

[Epoch 04] train_loss=0.2692 | val_loss=0.2077 | val_mcc=0.7422 | val_f1=0.7911 | val_auroc=0.9562

[Epoch 05] train_loss=0.2411 | val_loss=0.2685 | val_mcc=0.6961 | val_f1=0.7539 | val_auroc=0.9535

[Epoch 06] train_loss=0.2148 | val_loss=0.2275 | val_mcc=0.7255 | val_f1=0.7779 | val_auroc=0.9510

[Epoch 07] train_loss=0.1761 | val_loss=0.2719 | val_mcc=0.7071 | val_f1=0.7647 | val_auroc=0.9490

[Epoch 08] train_loss=0.1484 | val_loss=0.3031 | val_mcc=0.6961 | val_f1=0.7551 | val_auroc=0.9493

[Epoch 09] train_loss=0.1073 | val_loss=0.3108 | val_mcc=0.7007 | val_f1=0.7595 | val_auroc=0.9448

[Epoch 10] train_loss=0.0877 | val_loss=0.3491 | val_mcc=0.6890 | val_f1=0.7503 | val_auroc=0.9422
[EarlyStop] epoch=10 | best_val_mcc=0.7422
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7448 | F1=0.8120 | AUROC=0.9496 | AUPRC=0.8890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7612 | F1=0.8612 | AUROC=0.9679 | AUPRC=0.9674
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4076 | F1=0.6964 | AUROC=0.7616 | AUPRC=0.7490
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6167 | F1=0.8024 | AUROC=0.8857 | AUPRC=0.8531
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4387 | val_loss=0.2412 | val_mcc=0.7101 | val_f1=0.7668 | val_auroc=0.9512

[Epoch 02] train_loss=0.3137 | val_loss=0.2206 | val_mcc=0.7351 | val_f1=0.7870 | val_auroc=0.9550

[Epoch 03] train_loss=0.2848 | val_loss=0.2362 | val_mcc=0.7253 | val_f1=0.7786 | val_auroc=0.9554

[Epoch 04] train_loss=0.2548 | val_loss=0.2136 | val_mcc=0.7265 | val_f1=0.7795 | val_auroc=0.9552

[Epoch 05] train_loss=0.2286 | val_loss=0.2620 | val_mcc=0.7075 | val_f1=0.7629 | val_auroc=0.9551

[Epoch 06] train_loss=0.1930 | val_loss=0.2803 | val_mcc=0.6946 | val_f1=0.7523 | val_auroc=0.9526

[Epoch 07] train_loss=0.1546 | val_loss=0.2562 | val_mcc=0.7103 | val_f1=0.7672 | val_auroc=0.9520

[Epoch 08] train_loss=0.1312 | val_loss=0.2759 | val_mcc=0.7072 | val_f1=0.7645 | val_auroc=0.9509
[EarlyStop] epoch=8 | best_val_mcc=0.7351
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7441 | F1=0.8150 | AUROC=0.9509 | AUPRC=0.8919
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8080 | F1=0.8953 | AUROC=0.9721 | AUPRC=0.9714
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3901 | F1=0.7023 | AUROC=0.7531 | AUPRC=0.7410
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5855 | F1=0.7890 | AUROC=0.8846 | AUPRC=0.8557
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 159.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7589 | F1=0.8264 | AUROC=0.9607 | AUPRC=0.9129
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8852 | F1=0.9391 | AUROC=0.9859 | AUPRC=0.9867
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4111 | F1=0.7253 | AUROC=0.7603 | AUPRC=0.7363
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5568 | F1=0.7756 | AUROC=0.8991 | AUPRC=0.8737
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 129.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7479 | F1=0.8187 | AUROC=0.9539 | AUPRC=0.9020
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8335 | F1=0.9126 | AUROC=0.9763 | AUPRC=0.9772
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3812 | F1=0.7103 | AUROC=0.7615 | AUPRC=0.7439
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5632 | F1=0.7785 | AUROC=0.8906 | AUPRC=0.8620
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 91.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7568 | F1=0.8250 | AUROC=0.9550 | AUPRC=0.9051
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8083 | F1=0.8988 | AUROC=0.9716 | AUPRC=0.9728
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4157 | F1=0.7254 | AUROC=0.7713 | AUPRC=0.7647
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5970 | F1=0.7940 | AUROC=0.8946 | AUPRC=0.8669
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 63.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7438 | F1=0.8158 | AUROC=0.9552 | AUPRC=0.9006
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8173 | F1=0.9028 | AUROC=0.9743 | AUPRC=0.9754
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5930 | val_loss=0.4600 | val_mcc=0.4530 | val_f1=0.5644 | val_auroc=0.8179

[Epoch 02] train_loss=0.5040 | val_loss=0.4710 | val_mcc=0.4671 | val_f1=0.5773 | val_auroc=0.8334

[Epoch 03] train_loss=0.4616 | val_loss=0.4230 | val_mcc=0.4808 | val_f1=0.5869 | val_auroc=0.8441

[Epoch 04] train_loss=0.4234 | val_loss=0.3869 | val_mcc=0.4977 | val_f1=0.5961 | val_auroc=0.8533

[Epoch 05] train_loss=0.3781 | val_loss=0.4425 | val_mcc=0.4771 | val_f1=0.5849 | val_auroc=0.8542

[Epoch 06] train_loss=0.3212 | val_loss=0.4683 | val_mcc=0.4877 | val_f1=0.5929 | val_auroc=0.8545

[Epoch 07] train_loss=0.2632 | val_loss=0.4814 | val_mcc=0.4749 | val_f1=0.5830 | val_auroc=0.8460

[Epoch 08] train_loss=0.2082 | val_loss=0.5494 | val_mcc=0.4616 | val_f1=0.5731 | val_auroc=0.8411

[Epoch 09] train_loss=0.1479 | val_loss=0.5777 | val_mcc=0.4663 | val_f1=0.5767 | val_auroc=0.8458

[Epoch 10] train_loss=0.1212 | val_loss=0.5818 | val_mcc=0.4679 | val_f1=0.5775 | val_auroc=0.8421
[EarlyStop] epoch=10 | best_val_mcc=0.4977
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5615 | F1=0.6762 | AUROC=0.8678 | AUPRC=0.7416
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5129 | F1=0.7182 | AUROC=0.8319 | AUPRC=0.8347
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3126 | F1=0.6200 | AUROC=0.7192 | AUPRC=0.7016
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4977 | F1=0.7058 | AUROC=0.8346 | AUPRC=0.7969
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5931 | val_loss=0.5645 | val_mcc=0.4285 | val_f1=0.5461 | val_auroc=0.8208

[Epoch 02] train_loss=0.5122 | val_loss=0.4670 | val_mcc=0.4796 | val_f1=0.5868 | val_auroc=0.8380

[Epoch 03] train_loss=0.4707 | val_loss=0.4131 | val_mcc=0.4824 | val_f1=0.5860 | val_auroc=0.8437

[Epoch 04] train_loss=0.4364 | val_loss=0.4976 | val_mcc=0.4757 | val_f1=0.5828 | val_auroc=0.8507

[Epoch 05] train_loss=0.3938 | val_loss=0.4318 | val_mcc=0.4853 | val_f1=0.5904 | val_auroc=0.8496

[Epoch 06] train_loss=0.3401 | val_loss=0.4640 | val_mcc=0.4818 | val_f1=0.5880 | val_auroc=0.8426

[Epoch 07] train_loss=0.2884 | val_loss=0.5425 | val_mcc=0.4706 | val_f1=0.5799 | val_auroc=0.8407

[Epoch 08] train_loss=0.2235 | val_loss=0.6427 | val_mcc=0.4584 | val_f1=0.5703 | val_auroc=0.8276

[Epoch 09] train_loss=0.1815 | val_loss=0.6879 | val_mcc=0.4619 | val_f1=0.5733 | val_auroc=0.8275

[Epoch 10] train_loss=0.1275 | val_loss=0.9080 | val_mcc=0.4433 | val_f1=0.5578 | val_auroc=0.8283

[Epoch 11] train_loss=0.1049 | val_loss=0.8310 | val_mcc=0.4678 | val_f1=0.5776 | val_auroc=0.8272
[EarlyStop] epoch=11 | best_val_mcc=0.4853
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5550 | F1=0.6786 | AUROC=0.8652 | AUPRC=0.7402
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5232 | F1=0.7327 | AUROC=0.8409 | AUPRC=0.8421
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3182 | F1=0.6426 | AUROC=0.7215 | AUPRC=0.7108
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5206 | F1=0.7276 | AUROC=0.8329 | AUPRC=0.7951
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5799 | val_loss=0.3920 | val_mcc=0.4527 | val_f1=0.5508 | val_auroc=0.8312

[Epoch 02] train_loss=0.5022 | val_loss=0.3945 | val_mcc=0.4865 | val_f1=0.5869 | val_auroc=0.8425

[Epoch 03] train_loss=0.4665 | val_loss=0.3868 | val_mcc=0.5045 | val_f1=0.6018 | val_auroc=0.8532

[Epoch 04] train_loss=0.4262 | val_loss=0.3701 | val_mcc=0.4896 | val_f1=0.5797 | val_auroc=0.8557

[Epoch 05] train_loss=0.3812 | val_loss=0.3936 | val_mcc=0.4962 | val_f1=0.5929 | val_auroc=0.8563

[Epoch 06] train_loss=0.3171 | val_loss=0.4583 | val_mcc=0.4937 | val_f1=0.5969 | val_auroc=0.8556

[Epoch 07] train_loss=0.2567 | val_loss=0.5505 | val_mcc=0.4782 | val_f1=0.5857 | val_auroc=0.8462

[Epoch 08] train_loss=0.1848 | val_loss=0.6450 | val_mcc=0.4731 | val_f1=0.5818 | val_auroc=0.8422

[Epoch 09] train_loss=0.1477 | val_loss=0.6649 | val_mcc=0.4788 | val_f1=0.5861 | val_auroc=0.8400
[EarlyStop] epoch=9 | best_val_mcc=0.5045
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5591 | F1=0.6738 | AUROC=0.8695 | AUPRC=0.7489
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.4837 | F1=0.7021 | AUROC=0.8290 | AUPRC=0.8306
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3217 | F1=0.6249 | AUROC=0.7260 | AUPRC=0.7124
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5021 | F1=0.7070 | AUROC=0.8385 | AUPRC=0.8020
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5907 | val_loss=0.4661 | val_mcc=0.4611 | val_f1=0.5700 | val_auroc=0.8175

[Epoch 02] train_loss=0.5024 | val_loss=0.4939 | val_mcc=0.4635 | val_f1=0.5742 | val_auroc=0.8352

[Epoch 03] train_loss=0.4603 | val_loss=0.4419 | val_mcc=0.4809 | val_f1=0.5878 | val_auroc=0.8457

[Epoch 04] train_loss=0.4191 | val_loss=0.4487 | val_mcc=0.4793 | val_f1=0.5865 | val_auroc=0.8503

[Epoch 05] train_loss=0.3669 | val_loss=0.4329 | val_mcc=0.4829 | val_f1=0.5890 | val_auroc=0.8516

[Epoch 06] train_loss=0.3049 | val_loss=0.4624 | val_mcc=0.4826 | val_f1=0.5891 | val_auroc=0.8516

[Epoch 07] train_loss=0.2377 | val_loss=0.5401 | val_mcc=0.4742 | val_f1=0.5824 | val_auroc=0.8509

[Epoch 08] train_loss=0.1789 | val_loss=0.5642 | val_mcc=0.4724 | val_f1=0.5813 | val_auroc=0.8433

[Epoch 09] train_loss=0.1335 | val_loss=0.6191 | val_mcc=0.4650 | val_f1=0.5756 | val_auroc=0.8398

[Epoch 10] train_loss=0.0868 | val_loss=0.7442 | val_mcc=0.4520 | val_f1=0.5644 | val_auroc=0.8399

[Epoch 11] train_loss=0.0657 | val_loss=0.7209 | val_mcc=0.4632 | val_f1=0.5741 | val_auroc=0.8415
[EarlyStop] epoch=11 | best_val_mcc=0.4829
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5441 | F1=0.6721 | AUROC=0.8616 | AUPRC=0.7288
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5185 | F1=0.7424 | AUROC=0.8409 | AUPRC=0.8374
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3493 | F1=0.6630 | AUROC=0.7246 | AUPRC=0.7020
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5153 | F1=0.7299 | AUROC=0.8392 | AUPRC=0.8014
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 166.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5471 | F1=0.6793 | AUROC=0.8682 | AUPRC=0.7293
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5248 | F1=0.7590 | AUROC=0.8330 | AUPRC=0.8268
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3213 | F1=0.6705 | AUROC=0.7204 | AUPRC=0.7090
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5116 | F1=0.7438 | AUROC=0.8343 | AUPRC=0.8005
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 82.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5473 | F1=0.6789 | AUROC=0.8665 | AUPRC=0.7362
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5220 | F1=0.7565 | AUROC=0.8340 | AUPRC=0.8240
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3478 | F1=0.6794 | AUROC=0.7303 | AUPRC=0.7100
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5219 | F1=0.7471 | AUROC=0.8349 | AUPRC=0.7977
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 41.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5594 | F1=0.6860 | AUROC=0.8690 | AUPRC=0.7433
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5318 | F1=0.7534 | AUROC=0.8400 | AUPRC=0.8366
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3624 | F1=0.6758 | AUROC=0.7335 | AUPRC=0.7059
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5284 | F1=0.7454 | AUROC=0.8390 | AUPRC=0.7985
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 43.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5521 | F1=0.6815 | AUROC=0.8684 | AUPRC=0.7464
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5250 | F1=0.7555 | AUROC=0.8292 | AUPRC=0.8290
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3309 | F1=0.6672 | AUROC=0.7257 | AUPRC=0.6986
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4410 | val_loss=0.2362 | val_mcc=0.7140 | val_f1=0.7702 | val_auroc=0.9529

[Epoch 02] train_loss=0.3050 | val_loss=0.2369 | val_mcc=0.7187 | val_f1=0.7733 | val_auroc=0.9556

[Epoch 03] train_loss=0.2706 | val_loss=0.2178 | val_mcc=0.7348 | val_f1=0.7867 | val_auroc=0.9566

[Epoch 04] train_loss=0.2427 | val_loss=0.2336 | val_mcc=0.7269 | val_f1=0.7801 | val_auroc=0.9574

[Epoch 05] train_loss=0.2150 | val_loss=0.2606 | val_mcc=0.7099 | val_f1=0.7651 | val_auroc=0.9566

[Epoch 06] train_loss=0.1789 | val_loss=0.2474 | val_mcc=0.7150 | val_f1=0.7709 | val_auroc=0.9543

[Epoch 07] train_loss=0.1458 | val_loss=0.2753 | val_mcc=0.7030 | val_f1=0.7612 | val_auroc=0.9511

[Epoch 08] train_loss=0.1068 | val_loss=0.2923 | val_mcc=0.7070 | val_f1=0.7641 | val_auroc=0.9514

[Epoch 09] train_loss=0.0884 | val_loss=0.2986 | val_mcc=0.7153 | val_f1=0.7708 | val_auroc=0.9516
[EarlyStop] epoch=9 | best_val_mcc=0.7348
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7398 | F1=0.8116 | AUROC=0.9487 | AUPRC=0.8845
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7967 | F1=0.8858 | AUROC=0.9684 | AUPRC=0.9681
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4017 | F1=0.7047 | AUROC=0.7459 | AUPRC=0.7249
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5231 | F1=0.7600 | AUROC=0.8673 | AUPRC=0.8401
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4309 | val_loss=0.3037 | val_mcc=0.6831 | val_f1=0.7381 | val_auroc=0.9575

[Epoch 02] train_loss=0.3110 | val_loss=0.2335 | val_mcc=0.7227 | val_f1=0.7762 | val_auroc=0.9579

[Epoch 03] train_loss=0.2843 | val_loss=0.2107 | val_mcc=0.7334 | val_f1=0.7856 | val_auroc=0.9580

[Epoch 04] train_loss=0.2581 | val_loss=0.2418 | val_mcc=0.7190 | val_f1=0.7728 | val_auroc=0.9566

[Epoch 05] train_loss=0.2340 | val_loss=0.2333 | val_mcc=0.7203 | val_f1=0.7751 | val_auroc=0.9526

[Epoch 06] train_loss=0.2046 | val_loss=0.2712 | val_mcc=0.7065 | val_f1=0.7627 | val_auroc=0.9529

[Epoch 07] train_loss=0.1675 | val_loss=0.2940 | val_mcc=0.7012 | val_f1=0.7586 | val_auroc=0.9487

[Epoch 08] train_loss=0.1221 | val_loss=0.3276 | val_mcc=0.6901 | val_f1=0.7511 | val_auroc=0.9421

[Epoch 09] train_loss=0.1049 | val_loss=0.3691 | val_mcc=0.6812 | val_f1=0.7438 | val_auroc=0.9381
[EarlyStop] epoch=9 | best_val_mcc=0.7334
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7518 | F1=0.8202 | AUROC=0.9508 | AUPRC=0.8873
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8022 | F1=0.8923 | AUROC=0.9657 | AUPRC=0.9634
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4061 | F1=0.7058 | AUROC=0.7574 | AUPRC=0.7323
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5532 | F1=0.7739 | AUROC=0.8715 | AUPRC=0.8398
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4482 | val_loss=0.2266 | val_mcc=0.7186 | val_f1=0.7735 | val_auroc=0.9535

[Epoch 02] train_loss=0.3096 | val_loss=0.2133 | val_mcc=0.7172 | val_f1=0.7635 | val_auroc=0.9561

[Epoch 03] train_loss=0.2816 | val_loss=0.2091 | val_mcc=0.7373 | val_f1=0.7865 | val_auroc=0.9570

[Epoch 04] train_loss=0.2564 | val_loss=0.2251 | val_mcc=0.7331 | val_f1=0.7854 | val_auroc=0.9569

[Epoch 05] train_loss=0.2330 | val_loss=0.2348 | val_mcc=0.7282 | val_f1=0.7814 | val_auroc=0.9556

[Epoch 06] train_loss=0.2005 | val_loss=0.2365 | val_mcc=0.7254 | val_f1=0.7792 | val_auroc=0.9546

[Epoch 07] train_loss=0.1631 | val_loss=0.2927 | val_mcc=0.6923 | val_f1=0.7525 | val_auroc=0.9470

[Epoch 08] train_loss=0.1174 | val_loss=0.2829 | val_mcc=0.7059 | val_f1=0.7636 | val_auroc=0.9482

[Epoch 09] train_loss=0.0972 | val_loss=0.3125 | val_mcc=0.6932 | val_f1=0.7535 | val_auroc=0.9442
[EarlyStop] epoch=9 | best_val_mcc=0.7373
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7516 | F1=0.8167 | AUROC=0.9508 | AUPRC=0.8874
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7521 | F1=0.8567 | AUROC=0.9630 | AUPRC=0.9623
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4031 | F1=0.6943 | AUROC=0.7608 | AUPRC=0.7420
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5728 | F1=0.7811 | AUROC=0.8729 | AUPRC=0.8428
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4460 | val_loss=0.2230 | val_mcc=0.7219 | val_f1=0.7755 | val_auroc=0.9538

[Epoch 02] train_loss=0.3063 | val_loss=0.2325 | val_mcc=0.7254 | val_f1=0.7786 | val_auroc=0.9571

[Epoch 03] train_loss=0.2708 | val_loss=0.2232 | val_mcc=0.7294 | val_f1=0.7824 | val_auroc=0.9572

[Epoch 04] train_loss=0.2437 | val_loss=0.2332 | val_mcc=0.7234 | val_f1=0.7772 | val_auroc=0.9569

[Epoch 05] train_loss=0.2097 | val_loss=0.2359 | val_mcc=0.7261 | val_f1=0.7796 | val_auroc=0.9567

[Epoch 06] train_loss=0.1781 | val_loss=0.2423 | val_mcc=0.7193 | val_f1=0.7743 | val_auroc=0.9532

[Epoch 07] train_loss=0.1417 | val_loss=0.2602 | val_mcc=0.7175 | val_f1=0.7729 | val_auroc=0.9499

[Epoch 08] train_loss=0.1023 | val_loss=0.2865 | val_mcc=0.7047 | val_f1=0.7627 | val_auroc=0.9501

[Epoch 09] train_loss=0.0815 | val_loss=0.3070 | val_mcc=0.7007 | val_f1=0.7594 | val_auroc=0.9486
[EarlyStop] epoch=9 | best_val_mcc=0.7294
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7402 | F1=0.8132 | AUROC=0.9509 | AUPRC=0.8882
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8026 | F1=0.8958 | AUROC=0.9673 | AUPRC=0.9683
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3919 | F1=0.7095 | AUROC=0.7539 | AUPRC=0.7233
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5401 | F1=0.7685 | AUROC=0.8707 | AUPRC=0.8364
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 161.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7575 | F1=0.8254 | AUROC=0.9605 | AUPRC=0.9108
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8627 | F1=0.9270 | AUROC=0.9822 | AUPRC=0.9815
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3997 | F1=0.7191 | AUROC=0.7598 | AUPRC=0.7390
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5493 | F1=0.7724 | AUROC=0.8901 | AUPRC=0.8590
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 123.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7434 | F1=0.8155 | AUROC=0.9539 | AUPRC=0.8996
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8018 | F1=0.8968 | AUROC=0.9703 | AUPRC=0.9701
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3981 | F1=0.7182 | AUROC=0.7589 | AUPRC=0.7422
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5447 | F1=0.7705 | AUROC=0.8792 | AUPRC=0.8531
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 73.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7461 | F1=0.8174 | AUROC=0.9517 | AUPRC=0.8919
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8164 | F1=0.9037 | AUROC=0.9715 | AUPRC=0.9702
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4201 | F1=0.7247 | AUROC=0.7664 | AUPRC=0.7443
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5415 | F1=0.7691 | AUROC=0.8770 | AUPRC=0.8412
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 99.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7393 | F1=0.8126 | AUROC=0.9510 | AUPRC=0.8946
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8045 | F1=0.8984 | AUROC=0.9661 | AUPRC=0.9661
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.6305 | val_loss=0.5202 | val_mcc=0.3931 | val_f1=0.5185 | val_auroc=0.7692

[Epoch 02] train_loss=0.5544 | val_loss=0.4802 | val_mcc=0.4202 | val_f1=0.5365 | val_auroc=0.7845

[Epoch 03] train_loss=0.5195 | val_loss=0.4601 | val_mcc=0.4426 | val_f1=0.5525 | val_auroc=0.7991

[Epoch 04] train_loss=0.4865 | val_loss=0.4732 | val_mcc=0.4527 | val_f1=0.5639 | val_auroc=0.8073

[Epoch 05] train_loss=0.4472 | val_loss=0.5011 | val_mcc=0.4513 | val_f1=0.5653 | val_auroc=0.8177

[Epoch 06] train_loss=0.4061 | val_loss=0.4267 | val_mcc=0.4628 | val_f1=0.5663 | val_auroc=0.8179

[Epoch 07] train_loss=0.3486 | val_loss=0.4537 | val_mcc=0.4707 | val_f1=0.5768 | val_auroc=0.8273

[Epoch 08] train_loss=0.2914 | val_loss=0.5163 | val_mcc=0.4447 | val_f1=0.5602 | val_auroc=0.8205

[Epoch 09] train_loss=0.2390 | val_loss=0.6231 | val_mcc=0.4289 | val_f1=0.5472 | val_auroc=0.8227

[Epoch 10] train_loss=0.1990 | val_loss=0.6567 | val_mcc=0.4115 | val_f1=0.5343 | val_auroc=0.8189

[Epoch 11] train_loss=0.1577 | val_loss=0.6551 | val_mcc=0.4191 | val_f1=0.5410 | val_auroc=0.8099

[Epoch 12] train_loss=0.1153 | val_loss=0.6702 | val_mcc=0.4343 | val_f1=0.5524 | val_auroc=0.8184

[Epoch 13] train_loss=0.0971 | val_loss=0.7537 | val_mcc=0.4206 | val_f1=0.5416 | val_auroc=0.8185
[EarlyStop] epoch=13 | best_val_mcc=0.4707
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.4933 | F1=0.6267 | AUROC=0.8165 | AUPRC=0.6890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.4880 | F1=0.7147 | AUROC=0.8152 | AUPRC=0.8062
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3611 | F1=0.6532 | AUROC=0.7205 | AUPRC=0.6962
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4539 | F1=0.6727 | AUROC=0.7827 | AUPRC=0.7702
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.6352 | val_loss=0.5145 | val_mcc=0.3958 | val_f1=0.5193 | val_auroc=0.7742

[Epoch 02] train_loss=0.5566 | val_loss=0.4807 | val_mcc=0.4390 | val_f1=0.5500 | val_auroc=0.7922

[Epoch 03] train_loss=0.5272 | val_loss=0.4867 | val_mcc=0.4489 | val_f1=0.5609 | val_auroc=0.8009

[Epoch 04] train_loss=0.4953 | val_loss=0.4306 | val_mcc=0.4652 | val_f1=0.5627 | val_auroc=0.8059

[Epoch 05] train_loss=0.4583 | val_loss=0.4817 | val_mcc=0.4486 | val_f1=0.5621 | val_auroc=0.8128

[Epoch 06] train_loss=0.4107 | val_loss=0.5591 | val_mcc=0.4200 | val_f1=0.5412 | val_auroc=0.8070

[Epoch 07] train_loss=0.3582 | val_loss=0.5809 | val_mcc=0.4269 | val_f1=0.5467 | val_auroc=0.8102

[Epoch 08] train_loss=0.3083 | val_loss=0.6341 | val_mcc=0.4096 | val_f1=0.5336 | val_auroc=0.8041

[Epoch 09] train_loss=0.2418 | val_loss=0.7050 | val_mcc=0.4012 | val_f1=0.5277 | val_auroc=0.7926

[Epoch 10] train_loss=0.2070 | val_loss=0.7609 | val_mcc=0.3939 | val_f1=0.5222 | val_auroc=0.7895
[EarlyStop] epoch=10 | best_val_mcc=0.4652
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.4843 | F1=0.6056 | AUROC=0.7968 | AUPRC=0.6649
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.4739 | F1=0.6865 | AUROC=0.7899 | AUPRC=0.7824
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3557 | F1=0.6267 | AUROC=0.7073 | AUPRC=0.6916
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.4455 | F1=0.6440 | AUROC=0.7641 | AUPRC=0.7433
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.6287 | val_loss=0.5551 | val_mcc=0.3823 | val_f1=0.5136 | val_auroc=0.7768

[Epoch 02] train_loss=0.5501 | val_loss=0.4839 | val_mcc=0.4342 | val_f1=0.5490 | val_auroc=0.7991

[Epoch 03] train_loss=0.5152 | val_loss=0.4217 | val_mcc=0.4534 | val_f1=0.5512 | val_auroc=0.8086

[Epoch 04] train_loss=0.4848 | val_loss=0.4827 | val_mcc=0.4553 | val_f1=0.5677 | val_auroc=0.8206

[Epoch 05] train_loss=0.4437 | val_loss=0.5485 | val_mcc=0.4423 | val_f1=0.5576 | val_auroc=0.8268

[Epoch 06] train_loss=0.4037 | val_loss=0.5216 | val_mcc=0.4475 | val_f1=0.5624 | val_auroc=0.8222

[Epoch 07] train_loss=0.3433 | val_loss=0.5769 | val_mcc=0.4533 | val_f1=0.5665 | val_auroc=0.8260

[Epoch 08] train_loss=0.2921 | val_loss=0.5564 | val_mcc=0.4428 | val_f1=0.5588 | val_auroc=0.8144

[Epoch 09] train_loss=0.2198 | val_loss=0.6028 | val_mcc=0.4461 | val_f1=0.5612 | val_auroc=0.8134

[Epoch 10] train_loss=0.1851 | val_loss=0.6815 | val_mcc=0.4353 | val_f1=0.5532 | val_auroc=0.8116
[EarlyStop] epoch=10 | best_val_mcc=0.4553
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.4761 | F1=0.6220 | AUROC=0.8158 | AUPRC=0.6937
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.4549 | F1=0.7117 | AUROC=0.8007 | AUPRC=0.8045
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3293 | F1=0.6444 | AUROC=0.7188 | AUPRC=0.6987
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.4276 | F1=0.6719 | AUROC=0.7766 | AUPRC=0.7543
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.6330 | val_loss=0.4820 | val_mcc=0.3866 | val_f1=0.5034 | val_auroc=0.7677

[Epoch 02] train_loss=0.5512 | val_loss=0.4601 | val_mcc=0.4279 | val_f1=0.5373 | val_auroc=0.7904

[Epoch 03] train_loss=0.5130 | val_loss=0.4440 | val_mcc=0.4492 | val_f1=0.5542 | val_auroc=0.8029

[Epoch 04] train_loss=0.4771 | val_loss=0.4763 | val_mcc=0.4440 | val_f1=0.5582 | val_auroc=0.8091

[Epoch 05] train_loss=0.4333 | val_loss=0.4334 | val_mcc=0.4602 | val_f1=0.5653 | val_auroc=0.8147

[Epoch 06] train_loss=0.3798 | val_loss=0.5022 | val_mcc=0.4337 | val_f1=0.5520 | val_auroc=0.8189

[Epoch 07] train_loss=0.3202 | val_loss=0.4894 | val_mcc=0.4318 | val_f1=0.5497 | val_auroc=0.8140

[Epoch 08] train_loss=0.2616 | val_loss=0.6082 | val_mcc=0.4131 | val_f1=0.5359 | val_auroc=0.8182

[Epoch 09] train_loss=0.2103 | val_loss=0.6223 | val_mcc=0.4245 | val_f1=0.5448 | val_auroc=0.8161

[Epoch 10] train_loss=0.1515 | val_loss=0.6192 | val_mcc=0.4392 | val_f1=0.5561 | val_auroc=0.8199

[Epoch 11] train_loss=0.1261 | val_loss=0.6626 | val_mcc=0.4246 | val_f1=0.5452 | val_auroc=0.8125
[EarlyStop] epoch=11 | best_val_mcc=0.4602
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.4839 | F1=0.6161 | AUROC=0.8088 | AUPRC=0.6820
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.4413 | F1=0.6753 | AUROC=0.8009 | AUPRC=0.7948
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3524 | F1=0.6408 | AUROC=0.7162 | AUPRC=0.6925
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.4424 | F1=0.6594 | AUROC=0.7785 | AUPRC=0.7597
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 332.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5106 | F1=0.6528 | AUROC=0.8476 | AUPRC=0.7112
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5049 | F1=0.7500 | AUROC=0.8314 | AUPRC=0.8198
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3534 | F1=0.6772 | AUROC=0.7320 | AUPRC=0.7061
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4413 | F1=0.6995 | AUROC=0.7971 | AUPRC=0.7686
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 119.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.4785 | F1=0.6262 | AUROC=0.8243 | AUPRC=0.6933
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4916 | F1=0.7332 | AUROC=0.8087 | AUPRC=0.7975
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3286 | F1=0.6489 | AUROC=0.7231 | AUPRC=0.7050
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4394 | F1=0.6871 | AUROC=0.7750 | AUPRC=0.7504
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 54.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.4659 | F1=0.6165 | AUROC=0.8133 | AUPRC=0.6833
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4401 | F1=0.7073 | AUROC=0.7965 | AUPRC=0.7994
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3381 | F1=0.6503 | AUROC=0.7186 | AUPRC=0.7012
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4083 | F1=0.6630 | AUROC=0.7636 | AUPRC=0.7473
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 51.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.4721 | F1=0.6209 | AUROC=0.8120 | AUPRC=0.6838
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4544 | F1=0.7143 | AUROC=0.7946 | AUPRC=0.7914
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3409 | F1=0.6535 | AUROC=0.7164 | AUPRC=0.7084
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4512 | val_loss=0.2303 | val_mcc=0.7088 | val_f1=0.7654 | val_auroc=0.9496

[Epoch 02] train_loss=0.3218 | val_loss=0.2568 | val_mcc=0.7017 | val_f1=0.7586 | val_auroc=0.9530

[Epoch 03] train_loss=0.2963 | val_loss=0.2368 | val_mcc=0.7182 | val_f1=0.7731 | val_auroc=0.9543

[Epoch 04] train_loss=0.2738 | val_loss=0.2702 | val_mcc=0.6977 | val_f1=0.7546 | val_auroc=0.9531

[Epoch 05] train_loss=0.2549 | val_loss=0.2485 | val_mcc=0.7074 | val_f1=0.7646 | val_auroc=0.9505

[Epoch 06] train_loss=0.2278 | val_loss=0.2464 | val_mcc=0.7105 | val_f1=0.7673 | val_auroc=0.9506

[Epoch 07] train_loss=0.1965 | val_loss=0.2685 | val_mcc=0.6972 | val_f1=0.7563 | val_auroc=0.9478

[Epoch 08] train_loss=0.1655 | val_loss=0.2959 | val_mcc=0.6852 | val_f1=0.7455 | val_auroc=0.9476

[Epoch 09] train_loss=0.1437 | val_loss=0.2781 | val_mcc=0.6922 | val_f1=0.7528 | val_auroc=0.9462
[EarlyStop] epoch=9 | best_val_mcc=0.7182
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7153 | F1=0.7956 | AUROC=0.9406 | AUPRC=0.8733
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8221 | F1=0.9067 | AUROC=0.9640 | AUPRC=0.9609
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3815 | F1=0.7047 | AUROC=0.7427 | AUPRC=0.7105
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4947 | F1=0.7486 | AUROC=0.8494 | AUPRC=0.8053
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4703 | val_loss=0.2437 | val_mcc=0.7113 | val_f1=0.7681 | val_auroc=0.9500

[Epoch 02] train_loss=0.3361 | val_loss=0.2940 | val_mcc=0.6840 | val_f1=0.7400 | val_auroc=0.9542

[Epoch 03] train_loss=0.3095 | val_loss=0.2136 | val_mcc=0.7345 | val_f1=0.7861 | val_auroc=0.9558

[Epoch 04] train_loss=0.2932 | val_loss=0.2159 | val_mcc=0.7320 | val_f1=0.7841 | val_auroc=0.9561

[Epoch 05] train_loss=0.2664 | val_loss=0.2394 | val_mcc=0.7084 | val_f1=0.7656 | val_auroc=0.9521

[Epoch 06] train_loss=0.2415 | val_loss=0.3127 | val_mcc=0.6819 | val_f1=0.7388 | val_auroc=0.9507

[Epoch 07] train_loss=0.2088 | val_loss=0.2509 | val_mcc=0.6973 | val_f1=0.7568 | val_auroc=0.9482

[Epoch 08] train_loss=0.1679 | val_loss=0.2895 | val_mcc=0.6798 | val_f1=0.7430 | val_auroc=0.9414

[Epoch 09] train_loss=0.1431 | val_loss=0.3087 | val_mcc=0.6738 | val_f1=0.7383 | val_auroc=0.9387
[EarlyStop] epoch=9 | best_val_mcc=0.7345
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7341 | F1=0.8070 | AUROC=0.9413 | AUPRC=0.8705
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7929 | F1=0.8848 | AUROC=0.9636 | AUPRC=0.9653
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3923 | F1=0.6929 | AUROC=0.7431 | AUPRC=0.7138
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5308 | F1=0.7639 | AUROC=0.8449 | AUPRC=0.7960
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4428 | val_loss=0.2274 | val_mcc=0.7181 | val_f1=0.7731 | val_auroc=0.9519

[Epoch 02] train_loss=0.3209 | val_loss=0.2141 | val_mcc=0.7325 | val_f1=0.7842 | val_auroc=0.9554

[Epoch 03] train_loss=0.3010 | val_loss=0.2194 | val_mcc=0.7308 | val_f1=0.7833 | val_auroc=0.9553

[Epoch 04] train_loss=0.2816 | val_loss=0.2430 | val_mcc=0.7145 | val_f1=0.7699 | val_auroc=0.9551

[Epoch 05] train_loss=0.2593 | val_loss=0.2398 | val_mcc=0.7110 | val_f1=0.7676 | val_auroc=0.9526

[Epoch 06] train_loss=0.2290 | val_loss=0.2304 | val_mcc=0.7121 | val_f1=0.7675 | val_auroc=0.9506

[Epoch 07] train_loss=0.1865 | val_loss=0.2780 | val_mcc=0.6848 | val_f1=0.7471 | val_auroc=0.9447

[Epoch 08] train_loss=0.1615 | val_loss=0.2832 | val_mcc=0.6825 | val_f1=0.7448 | val_auroc=0.9415
[EarlyStop] epoch=8 | best_val_mcc=0.7325
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7333 | F1=0.8059 | AUROC=0.9418 | AUPRC=0.8737
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7864 | F1=0.8789 | AUROC=0.9669 | AUPRC=0.9658
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3773 | F1=0.6868 | AUROC=0.7404 | AUPRC=0.7137
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5378 | F1=0.7664 | AUROC=0.8508 | AUPRC=0.8072
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4376 | val_loss=0.2581 | val_mcc=0.6906 | val_f1=0.7507 | val_auroc=0.9493

[Epoch 02] train_loss=0.3237 | val_loss=0.2398 | val_mcc=0.7103 | val_f1=0.7666 | val_auroc=0.9539

[Epoch 03] train_loss=0.2982 | val_loss=0.2532 | val_mcc=0.7046 | val_f1=0.7610 | val_auroc=0.9543

[Epoch 04] train_loss=0.2741 | val_loss=0.2534 | val_mcc=0.7034 | val_f1=0.7601 | val_auroc=0.9537

[Epoch 05] train_loss=0.2498 | val_loss=0.2727 | val_mcc=0.6930 | val_f1=0.7511 | val_auroc=0.9531

[Epoch 06] train_loss=0.2192 | val_loss=0.2772 | val_mcc=0.6871 | val_f1=0.7469 | val_auroc=0.9498

[Epoch 07] train_loss=0.1832 | val_loss=0.2682 | val_mcc=0.6945 | val_f1=0.7542 | val_auroc=0.9495

[Epoch 08] train_loss=0.1617 | val_loss=0.2864 | val_mcc=0.6856 | val_f1=0.7470 | val_auroc=0.9464
[EarlyStop] epoch=8 | best_val_mcc=0.7103
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7140 | F1=0.7948 | AUROC=0.9412 | AUPRC=0.8691
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8276 | F1=0.9099 | AUROC=0.9669 | AUPRC=0.9619
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3780 | F1=0.7057 | AUROC=0.7381 | AUPRC=0.7103
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.4862 | F1=0.7451 | AUROC=0.8402 | AUPRC=0.7942
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 180.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7446 | F1=0.8164 | AUROC=0.9568 | AUPRC=0.9023
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8630 | F1=0.9268 | AUROC=0.9829 | AUPRC=0.9812
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3837 | F1=0.7105 | AUROC=0.7599 | AUPRC=0.7269
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5179 | F1=0.7587 | AUROC=0.8790 | AUPRC=0.8527
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 154.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7229 | F1=0.8010 | AUROC=0.9457 | AUPRC=0.8834
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8422 | F1=0.9169 | AUROC=0.9706 | AUPRC=0.9702
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4069 | F1=0.7162 | AUROC=0.7578 | AUPRC=0.7277
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5244 | F1=0.7616 | AUROC=0.8565 | AUPRC=0.8103
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 89.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7279 | F1=0.8046 | AUROC=0.9467 | AUPRC=0.8828
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8299 | F1=0.9120 | AUROC=0.9711 | AUPRC=0.9724
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4072 | F1=0.7201 | AUROC=0.7519 | AUPRC=0.7357
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5324 | F1=0.7651 | AUROC=0.8618 | AUPRC=0.8205
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 85.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7203 | F1=0.7992 | AUROC=0.9441 | AUPRC=0.8802
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8216 | F1=0.9072 | AUROC=0.9694 | AUPRC=0.9696
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.6424 | val_loss=0.5523 | val_mcc=0.4205 | val_f1=0.5412 | val_auroc=0.7855

[Epoch 02] train_loss=0.5327 | val_loss=0.4683 | val_mcc=0.4974 | val_f1=0.5919 | val_auroc=0.8058

[Epoch 03] train_loss=0.5066 | val_loss=0.4276 | val_mcc=0.5126 | val_f1=0.5982 | val_auroc=0.8101

[Epoch 04] train_loss=0.4814 | val_loss=0.4188 | val_mcc=0.5102 | val_f1=0.5975 | val_auroc=0.8101

[Epoch 05] train_loss=0.4524 | val_loss=0.4086 | val_mcc=0.5032 | val_f1=0.5932 | val_auroc=0.8121

[Epoch 06] train_loss=0.4186 | val_loss=0.4847 | val_mcc=0.4506 | val_f1=0.5644 | val_auroc=0.8086

[Epoch 07] train_loss=0.3818 | val_loss=0.4787 | val_mcc=0.4498 | val_f1=0.5633 | val_auroc=0.8013

[Epoch 08] train_loss=0.3267 | val_loss=0.4991 | val_mcc=0.4361 | val_f1=0.5536 | val_auroc=0.8035

[Epoch 09] train_loss=0.2976 | val_loss=0.5380 | val_mcc=0.4064 | val_f1=0.5314 | val_auroc=0.7899
[EarlyStop] epoch=9 | best_val_mcc=0.5126
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5399 | F1=0.6478 | AUROC=0.8115 | AUPRC=0.7147
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.4803 | F1=0.6780 | AUROC=0.7864 | AUPRC=0.8080
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3571 | F1=0.6190 | AUROC=0.7133 | AUPRC=0.7139
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4917 | F1=0.6809 | AUROC=0.7819 | AUPRC=0.7883
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.6359 | val_loss=0.4610 | val_mcc=0.4782 | val_f1=0.5679 | val_auroc=0.7953

[Epoch 02] train_loss=0.5358 | val_loss=0.4076 | val_mcc=0.5145 | val_f1=0.5849 | val_auroc=0.8086

[Epoch 03] train_loss=0.5137 | val_loss=0.4649 | val_mcc=0.5061 | val_f1=0.6018 | val_auroc=0.8131

[Epoch 04] train_loss=0.4842 | val_loss=0.4275 | val_mcc=0.5112 | val_f1=0.6057 | val_auroc=0.8221

[Epoch 05] train_loss=0.4584 | val_loss=0.4350 | val_mcc=0.4920 | val_f1=0.5936 | val_auroc=0.8226

[Epoch 06] train_loss=0.4160 | val_loss=0.4598 | val_mcc=0.4609 | val_f1=0.5715 | val_auroc=0.8139

[Epoch 07] train_loss=0.3597 | val_loss=0.4937 | val_mcc=0.4298 | val_f1=0.5475 | val_auroc=0.7960

[Epoch 08] train_loss=0.3277 | val_loss=0.5897 | val_mcc=0.3996 | val_f1=0.5264 | val_auroc=0.7942
[EarlyStop] epoch=8 | best_val_mcc=0.5145
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5328 | F1=0.6262 | AUROC=0.8117 | AUPRC=0.7123
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.4792 | F1=0.6585 | AUROC=0.7812 | AUPRC=0.8028
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3462 | F1=0.5770 | AUROC=0.7107 | AUPRC=0.7094
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.4895 | F1=0.6589 | AUROC=0.7793 | AUPRC=0.7875
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.6285 | val_loss=0.4427 | val_mcc=0.4852 | val_f1=0.5686 | val_auroc=0.7978

[Epoch 02] train_loss=0.5350 | val_loss=0.4493 | val_mcc=0.5100 | val_f1=0.5990 | val_auroc=0.8102

[Epoch 03] train_loss=0.5050 | val_loss=0.4480 | val_mcc=0.5117 | val_f1=0.6043 | val_auroc=0.8146

[Epoch 04] train_loss=0.4812 | val_loss=0.4134 | val_mcc=0.5269 | val_f1=0.6097 | val_auroc=0.8182

[Epoch 05] train_loss=0.4500 | val_loss=0.4592 | val_mcc=0.4981 | val_f1=0.5995 | val_auroc=0.8209

[Epoch 06] train_loss=0.4144 | val_loss=0.4677 | val_mcc=0.4973 | val_f1=0.5990 | val_auroc=0.8160

[Epoch 07] train_loss=0.3757 | val_loss=0.5571 | val_mcc=0.4225 | val_f1=0.5429 | val_auroc=0.8087

[Epoch 08] train_loss=0.3305 | val_loss=0.5141 | val_mcc=0.4627 | val_f1=0.5738 | val_auroc=0.8168

[Epoch 09] train_loss=0.2713 | val_loss=0.5939 | val_mcc=0.4099 | val_f1=0.5342 | val_auroc=0.7938

[Epoch 10] train_loss=0.2428 | val_loss=0.6976 | val_mcc=0.3988 | val_f1=0.5246 | val_auroc=0.8017
[EarlyStop] epoch=10 | best_val_mcc=0.5269
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5353 | F1=0.6457 | AUROC=0.8090 | AUPRC=0.7112
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.4710 | F1=0.6678 | AUROC=0.7970 | AUPRC=0.8111
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3518 | F1=0.6135 | AUROC=0.7095 | AUPRC=0.7148
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.4793 | F1=0.6763 | AUROC=0.7801 | AUPRC=0.7826
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.6431 | val_loss=0.4852 | val_mcc=0.4486 | val_f1=0.5491 | val_auroc=0.7856

[Epoch 02] train_loss=0.5318 | val_loss=0.5014 | val_mcc=0.4659 | val_f1=0.5749 | val_auroc=0.8057

[Epoch 03] train_loss=0.4986 | val_loss=0.4865 | val_mcc=0.4709 | val_f1=0.5787 | val_auroc=0.8083

[Epoch 04] train_loss=0.4705 | val_loss=0.4510 | val_mcc=0.4873 | val_f1=0.5896 | val_auroc=0.8113

[Epoch 05] train_loss=0.4374 | val_loss=0.4389 | val_mcc=0.4833 | val_f1=0.5857 | val_auroc=0.8058

[Epoch 06] train_loss=0.3992 | val_loss=0.4711 | val_mcc=0.4481 | val_f1=0.5618 | val_auroc=0.8035

[Epoch 07] train_loss=0.3587 | val_loss=0.4865 | val_mcc=0.4389 | val_f1=0.5551 | val_auroc=0.7988

[Epoch 08] train_loss=0.3127 | val_loss=0.5952 | val_mcc=0.4020 | val_f1=0.5277 | val_auroc=0.7958

[Epoch 09] train_loss=0.2608 | val_loss=0.5423 | val_mcc=0.4175 | val_f1=0.5395 | val_auroc=0.7949

[Epoch 10] train_loss=0.2322 | val_loss=0.6046 | val_mcc=0.4009 | val_f1=0.5275 | val_auroc=0.7932
[EarlyStop] epoch=10 | best_val_mcc=0.4873
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5162 | F1=0.6471 | AUROC=0.8078 | AUPRC=0.7132
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.4868 | F1=0.7100 | AUROC=0.7850 | AUPRC=0.8095
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3362 | F1=0.6296 | AUROC=0.7135 | AUPRC=0.7189
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.4836 | F1=0.6982 | AUROC=0.7812 | AUPRC=0.7892
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 323.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5558 | F1=0.6833 | AUROC=0.8751 | AUPRC=0.7765
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5203 | F1=0.7474 | AUROC=0.8582 | AUPRC=0.8591
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3489 | F1=0.6682 | AUROC=0.7484 | AUPRC=0.7530
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4844 | F1=0.7169 | AUROC=0.8257 | AUPRC=0.8206
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 196.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5251 | F1=0.6602 | AUROC=0.8385 | AUPRC=0.7474
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4992 | F1=0.7298 | AUROC=0.8091 | AUPRC=0.8326
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3149 | F1=0.6438 | AUROC=0.7210 | AUPRC=0.7243
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5014 | F1=0.7210 | AUROC=0.7961 | AUPRC=0.7996
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 43.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5286 | F1=0.6608 | AUROC=0.8361 | AUPRC=0.7413
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5290 | F1=0.7427 | AUROC=0.8162 | AUPRC=0.8312
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3380 | F1=0.6514 | AUROC=0.7159 | AUPRC=0.7243
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4833 | F1=0.7090 | AUROC=0.7965 | AUPRC=0.7981
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 82.
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5128 | F1=0.6482 | AUROC=0.8257 | AUPRC=0.7307
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5076 | F1=0.7270 | AUROC=0.8003 | AUPRC=0.8203
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3192 | F1=0.6363 | AUROC=0.7063 | AUPRC=0.7176
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4527 | val_loss=0.2354 | val_mcc=0.7094 | val_f1=0.7665 | val_auroc=0.9511

[Epoch 02] train_loss=0.3227 | val_loss=0.2188 | val_mcc=0.7280 | val_f1=0.7807 | val_auroc=0.9537

[Epoch 03] train_loss=0.3008 | val_loss=0.2446 | val_mcc=0.7116 | val_f1=0.7667 | val_auroc=0.9553

[Epoch 04] train_loss=0.2813 | val_loss=0.2243 | val_mcc=0.7214 | val_f1=0.7760 | val_auroc=0.9556

[Epoch 05] train_loss=0.2646 | val_loss=0.2582 | val_mcc=0.6958 | val_f1=0.7539 | val_auroc=0.9531

[Epoch 06] train_loss=0.2412 | val_loss=0.2330 | val_mcc=0.7164 | val_f1=0.7719 | val_auroc=0.9534

[Epoch 07] train_loss=0.2173 | val_loss=0.2387 | val_mcc=0.7122 | val_f1=0.7687 | val_auroc=0.9514

[Epoch 08] train_loss=0.1998 | val_loss=0.2430 | val_mcc=0.7066 | val_f1=0.7644 | val_auroc=0.9496
[EarlyStop] epoch=8 | best_val_mcc=0.7280
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7342 | F1=0.8071 | AUROC=0.9440 | AUPRC=0.8813
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7736 | F1=0.8735 | AUROC=0.9614 | AUPRC=0.9523
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4194 | F1=0.7101 | AUROC=0.7523 | AUPRC=0.7379
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5370 | F1=0.7668 | AUROC=0.8628 | AUPRC=0.8419
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4449 | val_loss=0.2778 | val_mcc=0.6902 | val_f1=0.7471 | val_auroc=0.9551

[Epoch 02] train_loss=0.3187 | val_loss=0.2243 | val_mcc=0.7272 | val_f1=0.7803 | val_auroc=0.9576

[Epoch 03] train_loss=0.2991 | val_loss=0.2418 | val_mcc=0.7200 | val_f1=0.7735 | val_auroc=0.9580

[Epoch 04] train_loss=0.2829 | val_loss=0.2404 | val_mcc=0.7188 | val_f1=0.7730 | val_auroc=0.9574

[Epoch 05] train_loss=0.2653 | val_loss=0.2822 | val_mcc=0.6839 | val_f1=0.7419 | val_auroc=0.9532

[Epoch 06] train_loss=0.2465 | val_loss=0.2450 | val_mcc=0.7030 | val_f1=0.7611 | val_auroc=0.9515

[Epoch 07] train_loss=0.2077 | val_loss=0.2837 | val_mcc=0.6822 | val_f1=0.7434 | val_auroc=0.9471

[Epoch 08] train_loss=0.1854 | val_loss=0.2881 | val_mcc=0.6847 | val_f1=0.7459 | val_auroc=0.9444
[EarlyStop] epoch=8 | best_val_mcc=0.7272
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7367 | F1=0.8107 | AUROC=0.9488 | AUPRC=0.8904
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8284 | F1=0.9091 | AUROC=0.9652 | AUPRC=0.9572
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3975 | F1=0.7143 | AUROC=0.7501 | AUPRC=0.7307
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5190 | F1=0.7592 | AUROC=0.8657 | AUPRC=0.8468
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4672 | val_loss=0.2369 | val_mcc=0.7079 | val_f1=0.7653 | val_auroc=0.9520

[Epoch 02] train_loss=0.3333 | val_loss=0.2089 | val_mcc=0.7314 | val_f1=0.7812 | val_auroc=0.9559

[Epoch 03] train_loss=0.3002 | val_loss=0.2348 | val_mcc=0.7169 | val_f1=0.7722 | val_auroc=0.9544

[Epoch 04] train_loss=0.2865 | val_loss=0.2361 | val_mcc=0.7110 | val_f1=0.7677 | val_auroc=0.9550

[Epoch 05] train_loss=0.2667 | val_loss=0.2226 | val_mcc=0.7164 | val_f1=0.7720 | val_auroc=0.9541

[Epoch 06] train_loss=0.2435 | val_loss=0.2266 | val_mcc=0.7090 | val_f1=0.7653 | val_auroc=0.9502

[Epoch 07] train_loss=0.2076 | val_loss=0.2628 | val_mcc=0.6921 | val_f1=0.7528 | val_auroc=0.9460

[Epoch 08] train_loss=0.1848 | val_loss=0.2916 | val_mcc=0.6782 | val_f1=0.7418 | val_auroc=0.9420
[EarlyStop] epoch=8 | best_val_mcc=0.7314
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7385 | F1=0.8077 | AUROC=0.9473 | AUPRC=0.8854
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7413 | F1=0.8499 | AUROC=0.9599 | AUPRC=0.9535
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3912 | F1=0.6862 | AUROC=0.7570 | AUPRC=0.7320
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5638 | F1=0.7781 | AUROC=0.8612 | AUPRC=0.8370
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4462 | val_loss=0.2448 | val_mcc=0.7059 | val_f1=0.7635 | val_auroc=0.9527

[Epoch 02] train_loss=0.3241 | val_loss=0.2315 | val_mcc=0.7164 | val_f1=0.7718 | val_auroc=0.9549

[Epoch 03] train_loss=0.2953 | val_loss=0.2554 | val_mcc=0.7037 | val_f1=0.7595 | val_auroc=0.9556

[Epoch 04] train_loss=0.2741 | val_loss=0.2320 | val_mcc=0.7171 | val_f1=0.7724 | val_auroc=0.9553

[Epoch 05] train_loss=0.2530 | val_loss=0.2300 | val_mcc=0.7224 | val_f1=0.7768 | val_auroc=0.9532

[Epoch 06] train_loss=0.2256 | val_loss=0.2655 | val_mcc=0.6965 | val_f1=0.7550 | val_auroc=0.9504

[Epoch 07] train_loss=0.1968 | val_loss=0.2677 | val_mcc=0.6922 | val_f1=0.7527 | val_auroc=0.9467

[Epoch 08] train_loss=0.1664 | val_loss=0.2820 | val_mcc=0.6820 | val_f1=0.7448 | val_auroc=0.9421

[Epoch 09] train_loss=0.1436 | val_loss=0.3407 | val_mcc=0.6586 | val_f1=0.7234 | val_auroc=0.9415

[Epoch 10] train_loss=0.1124 | val_loss=0.3423 | val_mcc=0.6630 | val_f1=0.7285 | val_auroc=0.9395

[Epoch 11] train_loss=0.0966 | val_loss=0.3519 | val_mcc=0.6652 | val_f1=0.7309 | val_auroc=0.9373
[EarlyStop] epoch=11 | best_val_mcc=0.7224
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7244 | F1=0.8017 | AUROC=0.9401 | AUPRC=0.8750
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7683 | F1=0.8737 | AUROC=0.9599 | AUPRC=0.9462
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4031 | F1=0.7123 | AUROC=0.7489 | AUPRC=0.7365
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5196 | F1=0.7595 | AUROC=0.8590 | AUPRC=0.8383
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 199.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7595 | F1=0.8269 | AUROC=0.9608 | AUPRC=0.9138
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8506 | F1=0.9215 | AUROC=0.9826 | AUPRC=0.9831
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4046 | F1=0.7217 | AUROC=0.7702 | AUPRC=0.7517
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5397 | F1=0.7681 | AUROC=0.8841 | AUPRC=0.8652
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 114.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7438 | F1=0.8158 | AUROC=0.9519 | AUPRC=0.8983
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8197 | F1=0.9048 | AUROC=0.9671 | AUPRC=0.9664
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4081 | F1=0.7194 | AUROC=0.7641 | AUPRC=0.7471
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5422 | F1=0.7693 | AUROC=0.8738 | AUPRC=0.8485
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 99.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7369 | F1=0.8109 | AUROC=0.9499 | AUPRC=0.8931
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8497 | F1=0.9224 | AUROC=0.9658 | AUPRC=0.9612
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4011 | F1=0.7196 | AUROC=0.7608 | AUPRC=0.7463
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5365 | F1=0.7668 | AUROC=0.8754 | AUPRC=0.8556
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 78.
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7452 | F1=0.8168 | AUROC=0.9491 | AUPRC=0.8925
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8134 | F1=0.9024 | AUROC=0.9659 | AUPRC=0.9623
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.4105 | val_loss=0.2538 | val_mcc=0.7144 | val_f1=0.7691 | val_auroc=0.9562

[Epoch 02] train_loss=0.3029 | val_loss=0.2041 | val_mcc=0.7347 | val_f1=0.7837 | val_auroc=0.9576

[Epoch 03] train_loss=0.2786 | val_loss=0.2043 | val_mcc=0.7436 | val_f1=0.7903 | val_auroc=0.9579

[Epoch 04] train_loss=0.2596 | val_loss=0.2259 | val_mcc=0.7374 | val_f1=0.7887 | val_auroc=0.9589

[Epoch 05] train_loss=0.2415 | val_loss=0.2018 | val_mcc=0.7508 | val_f1=0.7971 | val_auroc=0.9600

[Epoch 06] train_loss=0.2180 | val_loss=0.2111 | val_mcc=0.7519 | val_f1=0.8004 | val_auroc=0.9610

[Epoch 07] train_loss=0.1977 | val_loss=0.2279 | val_mcc=0.7391 | val_f1=0.7902 | val_auroc=0.9583

[Epoch 08] train_loss=0.1783 | val_loss=0.2536 | val_mcc=0.7229 | val_f1=0.7769 | val_auroc=0.9563

[Epoch 09] train_loss=0.1568 | val_loss=0.2468 | val_mcc=0.7258 | val_f1=0.7796 | val_auroc=0.9552

[Epoch 10] train_loss=0.1301 | val_loss=0.3003 | val_mcc=0.7115 | val_f1=0.7670 | val_auroc=0.9533

[Epoch 11] train_loss=0.1015 | val_loss=0.2996 | val_mcc=0.7154 | val_f1=0.7704 | val_auroc=0.9534

[Epoch 12] train_loss=0.0903 | val_loss=0.3260 | val_mcc=0.7114 | val_f1=0.7667 | val_auroc=0.9527
[EarlyStop] epoch=12 | best_val_mcc=0.7519
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7486 | F1=0.8181 | AUROC=0.9536 | AUPRC=0.8938
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7923 | F1=0.8851 | AUROC=0.9731 | AUPRC=0.9744
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4141 | F1=0.7136 | AUROC=0.7602 | AUPRC=0.7391
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5366 | F1=0.7660 | AUROC=0.8734 | AUPRC=0.8505
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3985 | val_loss=0.2272 | val_mcc=0.7349 | val_f1=0.7868 | val_auroc=0.9565

[Epoch 02] train_loss=0.3030 | val_loss=0.2295 | val_mcc=0.7331 | val_f1=0.7850 | val_auroc=0.9574

[Epoch 03] train_loss=0.2794 | val_loss=0.2092 | val_mcc=0.7408 | val_f1=0.7912 | val_auroc=0.9584

[Epoch 04] train_loss=0.2623 | val_loss=0.2026 | val_mcc=0.7479 | val_f1=0.7964 | val_auroc=0.9596

[Epoch 05] train_loss=0.2454 | val_loss=0.2089 | val_mcc=0.7476 | val_f1=0.7962 | val_auroc=0.9592

[Epoch 06] train_loss=0.2214 | val_loss=0.2943 | val_mcc=0.7043 | val_f1=0.7583 | val_auroc=0.9546

[Epoch 07] train_loss=0.1992 | val_loss=0.2828 | val_mcc=0.7164 | val_f1=0.7698 | val_auroc=0.9566

[Epoch 08] train_loss=0.1785 | val_loss=0.2448 | val_mcc=0.7346 | val_f1=0.7865 | val_auroc=0.9561

[Epoch 09] train_loss=0.1475 | val_loss=0.3083 | val_mcc=0.7130 | val_f1=0.7684 | val_auroc=0.9508

[Epoch 10] train_loss=0.1327 | val_loss=0.3230 | val_mcc=0.7081 | val_f1=0.7650 | val_auroc=0.9490
[EarlyStop] epoch=10 | best_val_mcc=0.7479
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7530 | F1=0.8196 | AUROC=0.9516 | AUPRC=0.8901
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7647 | F1=0.8656 | AUROC=0.9699 | AUPRC=0.9704
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3893 | F1=0.6933 | AUROC=0.7583 | AUPRC=0.7360
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5378 | F1=0.7658 | AUROC=0.8647 | AUPRC=0.8399
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4095 | val_loss=0.2083 | val_mcc=0.7214 | val_f1=0.7696 | val_auroc=0.9569

[Epoch 02] train_loss=0.3019 | val_loss=0.2082 | val_mcc=0.7459 | val_f1=0.7955 | val_auroc=0.9598

[Epoch 03] train_loss=0.2817 | val_loss=0.2022 | val_mcc=0.7538 | val_f1=0.8019 | val_auroc=0.9617

[Epoch 04] train_loss=0.2601 | val_loss=0.2247 | val_mcc=0.7401 | val_f1=0.7905 | val_auroc=0.9594

[Epoch 05] train_loss=0.2422 | val_loss=0.2104 | val_mcc=0.7460 | val_f1=0.7957 | val_auroc=0.9607

[Epoch 06] train_loss=0.2201 | val_loss=0.2160 | val_mcc=0.7436 | val_f1=0.7938 | val_auroc=0.9592

[Epoch 07] train_loss=0.1971 | val_loss=0.2470 | val_mcc=0.7245 | val_f1=0.7786 | val_auroc=0.9548

[Epoch 08] train_loss=0.1616 | val_loss=0.2546 | val_mcc=0.7154 | val_f1=0.7702 | val_auroc=0.9536

[Epoch 09] train_loss=0.1479 | val_loss=0.2975 | val_mcc=0.7141 | val_f1=0.7692 | val_auroc=0.9535
[EarlyStop] epoch=9 | best_val_mcc=0.7538
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7597 | F1=0.8265 | AUROC=0.9552 | AUPRC=0.8988
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7934 | F1=0.8879 | AUROC=0.9740 | AUPRC=0.9742
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4124 | F1=0.7175 | AUROC=0.7667 | AUPRC=0.7447
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5294 | F1=0.7636 | AUROC=0.8749 | AUPRC=0.8498
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4051 | val_loss=0.2219 | val_mcc=0.7232 | val_f1=0.7775 | val_auroc=0.9565

[Epoch 02] train_loss=0.2998 | val_loss=0.2428 | val_mcc=0.7246 | val_f1=0.7770 | val_auroc=0.9578

[Epoch 03] train_loss=0.2762 | val_loss=0.2200 | val_mcc=0.7414 | val_f1=0.7918 | val_auroc=0.9596

[Epoch 04] train_loss=0.2529 | val_loss=0.2099 | val_mcc=0.7433 | val_f1=0.7935 | val_auroc=0.9599

[Epoch 05] train_loss=0.2334 | val_loss=0.2102 | val_mcc=0.7456 | val_f1=0.7951 | val_auroc=0.9591

[Epoch 06] train_loss=0.2106 | val_loss=0.2096 | val_mcc=0.7391 | val_f1=0.7894 | val_auroc=0.9598

[Epoch 07] train_loss=0.1856 | val_loss=0.2989 | val_mcc=0.7013 | val_f1=0.7552 | val_auroc=0.9579

[Epoch 08] train_loss=0.1583 | val_loss=0.2481 | val_mcc=0.7310 | val_f1=0.7837 | val_auroc=0.9574

[Epoch 09] train_loss=0.1293 | val_loss=0.2742 | val_mcc=0.7182 | val_f1=0.7735 | val_auroc=0.9536

[Epoch 10] train_loss=0.0981 | val_loss=0.3071 | val_mcc=0.7103 | val_f1=0.7665 | val_auroc=0.9534

[Epoch 11] train_loss=0.0812 | val_loss=0.3328 | val_mcc=0.7033 | val_f1=0.7609 | val_auroc=0.9512
[EarlyStop] epoch=11 | best_val_mcc=0.7456
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7554 | F1=0.8225 | AUROC=0.9534 | AUPRC=0.8949
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7777 | F1=0.8777 | AUROC=0.9676 | AUPRC=0.9678
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4047 | F1=0.7061 | AUROC=0.7561 | AUPRC=0.7379
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5451 | F1=0.7697 | AUROC=0.8703 | AUPRC=0.8398
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 182.
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7617 | F1=0.8285 | AUROC=0.9603 | AUPRC=0.9106
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8547 | F1=0.9222 | AUROC=0.9812 | AUPRC=0.9811
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3954 | F1=0.7176 | AUROC=0.7592 | AUPRC=0.7389
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5281 | F1=0.7629 | AUROC=0.8907 | AUPRC=0.8652
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 145.
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7561 | F1=0.8245 | AUROC=0.9585 | AUPRC=0.9069
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8159 | F1=0.9043 | AUROC=0.9750 | AUPRC=0.9749
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4142 | F1=0.7223 | AUROC=0.7672 | AUPRC=0.7420
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5147 | F1=0.7574 | AUROC=0.8808 | AUPRC=0.8562
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 79.
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7546 | F1=0.8234 | AUROC=0.9542 | AUPRC=0.9000
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8050 | F1=0.8978 | AUROC=0.9692 | AUPRC=0.9688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4199 | F1=0.7243 | AUROC=0.7642 | AUPRC=0.7425
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5347 | F1=0.7661 | AUROC=0.8812 | AUPRC=0.8578
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 113.
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7568 | F1=0.8250 | AUROC=0.9543 | AUPRC=0.8985
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8040 | F1=0.8946 | AUROC=0.9720 | AUPRC=0.9710
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4101 | F1=0.7211 | AUROC=0.7649 | AUPRC=0.7455
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4064 | val_loss=0.2311 | val_mcc=0.7244 | val_f1=0.7783 | val_auroc=0.9567

[Epoch 02] train_loss=0.3050 | val_loss=0.2074 | val_mcc=0.7404 | val_f1=0.7905 | val_auroc=0.9579

[Epoch 03] train_loss=0.2837 | val_loss=0.2023 | val_mcc=0.7430 | val_f1=0.7919 | val_auroc=0.9593

[Epoch 04] train_loss=0.2652 | val_loss=0.1974 | val_mcc=0.7463 | val_f1=0.7940 | val_auroc=0.9610

[Epoch 05] train_loss=0.2486 | val_loss=0.1995 | val_mcc=0.7489 | val_f1=0.7968 | val_auroc=0.9611

[Epoch 06] train_loss=0.2301 | val_loss=0.2030 | val_mcc=0.7530 | val_f1=0.8011 | val_auroc=0.9627

[Epoch 07] train_loss=0.2103 | val_loss=0.2231 | val_mcc=0.7441 | val_f1=0.7941 | val_auroc=0.9613

[Epoch 08] train_loss=0.1847 | val_loss=0.2252 | val_mcc=0.7382 | val_f1=0.7894 | val_auroc=0.9605

[Epoch 09] train_loss=0.1643 | val_loss=0.2299 | val_mcc=0.7378 | val_f1=0.7891 | val_auroc=0.9597

[Epoch 10] train_loss=0.1396 | val_loss=0.2604 | val_mcc=0.7278 | val_f1=0.7812 | val_auroc=0.9560

[Epoch 11] train_loss=0.1122 | val_loss=0.2689 | val_mcc=0.7258 | val_f1=0.7796 | val_auroc=0.9568

[Epoch 12] train_loss=0.0984 | val_loss=0.2970 | val_mcc=0.7145 | val_f1=0.7701 | val_auroc=0.9545
[EarlyStop] epoch=12 | best_val_mcc=0.7530
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7556 | F1=0.8229 | AUROC=0.9541 | AUPRC=0.8952
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7788 | F1=0.8769 | AUROC=0.9686 | AUPRC=0.9689
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4242 | F1=0.7160 | AUROC=0.7673 | AUPRC=0.7444
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5393 | F1=0.7674 | AUROC=0.8699 | AUPRC=0.8464
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4092 | val_loss=0.2171 | val_mcc=0.7173 | val_f1=0.7689 | val_auroc=0.9525

[Epoch 02] train_loss=0.3099 | val_loss=0.2301 | val_mcc=0.7322 | val_f1=0.7841 | val_auroc=0.9585

[Epoch 03] train_loss=0.2886 | val_loss=0.2045 | val_mcc=0.7404 | val_f1=0.7882 | val_auroc=0.9578

[Epoch 04] train_loss=0.2676 | val_loss=0.2318 | val_mcc=0.7343 | val_f1=0.7857 | val_auroc=0.9588

[Epoch 05] train_loss=0.2484 | val_loss=0.2290 | val_mcc=0.7377 | val_f1=0.7887 | val_auroc=0.9595

[Epoch 06] train_loss=0.2335 | val_loss=0.2382 | val_mcc=0.7306 | val_f1=0.7831 | val_auroc=0.9575

[Epoch 07] train_loss=0.2099 | val_loss=0.2602 | val_mcc=0.7263 | val_f1=0.7789 | val_auroc=0.9568

[Epoch 08] train_loss=0.1827 | val_loss=0.2758 | val_mcc=0.7219 | val_f1=0.7759 | val_auroc=0.9546

[Epoch 09] train_loss=0.1636 | val_loss=0.2686 | val_mcc=0.7236 | val_f1=0.7778 | val_auroc=0.9528
[EarlyStop] epoch=9 | best_val_mcc=0.7404
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7543 | F1=0.8187 | AUROC=0.9520 | AUPRC=0.8912
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7495 | F1=0.8517 | AUROC=0.9669 | AUPRC=0.9658
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4062 | F1=0.6949 | AUROC=0.7625 | AUPRC=0.7454
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5662 | F1=0.7783 | AUROC=0.8694 | AUPRC=0.8400
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4090 | val_loss=0.2131 | val_mcc=0.7304 | val_f1=0.7827 | val_auroc=0.9571

[Epoch 02] train_loss=0.3048 | val_loss=0.2149 | val_mcc=0.7110 | val_f1=0.7576 | val_auroc=0.9555

[Epoch 03] train_loss=0.2833 | val_loss=0.2043 | val_mcc=0.7374 | val_f1=0.7855 | val_auroc=0.9583

[Epoch 04] train_loss=0.2648 | val_loss=0.2007 | val_mcc=0.7403 | val_f1=0.7892 | val_auroc=0.9602

[Epoch 05] train_loss=0.2471 | val_loss=0.1980 | val_mcc=0.7446 | val_f1=0.7910 | val_auroc=0.9618

[Epoch 06] train_loss=0.2230 | val_loss=0.2232 | val_mcc=0.7380 | val_f1=0.7893 | val_auroc=0.9589

[Epoch 07] train_loss=0.1950 | val_loss=0.2509 | val_mcc=0.7295 | val_f1=0.7825 | val_auroc=0.9561

[Epoch 08] train_loss=0.1707 | val_loss=0.2484 | val_mcc=0.7333 | val_f1=0.7855 | val_auroc=0.9563

[Epoch 09] train_loss=0.1453 | val_loss=0.2545 | val_mcc=0.7349 | val_f1=0.7869 | val_auroc=0.9547

[Epoch 10] train_loss=0.1126 | val_loss=0.2921 | val_mcc=0.7117 | val_f1=0.7683 | val_auroc=0.9498

[Epoch 11] train_loss=0.0978 | val_loss=0.3383 | val_mcc=0.7044 | val_f1=0.7619 | val_auroc=0.9470
[EarlyStop] epoch=11 | best_val_mcc=0.7446
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7618 | F1=0.8232 | AUROC=0.9549 | AUPRC=0.8951
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7495 | F1=0.8517 | AUROC=0.9699 | AUPRC=0.9703
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4081 | F1=0.6926 | AUROC=0.7611 | AUPRC=0.7355
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5705 | F1=0.7794 | AUROC=0.8722 | AUPRC=0.8417
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4087 | val_loss=0.2416 | val_mcc=0.7079 | val_f1=0.7652 | val_auroc=0.9520

[Epoch 02] train_loss=0.3073 | val_loss=0.2254 | val_mcc=0.7267 | val_f1=0.7801 | val_auroc=0.9574

[Epoch 03] train_loss=0.2828 | val_loss=0.2153 | val_mcc=0.7406 | val_f1=0.7914 | val_auroc=0.9595

[Epoch 04] train_loss=0.2629 | val_loss=0.2153 | val_mcc=0.7378 | val_f1=0.7891 | val_auroc=0.9575

[Epoch 05] train_loss=0.2446 | val_loss=0.2222 | val_mcc=0.7405 | val_f1=0.7906 | val_auroc=0.9615

[Epoch 06] train_loss=0.2240 | val_loss=0.2225 | val_mcc=0.7410 | val_f1=0.7912 | val_auroc=0.9611

[Epoch 07] train_loss=0.1984 | val_loss=0.2289 | val_mcc=0.7382 | val_f1=0.7894 | val_auroc=0.9594

[Epoch 08] train_loss=0.1737 | val_loss=0.2291 | val_mcc=0.7394 | val_f1=0.7904 | val_auroc=0.9595

[Epoch 09] train_loss=0.1449 | val_loss=0.2794 | val_mcc=0.7170 | val_f1=0.7713 | val_auroc=0.9565

[Epoch 10] train_loss=0.1178 | val_loss=0.2777 | val_mcc=0.7163 | val_f1=0.7718 | val_auroc=0.9547

[Epoch 11] train_loss=0.0902 | val_loss=0.3030 | val_mcc=0.7157 | val_f1=0.7706 | val_auroc=0.9546

[Epoch 12] train_loss=0.0742 | val_loss=0.3108 | val_mcc=0.7099 | val_f1=0.7668 | val_auroc=0.9518
[EarlyStop] epoch=12 | best_val_mcc=0.7410
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7495 | F1=0.8198 | AUROC=0.9549 | AUPRC=0.8982
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7831 | F1=0.8849 | AUROC=0.9693 | AUPRC=0.9710
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3957 | F1=0.7130 | AUROC=0.7653 | AUPRC=0.7420
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5554 | F1=0.7753 | AUROC=0.8805 | AUPRC=0.8485
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 186.
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7558 | F1=0.8243 | AUROC=0.9598 | AUPRC=0.9090
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8524 | F1=0.9203 | AUROC=0.9820 | AUPRC=0.9815
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3889 | F1=0.7140 | AUROC=0.7598 | AUPRC=0.7340
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5369 | F1=0.7670 | AUROC=0.8929 | AUPRC=0.8704
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 151.
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7534 | F1=0.8226 | AUROC=0.9551 | AUPRC=0.9016
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8284 | F1=0.9091 | AUROC=0.9752 | AUPRC=0.9751
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4151 | F1=0.7242 | AUROC=0.7696 | AUPRC=0.7567
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5251 | F1=0.7619 | AUROC=0.8860 | AUPRC=0.8651
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 86.
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7530 | F1=0.8223 | AUROC=0.9554 | AUPRC=0.9002
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8162 | F1=0.9040 | AUROC=0.9695 | AUPRC=0.9699
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4281 | F1=0.7292 | AUROC=0.7685 | AUPRC=0.7488
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5263 | F1=0.7624 | AUROC=0.8767 | AUPRC=0.8479
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 104.
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7554 | F1=0.8240 | AUROC=0.9544 | AUPRC=0.9013
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8194 | F1=0.9050 | AUROC=0.9706 | AUPRC=0.9703
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4074 | F1=0.7205 | AUROC=0.7674 | AUPRC=0.7528
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4166 | val_loss=0.2145 | val_mcc=0.7276 | val_f1=0.7771 | val_auroc=0.9544

[Epoch 02] train_loss=0.3034 | val_loss=0.2342 | val_mcc=0.7247 | val_f1=0.7785 | val_auroc=0.9555

[Epoch 03] train_loss=0.2698 | val_loss=0.2346 | val_mcc=0.7272 | val_f1=0.7800 | val_auroc=0.9569

[Epoch 04] train_loss=0.2454 | val_loss=0.2490 | val_mcc=0.7156 | val_f1=0.7703 | val_auroc=0.9557

[Epoch 05] train_loss=0.2176 | val_loss=0.2481 | val_mcc=0.7166 | val_f1=0.7714 | val_auroc=0.9545

[Epoch 06] train_loss=0.1820 | val_loss=0.2695 | val_mcc=0.7087 | val_f1=0.7639 | val_auroc=0.9554

[Epoch 07] train_loss=0.1612 | val_loss=0.2543 | val_mcc=0.7203 | val_f1=0.7750 | val_auroc=0.9544
[EarlyStop] epoch=7 | best_val_mcc=0.7276
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7521 | F1=0.8157 | AUROC=0.9497 | AUPRC=0.8868
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7495 | F1=0.8517 | AUROC=0.9654 | AUPRC=0.9643
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4069 | F1=0.6897 | AUROC=0.7627 | AUPRC=0.7359
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5752 | F1=0.7818 | AUROC=0.8752 | AUPRC=0.8421
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4258 | val_loss=0.2686 | val_mcc=0.6988 | val_f1=0.7552 | val_auroc=0.9542

[Epoch 02] train_loss=0.3084 | val_loss=0.2483 | val_mcc=0.7188 | val_f1=0.7721 | val_auroc=0.9578

[Epoch 03] train_loss=0.2822 | val_loss=0.2114 | val_mcc=0.7443 | val_f1=0.7942 | val_auroc=0.9582

[Epoch 04] train_loss=0.2540 | val_loss=0.2330 | val_mcc=0.7329 | val_f1=0.7852 | val_auroc=0.9552

[Epoch 05] train_loss=0.2318 | val_loss=0.2339 | val_mcc=0.7286 | val_f1=0.7818 | val_auroc=0.9547

[Epoch 06] train_loss=0.2006 | val_loss=0.3054 | val_mcc=0.6911 | val_f1=0.7481 | val_auroc=0.9512

[Epoch 07] train_loss=0.1671 | val_loss=0.2715 | val_mcc=0.7115 | val_f1=0.7677 | val_auroc=0.9457

[Epoch 08] train_loss=0.1243 | val_loss=0.4046 | val_mcc=0.6697 | val_f1=0.7297 | val_auroc=0.9447

[Epoch 09] train_loss=0.1005 | val_loss=0.3747 | val_mcc=0.6896 | val_f1=0.7499 | val_auroc=0.9425
[EarlyStop] epoch=9 | best_val_mcc=0.7443
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7577 | F1=0.8247 | AUROC=0.9536 | AUPRC=0.8924
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7981 | F1=0.8882 | AUROC=0.9721 | AUPRC=0.9707
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4036 | F1=0.7082 | AUROC=0.7539 | AUPRC=0.7328
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5459 | F1=0.7708 | AUROC=0.8678 | AUPRC=0.8394
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4192 | val_loss=0.2157 | val_mcc=0.7188 | val_f1=0.7694 | val_auroc=0.9537

[Epoch 02] train_loss=0.2997 | val_loss=0.2115 | val_mcc=0.7265 | val_f1=0.7771 | val_auroc=0.9551

[Epoch 03] train_loss=0.2761 | val_loss=0.2098 | val_mcc=0.7332 | val_f1=0.7826 | val_auroc=0.9554

[Epoch 04] train_loss=0.2500 | val_loss=0.2076 | val_mcc=0.7429 | val_f1=0.7922 | val_auroc=0.9571

[Epoch 05] train_loss=0.2187 | val_loss=0.2153 | val_mcc=0.7420 | val_f1=0.7904 | val_auroc=0.9564

[Epoch 06] train_loss=0.1853 | val_loss=0.2478 | val_mcc=0.7207 | val_f1=0.7754 | val_auroc=0.9517

[Epoch 07] train_loss=0.1575 | val_loss=0.2824 | val_mcc=0.7156 | val_f1=0.7713 | val_auroc=0.9509

[Epoch 08] train_loss=0.1183 | val_loss=0.2855 | val_mcc=0.7082 | val_f1=0.7655 | val_auroc=0.9479

[Epoch 09] train_loss=0.0822 | val_loss=0.3624 | val_mcc=0.6835 | val_f1=0.7453 | val_auroc=0.9439

[Epoch 10] train_loss=0.0622 | val_loss=0.3728 | val_mcc=0.6896 | val_f1=0.7507 | val_auroc=0.9422
[EarlyStop] epoch=10 | best_val_mcc=0.7429
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7549 | F1=0.8215 | AUROC=0.9516 | AUPRC=0.8896
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7622 | F1=0.8638 | AUROC=0.9693 | AUPRC=0.9704
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4119 | F1=0.7070 | AUROC=0.7557 | AUPRC=0.7338
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5665 | F1=0.7790 | AUROC=0.8690 | AUPRC=0.8335
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4032 | val_loss=0.2260 | val_mcc=0.7254 | val_f1=0.7793 | val_auroc=0.9577

[Epoch 02] train_loss=0.2961 | val_loss=0.2315 | val_mcc=0.7267 | val_f1=0.7798 | val_auroc=0.9581

[Epoch 03] train_loss=0.2662 | val_loss=0.2231 | val_mcc=0.7273 | val_f1=0.7807 | val_auroc=0.9577

[Epoch 04] train_loss=0.2365 | val_loss=0.2565 | val_mcc=0.7138 | val_f1=0.7670 | val_auroc=0.9576

[Epoch 05] train_loss=0.2028 | val_loss=0.2472 | val_mcc=0.7209 | val_f1=0.7748 | val_auroc=0.9558

[Epoch 06] train_loss=0.1677 | val_loss=0.2836 | val_mcc=0.7022 | val_f1=0.7586 | val_auroc=0.9546

[Epoch 07] train_loss=0.1304 | val_loss=0.2955 | val_mcc=0.7013 | val_f1=0.7592 | val_auroc=0.9497

[Epoch 08] train_loss=0.0920 | val_loss=0.3058 | val_mcc=0.7006 | val_f1=0.7585 | val_auroc=0.9507

[Epoch 09] train_loss=0.0745 | val_loss=0.3351 | val_mcc=0.6980 | val_f1=0.7553 | val_auroc=0.9507
[EarlyStop] epoch=9 | best_val_mcc=0.7273
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7416 | F1=0.8140 | AUROC=0.9511 | AUPRC=0.8913
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7877 | F1=0.8848 | AUROC=0.9689 | AUPRC=0.9682
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4042 | F1=0.7156 | AUROC=0.7553 | AUPRC=0.7382
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5324 | F1=0.7651 | AUROC=0.8695 | AUPRC=0.8410
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 155.
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7513 | F1=0.8211 | AUROC=0.9595 | AUPRC=0.9086
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8604 | F1=0.9251 | AUROC=0.9805 | AUPRC=0.9803
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3853 | F1=0.7137 | AUROC=0.7553 | AUPRC=0.7293
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5362 | F1=0.7665 | AUROC=0.8936 | AUPRC=0.8688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 107.
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7512 | F1=0.8211 | AUROC=0.9558 | AUPRC=0.9018
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8227 | F1=0.9061 | AUROC=0.9767 | AUPRC=0.9765
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4163 | F1=0.7243 | AUROC=0.7664 | AUPRC=0.7405
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5334 | F1=0.7655 | AUROC=0.8820 | AUPRC=0.8567
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 69.
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7615 | F1=0.8283 | AUROC=0.9551 | AUPRC=0.9053
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8023 | F1=0.8961 | AUROC=0.9698 | AUPRC=0.9705
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4044 | F1=0.7191 | AUROC=0.7656 | AUPRC=0.7458
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5637 | F1=0.7790 | AUROC=0.8829 | AUPRC=0.8546
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 99.
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7447 | F1=0.8165 | AUROC=0.9537 | AUPRC=0.8976
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8029 | F1=0.8955 | AUROC=0.9720 | AUPRC=0.9705
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_cls_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4062 | F1=0.7177 | AUROC=0.7605 | AUPRC=0.7456
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.5548 | val_loss=0.3887 | val_mcc=0.4983 | val_f1=0.5869 | val_auroc=0.8347

[Epoch 02] train_loss=0.4828 | val_loss=0.4046 | val_mcc=0.5099 | val_f1=0.6090 | val_auroc=0.8557

[Epoch 03] train_loss=0.4427 | val_loss=0.3865 | val_mcc=0.5307 | val_f1=0.6258 | val_auroc=0.8730

[Epoch 04] train_loss=0.4073 | val_loss=0.4213 | val_mcc=0.5271 | val_f1=0.6223 | val_auroc=0.8784

[Epoch 05] train_loss=0.3718 | val_loss=0.3918 | val_mcc=0.5343 | val_f1=0.6289 | val_auroc=0.8773

[Epoch 06] train_loss=0.3350 | val_loss=0.4324 | val_mcc=0.5152 | val_f1=0.6133 | val_auroc=0.8728

[Epoch 07] train_loss=0.2924 | val_loss=0.4708 | val_mcc=0.5005 | val_f1=0.6023 | val_auroc=0.8649

[Epoch 08] train_loss=0.2492 | val_loss=0.4654 | val_mcc=0.5107 | val_f1=0.6106 | val_auroc=0.8631

[Epoch 09] train_loss=0.1968 | val_loss=0.5635 | val_mcc=0.4854 | val_f1=0.5895 | val_auroc=0.8602

[Epoch 10] train_loss=0.1380 | val_loss=0.5390 | val_mcc=0.4958 | val_f1=0.5992 | val_auroc=0.8569

[Epoch 11] train_loss=0.1135 | val_loss=0.6588 | val_mcc=0.4723 | val_f1=0.5793 | val_auroc=0.8550
[EarlyStop] epoch=11 | best_val_mcc=0.5343
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6011 | F1=0.7138 | AUROC=0.8884 | AUPRC=0.7871
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5260 | F1=0.7504 | AUROC=0.8529 | AUPRC=0.8566
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3999 | F1=0.6965 | AUROC=0.7485 | AUPRC=0.7277
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5474 | F1=0.7511 | AUROC=0.8557 | AUPRC=0.8318
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5632 | val_loss=0.5241 | val_mcc=0.4561 | val_f1=0.5680 | val_auroc=0.8336

[Epoch 02] train_loss=0.4888 | val_loss=0.4458 | val_mcc=0.5021 | val_f1=0.6040 | val_auroc=0.8589

[Epoch 03] train_loss=0.4522 | val_loss=0.4674 | val_mcc=0.5053 | val_f1=0.6042 | val_auroc=0.8718

[Epoch 04] train_loss=0.4103 | val_loss=0.4143 | val_mcc=0.5275 | val_f1=0.6236 | val_auroc=0.8732

[Epoch 05] train_loss=0.3795 | val_loss=0.3904 | val_mcc=0.5318 | val_f1=0.6256 | val_auroc=0.8727

[Epoch 06] train_loss=0.3389 | val_loss=0.5263 | val_mcc=0.4817 | val_f1=0.5848 | val_auroc=0.8627

[Epoch 07] train_loss=0.2874 | val_loss=0.4947 | val_mcc=0.4817 | val_f1=0.5881 | val_auroc=0.8514

[Epoch 08] train_loss=0.2341 | val_loss=0.6044 | val_mcc=0.4863 | val_f1=0.5918 | val_auroc=0.8478

[Epoch 09] train_loss=0.1927 | val_loss=0.6900 | val_mcc=0.4559 | val_f1=0.5679 | val_auroc=0.8391

[Epoch 10] train_loss=0.1208 | val_loss=0.8032 | val_mcc=0.4670 | val_f1=0.5770 | val_auroc=0.8379

[Epoch 11] train_loss=0.0952 | val_loss=0.9409 | val_mcc=0.4640 | val_f1=0.5736 | val_auroc=0.8353
[EarlyStop] epoch=11 | best_val_mcc=0.5318
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6019 | F1=0.7106 | AUROC=0.8858 | AUPRC=0.7737
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5333 | F1=0.7414 | AUROC=0.8497 | AUPRC=0.8415
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3594 | F1=0.6609 | AUROC=0.7368 | AUPRC=0.7201
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5415 | F1=0.7374 | AUROC=0.8515 | AUPRC=0.8237
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5505 | val_loss=0.4013 | val_mcc=0.4862 | val_f1=0.5874 | val_auroc=0.8408

[Epoch 02] train_loss=0.4835 | val_loss=0.3984 | val_mcc=0.5176 | val_f1=0.6156 | val_auroc=0.8623

[Epoch 03] train_loss=0.4503 | val_loss=0.3519 | val_mcc=0.5381 | val_f1=0.6258 | val_auroc=0.8695

[Epoch 04] train_loss=0.4013 | val_loss=0.3917 | val_mcc=0.5307 | val_f1=0.6261 | val_auroc=0.8744

[Epoch 05] train_loss=0.3711 | val_loss=0.4614 | val_mcc=0.5068 | val_f1=0.6059 | val_auroc=0.8704

[Epoch 06] train_loss=0.3302 | val_loss=0.3847 | val_mcc=0.5413 | val_f1=0.6302 | val_auroc=0.8715

[Epoch 07] train_loss=0.2806 | val_loss=0.5025 | val_mcc=0.5012 | val_f1=0.6032 | val_auroc=0.8596

[Epoch 08] train_loss=0.2324 | val_loss=0.5206 | val_mcc=0.5011 | val_f1=0.6032 | val_auroc=0.8513

[Epoch 09] train_loss=0.1849 | val_loss=0.5758 | val_mcc=0.4939 | val_f1=0.5973 | val_auroc=0.8482

[Epoch 10] train_loss=0.1363 | val_loss=0.6708 | val_mcc=0.4820 | val_f1=0.5883 | val_auroc=0.8386

[Epoch 11] train_loss=0.0902 | val_loss=0.7969 | val_mcc=0.4758 | val_f1=0.5839 | val_auroc=0.8395

[Epoch 12] train_loss=0.0699 | val_loss=0.8452 | val_mcc=0.4833 | val_f1=0.5893 | val_auroc=0.8402
[EarlyStop] epoch=12 | best_val_mcc=0.5413
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5999 | F1=0.7050 | AUROC=0.8887 | AUPRC=0.7806
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5466 | F1=0.7392 | AUROC=0.8600 | AUPRC=0.8584
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4014 | F1=0.6716 | AUROC=0.7418 | AUPRC=0.7250
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5587 | F1=0.7432 | AUROC=0.8597 | AUPRC=0.8283
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5537 | val_loss=0.3986 | val_mcc=0.5009 | val_f1=0.5961 | val_auroc=0.8381

[Epoch 02] train_loss=0.4822 | val_loss=0.4168 | val_mcc=0.5126 | val_f1=0.6121 | val_auroc=0.8600

[Epoch 03] train_loss=0.4395 | val_loss=0.3982 | val_mcc=0.5271 | val_f1=0.6233 | val_auroc=0.8730

[Epoch 04] train_loss=0.4032 | val_loss=0.3951 | val_mcc=0.5287 | val_f1=0.6246 | val_auroc=0.8745

[Epoch 05] train_loss=0.3595 | val_loss=0.4600 | val_mcc=0.5002 | val_f1=0.6008 | val_auroc=0.8686

[Epoch 06] train_loss=0.3151 | val_loss=0.4061 | val_mcc=0.5124 | val_f1=0.6117 | val_auroc=0.8661

[Epoch 07] train_loss=0.2635 | val_loss=0.5478 | val_mcc=0.4659 | val_f1=0.5731 | val_auroc=0.8575

[Epoch 08] train_loss=0.2089 | val_loss=0.5678 | val_mcc=0.4804 | val_f1=0.5860 | val_auroc=0.8593

[Epoch 09] train_loss=0.1424 | val_loss=0.6372 | val_mcc=0.4662 | val_f1=0.5743 | val_auroc=0.8583

[Epoch 10] train_loss=0.1112 | val_loss=0.6586 | val_mcc=0.4702 | val_f1=0.5785 | val_auroc=0.8542
[EarlyStop] epoch=10 | best_val_mcc=0.5287
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6095 | F1=0.7206 | AUROC=0.8877 | AUPRC=0.7862
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5633 | F1=0.7695 | AUROC=0.8597 | AUPRC=0.8632
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3760 | F1=0.6900 | AUROC=0.7456 | AUPRC=0.7252
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5935 | F1=0.7795 | AUROC=0.8592 | AUPRC=0.8333
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 136.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5715 | F1=0.6955 | AUROC=0.8797 | AUPRC=0.7702
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5362 | F1=0.7655 | AUROC=0.8485 | AUPRC=0.8531
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3579 | F1=0.6806 | AUROC=0.7305 | AUPRC=0.7046
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5371 | F1=0.7552 | AUROC=0.8479 | AUPRC=0.8229
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 175.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5794 | F1=0.7006 | AUROC=0.8806 | AUPRC=0.7754
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5391 | F1=0.7672 | AUROC=0.8485 | AUPRC=0.8537
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3626 | F1=0.6850 | AUROC=0.7378 | AUPRC=0.7235
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5553 | F1=0.7617 | AUROC=0.8523 | AUPRC=0.8310
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 47.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5826 | F1=0.7028 | AUROC=0.8812 | AUPRC=0.7806
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5448 | F1=0.7681 | AUROC=0.8643 | AUPRC=0.8669
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3684 | F1=0.6851 | AUROC=0.7446 | AUPRC=0.7297
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5440 | F1=0.7551 | AUROC=0.8521 | AUPRC=0.8289
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 55.
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5950 | F1=0.7113 | AUROC=0.8858 | AUPRC=0.7881
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5562 | F1=0.7733 | AUROC=0.8601 | AUPRC=0.8639
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3833 | F1=0.6907 | AUROC=0.7469 | AUPRC=0.7283
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5423 | F1=0.7535 | AUROC=0.8563 | AUPRC=0.8364
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5545 | val_loss=0.4147 | val_mcc=0.4916 | val_f1=0.5908 | val_auroc=0.8350

[Epoch 02] train_loss=0.4865 | val_loss=0.3848 | val_mcc=0.5208 | val_f1=0.6148 | val_auroc=0.8578

[Epoch 03] train_loss=0.4509 | val_loss=0.4344 | val_mcc=0.5092 | val_f1=0.6088 | val_auroc=0.8678

[Epoch 04] train_loss=0.4219 | val_loss=0.4141 | val_mcc=0.5203 | val_f1=0.6178 | val_auroc=0.8753

[Epoch 05] train_loss=0.3960 | val_loss=0.4292 | val_mcc=0.5279 | val_f1=0.6227 | val_auroc=0.8821

[Epoch 06] train_loss=0.3691 | val_loss=0.4287 | val_mcc=0.5207 | val_f1=0.6176 | val_auroc=0.8726

[Epoch 07] train_loss=0.3407 | val_loss=0.3834 | val_mcc=0.5288 | val_f1=0.6227 | val_auroc=0.8751

[Epoch 08] train_loss=0.3159 | val_loss=0.4596 | val_mcc=0.5205 | val_f1=0.6177 | val_auroc=0.8704

[Epoch 09] train_loss=0.2866 | val_loss=0.4905 | val_mcc=0.5122 | val_f1=0.6111 | val_auroc=0.8670

[Epoch 10] train_loss=0.2607 | val_loss=0.4713 | val_mcc=0.5100 | val_f1=0.6101 | val_auroc=0.8642

[Epoch 11] train_loss=0.2321 | val_loss=0.5651 | val_mcc=0.4808 | val_f1=0.5875 | val_auroc=0.8535

[Epoch 12] train_loss=0.1944 | val_loss=0.5762 | val_mcc=0.4877 | val_f1=0.5923 | val_auroc=0.8581

[Epoch 13] train_loss=0.1739 | val_loss=0.6469 | val_mcc=0.4743 | val_f1=0.5814 | val_auroc=0.8494
[EarlyStop] epoch=13 | best_val_mcc=0.5288
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5824 | F1=0.6944 | AUROC=0.8867 | AUPRC=0.7676
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5174 | F1=0.7296 | AUROC=0.8593 | AUPRC=0.8481
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3451 | F1=0.6485 | AUROC=0.7428 | AUPRC=0.7224
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5351 | F1=0.7294 | AUROC=0.8605 | AUPRC=0.8327
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5556 | val_loss=0.3833 | val_mcc=0.5008 | val_f1=0.5889 | val_auroc=0.8413

[Epoch 02] train_loss=0.4840 | val_loss=0.3946 | val_mcc=0.5163 | val_f1=0.6141 | val_auroc=0.8656

[Epoch 03] train_loss=0.4519 | val_loss=0.3861 | val_mcc=0.5217 | val_f1=0.6188 | val_auroc=0.8743

[Epoch 04] train_loss=0.4182 | val_loss=0.4100 | val_mcc=0.5216 | val_f1=0.6189 | val_auroc=0.8769

[Epoch 05] train_loss=0.3887 | val_loss=0.4806 | val_mcc=0.5048 | val_f1=0.6024 | val_auroc=0.8759

[Epoch 06] train_loss=0.3629 | val_loss=0.4150 | val_mcc=0.5160 | val_f1=0.6146 | val_auroc=0.8685

[Epoch 07] train_loss=0.3270 | val_loss=0.5201 | val_mcc=0.4961 | val_f1=0.5975 | val_auroc=0.8643

[Epoch 08] train_loss=0.2891 | val_loss=0.5315 | val_mcc=0.5050 | val_f1=0.6058 | val_auroc=0.8638

[Epoch 09] train_loss=0.2697 | val_loss=0.5920 | val_mcc=0.4941 | val_f1=0.5960 | val_auroc=0.8622
[EarlyStop] epoch=9 | best_val_mcc=0.5217
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6125 | F1=0.7206 | AUROC=0.8928 | AUPRC=0.7873
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5684 | F1=0.7657 | AUROC=0.8718 | AUPRC=0.8709
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3910 | F1=0.6887 | AUROC=0.7559 | AUPRC=0.7334
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5607 | F1=0.7550 | AUROC=0.8640 | AUPRC=0.8388
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5519 | val_loss=0.4438 | val_mcc=0.4867 | val_f1=0.5917 | val_auroc=0.8380

[Epoch 02] train_loss=0.4883 | val_loss=0.4082 | val_mcc=0.5104 | val_f1=0.6103 | val_auroc=0.8627

[Epoch 03] train_loss=0.4502 | val_loss=0.3928 | val_mcc=0.5266 | val_f1=0.6230 | val_auroc=0.8751

[Epoch 04] train_loss=0.4164 | val_loss=0.3702 | val_mcc=0.5338 | val_f1=0.6277 | val_auroc=0.8775

[Epoch 05] train_loss=0.3928 | val_loss=0.3738 | val_mcc=0.5401 | val_f1=0.6320 | val_auroc=0.8778

[Epoch 06] train_loss=0.3593 | val_loss=0.3641 | val_mcc=0.5398 | val_f1=0.6300 | val_auroc=0.8811

[Epoch 07] train_loss=0.3268 | val_loss=0.4131 | val_mcc=0.5270 | val_f1=0.6221 | val_auroc=0.8753

[Epoch 08] train_loss=0.2989 | val_loss=0.4304 | val_mcc=0.5243 | val_f1=0.6184 | val_auroc=0.8693

[Epoch 09] train_loss=0.2722 | val_loss=0.4526 | val_mcc=0.5222 | val_f1=0.6185 | val_auroc=0.8669

[Epoch 10] train_loss=0.2253 | val_loss=0.5614 | val_mcc=0.5092 | val_f1=0.6095 | val_auroc=0.8608

[Epoch 11] train_loss=0.2050 | val_loss=0.6133 | val_mcc=0.5107 | val_f1=0.6107 | val_auroc=0.8613
[EarlyStop] epoch=11 | best_val_mcc=0.5401
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6193 | F1=0.7221 | AUROC=0.8918 | AUPRC=0.7856
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5394 | F1=0.7511 | AUROC=0.8573 | AUPRC=0.8494
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3933 | F1=0.6829 | AUROC=0.7443 | AUPRC=0.7228
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5469 | F1=0.7418 | AUROC=0.8632 | AUPRC=0.8363
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5566 | val_loss=0.3920 | val_mcc=0.4940 | val_f1=0.5881 | val_auroc=0.8366

[Epoch 02] train_loss=0.4892 | val_loss=0.3901 | val_mcc=0.5220 | val_f1=0.6176 | val_auroc=0.8617

[Epoch 03] train_loss=0.4507 | val_loss=0.3886 | val_mcc=0.5372 | val_f1=0.6311 | val_auroc=0.8770

[Epoch 04] train_loss=0.4193 | val_loss=0.3956 | val_mcc=0.5326 | val_f1=0.6275 | val_auroc=0.8790

[Epoch 05] train_loss=0.3937 | val_loss=0.3974 | val_mcc=0.5306 | val_f1=0.6260 | val_auroc=0.8800

[Epoch 06] train_loss=0.3646 | val_loss=0.4013 | val_mcc=0.5383 | val_f1=0.6319 | val_auroc=0.8792

[Epoch 07] train_loss=0.3328 | val_loss=0.4097 | val_mcc=0.5316 | val_f1=0.6268 | val_auroc=0.8760

[Epoch 08] train_loss=0.3025 | val_loss=0.4623 | val_mcc=0.5110 | val_f1=0.6103 | val_auroc=0.8712

[Epoch 09] train_loss=0.2679 | val_loss=0.4487 | val_mcc=0.5134 | val_f1=0.6122 | val_auroc=0.8619

[Epoch 10] train_loss=0.2399 | val_loss=0.4668 | val_mcc=0.5116 | val_f1=0.6105 | val_auroc=0.8630

[Epoch 11] train_loss=0.1959 | val_loss=0.5485 | val_mcc=0.4960 | val_f1=0.5990 | val_auroc=0.8596

[Epoch 12] train_loss=0.1771 | val_loss=0.5822 | val_mcc=0.5024 | val_f1=0.6036 | val_auroc=0.8618
[EarlyStop] epoch=12 | best_val_mcc=0.5383
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6070 | F1=0.7189 | AUROC=0.8944 | AUPRC=0.7875
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5619 | F1=0.7755 | AUROC=0.8704 | AUPRC=0.8633
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3582 | F1=0.6844 | AUROC=0.7436 | AUPRC=0.7234
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5501 | F1=0.7568 | AUROC=0.8617 | AUPRC=0.8353
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 153.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5806 | F1=0.7019 | AUROC=0.8834 | AUPRC=0.7772
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5590 | F1=0.7763 | AUROC=0.8514 | AUPRC=0.8521
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3600 | F1=0.6867 | AUROC=0.7360 | AUPRC=0.7153
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5524 | F1=0.7636 | AUROC=0.8559 | AUPRC=0.8293
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 96.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5704 | F1=0.6944 | AUROC=0.8828 | AUPRC=0.7800
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5368 | F1=0.7592 | AUROC=0.8561 | AUPRC=0.8612
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3533 | F1=0.6757 | AUROC=0.7464 | AUPRC=0.7319
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5216 | F1=0.7419 | AUROC=0.8509 | AUPRC=0.8338
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 60.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5781 | F1=0.6995 | AUROC=0.8863 | AUPRC=0.7798
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5307 | F1=0.7591 | AUROC=0.8647 | AUPRC=0.8726
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4013 | F1=0.6975 | AUROC=0.7496 | AUPRC=0.7343
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5498 | F1=0.7588 | AUROC=0.8615 | AUPRC=0.8353
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 61.
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5925 | F1=0.7094 | AUROC=0.8876 | AUPRC=0.7866
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5534 | F1=0.7715 | AUROC=0.8648 | AUPRC=0.8660
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3775 | F1=0.6905 | AUROC=0.7454 | AUPRC=0.7278
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5685 | F1=0.7680 | AUROC=0.8618 | AUPRC=0.8365
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5591 | val_loss=0.4393 | val_mcc=0.4852 | val_f1=0.5895 | val_auroc=0.8376

[Epoch 02] train_loss=0.4910 | val_loss=0.4051 | val_mcc=0.5169 | val_f1=0.6144 | val_auroc=0.8606

[Epoch 03] train_loss=0.4532 | val_loss=0.3881 | val_mcc=0.5295 | val_f1=0.6249 | val_auroc=0.8727

[Epoch 04] train_loss=0.4234 | val_loss=0.4034 | val_mcc=0.5325 | val_f1=0.6269 | val_auroc=0.8806

[Epoch 05] train_loss=0.3946 | val_loss=0.3828 | val_mcc=0.5400 | val_f1=0.6332 | val_auroc=0.8809

[Epoch 06] train_loss=0.3681 | val_loss=0.4016 | val_mcc=0.5365 | val_f1=0.6305 | val_auroc=0.8828

[Epoch 07] train_loss=0.3373 | val_loss=0.4460 | val_mcc=0.5205 | val_f1=0.6169 | val_auroc=0.8772

[Epoch 08] train_loss=0.3091 | val_loss=0.4372 | val_mcc=0.5236 | val_f1=0.6206 | val_auroc=0.8746

[Epoch 09] train_loss=0.2786 | val_loss=0.4781 | val_mcc=0.5125 | val_f1=0.6116 | val_auroc=0.8703

[Epoch 10] train_loss=0.2367 | val_loss=0.5219 | val_mcc=0.5046 | val_f1=0.6047 | val_auroc=0.8685

[Epoch 11] train_loss=0.2165 | val_loss=0.5214 | val_mcc=0.5046 | val_f1=0.6055 | val_auroc=0.8664
[EarlyStop] epoch=11 | best_val_mcc=0.5400
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6112 | F1=0.7194 | AUROC=0.8919 | AUPRC=0.7871
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5559 | F1=0.7618 | AUROC=0.8677 | AUPRC=0.8613
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3805 | F1=0.6840 | AUROC=0.7490 | AUPRC=0.7179
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5595 | F1=0.7559 | AUROC=0.8637 | AUPRC=0.8378
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5604 | val_loss=0.4509 | val_mcc=0.4913 | val_f1=0.5944 | val_auroc=0.8341

[Epoch 02] train_loss=0.4908 | val_loss=0.4343 | val_mcc=0.5039 | val_f1=0.6054 | val_auroc=0.8630

[Epoch 03] train_loss=0.4553 | val_loss=0.3708 | val_mcc=0.5428 | val_f1=0.6338 | val_auroc=0.8771

[Epoch 04] train_loss=0.4176 | val_loss=0.4818 | val_mcc=0.5009 | val_f1=0.5992 | val_auroc=0.8782

[Epoch 05] train_loss=0.3907 | val_loss=0.4311 | val_mcc=0.5209 | val_f1=0.6179 | val_auroc=0.8779

[Epoch 06] train_loss=0.3605 | val_loss=0.4050 | val_mcc=0.5292 | val_f1=0.6243 | val_auroc=0.8779

[Epoch 07] train_loss=0.3266 | val_loss=0.5373 | val_mcc=0.4984 | val_f1=0.5982 | val_auroc=0.8719

[Epoch 08] train_loss=0.2845 | val_loss=0.5193 | val_mcc=0.5057 | val_f1=0.6066 | val_auroc=0.8653

[Epoch 09] train_loss=0.2621 | val_loss=0.5405 | val_mcc=0.5186 | val_f1=0.6167 | val_auroc=0.8667
[EarlyStop] epoch=9 | best_val_mcc=0.5428
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6093 | F1=0.7148 | AUROC=0.8897 | AUPRC=0.7897
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5574 | F1=0.7524 | AUROC=0.8642 | AUPRC=0.8674
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3761 | F1=0.6688 | AUROC=0.7464 | AUPRC=0.7253
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5498 | F1=0.7421 | AUROC=0.8615 | AUPRC=0.8407
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5575 | val_loss=0.4985 | val_mcc=0.4674 | val_f1=0.5771 | val_auroc=0.8386

[Epoch 02] train_loss=0.4887 | val_loss=0.3975 | val_mcc=0.5081 | val_f1=0.6076 | val_auroc=0.8571

[Epoch 03] train_loss=0.4510 | val_loss=0.4167 | val_mcc=0.5133 | val_f1=0.6124 | val_auroc=0.8732

[Epoch 04] train_loss=0.4222 | val_loss=0.3871 | val_mcc=0.5321 | val_f1=0.6272 | val_auroc=0.8817

[Epoch 05] train_loss=0.3918 | val_loss=0.3932 | val_mcc=0.5457 | val_f1=0.6378 | val_auroc=0.8834

[Epoch 06] train_loss=0.3617 | val_loss=0.3822 | val_mcc=0.5423 | val_f1=0.6345 | val_auroc=0.8799

[Epoch 07] train_loss=0.3272 | val_loss=0.4177 | val_mcc=0.5244 | val_f1=0.6200 | val_auroc=0.8681

[Epoch 08] train_loss=0.2960 | val_loss=0.4870 | val_mcc=0.5159 | val_f1=0.6146 | val_auroc=0.8723

[Epoch 09] train_loss=0.2659 | val_loss=0.4846 | val_mcc=0.5107 | val_f1=0.6091 | val_auroc=0.8568

[Epoch 10] train_loss=0.2196 | val_loss=0.5487 | val_mcc=0.5102 | val_f1=0.6097 | val_auroc=0.8603

[Epoch 11] train_loss=0.1981 | val_loss=0.6325 | val_mcc=0.4997 | val_f1=0.6022 | val_auroc=0.8548
[EarlyStop] epoch=11 | best_val_mcc=0.5457
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6068 | F1=0.7177 | AUROC=0.8939 | AUPRC=0.7927
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5715 | F1=0.7750 | AUROC=0.8642 | AUPRC=0.8657
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3668 | F1=0.6803 | AUROC=0.7453 | AUPRC=0.7230
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5585 | F1=0.7575 | AUROC=0.8629 | AUPRC=0.8397
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5575 | val_loss=0.4830 | val_mcc=0.4727 | val_f1=0.5814 | val_auroc=0.8389

[Epoch 02] train_loss=0.4856 | val_loss=0.4245 | val_mcc=0.5092 | val_f1=0.6095 | val_auroc=0.8635

[Epoch 03] train_loss=0.4469 | val_loss=0.3917 | val_mcc=0.5334 | val_f1=0.6282 | val_auroc=0.8753

[Epoch 04] train_loss=0.4171 | val_loss=0.4204 | val_mcc=0.5306 | val_f1=0.6244 | val_auroc=0.8815

[Epoch 05] train_loss=0.3891 | val_loss=0.4190 | val_mcc=0.5244 | val_f1=0.6202 | val_auroc=0.8809

[Epoch 06] train_loss=0.3600 | val_loss=0.4692 | val_mcc=0.5075 | val_f1=0.6041 | val_auroc=0.8777

[Epoch 07] train_loss=0.3290 | val_loss=0.4475 | val_mcc=0.5150 | val_f1=0.6133 | val_auroc=0.8744

[Epoch 08] train_loss=0.2860 | val_loss=0.4499 | val_mcc=0.5164 | val_f1=0.6146 | val_auroc=0.8731

[Epoch 09] train_loss=0.2610 | val_loss=0.5250 | val_mcc=0.4986 | val_f1=0.5987 | val_auroc=0.8714
[EarlyStop] epoch=9 | best_val_mcc=0.5334
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6026 | F1=0.7149 | AUROC=0.8899 | AUPRC=0.7878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5456 | F1=0.7626 | AUROC=0.8642 | AUPRC=0.8637
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3879 | F1=0.6885 | AUROC=0.7474 | AUPRC=0.7236
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5474 | F1=0.7511 | AUROC=0.8583 | AUPRC=0.8355
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 178.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5693 | F1=0.6942 | AUROC=0.8799 | AUPRC=0.7687
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5447 | F1=0.7695 | AUROC=0.8437 | AUPRC=0.8457
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3585 | F1=0.6862 | AUROC=0.7324 | AUPRC=0.7108
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5304 | F1=0.7534 | AUROC=0.8478 | AUPRC=0.8257
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 119.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5883 | F1=0.7069 | AUROC=0.8862 | AUPRC=0.7807
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5448 | F1=0.7708 | AUROC=0.8568 | AUPRC=0.8581
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3804 | F1=0.6916 | AUROC=0.7415 | AUPRC=0.7248
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5412 | F1=0.7556 | AUROC=0.8581 | AUPRC=0.8350
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 65.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5774 | F1=0.6989 | AUROC=0.8821 | AUPRC=0.7743
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5309 | F1=0.7570 | AUROC=0.8515 | AUPRC=0.8562
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3788 | F1=0.6878 | AUROC=0.7434 | AUPRC=0.7238
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5406 | F1=0.7518 | AUROC=0.8518 | AUPRC=0.8282
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 56.
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5946 | F1=0.7110 | AUROC=0.8860 | AUPRC=0.7854
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5907 | F1=0.7882 | AUROC=0.8693 | AUPRC=0.8670
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3789 | F1=0.6901 | AUROC=0.7495 | AUPRC=0.7403
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ProteinGym | MCC=0.5357 | F1=0.7504 | AUROC=0.8553 | AUPRC=0.8353
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.6996 | val_loss=0.5956 | val_mcc=0.0830 | val_f1=0.1978 | val_auroc=0.5725

[Epoch 02] train_loss=0.6822 | val_loss=0.7178 | val_mcc=0.0740 | val_f1=0.3257 | val_auroc=0.5802

[Epoch 03] train_loss=0.6736 | val_loss=0.6039 | val_mcc=0.0950 | val_f1=0.2691 | val_auroc=0.5934

[Epoch 04] train_loss=0.6600 | val_loss=0.6397 | val_mcc=0.1053 | val_f1=0.3157 | val_auroc=0.5963

[Epoch 05] train_loss=0.6383 | val_loss=0.6735 | val_mcc=0.0968 | val_f1=0.3202 | val_auroc=0.5843

[Epoch 06] train_loss=0.6091 | val_loss=0.6533 | val_mcc=0.1049 | val_f1=0.3199 | val_auroc=0.5933

[Epoch 07] train_loss=0.5648 | val_loss=0.6618 | val_mcc=0.1156 | val_f1=0.3278 | val_auroc=0.6004

[Epoch 08] train_loss=0.5131 | val_loss=0.7437 | val_mcc=0.0958 | val_f1=0.3217 | val_auroc=0.5858

[Epoch 09] train_loss=0.4481 | val_loss=0.8179 | val_mcc=0.1019 | val_f1=0.3273 | val_auroc=0.5889

[Epoch 10] train_loss=0.3873 | val_loss=0.9613 | val_mcc=0.0925 | val_f1=0.3272 | val_auroc=0.5844

[Epoch 11] train_loss=0.3165 | val_loss=1.0657 | val_mcc=0.0967 | val_f1=0.3297 | val_auroc=0.5901

[Epoch 12] train_loss=0.2425 | val_loss=0.9884 | val_mcc=0.0982 | val_f1=0.3203 | val_auroc=0.5869

[Epoch 13] train_loss=0.2075 | val_loss=1.1347 | val_mcc=0.0877 | val_f1=0.3193 | val_auroc=0.5856
[EarlyStop] epoch=13 | best_val_mcc=0.1156
[Test] train3__val_mean_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.1122 | F1=0.3933 | AUROC=0.5876 | AUPRC=0.3421
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.0834 | F1=0.5031 | AUROC=0.5547 | AUPRC=0.5485
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.0564 | F1=0.4874 | AUROC=0.5595 | AUPRC=0.5489
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.0634 | F1=0.4782 | AUROC=0.5523 | AUPRC=0.4979
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 34.
[Test] train3__val_mean_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.0821 | F1=0.3815 | AUROC=0.5646 | AUPRC=0.3294
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.0662 | F1=0.5060 | AUROC=0.5464 | AUPRC=0.5516
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.0772 | F1=0.5229 | AUROC=0.5481 | AUPRC=0.5429
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.0442 | F1=0.4719 | AUROC=0.5408 | AUPRC=0.4832
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 38.
[Test] train3__val_mean_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.0756 | F1=0.3849 | AUROC=0.5627 | AUPRC=0.3262
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.0983 | F1=0.5491 | AUROC=0.5871 | AUPRC=0.5683
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.0457 | F1=0.5160 | AUROC=0.5328 | AUPRC=0.5170
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.0611 | F1=0.5050 | AUROC=0.5426 | AUPRC=0.4811
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4776 | val_loss=0.2736 | val_mcc=0.6694 | val_f1=0.7338 | val_auroc=0.9408

[Epoch 02] train_loss=0.3650 | val_loss=0.2810 | val_mcc=0.6653 | val_f1=0.7294 | val_auroc=0.9419

[Epoch 03] train_loss=0.3447 | val_loss=0.2809 | val_mcc=0.6634 | val_f1=0.7277 | val_auroc=0.9435

[Epoch 04] train_loss=0.3328 | val_loss=0.3093 | val_mcc=0.6578 | val_f1=0.7198 | val_auroc=0.9431

[Epoch 05] train_loss=0.3177 | val_loss=0.2783 | val_mcc=0.6686 | val_f1=0.7324 | val_auroc=0.9415

[Epoch 06] train_loss=0.2934 | val_loss=0.3003 | val_mcc=0.6543 | val_f1=0.7204 | val_auroc=0.9384

[Epoch 07] train_loss=0.2847 | val_loss=0.3100 | val_mcc=0.6552 | val_f1=0.7197 | val_auroc=0.9395
[EarlyStop] epoch=7 | best_val_mcc=0.6694
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.6769 | F1=0.7688 | AUROC=0.9272 | AUPRC=0.8330
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7936 | F1=0.8919 | AUROC=0.9614 | AUPRC=0.9641
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3423 | F1=0.6905 | AUROC=0.7076 | AUPRC=0.6819
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4424 | F1=0.7273 | AUROC=0.8072 | AUPRC=0.7411
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 133.
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7027 | F1=0.7869 | AUROC=0.9418 | AUPRC=0.8683
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8227 | F1=0.9061 | AUROC=0.9759 | AUPRC=0.9762
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3540 | F1=0.6949 | AUROC=0.7285 | AUPRC=0.7031
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4573 | F1=0.7333 | AUROC=0.8447 | AUPRC=0.8111
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 105.
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6781 | F1=0.7697 | AUROC=0.9286 | AUPRC=0.8382
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8143 | F1=0.9015 | AUROC=0.9687 | AUPRC=0.9703
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3178 | F1=0.6784 | AUROC=0.7076 | AUPRC=0.6770
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v1_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4529 | F1=0.7315 | AUROC=0.8175 | AUPRC=0.7597
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.6921 | val_loss=0.6936 | val_mcc=0.1108 | val_f1=0.3404 | val_auroc=0.6131

[Epoch 02] train_loss=0.6767 | val_loss=0.7180 | val_mcc=0.1018 | val_f1=0.3346 | val_auroc=0.6077

[Epoch 03] train_loss=0.6692 | val_loss=0.6600 | val_mcc=0.1472 | val_f1=0.3586 | val_auroc=0.6398

[Epoch 04] train_loss=0.6625 | val_loss=0.6558 | val_mcc=0.1096 | val_f1=0.3309 | val_auroc=0.6194

[Epoch 05] train_loss=0.6600 | val_loss=0.6286 | val_mcc=0.1936 | val_f1=0.3773 | val_auroc=0.6568

[Epoch 06] train_loss=0.6510 | val_loss=0.5969 | val_mcc=0.1974 | val_f1=0.3732 | val_auroc=0.6518

[Epoch 07] train_loss=0.6439 | val_loss=0.6204 | val_mcc=0.1822 | val_f1=0.3713 | val_auroc=0.6547

[Epoch 08] train_loss=0.6394 | val_loss=0.6265 | val_mcc=0.2043 | val_f1=0.3877 | val_auroc=0.6704

[Epoch 09] train_loss=0.6338 | val_loss=0.5504 | val_mcc=0.2608 | val_f1=0.3867 | val_auroc=0.6863

[Epoch 10] train_loss=0.6269 | val_loss=0.5975 | val_mcc=0.2229 | val_f1=0.3962 | val_auroc=0.6834

[Epoch 11] train_loss=0.6193 | val_loss=0.5854 | val_mcc=0.2525 | val_f1=0.4104 | val_auroc=0.7003

[Epoch 12] train_loss=0.6128 | val_loss=0.5616 | val_mcc=0.2697 | val_f1=0.4170 | val_auroc=0.7027

[Epoch 13] train_loss=0.6117 | val_loss=0.5919 | val_mcc=0.2549 | val_f1=0.4209 | val_auroc=0.7024

[Epoch 14] train_loss=0.6019 | val_loss=0.5531 | val_mcc=0.2736 | val_f1=0.4212 | val_auroc=0.7118

[Epoch 15] train_loss=0.5983 | val_loss=0.5486 | val_mcc=0.2829 | val_f1=0.4284 | val_auroc=0.7182

[Epoch 16] train_loss=0.5890 | val_loss=0.6334 | val_mcc=0.2442 | val_f1=0.4172 | val_auroc=0.7232

[Epoch 17] train_loss=0.5820 | val_loss=0.6085 | val_mcc=0.2739 | val_f1=0.4367 | val_auroc=0.7247

[Epoch 18] train_loss=0.5748 | val_loss=0.5740 | val_mcc=0.2797 | val_f1=0.4365 | val_auroc=0.7247

[Epoch 19] train_loss=0.5684 | val_loss=0.5166 | val_mcc=0.2659 | val_f1=0.4148 | val_auroc=0.7142

[Epoch 20] train_loss=0.5584 | val_loss=0.5417 | val_mcc=0.2842 | val_f1=0.4373 | val_auroc=0.7240

[Epoch 21] train_loss=0.5534 | val_loss=0.6523 | val_mcc=0.2629 | val_f1=0.4296 | val_auroc=0.7328

[Epoch 22] train_loss=0.5500 | val_loss=0.5278 | val_mcc=0.3043 | val_f1=0.4514 | val_auroc=0.7330

[Epoch 23] train_loss=0.5418 | val_loss=0.6020 | val_mcc=0.2741 | val_f1=0.4370 | val_auroc=0.7297

[Epoch 24] train_loss=0.5372 | val_loss=0.5449 | val_mcc=0.3056 | val_f1=0.4535 | val_auroc=0.7383

[Epoch 25] train_loss=0.5329 | val_loss=0.5609 | val_mcc=0.3028 | val_f1=0.4554 | val_auroc=0.7402

[Epoch 26] train_loss=0.5302 | val_loss=0.5534 | val_mcc=0.3115 | val_f1=0.4596 | val_auroc=0.7432

[Epoch 27] train_loss=0.5278 | val_loss=0.5993 | val_mcc=0.2877 | val_f1=0.4462 | val_auroc=0.7374

[Epoch 28] train_loss=0.5216 | val_loss=0.5521 | val_mcc=0.3124 | val_f1=0.4603 | val_auroc=0.7444

[Epoch 29] train_loss=0.5192 | val_loss=0.5483 | val_mcc=0.3141 | val_f1=0.4619 | val_auroc=0.7426

[Epoch 30] train_loss=0.5139 | val_loss=0.5581 | val_mcc=0.3164 | val_f1=0.4651 | val_auroc=0.7475
[Test] train3__val_mean_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.3316 | F1=0.5284 | AUROC=0.7409 | AUPRC=0.5647
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.3186 | F1=0.6330 | AUROC=0.7333 | AUPRC=0.7304
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.2286 | F1=0.5877 | AUROC=0.6580 | AUPRC=0.6516
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.3184 | F1=0.6136 | AUROC=0.7125 | AUPRC=0.6762
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 389.
[Test] train3__val_mean_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.3463 | F1=0.5456 | AUROC=0.7562 | AUPRC=0.5569
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.4053 | F1=0.6975 | AUROC=0.7690 | AUPRC=0.7690
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.2363 | F1=0.6141 | AUROC=0.6608 | AUPRC=0.6555
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.3161 | F1=0.6436 | AUROC=0.7226 | AUPRC=0.6765
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 96.
[Test] train3__val_mean_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.2016 | F1=0.4410 | AUROC=0.6460 | AUPRC=0.4688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.1934 | F1=0.5535 | AUROC=0.6234 | AUPRC=0.6583
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.1641 | F1=0.5306 | AUROC=0.5871 | AUPRC=0.6146
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.2047 | F1=0.5421 | AUROC=0.6380 | AUPRC=0.6188
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4813 | val_loss=0.2752 | val_mcc=0.6675 | val_f1=0.7324 | val_auroc=0.9383

[Epoch 02] train_loss=0.3739 | val_loss=0.2617 | val_mcc=0.6714 | val_f1=0.7362 | val_auroc=0.9413

[Epoch 03] train_loss=0.3613 | val_loss=0.2822 | val_mcc=0.6717 | val_f1=0.7335 | val_auroc=0.9443

[Epoch 04] train_loss=0.3528 | val_loss=0.2436 | val_mcc=0.6942 | val_f1=0.7544 | val_auroc=0.9454

[Epoch 05] train_loss=0.3471 | val_loss=0.2857 | val_mcc=0.6635 | val_f1=0.7269 | val_auroc=0.9448

[Epoch 06] train_loss=0.3400 | val_loss=0.2553 | val_mcc=0.6874 | val_f1=0.7485 | val_auroc=0.9472

[Epoch 07] train_loss=0.3390 | val_loss=0.2816 | val_mcc=0.6700 | val_f1=0.7322 | val_auroc=0.9466

[Epoch 08] train_loss=0.3346 | val_loss=0.2437 | val_mcc=0.7030 | val_f1=0.7612 | val_auroc=0.9490

[Epoch 09] train_loss=0.3309 | val_loss=0.2492 | val_mcc=0.7004 | val_f1=0.7588 | val_auroc=0.9494

[Epoch 10] train_loss=0.3266 | val_loss=0.2438 | val_mcc=0.6997 | val_f1=0.7587 | val_auroc=0.9494

[Epoch 11] train_loss=0.3267 | val_loss=0.2453 | val_mcc=0.7042 | val_f1=0.7622 | val_auroc=0.9489

[Epoch 12] train_loss=0.3210 | val_loss=0.2447 | val_mcc=0.7065 | val_f1=0.7638 | val_auroc=0.9507

[Epoch 13] train_loss=0.3162 | val_loss=0.2509 | val_mcc=0.6985 | val_f1=0.7574 | val_auroc=0.9485

[Epoch 14] train_loss=0.3135 | val_loss=0.2530 | val_mcc=0.6996 | val_f1=0.7577 | val_auroc=0.9500

[Epoch 15] train_loss=0.3116 | val_loss=0.2731 | val_mcc=0.6896 | val_f1=0.7477 | val_auroc=0.9506

[Epoch 16] train_loss=0.3066 | val_loss=0.2391 | val_mcc=0.7075 | val_f1=0.7651 | val_auroc=0.9487

[Epoch 17] train_loss=0.3051 | val_loss=0.2641 | val_mcc=0.6882 | val_f1=0.7482 | val_auroc=0.9485

[Epoch 18] train_loss=0.3058 | val_loss=0.2775 | val_mcc=0.6834 | val_f1=0.7424 | val_auroc=0.9493

[Epoch 19] train_loss=0.2975 | val_loss=0.2456 | val_mcc=0.7043 | val_f1=0.7623 | val_auroc=0.9477

[Epoch 20] train_loss=0.2963 | val_loss=0.2627 | val_mcc=0.6997 | val_f1=0.7578 | val_auroc=0.9465

[Epoch 21] train_loss=0.2926 | val_loss=0.2593 | val_mcc=0.7006 | val_f1=0.7581 | val_auroc=0.9486

[Epoch 22] train_loss=0.2871 | val_loss=0.2578 | val_mcc=0.7034 | val_f1=0.7606 | val_auroc=0.9474
[EarlyStop] epoch=22 | best_val_mcc=0.7075
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.7083 | F1=0.7900 | AUROC=0.9358 | AUPRC=0.8559
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8050 | F1=0.8906 | AUROC=0.9698 | AUPRC=0.9704
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3511 | F1=0.6832 | AUROC=0.7207 | AUPRC=0.7089
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4826 | F1=0.7431 | AUROC=0.8332 | AUPRC=0.7843
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 167.
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7306 | F1=0.8064 | AUROC=0.9514 | AUPRC=0.8903
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8539 | F1=0.9226 | AUROC=0.9840 | AUPRC=0.9845
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3752 | F1=0.7075 | AUROC=0.7454 | AUPRC=0.7244
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5071 | F1=0.7539 | AUROC=0.8664 | AUPRC=0.8327
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 214.
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6808 | F1=0.7715 | AUROC=0.9342 | AUPRC=0.8561
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.7891 | F1=0.8876 | AUROC=0.9668 | AUPRC=0.9672
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3492 | F1=0.6921 | AUROC=0.7287 | AUPRC=0.7053
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v3_650m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4791 | F1=0.7422 | AUROC=0.8352 | AUPRC=0.7862
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.6993 | val_loss=0.6429 | val_mcc=0.0635 | val_f1=0.2436 | val_auroc=0.5776

[Epoch 02] train_loss=0.6868 | val_loss=0.7310 | val_mcc=0.0896 | val_f1=0.3358 | val_auroc=0.5812

[Epoch 03] train_loss=0.6844 | val_loss=0.6718 | val_mcc=0.0915 | val_f1=0.3176 | val_auroc=0.5838

[Epoch 04] train_loss=0.6814 | val_loss=0.7057 | val_mcc=0.0923 | val_f1=0.3330 | val_auroc=0.5880

[Epoch 05] train_loss=0.6775 | val_loss=0.6054 | val_mcc=0.0934 | val_f1=0.2525 | val_auroc=0.5952

[Epoch 06] train_loss=0.6733 | val_loss=0.6540 | val_mcc=0.1000 | val_f1=0.3173 | val_auroc=0.5913

[Epoch 07] train_loss=0.6682 | val_loss=0.7093 | val_mcc=0.1128 | val_f1=0.3434 | val_auroc=0.6086

[Epoch 08] train_loss=0.6608 | val_loss=0.6255 | val_mcc=0.1400 | val_f1=0.3375 | val_auroc=0.6161

[Epoch 09] train_loss=0.6491 | val_loss=0.6758 | val_mcc=0.1354 | val_f1=0.3490 | val_auroc=0.6249

[Epoch 10] train_loss=0.6357 | val_loss=0.6483 | val_mcc=0.1539 | val_f1=0.3578 | val_auroc=0.6353

[Epoch 11] train_loss=0.6200 | val_loss=0.6162 | val_mcc=0.1516 | val_f1=0.3487 | val_auroc=0.6351

[Epoch 12] train_loss=0.6024 | val_loss=0.7882 | val_mcc=0.1560 | val_f1=0.3654 | val_auroc=0.6419

[Epoch 13] train_loss=0.5849 | val_loss=0.7031 | val_mcc=0.1555 | val_f1=0.3621 | val_auroc=0.6361

[Epoch 14] train_loss=0.5612 | val_loss=0.6379 | val_mcc=0.1497 | val_f1=0.3489 | val_auroc=0.6351

[Epoch 15] train_loss=0.5407 | val_loss=0.7336 | val_mcc=0.1482 | val_f1=0.3580 | val_auroc=0.6287

[Epoch 16] train_loss=0.5115 | val_loss=0.6892 | val_mcc=0.1632 | val_f1=0.3621 | val_auroc=0.6381

[Epoch 17] train_loss=0.4855 | val_loss=0.7511 | val_mcc=0.1461 | val_f1=0.3545 | val_auroc=0.6287

[Epoch 18] train_loss=0.4550 | val_loss=0.8225 | val_mcc=0.1474 | val_f1=0.3579 | val_auroc=0.6242

[Epoch 19] train_loss=0.4316 | val_loss=0.9888 | val_mcc=0.1374 | val_f1=0.3560 | val_auroc=0.6217

[Epoch 20] train_loss=0.3991 | val_loss=0.8403 | val_mcc=0.1399 | val_f1=0.3494 | val_auroc=0.6182

[Epoch 21] train_loss=0.3594 | val_loss=0.9204 | val_mcc=0.1384 | val_f1=0.3515 | val_auroc=0.6187

[Epoch 22] train_loss=0.3319 | val_loss=0.9459 | val_mcc=0.1427 | val_f1=0.3524 | val_auroc=0.6188
[EarlyStop] epoch=22 | best_val_mcc=0.1632
[Test] train3__val_mean_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.1657 | F1=0.4264 | AUROC=0.6294 | AUPRC=0.3762
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.2291 | F1=0.5937 | AUROC=0.6451 | AUPRC=0.6267
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.0697 | F1=0.5171 | AUROC=0.5341 | AUPRC=0.5162
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.1457 | F1=0.5357 | AUROC=0.6002 | AUPRC=0.5516
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 55.
[Test] train3__val_mean_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.0728 | F1=0.3763 | AUROC=0.5697 | AUPRC=0.3338
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.0491 | F1=0.5000 | AUROC=0.5515 | AUPRC=0.5509
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=-0.0248 | F1=0.4837 | AUROC=0.4946 | AUPRC=0.5042
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.0440 | F1=0.4868 | AUROC=0.5326 | AUPRC=0.4869
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 57.
[Test] train3__val_mean_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.1111 | F1=0.4050 | AUROC=0.5810 | AUPRC=0.3363
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.1326 | F1=0.5698 | AUROC=0.5975 | AUPRC=0.5994
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.0518 | F1=0.5269 | AUROC=0.5434 | AUPRC=0.5540
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.0995 | F1=0.5258 | AUROC=0.5545 | AUPRC=0.5002
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4738 | val_loss=0.2534 | val_mcc=0.6869 | val_f1=0.7487 | val_auroc=0.9425

[Epoch 02] train_loss=0.3725 | val_loss=0.2619 | val_mcc=0.6847 | val_f1=0.7461 | val_auroc=0.9449

[Epoch 03] train_loss=0.3571 | val_loss=0.2838 | val_mcc=0.6692 | val_f1=0.7319 | val_auroc=0.9451

[Epoch 04] train_loss=0.3498 | val_loss=0.2753 | val_mcc=0.6757 | val_f1=0.7373 | val_auroc=0.9455

[Epoch 05] train_loss=0.3438 | val_loss=0.2484 | val_mcc=0.6924 | val_f1=0.7530 | val_auroc=0.9459

[Epoch 06] train_loss=0.3385 | val_loss=0.2859 | val_mcc=0.6679 | val_f1=0.7299 | val_auroc=0.9468

[Epoch 07] train_loss=0.3336 | val_loss=0.2687 | val_mcc=0.6810 | val_f1=0.7423 | val_auroc=0.9460

[Epoch 08] train_loss=0.3285 | val_loss=0.2802 | val_mcc=0.6751 | val_f1=0.7366 | val_auroc=0.9457

[Epoch 09] train_loss=0.3209 | val_loss=0.2797 | val_mcc=0.6749 | val_f1=0.7362 | val_auroc=0.9459

[Epoch 10] train_loss=0.3151 | val_loss=0.2595 | val_mcc=0.6838 | val_f1=0.7454 | val_auroc=0.9452

[Epoch 11] train_loss=0.3102 | val_loss=0.2673 | val_mcc=0.6782 | val_f1=0.7405 | val_auroc=0.9440
[EarlyStop] epoch=11 | best_val_mcc=0.6924
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_Test | MCC=0.6923 | F1=0.7792 | AUROC=0.9309 | AUPRC=0.8412
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7892 | F1=0.8838 | AUROC=0.9709 | AUPRC=0.9715
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3034 | F1=0.6628 | AUROC=0.7026 | AUPRC=0.6771
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.4720 | F1=0.7392 | AUROC=0.8211 | AUPRC=0.7678
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 165.
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7059 | F1=0.7891 | AUROC=0.9417 | AUPRC=0.8716
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8067 | F1=0.8962 | AUROC=0.9774 | AUPRC=0.9775
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3566 | F1=0.6983 | AUROC=0.7255 | AUPRC=0.6883
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4947 | F1=0.7487 | AUROC=0.8558 | AUPRC=0.8217
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 112.
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6847 | F1=0.7743 | AUROC=0.9322 | AUPRC=0.8434
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8348 | F1=0.9115 | AUROC=0.9719 | AUPRC=0.9738
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3446 | F1=0.6898 | AUROC=0.7200 | AUPRC=0.6889
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_spliceai_nt_v2_500m_None_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4829 | F1=0.7438 | AUROC=0.8266 | AUPRC=0.7718
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.5261 | val_loss=0.3898 | val_mcc=0.5516 | val_f1=0.6410 | val_auroc=0.8593

[Epoch 02] train_loss=0.4593 | val_loss=0.3752 | val_mcc=0.5664 | val_f1=0.6533 | val_auroc=0.8701

[Epoch 03] train_loss=0.4324 | val_loss=0.3779 | val_mcc=0.5716 | val_f1=0.6579 | val_auroc=0.8801

[Epoch 04] train_loss=0.4081 | val_loss=0.3579 | val_mcc=0.5814 | val_f1=0.6655 | val_auroc=0.8867

[Epoch 05] train_loss=0.3855 | val_loss=0.3474 | val_mcc=0.5807 | val_f1=0.6648 | val_auroc=0.8908

[Epoch 06] train_loss=0.3594 | val_loss=0.4081 | val_mcc=0.5569 | val_f1=0.6445 | val_auroc=0.8949

[Epoch 07] train_loss=0.3361 | val_loss=0.3719 | val_mcc=0.5734 | val_f1=0.6592 | val_auroc=0.8927

[Epoch 08] train_loss=0.3085 | val_loss=0.3942 | val_mcc=0.5617 | val_f1=0.6499 | val_auroc=0.8876

[Epoch 09] train_loss=0.2753 | val_loss=0.4176 | val_mcc=0.5567 | val_f1=0.6453 | val_auroc=0.8891

[Epoch 10] train_loss=0.2565 | val_loss=0.4069 | val_mcc=0.5622 | val_f1=0.6504 | val_auroc=0.8853
[EarlyStop] epoch=10 | best_val_mcc=0.5814
[Test] train3__val_mean_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6380 | F1=0.7385 | AUROC=0.9002 | AUPRC=0.8098
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5993 | F1=0.7923 | AUROC=0.8838 | AUPRC=0.8808
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4570 | F1=0.7139 | AUROC=0.7853 | AUPRC=0.7688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5930 | F1=0.7775 | AUROC=0.8733 | AUPRC=0.8501
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 231.
[Test] train3__val_mean_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6194 | F1=0.7283 | AUROC=0.9028 | AUPRC=0.8068
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.6015 | F1=0.8061 | AUROC=0.8842 | AUPRC=0.8787
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4569 | F1=0.7290 | AUROC=0.7829 | AUPRC=0.7666
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5713 | F1=0.7733 | AUROC=0.8756 | AUPRC=0.8531
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 135.
[Test] train3__val_mean_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6241 | F1=0.7311 | AUROC=0.8989 | AUPRC=0.8033
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5904 | F1=0.7901 | AUROC=0.8739 | AUPRC=0.8704
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4465 | F1=0.7177 | AUROC=0.7754 | AUPRC=0.7575
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5846 | F1=0.7761 | AUROC=0.8674 | AUPRC=0.8442
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.3931 | val_loss=0.2239 | val_mcc=0.7260 | val_f1=0.7797 | val_auroc=0.9574

[Epoch 02] train_loss=0.2967 | val_loss=0.2420 | val_mcc=0.7260 | val_f1=0.7775 | val_auroc=0.9612

[Epoch 03] train_loss=0.2764 | val_loss=0.2273 | val_mcc=0.7418 | val_f1=0.7910 | val_auroc=0.9627

[Epoch 04] train_loss=0.2617 | val_loss=0.2013 | val_mcc=0.7585 | val_f1=0.8056 | val_auroc=0.9640

[Epoch 05] train_loss=0.2463 | val_loss=0.2094 | val_mcc=0.7565 | val_f1=0.8038 | val_auroc=0.9652

[Epoch 06] train_loss=0.2318 | val_loss=0.1998 | val_mcc=0.7636 | val_f1=0.8097 | val_auroc=0.9648

[Epoch 07] train_loss=0.2149 | val_loss=0.2008 | val_mcc=0.7699 | val_f1=0.8148 | val_auroc=0.9648

[Epoch 08] train_loss=0.2023 | val_loss=0.2538 | val_mcc=0.7407 | val_f1=0.7887 | val_auroc=0.9648

[Epoch 09] train_loss=0.1827 | val_loss=0.1941 | val_mcc=0.7741 | val_f1=0.8179 | val_auroc=0.9641

[Epoch 10] train_loss=0.1664 | val_loss=0.2198 | val_mcc=0.7580 | val_f1=0.8052 | val_auroc=0.9621

[Epoch 11] train_loss=0.1491 | val_loss=0.2400 | val_mcc=0.7437 | val_f1=0.7934 | val_auroc=0.9600

[Epoch 12] train_loss=0.1312 | val_loss=0.2619 | val_mcc=0.7368 | val_f1=0.7874 | val_auroc=0.9585

[Epoch 13] train_loss=0.1159 | val_loss=0.2649 | val_mcc=0.7336 | val_f1=0.7855 | val_auroc=0.9566

[Epoch 14] train_loss=0.0938 | val_loss=0.2826 | val_mcc=0.7350 | val_f1=0.7861 | val_auroc=0.9580

[Epoch 15] train_loss=0.0827 | val_loss=0.3082 | val_mcc=0.7290 | val_f1=0.7808 | val_auroc=0.9575
[EarlyStop] epoch=15 | best_val_mcc=0.7741
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7766 | F1=0.8378 | AUROC=0.9583 | AUPRC=0.9099
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8080 | F1=0.8953 | AUROC=0.9752 | AUPRC=0.9743
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4120 | F1=0.7075 | AUROC=0.7722 | AUPRC=0.7548
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6167 | F1=0.8027 | AUROC=0.8872 | AUPRC=0.8507
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 146.
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7784 | F1=0.8402 | AUROC=0.9649 | AUPRC=0.9221
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8694 | F1=0.9329 | AUROC=0.9854 | AUPRC=0.9864
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4301 | F1=0.7347 | AUROC=0.7743 | AUPRC=0.7446
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5820 | F1=0.7868 | AUROC=0.9032 | AUPRC=0.8754
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 160.
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7729 | F1=0.8364 | AUROC=0.9577 | AUPRC=0.9092
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8314 | F1=0.9104 | AUROC=0.9771 | AUPRC=0.9771
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4137 | F1=0.7237 | AUROC=0.7770 | AUPRC=0.7623
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5818 | F1=0.7872 | AUROC=0.8901 | AUPRC=0.8541
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.5471 | val_loss=0.3891 | val_mcc=0.5107 | val_f1=0.6037 | val_auroc=0.8454

[Epoch 02] train_loss=0.4861 | val_loss=0.3786 | val_mcc=0.5206 | val_f1=0.6156 | val_auroc=0.8613

[Epoch 03] train_loss=0.4499 | val_loss=0.3663 | val_mcc=0.5320 | val_f1=0.6256 | val_auroc=0.8745

[Epoch 04] train_loss=0.4240 | val_loss=0.3946 | val_mcc=0.5323 | val_f1=0.6272 | val_auroc=0.8826

[Epoch 05] train_loss=0.3981 | val_loss=0.3926 | val_mcc=0.5290 | val_f1=0.6247 | val_auroc=0.8807

[Epoch 06] train_loss=0.3701 | val_loss=0.3721 | val_mcc=0.5416 | val_f1=0.6341 | val_auroc=0.8801

[Epoch 07] train_loss=0.3433 | val_loss=0.3734 | val_mcc=0.5359 | val_f1=0.6288 | val_auroc=0.8770

[Epoch 08] train_loss=0.3139 | val_loss=0.4263 | val_mcc=0.5207 | val_f1=0.6184 | val_auroc=0.8747

[Epoch 09] train_loss=0.2910 | val_loss=0.4547 | val_mcc=0.5194 | val_f1=0.6170 | val_auroc=0.8756

[Epoch 10] train_loss=0.2626 | val_loss=0.4526 | val_mcc=0.5000 | val_f1=0.6022 | val_auroc=0.8626

[Epoch 11] train_loss=0.2217 | val_loss=0.4793 | val_mcc=0.5173 | val_f1=0.6157 | val_auroc=0.8676

[Epoch 12] train_loss=0.2024 | val_loss=0.5123 | val_mcc=0.5111 | val_f1=0.6108 | val_auroc=0.8665
[EarlyStop] epoch=12 | best_val_mcc=0.5416
[Test] train3__val_mean_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6053 | F1=0.7147 | AUROC=0.8943 | AUPRC=0.7882
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5623 | F1=0.7634 | AUROC=0.8741 | AUPRC=0.8678
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3871 | F1=0.6812 | AUROC=0.7582 | AUPRC=0.7344
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5371 | F1=0.7390 | AUROC=0.8660 | AUPRC=0.8370
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 199.
[Test] train3__val_mean_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5833 | F1=0.7039 | AUROC=0.8875 | AUPRC=0.7792
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5561 | F1=0.7759 | AUROC=0.8630 | AUPRC=0.8645
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3613 | F1=0.6858 | AUROC=0.7379 | AUPRC=0.7221
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5513 | F1=0.7634 | AUROC=0.8558 | AUPRC=0.8266
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 114.
[Test] train3__val_mean_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5623 | F1=0.6891 | AUROC=0.8864 | AUPRC=0.7750
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4966 | F1=0.7401 | AUROC=0.8558 | AUPRC=0.8535
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3669 | F1=0.6832 | AUROC=0.7506 | AUPRC=0.7453
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5371 | F1=0.7513 | AUROC=0.8598 | AUPRC=0.8354
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.4143 | val_loss=0.2227 | val_mcc=0.7355 | val_f1=0.7873 | val_auroc=0.9583

[Epoch 02] train_loss=0.2985 | val_loss=0.2238 | val_mcc=0.7356 | val_f1=0.7866 | val_auroc=0.9609

[Epoch 03] train_loss=0.2770 | val_loss=0.2013 | val_mcc=0.7540 | val_f1=0.8021 | val_auroc=0.9632

[Epoch 04] train_loss=0.2585 | val_loss=0.1957 | val_mcc=0.7573 | val_f1=0.8046 | val_auroc=0.9640

[Epoch 05] train_loss=0.2391 | val_loss=0.2045 | val_mcc=0.7506 | val_f1=0.7994 | val_auroc=0.9635

[Epoch 06] train_loss=0.2246 | val_loss=0.1975 | val_mcc=0.7578 | val_f1=0.8051 | val_auroc=0.9647

[Epoch 07] train_loss=0.2056 | val_loss=0.2374 | val_mcc=0.7315 | val_f1=0.7823 | val_auroc=0.9629

[Epoch 08] train_loss=0.1851 | val_loss=0.2308 | val_mcc=0.7404 | val_f1=0.7911 | val_auroc=0.9601

[Epoch 09] train_loss=0.1696 | val_loss=0.2159 | val_mcc=0.7556 | val_f1=0.8033 | val_auroc=0.9622

[Epoch 10] train_loss=0.1509 | val_loss=0.2479 | val_mcc=0.7302 | val_f1=0.7827 | val_auroc=0.9587

[Epoch 11] train_loss=0.1264 | val_loss=0.2421 | val_mcc=0.7406 | val_f1=0.7914 | val_auroc=0.9597

[Epoch 12] train_loss=0.1147 | val_loss=0.2516 | val_mcc=0.7358 | val_f1=0.7876 | val_auroc=0.9573
[EarlyStop] epoch=12 | best_val_mcc=0.7578
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7650 | F1=0.8299 | AUROC=0.9579 | AUPRC=0.9049
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8261 | F1=0.9072 | AUROC=0.9716 | AUPRC=0.9721
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4443 | F1=0.7290 | AUROC=0.7657 | AUPRC=0.7350
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5772 | F1=0.7849 | AUROC=0.8849 | AUPRC=0.8554
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 158.
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7689 | F1=0.8335 | AUROC=0.9633 | AUPRC=0.9145
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8618 | F1=0.9276 | AUROC=0.9832 | AUPRC=0.9835
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4041 | F1=0.7209 | AUROC=0.7594 | AUPRC=0.7353
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5557 | F1=0.7752 | AUROC=0.8946 | AUPRC=0.8676
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 157.
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7505 | F1=0.8205 | AUROC=0.9560 | AUPRC=0.9046
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8295 | F1=0.9128 | AUROC=0.9733 | AUPRC=0.9745
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4271 | F1=0.7316 | AUROC=0.7622 | AUPRC=0.7329
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5564 | F1=0.7755 | AUROC=0.8852 | AUPRC=0.8608
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.5574 | val_loss=0.4206 | val_mcc=0.4791 | val_f1=0.5760 | val_auroc=0.8179

[Epoch 02] train_loss=0.5092 | val_loss=0.4257 | val_mcc=0.5015 | val_f1=0.6000 | val_auroc=0.8325

[Epoch 03] train_loss=0.4821 | val_loss=0.4166 | val_mcc=0.5115 | val_f1=0.6098 | val_auroc=0.8486

[Epoch 04] train_loss=0.4524 | val_loss=0.4344 | val_mcc=0.5237 | val_f1=0.6206 | val_auroc=0.8673

[Epoch 05] train_loss=0.4211 | val_loss=0.3930 | val_mcc=0.5344 | val_f1=0.6288 | val_auroc=0.8727

[Epoch 06] train_loss=0.4001 | val_loss=0.3739 | val_mcc=0.5468 | val_f1=0.6382 | val_auroc=0.8816

[Epoch 07] train_loss=0.3763 | val_loss=0.3801 | val_mcc=0.5520 | val_f1=0.6426 | val_auroc=0.8832

[Epoch 08] train_loss=0.3507 | val_loss=0.4260 | val_mcc=0.5275 | val_f1=0.6224 | val_auroc=0.8785

[Epoch 09] train_loss=0.3289 | val_loss=0.4595 | val_mcc=0.5240 | val_f1=0.6187 | val_auroc=0.8779

[Epoch 10] train_loss=0.3069 | val_loss=0.4326 | val_mcc=0.5267 | val_f1=0.6228 | val_auroc=0.8736

[Epoch 11] train_loss=0.2906 | val_loss=0.4442 | val_mcc=0.5161 | val_f1=0.6146 | val_auroc=0.8691

[Epoch 12] train_loss=0.2564 | val_loss=0.4743 | val_mcc=0.5223 | val_f1=0.6187 | val_auroc=0.8754

[Epoch 13] train_loss=0.2385 | val_loss=0.4650 | val_mcc=0.5210 | val_f1=0.6185 | val_auroc=0.8707
[EarlyStop] epoch=13 | best_val_mcc=0.5520
[Test] train3__val_mean_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5939 | F1=0.7066 | AUROC=0.8905 | AUPRC=0.7928
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5741 | F1=0.7774 | AUROC=0.8725 | AUPRC=0.8619
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4258 | F1=0.7038 | AUROC=0.7698 | AUPRC=0.7537
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5247 | F1=0.7309 | AUROC=0.8387 | AUPRC=0.8131
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 218.
[Test] train3__val_mean_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5649 | F1=0.6895 | AUROC=0.8788 | AUPRC=0.7669
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5678 | F1=0.7841 | AUROC=0.8546 | AUPRC=0.8415
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3879 | F1=0.6955 | AUROC=0.7566 | AUPRC=0.7340
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4813 | F1=0.7186 | AUROC=0.8272 | AUPRC=0.7962
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 184.
[Test] train3__val_mean_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5514 | F1=0.6777 | AUROC=0.8662 | AUPRC=0.7507
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5477 | F1=0.7679 | AUROC=0.8500 | AUPRC=0.8259
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3794 | F1=0.6781 | AUROC=0.7487 | AUPRC=0.7270
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4634 | F1=0.7036 | AUROC=0.8156 | AUPRC=0.7857
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.3958 | val_loss=0.2227 | val_mcc=0.7322 | val_f1=0.7847 | val_auroc=0.9566

[Epoch 02] train_loss=0.3069 | val_loss=0.2226 | val_mcc=0.7373 | val_f1=0.7882 | val_auroc=0.9608

[Epoch 03] train_loss=0.2886 | val_loss=0.2061 | val_mcc=0.7507 | val_f1=0.7994 | val_auroc=0.9620

[Epoch 04] train_loss=0.2741 | val_loss=0.2228 | val_mcc=0.7397 | val_f1=0.7896 | val_auroc=0.9639

[Epoch 05] train_loss=0.2609 | val_loss=0.2280 | val_mcc=0.7362 | val_f1=0.7860 | val_auroc=0.9644

[Epoch 06] train_loss=0.2469 | val_loss=0.1974 | val_mcc=0.7616 | val_f1=0.8081 | val_auroc=0.9652

[Epoch 07] train_loss=0.2313 | val_loss=0.2236 | val_mcc=0.7413 | val_f1=0.7899 | val_auroc=0.9660

[Epoch 08] train_loss=0.2179 | val_loss=0.2210 | val_mcc=0.7489 | val_f1=0.7972 | val_auroc=0.9640

[Epoch 09] train_loss=0.2022 | val_loss=0.2137 | val_mcc=0.7537 | val_f1=0.8013 | val_auroc=0.9646

[Epoch 10] train_loss=0.1922 | val_loss=0.2140 | val_mcc=0.7615 | val_f1=0.8080 | val_auroc=0.9627

[Epoch 11] train_loss=0.1727 | val_loss=0.2334 | val_mcc=0.7467 | val_f1=0.7952 | val_auroc=0.9634

[Epoch 12] train_loss=0.1613 | val_loss=0.2379 | val_mcc=0.7413 | val_f1=0.7908 | val_auroc=0.9624
[EarlyStop] epoch=12 | best_val_mcc=0.7616
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7747 | F1=0.8371 | AUROC=0.9590 | AUPRC=0.9123
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8352 | F1=0.9113 | AUROC=0.9753 | AUPRC=0.9729
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4120 | F1=0.7162 | AUROC=0.7741 | AUPRC=0.7445
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5693 | F1=0.7814 | AUROC=0.8782 | AUPRC=0.8443
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 218.
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7757 | F1=0.8384 | AUROC=0.9640 | AUPRC=0.9222
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8623 | F1=0.9272 | AUROC=0.9863 | AUPRC=0.9863
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4274 | F1=0.7302 | AUROC=0.7720 | AUPRC=0.7430
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5451 | F1=0.7707 | AUROC=0.8923 | AUPRC=0.8606
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 211.
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7523 | F1=0.8218 | AUROC=0.9561 | AUPRC=0.9094
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8214 | F1=0.9075 | AUROC=0.9765 | AUPRC=0.9753
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3960 | F1=0.7165 | AUROC=0.7635 | AUPRC=0.7415
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5402 | F1=0.7686 | AUROC=0.8757 | AUPRC=0.8496
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.5645 | val_loss=0.4333 | val_mcc=0.5428 | val_f1=0.6273 | val_auroc=0.8266

[Epoch 02] train_loss=0.4946 | val_loss=0.3833 | val_mcc=0.5792 | val_f1=0.6522 | val_auroc=0.8443

[Epoch 03] train_loss=0.4781 | val_loss=0.3594 | val_mcc=0.5783 | val_f1=0.6538 | val_auroc=0.8513

[Epoch 04] train_loss=0.4646 | val_loss=0.3982 | val_mcc=0.5704 | val_f1=0.6541 | val_auroc=0.8555

[Epoch 05] train_loss=0.4559 | val_loss=0.3717 | val_mcc=0.5676 | val_f1=0.6509 | val_auroc=0.8588

[Epoch 06] train_loss=0.4508 | val_loss=0.4008 | val_mcc=0.5571 | val_f1=0.6462 | val_auroc=0.8628

[Epoch 07] train_loss=0.4423 | val_loss=0.3891 | val_mcc=0.5589 | val_f1=0.6476 | val_auroc=0.8651

[Epoch 08] train_loss=0.4378 | val_loss=0.3695 | val_mcc=0.5774 | val_f1=0.6611 | val_auroc=0.8687
[EarlyStop] epoch=8 | best_val_mcc=0.5792
[Test] train3__val_mean_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5988 | F1=0.6928 | AUROC=0.8438 | AUPRC=0.7714
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5406 | F1=0.7258 | AUROC=0.8100 | AUPRC=0.8441
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3920 | F1=0.6449 | AUROC=0.7306 | AUPRC=0.7453
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5279 | F1=0.7096 | AUROC=0.8013 | AUPRC=0.8151
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 437.
[Test] train3__val_mean_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6085 | F1=0.7193 | AUROC=0.8911 | AUPRC=0.8079
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5935 | F1=0.7900 | AUROC=0.8842 | AUPRC=0.8810
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3879 | F1=0.6890 | AUROC=0.7579 | AUPRC=0.7562
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5392 | F1=0.7466 | AUROC=0.8563 | AUPRC=0.8474
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 192.
[Test] train3__val_mean_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5908 | F1=0.7055 | AUROC=0.8876 | AUPRC=0.8045
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5483 | F1=0.7644 | AUROC=0.8666 | AUPRC=0.8733
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3884 | F1=0.6832 | AUROC=0.7605 | AUPRC=0.7637
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5377 | F1=0.7453 | AUROC=0.8511 | AUPRC=0.8392
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.3941 | val_loss=0.2350 | val_mcc=0.7250 | val_f1=0.7778 | val_auroc=0.9591

[Epoch 02] train_loss=0.3053 | val_loss=0.2387 | val_mcc=0.7226 | val_f1=0.7749 | val_auroc=0.9615

[Epoch 03] train_loss=0.2938 | val_loss=0.2138 | val_mcc=0.7387 | val_f1=0.7893 | val_auroc=0.9634

[Epoch 04] train_loss=0.2819 | val_loss=0.2048 | val_mcc=0.7462 | val_f1=0.7958 | val_auroc=0.9640

[Epoch 05] train_loss=0.2763 | val_loss=0.2035 | val_mcc=0.7475 | val_f1=0.7968 | val_auroc=0.9642

[Epoch 06] train_loss=0.2716 | val_loss=0.1993 | val_mcc=0.7502 | val_f1=0.7990 | val_auroc=0.9652

[Epoch 07] train_loss=0.2675 | val_loss=0.2590 | val_mcc=0.7148 | val_f1=0.7651 | val_auroc=0.9651

[Epoch 08] train_loss=0.2675 | val_loss=0.1937 | val_mcc=0.7569 | val_f1=0.8044 | val_auroc=0.9656

[Epoch 09] train_loss=0.2593 | val_loss=0.1925 | val_mcc=0.7584 | val_f1=0.8055 | val_auroc=0.9653

[Epoch 10] train_loss=0.2569 | val_loss=0.2075 | val_mcc=0.7573 | val_f1=0.8041 | val_auroc=0.9666

[Epoch 11] train_loss=0.2534 | val_loss=0.2186 | val_mcc=0.7476 | val_f1=0.7955 | val_auroc=0.9669

[Epoch 12] train_loss=0.2496 | val_loss=0.2047 | val_mcc=0.7558 | val_f1=0.8028 | val_auroc=0.9671

[Epoch 13] train_loss=0.2455 | val_loss=0.2015 | val_mcc=0.7563 | val_f1=0.8033 | val_auroc=0.9673

[Epoch 14] train_loss=0.2386 | val_loss=0.1837 | val_mcc=0.7620 | val_f1=0.8082 | val_auroc=0.9671

[Epoch 15] train_loss=0.2370 | val_loss=0.1917 | val_mcc=0.7601 | val_f1=0.8069 | val_auroc=0.9668

[Epoch 16] train_loss=0.2350 | val_loss=0.2095 | val_mcc=0.7531 | val_f1=0.8003 | val_auroc=0.9673

[Epoch 17] train_loss=0.2304 | val_loss=0.2353 | val_mcc=0.7372 | val_f1=0.7855 | val_auroc=0.9674

[Epoch 18] train_loss=0.2288 | val_loss=0.2022 | val_mcc=0.7616 | val_f1=0.8077 | val_auroc=0.9673

[Epoch 19] train_loss=0.2243 | val_loss=0.2004 | val_mcc=0.7617 | val_f1=0.8078 | val_auroc=0.9672

[Epoch 20] train_loss=0.2218 | val_loss=0.2105 | val_mcc=0.7556 | val_f1=0.8024 | val_auroc=0.9669
[EarlyStop] epoch=20 | best_val_mcc=0.7620
[Test] train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7728 | F1=0.8348 | AUROC=0.9567 | AUPRC=0.9119
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7960 | F1=0.8862 | AUROC=0.9718 | AUPRC=0.9705
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4137 | F1=0.7106 | AUROC=0.7702 | AUPRC=0.7660
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5808 | F1=0.7863 | AUROC=0.8795 | AUPRC=0.8594
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 202.
[Test] train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7791 | F1=0.8408 | AUROC=0.9641 | AUPRC=0.9229
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8611 | F1=0.9283 | AUROC=0.9809 | AUPRC=0.9810
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4339 | F1=0.7338 | AUROC=0.7819 | AUPRC=0.7823
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5475 | F1=0.7717 | AUROC=0.8944 | AUPRC=0.8730
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 206.
[Test] train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7742 | F1=0.8373 | AUROC=0.9597 | AUPRC=0.9155
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8550 | F1=0.9262 | AUROC=0.9769 | AUPRC=0.9776
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4126 | F1=0.7240 | AUROC=0.7796 | AUPRC=0.7621
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_prot_spliceai_None_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5646 | F1=0.7792 | AUROC=0.8881 | AUPRC=0.8647
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test

[Epoch 01] train_loss=0.5327 | val_loss=0.4203 | val_mcc=0.5392 | val_f1=0.6325 | val_auroc=0.8568

[Epoch 02] train_loss=0.4581 | val_loss=0.3888 | val_mcc=0.5579 | val_f1=0.6471 | val_auroc=0.8675

[Epoch 03] train_loss=0.4255 | val_loss=0.3963 | val_mcc=0.5681 | val_f1=0.6551 | val_auroc=0.8770

[Epoch 04] train_loss=0.3927 | val_loss=0.3697 | val_mcc=0.5686 | val_f1=0.6555 | val_auroc=0.8806

[Epoch 05] train_loss=0.3541 | val_loss=0.4326 | val_mcc=0.5558 | val_f1=0.6435 | val_auroc=0.8850

[Epoch 06] train_loss=0.3147 | val_loss=0.3878 | val_mcc=0.5641 | val_f1=0.6520 | val_auroc=0.8808

[Epoch 07] train_loss=0.2699 | val_loss=0.4865 | val_mcc=0.5389 | val_f1=0.6303 | val_auroc=0.8774

[Epoch 08] train_loss=0.2241 | val_loss=0.4487 | val_mcc=0.5452 | val_f1=0.6374 | val_auroc=0.8735

[Epoch 09] train_loss=0.1618 | val_loss=0.5127 | val_mcc=0.5273 | val_f1=0.6230 | val_auroc=0.8701

[Epoch 10] train_loss=0.1321 | val_loss=0.5517 | val_mcc=0.5255 | val_f1=0.6214 | val_auroc=0.8694
[EarlyStop] epoch=10 | best_val_mcc=0.5686
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6321 | F1=0.7342 | AUROC=0.8917 | AUPRC=0.8007
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5483 | F1=0.7644 | AUROC=0.8670 | AUPRC=0.8640
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4257 | F1=0.6957 | AUROC=0.7768 | AUPRC=0.7640
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5856 | F1=0.7705 | AUROC=0.8662 | AUPRC=0.8426
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5374 | val_loss=0.4215 | val_mcc=0.5372 | val_f1=0.6311 | val_auroc=0.8587

[Epoch 02] train_loss=0.4638 | val_loss=0.4604 | val_mcc=0.5314 | val_f1=0.6251 | val_auroc=0.8713

[Epoch 03] train_loss=0.4291 | val_loss=0.4707 | val_mcc=0.5385 | val_f1=0.6291 | val_auroc=0.8807

[Epoch 04] train_loss=0.3964 | val_loss=0.4662 | val_mcc=0.5313 | val_f1=0.6238 | val_auroc=0.8805

[Epoch 05] train_loss=0.3575 | val_loss=0.4016 | val_mcc=0.5704 | val_f1=0.6569 | val_auroc=0.8856

[Epoch 06] train_loss=0.3146 | val_loss=0.3881 | val_mcc=0.5695 | val_f1=0.6560 | val_auroc=0.8806

[Epoch 07] train_loss=0.2629 | val_loss=0.4629 | val_mcc=0.5551 | val_f1=0.6451 | val_auroc=0.8705

[Epoch 08] train_loss=0.2112 | val_loss=0.5507 | val_mcc=0.5469 | val_f1=0.6386 | val_auroc=0.8640

[Epoch 09] train_loss=0.1619 | val_loss=0.6048 | val_mcc=0.5191 | val_f1=0.6171 | val_auroc=0.8545

[Epoch 10] train_loss=0.1030 | val_loss=0.7761 | val_mcc=0.5196 | val_f1=0.6170 | val_auroc=0.8540

[Epoch 11] train_loss=0.0785 | val_loss=0.9323 | val_mcc=0.4839 | val_f1=0.5873 | val_auroc=0.8473
[EarlyStop] epoch=11 | best_val_mcc=0.5704
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6311 | F1=0.7352 | AUROC=0.9004 | AUPRC=0.8013
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6020 | F1=0.7947 | AUROC=0.8838 | AUPRC=0.8769
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4556 | F1=0.7214 | AUROC=0.7799 | AUPRC=0.7554
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5979 | F1=0.7825 | AUROC=0.8720 | AUPRC=0.8385
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5299 | val_loss=0.4073 | val_mcc=0.5383 | val_f1=0.6317 | val_auroc=0.8611

[Epoch 02] train_loss=0.4570 | val_loss=0.3625 | val_mcc=0.5713 | val_f1=0.6571 | val_auroc=0.8747

[Epoch 03] train_loss=0.4237 | val_loss=0.3700 | val_mcc=0.5787 | val_f1=0.6635 | val_auroc=0.8862

[Epoch 04] train_loss=0.3926 | val_loss=0.3337 | val_mcc=0.5814 | val_f1=0.6616 | val_auroc=0.8867

[Epoch 05] train_loss=0.3534 | val_loss=0.3515 | val_mcc=0.5862 | val_f1=0.6687 | val_auroc=0.8912

[Epoch 06] train_loss=0.3103 | val_loss=0.4524 | val_mcc=0.5489 | val_f1=0.6389 | val_auroc=0.8839

[Epoch 07] train_loss=0.2597 | val_loss=0.4056 | val_mcc=0.5652 | val_f1=0.6520 | val_auroc=0.8731

[Epoch 08] train_loss=0.2074 | val_loss=0.4600 | val_mcc=0.5464 | val_f1=0.6377 | val_auroc=0.8688

[Epoch 09] train_loss=0.1596 | val_loss=0.5456 | val_mcc=0.5449 | val_f1=0.6371 | val_auroc=0.8661

[Epoch 10] train_loss=0.1027 | val_loss=0.7500 | val_mcc=0.5123 | val_f1=0.6101 | val_auroc=0.8634

[Epoch 11] train_loss=0.0757 | val_loss=0.7518 | val_mcc=0.5292 | val_f1=0.6246 | val_auroc=0.8621
[EarlyStop] epoch=11 | best_val_mcc=0.5862
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6404 | F1=0.7379 | AUROC=0.9018 | AUPRC=0.8059
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5722 | F1=0.7729 | AUROC=0.8805 | AUPRC=0.8692
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4572 | F1=0.7074 | AUROC=0.7869 | AUPRC=0.7697
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5730 | F1=0.7602 | AUROC=0.8734 | AUPRC=0.8481
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5287 | val_loss=0.3793 | val_mcc=0.5456 | val_f1=0.6355 | val_auroc=0.8596

[Epoch 02] train_loss=0.4571 | val_loss=0.3642 | val_mcc=0.5647 | val_f1=0.6514 | val_auroc=0.8704

[Epoch 03] train_loss=0.4186 | val_loss=0.4065 | val_mcc=0.5539 | val_f1=0.6437 | val_auroc=0.8780

[Epoch 04] train_loss=0.3801 | val_loss=0.4058 | val_mcc=0.5592 | val_f1=0.6473 | val_auroc=0.8847

[Epoch 05] train_loss=0.3379 | val_loss=0.3904 | val_mcc=0.5624 | val_f1=0.6507 | val_auroc=0.8835

[Epoch 06] train_loss=0.2919 | val_loss=0.4069 | val_mcc=0.5520 | val_f1=0.6426 | val_auroc=0.8781

[Epoch 07] train_loss=0.2242 | val_loss=0.4677 | val_mcc=0.5259 | val_f1=0.6216 | val_auroc=0.8753

[Epoch 08] train_loss=0.1870 | val_loss=0.4994 | val_mcc=0.5201 | val_f1=0.6175 | val_auroc=0.8715
[EarlyStop] epoch=8 | best_val_mcc=0.5647
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6227 | F1=0.7242 | AUROC=0.8773 | AUPRC=0.7827
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5711 | F1=0.7676 | AUROC=0.8672 | AUPRC=0.8682
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4243 | F1=0.6836 | AUROC=0.7661 | AUPRC=0.7559
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5661 | F1=0.7554 | AUROC=0.8514 | AUPRC=0.8362
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 229.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6081 | F1=0.7205 | AUROC=0.8965 | AUPRC=0.7946
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5915 | F1=0.7989 | AUROC=0.8798 | AUPRC=0.8785
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4449 | F1=0.7218 | AUROC=0.7725 | AUPRC=0.7487
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5796 | F1=0.7762 | AUROC=0.8710 | AUPRC=0.8493
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 164.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6061 | F1=0.7181 | AUROC=0.8910 | AUPRC=0.7922
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5761 | F1=0.7837 | AUROC=0.8715 | AUPRC=0.8673
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4153 | F1=0.6981 | AUROC=0.7688 | AUPRC=0.7585
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5666 | F1=0.7661 | AUROC=0.8637 | AUPRC=0.8385
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 70.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6116 | F1=0.7221 | AUROC=0.8877 | AUPRC=0.7870
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5761 | F1=0.7862 | AUROC=0.8674 | AUPRC=0.8660
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4225 | F1=0.7059 | AUROC=0.7763 | AUPRC=0.7645
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5725 | F1=0.7721 | AUROC=0.8560 | AUPRC=0.8325
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 134.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6160 | F1=0.7256 | AUROC=0.8899 | AUPRC=0.7905
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5761 | F1=0.7868 | AUROC=0.8671 | AUPRC=0.8665
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4260 | F1=0.7029 | AUROC=0.7699 | AUPRC=0.7582
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']

[Epoch 01] train_loss=0.3906 | val_loss=0.2408 | val_mcc=0.7238 | val_f1=0.7767 | val_auroc=0.9568

[Epoch 02] train_loss=0.2908 | val_loss=0.2220 | val_mcc=0.7407 | val_f1=0.7909 | val_auroc=0.9602

[Epoch 03] train_loss=0.2649 | val_loss=0.2209 | val_mcc=0.7421 | val_f1=0.7918 | val_auroc=0.9616

[Epoch 04] train_loss=0.2438 | val_loss=0.2114 | val_mcc=0.7474 | val_f1=0.7968 | val_auroc=0.9607

[Epoch 05] train_loss=0.2201 | val_loss=0.2375 | val_mcc=0.7338 | val_f1=0.7837 | val_auroc=0.9617

[Epoch 06] train_loss=0.1917 | val_loss=0.2245 | val_mcc=0.7458 | val_f1=0.7955 | val_auroc=0.9581

[Epoch 07] train_loss=0.1652 | val_loss=0.2344 | val_mcc=0.7408 | val_f1=0.7916 | val_auroc=0.9578

[Epoch 08] train_loss=0.1287 | val_loss=0.3400 | val_mcc=0.6888 | val_f1=0.7441 | val_auroc=0.9559

[Epoch 09] train_loss=0.0913 | val_loss=0.3085 | val_mcc=0.7105 | val_f1=0.7656 | val_auroc=0.9549

[Epoch 10] train_loss=0.0757 | val_loss=0.3020 | val_mcc=0.7140 | val_f1=0.7693 | val_auroc=0.9538
[EarlyStop] epoch=10 | best_val_mcc=0.7474
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7577 | F1=0.8254 | AUROC=0.9538 | AUPRC=0.9054
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8056 | F1=0.8972 | AUROC=0.9699 | AUPRC=0.9695
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4402 | F1=0.7286 | AUROC=0.7752 | AUPRC=0.7615
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5756 | F1=0.7844 | AUROC=0.8856 | AUPRC=0.8600
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4072 | val_loss=0.2807 | val_mcc=0.6962 | val_f1=0.7510 | val_auroc=0.9559

[Epoch 02] train_loss=0.3024 | val_loss=0.2158 | val_mcc=0.7483 | val_f1=0.7975 | val_auroc=0.9597

[Epoch 03] train_loss=0.2737 | val_loss=0.1938 | val_mcc=0.7667 | val_f1=0.8111 | val_auroc=0.9602

[Epoch 04] train_loss=0.2549 | val_loss=0.2176 | val_mcc=0.7430 | val_f1=0.7932 | val_auroc=0.9603

[Epoch 05] train_loss=0.2328 | val_loss=0.2218 | val_mcc=0.7403 | val_f1=0.7909 | val_auroc=0.9601

[Epoch 06] train_loss=0.1999 | val_loss=0.2310 | val_mcc=0.7337 | val_f1=0.7857 | val_auroc=0.9575

[Epoch 07] train_loss=0.1739 | val_loss=0.2488 | val_mcc=0.7212 | val_f1=0.7758 | val_auroc=0.9531

[Epoch 08] train_loss=0.1179 | val_loss=0.2949 | val_mcc=0.7167 | val_f1=0.7724 | val_auroc=0.9480

[Epoch 09] train_loss=0.0957 | val_loss=0.3895 | val_mcc=0.6781 | val_f1=0.7391 | val_auroc=0.9444
[EarlyStop] epoch=9 | best_val_mcc=0.7667
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7660 | F1=0.8280 | AUROC=0.9555 | AUPRC=0.9075
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7538 | F1=0.8624 | AUROC=0.9706 | AUPRC=0.9712
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4275 | F1=0.7034 | AUROC=0.7765 | AUPRC=0.7644
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6108 | F1=0.7997 | AUROC=0.8920 | AUPRC=0.8626
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4191 | val_loss=0.2154 | val_mcc=0.7228 | val_f1=0.7746 | val_auroc=0.9539

[Epoch 02] train_loss=0.3015 | val_loss=0.2044 | val_mcc=0.7476 | val_f1=0.7960 | val_auroc=0.9584

[Epoch 03] train_loss=0.2733 | val_loss=0.2018 | val_mcc=0.7523 | val_f1=0.8006 | val_auroc=0.9603

[Epoch 04] train_loss=0.2570 | val_loss=0.1988 | val_mcc=0.7547 | val_f1=0.8023 | val_auroc=0.9608

[Epoch 05] train_loss=0.2355 | val_loss=0.2602 | val_mcc=0.7236 | val_f1=0.7747 | val_auroc=0.9608

[Epoch 06] train_loss=0.2100 | val_loss=0.2336 | val_mcc=0.7293 | val_f1=0.7816 | val_auroc=0.9588

[Epoch 07] train_loss=0.1730 | val_loss=0.2264 | val_mcc=0.7418 | val_f1=0.7923 | val_auroc=0.9568

[Epoch 08] train_loss=0.1419 | val_loss=0.3135 | val_mcc=0.6947 | val_f1=0.7534 | val_auroc=0.9480

[Epoch 09] train_loss=0.1004 | val_loss=0.2757 | val_mcc=0.7284 | val_f1=0.7813 | val_auroc=0.9493

[Epoch 10] train_loss=0.0779 | val_loss=0.3438 | val_mcc=0.7060 | val_f1=0.7631 | val_auroc=0.9488
[EarlyStop] epoch=10 | best_val_mcc=0.7547
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7619 | F1=0.8269 | AUROC=0.9556 | AUPRC=0.9072
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7732 | F1=0.8775 | AUROC=0.9694 | AUPRC=0.9687
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4539 | F1=0.7230 | AUROC=0.7802 | AUPRC=0.7680
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6149 | F1=0.8024 | AUROC=0.8946 | AUPRC=0.8671
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4018 | val_loss=0.2281 | val_mcc=0.7323 | val_f1=0.7843 | val_auroc=0.9583

[Epoch 02] train_loss=0.2924 | val_loss=0.2140 | val_mcc=0.7505 | val_f1=0.7991 | val_auroc=0.9601

[Epoch 03] train_loss=0.2687 | val_loss=0.2090 | val_mcc=0.7522 | val_f1=0.8004 | val_auroc=0.9625

[Epoch 04] train_loss=0.2433 | val_loss=0.2233 | val_mcc=0.7418 | val_f1=0.7908 | val_auroc=0.9629

[Epoch 05] train_loss=0.2170 | val_loss=0.2234 | val_mcc=0.7392 | val_f1=0.7897 | val_auroc=0.9607

[Epoch 06] train_loss=0.1836 | val_loss=0.2276 | val_mcc=0.7348 | val_f1=0.7867 | val_auroc=0.9579

[Epoch 07] train_loss=0.1528 | val_loss=0.2414 | val_mcc=0.7300 | val_f1=0.7830 | val_auroc=0.9556

[Epoch 08] train_loss=0.1079 | val_loss=0.2723 | val_mcc=0.7260 | val_f1=0.7789 | val_auroc=0.9555

[Epoch 09] train_loss=0.0862 | val_loss=0.2794 | val_mcc=0.7237 | val_f1=0.7777 | val_auroc=0.9542
[EarlyStop] epoch=9 | best_val_mcc=0.7522
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7595 | F1=0.8269 | AUROC=0.9567 | AUPRC=0.9083
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7996 | F1=0.8945 | AUROC=0.9732 | AUPRC=0.9740
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4170 | F1=0.7198 | AUROC=0.7742 | AUPRC=0.7607
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5642 | F1=0.7791 | AUROC=0.8869 | AUPRC=0.8611
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 156.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7793 | F1=0.8409 | AUROC=0.9641 | AUPRC=0.9198
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8755 | F1=0.9355 | AUROC=0.9874 | AUPRC=0.9883
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4199 | F1=0.7269 | AUROC=0.7740 | AUPRC=0.7482
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5572 | F1=0.7757 | AUROC=0.8972 | AUPRC=0.8595
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 147.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7562 | F1=0.8246 | AUROC=0.9565 | AUPRC=0.9084
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8105 | F1=0.9010 | AUROC=0.9739 | AUPRC=0.9738
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4153 | F1=0.7220 | AUROC=0.7754 | AUPRC=0.7569
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5742 | F1=0.7835 | AUROC=0.8921 | AUPRC=0.8582
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 127.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7568 | F1=0.8250 | AUROC=0.9557 | AUPRC=0.9018
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8211 | F1=0.9080 | AUROC=0.9747 | AUPRC=0.9746
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4445 | F1=0.7339 | AUROC=0.7830 | AUPRC=0.7628
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5654 | F1=0.7797 | AUROC=0.8876 | AUPRC=0.8578
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 117.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7575 | F1=0.8255 | AUROC=0.9573 | AUPRC=0.9123
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8187 | F1=0.9059 | AUROC=0.9751 | AUPRC=0.9754
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.5582 | val_loss=0.4092 | val_mcc=0.5021 | val_f1=0.5995 | val_auroc=0.8374

[Epoch 02] train_loss=0.4813 | val_loss=0.3899 | val_mcc=0.5291 | val_f1=0.6233 | val_auroc=0.8592

[Epoch 03] train_loss=0.4461 | val_loss=0.4435 | val_mcc=0.5117 | val_f1=0.6096 | val_auroc=0.8753

[Epoch 04] train_loss=0.4088 | val_loss=0.3773 | val_mcc=0.5407 | val_f1=0.6336 | val_auroc=0.8790

[Epoch 05] train_loss=0.3699 | val_loss=0.3755 | val_mcc=0.5334 | val_f1=0.6276 | val_auroc=0.8749

[Epoch 06] train_loss=0.3312 | val_loss=0.4143 | val_mcc=0.5238 | val_f1=0.6208 | val_auroc=0.8730

[Epoch 07] train_loss=0.2907 | val_loss=0.4522 | val_mcc=0.5101 | val_f1=0.6098 | val_auroc=0.8677

[Epoch 08] train_loss=0.2384 | val_loss=0.4835 | val_mcc=0.5076 | val_f1=0.6083 | val_auroc=0.8631

[Epoch 09] train_loss=0.1800 | val_loss=0.5499 | val_mcc=0.4911 | val_f1=0.5945 | val_auroc=0.8603

[Epoch 10] train_loss=0.1502 | val_loss=0.5255 | val_mcc=0.4967 | val_f1=0.5999 | val_auroc=0.8573
[EarlyStop] epoch=10 | best_val_mcc=0.5407
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6102 | F1=0.7186 | AUROC=0.8914 | AUPRC=0.7906
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5409 | F1=0.7560 | AUROC=0.8604 | AUPRC=0.8595
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3924 | F1=0.6920 | AUROC=0.7539 | AUPRC=0.7294
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5634 | F1=0.7558 | AUROC=0.8632 | AUPRC=0.8336
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5520 | val_loss=0.4827 | val_mcc=0.4742 | val_f1=0.5825 | val_auroc=0.8406

[Epoch 02] train_loss=0.4847 | val_loss=0.4268 | val_mcc=0.5147 | val_f1=0.6137 | val_auroc=0.8633

[Epoch 03] train_loss=0.4473 | val_loss=0.4185 | val_mcc=0.5220 | val_f1=0.6191 | val_auroc=0.8763

[Epoch 04] train_loss=0.4091 | val_loss=0.3928 | val_mcc=0.5368 | val_f1=0.6307 | val_auroc=0.8782

[Epoch 05] train_loss=0.3708 | val_loss=0.3770 | val_mcc=0.5320 | val_f1=0.6254 | val_auroc=0.8731

[Epoch 06] train_loss=0.3305 | val_loss=0.4462 | val_mcc=0.5238 | val_f1=0.6207 | val_auroc=0.8693

[Epoch 07] train_loss=0.2795 | val_loss=0.5761 | val_mcc=0.4751 | val_f1=0.5810 | val_auroc=0.8558

[Epoch 08] train_loss=0.2249 | val_loss=0.7021 | val_mcc=0.4616 | val_f1=0.5700 | val_auroc=0.8453

[Epoch 09] train_loss=0.1541 | val_loss=0.7595 | val_mcc=0.4607 | val_f1=0.5716 | val_auroc=0.8375

[Epoch 10] train_loss=0.1209 | val_loss=0.8716 | val_mcc=0.4483 | val_f1=0.5615 | val_auroc=0.8372
[EarlyStop] epoch=10 | best_val_mcc=0.5368
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6085 | F1=0.7182 | AUROC=0.8928 | AUPRC=0.7912
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5745 | F1=0.7761 | AUROC=0.8719 | AUPRC=0.8725
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3970 | F1=0.6917 | AUROC=0.7528 | AUPRC=0.7319
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5648 | F1=0.7567 | AUROC=0.8601 | AUPRC=0.8311
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5479 | val_loss=0.4661 | val_mcc=0.4802 | val_f1=0.5873 | val_auroc=0.8406

[Epoch 02] train_loss=0.4824 | val_loss=0.3595 | val_mcc=0.5291 | val_f1=0.6170 | val_auroc=0.8635

[Epoch 03] train_loss=0.4385 | val_loss=0.3686 | val_mcc=0.5369 | val_f1=0.6291 | val_auroc=0.8740

[Epoch 04] train_loss=0.4072 | val_loss=0.3923 | val_mcc=0.5311 | val_f1=0.6264 | val_auroc=0.8809

[Epoch 05] train_loss=0.3648 | val_loss=0.3764 | val_mcc=0.5284 | val_f1=0.6211 | val_auroc=0.8691

[Epoch 06] train_loss=0.3271 | val_loss=0.4674 | val_mcc=0.5221 | val_f1=0.6192 | val_auroc=0.8715

[Epoch 07] train_loss=0.2784 | val_loss=0.4603 | val_mcc=0.5196 | val_f1=0.6163 | val_auroc=0.8593

[Epoch 08] train_loss=0.2054 | val_loss=0.5999 | val_mcc=0.4915 | val_f1=0.5956 | val_auroc=0.8577

[Epoch 09] train_loss=0.1698 | val_loss=0.6291 | val_mcc=0.4907 | val_f1=0.5953 | val_auroc=0.8460
[EarlyStop] epoch=9 | best_val_mcc=0.5369
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6102 | F1=0.7170 | AUROC=0.8906 | AUPRC=0.7908
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5462 | F1=0.7519 | AUROC=0.8642 | AUPRC=0.8681
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3783 | F1=0.6745 | AUROC=0.7438 | AUPRC=0.7264
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5496 | F1=0.7457 | AUROC=0.8616 | AUPRC=0.8360
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5585 | val_loss=0.4695 | val_mcc=0.4790 | val_f1=0.5862 | val_auroc=0.8329

[Epoch 02] train_loss=0.4797 | val_loss=0.4125 | val_mcc=0.5088 | val_f1=0.6088 | val_auroc=0.8589

[Epoch 03] train_loss=0.4420 | val_loss=0.4281 | val_mcc=0.5153 | val_f1=0.6137 | val_auroc=0.8723

[Epoch 04] train_loss=0.3997 | val_loss=0.3964 | val_mcc=0.5296 | val_f1=0.6253 | val_auroc=0.8732

[Epoch 05] train_loss=0.3567 | val_loss=0.3925 | val_mcc=0.5338 | val_f1=0.6284 | val_auroc=0.8731

[Epoch 06] train_loss=0.3141 | val_loss=0.4472 | val_mcc=0.5055 | val_f1=0.6063 | val_auroc=0.8674

[Epoch 07] train_loss=0.2572 | val_loss=0.5247 | val_mcc=0.4795 | val_f1=0.5856 | val_auroc=0.8591

[Epoch 08] train_loss=0.2007 | val_loss=0.5489 | val_mcc=0.4790 | val_f1=0.5862 | val_auroc=0.8531

[Epoch 09] train_loss=0.1483 | val_loss=0.6016 | val_mcc=0.4785 | val_f1=0.5859 | val_auroc=0.8475

[Epoch 10] train_loss=0.0948 | val_loss=0.6895 | val_mcc=0.4708 | val_f1=0.5794 | val_auroc=0.8484

[Epoch 11] train_loss=0.0707 | val_loss=0.7439 | val_mcc=0.4637 | val_f1=0.5736 | val_auroc=0.8505
[EarlyStop] epoch=11 | best_val_mcc=0.5338
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6031 | F1=0.7142 | AUROC=0.8884 | AUPRC=0.7822
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5556 | F1=0.7625 | AUROC=0.8609 | AUPRC=0.8572
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3895 | F1=0.6876 | AUROC=0.7512 | AUPRC=0.7354
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5607 | F1=0.7554 | AUROC=0.8621 | AUPRC=0.8343
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 198.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5716 | F1=0.6956 | AUROC=0.8805 | AUPRC=0.7703
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5363 | F1=0.7627 | AUROC=0.8477 | AUPRC=0.8523
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3624 | F1=0.6821 | AUROC=0.7359 | AUPRC=0.7149
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5286 | F1=0.7485 | AUROC=0.8503 | AUPRC=0.8204
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 109.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5825 | F1=0.7027 | AUROC=0.8843 | AUPRC=0.7807
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5449 | F1=0.7661 | AUROC=0.8487 | AUPRC=0.8497
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3835 | F1=0.6935 | AUROC=0.7466 | AUPRC=0.7245
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5401 | F1=0.7504 | AUROC=0.8536 | AUPRC=0.8297
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 64.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5810 | F1=0.7014 | AUROC=0.8794 | AUPRC=0.7750
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5305 | F1=0.7612 | AUROC=0.8478 | AUPRC=0.8459
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3640 | F1=0.6845 | AUROC=0.7436 | AUPRC=0.7267
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5479 | F1=0.7568 | AUROC=0.8472 | AUPRC=0.8266
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 62.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5931 | F1=0.7101 | AUROC=0.8859 | AUPRC=0.7855
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5504 | F1=0.7723 | AUROC=0.8584 | AUPRC=0.8648
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3789 | F1=0.6910 | AUROC=0.7488 | AUPRC=0.7215
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']

[Epoch 01] train_loss=0.4181 | val_loss=0.2271 | val_mcc=0.7265 | val_f1=0.7799 | val_auroc=0.9539

[Epoch 02] train_loss=0.3011 | val_loss=0.2064 | val_mcc=0.7468 | val_f1=0.7962 | val_auroc=0.9607

[Epoch 03] train_loss=0.2689 | val_loss=0.1965 | val_mcc=0.7477 | val_f1=0.7943 | val_auroc=0.9611

[Epoch 04] train_loss=0.2426 | val_loss=0.2102 | val_mcc=0.7520 | val_f1=0.8005 | val_auroc=0.9614

[Epoch 05] train_loss=0.2152 | val_loss=0.2215 | val_mcc=0.7402 | val_f1=0.7910 | val_auroc=0.9602

[Epoch 06] train_loss=0.1914 | val_loss=0.2155 | val_mcc=0.7430 | val_f1=0.7931 | val_auroc=0.9598

[Epoch 07] train_loss=0.1628 | val_loss=0.2485 | val_mcc=0.7322 | val_f1=0.7838 | val_auroc=0.9592

[Epoch 08] train_loss=0.1313 | val_loss=0.2598 | val_mcc=0.7374 | val_f1=0.7886 | val_auroc=0.9570

[Epoch 09] train_loss=0.0944 | val_loss=0.2721 | val_mcc=0.7232 | val_f1=0.7775 | val_auroc=0.9542

[Epoch 10] train_loss=0.0785 | val_loss=0.3124 | val_mcc=0.7085 | val_f1=0.7645 | val_auroc=0.9533
[EarlyStop] epoch=10 | best_val_mcc=0.7520
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7555 | F1=0.8236 | AUROC=0.9544 | AUPRC=0.8955
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7804 | F1=0.8832 | AUROC=0.9680 | AUPRC=0.9683
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4218 | F1=0.7182 | AUROC=0.7650 | AUPRC=0.7413
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5565 | F1=0.7756 | AUROC=0.8770 | AUPRC=0.8522
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4134 | val_loss=0.2667 | val_mcc=0.6949 | val_f1=0.7521 | val_auroc=0.9549

[Epoch 02] train_loss=0.3024 | val_loss=0.2434 | val_mcc=0.7213 | val_f1=0.7735 | val_auroc=0.9600

[Epoch 03] train_loss=0.2750 | val_loss=0.2318 | val_mcc=0.7311 | val_f1=0.7827 | val_auroc=0.9596

[Epoch 04] train_loss=0.2475 | val_loss=0.2008 | val_mcc=0.7540 | val_f1=0.8019 | val_auroc=0.9627

[Epoch 05] train_loss=0.2243 | val_loss=0.2020 | val_mcc=0.7440 | val_f1=0.7892 | val_auroc=0.9607

[Epoch 06] train_loss=0.2031 | val_loss=0.2485 | val_mcc=0.7278 | val_f1=0.7804 | val_auroc=0.9583

[Epoch 07] train_loss=0.1668 | val_loss=0.2619 | val_mcc=0.7300 | val_f1=0.7825 | val_auroc=0.9555

[Epoch 08] train_loss=0.1302 | val_loss=0.4189 | val_mcc=0.6554 | val_f1=0.7156 | val_auroc=0.9485

[Epoch 09] train_loss=0.0887 | val_loss=0.3947 | val_mcc=0.6827 | val_f1=0.7416 | val_auroc=0.9472

[Epoch 10] train_loss=0.0696 | val_loss=0.3646 | val_mcc=0.6990 | val_f1=0.7580 | val_auroc=0.9446
[EarlyStop] epoch=10 | best_val_mcc=0.7540
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7629 | F1=0.8276 | AUROC=0.9571 | AUPRC=0.9018
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8090 | F1=0.8947 | AUROC=0.9711 | AUPRC=0.9718
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4182 | F1=0.7134 | AUROC=0.7637 | AUPRC=0.7437
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5879 | F1=0.7894 | AUROC=0.8879 | AUPRC=0.8623
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4045 | val_loss=0.2362 | val_mcc=0.7207 | val_f1=0.7748 | val_auroc=0.9575

[Epoch 02] train_loss=0.2990 | val_loss=0.2153 | val_mcc=0.7433 | val_f1=0.7935 | val_auroc=0.9595

[Epoch 03] train_loss=0.2722 | val_loss=0.1984 | val_mcc=0.7472 | val_f1=0.7933 | val_auroc=0.9597

[Epoch 04] train_loss=0.2489 | val_loss=0.2013 | val_mcc=0.7539 | val_f1=0.8020 | val_auroc=0.9635

[Epoch 05] train_loss=0.2246 | val_loss=0.2409 | val_mcc=0.7262 | val_f1=0.7788 | val_auroc=0.9587

[Epoch 06] train_loss=0.1941 | val_loss=0.2284 | val_mcc=0.7319 | val_f1=0.7843 | val_auroc=0.9570

[Epoch 07] train_loss=0.1613 | val_loss=0.2825 | val_mcc=0.7142 | val_f1=0.7681 | val_auroc=0.9568

[Epoch 08] train_loss=0.1281 | val_loss=0.2879 | val_mcc=0.7166 | val_f1=0.7717 | val_auroc=0.9517

[Epoch 09] train_loss=0.0847 | val_loss=0.3404 | val_mcc=0.6993 | val_f1=0.7576 | val_auroc=0.9465

[Epoch 10] train_loss=0.0677 | val_loss=0.3333 | val_mcc=0.7099 | val_f1=0.7669 | val_auroc=0.9476
[EarlyStop] epoch=10 | best_val_mcc=0.7539
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7629 | F1=0.8290 | AUROC=0.9577 | AUPRC=0.9056
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8173 | F1=0.9028 | AUROC=0.9720 | AUPRC=0.9742
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4017 | F1=0.7118 | AUROC=0.7584 | AUPRC=0.7298
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5604 | F1=0.7775 | AUROC=0.8831 | AUPRC=0.8578
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4075 | val_loss=0.2326 | val_mcc=0.7226 | val_f1=0.7770 | val_auroc=0.9561

[Epoch 02] train_loss=0.2977 | val_loss=0.2165 | val_mcc=0.7352 | val_f1=0.7871 | val_auroc=0.9586

[Epoch 03] train_loss=0.2681 | val_loss=0.2260 | val_mcc=0.7350 | val_f1=0.7864 | val_auroc=0.9605

[Epoch 04] train_loss=0.2406 | val_loss=0.2252 | val_mcc=0.7401 | val_f1=0.7900 | val_auroc=0.9626

[Epoch 05] train_loss=0.2120 | val_loss=0.2422 | val_mcc=0.7260 | val_f1=0.7786 | val_auroc=0.9589

[Epoch 06] train_loss=0.1814 | val_loss=0.2277 | val_mcc=0.7291 | val_f1=0.7820 | val_auroc=0.9562

[Epoch 07] train_loss=0.1469 | val_loss=0.2690 | val_mcc=0.7198 | val_f1=0.7739 | val_auroc=0.9549

[Epoch 08] train_loss=0.1091 | val_loss=0.2950 | val_mcc=0.7045 | val_f1=0.7624 | val_auroc=0.9503

[Epoch 09] train_loss=0.0713 | val_loss=0.2983 | val_mcc=0.7104 | val_f1=0.7673 | val_auroc=0.9505

[Epoch 10] train_loss=0.0555 | val_loss=0.3520 | val_mcc=0.6947 | val_f1=0.7532 | val_auroc=0.9497
[EarlyStop] epoch=10 | best_val_mcc=0.7401
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7512 | F1=0.8210 | AUROC=0.9554 | AUPRC=0.9001
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8185 | F1=0.9062 | AUROC=0.9674 | AUPRC=0.9708
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4167 | F1=0.7273 | AUROC=0.7663 | AUPRC=0.7362
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5491 | F1=0.7725 | AUROC=0.8870 | AUPRC=0.8630
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 172.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7640 | F1=0.8301 | AUROC=0.9627 | AUPRC=0.9138
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8533 | F1=0.9231 | AUROC=0.9835 | AUPRC=0.9835
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3960 | F1=0.7165 | AUROC=0.7588 | AUPRC=0.7273
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5497 | F1=0.7726 | AUROC=0.8897 | AUPRC=0.8647
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 165.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7498 | F1=0.8200 | AUROC=0.9555 | AUPRC=0.9012
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8214 | F1=0.9075 | AUROC=0.9741 | AUPRC=0.9743
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4044 | F1=0.7191 | AUROC=0.7612 | AUPRC=0.7382
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5373 | F1=0.7672 | AUROC=0.8844 | AUPRC=0.8598
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 135.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7475 | F1=0.8184 | AUROC=0.9557 | AUPRC=0.9017
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8244 | F1=0.9088 | AUROC=0.9721 | AUPRC=0.9722
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4222 | F1=0.7268 | AUROC=0.7701 | AUPRC=0.7395
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5613 | F1=0.7779 | AUROC=0.8858 | AUPRC=0.8584
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 195.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7416 | F1=0.8143 | AUROC=0.9523 | AUPRC=0.8988
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8330 | F1=0.9131 | AUROC=0.9720 | AUPRC=0.9719
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.5729 | val_loss=0.4794 | val_mcc=0.4682 | val_f1=0.5760 | val_auroc=0.8141

[Epoch 02] train_loss=0.5091 | val_loss=0.4764 | val_mcc=0.4923 | val_f1=0.5962 | val_auroc=0.8283

[Epoch 03] train_loss=0.4717 | val_loss=0.3993 | val_mcc=0.5145 | val_f1=0.6098 | val_auroc=0.8461

[Epoch 04] train_loss=0.4349 | val_loss=0.3901 | val_mcc=0.5389 | val_f1=0.6305 | val_auroc=0.8632

[Epoch 05] train_loss=0.3951 | val_loss=0.3976 | val_mcc=0.5213 | val_f1=0.6183 | val_auroc=0.8671

[Epoch 06] train_loss=0.3589 | val_loss=0.4448 | val_mcc=0.5133 | val_f1=0.6120 | val_auroc=0.8707

[Epoch 07] train_loss=0.3156 | val_loss=0.4561 | val_mcc=0.5205 | val_f1=0.6178 | val_auroc=0.8701

[Epoch 08] train_loss=0.2713 | val_loss=0.4603 | val_mcc=0.5022 | val_f1=0.6040 | val_auroc=0.8615

[Epoch 09] train_loss=0.2086 | val_loss=0.5688 | val_mcc=0.4820 | val_f1=0.5858 | val_auroc=0.8621

[Epoch 10] train_loss=0.1767 | val_loss=0.5000 | val_mcc=0.4975 | val_f1=0.6005 | val_auroc=0.8549
[EarlyStop] epoch=10 | best_val_mcc=0.5389
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5865 | F1=0.6949 | AUROC=0.8650 | AUPRC=0.7606
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5723 | F1=0.7654 | AUROC=0.8457 | AUPRC=0.8334
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4021 | F1=0.6810 | AUROC=0.7469 | AUPRC=0.7382
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5217 | F1=0.7183 | AUROC=0.8203 | AUPRC=0.7948
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5687 | val_loss=0.4508 | val_mcc=0.4771 | val_f1=0.5791 | val_auroc=0.8122

[Epoch 02] train_loss=0.5087 | val_loss=0.4176 | val_mcc=0.5058 | val_f1=0.5997 | val_auroc=0.8355

[Epoch 03] train_loss=0.4725 | val_loss=0.4568 | val_mcc=0.5094 | val_f1=0.6096 | val_auroc=0.8533

[Epoch 04] train_loss=0.4341 | val_loss=0.4723 | val_mcc=0.5128 | val_f1=0.6115 | val_auroc=0.8659

[Epoch 05] train_loss=0.3898 | val_loss=0.4296 | val_mcc=0.5249 | val_f1=0.6216 | val_auroc=0.8648

[Epoch 06] train_loss=0.3416 | val_loss=0.5146 | val_mcc=0.4957 | val_f1=0.5969 | val_auroc=0.8627

[Epoch 07] train_loss=0.2896 | val_loss=0.4460 | val_mcc=0.5014 | val_f1=0.5996 | val_auroc=0.8412

[Epoch 08] train_loss=0.2301 | val_loss=0.5837 | val_mcc=0.4963 | val_f1=0.5993 | val_auroc=0.8525

[Epoch 09] train_loss=0.1826 | val_loss=0.5922 | val_mcc=0.4852 | val_f1=0.5910 | val_auroc=0.8448

[Epoch 10] train_loss=0.1187 | val_loss=0.7399 | val_mcc=0.4647 | val_f1=0.5754 | val_auroc=0.8353

[Epoch 11] train_loss=0.0945 | val_loss=0.8508 | val_mcc=0.4739 | val_f1=0.5818 | val_auroc=0.8379
[EarlyStop] epoch=11 | best_val_mcc=0.5249
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5701 | F1=0.6898 | AUROC=0.8653 | AUPRC=0.7530
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5523 | F1=0.7620 | AUROC=0.8454 | AUPRC=0.8344
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4065 | F1=0.6921 | AUROC=0.7481 | AUPRC=0.7347
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.4957 | F1=0.7162 | AUROC=0.8159 | AUPRC=0.7894
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5795 | val_loss=0.4889 | val_mcc=0.4670 | val_f1=0.5764 | val_auroc=0.8169

[Epoch 02] train_loss=0.5063 | val_loss=0.4043 | val_mcc=0.4969 | val_f1=0.5921 | val_auroc=0.8330

[Epoch 03] train_loss=0.4720 | val_loss=0.4581 | val_mcc=0.5074 | val_f1=0.6081 | val_auroc=0.8554

[Epoch 04] train_loss=0.4385 | val_loss=0.4057 | val_mcc=0.5289 | val_f1=0.6246 | val_auroc=0.8688

[Epoch 05] train_loss=0.3943 | val_loss=0.4372 | val_mcc=0.5253 | val_f1=0.6213 | val_auroc=0.8767

[Epoch 06] train_loss=0.3569 | val_loss=0.4250 | val_mcc=0.5279 | val_f1=0.6239 | val_auroc=0.8716

[Epoch 07] train_loss=0.3089 | val_loss=0.4609 | val_mcc=0.5209 | val_f1=0.6184 | val_auroc=0.8651

[Epoch 08] train_loss=0.2520 | val_loss=0.5066 | val_mcc=0.5094 | val_f1=0.6095 | val_auroc=0.8591

[Epoch 09] train_loss=0.1749 | val_loss=0.6273 | val_mcc=0.5043 | val_f1=0.6056 | val_auroc=0.8543

[Epoch 10] train_loss=0.1402 | val_loss=0.7119 | val_mcc=0.4874 | val_f1=0.5919 | val_auroc=0.8499
[EarlyStop] epoch=10 | best_val_mcc=0.5289
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5702 | F1=0.6883 | AUROC=0.8705 | AUPRC=0.7664
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5436 | F1=0.7579 | AUROC=0.8528 | AUPRC=0.8410
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3956 | F1=0.6799 | AUROC=0.7581 | AUPRC=0.7436
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.4915 | F1=0.7091 | AUROC=0.8230 | AUPRC=0.7927
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5687 | val_loss=0.4266 | val_mcc=0.4797 | val_f1=0.5750 | val_auroc=0.8165

[Epoch 02] train_loss=0.5049 | val_loss=0.4466 | val_mcc=0.4983 | val_f1=0.5997 | val_auroc=0.8304

[Epoch 03] train_loss=0.4680 | val_loss=0.4076 | val_mcc=0.5180 | val_f1=0.6143 | val_auroc=0.8487

[Epoch 04] train_loss=0.4282 | val_loss=0.4200 | val_mcc=0.5189 | val_f1=0.6170 | val_auroc=0.8641

[Epoch 05] train_loss=0.3829 | val_loss=0.3932 | val_mcc=0.5286 | val_f1=0.6241 | val_auroc=0.8720

[Epoch 06] train_loss=0.3383 | val_loss=0.4221 | val_mcc=0.5311 | val_f1=0.6263 | val_auroc=0.8701

[Epoch 07] train_loss=0.2876 | val_loss=0.4376 | val_mcc=0.5131 | val_f1=0.6123 | val_auroc=0.8622

[Epoch 08] train_loss=0.2331 | val_loss=0.5196 | val_mcc=0.4921 | val_f1=0.5958 | val_auroc=0.8593

[Epoch 09] train_loss=0.1778 | val_loss=0.6836 | val_mcc=0.4548 | val_f1=0.5629 | val_auroc=0.8532

[Epoch 10] train_loss=0.1312 | val_loss=0.6715 | val_mcc=0.4859 | val_f1=0.5903 | val_auroc=0.8572

[Epoch 11] train_loss=0.0816 | val_loss=0.6574 | val_mcc=0.4756 | val_f1=0.5835 | val_auroc=0.8492

[Epoch 12] train_loss=0.0635 | val_loss=0.7241 | val_mcc=0.4727 | val_f1=0.5807 | val_auroc=0.8502
[EarlyStop] epoch=12 | best_val_mcc=0.5311
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5786 | F1=0.6976 | AUROC=0.8738 | AUPRC=0.7663
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5825 | F1=0.7822 | AUROC=0.8564 | AUPRC=0.8473
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4104 | F1=0.7011 | AUROC=0.7611 | AUPRC=0.7497
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5197 | F1=0.7344 | AUROC=0.8307 | AUPRC=0.8099
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 234.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5534 | F1=0.6816 | AUROC=0.8706 | AUPRC=0.7531
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5226 | F1=0.7634 | AUROC=0.8424 | AUPRC=0.8246
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3819 | F1=0.6921 | AUROC=0.7513 | AUPRC=0.7242
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4886 | F1=0.7198 | AUROC=0.8210 | AUPRC=0.7905
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 160.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5493 | F1=0.6770 | AUROC=0.8636 | AUPRC=0.7523
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5250 | F1=0.7562 | AUROC=0.8455 | AUPRC=0.8274
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4017 | F1=0.6924 | AUROC=0.7478 | AUPRC=0.7338
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4836 | F1=0.7121 | AUROC=0.8094 | AUPRC=0.7850
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 120.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5212 | F1=0.6561 | AUROC=0.8434 | AUPRC=0.7291
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5197 | F1=0.7504 | AUROC=0.8224 | AUPRC=0.8176
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3598 | F1=0.6692 | AUROC=0.7356 | AUPRC=0.7233
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4295 | F1=0.6795 | AUROC=0.7886 | AUPRC=0.7614
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 78.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5266 | F1=0.6591 | AUROC=0.8497 | AUPRC=0.7356
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.4799 | F1=0.7289 | AUROC=0.8241 | AUPRC=0.8162
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3631 | F1=0.6682 | AUROC=0.7372 | AUPRC=0.7195
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4156 | val_loss=0.2199 | val_mcc=0.7251 | val_f1=0.7781 | val_auroc=0.9540

[Epoch 02] train_loss=0.3065 | val_loss=0.2214 | val_mcc=0.7307 | val_f1=0.7831 | val_auroc=0.9596

[Epoch 03] train_loss=0.2824 | val_loss=0.2193 | val_mcc=0.7382 | val_f1=0.7891 | val_auroc=0.9601

[Epoch 04] train_loss=0.2596 | val_loss=0.2440 | val_mcc=0.7219 | val_f1=0.7742 | val_auroc=0.9597

[Epoch 05] train_loss=0.2413 | val_loss=0.2296 | val_mcc=0.7342 | val_f1=0.7854 | val_auroc=0.9599

[Epoch 06] train_loss=0.2160 | val_loss=0.2644 | val_mcc=0.7108 | val_f1=0.7647 | val_auroc=0.9583

[Epoch 07] train_loss=0.1900 | val_loss=0.2399 | val_mcc=0.7245 | val_f1=0.7777 | val_auroc=0.9572

[Epoch 08] train_loss=0.1543 | val_loss=0.2673 | val_mcc=0.7167 | val_f1=0.7705 | val_auroc=0.9567

[Epoch 09] train_loss=0.1325 | val_loss=0.2453 | val_mcc=0.7312 | val_f1=0.7839 | val_auroc=0.9549
[EarlyStop] epoch=9 | best_val_mcc=0.7382
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7474 | F1=0.8183 | AUROC=0.9543 | AUPRC=0.9058
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8387 | F1=0.9161 | AUROC=0.9748 | AUPRC=0.9739
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4049 | F1=0.7176 | AUROC=0.7650 | AUPRC=0.7459
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5240 | F1=0.7614 | AUROC=0.8693 | AUPRC=0.8323
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4275 | val_loss=0.2425 | val_mcc=0.7108 | val_f1=0.7675 | val_auroc=0.9536

[Epoch 02] train_loss=0.3159 | val_loss=0.2253 | val_mcc=0.7355 | val_f1=0.7866 | val_auroc=0.9607

[Epoch 03] train_loss=0.2889 | val_loss=0.2438 | val_mcc=0.7212 | val_f1=0.7733 | val_auroc=0.9608

[Epoch 04] train_loss=0.2763 | val_loss=0.2136 | val_mcc=0.7420 | val_f1=0.7922 | val_auroc=0.9629

[Epoch 05] train_loss=0.2550 | val_loss=0.2162 | val_mcc=0.7371 | val_f1=0.7885 | val_auroc=0.9595

[Epoch 06] train_loss=0.2239 | val_loss=0.2235 | val_mcc=0.7298 | val_f1=0.7828 | val_auroc=0.9573

[Epoch 07] train_loss=0.1946 | val_loss=0.2762 | val_mcc=0.6971 | val_f1=0.7556 | val_auroc=0.9485

[Epoch 08] train_loss=0.1619 | val_loss=0.3003 | val_mcc=0.6897 | val_f1=0.7495 | val_auroc=0.9465

[Epoch 09] train_loss=0.1118 | val_loss=0.3630 | val_mcc=0.6782 | val_f1=0.7387 | val_auroc=0.9434

[Epoch 10] train_loss=0.0952 | val_loss=0.3659 | val_mcc=0.6889 | val_f1=0.7488 | val_auroc=0.9408
[EarlyStop] epoch=10 | best_val_mcc=0.7420
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7533 | F1=0.8225 | AUROC=0.9547 | AUPRC=0.9041
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8474 | F1=0.9204 | AUROC=0.9755 | AUPRC=0.9750
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3996 | F1=0.7164 | AUROC=0.7688 | AUPRC=0.7400
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5301 | F1=0.7641 | AUROC=0.8710 | AUPRC=0.8319
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4367 | val_loss=0.2270 | val_mcc=0.7181 | val_f1=0.7734 | val_auroc=0.9540

[Epoch 02] train_loss=0.3202 | val_loss=0.2186 | val_mcc=0.7346 | val_f1=0.7866 | val_auroc=0.9590

[Epoch 03] train_loss=0.2883 | val_loss=0.2071 | val_mcc=0.7430 | val_f1=0.7932 | val_auroc=0.9603

[Epoch 04] train_loss=0.2715 | val_loss=0.2138 | val_mcc=0.7434 | val_f1=0.7936 | val_auroc=0.9590

[Epoch 05] train_loss=0.2500 | val_loss=0.2220 | val_mcc=0.7351 | val_f1=0.7866 | val_auroc=0.9605

[Epoch 06] train_loss=0.2228 | val_loss=0.2390 | val_mcc=0.7217 | val_f1=0.7760 | val_auroc=0.9552

[Epoch 07] train_loss=0.1943 | val_loss=0.2354 | val_mcc=0.7276 | val_f1=0.7810 | val_auroc=0.9533

[Epoch 08] train_loss=0.1667 | val_loss=0.2894 | val_mcc=0.7063 | val_f1=0.7633 | val_auroc=0.9505

[Epoch 09] train_loss=0.1203 | val_loss=0.2930 | val_mcc=0.7083 | val_f1=0.7654 | val_auroc=0.9485

[Epoch 10] train_loss=0.0970 | val_loss=0.3158 | val_mcc=0.7016 | val_f1=0.7602 | val_auroc=0.9444
[EarlyStop] epoch=10 | best_val_mcc=0.7434
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7482 | F1=0.8183 | AUROC=0.9504 | AUPRC=0.9001
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8116 | F1=0.8999 | AUROC=0.9660 | AUPRC=0.9668
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4145 | F1=0.7156 | AUROC=0.7663 | AUPRC=0.7421
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5309 | F1=0.7636 | AUROC=0.8602 | AUPRC=0.8302
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4167 | val_loss=0.2578 | val_mcc=0.7002 | val_f1=0.7575 | val_auroc=0.9544

[Epoch 02] train_loss=0.3081 | val_loss=0.2138 | val_mcc=0.7310 | val_f1=0.7838 | val_auroc=0.9581

[Epoch 03] train_loss=0.2795 | val_loss=0.2660 | val_mcc=0.7028 | val_f1=0.7564 | val_auroc=0.9608

[Epoch 04] train_loss=0.2599 | val_loss=0.2233 | val_mcc=0.7306 | val_f1=0.7826 | val_auroc=0.9612

[Epoch 05] train_loss=0.2300 | val_loss=0.2373 | val_mcc=0.7245 | val_f1=0.7772 | val_auroc=0.9600

[Epoch 06] train_loss=0.2024 | val_loss=0.2336 | val_mcc=0.7238 | val_f1=0.7773 | val_auroc=0.9593

[Epoch 07] train_loss=0.1623 | val_loss=0.2493 | val_mcc=0.7204 | val_f1=0.7744 | val_auroc=0.9578

[Epoch 08] train_loss=0.1432 | val_loss=0.2666 | val_mcc=0.7130 | val_f1=0.7686 | val_auroc=0.9557
[EarlyStop] epoch=8 | best_val_mcc=0.7310
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7525 | F1=0.8213 | AUROC=0.9482 | AUPRC=0.8926
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8040 | F1=0.8946 | AUROC=0.9678 | AUPRC=0.9654
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4005 | F1=0.7067 | AUROC=0.7578 | AUPRC=0.7324
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5213 | F1=0.7597 | AUROC=0.8551 | AUPRC=0.8187
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 207.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7751 | F1=0.8380 | AUROC=0.9626 | AUPRC=0.9187
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8586 | F1=0.9265 | AUROC=0.9842 | AUPRC=0.9845
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4325 | F1=0.7332 | AUROC=0.7724 | AUPRC=0.7459
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5272 | F1=0.7628 | AUROC=0.8851 | AUPRC=0.8541
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 177.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7577 | F1=0.8256 | AUROC=0.9556 | AUPRC=0.9080
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8382 | F1=0.9168 | AUROC=0.9719 | AUPRC=0.9727
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4232 | F1=0.7287 | AUROC=0.7690 | AUPRC=0.7402
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5262 | F1=0.7624 | AUROC=0.8708 | AUPRC=0.8380
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 135.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7465 | F1=0.8177 | AUROC=0.9553 | AUPRC=0.9081
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8183 | F1=0.9064 | AUROC=0.9732 | AUPRC=0.9753
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4286 | F1=0.7278 | AUROC=0.7748 | AUPRC=0.7461
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5378 | F1=0.7675 | AUROC=0.8755 | AUPRC=0.8411
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 147.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7534 | F1=0.8226 | AUROC=0.9557 | AUPRC=0.9073
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8267 | F1=0.9112 | AUROC=0.9705 | AUPRC=0.9711
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5684 | val_loss=0.4115 | val_mcc=0.5487 | val_f1=0.6267 | val_auroc=0.8280

[Epoch 02] train_loss=0.4895 | val_loss=0.4275 | val_mcc=0.5577 | val_f1=0.6437 | val_auroc=0.8424

[Epoch 03] train_loss=0.4678 | val_loss=0.4092 | val_mcc=0.5687 | val_f1=0.6521 | val_auroc=0.8500

[Epoch 04] train_loss=0.4485 | val_loss=0.4037 | val_mcc=0.5553 | val_f1=0.6440 | val_auroc=0.8546

[Epoch 05] train_loss=0.4293 | val_loss=0.3612 | val_mcc=0.5776 | val_f1=0.6565 | val_auroc=0.8553

[Epoch 06] train_loss=0.4045 | val_loss=0.4235 | val_mcc=0.5290 | val_f1=0.6248 | val_auroc=0.8570

[Epoch 07] train_loss=0.3731 | val_loss=0.3666 | val_mcc=0.5562 | val_f1=0.6406 | val_auroc=0.8484

[Epoch 08] train_loss=0.3348 | val_loss=0.3964 | val_mcc=0.5346 | val_f1=0.6273 | val_auroc=0.8427

[Epoch 09] train_loss=0.2851 | val_loss=0.4644 | val_mcc=0.4858 | val_f1=0.5915 | val_auroc=0.8345

[Epoch 10] train_loss=0.2262 | val_loss=0.5364 | val_mcc=0.4605 | val_f1=0.5716 | val_auroc=0.8362

[Epoch 11] train_loss=0.1939 | val_loss=0.5363 | val_mcc=0.4716 | val_f1=0.5803 | val_auroc=0.8377
[EarlyStop] epoch=11 | best_val_mcc=0.5776
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5998 | F1=0.7006 | AUROC=0.8453 | AUPRC=0.7748
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5207 | F1=0.7187 | AUROC=0.8038 | AUPRC=0.8405
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3764 | F1=0.6500 | AUROC=0.7257 | AUPRC=0.7509
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5179 | F1=0.7143 | AUROC=0.8032 | AUPRC=0.8108
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5681 | val_loss=0.4376 | val_mcc=0.5484 | val_f1=0.6308 | val_auroc=0.8309

[Epoch 02] train_loss=0.4928 | val_loss=0.3440 | val_mcc=0.5734 | val_f1=0.6347 | val_auroc=0.8451

[Epoch 03] train_loss=0.4756 | val_loss=0.4099 | val_mcc=0.5671 | val_f1=0.6499 | val_auroc=0.8514

[Epoch 04] train_loss=0.4510 | val_loss=0.3660 | val_mcc=0.5824 | val_f1=0.6583 | val_auroc=0.8521

[Epoch 05] train_loss=0.4286 | val_loss=0.4641 | val_mcc=0.5133 | val_f1=0.6122 | val_auroc=0.8555

[Epoch 06] train_loss=0.3977 | val_loss=0.4395 | val_mcc=0.5126 | val_f1=0.6122 | val_auroc=0.8471

[Epoch 07] train_loss=0.3557 | val_loss=0.5085 | val_mcc=0.4529 | val_f1=0.5658 | val_auroc=0.8370

[Epoch 08] train_loss=0.2980 | val_loss=0.4982 | val_mcc=0.4837 | val_f1=0.5899 | val_auroc=0.8326

[Epoch 09] train_loss=0.2276 | val_loss=0.5799 | val_mcc=0.4604 | val_f1=0.5722 | val_auroc=0.8194

[Epoch 10] train_loss=0.1968 | val_loss=0.7599 | val_mcc=0.4247 | val_f1=0.5430 | val_auroc=0.8196
[EarlyStop] epoch=10 | best_val_mcc=0.5824
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6005 | F1=0.6987 | AUROC=0.8432 | AUPRC=0.7735
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5460 | F1=0.7346 | AUROC=0.8017 | AUPRC=0.8415
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3764 | F1=0.6453 | AUROC=0.7185 | AUPRC=0.7436
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5291 | F1=0.7156 | AUROC=0.7939 | AUPRC=0.8045
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5791 | val_loss=0.3846 | val_mcc=0.5562 | val_f1=0.6267 | val_auroc=0.8299

[Epoch 02] train_loss=0.4957 | val_loss=0.3980 | val_mcc=0.5723 | val_f1=0.6519 | val_auroc=0.8443

[Epoch 03] train_loss=0.4695 | val_loss=0.3646 | val_mcc=0.5802 | val_f1=0.6545 | val_auroc=0.8517

[Epoch 04] train_loss=0.4503 | val_loss=0.3842 | val_mcc=0.5746 | val_f1=0.6558 | val_auroc=0.8572

[Epoch 05] train_loss=0.4289 | val_loss=0.3911 | val_mcc=0.5678 | val_f1=0.6521 | val_auroc=0.8554

[Epoch 06] train_loss=0.4013 | val_loss=0.4184 | val_mcc=0.5391 | val_f1=0.6324 | val_auroc=0.8540

[Epoch 07] train_loss=0.3597 | val_loss=0.4079 | val_mcc=0.5257 | val_f1=0.6207 | val_auroc=0.8432

[Epoch 08] train_loss=0.2916 | val_loss=0.5159 | val_mcc=0.4890 | val_f1=0.5939 | val_auroc=0.8392

[Epoch 09] train_loss=0.2470 | val_loss=0.5328 | val_mcc=0.4931 | val_f1=0.5971 | val_auroc=0.8322
[EarlyStop] epoch=9 | best_val_mcc=0.5802
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6071 | F1=0.6996 | AUROC=0.8469 | AUPRC=0.7736
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5397 | F1=0.7219 | AUROC=0.8068 | AUPRC=0.8380
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3813 | F1=0.6386 | AUROC=0.7286 | AUPRC=0.7500
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5151 | F1=0.7018 | AUROC=0.8009 | AUPRC=0.8076
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5710 | val_loss=0.4313 | val_mcc=0.5317 | val_f1=0.6172 | val_auroc=0.8208

[Epoch 02] train_loss=0.4901 | val_loss=0.3982 | val_mcc=0.5622 | val_f1=0.6432 | val_auroc=0.8412

[Epoch 03] train_loss=0.4654 | val_loss=0.4031 | val_mcc=0.5626 | val_f1=0.6479 | val_auroc=0.8508

[Epoch 04] train_loss=0.4408 | val_loss=0.3722 | val_mcc=0.5747 | val_f1=0.6545 | val_auroc=0.8521

[Epoch 05] train_loss=0.4181 | val_loss=0.4314 | val_mcc=0.5250 | val_f1=0.6215 | val_auroc=0.8554

[Epoch 06] train_loss=0.3861 | val_loss=0.4008 | val_mcc=0.5275 | val_f1=0.6232 | val_auroc=0.8540

[Epoch 07] train_loss=0.3440 | val_loss=0.3791 | val_mcc=0.5326 | val_f1=0.6240 | val_auroc=0.8493

[Epoch 08] train_loss=0.2876 | val_loss=0.4681 | val_mcc=0.4759 | val_f1=0.5840 | val_auroc=0.8354

[Epoch 09] train_loss=0.2151 | val_loss=0.4959 | val_mcc=0.4831 | val_f1=0.5895 | val_auroc=0.8417

[Epoch 10] train_loss=0.1862 | val_loss=0.4994 | val_mcc=0.4877 | val_f1=0.5924 | val_auroc=0.8408
[EarlyStop] epoch=10 | best_val_mcc=0.5747
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5982 | F1=0.6998 | AUROC=0.8464 | AUPRC=0.7770
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5265 | F1=0.7276 | AUROC=0.8048 | AUPRC=0.8416
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3807 | F1=0.6534 | AUROC=0.7273 | AUPRC=0.7423
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5108 | F1=0.7105 | AUROC=0.8004 | AUPRC=0.8130
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 242.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5873 | F1=0.7037 | AUROC=0.8817 | AUPRC=0.7966
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5456 | F1=0.7626 | AUROC=0.8610 | AUPRC=0.8670
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3852 | F1=0.6836 | AUROC=0.7517 | AUPRC=0.7544
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5221 | F1=0.7335 | AUROC=0.8454 | AUPRC=0.8374
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 171.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5834 | F1=0.6998 | AUROC=0.8698 | AUPRC=0.7897
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5464 | F1=0.7598 | AUROC=0.8409 | AUPRC=0.8591
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3855 | F1=0.6807 | AUROC=0.7452 | AUPRC=0.7540
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4987 | F1=0.7203 | AUROC=0.8277 | AUPRC=0.8299
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 259.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5815 | F1=0.6980 | AUROC=0.8643 | AUPRC=0.7860
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5566 | F1=0.7603 | AUROC=0.8357 | AUPRC=0.8562
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3482 | F1=0.6588 | AUROC=0.7364 | AUPRC=0.7479
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5013 | F1=0.7201 | AUROC=0.8222 | AUPRC=0.8219
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 240.
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5793 | F1=0.6969 | AUROC=0.8599 | AUPRC=0.7827
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5101 | F1=0.7375 | AUROC=0.8300 | AUPRC=0.8545
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3637 | F1=0.6640 | AUROC=0.7270 | AUPRC=0.7396
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4221 | val_loss=0.2229 | val_mcc=0.7254 | val_f1=0.7792 | val_auroc=0.9576

[Epoch 02] train_loss=0.3014 | val_loss=0.2032 | val_mcc=0.7415 | val_f1=0.7921 | val_auroc=0.9616

[Epoch 03] train_loss=0.2803 | val_loss=0.2173 | val_mcc=0.7337 | val_f1=0.7850 | val_auroc=0.9627

[Epoch 04] train_loss=0.2665 | val_loss=0.1960 | val_mcc=0.7473 | val_f1=0.7965 | val_auroc=0.9626

[Epoch 05] train_loss=0.2522 | val_loss=0.2268 | val_mcc=0.7297 | val_f1=0.7814 | val_auroc=0.9613

[Epoch 06] train_loss=0.2349 | val_loss=0.2259 | val_mcc=0.7306 | val_f1=0.7827 | val_auroc=0.9602

[Epoch 07] train_loss=0.2154 | val_loss=0.2428 | val_mcc=0.7184 | val_f1=0.7727 | val_auroc=0.9573

[Epoch 08] train_loss=0.1886 | val_loss=0.2310 | val_mcc=0.7239 | val_f1=0.7781 | val_auroc=0.9547

[Epoch 09] train_loss=0.1551 | val_loss=0.2528 | val_mcc=0.7118 | val_f1=0.7685 | val_auroc=0.9511

[Epoch 10] train_loss=0.1326 | val_loss=0.2942 | val_mcc=0.6973 | val_f1=0.7554 | val_auroc=0.9500
[EarlyStop] epoch=10 | best_val_mcc=0.7473
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7587 | F1=0.8251 | AUROC=0.9520 | AUPRC=0.9032
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8059 | F1=0.8933 | AUROC=0.9671 | AUPRC=0.9657
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4163 | F1=0.7174 | AUROC=0.7641 | AUPRC=0.7646
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5304 | F1=0.7640 | AUROC=0.8669 | AUPRC=0.8547
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4382 | val_loss=0.2015 | val_mcc=0.7427 | val_f1=0.7911 | val_auroc=0.9590

[Epoch 02] train_loss=0.3076 | val_loss=0.1870 | val_mcc=0.7520 | val_f1=0.7940 | val_auroc=0.9628

[Epoch 03] train_loss=0.2909 | val_loss=0.1892 | val_mcc=0.7584 | val_f1=0.8044 | val_auroc=0.9638

[Epoch 04] train_loss=0.2728 | val_loss=0.2058 | val_mcc=0.7472 | val_f1=0.7966 | val_auroc=0.9627

[Epoch 05] train_loss=0.2612 | val_loss=0.2296 | val_mcc=0.7317 | val_f1=0.7827 | val_auroc=0.9618

[Epoch 06] train_loss=0.2391 | val_loss=0.2394 | val_mcc=0.7238 | val_f1=0.7761 | val_auroc=0.9603

[Epoch 07] train_loss=0.2164 | val_loss=0.2459 | val_mcc=0.7107 | val_f1=0.7666 | val_auroc=0.9545

[Epoch 08] train_loss=0.1716 | val_loss=0.2881 | val_mcc=0.6917 | val_f1=0.7512 | val_auroc=0.9492

[Epoch 09] train_loss=0.1489 | val_loss=0.2957 | val_mcc=0.6993 | val_f1=0.7583 | val_auroc=0.9447
[EarlyStop] epoch=9 | best_val_mcc=0.7584
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7668 | F1=0.8301 | AUROC=0.9527 | AUPRC=0.9048
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8024 | F1=0.8889 | AUROC=0.9695 | AUPRC=0.9682
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4120 | F1=0.7075 | AUROC=0.7702 | AUPRC=0.7657
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5560 | F1=0.7751 | AUROC=0.8727 | AUPRC=0.8592
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4200 | val_loss=0.2168 | val_mcc=0.7418 | val_f1=0.7924 | val_auroc=0.9598

[Epoch 02] train_loss=0.3058 | val_loss=0.1938 | val_mcc=0.7544 | val_f1=0.8013 | val_auroc=0.9623

[Epoch 03] train_loss=0.2884 | val_loss=0.1953 | val_mcc=0.7566 | val_f1=0.8036 | val_auroc=0.9631

[Epoch 04] train_loss=0.2749 | val_loss=0.2125 | val_mcc=0.7467 | val_f1=0.7959 | val_auroc=0.9631

[Epoch 05] train_loss=0.2598 | val_loss=0.2092 | val_mcc=0.7406 | val_f1=0.7914 | val_auroc=0.9609

[Epoch 06] train_loss=0.2426 | val_loss=0.2167 | val_mcc=0.7333 | val_f1=0.7856 | val_auroc=0.9578

[Epoch 07] train_loss=0.2209 | val_loss=0.2559 | val_mcc=0.7027 | val_f1=0.7597 | val_auroc=0.9549

[Epoch 08] train_loss=0.1806 | val_loss=0.2666 | val_mcc=0.7023 | val_f1=0.7605 | val_auroc=0.9504

[Epoch 09] train_loss=0.1498 | val_loss=0.2918 | val_mcc=0.6912 | val_f1=0.7519 | val_auroc=0.9443
[EarlyStop] epoch=9 | best_val_mcc=0.7566
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7611 | F1=0.8265 | AUROC=0.9514 | AUPRC=0.9029
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7947 | F1=0.8837 | AUROC=0.9680 | AUPRC=0.9668
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3895 | F1=0.6974 | AUROC=0.7599 | AUPRC=0.7585
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5308 | F1=0.7639 | AUROC=0.8668 | AUPRC=0.8532
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4096 | val_loss=0.2079 | val_mcc=0.7353 | val_f1=0.7870 | val_auroc=0.9592

[Epoch 02] train_loss=0.2984 | val_loss=0.2447 | val_mcc=0.7215 | val_f1=0.7731 | val_auroc=0.9618

[Epoch 03] train_loss=0.2825 | val_loss=0.2029 | val_mcc=0.7473 | val_f1=0.7967 | val_auroc=0.9627

[Epoch 04] train_loss=0.2674 | val_loss=0.2259 | val_mcc=0.7305 | val_f1=0.7816 | val_auroc=0.9631

[Epoch 05] train_loss=0.2498 | val_loss=0.2232 | val_mcc=0.7281 | val_f1=0.7807 | val_auroc=0.9612

[Epoch 06] train_loss=0.2319 | val_loss=0.2325 | val_mcc=0.7231 | val_f1=0.7764 | val_auroc=0.9591

[Epoch 07] train_loss=0.2081 | val_loss=0.2725 | val_mcc=0.6927 | val_f1=0.7496 | val_auroc=0.9565

[Epoch 08] train_loss=0.1704 | val_loss=0.2401 | val_mcc=0.7177 | val_f1=0.7731 | val_auroc=0.9534

[Epoch 09] train_loss=0.1499 | val_loss=0.2558 | val_mcc=0.7125 | val_f1=0.7690 | val_auroc=0.9520
[EarlyStop] epoch=9 | best_val_mcc=0.7473
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7597 | F1=0.8269 | AUROC=0.9518 | AUPRC=0.9031
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7987 | F1=0.8912 | AUROC=0.9676 | AUPRC=0.9661
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4107 | F1=0.7161 | AUROC=0.7681 | AUPRC=0.7643
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5283 | F1=0.7633 | AUROC=0.8714 | AUPRC=0.8574
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 187.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7695 | F1=0.8340 | AUROC=0.9630 | AUPRC=0.9213
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8447 | F1=0.9188 | AUROC=0.9813 | AUPRC=0.9821
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4003 | F1=0.7180 | AUROC=0.7772 | AUPRC=0.7697
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5450 | F1=0.7706 | AUROC=0.8892 | AUPRC=0.8681
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 169.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7546 | F1=0.8234 | AUROC=0.9544 | AUPRC=0.9079
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8071 | F1=0.9003 | AUROC=0.9677 | AUPRC=0.9689
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4161 | F1=0.7239 | AUROC=0.7677 | AUPRC=0.7566
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5393 | F1=0.7681 | AUROC=0.8822 | AUPRC=0.8622
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 130.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7538 | F1=0.8229 | AUROC=0.9545 | AUPRC=0.9070
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8324 | F1=0.9141 | AUROC=0.9704 | AUPRC=0.9706
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4321 | F1=0.7325 | AUROC=0.7724 | AUPRC=0.7665
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5272 | F1=0.7628 | AUROC=0.8753 | AUPRC=0.8578
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 171.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7529 | F1=0.8223 | AUROC=0.9543 | AUPRC=0.9078
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v1_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8167 | F1=0.9034 | AUROC=0.9687 | AUPRC=0.9691
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5316 | val_loss=0.3999 | val_mcc=0.5497 | val_f1=0.6397 | val_auroc=0.8581

[Epoch 02] train_loss=0.4651 | val_loss=0.3893 | val_mcc=0.5642 | val_f1=0.6518 | val_auroc=0.8692

[Epoch 03] train_loss=0.4349 | val_loss=0.3935 | val_mcc=0.5675 | val_f1=0.6547 | val_auroc=0.8787

[Epoch 04] train_loss=0.4077 | val_loss=0.3540 | val_mcc=0.5888 | val_f1=0.6712 | val_auroc=0.8886

[Epoch 05] train_loss=0.3780 | val_loss=0.3482 | val_mcc=0.5872 | val_f1=0.6697 | val_auroc=0.8889

[Epoch 06] train_loss=0.3500 | val_loss=0.4021 | val_mcc=0.5623 | val_f1=0.6498 | val_auroc=0.8904

[Epoch 07] train_loss=0.3226 | val_loss=0.4002 | val_mcc=0.5593 | val_f1=0.6479 | val_auroc=0.8878

[Epoch 08] train_loss=0.2959 | val_loss=0.4044 | val_mcc=0.5618 | val_f1=0.6501 | val_auroc=0.8853

[Epoch 09] train_loss=0.2575 | val_loss=0.4296 | val_mcc=0.5594 | val_f1=0.6482 | val_auroc=0.8845

[Epoch 10] train_loss=0.2391 | val_loss=0.4545 | val_mcc=0.5541 | val_f1=0.6433 | val_auroc=0.8818
[EarlyStop] epoch=10 | best_val_mcc=0.5888
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6332 | F1=0.7351 | AUROC=0.8998 | AUPRC=0.8084
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.6021 | F1=0.7941 | AUROC=0.8833 | AUPRC=0.8749
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4449 | F1=0.7076 | AUROC=0.7856 | AUPRC=0.7734
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5749 | F1=0.7666 | AUROC=0.8707 | AUPRC=0.8460
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5442 | val_loss=0.4102 | val_mcc=0.5455 | val_f1=0.6369 | val_auroc=0.8539

[Epoch 02] train_loss=0.4680 | val_loss=0.4237 | val_mcc=0.5484 | val_f1=0.6396 | val_auroc=0.8695

[Epoch 03] train_loss=0.4388 | val_loss=0.4344 | val_mcc=0.5483 | val_f1=0.6382 | val_auroc=0.8761

[Epoch 04] train_loss=0.4069 | val_loss=0.3926 | val_mcc=0.5730 | val_f1=0.6589 | val_auroc=0.8824

[Epoch 05] train_loss=0.3783 | val_loss=0.4189 | val_mcc=0.5641 | val_f1=0.6506 | val_auroc=0.8899

[Epoch 06] train_loss=0.3480 | val_loss=0.4514 | val_mcc=0.5441 | val_f1=0.6344 | val_auroc=0.8833

[Epoch 07] train_loss=0.3222 | val_loss=0.3854 | val_mcc=0.5706 | val_f1=0.6568 | val_auroc=0.8808

[Epoch 08] train_loss=0.2961 | val_loss=0.5199 | val_mcc=0.5280 | val_f1=0.6199 | val_auroc=0.8764

[Epoch 09] train_loss=0.2528 | val_loss=0.5238 | val_mcc=0.5396 | val_f1=0.6315 | val_auroc=0.8732

[Epoch 10] train_loss=0.2369 | val_loss=0.5296 | val_mcc=0.5435 | val_f1=0.6356 | val_auroc=0.8703
[EarlyStop] epoch=10 | best_val_mcc=0.5730
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6229 | F1=0.7299 | AUROC=0.8970 | AUPRC=0.8003
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5875 | F1=0.7920 | AUROC=0.8761 | AUPRC=0.8743
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4496 | F1=0.7183 | AUROC=0.7825 | AUPRC=0.7765
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6004 | F1=0.7834 | AUROC=0.8712 | AUPRC=0.8377
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5201 | val_loss=0.3873 | val_mcc=0.5510 | val_f1=0.6408 | val_auroc=0.8587

[Epoch 02] train_loss=0.4616 | val_loss=0.3394 | val_mcc=0.5731 | val_f1=0.6544 | val_auroc=0.8717

[Epoch 03] train_loss=0.4267 | val_loss=0.3679 | val_mcc=0.5727 | val_f1=0.6587 | val_auroc=0.8814

[Epoch 04] train_loss=0.3945 | val_loss=0.3605 | val_mcc=0.5765 | val_f1=0.6617 | val_auroc=0.8885

[Epoch 05] train_loss=0.3696 | val_loss=0.3299 | val_mcc=0.5958 | val_f1=0.6741 | val_auroc=0.8910

[Epoch 06] train_loss=0.3427 | val_loss=0.3850 | val_mcc=0.5620 | val_f1=0.6503 | val_auroc=0.8902

[Epoch 07] train_loss=0.3087 | val_loss=0.4396 | val_mcc=0.5524 | val_f1=0.6420 | val_auroc=0.8852

[Epoch 08] train_loss=0.2783 | val_loss=0.3992 | val_mcc=0.5720 | val_f1=0.6577 | val_auroc=0.8819

[Epoch 09] train_loss=0.2495 | val_loss=0.4967 | val_mcc=0.5558 | val_f1=0.6454 | val_auroc=0.8806

[Epoch 10] train_loss=0.2073 | val_loss=0.4630 | val_mcc=0.5560 | val_f1=0.6404 | val_auroc=0.8731

[Epoch 11] train_loss=0.1911 | val_loss=0.5439 | val_mcc=0.5401 | val_f1=0.6334 | val_auroc=0.8672
[EarlyStop] epoch=11 | best_val_mcc=0.5958
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6452 | F1=0.7374 | AUROC=0.9070 | AUPRC=0.8066
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5831 | F1=0.7668 | AUROC=0.8907 | AUPRC=0.8728
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4549 | F1=0.6954 | AUROC=0.7860 | AUPRC=0.7743
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5808 | F1=0.7571 | AUROC=0.8802 | AUPRC=0.8507
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5325 | val_loss=0.3867 | val_mcc=0.5431 | val_f1=0.6339 | val_auroc=0.8576

[Epoch 02] train_loss=0.4618 | val_loss=0.4365 | val_mcc=0.5380 | val_f1=0.6312 | val_auroc=0.8677

[Epoch 03] train_loss=0.4337 | val_loss=0.3835 | val_mcc=0.5648 | val_f1=0.6526 | val_auroc=0.8791

[Epoch 04] train_loss=0.4039 | val_loss=0.3640 | val_mcc=0.5778 | val_f1=0.6628 | val_auroc=0.8846

[Epoch 05] train_loss=0.3769 | val_loss=0.3907 | val_mcc=0.5606 | val_f1=0.6486 | val_auroc=0.8898

[Epoch 06] train_loss=0.3522 | val_loss=0.3790 | val_mcc=0.5700 | val_f1=0.6565 | val_auroc=0.8891

[Epoch 07] train_loss=0.3211 | val_loss=0.3970 | val_mcc=0.5674 | val_f1=0.6540 | val_auroc=0.8938

[Epoch 08] train_loss=0.2897 | val_loss=0.3820 | val_mcc=0.5634 | val_f1=0.6514 | val_auroc=0.8855

[Epoch 09] train_loss=0.2512 | val_loss=0.4162 | val_mcc=0.5616 | val_f1=0.6497 | val_auroc=0.8888

[Epoch 10] train_loss=0.2298 | val_loss=0.4382 | val_mcc=0.5565 | val_f1=0.6457 | val_auroc=0.8856
[EarlyStop] epoch=10 | best_val_mcc=0.5778
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6365 | F1=0.7380 | AUROC=0.8994 | AUPRC=0.8113
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5762 | F1=0.7825 | AUROC=0.8789 | AUPRC=0.8705
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4358 | F1=0.7034 | AUROC=0.7791 | AUPRC=0.7646
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5729 | F1=0.7679 | AUROC=0.8730 | AUPRC=0.8509
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 235.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6146 | F1=0.7251 | AUROC=0.8997 | AUPRC=0.7998
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5919 | F1=0.8000 | AUROC=0.8801 | AUPRC=0.8790
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4118 | F1=0.7044 | AUROC=0.7796 | AUPRC=0.7504
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5937 | F1=0.7857 | AUROC=0.8723 | AUPRC=0.8419
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 203.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6148 | F1=0.7247 | AUROC=0.8964 | AUPRC=0.8040
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5846 | F1=0.7908 | AUROC=0.8749 | AUPRC=0.8679
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4137 | F1=0.6981 | AUROC=0.7789 | AUPRC=0.7652
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.6006 | F1=0.7863 | AUROC=0.8753 | AUPRC=0.8484
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 74.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6199 | F1=0.7277 | AUROC=0.8904 | AUPRC=0.7919
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5593 | F1=0.7724 | AUROC=0.8681 | AUPRC=0.8629
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4499 | F1=0.7162 | AUROC=0.7781 | AUPRC=0.7668
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5432 | F1=0.7530 | AUROC=0.8578 | AUPRC=0.8320
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 109.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6105 | F1=0.7219 | AUROC=0.8924 | AUPRC=0.7960
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5619 | F1=0.7794 | AUROC=0.8821 | AUPRC=0.8680
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4344 | F1=0.7133 | AUROC=0.7781 | AUPRC=0.7750
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']

[Epoch 01] train_loss=0.4002 | val_loss=0.2251 | val_mcc=0.7250 | val_f1=0.7790 | val_auroc=0.9525

[Epoch 02] train_loss=0.2992 | val_loss=0.2125 | val_mcc=0.7464 | val_f1=0.7960 | val_auroc=0.9599

[Epoch 03] train_loss=0.2775 | val_loss=0.2300 | val_mcc=0.7306 | val_f1=0.7823 | val_auroc=0.9606

[Epoch 04] train_loss=0.2610 | val_loss=0.2227 | val_mcc=0.7424 | val_f1=0.7919 | val_auroc=0.9617

[Epoch 05] train_loss=0.2474 | val_loss=0.2161 | val_mcc=0.7431 | val_f1=0.7931 | val_auroc=0.9606

[Epoch 06] train_loss=0.2285 | val_loss=0.2244 | val_mcc=0.7442 | val_f1=0.7933 | val_auroc=0.9625

[Epoch 07] train_loss=0.2091 | val_loss=0.2011 | val_mcc=0.7605 | val_f1=0.8072 | val_auroc=0.9642

[Epoch 08] train_loss=0.1949 | val_loss=0.2235 | val_mcc=0.7462 | val_f1=0.7952 | val_auroc=0.9629

[Epoch 09] train_loss=0.1844 | val_loss=0.2247 | val_mcc=0.7487 | val_f1=0.7974 | val_auroc=0.9624

[Epoch 10] train_loss=0.1735 | val_loss=0.2360 | val_mcc=0.7490 | val_f1=0.7970 | val_auroc=0.9617

[Epoch 11] train_loss=0.1597 | val_loss=0.2309 | val_mcc=0.7527 | val_f1=0.8009 | val_auroc=0.9612

[Epoch 12] train_loss=0.1446 | val_loss=0.2433 | val_mcc=0.7446 | val_f1=0.7942 | val_auroc=0.9609

[Epoch 13] train_loss=0.1380 | val_loss=0.2484 | val_mcc=0.7464 | val_f1=0.7957 | val_auroc=0.9591
[EarlyStop] epoch=13 | best_val_mcc=0.7605
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7756 | F1=0.8381 | AUROC=0.9591 | AUPRC=0.9133
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8080 | F1=0.8991 | AUROC=0.9747 | AUPRC=0.9738
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4347 | F1=0.7273 | AUROC=0.7785 | AUPRC=0.7634
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5968 | F1=0.7940 | AUROC=0.8910 | AUPRC=0.8629
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4180 | val_loss=0.2451 | val_mcc=0.7133 | val_f1=0.7689 | val_auroc=0.9547

[Epoch 02] train_loss=0.3051 | val_loss=0.2359 | val_mcc=0.7254 | val_f1=0.7780 | val_auroc=0.9594

[Epoch 03] train_loss=0.2847 | val_loss=0.2362 | val_mcc=0.7323 | val_f1=0.7832 | val_auroc=0.9603

[Epoch 04] train_loss=0.2653 | val_loss=0.2207 | val_mcc=0.7497 | val_f1=0.7985 | val_auroc=0.9612

[Epoch 05] train_loss=0.2493 | val_loss=0.2116 | val_mcc=0.7551 | val_f1=0.8030 | val_auroc=0.9613

[Epoch 06] train_loss=0.2311 | val_loss=0.2536 | val_mcc=0.7236 | val_f1=0.7759 | val_auroc=0.9591

[Epoch 07] train_loss=0.2098 | val_loss=0.2287 | val_mcc=0.7389 | val_f1=0.7896 | val_auroc=0.9599

[Epoch 08] train_loss=0.1928 | val_loss=0.2171 | val_mcc=0.7466 | val_f1=0.7962 | val_auroc=0.9590

[Epoch 09] train_loss=0.1752 | val_loss=0.2881 | val_mcc=0.7178 | val_f1=0.7712 | val_auroc=0.9561

[Epoch 10] train_loss=0.1430 | val_loss=0.2954 | val_mcc=0.7203 | val_f1=0.7742 | val_auroc=0.9533

[Epoch 11] train_loss=0.1276 | val_loss=0.3023 | val_mcc=0.7185 | val_f1=0.7730 | val_auroc=0.9512
[EarlyStop] epoch=11 | best_val_mcc=0.7551
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7708 | F1=0.8347 | AUROC=0.9554 | AUPRC=0.9039
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8059 | F1=0.8969 | AUROC=0.9729 | AUPRC=0.9732
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4373 | F1=0.7275 | AUROC=0.7839 | AUPRC=0.7743
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6076 | F1=0.7992 | AUROC=0.8926 | AUPRC=0.8559
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4154 | val_loss=0.2102 | val_mcc=0.7240 | val_f1=0.7752 | val_auroc=0.9539

[Epoch 02] train_loss=0.3062 | val_loss=0.2283 | val_mcc=0.7356 | val_f1=0.7868 | val_auroc=0.9600

[Epoch 03] train_loss=0.2817 | val_loss=0.2038 | val_mcc=0.7524 | val_f1=0.8008 | val_auroc=0.9625

[Epoch 04] train_loss=0.2637 | val_loss=0.2272 | val_mcc=0.7382 | val_f1=0.7881 | val_auroc=0.9633

[Epoch 05] train_loss=0.2468 | val_loss=0.1923 | val_mcc=0.7643 | val_f1=0.8102 | val_auroc=0.9651

[Epoch 06] train_loss=0.2325 | val_loss=0.2154 | val_mcc=0.7504 | val_f1=0.7991 | val_auroc=0.9617

[Epoch 07] train_loss=0.2101 | val_loss=0.1919 | val_mcc=0.7706 | val_f1=0.8143 | val_auroc=0.9642

[Epoch 08] train_loss=0.1909 | val_loss=0.2058 | val_mcc=0.7652 | val_f1=0.8105 | val_auroc=0.9615

[Epoch 09] train_loss=0.1676 | val_loss=0.2857 | val_mcc=0.7215 | val_f1=0.7728 | val_auroc=0.9597

[Epoch 10] train_loss=0.1476 | val_loss=0.2471 | val_mcc=0.7394 | val_f1=0.7905 | val_auroc=0.9579

[Epoch 11] train_loss=0.1302 | val_loss=0.2745 | val_mcc=0.7352 | val_f1=0.7868 | val_auroc=0.9566

[Epoch 12] train_loss=0.1022 | val_loss=0.3046 | val_mcc=0.7275 | val_f1=0.7810 | val_auroc=0.9527

[Epoch 13] train_loss=0.0913 | val_loss=0.3087 | val_mcc=0.7307 | val_f1=0.7835 | val_auroc=0.9532
[EarlyStop] epoch=13 | best_val_mcc=0.7706
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7899 | F1=0.8455 | AUROC=0.9589 | AUPRC=0.9127
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7909 | F1=0.8827 | AUROC=0.9732 | AUPRC=0.9719
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4826 | F1=0.7356 | AUROC=0.7905 | AUPRC=0.7765
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6600 | F1=0.8221 | AUROC=0.8989 | AUPRC=0.8710
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4010 | val_loss=0.2116 | val_mcc=0.7365 | val_f1=0.7875 | val_auroc=0.9563

[Epoch 02] train_loss=0.2997 | val_loss=0.2269 | val_mcc=0.7383 | val_f1=0.7893 | val_auroc=0.9593

[Epoch 03] train_loss=0.2791 | val_loss=0.2175 | val_mcc=0.7446 | val_f1=0.7944 | val_auroc=0.9608

[Epoch 04] train_loss=0.2608 | val_loss=0.2159 | val_mcc=0.7480 | val_f1=0.7966 | val_auroc=0.9641

[Epoch 05] train_loss=0.2449 | val_loss=0.1888 | val_mcc=0.7661 | val_f1=0.8116 | val_auroc=0.9652

[Epoch 06] train_loss=0.2279 | val_loss=0.2009 | val_mcc=0.7624 | val_f1=0.8087 | val_auroc=0.9650

[Epoch 07] train_loss=0.2080 | val_loss=0.2291 | val_mcc=0.7409 | val_f1=0.7899 | val_auroc=0.9650

[Epoch 08] train_loss=0.1841 | val_loss=0.2364 | val_mcc=0.7405 | val_f1=0.7892 | val_auroc=0.9658

[Epoch 09] train_loss=0.1686 | val_loss=0.2371 | val_mcc=0.7447 | val_f1=0.7939 | val_auroc=0.9609

[Epoch 10] train_loss=0.1389 | val_loss=0.2358 | val_mcc=0.7484 | val_f1=0.7971 | val_auroc=0.9624

[Epoch 11] train_loss=0.1233 | val_loss=0.2543 | val_mcc=0.7381 | val_f1=0.7885 | val_auroc=0.9608
[EarlyStop] epoch=11 | best_val_mcc=0.7661
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7742 | F1=0.8361 | AUROC=0.9595 | AUPRC=0.9140
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8027 | F1=0.8919 | AUROC=0.9758 | AUPRC=0.9751
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4434 | F1=0.7229 | AUROC=0.7763 | AUPRC=0.7677
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5807 | F1=0.7864 | AUROC=0.8860 | AUPRC=0.8576
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 183.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7826 | F1=0.8433 | AUROC=0.9654 | AUPRC=0.9231
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8759 | F1=0.9351 | AUROC=0.9869 | AUPRC=0.9875
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4338 | F1=0.7355 | AUROC=0.7772 | AUPRC=0.7585
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5738 | F1=0.7831 | AUROC=0.9005 | AUPRC=0.8688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 180.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7607 | F1=0.8278 | AUROC=0.9579 | AUPRC=0.9124
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8219 | F1=0.9069 | AUROC=0.9775 | AUPRC=0.9773
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4149 | F1=0.7238 | AUROC=0.7782 | AUPRC=0.7660
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5817 | F1=0.7870 | AUROC=0.8948 | AUPRC=0.8654
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 177.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7631 | F1=0.8294 | AUROC=0.9556 | AUPRC=0.9063
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8219 | F1=0.9069 | AUROC=0.9743 | AUPRC=0.9742
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4196 | F1=0.7235 | AUROC=0.7750 | AUPRC=0.7646
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5844 | F1=0.7884 | AUROC=0.8870 | AUPRC=0.8512
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 142.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7580 | F1=0.8258 | AUROC=0.9569 | AUPRC=0.9019
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8442 | F1=0.9192 | AUROC=0.9770 | AUPRC=0.9776
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.5564 | val_loss=0.4260 | val_mcc=0.4956 | val_f1=0.5966 | val_auroc=0.8367

[Epoch 02] train_loss=0.4877 | val_loss=0.4102 | val_mcc=0.5111 | val_f1=0.6102 | val_auroc=0.8571

[Epoch 03] train_loss=0.4523 | val_loss=0.3982 | val_mcc=0.5274 | val_f1=0.6236 | val_auroc=0.8749

[Epoch 04] train_loss=0.4187 | val_loss=0.3960 | val_mcc=0.5354 | val_f1=0.6297 | val_auroc=0.8810

[Epoch 05] train_loss=0.3953 | val_loss=0.3476 | val_mcc=0.5519 | val_f1=0.6381 | val_auroc=0.8809

[Epoch 06] train_loss=0.3671 | val_loss=0.3704 | val_mcc=0.5460 | val_f1=0.6371 | val_auroc=0.8809

[Epoch 07] train_loss=0.3389 | val_loss=0.4297 | val_mcc=0.5272 | val_f1=0.6231 | val_auroc=0.8770

[Epoch 08] train_loss=0.3081 | val_loss=0.4179 | val_mcc=0.5291 | val_f1=0.6246 | val_auroc=0.8747

[Epoch 09] train_loss=0.2851 | val_loss=0.4574 | val_mcc=0.5167 | val_f1=0.6152 | val_auroc=0.8726

[Epoch 10] train_loss=0.2410 | val_loss=0.4962 | val_mcc=0.5099 | val_f1=0.6096 | val_auroc=0.8694

[Epoch 11] train_loss=0.2232 | val_loss=0.5102 | val_mcc=0.5121 | val_f1=0.6115 | val_auroc=0.8662
[EarlyStop] epoch=11 | best_val_mcc=0.5519
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6144 | F1=0.7154 | AUROC=0.8960 | AUPRC=0.7947
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5637 | F1=0.7547 | AUROC=0.8639 | AUPRC=0.8613
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3945 | F1=0.6656 | AUROC=0.7499 | AUPRC=0.7287
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5512 | F1=0.7351 | AUROC=0.8669 | AUPRC=0.8399
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5577 | val_loss=0.4478 | val_mcc=0.4873 | val_f1=0.5916 | val_auroc=0.8338

[Epoch 02] train_loss=0.4877 | val_loss=0.4432 | val_mcc=0.5057 | val_f1=0.6066 | val_auroc=0.8627

[Epoch 03] train_loss=0.4539 | val_loss=0.4019 | val_mcc=0.5259 | val_f1=0.6224 | val_auroc=0.8760

[Epoch 04] train_loss=0.4199 | val_loss=0.4155 | val_mcc=0.5311 | val_f1=0.6263 | val_auroc=0.8775

[Epoch 05] train_loss=0.3906 | val_loss=0.4036 | val_mcc=0.5266 | val_f1=0.6229 | val_auroc=0.8776

[Epoch 06] train_loss=0.3629 | val_loss=0.5252 | val_mcc=0.5064 | val_f1=0.6015 | val_auroc=0.8794

[Epoch 07] train_loss=0.3364 | val_loss=0.4225 | val_mcc=0.5286 | val_f1=0.6245 | val_auroc=0.8750

[Epoch 08] train_loss=0.3096 | val_loss=0.4450 | val_mcc=0.5287 | val_f1=0.6242 | val_auroc=0.8736

[Epoch 09] train_loss=0.2632 | val_loss=0.5454 | val_mcc=0.5148 | val_f1=0.6132 | val_auroc=0.8688

[Epoch 10] train_loss=0.2490 | val_loss=0.6475 | val_mcc=0.4994 | val_f1=0.5992 | val_auroc=0.8643
[EarlyStop] epoch=10 | best_val_mcc=0.5311
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5974 | F1=0.7123 | AUROC=0.8912 | AUPRC=0.7872
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5564 | F1=0.7713 | AUROC=0.8684 | AUPRC=0.8672
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3820 | F1=0.6935 | AUROC=0.7493 | AUPRC=0.7313
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5446 | F1=0.7539 | AUROC=0.8671 | AUPRC=0.8375
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5534 | val_loss=0.3938 | val_mcc=0.4962 | val_f1=0.5917 | val_auroc=0.8386

[Epoch 02] train_loss=0.4853 | val_loss=0.3618 | val_mcc=0.5195 | val_f1=0.6097 | val_auroc=0.8599

[Epoch 03] train_loss=0.4494 | val_loss=0.3670 | val_mcc=0.5323 | val_f1=0.6256 | val_auroc=0.8764

[Epoch 04] train_loss=0.4226 | val_loss=0.3682 | val_mcc=0.5379 | val_f1=0.6314 | val_auroc=0.8809

[Epoch 05] train_loss=0.3904 | val_loss=0.3645 | val_mcc=0.5406 | val_f1=0.6321 | val_auroc=0.8783

[Epoch 06] train_loss=0.3619 | val_loss=0.3894 | val_mcc=0.5396 | val_f1=0.6326 | val_auroc=0.8787

[Epoch 07] train_loss=0.3248 | val_loss=0.5046 | val_mcc=0.5022 | val_f1=0.6016 | val_auroc=0.8698

[Epoch 08] train_loss=0.3016 | val_loss=0.5369 | val_mcc=0.5160 | val_f1=0.6134 | val_auroc=0.8725

[Epoch 09] train_loss=0.2686 | val_loss=0.5081 | val_mcc=0.5154 | val_f1=0.6143 | val_auroc=0.8625

[Epoch 10] train_loss=0.2219 | val_loss=0.5427 | val_mcc=0.5154 | val_f1=0.6141 | val_auroc=0.8565

[Epoch 11] train_loss=0.2018 | val_loss=0.6700 | val_mcc=0.4944 | val_f1=0.5970 | val_auroc=0.8548
[EarlyStop] epoch=11 | best_val_mcc=0.5406
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6108 | F1=0.7160 | AUROC=0.8919 | AUPRC=0.7842
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5555 | F1=0.7554 | AUROC=0.8614 | AUPRC=0.8569
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3724 | F1=0.6709 | AUROC=0.7450 | AUPRC=0.7275
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5498 | F1=0.7421 | AUROC=0.8616 | AUPRC=0.8309
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5603 | val_loss=0.4315 | val_mcc=0.4934 | val_f1=0.5954 | val_auroc=0.8343

[Epoch 02] train_loss=0.4905 | val_loss=0.4155 | val_mcc=0.5070 | val_f1=0.6071 | val_auroc=0.8559

[Epoch 03] train_loss=0.4573 | val_loss=0.3960 | val_mcc=0.5175 | val_f1=0.6158 | val_auroc=0.8710

[Epoch 04] train_loss=0.4265 | val_loss=0.3749 | val_mcc=0.5406 | val_f1=0.6335 | val_auroc=0.8801

[Epoch 05] train_loss=0.3966 | val_loss=0.3961 | val_mcc=0.5376 | val_f1=0.6312 | val_auroc=0.8819

[Epoch 06] train_loss=0.3678 | val_loss=0.3830 | val_mcc=0.5404 | val_f1=0.6335 | val_auroc=0.8798

[Epoch 07] train_loss=0.3377 | val_loss=0.4338 | val_mcc=0.5213 | val_f1=0.6185 | val_auroc=0.8766

[Epoch 08] train_loss=0.3076 | val_loss=0.4261 | val_mcc=0.5279 | val_f1=0.6239 | val_auroc=0.8742

[Epoch 09] train_loss=0.2640 | val_loss=0.4749 | val_mcc=0.5123 | val_f1=0.6112 | val_auroc=0.8691

[Epoch 10] train_loss=0.2450 | val_loss=0.4835 | val_mcc=0.5218 | val_f1=0.6188 | val_auroc=0.8716
[EarlyStop] epoch=10 | best_val_mcc=0.5406
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6237 | F1=0.7292 | AUROC=0.8926 | AUPRC=0.7914
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5944 | F1=0.7869 | AUROC=0.8644 | AUPRC=0.8671
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3833 | F1=0.6898 | AUROC=0.7507 | AUPRC=0.7314
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5861 | F1=0.7736 | AUROC=0.8664 | AUPRC=0.8378
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 186.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5725 | F1=0.6962 | AUROC=0.8825 | AUPRC=0.7785
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5165 | F1=0.7578 | AUROC=0.8526 | AUPRC=0.8572
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3703 | F1=0.6907 | AUROC=0.7337 | AUPRC=0.7184
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5367 | F1=0.7545 | AUROC=0.8514 | AUPRC=0.8277
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 128.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5884 | F1=0.7069 | AUROC=0.8876 | AUPRC=0.7833
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5447 | F1=0.7688 | AUROC=0.8596 | AUPRC=0.8635
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3774 | F1=0.6887 | AUROC=0.7478 | AUPRC=0.7334
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5481 | F1=0.7572 | AUROC=0.8556 | AUPRC=0.8309
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 74.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5834 | F1=0.7033 | AUROC=0.8854 | AUPRC=0.7778
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5307 | F1=0.7591 | AUROC=0.8585 | AUPRC=0.8610
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3803 | F1=0.6878 | AUROC=0.7495 | AUPRC=0.7370
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5531 | F1=0.7590 | AUROC=0.8541 | AUPRC=0.8257
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 99.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5836 | F1=0.7036 | AUROC=0.8845 | AUPRC=0.7836
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5477 | F1=0.7679 | AUROC=0.8550 | AUPRC=0.8594
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3685 | F1=0.6865 | AUROC=0.7462 | AUPRC=0.7358
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']

[Epoch 01] train_loss=0.4137 | val_loss=0.2169 | val_mcc=0.7290 | val_f1=0.7816 | val_auroc=0.9556

[Epoch 02] train_loss=0.2972 | val_loss=0.2331 | val_mcc=0.7234 | val_f1=0.7768 | val_auroc=0.9596

[Epoch 03] train_loss=0.2758 | val_loss=0.2251 | val_mcc=0.7342 | val_f1=0.7849 | val_auroc=0.9635

[Epoch 04] train_loss=0.2573 | val_loss=0.2217 | val_mcc=0.7439 | val_f1=0.7928 | val_auroc=0.9638

[Epoch 05] train_loss=0.2364 | val_loss=0.2077 | val_mcc=0.7516 | val_f1=0.7999 | val_auroc=0.9642

[Epoch 06] train_loss=0.2213 | val_loss=0.2063 | val_mcc=0.7569 | val_f1=0.8043 | val_auroc=0.9644

[Epoch 07] train_loss=0.2056 | val_loss=0.2711 | val_mcc=0.7158 | val_f1=0.7665 | val_auroc=0.9637

[Epoch 08] train_loss=0.1814 | val_loss=0.2539 | val_mcc=0.7324 | val_f1=0.7826 | val_auroc=0.9618

[Epoch 09] train_loss=0.1616 | val_loss=0.2844 | val_mcc=0.7113 | val_f1=0.7639 | val_auroc=0.9601

[Epoch 10] train_loss=0.1473 | val_loss=0.2494 | val_mcc=0.7342 | val_f1=0.7863 | val_auroc=0.9575

[Epoch 11] train_loss=0.1198 | val_loss=0.2646 | val_mcc=0.7281 | val_f1=0.7812 | val_auroc=0.9584

[Epoch 12] train_loss=0.1067 | val_loss=0.2973 | val_mcc=0.7126 | val_f1=0.7675 | val_auroc=0.9568
[EarlyStop] epoch=12 | best_val_mcc=0.7569
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7565 | F1=0.8244 | AUROC=0.9569 | AUPRC=0.9003
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8063 | F1=0.8966 | AUROC=0.9738 | AUPRC=0.9742
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4231 | F1=0.7231 | AUROC=0.7646 | AUPRC=0.7322
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5448 | F1=0.7702 | AUROC=0.8796 | AUPRC=0.8518
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4090 | val_loss=0.2171 | val_mcc=0.7098 | val_f1=0.7527 | val_auroc=0.9551

[Epoch 02] train_loss=0.3098 | val_loss=0.2159 | val_mcc=0.7357 | val_f1=0.7875 | val_auroc=0.9584

[Epoch 03] train_loss=0.2859 | val_loss=0.2212 | val_mcc=0.7415 | val_f1=0.7918 | val_auroc=0.9611

[Epoch 04] train_loss=0.2585 | val_loss=0.2343 | val_mcc=0.7364 | val_f1=0.7869 | val_auroc=0.9609

[Epoch 05] train_loss=0.2405 | val_loss=0.2277 | val_mcc=0.7410 | val_f1=0.7908 | val_auroc=0.9622

[Epoch 06] train_loss=0.2185 | val_loss=0.2197 | val_mcc=0.7341 | val_f1=0.7860 | val_auroc=0.9592

[Epoch 07] train_loss=0.2002 | val_loss=0.2371 | val_mcc=0.7263 | val_f1=0.7799 | val_auroc=0.9572

[Epoch 08] train_loss=0.1727 | val_loss=0.2824 | val_mcc=0.7111 | val_f1=0.7663 | val_auroc=0.9557

[Epoch 09] train_loss=0.1585 | val_loss=0.2838 | val_mcc=0.7212 | val_f1=0.7754 | val_auroc=0.9561
[EarlyStop] epoch=9 | best_val_mcc=0.7415
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7477 | F1=0.8185 | AUROC=0.9546 | AUPRC=0.8921
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8194 | F1=0.9050 | AUROC=0.9716 | AUPRC=0.9724
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4006 | F1=0.7161 | AUROC=0.7641 | AUPRC=0.7432
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5285 | F1=0.7634 | AUROC=0.8775 | AUPRC=0.8541
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4256 | val_loss=0.2165 | val_mcc=0.7225 | val_f1=0.7748 | val_auroc=0.9543

[Epoch 02] train_loss=0.3093 | val_loss=0.2194 | val_mcc=0.7370 | val_f1=0.7885 | val_auroc=0.9583

[Epoch 03] train_loss=0.2835 | val_loss=0.2171 | val_mcc=0.7385 | val_f1=0.7893 | val_auroc=0.9613

[Epoch 04] train_loss=0.2637 | val_loss=0.2281 | val_mcc=0.7383 | val_f1=0.7875 | val_auroc=0.9637

[Epoch 05] train_loss=0.2401 | val_loss=0.2069 | val_mcc=0.7525 | val_f1=0.8007 | val_auroc=0.9612

[Epoch 06] train_loss=0.2181 | val_loss=0.2085 | val_mcc=0.7484 | val_f1=0.7972 | val_auroc=0.9609

[Epoch 07] train_loss=0.1989 | val_loss=0.2293 | val_mcc=0.7404 | val_f1=0.7911 | val_auroc=0.9586

[Epoch 08] train_loss=0.1793 | val_loss=0.2372 | val_mcc=0.7342 | val_f1=0.7861 | val_auroc=0.9583

[Epoch 09] train_loss=0.1587 | val_loss=0.2693 | val_mcc=0.7249 | val_f1=0.7782 | val_auroc=0.9580

[Epoch 10] train_loss=0.1268 | val_loss=0.2719 | val_mcc=0.7288 | val_f1=0.7820 | val_auroc=0.9542

[Epoch 11] train_loss=0.1105 | val_loss=0.3057 | val_mcc=0.7172 | val_f1=0.7727 | val_auroc=0.9517
[EarlyStop] epoch=11 | best_val_mcc=0.7525
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7502 | F1=0.8183 | AUROC=0.9536 | AUPRC=0.8904
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7788 | F1=0.8769 | AUROC=0.9654 | AUPRC=0.9623
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4436 | F1=0.7242 | AUROC=0.7713 | AUPRC=0.7463
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5912 | F1=0.7900 | AUROC=0.8825 | AUPRC=0.8567
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4045 | val_loss=0.2402 | val_mcc=0.7272 | val_f1=0.7791 | val_auroc=0.9591

[Epoch 02] train_loss=0.3006 | val_loss=0.2375 | val_mcc=0.7271 | val_f1=0.7787 | val_auroc=0.9609

[Epoch 03] train_loss=0.2756 | val_loss=0.2163 | val_mcc=0.7352 | val_f1=0.7869 | val_auroc=0.9606

[Epoch 04] train_loss=0.2554 | val_loss=0.1963 | val_mcc=0.7527 | val_f1=0.8007 | val_auroc=0.9632

[Epoch 05] train_loss=0.2316 | val_loss=0.2382 | val_mcc=0.7349 | val_f1=0.7839 | val_auroc=0.9656

[Epoch 06] train_loss=0.2139 | val_loss=0.1989 | val_mcc=0.7557 | val_f1=0.8034 | val_auroc=0.9643

[Epoch 07] train_loss=0.1904 | val_loss=0.2381 | val_mcc=0.7369 | val_f1=0.7870 | val_auroc=0.9628

[Epoch 08] train_loss=0.1705 | val_loss=0.2608 | val_mcc=0.7246 | val_f1=0.7769 | val_auroc=0.9601

[Epoch 09] train_loss=0.1463 | val_loss=0.2836 | val_mcc=0.7205 | val_f1=0.7734 | val_auroc=0.9591

[Epoch 10] train_loss=0.1284 | val_loss=0.3147 | val_mcc=0.6945 | val_f1=0.7526 | val_auroc=0.9553

[Epoch 11] train_loss=0.1014 | val_loss=0.3115 | val_mcc=0.7068 | val_f1=0.7627 | val_auroc=0.9556

[Epoch 12] train_loss=0.0849 | val_loss=0.3116 | val_mcc=0.7137 | val_f1=0.7689 | val_auroc=0.9556
[EarlyStop] epoch=12 | best_val_mcc=0.7557
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7579 | F1=0.8242 | AUROC=0.9556 | AUPRC=0.8972
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7970 | F1=0.8889 | AUROC=0.9723 | AUPRC=0.9709
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4243 | F1=0.7168 | AUROC=0.7669 | AUPRC=0.7401
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5627 | F1=0.7767 | AUROC=0.8802 | AUPRC=0.8540
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 199.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7660 | F1=0.8315 | AUROC=0.9626 | AUPRC=0.9144
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8597 | F1=0.9256 | AUROC=0.9813 | AUPRC=0.9812
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4060 | F1=0.7222 | AUROC=0.7642 | AUPRC=0.7411
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5479 | F1=0.7718 | AUROC=0.8902 | AUPRC=0.8604
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 174.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7568 | F1=0.8250 | AUROC=0.9560 | AUPRC=0.9005
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8214 | F1=0.9075 | AUROC=0.9729 | AUPRC=0.9747
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4128 | F1=0.7244 | AUROC=0.7648 | AUPRC=0.7387
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5535 | F1=0.7744 | AUROC=0.8811 | AUPRC=0.8589
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 119.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7510 | F1=0.8209 | AUROC=0.9545 | AUPRC=0.9027
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8352 | F1=0.9157 | AUROC=0.9716 | AUPRC=0.9714
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4260 | F1=0.7297 | AUROC=0.7688 | AUPRC=0.7472
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5598 | F1=0.7772 | AUROC=0.8830 | AUPRC=0.8546
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 123.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7521 | F1=0.8217 | AUROC=0.9557 | AUPRC=0.8974
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8239 | F1=0.9096 | AUROC=0.9724 | AUPRC=0.9740
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.5625 | val_loss=0.4388 | val_mcc=0.4796 | val_f1=0.5782 | val_auroc=0.8153

[Epoch 02] train_loss=0.5063 | val_loss=0.4188 | val_mcc=0.4984 | val_f1=0.5946 | val_auroc=0.8249

[Epoch 03] train_loss=0.4815 | val_loss=0.4767 | val_mcc=0.5006 | val_f1=0.6028 | val_auroc=0.8449

[Epoch 04] train_loss=0.4511 | val_loss=0.4163 | val_mcc=0.5290 | val_f1=0.6245 | val_auroc=0.8611

[Epoch 05] train_loss=0.4206 | val_loss=0.4037 | val_mcc=0.5253 | val_f1=0.6219 | val_auroc=0.8675

[Epoch 06] train_loss=0.3974 | val_loss=0.4395 | val_mcc=0.5282 | val_f1=0.6229 | val_auroc=0.8780

[Epoch 07] train_loss=0.3692 | val_loss=0.4273 | val_mcc=0.5313 | val_f1=0.6262 | val_auroc=0.8769

[Epoch 08] train_loss=0.3504 | val_loss=0.4261 | val_mcc=0.5321 | val_f1=0.6269 | val_auroc=0.8787

[Epoch 09] train_loss=0.3288 | val_loss=0.4412 | val_mcc=0.5271 | val_f1=0.6225 | val_auroc=0.8761

[Epoch 10] train_loss=0.3051 | val_loss=0.4040 | val_mcc=0.5319 | val_f1=0.6270 | val_auroc=0.8739

[Epoch 11] train_loss=0.2828 | val_loss=0.4275 | val_mcc=0.5305 | val_f1=0.6260 | val_auroc=0.8718

[Epoch 12] train_loss=0.2673 | val_loss=0.4140 | val_mcc=0.5251 | val_f1=0.6211 | val_auroc=0.8676

[Epoch 13] train_loss=0.2276 | val_loss=0.4893 | val_mcc=0.5098 | val_f1=0.6095 | val_auroc=0.8682

[Epoch 14] train_loss=0.2131 | val_loss=0.5062 | val_mcc=0.5107 | val_f1=0.6104 | val_auroc=0.8671
[EarlyStop] epoch=14 | best_val_mcc=0.5321
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5801 | F1=0.7010 | AUROC=0.8893 | AUPRC=0.7873
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5740 | F1=0.7893 | AUROC=0.8730 | AUPRC=0.8655
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4228 | F1=0.7163 | AUROC=0.7688 | AUPRC=0.7584
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5203 | F1=0.7376 | AUROC=0.8435 | AUPRC=0.8165
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5666 | val_loss=0.5235 | val_mcc=0.4656 | val_f1=0.5761 | val_auroc=0.8147

[Epoch 02] train_loss=0.5134 | val_loss=0.4913 | val_mcc=0.4770 | val_f1=0.5848 | val_auroc=0.8258

[Epoch 03] train_loss=0.4818 | val_loss=0.4331 | val_mcc=0.5115 | val_f1=0.6106 | val_auroc=0.8519

[Epoch 04] train_loss=0.4505 | val_loss=0.4181 | val_mcc=0.5392 | val_f1=0.6327 | val_auroc=0.8694

[Epoch 05] train_loss=0.4177 | val_loss=0.5380 | val_mcc=0.4933 | val_f1=0.5906 | val_auroc=0.8757

[Epoch 06] train_loss=0.3955 | val_loss=0.5068 | val_mcc=0.5094 | val_f1=0.6051 | val_auroc=0.8791

[Epoch 07] train_loss=0.3684 | val_loss=0.4320 | val_mcc=0.5390 | val_f1=0.6322 | val_auroc=0.8778

[Epoch 08] train_loss=0.3461 | val_loss=0.4201 | val_mcc=0.5407 | val_f1=0.6338 | val_auroc=0.8762

[Epoch 09] train_loss=0.3331 | val_loss=0.4441 | val_mcc=0.5381 | val_f1=0.6316 | val_auroc=0.8760

[Epoch 10] train_loss=0.3100 | val_loss=0.4879 | val_mcc=0.5204 | val_f1=0.6167 | val_auroc=0.8733

[Epoch 11] train_loss=0.2889 | val_loss=0.4861 | val_mcc=0.5267 | val_f1=0.6222 | val_auroc=0.8704

[Epoch 12] train_loss=0.2639 | val_loss=0.5494 | val_mcc=0.5189 | val_f1=0.6151 | val_auroc=0.8701

[Epoch 13] train_loss=0.2335 | val_loss=0.5686 | val_mcc=0.5174 | val_f1=0.6150 | val_auroc=0.8648

[Epoch 14] train_loss=0.2214 | val_loss=0.5999 | val_mcc=0.5050 | val_f1=0.6053 | val_auroc=0.8598
[EarlyStop] epoch=14 | best_val_mcc=0.5407
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5846 | F1=0.7031 | AUROC=0.8840 | AUPRC=0.7733
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5820 | F1=0.7848 | AUROC=0.8667 | AUPRC=0.8609
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4193 | F1=0.7079 | AUROC=0.7656 | AUPRC=0.7464
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5362 | F1=0.7436 | AUROC=0.8339 | AUPRC=0.8018
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5686 | val_loss=0.4395 | val_mcc=0.4825 | val_f1=0.5834 | val_auroc=0.8177

[Epoch 02] train_loss=0.5078 | val_loss=0.4046 | val_mcc=0.5079 | val_f1=0.6036 | val_auroc=0.8353

[Epoch 03] train_loss=0.4795 | val_loss=0.3989 | val_mcc=0.5275 | val_f1=0.6215 | val_auroc=0.8532

[Epoch 04] train_loss=0.4519 | val_loss=0.3922 | val_mcc=0.5374 | val_f1=0.6304 | val_auroc=0.8704

[Epoch 05] train_loss=0.4214 | val_loss=0.4432 | val_mcc=0.5276 | val_f1=0.6224 | val_auroc=0.8783

[Epoch 06] train_loss=0.3934 | val_loss=0.3977 | val_mcc=0.5342 | val_f1=0.6288 | val_auroc=0.8768

[Epoch 07] train_loss=0.3689 | val_loss=0.4099 | val_mcc=0.5465 | val_f1=0.6381 | val_auroc=0.8812

[Epoch 08] train_loss=0.3456 | val_loss=0.3782 | val_mcc=0.5545 | val_f1=0.6440 | val_auroc=0.8793

[Epoch 09] train_loss=0.3280 | val_loss=0.4733 | val_mcc=0.5220 | val_f1=0.6181 | val_auroc=0.8779

[Epoch 10] train_loss=0.2996 | val_loss=0.4254 | val_mcc=0.5431 | val_f1=0.6355 | val_auroc=0.8769

[Epoch 11] train_loss=0.2752 | val_loss=0.4804 | val_mcc=0.5225 | val_f1=0.6195 | val_auroc=0.8715

[Epoch 12] train_loss=0.2577 | val_loss=0.4623 | val_mcc=0.5232 | val_f1=0.6201 | val_auroc=0.8675

[Epoch 13] train_loss=0.2247 | val_loss=0.4925 | val_mcc=0.5194 | val_f1=0.6174 | val_auroc=0.8666

[Epoch 14] train_loss=0.2027 | val_loss=0.5626 | val_mcc=0.5177 | val_f1=0.6160 | val_auroc=0.8663
[EarlyStop] epoch=14 | best_val_mcc=0.5545
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5907 | F1=0.7023 | AUROC=0.8834 | AUPRC=0.7824
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5674 | F1=0.7678 | AUROC=0.8594 | AUPRC=0.8544
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3983 | F1=0.6830 | AUROC=0.7669 | AUPRC=0.7538
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5234 | F1=0.7270 | AUROC=0.8297 | AUPRC=0.8009
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5656 | val_loss=0.4877 | val_mcc=0.4652 | val_f1=0.5748 | val_auroc=0.8159

[Epoch 02] train_loss=0.5049 | val_loss=0.5121 | val_mcc=0.4773 | val_f1=0.5845 | val_auroc=0.8335

[Epoch 03] train_loss=0.4756 | val_loss=0.4485 | val_mcc=0.5118 | val_f1=0.6115 | val_auroc=0.8485

[Epoch 04] train_loss=0.4452 | val_loss=0.4035 | val_mcc=0.5337 | val_f1=0.6278 | val_auroc=0.8657

[Epoch 05] train_loss=0.4169 | val_loss=0.3887 | val_mcc=0.5396 | val_f1=0.6328 | val_auroc=0.8752

[Epoch 06] train_loss=0.3891 | val_loss=0.4186 | val_mcc=0.5404 | val_f1=0.6333 | val_auroc=0.8796

[Epoch 07] train_loss=0.3660 | val_loss=0.4393 | val_mcc=0.5292 | val_f1=0.6238 | val_auroc=0.8829

[Epoch 08] train_loss=0.3363 | val_loss=0.3948 | val_mcc=0.5323 | val_f1=0.6273 | val_auroc=0.8761

[Epoch 09] train_loss=0.3122 | val_loss=0.4076 | val_mcc=0.5352 | val_f1=0.6296 | val_auroc=0.8777

[Epoch 10] train_loss=0.2849 | val_loss=0.4572 | val_mcc=0.5225 | val_f1=0.6195 | val_auroc=0.8749

[Epoch 11] train_loss=0.2504 | val_loss=0.4433 | val_mcc=0.5201 | val_f1=0.6180 | val_auroc=0.8733

[Epoch 12] train_loss=0.2342 | val_loss=0.4816 | val_mcc=0.5167 | val_f1=0.6150 | val_auroc=0.8738
[EarlyStop] epoch=12 | best_val_mcc=0.5404
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.5947 | F1=0.7103 | AUROC=0.8899 | AUPRC=0.7906
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5989 | F1=0.7989 | AUROC=0.8774 | AUPRC=0.8646
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4180 | F1=0.7113 | AUROC=0.7661 | AUPRC=0.7518
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5142 | F1=0.7318 | AUROC=0.8405 | AUPRC=0.8125
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 334.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5736 | F1=0.6952 | AUROC=0.8798 | AUPRC=0.7677
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5760 | F1=0.7850 | AUROC=0.8601 | AUPRC=0.8494
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4073 | F1=0.7019 | AUROC=0.7535 | AUPRC=0.7345
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5043 | F1=0.7303 | AUROC=0.8294 | AUPRC=0.7921
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 185.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5486 | F1=0.6757 | AUROC=0.8668 | AUPRC=0.7556
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5195 | F1=0.7511 | AUROC=0.8382 | AUPRC=0.8246
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3896 | F1=0.6872 | AUROC=0.7525 | AUPRC=0.7290
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4956 | F1=0.7140 | AUROC=0.8171 | AUPRC=0.7920
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 97.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5631 | F1=0.6865 | AUROC=0.8608 | AUPRC=0.7534
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5362 | F1=0.7634 | AUROC=0.8393 | AUPRC=0.8324
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3956 | F1=0.6902 | AUROC=0.7510 | AUPRC=0.7380
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5096 | F1=0.7247 | AUROC=0.8170 | AUPRC=0.7888
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 189.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5581 | F1=0.6839 | AUROC=0.8646 | AUPRC=0.7545
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5305 | F1=0.7605 | AUROC=0.8430 | AUPRC=0.8235
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3985 | F1=0.6922 | AUROC=0.7496 | AUPRC=0.7320
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4212 | val_loss=0.2333 | val_mcc=0.7146 | val_f1=0.7707 | val_auroc=0.9526

[Epoch 02] train_loss=0.3137 | val_loss=0.2356 | val_mcc=0.7206 | val_f1=0.7748 | val_auroc=0.9573

[Epoch 03] train_loss=0.2904 | val_loss=0.2378 | val_mcc=0.7222 | val_f1=0.7749 | val_auroc=0.9609

[Epoch 04] train_loss=0.2754 | val_loss=0.2061 | val_mcc=0.7478 | val_f1=0.7971 | val_auroc=0.9601

[Epoch 05] train_loss=0.2616 | val_loss=0.2277 | val_mcc=0.7314 | val_f1=0.7827 | val_auroc=0.9622

[Epoch 06] train_loss=0.2449 | val_loss=0.2034 | val_mcc=0.7537 | val_f1=0.8019 | val_auroc=0.9625

[Epoch 07] train_loss=0.2313 | val_loss=0.2308 | val_mcc=0.7318 | val_f1=0.7825 | val_auroc=0.9638

[Epoch 08] train_loss=0.2156 | val_loss=0.2146 | val_mcc=0.7492 | val_f1=0.7981 | val_auroc=0.9622

[Epoch 09] train_loss=0.2030 | val_loss=0.2175 | val_mcc=0.7514 | val_f1=0.7999 | val_auroc=0.9623

[Epoch 10] train_loss=0.1880 | val_loss=0.2612 | val_mcc=0.7181 | val_f1=0.7702 | val_auroc=0.9608

[Epoch 11] train_loss=0.1689 | val_loss=0.2336 | val_mcc=0.7463 | val_f1=0.7954 | val_auroc=0.9618

[Epoch 12] train_loss=0.1578 | val_loss=0.2400 | val_mcc=0.7445 | val_f1=0.7937 | val_auroc=0.9608
[EarlyStop] epoch=12 | best_val_mcc=0.7537
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7610 | F1=0.8275 | AUROC=0.9577 | AUPRC=0.9072
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7983 | F1=0.8916 | AUROC=0.9719 | AUPRC=0.9671
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4064 | F1=0.7146 | AUROC=0.7696 | AUPRC=0.7473
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5615 | F1=0.7777 | AUROC=0.8766 | AUPRC=0.8482
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4453 | val_loss=0.2628 | val_mcc=0.6888 | val_f1=0.7486 | val_auroc=0.9510

[Epoch 02] train_loss=0.3199 | val_loss=0.3415 | val_mcc=0.6510 | val_f1=0.7086 | val_auroc=0.9557

[Epoch 03] train_loss=0.2967 | val_loss=0.2216 | val_mcc=0.7336 | val_f1=0.7855 | val_auroc=0.9603

[Epoch 04] train_loss=0.2805 | val_loss=0.2017 | val_mcc=0.7515 | val_f1=0.8000 | val_auroc=0.9621

[Epoch 05] train_loss=0.2656 | val_loss=0.2481 | val_mcc=0.7204 | val_f1=0.7715 | val_auroc=0.9639

[Epoch 06] train_loss=0.2493 | val_loss=0.2237 | val_mcc=0.7339 | val_f1=0.7844 | val_auroc=0.9643

[Epoch 07] train_loss=0.2380 | val_loss=0.2418 | val_mcc=0.7342 | val_f1=0.7830 | val_auroc=0.9643

[Epoch 08] train_loss=0.2176 | val_loss=0.3021 | val_mcc=0.6907 | val_f1=0.7441 | val_auroc=0.9606

[Epoch 09] train_loss=0.2000 | val_loss=0.2251 | val_mcc=0.7490 | val_f1=0.7977 | val_auroc=0.9612

[Epoch 10] train_loss=0.1862 | val_loss=0.2394 | val_mcc=0.7410 | val_f1=0.7908 | val_auroc=0.9593
[EarlyStop] epoch=10 | best_val_mcc=0.7515
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7596 | F1=0.8260 | AUROC=0.9534 | AUPRC=0.9014
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8190 | F1=0.8985 | AUROC=0.9772 | AUPRC=0.9742
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4051 | F1=0.7092 | AUROC=0.7661 | AUPRC=0.7404
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5588 | F1=0.7763 | AUROC=0.8720 | AUPRC=0.8356
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4156 | val_loss=0.2104 | val_mcc=0.7333 | val_f1=0.7831 | val_auroc=0.9560

[Epoch 02] train_loss=0.3098 | val_loss=0.2507 | val_mcc=0.7163 | val_f1=0.7685 | val_auroc=0.9610

[Epoch 03] train_loss=0.2863 | val_loss=0.2036 | val_mcc=0.7522 | val_f1=0.8004 | val_auroc=0.9606

[Epoch 04] train_loss=0.2757 | val_loss=0.2084 | val_mcc=0.7492 | val_f1=0.7982 | val_auroc=0.9637

[Epoch 05] train_loss=0.2593 | val_loss=0.2438 | val_mcc=0.7231 | val_f1=0.7742 | val_auroc=0.9635

[Epoch 06] train_loss=0.2456 | val_loss=0.2111 | val_mcc=0.7512 | val_f1=0.7995 | val_auroc=0.9638

[Epoch 07] train_loss=0.2309 | val_loss=0.2096 | val_mcc=0.7489 | val_f1=0.7981 | val_auroc=0.9626

[Epoch 08] train_loss=0.2089 | val_loss=0.2155 | val_mcc=0.7498 | val_f1=0.7985 | val_auroc=0.9626

[Epoch 09] train_loss=0.1995 | val_loss=0.2153 | val_mcc=0.7526 | val_f1=0.8008 | val_auroc=0.9620

[Epoch 10] train_loss=0.1870 | val_loss=0.2282 | val_mcc=0.7482 | val_f1=0.7974 | val_auroc=0.9599

[Epoch 11] train_loss=0.1785 | val_loss=0.2402 | val_mcc=0.7375 | val_f1=0.7878 | val_auroc=0.9608

[Epoch 12] train_loss=0.1713 | val_loss=0.2399 | val_mcc=0.7332 | val_f1=0.7850 | val_auroc=0.9590

[Epoch 13] train_loss=0.1603 | val_loss=0.2515 | val_mcc=0.7316 | val_f1=0.7837 | val_auroc=0.9580

[Epoch 14] train_loss=0.1452 | val_loss=0.2679 | val_mcc=0.7246 | val_f1=0.7780 | val_auroc=0.9549

[Epoch 15] train_loss=0.1369 | val_loss=0.2580 | val_mcc=0.7289 | val_f1=0.7821 | val_auroc=0.9543
[EarlyStop] epoch=15 | best_val_mcc=0.7526
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7551 | F1=0.8236 | AUROC=0.9581 | AUPRC=0.9067
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8132 | F1=0.9027 | AUROC=0.9704 | AUPRC=0.9689
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4326 | F1=0.7286 | AUROC=0.7759 | AUPRC=0.7547
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5719 | F1=0.7822 | AUROC=0.8737 | AUPRC=0.8447
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4191 | val_loss=0.2219 | val_mcc=0.7224 | val_f1=0.7769 | val_auroc=0.9554

[Epoch 02] train_loss=0.3083 | val_loss=0.2273 | val_mcc=0.7237 | val_f1=0.7775 | val_auroc=0.9576

[Epoch 03] train_loss=0.2882 | val_loss=0.2052 | val_mcc=0.7473 | val_f1=0.7964 | val_auroc=0.9603

[Epoch 04] train_loss=0.2735 | val_loss=0.2126 | val_mcc=0.7411 | val_f1=0.7915 | val_auroc=0.9624

[Epoch 05] train_loss=0.2613 | val_loss=0.2376 | val_mcc=0.7298 | val_f1=0.7803 | val_auroc=0.9637

[Epoch 06] train_loss=0.2445 | val_loss=0.2270 | val_mcc=0.7339 | val_f1=0.7843 | val_auroc=0.9639

[Epoch 07] train_loss=0.2272 | val_loss=0.2393 | val_mcc=0.7315 | val_f1=0.7812 | val_auroc=0.9637

[Epoch 08] train_loss=0.2113 | val_loss=0.2108 | val_mcc=0.7544 | val_f1=0.8020 | val_auroc=0.9647

[Epoch 09] train_loss=0.1974 | val_loss=0.2271 | val_mcc=0.7441 | val_f1=0.7928 | val_auroc=0.9645

[Epoch 10] train_loss=0.1874 | val_loss=0.2205 | val_mcc=0.7497 | val_f1=0.7982 | val_auroc=0.9636

[Epoch 11] train_loss=0.1781 | val_loss=0.2454 | val_mcc=0.7346 | val_f1=0.7851 | val_auroc=0.9623

[Epoch 12] train_loss=0.1681 | val_loss=0.2390 | val_mcc=0.7445 | val_f1=0.7933 | val_auroc=0.9632

[Epoch 13] train_loss=0.1548 | val_loss=0.2366 | val_mcc=0.7464 | val_f1=0.7952 | val_auroc=0.9628

[Epoch 14] train_loss=0.1489 | val_loss=0.2439 | val_mcc=0.7382 | val_f1=0.7884 | val_auroc=0.9617
[EarlyStop] epoch=14 | best_val_mcc=0.7544
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7640 | F1=0.8300 | AUROC=0.9596 | AUPRC=0.9097
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8261 | F1=0.9072 | AUROC=0.9760 | AUPRC=0.9690
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4151 | F1=0.7216 | AUROC=0.7752 | AUPRC=0.7529
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5526 | F1=0.7738 | AUROC=0.8783 | AUPRC=0.8493
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 214.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7777 | F1=0.8398 | AUROC=0.9635 | AUPRC=0.9198
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8819 | F1=0.9379 | AUROC=0.9855 | AUPRC=0.9853
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4395 | F1=0.7358 | AUROC=0.7747 | AUPRC=0.7504
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5359 | F1=0.7666 | AUROC=0.8869 | AUPRC=0.8605
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 181.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7615 | F1=0.8283 | AUROC=0.9572 | AUPRC=0.9085
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8439 | F1=0.9197 | AUROC=0.9768 | AUPRC=0.9766
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4217 | F1=0.7282 | AUROC=0.7702 | AUPRC=0.7509
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5466 | F1=0.7713 | AUROC=0.8810 | AUPRC=0.8486
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 107.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7569 | F1=0.8251 | AUROC=0.9557 | AUPRC=0.9077
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8390 | F1=0.9158 | AUROC=0.9740 | AUPRC=0.9735
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4140 | F1=0.7219 | AUROC=0.7726 | AUPRC=0.7409
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5496 | F1=0.7727 | AUROC=0.8777 | AUPRC=0.8472
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 113.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7623 | F1=0.8289 | AUROC=0.9577 | AUPRC=0.9101
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8151 | F1=0.9059 | AUROC=0.9746 | AUPRC=0.9744
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5648 | val_loss=0.4204 | val_mcc=0.5487 | val_f1=0.6265 | val_auroc=0.8291

[Epoch 02] train_loss=0.4948 | val_loss=0.3703 | val_mcc=0.5804 | val_f1=0.6466 | val_auroc=0.8444

[Epoch 03] train_loss=0.4785 | val_loss=0.4208 | val_mcc=0.5681 | val_f1=0.6522 | val_auroc=0.8500

[Epoch 04] train_loss=0.4641 | val_loss=0.3630 | val_mcc=0.5878 | val_f1=0.6606 | val_auroc=0.8551

[Epoch 05] train_loss=0.4543 | val_loss=0.3880 | val_mcc=0.5848 | val_f1=0.6643 | val_auroc=0.8581

[Epoch 06] train_loss=0.4444 | val_loss=0.4497 | val_mcc=0.5471 | val_f1=0.6388 | val_auroc=0.8618

[Epoch 07] train_loss=0.4375 | val_loss=0.4048 | val_mcc=0.5672 | val_f1=0.6542 | val_auroc=0.8664

[Epoch 08] train_loss=0.4273 | val_loss=0.3621 | val_mcc=0.5837 | val_f1=0.6653 | val_auroc=0.8710

[Epoch 09] train_loss=0.4167 | val_loss=0.3664 | val_mcc=0.5773 | val_f1=0.6607 | val_auroc=0.8723

[Epoch 10] train_loss=0.4106 | val_loss=0.3681 | val_mcc=0.5788 | val_f1=0.6630 | val_auroc=0.8759
[EarlyStop] epoch=10 | best_val_mcc=0.5878
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6121 | F1=0.7041 | AUROC=0.8515 | AUPRC=0.7779
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5616 | F1=0.7368 | AUROC=0.8196 | AUPRC=0.8489
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3835 | F1=0.6421 | AUROC=0.7342 | AUPRC=0.7475
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5309 | F1=0.7108 | AUROC=0.8128 | AUPRC=0.8155
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5686 | val_loss=0.4572 | val_mcc=0.5423 | val_f1=0.6304 | val_auroc=0.8275

[Epoch 02] train_loss=0.4968 | val_loss=0.4159 | val_mcc=0.5733 | val_f1=0.6533 | val_auroc=0.8445

[Epoch 03] train_loss=0.4778 | val_loss=0.3678 | val_mcc=0.5858 | val_f1=0.6582 | val_auroc=0.8494

[Epoch 04] train_loss=0.4656 | val_loss=0.3859 | val_mcc=0.5804 | val_f1=0.6596 | val_auroc=0.8541

[Epoch 05] train_loss=0.4624 | val_loss=0.3980 | val_mcc=0.5813 | val_f1=0.6632 | val_auroc=0.8575

[Epoch 06] train_loss=0.4499 | val_loss=0.3529 | val_mcc=0.5902 | val_f1=0.6651 | val_auroc=0.8612

[Epoch 07] train_loss=0.4453 | val_loss=0.4266 | val_mcc=0.5554 | val_f1=0.6453 | val_auroc=0.8636

[Epoch 08] train_loss=0.4354 | val_loss=0.4779 | val_mcc=0.5405 | val_f1=0.6331 | val_auroc=0.8660

[Epoch 09] train_loss=0.4313 | val_loss=0.3280 | val_mcc=0.6047 | val_f1=0.6747 | val_auroc=0.8692

[Epoch 10] train_loss=0.4227 | val_loss=0.3895 | val_mcc=0.5759 | val_f1=0.6608 | val_auroc=0.8722

[Epoch 11] train_loss=0.4190 | val_loss=0.4222 | val_mcc=0.5525 | val_f1=0.6428 | val_auroc=0.8711

[Epoch 12] train_loss=0.4113 | val_loss=0.3523 | val_mcc=0.5874 | val_f1=0.6678 | val_auroc=0.8735

[Epoch 13] train_loss=0.4063 | val_loss=0.4219 | val_mcc=0.5599 | val_f1=0.6488 | val_auroc=0.8733

[Epoch 14] train_loss=0.3958 | val_loss=0.3858 | val_mcc=0.5679 | val_f1=0.6549 | val_auroc=0.8756

[Epoch 15] train_loss=0.3882 | val_loss=0.4130 | val_mcc=0.5569 | val_f1=0.6464 | val_auroc=0.8758
[EarlyStop] epoch=15 | best_val_mcc=0.6047
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6233 | F1=0.7135 | AUROC=0.8673 | AUPRC=0.7906
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5641 | F1=0.7389 | AUROC=0.8437 | AUPRC=0.8624
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4012 | F1=0.6542 | AUROC=0.7482 | AUPRC=0.7582
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5483 | F1=0.7243 | AUROC=0.8327 | AUPRC=0.8247
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5639 | val_loss=0.4588 | val_mcc=0.5252 | val_f1=0.6196 | val_auroc=0.8296

[Epoch 02] train_loss=0.4966 | val_loss=0.3717 | val_mcc=0.5792 | val_f1=0.6486 | val_auroc=0.8460

[Epoch 03] train_loss=0.4771 | val_loss=0.3609 | val_mcc=0.5807 | val_f1=0.6546 | val_auroc=0.8506

[Epoch 04] train_loss=0.4635 | val_loss=0.3644 | val_mcc=0.5881 | val_f1=0.6638 | val_auroc=0.8575

[Epoch 05] train_loss=0.4548 | val_loss=0.3362 | val_mcc=0.5954 | val_f1=0.6643 | val_auroc=0.8618

[Epoch 06] train_loss=0.4449 | val_loss=0.3672 | val_mcc=0.5789 | val_f1=0.6602 | val_auroc=0.8669

[Epoch 07] train_loss=0.4394 | val_loss=0.3588 | val_mcc=0.5836 | val_f1=0.6654 | val_auroc=0.8695

[Epoch 08] train_loss=0.4340 | val_loss=0.3282 | val_mcc=0.5997 | val_f1=0.6734 | val_auroc=0.8705

[Epoch 09] train_loss=0.4251 | val_loss=0.3533 | val_mcc=0.5836 | val_f1=0.6662 | val_auroc=0.8775

[Epoch 10] train_loss=0.4142 | val_loss=0.3321 | val_mcc=0.5952 | val_f1=0.6731 | val_auroc=0.8756

[Epoch 11] train_loss=0.4073 | val_loss=0.3388 | val_mcc=0.5916 | val_f1=0.6717 | val_auroc=0.8823

[Epoch 12] train_loss=0.3960 | val_loss=0.3760 | val_mcc=0.5712 | val_f1=0.6576 | val_auroc=0.8821

[Epoch 13] train_loss=0.3802 | val_loss=0.3284 | val_mcc=0.5951 | val_f1=0.6730 | val_auroc=0.8841

[Epoch 14] train_loss=0.3720 | val_loss=0.3428 | val_mcc=0.5882 | val_f1=0.6696 | val_auroc=0.8833
[EarlyStop] epoch=14 | best_val_mcc=0.5997
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6206 | F1=0.7143 | AUROC=0.8681 | AUPRC=0.7911
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5669 | F1=0.7455 | AUROC=0.8493 | AUPRC=0.8646
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3934 | F1=0.6543 | AUROC=0.7457 | AUPRC=0.7587
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5359 | F1=0.7204 | AUROC=0.8324 | AUPRC=0.8267
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5770 | val_loss=0.4203 | val_mcc=0.5337 | val_f1=0.6165 | val_auroc=0.8218

[Epoch 02] train_loss=0.4961 | val_loss=0.3762 | val_mcc=0.5722 | val_f1=0.6438 | val_auroc=0.8419

[Epoch 03] train_loss=0.4768 | val_loss=0.3977 | val_mcc=0.5762 | val_f1=0.6556 | val_auroc=0.8491

[Epoch 04] train_loss=0.4634 | val_loss=0.4015 | val_mcc=0.5689 | val_f1=0.6533 | val_auroc=0.8568

[Epoch 05] train_loss=0.4527 | val_loss=0.3987 | val_mcc=0.5599 | val_f1=0.6464 | val_auroc=0.8536

[Epoch 06] train_loss=0.4436 | val_loss=0.3823 | val_mcc=0.5715 | val_f1=0.6562 | val_auroc=0.8631

[Epoch 07] train_loss=0.4351 | val_loss=0.3593 | val_mcc=0.5843 | val_f1=0.6644 | val_auroc=0.8686

[Epoch 08] train_loss=0.4262 | val_loss=0.3566 | val_mcc=0.5865 | val_f1=0.6669 | val_auroc=0.8727

[Epoch 09] train_loss=0.4162 | val_loss=0.3813 | val_mcc=0.5728 | val_f1=0.6584 | val_auroc=0.8752

[Epoch 10] train_loss=0.4068 | val_loss=0.3619 | val_mcc=0.5790 | val_f1=0.6634 | val_auroc=0.8783

[Epoch 11] train_loss=0.3966 | val_loss=0.4146 | val_mcc=0.5567 | val_f1=0.6458 | val_auroc=0.8805

[Epoch 12] train_loss=0.3846 | val_loss=0.4135 | val_mcc=0.5523 | val_f1=0.6420 | val_auroc=0.8835

[Epoch 13] train_loss=0.3672 | val_loss=0.3762 | val_mcc=0.5697 | val_f1=0.6564 | val_auroc=0.8837

[Epoch 14] train_loss=0.3563 | val_loss=0.3686 | val_mcc=0.5812 | val_f1=0.6654 | val_auroc=0.8859
[EarlyStop] epoch=14 | best_val_mcc=0.5865
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6188 | F1=0.7196 | AUROC=0.8716 | AUPRC=0.7983
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5506 | F1=0.7508 | AUROC=0.8436 | AUPRC=0.8620
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3742 | F1=0.6624 | AUROC=0.7511 | AUPRC=0.7594
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5305 | F1=0.7294 | AUROC=0.8371 | AUPRC=0.8257
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 336.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6008 | F1=0.7134 | AUROC=0.8886 | AUPRC=0.8058
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5832 | F1=0.7803 | AUROC=0.8732 | AUPRC=0.8780
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3894 | F1=0.6900 | AUROC=0.7546 | AUPRC=0.7583
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5460 | F1=0.7502 | AUROC=0.8525 | AUPRC=0.8401
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 331.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6001 | F1=0.7126 | AUROC=0.8809 | AUPRC=0.8008
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5428 | F1=0.7608 | AUROC=0.8516 | AUPRC=0.8672
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3886 | F1=0.6817 | AUROC=0.7551 | AUPRC=0.7591
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5540 | F1=0.7529 | AUROC=0.8485 | AUPRC=0.8346
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 82.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5905 | F1=0.7049 | AUROC=0.8686 | AUPRC=0.7919
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5581 | F1=0.7651 | AUROC=0.8476 | AUPRC=0.8643
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3635 | F1=0.6656 | AUROC=0.7437 | AUPRC=0.7429
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5153 | F1=0.7303 | AUROC=0.8262 | AUPRC=0.8281
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 284.
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5807 | F1=0.6986 | AUROC=0.8649 | AUPRC=0.7837
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5280 | F1=0.7559 | AUROC=0.8340 | AUPRC=0.8556
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3783 | F1=0.6745 | AUROC=0.7433 | AUPRC=0.7511
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4251 | val_loss=0.2165 | val_mcc=0.7324 | val_f1=0.7846 | val_auroc=0.9574

[Epoch 02] train_loss=0.3149 | val_loss=0.2022 | val_mcc=0.7481 | val_f1=0.7974 | val_auroc=0.9618

[Epoch 03] train_loss=0.2910 | val_loss=0.2298 | val_mcc=0.7303 | val_f1=0.7815 | val_auroc=0.9623

[Epoch 04] train_loss=0.2810 | val_loss=0.2153 | val_mcc=0.7474 | val_f1=0.7963 | val_auroc=0.9643

[Epoch 05] train_loss=0.2752 | val_loss=0.1927 | val_mcc=0.7576 | val_f1=0.8048 | val_auroc=0.9643

[Epoch 06] train_loss=0.2729 | val_loss=0.1976 | val_mcc=0.7609 | val_f1=0.8076 | val_auroc=0.9641

[Epoch 07] train_loss=0.2681 | val_loss=0.2338 | val_mcc=0.7370 | val_f1=0.7862 | val_auroc=0.9648

[Epoch 08] train_loss=0.2605 | val_loss=0.2080 | val_mcc=0.7533 | val_f1=0.8012 | val_auroc=0.9652

[Epoch 09] train_loss=0.2546 | val_loss=0.1938 | val_mcc=0.7622 | val_f1=0.8086 | val_auroc=0.9658

[Epoch 10] train_loss=0.2531 | val_loss=0.2080 | val_mcc=0.7540 | val_f1=0.8015 | val_auroc=0.9661

[Epoch 11] train_loss=0.2480 | val_loss=0.1960 | val_mcc=0.7670 | val_f1=0.8123 | val_auroc=0.9671

[Epoch 12] train_loss=0.2438 | val_loss=0.1844 | val_mcc=0.7711 | val_f1=0.8155 | val_auroc=0.9668

[Epoch 13] train_loss=0.2373 | val_loss=0.2487 | val_mcc=0.7245 | val_f1=0.7740 | val_auroc=0.9665

[Epoch 14] train_loss=0.2323 | val_loss=0.1948 | val_mcc=0.7654 | val_f1=0.8110 | val_auroc=0.9675

[Epoch 15] train_loss=0.2276 | val_loss=0.1937 | val_mcc=0.7684 | val_f1=0.8134 | val_auroc=0.9673

[Epoch 16] train_loss=0.2188 | val_loss=0.2374 | val_mcc=0.7393 | val_f1=0.7883 | val_auroc=0.9633

[Epoch 17] train_loss=0.2108 | val_loss=0.2154 | val_mcc=0.7618 | val_f1=0.8070 | val_auroc=0.9666

[Epoch 18] train_loss=0.2044 | val_loss=0.2219 | val_mcc=0.7556 | val_f1=0.8021 | val_auroc=0.9655
[EarlyStop] epoch=18 | best_val_mcc=0.7711
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7746 | F1=0.8365 | AUROC=0.9582 | AUPRC=0.9104
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7834 | F1=0.8807 | AUROC=0.9697 | AUPRC=0.9673
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4138 | F1=0.7119 | AUROC=0.7722 | AUPRC=0.7679
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5835 | F1=0.7877 | AUROC=0.8800 | AUPRC=0.8514
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4209 | val_loss=0.2278 | val_mcc=0.7266 | val_f1=0.7796 | val_auroc=0.9597

[Epoch 02] train_loss=0.3137 | val_loss=0.1938 | val_mcc=0.7478 | val_f1=0.7961 | val_auroc=0.9619

[Epoch 03] train_loss=0.2942 | val_loss=0.2274 | val_mcc=0.7317 | val_f1=0.7827 | val_auroc=0.9634

[Epoch 04] train_loss=0.2835 | val_loss=0.2313 | val_mcc=0.7323 | val_f1=0.7829 | val_auroc=0.9635

[Epoch 05] train_loss=0.2772 | val_loss=0.2063 | val_mcc=0.7444 | val_f1=0.7940 | val_auroc=0.9644

[Epoch 06] train_loss=0.2754 | val_loss=0.2511 | val_mcc=0.7215 | val_f1=0.7712 | val_auroc=0.9653

[Epoch 07] train_loss=0.2651 | val_loss=0.2211 | val_mcc=0.7372 | val_f1=0.7875 | val_auroc=0.9643

[Epoch 08] train_loss=0.2622 | val_loss=0.2104 | val_mcc=0.7452 | val_f1=0.7945 | val_auroc=0.9652
[EarlyStop] epoch=8 | best_val_mcc=0.7478
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7683 | F1=0.8309 | AUROC=0.9526 | AUPRC=0.9014
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7896 | F1=0.8802 | AUROC=0.9651 | AUPRC=0.9632
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4103 | F1=0.7034 | AUROC=0.7634 | AUPRC=0.7576
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5643 | F1=0.7791 | AUROC=0.8773 | AUPRC=0.8628
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4229 | val_loss=0.2792 | val_mcc=0.6886 | val_f1=0.7442 | val_auroc=0.9576

[Epoch 02] train_loss=0.3162 | val_loss=0.1995 | val_mcc=0.7464 | val_f1=0.7957 | val_auroc=0.9616

[Epoch 03] train_loss=0.2961 | val_loss=0.2349 | val_mcc=0.7269 | val_f1=0.7786 | val_auroc=0.9631

[Epoch 04] train_loss=0.2850 | val_loss=0.1980 | val_mcc=0.7541 | val_f1=0.8022 | val_auroc=0.9632

[Epoch 05] train_loss=0.2769 | val_loss=0.2324 | val_mcc=0.7314 | val_f1=0.7819 | val_auroc=0.9646

[Epoch 06] train_loss=0.2769 | val_loss=0.1938 | val_mcc=0.7602 | val_f1=0.8070 | val_auroc=0.9650

[Epoch 07] train_loss=0.2706 | val_loss=0.2338 | val_mcc=0.7332 | val_f1=0.7831 | val_auroc=0.9655

[Epoch 08] train_loss=0.2644 | val_loss=0.2083 | val_mcc=0.7511 | val_f1=0.7992 | val_auroc=0.9659

[Epoch 09] train_loss=0.2632 | val_loss=0.2179 | val_mcc=0.7433 | val_f1=0.7925 | val_auroc=0.9651

[Epoch 10] train_loss=0.2562 | val_loss=0.2015 | val_mcc=0.7573 | val_f1=0.8046 | val_auroc=0.9665

[Epoch 11] train_loss=0.2488 | val_loss=0.2037 | val_mcc=0.7545 | val_f1=0.8020 | val_auroc=0.9668

[Epoch 12] train_loss=0.2468 | val_loss=0.1931 | val_mcc=0.7616 | val_f1=0.8082 | val_auroc=0.9661

[Epoch 13] train_loss=0.2416 | val_loss=0.1916 | val_mcc=0.7635 | val_f1=0.8097 | val_auroc=0.9669

[Epoch 14] train_loss=0.2403 | val_loss=0.2177 | val_mcc=0.7425 | val_f1=0.7923 | val_auroc=0.9644

[Epoch 15] train_loss=0.2384 | val_loss=0.2046 | val_mcc=0.7551 | val_f1=0.8025 | val_auroc=0.9671

[Epoch 16] train_loss=0.2350 | val_loss=0.2076 | val_mcc=0.7528 | val_f1=0.8003 | val_auroc=0.9674

[Epoch 17] train_loss=0.2310 | val_loss=0.2273 | val_mcc=0.7433 | val_f1=0.7915 | val_auroc=0.9667

[Epoch 18] train_loss=0.2274 | val_loss=0.1928 | val_mcc=0.7665 | val_f1=0.8121 | val_auroc=0.9671

[Epoch 19] train_loss=0.2224 | val_loss=0.2041 | val_mcc=0.7562 | val_f1=0.8037 | val_auroc=0.9656

[Epoch 20] train_loss=0.2210 | val_loss=0.2082 | val_mcc=0.7576 | val_f1=0.8046 | val_auroc=0.9654

[Epoch 21] train_loss=0.2181 | val_loss=0.2080 | val_mcc=0.7563 | val_f1=0.8037 | val_auroc=0.9647

[Epoch 22] train_loss=0.2185 | val_loss=0.2417 | val_mcc=0.7349 | val_f1=0.7842 | val_auroc=0.9656

[Epoch 23] train_loss=0.2144 | val_loss=0.2229 | val_mcc=0.7458 | val_f1=0.7945 | val_auroc=0.9646

[Epoch 24] train_loss=0.2144 | val_loss=0.2176 | val_mcc=0.7507 | val_f1=0.7988 | val_auroc=0.9645
[EarlyStop] epoch=24 | best_val_mcc=0.7665
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7657 | F1=0.8311 | AUROC=0.9576 | AUPRC=0.9117
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7858 | F1=0.8866 | AUROC=0.9707 | AUPRC=0.9699
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4058 | F1=0.7125 | AUROC=0.7702 | AUPRC=0.7602
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5726 | F1=0.7829 | AUROC=0.8805 | AUPRC=0.8557
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4098 | val_loss=0.2159 | val_mcc=0.7339 | val_f1=0.7861 | val_auroc=0.9586

[Epoch 02] train_loss=0.3075 | val_loss=0.2052 | val_mcc=0.7476 | val_f1=0.7969 | val_auroc=0.9632

[Epoch 03] train_loss=0.2904 | val_loss=0.2237 | val_mcc=0.7374 | val_f1=0.7869 | val_auroc=0.9645

[Epoch 04] train_loss=0.2796 | val_loss=0.2183 | val_mcc=0.7370 | val_f1=0.7868 | val_auroc=0.9656

[Epoch 05] train_loss=0.2740 | val_loss=0.2063 | val_mcc=0.7447 | val_f1=0.7942 | val_auroc=0.9649

[Epoch 06] train_loss=0.2683 | val_loss=0.2156 | val_mcc=0.7427 | val_f1=0.7922 | val_auroc=0.9650

[Epoch 07] train_loss=0.2637 | val_loss=0.1897 | val_mcc=0.7620 | val_f1=0.8085 | val_auroc=0.9661

[Epoch 08] train_loss=0.2607 | val_loss=0.2080 | val_mcc=0.7523 | val_f1=0.7999 | val_auroc=0.9664

[Epoch 09] train_loss=0.2564 | val_loss=0.2213 | val_mcc=0.7374 | val_f1=0.7870 | val_auroc=0.9652

[Epoch 10] train_loss=0.2543 | val_loss=0.1911 | val_mcc=0.7631 | val_f1=0.8094 | val_auroc=0.9662

[Epoch 11] train_loss=0.2514 | val_loss=0.2052 | val_mcc=0.7539 | val_f1=0.8014 | val_auroc=0.9666

[Epoch 12] train_loss=0.2498 | val_loss=0.2097 | val_mcc=0.7481 | val_f1=0.7963 | val_auroc=0.9672

[Epoch 13] train_loss=0.2468 | val_loss=0.2112 | val_mcc=0.7517 | val_f1=0.7993 | val_auroc=0.9659

[Epoch 14] train_loss=0.2426 | val_loss=0.2123 | val_mcc=0.7539 | val_f1=0.8008 | val_auroc=0.9665

[Epoch 15] train_loss=0.2377 | val_loss=0.2042 | val_mcc=0.7581 | val_f1=0.8047 | val_auroc=0.9676

[Epoch 16] train_loss=0.2377 | val_loss=0.1943 | val_mcc=0.7644 | val_f1=0.8103 | val_auroc=0.9670

[Epoch 17] train_loss=0.2355 | val_loss=0.2040 | val_mcc=0.7550 | val_f1=0.8022 | val_auroc=0.9671

[Epoch 18] train_loss=0.2350 | val_loss=0.2058 | val_mcc=0.7566 | val_f1=0.8034 | val_auroc=0.9673

[Epoch 19] train_loss=0.2323 | val_loss=0.1954 | val_mcc=0.7656 | val_f1=0.8112 | val_auroc=0.9675

[Epoch 20] train_loss=0.2311 | val_loss=0.2060 | val_mcc=0.7569 | val_f1=0.8035 | val_auroc=0.9673

[Epoch 21] train_loss=0.2273 | val_loss=0.2029 | val_mcc=0.7576 | val_f1=0.8043 | val_auroc=0.9674

[Epoch 22] train_loss=0.2250 | val_loss=0.1867 | val_mcc=0.7730 | val_f1=0.8173 | val_auroc=0.9673

[Epoch 23] train_loss=0.2239 | val_loss=0.2055 | val_mcc=0.7563 | val_f1=0.8031 | val_auroc=0.9673

[Epoch 24] train_loss=0.2232 | val_loss=0.2040 | val_mcc=0.7584 | val_f1=0.8049 | val_auroc=0.9671

[Epoch 25] train_loss=0.2203 | val_loss=0.1955 | val_mcc=0.7616 | val_f1=0.8080 | val_auroc=0.9669

[Epoch 26] train_loss=0.2205 | val_loss=0.2066 | val_mcc=0.7561 | val_f1=0.8031 | val_auroc=0.9669

[Epoch 27] train_loss=0.2150 | val_loss=0.2007 | val_mcc=0.7600 | val_f1=0.8065 | val_auroc=0.9668

[Epoch 28] train_loss=0.2151 | val_loss=0.2019 | val_mcc=0.7589 | val_f1=0.8056 | val_auroc=0.9669
[EarlyStop] epoch=28 | best_val_mcc=0.7730
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7753 | F1=0.8377 | AUROC=0.9573 | AUPRC=0.9101
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8212 | F1=0.9036 | AUROC=0.9702 | AUPRC=0.9691
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4151 | F1=0.7177 | AUROC=0.7712 | AUPRC=0.7635
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5615 | F1=0.7778 | AUROC=0.8727 | AUPRC=0.8412
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 174.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7782 | F1=0.8401 | AUROC=0.9640 | AUPRC=0.9230
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8563 | F1=0.9244 | AUROC=0.9818 | AUPRC=0.9822
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4171 | F1=0.7259 | AUROC=0.7761 | AUPRC=0.7730
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5468 | F1=0.7712 | AUROC=0.8894 | AUPRC=0.8727
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 208.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7675 | F1=0.8326 | AUROC=0.9587 | AUPRC=0.9138
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8159 | F1=0.9043 | AUROC=0.9691 | AUPRC=0.9699
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4019 | F1=0.7189 | AUROC=0.7719 | AUPRC=0.7646
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5603 | F1=0.7774 | AUROC=0.8838 | AUPRC=0.8606
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 148.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7628 | F1=0.8292 | AUROC=0.9581 | AUPRC=0.9125
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8189 | F1=0.9056 | AUROC=0.9734 | AUPRC=0.9745
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3991 | F1=0.7179 | AUROC=0.7719 | AUPRC=0.7676
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5459 | F1=0.7711 | AUROC=0.8813 | AUPRC=0.8630
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 173.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7561 | F1=0.8245 | AUROC=0.9557 | AUPRC=0.9083
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v3_650m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8335 | F1=0.9126 | AUROC=0.9688 | AUPRC=0.9662
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5331 | val_loss=0.4050 | val_mcc=0.5431 | val_f1=0.6352 | val_auroc=0.8576

[Epoch 02] train_loss=0.4642 | val_loss=0.4142 | val_mcc=0.5493 | val_f1=0.6405 | val_auroc=0.8710

[Epoch 03] train_loss=0.4325 | val_loss=0.3943 | val_mcc=0.5646 | val_f1=0.6523 | val_auroc=0.8793

[Epoch 04] train_loss=0.4020 | val_loss=0.4135 | val_mcc=0.5592 | val_f1=0.6470 | val_auroc=0.8892

[Epoch 05] train_loss=0.3754 | val_loss=0.3599 | val_mcc=0.5851 | val_f1=0.6685 | val_auroc=0.8941

[Epoch 06] train_loss=0.3484 | val_loss=0.3662 | val_mcc=0.5872 | val_f1=0.6701 | val_auroc=0.8934

[Epoch 07] train_loss=0.3183 | val_loss=0.4235 | val_mcc=0.5632 | val_f1=0.6498 | val_auroc=0.8916

[Epoch 08] train_loss=0.2938 | val_loss=0.3861 | val_mcc=0.5674 | val_f1=0.6546 | val_auroc=0.8879

[Epoch 09] train_loss=0.2630 | val_loss=0.4335 | val_mcc=0.5588 | val_f1=0.6477 | val_auroc=0.8819

[Epoch 10] train_loss=0.2333 | val_loss=0.4185 | val_mcc=0.5542 | val_f1=0.6443 | val_auroc=0.8795

[Epoch 11] train_loss=0.1953 | val_loss=0.4837 | val_mcc=0.5291 | val_f1=0.6243 | val_auroc=0.8759

[Epoch 12] train_loss=0.1755 | val_loss=0.4903 | val_mcc=0.5484 | val_f1=0.6398 | val_auroc=0.8801
[EarlyStop] epoch=12 | best_val_mcc=0.5872
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6420 | F1=0.7426 | AUROC=0.9074 | AUPRC=0.8180
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5988 | F1=0.7965 | AUROC=0.8885 | AUPRC=0.8756
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4392 | F1=0.7119 | AUROC=0.7842 | AUPRC=0.7586
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6000 | F1=0.7818 | AUROC=0.8793 | AUPRC=0.8531
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5373 | val_loss=0.4269 | val_mcc=0.5390 | val_f1=0.6325 | val_auroc=0.8575

[Epoch 02] train_loss=0.4681 | val_loss=0.4114 | val_mcc=0.5521 | val_f1=0.6426 | val_auroc=0.8725

[Epoch 03] train_loss=0.4366 | val_loss=0.3826 | val_mcc=0.5714 | val_f1=0.6577 | val_auroc=0.8796

[Epoch 04] train_loss=0.4053 | val_loss=0.3473 | val_mcc=0.5892 | val_f1=0.6710 | val_auroc=0.8911

[Epoch 05] train_loss=0.3759 | val_loss=0.3791 | val_mcc=0.5820 | val_f1=0.6659 | val_auroc=0.8916

[Epoch 06] train_loss=0.3449 | val_loss=0.4452 | val_mcc=0.5603 | val_f1=0.6467 | val_auroc=0.8897

[Epoch 07] train_loss=0.3149 | val_loss=0.4350 | val_mcc=0.5666 | val_f1=0.6537 | val_auroc=0.8881

[Epoch 08] train_loss=0.2890 | val_loss=0.4901 | val_mcc=0.5437 | val_f1=0.6346 | val_auroc=0.8767

[Epoch 09] train_loss=0.2471 | val_loss=0.5069 | val_mcc=0.5540 | val_f1=0.6440 | val_auroc=0.8762

[Epoch 10] train_loss=0.2259 | val_loss=0.5279 | val_mcc=0.5543 | val_f1=0.6440 | val_auroc=0.8728
[EarlyStop] epoch=10 | best_val_mcc=0.5892
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6407 | F1=0.7386 | AUROC=0.9013 | AUPRC=0.8088
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.6093 | F1=0.7928 | AUROC=0.8897 | AUPRC=0.8852
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4483 | F1=0.7021 | AUROC=0.7840 | AUPRC=0.7692
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6048 | F1=0.7805 | AUROC=0.8788 | AUPRC=0.8546
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5300 | val_loss=0.4330 | val_mcc=0.5318 | val_f1=0.6269 | val_auroc=0.8586

[Epoch 02] train_loss=0.4633 | val_loss=0.3829 | val_mcc=0.5530 | val_f1=0.6432 | val_auroc=0.8711

[Epoch 03] train_loss=0.4329 | val_loss=0.3579 | val_mcc=0.5814 | val_f1=0.6653 | val_auroc=0.8861

[Epoch 04] train_loss=0.4035 | val_loss=0.3531 | val_mcc=0.5873 | val_f1=0.6697 | val_auroc=0.8904

[Epoch 05] train_loss=0.3754 | val_loss=0.3359 | val_mcc=0.5890 | val_f1=0.6701 | val_auroc=0.8909

[Epoch 06] train_loss=0.3460 | val_loss=0.3537 | val_mcc=0.5831 | val_f1=0.6667 | val_auroc=0.8914

[Epoch 07] train_loss=0.3168 | val_loss=0.3579 | val_mcc=0.5847 | val_f1=0.6677 | val_auroc=0.8915

[Epoch 08] train_loss=0.2824 | val_loss=0.4295 | val_mcc=0.5501 | val_f1=0.6411 | val_auroc=0.8758

[Epoch 09] train_loss=0.2645 | val_loss=0.4381 | val_mcc=0.5695 | val_f1=0.6561 | val_auroc=0.8830

[Epoch 10] train_loss=0.2102 | val_loss=0.5332 | val_mcc=0.5516 | val_f1=0.6420 | val_auroc=0.8754

[Epoch 11] train_loss=0.1978 | val_loss=0.6030 | val_mcc=0.5350 | val_f1=0.6279 | val_auroc=0.8735
[EarlyStop] epoch=11 | best_val_mcc=0.5890
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6392 | F1=0.7357 | AUROC=0.9086 | AUPRC=0.8163
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.6033 | F1=0.7834 | AUROC=0.8870 | AUPRC=0.8762
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4472 | F1=0.6956 | AUROC=0.7889 | AUPRC=0.7726
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5965 | F1=0.7731 | AUROC=0.8823 | AUPRC=0.8564
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5293 | val_loss=0.3876 | val_mcc=0.5504 | val_f1=0.6400 | val_auroc=0.8593

[Epoch 02] train_loss=0.4594 | val_loss=0.3897 | val_mcc=0.5556 | val_f1=0.6453 | val_auroc=0.8712

[Epoch 03] train_loss=0.4279 | val_loss=0.3553 | val_mcc=0.5768 | val_f1=0.6615 | val_auroc=0.8805

[Epoch 04] train_loss=0.4006 | val_loss=0.3952 | val_mcc=0.5655 | val_f1=0.6524 | val_auroc=0.8872

[Epoch 05] train_loss=0.3713 | val_loss=0.3598 | val_mcc=0.5831 | val_f1=0.6669 | val_auroc=0.8902

[Epoch 06] train_loss=0.3425 | val_loss=0.3662 | val_mcc=0.5747 | val_f1=0.6603 | val_auroc=0.8895

[Epoch 07] train_loss=0.3155 | val_loss=0.4724 | val_mcc=0.5354 | val_f1=0.6253 | val_auroc=0.8872

[Epoch 08] train_loss=0.2824 | val_loss=0.4290 | val_mcc=0.5479 | val_f1=0.6388 | val_auroc=0.8829

[Epoch 09] train_loss=0.2467 | val_loss=0.5115 | val_mcc=0.5342 | val_f1=0.6259 | val_auroc=0.8814

[Epoch 10] train_loss=0.2070 | val_loss=0.5593 | val_mcc=0.5134 | val_f1=0.6082 | val_auroc=0.8793

[Epoch 11] train_loss=0.1840 | val_loss=0.4959 | val_mcc=0.5377 | val_f1=0.6311 | val_auroc=0.8769
[EarlyStop] epoch=11 | best_val_mcc=0.5831
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6415 | F1=0.7420 | AUROC=0.9048 | AUPRC=0.8164
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.6017 | F1=0.7965 | AUROC=0.8850 | AUPRC=0.8761
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4549 | F1=0.7156 | AUROC=0.7896 | AUPRC=0.7711
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.6140 | F1=0.7905 | AUROC=0.8799 | AUPRC=0.8598
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 252.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.6077 | F1=0.7202 | AUROC=0.8960 | AUPRC=0.7917
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5944 | F1=0.8006 | AUROC=0.8809 | AUPRC=0.8770
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4464 | F1=0.7202 | AUROC=0.7819 | AUPRC=0.7518
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5700 | F1=0.7728 | AUROC=0.8714 | AUPRC=0.8421
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 150.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6182 | F1=0.7270 | AUROC=0.8923 | AUPRC=0.7979
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5875 | F1=0.7920 | AUROC=0.8717 | AUPRC=0.8641
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4320 | F1=0.7060 | AUROC=0.7766 | AUPRC=0.7490
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5754 | F1=0.7718 | AUROC=0.8665 | AUPRC=0.8462
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 111.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.6093 | F1=0.7207 | AUROC=0.8873 | AUPRC=0.7919
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5647 | F1=0.7779 | AUROC=0.8677 | AUPRC=0.8654
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4210 | F1=0.7044 | AUROC=0.7720 | AUPRC=0.7532
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5791 | F1=0.7732 | AUROC=0.8592 | AUPRC=0.8393
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 67.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6253 | F1=0.7320 | AUROC=0.8932 | AUPRC=0.8020
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.6075 | F1=0.7988 | AUROC=0.8803 | AUPRC=0.8756
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4314 | F1=0.7113 | AUROC=0.7706 | AUPRC=0.7610
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']

[Epoch 01] train_loss=0.3963 | val_loss=0.2214 | val_mcc=0.7332 | val_f1=0.7855 | val_auroc=0.9562

[Epoch 02] train_loss=0.2977 | val_loss=0.1927 | val_mcc=0.7528 | val_f1=0.7991 | val_auroc=0.9608

[Epoch 03] train_loss=0.2811 | val_loss=0.2383 | val_mcc=0.7278 | val_f1=0.7793 | val_auroc=0.9615

[Epoch 04] train_loss=0.2588 | val_loss=0.1891 | val_mcc=0.7626 | val_f1=0.8079 | val_auroc=0.9631

[Epoch 05] train_loss=0.2432 | val_loss=0.2079 | val_mcc=0.7441 | val_f1=0.7939 | val_auroc=0.9635

[Epoch 06] train_loss=0.2276 | val_loss=0.2294 | val_mcc=0.7394 | val_f1=0.7893 | val_auroc=0.9626

[Epoch 07] train_loss=0.2079 | val_loss=0.2113 | val_mcc=0.7520 | val_f1=0.8005 | val_auroc=0.9627

[Epoch 08] train_loss=0.1874 | val_loss=0.2127 | val_mcc=0.7546 | val_f1=0.8025 | val_auroc=0.9623

[Epoch 09] train_loss=0.1669 | val_loss=0.2322 | val_mcc=0.7463 | val_f1=0.7953 | val_auroc=0.9629

[Epoch 10] train_loss=0.1534 | val_loss=0.2345 | val_mcc=0.7435 | val_f1=0.7934 | val_auroc=0.9605
[EarlyStop] epoch=10 | best_val_mcc=0.7626
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7692 | F1=0.8311 | AUROC=0.9558 | AUPRC=0.9055
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7892 | F1=0.8838 | AUROC=0.9712 | AUPRC=0.9721
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4330 | F1=0.7106 | AUROC=0.7728 | AUPRC=0.7581
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.6157 | F1=0.8024 | AUROC=0.8902 | AUPRC=0.8540
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4265 | val_loss=0.2537 | val_mcc=0.7090 | val_f1=0.7642 | val_auroc=0.9557

[Epoch 02] train_loss=0.3119 | val_loss=0.2080 | val_mcc=0.7467 | val_f1=0.7963 | val_auroc=0.9606

[Epoch 03] train_loss=0.2930 | val_loss=0.1969 | val_mcc=0.7586 | val_f1=0.8052 | val_auroc=0.9618

[Epoch 04] train_loss=0.2688 | val_loss=0.2023 | val_mcc=0.7566 | val_f1=0.8041 | val_auroc=0.9621

[Epoch 05] train_loss=0.2507 | val_loss=0.2023 | val_mcc=0.7615 | val_f1=0.8080 | val_auroc=0.9638

[Epoch 06] train_loss=0.2376 | val_loss=0.2047 | val_mcc=0.7663 | val_f1=0.8119 | val_auroc=0.9641

[Epoch 07] train_loss=0.2140 | val_loss=0.2573 | val_mcc=0.7323 | val_f1=0.7832 | val_auroc=0.9609

[Epoch 08] train_loss=0.1960 | val_loss=0.2274 | val_mcc=0.7518 | val_f1=0.8004 | val_auroc=0.9622

[Epoch 09] train_loss=0.1815 | val_loss=0.2718 | val_mcc=0.7316 | val_f1=0.7821 | val_auroc=0.9600

[Epoch 10] train_loss=0.1605 | val_loss=0.2746 | val_mcc=0.7301 | val_f1=0.7810 | val_auroc=0.9594

[Epoch 11] train_loss=0.1320 | val_loss=0.2866 | val_mcc=0.7348 | val_f1=0.7867 | val_auroc=0.9563

[Epoch 12] train_loss=0.1206 | val_loss=0.3113 | val_mcc=0.7230 | val_f1=0.7764 | val_auroc=0.9540
[EarlyStop] epoch=12 | best_val_mcc=0.7663
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7785 | F1=0.8399 | AUROC=0.9590 | AUPRC=0.9102
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8134 | F1=0.9024 | AUROC=0.9751 | AUPRC=0.9758
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4680 | F1=0.7392 | AUROC=0.7877 | AUPRC=0.7793
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.6240 | F1=0.8069 | AUROC=0.8967 | AUPRC=0.8670
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4140 | val_loss=0.2111 | val_mcc=0.7303 | val_f1=0.7799 | val_auroc=0.9540

[Epoch 02] train_loss=0.3008 | val_loss=0.1944 | val_mcc=0.7530 | val_f1=0.7972 | val_auroc=0.9596

[Epoch 03] train_loss=0.2805 | val_loss=0.2086 | val_mcc=0.7531 | val_f1=0.8012 | val_auroc=0.9624

[Epoch 04] train_loss=0.2640 | val_loss=0.1921 | val_mcc=0.7592 | val_f1=0.8038 | val_auroc=0.9610

[Epoch 05] train_loss=0.2473 | val_loss=0.2234 | val_mcc=0.7428 | val_f1=0.7924 | val_auroc=0.9630

[Epoch 06] train_loss=0.2291 | val_loss=0.2302 | val_mcc=0.7367 | val_f1=0.7870 | val_auroc=0.9632

[Epoch 07] train_loss=0.2106 | val_loss=0.1915 | val_mcc=0.7736 | val_f1=0.8176 | val_auroc=0.9648

[Epoch 08] train_loss=0.1906 | val_loss=0.2435 | val_mcc=0.7340 | val_f1=0.7850 | val_auroc=0.9597

[Epoch 09] train_loss=0.1692 | val_loss=0.2199 | val_mcc=0.7601 | val_f1=0.8062 | val_auroc=0.9592

[Epoch 10] train_loss=0.1486 | val_loss=0.2788 | val_mcc=0.7176 | val_f1=0.7716 | val_auroc=0.9568

[Epoch 11] train_loss=0.1318 | val_loss=0.2825 | val_mcc=0.7273 | val_f1=0.7807 | val_auroc=0.9517

[Epoch 12] train_loss=0.0988 | val_loss=0.2920 | val_mcc=0.7299 | val_f1=0.7827 | val_auroc=0.9531

[Epoch 13] train_loss=0.0866 | val_loss=0.3419 | val_mcc=0.7169 | val_f1=0.7720 | val_auroc=0.9508
[EarlyStop] epoch=13 | best_val_mcc=0.7736
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7761 | F1=0.8371 | AUROC=0.9597 | AUPRC=0.9092
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7939 | F1=0.8875 | AUROC=0.9736 | AUPRC=0.9737
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4554 | F1=0.7285 | AUROC=0.7822 | AUPRC=0.7671
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.6472 | F1=0.8176 | AUROC=0.8990 | AUPRC=0.8630
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3977 | val_loss=0.2315 | val_mcc=0.7236 | val_f1=0.7769 | val_auroc=0.9583

[Epoch 02] train_loss=0.2988 | val_loss=0.2463 | val_mcc=0.7208 | val_f1=0.7731 | val_auroc=0.9608

[Epoch 03] train_loss=0.2767 | val_loss=0.2043 | val_mcc=0.7521 | val_f1=0.8005 | val_auroc=0.9624

[Epoch 04] train_loss=0.2594 | val_loss=0.2150 | val_mcc=0.7523 | val_f1=0.7999 | val_auroc=0.9638

[Epoch 05] train_loss=0.2401 | val_loss=0.2195 | val_mcc=0.7436 | val_f1=0.7925 | val_auroc=0.9647

[Epoch 06] train_loss=0.2252 | val_loss=0.2514 | val_mcc=0.7313 | val_f1=0.7798 | val_auroc=0.9655

[Epoch 07] train_loss=0.2073 | val_loss=0.2083 | val_mcc=0.7594 | val_f1=0.8059 | val_auroc=0.9650

[Epoch 08] train_loss=0.1809 | val_loss=0.2573 | val_mcc=0.7363 | val_f1=0.7859 | val_auroc=0.9612

[Epoch 09] train_loss=0.1599 | val_loss=0.2354 | val_mcc=0.7507 | val_f1=0.7990 | val_auroc=0.9612

[Epoch 10] train_loss=0.1402 | val_loss=0.2623 | val_mcc=0.7379 | val_f1=0.7880 | val_auroc=0.9603

[Epoch 11] train_loss=0.1192 | val_loss=0.2759 | val_mcc=0.7395 | val_f1=0.7895 | val_auroc=0.9587

[Epoch 12] train_loss=0.0921 | val_loss=0.2853 | val_mcc=0.7295 | val_f1=0.7819 | val_auroc=0.9560

[Epoch 13] train_loss=0.0811 | val_loss=0.3294 | val_mcc=0.7093 | val_f1=0.7642 | val_auroc=0.9546
[EarlyStop] epoch=13 | best_val_mcc=0.7594
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7700 | F1=0.8343 | AUROC=0.9587 | AUPRC=0.9101
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8156 | F1=0.9048 | AUROC=0.9725 | AUPRC=0.9724
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4183 | F1=0.7234 | AUROC=0.7793 | AUPRC=0.7587
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5918 | F1=0.7917 | AUROC=0.8903 | AUPRC=0.8563
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 213.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7854 | F1=0.8453 | AUROC=0.9657 | AUPRC=0.9245
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.9010 | F1=0.9488 | AUROC=0.9879 | AUPRC=0.9890
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4309 | F1=0.7324 | AUROC=0.7751 | AUPRC=0.7518
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5892 | F1=0.7896 | AUROC=0.9048 | AUPRC=0.8766
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 161.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7595 | F1=0.8269 | AUROC=0.9572 | AUPRC=0.9095
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8278 | F1=0.9096 | AUROC=0.9771 | AUPRC=0.9779
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4268 | F1=0.7291 | AUROC=0.7778 | AUPRC=0.7527
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5649 | F1=0.7794 | AUROC=0.8915 | AUPRC=0.8588
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 148.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7478 | F1=0.8186 | AUROC=0.9559 | AUPRC=0.9049
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8107 | F1=0.9007 | AUROC=0.9760 | AUPRC=0.9765
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4316 | F1=0.7292 | AUROC=0.7857 | AUPRC=0.7721
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5750 | F1=0.7840 | AUROC=0.8894 | AUPRC=0.8557
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 132.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7501 | F1=0.8202 | AUROC=0.9546 | AUPRC=0.9040
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1b_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8102 | F1=0.9013 | AUROC=0.9739 | AUPRC=0.9738
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.5568 | val_loss=0.4732 | val_mcc=0.4746 | val_f1=0.5829 | val_auroc=0.8351

[Epoch 02] train_loss=0.4881 | val_loss=0.4277 | val_mcc=0.5080 | val_f1=0.6085 | val_auroc=0.8592

[Epoch 03] train_loss=0.4528 | val_loss=0.4137 | val_mcc=0.5105 | val_f1=0.6105 | val_auroc=0.8676

[Epoch 04] train_loss=0.4244 | val_loss=0.4254 | val_mcc=0.5197 | val_f1=0.6161 | val_auroc=0.8814

[Epoch 05] train_loss=0.3928 | val_loss=0.3763 | val_mcc=0.5459 | val_f1=0.6379 | val_auroc=0.8836

[Epoch 06] train_loss=0.3645 | val_loss=0.4219 | val_mcc=0.5239 | val_f1=0.6201 | val_auroc=0.8773

[Epoch 07] train_loss=0.3387 | val_loss=0.3739 | val_mcc=0.5452 | val_f1=0.6362 | val_auroc=0.8795

[Epoch 08] train_loss=0.3102 | val_loss=0.4588 | val_mcc=0.5129 | val_f1=0.6113 | val_auroc=0.8712

[Epoch 09] train_loss=0.2773 | val_loss=0.4882 | val_mcc=0.5101 | val_f1=0.6095 | val_auroc=0.8722

[Epoch 10] train_loss=0.2331 | val_loss=0.5002 | val_mcc=0.4979 | val_f1=0.6004 | val_auroc=0.8672

[Epoch 11] train_loss=0.2134 | val_loss=0.5441 | val_mcc=0.5057 | val_f1=0.6054 | val_auroc=0.8698
[EarlyStop] epoch=11 | best_val_mcc=0.5459
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6151 | F1=0.7232 | AUROC=0.8941 | AUPRC=0.7909
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5519 | F1=0.7635 | AUROC=0.8601 | AUPRC=0.8613
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3848 | F1=0.6903 | AUROC=0.7463 | AUPRC=0.7187
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5477 | F1=0.7526 | AUROC=0.8595 | AUPRC=0.8335
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5664 | val_loss=0.4632 | val_mcc=0.4896 | val_f1=0.5944 | val_auroc=0.8394

[Epoch 02] train_loss=0.4841 | val_loss=0.3681 | val_mcc=0.5222 | val_f1=0.6143 | val_auroc=0.8639

[Epoch 03] train_loss=0.4500 | val_loss=0.4043 | val_mcc=0.5314 | val_f1=0.6266 | val_auroc=0.8773

[Epoch 04] train_loss=0.4160 | val_loss=0.4354 | val_mcc=0.5318 | val_f1=0.6257 | val_auroc=0.8828

[Epoch 05] train_loss=0.3829 | val_loss=0.4929 | val_mcc=0.5089 | val_f1=0.6052 | val_auroc=0.8787

[Epoch 06] train_loss=0.3578 | val_loss=0.4528 | val_mcc=0.5251 | val_f1=0.6209 | val_auroc=0.8771

[Epoch 07] train_loss=0.3281 | val_loss=0.4690 | val_mcc=0.5174 | val_f1=0.6153 | val_auroc=0.8745

[Epoch 08] train_loss=0.2976 | val_loss=0.5314 | val_mcc=0.5043 | val_f1=0.6045 | val_auroc=0.8670

[Epoch 09] train_loss=0.2540 | val_loss=0.5485 | val_mcc=0.5186 | val_f1=0.6167 | val_auroc=0.8654

[Epoch 10] train_loss=0.2341 | val_loss=0.5975 | val_mcc=0.5141 | val_f1=0.6131 | val_auroc=0.8639
[EarlyStop] epoch=10 | best_val_mcc=0.5318
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5982 | F1=0.7141 | AUROC=0.8948 | AUPRC=0.7907
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5590 | F1=0.7776 | AUROC=0.8637 | AUPRC=0.8639
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3799 | F1=0.6987 | AUROC=0.7461 | AUPRC=0.7176
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5543 | F1=0.7637 | AUROC=0.8647 | AUPRC=0.8415
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5585 | val_loss=0.4006 | val_mcc=0.5027 | val_f1=0.6001 | val_auroc=0.8418

[Epoch 02] train_loss=0.4843 | val_loss=0.3614 | val_mcc=0.5341 | val_f1=0.6244 | val_auroc=0.8676

[Epoch 03] train_loss=0.4428 | val_loss=0.3914 | val_mcc=0.5432 | val_f1=0.6358 | val_auroc=0.8808

[Epoch 04] train_loss=0.4108 | val_loss=0.3557 | val_mcc=0.5539 | val_f1=0.6430 | val_auroc=0.8846

[Epoch 05] train_loss=0.3827 | val_loss=0.4111 | val_mcc=0.5319 | val_f1=0.6268 | val_auroc=0.8801

[Epoch 06] train_loss=0.3544 | val_loss=0.4216 | val_mcc=0.5282 | val_f1=0.6241 | val_auroc=0.8777

[Epoch 07] train_loss=0.3242 | val_loss=0.4529 | val_mcc=0.5314 | val_f1=0.6264 | val_auroc=0.8787

[Epoch 08] train_loss=0.2905 | val_loss=0.4376 | val_mcc=0.5280 | val_f1=0.6238 | val_auroc=0.8724

[Epoch 09] train_loss=0.2404 | val_loss=0.5149 | val_mcc=0.5183 | val_f1=0.6165 | val_auroc=0.8653

[Epoch 10] train_loss=0.2185 | val_loss=0.6065 | val_mcc=0.5081 | val_f1=0.6085 | val_auroc=0.8623
[EarlyStop] epoch=10 | best_val_mcc=0.5539
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6203 | F1=0.7238 | AUROC=0.8975 | AUPRC=0.7981
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5302 | F1=0.7403 | AUROC=0.8654 | AUPRC=0.8632
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4006 | F1=0.6885 | AUROC=0.7525 | AUPRC=0.7303
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5648 | F1=0.7529 | AUROC=0.8685 | AUPRC=0.8433
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5529 | val_loss=0.4450 | val_mcc=0.4956 | val_f1=0.5984 | val_auroc=0.8382

[Epoch 02] train_loss=0.4853 | val_loss=0.4172 | val_mcc=0.5109 | val_f1=0.6108 | val_auroc=0.8623

[Epoch 03] train_loss=0.4486 | val_loss=0.3834 | val_mcc=0.5280 | val_f1=0.6237 | val_auroc=0.8757

[Epoch 04] train_loss=0.4119 | val_loss=0.4134 | val_mcc=0.5228 | val_f1=0.6191 | val_auroc=0.8835

[Epoch 05] train_loss=0.3826 | val_loss=0.4211 | val_mcc=0.5199 | val_f1=0.6169 | val_auroc=0.8819

[Epoch 06] train_loss=0.3529 | val_loss=0.3908 | val_mcc=0.5446 | val_f1=0.6368 | val_auroc=0.8822

[Epoch 07] train_loss=0.3228 | val_loss=0.3990 | val_mcc=0.5279 | val_f1=0.6236 | val_auroc=0.8763

[Epoch 08] train_loss=0.2887 | val_loss=0.5005 | val_mcc=0.5000 | val_f1=0.6004 | val_auroc=0.8728

[Epoch 09] train_loss=0.2529 | val_loss=0.4670 | val_mcc=0.5243 | val_f1=0.6211 | val_auroc=0.8727

[Epoch 10] train_loss=0.2258 | val_loss=0.5278 | val_mcc=0.5027 | val_f1=0.6039 | val_auroc=0.8677

[Epoch 11] train_loss=0.1782 | val_loss=0.6190 | val_mcc=0.4845 | val_f1=0.5882 | val_auroc=0.8636

[Epoch 12] train_loss=0.1594 | val_loss=0.5933 | val_mcc=0.4939 | val_f1=0.5972 | val_auroc=0.8599
[EarlyStop] epoch=12 | best_val_mcc=0.5446
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6136 | F1=0.7211 | AUROC=0.8919 | AUPRC=0.7840
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5644 | F1=0.7667 | AUROC=0.8576 | AUPRC=0.8486
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3729 | F1=0.6809 | AUROC=0.7437 | AUPRC=0.7201
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5663 | F1=0.7591 | AUROC=0.8611 | AUPRC=0.8395
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 184.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5732 | F1=0.6967 | AUROC=0.8796 | AUPRC=0.7702
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5505 | F1=0.7736 | AUROC=0.8542 | AUPRC=0.8556
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3792 | F1=0.6938 | AUROC=0.7315 | AUPRC=0.7159
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5345 | F1=0.7541 | AUROC=0.8448 | AUPRC=0.8178
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 92.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5827 | F1=0.7029 | AUROC=0.8843 | AUPRC=0.7780
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5477 | F1=0.7686 | AUROC=0.8559 | AUPRC=0.8501
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3684 | F1=0.6851 | AUROC=0.7420 | AUPRC=0.7265
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5224 | F1=0.7462 | AUROC=0.8497 | AUPRC=0.8231
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 100.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5856 | F1=0.7047 | AUROC=0.8825 | AUPRC=0.7821
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5419 | F1=0.7663 | AUROC=0.8572 | AUPRC=0.8625
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3535 | F1=0.6796 | AUROC=0.7333 | AUPRC=0.7201
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5352 | F1=0.7516 | AUROC=0.8537 | AUPRC=0.8293
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 84.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.6042 | F1=0.7175 | AUROC=0.8904 | AUPRC=0.7913
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5679 | F1=0.7765 | AUROC=0.8617 | AUPRC=0.8644
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3818 | F1=0.6902 | AUROC=0.7438 | AUPRC=0.7281
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']

[Epoch 01] train_loss=0.3962 | val_loss=0.2194 | val_mcc=0.7263 | val_f1=0.7798 | val_auroc=0.9562

[Epoch 02] train_loss=0.2981 | val_loss=0.2086 | val_mcc=0.7440 | val_f1=0.7939 | val_auroc=0.9597

[Epoch 03] train_loss=0.2699 | val_loss=0.2041 | val_mcc=0.7497 | val_f1=0.7983 | val_auroc=0.9602

[Epoch 04] train_loss=0.2533 | val_loss=0.2286 | val_mcc=0.7385 | val_f1=0.7885 | val_auroc=0.9627

[Epoch 05] train_loss=0.2354 | val_loss=0.2204 | val_mcc=0.7400 | val_f1=0.7902 | val_auroc=0.9622

[Epoch 06] train_loss=0.2150 | val_loss=0.2138 | val_mcc=0.7482 | val_f1=0.7975 | val_auroc=0.9616

[Epoch 07] train_loss=0.1951 | val_loss=0.2490 | val_mcc=0.7295 | val_f1=0.7806 | val_auroc=0.9615

[Epoch 08] train_loss=0.1700 | val_loss=0.2383 | val_mcc=0.7365 | val_f1=0.7874 | val_auroc=0.9606

[Epoch 09] train_loss=0.1576 | val_loss=0.2698 | val_mcc=0.7235 | val_f1=0.7755 | val_auroc=0.9601
[EarlyStop] epoch=9 | best_val_mcc=0.7497
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7640 | F1=0.8289 | AUROC=0.9549 | AUPRC=0.8968
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8027 | F1=0.8919 | AUROC=0.9696 | AUPRC=0.9713
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4211 | F1=0.7132 | AUROC=0.7658 | AUPRC=0.7396
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5493 | F1=0.7720 | AUROC=0.8802 | AUPRC=0.8540
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4212 | val_loss=0.2513 | val_mcc=0.7101 | val_f1=0.7652 | val_auroc=0.9559

[Epoch 02] train_loss=0.3079 | val_loss=0.2069 | val_mcc=0.7455 | val_f1=0.7952 | val_auroc=0.9610

[Epoch 03] train_loss=0.2836 | val_loss=0.2523 | val_mcc=0.7223 | val_f1=0.7733 | val_auroc=0.9619

[Epoch 04] train_loss=0.2586 | val_loss=0.2117 | val_mcc=0.7485 | val_f1=0.7976 | val_auroc=0.9632

[Epoch 05] train_loss=0.2424 | val_loss=0.2076 | val_mcc=0.7550 | val_f1=0.8029 | val_auroc=0.9644

[Epoch 06] train_loss=0.2189 | val_loss=0.2374 | val_mcc=0.7371 | val_f1=0.7869 | val_auroc=0.9631

[Epoch 07] train_loss=0.2015 | val_loss=0.2413 | val_mcc=0.7440 | val_f1=0.7938 | val_auroc=0.9603

[Epoch 08] train_loss=0.1812 | val_loss=0.2654 | val_mcc=0.7308 | val_f1=0.7817 | val_auroc=0.9608

[Epoch 09] train_loss=0.1600 | val_loss=0.2958 | val_mcc=0.7111 | val_f1=0.7672 | val_auroc=0.9543

[Epoch 10] train_loss=0.1309 | val_loss=0.2832 | val_mcc=0.7254 | val_f1=0.7792 | val_auroc=0.9548

[Epoch 11] train_loss=0.1175 | val_loss=0.3174 | val_mcc=0.7150 | val_f1=0.7703 | val_auroc=0.9528
[EarlyStop] epoch=11 | best_val_mcc=0.7550
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7704 | F1=0.8344 | AUROC=0.9581 | AUPRC=0.8990
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8234 | F1=0.9055 | AUROC=0.9739 | AUPRC=0.9730
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4329 | F1=0.7293 | AUROC=0.7687 | AUPRC=0.7425
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5611 | F1=0.7778 | AUROC=0.8850 | AUPRC=0.8602
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4236 | val_loss=0.2107 | val_mcc=0.7350 | val_f1=0.7851 | val_auroc=0.9565

[Epoch 02] train_loss=0.3052 | val_loss=0.2128 | val_mcc=0.7457 | val_f1=0.7955 | val_auroc=0.9608

[Epoch 03] train_loss=0.2777 | val_loss=0.1913 | val_mcc=0.7650 | val_f1=0.8102 | val_auroc=0.9642

[Epoch 04] train_loss=0.2541 | val_loss=0.2071 | val_mcc=0.7496 | val_f1=0.7986 | val_auroc=0.9627

[Epoch 05] train_loss=0.2370 | val_loss=0.2289 | val_mcc=0.7435 | val_f1=0.7916 | val_auroc=0.9654

[Epoch 06] train_loss=0.2133 | val_loss=0.2078 | val_mcc=0.7486 | val_f1=0.7972 | val_auroc=0.9614

[Epoch 07] train_loss=0.1924 | val_loss=0.2329 | val_mcc=0.7367 | val_f1=0.7882 | val_auroc=0.9599

[Epoch 08] train_loss=0.1616 | val_loss=0.2530 | val_mcc=0.7370 | val_f1=0.7885 | val_auroc=0.9590

[Epoch 09] train_loss=0.1485 | val_loss=0.2762 | val_mcc=0.7205 | val_f1=0.7748 | val_auroc=0.9554
[EarlyStop] epoch=9 | best_val_mcc=0.7650
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7660 | F1=0.8291 | AUROC=0.9564 | AUPRC=0.9001
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7935 | F1=0.8844 | AUROC=0.9716 | AUPRC=0.9724
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4224 | F1=0.7116 | AUROC=0.7682 | AUPRC=0.7411
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5707 | F1=0.7812 | AUROC=0.8832 | AUPRC=0.8595
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4080 | val_loss=0.2312 | val_mcc=0.7186 | val_f1=0.7737 | val_auroc=0.9559

[Epoch 02] train_loss=0.3015 | val_loss=0.2149 | val_mcc=0.7370 | val_f1=0.7885 | val_auroc=0.9591

[Epoch 03] train_loss=0.2757 | val_loss=0.2187 | val_mcc=0.7437 | val_f1=0.7932 | val_auroc=0.9619

[Epoch 04] train_loss=0.2530 | val_loss=0.2060 | val_mcc=0.7548 | val_f1=0.8027 | val_auroc=0.9634

[Epoch 05] train_loss=0.2344 | val_loss=0.1998 | val_mcc=0.7561 | val_f1=0.8037 | val_auroc=0.9635

[Epoch 06] train_loss=0.2116 | val_loss=0.2421 | val_mcc=0.7376 | val_f1=0.7872 | val_auroc=0.9632

[Epoch 07] train_loss=0.1914 | val_loss=0.2167 | val_mcc=0.7498 | val_f1=0.7987 | val_auroc=0.9627

[Epoch 08] train_loss=0.1696 | val_loss=0.2392 | val_mcc=0.7412 | val_f1=0.7909 | val_auroc=0.9623

[Epoch 09] train_loss=0.1476 | val_loss=0.2689 | val_mcc=0.7232 | val_f1=0.7758 | val_auroc=0.9596

[Epoch 10] train_loss=0.1223 | val_loss=0.2586 | val_mcc=0.7325 | val_f1=0.7845 | val_auroc=0.9595

[Epoch 11] train_loss=0.1073 | val_loss=0.2651 | val_mcc=0.7293 | val_f1=0.7822 | val_auroc=0.9582
[EarlyStop] epoch=11 | best_val_mcc=0.7561
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7715 | F1=0.8343 | AUROC=0.9556 | AUPRC=0.8998
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8027 | F1=0.8919 | AUROC=0.9712 | AUPRC=0.9714
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4398 | F1=0.7266 | AUROC=0.7647 | AUPRC=0.7330
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5650 | F1=0.7792 | AUROC=0.8818 | AUPRC=0.8580
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 219.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7713 | F1=0.8353 | AUROC=0.9617 | AUPRC=0.9117
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8677 | F1=0.9304 | AUROC=0.9829 | AUPRC=0.9834
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4108 | F1=0.7227 | AUROC=0.7621 | AUPRC=0.7349
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5589 | F1=0.7767 | AUROC=0.8902 | AUPRC=0.8674
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 167.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7495 | F1=0.8198 | AUROC=0.9566 | AUPRC=0.9035
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8267 | F1=0.9112 | AUROC=0.9713 | AUPRC=0.9724
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4024 | F1=0.7219 | AUROC=0.7609 | AUPRC=0.7373
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5401 | F1=0.7685 | AUROC=0.8832 | AUPRC=0.8594
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 87.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7415 | F1=0.8142 | AUROC=0.9550 | AUPRC=0.8971
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8159 | F1=0.9043 | AUROC=0.9688 | AUPRC=0.9693
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4099 | F1=0.7207 | AUROC=0.7617 | AUPRC=0.7347
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5515 | F1=0.7736 | AUROC=0.8808 | AUPRC=0.8536
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 107.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7483 | F1=0.8190 | AUROC=0.9544 | AUPRC=0.8994
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8242 | F1=0.9091 | AUROC=0.9717 | AUPRC=0.9721
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...

[Epoch 01] train_loss=0.5634 | val_loss=0.4213 | val_mcc=0.4811 | val_f1=0.5772 | val_auroc=0.8163

[Epoch 02] train_loss=0.5076 | val_loss=0.4608 | val_mcc=0.4961 | val_f1=0.5989 | val_auroc=0.8306

[Epoch 03] train_loss=0.4804 | val_loss=0.4407 | val_mcc=0.5053 | val_f1=0.6062 | val_auroc=0.8458

[Epoch 04] train_loss=0.4475 | val_loss=0.4375 | val_mcc=0.5229 | val_f1=0.6201 | val_auroc=0.8659

[Epoch 05] train_loss=0.4156 | val_loss=0.4064 | val_mcc=0.5388 | val_f1=0.6324 | val_auroc=0.8760

[Epoch 06] train_loss=0.3872 | val_loss=0.5011 | val_mcc=0.5038 | val_f1=0.6011 | val_auroc=0.8778

[Epoch 07] train_loss=0.3621 | val_loss=0.3913 | val_mcc=0.5367 | val_f1=0.6307 | val_auroc=0.8786

[Epoch 08] train_loss=0.3352 | val_loss=0.3861 | val_mcc=0.5476 | val_f1=0.6390 | val_auroc=0.8798

[Epoch 09] train_loss=0.3137 | val_loss=0.3862 | val_mcc=0.5285 | val_f1=0.6234 | val_auroc=0.8750

[Epoch 10] train_loss=0.2884 | val_loss=0.4322 | val_mcc=0.5293 | val_f1=0.6250 | val_auroc=0.8757

[Epoch 11] train_loss=0.2624 | val_loss=0.5092 | val_mcc=0.5005 | val_f1=0.6001 | val_auroc=0.8713

[Epoch 12] train_loss=0.2389 | val_loss=0.4575 | val_mcc=0.5181 | val_f1=0.6164 | val_auroc=0.8719

[Epoch 13] train_loss=0.2027 | val_loss=0.4761 | val_mcc=0.5183 | val_f1=0.6165 | val_auroc=0.8702

[Epoch 14] train_loss=0.1867 | val_loss=0.5026 | val_mcc=0.5112 | val_f1=0.6110 | val_auroc=0.8670
[EarlyStop] epoch=14 | best_val_mcc=0.5476
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.5851 | F1=0.6994 | AUROC=0.8863 | AUPRC=0.7845
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5882 | F1=0.7852 | AUROC=0.8780 | AUPRC=0.8611
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4141 | F1=0.6952 | AUROC=0.7620 | AUPRC=0.7419
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5109 | F1=0.7214 | AUROC=0.8402 | AUPRC=0.8145
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5685 | val_loss=0.4236 | val_mcc=0.4909 | val_f1=0.5836 | val_auroc=0.8140

[Epoch 02] train_loss=0.5098 | val_loss=0.4504 | val_mcc=0.5011 | val_f1=0.6019 | val_auroc=0.8361

[Epoch 03] train_loss=0.4814 | val_loss=0.4370 | val_mcc=0.5181 | val_f1=0.6163 | val_auroc=0.8559

[Epoch 04] train_loss=0.4472 | val_loss=0.3785 | val_mcc=0.5424 | val_f1=0.6342 | val_auroc=0.8733

[Epoch 05] train_loss=0.4152 | val_loss=0.3618 | val_mcc=0.5510 | val_f1=0.6402 | val_auroc=0.8759

[Epoch 06] train_loss=0.3861 | val_loss=0.4344 | val_mcc=0.5354 | val_f1=0.6292 | val_auroc=0.8781

[Epoch 07] train_loss=0.3660 | val_loss=0.4745 | val_mcc=0.5224 | val_f1=0.6166 | val_auroc=0.8772

[Epoch 08] train_loss=0.3394 | val_loss=0.4258 | val_mcc=0.5349 | val_f1=0.6294 | val_auroc=0.8754

[Epoch 09] train_loss=0.3202 | val_loss=0.4483 | val_mcc=0.5308 | val_f1=0.6258 | val_auroc=0.8724

[Epoch 10] train_loss=0.2861 | val_loss=0.4402 | val_mcc=0.5397 | val_f1=0.6329 | val_auroc=0.8735

[Epoch 11] train_loss=0.2658 | val_loss=0.4523 | val_mcc=0.5330 | val_f1=0.6278 | val_auroc=0.8674
[EarlyStop] epoch=11 | best_val_mcc=0.5510
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.5897 | F1=0.6987 | AUROC=0.8844 | AUPRC=0.7765
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5903 | F1=0.7800 | AUROC=0.8734 | AUPRC=0.8576
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3986 | F1=0.6815 | AUROC=0.7642 | AUPRC=0.7476
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5120 | F1=0.7120 | AUROC=0.8400 | AUPRC=0.8055
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5744 | val_loss=0.4642 | val_mcc=0.4715 | val_f1=0.5771 | val_auroc=0.8181

[Epoch 02] train_loss=0.5079 | val_loss=0.4242 | val_mcc=0.5073 | val_f1=0.6040 | val_auroc=0.8333

[Epoch 03] train_loss=0.4830 | val_loss=0.3961 | val_mcc=0.5200 | val_f1=0.6150 | val_auroc=0.8529

[Epoch 04] train_loss=0.4454 | val_loss=0.3847 | val_mcc=0.5513 | val_f1=0.6410 | val_auroc=0.8725

[Epoch 05] train_loss=0.4232 | val_loss=0.3373 | val_mcc=0.5470 | val_f1=0.6273 | val_auroc=0.8774

[Epoch 06] train_loss=0.3923 | val_loss=0.3863 | val_mcc=0.5505 | val_f1=0.6415 | val_auroc=0.8805

[Epoch 07] train_loss=0.3644 | val_loss=0.3981 | val_mcc=0.5356 | val_f1=0.6299 | val_auroc=0.8796

[Epoch 08] train_loss=0.3419 | val_loss=0.4040 | val_mcc=0.5409 | val_f1=0.6340 | val_auroc=0.8786

[Epoch 09] train_loss=0.3066 | val_loss=0.4280 | val_mcc=0.5383 | val_f1=0.6320 | val_auroc=0.8789

[Epoch 10] train_loss=0.2888 | val_loss=0.4748 | val_mcc=0.5281 | val_f1=0.6240 | val_auroc=0.8763
[EarlyStop] epoch=10 | best_val_mcc=0.5513
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.5998 | F1=0.7076 | AUROC=0.8770 | AUPRC=0.7744
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5978 | F1=0.7868 | AUROC=0.8599 | AUPRC=0.8467
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4185 | F1=0.6905 | AUROC=0.7599 | AUPRC=0.7450
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5360 | F1=0.7330 | AUROC=0.8342 | AUPRC=0.8031
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5630 | val_loss=0.5015 | val_mcc=0.4663 | val_f1=0.5765 | val_auroc=0.8171

[Epoch 02] train_loss=0.5093 | val_loss=0.4309 | val_mcc=0.5051 | val_f1=0.6032 | val_auroc=0.8343

[Epoch 03] train_loss=0.4792 | val_loss=0.4217 | val_mcc=0.5209 | val_f1=0.6175 | val_auroc=0.8530

[Epoch 04] train_loss=0.4479 | val_loss=0.3986 | val_mcc=0.5378 | val_f1=0.6309 | val_auroc=0.8670

[Epoch 05] train_loss=0.4151 | val_loss=0.3875 | val_mcc=0.5393 | val_f1=0.6327 | val_auroc=0.8753

[Epoch 06] train_loss=0.3847 | val_loss=0.3742 | val_mcc=0.5519 | val_f1=0.6415 | val_auroc=0.8818

[Epoch 07] train_loss=0.3576 | val_loss=0.4075 | val_mcc=0.5453 | val_f1=0.6372 | val_auroc=0.8800

[Epoch 08] train_loss=0.3284 | val_loss=0.4225 | val_mcc=0.5374 | val_f1=0.6308 | val_auroc=0.8805

[Epoch 09] train_loss=0.3001 | val_loss=0.4789 | val_mcc=0.5148 | val_f1=0.6115 | val_auroc=0.8768

[Epoch 10] train_loss=0.2775 | val_loss=0.4839 | val_mcc=0.5160 | val_f1=0.6127 | val_auroc=0.8753

[Epoch 11] train_loss=0.2347 | val_loss=0.4449 | val_mcc=0.5191 | val_f1=0.6170 | val_auroc=0.8712

[Epoch 12] train_loss=0.2151 | val_loss=0.4848 | val_mcc=0.5191 | val_f1=0.6169 | val_auroc=0.8703
[EarlyStop] epoch=12 | best_val_mcc=0.5519
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6014 | F1=0.7084 | AUROC=0.8873 | AUPRC=0.7855
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5758 | F1=0.7727 | AUROC=0.8706 | AUPRC=0.8553
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3937 | F1=0.6809 | AUROC=0.7618 | AUPRC=0.7427
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5334 | F1=0.7302 | AUROC=0.8393 | AUPRC=0.8113
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 279.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5625 | F1=0.6870 | AUROC=0.8743 | AUPRC=0.7534
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5334 | F1=0.7644 | AUROC=0.8430 | AUPRC=0.8239
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3880 | F1=0.6964 | AUROC=0.7458 | AUPRC=0.7203
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.4963 | F1=0.7266 | AUROC=0.8214 | AUPRC=0.7912
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 156.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.5475 | F1=0.6751 | AUROC=0.8628 | AUPRC=0.7486
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5305 | F1=0.7605 | AUROC=0.8480 | AUPRC=0.8294
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3776 | F1=0.6800 | AUROC=0.7468 | AUPRC=0.7286
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.4906 | F1=0.7174 | AUROC=0.8191 | AUPRC=0.7827
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 134.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5462 | F1=0.6747 | AUROC=0.8535 | AUPRC=0.7369
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5193 | F1=0.7533 | AUROC=0.8323 | AUPRC=0.8189
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3957 | F1=0.6888 | AUROC=0.7498 | AUPRC=0.7284
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.4929 | F1=0.7106 | AUROC=0.8037 | AUPRC=0.7842
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 151.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5601 | F1=0.6839 | AUROC=0.8662 | AUPRC=0.7533
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5449 | F1=0.7668 | AUROC=0.8462 | AUPRC=0.8340
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3804 | F1=0.6845 | AUROC=0.7444 | AUPRC=0.7205
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.4136 | val_loss=0.2219 | val_mcc=0.7286 | val_f1=0.7818 | val_auroc=0.9573

[Epoch 02] train_loss=0.3090 | val_loss=0.2282 | val_mcc=0.7304 | val_f1=0.7825 | val_auroc=0.9601

[Epoch 03] train_loss=0.2899 | val_loss=0.2394 | val_mcc=0.7233 | val_f1=0.7753 | val_auroc=0.9610

[Epoch 04] train_loss=0.2771 | val_loss=0.1977 | val_mcc=0.7578 | val_f1=0.8047 | val_auroc=0.9618

[Epoch 05] train_loss=0.2591 | val_loss=0.2186 | val_mcc=0.7417 | val_f1=0.7917 | val_auroc=0.9620

[Epoch 06] train_loss=0.2470 | val_loss=0.2181 | val_mcc=0.7497 | val_f1=0.7979 | val_auroc=0.9629

[Epoch 07] train_loss=0.2322 | val_loss=0.2292 | val_mcc=0.7382 | val_f1=0.7884 | val_auroc=0.9622

[Epoch 08] train_loss=0.2151 | val_loss=0.2085 | val_mcc=0.7577 | val_f1=0.8047 | val_auroc=0.9642

[Epoch 09] train_loss=0.2013 | val_loss=0.2301 | val_mcc=0.7414 | val_f1=0.7907 | val_auroc=0.9628

[Epoch 10] train_loss=0.1918 | val_loss=0.2205 | val_mcc=0.7454 | val_f1=0.7948 | val_auroc=0.9623
[EarlyStop] epoch=10 | best_val_mcc=0.7578
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7603 | F1=0.8255 | AUROC=0.9553 | AUPRC=0.9029
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8001 | F1=0.8902 | AUROC=0.9719 | AUPRC=0.9679
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4105 | F1=0.7074 | AUROC=0.7691 | AUPRC=0.7430
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5702 | F1=0.7809 | AUROC=0.8693 | AUPRC=0.8307
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4173 | val_loss=0.2717 | val_mcc=0.6913 | val_f1=0.7473 | val_auroc=0.9570

[Epoch 02] train_loss=0.3087 | val_loss=0.2251 | val_mcc=0.7372 | val_f1=0.7882 | val_auroc=0.9606

[Epoch 03] train_loss=0.2935 | val_loss=0.2022 | val_mcc=0.7502 | val_f1=0.7986 | val_auroc=0.9612

[Epoch 04] train_loss=0.2815 | val_loss=0.2565 | val_mcc=0.7165 | val_f1=0.7686 | val_auroc=0.9621

[Epoch 05] train_loss=0.2632 | val_loss=0.2410 | val_mcc=0.7303 | val_f1=0.7804 | val_auroc=0.9639

[Epoch 06] train_loss=0.2473 | val_loss=0.2154 | val_mcc=0.7465 | val_f1=0.7955 | val_auroc=0.9636

[Epoch 07] train_loss=0.2378 | val_loss=0.2153 | val_mcc=0.7462 | val_f1=0.7958 | val_auroc=0.9614

[Epoch 08] train_loss=0.2127 | val_loss=0.2321 | val_mcc=0.7426 | val_f1=0.7916 | val_auroc=0.9630

[Epoch 09] train_loss=0.1993 | val_loss=0.2363 | val_mcc=0.7354 | val_f1=0.7866 | val_auroc=0.9608
[EarlyStop] epoch=9 | best_val_mcc=0.7502
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7625 | F1=0.8267 | AUROC=0.9537 | AUPRC=0.9015
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8069 | F1=0.8926 | AUROC=0.9693 | AUPRC=0.9667
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4359 | F1=0.7177 | AUROC=0.7656 | AUPRC=0.7357
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5664 | F1=0.7795 | AUROC=0.8703 | AUPRC=0.8346
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4274 | val_loss=0.2278 | val_mcc=0.7197 | val_f1=0.7748 | val_auroc=0.9548

[Epoch 02] train_loss=0.3123 | val_loss=0.2355 | val_mcc=0.7230 | val_f1=0.7758 | val_auroc=0.9598

[Epoch 03] train_loss=0.2911 | val_loss=0.2004 | val_mcc=0.7530 | val_f1=0.8013 | val_auroc=0.9622

[Epoch 04] train_loss=0.2784 | val_loss=0.1925 | val_mcc=0.7573 | val_f1=0.8035 | val_auroc=0.9627

[Epoch 05] train_loss=0.2591 | val_loss=0.1938 | val_mcc=0.7620 | val_f1=0.8080 | val_auroc=0.9633

[Epoch 06] train_loss=0.2483 | val_loss=0.2649 | val_mcc=0.7114 | val_f1=0.7630 | val_auroc=0.9630

[Epoch 07] train_loss=0.2337 | val_loss=0.2541 | val_mcc=0.7239 | val_f1=0.7745 | val_auroc=0.9629

[Epoch 08] train_loss=0.2157 | val_loss=0.2411 | val_mcc=0.7381 | val_f1=0.7877 | val_auroc=0.9622

[Epoch 09] train_loss=0.1993 | val_loss=0.2131 | val_mcc=0.7500 | val_f1=0.7989 | val_auroc=0.9600

[Epoch 10] train_loss=0.1758 | val_loss=0.2155 | val_mcc=0.7600 | val_f1=0.8069 | val_auroc=0.9600

[Epoch 11] train_loss=0.1614 | val_loss=0.2591 | val_mcc=0.7271 | val_f1=0.7790 | val_auroc=0.9577
[EarlyStop] epoch=11 | best_val_mcc=0.7620
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7618 | F1=0.8265 | AUROC=0.9563 | AUPRC=0.9048
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8127 | F1=0.8957 | AUROC=0.9763 | AUPRC=0.9742
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4165 | F1=0.7099 | AUROC=0.7689 | AUPRC=0.7458
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5597 | F1=0.7764 | AUROC=0.8739 | AUPRC=0.8410
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4061 | val_loss=0.2310 | val_mcc=0.7248 | val_f1=0.7783 | val_auroc=0.9579

[Epoch 02] train_loss=0.3073 | val_loss=0.2285 | val_mcc=0.7348 | val_f1=0.7855 | val_auroc=0.9608

[Epoch 03] train_loss=0.2839 | val_loss=0.2255 | val_mcc=0.7389 | val_f1=0.7890 | val_auroc=0.9623

[Epoch 04] train_loss=0.2709 | val_loss=0.2023 | val_mcc=0.7547 | val_f1=0.8026 | val_auroc=0.9640

[Epoch 05] train_loss=0.2518 | val_loss=0.2073 | val_mcc=0.7535 | val_f1=0.8013 | val_auroc=0.9641

[Epoch 06] train_loss=0.2394 | val_loss=0.2461 | val_mcc=0.7282 | val_f1=0.7779 | val_auroc=0.9646

[Epoch 07] train_loss=0.2229 | val_loss=0.2506 | val_mcc=0.7304 | val_f1=0.7799 | val_auroc=0.9639

[Epoch 08] train_loss=0.2030 | val_loss=0.2196 | val_mcc=0.7537 | val_f1=0.8012 | val_auroc=0.9635

[Epoch 09] train_loss=0.1843 | val_loss=0.2183 | val_mcc=0.7513 | val_f1=0.7993 | val_auroc=0.9641

[Epoch 10] train_loss=0.1708 | val_loss=0.2431 | val_mcc=0.7405 | val_f1=0.7897 | val_auroc=0.9629
[EarlyStop] epoch=10 | best_val_mcc=0.7547
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7559 | F1=0.8242 | AUROC=0.9573 | AUPRC=0.9074
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8398 | F1=0.9151 | AUROC=0.9764 | AUPRC=0.9739
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3975 | F1=0.7107 | AUROC=0.7660 | AUPRC=0.7364
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5637 | F1=0.7790 | AUROC=0.8743 | AUPRC=0.8397
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 166.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7681 | F1=0.8330 | AUROC=0.9633 | AUPRC=0.9183
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8627 | F1=0.9270 | AUROC=0.9845 | AUPRC=0.9849
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4179 | F1=0.7252 | AUROC=0.7715 | AUPRC=0.7472
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5347 | F1=0.7661 | AUROC=0.8886 | AUPRC=0.8693
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 178.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7624 | F1=0.8290 | AUROC=0.9571 | AUPRC=0.9087
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8504 | F1=0.9217 | AUROC=0.9746 | AUPRC=0.9744
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4337 | F1=0.7313 | AUROC=0.7708 | AUPRC=0.7463
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5511 | F1=0.7734 | AUROC=0.8785 | AUPRC=0.8448
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 171.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7451 | F1=0.8167 | AUROC=0.9560 | AUPRC=0.9061
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8185 | F1=0.9062 | AUROC=0.9745 | AUPRC=0.9752
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3946 | F1=0.7133 | AUROC=0.7708 | AUPRC=0.7430
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5385 | F1=0.7678 | AUROC=0.8748 | AUPRC=0.8351
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 179.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7517 | F1=0.8214 | AUROC=0.9572 | AUPRC=0.9095
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esm2_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8244 | F1=0.9088 | AUROC=0.9704 | AUPRC=0.9707
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.5753 | val_loss=0.3911 | val_mcc=0.5476 | val_f1=0.6149 | val_auroc=0.8263

[Epoch 02] train_loss=0.4974 | val_loss=0.3806 | val_mcc=0.5797 | val_f1=0.6481 | val_auroc=0.8431

[Epoch 03] train_loss=0.4782 | val_loss=0.4104 | val_mcc=0.5767 | val_f1=0.6573 | val_auroc=0.8504

[Epoch 04] train_loss=0.4657 | val_loss=0.4386 | val_mcc=0.5568 | val_f1=0.6461 | val_auroc=0.8542

[Epoch 05] train_loss=0.4531 | val_loss=0.3804 | val_mcc=0.5763 | val_f1=0.6584 | val_auroc=0.8587

[Epoch 06] train_loss=0.4450 | val_loss=0.4028 | val_mcc=0.5631 | val_f1=0.6508 | val_auroc=0.8607

[Epoch 07] train_loss=0.4318 | val_loss=0.3605 | val_mcc=0.5840 | val_f1=0.6644 | val_auroc=0.8658

[Epoch 08] train_loss=0.4263 | val_loss=0.3501 | val_mcc=0.5893 | val_f1=0.6673 | val_auroc=0.8663

[Epoch 09] train_loss=0.4204 | val_loss=0.3944 | val_mcc=0.5718 | val_f1=0.6578 | val_auroc=0.8704

[Epoch 10] train_loss=0.4129 | val_loss=0.3409 | val_mcc=0.5950 | val_f1=0.6731 | val_auroc=0.8714

[Epoch 11] train_loss=0.4059 | val_loss=0.3490 | val_mcc=0.5856 | val_f1=0.6665 | val_auroc=0.8711

[Epoch 12] train_loss=0.3976 | val_loss=0.4169 | val_mcc=0.5478 | val_f1=0.6390 | val_auroc=0.8746

[Epoch 13] train_loss=0.3929 | val_loss=0.3742 | val_mcc=0.5718 | val_f1=0.6578 | val_auroc=0.8752

[Epoch 14] train_loss=0.3855 | val_loss=0.4016 | val_mcc=0.5571 | val_f1=0.6465 | val_auroc=0.8769

[Epoch 15] train_loss=0.3712 | val_loss=0.3864 | val_mcc=0.5677 | val_f1=0.6549 | val_auroc=0.8767

[Epoch 16] train_loss=0.3663 | val_loss=0.4084 | val_mcc=0.5565 | val_f1=0.6457 | val_auroc=0.8778
[EarlyStop] epoch=16 | best_val_mcc=0.5950
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.6198 | F1=0.7185 | AUROC=0.8676 | AUPRC=0.7953
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.5802 | F1=0.7599 | AUROC=0.8478 | AUPRC=0.8645
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.3898 | F1=0.6634 | AUROC=0.7448 | AUPRC=0.7532
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5396 | F1=0.7303 | AUROC=0.8275 | AUPRC=0.8302
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.5700 | val_loss=0.3750 | val_mcc=0.5634 | val_f1=0.6230 | val_auroc=0.8307

[Epoch 02] train_loss=0.5023 | val_loss=0.4210 | val_mcc=0.5667 | val_f1=0.6496 | val_auroc=0.8450

[Epoch 03] train_loss=0.4837 | val_loss=0.4318 | val_mcc=0.5581 | val_f1=0.6459 | val_auroc=0.8484

[Epoch 04] train_loss=0.4686 | val_loss=0.3827 | val_mcc=0.5859 | val_f1=0.6622 | val_auroc=0.8543

[Epoch 05] train_loss=0.4574 | val_loss=0.3680 | val_mcc=0.5830 | val_f1=0.6608 | val_auroc=0.8593

[Epoch 06] train_loss=0.4520 | val_loss=0.4779 | val_mcc=0.5220 | val_f1=0.6184 | val_auroc=0.8590

[Epoch 07] train_loss=0.4437 | val_loss=0.3454 | val_mcc=0.5987 | val_f1=0.6717 | val_auroc=0.8647

[Epoch 08] train_loss=0.4307 | val_loss=0.4952 | val_mcc=0.5134 | val_f1=0.6110 | val_auroc=0.8639

[Epoch 09] train_loss=0.4242 | val_loss=0.3389 | val_mcc=0.5975 | val_f1=0.6726 | val_auroc=0.8662

[Epoch 10] train_loss=0.4125 | val_loss=0.3835 | val_mcc=0.5687 | val_f1=0.6553 | val_auroc=0.8671

[Epoch 11] train_loss=0.4015 | val_loss=0.3906 | val_mcc=0.5752 | val_f1=0.6605 | val_auroc=0.8687

[Epoch 12] train_loss=0.3824 | val_loss=0.4304 | val_mcc=0.5322 | val_f1=0.6270 | val_auroc=0.8654

[Epoch 13] train_loss=0.3789 | val_loss=0.3671 | val_mcc=0.5749 | val_f1=0.6592 | val_auroc=0.8671
[EarlyStop] epoch=13 | best_val_mcc=0.5987
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.6239 | F1=0.7148 | AUROC=0.8557 | AUPRC=0.7854
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.5676 | F1=0.7447 | AUROC=0.8335 | AUPRC=0.8583
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.3858 | F1=0.6498 | AUROC=0.7304 | AUPRC=0.7482
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5451 | F1=0.7235 | AUROC=0.8167 | AUPRC=0.8247
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.5664 | val_loss=0.4096 | val_mcc=0.5563 | val_f1=0.6318 | val_auroc=0.8311

[Epoch 02] train_loss=0.4929 | val_loss=0.3618 | val_mcc=0.5864 | val_f1=0.6516 | val_auroc=0.8473

[Epoch 03] train_loss=0.4733 | val_loss=0.3403 | val_mcc=0.5938 | val_f1=0.6614 | val_auroc=0.8556

[Epoch 04] train_loss=0.4646 | val_loss=0.3615 | val_mcc=0.5796 | val_f1=0.6592 | val_auroc=0.8592

[Epoch 05] train_loss=0.4528 | val_loss=0.3527 | val_mcc=0.5884 | val_f1=0.6642 | val_auroc=0.8654

[Epoch 06] train_loss=0.4486 | val_loss=0.4377 | val_mcc=0.5379 | val_f1=0.6314 | val_auroc=0.8639

[Epoch 07] train_loss=0.4384 | val_loss=0.4200 | val_mcc=0.5663 | val_f1=0.6536 | val_auroc=0.8703

[Epoch 08] train_loss=0.4249 | val_loss=0.3582 | val_mcc=0.5873 | val_f1=0.6680 | val_auroc=0.8696

[Epoch 09] train_loss=0.4206 | val_loss=0.3256 | val_mcc=0.6006 | val_f1=0.6735 | val_auroc=0.8710

[Epoch 10] train_loss=0.4103 | val_loss=0.3532 | val_mcc=0.5829 | val_f1=0.6649 | val_auroc=0.8707

[Epoch 11] train_loss=0.4051 | val_loss=0.3587 | val_mcc=0.5843 | val_f1=0.6670 | val_auroc=0.8741

[Epoch 12] train_loss=0.3980 | val_loss=0.4474 | val_mcc=0.5382 | val_f1=0.6308 | val_auroc=0.8728

[Epoch 13] train_loss=0.3909 | val_loss=0.3639 | val_mcc=0.5739 | val_f1=0.6592 | val_auroc=0.8734

[Epoch 14] train_loss=0.3795 | val_loss=0.3750 | val_mcc=0.5685 | val_f1=0.6552 | val_auroc=0.8711

[Epoch 15] train_loss=0.3746 | val_loss=0.3740 | val_mcc=0.5660 | val_f1=0.6533 | val_auroc=0.8731
[EarlyStop] epoch=15 | best_val_mcc=0.6006
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.6210 | F1=0.7145 | AUROC=0.8645 | AUPRC=0.7923
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.5596 | F1=0.7440 | AUROC=0.8472 | AUPRC=0.8639
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.3984 | F1=0.6560 | AUROC=0.7380 | AUPRC=0.7509
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5472 | F1=0.7270 | AUROC=0.8288 | AUPRC=0.8308
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.5653 | val_loss=0.3784 | val_mcc=0.5557 | val_f1=0.6204 | val_auroc=0.8309

[Epoch 02] train_loss=0.4918 | val_loss=0.4178 | val_mcc=0.5678 | val_f1=0.6502 | val_auroc=0.8457

[Epoch 03] train_loss=0.4745 | val_loss=0.4109 | val_mcc=0.5672 | val_f1=0.6518 | val_auroc=0.8517

[Epoch 04] train_loss=0.4583 | val_loss=0.3976 | val_mcc=0.5667 | val_f1=0.6519 | val_auroc=0.8561

[Epoch 05] train_loss=0.4472 | val_loss=0.3822 | val_mcc=0.5767 | val_f1=0.6598 | val_auroc=0.8619

[Epoch 06] train_loss=0.4374 | val_loss=0.3619 | val_mcc=0.5829 | val_f1=0.6633 | val_auroc=0.8654

[Epoch 07] train_loss=0.4240 | val_loss=0.3469 | val_mcc=0.5906 | val_f1=0.6671 | val_auroc=0.8677

[Epoch 08] train_loss=0.4150 | val_loss=0.4098 | val_mcc=0.5589 | val_f1=0.6480 | val_auroc=0.8728

[Epoch 09] train_loss=0.4001 | val_loss=0.3777 | val_mcc=0.5673 | val_f1=0.6545 | val_auroc=0.8753

[Epoch 10] train_loss=0.3869 | val_loss=0.3642 | val_mcc=0.5745 | val_f1=0.6597 | val_auroc=0.8747

[Epoch 11] train_loss=0.3738 | val_loss=0.3981 | val_mcc=0.5566 | val_f1=0.6461 | val_auroc=0.8764

[Epoch 12] train_loss=0.3453 | val_loss=0.3789 | val_mcc=0.5632 | val_f1=0.6513 | val_auroc=0.8760

[Epoch 13] train_loss=0.3350 | val_loss=0.3879 | val_mcc=0.5598 | val_f1=0.6487 | val_auroc=0.8749
[EarlyStop] epoch=13 | best_val_mcc=0.5906
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.6163 | F1=0.7121 | AUROC=0.8618 | AUPRC=0.7900
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.5745 | F1=0.7516 | AUROC=0.8507 | AUPRC=0.8668
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.3811 | F1=0.6522 | AUROC=0.7350 | AUPRC=0.7476
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5384 | F1=0.7230 | AUROC=0.8270 | AUPRC=0.8268
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 302.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.5921 | F1=0.7079 | AUROC=0.8855 | AUPRC=0.7993
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.5625 | F1=0.7722 | AUROC=0.8660 | AUPRC=0.8747
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3806 | F1=0.6826 | AUROC=0.7544 | AUPRC=0.7552
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5552 | F1=0.7587 | AUROC=0.8464 | AUPRC=0.8395
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 314.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.6003 | F1=0.7118 | AUROC=0.8820 | AUPRC=0.8043
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5466 | F1=0.7590 | AUROC=0.8577 | AUPRC=0.8688
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3964 | F1=0.6839 | AUROC=0.7525 | AUPRC=0.7521
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5442 | F1=0.7466 | AUROC=0.8401 | AUPRC=0.8318
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 281.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.5784 | F1=0.6958 | AUROC=0.8636 | AUPRC=0.7878
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5325 | F1=0.7511 | AUROC=0.8384 | AUPRC=0.8581
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.3750 | F1=0.6750 | AUROC=0.7406 | AUPRC=0.7476
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5124 | F1=0.7267 | AUROC=0.8282 | AUPRC=0.8258
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 229.
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.5964 | F1=0.7090 | AUROC=0.8720 | AUPRC=0.7929
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.5226 | F1=0.7515 | AUROC=0.8481 | AUPRC=0.8631
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.3597 | F1=0.6698 | AUROC=0.7509 | AUPRC=0.7469
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...

[Epoch 01] train_loss=0.3994 | val_loss=0.2092 | val_mcc=0.7346 | val_f1=0.7864 | val_auroc=0.9588

[Epoch 02] train_loss=0.3012 | val_loss=0.2022 | val_mcc=0.7411 | val_f1=0.7918 | val_auroc=0.9618

[Epoch 03] train_loss=0.2889 | val_loss=0.1928 | val_mcc=0.7570 | val_f1=0.8041 | val_auroc=0.9634

[Epoch 04] train_loss=0.2794 | val_loss=0.1918 | val_mcc=0.7579 | val_f1=0.8051 | val_auroc=0.9645

[Epoch 05] train_loss=0.2707 | val_loss=0.2085 | val_mcc=0.7452 | val_f1=0.7947 | val_auroc=0.9648

[Epoch 06] train_loss=0.2673 | val_loss=0.2350 | val_mcc=0.7287 | val_f1=0.7794 | val_auroc=0.9647

[Epoch 07] train_loss=0.2632 | val_loss=0.2000 | val_mcc=0.7502 | val_f1=0.7991 | val_auroc=0.9645

[Epoch 08] train_loss=0.2547 | val_loss=0.2419 | val_mcc=0.7238 | val_f1=0.7749 | val_auroc=0.9645

[Epoch 09] train_loss=0.2482 | val_loss=0.1977 | val_mcc=0.7560 | val_f1=0.8037 | val_auroc=0.9651

[Epoch 10] train_loss=0.2451 | val_loss=0.2206 | val_mcc=0.7422 | val_f1=0.7912 | val_auroc=0.9650
[EarlyStop] epoch=10 | best_val_mcc=0.7579
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7718 | F1=0.8346 | AUROC=0.9531 | AUPRC=0.9055
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8147 | F1=0.8977 | AUROC=0.9710 | AUPRC=0.9697
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4226 | F1=0.7142 | AUROC=0.7688 | AUPRC=0.7628
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5671 | F1=0.7806 | AUROC=0.8771 | AUPRC=0.8646
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4414 | val_loss=0.2220 | val_mcc=0.7232 | val_f1=0.7774 | val_auroc=0.9581

[Epoch 02] train_loss=0.3143 | val_loss=0.2546 | val_mcc=0.7119 | val_f1=0.7641 | val_auroc=0.9626

[Epoch 03] train_loss=0.2931 | val_loss=0.1878 | val_mcc=0.7624 | val_f1=0.8061 | val_auroc=0.9637

[Epoch 04] train_loss=0.2851 | val_loss=0.2058 | val_mcc=0.7491 | val_f1=0.7981 | val_auroc=0.9647

[Epoch 05] train_loss=0.2754 | val_loss=0.1909 | val_mcc=0.7562 | val_f1=0.8034 | val_auroc=0.9650

[Epoch 06] train_loss=0.2746 | val_loss=0.1958 | val_mcc=0.7543 | val_f1=0.8023 | val_auroc=0.9663

[Epoch 07] train_loss=0.2654 | val_loss=0.1935 | val_mcc=0.7531 | val_f1=0.8013 | val_auroc=0.9657

[Epoch 08] train_loss=0.2578 | val_loss=0.1947 | val_mcc=0.7527 | val_f1=0.8011 | val_auroc=0.9662

[Epoch 09] train_loss=0.2562 | val_loss=0.2317 | val_mcc=0.7384 | val_f1=0.7869 | val_auroc=0.9660
[EarlyStop] epoch=9 | best_val_mcc=0.7624
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7637 | F1=0.8254 | AUROC=0.9518 | AUPRC=0.9038
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7810 | F1=0.8724 | AUROC=0.9678 | AUPRC=0.9672
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4107 | F1=0.6970 | AUROC=0.7649 | AUPRC=0.7592
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5700 | F1=0.7806 | AUROC=0.8761 | AUPRC=0.8635
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.4220 | val_loss=0.2049 | val_mcc=0.7344 | val_f1=0.7859 | val_auroc=0.9587

[Epoch 02] train_loss=0.3104 | val_loss=0.1908 | val_mcc=0.7534 | val_f1=0.8006 | val_auroc=0.9629

[Epoch 03] train_loss=0.2903 | val_loss=0.1921 | val_mcc=0.7560 | val_f1=0.8034 | val_auroc=0.9634

[Epoch 04] train_loss=0.2868 | val_loss=0.2759 | val_mcc=0.7015 | val_f1=0.7531 | val_auroc=0.9650

[Epoch 05] train_loss=0.2764 | val_loss=0.1893 | val_mcc=0.7583 | val_f1=0.8055 | val_auroc=0.9652

[Epoch 06] train_loss=0.2738 | val_loss=0.2355 | val_mcc=0.7280 | val_f1=0.7788 | val_auroc=0.9653

[Epoch 07] train_loss=0.2645 | val_loss=0.2161 | val_mcc=0.7433 | val_f1=0.7928 | val_auroc=0.9653

[Epoch 08] train_loss=0.2575 | val_loss=0.2106 | val_mcc=0.7457 | val_f1=0.7948 | val_auroc=0.9658

[Epoch 09] train_loss=0.2514 | val_loss=0.2013 | val_mcc=0.7497 | val_f1=0.7985 | val_auroc=0.9658

[Epoch 10] train_loss=0.2460 | val_loss=0.2082 | val_mcc=0.7483 | val_f1=0.7969 | val_auroc=0.9663

[Epoch 11] train_loss=0.2420 | val_loss=0.2338 | val_mcc=0.7298 | val_f1=0.7807 | val_auroc=0.9645
[EarlyStop] epoch=11 | best_val_mcc=0.7583
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7632 | F1=0.8285 | AUROC=0.9531 | AUPRC=0.9056
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.8075 | F1=0.8956 | AUROC=0.9695 | AUPRC=0.9686
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4154 | F1=0.7132 | AUROC=0.7692 | AUPRC=0.7663
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5554 | F1=0.7752 | AUROC=0.8789 | AUPRC=0.8645
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.4030 | val_loss=0.2485 | val_mcc=0.7087 | val_f1=0.7639 | val_auroc=0.9585

[Epoch 02] train_loss=0.3002 | val_loss=0.1998 | val_mcc=0.7501 | val_f1=0.7989 | val_auroc=0.9624

[Epoch 03] train_loss=0.2864 | val_loss=0.2513 | val_mcc=0.7197 | val_f1=0.7709 | val_auroc=0.9634

[Epoch 04] train_loss=0.2769 | val_loss=0.2024 | val_mcc=0.7547 | val_f1=0.8027 | val_auroc=0.9639

[Epoch 05] train_loss=0.2711 | val_loss=0.2163 | val_mcc=0.7420 | val_f1=0.7916 | val_auroc=0.9650

[Epoch 06] train_loss=0.2658 | val_loss=0.2520 | val_mcc=0.7214 | val_f1=0.7716 | val_auroc=0.9644

[Epoch 07] train_loss=0.2606 | val_loss=0.1965 | val_mcc=0.7583 | val_f1=0.8055 | val_auroc=0.9652

[Epoch 08] train_loss=0.2526 | val_loss=0.2123 | val_mcc=0.7501 | val_f1=0.7984 | val_auroc=0.9658

[Epoch 09] train_loss=0.2464 | val_loss=0.2127 | val_mcc=0.7462 | val_f1=0.7951 | val_auroc=0.9659

[Epoch 10] train_loss=0.2372 | val_loss=0.2008 | val_mcc=0.7515 | val_f1=0.8001 | val_auroc=0.9658

[Epoch 11] train_loss=0.2299 | val_loss=0.2254 | val_mcc=0.7361 | val_f1=0.7864 | val_auroc=0.9647

[Epoch 12] train_loss=0.2162 | val_loss=0.2034 | val_mcc=0.7498 | val_f1=0.7986 | val_auroc=0.9652

[Epoch 13] train_loss=0.2100 | val_loss=0.2250 | val_mcc=0.7365 | val_f1=0.7871 | val_auroc=0.9649
[EarlyStop] epoch=13 | best_val_mcc=0.7583
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7623 | F1=0.8285 | AUROC=0.9537 | AUPRC=0.9063
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8212 | F1=0.9036 | AUROC=0.9701 | AUPRC=0.9693
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4164 | F1=0.7178 | AUROC=0.7676 | AUPRC=0.7647
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5489 | F1=0.7724 | AUROC=0.8779 | AUPRC=0.8634
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1152D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 220.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7690 | F1=0.8336 | AUROC=0.9627 | AUPRC=0.9214
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8586 | F1=0.9265 | AUROC=0.9835 | AUPRC=0.9836
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.4311 | F1=0.7327 | AUROC=0.7805 | AUPRC=0.7693
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5390 | F1=0.7679 | AUROC=0.8928 | AUPRC=0.8741
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 126.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7593 | F1=0.8268 | AUROC=0.9573 | AUPRC=0.9127
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8219 | F1=0.9069 | AUROC=0.9733 | AUPRC=0.9739
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.3939 | F1=0.7144 | AUROC=0.7731 | AUPRC=0.7670
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5563 | F1=0.7757 | AUROC=0.8838 | AUPRC=0.8622
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 123.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7654 | F1=0.8311 | AUROC=0.9584 | AUPRC=0.9117
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8189 | F1=0.9056 | AUROC=0.9706 | AUPRC=0.9711
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4090 | F1=0.7214 | AUROC=0.7721 | AUPRC=0.7619
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5433 | F1=0.7698 | AUROC=0.8868 | AUPRC=0.8718
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 157.
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7622 | F1=0.8288 | AUROC=0.9572 | AUPRC=0.9123
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_spliceai_nt_v2_500m_esmc_600m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8240 | F1=0.9094 | AUROC=0.9692 | AUPRC=0.9708
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core', 'spliceai']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.


[Epoch 01] train_loss=0.4014 | val_loss=0.2257 | val_mcc=0.7295 | val_f1=0.7825 | val_auroc=0.9573

[Epoch 02] train_loss=0.2907 | val_loss=0.2646 | val_mcc=0.7121 | val_f1=0.7651 | val_auroc=0.9591

[Epoch 03] train_loss=0.2655 | val_loss=0.2117 | val_mcc=0.7478 | val_f1=0.7971 | val_auroc=0.9613

[Epoch 04] train_loss=0.2405 | val_loss=0.2016 | val_mcc=0.7527 | val_f1=0.8010 | val_auroc=0.9627

[Epoch 05] train_loss=0.2164 | val_loss=0.2282 | val_mcc=0.7391 | val_f1=0.7897 | val_auroc=0.9606

[Epoch 06] train_loss=0.1923 | val_loss=0.2153 | val_mcc=0.7522 | val_f1=0.8007 | val_auroc=0.9610

[Epoch 07] train_loss=0.1620 | val_loss=0.2310 | val_mcc=0.7227 | val_f1=0.7769 | val_auroc=0.9557

[Epoch 08] train_loss=0.1346 | val_loss=0.2889 | val_mcc=0.6990 | val_f1=0.7570 | val_auroc=0.9522

[Epoch 09] train_loss=0.0960 | val_loss=0.2820 | val_mcc=0.7210 | val_f1=0.7751 | val_auroc=0.9554

[Epoch 10] train_loss=0.0778 | val_loss=0.3002 | val_mcc=0.7144 | val_f1=0.7696 | val_auroc=0.9534
[EarlyStop] epoch=10 | best_val_mcc=0.7527
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7645 | F1=0.8299 | AUROC=0.9576 | AUPRC=0.9044
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8054 | F1=0.8936 | AUROC=0.9717 | AUPRC=0.9731
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4231 | F1=0.7179 | AUROC=0.7662 | AUPRC=0.7417
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5336 | F1=0.7651 | AUROC=0.8786 | AUPRC=0.8544
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.3997 | val_loss=0.2194 | val_mcc=0.7398 | val_f1=0.7908 | val_auroc=0.9596

[Epoch 02] train_loss=0.2959 | val_loss=0.2364 | val_mcc=0.7323 | val_f1=0.7830 | val_auroc=0.9629

[Epoch 03] train_loss=0.2711 | val_loss=0.2028 | val_mcc=0.7493 | val_f1=0.7980 | val_auroc=0.9615

[Epoch 04] train_loss=0.2442 | val_loss=0.1997 | val_mcc=0.7625 | val_f1=0.8088 | val_auroc=0.9644

[Epoch 05] train_loss=0.2187 | val_loss=0.2353 | val_mcc=0.7358 | val_f1=0.7854 | val_auroc=0.9638

[Epoch 06] train_loss=0.1885 | val_loss=0.2212 | val_mcc=0.7373 | val_f1=0.7883 | val_auroc=0.9575

[Epoch 07] train_loss=0.1577 | val_loss=0.3317 | val_mcc=0.6910 | val_f1=0.7481 | val_auroc=0.9524

[Epoch 08] train_loss=0.1218 | val_loss=0.3429 | val_mcc=0.6887 | val_f1=0.7479 | val_auroc=0.9465

[Epoch 09] train_loss=0.0847 | val_loss=0.3275 | val_mcc=0.7080 | val_f1=0.7654 | val_auroc=0.9471

[Epoch 10] train_loss=0.0638 | val_loss=0.3851 | val_mcc=0.6891 | val_f1=0.7490 | val_auroc=0.9467
[EarlyStop] epoch=10 | best_val_mcc=0.7625
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7693 | F1=0.8336 | AUROC=0.9583 | AUPRC=0.9040
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.8120 | F1=0.8996 | AUROC=0.9739 | AUPRC=0.9750
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4252 | F1=0.7213 | AUROC=0.7665 | AUPRC=0.7399
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5372 | F1=0.7671 | AUROC=0.8748 | AUPRC=0.8470
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3975 | val_loss=0.2078 | val_mcc=0.7351 | val_f1=0.7837 | val_auroc=0.9565

[Epoch 02] train_loss=0.2970 | val_loss=0.2036 | val_mcc=0.7456 | val_f1=0.7948 | val_auroc=0.9604

[Epoch 03] train_loss=0.2678 | val_loss=0.2000 | val_mcc=0.7549 | val_f1=0.8027 | val_auroc=0.9628

[Epoch 04] train_loss=0.2430 | val_loss=0.1920 | val_mcc=0.7459 | val_f1=0.7910 | val_auroc=0.9628

[Epoch 05] train_loss=0.2200 | val_loss=0.2097 | val_mcc=0.7501 | val_f1=0.7989 | val_auroc=0.9636

[Epoch 06] train_loss=0.1865 | val_loss=0.2258 | val_mcc=0.7398 | val_f1=0.7907 | val_auroc=0.9573

[Epoch 07] train_loss=0.1564 | val_loss=0.2466 | val_mcc=0.7248 | val_f1=0.7788 | val_auroc=0.9553

[Epoch 08] train_loss=0.1103 | val_loss=0.2741 | val_mcc=0.7209 | val_f1=0.7756 | val_auroc=0.9527

[Epoch 09] train_loss=0.0875 | val_loss=0.3130 | val_mcc=0.7074 | val_f1=0.7649 | val_auroc=0.9482
[EarlyStop] epoch=9 | best_val_mcc=0.7549
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7604 | F1=0.8266 | AUROC=0.9575 | AUPRC=0.9019
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7996 | F1=0.8906 | AUROC=0.9692 | AUPRC=0.9697
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4231 | F1=0.7179 | AUROC=0.7718 | AUPRC=0.7514
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5693 | F1=0.7813 | AUROC=0.8800 | AUPRC=0.8576
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3897 | val_loss=0.2257 | val_mcc=0.7216 | val_f1=0.7762 | val_auroc=0.9570

[Epoch 02] train_loss=0.2851 | val_loss=0.2113 | val_mcc=0.7470 | val_f1=0.7965 | val_auroc=0.9610

[Epoch 03] train_loss=0.2593 | val_loss=0.2109 | val_mcc=0.7488 | val_f1=0.7978 | val_auroc=0.9622

[Epoch 04] train_loss=0.2355 | val_loss=0.2098 | val_mcc=0.7510 | val_f1=0.7996 | val_auroc=0.9626

[Epoch 05] train_loss=0.2041 | val_loss=0.2466 | val_mcc=0.7298 | val_f1=0.7799 | val_auroc=0.9619

[Epoch 06] train_loss=0.1731 | val_loss=0.2505 | val_mcc=0.7278 | val_f1=0.7797 | val_auroc=0.9593

[Epoch 07] train_loss=0.1353 | val_loss=0.2554 | val_mcc=0.7277 | val_f1=0.7810 | val_auroc=0.9550

[Epoch 08] train_loss=0.1061 | val_loss=0.2976 | val_mcc=0.7143 | val_f1=0.7694 | val_auroc=0.9540

[Epoch 09] train_loss=0.0685 | val_loss=0.3151 | val_mcc=0.7105 | val_f1=0.7663 | val_auroc=0.9523

[Epoch 10] train_loss=0.0522 | val_loss=0.3399 | val_mcc=0.7049 | val_f1=0.7611 | val_auroc=0.9528
[EarlyStop] epoch=10 | best_val_mcc=0.7510
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7643 | F1=0.8302 | AUROC=0.9572 | AUPRC=0.9051
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.7999 | F1=0.8942 | AUROC=0.9697 | AUPRC=0.9707
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4174 | F1=0.7210 | AUROC=0.7615 | AUPRC=0.7319
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5689 | F1=0.7814 | AUROC=0.8835 | AUPRC=0.8599
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1280D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 173.
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7583 | F1=0.8261 | AUROC=0.9625 | AUPRC=0.9110
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8539 | F1=0.9226 | AUROC=0.9825 | AUPRC=0.9820
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3914 | F1=0.7142 | AUROC=0.7594 | AUPRC=0.7288
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5340 | F1=0.7656 | AUROC=0.8882 | AUPRC=0.8581
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 121.
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7617 | F1=0.8285 | AUROC=0.9579 | AUPRC=0.9078
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8360 | F1=0.9145 | AUROC=0.9756 | AUPRC=0.9761
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4243 | F1=0.7262 | AUROC=0.7599 | AUPRC=0.7329
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5390 | F1=0.7679 | AUROC=0.8825 | AUPRC=0.8515
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 111.
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7604 | F1=0.8275 | AUROC=0.9574 | AUPRC=0.9024
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8335 | F1=0.9126 | AUROC=0.9752 | AUPRC=0.9766
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4283 | F1=0.7270 | AUROC=0.7734 | AUPRC=0.7539
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5372 | F1=0.7672 | AUROC=0.8815 | AUPRC=0.8563
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 118.
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7585 | F1=0.8262 | AUROC=0.9564 | AUPRC=0.9010
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8308 | F1=0.9110 | AUROC=0.9737 | AUPRC=0.9745
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v1_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4236 | F1=0.7273 | AUROC=0.7681 | AUPRC=0.7472
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']

[Epoch 01] train_loss=0.3930 | val_loss=0.2303 | val_mcc=0.7298 | val_f1=0.7823 | val_auroc=0.9578

[Epoch 02] train_loss=0.2923 | val_loss=0.2232 | val_mcc=0.7329 | val_f1=0.7852 | val_auroc=0.9559

[Epoch 03] train_loss=0.2708 | val_loss=0.2148 | val_mcc=0.7447 | val_f1=0.7939 | val_auroc=0.9634

[Epoch 04] train_loss=0.2500 | val_loss=0.2085 | val_mcc=0.7467 | val_f1=0.7962 | val_auroc=0.9619

[Epoch 05] train_loss=0.2336 | val_loss=0.2313 | val_mcc=0.7365 | val_f1=0.7865 | val_auroc=0.9634

[Epoch 06] train_loss=0.2123 | val_loss=0.2115 | val_mcc=0.7481 | val_f1=0.7972 | val_auroc=0.9636

[Epoch 07] train_loss=0.1930 | val_loss=0.2151 | val_mcc=0.7505 | val_f1=0.7993 | val_auroc=0.9620

[Epoch 08] train_loss=0.1747 | val_loss=0.2406 | val_mcc=0.7409 | val_f1=0.7906 | val_auroc=0.9625

[Epoch 09] train_loss=0.1554 | val_loss=0.2399 | val_mcc=0.7316 | val_f1=0.7843 | val_auroc=0.9575

[Epoch 10] train_loss=0.1357 | val_loss=0.2374 | val_mcc=0.7329 | val_f1=0.7838 | val_auroc=0.9570

[Epoch 11] train_loss=0.1203 | val_loss=0.2889 | val_mcc=0.7181 | val_f1=0.7731 | val_auroc=0.9534

[Epoch 12] train_loss=0.0970 | val_loss=0.2675 | val_mcc=0.7235 | val_f1=0.7774 | val_auroc=0.9553

[Epoch 13] train_loss=0.0863 | val_loss=0.3097 | val_mcc=0.7227 | val_f1=0.7766 | val_auroc=0.9549
[EarlyStop] epoch=13 | best_val_mcc=0.7505
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7575 | F1=0.8246 | AUROC=0.9561 | AUPRC=0.8992
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.8120 | F1=0.8996 | AUROC=0.9709 | AUPRC=0.9682
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4430 | F1=0.7289 | AUROC=0.7726 | AUPRC=0.7455
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5833 | F1=0.7873 | AUROC=0.8863 | AUPRC=0.8581
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4028 | val_loss=0.2620 | val_mcc=0.7012 | val_f1=0.7570 | val_auroc=0.9570

[Epoch 02] train_loss=0.3036 | val_loss=0.2816 | val_mcc=0.6965 | val_f1=0.7503 | val_auroc=0.9599

[Epoch 03] train_loss=0.2780 | val_loss=0.1956 | val_mcc=0.7598 | val_f1=0.8062 | val_auroc=0.9628

[Epoch 04] train_loss=0.2564 | val_loss=0.2381 | val_mcc=0.7353 | val_f1=0.7848 | val_auroc=0.9640

[Epoch 05] train_loss=0.2355 | val_loss=0.2532 | val_mcc=0.7255 | val_f1=0.7760 | val_auroc=0.9637

[Epoch 06] train_loss=0.2171 | val_loss=0.2509 | val_mcc=0.7296 | val_f1=0.7809 | val_auroc=0.9618

[Epoch 07] train_loss=0.1986 | val_loss=0.3599 | val_mcc=0.6708 | val_f1=0.7259 | val_auroc=0.9585

[Epoch 08] train_loss=0.1710 | val_loss=0.2750 | val_mcc=0.7245 | val_f1=0.7770 | val_auroc=0.9591

[Epoch 09] train_loss=0.1537 | val_loss=0.3206 | val_mcc=0.7032 | val_f1=0.7597 | val_auroc=0.9546
[EarlyStop] epoch=9 | best_val_mcc=0.7598
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7713 | F1=0.8335 | AUROC=0.9577 | AUPRC=0.9030
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7915 | F1=0.8824 | AUROC=0.9732 | AUPRC=0.9727
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4255 | F1=0.7148 | AUROC=0.7684 | AUPRC=0.7417
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5625 | F1=0.7777 | AUROC=0.8831 | AUPRC=0.8650
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3971 | val_loss=0.2241 | val_mcc=0.7230 | val_f1=0.7764 | val_auroc=0.9515

[Epoch 02] train_loss=0.2993 | val_loss=0.2522 | val_mcc=0.7191 | val_f1=0.7718 | val_auroc=0.9604

[Epoch 03] train_loss=0.2760 | val_loss=0.2109 | val_mcc=0.7472 | val_f1=0.7966 | val_auroc=0.9615

[Epoch 04] train_loss=0.2562 | val_loss=0.2050 | val_mcc=0.7510 | val_f1=0.7987 | val_auroc=0.9596

[Epoch 05] train_loss=0.2367 | val_loss=0.2144 | val_mcc=0.7497 | val_f1=0.7987 | val_auroc=0.9608

[Epoch 06] train_loss=0.2156 | val_loss=0.2093 | val_mcc=0.7548 | val_f1=0.8027 | val_auroc=0.9615

[Epoch 07] train_loss=0.1928 | val_loss=0.2255 | val_mcc=0.7476 | val_f1=0.7969 | val_auroc=0.9590

[Epoch 08] train_loss=0.1716 | val_loss=0.2353 | val_mcc=0.7399 | val_f1=0.7905 | val_auroc=0.9560

[Epoch 09] train_loss=0.1508 | val_loss=0.2397 | val_mcc=0.7372 | val_f1=0.7887 | val_auroc=0.9574

[Epoch 10] train_loss=0.1307 | val_loss=0.2671 | val_mcc=0.7262 | val_f1=0.7798 | val_auroc=0.9552

[Epoch 11] train_loss=0.1047 | val_loss=0.3244 | val_mcc=0.7155 | val_f1=0.7707 | val_auroc=0.9531

[Epoch 12] train_loss=0.0899 | val_loss=0.3400 | val_mcc=0.7087 | val_f1=0.7658 | val_auroc=0.9494
[EarlyStop] epoch=12 | best_val_mcc=0.7548
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7595 | F1=0.8262 | AUROC=0.9570 | AUPRC=0.9018
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7987 | F1=0.8912 | AUROC=0.9710 | AUPRC=0.9680
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4293 | F1=0.7217 | AUROC=0.7726 | AUPRC=0.7392
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5808 | F1=0.7856 | AUROC=0.8873 | AUPRC=0.8605
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3870 | val_loss=0.2281 | val_mcc=0.7295 | val_f1=0.7824 | val_auroc=0.9570

[Epoch 02] train_loss=0.2917 | val_loss=0.2074 | val_mcc=0.7528 | val_f1=0.8010 | val_auroc=0.9599

[Epoch 03] train_loss=0.2734 | val_loss=0.1968 | val_mcc=0.7575 | val_f1=0.8045 | val_auroc=0.9628

[Epoch 04] train_loss=0.2523 | val_loss=0.2016 | val_mcc=0.7617 | val_f1=0.8081 | val_auroc=0.9650

[Epoch 05] train_loss=0.2362 | val_loss=0.1952 | val_mcc=0.7564 | val_f1=0.8037 | val_auroc=0.9636

[Epoch 06] train_loss=0.2133 | val_loss=0.2201 | val_mcc=0.7451 | val_f1=0.7943 | val_auroc=0.9646

[Epoch 07] train_loss=0.1910 | val_loss=0.2142 | val_mcc=0.7564 | val_f1=0.8037 | val_auroc=0.9645

[Epoch 08] train_loss=0.1713 | val_loss=0.2275 | val_mcc=0.7440 | val_f1=0.7939 | val_auroc=0.9616

[Epoch 09] train_loss=0.1381 | val_loss=0.2425 | val_mcc=0.7388 | val_f1=0.7898 | val_auroc=0.9607

[Epoch 10] train_loss=0.1225 | val_loss=0.2527 | val_mcc=0.7367 | val_f1=0.7881 | val_auroc=0.9591
[EarlyStop] epoch=10 | best_val_mcc=0.7617
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7644 | F1=0.8303 | AUROC=0.9593 | AUPRC=0.9078
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8402 | F1=0.9148 | AUROC=0.9754 | AUPRC=0.9757
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4385 | F1=0.7310 | AUROC=0.7680 | AUPRC=0.7364
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5457 | F1=0.7710 | AUROC=0.8857 | AUPRC=0.8615
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1536D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 184.
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7664 | F1=0.8318 | AUROC=0.9630 | AUPRC=0.9131
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8385 | F1=0.9163 | AUROC=0.9803 | AUPRC=0.9802
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3966 | F1=0.7177 | AUROC=0.7583 | AUPRC=0.7313
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5330 | F1=0.7651 | AUROC=0.8890 | AUPRC=0.8600
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 163.
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7703 | F1=0.8346 | AUROC=0.9595 | AUPRC=0.9108
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8533 | F1=0.9231 | AUROC=0.9758 | AUPRC=0.9770
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4405 | F1=0.7356 | AUROC=0.7722 | AUPRC=0.7516
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5669 | F1=0.7804 | AUROC=0.8900 | AUPRC=0.8723
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 118.
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7607 | F1=0.8277 | AUROC=0.9577 | AUPRC=0.9038
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8128 | F1=0.9032 | AUROC=0.9714 | AUPRC=0.9709
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4153 | F1=0.7220 | AUROC=0.7650 | AUPRC=0.7444
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5554 | F1=0.7753 | AUROC=0.8895 | AUPRC=0.8631
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 85.
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7623 | F1=0.8289 | AUROC=0.9573 | AUPRC=0.9055
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8276 | F1=0.9099 | AUROC=0.9734 | AUPRC=0.9744
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v3_650m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4203 | F1=0.7277 | AUROC=0.7669 | AUPRC=0.7425
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']

[Epoch 01] train_loss=0.3880 | val_loss=0.2172 | val_mcc=0.7384 | val_f1=0.7897 | val_auroc=0.9574

[Epoch 02] train_loss=0.2946 | val_loss=0.2099 | val_mcc=0.7453 | val_f1=0.7951 | val_auroc=0.9603

[Epoch 03] train_loss=0.2717 | val_loss=0.2155 | val_mcc=0.7473 | val_f1=0.7965 | val_auroc=0.9623

[Epoch 04] train_loss=0.2523 | val_loss=0.2187 | val_mcc=0.7467 | val_f1=0.7958 | val_auroc=0.9632

[Epoch 05] train_loss=0.2346 | val_loss=0.2284 | val_mcc=0.7454 | val_f1=0.7942 | val_auroc=0.9629

[Epoch 06] train_loss=0.2120 | val_loss=0.2344 | val_mcc=0.7410 | val_f1=0.7905 | val_auroc=0.9628

[Epoch 07] train_loss=0.1966 | val_loss=0.2349 | val_mcc=0.7342 | val_f1=0.7858 | val_auroc=0.9616

[Epoch 08] train_loss=0.1665 | val_loss=0.2507 | val_mcc=0.7317 | val_f1=0.7827 | val_auroc=0.9625

[Epoch 09] train_loss=0.1547 | val_loss=0.2278 | val_mcc=0.7492 | val_f1=0.7983 | val_auroc=0.9628

[Epoch 10] train_loss=0.1427 | val_loss=0.2299 | val_mcc=0.7411 | val_f1=0.7918 | val_auroc=0.9616

[Epoch 11] train_loss=0.1292 | val_loss=0.2790 | val_mcc=0.7277 | val_f1=0.7798 | val_auroc=0.9598

[Epoch 12] train_loss=0.1183 | val_loss=0.2978 | val_mcc=0.7136 | val_f1=0.7681 | val_auroc=0.9582

[Epoch 13] train_loss=0.1079 | val_loss=0.2585 | val_mcc=0.7315 | val_f1=0.7841 | val_auroc=0.9582

[Epoch 14] train_loss=0.0961 | val_loss=0.2753 | val_mcc=0.7298 | val_f1=0.7826 | val_auroc=0.9585

[Epoch 15] train_loss=0.0881 | val_loss=0.2940 | val_mcc=0.7203 | val_f1=0.7745 | val_auroc=0.9584
[EarlyStop] epoch=15 | best_val_mcc=0.7492
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_Test | MCC=0.7528 | F1=0.8218 | AUROC=0.9560 | AUPRC=0.8975
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ClinVarHQ | MCC=0.7983 | F1=0.8916 | AUROC=0.9714 | AUPRC=0.9686
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_UniProt | MCC=0.4368 | F1=0.7297 | AUROC=0.7663 | AUPRC=0.7363
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Concat | test=Train3Val_ProteinGym | MCC=0.5678 | F1=0.7805 | AUROC=0.8802 | AUPRC=0.8467
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test

[Epoch 01] train_loss=0.4005 | val_loss=0.2533 | val_mcc=0.7171 | val_f1=0.7703 | val_auroc=0.9592

[Epoch 02] train_loss=0.2993 | val_loss=0.1996 | val_mcc=0.7456 | val_f1=0.7949 | val_auroc=0.9613

[Epoch 03] train_loss=0.2791 | val_loss=0.2549 | val_mcc=0.7211 | val_f1=0.7723 | val_auroc=0.9634

[Epoch 04] train_loss=0.2547 | val_loss=0.1927 | val_mcc=0.7540 | val_f1=0.7973 | val_auroc=0.9631

[Epoch 05] train_loss=0.2368 | val_loss=0.1916 | val_mcc=0.7568 | val_f1=0.8026 | val_auroc=0.9636

[Epoch 06] train_loss=0.2170 | val_loss=0.2248 | val_mcc=0.7427 | val_f1=0.7927 | val_auroc=0.9619

[Epoch 07] train_loss=0.1988 | val_loss=0.2434 | val_mcc=0.7259 | val_f1=0.7796 | val_auroc=0.9576

[Epoch 08] train_loss=0.1748 | val_loss=0.2427 | val_mcc=0.7406 | val_f1=0.7914 | val_auroc=0.9588

[Epoch 09] train_loss=0.1589 | val_loss=0.2754 | val_mcc=0.7330 | val_f1=0.7843 | val_auroc=0.9588

[Epoch 10] train_loss=0.1263 | val_loss=0.2823 | val_mcc=0.7260 | val_f1=0.7796 | val_auroc=0.9551

[Epoch 11] train_loss=0.1165 | val_loss=0.3271 | val_mcc=0.7137 | val_f1=0.7689 | val_auroc=0.9535
[EarlyStop] epoch=11 | best_val_mcc=0.7568
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_Test | MCC=0.7609 | F1=0.8239 | AUROC=0.9561 | AUPRC=0.8932
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ClinVarHQ | MCC=0.7720 | F1=0.8679 | AUROC=0.9725 | AUPRC=0.9711
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_UniProt | MCC=0.4089 | F1=0.6992 | AUROC=0.7656 | AUPRC=0.7318
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_CrossAttn | test=Train3Val_ProteinGym | MCC=0.5882 | F1=0.7877 | AUROC=0.8790 | AUPRC=0.8468
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test

[Epoch 01] train_loss=0.3897 | val_loss=0.2111 | val_mcc=0.7397 | val_f1=0.7903 | val_auroc=0.9576

[Epoch 02] train_loss=0.2969 | val_loss=0.2144 | val_mcc=0.7411 | val_f1=0.7918 | val_auroc=0.9594

[Epoch 03] train_loss=0.2728 | val_loss=0.2010 | val_mcc=0.7563 | val_f1=0.8035 | val_auroc=0.9615

[Epoch 04] train_loss=0.2599 | val_loss=0.2356 | val_mcc=0.7364 | val_f1=0.7861 | val_auroc=0.9645

[Epoch 05] train_loss=0.2330 | val_loss=0.2122 | val_mcc=0.7519 | val_f1=0.8002 | val_auroc=0.9638

[Epoch 06] train_loss=0.2115 | val_loss=0.2088 | val_mcc=0.7473 | val_f1=0.7964 | val_auroc=0.9613

[Epoch 07] train_loss=0.1927 | val_loss=0.2312 | val_mcc=0.7432 | val_f1=0.7935 | val_auroc=0.9601

[Epoch 08] train_loss=0.1593 | val_loss=0.2421 | val_mcc=0.7310 | val_f1=0.7837 | val_auroc=0.9576

[Epoch 09] train_loss=0.1414 | val_loss=0.2659 | val_mcc=0.7239 | val_f1=0.7781 | val_auroc=0.9555
[EarlyStop] epoch=9 | best_val_mcc=0.7563
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_Test | MCC=0.7618 | F1=0.8265 | AUROC=0.9561 | AUPRC=0.8977
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ClinVarHQ | MCC=0.7788 | F1=0.8769 | AUROC=0.9669 | AUPRC=0.9660
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_UniProt | MCC=0.4150 | F1=0.7098 | AUROC=0.7716 | AUPRC=0.7470
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Transformer | test=Train3Val_ProteinGym | MCC=0.5810 | F1=0.7859 | AUROC=0.8841 | AUPRC=0.8612
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test

[Epoch 01] train_loss=0.3874 | val_loss=0.2196 | val_mcc=0.7336 | val_f1=0.7858 | val_auroc=0.9564

[Epoch 02] train_loss=0.2942 | val_loss=0.2204 | val_mcc=0.7330 | val_f1=0.7850 | val_auroc=0.9604

[Epoch 03] train_loss=0.2683 | val_loss=0.2058 | val_mcc=0.7539 | val_f1=0.8019 | val_auroc=0.9630

[Epoch 04] train_loss=0.2493 | val_loss=0.2037 | val_mcc=0.7599 | val_f1=0.8068 | val_auroc=0.9631

[Epoch 05] train_loss=0.2296 | val_loss=0.2369 | val_mcc=0.7408 | val_f1=0.7893 | val_auroc=0.9642

[Epoch 06] train_loss=0.2103 | val_loss=0.2276 | val_mcc=0.7409 | val_f1=0.7904 | val_auroc=0.9639

[Epoch 07] train_loss=0.1878 | val_loss=0.2268 | val_mcc=0.7487 | val_f1=0.7975 | val_auroc=0.9622

[Epoch 08] train_loss=0.1624 | val_loss=0.2672 | val_mcc=0.7292 | val_f1=0.7806 | val_auroc=0.9589

[Epoch 09] train_loss=0.1347 | val_loss=0.2489 | val_mcc=0.7358 | val_f1=0.7874 | val_auroc=0.9596

[Epoch 10] train_loss=0.1194 | val_loss=0.2607 | val_mcc=0.7371 | val_f1=0.7882 | val_auroc=0.9596
[EarlyStop] epoch=10 | best_val_mcc=0.7599
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_Test | MCC=0.7648 | F1=0.8303 | AUROC=0.9570 | AUPRC=0.9011
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ClinVarHQ | MCC=0.8124 | F1=0.8992 | AUROC=0.9724 | AUPRC=0.9726
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_UniProt | MCC=0.4361 | F1=0.7278 | AUROC=0.7665 | AUPRC=0.7336
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym
[*] Reuse trained PyTorch checkpoint from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_PyTorch_Gating | test=Train3Val_ProteinGym | MCC=0.5531 | F1=0.7741 | AUROC=0.8814 | AUPRC=0.8576
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test
[*] PCA (DNA): Nén từ 1024D xuống 256D...
[*] PCA (Protein): Nén từ 1280D xuống 256D...
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 204.
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_Test | MCC=0.7713 | F1=0.8353 | AUROC=0.9620 | AUPRC=0.9115
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ClinVarHQ | MCC=0.8591 | F1=0.9260 | AUROC=0.9822 | AUPRC=0.9823
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_UniProt | MCC=0.3942 | F1=0.7152 | AUROC=0.7588 | AUPRC=0.7306
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym
[*] Reuse trained XGBoost-Pure artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Pure_XGBoost_Concat | test=Train3Val_ProteinGym | MCC=0.5519 | F1=0.7733 | AUROC=0.8928 | AUPRC=0.8723
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 179.
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_Test | MCC=0.7603 | F1=0.8275 | AUROC=0.9579 | AUPRC=0.9068
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8392 | F1=0.9156 | AUROC=0.9758 | AUPRC=0.9773
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_UniProt | MCC=0.4291 | F1=0.7289 | AUROC=0.7640 | AUPRC=0.7383
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Concat_XGBoost | test=Train3Val_ProteinGym | MCC=0.5511 | F1=0.7732 | AUROC=0.8866 | AUPRC=0.8527
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 142.
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_Test | MCC=0.7518 | F1=0.8215 | AUROC=0.9565 | AUPRC=0.9045
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8191 | F1=0.9053 | AUROC=0.9730 | AUPRC=0.9723
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_UniProt | MCC=0.4439 | F1=0.7353 | AUROC=0.7686 | AUPRC=0.7423
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1472 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_CrossAttn_XGBoost | test=Train3Val_ProteinGym | MCC=0.5366 | F1=0.7669 | AUROC=0.8892 | AUPRC=0.8698
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 6095 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test
[*] Đang khởi tạo XGBoost...
[+] Huấn luyện xong! Dừng ở cây thứ 140.
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_Test | MCC=0.7560 | F1=0.8244 | AUROC=0.9573 | AUPRC=0.9076
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 703 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_ClinVarHQ | MCC=0.8385 | F1=0.9163 | AUROC=0.9738 | AUPRC=0.9747
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 13701 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 1333 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Running config=train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt
[*] Reuse trained Hybrid artifacts from shared train/val cache
[Test] train3__val_mean_bio_core_dna_prot_nt_v2_500m_esm1v_650m_Hybrid_Transformer_XGBoost | test=Train3Val_UniProt | MCC=0.4302 | F1=0.7312 | AUROC=0.7698 | AUPRC=0.7342
[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']
  -> Đang nạp và tiền xử lý DNA Embeddings...
  -> Đang nạp và tiền xử lý Protein Embeddings...
[+] Dataset sẵn sàng: 23208 mẫu. Đã tối ưu hóa RAM & CPU 100%.

[*] Đang nạp dữ liệu bảng (Backbone). Active Mods: ['dna', 'prot', 'bio_core']

,Dataset,Pooling,Ablation,DNA_Model,Prot_Model,Network,Accuracy,Precision,Recall,Specificity,F1_Score,MCC,AUROC,AUPRC,Source
0,Train3Val_ClinVarHQ,mean,bio_core_dna_prot_spliceai,nt_v2_500m,esm1b_650m,Pure_XGBoost_Concat,0.9502,0.9672,0.9310,0.9690,0.9488,0.9010,0.9879,0.9890,OURS
1,Train3Val_ClinVarHQ,cls,bio_core_dna_prot_spliceai,nt_v3_650m,esm1b_650m,Pure_XGBoost_Concat,0.9431,0.9724,0.9109,0.9746,0.9407,0.8879,0.9863,0.9877,OURS
2,Train3Val_ClinVarHQ,cls,bio_core_dna_prot_spliceai,nt_v2_500m,esm1b_650m,Pure_XGBoost_Concat,0.9417,0.9723,0.9080,0.9746,0.9391,0.8852,0.9859,0.9867,OURS
3,Train3Val_ClinVarHQ,mean,bio_core_dna_prot_spliceai,nt_v3_650m,esm2_650m,Pure_XGBoost_Concat,0.9403,0.9665,0.9109,0.9690,0.9379,0.8819,0.9855,0.9853,OURS
4,Train3Val_ClinVarHQ,cls,bio_core_prot_spliceai,NaN,esm2_650m,Pure_XGBoost_Concat,0.9374,0.9663,0.9052,0.9690,0.9347,0.8765,0.9861,0.9862,OURS
5,Train3Val_ClinVarHQ,mean,bio_core_dna_prot_spliceai,nt_v3_650m,esm1b_650m,Pure_XGBoost_Concat,0.9374,0.9606,0.9109,0.9634,0.9351,0.8759,0.9869,0.9875,OURS
6,Train3Val_ClinVarHQ,center,bio_core_dna_prot_spliceai,nt_v2_500m,esmc_600m,Pure_XGBoost_Concat,0.9374,0.9578,0.9138,0.9606,0.9353,0.8757,0.9844,0.9850,OURS
7,Train3Val_ClinVarHQ,mean,bio_core_dna_prot_spliceai,nt_v1_500m,esm1b_650m,Pure_XGBoost_Concat,0.9374,0.9551,0.9167,0.9577,0.9355,0.8755,0.9874,0.9883,OURS
8,Train3Val_ClinVarHQ,center,bio_core_dna_prot_spliceai,nt_v1_500m,esmc_600m,Pure_XGBoost_Concat,0.9360,0.9690,0.8994,0.9718,0.9329,0.8741,0.9840,0.9846,OURS
9,Train3Val_ClinVarHQ,cls,bio_dna_prot,nt_v2_500m,esm1b_650m,Pure_XGBoost_Concat,0.9360,0.9633,0.9052,0.9662,0.9333,0.8735,0.9867,0.9874,OURS
10,Train3Val_ClinVarHQ,center,bio_core_dna_prot_spliceai,nt_v3_650m,esmc_600m,Pure_XGBoost_Concat,0.9346,0.9660,0.8994,0.9690,0.9315,0.8711,0.9838,0.9844,OURS
11,Train3Val_ClinVarHQ,mean,bio_core_prot_spliceai,NaN,esm1b_650m,Pure_XGBoost_Concat,0.9346,0.9467,0.9195,0.9493,0.9329,0.8694,0.9854,0.9864,OURS
12,Train3Val_ClinVarHQ,center,bio_prot,NaN,esmc_600m,Pure_XGBoost_Concat,0.9331,0.9659,0.8966,0.9690,0.9300,0.8684,0.9861,0.9866,OURS
13,Train3Val_ClinVarHQ,center,bio_prot,NaN,esmc_600m,Pure_XGBoost_Concat,0.9331,0.9659,0.8966,0.9690,0.9300,0.8684,0.9861,0.9866,OURS
14,Train3Val_ClinVarHQ,center,bio_prot,NaN,esmc_600m,Pure_XGBoost_Concat,0.9331,0.9659,0.8966,0.9690,0.9300,0.8684,0.9861,0.9866,OURS
15,Train3Val_ClinVarHQ,mean,bio_core_dna_prot_spliceai,nt_v2_500m,esm1v_650m,Pure_XGBoost_Concat,0.9331,0.9602,0.9023,0.9634,0.9304,0.8677,0.9829,0.9834,OURS
16,Train3Val_ClinVarHQ,center,bio_dna_geom_prot,nt_v1_500m,esmc_600m,Pure_XGBoost_Concat,0.9331,0.9574,0.9052,0.9606,0.9306,0.8675,0.9837,0.9841,OURS
17,Train3Val_ClinVarHQ,center,bio_core_dna_prot_spliceai,nt_v3_650m,esm2_650m,Pure_XGBoost_Concat,0.9331,0.9574,0.9052,0.9606,0.9306,0.8675,0.9864,0.9853,OURS
18,Train3Val_ClinVarHQ,center,bio_core_prot_spliceai,NaN,esm1b_650m,Pure_XGBoost_Concat,0.9331,0.9493,0.9138,0.9521,0.9312,0.8668,0.9839,0.9840,OURS
19,Train3Val_ClinVarHQ,center,bio_core_dna_prot_spliceai,nt_v2_500m,esm1v_650m,Pure_XGBoost_Concat,0.9331,0.9493,0.9138,0.9521,0.9312,0.8668,0.9841,0.9851,OURS
20,Train3Val_ClinVarHQ,center,bio_geom_prot,nt_v1_500m,esmc_600m,Pure_XGBoost_Concat,0.9317,0.9601,0.8994,0.9634,0.9288,0.8650,0.9836,0.9838,OURS
21,Train3Val_ClinVarHQ,center,bio_core_prot_spliceai,NaN,esmc_600m,Pure_XGBoost_Concat,0.9317,0.9573,0.9023,0.9606,0.9290,0.8648,0.9840,0.9849,OURS
22,Train3Val_ClinVarHQ,center,bio_prot,NaN,esmc_600m,Hybrid_Concat_XGBoost,0.9317,0.9545,0.9052,0.9577,0.9292,0.8645,0.9768,0.9780,OURS
23,Train3Val_ClinVarHQ,center,bio_prot,NaN,esmc_600m,Hybrid_Concat_XGBoost,0.9317,0.9545,0.9052,0.9577,0.9292,0.8645,0.9768,0.9780,OURS
24,Train3Val_ClinVarHQ,center,bio_prot,NaN,esmc_600m,Hybrid_Concat_XGBoost,0.9317,0.9545,0.9052,0.9577,0.9292,0.8645,0.9768,0.9780,OURS
25,Train3Val_ClinVarHQ,center,bio_dna_prot,nt_v1_500m,esmc_600m,Hybrid_Concat_XGBoost,0.9317,0.9491,0.9109,0.9521,0.9296,0.8641,0.9793,0.9794,OURS
26,Train3Val_ClinVarHQ,cls,bio_core_dna_prot_spliceai,nt_v2_500m,esm2_650m,Pure_XGBoost_Concat,0.9303,0.9657,0.8908,0.9690,0.9268,0.8630,0.9829,0.9812,OURS
27,Train3Val_ClinVarHQ,cls,bio_core_dna_prot_spliceai,nt_v2_500m,esm1v_650m,Pure_XGBoost_Concat,0.9303,0.9628,0.8937,0.9662,0.9270,0.8627,0.9822,0.9815,OURS
28,Train3Val_ClinVarHQ,mean,bio_core_dna_prot_spliceai,nt_v2_500m,esm2_650m,Pure_XGBoost_Concat,0.9303,0.9628,0.8937,0.9662,0.9270,0.8627,0.9845,0.9849,OURS
29,Train3Val_ClinVarHQ,cls,bio_geom_prot,nt_v2_500m,esm1b_650m,Pure_XGBoost_Concat,0.9303,0.9600,0.8966,0.9634,0.9272,0.8623,0.9844,0.9858,OURS
30,Train3Val_ClinVarHQ,mean,bio_core_prot_spliceai,NaN,esm2_650m,Pure_XGBoost_Concat,0.9303,0.9600,0.8966,0.9634,0.9272,0.8623,0.9863,0.9863,OURS
31,Train3Val_ClinVarHQ,mean,bio_dna_prot,nt_v2_500m,esm1b_650m,Pure_XGBoost_Concat,0.9303,0.9572,0.8994,0.9606,0.9274,0.8620,0.9870,0.9875,OURS
32,Train3Val_ClinVarHQ,cls,bio_core_dna_prot_spliceai,nt_v3_650m,esmc_600m,Pure_XGBoost_Concat,0.9303,0.9572,0.8994,0.9606,0.9274,0.8620,0.9825,0.9834,OURS
33,Train3Val_ClinVarHQ,mean,bio_core_prot_spliceai,NaN,esm1v_650m,Pure_XGBoost_Concat,0.9303,0.9544,0.9023,0.9577,0.9276,0.8618,0.9832,0.9835,OURS
34,Train3Val_ClinVarHQ,center,bio_core_dna_prot_spliceai,nt_v1_500m,esm1v_650m,Pure_XGBoost_Concat,0.9303,0.9489,0.9080,0.9521,0.9280,0.8613,0.9839,0.9846,OURS
35,Train3Val_ClinVarHQ,mean,bio_prot,NaN,esm1b_650m,Pure_XGBoost_Concat,0.9303,0.9463,0.9109,0.9493,0.9283,0.8611,0.9845,0.9851,OURS
36,Train3Val_ClinVarHQ,mean,bio_prot,NaN,esm1b_650m,Pure_XGBoost_Concat,0.9303,0.9463,0.9109,0.9493,0.9283,0.8611,0.9845,0.9851,OURS
37,Train3Val_ClinVarHQ,mean,bio_prot,NaN,esm1b_650m,Pure_XGBoost_Concat,0.9303,0.9463,0.9109,0.9493,0.9283,0.8611,0.9845,0.9851,OURS
38,Train3Val_ClinVarHQ,center,bio_core_dna_prot_spliceai,nt_v3_650m,esm2_650m,Hybrid_Concat_XGBoost,0.9303,0.9463,0.9109,0.9493,0.9283,0.8611,0.9764,0.9743,OURS
39,Train3Val_ClinVarHQ,mean,bio_core_prot_spliceai,NaN,esmc_600m,Pure_XGBoost_Concat,0.9303,0.9463,0.9109,0.9493,0.9283,0.8611,0.9809,0.9810,OURS

,Dataset,Model,file_path,score_col,rankscore_col,pred_col,resolved_prob_col,resolved_prob_kind,resolved_threshold,pred_source,label_col
0,test,SIFT,D:/variant_data/test_full_seq_after_vep_final....,['SIFT_score'],"['SIFT_converted_rankscore', 'SIFT_rankscore']",['SIFT_pred'],SIFT_converted_rankscore,rankscore,0.395750,SIFT_pred,Label
1,test,SIFT4G,D:/variant_data/test_full_seq_after_vep_final....,['SIFT4G_score'],"['SIFT4G_converted_rankscore', 'SIFT4G_ranksco...",['SIFT4G_pred'],SIFT4G_converted_rankscore,rankscore,0.395750,SIFT4G_pred,Label
2,test,Polyphen2_HDIV,D:/variant_data/test_full_seq_after_vep_final....,['Polyphen2_HDIV_score'],['Polyphen2_HDIV_rankscore'],['Polyphen2_HDIV_pred'],Polyphen2_HDIV_rankscore,rankscore,0.380280,Polyphen2_HDIV_pred,Label
3,test,Polyphen2_HVAR,D:/variant_data/test_full_seq_after_vep_final....,['Polyphen2_HVAR_score'],['Polyphen2_HVAR_rankscore'],['Polyphen2_HVAR_pred'],Polyphen2_HVAR_rankscore,rankscore,0.487620,Polyphen2_HVAR_pred,Label
4,test,MutationTaster,D:/variant_data/test_full_seq_after_vep_final....,['MutationTaster_score'],['MutationTaster_rankscore'],['MutationTaster_pred'],MutationTaster_rankscore,rankscore,0.317330,MutationTaster_pred,Label
5,test,MetaSVM,D:/variant_data/test_full_seq_after_vep_final....,['MetaSVM_score'],['MetaSVM_rankscore'],['MetaSVM_pred'],MetaSVM_rankscore,rankscore,0.822570,MetaSVM_pred,Label
6,test,MetaLR,D:/variant_data/test_full_seq_after_vep_final....,['MetaLR_score'],['MetaLR_rankscore'],['MetaLR_pred'],MetaLR_rankscore,rankscore,0.811010,MetaLR_pred,Label
7,test,MetaRNN,D:/variant_data/test_full_seq_after_vep_final....,['MetaRNN_score'],['MetaRNN_rankscore'],['MetaRNN_pred'],MetaRNN_rankscore,rankscore,0.614900,MetaRNN_pred,Label
8,test,M-CAP,D:/variant_data/test_full_seq_after_vep_final....,['M-CAP_score'],['M-CAP_rankscore'],['M-CAP_pred'],M-CAP_rankscore,rankscore,0.025000,M-CAP_pred,Label
9,test,REVEL,D:/variant_data/test_full_seq_after_vep_final....,['REVEL_score'],['REVEL_rankscore'],['REVEL_pred'],REVEL_rankscore,rankscore,0.500000,REVEL_pred,Label
10,test,MutPred2,D:/variant_data/test_full_seq_after_vep_final....,['MutPred2_score'],['MutPred2_rankscore'],['MutPred2_pred'],MutPred2_rankscore,rankscore,0.500000,MutPred2_pred,Label
11,test,MVP,D:/variant_data/test_full_seq_after_vep_final....,['MVP_score'],['MVP_rankscore'],['MVP_pred'],MVP_rankscore,rankscore,0.500000,MVP_pred,Label
12,test,gMVP,D:/variant_data/test_full_seq_after_vep_final....,['gMVP_score'],['gMVP_rankscore'],['gMVP_pred'],gMVP_rankscore,rankscore,0.500000,gMVP_pred,Label
13,test,MisFit_D,D:/variant_data/test_full_seq_after_vep_final....,['MisFit_D_score'],['MisFit_D_rankscore'],"['MisFit_D_pred_lenient', 'MisFit_D_pred']",MisFit_D_rankscore,rankscore,0.450000,MisFit_D_pred_lenient,Label
14,test,MPC,D:/variant_data/test_full_seq_after_vep_final....,['MPC_score'],['MPC_rankscore'],['MPC_pred'],MPC_rankscore,rankscore,0.500000,MPC_pred,Label
15,test,PrimateAI,D:/variant_data/test_full_seq_after_vep_final....,['PrimateAI_score'],['PrimateAI_rankscore'],['PrimateAI_pred'],PrimateAI_rankscore,rankscore,0.803000,PrimateAI_pred,Label
16,test,BayesDel_addAF,D:/variant_data/test_full_seq_after_vep_final....,['BayesDel_addAF_score'],['BayesDel_addAF_rankscore'],['BayesDel_addAF_pred'],BayesDel_addAF_rankscore,rankscore,0.069265,BayesDel_addAF_pred,Label
17,test,BayesDel_noAF,D:/variant_data/test_full_seq_after_vep_final....,['BayesDel_noAF_score'],['BayesDel_noAF_rankscore'],['BayesDel_noAF_pred'],BayesDel_noAF_rankscore,rankscore,-0.057010,BayesDel_noAF_pred,Label
18,test,ClinPred,D:/variant_data/test_full_seq_after_vep_final....,['ClinPred_score'],['ClinPred_rankscore'],['ClinPred_pred'],ClinPred_rankscore,rankscore,0.500000,ClinPred_pred,Label
19,test,LIST-S2,D:/variant_data/test_full_seq_after_vep_final....,['LIST-S2_score'],['LIST-S2_rankscore'],['LIST-S2_pred'],LIST-S2_rankscore,rankscore,0.850000,LIST-S2_pred,Label
20,test,VARITY_R,D:/variant_data/test_full_seq_after_vep_final....,['VARITY_R_score'],['VARITY_R_rankscore'],['VARITY_R_pred'],VARITY_R_rankscore,rankscore,0.500000,VARITY_R_pred,Label
21,test,VARITY_ER,D:/variant_data/test_full_seq_after_vep_final....,['VARITY_ER_score'],['VARITY_ER_rankscore'],['VARITY_ER_pred'],VARITY_ER_rankscore,rankscore,0.500000,VARITY_ER_pred,Label
22,test,AlphaMissense,D:/variant_data/test_full_seq_after_vep_final....,['AlphaMissense_score'],['AlphaMissense_rankscore'],['AlphaMissense_pred'],AlphaMissense_rankscore,rankscore,0.500000,AlphaMissense_pred,Label
23,test,PHACTboost,D:/variant_data/test_full_seq_after_vep_final....,['PHACTboost_score'],['PHACTboost_rankscore'],['PHACTboost_pred'],PHACTboost_rankscore,rankscore,0.620000,PHACTboost_pred,Label
24,test,MutFormer,D:/variant_data/test_full_seq_after_vep_final....,['MutFormer_score'],['MutFormer_rankscore'],['MutFormer_pred'],MutFormer_rankscore,rankscore,0.883800,MutFormer_pred,Label
25,test,popEVE,D:/variant_data/test_full_seq_after_vep_final....,['popEVE_score'],"['popEVE_converted_rankscore', 'popEVE_ranksco...",['popEVE_pred'],popEVE_converted_rankscore,rankscore,0.500000,popEVE_pred,Label
26,test,CADD,D:/variant_data/test_full_seq_after_vep_final....,"['CADD_raw', 'CADD_phred']",['CADD_raw_rankscore'],['CADD_pred'],CADD_raw_rankscore,rankscore,0.500000,CADD_pred,Label
27,test,DANN,D:/variant_data/test_full_seq_after_vep_final....,['DANN_score'],['DANN_rankscore'],['DANN_pred'],DANN_rankscore,rankscore,0.500000,DANN_pred,Label
28,clinvarhq,SIFT,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['SIFT_score'],"['SIFT_converted_rankscore', 'SIFT_rankscore']",['SIFT_pred'],SIFT_converted_rankscore,rankscore,0.395750,SIFT_pred,Label
29,clinvarhq,SIFT4G,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['SIFT4G_score'],"['SIFT4G_converted_rankscore', 'SIFT4G_ranksco...",['SIFT4G_pred'],SIFT4G_converted_rankscore,rankscore,0.395750,SIFT4G_pred,Label
30,clinvarhq,Polyphen2_HDIV,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['Polyphen2_HDIV_score'],['Polyphen2_HDIV_rankscore'],['Polyphen2_HDIV_pred'],Polyphen2_HDIV_rankscore,rankscore,0.380280,Polyphen2_HDIV_pred,Label
31,clinvarhq,Polyphen2_HVAR,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['Polyphen2_HVAR_score'],['Polyphen2_HVAR_rankscore'],['Polyphen2_HVAR_pred'],Polyphen2_HVAR_rankscore,rankscore,0.487620,Polyphen2_HVAR_pred,Label
32,clinvarhq,MutationTaster,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MutationTaster_score'],['MutationTaster_rankscore'],['MutationTaster_pred'],MutationTaster_rankscore,rankscore,0.317330,MutationTaster_pred,Label
33,clinvarhq,MetaSVM,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MetaSVM_score'],['MetaSVM_rankscore'],['MetaSVM_pred'],MetaSVM_rankscore,rankscore,0.822570,MetaSVM_pred,Label
34,clinvarhq,MetaLR,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MetaLR_score'],['MetaLR_rankscore'],['MetaLR_pred'],MetaLR_rankscore,rankscore,0.811010,MetaLR_pred,Label
35,clinvarhq,MetaRNN,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MetaRNN_score'],['MetaRNN_rankscore'],['MetaRNN_pred'],MetaRNN_rankscore,rankscore,0.614900,MetaRNN_pred,Label
36,clinvarhq,M-CAP,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['M-CAP_score'],['M-CAP_rankscore'],['M-CAP_pred'],M-CAP_rankscore,rankscore,0.025000,M-CAP_pred,Label
37,clinvarhq,REVEL,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['REVEL_score'],['REVEL_rankscore'],['REVEL_pred'],REVEL_rankscore,rankscore,0.500000,REVEL_pred,Label
38,clinvarhq,MutPred2,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MutPred2_score'],['MutPred2_rankscore'],['MutPred2_pred'],MutPred2_rankscore,rankscore,0.500000,MutPred2_pred,Label
39,clinvarhq,MVP,D:/variant_data/clinvarhq_full_seq_after_vep_f...,['MVP_score'],['MVP_rankscore'],['MVP_pred'],MVP_rankscore,rankscore,0.500000,MVP_pred,Label

Empty DataFrame
Columns: [Dataset, file_path, column, exists, null_count]
Index: []