In [2]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\dotru\STUDIE\FPTU\AiTA_Lab\data\ver3\clinvar_raw.tsv', sep='\t')
df

C:\Users\dotru\AppData\Local\Temp\ipykernel_19108\1665182257.py:1: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'C:\Users\dotru\STUDIE\FPTU\AiTA_Lab\data\ver3\clinvar_raw.tsv', sep='\t')

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),...,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
0,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024",397704705,...,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-,SCV001451119|SCV005622007|SCV005909190,-,-
1,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024",397704705,...,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-,SCV001451119|SCV005622007|SCV005909190,-,-
2,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010",397704709,...,G,-,-,-,-,-,-,SCV000020156,-,-
3,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010",397704709,...,G,-,-,-,-,-,-,SCV000020156,-,-
4,15043,single nucleotide variant,NM_014630.3(ZNF592):c.3136G>A (p.Gly1046Arg),9640,ZNF592,HGNC:28986,Uncertain significance,0,"Jun 29, 2015",150829393,...,A,-,-,-,-,-,-,SCV000020157,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8992041,4968329,single nucleotide variant,NM_001387220.1(IKZF2):c.485A>C (p.His162Pro),22807,IKZF2,HGNC:13177,Uncertain significance,0,"Jun 30, 2006",-1,...,G,-,-,-,-,-,-,SCV007614805,-,-
8992042,4968330,Microsatellite,NM_006005.3(WFS1):c.2419AGC[1] (p.Ser808del),7466,WFS1,HGNC:12762,Uncertain significance,0,"Jun 30, 2006",-1,...,C,-,-,-,-,-,-,SCV007614806,-,-
8992043,4968330,Microsatellite,NM_006005.3(WFS1):c.2419AGC[1] (p.Ser808del),7466,WFS1,HGNC:12762,Uncertain significance,0,"Jun 30, 2006",-1,...,C,-,-,-,-,-,-,SCV007614806,-,-
8992044,4968331,single nucleotide variant,NM_001191057.4(PDE1C):c.1194C>G (p.Phe398Leu),5137,PDE1C,HGNC:8776,Likely pathogenic,1,"Jun 30, 2006",-1,...,C,-,-,-,-,-,-,SCV007614807,-,-
8992045,4968331,single nucleotide variant,NM_001191057.4(PDE1C):c.1194C>G (p.Phe398Leu),5137,PDE1C,HGNC:8776,Likely pathogenic,1,"Jun 30, 2006",-1,...,C,-,-,-,-,-,-,SCV007614807,-,-

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8992046 entries, 0 to 8992045
Data columns (total 43 columns):
 #   Column                                      Dtype
---  ------                                      -----
 0   #AlleleID                                   int64
 1   Type                                        object
 2   Name                                        object
 3   GeneID                                      int64
 4   GeneSymbol                                  object
 5   HGNC_ID                                     object
 6   ClinicalSignificance                        object
 7   ClinSigSimple                               int64
 8   LastEvaluated                               object
 9   RS# (dbSNP)                                 int64
 10  nsv/esv (dbVar)                             object
 11  RCVaccession                                object
 12  PhenotypeIDS                                object
 13  PhenotypeList                               object
 14  Origin                                      object
 15  OriginSimple                                object
 16  Assembly                                    object
 17  ChromosomeAccession                         object
 18  Chromosome                                  object
 19  Start                                       int64
 20  Stop                                        int64
 21  ReferenceAllele                             object
 22  AlternateAllele                             object
 23  Cytogenetic                                 object
 24  ReviewStatus                                object
 25  NumberSubmitters                            int64
 26  Guidelines                                  object
 27  TestedInGTR                                 object
 28  OtherIDs                                    object
 29  SubmitterCategories                         int64
 30  VariationID                                 int64
 31  PositionVCF                                 int64
 32  ReferenceAlleleVCF                          object
 33  AlternateAlleleVCF                          object
 34  SomaticClinicalImpact                       object
 35  SomaticClinicalImpactLastEvaluated          object
 36  ReviewStatusClinicalImpact                  object
 37  Oncogenicity                                object
 38  OncogenicityLastEvaluated                   object
 39  ReviewStatusOncogenicity                    object
 40  SCVsForAggregateGermlineClassification      object
 41  SCVsForAggregateSomaticClinicalImpact       object
 42  SCVsForAggregateOncogenicityClassification  object
dtypes: int64(10), object(33)
memory usage: 2.9+ GB

In [4]:
df_variant = df.drop(columns = ['RS# (dbSNP)', 'nsv/esv (dbVar)', 'RCVaccession', 'Cytogenetic', 'NumberSubmitters', 'SubmitterCategories', 'TestedInGTR', 'OtherIDs', 'SCVsForAggregateGermlineClassification', 'SCVsForAggregateSomaticClinicalImpact', 'SCVsForAggregateOncogenicityClassification'])
df_variant

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,PhenotypeIDS,...,VariationID,PositionVCF,ReferenceAlleleVCF,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity
0,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024","MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",...,2,4820844,GGAT,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-
1,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024","MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",...,2,4781213,GGAT,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-
2,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010","MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",...,3,4827360,GCTGCTGGACCTGCC,G,-,-,-,-,-,-
3,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010","MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",...,3,4787729,GCTGCTGGACCTGCC,G,-,-,-,-,-,-
4,15043,single nucleotide variant,NM_014630.3(ZNF592):c.3136G>A (p.Gly1046Arg),9640,ZNF592,HGNC:28986,Uncertain significance,0,"Jun 29, 2015","MONDO:MONDO:0033005,MedGen:C4551772,OMIM:25130...",...,4,85342440,G,A,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8992041,4968329,single nucleotide variant,NM_001387220.1(IKZF2):c.485A>C (p.His162Pro),22807,IKZF2,HGNC:13177,Uncertain significance,0,"Jun 30, 2006","MONDO:MONDO:0979234,MedGen:C6012290,OMIM:62123...",...,4857408,213049802,T,G,-,-,-,-,-,-
8992042,4968330,Microsatellite,NM_006005.3(WFS1):c.2419AGC[1] (p.Ser808del),7466,WFS1,HGNC:12762,Uncertain significance,0,"Jun 30, 2006","MONDO:MONDO:0010963,MedGen:C1833021,OMIM:60096...",...,4857409,6303939,CCAG,C,-,-,-,-,-,-
8992043,4968330,Microsatellite,NM_006005.3(WFS1):c.2419AGC[1] (p.Ser808del),7466,WFS1,HGNC:12762,Uncertain significance,0,"Jun 30, 2006","MONDO:MONDO:0010963,MedGen:C1833021,OMIM:60096...",...,4857409,6302212,CCAG,C,-,-,-,-,-,-
8992044,4968331,single nucleotide variant,NM_001191057.4(PDE1C):c.1194C>G (p.Phe398Leu),5137,PDE1C,HGNC:8776,Likely pathogenic,1,"Jun 30, 2006","MONDO:MONDO:0029137,MedGen:C4748334,OMIM:618140",...,4857410,31876803,G,C,-,-,-,-,-,-
8992045,4968331,single nucleotide variant,NM_001191057.4(PDE1C):c.1194C>G (p.Phe398Leu),5137,PDE1C,HGNC:8776,Likely pathogenic,1,"Jun 30, 2006","MONDO:MONDO:0029137,MedGen:C4748334,OMIM:618140",...,4857410,31837189,G,C,-,-,-,-,-,-

In [5]:
df_variant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8992046 entries, 0 to 8992045
Data columns (total 32 columns):
 #   Column                              Dtype
---  ------                              -----
 0   #AlleleID                           int64
 1   Type                                object
 2   Name                                object
 3   GeneID                              int64
 4   GeneSymbol                          object
 5   HGNC_ID                             object
 6   ClinicalSignificance                object
 7   ClinSigSimple                       int64
 8   LastEvaluated                       object
 9   PhenotypeIDS                        object
 10  PhenotypeList                       object
 11  Origin                              object
 12  OriginSimple                        object
 13  Assembly                            object
 14  ChromosomeAccession                 object
 15  Chromosome                          object
 16  Start                               int64
 17  Stop                                int64
 18  ReferenceAllele                     object
 19  AlternateAllele                     object
 20  ReviewStatus                        object
 21  Guidelines                          object
 22  VariationID                         int64
 23  PositionVCF                         int64
 24  ReferenceAlleleVCF                  object
 25  AlternateAlleleVCF                  object
 26  SomaticClinicalImpact               object
 27  SomaticClinicalImpactLastEvaluated  object
 28  ReviewStatusClinicalImpact          object
 29  Oncogenicity                        object
 30  OncogenicityLastEvaluated           object
 31  ReviewStatusOncogenicity            object
dtypes: int64(7), object(25)
memory usage: 2.1+ GB

In [6]:
df_variant.isnull().sum()

#AlleleID                             0
Type                                  0
Name                                  0
GeneID                                0
GeneSymbol                            0
HGNC_ID                               0
ClinicalSignificance                  0
ClinSigSimple                         0
LastEvaluated                         0
PhenotypeIDS                          0
PhenotypeList                         0
Origin                                0
OriginSimple                          0
Assembly                              0
ChromosomeAccession                   0
Chromosome                            0
Start                                 0
Stop                                  0
ReferenceAllele                       0
AlternateAllele                       0
ReviewStatus                          0
Guidelines                            0
VariationID                           0
PositionVCF                           0
ReferenceAlleleVCF                    0
AlternateAlleleVCF                    0
SomaticClinicalImpact                 0
SomaticClinicalImpactLastEvaluated    0
ReviewStatusClinicalImpact            0
Oncogenicity                          0
OncogenicityLastEvaluated             0
ReviewStatusOncogenicity              0
dtype: int64

In [7]:
df_variant.isna().sum()

#AlleleID                             0
Type                                  0
Name                                  0
GeneID                                0
GeneSymbol                            0
HGNC_ID                               0
ClinicalSignificance                  0
ClinSigSimple                         0
LastEvaluated                         0
PhenotypeIDS                          0
PhenotypeList                         0
Origin                                0
OriginSimple                          0
Assembly                              0
ChromosomeAccession                   0
Chromosome                            0
Start                                 0
Stop                                  0
ReferenceAllele                       0
AlternateAllele                       0
ReviewStatus                          0
Guidelines                            0
VariationID                           0
PositionVCF                           0
ReferenceAlleleVCF                    0
AlternateAlleleVCF                    0
SomaticClinicalImpact                 0
SomaticClinicalImpactLastEvaluated    0
ReviewStatusClinicalImpact            0
Oncogenicity                          0
OncogenicityLastEvaluated             0
ReviewStatusOncogenicity              0
dtype: int64

In [8]:
df_variant.duplicated().sum()

np.int64(0)

In [18]:
df_official['ReviewStatus'].unique()

array(['no assertion criteria provided',
       'criteria provided, multiple submitters, no conflicts',
       'criteria provided, single submitter',
       'criteria provided, conflicting classifications',
       'reviewed by expert panel',
       'no classification for the single variant',
       'no classifications from unflagged records',
       'no classification provided', 'practice guideline', '-'],
      dtype=object)

In [19]:
df_official['Guidelines'].unique()

array(['-', 'ACMG2021,ACMG2022', 'ACMG2022',
       'ACMG2013,ACMG2016,ACMG2021,ACMG2022',
       'ACMG2016,ACMG2021,ACMG2022', 'ACMG2013'], dtype=object)

In [20]:
df_official['SomaticClinicalImpact'].unique()

array(['-', 'Tier I - Strong', 'Tier II - Potential',
       'no classification for the single variant',
       'Tier IV - Benign/Likely benign', 'Tier III - Unknown'],
      dtype=object)

In [23]:
df_official['Oncogenicity'].unique()

array(['-', 'Likely oncogenic', 'Oncogenic',
       'no classification for the single variant', 'Benign',
       'Uncertain significance', 'Likely benign',
       'Conflicting classifications of oncogenicity'], dtype=object)

In [10]:
df_official['Type'].unique()

array(['Indel', 'Deletion', 'single nucleotide variant', 'Duplication',
       'Microsatellite', 'Insertion', 'Variation', 'Translocation',
       'Inversion', 'copy number gain', 'copy number loss', 'Complex'],
      dtype=object)

In [11]:
df_official = df_variant[df_variant['Type']=='single nucleotide variant']

In [14]:
df_official['Type'].unique()

array(['single nucleotide variant'], dtype=object)

In [13]:
df_official['Assembly'].unique()

array(['GRCh37', 'GRCh38', 'na'], dtype=object)

In [15]:
df_official = df_official[df_official['Assembly']=='GRCh38']

In [16]:
df_official['Assembly'].unique()

array(['GRCh38'], dtype=object)

In [17]:
df_official

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,PhenotypeIDS,...,VariationID,PositionVCF,ReferenceAlleleVCF,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity
5,15043,single nucleotide variant,NM_014630.3(ZNF592):c.3136G>A (p.Gly1046Arg),9640,ZNF592,HGNC:28986,Uncertain significance,0,"Jun 29, 2015","MONDO:MONDO:0033005,MedGen:C4551772,OMIM:25130...",...,4,84799209,G,A,-,-,-,-,-,-
7,15044,single nucleotide variant,NM_017547.4(FOXRED1):c.694C>T (p.Gln232Ter),55572,FOXRED1,HGNC:26927,Pathogenic,1,"Aug 17, 2025","MONDO:MONDO:0032624,MedGen:C4748791,OMIM:61824...",...,5,126275389,C,T,-,-,-,-,-,-
9,15045,single nucleotide variant,NM_017547.4(FOXRED1):c.1289A>G (p.Asn430Ser),55572,FOXRED1,HGNC:26927,Likely pathogenic,1,"Jun 06, 2024","MONDO:MONDO:0032624,MedGen:C4748791,OMIM:618241",...,6,126277517,A,G,-,-,-,-,-,-
11,15046,single nucleotide variant,NM_025152.3(NUBPL):c.166G>A (p.Gly56Arg),80224,NUBPL,HGNC:20278,Conflicting classifications of pathogenicity,1,"Apr 08, 2025","MedGen:C3661900|MeSH:D030342,MedGen:C0950123|M...",...,214885,31562125,G,A,-,-,-,-,-,-
13,15048,single nucleotide variant,NM_000410.4(HFE):c.845G>A (p.Cys282Tyr),3077,HFE,HGNC:4886,"Pathogenic/Pathogenic, low penetrance; risk fa...",1,"Feb 13, 2026","MONDO:MONDO:0021001,MedGen:C3469186,OMIM:23520...",...,9,26092913,G,A,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8992035,4968326,single nucleotide variant,NM_177398.4(LMX1A):c.718C>T (p.Gln240Ter),4009,LMX1A,HGNC:6653,Pathogenic,1,"Jun 30, 2006","MONDO:MONDO:0011074,MedGen:C1832379,OMIM:60141...",...,4857405,165210728,G,A,-,-,-,-,-,-
8992037,4968327,single nucleotide variant,NM_001046.3(SLC12A2):c.2977G>T (p.Glu993Ter),6558,SLC12A2,HGNC:10911,Pathogenic,1,"Jun 30, 2006","MONDO:MONDO:0033665,MedGen:C5436768,OMIM:619081",...,4857406,128177152,G,T,-,-,-,-,-,-
8992039,4968328,single nucleotide variant,NM_001001331.4(ATP2B2):c.529A>T (p.Lys177Ter),491,ATP2B2,HGNC:815,Pathogenic,1,"Jun 30, 2006","MONDO:MONDO:0030719,MedGen:C5676948,OMIM:619804",...,4857407,10402217,T,A,-,-,-,-,-,-
8992041,4968329,single nucleotide variant,NM_001387220.1(IKZF2):c.485A>C (p.His162Pro),22807,IKZF2,HGNC:13177,Uncertain significance,0,"Jun 30, 2006","MONDO:MONDO:0979234,MedGen:C6012290,OMIM:62123...",...,4857408,213049802,T,G,-,-,-,-,-,-
8992045,4968331,single nucleotide variant,NM_001191057.4(PDE1C):c.1194C>G (p.Phe398Leu),5137,PDE1C,HGNC:8776,Likely pathogenic,1,"Jun 30, 2006","MONDO:MONDO:0029137,MedGen:C4748334,OMIM:618140",...,4857410,31837189,G,C,-,-,-,-,-,-

In [24]:
df_official = df_official.drop(columns = ['SomaticClinicalImpactLastEvaluated'	,'OncogenicityLastEvaluated'])

In [25]:
df_official = df_official.drop(columns = ['ReferenceAllele','AlternateAllele','LastEvaluated','Guidelines'])

In [26]:
df_official

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,PhenotypeIDS,PhenotypeList,...,Stop,ReviewStatus,VariationID,PositionVCF,ReferenceAlleleVCF,AlternateAlleleVCF,SomaticClinicalImpact,ReviewStatusClinicalImpact,Oncogenicity,ReviewStatusOncogenicity
5,15043,single nucleotide variant,NM_014630.3(ZNF592):c.3136G>A (p.Gly1046Arg),9640,ZNF592,HGNC:28986,Uncertain significance,0,"MONDO:MONDO:0033005,MedGen:C4551772,OMIM:25130...",Galloway-Mowat syndrome 1,...,84799209,no assertion criteria provided,4,84799209,G,A,-,-,-,-
7,15044,single nucleotide variant,NM_017547.4(FOXRED1):c.694C>T (p.Gln232Ter),55572,FOXRED1,HGNC:26927,Pathogenic,1,"MONDO:MONDO:0032624,MedGen:C4748791,OMIM:61824...","Mitochondrial complex I deficiency, nuclear ty...",...,126275389,"criteria provided, multiple submitters, no con...",5,126275389,C,T,-,-,-,-
9,15045,single nucleotide variant,NM_017547.4(FOXRED1):c.1289A>G (p.Asn430Ser),55572,FOXRED1,HGNC:26927,Likely pathogenic,1,"MONDO:MONDO:0032624,MedGen:C4748791,OMIM:618241","Mitochondrial complex I deficiency, nuclear ty...",...,126277517,"criteria provided, single submitter",6,126277517,A,G,-,-,-,-
11,15046,single nucleotide variant,NM_025152.3(NUBPL):c.166G>A (p.Gly56Arg),80224,NUBPL,HGNC:20278,Conflicting classifications of pathogenicity,1,"MedGen:C3661900|MeSH:D030342,MedGen:C0950123|M...",not provided|Inborn genetic diseases|Mitochond...,...,31562125,"criteria provided, conflicting classifications",214885,31562125,G,A,-,-,-,-
13,15048,single nucleotide variant,NM_000410.4(HFE):c.845G>A (p.Cys282Tyr),3077,HFE,HGNC:4886,"Pathogenic/Pathogenic, low penetrance; risk fa...",1,"MONDO:MONDO:0021001,MedGen:C3469186,OMIM:23520...",Hemochromatosis type 1|not provided|Hereditary...,...,26092913,"criteria provided, multiple submitters, no con...",9,26092913,G,A,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8992035,4968326,single nucleotide variant,NM_177398.4(LMX1A):c.718C>T (p.Gln240Ter),4009,LMX1A,HGNC:6653,Pathogenic,1,"MONDO:MONDO:0011074,MedGen:C1832379,OMIM:60141...",Autosomal dominant nonsyndromic hearing loss 7,...,165210728,"criteria provided, single submitter",4857405,165210728,G,A,-,-,-,-
8992037,4968327,single nucleotide variant,NM_001046.3(SLC12A2):c.2977G>T (p.Glu993Ter),6558,SLC12A2,HGNC:10911,Pathogenic,1,"MONDO:MONDO:0033665,MedGen:C5436768,OMIM:619081","Hearing loss, autosomal dominant 78",...,128177152,"criteria provided, single submitter",4857406,128177152,G,T,-,-,-,-
8992039,4968328,single nucleotide variant,NM_001001331.4(ATP2B2):c.529A>T (p.Lys177Ter),491,ATP2B2,HGNC:815,Pathogenic,1,"MONDO:MONDO:0030719,MedGen:C5676948,OMIM:619804","Hearing loss, autosomal dominant 82",...,10402217,"criteria provided, single submitter",4857407,10402217,T,A,-,-,-,-
8992041,4968329,single nucleotide variant,NM_001387220.1(IKZF2):c.485A>C (p.His162Pro),22807,IKZF2,HGNC:13177,Uncertain significance,0,"MONDO:MONDO:0979234,MedGen:C6012290,OMIM:62123...",ICHAD syndrome,...,213049802,"criteria provided, single submitter",4857408,213049802,T,G,-,-,-,-
8992045,4968331,single nucleotide variant,NM_001191057.4(PDE1C):c.1194C>G (p.Phe398Leu),5137,PDE1C,HGNC:8776,Likely pathogenic,1,"MONDO:MONDO:0029137,MedGen:C4748334,OMIM:618140","Hearing loss, autosomal dominant 74",...,31837189,"criteria provided, single submitter",4857410,31837189,G,C,-,-,-,-

In [27]:
# Danh sách giá trị cần kiểm tra
invalid_values = ["-", "na", "n/a", "NA", "N/A", "NaN", "nan"]

# Thay thế toàn bộ giá trị lỗi trong toàn DataFrame bằng np.nan
df_official = df_official.replace(invalid_values, np.nan)

In [28]:
df_official.isnull().sum()

#AlleleID                           0
Type                                0
Name                                0
GeneID                              0
GeneSymbol                        749
HGNC_ID                          4485
ClinicalSignificance           235824
ClinSigSimple                       0
PhenotypeIDS                    48385
PhenotypeList                     562
Origin                              0
OriginSimple                        0
Assembly                            0
ChromosomeAccession                 0
Chromosome                          0
Start                               0
Stop                                0
ReviewStatus                   235824
VariationID                         0
PositionVCF                         0
ReferenceAlleleVCF                  8
AlternateAlleleVCF                  8
SomaticClinicalImpact         4136144
ReviewStatusClinicalImpact    4136144
Oncogenicity                  4135779
ReviewStatusOncogenicity      4135779
dtype: int64

In [29]:
df_official = df_official.rename(columns={"Chromosome": "CHROM"})
df_official = df_official.rename(columns={"PositionVCF": "POS"})
df_official = df_official.rename(columns={"ReferenceAlleleVCF": "REF"})
df_official = df_official.rename(columns={"AlternateAlleleVCF": "ALT"})
def normalize_chromosome(chrom_name):
    chrom_str = str(chrom_name).strip() # Chuyển sang string và xóa khoảng trắng

# Lọc bỏ các contig không xác định (Unplaced/random/alt)
    if 'Un' in chrom_str or 'random' in chrom_str or 'alt' in chrom_str:
        return None # Sẽ bị xóa ở bước tiếp theo

    # Xử lý các trường hợp đặc biệt (MT -> chrM)
    if chrom_str.upper() == 'MT':
        return 'chrM'

    # Nếu nó đã có 'chr' rồi thì thôi (như chr1, chrX, chrM của bạn)
    if chrom_str.startswith('chr'):
        return chrom_str

    # Nếu nó là số (1, 2, X, Y) thì thêm 'chr'
    return 'chr' + chrom_str

print("Đang chuẩn hóa tên chromosome ...")
df_official['CHROM'] = df_official['CHROM'].apply(normalize_chromosome)

original_count = len(df_official)

Đang chuẩn hóa tên chromosome ...

In [30]:
df_official.isnull().sum()

#AlleleID                           0
Type                                0
Name                                0
GeneID                              0
GeneSymbol                        749
HGNC_ID                          4485
ClinicalSignificance           235824
ClinSigSimple                       0
PhenotypeIDS                    48385
PhenotypeList                     562
Origin                              0
OriginSimple                        0
Assembly                            0
ChromosomeAccession                 0
CHROM                               2
Start                               0
Stop                                0
ReviewStatus                   235824
VariationID                         0
POS                                 0
REF                                 8
ALT                                 8
SomaticClinicalImpact         4136144
ReviewStatusClinicalImpact    4136144
Oncogenicity                  4135779
ReviewStatusOncogenicity      4135779
dtype: int64

In [31]:
df_official = df_official.dropna(subset=['CHROM']) # Xóa các hàng (như chrUn) đã bị gán None
df_official = df_official.dropna(subset=['POS'])
df_official = df_official.dropna(subset=['REF'])
df_official = df_official.dropna(subset=['ALT'])
removed_count = original_count - len(df_official)
print(f"Đã lọc bỏ {removed_count} hàng ('chrUn' hoặc contig rác, thiếu POS, ALT, REF).")

print("Đang sắp xếp df_official (theo chrom và pos)...")
# 1. Đảm bảo 'pos' là kiểu số (integer) để sắp xếp đúng
df_official['POS'] = pd.to_numeric(df_official['POS'])
# 2. Sắp xếp theo 'chrom' trước, sau đó theo 'pos'
df_official = df_official.sort_values(by=["CHROM", "POS"])
df_official

Đã lọc bỏ 10 hàng ('chrUn' hoặc contig rác, thiếu POS, ALT, REF).
Đang sắp xếp df_official (theo chrom và pos)...

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,PhenotypeIDS,PhenotypeList,...,Stop,ReviewStatus,VariationID,POS,REF,ALT,SomaticClinicalImpact,ReviewStatusClinicalImpact,Oncogenicity,ReviewStatusOncogenicity
3866765,2193183,single nucleotide variant,NM_001005484.2(OR4F5):c.107A>G (p.Glu36Gly),79501,OR4F5,HGNC:14825,Likely benign,0,MedGen:CN169374,not specified,...,69134,"criteria provided, single submitter",2205837,69134,A,G,NaN,NaN,NaN,NaN
8420090,4679177,single nucleotide variant,NM_001005484.2(OR4F5):c.214C>T (p.Pro72Ser),79501,OR4F5,HGNC:14825,Uncertain significance,0,MedGen:CN169374,not specified,...,69241,"criteria provided, single submitter",4562067,69241,C,T,NaN,NaN,NaN,NaN
7144036,4039319,single nucleotide variant,NM_001005484.2(OR4F5):c.281A>G (p.Lys94Arg),79501,OR4F5,HGNC:14825,Uncertain significance,0,MedGen:CN169374,not specified,...,69308,"criteria provided, single submitter",3925305,69308,A,G,NaN,NaN,NaN,NaN
5827321,3374047,single nucleotide variant,NM_001005484.2(OR4F5):c.287T>G (p.Ile96Ser),79501,OR4F5,HGNC:14825,Uncertain significance,0,MedGen:CN169374,not specified,...,69314,"criteria provided, single submitter",3205580,69314,T,G,NaN,NaN,NaN,NaN
7144038,4039320,single nucleotide variant,NM_001005484.2(OR4F5):c.377T>C (p.Met126Thr),79501,OR4F5,HGNC:14825,Uncertain significance,0,MedGen:CN169374,not specified,...,69404,"criteria provided, single submitter",3925306,69404,T,C,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1099155,706349,single nucleotide variant,NM_002186.3(IL9R):c.1094G>A (p.Arg365His),3581,IL9R,HGNC:6030,Benign,0,MedGen:C3661900,not provided,...,57196457,"criteria provided, multiple submitters, no con...",771064,57196457,G,A,NaN,NaN,NaN,NaN
8646032,4792913,single nucleotide variant,NC_000023.11:g.156021711C>T,-1,NaN,NaN,Likely benign,0,MedGen:C3661900,not provided,...,57208231,"criteria provided, single submitter",4681502,57208231,C,T,NaN,NaN,NaN,NaN
7459888,4197692,single nucleotide variant,NC_000023.11:g.156022415C>A,-1,NaN,NaN,Likely benign,0,MedGen:C3661900,not provided,...,57208935,"criteria provided, single submitter",4085007,57208935,C,A,NaN,NaN,NaN,NaN
5450908,3184976,single nucleotide variant,NC_000023.11:g.156023032T>C,-1,NaN,NaN,Likely benign,0,MedGen:C3661900,not provided,...,57209552,"criteria provided, single submitter",3024664,57209552,T,C,NaN,NaN,NaN,NaN
5455293,3187171,single nucleotide variant,NC_000023.11:g.156025065C>T,-1,NaN,NaN,Likely benign,0,MedGen:C3661900,not provided,...,57211585,"criteria provided, single submitter",3026862,57211585,C,T,NaN,NaN,NaN,NaN

In [32]:
df_official.isnull().sum()

#AlleleID                           0
Type                                0
Name                                0
GeneID                              0
GeneSymbol                        748
HGNC_ID                          4484
ClinicalSignificance           235824
ClinSigSimple                       0
PhenotypeIDS                    48385
PhenotypeList                     562
Origin                              0
OriginSimple                        0
Assembly                            0
ChromosomeAccession                 0
CHROM                               0
Start                               0
Stop                                0
ReviewStatus                   235824
VariationID                         0
POS                                 0
REF                                 0
ALT                                 0
SomaticClinicalImpact         4136134
ReviewStatusClinicalImpact    4136134
Oncogenicity                  4135769
ReviewStatusOncogenicity      4135769
dtype: int64

In [33]:
df_official.to_csv(r'C:\Users\dotru\STUDIE\FPTU\AiTA_Lab\data\ver3\clinvar_clean.csv', index=False)

In [3]:
df = pd.read_csv(r'C:\Users\dotru\STUDIE\FPTU\AiTA_Lab\data\ver3\clinvar_clean.csv')
df.to_parquet(r'C:\Users\dotru\STUDIE\FPTU\AiTA_Lab\data\ver3\clinvar_clean.parquet', index=False)

C:\Users\dotru\AppData\Local\Temp\ipykernel_16596\2559499556.py:1: DtypeWarning: Columns (22,23,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'C:\Users\dotru\STUDIE\FPTU\AiTA_Lab\data\ver3\clinvar_clean.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4137591 entries, 0 to 4137590
Data columns (total 26 columns):
 #   Column                      Dtype
---  ------                      -----
 0   #AlleleID                   int64
 1   Type                        object
 2   Name                        object
 3   GeneID                      int64
 4   GeneSymbol                  object
 5   HGNC_ID                     object
 6   ClinicalSignificance        object
 7   ClinSigSimple               int64
 8   PhenotypeIDS                object
 9   PhenotypeList               object
 10  Origin                      object
 11  OriginSimple                object
 12  Assembly                    object
 13  ChromosomeAccession         object
 14  CHROM                       object
 15  Start                       int64
 16  Stop                        int64
 17  ReviewStatus                object
 18  VariationID                 int64
 19  POS                         int64
 20  REF                         object
 21  ALT                         object
 22  SomaticClinicalImpact       object
 23  ReviewStatusClinicalImpact  object
 24  Oncogenicity                object
 25  ReviewStatusOncogenicity    object
dtypes: int64(7), object(19)
memory usage: 820.8+ MB